### ISSUE TITLE
PERFORCE: Do not output peforce syncing to console

### ISSUE THREAD

**Issue by v1v** [gocd/gocd#10]
**DESCRIPTION:**
Our perforce projects and materials are huge, so for each job there are thousands of lines about the p4 updating phase, and it makes our Console tabs huge and hard to debug in case of any errors.

**FEATURE:**
As Developer I'd like to redirect that output to another tab

**EXAMPLE:**
_URL:_ http://go.xxxxx.com/go/tab/build/detail/Project-0.0/95/Build/1/Build
_Console tab:_

```
[go] Start to prepare Project-0.0/285858/Build/1/Build on ci-cent5-019.xxxxx.com [/space/go-agent] at Tue Mar 04 12:16:45 GMT 2014
[go] Cleaning working directory "/space/go-agent/pipelines/Project-0.0" since stage is configured to clean working directory
[go] Start updating files at revision 285858 from perforce:1666
Client cruise-ci-cent5-019.xxxx.com-Project-0.0-LvmKLZEYMmUfkjm8kuVj2hA3gjc saved.
//Project/0.0/Lab/JavaAPI/.classpath#2 - deleted as /space/go-agent/pipelines/Project-0.0/Project/0.0/Lab/JavaAPI/.classpath
//Project/0.0/Lab/JavaAPI/.project#2 - deleted as /space/go-agent/pipelines/Project-0.0/Project/0.0/Lab/JavaAPI/.project
//Project/0.0/Lab/JavaAPI/.settings/org.eclipse.jdt.core.prefs#2 - deleted as /space/go-agent/pipelines/Project-0.0/Project/0.0/Lab/JavaAPI/.settings/org.eclipse.jdt.core.prefs
......
(another thousands lines about p4 sync output)
.....
```

**FURTHER DETAILS:**
I've already tried the suggested approach:
http://support.thoughtworks.com/entries/21577271-Is-it-possible-to-read-the-P4CLIENT-setting-that-an-agent-is-using-

But even using a p4 (p4.sh p4.cmd) wrapper, still got issues...

**Comment by arvindsv** [comment]
Closing as stale.
