### ISSUE TITLE
The pipeline search on dashboard on browser back is not consistent
across Chrome and Firefox.

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#100]
### Steps to reproduce
1.  Create few pipelines and search for the same from the dashboard.
2.  On Chrome and Firefox ---> Navigate to one of the pipelines from
   the dashboard.
3.  Perform browser back.
#### Expected result

The behaviour should be consistent across browsers.
#### Current result

The search happens instantly on firefox but on chrome it waits for the next auto refresh.

**Comment by arvindsv** [comment]
Closing. Related to #3739.
