### ISSUE TITLE
Allow short git sha in pipeline label

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#101]
## Description
Currently in Go you can name a material, for instance 'git', and reference it in the label template. This however yields to the full, long git revision being used, which is not very nice in the UI.

Go should allow short git revision number to be mentioned as the pipeline label

**Comment by idapi** [comment]
I just discovered the option of including the revision number this way, in our case for our Mercurial material; it will be useful. However, as you say, having a 40+ chars label is not ideal. Would be nice to simply be able to apply some logic in the label template; such as a nice Python slicing - rev[:12] :-)

**Comment by alexschwartz** [comment]
+1 vote for this request.

(I actually filed a ticket for this topic years ago  before GO was open source.)

**Comment by arvindsv** [comment]
Though I agree it would be nice, there's no one who has stepped up and even attempted to take a stab at this. It's now an open-source project, and this would definitely be nice to have. Might be worth bringing it up on the dev mailing list and drumming up some support for it. Maybe someone there is free, and looking for something small to do.

**Comment by alexschwartz** [comment]
I am contributing to implement it; would be my first contribution though.
(Plan: I familiarise myself with the details of the contrib guide, implement it, and generate the merge request.)

Is there a need to discuss the syntax (and/or implementation) on the dev mailing list?
I like the Python slicing syntax.

**Comment by arvindsv** [comment]
> I am contributing to implement it; would be my first contribution though.

That would be wonderful!

> (Plan: I familiarise myself with the details of the contrib guide, implement it, and generate the merge request.)

Sounds good. Ask, if you need any help setting up you environment or anything else. I might not be around much this weekend, but I should be able to respond sometime later. Others can help tool

> Is there a need to discuss the syntax (and/or implementation) on the dev mailing list?

Yes, please do that. If others have no ideas, or no one has any major concerns, then it's your call. You can push for your preferred format, of course. :)

Think about whether it can be made extensible (not necessarily a plugin, in this case, just easily extensible).

**Comment by alexschwartz** [comment]
thanks, I will do so.

**Comment by paulclarkin** [comment]
Note, the Git short hash isn't just the long hash sliced, it attempts to be unique.

See https://www.kernel.org/pub/software/scm/git/docs/git-rev-parse.html under --short.

The length of the short hash can vary as git tries to find a unique hash that's as short as possible.

> Instead of outputting the full SHA1 values of object names try to abbreviate them to a shorter unique name. When no length is specified 7 is used. The minimum length is 4.

**Comment by grahamc** [comment]
@ashwanthkumar asked me to throw in my $0.02

Using his plugin https://github.com/ashwanthkumar/gocd-build-github-pull-requests, it would be very nice to be able to access the PR number being built as well.

**Comment by ashwanthkumar** [comment]
+1 for the feature. It would be really nice if feature can be made available to SCM plugins as well.

**Comment by alexschwartz** [comment]
the gocd-build-github-pull-requests support sounds like a cool feature.

nevertheless I suggest to split this off.

**Comment by alexschwartz** [comment]
Paul, 

thanks a lot for pointing to the details of the git short hash.
This means the git short hash could be shorter than 7 characters, but not longer.

From my point of view for the pipeline labels it would be sufficient to have a 7 chars long version:
* it is short enough (ok, could be even shorter, but 7 chars is much better for labels than the full length)
* it is unique (with a very high probability)

--Alex

**Comment by arvindsv** [comment]
@alexschwartz, from what I understand, you're looking to introduce a generic way of shortening the label (slice/dice). So, the size (6 or 7 or more), can be decided by the user. As @paulclarkin says, it might be prudent to use 7. That makes sense.

**Comment by ketan** [comment]
Tested and verified works on `15.1.0(1823-9db0d814df07de)`. The syntax used was - 

```
    <pipeline name="myPipeline" labeltemplate="${COUNT}-${git[:8]}" isLocked="false">
      <materials>
        <git url="https://github.com/user/repository" materialName="git" />
      </materials>
```
