### ISSUE TITLE
Make templates have materials too (not just pipelines).

### ISSUE THREAD

**Issue by JonasGroeger** [gocd/gocd#1011]
Hello!

GOCD currently differentiates between Templates (with generic functionality) and Pipelines (instantiated Templates) with customized settings.

Currently, only Pipelines offer the functionality to attach materials to them (like git repositories). **It would be great to have Templates that have materials.**

This is useful when multiple Pipelines have similar materials.

I am willing to implement that feature. I just want to know if this is somehting the GOCD developers want and that will be accepted.

Greetings
JonasGroeger

**Comment by arvindsv** [comment]
@JonasGroeger, can you move this to the mailing list instead?

I can see what you're saying, but it makes me feel a little queasy. :) I suppose I think that the templates are complicated enough as they are (with parameters, etc). But, I'd like to see if it makes sense to others as well.

**Comment by JonasGroeger** [comment]
For reference, here the [thread in the mailing list.](https://groups.google.com/forum/#!topic/go-cd/l1EwAGSGLNc)

**Comment by JonasGroeger** [comment]
@arvindsv I posted it to the normal mailinglist. Should it go to the dev mailing list?

**Comment by arvindsv** [comment]
I was about to say (to your earlier comment about go-cd-dev mailing list), that it was not needed. :) But, I see you posted it already. :) I'll ask some people to think about this. Thanks!

**Comment by JonasGroeger** [comment]
@arvindsv Any update on this one?

**Comment by arvindsv** [comment]
Oh no. I'd said [in this other thread](https://groups.google.com/d/topic/go-cd/SKCs-IKmSfY/discussion) that I'd help. Damn. Sorry. :( I'm crafting a response to this now, with steps to achieve this. Give me a few minutes, please.

**Comment by arvindsv** [comment]
Here's what I would do:

1. Make this change first in the back-end (config) and then get to the front-end. For the config change, you can read [this](http://www.go.cd/documentation/developer/2/2.3.html). This talks about adding a XSL migration to the current config, to make the config allow materials inside templates. That would be the first step.

2. Once you have that, you'd need to figure out how to get the materials from the template into the pipeline config. Merging the pipeline config with its template. You'll probably have to start from [here](https://github.com/gocd/gocd/blob/master/config/config-api/src/com/thoughtworks/go/config/TemplateExpansionPreprocessor.java).

3. During step 2, you'd need to consider how you'll handle potentially duplicate materials between the template and the pipeline. Maybe you can use the same mechanism used to make sure that a pipeline doesn't have the same material twice.

Once you have all of this, you should be very close to your goal. You can start looking at the UI. We can talk about that later. Feel free to ask for help getting started. Sorry I missed replying to the earlier thread.

**Comment by JonasGroeger** [comment]
Thank you for your reply! I will look into that starting on Monday next week.

**Comment by mikeparker** [comment]
I think we would like this functionality - as we have shared scripts that we pull down from a github repo for all pipelines that use a template. Unless I'm missing a better way of doing this?

**Comment by arvindsv** [comment]
@mikeparker: There's some conversation around [here](https://github.com/tomzo/gocd-yaml-config-plugin/issues/2) which might be interesting. I suspect that templating changes will happen there, rather than in core.
