### ISSUE TITLE
Unable to change configuration after making one of the pipelines use a template

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1012]
https://groups.google.com/d/msg/go-cd/fgLSGOavVFo/fZT_3zIZlUoJ

**Comment by zabil** [comment]
Finding it tough to replicate this.

**Comment by ketan** [comment]
Steps to reproduce from the original [mail thread](https://groups.google.com/forum/#!msg/go-cd/fgLSGOavVFo/iTM71QRQqSYJ) - 

1.  Create a template that has no environment variables defined.  
2.  Create two pipelines off of that template. 
3.  Add a parameter to ONE of the pipelines using that template.  
4.  Update the template and create an environment variable, and assign the parameter from the pipelines to that environment variable on the template.  When you try to save the template, it will start throwing the error.  

At this point, try going to the pipeline that doesn't have the parameter defined and try creating it.  Go back to the template and try to create the environment variable again, it should still throw the error and every time you press save, it will append the variable names and the error will get longer and longer.

**Comment by zabil** [comment]
this can be replicated on experimental release15.2.0-2153 (c935e43e651a2a3591792f167ac87023c5491b2e)

**Comment by chopraapooja** [comment]
verified on Go v15.2.0-2177
