### ISSUE TITLE
Issues with gocd mac os x installer with 1.6 version of the JDK

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1014]
To replicate

* Download the go.cd mac os x installers (from https://build.go.cd/go/tab/pipeline/history/distributions-all)
* Launch the "Go Server" on a mac with version 1.6 of the JDK

The server app tries to launch and stops without an error message or indication to the user. 

**Notes**
Go server: 15.1 (Which runs on only JDK 7)
The mac launcher does not report errors when it spawns off a go server.

Also refer #308 #796

**Comment by ketan** [comment]
Verified on `15.1.0(1839-0f15ee122cda40)` running on `Mac OS X 10.10.3` on both JDK 7 and JDK 8.
