### ISSUE TITLE
Task is never cancelled and keep the agent busy while console logs (and UI) state the opposite.

### ISSUE THREAD

**Issue by papazaf** [gocd/gocd#1019]
Please check this agent console log bellow:

```
12:31:33.767 [QbTrigger] GO_PIPELINE_COUNTER : 79
12:31:33.767 [QbTrigger] GO_JOB_NAME : TalkToQB
12:31:33.767 [QbCheck] Checking if configuration is valid: 207186
12:31:34.376 [QbCheck] Checking build with version: master.0.0.0.6192 in Configuration with id: 207186. Getting latest 11 builds. Time left: 7200000ms
12:31:34.376 [QbCheck] [searchBuild] Will GET : https://!!!/rest/builds?configuration_id=207186&count=11
12:33:35.647 [QbCheck] Checking build with version: master.0.0.0.6192 in Configuration with id: 207186. Getting latest 11 builds. Time left: 7078729ms
12:33:35.647 [QbCheck] [searchBuild] Will GET : https://!!!/rest/builds?configuration_id=207186&count=11
12:34:35.991 [go] Start to execute cancel task: Kills child processes
12:34:36.054 [go] Task is cancelled
12:35:36.856 [QbCheck] Checking build with version: master.0.0.0.6192 in Configuration with id: 207186. Getting latest 11 builds. Time left: 6957520ms
12:35:36.856 [QbCheck] [searchBuild] Will GET : https://!!!/rest/builds?configuration_id=207186&count=11
12:37:38.174 [QbCheck] Checking build with version: master.0.0.0.6192 in Configuration with id: 207186. Getting latest 11 builds. Time left: 6836202ms
12:37:38.174 [QbCheck] [searchBuild] Will GET : https://!!!/rest/builds?configuration_id=207186&count=11
```

The QbCheck plugin does:
```javascript
while(true){
    doGet();
    if(time_elapsed)
      break;
}
```

Although "[go] Task is cancelled" is reported and the UI prevents me from cancelling it again, the agent is occupied and cannot be used anymore.

**Comment by mehtadev17** [comment]
I am having the same issue. Is there any fix available?

**Comment by matfed** [comment]
+1
Any update on that?

**Comment by arvindsv** [comment]
A task which does not block SIGTERM should be killed. If it blocks SIGTERM, then it is preventing itself from being killed. Maybe that is what is happening. Some discussion [here](https://github.com/gocd/gocd/issues/756#issuecomment-109287238).

**Comment by zabil** [comment]
@matfed @mehtadev17 @matfed 
Are your agents running on Java 8?

**Comment by matfed** [comment]
yes, they're using Java 8

**Comment by zabil** [comment]
Aha, unfortunately issue specific to java 8 on linux machines
JDK 8 changed the signature of a native method we relied on for killing child processes spawned by go agents.

We are trying to this and other JDK8 issues at #1086

**Comment by matfed** [comment]
@zabil That's it! Thanks a lot.

I the meantime, is there any recommended way of setting different Java version for agent and for tasks it spawns? Perhaps I can rename JAVA_HOME property to AGENT_JAVA_HOME and set it to Java 7, while keeping JAVA_HOME pointing to Java 8?

**Comment by jyotisingh** [comment]
> is there any recommended way of setting different Java version for agent and for tasks it spawns

Until #1086 is fully done, you could set JAVA_HOME for agents to java7 home path. 
On Linux, use `/etc/default/go-agent` file to set JAVA_HOME. On windows, set system level environment-variable `GO_AGENT_JAVA_HOME`.
You should be able to override JAVA_HOME at environment/pipeline level to point to java8 and then all tasks would run with java8.

**Comment by zabil** [comment]
#1909 has been merged for this issue

**Comment by rajiesh** [comment]
verified on 16.2.0-3024(0946fc7a9a54555f437fda398fafde0fbc7985bd), the child processes are killed on cancel and agent comes back to idle state
