### ISSUE TITLE
Skipping or disabling a Task or a Stage

### ISSUE THREAD

**Issue by yshdev** [gocd/gocd#10253]
##### Issue Type

- Feature proposal
##### Summary
Sometimes, when I want to test a pipeline and I have one of the tasks failing, I have to modify the task itself 
to not fail or delete it (and then I will have to restore it again).
My proposal is to add an option for skipping the task or the failing task/stage so that the pipeline can continue as the task/stage has succeeded.

**Comment by chadlwilson** [comment]
You can change the "run if condition" on subsequent tasks within a job to have "Any" rather the default of "Passed", but that only works within a job, and is a little clunky.

Personally I would suggest however that you consider using a [Pipelines as Code](https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html) approach using one of the plugins (YAML, JSON, Groovy) so you are just commenting out a task or stage you don't want in some config and pushing. Then you can revert the commit and push again to get back exactly how you were.
