### ISSUE TITLE
[SCM endpoint] Improve the response of the endpoint

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1029]
The following gives no visible response to know if things were successful.

```
$ curl 'http://localhost:8153/go/api/material/notify/scm?scm_name=MySCM' -XPOST
```

I'd have expected the response body to contain some form of a JSON response, or even a text response saying "OK" or some sort of a confirmation.

**Comment by srinivasupadhya** [comment]
the issue is generic to all post commit hook implementers - [code](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/controllers/api/materials_controller.rb#L22)

**Comment by arvindsv** [comment]
This needs some work (async material update needs to finish and call back), but would be very useful to have. Others have asked too.

**Comment by ketan** [comment]
Picking this up, can someone assign this to me, please?

**Comment by arvindsv** [comment]
Weirdly enough, it looks like you cannot assign the creator of an issue.

**Comment by ketan** [comment]
Verified, works as expected `15.2.0(2067-07d65665c731a6)`
