### ISSUE TITLE
Agent -side plugin doesn't get deleted after the same plugin was
deleted on server side

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#103]
### Steps to reproduce
1.  plugin called test.jar on server side which is present on the agent side as well
2.  Delete this plugin from server side . Restart the server
3.  Now restart the agent and check the plugins folder on agent side

#### Expected Result
The deleted plugin should not be present on agent side

#### Current Result
The deleted plugin is still present

**Comment by arikagoyal** [comment]
Works fine on 15.1.0(1434-8bfacdfeec4b10)
