### ISSUE TITLE
user apis

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#1030]
there is user listing api - `https://<go-server>/go/api/users.xml`

need to add apis for setting up notifications:
* add email-id to user
* register user for notifications

with [notification end-point](https://github.com/gocd/gocd/issues/867) the need for this could become less important

**Comment by dsenecalb** [comment]
+1

Also, add user and grant a default user notification scheme

**Comment by rajiesh** [comment]
verified this feature on go-server 15.3.0-2672(47fd7343016e4a9cda3f8a871539007c2d1cf1b9). Ability to add email and notification validated and working as expected. This story can be closed
