### ISSUE TITLE
Restoring 21.1.0 backup on 22.1.0 fails horribly

### ISSUE THREAD

**Issue by dbuteyn** [gocd/gocd#10343]
##### Issue Type

- Bug Report

##### Summary

Upgrade from 21.1.0 to 22.1.0 failed horribly.

###### Basic environment details

* Go Version: 22.1.0
* JAVA Version: openjdk 11.0.14
* OS: Debian 11

##### Steps to Reproduce

1. Create backup of 21.1.0.
2. Install 22.1.0 deb package on brand new VM.
3. Follow instructions: https://docs.gocd.org/current/advanced_usage/one_click_backup.html
4. Go server fail to start with a million errors.

##### Expected Results
Working Go server installation.

##### Actual Results
Broken Go server installation.

##### Possible Fix
Difficult to say, too many errors. Delete and recreate config file I suppose? Which kinda defeats the purpose of backing up and restoring from said backup...

##### Log snippets (just some, there are hundreds of lines)
```
[WrapperJarAppMain] BasicLazyInitializer:165 - Javassist Enhancement failed: com.thoughtworks.go.domain.NotificationFilter
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7a98172

[WrapperJarAppMain] PojoEntityTuplizer:197 - could not create proxy factory for:com.thoughtworks.go.domain.NotificationFilter
org.hibernate.HibernateException: Javassist Enhancement failed: com.thoughtworks.go.domain.NotificationFilter

[WrapperJarAppMain] BasicLazyInitializer:165 - Javassist Enhancement failed: com.thoughtworks.go.server.domain.ServerBackup
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @7a98172

[WrapperJarAppMain] PojoEntityTuplizer:197 - could not create proxy factory for:com.thoughtworks.go.server.domain.ServerBackup
org.hibernate.HibernateException: Javassist Enhancement failed: com.thoughtworks.go.server.domain.ServerBackup

2022-04-14 04:51:22,943 INFO  [WrapperJarAppMain] GoConfigMigration:93 - Upgrading config file from version 139 to version 139
2022-04-14 04:51:23,007 INFO  [WrapperJarAppMain] GoConfigMigration:101 - Finished upgrading config file
2022-04-14 04:51:23,012 INFO  [WrapperJarAppMain] GoConfigMigrator:106 - [Config Save] Starting Config Save post upgrade using FullConfigSaveNormalFlow
2022-04-14 04:51:23,106 INFO  [Thread-78] DefaultPluginJarChangeListener:67 - Plugin load starting: /var/lib/go-server/plugins/bundled/gocd-ldap-authentication-plugin.jar
2022-04-14 04:51:23,253 WARN  [WrapperJarAppMain] GoConfigMigrator:98 - Error upgrading config file, trying to upgrade using the versioned config file.
2022-04-14 04:51:23,262 INFO  [WrapperJarAppMain] GoConfigMigration:79 - Config file is backed up, location: /etc/go/cruise-config.xml.invalid.2022-04-14-04-51-23
2022-04-14 04:51:23,287 WARN  [WrapperJarAppMain] GoConfigMigrator:137 - Go encountered an invalid configuration file while starting up. The invalid configuration file has been renamed to ‘/etc/go/cruise-config.xml.invalid.2022-04-14-04-51-23’ and a new configuration file has been automatically created using the last good configuration. Cause: 'Unable to make field private static final long java.util.ArrayList.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @7a98172'
2022-04-14 04:51:23,292 INFO  [WrapperJarAppMain] GoConfigMigration:93 - Upgrading config file from version 139 to version 139
2022-04-14 04:51:23,337 INFO  [WrapperJarAppMain] GoConfigMigration:101 - Finished upgrading config file
2022-04-14 04:51:23,338 INFO  [WrapperJarAppMain] GoConfigMigrator:106 - [Config Save] Starting Config Save post upgrade using FullConfigSaveNormalFlow
2022-04-14 04:51:23,400 WARN  [WrapperJarAppMain] GoConfigMigrator:126 - The versioned config file could be invalid or migrating the versioned config resulted in an invalid configuration
2022-04-14 04:51:23,402 ERROR [WrapperJarAppMain] GoConfigMigrator:64 - There are errors in the Cruise config file.  Please read the error message and correct the errors.
Once fixed, please restart GoCD.

(30 more like below)
[83@MessageListener for MaterialUpdateStatusNotifier] JMSMessageListenerAdapter:95 - Error receiving message. Message receiving will continue despite this error. Backing off for a few seconds. This error is unexpected and should be reported to https://github.com/gocd/gocd/issues
```

##### Additional notes

The initial problem I encountered was this:
```
STATUS | wrapper  | 2022/04/14 04:34:04 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2022/04/14 04:34:04 | Java Service Wrapper Standard Edition 64-bit 3.5.49
STATUS | wrapper  | 2022/04/14 04:34:04 |   Copyright (C) 1999-2022 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2022/04/14 04:34:04 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2022/04/14 04:34:04 | 
ERROR  | wrapper  | 2022/04/14 04:34:04 | License Error:
ERROR  | wrapper  | 2022/04/14 04:34:04 | The License Key does not authorize the use of this version of the Wrapper.
ERROR  | wrapper  | 2022/04/14 04:34:04 | Upgrade term is 2008-06-03 to 2021-06-03.  This version's release date is 2022-02-09.
ERROR  | wrapper  | 2022/04/14 04:34:04 | 
ERROR  | wrapper  | 2022/04/14 04:34:04 | The Java Service Wrapper requires a License Key to activate the
ERROR  | wrapper  | 2022/04/14 04:34:04 | software.  Licenses can be purchased on the Java Service Wrapper
ERROR  | wrapper  | 2022/04/14 04:34:04 | web site:
ERROR  | wrapper  | 2022/04/14 04:34:04 |   https://wrapper.tanukisoftware.com/purchase
ERROR  | wrapper  | 2022/04/14 04:34:04 | 
ERROR  | wrapper  | 2022/04/14 04:34:04 | You can also immediately obtain a one-month Free trial license:
ERROR  | wrapper  | 2022/04/14 04:34:04 |   http://wrapper.tanukisoftware.com/trial
ERROR  | wrapper  | 2022/04/14 04:34:04 | 
ERROR  | wrapper  | 2022/04/14 04:34:04 | License Keys can be generated for the following HostId:
ERROR  | wrapper  | 2022/04/14 04:34:04 |   HostId #1 (ens192):     000c29c1f2d5
ERROR  | wrapper  | 2022/04/14 04:34:04 | 
ERROR  | wrapper  | 2022/04/14 04:34:04 | You may include license keys for several servers within a single file by
ERROR  | wrapper  | 2022/04/14 04:34:04 |   prefixing the property names of each key with their respective
ERROR  | wrapper  | 2022/04/14 04:34:04 |   server host name or HostId. Please use the following syntax:
ERROR  | wrapper  | 2022/04/14 04:34:04 |   wrapper.<hostname|hostid>.license.*.
ERROR  | wrapper  | 2022/04/14 04:34:04 |   The host name of this machine is: gocd-server
ERROR  | wrapper  | 2022/04/14 04:34:04 | 
STATUS | wrapper  | 2022/04/14 04:34:04 | <-- Wrapper Stopped
```
This error was caused by following this instruction:

> Wrapper Configuration - Unzip the wrapper-config-dir.zip into a temp directory. Copy all the files from this directory to ${SERVER_INSTALLATION_DIR}/wrapper-config directory.

Kindly remove this instruction from the docs to prevent people from destroying perfectly functioning installations. I was able to resolve this license problem by reverting wrapper.conf back to its original state.

Would be nice if this time bomb was mentioned on the official site.

**Comment by chadlwilson** [comment]
Sorry, I'm not really following what the sequence of events was, what you were trying to achieve or what the problem is you are describing.

it sounds like you afterwards you have a working 22.1.0 installation with all your data and no loss of data/config, so doesn't seem like the upgrade "failed horribly"? Is the summation of the problem here the documentation issue you reference, or are there multiple problems you are describing?

If there are multiple errors other than the wrapper license issue above, can you please share what you were trying to achieve by restoring a backup from an earlier version on a new version? Is there some other problem that led you to try and restore from a backup?

Normally for an upgrade, you would take a backup but then upgrade in-place per [this](https://docs.gocd.org/current/installation/upgrading_go.html), not restore an older backup on a fresh installation.

**Comment by dbuteyn** [comment]
> Sorry, I'm not really following what the sequence of events was, what you were trying to achieve or what the problem is you are describing.

I took the following steps:
1. Installed 22.1.0 on a new VM (everything working fine).
2. Created backup of existing VM with 21.1.0 (also working fine).
3. Restored backup of 21.1.0 VM, on 22.1.0 VM per instructions (all hell broke loose).

> it sounds like you now have a working 22.1.0 installation with all your data and no loss of data/config, so doesn't seem like the upgrade "failed horribly"?

Recovery steps involved rolling back wrapper config to package-supplied version, deleting database and deleting config file. This was followed by re-configuring 30+ pipelines by hand.

> Is the summation of the problem here the documentation issue you reference after doing a backup restore, or are there multiple problems you are describing?

Go server process would not launch after backup was restored. By following the restoration steps per documentation I replaced a perfectly fine wrapper config and valid license with a wrapper config containing a license locked to 21.1.0. This issue was resolved by reverting the wrapper config back to its original state.

> If there are multiple errors other than the wrapper license issue above, can you please share what you were trying to achieve by restoring a backup from an earlier version on a new version? Is there some other problem that led you to try and restore from a backup?

This build server was cobbled together by hand (a sin, I know). I wanted to replace it with a new one that was completely installed from package so that in the event of catastrophic failure I could simply spin up a generic Debian instance and `apt install` the whole shebang and have it ready to go in minutes.

The installation process itself went without any issues. Restoring the existing configuration however...

> Normally for an upgrade, you would take a backup but then upgrade in-place per [this](https://docs.gocd.org/current/installation/upgrading_go.html), not restore an older backup on a fresh installation.

So in event of disaster when the original server is no longer available, how does one restore a backup on a new installation? Install an older version, restore and then upgrade? Sounds a bit backwards...

**Comment by chadlwilson** [comment]
So the config xml error in the logs was after correcting the wrapper config?

The errors in your logs imply the server started on Java 16/17 as it's not possible to get those errors in Java 11 as you mentioned earlier - but the full log will say the specific version. It also applies there was some overriden server config still in place which caused the OOTB JVM configuration to not be applied.

Did you review the release notes and instructions at https://www.gocd.org/releases#22-1-0 regarding issues starting on Java 16/17 and make any changes related to that?

It's possible there's something in your old config which you were overriding in the server start-up params that was overriding/conflicting with the required settings. It would have been possible to correct this.

Unfortunately theres still insufficient information here to understand why you took the actions you did or what needs to be resolved other than reviewing the restore instructions.

Can you please share the full startup log (partially redacted if necessary) and the wrapper-properties.conf that was in place at this time to have a guess at what happened. Based on the errors I can only guess that your old properties were overriding something they shouldn't in a way that was highly coupled to older versions of GoCD.

In a 'disaster recovery' situation you wouldn't be trying to upgrade a server at the same time as restoring service. Or you shouldn't, that's not good practice. You should be restoring the server to a 'known good' configuration first (which would be 21.1.0 with your config, db, artifacts etc) and then considering an upgrade later. Nevertheless, generally it should be possible to get the server to auto-upgrade with old config as you did, but need to understand more detail of your old config to understand what went wrong in your specific case.

**Comment by dbuteyn** [comment]
> So the config xml error in the logs was after correcting the wrapper config license problem?
Correct.
> The errors in your logs imply the server started on Java 16/17 as it's not possible to get those errors in Java 11 as you mentioned earlier - but the full log will say the specific version. It also applies there was some overriden server config still in place which caused the OOTB JVM configuration to not be applied.

I was unable to get the JVM version from `http://<go-server-host>/go/about` as the process failed to start. Currently it says JVM 17.0.2. I installed openjdk 11.0.14 hoping it would make a difference but it did not.

> Did you review the release notes and instructions at https://www.gocd.org/releases#22-1-0 regarding issues starting on Java 16/17 and make any changes related to that?

We are using zero plugins, if that's what you are after.

> Unfortunately theres still insufficient information here to understand why you took the actions you did or what needs to be resolved other than reviewing the restore instructions.

I wanted to reinstall and preserve existing configuration. Not because I had to, simply because I wanted to.

> Can you please share the full startup log (partially redacted if necessary) and the wrapper-properties.conf that was in place at this time to have a guess at what happened. Based on the errors I can only guess that your old properties were overriding something they shouldn't in a way that was highly coupled to older versions of GoCD.

I can. Service was started at 4:11:26 after installation. Service stopped at 4:23:11 for restore. Service started after restore at 4:31:55. Made several attempts to try and fix things until I gave up at 5:22:53 and deleted `/etc/go/cruise-config.xml` + `/var/lib/go-server/db/h2db/cruise.mv.db`.

[go-server.log](https://github.com/gocd/gocd/files/8501763/go-server.log)
[go-server-wrapper.log](https://github.com/gocd/gocd/files/8501764/go-server-wrapper.log)
[wrapper-properties.conf.txt](https://github.com/gocd/gocd/files/8501773/wrapper-properties.conf.txt)

**Comment by chadlwilson** [comment]
Finally got around to checking this.

So the root cause of your issue was the same issue, using the old `wrapper.conf` with a new GoCD version in this case didn't work correctly. I have [updated the docs](https://docs.gocd.org/current/advanced_usage/one_click_backup.html) accordingly. Apart from there being an updated wrapper license between the versions, there were additional args needed for [correctness on Java 17](https://www.gocd.org/releases/#22-1-0).

![image](https://user-images.githubusercontent.com/29788154/169641155-52cc04a5-7e7f-4c57-acdd-3e345933d10b.png)

Your errors when you got GoCD to start initially imply you didn't have these arguments in the `wrapper.conf`. I am inferring from the logs at some point in the process, you corrected/synced the license information, but perhaps not the other differences in args?

I don't see any other custom overrides to the wrapper config, so you would have been able to get a working installation by using the packaged `wrapper.conf` and retrying alongside your backed up config/database/configuration history.

**Comment by dbuteyn** [comment]
Eventually I replaced wrapper.conf what was provided by the 22.1.0 package as GoCD 22.1.0 was working properly with the original file. I guess the extra arguments required for JVM 17 really messed things up.

Thank you for your time.
