### ISSUE TITLE
GoCD outgoing webhook to Zulip not working

### ISSUE THREAD

**Issue by yuroitaki** [gocd/gocd#10379]
##### Issue Type

- Bug Report

##### Summary

[Zulip](https://zulip.com/) is a team chat application that supports various integrations, including outgoing webhook of GoCD detailed [here](https://zulip.com/integrations/doc/gocd). When there is an event in GoCD (like build finishes), we want to receive notification in Zulip. According to the [guide](https://zulip.com/integrations/doc/gocd), one just need to add a code snippet to Config.XML in GoCD for GoCD to send the event data to the configured webhook URL.

However, as discussed [here](https://github.com/zulip/zulip/issues/21224), the outgoing webhook from GoCD doesn't seem to be working. It seems like the configuration of webhook URL in Config.XML merely just made GoCD replace digits in the commit message with the configured URL, but not actually sending any data to the configured URL.

Can I check if this is an expected behavior?

###### Basic environment details

* Go Version: 22.1.0
* JAVA Version: 17.0.2
* OS: Linux 5.10.47-linuxkit

**Comment by chadlwilson** [comment]
I'm not familiar with Zulip, however the instructions there don't make a huge amount of sense to me with my knowledge of GoCD. The tracking tool is just a easy way to link text from commits to tracking systems AFAIK, and as [the docs](https://docs.gocd.org/current/integration/) that Zulip links to says - it's not an outgoing webhook call. Unless something changed over the years.....

Based on https://github.com/zulip/zulip/issues/38 and https://github.com/zulip/zulip/commit/e1eabe286ad2888cd2f5904c8f592874ba991d00 I'm not quite sure how this could have worked, but it doesn't seem something the GoCD team were involved with?

I believe to do this kind of thing a GoCD plugin would need to be built against the [Notifications Plugin API](https://plugin-api.gocd.org/current/notifications/#stage-start-notifications) as also suggested back [here](https://groups.google.com/g/go-cd/c/9nplH_uusLc).

As you have already done, would suggest you follow up with the Zulip folks.

**Comment by yuroitaki** [comment]
@chadlwilson Thanks for your detailed explanation, will follow up with the Zulip folks then :)

**Comment by chadlwilson** [comment]
Hi @yuroitaki - as this doesnt seem to be a GoCD issue at this stage, I'm going to close this for now. Can follow up discussion on the Zulip issue or elsewhere if I can be of any assistance, or we can re-open this if I have misunderstood the background.
