### ISSUE TITLE
Cannot do initial LDAP login as administrator

### ISSUE THREAD

**Issue by liuwenzhi0318** [gocd/gocd#10378]
After authorizing ldap, click on the authorization management to log in, but the management password of the login page is how much, and the official document has not been found.

> Please ask the administrator to add you to GoCD. See [Help Topic: Authentication](https://docs.gocd.org/22.1.0/configuration/dev_authentication.html#common-errors).

**Comment by liuwenzhi0318** [comment]
![image](https://user-images.githubusercontent.com/37536326/165282365-204f009f-63a4-4237-a96c-d4e5a6aad60d.png)

**Comment by chadlwilson** [comment]
Hi - sorry, it's not clear what problem you are reporting or what steps you took to get there.

Can you please follow the GitHub issue template and write down at least the below?
- summary of problem
- steps to reproduce
- expected results
- actual results

**Comment by liuwenzhi0318** [comment]
![image](https://user-images.githubusercontent.com/37536326/165419715-be1d9c5d-201b-4613-bf06-0c1637c7de23.png)

Hi. As shown in the figure above, after configuring LDAP and checking it “Specify allow only known users to login field”, if the ldap account cannot be logged in, it requires the authorization of the administrator account to enter, so I don't know what the password of the administrator account is.

**Comment by liuwenzhi0318** [comment]
Append: Suspected administrator account needs to be created by yourself or there is an administrator account by default

**Comment by liuwenzhi0318** [comment]
Hi 
Maybe this is not a few technical problems, the use of external LDAP is successful, but the login interface needs to use the management account to go in to authorize the LDAP account, my problem is that the administrator account password does not know how much

**Comment by chadlwilson** [comment]
If I recall correctly, if *no* user accounts have been designated as a GoCD admin *all* users that are able to log in via an allowed Authorization configuration will be considered administrators. This is to allow you to go to https://build.gocd.org/go/admin/users and then designate at least one user as a admin.

The message below implies "Allow only known users to log in" has been enabled/checked. For your initial setup you probably want to disable this until you have specified which LDAP users should be GoCD admins.
![image](https://user-images.githubusercontent.com/29788154/165421550-ccb220fd-48b1-451d-8542-2941997a12ce.png)

So, you want to
* set up the authorization configuration with "Allow only known users to log in" **unchecked/disabled** initially (as in your screenshot above) so any LDAP user can log in (see [here](https://docs.gocd.org/22.1.0/configuration/dev_authentication.html#controlling-user-access))
* login via LDAP as yourself. If there are no specified GoCD admins, all users are admins, and you should have admin permissions
* go to User Management and import any user from LDAP and then enable that user (probably yourself) as a GoCD **System Admin**.
* re-enable "only allow known users to log in" if this is what you want
* login via LDAP as yourself (now the only admin).
* import other LDAP users via User Management and specify them as admins if appropriate.

**Comment by liuwenzhi0318** [comment]
Thank you for your answer; at present, "only allow known users to login field" is selected, and the above error message will be displayed even when LDAP login.

Because this is my first experience with GOCD, I deleted and redeployed, and I can use LDAP to log in without checking "only allow known users to login field".
