### ISSUE TITLE
Email server Send Error

### ISSUE THREAD

**Issue by liuwenzhi0318** [gocd/gocd#10383]
##### Issue Type

In the "Email server", set the SMTP port to 465 and enable "Use SMTPS". Clicking "Send Test Email" also prompts success and can receive emails, but it always prompts to use 25 when the information is sent to the user in the build acquisition stage. port

config：
![image](https://user-images.githubusercontent.com/37536326/165881866-daba6d0c-db39-41a3-a0fb-eda269f82562.png)

error:
![image](https://user-images.githubusercontent.com/37536326/165881814-f4ba076d-9b41-4d8e-9231-eb75752c3054.png)

**Comment by liuwenzhi0318** [comment]
The environment on my side must use an encryption protocol, and port 25 is disabled.

**Comment by chadlwilson** [comment]
Based on the stack trace (`com.tw.go.plugin.EmailNotificationPluginImpl`), this configuration is for the "email notifier" plugin at https://github.com/gocd-contrib/email-notifier - however your screenshot of configuration is from the GoCD Server configuration.

it seems you have installed the email notifier plugin. I don't understand the background of this plugin, but this plugin has its own configuration independent of the server configuration. You will likely need to configure it separately at `/go/admin/plugins` using the plugin's configuration.

Can you check your config of the plugin, and if there is a problem with that plugin's configuration please open it at https://github.com/gocd-contrib/email-notifier ?
