### ISSUE TITLE
you are not aythenticated /gocd pipeline/ git repository url

### ISSUE THREAD

**Issue by sumanreddyy45** [gocd/gocd#10392]
##### Issue Type

- Security issue? [**DO NOT** report it here. Please use [hackerone](https://hackerone.com/gocd) to report the issue.]
- Bug Report
- Feature proposal
- Feature enhancement
- Documentation Report
- Question? [**DO NOT** ask it here. Ask in the [mailing list](https://groups.google.com/forum/#!forum/go-cd)].

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by chadlwilson** [comment]
Hi - sorry, there's not enough information here to understand what problem you are reporting, so I am going to close this.

If you still have a problem please create a new ticket with the details in the template filled in so we can understand, or perhaps ask for some help on our [Google Groups](https://groups.google.com/g/go-cd/).
