### ISSUE TITLE
Builds not triggered on SVN external changes

### ISSUE THREAD

**Issue by thenathanjones** [gocd/gocd#1039]
Hey guys,

Our build currently makes use of SVN externals to simulate a single tree structure that we're looking to migrate to as part of a Gradle multi-project build.

We're finding a situation where code changes to the externals are not triggering a build. Changes to the top level repository are. If we manually trigger a build all the changes made to the externals are successfully pulled down.

We're currently using version 1.8.11 of Subversion and both agent/server are on CentOS 7.1.15, of which I have no control over. The version of Go we're currently using is 14.4.0.

Any ideas what it could be? My suspicion is an SVN version issue looking at the code, but would this make sense?

Nathan

**Comment by arvindsv** [comment]
Have you set [checkExternals](http://www.go.cd/documentation/user/current/configuration/configuration_reference.html#svn) to true?

**Comment by thenathanjones** [comment]
Yes the flag is set

**Comment by arvindsv** [comment]
[This](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/domain/materials/svn/SvnCommand.java#L97) is what it does, to get all external URLs, and then it does [this](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/domain/materials/svn/SvnCommand.java#L134) on all those externals, to find out what has changed. I think you can try executing those, and see if something fails, maybe?

**Comment by thenathanjones** [comment]
It appears to be because they use the ^ character for root relative paths
to the externals. I made a failing test to confirm, and have a fix, I just
want to try it out in a running system before I submit a pull request.
Thanks for the pointer to the code.

2015-04-18 4:38 GMT+12:00 Aravind SV <notifications@github.com>:

**Comment by thenathanjones** [comment]
Hey guys, any update on when we can look at getting #1051 included? This and a few other bugs are really giving me grief at my current client but i'm not seeing it on any roadmap or had any feedback to the pull request.

**Comment by zabil** [comment]
I believe testing manual testing is over in this. Functional twist tests need to be added?
