### ISSUE TITLE
Agent process is killed and new plugins.zip is downloaded on every
server restart without changes made to the server plugins directory

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#104]
### Steps to reproduce
1.  Have couple of plugins at the server side
2.  Notice that agent-plugins.zip is present in the sandbox directory of the agent
3.  Keep a note of the time stamp of the agent-plugins.zip on the agent side
4.  Also keep a note of the process id of the running agent
5.  Restart the server

#### Expected result

Since the plugins have not undergone any change the agent-plugins.zip should not be downloaded again and certainly agent process should not get killed

#### Current result

The new timestamp of agent-plugins.zip and new process id of agent indicates that agent was killed and plugins.zip was downloaded again which is incorrect

**Comment by arikagoyal** [comment]
Should be handled with #121

**Comment by arikagoyal** [comment]
Works fine on 15.1.0(1541-0371244c807770)
