### ISSUE TITLE
Replace NanoHttpd with an alternative

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd#10428]
##### Summary

In #3781 Nanohttpd was added in order to provide a simple health API for long-lived agents. Unfortunately [nanohttpd](https://github.com/NanoHttpd/nanohttpd) appears to be abandoned, and also has an unpatched security vulnerability (at https://github.com/NanoHttpd/nanohttpd/issues/620)

It would probably be wise to replace with an alternative, although there might not be an option quite as small.

[Javalin](https://javalin.io/) based on Jetty is one possible option (since we use Spring with Jetty on server side, at least underlying webserver is consistent), although Jetty is likely to be less lightweight overall compared to nanohttpd.

**Comment by chadlwilson** [comment]
I had spike-hacked to change to just use the built-in JDK `HttpServer` some time ago [here](https://github.com/gocd/gocd/compare/master...chadlwilson:replace-nano-with-builtin?expand=1) which i hadn't pushed or finished off.

Needs the tests to be re-worked and possibly some additional effort to ensure it is configured "safely" in terms of max connections, timeouts etc, hopefully similar to NanoHttpd. My feeling is that this seems much better than pulling in all of Jetty via Javalin.

**Comment by ravikp** [comment]
If the customers use JRE 13/14 especially on the agent(without the packaged JRE version in the artefact), then there is a potential issue to be considered when using your(@chadlwilson) patch in progress that uses inbuilt http server. Here is the issue reported in the JDK bug tracker system.

https://bugs.openjdk.org/browse/JDK-8233185

I haven't undestood that usage of PUT method at [line](https://github.com/gocd/gocd/blob/4deb96d823b921419680560be080588e900d406e/agent/src/main/java/com/thoughtworks/go/agent/statusapi/AgentStatusHttpd.java#L42). The `dependency-check-suppress.xml` describes only about the GET requests. Is there a functional need for PUT requests?

**Comment by ravikp** [comment]
Never mind about the [JDK bug](https://bugs.openjdk.org/browse/JDK-8233185), it may not be applicable, because the [patch](https://github.com/gocd/gocd/compare/master...chadlwilson:replace-nano-with-builtin) is stopping on a postdestroy, which may be a different thread.

**Comment by chadlwilson** [comment]
> If the customers use JRE 13/14 especially on the agent(without the packaged JRE version in the artefact), then there is a potential issue to be considered when using your(@chadlwilson) patch in progress that uses inbuilt http server. Here is the issue reported in the JDK bug tracker system.
> 
> https://bugs.openjdk.org/browse/JDK-8233185

Thanks @ravikp - I'll take a look and consider that, since currently it doesn't use a separate `executor`. I don't think it would be calling `.stop()` on a dispatch thread (that would happen on the main thread during regular Spring shutdown for an agent) but will check.

> I haven't undestood that usage of PUT method at [line](https://github.com/gocd/gocd/blob/4deb96d823b921419680560be080588e900d406e/agent/src/main/java/com/thoughtworks/go/agent/statusapi/AgentStatusHttpd.java#L42). The `dependency-check-suppress.xml` describes only about the GET requests. Is there a functional need for PUT requests?

Yeah, I don't understand that either - just ported across the original semantics. It seems there from the start but #3781 doesn't mention why `PUT` was specifically allowed (and not, say, `POST`). It might have been an oversight left in during some testing?

**Comment by chadlwilson** [comment]
`PUT` also is not documented at https://api.gocd.org/current/#agent-health so probably safe to remove.

**Comment by ravikp** [comment]
I started writing tests on top of your [work](https://github.com/gocd/gocd/compare/master...chadlwilson:replace-nano-with-builtin), which I will soon publish. IMO, during the refactoring of test cases according to your work, I have observed that [the test `shouldNotInitializeServerIfSettingIsTurnedOff`](https://github.com/gocd/gocd/blob/4deb96d823b921419680560be080588e900d406e/agent/src/test/java/com/thoughtworks/go/agent/statusapi/AgentStatusHttpdTest.java#L94) is incorrectly implemented. Because, the line `        when(systemEnvironment.getAgentStatusEnabled()).thenReturn(true);` should expect to return `false`. 

Is my understanding right?

**Comment by ravikp** [comment]
Since I'm writing the test cases based on your [work](https://github.com/gocd/gocd/compare/master...chadlwilson:replace-nano-with-builtin) shall I refactor and remove the PUT api?

**Comment by chadlwilson** [comment]
> I started writing tests on top of your [work](https://github.com/gocd/gocd/compare/master...chadlwilson:replace-nano-with-builtin), which I will soon publish. IMO, during the refactoring of test cases according to your work, I have observed that the test [shouldNotInitializeServerIfSettingIsTurnedOff](https://github.com/gocd/gocd/blob/4deb96d823b921419680560be080588e900d406e/agent/src/test/java/com/thoughtworks/go/agent/statusapi/AgentStatusHttpdTest.java#L94) is incorrectly implemented. Because, the line `when(systemEnvironment.getAgentStatusEnabled()).thenReturn(true);` should expect to return `false`.
> 
> @chadlwilson Is my understanding right?

Yeah, that test is broken. Fixed at https://github.com/gocd/gocd/pull/12200/files to decouple from whatever you are working on :-)

> Since I'm writing the test cases based on your [work](https://github.com/gocd/gocd/compare/master...chadlwilson:replace-nano-with-builtin) shall I refactor to remove the PUT api?

Yeah, let's do it.

**Comment by ravikp** [comment]
The respective code change is coming in the PR #12202.
