### ISSUE TITLE
Incompatible revisions causing 100% CPU load

### ISSUE THREAD

**Issue by ngrash** [gocd/gocd#1044]
Go Version: 14.4.0(1356-86064ef5ee28e0)

Number of pipelines: 124
Number of agents: 6
Number of environments: 13
Number of unique materials: 124
Number of schedulable materials: 124

[View full output of http://go-server:8153/go/api/support](http://pastebin.com/SRabDyMe).

A short time after starting `go-server` as a daemon, the CPU load goes up to 100% on all eight cores. As suggested by @arvindsv in IRC, I added more memory but without an effect. The result is that the server has very poor response-time and is useless for us at the moment, because almost no pipelines are triggered.

The log file `/var/log/go-server/go-server.log` contains a lot of lines like the following (~90 in the last 10 hours):
`2015-04-20 07:08:08,777  WARN [72@MessageListener for ScheduleCheckListener] DependencyFanInNode:220 - [Fan-in] - Incompatible materials for PIPELINE/X/STAGE/Y. Config: [GUID]. Instance: [].`

Checking `http://go-server:8153/go/tab/pipeline/history/PIPELINE` I see that revision X is not listed. 

Not sure if this is important or just how the internal numbering works: The revision X - 1 has the ID X, i.e. the link points to http://go-server:8153/go/pipelines/value_stream_map/PIPELINE/X.

I'll happily provide more information, so let me know what's needed.

(The title comes from @arvindsv's guess about the cause)

**Comment by arvindsv** [comment]
Hi @ngrash, the first thing I'd do now is to take a backup, using ```http://your-go-server:8153/go/admin/backup```, and keep it. I can provide a secure location to upload that to, if you don't mind.

You should also try passing in the system property ```-Dresolve.fanin.revisions=N``` and restart Go, to see if it helps. That turns off fan-in. It might be useful to do this, till we can figure out what is causing the issue. But, do that only after taking a backup. Once you do that, and if it works around (or does not work around) the problem, please capture the output of ```/go/api/support``` again.

The people that are best positioned to look at this are busy this week, and I don't see this being looked at till next week. Just to let you know.

Thank you!

**Comment by arvindsv** [comment]
The title could be "Incompatible revisions", not "Missing revisions". But, it's ok. :)

**Comment by ngrash** [comment]
Thanks, @arvindsv. I created a backup as you suggested and restarted the service with `-Dresolve.fanin.revisions=N`. The CPU load still goes up to 100% most of the time, but it drops to a normal level periodically. The system is responding again and I successfully triggered some workflows.

I'm aware of the [drawbacks of disabling fan-in](www.go.cd/documentation/user/current/advanced_usage/fan_in.html) but as far as I understand, we can continue using the system now, as long as we double check our unit tests and deployments.

I uploaded [the output of go/api/support](http://pastebin.com/hjFknzXv).

You can contact me in IRC for a secure location to upload the backup.

**Comment by arvindsv** [comment]
Great, I will. When it goes to 100%, take the output of that periodically, and it might help.

**Comment by arvindsv** [comment]
Oh, also, yes, you can continue using the system now. It'll be alright. Once we find the issue, then we can look at turning it back on.

**Comment by ngrash** [comment]
I tried to capture the output with [high CPU load](http://pastebin.com/mQDvkACh) and [low CPU load](http://pastebin.com/8Hbum4w7). Hopefully I got the right timing, the load is not very stable.

Good to hear that we can continue using the system. Thanks a lot.

**Comment by ngrash** [comment]
Just to make that clear, the uptime is high most of the time. Load average reported by `uptime` is `6.44, 6.59, 6.63`. The box got eight cores, so that's probably not too bad, but then again it's only running Go.

**Comment by arvindsv** [comment]
That does seem quite high. Thanks for the outputs from /go/api/support. It will help.

**Comment by etiennetremel** [comment]
Any update on this? We are experiencing a similar issue causing our server to have a very poor response time.
