### ISSUE TITLE
Using Postgres / MySQL with Docker image 

### ISSUE THREAD

**Issue by binaryfire** [gocd/gocd#10494]
Hi guys

Is it possible to use a Postgres or MySQL db with your Docker image? There aren't any db environment variables listed on Docker Hub and I can't find anything in the docs

Thanks!

**Comment by sriramnrn** [comment]
On Sun, 5 Jun 2022 at 11:10 PM, Raj Siva-Rajah ***@***.***>
wrote:

> Hi guys
>
> Is it possible to use a Postgres or MySQL db with your Docker image? There
> aren't any db environment variables listed on Docker Hub and I can't find
> anything in the docs
>

https://docs.gocd.org/current/installation/configuring_database/postgres.html



Thanks!

**Comment by sriramnrn** [comment]
On Sun, 5 Jun 2022 at 11:12 PM, Sriram Narayanan ***@***.***>
wrote:

> On Sun, 5 Jun 2022 at 11:10 PM, Raj Siva-Rajah ***@***.***>
> wrote:
>
> > Hi guys
> >
> > Is it possible to use a Postgres or MySQL db with your Docker image?
> There
> > aren't any db environment variables listed on Docker Hub and I can't find
> > anything in the docs
> >
>
>
> https://docs.gocd.org/current/installation/configuring_database/postgres.html
>
>
Also,

https://hub.docker.com/r/gocd/gocd-server-centos-8

**Comment by binaryfire** [comment]
@sriramnrn I had a good look through those links but couldn't see any instructions re: connecting an external db to the Docker image? The info is for a bare metal setup.

Would I create a volume for the /config directory and specify the db container's port etc in there?

**Comment by chadlwilson** [comment]
The DB configuration isn't externalised to environment vars - you basically need to create your config inside `/godata/config/db.properties` per [the docs](https://docs.gocd.org/current/installation/configuring_database/postgres.html) @sriramnrn links to.

You can mount a file directly into that path, or create a file inside your external volume, if you are mounting a volume into `/godata` entirely.

**Comment by binaryfire** [comment]
@chadlwilson Great thanks. Could be worth mentioning that in the docs?

**Comment by chadlwilson** [comment]
> @chadlwilson Great thanks. Could be worth mentioning that in the docs?

If you have a suggested edit that would clarify things, a suggested PR or wording change would be welcome
* Docker READMES: https://github.com/gocd/gocd/blob/master/buildSrc/src/main/resources/gocd-docker-server/README.md.ftl
* Main docs: https://github.com/gocd/docs.go.cd/blob/master/content/installation/configuring_database/postgres.md
