### ISSUE TITLE
Job Instance API does not return `job_state_transitions`

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#10566]
##### Issue Type

- Bug Report

##### Summary

The job instance API with 22.2.0 (master) is not returning any `job_state_transitions` as is mentioned in the documentation. When I run the following command, the `job_state_transitions` is empty:

`curl  -H 'Accept: application/vnd.go.cd+json' -s http://admin:badger@localhost:8153/go/api/jobs/up42/1/up42_stage/1/up42_job`

```
{
  "name" : "up42_job",
  "state" : "Scheduled",
  "result" : "Unknown",
  "original_job_id" : null,
  "scheduled_date" : 1656610300191,
  "rerun" : false,
  "agent_uuid" : null,
  "pipeline_name" : "up42",
  "pipeline_counter" : 1,
  "stage_name" : "up42_stage",
  "stage_counter" : "1",
  "job_state_transitions" : []
}
```

Digging a bit deeper, it looks like the [api controller](https://github.com/gocd/gocd/blob/54e657fd508ebb1f8764988456f5e78e42f076e8/api/api-job-instance-v1/src/main/java/com/thoughtworks/go/apiv1/jobinstance/JobInstanceControllerV1.java#L92) is invoking a service method that does not pull in the relevant job state transition data from DB.

**Comment by ketan** [comment]
Seems the fix is this. Tests will require some fixing.

```patch
diff --git a/api/api-job-instance-v1/src/main/java/com/thoughtworks/go/apiv1/jobinstance/JobInstanceControllerV1.java b/api/api-job-instance-v1/src/main/java/com/thoughtworks/go/apiv1/jobinstance/JobInstanceControllerV1.java
index 02ea688ba7..9155d271eb 100644
--- a/api/api-job-instance-v1/src/main/java/com/thoughtworks/go/apiv1/jobinstance/JobInstanceControllerV1.java
+++ b/api/api-job-instance-v1/src/main/java/com/thoughtworks/go/apiv1/jobinstance/JobInstanceControllerV1.java
@@ -22,9 +22,8 @@ import com.thoughtworks.go.apiv1.jobinstance.representers.JobInstanceRepresenter
 import com.thoughtworks.go.apiv1.jobinstance.representers.JobInstancesRepresenter;
 import com.thoughtworks.go.config.exceptions.BadRequestException;
 import com.thoughtworks.go.config.exceptions.RecordNotFoundException;
-import com.thoughtworks.go.domain.JobInstance;
-import com.thoughtworks.go.domain.JobInstances;
-import com.thoughtworks.go.domain.PipelineRunIdInfo;
+import com.thoughtworks.go.domain.*;
+import com.thoughtworks.go.server.dao.JobInstanceDao;
 import com.thoughtworks.go.server.service.JobInstanceService;
 import com.thoughtworks.go.spark.Routes;
 import com.thoughtworks.go.spark.spring.SparkSpringController;
@@ -43,11 +42,14 @@ public class JobInstanceControllerV1 extends ApiController implements SparkSprin
     private final ApiAuthenticationHelper apiAuthenticationHelper;
     private final JobInstanceService jobInstanceService;
 
+    private final JobInstanceDao jobInstanceDao;
+
     @Autowired
-    public JobInstanceControllerV1(ApiAuthenticationHelper apiAuthenticationHelper, JobInstanceService jobInstanceService) {
+    public JobInstanceControllerV1(ApiAuthenticationHelper apiAuthenticationHelper, JobInstanceService jobInstanceService, JobInstanceDao jobInstanceDao) {
         super(ApiVersion.v1);
         this.apiAuthenticationHelper = apiAuthenticationHelper;
         this.jobInstanceService = jobInstanceService;
+        this.jobInstanceDao = jobInstanceDao;
     }
 
     @Override
@@ -89,7 +91,8 @@ public class JobInstanceControllerV1 extends ApiController implements SparkSprin
         String jobName = request.params("job_name");
         Integer pipelineCounter = getValue(request, "pipeline_counter");
         Integer stageCounter = getValue(request, "stage_counter");
-        JobInstance jobInstance = jobInstanceService.findJobInstance(pipelineName, stageName, jobName, pipelineCounter, stageCounter, currentUsername());
+        StageIdentifier stageIdentifier = new StageIdentifier(pipelineName, pipelineCounter, null, stageName, stageCounter.toString());
+        JobInstance jobInstance = jobInstanceDao.mostRecentJobWithTransitions(new JobIdentifier(stageIdentifier, jobName));
         if (jobInstance.isNull()) {
             throw new RecordNotFoundException(format("No job instance was found for '%s/%s/%s/%s/%s'.", pipelineName, pipelineCounter, stageName, stageCounter, jobName));
         }
```

**Comment by chadlwilson** [comment]
The `job_state_transitions` with an empty array is also mentioned in the [history](https://api.gocd.org/current/#get-job-history) too.

Do you think it's actually intentional to not return this, and it's more of an issue with the docs using a default serialized representation which includes the empty collection? Obviously we could correct the example in the docs to represent reality.

Having said this, since https://api.gocd.org/current/#agent-job-run-history does include the transitions and there is no other way to get them it probably makes sense that they should be returned...

**Comment by chadlwilson** [comment]
As far as I can see, the job **history** API never returned the transitions, even in its earlier Rails incarnation. It seems to have always used the below, which doesn't load the transitions.

https://github.com/gocd/gocd/blob/5638a49a35e5a96836f8870deae69a8e9c8f1093/server/src/main/resources/com/thoughtworks/go/server/dao/maps/JobInstance.xml#L101-L110

Should these be consistent I wonder?

**Comment by ketan** [comment]
The reason I called this out as a bug is that the job instance API seems to indicate (based on the example) that it should return the transitions, but somehow that's not the case. I don't recall very much about the old APIs; but I do know that the new APIs are simply a port of the old APIs, so I'm sure that the old APIs probably don't return that data either.

I was looking to use the job instance API to finally get rid of the job detail page, and rebuild it as an SPA - I realied that the stage detail API seems to have the right detail (used to show the popup shown below), but the job instance API is missing the data, and that to me felt incoherent.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/10598/176998298-f352f03e-7d04-46a5-8e0c-f5159f0bb11d.png">

**Comment by sriramnrn** [comment]
Hi Ketan, could you elaborate on what you intend to get rid of?

Many of us GoCD fans use the Job details page to great social, technical
and political success.

In case you do plan to include the same information, then that would be
good indeed.

Thanks,

Sriram

**Comment by ketan** [comment]
Sorry, should have been clearer — I do not intend to remove it, but replace it with a newer, lighter and more modern page that consumes APIs instead of being rendered on the server side. The current page uses apache velocity which is deprecated, and causing hindrances to upgrade gocd to newer versions of spring & hibernate.

**Comment by chadlwilson** [comment]
Thanks @ketan. Would it be sufficient/useful for what you are trying to do to just have the job instances API return them (something akin to your suggested fix), but not the paginated history API?

**Comment by ketan** [comment]
I've not given much thought about the paginated history API yet. For now, I'm thinking that it'd be nice for the job API to return the transitions. I might need some more stuff once I get to implementing the page.

**Comment by arvindsv** [comment]
I seem to remember that something about returning the transition details in the paginated history API being very expensive (from a performance perspective), but I could be wrong.
