### ISSUE TITLE
Gocd-server:v22.1.0 can no longer check connections on private git materials

### ISSUE THREAD

**Issue by LawrenceSpear** [gocd/gocd#10561]
##### Issue Type

- Bug Report

##### Summary

When trying to check a connection on a private github or bitbucket repo the check connection will timeout the entire server and the JVM will automatically restart

##### Environment

Just run the gocd/gocd-server:v22.1.0 docker image with only setting the port.

Tested on a machine with 64GB of RAM and an Intel core i9-9980HK using Docker Desktop v4.9.1

Tested on Synology NAS as well

###### Basic environment details

Download gocd/gocd-server:v22.1.0 
Set port to 8153

##### Expected Results

Type in a private git repo URL

click check connection

Should just report that it can't log after the timeout in like it does in v21.4.0, v21.3.0, v21.1.0

Launch another browser to the go server while waiting for the timeout and it will be responsive

##### Actual Results

Type in a private git repo URL

click check connection

Server with restart

Launching another browser to the go server while waiting for the timeout and it won't respond

##### Possible Fix

I'm guessing the check connection is using the main servers thread to check the URL instead of launching a child thread to check it

**Comment by chadlwilson** [comment]
I can't replicate anything like this. Tried with a GitHub private repo over both SSH and HTTPS with different combinations of reasons for the failure and it always works fine.

Can you please be more specific about the _exact_ steps you are following? Preferably an example with a real repo URL that can be repeated, and/or screenshots of which screen you are on. For example, what do you mean by "report that it can't log after the timeout"? If username/pass authentication is wrong, why would it timeout? Is the repo address valid?

What is the repository manager you are connecting to? GitHub? Are you using SSH or HTTPS? Are you using the pipeline wizard to add a new pipeline+material and testing it while creating a new pipeline? Are you adding a config repository? Which exact screen/URL are you testing the connection on? What's the mistake you are making with your auth? Wrong username? Wrong password?

What do you mean by "report that it can't log after the timeout"? If the authentication is wrong, why would it timeout?

If you can include a redacted `config.xml` which keeps all the key information there might be a clue there, but the description at https://groups.google.com/g/go-cd/c/nDVhq8zU5r4 is very confusing - you initially said that you rebuilt the container and it was working fine, but then seem to have come across the same problem again without much description.

**Comment by arvindsv** [comment]
Yes, seems strange. Will need more info. I checked on both the new pipeline wizard and the config repos page (before reading that Chad did the same) and it seems to work fine:

<img width="793" alt="2022_06_30_13-46-32" src="https://user-images.githubusercontent.com/172235/176680779-cab87666-dd6e-4d09-b5a3-9f0fd5e23ba4.png">

<img width="796" alt="2022_06_30_13-46-13" src="https://user-images.githubusercontent.com/172235/176680817-acf6fdc0-5e80-4c7a-9f64-668f09f6ec78.png">

**Comment by arvindsv** [comment]
> I'm guessing the check connection is using the main servers thread to check the URL instead of launching a child thread to check it

Not really. It just spawns a `git` process on that web request's thread. Nothing special.

**Comment by chadlwilson** [comment]
Thanks.

>     * Change URL to https://github.com/mtmg-li/Pipeline-Test.git, which is private
> 
>     * Click Test Connection
> 
>     * While it’s “testing” Ctrl click the go icon in the corner to launch a new browser to the same go instance and you’ll see it won’t load. If you refresh the 1st browser window it will be the GoCD starting screen

And what error are you expecting to get? i.e do you have the username+pass configured? (it's not mentioned in the steps so I assume now?) with your legit username and a personal access token?

For me it immediately fails with the below (expected)

![image](https://user-images.githubusercontent.com/29788154/176701134-d4afa4ec-24ac-4f3f-957a-a2a8fd486c2b.png)

If I set a username but no pass, it immediately fails with 
![image](https://user-images.githubusercontent.com/29788154/176701556-9246ef1f-a79a-4e34-87ce-f7887fa23062.png)

If I set a username and pass that are bad it immediately fails with

![image](https://user-images.githubusercontent.com/29788154/176701691-ffccf281-b820-4510-ad5b-82fe6fb73e9f.png)

etc etc.

The "testing connection" never spins for any significant amount of time, and the JVM certainly never restarts.

> I tested these same steps on v17.3.0, v19.5.0, v21.3.0 and v21.4.0. They all worked just fine. Only v21.4.0 would restart the JVM.

_Your original message_:
> Should just report that it can't log after the timeout in like it does in v21.4.0, v21.3.0, v21.1.0

Can you clarify? In your original message you said it only fails in `22.1.0` and worked in `21.4.0`, but now you say `21.4.0` is problematic as well?

Have you tried a different browser? And this is Windows... 11 I assume?

**Comment by LawrenceSpear** [comment]
Sorry, too many versions and not enough caffeine. Only 22.1.0 had the error. 21.4.0 worked. 

Correct I didn't fill in the username/password yet and was expecting a quick error message back around failed to auth, but instead it timedout and reset the GoCD server.

I'm running Windows 11 and using Edge.

I just installed Firefox and did the same steps and got the same results as I did when running Edge with the JVM being reset.

If I use a valid user and valid pass token it will check ok.

**Comment by LawrenceSpear** [comment]
I just deleted my container and image. Redownloaded the image and created a new container from it only setting the port to 8153. Starting it and just setting the Material URL to https://github.com/mtmg-li/Pipeline-Test.git. Clicking test connection causes the JVM to reset.

**Comment by LawrenceSpear** [comment]
Using wsl2 and I don't have a .wslconfig file, so the container should have no limit on CPU or RAM

**Comment by LawrenceSpear** [comment]
On my NAS it's using synology's linux distro with no limits as well

**Comment by chadlwilson** [comment]
I've tried again to replicate this (on Windows 10 with WSL2) and I cannot do so. Unless we can find an error or narrow down what is going on, there's nothing we can do here.

If you can find information/errors in the container logs when it resets and can share results of `/go/api/support` can take another look and re-open, but not sure what else we can do.
