### ISSUE TITLE
Upgrading database from H2 to MySQL fails with multiple duplicate key issues & script crashing

### ISSUE THREAD

**Issue by rushi** [gocd/gocd#10605]
I cannot upgrade GoCD (v20.4.0) database from H2 to MySQL as the **migration script crashed**. How can I fix the upgrade process so it will complete and migrate the data?

#### Summary

I am currently on **GoCD 20.4.0** and I am trying to upgrade my database from **H2 to MySQL** so that I can upgrade to future versions of GoCD. I used the [latest stable release](https://github.com/gocd/gocd-database-migrator/releases/tag/1.0.0-39) of the `gocd-database-migrator` tool to run the database upgrade and after processing all the records, it started throwing errors about duplicate keys for various tables along with foreign key constraint problems. 

The script ran and [sent a bunch of output](https://gist.github.com/rushi/4224202f4fe0cbf51b8c95389b41c8ed) and crashed completely.

#### Environment

Config partially sanitized from `/go/api/support`: https://gist.github.com/rushi/3cd698fe049c9399fbde6c791ed252ee

##### Basic environment details

* Go Version: 20.4.0 (11749-5553066d29d315951efa5ead0c087374df6338b9)
* JAVA Version: 13.0.2
* OS: Linux 5.4.0-1080-aws (Ubuntu 18.04.6 LTS from `/etc/lsb-release`)

##### Additional Environment Details

* MySQL v8.0.26 with the InnoDB Engine 
* 2 vCores 2GB Ram hosted on AWS

#### Log snippets

The script crashed at the end, and here is the entire log of the process: https://gist.github.com/rushi/4224202f4fe0cbf51b8c95389b41c8ed

Some code I used to parse the log:

* `grep "java.lang.RuntimeException: java.sql.SQLIntegrityConstraintViolationException" gocd-database-migrator-mysql-2022-07-16.log` 
* `grep "Executing SQL: insert into" gocd-database-migrator-mysql-2022-07-16.log`

#### Any other info

I see lines like `Duplicate entry '1' for key 'DATASHARINGSETTINGS.PRIMARY'` and not sure why that would fail because `DATASHARINGSETTINGS` has literally only one entry

**Comment by rushi** [comment]
Let me now if any information from the H2 database is required. I can open up a shell and grab some data

**Comment by chadlwilson** [comment]
To clear things up, I would start by addressing the earliest `ERROR`s.

`com.mysql.cj.jdbc.exceptions.PacketTooBigException: Packet for query is too large (21,300,627 > 16,777,216). You can change this value on the server by setting the 'max_allowed_packet' variable.`

Either that, or try decreasing the `batch-size` (see [here](https://github.com/gocd/gocd-database-migrator)) until you stop getting any of these errors.

**Comment by rushi** [comment]
@chadlwilson Thank you changing the batch-size actually solved it! But ofcourse I ran into the [lower_case_table_names](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_lower_case_table_names) issue. Since I am using a hosted MySQL provider (ScaleGrid) I can't change that system variable. 

Are there any other options to solve this issue? Can I rename the tables to the correct case?

**Comment by chadlwilson** [comment]
I'm not sure, but I don't think so within GoCD unless you can find a similar way to do affect case sensitivity at driver level (although not sure that's possible with MySQL.

I'd probably be checking again with ScaleGrid.

**Comment by chadlwilson** [comment]
Perhaps you also want to consider PostgreSQL instead if that's easier to get over the line.

Closing this for now, as does not seem to be a GoCD issue here. Happy to continue the conversation regardless.

**Comment by rushi** [comment]
I used Postgres and it's working like a charm. I'd prefer MySQL but I can migrate from Postgres to MySQL later.

Thank you @chadlwilson for your help over a weekend.

**Comment by sriramnrn** [comment]
On Sun, 17 Jul 2022 at 5:56 PM, Rushi Vishavadia ***@***.***>
wrote:

> I used Postgres and it's working like a charm. I'd prefer MySQL but I can
> migrate from Postgres to MySQL later.
>


Could you share why you prefer MySQL in this case where the DB would be
exclusive to GoCD?
( eg company policy, you query the DB content, etc)

Thank you @chadlwilson <https://github.com/chadlwilson> for your help over

**Comment by rushi** [comment]
@sriramnrn Because of experience. I prefer MySQL because I have used it a lot more and maintained large installations. Nothing against Postgres I just don't have enough experience.
