### ISSUE TITLE
Assets (and content) could be served as gzip

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1060]
The assets that could be served by gocd (css, js) and potentially any other content could potentially be served as gzip content to send the content quickly over the wire.

Currently the assets are minified but not served gzipped.

**Comment by arvindsv** [comment]
Some related conversation [here, on Gitter](https://gitter.im/gocd/gocd?at=553f876cdc036cab2e23c9d2).

**Comment by ketan** [comment]
Related issue - #1073

**Comment by zabil** [comment]
Is someone testing this?

**Comment by ketan** [comment]
It's not assigned, so all yours :)

Make sure to read the commit message before anything else.

**Comment by juhijariwala** [comment]
Works as expected (tested locally).

**Comment by zabil** [comment]
@juhijariwala this must have gone into the build by now. Did you get a chance to check this? Is so advice on closing.

**Comment by juhijariwala** [comment]
Works as expected. Tested with Go Version: 15.2.0(2188-a788f1876e2e1f)
