### ISSUE TITLE
Support secure environment variables at environment/stage/job
levels

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#107]
## Description
Currently secure environment variables have been implemented only at the pipeline level. Go should also support environment/stage/job level secure environment variables.

http://support.thoughtworks.com/entries/22004466-Secure-Env-variables-at-the-Env-level-currently-only-can-do-this-for-a-pipeline-?page=1#post_21736954

**Comment by agileassistance** [comment]
I would really appreciate this feature in the upcoming release; it's vital for keeping sensitive information secured in the build and the lack of it leads to some convoluted/unnecessary workarounds that makes the pipelines hard to maintain.

**Comment by ketan** [comment]
Closing as duplicate of #194. Please track progress there.
