### ISSUE TITLE
The job detail page does not show the entire console output when a job is cancelled.

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1072]
To replicate.
- Go to the job details the job details page
- View the console out in the console tab
- Cancel the stage on another page
- The page reloads with the final console output because the stage is cancelled
- The agent keeps writing to the console file and the and that output (along "Job completed") will be seen only when the job is over and the page is refreshed again.

Tested on 14.4+ builds on mac

**Comment by ketan** [comment]
Here's the task that can be used -

```shell
bash -c 'for i in {{1..300}}; do echo foo; echo bar; sleep 1; done'
```

**Comment by zabil** [comment]
Similar to #923

**Comment by arvindsv** [comment]
Closing as stale.
