### ISSUE TITLE
Issue with same material having different trigger types (manual/automatic) in different pipelines

### ISSUE THREAD

**Issue by mujir** [gocd/gocd#1080]
One 'material' (a github repository) is a trigger in multiple pipelines across different pipeline groups. We need it be a 'manual' trigger for one pipeline and 'automatic' trigger in other pipelines. Changing it in the other pipeline gives this error

"Material of type Git (https://github.com/Bhamni/bahmni-environment.git) is specified more than once in the configuration with different values for the autoUpdate attribute. All copies of the a material should have the same value for this attribute"

**Comment by pshelton-skype** [comment]
We are facing exactly the same issue. We have some test source git repos that we want to trigger builds on commits, then trigger subsequent pipelines that also consume the test source. But, we don't want the subsequent pipelines to be triggered by material changes but only by the upstream pipeline. We've taken to pulling the git repo manually in each downstream stage rather than having it configured as a material, but this is less maintainable. Ideally, materials would have pipeline-specific settings rather than global settings.

**Comment by srinivasupadhya** [comment]
This should help -
https://groups.google.com/d/topic/go-cd/rBouLywo3a4/discussion

**Comment by jyotisingh** [comment]
>> One 'material' (a github repository) is a trigger in multiple pipelines across different pipeline groups. We need it be a 'manual' trigger for one pipeline and 'automatic' trigger in other pipelines. 

Correct me if I might have misunderstood your problem. 
'autoUpdate' property on a material would tell Go if it should update its local copy of the material. It has nothing to do with triggering a pipeline. If you wish to trigger your pipeline manually, just configure it to do so. [Details](http://www.go.cd/documentation/user/current/configuration/pipeline_scheduling.html#pipeline-scheduling)

>> we don't want the subsequent pipelines to be triggered by material changes but only by the upstream pipeline

You could use material blacklisting here. [Details](http://www.go.cd/documentation/user/current/configuration/admin_add_material.html#blacklist)

**Comment by joel74** [comment]
It makes no sense to me, and seems like a significant bug, that materials need to have the same settings across pipelines. Say I have Pipeline1 and Pipeline2, and both references material svn.myco.com/project1. I want Pipeline1 to poll for new changes (AutoUpdate) and Pipeline2 not to. The settings for a material in one pipeline should not affect / restrict the settings for a material in another pipeline. Materials are pipeline components, not separate entities.

**Comment by chadlwilson** [comment]
Related to #1033
