### ISSUE TITLE
Elastic agents

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1082]
More details here.

https://arvindsv.github.io/elastic_agents_for_gocd.html

---
### Tasks:

* Move to websockets for agent-server communication. 
  Take care of build assignments and rescheduling flows
* Server could invoke the plugin right after scheduling based on the agent requirements(resources). 
  Plugins are tagged with special resources stating the kind of plugin they handle, as well as the resources they are capable of handling. eg. : For a docker plugin, the plugin settings would be something like "linux, mvn" maps to build/dockerfile and "ab, linux" maps to performance/dockerfile. So when the plugin is told about "ab, linux" it know it has to create a performance agent. The plugin should pass along these resources for the agent to auto-register. What about environments?
* plugins brings up the required agents(if it has to)
* agent will now run as regular agent, so work assignment flow would be the same as regular plugins. 
* periodically, the plugin decides to kill the agents it has spun up based on whatever arbitrary rule that it fancies, say run duration, idle-state etc.  The same needs to be tracked by the plugin. We probably need to notify the plugin about the current status of the agent ie. idle or not. No other info would be made available in Go to allow the plugin to make this decision.
* auto-registration of such agents is already taken care of. The pending task here would be for plugins to make sure that autoregister.properties file is available for the agent with the right values. Question: How do we pass the autoregister key to such agents? Same for environments key?

### Open questions so far, with some answers

1. Who provisions the agent, once the agent machine is provisioned, how is the registration handled. Who manages accounts/ssh keys for machines running elastic agents?

  Ans. Agent provisioning managed by plugin implementations. Registration is managed by the existing `autoregister.properties` mechanism.

2. When an agent boots up and (re-)registers, how does the server tell between an elastic agent (and what kind, ec2 vs docker) and "normal agent". How does a specific plugin know about its agent vs an agent belonging to another plugin?

  Ans. 
  * Based on the conversation here. We felt that the right way to address this issue is to have an additional property (agent.auto.register.plugin.id) in the autoregister.properties. This property SHOULD indicate which particular plugin owns an agent. This will be a runtime property that will NOT be persisted in the <agent/> tag in cruise-config.xml

  * ~~We're going with resources (for now). So if a EC2 plugin is tasked with bring up agents with resources "centos65, ec2, firefox, java" any agents that come up with those **exact** resources will be managed by the ec2 plugin. Plugins will be tasked with ensuring that `autoregister.properties` contain the correct resources.~~

3. Is the `cruise-config.xml` involved every time an agent is spun up and shut down. Who manages the list of agents?
  
  **Proposal**: Yes. Well ideally we could leave all of this for the plugin to figure out, but if the agent is not part of the config, build assignment workflow needs to be changed too to accomodate this - either by letting plugin do that work, or server could ask all the plugins for the available agents all the time. So, for now we think it should be left in the config xml. After the agent-config save optimization(#1655) is merged(and if it really works), it should not be a concern.

4. Should agent machines be shut down, or destroyed altogether? 
  Who decides this action (server or plugin), and based on what?
    Ans. * One option is that the server will notify the plugin every time a job is assigned/completed to an agent and let the plugin keep track of inactive agents for it to decide when it should shut them down. For e.g., in order to optimise costs, plugin implementations could keep track of when instances were booted in order to determine if they should be shut down down, shutting down at the last possible moment (58/59th minute of the hour, perhaps).   
    Since plugins should not be running threads, another alternative is to "ping" the plugin every once in a while to allow it to do any such maintenance tasks.

    **Proposal**: The decision of when and who to kill should be left at the discretion of the plugin. We probably need an easy/reliable way for the plugin to know the current status of an agent. Easy coz our APIs use basic auth which wont work for plugins. There is `GoApplicationAccessor` but we have been talking about key based access for apis, so may be explore that option.
    Also, since the plugin manages the agents now, it should tell Go server when it brings down an agent so we could cleanup entries from config(else a bunch of missing/lost-contact agents show up). Plus the plugin would also need to keep track of agents gone missing, or those that never came up if a plugin creates 100 instances, it's likely that one of them never really "comes up" — and that is something the plugin needs to manage or handle or in cases where an agent goes missing, the plugin would need to terminate it (if that's what it wants to do).
  

6. What happens to the entries in `cruise-config.xml` if there are any? Does the server even care for agents now, if management/assignment is left to the elastic plugin?
  Configurations for plugins
    - minimum number of agents to keep
    - maximum number of agents to spin
    - keep idle agents?
    - how long to keep idle agents?
    - credentials for AWS/openstack etc
    - What else?

    Ans. All of these are plugin specific. The only part Go does is allow configuration to be stored and edited by the user.
    
    **Proposal**: management would now be plugin's headache, so the config mentioned above should basically be "plugin settings". The onus is on plugins to let the server know about agents that it killed so Go could do the required cleanup.

8. How and who manages environment assignment?
  Ans. The plugin manages this in a manner similar to how it manages resource assignment of an agent.

**Comment by ketan** [comment]
### Open questions so far, with some answers

- Who provisions the agent, once the agent machine is provisioned, how is the registration handled. Who manages accounts/ssh keys for machines running elastic agents?

> Agent provisioning managed by plugin implementations. Registration is managed by the existing `autoregister.properties` mechanism.

- When an agent boots up and (re-)registers, how does the server tell between an elastic agent (and what kind, ec2 vs docker) and "normal agent". How does a specific plugin know about its agent vs an agent belonging to another plugin?

> We're going with resources (for now). So if a EC2 plugin is tasked with bring up agents with resources "centos65, ec2, firefox, java" any agents that come up with those **exact** resources will be managed by the ec2 plugin. Plugins will be tasked with ensuring that `autoregister.properties` contain the correct resources.

- Is the `cruise-config.xml` involved every time an agent is spun up and shut down Who manages the list of agents?
- Should agent machines be shut down, or destroyed altogether? Who decides this action, and based on what?
- Does the server even care for agents now, if management/assignment is left to the elastic plugin?
- Configurations for plugins
    - minimum number of agents to keep
    - maximum number of agents to spin
    - keep idle agents?
    - how long to keep idle agents?
    - credentials for AWS/openstack etc
    - What else?
- How and who manages environment assignment?

**Comment by ketan** [comment]
I'm opening this up for discussion. If there are additional questions or thoughts anyone has, please feel free to add a comment, I'll update the original description with relevant information extracted out of the comments.

**Comment by ketan** [comment]
Adding @reidca @sweitzel74 @lruth-daptiv to this conversation since they voted for the feature on #1076

**Comment by arvindsv** [comment]
> We're going with resources (for now). So if a EC2 plugin is tasked with bring up agents with resources "centos65, ec2, firefox, java" any agents that come up with those exact resources will be managed by the ec2 plugin. Plugins will be tasked with ensuring that autoregister.properties contain the correct resources.

I feel that forcing those *exact* resources is too restrictive. The way I think about it: If the plugin claims to handle "ec2, java" as resources, then any agent with those two resources (among others) will be considered fair game. We can also consider whether forcing plugin ID to be one of the resources makes sense.

> Is the cruise-config.xml involved every time an agent is spun up and shut down. Who manages the list of agents? What happens to the entries in cruise-config.xml if there are any?

I think the config file should be used the same way as it is used today. We might need to consider some way for the plugin to mark some of its plugins as unused? Maybe as a response to the "ping"?

> Does the server even care for agents now, if management/assignment is left to the elastic plugin?

Cares, in what sense? It still needs to handle registration and communication and everything else.

> Configurations for plugins
> ... credentials for AWS/openstack etc ...

All of these are plugin specific. The only part Go does is allow configuration to be stored and edited by the user.

> How and who manages environment assignment?

Can't that happen during auto registration? I wonder how the user provides input to this process. However, that is up to the plugin again, to get those settings from the user and setup the right auto registration properties, right?

**Comment by matt-richardson** [comment]
>We're going with resources (for now). So if a EC2 plugin is tasked with bring up agents with resources "centos65, ec2, firefox, java" any agents that come up with those exact resources will be managed by the ec2 plugin. Plugins will be tasked with ensuring that autoregister.properties contain the correct resources.

This would mean that you cant have burst agents (ie, 2 normal agents, but add additional cloud agents). I think that this is overloading the meaning of resources in a bad way.

Maybe having a resource specifying "ec2-agent" (or whatever the name of the cloud plugin) would work better?

**Comment by ketan** [comment]
>> We're going with resources (for now). So if a EC2 plugin is tasked with bring up agents with resources "centos65, ec2, firefox, java" any agents that come up with those exact resources will be managed by the ec2 plugin. Plugins will be tasked with ensuring that autoregister.properties contain the correct resources.
>
> This would mean that you cant have burst agents (ie, 2 normal agents, but add additional cloud agents). I think that this is overloading the meaning of resources in a bad way.
> 
> Maybe having a resource specifying "ec2-agent" (or whatever the name of the cloud plugin) would work better?

Based on the conversation [here](https://gitter.im/gocd/gocd?at=559be4b15331f9985a7fc041). We felt that the right way to address this issue is to have an additional property (`agent.auto.register.plugin.id`) in the [`autoregister.properties`](http://www.go.cd/documentation/user/current/advanced_usage/agent_auto_register.html). This property SHOULD indicate which particular plugin owns an agent. This will be a runtime property that will NOT be persisted in the `<agent/>` tag in `cruise-config.xml`

/cc @arvindsv

**Comment by srinivasupadhya** [comment]
> This will be a runtime property that will NOT be persisted in the <agent/> tag in cruise-config.xml

If its not persisted then on server restart causing agent restart (server upgrade/plugin add/update/remove) the data is lost.

**Comment by arvindsv** [comment]
> If its not persisted then on server restart causing agent restart (server upgrade/plugin add/update/remove) the data is lost.

The data is lost, but the agent auto-register will happen again, right?

**Comment by kcormier** [comment]
@ketan Is this work complete/stable enough to start testing?  We are quite interested in this functionality and would be happy to evaluate & provide some testing & feedback if you can point us in the right direction for that.

**Comment by ketan** [comment]
@kcormier — yes this work is stable enough to start testing, there are a few edge cases that we need to start addressing. These are edge cases on the go end of things, not that of the plugin. In terms of the server-plugin communication protocol, that is mostly close to what we want, so we don't expect too many changes there.

You can find a sample docker plugin at https://github.com/gocd-contrib/docker-elastic-agents

**Comment by KJTsanaktsidis** [comment]
Is this plugin API in the 16.5 release? I'm looking at moving our CI stuff to GoCD but this is a pretty important feature for us. If the plugin API is shipped I'll probably look at forking the docker-elastic-agents plugin and hacking it into something that fits our needs. I guess if I build anything useful I'll share it back too.

**Comment by arvindsv** [comment]
Not yet. It's coming soon. Needs a bit more breathing room to finish it off (or at least get it in a state for people to try).

@ashwanthkumar was [trying out something related](https://github.com/ind9/vasuki), without using this endpoint. In case it helps you not redo work.

**Comment by EugenMayer** [comment]
awesome!
