### ISSUE TITLE
Associating pipeline(s) which is already part of GLOBAL environment

### ISSUE THREAD

**Issue by agileturret** [gocd/gocd#10841]
##### Issue Type

- Feature enhancement

##### Summary

Associating pipeline(s) which is already part of GLOBAL environment, yup cant add multiple pipelines to a common GLOBAL env vars.

##### Environment

GoCD K8S

##### Steps to Reproduce

1. Set pipelineA to use environment GLOBAL 
2. Set pipelineB to use environment GLOBAL
3. Boom!
4. 

##### Expected Results

Should be able to share environments across pipelines.

##### Actual Results

Exception: Associating pipeline(s) which is already part of GLOBAL environment

**Comment by chadlwilson** [comment]
Sorry, I'm not sure what you are describing or asking for here. You've marked it as enhancement but you seem to be describing a bug? Multiple pipelines can definitely refer to the same environment and inherit environment vars.

Can you please describe the problem more fully and include a fuller description of what you tried, where the error appeared, what happened with screenshots and where these pipelines are defined (config repos? In UI? Same config repo? Different?)

**Comment by arvindsv** [comment]
Agree. The report can be (much) better.

Trying to read between the lines, it seems like this could be about being able to associate a single pipeline, with multiple environments, which [isn't possible](https://docs.gocd.org/current/introduction/concepts_in_go.html#environment).

**Comment by chadlwilson** [comment]
Let us know if you're able to supply more detail here and we can reopen.
