### ISSUE TITLE
Auto registration of  gocd/gocd-agent-docker-dind:v22.2.0 agent failing to connect to v22.2.0 server.

### ISSUE THREAD

**Issue by gregoryfischer** [gocd/gocd#10844]
##### Issue Type

- Bug Report

##### Summary

We have been using goad-server v19.12 with the ubuntu agents of the same version with great success for sometime now but we want to upgrade to v22.2.0 for both the server as well as switch to the 

However, we first need to get everything working locally before we can rollout but I can not get the DIND agents (gocd/gocd-agent-docker-dind:v22.2.0) to connect to the the server both running locally on my development machine. Here are the agent logs which loop every min trying to connect.

##### Environment
macOS Monterey version 12.6
2.6 GHz 6-Core Intel Core i7
16 GB 2400 MHz DDR4
Radeon Pro 560X 4 GB
Docker Desktop 4.12.0 (85629) is currently the newest version available.

###### Basic environment details

See above.

###### Additional Environment Details

na

##### Steps to Reproduce

1. docker run -d -p8153:8153 gocd/gocd-server:v22.2.0
2. when the server completes boot up grab the agentAutoRegisterKey value from the config.xml
3. create a new STAGE environment using the new server UI
4. docker run --privileged -d -e GO_SERVER_URL=http://gocd-server:8153/go -e AGENT_AUTO_REGISTER_KEY=`your-key-here` -e AGENT_AUTO_REGISTER_ENVIRONMENTS=STAGE -e AGENT_BOOTSTRAPPER_ARGS='-sslVerificationMode NONE' gocd/gocd-agent-docker-dind:v22.2.0

##### Expected Results
Agent auto-registers with the server and is automatically associated with running STAGE assigned pipelines.

##### Actual Results
See error output below: the server comes up fine but the agent never successfully connects to the server.

##### Possible Fix
unknown

##### Log snippets
```
jvm 1    | WrapperManager: Initializing...
jvm 1    | [Tue Sep 20 18:01:32 GMT 2022] Starting process: 
jvm 1    | [Tue Sep 20 18:01:32 GMT 2022]   Working directory    : /go
jvm 1    | [Tue Sep 20 18:01:32 GMT 2022]   Application arguments: [-serverUrl, http://gocd-server:8153/go, -sslVerificationMode, NONE]
jvm 1    | [Tue Sep 20 18:01:32 GMT 2022]            GoCD Version: 22.2.0-14697
jvm 1    | [Tue Sep 20 18:01:32 GMT 2022]            Java Version: 17.0.4
jvm 1    | [Tue Sep 20 18:01:32 GMT 2022]        Operating System: Linux(5.10.124-linuxkit)
jvm 1    | Could not find file `config/agent-bootstrapper-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:onejar:lib/agent-bootstrapper-22.2.0-14697-classes.jar!/config/agent-bootstrapper-logback.xml'.
jvm 1    | 2022-09-20 18:01:32,955 INFO  [WrapperJarAppMain] DefaultAgentLauncherCreatorImpl:67 - Attempting to load com.thoughtworks.go.agent.launcher.AgentLauncherImpl as specified by manifest key Go-Agent-Launcher-Class
jvm 1    | 2022-09-20 18:01:33,020 INFO  [WrapperJarAppMain] ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLauncher using java.net.URLClassLoader
jvm 1    | SLF4J: Class path contains multiple SLF4J bindings.
jvm 1    | SLF4J: Found binding in [jar:onejar:lib/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: Found binding in [jar:file:/go/data/deps-86eb52a0fa7d4552-agent-launcher.jar/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
jvm 1    | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
jvm 1    | 2022-09-20 18:01:33,053 INFO  [WrapperJarAppMain] AgentBootstrapper:74 - Attempting create and start launcher...
jvm 1    | 2022-09-20 18:01:33,059 INFO  [WrapperJarAppMain] ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLaunchDescriptor using java.net.URLClassLoader
jvm 1    | Could not find file `config/agent-launcher-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:file:/go/data/deps-86eb52a0fa7d4552-agent-launcher.jar/agent-launcher-22.2.0-14697-classes.jar!/config/agent-launcher-logback.xml'.
jvm 1    | 2022-09-20 18:01:33,137 INFO  [TouchLoopThread-1] Lockfile:103 - Using lock file: /go/.agent-bootstrapper.running
jvm 1    | 2022-09-20 18:01:33,639 ERROR [WrapperJarAppMain] ServerBinaryDownloader:88 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error: 
jvm 1    | org.apache.http.conn.HttpHostConnectException: Connect to gocd-server:8153 [gocd-server/127.0.0.1] failed: Connection refused
jvm 1    | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
jvm 1    | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
jvm 1    | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
jvm 1    | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
jvm 1    | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
jvm 1    | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
jvm 1    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
```

##### Code snippets/Screenshots
na

##### Any other info
na

**Comment by chadlwilson** [comment]
Thanks for the details. I think this is possibly due to misunderstanding of how docker networking works.

Containers brought up like this cannot see each other via DNS (`gocd-server`). They'd need to be a on the same user defined [docker bridge network](https://docs.docker.com/network/bridge/) to do that, like how `docker-compose` works.

Since you are already exposing your server outside docker on port `8153`, easiest alternative on MacOS is instead to use `-e GO_SERVER_URL=http://host.docker.internal:8153/go` in your agent so it goes outside docker to your MacOS host and then back-in to connect.

Either that or create a network, add both containers to it and yada yada - or switch to docker-compose to make it easier to bring the containers up together on the same network with DNS etc, similar to https://github.com/TWChennai/gocd-git-path-material-plugin/blob/master/docker-compose.yml

**Comment by gregoryfischer** [comment]
Thank you @chadlwilson that works. I don't recall this being an issue with v19.12 but it has been a couple years so I may well have been testing as a compose stack back then.
