### ISSUE TITLE
Support for Java 8

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1086]
Public [http://www.oracle.com/technetwork/java/eol-135779.html#Java6-end-public-updates](updates) for JDK 7 ends April 2015.

We need to start supporting Go on JDK 8

**Comment by zabil** [comment]
We'll have to support both JDK7 and JDK8 for a few releases because our agents are run on a global JDK setup.

On the long run @ketan suggested we decouple our server or agents from running on a global JDK. With java 8 they've introduced [profiles](https://blogs.oracle.com/jtc/entry/a_first_look_at_compact) maybe try them out?

**Comment by ketan** [comment]
There is another alternative in that we force a dependency on the system provided jdk8 (`java-1.8.0-openjdk` on centos) ubuntu still hasn't sorted its openjdk8 story yet, so I'm not sure what the solution there is (short of using `ppa:openjdk-r/ppa`)

**Comment by zabil** [comment]
Strategy to be adopted
develop on Java 8 and cross compile to Java 7

```
-source 1.7 -target 1.7
```

Problems so far #1248

**Comment by zabil** [comment]
Agents on build.go.cd keep running out of memory on JDK8
I suspect changes how the permgen is handled
https://dzone.com/articles/java-8-permgen-metaspace

This means we'll have to set an alternate flag to control the native space usage. Moving this to next release as it requires further testing.

**Comment by zabil** [comment]
Fixed with https://github.com/gocd/gocd/commit/f768e5d7891720dafe6bd9f419ffaf28503e2e64
