### ISSUE TITLE
Default to Jetty 9

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1087]
Go 15.1 comes bundled and experimental version of jetty9 with performance issues. Fix those issues and switch to running on Jetty 9 by default.

**Comment by ketan** [comment]
Is there something specific that needs to be tested with jetty9 once installers are out?

**Comment by zabil** [comment]
Verified on experimental release15.2.0-2237 (2fd095a561193826f445f9627cf6861c8983f0dc)
