### ISSUE TITLE
Can't disable autoupdate of a git material

### ISSUE THREAD

**Issue by asavchkov** [gocd/gocd#10898]
##### Issue Type
- Bug Report

##### Summary
Disabling of repository polling through the UI has no effect

##### Environment
Self-hosted GoCD

###### Basic environment details
* Go Version: GoCD Version: 22.2.0 (14697-4bdda4e0d769e66da651926c7066979740bd7ae7).
* JAVA Version: JVM version: 17.0.4
* OS: Linux 5.15.0-47-generic

##### Steps to Reproduce
1. Set `autoUpdate = false` of a git material like this (Groovy configuration plugin)
```
      materials {
        git('myrepo') {
          url = 'git@our.git.url:group/subgroup/myrepo.git'
          branch = 'main'
          autoUpdate = false
        }
```
2. In the UI on the **Config Repositories** page set **Repository polling behavior**: **Fetch updates to this repository only on webhook or manual trigger** and save.

##### Expected Results
The repository configuration is successfully applied

##### Actual Results
The repository configuration UI outputs an error
```
INVALID MERGED CONFIGURATION
Number of errors: 4+
1. The material of type Git (git@our.git.url:group/subgroup/myrepo.git) is used elsewhere with a different value for autoUpdate (&quot;Poll for changes&quot;). All copies of this material must have the same autoUpdate setting or configuration repository must be removed.
 Config Repository: myrepo-config-id (auto update enabled).
 Pipelines: My-pipeline (auto update disabled);; 
```
Other of 4+ errors all refer to the same reason.
Looks like the UI part of the configuration is not changed despite the option to switch off auto-updating is selected.

##### Any other info
Ideally I would like to control this option from a single place - either from the UI or from the config repository file.

**Comment by asavchkov** [comment]
I seem to have understood my situation. My config repository file is in the same repository as the main source code. So the Config Repository part of GoCD has its polling enabled while the Pipeline part has not, and as they both refer to the same repository/branch this is where a conflict occurs. Something related to https://github.com/gocd/gocd/issues/10560 perhaps.
Closing this for the moment to rethink how to deal with this. It would be a pity however if it was impossible to keep the pipeline configuration together with the source code.

**Comment by chadlwilson** [comment]
You also might want to note the shorthand syntax here for referring to the same repo that a config material is defined in within the YAML to avoid having to repeat oneself: https://github.com/tomzo/gocd-yaml-config-plugin#configrepo
