### ISSUE TITLE
Build ids are truncated in pipeline activity page

### ISSUE THREAD

**Issue by jales-els** [gocd/gocd#10891]
##### Issue Type

- Bug Report

##### Summary

Build ids are truncated when over 17 characters on the pipeline activity page.

Build id on VSM page: 
![image](https://user-images.githubusercontent.com/63352676/193848998-e12eaeea-4ca0-41b5-8170-47051e672e70.png)

Build id on pipeline activity page:
![image](https://user-images.githubusercontent.com/63352676/193849603-929ae15e-99ea-4694-b07b-74bbf30dbe24.png)

###### Basic environment details

* Go Version: `21.4.0 (13469-f3b865c5018dec2bddf98496e0e74e8e70a80cb6)`
* JAVA Version: `15.0.2`
* OS: `amzn2`

##### Steps to Reproduce

1.  Have a build id over 17 characters 
2. Navigate to the pipeline activity page

##### Expected Results

The full build id should be present

##### Actual Results

Only the first 17 characters of the build id are shown 

##### Possible Fix

Code here is hcanged 
https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/pipeline_run_info_widget.tsx#L83

**Comment by chadlwilson** [comment]
Thanks for the sleuthing. Now I am wondering why such specific code was written to do the `substr` here...
