### ISSUE TITLE
Better support for Tests

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#1096]
The biggest time consumer in any CI/CD setup is running tests. It has become fundamental practice to write tests and every new framework supports writing & running tests first. Which means there are more tests to run & make sense of the results. We want to provide features to ease the pain.
- Parallelization - out of box support for TLB? custom runner for each type (junit, rspec etc.) which contacts Go server asking for next test to run? - Go supports '[run X instance](http://www.go.cd/2014/10/09/Distrubuted-Test-Execution.html)' of a job which could be used to distribute tests using TLB. Need to add first class support for test distribution.
- Intelligent test runs - Run tests in failed first order, Re-run failed tests etc.
- Real time reports - how many ran, how many failed & which ones failed - while the job is running
- Parse test reports - provide pluggability for all kinds of test reports/migrators for other test report formats. Currently only XUnit format is supported. - Something on the lines of [xunit-converter](https://github.com/srinivasupadhya/xunit-converter-task)?
- Test metrics - possibly list flaky tests, show time consuming tests etc.

**Comment by srinivasupadhya** [comment]
This is a placeholder issue. We will split this into separate issues later.

**Comment by RehanSaeed** [comment]
+1 for xUnit support.

**Comment by cfriedt** [comment]
Definitely needs better unit test reporting!
