### ISSUE TITLE
Dashboard Revamp/Rewrite

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#1097]
People spend most of their time on Go on dashboard page. With the number of pipelines & users increasing, the dashboard page needs to be optimized for performance, while giving as much info as possible in the best possible way for its consumption.
- Rewrite dashboard to hit API instead of getting the whole markup.
- Move some logic to client side to reduce load on server. more intelligent updates rather than full update?
- UX improvements

**Comment by arvindsv** [comment]
Closing in favor of #1841.
