### ISSUE TITLE
Agent Management

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#1099]
In a CI/CD setup agent management is the hardest part. Remembering what is installed on what agent, knowing when an agent goes down, accessing agent machine to do some changes are a few things that would like to give first class support for.
- Notification of status when a new agent is available (pending) or goes missing - the [notification end-point](http://www.go.cd/documentation/developer/writing_go_plugins/notification/notification_plugin_overview.html) is available. Need to add "agent status change" notification to it.
- Capabilities / Resource (add, edit, remove) - detect software available on agent along with versions & auto update resources of agent
- Key management - manage ssh keys
- Console - to make changes on agent without having to ssh to the agent

**Comment by lenucksi** [comment]
#1236 seems to be a possible application of this extension to the notification endpoint.
