### ISSUE TITLE
Missing error description when creating a new task

### ISSUE THREAD

**Issue by go-thoughtworks** [gocd/gocd#11]
We were creating a new pipeline.  In step 3, we were prompted for "Initial Job and Task."  We specified an absolute working directory (any directory starting with /).  When we clicked "Finish" we see the error "! Save failed, see errors below".  However, no errors were displayed and no form fields were highlighted.

We eventually found that changing the working directory to a relative one corrects the error.

**Comment by JonasGroeger** [comment]
This is also happening in 14.3.0(1186-65818fec82f654). Workaround for me: Remove all # in command arguments, like @danieljwest said.

**Comment by arvindsv** [comment]
Probably related to [this](https://github.com/gocd/gocd/issues/854). I'm closing this one as a duplicate. If you think it's not, let me know. Happy to reopen it.

**Comment by arvindsv** [comment]
Reopening. This is about the error message. That's about the actual issue.

**Comment by arvindsv** [comment]
@maheshp @varshavaradarajan: This should get closed, when we move to the new config UI.

**Comment by varshavaradarajan** [comment]
Well, shows the error when creating a new pipeline if the working directory of the task is outside the sandbox.
