### ISSUE TITLE
[RFC] - API improvements and guidelines

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1100]
This RFC is to gather feedback on fixing some of the inconsistencies with existing APIs (see #572) and establish guidelines for new APIs going forward. A lot of this is inspired from GitHub's APIs described at https://developer.github.com/v3/ with a combination of JSON HAL spec described at http://stateless.co/hal_specification.html.

API Endpoint
============

All APIs will be accessed from `https://go-server-url:8154/go/api`. All data will be sent and recieved as JSON. You may access the APIs over plain text, but for security reasons we suggest that users use SSL.

Authentication
==============

All APIs require you to authenticate yourself using your username and password. A cookie will also be returned as a result of the first authentication call. You may use this cookie for any further authentication attempts. If authentication fails, Go will return status `401`, `403` or `404`.

Basic authentication
--------------------

**Example:**

``` bash
curl -u 'username:password' -H 'Accept: application/vnd.go.cd.v1+json' https://build.example.com/go/api
```

**Response:**

```
HTTP/1.1 200 OK
Content-Type: application/vnd.go.cd.v1+json; charset=utf-8
Set-Cookie: JSESSIONID=JDQz5YSF6W4LzG9JuqPC7g;Path=/go;Expires=Tue, 19-May-2015 09:41:09 GMT
```

```json
{
  "pipelines_url": "https://build.example.com/api/pipelines",
  "users_url": "https://build.example.com/api/users",
}
```

Cookie/Session authentication
-----------------------------

Using the cookie/session returned from the previous API call, one can make further API calls. Using a cookie will dramatically improve performance of API calls especially if go is authenticating against an external source like LDAP.

``` bash
curl --cookie 'JSESSIONID=JDQz5YSF6W4LzG9JuqPC7g' -H 'Accept: application/vnd.go.cd.v1+json' https://build.example.com/go/api
```

**Response:**

```
HTTP/1.1 200 OK
Content-Type: application/vnd.go.cd.v1+json; charset=utf-8
Set-Cookie: session_id=some-session-id
```

```json
{
  "pipelines_url": "https://build.example.com/api/pipelines",
  "users_url": "https://build.example.com/api/users",
}
```

Versioning
==========

By default, all requests receive the **v1** version of the API. It is recommended to explicitly request this version via the `Accept` header.

```
Accept: application/vnd.go.cd.v1+json
```

If you specify an unsupported, `Accept` header, Go will respond with the current default JSON representation of the resource.

Response body
=============

The on successful responses (status 2XX), the response body will consist of 2 json objects `links` and the `_embedded` object/resource being rendered. Embedded resources may be rendered partially and can point to other URLs to get more information about those resources.

```json
{
  "_links": {
    "self": {
      "href": "https://build.example.com/go/api/pipelines/MyPipeline/10/RunTests"
    },
    "next": {
      "href": "https://build.example.com/go/api/pipelines/MyPipeline/11/RunTests"
    },
    "latest": {
      "href": "https://build.example.com/go/api/pipelines/MyPipeline/latest/RunTests"
    },
    "oldest": {
      "href": "https://build.example.com/go/api/pipelines/MyPipeline/1/RunTests"
    }
  },
  "_embedded": {
    "stage": {
      "name": "RunTests",
      "result": "failed",
      "total-time": "123.45",
      "jobs": [
        {
          "_links": {
            "self": "https://build.example.com/go/api/pipelines/MyPipeline/10/RSpec"
          },
          "name": "RSpec",
          "result": "passed",
          ...
        },
        {
          "_links": {
            "self": "https://build.example.com/go/api/pipelines/MyPipeline/10/Jasmine"
          },
          "name": "Jasmine",
          "result": "failed",
          ...
        }
      ]
    }
  }

}
```

Pagination
==========

Requests that return multiple results will be paginated to 25 items by default. The `next` and `previous` page links, if applicable will be included in the response body in the `_links` section.

**Example:**

``` bash
curl -u 'username:password' -H 'Accept: application/vnd.go.cd.v1+json' https://build.example.com/go/api/pipelines/MyPipeline
```

**Response:**

```
HTTP/1.1 200 OK
Content-Type: application/vnd.go.cd.v1+json; charset=utf-8
Set-Cookie: session_id=some-session-id
```

```json
{
  "_links": {
    "self": {
      "href": "https://build.example.com/go/api/pipelines/MyPipeline?less_than_counter=29"
    },
    "next": {
      "href": "https://build.example.com/go/api/pipelines/MyPipeline?more_than_counter=28"
    },
    "latest": {
      "href": "https://build.example.com/go/api/pipelines/MyPipeline"
    },
    "oldest": {
      "href": "https://build.example.com/go/api/pipelines/MyPipeline?less_than_counter=26"
    }
  },
  "_embedded": {
    "pipelines": [
    ]
  }

}
```

**Comment by arvindsv** [comment]
I've been keeping an eye out on http://jsonapi.org/. How about using that or contributing to that discussion, so that we don't have yet another standard? Parts of it will be similar, I'm sure.

**Comment by ketan** [comment]
@arvindsv - unfortunately (unlike JSON JAL), it's still a WIP. Tooling and programming language support is also lacking.

**Comment by ranjib** [comment]
api version should be part of the url. `http://go.example.com/api/v1`
for pagination support, having count of total entries will also help. what about having `begin` or `start` field instead of self, for paged responses

**Comment by ketan** [comment]
> api version should be part of the url. http://go.example.com/api/v1

This [SO post](http://stackoverflow.com/a/398564) explains my reasoning very well. The tl;dr; version is that *every resource should be represented by a unique URI. Resource URIs that API users can depend on should be permalinks.*

> for pagination support, having count of total entries will also help.

I'm a bit torn on this - it makes sense when listing the head page (latest), the number of items can change as you are flipping through the pages.

What was your motivation to suggest this, is this for informational purposes or something else (like to figure out when you're on the last page?)

> what about having begin or start field instead of self, for paged responses

What's the motivation about `begin` or `start` - is this synonymous with `latest` and `newest` in the proposal, or are you suggesting something else?

**Comment by arvindsv** [comment]
About auth, I think it would be good to have a (controlled) API key based auth. The other parts I'm ok with. Still thinking about the embedded bit. Grappling with whether I think it is too heavy. I understand the need. Thinking.

**Comment by arvindsv** [comment]
Ok, I can make my peace with it.

**Comment by zabil** [comment]
Should be capture etags and support for conflicts (PUT)
http://fideloper.com/etags-and-optimistic-concurrency-control

**Comment by zabil** [comment]
#1205 
#1364
