### ISSUE TITLE
Locked pipeline cannot be unlocked

### ISSUE THREAD

**Issue by lmachacek** [gocd/gocd#11016]
##### Issue Type

- Bug Report

##### Summary

We have a pipeline for smoke test running each ten minutes. It has been OK for ages but today this pipeline was cancelled by GoCD itself because of:
```
    Go cancelled this job as it has not been assigned an agent for more than 5 minute(s)
```
And GoCD locked the pipeline.

But now we are not able to unlock it, because GoCD shows:
```
Locked pipeline instance is currently running (one of the stages is in progress)
```

When I try the same SELECT as GoCD does, then I can see, that stages state is **Cancelled** in the DB, but even though GoCD tells me that one stage is in progress:

```sql
gocd=> SELECT builds.stageId, stages.cancelledBy, stages.result as stageResult, stages.state as stageState
        FROM stages
        INNER JOIN pipelines ON pipelines.id = stages.pipelineId
        INNER JOIN builds ON stages.id = builds.stageId AND builds.ignored != true
        LEFT JOIN buildstatetransitions ON builds.id = buildstatetransitions.buildId
WHERE pipelines.name = 'DEV-smoke-tests-gateway'
        AND pipelines.counter = 135348
        ORDER BY stageId DESC;

 stageid | cancelledby | stageresult | stagestate 
---------+-------------+-------------+------------
 4068349 |             | Cancelled   | Cancelled
 4068349 |             | Cancelled   | Cancelled
(2 rows)

```

After looking into GoCD source code, I think that the problem is in an inconsistency between DB and cache.
Stages are cached on this line https://github.com/gocd/gocd/blob/cc84e2045638e8afca741a016f4c02e727efe807/server/src/main/java/com/thoughtworks/go/server/dao/StageSqlMapDao.java#L765 It is called from this method https://github.com/gocd/gocd/blob/cc84e2045638e8afca741a016f4c02e727efe807/server/src/main/java/com/thoughtworks/go/server/service/StageService.java#L561 which is used in `PipelineUnlockApiService.isUnlockable()`.

And now I cannot see any other way how to invalidate the cache than restarting of GoCD.

I tried to cancel the stage again by API but it failed with _Stage is not active. Cancellation Ignored._ message

I tried also to unlock the pipeline directly in the DB in `pipelinestates` table but GoCD still shows that the pipeline is locked. That info is probably also taken from the cache.

##### Basic environment details

* Go Version: `22.2.0 (14697-4bdda4e0d769e66da651926c7066979740bd7ae7)`
* JAVA Version: `17.0.4`
* OS: `Linux 5.4.209-116.367.amzn2.x86_64`

##### Steps to Reproduce

I wasn't able to reproduce it again. There must be probably a proper interplay of events.

##### Expected Results

It is possible to unlock the pipeline when all stages are in state **Cancelled** in DB.

##### Actual Results

It is not possible to unlock the pipeline when all stages are in state **Cancelled** (at least their state is Cancelled in DB).

##### Possible Fix

It would be nice to have a possibility to invalidate the cache other way then by restarting of GoCD.

**Comment by chadlwilson** [comment]
Thanks for the report and the digging.

I guess to resolve this properly we'd have to figure out the race condition/sequence of events that allowed the cache to be able to get into an inconsistent state and the pipeline to be locked (or do you have "lock on failure" enabled for the pipeline?)

Is your suspicion that it's something specific to when GoCD itself cancels a pipeline job for agent assignment? Did you try replicating specifically for the inactivity case, or only with other perhaps manually cancelled jobs?

**Comment by lmachacek** [comment]
Pipeline lock behavior is set on "Run single instance of pipeline at a time".
It failed to assign the agent twice in a row and then it locked up.

I'm guessing it's because it got locked by GoCD. We cancel jobs time to time and so far nothing like that has happened.

I'll try to block the agent assignment during the weekend and test this specific case again for longer time. It's hard to do it during the working week as these experiments can block work of other teams.

**Comment by lmachacek** [comment]
Probably I found the reason how the inconsistency happened.

We run GoCD in EKS cluster and have only one replica. Even today I noticed that the GoCD server pod was restarted around the time when the pipeline was cancelled for the first time. And also console output of the pipeline looks weird:
![obrazek](https://user-images.githubusercontent.com/92144628/202727765-1aee5ebf-4c60-40c3-b788-65ac7811bbab.png)

First request is at 7:30 to create agent pod and the job would be successful, but instead of `[go] Current job status: passed` there is another request to create pod at 7:38.

**Comment by chadlwilson** [comment]
Putting aside whether something could be done about things to avoid it getting into a weird state, there are likely many things that can probably get into a bad state if your server has an uncontrolled restart under load. Which obviously is a risk when running any software, but especially as a container within a cluster, and made worse by stateful software like GoCD where you cannot run multiple replicas.

You're probably best to focus on why the server was restarted, and whether that was due to something within your control (memory issues, health check failure etc) to minimise any uncontrolled restarts.

As to the pipeline It's a bit tough for me to put together the sequence of actions from the above without a specific timeline of when things happened, since I cannot see your server logs and a lot of the above events are collapsed so hard to tell what happened. Need to know when did each thing happen (When did the server get stopped. What time did it successfully restart etc. What exactly did the server think the agent was doing at the time it got restarted, when did the agent finish etc) to narrow down how it got locked but not unlocked.

**Comment by lmachacek** [comment]
Yes, I understand, it's easy to get into weird state in stateful application in K8s.

We normally set GoCD into Maintenance mode before any planned restart (upgrade or configuration changes) but in this case it was unplanned restart of one EKS node where GoCD pod lived and was rescheduled on another node and that means stop and start of another instance elsewhere.

As for the locking, we use `lock_behavior: unlockWhenFinished`, so GoCD locks pipeline at the beginning but when the agent is not available for longer time it cancels the pipeline like this:
```
Go cancelled this job as it has not been assigned an agent for more than 5 minute(s)
```
... and does not unlock, so it remains locked. Normally it is possible to unlock.

Now it would be hard to find out how that inconsistency happened. So, we can close this ticket for now and if it ever happens again, I'll hopefully capture it earlier and it will be easier to find more information for further analysis.

**Comment by chadlwilson** [comment]
Thanks, understood.

It's still be helpful if you are able to construct a rough timeline from your logs of what happened last time. The logs of the server (to know when it died and then started again, as well as the job logs for the pipeline (initial start time, does it look like it got re-scheduled on start) that ended up stuck would allow this - even if we're not sure exactly when the pipeline got locked and which bit failed to unlock it.
