### ISSUE TITLE
Server randomly crashes with fatal JVM error(using jdk 1.8.0_31-b13)

### ISSUE THREAD

**Issue by ckarthik17** [gocd/gocd#1103]
Go server crashes randomly with the below errror

Go server version : 15.1
JDK : 1.8.0_31-b13
OS : Ubuntu 14.04

Head of the error below (Let me know if you need more information)

```#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f14b3dba4b1, pid=17247, tid=139726829995776
#
# JRE version: Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x3e94b1]  CallGenerator::for_method_handle_inline(JVMState*, ciMethod*, ciMethod*, bool&)+0x591
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread (0x00007f14ac12e800):  JavaThread "C2 CompilerThread0" daemon [_thread_in_native, id=17256, stack(0x00007f14b0014000,0x00007f14b0115000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000
```

**Comment by ketan** [comment]
Would you mind enabling core dumps by adding `ulimit -c unlimited` to `/etc/defaults/go-server`

Also can you provide us the contents of `https://build.go.cd/go/api/support`

**Comment by andreitognolo** [comment]
I had the same problem.

Go server version: 15.1.0(1863-42e58c22aefd03)
JDK: 1.8.0_31-b13
OS: CentOS release 6.6 (Final)

[Here](https://gist.github.com/andreitognolo/b584c0218fa6d2a7bacc) is the content of `https://build.go.cd/go/api/support`

I've enabled the `ulimit -c unlimited` and will get back to you if it happens again.

**Comment by ketan** [comment]
Oh Snap!

Andrei, thanks a lot. We look forward to the core dumps!

**Comment by ketan** [comment]
Hey @andreitognolo -

Did you happen to see a crash since our last communication?

Thanks.

**Comment by andreitognolo** [comment]
Hey @ketan 

No, I didn't.

**Comment by jyotisingh** [comment]
Test this with #1086

**Comment by arvindsv** [comment]
Closing till this happens again. Feel free to reopen.
