### ISSUE TITLE
Better support for Materials

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#1105]
Go should improve integration with materials (SCM/Package Repository/Pipeline).

* Provide `materials` view where user can see list of materials -> click on one of the materials provides list of `modifications` (with pagination) -> click on one of the modifications provides list of `modified files` (with pagination) -> click on the modified file show `changes` to the file in that modification

**Comment by srinivasupadhya** [comment]
#1145 can be done as part of this

**Comment by arvindsv** [comment]
Closing as a duplicate of #1545.
