### ISSUE TITLE
XSS vulnerability on user settings page

### ISSUE THREAD

**Issue by orfjackal** [gocd/gocd#1109]
Go Version: 15.1.0(1863-42e58c22aefd03)

### Steps to reproduce:

1. Go to user preferences
2. Edit email settings
3. Insert `<style>* { background-color: red; }</style>` to "My check-in aliases"
4. Save

### Expected result:

The code shows up in the UI as plain text, without changing the site's style.

### Actual result:

The page becomes red.

**Comment by arvindsv** [comment]
Thank you! I've put in a fix. Will monitor, verify and then close this.

**Comment by zabil** [comment]
Verified on 15.2.0-2022 (b1cad1dbd4794401c566acc3aa01a933daeb7c43)
