### ISSUE TITLE
The "Get pipeline instance" API request returns an undocumented stage status

### ISSUE THREAD

**Issue by asavchkov** [gocd/gocd#11170]
##### Issue Type
- Bug Report

##### Summary

According to [the documentation](https://api.gocd.org/current/#get-pipeline-instance) of the "Get pipeline instance" API request the `stages[N].status` field should return the state of the stage, e.g. "Completed". Currently it simply echoes the `result` field:
```
  "stages" : [ {
    "result" : "Passed",
    "status" : "Passed",
    ...
  }, {
    "result" : "Failed",
    "status" : "Failed",
```
Looks like a bug to me or at least it seems to disagree with the documentation.

###### Basic environment details
* Go Version: 22.3.0 (15301)
* JAVA Version: 17.0.5
* OS: Linux 5.15.0-56-generic

**Comment by chadlwilson** [comment]
Thanks for raising. I believe this is a documentation issue. Stage results and statuses are similar but modelling is distinct.

https://github.com/gocd/gocd/blob/0f58107c851cf2df6ce7c6902eebde796dc1f742/domain/src/main/java/com/thoughtworks/go/domain/StageState.java#L20-L26

I believe they will only be different in the case that the stage is building, and hasn't been previously built, in which case its `status=Building`, `result=Unknown`.

Jobs have a status of `Completed` but not Stages, as far as I can tell.

There is some logic on Stages to render `Completed` for `Passed|Failed|Cancelled` but seems it is only used by some [XML-based feed APIs](https://api.gocd.org/current/#feeds), which I have no personal knowledge/awareness of.  :) It's possible these are essentially legacy APIs.

https://github.com/gocd/gocd/blob/0f58107c851cf2df6ce7c6902eebde796dc1f742/domain/src/main/java/com/thoughtworks/go/domain/StageState.java#L113-L115
https://github.com/gocd/gocd/blob/0f58107c851cf2df6ce7c6902eebde796dc1f742/domain/src/main/java/com/thoughtworks/go/domain/StageState.java#L34-L36
