### ISSUE TITLE
Can't Edit Pipeline in Firefox

### ISSUE THREAD

**Issue by davidvedvick** [gocd/gocd#11179]
##### Issue Type

Bug Report

##### Summary

Updating a pipeline in Firefox gives the following error:

> Someone has modified the configuration for pipeline 'nsfn-deploy'. Please update your copy of the config with the changes and try again.

Works in Chromium. In my research I came across #8769, so maybe it's due to different handling of ETags with Firefox.

###### Basic environment details

Artifact | Version
----------|-------------
Go Server Version: | 22.3.0 (15301-9d23ed19a9ea46eaf7f18bd16671ae0569871f53)
JVM version: | 17.0.5
OS Information: | Linux 5.15.0-57-generic
Usable space in artifacts repository: | 212.87 GB
Pipelines Count: | 4

Client: Firefox 108.0.1 (Snap) Ubuntu 22.04.1 LTS 

###### Additional Environment Details

Running on Docker:

```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

##### Steps to Reproduce

1.  Create a pipeline
2. Save pipeline
3. Attempt to edit pipeline

##### Expected Results

Pipeline can be edited.

##### Actual Results

The following error occurs

> Someone has modified the configuration for pipeline 'nsfn-deploy'. Please update your copy of the config with the changes and try again.

##### Possible Fix

Use Chromium :(

**Comment by davidvedvick** [comment]
Some further information: works on Firefox, in Linux Mint 21.1 Cinnamon, Firefox 108.0.2. This seems like a very odd edge case! Please feel free to close unless wishing to investigate further.

**Comment by chadlwilson** [comment]
Nevetheless there's not enough detail to replicate here I don't think. I use Firefox day-to-day to edit pipelines :)

Do you have any kind of caching in front of your server? Does it work in a private tab for the same otherwise problematic version of Firefox?

**Comment by chadlwilson** [comment]
Sadly there is a long history of weird etag problems across pieces of GoCD. Most recently some cleanup was done in https://github.com/gocd/gocd/pull/10515 - hopefully that hasn't caused another weird problem...

**Comment by davidvedvick** [comment]
> Do you have any kind of caching proxy in front of your server? Does it work in a private tab for the same otherwise problematic version of Firefox?

Caching proxy? No, this is just for a little project and I run gocd on a home server, so nothing too complex (other than running on top of docker)
Does it work in a private tab? Yes! What does this mean, is it a silly cookie thing?

**Comment by chadlwilson** [comment]
Im not sure exsclty what it means, but think more likely that at some point in the original create/edit cycle a version of the pipeline config got cached locally by the browser that it's not re-getting from the server for some reason. But if you can recreate the problem on a newly created pipeline I can't really explain that. Pretty painful to debug without having the whole flow of traffic back and forth from the browser's perspective and possibly quite dependent on the exact flow of pipeline creation/editing through various UI screens :(
