### ISSUE TITLE
Tasks folding in output log

### ISSUE THREAD

**Issue by noirbizarre** [gocd/gocd#1123]
Hi!

Right now, output log is quite dense and the lack of output colors make it very difficult to read.
Thanks to #142 we will soon have a colorized output.

To improve readability, it could be very useful to allow/perform tasks folding in output log.
I know, this the way TravisCI works, but it's very very useful when your build output a lots of logs (dependencies installation as example).

**Comment by srinivasupadhya** [comment]
duplicate https://github.com/gocd/gocd/issues/873 ?

**Comment by noirbizarre** [comment]
Yes, you're right.
Sorry, I searched for folding.
