### ISSUE TITLE
Delay between stages/jobs

### ISSUE THREAD

**Issue by hilverd** [gocd/gocd#1125]
Our teams are trying to reduce the overall time taken by pipelines. One of the things we have noticed is that there is a delay of approximately 20--30 seconds between stages. Some of our pipelines have up to 11 stages, so that adds up.

For example, consider this pipeline (cut from config XML):

```
<pipeline name="BetweenStagesDelay">
    <materials>
        <git url="https://github.com/gocd/gocd.git"/>
    </materials>
    <stage name="first">
        <jobs>
            <job name="j">
                <tasks>
                    <exec command="date"/>
                </tasks>
            </job>
        </jobs>
    </stage>
    <stage name="second">
        <jobs>
            <job name="j">
                <tasks>
                    <exec command="date"/>
                </tasks>
            </job>
        </jobs>
    </stage>
    <stage name="third">
        <jobs>
            <job name="j">
                <tasks>
                    <exec command="date"/>
                </tasks>
            </job>
        </jobs>
    </stage>
</pipeline>
```

If you trigger this pipeline, you'll see that there is approximately 20--30 seconds delay between stages "first" and "second" and between stages "second" and "third", even if there are no other pipelines defined and there are agents available.

From our run of this pipeline just now, the output from the job in each of these stages was:

```
Mon May 11 09:28:22 UTC 2015
Mon May 11 09:28:42 UTC 2015
Mon May 11 09:29:02 UTC 2015
```

Can this delay be reduced?

This was originally raised as request #23913 in the ThoughtWorks Knowledge Base, but I was advised to raise it here instead.

**Comment by FredrikWendt** [comment]
+1

**Comment by pmcgrath** [comment]
+1

**Comment by lyptt** [comment]
+1

**Comment by dsenecalb** [comment]
+1

**Comment by dsenecalb** [comment]
What's the status of for the ticket. We are looking forward that functionality that allows admin to increase/reduce the delay timing

**Comment by scottmuc** [comment]
+1

**Comment by richard-hulm** [comment]
+1

**Comment by mgreensmith** [comment]
+1

**Comment by xli** [comment]
I'm looking into this.

**Comment by xli** [comment]
Summary of why it happens:
* Overview of how agent and server works on scheduled job assignment:
  * Agent calls go-server every 10 sec to get new work when it is idling or completes a job.
  * Go server triggers job assignment only when an agent called and no work is assigned to agent.
  * Go server's work assignment is an asynchronous process.
* Why 20 seconds delay:
  * When an agent completes a job, it goes to sleep for 10 seconds.
  * An agent needs 2 calls to server to get a job assigned:
      1. First call triggers work assignment, but won't get work assigned.
      2. Second call gets assigned job details. It is 10 seconds after first call, work assignment will be done in 5 seconds (because of another periodical task refreshing an in-memory cache).
  * Hence Go needs about 20 seconds to assign a job, when:
     * A new stage is scheduled automatically after previous stage was completed
     * The agents can run new stage's jobs are just completed jobs of previous stage. There is no other idling agent available for the new stage's jobs.

**Comment by xli** [comment]
How Go works in details of work assignment.

There are 5 core classes / services involved:
* AgentController: 
       * calls server for new work every 10 seconds
* WorkAssignments: 
       * is called by BuildRepositoryMessageProducer when AgentController calls server
       * sends out IdleAgentMessage when an agent  has no work assigned.
       * maintains an internal in-memory agent to work assignments hash map
* WorkFinder: 
       * processes IdleAgentMessage, calls BuildAssignmentService to assign work to agent
* BuildAssignmentService:
       * assigns scheduled job to given idle agent
       * caches scheduled job list by loading from database periodically (5 secs). The cached scheduled job list will be updated in-memory when pipeline (jobs) configuration changed, but no update when new job is created.
* ScheduleService:
       * schedules next stage when a stage completed, which will trigger schedule jobs.
       * scheduled jobs data are persisted into database. These scheduled jobs will be picked up by BuildAssignmentService after it refreshed cached scheduled job list.

Notice:
* Go server won't assign job to an agent when a new job created
* Go server and agent communication is implemented on top of Spring HttpInvokerServiceExplorter, which is a one direction (client to server) Java-to-Java remoting protocol.

**Comment by xli** [comment]
Pros & Cons current design & implementation:

Pros:
* Agent is guaranteed to get new work while it is idling
* Go server only assigns a job to a working agent just called in 10 secs. It minimized the possibility of losing agent after assigned
* Performance is good when agents call server to get work. Work assignment is asynchronized, communication between Agent and server won't be blocked, or won't have performance issue when there is a lot of Agent
* Agent pull mode is simple and reliable.

Cons:
* Agent pull interval can't be shorter, current is 10 sec. The shorter, the heavier server side load when there are lots of agents.
* Cached scheduled job list in BuildAssignmentService will delay work assignment.
* It is designed for heavy load environment (Lots of agents and jobs), but adding up some delays for a simple Go environment (e.g. single server, agent and small number jobs)

**Comment by arvindsv** [comment]
@xli: All of what you've said makes sense. I think it's a good analysis. Just wanted to link to the [original post](https://groups.google.com/d/topic/go-cd/Yqd664rZ2LE/discussion), that I think led to this. There were people there who experimented with reducing the interval.

Moving to a more evented mode of communication (websockets, http 2.0) could help the server assign to the agents rather than the agents polling. But, that's a significant change (needs Spring update too, maybe).

**Comment by xli** [comment]
I have a temp solution for this ticket to reduce delay between stages to 10 seconds. 
However, considering we have a lot of reasons to improve overall communication between agent and server (for example: #1098), I started spiking WebSockets for agent and server communication. 
Will see how far I can push #1098, then come back to this ticket

**Comment by xli** [comment]
#1098 will address this ticket.
