### ISSUE TITLE
Loading materials admin page creates syntax error on MySQL 8.0

### ISSUE THREAD

**Issue by arstercz** [gocd/gocd#11260]
### Issue Type

- Bug Report

### Summary

the error occurs after start go-server：
```
2023-01-31 11:17:15,621 ERROR [qtp338329632-38] JDBCExceptionReporter:234 - You have an error in your 
SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use 
near '*    FROM modifications 
) mods JOIN materials m ON mods.materialid=m.id WHERE mo' at line 1
```

### Environment

my system env:
```
Centos 7 - kernel-3.10.0-693
go-server-22.3.0-15301
MySQL 8.0.23
```

db.properties:
```
# /etc/go/db.properties
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://127.0.0.1:3301/gocd?useUnicode=true&characterEncoding=utf8&useSSL=false
db.user=user_gocd
db.password=xxxxxxxx
db.maxActive=32
db.maxIdle=32
```
### Steps to Reproduce

1. start go-server 
2. click the `AGENTS` OR `MATERIALS` button on the gocd web
3. check the error file /var/log/go-server/go-server.log

### mysql query

```
2023-01-31 11:17:15| cli -> ser |【Query】 SELECT mods.* FROM (   SELECT MAX(id) OVER (PARTITION BY materialid)
 as max_id, *    FROM modifications ) mods JOIN materials m ON mods.materialid=m.id WHERE mods.id=mods.max_id;
2023-01-31 11:17:15| ser -> cli |【Err】 Err code:1064,Err msg:42000You have an error in your SQL syntax; check the
 manual that corresponds to your MySQL server version for the right syntax to use near '*    FROM modifications ) 
mods JOIN materials m ON mods.materialid=m.id WHERE mo' at line 1
```

### Possible Fix

read more from [mysql8-select](https://dev.mysql.com/doc/refman/8.0/en/select.html).

Use of an unqualified * with other items in the select list may produce a parse error. For example:
```
SELECT id, * FROM t1
```
to avoid this problem, use a qualified tbl_name.* reference:
```
SELECT id, t1.* FROM t1
```

So we should change the sql:
```
SELECT mods.* FROM (   SELECT MAX(id) OVER (PARTITION BY materialid) as max_id, *    FROM modifications ) 
mods JOIN materials m ON mods.materialid=m.id WHERE mods.id=mods.max_id;

==>

SELECT mods.* FROM (   SELECT MAX(id) OVER (PARTITION BY materialid) as max_id, modifications.*    FROM 
modifications ) mods JOIN materials m ON mods.materialid=m.id WHERE mods.id=mods.max_id;
```

**Comment by chadlwilson** [comment]
Related to #11134

What do you mean by "click the OR button on the gocd web"?

**Comment by arstercz** [comment]
> 

![image](https://user-images.githubusercontent.com/1954680/215670301-01283a7f-3d25-41f1-b4ba-a968c90fa987.png)

**Comment by chadlwilson** [comment]
Yeah, think the materials page trigger this. Is the server otherwise running ok?

**Comment by arstercz** [comment]
> Yeah, think the materials page triggers this. Is the server otherwise running ok?

Unfortunately, all the tasks are hung for long time, probably because cann't get the sql result:
```
2023-01-31 11:34:02,515 INFO  [ThreadPoolTaskScheduler-7] ConsoleActivityMonitor:111 - Job 'udbm-test-deploy/2/udbm-test-job/1/udbm-test-tasks' hung for more than '21' minutes
2023-01-31 11:34:06,363 WARN  [qtp338329632-222] JDBCExceptionReporter:233 - SQL Error: 1064, SQLState: 42000
2023-01-31 11:34:06,364 ERROR [qtp338329632-222] JDBCExceptionReporter:234 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to
use near '*    FROM modifications ) mods JOIN materials m ON mods.materialid=m.id WHERE mo' at line 1
2023-01-31 11:34:32,517 INFO  [ThreadPoolTaskScheduler-5] ConsoleActivityMonitor:111 - Job 'udbm-test-deploy/2/udbm-test-job/1/udbm-test-tasks' hung for more than '21' minutes
2023-01-31 11:35:02,518 INFO  [ThreadPoolTaskScheduler-4] ConsoleActivityMonitor:111 - Job 'udbm-test-deploy/2/udbm-test-job/1/udbm-test-tasks' hung for more than '22' minutes
```

**Comment by chadlwilson** [comment]
To my knowledge that particular query shouldn't affect the rest of the material subsystem, and is only to get a server-wide view of the materials and their latest modification.

Hung jobs when the jobs have started, and is likely something different to look into I think.

**Comment by arstercz** [comment]
the h2 database was used first, and then change to mysql database.

**Comment by chadlwilson** [comment]
OK, sure - what I am trying to say is that even if this bug is addressed and you upgraded your server to a new version, I don't think it will address any issue with your jobs being hung.

You'd have to look separately at why they are hung and whether there is a different problem, or a problem with your upgrade process. If you migrated databases using https://github.com/gocd/gocd-database-migrator and restarted your server while jobs were running, try cancelling the jobs and re-running them and see if there are any issues specific to running the jobs. If you started with a fresh mysql database but had previous agents connected to your server while it was running on H2 the server is probably confused about what agents you have so you'll probably need to at least restart the agents and re-authorise them.
