### ISSUE TITLE
Problem installing Go-Server in a Linux (Ubuntu) machine

### ISSUE THREAD

**Issue by rtaborda** [gocd/gocd#1126]
I can't seem to install the Go-Server in a Ubuntu machine, I'm following the steps in the documentation but I always get an error.

    $ sudo dpkg -i go-server-15.1.0.deb
    dpkg: error processing archive go-server-15.1.0.deb (--install):
    cannot access archive: No such file or directory
    Errors were encountered while processing:
    go-server-15.1.0.deb

I tried removing the 0, so 15.1 and got he same error. 
Also tried using dpkg -l \*go-server\* but nothing was found, tried searching the apt-cache but got the same result.

I would also like to point out that I've only started using Linux last week, so most likely I'm just doing something wrong or missing a step.

**Comment by arvindsv** [comment]
Hello @rtaborda. You need to download the DEB file, before you can use dpkg. You can get  it at: http://download.go.cd/gocd-deb/go-server-15.1.0-1863.deb

```dpkg -i``` is for installing a downloaded file. ```apt-get install``` is for installing a package from the package repositories. go-server is not in the usual package repositories. I can give you details about pointing to the correct repository, but it should be easier to download the file mentioned above and install it using ```dpkg -i```. You might need to run this, if ```dpkg -i``` fails saying that dependencies are unmet:

```
sudo apt-get update
sudo apt-get install openjdk-7-jre unzip
sudo dpkg -i go-server-15.1.0-1863.deb
```

**Comment by rtaborda** [comment]
That worked perfectly!
Thank you very much for the help
