### ISSUE TITLE
Maven part 3 - clean up

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#113]
### To Do:
- All jar dependancies which are not available in maven repo are checked in into local-maven-repo folder under source code. Move local-maven-repo to http based repo something like -http://google-caja.googlecode.com/svn/maven
- MENIFEST.MFis hardcoded for some module, need to find a way to generate MENIFEST.MF (ex agent-launcher & tfs-impl)
- move version of all modules from 1.0 -\> 14.1.0 for consistency

**Comment by arvindsv** [comment]
Closing this. When #2010 is done, all of this changes.
