### ISSUE TITLE
How Reset Password ? 

### ISSUE THREAD

**Issue by xlw712** [gocd/gocd#11324]
I use Password-file authentication,But settings after not login
![image](https://user-images.githubusercontent.com/10722207/220350852-b0fe918f-e97c-4432-9dc9-bf0574b87282.png)
I try delete password-file but not work too?
What should I do?

**Comment by chadlwilson** [comment]
Hello - GitHub issues are not the right place to use as a help forum for GoCD or its plugins.

They are for raising bugs and enhancement requests and co-ordinating software development effort. If you have questions please use [discussions](https://github.com/gocd/gocd/discussions) or the [GoCD forums](https://groups.google.com/g/go-cd).
