### ISSUE TITLE
Request Headers not passed in with the isValidUser auth plugin request

### ISSUE THREAD

**Issue by mattgauntseo-sentry** [gocd/gocd#11331]
##### Issue Type

- Bug Report

##### Summary

The document for the "is valid user" request in auth plugins suggest the request headers will be included, [see here](https://plugin-api.gocd.org/current/authorization/#is-valid-user).

> Request headers would contain all the HTTP request headers sent by the external authorization server to GoCD.

Testing with [a fork](https://github.com/getsentry/gocd-google-iap-authorization-plugin) of the google oauth plugin suggests that these headers are *not* passed in for this request as documented.

###### Basic environment details

* Go Version: ` 22.3.0 (15301-9d23ed19a9ea46eaf7f18bd16671ae0569871f53)`
* JAVA Version: `17.0.5`
* OS: `Linux 5.15.65+`
* Browser vendor and version (if relevant): `Chrome 110.0.5481.100`

##### Steps to Reproduce

1. I've installed https://github.com/getsentry/gocd-google-iap-authorization-plugin/releases/tag/v0.0.5 on a GKE cluster which is accessible behind a identity aware proxy
2. Setup plugin with Google OAuth credentials and the audience for the IAP
3. Sign in and create a personal access token
4. Look at the logs and see no headers are printed

##### Expected Results

I'd expect the IAP headers to be included with the "is valid user" request.

##### Actual Results

No headers are provided.

##### Possible Fix

This may be an issue with the docs rather than implementation, but it would be helpful for us to have access to the headers.

**Comment by mattgauntseo-sentry** [comment]
Yes that's what meant - they are *not* passed in (I've edited my original comment)

**Comment by chadlwilson** [comment]
Do they come through as you'd expect for FetchAccessToken?

**Comment by chadlwilson** [comment]
I've corrected the documentation, as the code definitely does not pass the headers for either `GetUserRoles` or `IsValidUser`. Doesn't seem it ever has either, unless it was perhaps different in a very ancient incarnation.

Would you be able to help me understand _why_ this would be useful, or how this might work?

I'm not a Google IAP expert, but does seem a bit of a different use case compared to a backend reliant on an OAuth2 redirect/auth code flow and traditional OAuth2 access token issued by an IdP. Is it essentially that IAP proxies every single request to GoCD and thus is able to stamp each request (even one using a GoCD API token) with headers like `x-goog-iap-jwt-assertion`, so the special header(s) are available for an arbitrary request to look at and "decide" to validate if they want to?

And you intend to implement `IsValidUser` by checking that a header already exists with the same user, that a signed JWT validates and has the expected username in it?

**Comment by mattgauntseo-sentry** [comment]
Yes, the headers come through for FetchAccessToken.
