### ISSUE TITLE
Provide arm64 arch-specific deb and rpms with correctly bundled JRE

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd#11354]
##### Issue Type

- Feature enhancement

##### Summary

After the implementation of #8544 in `23.1.0`
- the Go Server and Agent are properly validated against arm64 architecture via docker images for both Debian and CentOS
- wrapper binaries for arm64 are included within the `deb` and `rpm`s built.

This means users _can use the installs on most distros to run arm64_ **ONLY IF** the user supplies their own arm64 JRE or JVM and overrides `wrapper.java.command` in `/usr/share/go-(server|agent)/wrapper-config/wrapper-properties.conf` to tell the wrapper where to find an arm64 JRE they have installed elsewhere.

Due to an accident of history, an x64 JRE is bundled with both the `deb` and the `rpm` despite them marked marked as `all` arch and `noarch` respectively. 

##### Expected Results

Running debs or rpms on arm64 come with a correct-arch pre-packaged JRE or multi-arch package dependency (as with x64), rather than requiring a separate manual JRE install and any need to manually override the JRE in the config.

##### Actual Results

Currently an x64 JRE is bundled, which is wasteful and unusable on arm64 anyway with a separate JRE/JDK install provided by the user.

##### Possible Fix

Possibly we could either
1. bundle an arm64 JRE into the same deb/rpm at cost of massively increasing the size, and undermining the intention
2. produce aarch64/arm64 specific installers which bundle a valid JRE version (similar to the docker images)
3. keep the existing `noarch`/`all` top level variants, but extract the JRE (and optionally other) arch-specific bits into a new dependent package
    - The idea of this would be to smooth the upgrade path as I am not sure if `dnf` etc will transparently handle an upgrade for a version while switching arch, e.g from say `24.1.0-noarch` --> `24.2.0-aarch64` ?
4. One might argue it'd be better to stop bundling the JRE in these specific packages and add a dependency to some other standard JDK/JRE package and reconfigure the wrapper config to point to it rather than the bundled JRE. (e.g `java-17-openjdk-headless` on RHEL/CentOS, or `openjdk-17-jre-headless` on Debian/Ubuntu).
5. arguably stop publishing the `noarch`/`all` arch variants entirely since they are "incorrect".

**Comment by chadlwilson** [comment]
At this stage I am leaning towards **option 4**, but would need to dig a bit into the history of why the JRE was bundled, and the size/contents of these off-the-shelf packages.

It's possible that there weren't appropriate packages in repos at the time, since GoCD was using/targetting non LTS JDK versions (e.g `13`, `15` etc) for quite some time (which we no longer do or will do).

**Comment by matthiaskraaz** [comment]
Option 1: Sounds like you mentioned this option for the sake of completeness only.

Option 2: I like this one. We could even jlink a JRE with just the stuff needed by GoCD.

Option 3: I'm pretty sure that RPM and DEB can handle that kind of migration, but I'm willing to test it (with a local repo). But I think this sounds like a lot of effort without much benefit considering how cheap bandwidth and storage has become.

Option 4: I also like this one. I even started to work on this alreay. What I dislike about this option: chances are very good, that the user installs more than one JDK - one to run GoCD, one to build, maybe some more to test with various Java versions. Up to now, the user did not have to configure which Java GoCD runs with. Now he does.

Option 5: I think, this option pairs with option 2.

BTW: I think GoCD is using Java 17 right now. What is the state regarding Java 21? IMO, the biggie with Java 21 is JEP 400 (UTF-8 by default).

**Comment by matthiaskraaz** [comment]
Sounds to me like the the debundled GoCD package should have a dependency on a headless JRE 17.

On CentOS 9, there is an alias "jre-17-headless" that the GoCD RPM package could depend on. (alias isn't the correct term, but I don't remember what it was.) However the path to the java binary includes the name of the architecture, i. e. the path is architecture-specific. As the GoCD package is supposed to be architecture independent, we need some logic in the install scripts of the RPM or to select the correct path. The system requirements say CentOS/RedHat version 8+ for the RPM based Linux distributions. So I only need to check those versions of those distributions? Not SLES for example?

I have to check the situation for Debian and Ubuntu. The system requirements say Debian 10+ and Ubuntu 20+ for the DEB based Linux distributions. Right?

**Comment by chadlwilson** [comment]
> Sounds to me like the the debundled GoCD package should have a dependency on a headless JRE 17.

Yeah, that *should* work fine, let's give that a go first?

> On CentOS 9, there is an alias "jre-17-headless" that the GoCD RPM package could depend on. (alias isn't the correct term, but I don't remember what it was.) However the path to the java binary includes the name of the architecture, i. e. the path is architecture-specific. As the GoCD package is supposed to be architecture independent, we need some logic in the install scripts of the RPM or so to select the correct path.

Yeah, not sure if it's best to specify dependency on such a "virtual" package or pick a specific one, which might make it easier to know where it is installed.

I think on RHEL/CentOS we can possibly use symlinks maintained in `/etc/alternatives` without having to figure out the true install location, but that may not be possible on Ubuntu/Debian as don't think they have symlinks that include the specific java version, only `/etc/alternatives/java`.

Possibly we might need to update the `wrapper.conf` post-install/post-upgrade if there is no way to figure it out declaratively. The Tanuki Wrapper config can [find things from the environment](https://wrapper.tanukisoftware.com/doc/english/props-envvars.html), however env vars such as `WRAPPER_ARCH` are probably not the same as the packaging system arch, which I guess would need to come from `dpkg --print-architecture` or similar?  

| Platform | Possible virtual package req | Current real package | Possible install loc to use? | 
| -------- | -------- | -------- | ------ | 
| RHEL-esque | `jre-17-headless` | `java-17-openjdk-headless` | `/etc/alternatives/jre_17/bin/java` |
| Debian-esque | `java17-runtime-headless` | `openjdk-17-jre-headless` | `/usr/lib/jvm/java-17-openjdk-{arm64\|amd64}\bin/java` |

But there are at least two approaches to play with, roughly equivalent:

1) Current - link to the Java binary, let the wrapper figure out the rest.
    ```
    wrapper.java.command=/java/path/bin/java
    ```
2) Try to find the install directory to determine `JAVA_HOME`
    ````
    set.JAVA_HOME=/java/path
    wrapper.java.command=%JAVA_HOME%/bin/java
    ````

I'm also not sure whether you can declare dependency on a virtual package without the user being asked to choose which candidate to install. Need to be a bit careful about some virtual packages also allowing later (> 17) Java versions to be satisfy the requirement, which we don't want to allow right now.

> The system requirements say CentOS/RedHat version 8+ for the RPM based Linux distributions. So I only need to check those versions of those distributions? Not SLES for example?

I've never personally tried on SLES or heard anyone asking about it, so we can stick to RHEL-esque. Even CentOS is weird these days because CentOS Stream <> CentOS and doesn't, for example, get proper/timely security updates on packages. I switched the CentOS GoCD container images to be based on Stream for ease of migration, and its stable enough for purposes of a container, but doesn't get the security updates necessary (or publish security metadata) for packages (incl JREs) such that I'd suggest it's a good idea for users. If you wanted to validate with Alma or Rocky instead and assume RHEL/CentOS are OK, I think that'd be perfectly fine.

> I have to check the situation for Debian and Ubuntu. The system requirements say Debian 10+ and Ubuntu 20+ for the DEB based Linux distributions. Right?

It's kind of impossible to keep things things up-to-date everywhere, but generally speaking GoCD has tried to support LTS distributions that are still getting regular security updates. Gets into grey area if it's possible to purchase commercial extended security backports - probably we'd decide based on if it causes any particular friction to support it. :-) Debian 10 will be EOL soon, so we can ignore that one and stick to sanity checking on Debian 11/12, Ubuntu 20.04/22.04.

**Comment by matthiaskraaz** [comment]
`apt install java17-runtime-headless` actually asks me to select a package. So it seems like we should refrain from depending on a virtual package. I think, if we depend on a package with 17 in the name, we can be sure to get Java 17. DEB and REP also allow to specify the major version of the dependency in the requirement.

WRAPPER_ARCH says "arm" instead of arm64. Maybe one is supposed to concat WRAPPER_ARCH and WRAPPER_BITS?! I would prefer to just insert ```/usr/lib/jvm/java-17-openjdk-`dpkg --print-architecture`/bin/java``` into the wrapper.conf in the post install script.

I tested:
```
sudo apt update
sudo apt install openjdk-17-jre-headless
/usr/lib/jvm/java-17-openjdk-`dpkg --print-architecture`/bin/java -version
```

Worked with:
```
Ubuntu 20.04 x86-64 OK
Ubuntu 20.04 arm64 OK
Ubuntu 22.04 x86-64 OK
Ubuntu 22.04 arm64 OK

Debian 10 x86-64 and arm64: kein openjdk-17-jre-headless. install of openjdk-11-jre-headless fails
Exception in thread "main" java.lang.InternalError: Error loading java.security file
        at java.base/java.security.Security.initialize(Security.java:94)
        at java.base/java.security.Security$1.run(Security.java:79)
        at java.base/java.security.Security$1.run(Security.java:77)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.Security.<clinit>(Security.java:77)
        at java.base/sun.security.jca.ProviderList.<init>(ProviderList.java:176)
        at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:94)
        at java.base/sun.security.jca.ProviderList$2.run(ProviderList.java:92)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.jca.ProviderList.fromSecurityProperties(ProviderList.java:91)
        at java.base/sun.security.jca.Providers.<clinit>(Providers.java:54)
        at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:156)
        at java.base/java.security.cert.CertificateFactory.getInstance(CertificateFactory.java:193)
        at org.debian.security.KeyStoreHandler.<init>(KeyStoreHandler.java:50)
        at org.debian.security.UpdateCertificates.<init>(UpdateCertificates.java:65)
        at org.debian.security.UpdateCertificates.main(UpdateCertificates.java:51)
E: /etc/ca-certificates/update.d/jks-keystore exited with code 1.
Debian 11 x86 OK
Debian 11 arm64 OK
Debian 12 x86-64 OK
Debian 12 arm64 OK
```

So how about this for a plan:
- depend on the real package
- hardcode /etc/alternatives/jre_17/bin/java into the wrapper.conf for the RPM
- write `/usr/lib/jvm/java-17-openjdk-`dpkg --print-architecture`/bin/java -version` into the wrapper.conf in the DEB postinstall script

**Comment by chadlwilson** [comment]
> So how about this for a plan:
> 
>     * depend on the real package
> 
>     * hardcode /etc/alternatives/jre_17/bin/java into the wrapper.conf for the RPM
> 
>     * write `/usr/lib/jvm/java-17-openjdk-`dpkg --print-architecture`/bin/java -version` into the wrapper.conf in the DEB postinstall script

Seems reasonable to me, or at least worth a go :-)

The Debian 10 package install error is curious, but seems like an issue with their packages for updating the ca-certificates for the JVM, so not worth worrying about (especially as it's Java 11, which we won't support for `24.1.0`+).
