### ISSUE TITLE
Test Drive for GoCD 23.1 stuck starting on Windows with VPN

### ISSUE THREAD

**Issue by sandro-h** [gocd/gocd#11398]
##### Issue Type

- Bug Report

##### Summary

Test Drive for GoCD 23.1 doesn't start on Windows with VPN active. It waits indefinitely at the "Waiting for GoCD to bootstrap" step. This used to work with Test Drive for GoCD 22.2. It probably already stopped working with 22.3, but I can't verify that without a download link for that old version.

###### Basic environment details

* Go Version: 23.1
* JAVA Version: Bundled with Test Drive
* OS: Windows 10

###### Additional Environment Details

Only happens with (Cisco AnyConnect) VPN active.

##### Steps to Reproduce

While Cisco AnyConnect VPN is active, run GoCD Test Drive as described on https://www.gocd.org/test-drive-gocd.html:

```shell
curl -fsSL 'https://www.gocd.org/test-drive-gocd/try.sh' | bash -s 'https://download.gocd.org/test-drive/installers/23.1.0/16079/gocd-23.1.0-16079-2148-windows.zip'
```

##### Expected Results

Test Drive opens a browser window with the GoCD UI and continues to start the agent.

##### Actual Results

Test Drive is stuck indefinitely on `Waiting for GoCD to bootstrap...`. The GoCD server is actually started and accessible in the browser, but because Test Drive never completes this step, it doesn't launch the agent, so it's not really usable.

##### Log snippets

Log output when directly running `run-gocd.exe -X` and modifying the gocd-trial-launcher code to print the error in `TryConnect`:

```
Starting the GoCD server...
[DEBUG] server PID: 24468, writing to pidfile: "C:\\Users\\redacted\\gocd-23.1.0-16079-2148\\data\\server\\server.pid"
Waiting for GoCD to bootstrap[DEBUG] Attempting connection to localhost:8153
Error: dial tcp: lookup localhost on <redacted IP of VPN DNS server>:53: no such host
[DEBUG]   Failure.
.[DEBUG] Attempting connection to localhost:8153
Error: dial tcp: lookup localhost on <redacted IP of VPN DNS server>:53: no such host
[DEBUG]   Failure.
.[DEBUG] Attempting connection to localhost:8153
Error: dial tcp: lookup localhost on <redacted IP of VPN DNS server>:53: no such host
[DEBUG]   Failure.
```

##### Any other info

I'm pretty sure this is due to the Golang upgrade from 1.14 (according to `go version run-gocd.exe`) to 1.20 between GoCD 22.2 and 23.1. In the [release notes](https://tip.golang.org/doc/go1.19) for Golang 1.19, we find:

> The net package now has initial support for the netgo build tag on Windows. When used, the package uses the Go DNS client (as used by Resolver.PreferGo) instead of asking Windows for DNS results. The upstream DNS server it discovers from Windows may not yet be correct with complex system network configurations, however. 

And if I build the gocd-trial-launcher without `-tags netgo` it works. It also works if I use `127.0.0.1` for the connection test, avoiding the DNS lookup.

I realize this is an odd edge case for a secondary tool. We use test drive a lot for our users to test pipelines locally in a fast, cross-platform way. And we can't tell them to leave the company VPN every time they want to use it. So I'm hoping we can find a fix that won't tax your limited (and much appreciated) capacity too much for such an edge case.

**Comment by chadlwilson** [comment]
Thanks for the digging - you've done all the hard work here. Seems likely due to https://github.com/golang/go/issues/57757

Can you give `curl -fsSL 'https://www.gocd.org/test-drive-gocd/try.sh' | bash -s 'https://download.gocd.org/test-drive/installers/23.1.0/16079/gocd-23.1.0-16079-2164-windows.zip'` a go?

If it works OK, I can probably release it "properly".

**Comment by sandro-h** [comment]
Everything works perfectly with this new version 👍 Thanks for the quick fix!

**Comment by chadlwilson** [comment]
Cool, thanks - it's available officially at https://www.gocd.org/test-drive-gocd.html now. 🙏
