### ISSUE TITLE
ldap lock out

### ISSUE THREAD

**Issue by cheenpo** [gocd/gocd#1140]
I enabled ldap, but now can't login.
is there a place I can go to stop the go server process (kill the pid is fine), then reset/change some config, and then start it back up with no auth/ldap in place?

**Comment by cheenpo** [comment]
oh... on mac OS X version

**Comment by cheenpo** [comment]
figured it out:

remove this on cruise-config.xml in the Go Server/config folder:
    <security>
      <ldap uri="ldap://<HIDDEN>">
        <bases>
          <base value="blah blah" />
        </bases>
      </ldap>
    </security>

**Comment by ChennyBaBy** [comment]
What did you remove exactly?

**Comment by zabil** [comment]
Must've been this section
http://www.go.cd/documentation/user/current/configuration/configuration_reference.html#ldap
