### ISSUE TITLE
Plugin Author Link is malformed

### ISSUE THREAD

**Issue by paulclarkin** [gocd/gocd#1141]
On the plug in admin screen (/go/admin/plugins), the URL behind some author links is malformed.
It is being generated as http://https//github.com/srinivasupadhya for example.

**Comment by paulclarkin** [comment]
Issue is caused when the plugin URL is https:// as this doesn't match the check for http:// in GoPluginDescriptorModel.java

**Comment by paulclarkin** [comment]
@zabil Why's this reopened?

**Comment by zabil** [comment]
sorry @paulclarkin forgot to add a note. 
It opened automatically when I pushed it to "ready for QA" on our zenhub.io wall.

It will be closed once we test it out on experimental.

**Comment by mdaliejaz** [comment]
Verified. Works fine on 15.2.0(2012-e6220e7).
