### ISSUE TITLE
Ability to change the SSL certificate used to ensure it is trusted

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#115]
The Go Server uses a self-signed SSL certificate for HTTPS traffic which is issued for the name of the machine name.

There are several problems with this:
 - The certificate is not trusted as it is not signed by a trusted CA
 - Using the name of the server prevents any other, more friendly, host name being used
 - The certificate cannot be updated, changed or renewed

Can we have a mechanism for using a standard x509 certificate and have a configuration value where GO can look up the certificate from a file or from the certificate store (in the case of the Windows version)

**Comment by arvindsv** [comment]
@ketan: Can this be closed with https://github.com/gocd/gocd/pull/2236?

**Comment by ketan** [comment]
I'm going to close this out and declare that [this](https://docs.go.cd/current/installation/ssl_tls/custom_certificate.html) is the official way to update SSL certs going forward.
