### ISSUE TITLE
Environment variable GO_REVISION isn't defined when material name is defined

### ISSUE THREAD

**Issue by JeroenOortwijn** [gocd/gocd#11512]
##### Issue Type

- Bug Report

##### Summary

Once you give a material a material name, the GO_REVISION environment variable won't be defined anymore.
(See also issue  #11511.)

###### Basic environment details

* Go Version: `23.1.0 (16079-21e78c998e1eb35d8d489c1d3e3e9813dc18233a)`
* JAVA Version: `17.0.6`
* OS: `Linux 5.4.0-147-generic`

##### Steps to Reproduce

1. Create a pipeline with a SVN material without a material name and the following two custom commands: `echo %GO_PIPELINE_COUNTER%` and `echo %GO_REVISION%`
3. SVN Commit and check the output
4. Give the material a material name (e.g. `SVNtest`)
5. (The pipeline automatically runs again) Check the output

##### Expected Results
In both cases it should show the following output:
```
[go] Task: echo %GO_PIPELINE_COUNTER% took: 0.62s
88 
[go] Task status: passed, took: 0.62s
[go] Task: echo %GO_REVISION% took: 0.62s
8188 
[go] Task status: passed, took: 0.62s
```

##### Actual Results
In the case with the material name defined, it shows the following output:
```
[go] Task: echo %GO_PIPELINE_COUNTER% took: 0.62s
89 
[go] Task status: passed, took: 0.62s
[go] Task: echo %GO_REVISION% took: 0.62s
%GO_REVISION% 
[go] Task status: passed, took: 0.62s
```

**Comment by chadlwilson** [comment]
This might just be a documentation issue. When you name the material or add an alternate checkout location the env var is `%GO_REVISION_${material name or dest}%` as noted at https://docs.gocd.org/current/faq/dev_use_current_revision_in_build.html

So `GO_REVISION_SVNTEST` in your example above.

The clarification that may be needed is that `GO_REVISION` is only defined if using a single _unnamed_ material in default checkout location. It looks to me like the code has always been this way.

**Comment by JeroenOortwijn** [comment]
You are correct, I just confirmed that with the custom command `set` which lists all environment variables on the agent.

Before creating this issue, I tried `echo %GO_REVISION_${SVNtest}%`, but that didn't work.
Apparently I should have tried `echo %GO_REVISION_SVNTEST%`.

I agree that this issue is not a bug but a documentation improvement issue. 😉

**Comment by chadlwilson** [comment]
For what it's worth, if you expand the console log "Start to prepare" step from job details, the env vars being specifically set by GoCD (rather than inherited somehow from process context) are logged out.

**Comment by JeroenOortwijn** [comment]
You mean here?:
![image](https://user-images.githubusercontent.com/51476918/234333014-e427536e-e3a9-46fd-a520-cd014e1d46b0.png)

There isn't an expander in front of the `Start to prepare` step.

**Comment by chadlwilson** [comment]
Odd, the expanders look different here. Maybe they depend on whether "clean working directory" is set, or something else. No idea - never looked into it in detail.

![image](https://user-images.githubusercontent.com/29788154/234334012-b495a2e7-0885-4f96-bdf4-e30fbb1b57f8.png)

**Comment by chadlwilson** [comment]
Fixed in https://github.com/gocd/docs.go.cd/commit/955eca47b5fe308fba618563d4101f4560e8ad5c
