### ISSUE TITLE
Capture task output and reuse it in later tasks.

### ISSUE THREAD

**Issue by JonasGroeger** [gocd/gocd#1170]
Hello!

It would be very helpful to have the task output matched against a regular expression that captures some variables. Then, we can use these variables in later stages/jobs/tasks.

```
Task output > Match with regex -> save property
```

Meanwhile in a later stage:

```
saved property -> use in tasks, jobs and stages with special syntax ( i.e. %{version} )
```

This is for example useful when you build a software and then need the version of that built software in a later task (i.e. for deployment).

The configuration system we currently have in Pipelines is static in the sense that we have to define the properties and values before running something like a stage. The explanation above will allow dynamic properties to be added while running a certain task.

**Comment by JonasGroeger** [comment]
The configuration system we currently have in Pipelines is static in the sense that we have to define the properties and values beforehand. The explanation above will allow dynamic properties to be added while running a certain task.

**Comment by JonasGroeger** [comment]
Relevant discussion on gitter: https://gitter.im/gocd/gocd?at=556c84a19f3a9b7b060a2268

**Comment by JonasGroeger** [comment]
Ideally, somebody would have something like scoping in those parameters.

**Comment by DiegoZurita** [comment]
+1

**Comment by brianyee0** [comment]
+1

Our builds would get a version # early on, which would need to be referenced by later stages.  I don't see a way to do it without this functionality (or the clunky workaround in the gitter discussion).
