### ISSUE TITLE
#851 - User search with plugin does not display any results if the displayName is not set on user

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1178]
Related to #851 

Steps to reproduce:
1. Register application for your Go server on github ([link](https://github.com/settings/applications/new))
2. Build and install github plugin from [here](https://github.com/srinivasupadhya/gocd-oauth-login) on to your Go server.
3. Set plugin settings to have the client id and secret generated in step1.
4. Navigate to go-server/go/admin/users and search for say "jyotisingh". 

A search for this user on github [returns](https://github.com/search?q=jyotisingh&type=Users&ref=searchresults) multiple users wherein a few do not have a full-name/display-name set. When you search for the same term in Go, the plugin finds the desired users and returns them to Go, but Go is unable to display the result. Users authenticated using password file also do not have a full-name set, but they get displayed as expected.

This works as expected if all users in the resultset have a display-name set such as [this](https://github.com/search?q=admin&type=Users&ref=searchresults).

**Comment by srinivasupadhya** [comment]
we need to decide wether to handle empty `displayName` on rails or to make display name same as username if its empty on plugin response handler.

**Comment by mdaliejaz** [comment]
Verified. Works on 15.2.0(2093-c20772b).
