### ISSUE TITLE
Plugin settings popup does not load for pipeline group admins

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1184]
Related to #1121 

Group admins are allowed to view the list of available plugins. Now that a plugins settings icon has been added, it is available for such users to click. However, clicking this link brings up a popup with the loading icon, but never finishes loading. See the picture below:

![screen shot 2015-06-04 at 12 25 02](https://cloud.githubusercontent.com/assets/1046342/7978544/1c0098d2-0ab4-11e5-947b-71bd68632fba.png). 

The network tab reports a 403 error. 
Need to discuss if the group admin should be allowed to edit/view plugin settings at all.

**Comment by arvindsv** [comment]
I'd say we should show a message, since it is a system-wide setting.

**Comment by jyotisingh** [comment]
Ok, so I take it that a group admin would be allowed to edit a plugin config, provided there is a warning displayed stating that its a global config. Is that right @arvindsv ?

**Comment by arvindsv** [comment]
No, I was thinking not allowing a group admin to edit plugin config, since it is a system-wide setting. They could affect other groups/pipelines.

**Comment by arvindsv** [comment]
@jyotisingh: Do you need to assign #1121 to yourself? In zenhub, I see it assigned to @srinivasupadhya, still.

**Comment by jyotisingh** [comment]
>> No, I was thinking not allowing a group admin to edit plugin config, since it is a system-wide setting. They could affect other groups/pipelines.

Sounds good to me.

**Comment by jyotisingh** [comment]
>> @jyotisingh: Do you need to assign #1121 to yourself? In zenhub, I see it assigned to @srinivasupadhya, still.

I am not really testing #1121 right now. Stumbled across a bug related to that while testing #851. I could pick #1121 next if its still there to be picked. I unassiged @srinivasupadhya from the issue.

**Comment by mdaliejaz** [comment]
Verified as part of #1121.
