### ISSUE TITLE
Accessing login url for auth endpoint for the first time throws a 404 page 

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1185]
Related to #851

Steps:
1. Install and configure github-oauth plugin in Go
2. open a browser, clear all cache and cookies.
3. Access the login url -> localhost:8153/go/plugin/interact/github.oauth.login/index

It should redirect to github login page, but it throws a 404 page from github instead. If you hit the url again from browser, it starts working as expected. 

Findings:
Basically, first time around jsessionid gets generated and attached to the url causing github to throw a 404, eg: 
```url
https://github.com/login/oauth/authorize;jsessionid=px4zl3mmyjrx1toq7bw5e2v0d?client_id=6c4ce62f2e0d2fb1dde1&response_type=code&redirect_uri=https%3A%2F%2Flocalhost%3A8154%2Fgo%2Fplugin%2Finteract%2Fgithub.oauth.login%2Fauthenticate&scope=user,user:email
```

On second attempt, jessionid is not a part of the url (as a JESSIONID cookie is already set) and hence github responds with the authentication page as expected.

**Comment by arvindsv** [comment]
I remember someone asking about this [on the mailing list](https://groups.google.com/d/topic/go-cd/xU8aPOYGBSs/discussion). We should get rid of that jsessionid from the URL, right? Do you think that's the correct solution?

**Comment by jyotisingh** [comment]
>> We should get rid of that jsessionid from the URL, right? Do you think that's the correct solution?

Yes, in my opinion. The mail you linked to also makes sense. Let me put up a PR together for this. Wait does that imply I am no longer allowed to test this story! :wink:

**Comment by arvindsv** [comment]
:P No. Just means someone else will accept your PR.
