### ISSUE TITLE
Can't login based on `gocd-filebased-authentication-plugin` plugin

### ISSUE THREAD

**Issue by Zer0S2m** [gocd/gocd#11858]
##### Issue Type
- Bug Report

##### Summary

File based basic authentication not working using **`htpasswd`** на основе плагина **`gocd-filebased-authentication-plugin`**.
Also tried through normal mode and incognito mode

###### Basic environment details

- Go Version: 23.2.0-16614
- JAVA Version: 17.0.7
- OS: SMP Debian 5.10.179-2

##### Steps to Reproduce

1. Set up GoCD for production
2. Create user login with password by following command - **`htpasswd -nbB admin 'sPaYZGIf3tqGJ0t3' > ./passwd`**
3. Try to login

##### Expected Results
The user should be able to login on the server

##### Actual Results
The login page is reloaded and the user cannot log in using the current authorization data.

##### Log snippets
**`cruise-config.xml`** configuration file:
```xml
<security>
  <authConfigs>
    <authConfig id="test" pluginId="cd.go.authentication.passwordfile">
      <property>
        <key>PasswordFilePath</key>
        <value>/var/lib/go-server/config/passwd</value>
      </property>
    </authConfig>
  </authConfigs>
  <admins>
    <user>admin</user>
  </admins>
</security>
```

**`plugin-cd.go.authentication.passwordfile.log`** log file:
```
2023-08-11 12:30:18,088 INFO  [qtp1383397679-41] PasswordFilePlugin:72 - [Authenticate] Failed to authenticate user: admin using auth_config: pass
2023-08-11 12:30:18,089 INFO  [qtp1383397679-41] PasswordFilePlugin:72 - [Authenticate] Failed to authenticate user: admin.
```

**`passwd`** password file:
```
admin:$2y$05$KF.tQVJbFvWI93fR9wrZuOZBi7ZjXMZ6zcn3rWo9i35bMnvUQ6LTe
```

**Comment by Zer0S2m** [comment]
I noticed the following in the source code (exactly where the authorization process itself is called). [First stage](https://github.com/gocd/gocd-filebased-authentication-plugin/blob/master/gocd-filebased-authentication-plugin/src/main/java/cd/go/authentication/passwordfile/PasswordFilePlugin.java#L72):

```java
case REQUEST_IS_VALID_USER:
    return new IsValidUserRequestExecutor(request).execute();
default:
````

Next comes the processing of the request for authorization. [Second phase](https://github.com/gocd/gocd-filebased-authentication-plugin/blob/master/gocd-filebased-authentication-plugin/src/main/java/cd/go/authentication/passwordfile/executor/IsValidUserRequestExecutor.java#L48):
```java
@Override
public GoPluginApiResponse execute() throws Exception {
...
}
```

Perhaps the problem may be in the processing call method. I dare not state just a guess.

But when processing the request in the browser, I don't see that the `404` status code is showing a `200` response.

**Comment by chadlwilson** [comment]
```
I noticed the following in the source code (exactly where the authorization process itself is called)
```

Unfortunately the `PasswordFilePlugin:72` and line 72 from the log is misleading due to the way the GoCD plugin logger delegation works - the line numbers get misreported.

```
using auth_config: pass
```

```xml
<authConfig id="test" pluginId="cd.go.authentication.passwordfile">
```

These seem to be inconsistent? The id in your config is `test` but the logs say the name of the auth config is `pass`. Do you perhaps have multiple configs, and the wrong one is being used, with different `PasswordFile`s?

> But when processing the request in the browser, I don't see that the `404` status code is showing a `200` response.

I don't think I understand what you mean by this, maybe you can rephrase?

**Comment by Zer0S2m** [comment]
Yes, you are right. Somewhere I missed the ready file authorization configuration. I will study carefully!

> But when processing the request in the browser, I don't see that the `404` status code is showing a `200` response.

When I went to the authorization user interface through the browser and entered the data for authorization, I noticed that the response code was 200.
I'm a little confused in the code where the [authorization request](https://github.com/gocd/gocd-filebased-authentication-plugin/blob/master/gocd-filebased-authentication-plugin/src/main/java/cd/go/authentication/passwordfile/executor/IsValidUserRequestExecutor.java#L55C1-L61C52) is processed:
```java
final User found = find(username, authConfig);

if (found != null) {
    return new DefaultGoPluginApiResponse(200);
}

return new DefaultGoPluginApiResponse(404);
```
Theoretically, if the user is found, it returns a 200 response code, but in my case, I was waiting for a 404 response. I may have missed many factors.

**Comment by Zer0S2m** [comment]
Yes, you were right. I found the configurations for file-based authorization in another xml file along the path: **`/etc/go/cruise-config.xml`** and **`/var/lib/go-server/db/config.git/cruise-config.xml`**

Thank you for your help and your time!

**Comment by chadlwilson** [comment]
`/etc/go/cruise-config.xml` is the main config. The other is a source controlled history of the config that the server maintains. 

You shouldnt edit the second one directly. If you edit the first one directly you may need to restart the server to pick up changes because normally the server maintains this config file and changes are made via the servers admin UI or APIs.
