### ISSUE TITLE
gocd Kubernetes elastic agent keep rebuild in loop 

### ISSUE THREAD

**Issue by ankujuniyal** [gocd/gocd#11865]
##### Issue Type
- Bug Report

##### Summary

Task in job keep rebuild after 10 minutes, and every time new elastic agent assigned in every loop.  While if i use static agent on that case job run fine.  on elastic agent i got "shutdown single"

##### Environment
we are using kubernetes elastic agent. in task I have custom command "ping localhost"

On agent logs i am getting. 
```plain
wrapper  | TERM trapped.  Shutting down.
jvm 1    | 2023-08-11 10:03:56,503 INFO  [ShutdownThread-5] AgentProcessParentImpl$Shutdown:198 - Shutdown hook invoked. Shutting down Process[pid=146, exitValue="not exited"]
wrapper  | <-- Wrapper Stopped
```

###### Basic environment details
* Go Version: `23.3.0 (16991-f38981e8aa684d63ac96f517996cd888eff37640)`
* JAVA Version: `17.0.8`
* OS: `Linux 4.18.0-372.59.1.el8_6.x86_64`
* Elastic agent Version: Kubernetes based Elastic agent plugin for GoCD  3.9.0-453

##### Log snippets

```
[go] Received request to create a pod for job JobIdentifier{pipelineName='alt-shared-library_sit', pipelineCounter=64, pipelineLabel='64', stageName='alt-shared-library_sit', stageCounter='3', jobName='alt-shared-library_sit_job', jobId=6,785} in cluster https://api.ocp.india.com:6443 at 2023-08-14 07:01:13 +00:00

[go] Start to prepare alt-shared-library_sit/64/alt-shared-library_sit/3/alt-shared-library_sit_job on gocd-agent-consolidated-5401cbe5-6d3c-48c8-a873-919ba5fff9ce [/go]

[go] Start to build alt-shared-library_sit/64/alt-shared-library_sit/3/alt-shared-library_sit_job on gocd-agent-consolidated-5401cbe5-6d3c-48c8-a873-919ba5fff9ce [/go]

[go] Task: shtook: 0.107s

[go] Task: pwd took: 0.102s

[go] Task: ping localhost

[go] Received request to create a pod for job JobIdentifier{pipelineName='alt-shared-library_sit', pipelineCounter=64, pipelineLabel='64', stageName='alt-shared-library_sit', stageCounter='3', jobName='alt-shared-library_sit_job', jobId=6,786} in cluster https://api.ocp.india.com:6443 at 2023-08-14 07:12:38 +00:00

[go] Start to prepare alt-shared-library_sit/64/alt-shared-library_sit/3/alt-shared-library_sit_job on gocd-agent-consolidated-687a36e4-5f07-4432-9273-9eb643de7970 [/go]

[go] Start to build alt-shared-library_sit/64/alt-shared-library_sit/3/alt-shared-library_sit_job on gocd-agent-consolidated-687a36e4-5f07-4432-9273-9eb643de7970 [/go]

[go] Task: shtook: 0.7s

[go] Task: pwd took: 0.102s

[go] Task: ping localhost

[go] Received request to create a pod for job JobIdentifier{pipelineName='alt-shared-library_sit', pipelineCounter=64, pipelineLabel='64', stageName='alt-shared-library_sit', stageCounter='3', jobName='alt-shared-library_sit_job', jobId=6,787} in cluster https://api.ocp.india.com:6443 at 2023-08-14 07:23:38 +00:00

[go] Start to prepare alt-shared-library_sit/64/alt-shared-library_sit/3/alt-shared-library_sit_job on gocd-agent-consolidated-4f38a290-7196-48f6-a012-b3c1305ad0b2 [/go]

```

##### Code snippets/Screenshots
```
ping localhost
```

**Comment by chadlwilson** [comment]
What's in the rest of the elastic agent container logs?

And which agent image are you using for your elastic agent?

Are your static agents in kubernetes? Do they use the same agent container image?

Looks like the job is stuck and being timed out by GoCD (you have job timeouts configured)

Pods may not respond to localhost pings depending on your kubernetes or pod networking setup so it might be expected for them to hang if you gave no timeout to the ping command and the traffic is being dropped in the pod sandbox.

**Comment by ankujuniyal** [comment]
And what is "auto_register_timeout" in elastic agent configuration. If i change default value from 10 minutes to 20 minutes, my job keep running for 20 minutes after that new pod get created.

**Comment by chadlwilson** [comment]
I can't really reconcile what you have shared above with what you say is happening. If you share what is displayed in the job console logs (on the server UI) that will probably help clarify what is happening.

However, my **guess** is that some permissions are missing for the GoCD Server that is preventing the kubernetes elastic agent plugin from keeping track of the pods it has created, so it thinks they have not been created, and is killing them. You might want to check the security token that you have created to make sure it has the right permissions.

If you are **not** using the GoCD official helm chart to install, perhaps compare your role to https://github.com/gocd/helm-chart/blob/master/gocd/templates/gocd-cluster-role.yaml - which role you are using to generate the security token (in addition to double checking [here](https://github.com/gocd/kubernetes-elastic-agents/blob/master/docs/configure_cluster_profile.md))

Also, make sure you are using the [latest version of the kubernetes elastic agent plugin](https://github.com/gocd/kubernetes-elastic-agents/releases/tag/v3.9.0-453) to avoid confusion - you haven't shared the specific plugin version above (`20.9.0` is the minimum compatible server version, not the plugin's version)

**Comment by chadlwilson** [comment]
This doesn't seem like a bug at this stage, if you can supply additional information that indicates otherwise we can reopen.

**Comment by ankujuniyal** [comment]
Sorry my bad here is agent details. 

* Elastic agent Version: Kubernetes based Elastic agent plugin for GoCD  3.9.0-453

## job logs 
```
    64 bytes from ::1: seq=616 ttl=64 time=0.051 ms
    64 bytes from ::1: seq=617 ttl=64 time=0.055 ms
    64 bytes from ::1: seq=618 ttl=64 time=0.045 ms
    64 bytes from ::1: seq=619 ttl=64 time=0.059 ms
    64 bytes from ::1: seq=620 ttl=64 time=0.053 ms
    64 bytes from ::1: seq=621 ttl=64 time=0.055 ms
    64 bytes from ::1: seq=622 ttl=64 time=0.051 ms
    64 bytes from ::1: seq=623 ttl=64 time=0.051 ms
    64 bytes from ::1: seq=624 ttl=64 time=0.061 ms
    64 bytes from ::1: seq=625 ttl=64 time=0.049 ms
    64 bytes from ::1: seq=626 ttl=64 time=0.055 ms

[go] Received request to create a pod for job JobIdentifier{pipelineName='alt-shared-library_sit', pipelineCounter=64, pipelineLabel='64', stageName='alt-shared-library_sit', stageCounter='3', jobName='alt-shared-library_sit_job', jobId=6,786} in cluster https://api.ocp.india.com:6443 at 2023-08-14 07:12:38 +00:00

[go] Start to prepare alt-shared-library_sit/64/alt-shared-library_sit/3/alt-shared-library_sit_job on gocd-agent-consolidated-687a36e4-5f07-4432-9273-9eb643de7970 [/go]

[go] Start to build alt-shared-library_sit/64/alt-shared-library_sit/3/alt-shared-library_sit_job on gocd-agent-consolidated-687a36e4-5f07-4432-9273-9eb643de7970 [/go]
```


### ****

**Comment by chadlwilson** [comment]
If you are just doing `ping localhost` that will go forever by design. You need to make sure the process actually exits or your task won't finish.

e.g `ping -c 10 localhost`
