### ISSUE TITLE
Generates unrunnable maven commands given multiple arguments

### ISSUE THREAD

**Issue by anthonygreen** [gocd/gocd#1187]
The command

    /usr/local/bin/mvn

    clean install -Pnonforge

produces an error

    Unknown lifecycle phase "install -Pnonforge". 

(although the same command runs fine from bash)
 
    install 

runs fine (but won't complete in this build process)

**Comment by arvindsv** [comment]
Can you show the XML config snippet for this?

**Comment by anthonygreen** [comment]
Its what you'd expect:
    <exec command="/usr/local/bin/mvn" workingdir="framework/OSMF" >
      <arg>install -Pnonforge</arg>
    </exec>.

**Comment by arvindsv** [comment]
Right, that's what I thought. That's the equivalent of running:

```
$ mvn 'install -Pnonforge'
[ERROR] Unknown lifecycle phase "install -Pnonforge". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
```

Can you try this instead?

```
<exec command="/usr/local/bin/mvn" workingdir="framework/OSMF" >
  <arg>install</arg>
  <arg>-Pnonforge</arg>
</exec>
```

It should be the equivalent of running: ```mvn 'install' '-Pnonforge'```

**Comment by anthonygreen** [comment]
The instructions to place each argument on a new line obviously wasn't clear enough for me. :-/

**Comment by wildone** [comment]
<arg> =  1 arg, it would have said <args> if this wasn maven... :)
