### ISSUE TITLE
Authenticating API calls using auth plugin does not work

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1193]
Related to #851 

Could not find a way to pass on the credentials (to be authenticated by a plugin) while making a call to the API.
Even if we were to do this in multiple steps, ie. the authentication as a part of some call (to http://localhost:8153/go/plugin/interact/github.oauth.login/index) and use the same session for the later ones, could reach only as far as the login screen on github using the auth url. 

In this case I was using a github plugin, so I could potentially find other ways of setting tokens etc in the call but there needs to be a standard way of authenticating APIs in Go immaterial of the plugin that would be used behind the scenes.

**Comment by srinivasupadhya** [comment]
if plugin implements password based authentication then `username:password` in api should be passed to plugin for autentication. if not then its assumed its web based, atleast the current implementation assumes that.

**Comment by jyotisingh** [comment]
>> if not then its assumed its web based, atleast the current implementation assumes that.

Well @srinivasupadhya, the whole point of an auth plugin is so people could choose what kind of authentication implementation they want. Once you give that liberty and then take away API access, it would be a bit of a problem. The current implementation doesnot take care of that which is totally fine, this issue is just a record of the fact that API access is limited. We could decide if the support for APIs need to be added later or never based on the consensus or ofcourse @arvindsv. 

PS: Don't want to screw up your honeymoon :stuck_out_tongue: , lets talk more once you are back.

**Comment by arvindsv** [comment]
Ok, you two talk about it. Then we can take a call. I think the API should be flexible enough to allow someone to replace the Go login screen with their own. Maybe that means credentials need to be passed in? Don't know. Haven't thought enough about it.

**Comment by zabil** [comment]
Can be solved with #1246

**Comment by arvindsv** [comment]
Closing. This whole area has been revamped.
