### ISSUE TITLE
Initial lines of large console-logs are missing

### ISSUE THREAD

**Issue by chopraapooja** [gocd/gocd#1196]
Found In :- experimental release15.2.0-2029 

Steps to reproduce : 
1) Set up a pipeline with a job containing task which produce large amount of console logs (for e.g. simplest can be "cat go-server.log"  or any another large file near around 10 MB).
2) Look at the first few lines of the console logs from console log tabs on the job details page. Initial logs which tell about job start and preparation steps will miss as per shown in screenshot. And RAW output will also miss those logs .

![screen shot 2015-06-05 at 12 30 53 pm](https://cloud.githubusercontent.com/assets/10117539/8002632/15d397c2-0b8e-11e5-873e-29cee56537a1.png)

**Comment by ketan** [comment]
@chopraapooja - are you able to reproduce this again?

**Comment by ketan** [comment]
It appears that this is happening when a huge amount of log ~10mb is rendered in a very short time.

To reproduce - 

`$ cat huge-10-mb-log-file` # this will certainly fail with console log's head truncated
`$ cat huge-10-mb-log-file | pv --rate-limit 100k` # this will work as expected
