### ISSUE TITLE
Job setting "Run on all agents" does not work for 0 agents

### ISSUE THREAD

**Issue by webmaster128** [gocd/gocd#1197]
I needed to deactivate my only machine with resource `osx10.9`. In order to keep CI working, I set the following job settings in my `test` stage:

```
Job Name*: OSX10.9
Resources: osx10.9, 
Job Timeout: Use default (Never)
Run Type: Run on all agents
```

where I have 0 agents with resource `osx10.9`.

Now the mini-documentation (tooltip at "?") states

>  Job will run on all agents that match its resources (if any). If you’re using the Enterprise Edition, only agents in the same environment as this job’s pipeline will pick up the job. This option is particularly useful when deploying to multiple servers.

but I get the error

> Failed to trigger stage [test] pipeline [xxx] [Jun-05 13:43:04]
> Could not find matching agents to run job [OSX10.9] of stage [test].

This is especially annoying because I don't see another easy way to deactivate a job.

**Comment by srinivasupadhya** [comment]
But a "Run on all agents" job with no matching agent is an error scenario for Go. What do you suggest the behaviour should be? the stage goes green with the job not running at all?

And the message:
> If you’re using the Enterprise Edition, only agents in the same environment as this job’s pipeline will pick up the job.

is incorrect now since there is nothing called "Enterprise Edition". we will fix that.

**Comment by webmaster128** [comment]
> But a "Run on all agents" job with no matching agent is an error scenario for Go. What do you suggest the behaviour should be? the stage goes green with the job not running at all?

As a mathematician I expect that running on `all = 1` behaves exactly like running on `all = 0`, i.e. success as if the job did not exist.

That might have undesired effects in practice. As a workaround I could live with an option to deactivate a job.
