### ISSUE TITLE
jobStatus.json never stops after a job finishes

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1204]
From - https://github.com/gocd/gocd/pull/1174#discussion_r31886943

> I see that after #1130 was merged, the jobStatus.json call never stops, even after a job has gone green or red. It might be useful to fix that too, so that this call does not turn out to be a bottleneck.

**Comment by zabil** [comment]
[this](https://github.com/gocd/gocd/blob/8c55b3df7ae819ca9e2baaf6d9ceff9490e250d3/server/webapp/WEB-INF/rails.new/app/assets/javascripts/build_output_observer.js#L44) should has stopped the polling but ```this.is_output_empty``` is always false even after the build's completed.

**Comment by zabil** [comment]
```
   _update_live_output_raw: function (build_output) {
        var is_output_empty = !build_output;
        var buildoutputPreElement = $('buildoutput_pre');
        if (!is_output_empty && buildoutputPreElement) {
...
```

[Checks](https://github.com/gocd/gocd/blob/8c55b3df7ae819ca9e2baaf6d9ceff9490e250d3/server/webapp/WEB-INF/rails.new/app/assets/javascripts/build_output_observer.js#L73) for ```buildoutput_pre``` which (earlier) is not rendered when the job completes setting the right flags to pause the observer.

[This](https://github.com/gocd/gocd/blob/8c55b3df7ae819ca9e2baaf6d9ceff9490e250d3/server/webapp/WEB-INF/rails.new/app/assets/javascripts/build_output_observer.js#L89) 

```
   _update_live_output_color: function(build_output) {
        var is_output_empty = !build_output;
        if (!is_output_empty) {
            var consoleElement = jQuery('#buildoutput_pre');

            // parsing the entier console output and building HTML is computationally expensive and blows up memory
            // we therefore chunk the console output into 1000 lines each and hand it over to the parser, and also insert it into the DOM.

            var lines = build_output.match(/^.*([\n\r]+|$)/gm);
            while(lines.length){
                var slice = lines.splice(0, 1000);
                var htmlContents = this.ansi_up.ansi_to_html(slice.join("").escapeHTML(), {use_classes: true});
                consoleElement.append(htmlContents);
            }
        }
        return is_output_empty;
    },
```
does not do that.

**Comment by ketan** [comment]
I think the root cause is that the BuildOutputObserver is invoked on every tick of [`DashboardPeriodicalExecuter`](https://github.com/gocd/gocd/blob/8c55b3df7ae819ca9e2baaf6d9ceff9490e250d3/server/webapp/WEB-INF/vm/build_detail/build_detail_page.vm#L173-L176) with no feedback going into the DashboardPeriodicalExecuter to turn it off on certain events.

**Comment by chopraapooja** [comment]
I'm working on this.

**Comment by juhijariwala** [comment]
It works fine. verified on Go Version: 15.3.0(2409-0256d8f868257a)

**Comment by zabil** [comment]
PR - #1304
