### ISSUE TITLE
Material authentication changing to pipeline is not picking latest git credentials

### ISSUE THREAD

**Issue by Pramodspraxa** [gocd/gocd#12058]
##### Issue Type

- Bug Report

##### Summary

- We have many pipelines setup in which we have added azure git as material. After some days token added in Git material is expired. So we updated git token in all pipelines. When tried to execute pipeline again, but still it is giving error - 
[go] Job Started: 2023-09-29 08:38:09 CEST
[go] Start to prepare Pipeline1/281/Build-Stage/1/Pipeline1-Job-runOnAll-1 on WIN-2D15LVA1HTP [C:\Program Files (x86)\Go Agent]
[go] Start to update materials.

[go] Start updating files at revision REVISION from https://******@dev.azure.com/git-repo-url
[GIT] Fetching changes
STDERR: fatal: Verification code expired before contacting the server
STDERR: bash: line 1: /dev/tty: No such device or address
STDERR: error: failed to execute prompt script (exit code 1)
STDERR: fatal: could not read Password for 'https://e3yfws****@dev.azure.com/git-repo-url': No such file or directory
git fetch failed for [https://******@dev.azure.com/git-repo-url]

###### Basic environment details

* Go Version: 23.1.0
* OS: windows

##### Steps to Reproduce

1.  Create a pipeline and add a material info to that pipeline.
2.  Now trigger pipeline after setup some jobs. It should works fine.
3.  Now let's say if this material token is expired, then need to change it's token.
4.  Now change material's token value with new value.
5.  Run the pipeline.
6.  It will always pick old git material credential token and will give the error as mentioned above.

##### Expected Results

1. It should pick latest material credential token instead of old one.
##### Actual Results

1. It is always picking initial credential token.
##### Tried approaches -
1. Tried to restart gocd agent and gocd server both. Results are same.
2. Tried to clone a pipeline from existing and changed git material token value in this cloned pipeline. And executed, it works fine.

##### Code snippets/Screenshots
[go] Job Started: 2023-09-29 08:38:09 CEST
[go] Start to prepare Pipeline1/281/Build-Stage/1/Pipeline1-Job-runOnAll-1 on WIN-2D15LVA1HTP [C:\Program Files (x86)\Go Agent]
[go] Start to update materials.

[go] Start updating files at revision REVISION from https://******@dev.azure.com/git-repo-url
[GIT] Fetching changes
STDERR: fatal: Verification code expired before contacting the server
STDERR: bash: line 1: /dev/tty: No such device or address
STDERR: error: failed to execute prompt script (exit code 1)
STDERR: fatal: could not read Password for 'https://e3yfws****@dev.azure.com/git-repo-url': No such file or directory
git fetch failed for [https://******@dev.azure.com/git-repo-url]

**Comment by chadlwilson** [comment]
Is your GoCD version definitely 23.1.0? (Or did you mean 21.3.0?)

**Comment by Pramodspraxa** [comment]
Thanks for reaching me out. 
Sorry for my bad for version number. Below is the correct version.

GoCD Version: 22.3.0

![image](https://github.com/gocd/gocd/assets/51744379/3075f794-d083-4e24-8027-f407d6f887f9)

**Comment by chadlwilson** [comment]
The message 'Verification code expired before contacting the server' looks weird to me, and doesn't look like a normal token error, but you haven't detailed the specific mechanism you are trying to use. How do you know it's using the original credential?

An issue basically as you are describing was fixed in 22.2.0 with #10493 and thus i don't think this can be replicated based on the description here, which means we are probably not going to get anywhere unless you give much more specific instructions that you can replicate from scratch.

Anyway, perhaps look through the issues linked to that PR and make sure you have updated the materials consistently. Validate whether test connectivity works (or not) on the material and what error it gives (or not).

**Comment by chadlwilson** [comment]
Also, do you have the username in the actual username field, or hardcoded into the URL?

**Comment by Pramodspraxa** [comment]
> Also, do you have the username in the actual username field, or hardcoded into the URL?

It is hardcoded in URL itself. This is because Azure git work directly with token value. So token value is included in URL itself like below pattern - 

https://TOKEN_VALUE@GIT_URL

Also as I mentioned when I am cloning the pipeline and trying to run that, then new pipeline is working as expected with new token.

**Comment by chadlwilson** [comment]
Hardcoding into the URL is bad for security reasons (with that syntax it is treating it as the username and should be functionally equivalent to setting the username in GoCD, although not sure off top of my head if GoCD allows you to set a username without a password).

Putting that aside, that should reduce the chance that there are issues across pipelines. You might want to check that the username and password fields are fully cleared for that material in that pipeline.

It'd help if you could capture the XML representing that pipelines material from admin > config XML before and after so we can figure out what might need to be improved here. If you share that XML fragment but (redact the values)  for the material and compare the XML fragment from cloned material to the original problematic one, that would help.

**Comment by Pramodspraxa** [comment]
> While this doesn't get to the root of your problem (there may be some bug here when mixing username and username-hardcoded-in-URL), I believe with Azure DevOps you can also use a pattern like
> 
> username = anything password = PAT
> 
> Which would also allow you to keep the URL "clean" and more secure since GoCD will treat the username/password as sensitive values to be encrypted and redacted from logs.

I tried this approach and it worked fine. I copied username and password both from Azure DevOps and one pipeline worked fine. Hope all will work as expected.

Thank you very much for your help.

**Comment by chadlwilson** [comment]
I'm glad you found a way to fix your problem, however it doesn't help us explain what was going wrong with your earlier approach (while it was less secure to include a PAT in the URL, it probably should have worked and the failure is confusing and shouldn't really behave like that).

Unfortunately from the redacted error message it's hard for me to tell, which I was asking to see the config XML so we could figure out what was being sent.

What I suspect is that the username or password fields on the material might have still had values which were overriding the value in the URL, or something like that, but I can't really be sure without seeing how the config XML looked like.

It'd be useful if you could share that comparison on the broken pipeline (`Pipeline1` above). You could look at the "Config Changed" link between the bad and good stage runs on the Stage Details:

![image](https://github.com/gocd/gocd/assets/29788154/09ca8632-7a54-4c47-b58f-bf41af3b8e4e)

And share the redacted diff, e.g

```
@@ -1179,11 +1179,11 @@
--
</property>
<property>
<key>AWSAccessKeyId</key>
-          <encryptedValue>AES:BEFORE</encryptedValue>
+          <encryptedValue>AES:AFTER</encryptedValue>
</property>
<property>
<key>AWSSecretAccessKey</key>
-          <encryptedValue>AES:BEFORE</encryptedValue>
+          <encryptedValue>AES:AFTER</encryptedValue>
</property>
--
<property>
<key>EnvironmentVariables</key>
@@ -1389,7 +1389,7 @@
</property>

```

**Comment by Pramodspraxa** [comment]
Hi [chadlwilson](https://github.com/chadlwilson), I checked the stage details as you described in previous message and found that for that one pipeline, the only change when it was failed and then it started working using credentials is - 

-        <git url="https://TOKEN_VALUE@GIT_URL" branch="dev" materialName="material1" />
+        <git url="https://GIT_URL" branch="dev" username="USER_NAME" encryptedPassword="ENCRYPTED_PASSWORD" materialName="material1" />

I have not pasted screenshot here for above XML changes because it contains secret (so edited and pasted lines here).

**Comment by chadlwilson** [comment]
Hmm, okay, thanks for taking a look. Unfortunately, still a bit of a mystery as there’s nothing obviously weird there. Perhsps was a typo in the PAT or a character not encoded properly or a different material with the same identical URL and branch that had something weird configured at the time.

**Comment by chadlwilson** [comment]
Closing this for now as I can't replicate the issue. If there is an issue I suspect it relates to having a username hardcoded in the URL and GoCD logic for handling and de-duplicating material checks for such URLs - possibly the username (a token here) is extracted prior to de-duplication but then the wrong one is applied at runtime.

If anyone else has a similar issue and can help debug it, please comment and we can re-open.
