### ISSUE TITLE
Auto delete old artifacts does not keep latest artifact

### ISSUE THREAD

**Issue by joerayme** [gocd/gocd#1207]
When enabling the 'auto delete old artifacts' feature, Go will delete the oldest artifacts it can, even if that artifact happens to be from the latest run of a pipeline. When downstream pipelines are then run, they fail to fetch the upstream pipeline's artifact and the upstream has to be run again before the downstream can be.

**Comment by jyotisingh** [comment]
will be handled as a part of #410

**Comment by d-led** [comment]
cross-posting this here too, as it might help @joerayme  https://github.com/d-led/gorebuild
