### ISSUE TITLE
SSL connection errors/warnings with modern browsers

### ISSUE THREAD

**Issue by griffint61** [gocd/gocd#1210]
According to both Mozilla Firefox (version 38) and Google Chrome (version 43) Go server is using obsolete encryption technology for the https connection. The browser complaint appears to be related to the "TLS intolerance" of the Go server.

Firefox says:
Broken Encryption (TLS_RSA_WITH_RC4_128_SHA, 128 bit keys, TLS 1.2)
Parts of the page you are viewing were not encrypted or the encryption is not strong enough before being transmitted over the Internet.
Information sent over the Internet without encryption can be seen by other people while it is in transit.

Chrome says:
Your connection to go.example.com is encrypted with obsolete cryptography.
The connection uses TLS 1.2.
The connection is encrypted using RC4_128, with SHA1 for message authentication and RSA as the key exchange mechanism.

Red Hat's explanation of the Firefox 38 changes may be found here: https://access.redhat.com/articles/1422403

**Comment by arvindsv** [comment]
Should be fixed as a part of #1087 (or just after). Need to remove cipher restrictions.

**Comment by ketan** [comment]
Tested on `15.2.0(2241-b35653720b5497)` with the following CLI args and browsers

- Chrome 44.0.2403.81
- Firefox 38

### Default ciphers

```shell
$ bash ./server.sh
```

### Slightly secure ciphers

```shell
$ SERVER_STARTUP_ARGS="-Dgo.ssl.protocols.exclude=SSLv3 -Dgo.ssl.ciphers.include=TLS_DHE_RSA.*,TLS_ECDHE.* ­Dgo.ssl.ciphers.exclude=.*NULL.*,.*RC4.* -Dgo.ssl.protocols.include=TLSv1.2 -Dgo.ssl.renegotiation.allowed=N" ./server.sh
```

### ECDHE ciphers only

```shell
$ SERVER_STARTUP_ARGS="-Dgo.ssl.protocols.exclude=SSLv3 -Dgo.ssl.ciphers.include=TLS_ECDHE.* -Dgo.ssl.ciphers.exclude=.*NULL.*,.*RC4.* -Dgo.ssl.protocols.include=TLSv1.2 -Dgo.ssl.renegotiation.allowed=N" bash ./server.sh
```

**Comment by piotrekjanisz** [comment]
@ketan 
Hello Ketan, 
What are the default ciphers used by GO?

**Comment by ketan** [comment]
@piotrekjanisz - Go does not enforce any cipher suites. And uses whatever cipher suites are defaulted to by the JVM.

In some cases where the agent and server are on JVMs with incompatible default cipher suites, Go allows you to tweak the cipher suite include/exclude params so as to make the server and agent cipher suites compatible with each other.

Are you seeing any issues with cipher suites?

**Comment by piotrekjanisz** [comment]
@ketan
Thank you for a quick response! We've recently upgraded go from 14.3 to 15.3.1, which caused our load balancer to fail to connect to the GO server with "Unknown SSL protocol error in connection" error. 

We will try to tweak the ciphers.

**Comment by ketan** [comment]
This **could** also be a case of an old JVM version with deprecated ciphers — I'd suggest upgrading your JVM and the nss library (if you're on linux) to the latest version.

See https://github.com/gocd/gocd/issues/1360 for more details.
