### ISSUE TITLE
Agent API improvements

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1212]
Brand new API for handling agents in Go
Covers parts of 
#849, #264, #958, #1100 

 #1122

Adds support for, changing host name, adding resources, enabling or disabling agents.

**Comment by zabil** [comment]
Testing notes on 15.2.0-2067 (07d65665c731a615f6a6943cce0fd03440eb4a9e)

* PATCH to /api/agents/{uuid} with invalid param { enable : "invalid" } returns a 200 and does not change the state.

@arvindsv @ketan We need to take a call on how to handle addition of resources to the agent. In in the current PATCH for resources there's no locking.

Option 1
If we are to implement optimistic locking. We have to force a GET and PUT operation with etags (throwing a conflict if the etag version changes) 
  
Limit operations with PATCH
e.g 
{ command: 'addResource', data : resource }
{ command: 'deleteResource', data : resource }

But that means coming up with a consistent PATCH operation all operations on the resource.

**Comment by arvindsv** [comment]
> IMO it's a call if we need to support optimistic or pessimistic locking on a resource based on it's usage.

I don't mind leaving it with no locks. We have a standard way to upgrade APIs now (with the negotiation), and we can add it if we need it. Otherwise, we can try and make it consistent by having only one command. Say, a "changeTo" command, which will change the current resources to whatever the data shows.

I don't mind leaving it the way it is, knowing we can upgrade it if needed.

**Comment by ketan** [comment]
> Limit operations with PATCH
> e.g 
> { command: 'addResource', data : resource }
> { command: 'deleteResource', data : resource }

I thought about it a bit, and it feels more like perform an RPC than a PATCH via REST. I'm not a fan of this approach.

**Comment by ketan** [comment]
> I don't mind leaving it with no locks. We have a standard way to upgrade APIs now (with the negotiation), and we can add it if we need it.

In the interest of consistency – in some config change operations, we will need to perform this locking. I'd much rather start now than have multiple versions of APIs for various config resources which vary by just having a config header. This IMO is a very small change to make, and I can submit a PR if @zabil  and @arvindsv are on board.

**Comment by arvindsv** [comment]
> This IMO is a very small change to make

Can you explain how this will be, with an example like @zabil did? I ask because you said you don't like the approach @zabil suggested.

I'd also like to put @jyotisingh on the spot and make her the final decision maker on decisions such as this. :) I'm just someone with opinions.

**Comment by ketan** [comment]
> Can you explain how this will be, with an example like @zabil did? I ask because you said you don't like the approach @zabil suggested.

Zabil brought two separate ideas. (a) locking and (b) perform operations rather than set state.

I like (a), dislike (b).

Zabil linked this a while ago on gitter, can't find that link anymore.

``` bash
$ curl http://build.go.cd/go/api/agents/:uuid -I
HTTP/1.1 200 OK
ETag: "82b04f0f4ef21875166c19aa3b1b89f2"
```
Then PATCH the resource - 

```bash
$ http://build.go.cd/go/api/agents/:uuid \
    -XPATCH \
    -d '{stuff...}' \
    -H'If-None-Match:BAD-SANTA'
HTTP/1.1 409 CONFLICT
```

Then PATCH the resource with the right etag - 

```bash
$ http://build.go.cd/go/api/agents/:uuid \
    -XPATCH \
    -d '{stuff...}' \
    -H'If-None-Match:82b04f0f4ef21875166c19aa3b1b89f2'
HTTP/1.1 200 OK
ETag: "356aeae4ff34997ab7b23d0b035f7f50"
```

**Comment by ketan** [comment]
The link that @zabil pointed to - http://fideloper.com/etags-and-optimistic-concurrency-control

**Comment by ketan** [comment]
Unlike how our APIs currently function (`X-Cruise-MD5`), the Etag here is a hash of the resource being updated, not the the state of the entire config.

**Comment by zabil** [comment]
Ok need a yes or no for etag support, I think it's a great feature to have while patching.

Meanwhile in testing land along with issues mentioned initially when I run
```
curl -X PATCH -H "Accept: application/vnd.go.cd.v1+json" http://localhost:8153/go/api/agents
```

I get 

```
<!-- lots of html -->
<body>
  <!-- This file lives in public/422.html -->
  <div class="dialog">
    <h1>The change you wanted was rejected.</h1>
    <p>Maybe you tried to change something you didn't have access to.</p>
  </div>
  <p>If you are the application owner check the logs for more information.</p>
</body>
```
Instead of a graceful failure or return of the resource. Make this a json?

Any reason why we are upper casing "Disabled"
```
  "sandbox": "/Users/zabilcm/Testing/15.2/Go Agent.app",
  "status": "Disabled",
  "operating_system": "Mac OS X",
```

The ui shows it in lower case, Did not dig into where the problem is, but can we makes sure that we preserve the case of the data? The consumer should choose to play around with it.

**Comment by ketan** [comment]
> Any reason why we are upper casing "Disabled"
> ```
>   "sandbox": "/Users/zabilcm/Testing/15.2/Go Agent.app",
>   "status": "Disabled",
>   "operating_system": "Mac OS X",
> ```

That's an enum's toString() that is doing it. I think lowercasing is a good idea. I'll fix this along with etag support if most people on the team are OK with it.

**Comment by ketan** [comment]
I thought about this optimistic locking a bit more over the weekend -

**Comment by zabil** [comment]
One more issue to check on authentication

```
curl -H "Accept:application/vnd.go.cd.v1+json" http://localhost:8153/go/api/agents/82d31545-de97-493a-9c68-b54df23b5c59
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 401 Full authentication is required to access this resource</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /go/api/agents/82d31545-de97-493a-9c68-b54df23b5c59. Reason:
<pre>    Full authentication is required to access this resource</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>

</body>
</html>
```

As we are using the new api this should be handled better.

**Comment by zabil** [comment]
On: experimental release15.2.0-2143 (58ceb4eb99414bb4c24803fbf23238dc0df2fd46)

Everything works, except that 
patching with

```
{ "enabled": "notaboolean"} 
```
returns a 200 OK without changing state, which is misleading. 
Can we make it return the right status code?

**Comment by zabil** [comment]
Verified on experimental release15.2.0-2149 (d0369fb00f85d395f6534a3a434b7a612d286f7b)
