### ISSUE TITLE
Server upgrade from 14.4.0 to 15.1.0 breaks LDAP authentication

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#1215]
## Description
Server upgrade from 14.4.0(1356-86064ef5ee28e0) to 15.1.0(1863-42e58c22aefd03) breaks established LDAP authentication method.
Re-import of the LDAP certificates is required in order for the auth to work.
`C:\Program Files (x86)\Go Server\jre\bin\keytool.exe -import -trustcacerts -alias <certificate alias name> -file <Our cert filename> -keystore "cacerts"`

## Expected Behaviour
LDAP authentication should work as it used to without the need to re-import the certificates.

> I'm opening this issue on behalf of the user who reported this bug.

**Comment by jyotisingh** [comment]
It appears that the certificates were imported to the bundled jre and then an upgrade of Go server was performed. Importing certificates to bundled java certificate store is not supported since the folder is wiped clean during upgrades. Closing the issue.
