### ISSUE TITLE
Clean working directory does not delete Symbolic Links on Windows

### ISSUE THREAD

**Issue by lostrouter** [gocd/gocd#1217]
When cleaning the working directory, GO is seeing a directory sym link as a directory and not a sym link.  version 14.4.0(1356-86064ef5ee28e0)

**Comment by chopraapooja** [comment]
We tried to reproduce the scenario with both file and directory symlink.

Go is able to clean working directory containing directory symlink (created with `mklink /D symlink directory`).

In case of file symlink (created with `mklink symlink directory`), it is treating it as the directory and failing to list it contents. Is this the scenario you are facing?

**Comment by lostrouter** [comment]
that would make sense.  that is where i went wrong.
