### ISSUE TITLE
Support smartos / pkgin / pkgsrc

### ISSUE THREAD

**Issue by fire** [gocd/gocd#1218]
Please support pkgsrc as a packaging method for smartos - illumos hosts. 

Although it is possible to manually migrate the pkgadd script via http://www.perkin.org.uk/posts/installing-svr4-packages-on-smartos.html. It would be helpful if it was officially supported.

**Comment by arvindsv** [comment]
@fire: If you're willing to do the work needed to make it happen, I'll take care of integrating it, making sure the installers are built on https://build.go.cd and available on http://go.cd/download.

Here's [the code](https://github.com/gocd/gocd/blob/master/tasks/buildr_extensions.rake#L265) used for building the Solaris package. [This part](https://github.com/gocd/gocd/blob/master/tasks/buildr_extensions.rake#L306) is probably the most interesting, and maybe the only part that needs to change? I don't know.

**Comment by arvindsv** [comment]
No response. Closing.
