### ISSUE TITLE
BUG You can inject HTML using git commit message.

### ISSUE THREAD

**Issue by wojtek-oledzki** [gocd/gocd#1219]
The git commit message is not escaped.
It breaks the pipeline preview if you have `</div>` in your commit comment.

**Comment by ketan** [comment]
Would you mind providing a screenshot?

Also do you see this break in other places like on the stage/job detail page and on pipeline history page?

**Comment by wojtek-oledzki** [comment]
The original commit message is
```
[GST-231] GOCD BUG TEST

This is a </div> and this is a <</div>> and this is
<b>bold</b> and this is <<b>> :)
```

![GIT Material](https://cloud.githubusercontent.com/assets/11490007/8165971/950f3e5a-138c-11e5-8710-fc7e1efcad37.png)
![Extra bit :)](https://cloud.githubusercontent.com/assets/11490007/8165974/a09d3a60-138c-11e5-8223-9b678bf5888f.png)
![screen shot 2015-06-15 at 18 32 27](https://cloud.githubusercontent.com/assets/11490007/8166019/05d09b98-138d-11e5-9d30-d48b3bdbcadb.png)

**Comment by mdaliejaz** [comment]
Verified. Works fine on 15.2.0(2137-4b43c73).
