### ISSUE TITLE
PDF user documentation cuts off verbatim text

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#1220]
In `user-documentation-15.1.0.pdf`, on page 364, the examples on how to schedule runs of pipelines are cut off so you can't see the URL you should send the requests to. There are several examples of this (cut off text) throughout the document.

**Comment by srinivasupadhya** [comment]
can this be raised on [documentation](https://github.com/gocd/documentation) repository?

**Comment by jyotisingh** [comment]
Moved to https://github.com/gocd/documentation/issues/173
