### ISSUE TITLE
Logs are missing in console-log tab (job-details page)

### ISSUE THREAD

**Issue by chopraapooja** [gocd/gocd#1221]
**Where it got noticed ?**
15.2.0(2090-8ab5f52f556748) experimental realese

**How to reproduce ?**
**Step1** Create a pipeline with a job and trigger it.
**Step2** After triggering pipeline, change the name of running job [make sure pipeline should be in running state when you change name].
**Step3** Check console log tab in job details page, it will be blank. 
**Step4** But in raw output, It will show some logs like "Job[pipeline]/[pipeline_counter]/[stage]/[stage_counter]/[old_job_name] not found."
These logs should also come in console log tab as well.

**Comment by zabil** [comment]
This is a regression.
We used to render the contents of the log (pointing to the same location as the raw output) on an iframe once a job completes. It does not do that any longer.

**Comment by ketan** [comment]
It appears that this is happening when a huge amount of log ~10mb is rendered in a very short time.

To reproduce - 

`$ cat huge-10-mb-log-file` # this will certainly fail with console log's head truncated
`$ cat huge-10-mb-log-file | pv --rate-limit 100k` # this will work as expected
