### ISSUE TITLE
Non-Java based plugins with JSON Plugin API

### ISSUE THREAD

**Issue by hatt** [gocd/gocd#1222]
Since the current plugin API is just sending JSON between the server and the plugins, is it possible to write plugins in languages that aren't Java or even in the JVM? I don't quite get how the plugins are executed but writing plugins in Ruby for example would much easier for my organisation and allow us to open source some pretty generic task plugins instead of calling APIs via curl requests in CLI tasks.

If it's already possible, a pointer to some documentation or examples would be great.

**Comment by ketan** [comment]
I have in the past written OSGi plugins in JRuby. I think I can pull out an example of a simple go plugin in JRuby that should be super useful and superquick to implement than a java plugin.

**Comment by hatt** [comment]
Hi @ketan, just following up on this, have you had a chance to dig up that example or got a link to anything you know of?
