### ISSUE TITLE
Command Execution Issue on Windows Agents in GOCD v23.3

### ISSUE THREAD

**Issue by sjagannaddam-mdsol** [gocd/gocd#12247]
Dear GOCD Support Team,

I am writing to report a critical issue we have encountered after upgrading our GOCD server from version 21.2 to 23.3. This issue is specifically related to the execution of certain commands on Windows agents.

Issue Description:
Our pipelines, which execute on Windows agents, are failing to recognize basic commands such as git pull and mkdir when run through "Custom Command" tasks. The same commands and pipelines were functioning correctly on the previous version (21.2) of the GOCD server.

Error Encountered:
The error we are encountering is as follows:

[go] Task: git pull
Took: 0.179s
Exited: 1
'"git pull"' is not recognized as an internal or external command, operable program or batch file.
This error is indicative of either a PATH environment issue or a change in command parsing in the newer version of GOCD.

Specifics of the Issue:

1. The issue seems to be isolated to Windows agents, as pipelines running on Linux agents perform without any issues.
Commands like git pull & mkdir are not recognized.

2. This problem is not agent-specific; the same agent works fine when attached to a GOCD server running version 21.2.
We suspect this could be related to changes in how custom commands handle spaces or command syntax in GOCD version 23.3.

Environment Details:
GOCD Version: 23.3
Operating System of GOCD Server: [Your Server's OS]
Operating System of Agents: Windows [Version]

Sample Pipeline Task Configuration:

<tasks>
              <exec command="git pull">
                <runif status="passed" />
              </exec>
              <fetchartifact artifactOrigin="gocd" srcdir="test" pipeline="" stage="Build" job="defaultJob">
                <runif status="passed" />
              </fetchartifact>
              <exec command="%DEPLOY_SCRIPT%">
                <runif status="passed" />
              </exec>
              <exec command="mkdir reports 2&gt;nul">
                <runif status="passed" />
              </exec>
              <exec command="IF DEFINED APP_IR_GENERATOR (%APP_IR_GENERATOR%)">
                <runif status="passed" />
              </exec>
              <task>

Request:
We seek your guidance on how to resolve this issue. Specifically, we would like to know:

If there are any known compatibility issues with command execution on Windows agents in GOCD version 23.3.
Any recommended changes or updates to our pipeline configurations that would rectify this problem.
If there is a workaround or patch available to address this issue.
We appreciate your prompt attention to this matter as it is impacting our deployment workflows significantly.

**Comment by chadlwilson** [comment]
Please see the thread at https://groups.google.com/g/go-cd/c/cIDKw1vac6k (and avoid raising the same topic in multiple places in future).

As mentioned in the thread, at some point I'll try and figure out whether you were accidentally relying on behaviour from previous releases which wasn't supposed to work (and "broken" in `22.2.0` when correcting other issues) or whether there was an unintentional regression. Suggestions to correct the problem are included there.

You can help by providing the requested screenshot.

**Comment by chadlwilson** [comment]
As noted in https://groups.google.com/g/go-cd/c/cIDKw1vac6k/m/4lJC_1GjAAAJ the change in this behaviour is caused by #10625 which was a fix for #4173, #2153, #10521. It seems you were accidentally misconfiguring your Windows tasks with the arguments inside the command, and relying on this buggy handling of spaces for them to work on Windows.

You should correct your task configs to ensure the arguments are configured separately to the command to execute (as the UI guides you to do), or per the examples in the Google Groups thread.
