### ISSUE TITLE
GoCD isn't parsing new config repo. No pipeliens are shown

### ISSUE THREAD

**Issue by miguel-cardoso-mindera** [gocd/gocd#12256]
##### Issue Type

- Bug Report

##### Summary

We are changing our repositories from bitbucket to github. I tried changing the config repo from "bitbucket.org/xxx/gocd-pipelines" to "github.com/xxx/gocd-pipelines" but now the config repo is not getting parsed
<img width="573" alt="image" src="https://github.com/gocd/gocd/assets/134504267/0f915325-f182-4f7e-a903-08d8e1cfdfae">

In the network tab in google chrome I get this error:
```
Status code: 404
{
    "message": "Repository `REPO_CONFIG_ID` does not define any configurations"
}
```

###### Basic environment details

* Go Version: `20.10.0`
* JAVA Version: `15.0.1`
* OS: `Linux 4.18.0-326.el8.x86_64`
* Browser vendor and version (if relevant): `Google Chrome`

##### Steps to Reproduce

1. Change material for config repository
2. 
3. 
4. 

##### Expected Results
I expect gocd to start using new repository for its config

##### Actual Results
I get 404 error and now no pipelines show up since gocd isn't parsing the config repo

**Comment by chadlwilson** [comment]
Please discuss such things within the community at https://groups.google.com/g/go-cd before raising issues here.

This sounds like a support/configuration issue with your repository, not a bug report. Expand the repo to see the full error, check the logs and material authentication credentials. Test the connection and see what it reports.

**Comment by miguel-cardoso-mindera** [comment]
Leaving a comment here for others, turns out I got very unlucky and GoCD ran out of space at the same time I switch config repos...
After clearing space in GoCD server, it was able to parse the new config repository
