### ISSUE TITLE
Go-Agent on a different subnet

### ISSUE THREAD

**Issue by lgwapnitsky** [gocd/gocd#12297]
I have certain servers on a different subnet than my gocd server. How do I register the agents? I've followed the docs at https://docs.gocd.org/current/advanced_usage/agent_auto_register.html, but I don't see where to specify the hostname/ip address of the gocd server.

**Comment by chadlwilson** [comment]
Auto-registration is an additional capability on top of basic agent installation so not directly relevant.

It depends how you are running your agents (direct installs on which operating system vs containers vs kubernetes vs elastic agents) but the GoCD server URL is a basic config property of any install. Look at https://docs.gocd.org/current/installation/installing_go_agent.html for the relevant OS or for containers check out the Docker Hub page for your agent image e.g. https://hub.docker.com/r/gocd/gocd-agent-alpine-3.18

These are all linked off the download page: https://www.gocd.org/download/#docker
