### ISSUE TITLE
Perforce Connections require special login to create tickets on Server and Agents

### ISSUE THREAD

**Issue by ghost** [gocd/gocd#123]
I tried to create a new pipeline and ran into problems when I got to Step 2: Materials.
I chose Perforce, then filled in the Server and Port, Username field(using a non-epiring service user), Password field and a valid View.
I then clicked "Check Connection" and no matter what I changed or did, I kept getting a failure to connect message talking about a bad password.

It was then suggested that I do the following steps, which pre-login(create a ticket) for my perforce user on the agent machine:

a.       On Windows, If not installed, install PsExec.exe. Get from Windows SysInternals PsTools zip file from Microsoft and copy to server host machine and any Windows agent machines.

b.      Open Command Window as Administrator

c.       Run in command window: psexec \<computername> -s –I cmd

```
                                                           i.      this will open a new command window.
```

d.      In new command Window run:

```
                                                           i.      set P4PORT=<perforce-host>:<perforce port>

                                                         ii.      p4 –u <perforce service user> login

                                                        iii.      at prompt: <password>

                                                       iv.      p4 tickets 
```
1.       this will display the perforce login tickets, there should be a new one for this user and port.

After doing this the CHECK CONNECTION button reported a success.

So the question is, if I have the correct connection information already entered, including username and password, why wasn't that enough?

Apparently this is a bug and I was asked to submit it here. Thanks. Please feel free to contact me for additional information if needed.

**Comment by sghill** [comment]
+1. We're facing the same issue with perforce.

**Comment by arvindsv** [comment]
Closing as stale.
