### ISSUE TITLE
Feature: send email alert to the Go admin when an agent is stuck on a cancelled job

### ISSUE THREAD

**Issue by griffint61** [gocd/gocd#1236]
When an agent gets stuck in the cancelled-job state for more than some configurable number of minutes, send an email alert to the Go administrator.

This should be a global setting for the Go server, not a pipeline, stage, or job setting.

**Comment by lenucksi** [comment]
Maybe it would also be interesting to make this a plugin endpoint so you can create plugins to execute custom actions such as an API call to some autoscaling tooling.
