### ISSUE TITLE
Add configuration property to specify the agent name that will be registered with the server

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#124]
The names of the agent when registered with the GO server is the hostname (or is some cases the FQDN) that is obtained by Java. This not configurable however if the hostname itself does not contain any semantic meaning then this name if not very useful when assigning resources or environments.

It would be great if the agent has a configurable property that is used when first registering itself to the server. This could be specified on the install command line.

Additionally having a user interface option on the server to modify the agent name would be useful.

**Comment by piyush0101** [comment]
:+1: 

Even if this is similar to the Jenkins Swarm Slaves, it would be quite useful. With swarm slaves, you can specify the name of the slave that is going to be registered to the Jenkins master.

**Comment by reidca** [comment]
This is still a pain point for us. We have automated the install,. registration and configuration of GO Agents onto our workstations and servers via Puppet and Powershell. When the servers boot they install GO and auto-register themselves.

We still have to manually edit the xml to change the name of the agent and provide some kind of semantic name. Otherwise diagnosing pipelines or just seeing what is going on is very hard.

**Comment by mikeycmccarthy** [comment]
Hi @rusio, that looks like it would be great for us, were there are any limitations around what the GUID could be? We spin up agents as docker containers as well, and we get the same issue when we spin up a new version of an agent.

**Comment by ketan** [comment]
Thank you all for the feedback (and patience).

I've just about wrapped up #958 (API method for renaming agent). This'll allow renaming an agent via the API. I'm looking to make a few more quick improvements to set the agent name when auto-registering agents.

I'm considering adding a property called `agent.auto.register.hostname` inside the agent's `autoregister.properties`. This property, if set, will set the hostname of the agent, and should be very useful when auto-registering agents.

I know that this is what has been asked a couple of times here, I just wanted to get a quick show of hands to see if anyone has a better idea about how registration could be done.

**Comment by reidca** [comment]
Hi Ketan, thank you so much for taking this on. This will be invaluable for us. I already use the autoregister.properties file for setting up the pre-registration key, environments and resources. The missing link has always been the agent name. Having this property will be very useful and will mean agent setup and registration will be fully-automatic.

The only other idea I had was to have an environment variable which could be used to control the hostname however with a combination of the API method and the auto register file I think we have enough.

**Comment by rusio** [comment]
We use the full hostname of the agent as a value for the GUID, which is actually not a valid GUID, but it makes it a lot easier to refer to agents in the configuration file. So an arbitrary unique value for the agent ID would be good, without enforcing it to be a GUID.

**Comment by mikeycmccarthy** [comment]
Many thanks @rusio, we're trying this right now. Our use case is we roll a new version of the Docker container which is the agent. What happens currently is the old one shows up as a lost connection and then the new one turns up, and we have to do some editing of the config file to get around the guid thing. 

Myself and @xabierlaiseca are just trying out now to see what happens when an agent is trying to register with the same guid (but a different IP). Hopefully Go will replace the existing 'lost' one, or it may well complain that someone else is trying to register. Hopefully it's the former :)

**Comment by ketan** [comment]
> Myself and @xabierlaiseca are just trying out now to see what happens when an agent is trying to register with the same guid (but a different IP). Hopefully Go will replace the existing 'lost' one, or it may well complain that someone else is trying to register. Hopefully it's the former :)

That'll work as long as 2 agents don't attempt to connect with the same uuid. This is really not recommended, unless you know what you're doing.

If two agents are polling with the same UUID, go will assign some work to one agent, and when the second agent comes along, the server will be really really confused and assign the same work again, until the first agent comes back, and the server keeps repeating this.

**Comment by reidca** [comment]
Will this be in release 15.2?

**Comment by ketan** [comment]
> Will this be in release 15.2?

Yes, this has already been merged in.

**Comment by reidca** [comment]
Thank you so much for taking this piece on and completing it so quickly. Can't wait to get my scripts modified to use it and make the agent installation and setup process 100% automatic.
