### ISSUE TITLE
Get Agent Lis

### ISSUE THREAD

**Issue by eleite77** [gocd/gocd#1241]

**Comment by eleite77** [comment]
Hello
Is it possible to use JQuery and request the list of the Go agents in XML format (not the Html one retrieve in the json file)?
thanks

**Comment by ketan** [comment]
You may find the Agents api [here](http://www.go.cd/documentation/user/15.1.0/api/agent_api.html). This API is going to be deprecated, and you will have better luck with the [new API](http://api.go.cd/#agents) that will be available starting with 15.2 due in a few weeks.

**Comment by ketan** [comment]
@eleite77 I'm going to close this issue unless you let me know if there's something specific that is missing in the existing (or new) API that you would like to see.
