### ISSUE TITLE
Implement a consistent authentication scheme for accessing API's

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1246]
With new authentication end point #851 In place we'll need something more secure than basic auth for access to the GO REST API resources. 

A solution is to have the user generated a token which can be used to access the API's. This can allow for more fine grained access without having to pass around credentials on your request.

You can also control authorization on the API's.
@jyotisingh @srinivasupadhya @arvindsv Please feel free to add to this.

**Comment by Webysther** [comment]
Any news about API access using token?

**Comment by dbalakirev** [comment]
I would like to expose the content of the "go/api/support" endpoint into the our monitoring (after projecting the data into proper prometheus metrics).

In order to retrieve the data I would like not to use passwords.

**Comment by arvindsv** [comment]
This has been revamped with auth endpoints and support for access tokens. Closing.
