### ISSUE TITLE
HTTP -> HTTPS redirect in loadBalancer leads to error code 422 when editing cruise-config.xml in gocd-server gui with and gocd-server error InvalidAuthenticityToken

### ISSUE THREAD

**Issue by oskarTeodor** [gocd/gocd#12485]
##### Summary

Editing cruise-config.xml gives error code 422 from server with error message in html: "The change you wanted was rejected.  Maybe you tried to change something you didn't have access to."

gocd-server container shows error:    

`LOG: 2024-01-31 10:44:30,401 WARN  [qtp2095985054-34] Rails:-2 - HTTP Origin header (https://byggare-bob.lm.se) didn't match request.base_url (http://byggare-bob.lm.se)
LOG: 2024-01-31 10:44:30,410 ERROR [qtp2095985054-34] Rails:-2 -   
LOG: ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):`

##### Environment

RHEL 9

docker-ce, docker-compose

F5 BIG-IP

gocd-server v 23.5.0 via https://download.gocd.org/binaries/23.5.0-18179/rpm/go-server-23.5.0-18179.noarch.rpm installed on docker image based on java 17 openjdk

Browser: Firefox 122

##### Steps to Reproduce
1. Use DNS-record with http -> https redirect
2. Make change in cruise-config.xml via gocd-server-gui 
3. Error appears

##### Expected Results
That cruise-config.xml should be saved

##### Actual Results
Error code from gocd-server 422 and redirect to page that displays error: "The change you wanted was rejected.  Maybe you tried to change something you didn't have access to."

##### Possible Fix

Use gocd-server gui without https-redirect and it works

##### Log snippets

```
LOG: 2024-01-31 10:47:55,229 WARN  [qtp2095985054-31] Rails:-2 - HTTP Origin header (https://foo-bar.fake.url) didn't match request.base_url (http://foo-bar.fake.url)
LOG: 2024-01-31 10:47:55,233 ERROR [qtp2095985054-31] Rails:-2 -   
LOG: ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
LOG:   
LOG: actionpack (6.1.7.6) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
LOG: actionpack (6.1.7.6) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
LOG: actionpack (6.1.7.6) lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
LOG: activesupport (6.1.7.6) lib/active_support/callbacks.rb:427:in `block in make_lambda'
LOG: activesupport (6.1.7.6) lib/active_support/callbacks.rb:179:in `block in halting_and_conditional'
LOG: actionpack (6.1.7.6) lib/abstract_controller/callbacks.rb:34:in `block in Callbacks'
LOG: activesupport (6.1.7.6) lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
LOG: activesupport (6.1.7.6) lib/active_support/callbacks.rb:512:in `block in invoke_before'
LOG: org/jruby/RubyArray.java:1989:in `each'
LOG: activesupport (6.1.7.6) lib/active_support/callbacks.rb:512:in `invoke_before'
LOG: activesupport (6.1.7.6) lib/active_support/callbacks.rb:105:in `run_callbacks'
LOG: actionpack (6.1.7.6) lib/abstract_controller/callbacks.rb:41:in `process_action'
LOG: actionpack (6.1.7.6) lib/action_controller/metal/rescue.rb:22:in `process_action'
LOG: actionpack (6.1.7.6) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
LOG: activesupport (6.1.7.6) lib/active_support/notifications.rb:203:in `block in instrument'
LOG: activesupport (6.1.7.6) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
LOG: activesupport (6.1.7.6) lib/active_support/notifications.rb:203:in `instrument'
LOG: actionpack (6.1.7.6) lib/action_controller/metal/instrumentation.rb:33:in `process_action'
LOG: actionpack (6.1.7.6) lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
LOG: actionpack (6.1.7.6) lib/abstract_controller/base.rb:165:in `process'
LOG: actionview (6.1.7.6) lib/action_view/rendering.rb:39:in `process'
LOG: actionpack (6.1.7.6) lib/action_controller/metal.rb:190:in `dispatch'
LOG: actionpack (6.1.7.6) lib/action_controller/metal.rb:254:in `dispatch'
LOG: actionpack (6.1.7.6) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
LOG: actionpack (6.1.7.6) lib/action_dispatch/routing/route_set.rb:33:in `serve'
LOG: actionpack (6.1.7.6) lib/action_dispatch/journey/router.rb:50:in `block in serve'
LOG: org/jruby/RubyArray.java:1989:in `each'
LOG: actionpack (6.1.7.6) lib/action_dispatch/journey/router.rb:32:in `serve'
LOG: actionpack (6.1.7.6) lib/action_dispatch/routing/route_set.rb:842:in `call'
LOG: rack (2.2.8) lib/rack/tempfile_reaper.rb:15:in `call'
LOG: rack (2.2.8) lib/rack/etag.rb:27:in `call'
LOG: rack (2.2.8) lib/rack/conditional_get.rb:40:in `call'
LOG: rack (2.2.8) lib/rack/head.rb:12:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/http/content_security_policy.rb:19:in `call'
LOG: uri:classloader:/jruby/rack/session_store.rb:79:in `context'
LOG: rack (2.2.8) lib/rack/session/abstract/id.rb:260:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/cookies.rb:697:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
LOG: activesupport (6.1.7.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
LOG: railties (6.1.7.6) lib/rails/rack/logger.rb:37:in `call_app'
LOG: railties (6.1.7.6) lib/rails/rack/logger.rb:28:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
LOG: rack (2.2.8) lib/rack/method_override.rb:24:in `call'
LOG: rack (2.2.8) lib/rack/runtime.rb:22:in `call'
LOG: activesupport (6.1.7.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/static.rb:24:in `call'
LOG: rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
LOG: actionpack (6.1.7.6) lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
LOG: railties (6.1.7.6) lib/rails/engine.rb:539:in `call'
LOG: uri:classloader:/rack/handler/servlet.rb:22:in `call'

```

##### Additional information
I'm not sure if this is a bug or intended, but I can't find a setting that sets request.base_url.

**Comment by chadlwilson** [comment]
What are your settings for the site URLs in Admin > Server Configuration?

**Comment by chadlwilson** [comment]
Also, this sounds like it's not as much to do with an HTTP -> HTTPS redirect, but with using an HTTPS -> HTTP reverse proxy setup, terminating TLS at your load balancer and then proxying via regular HTTP to GoCD?

See https://github.com/gocd/gocd/issues/9197 for a similar issue

**Comment by chadlwilson** [comment]
Not sure what your reverse proxy/LB setup is, but you may need to make sure it's passing through appropriate headers on the original context, similar to the sample configs in https://docs.gocd.org/current/installation/configure-reverse-proxy.html or similar guidance at https://github.com/rails/rails/issues/22965#issuecomment-172929004

At a guess, [`X-Forwarded-Proto`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) is the main one you are missing.

**Comment by chadlwilson** [comment]
Might want to check https://my.f5.com/manage/s/article/K43444200 if Big-IP is where you are terminating TLS and proxying via.

**Comment by oskarTeodor** [comment]
When i allowed the `X-Forwarded-Proto-header` in F5, removed input at `Secure site URL` and  added my LB https-url in `Site URL` in the server configuration-section i started working. Thanks for the assistance!

**Comment by chadlwilson** [comment]
Good to hear :-) Reverse proxies are a pain.

The reason it's particularly messy with GoCD is essentially that different parts of GoCD are reliant on different frameworks/web server sub-components that handle request headers slightly differently, and have different approaches to CSRF protection and cross-origin handling.

The config XML edit here, alongside a few other mutating actions (e.g job re-runs from stag/job pages) still sit within older Ruby/Rails code which is why you specifically came across the issue here, while the rest of GoCD otherwise seems to work OK.
