### ISSUE TITLE
Many pipelines with many materials causing 100% CPU load

### ISSUE THREAD

**Issue by ctorpe** [gocd/gocd#1249]
Issue may be related to https://github.com/gocd/gocd/issues/1044

Number of pipelines: 494
Number of agents: 8
Number of environments: 3
Number of unique materials: 735
Number of schedulable materials: 735

We are running go-server 15.1 within a docker container on a vmware VM with:
8 cores (Intel® Xeon® Processor E3-1270 v3 (8M Cache, 3.50 GHz))
32GB memory.

We replicated the issue with a local build of the 15.2 mainline.
[The go-api-support dump with the issue shows more detail](https://gist.github.com/ctorpe/6af4e810b8cd36659ba1).

SCM materials are from git repositories. Pipeline material graphs representing dependencies between applications, libraries and APIs are complex and in the worst case contains pipeline depth of 2494.

What we saw was the host machine utilising all CPU and memory resources and eventually crashing the host after a prolonged time being overheated. This happened a few times. We used yourkit to analyse the performance issue and discovered that the pipeline auto scheduler was trying to compute a fan in graph and performing badly due to using CollectionUtils. Here's a snippet from the support_api_log.
```
Stacktrace:
  org.apache.commons.collections.CollectionUtils.select(CollectionUtils.java:512)
  org.apache.commons.collections.CollectionUtils.select(CollectionUtils.java:495)
  com.thoughtworks.go.server.service.dd.DependencyFanInNode.validateAllScmRevisionsAreSameWithinAFingerprint(DependencyFanInNode.java:180)
  com.thoughtworks.go.server.service.dd.DependencyFanInNode.fillNextRevisions(DependencyFanInNode.java:137)
  com.thoughtworks.go.server.service.dd.DependencyFanInNode.populateRevisions(DependencyFanInNode.java:77)
  com.thoughtworks.go.server.service.dd.FanInGraph.initChildren(FanInGraph.java:306)
  com.thoughtworks.go.server.service.dd.FanInGraph.computeRevisions(FanInGraph.java:180)
  com.thoughtworks.go.server.service.PipelineService.getRevisionsBasedOnDependencies(PipelineService.java:230)
  com.thoughtworks.go.server.service.AutoBuild.fanInOn(AutoBuild.java:131)
  com.thoughtworks.go.server.service.AutoBuild.fanInOnWithFallback(AutoBuild.java:112)
  com.thoughtworks.go.server.service.AutoBuild.onModifications(AutoBuild.java:72)
  com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:206)
  com.thoughtworks.go.server.scheduling.BuildCauseProducerService.newProduceBuildCause(BuildCauseProducerService.java:160)
  com.thoughtworks.go.server.scheduling.BuildCauseProducerService.autoSchedulePipeline(BuildCauseProducerService.java:122)
  com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:45)
  com.thoughtworks.go.server.scheduling.ScheduleCheckListener.onMessage(ScheduleCheckListener.java:24)
  com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:65)
  com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:50)
  java.lang.Thread.run(Thread.java:722)
```

See this programically sanitised config, still loadable into GO, which shows the complexity of the pipelines we have which cause the issue: [config.xml](https://gist.github.com/ctorpe/3910ec98d5ec71987bcc) 

Here's a yourkit analysis showing time spent on DependencyFanInNode.java:180
![yourkit-gocd-server-before-change](https://cloud.githubusercontent.com/assets/12992544/8275485/f5083142-18e9-11e5-90f2-549798e43152.png)

Here's the time spent on the same method after reducing the complexity from (O(n^2)) to O(n) 
![yourkit-gocd-server-after-change](https://cloud.githubusercontent.com/assets/12992544/8275500/3836e04e-18ea-11e5-80df-c63e80c0d871.png)

We have a patch which we intend to submit as a pull request to fix this issue. [You can see the go-api-support dump with the performance improvement](https://gist.github.com/ctorpe/a049a782772d06c39e92).

We've followed advice from the Performance-Tuning page and wanted to ask for any other advice which could be given to us in the future for these kind of work loads. We also wanted to mention this issue for anyone else having a similar problem.

**Comment by zabil** [comment]
@srinivasupadhya can we close this?

**Comment by srinivasupadhya** [comment]
yes. this does not require special testing, its well covered in integration & functional tests.
