### ISSUE TITLE
Improvements to documentation

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1264]
We have some ideas to improve on the documentation, Instead of rigging up the conversation before it begins, we'd like to gather feedback on what users (with different levels of expertise with go) would like to see in the documentation.

**Comment by zabil** [comment]
The document is centered around go configuration. 
For e.g. How to set up pipeline templates.
http://www.go.cd/documentation/user/current/configuration/pipeline_templates.html

It's not clear how to use these the templates once you've created a pipeline.
For e.g. here.
http://www.go.cd/documentation/user/current/configuration/quick_pipeline_setup.html

Ideally, we should have linked both.
I'd like the documentation not be screen based but concept based in this case around re-usablity.

**Comment by srinivasupadhya** [comment]
can this be raised on [documentation](https://github.com/gocd/documentation) repository?

**Comment by zabil** [comment]
@srinivasupadhya dang, yeah it belongs there.

**Comment by jyotisingh** [comment]
Moved to documentation repo https://github.com/gocd/documentation/issues/172
