### ISSUE TITLE
Optional Fan-Out / Fan-In & Pipeline Checkpoint

### ISSUE THREAD

**Issue by dsenecalb** [gocd/gocd#1270]
Hi, 

We all know that fan-out is the operation where from a upstream pipeline, two (or more) downstream pipelines start working in parallel. And from the fan-in the downstream pipeline will require two or more upstream pipelines in order to run. The problem for the fan-in is the dependency of all of its upstream pipelines.

Mentioning this operation, it doesn't allow the ability to perform the optional (logical OR) fan in. With the optional fan in, I understand that one of the upstream pipelines is successfully run first the downstream pipeline can run. 

Look into that picture of the optional fan-in:

 A (successful) ------\
                                 }---> C (must start run because of A or B).
 B (not run yet)------/

Another point. Is there a way to set a pipeline checkpoint which based of a pipeline stage result (maybe in the middle of the pipeline) can either run a downstream pipeline or continue to the next stage of the pipeline itstelf?

**Comment by srinivasupadhya** [comment]
optional fan-out -
https://groups.google.com/d/topic/go-cd/8lVLJlJs-t0/discussion

**Comment by arvindsv** [comment]
I suspect the authors of both are the same. :)

I'm closing this. Discussions should happen on the mailing list. We can reopen this later, if needed.

**Comment by Ehekatl** [comment]
I think we should have option for user to chose if a pipeline will use fan-in or not, from my side, it quite important because we want fan-in for all upstream downstream pipeline but for production we need manually approve, so it won't use fan-in, that's very ridiculous user case. @srinivasupadhya @arvindsv
