### ISSUE TITLE
Cannot access (404) the user preferences page when the authentication plugin is activated

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1273]
Found on experimental release15.2.0-2170 (05c70bb21bf9d3de8e2520a51b3a17feb8ce6d12)

Steps to reproduce
- Install an authentication plugin https://github.com/srinivasupadhya/gocd-oauth-login
- Set it up (using plugin settings) with valid github client key and secret.
-  Authorize using `<go-server>/go/plugin/interact/github.oauth.login/index`
- Access go server and select preferences for the user
- Boom. 404. 

Note: This happens on a go server when the authentication plugin is used **without** Server details->User management set up to use either LDAP or passwd file.

**Comment by zabil** [comment]
Related to #851

**Comment by srinivasupadhya** [comment]
This is because `SecurityConfig.isSecurityEnabled()` is false unless password file / LDAP is configured. Needs more thinking if we decide to enable it should be true if Authentication plugin exists.

**Comment by srinivasupadhya** [comment]
@jyotisingh says we can add a enable/disable flag in `<security/>` tag for plugins. if any plugin is enabled then `SecurityConfig.isSecurityEnabled()` is true

**Comment by arvindsv** [comment]
Closing. Auth has been redone since this time.
