### ISSUE TITLE
Standard out and standard error continues to write to an old log file

### ISSUE THREAD

**Issue by goeranu** [gocd/gocd#1275]
The Linux RPM package, go-server-15.1.0-1863.noarch, configures the server to write logs to _/var/log/go-server/go-server.log_.  It does so both by configuring log4j to use that log, and by redirecting standard output and standard error to the file when starting up.

This works fine initially.  But when log4j decides the log has reached its limit it does a rotation, and starts on a new file.  But standard out and standard error will not be redirected, they will continue to write to the old file, now called _/var/log/go-server/go-server.log.1_.  After enough rotations, it will write to a removed file.

I don't have any immediate suggestion for how to solve this in a **generic** way.  In systems using _systemd_, the best would probably be to not redirect at all and let the journal collect the output.  But that might mean loosing the output on a SysVinit system.

**Comment by arvindsv** [comment]
Does it make sense to write to /var/log/go-server/go-stdout.log or something? The only problem is logrotate won't happen and it can grow large. But, that's better than this.

**Comment by goeranu** [comment]
Separating the standard out/error logs from the log4j logs would keep a directory entry to the file standard out/error goes to, and be less confusing.  It would indeed reduce the problem.  I wouldn't consider the problem **solved** until all log files can be rotated.  But I do agree it is better than what we have now.

**Comment by rajiesh** [comment]
verified this issue on 15.3.0-2663, standard logs and errors are written into go-server.out.log. This issue can be closed
