### ISSUE TITLE
Add user needs a spinner while searching for user

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1279]
Authentication plugin extension allows a plugin to query external sources for user search.
The current modal does not display a loading status when search takes time to return result. (For e.g while accessing the Github user API)

Expected.
Display a spinner

**Comment by rajiesh** [comment]
preliminary test of this story on trunk 4da012b8687a7ca7350439ffc8f15e7c837afc08

Using chrome v 43.0

The spinner is not shown during the first search,

Setup Go Server to use LDAP or use GitHub login plugin
Login as Admin - navigate to user summary - click add user
Search for any user(ldap/git)
The first search will not have the spinner, the subsequent searches shows the spinner
Navigate to any other tabs/page(eg., pipeline) and visit User summary page and try add user - The first search will not have spinner, subsequent searches will show spinner

![image](https://cloud.githubusercontent.com/assets/6533924/9991275/4edb9752-6086-11e5-8933-cdadf717f180.png)

**Comment by rajiesh** [comment]
this issue verified on 15.3.0-2597 build and confirmed to be working fine without the issue of first time search not sowing up the spinner
