### ISSUE TITLE
Change the name of gocd

### ISSUE THREAD

**Issue by hammerdr** [gocd/gocd#128]
Go is a really hard language to find and identify. We should change the name to something memorable, short and googlable.

**Comment by webmaster128** [comment]
I'm not (yet) a committer but a happy user and yesterday I created https://github.com/gocd/gocd/issues/843

The core of my point: this is not a matter of taste ("Go" is quite cool), the current name is a real productivity killer.

**Comment by jyotisingh** [comment]
While all the reasons for renaming and not renaming Go still stand, if you are really blocked and do not know how to look up for more information about Go, try the following:
(i) Append "thoughtworks go" or "gocd" to your search string
(ii) Just ask on [go-cd](https://groups.google.com/forum/#!forum/go-cd) or [go-cd-dev](https://groups.google.com/forum/#!forum/go-cd-dev) mailing lists

**Comment by fff** [comment]
#843 is quite persuasive , and I'm feeling the exactly same pain when I tried to google some puzzle with "go". As go-cd is open-sourced and been expected to be widely used, googlable is quite a matter for new users, mail-list is no longer a fashion, and Google or stackoverflow is, searching is. So keep using a a name which is consistent and easy to distinguish, is quite important. 
One option maybe just use go-cd officially, which is much better than "Go".

**Comment by arvindsv** [comment]
Slowly, it's organically changing to "GoCD". Closing this.
