### ISSUE TITLE
Simplified Chinese support

### ISSUE THREAD

**Issue by Avey777** [gocd/gocd#12817]
Simplified Chinese support

**Comment by chadlwilson** [comment]
Please update your issue with a fuller description of what you're looking for and I'll reopen it 

If you want internationalisation of all menus/messages/UI then they will not be done.

If you want to ensure you can enter Chinese for pipeline names, have it in your artifacts, log files then that *should* work fine, I believe. If there is a specific issue, please update your issue to mention it and follow the issue template.
