### ISSUE TITLE
Go Server in IFRAME

### ISSUE THREAD

**Issue by eleite77** [gocd/gocd#1284]
Hello
I am developping a Web interface which gather Go Server Platform (Continuous integration) with Octopus (continuous deploy)

My main idea was to allow user to open each Platform in an Iframe
Octopus allows that but not go server.

I have a message that Go doesn't allow Inside iframe navigation
is there any way to do that?
thanks
E. Leite

**Comment by ketan** [comment]
Closing as dup of #1289
