### ISSUE TITLE
Consolidate API documentation

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1286]
#1264 

Move

http://www.go.cd/documentation/user/current/api/go_api.html

to

http://api.go.cd/

**Comment by ketan** [comment]
This would need substantial effort to migrate existing APIs to the new documentation format.

May I suggest an alternative that we continue to use the existing documentation at go.cd for the APIs – for the APIs that have been migrated, we clearly mark them as deprecated while pointing to the relevant section in api.go.cd.

As and when we migrate new APIs, api.go.cd can become the canonical home to the API documentation.

Thoughts?

**Comment by zabil** [comment]
@ketan At the pace we are going at w.r.t to API's couple with other priorities I think it will take a while to deprecate the older API's.

Meanwhile, I strongly feel that discoverability and readability of our current API's can be greatly improved if we move to slate. I looked through the old api section and it didn't look like significant effort. Am i missing something?  

Don't want to be in a place where they have to go to two places to learn how to use the API.

**Comment by jyotisingh** [comment]
This is already done!
