### ISSUE TITLE
Change X-Frame-Options SAMEORIGIN?

### ISSUE THREAD

**Issue by eleite77** [gocd/gocd#1289]
Hello

is it possible to change the configuration of Go server in order to allow Go Server Web Pages to be displayed in a IFrame? i think by changing the value of X-Frame-Options would be sufficient.

Thanks
E. Leite

**Comment by ketan** [comment]
`X-Frame-Options` is set to `SAMEORIGIN` by design. Are you expecting (or seeing) a different value than this?

```
% curl https://build.go.cd/go/pipelines -iI -uview:password -s | grep X-Frame-Options
X-Frame-Options: SAMEORIGIN
```

**Comment by arvindsv** [comment]
Integration should be through APIs, I feel. Changing this value will cause other problems. It'll be very insecure, for a start.

**Comment by eleite77** [comment]
ok thanks a lot for your advice
regards

Envoy? de mon iPhone

Le 1 juil. 2015 ? 12:56, Aravind SV <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Integration should be through APIs, I feel. Changing this value will cause other problems. It'll be very insecure, for a start.

-
