### ISSUE TITLE
I find the format of user@IP:PORT/repo not useful when I add git material. How can I change the SSH port?

### ISSUE THREAD

**Issue by ysf465639310** [gocd/gocd#12942]
##### Brief describe
I can't change ssh port by specify the port, the port was always 22

##### Screenshot detail

![screenshot-1721125863445](https://github.com/user-attachments/assets/7d0c6ba8-c56e-4871-90d8-530c4b1b98e6)

###### Basic environment details

* GOCD-SREVER Version: `24.20` docker image
* 
###### api/support
    "Timestamp": "2024-07-16T10:43:11Z",
    "Go Server Information": {
        "Version": "24.2.0 (19076-1406870fc6e121194028e55c4facc0c638d70007)"
    },
    "Config Statistics": {
        "Valid Config": {
            "Number of pipelines": 1,
            "Number of environments": 0,
            "Number of agents": 1,
            "Number of unique materials": 1,
            "Number of schedulable materials": 1
        },
        "Security": {
            "Plugins": [],
            "Enabled": false
        }
    }

**Comment by ysf465639310** [comment]
> What happens if you properly prefix as ssh, i.e include `ssh://` in the URL?

At first  I add "ssh://", but it always not  work, So I search other issue and find they don't   add the head of "ssh://", So I try to remove it 

![112](https://github.com/user-attachments/assets/1042100b-acb4-4822-8cc4-51211e2dd2fd)
![3](https://github.com/user-attachments/assets/39e7a4b1-8aab-4614-85d2-1ec6178b016e)

**Comment by ysf465639310** [comment]
> What happens if you properly prefix as ssh, i.e include `ssh://` in the URL?

I also find the bug of input of  the password，It was not work When I want to see the password without encryption，The  component of decryption is unavailable.

![3](https://github.com/user-attachments/assets/d382a274-3b33-4087-86fe-2f5b5f215792)

**Comment by chadlwilson** [comment]
> > What happens if you properly prefix as ssh, i.e include `ssh://` in the URL?
> 
> At first, I added "ssh://", but it always didn't work. So I searched for other issues and found that they didn't add the prefix of "ssh://". So I tried to remove it.

That's not correct. As you can see you need to include the `ssh://` prefix to get it to parse the port correctly. This is just git CLI behaviour and nothing GoCD can do:

Without protocol, port is ignored.
```
$ git ls-remote 192.168.11.3:667/volume1/blah.git
ssh: connect to host 192.168.11.3 port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

With `ssh://` port is correctly parsed:
```
$ git ls-remote ssh://192.168.11.3:667/volume1/blah.git
ssh: connect to host 192.168.11.3 port 667: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

As you can see, with the ssh prefix the port is parsed correctly. If you cannot connect with `ssh://` prefix there must be something else wrong with your targetr.

I'll open another issue for the issue with the "show password" button as that is a separate problem. One ticket - one issue.

**Comment by ysf465639310** [comment]
> > > What happens if you properly prefix as ssh, i.e include `ssh://` in the URL?
> > 
> > 
> > At first, I added "ssh://", but it always didn't work. So I searched for other issues and found that they didn't add the prefix of "ssh://". So I tried to remove it.
> 
> That's not correct. As you can see you need to include the `ssh://` prefix to get it to parse the port correctly. This is just git CLI behaviour and nothing GoCD can do:
> 
> Without protocol, port is ignored.
> 
> ```
> $ git ls-remote 192.168.11.3:667/volume1/blah.git
> ssh: connect to host 192.168.11.3 port 22: Connection refused
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> With `ssh://` port is correctly parsed:
> 
> ```
> $ git ls-remote ssh://192.168.11.3:667/volume1/blah.git
> ssh: connect to host 192.168.11.3 port 667: Connection refused
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> As you can see, with the ssh prefix the port is parsed correctly. If you cannot connect with `ssh://` prefix there must be something else wrong with your targetr.
> 
> I'll open another issue for the issue with the "show password" button as that is a separate problem. One ticket - one issue.

I created ssh account gituu for gitserver instead of yangshaofei and  gituu's password is empty then connected ok, 

I think this problem  are  caused by bugs in the password input box too.
 
![13123](https://github.com/user-attachments/assets/34f78845-c63a-4533-b898-efac5a404af8)

**Comment by chadlwilson** [comment]
You have not described why there is problem here, nor described how accounts are configured on your git repository manager and what you expect to pass/fail (and why).

The test connection just does a `git ls-remote` as I showed above. It is *not* a complete authentication test and it depends how your repository manager is configured. Some allow ls-remote without authentication. Others do not. That does not mean it has “bugs”, and since you appear to have a custom repo manager I cannot comment.

If something behaves differently between normal git CLI commands and GoCD then there may be a problem, but otherwise please try actually creating your material and ensure you understand how command line git works first before assuming GoCD is broken.
