### ISSUE TITLE
Passing preferences to agent

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1295]
This issue is being opened up as a result of issues we're facing with having preferences or configuration that needs to be sent from the server over to the agent.

A case in point is #1059 specifically [this conversation](https://github.com/gocd/gocd/pull/1059#issuecomment-103139397)

The problem we're facing is that the specific behavior of "git clean" needs to be set on the server, but the operation actually happens on the agent. We need to get some configuration over from the server to the agent for it to decide which git clean implementation it should use.

Also as another case - with TFS (#1155). We would like a feature toggle of sorts that can allow users to fallback to TFS SDK 10 if required, however since the agent also performs TFS operations, getting this information over to the agent for it to be able to "re-initialize" is important.

**Comment by arvindsv** [comment]
It is now possible to set agent-level system properties from the server side.
