### ISSUE TITLE
UI inconsistencies

### ISSUE THREAD

**Issue by wraithy** [gocd/gocd#1298]
## Getting to the overview of a run

Starting from pipeline history page
- Can't click on (red/green/yellow) progress bar. Instead must click on an `i` button which appears on mouseover. This is inconsistent with the rest of the website.
- Clicking on run number from the pipeline history page seems like it should take me to the run overview - instead takes me to the value stream map. This may be an opinion thing, but I  feel like there should be a separate link to this, which is clearly labeled so that I know what I'm getting if I click it.

For clarity, by "run overview" I mean  
`http://go-server/go/pipelines/<PIPELINE>/<INDEX>/<STAGE>/<INDEX>`  
## Restarting stages
- Clicking the restart stage button (which also appears on mouseover) gives a confirmation alert, but there is no alert when a stage is restarted from the stage overview page.
## Run overview problems
- Restarting a stage doesn't redirect you anywhere. The page should update to show the overview of the new run.
## Page dynamics
- When watching the console tab while a job is running, the page should scroll as more output appears.
## Editing a custom task
- 'Command' field doesn't seem to be a normal text field. This means you can't use `Home` and `End` to jump around.

**Comment by ketan** [comment]
Thank you for reporting this issue. We have already resolved one of the issues reported here (console log always stays at bottom)

We have a new UX person (@vinasoni) on board who will be addressing some of these issues, and more.

**Comment by whodafly** [comment]
I've just started using Go CD, having moved from Jenkins, and I have experienced the same issues. Glad to hear you guys have someone who'll be looking into this sort of stuff!

**Comment by ketan** [comment]
> Glad to hear you guys have someone who'll be looking into this sort of stuff!

That does not mean @vinasoni will be the the only one working on it. We'd love to hear from users about things that could be improved on and if there are specific ideas that users have – we'd love to hear about them as well.
