### ISSUE TITLE
Is there any queue mechanism to deal with conflict, pipeline is processing ?

### ISSUE THREAD

**Issue by Ehekatl** [gocd/gocd#1303]
I trigger pipeline through API, but somehow there could be multiple triggers happen in the same time.
The msg just show me a conflict, it could be so much better if there was a queue...

Really need this feature : (

**Comment by srinivasupadhya** [comment]
same as #14?

**Comment by Ehekatl** [comment]
Same I think, issue 14 to 1303 lol
Glad to see this feature now at the top of 15.3 proposal, hope it coming soon.
