### ISSUE TITLE
AWS Secret Access Not Always Masked

### ISSUE THREAD

**Issue by charles-niaid** [gocd/gocd#13066]
Hello,

I have not been able to reproduce this on demand, but sometimes the AWS secret access key isn't masked when viewing the cluster configuration.

**Unmasked**
<img width="594" alt="acceskey_unmasked" src="https://github.com/user-attachments/assets/6aeed3c3-262e-49c1-9843-7d0fb44e4222">

**Masked**
<img width="567" alt="accesskey_masked" src="https://github.com/user-attachments/assets/d0124417-0b1e-4d36-8a77-fde22caa8eeb">

Plugin Version: `7.4.0-663`

**Comment by chadlwilson** [comment]
Are you on the latest GoCD version?

**Comment by chadlwilson** [comment]
Some work was done to resolve this in the vast majority of cases in GoCD 23.4.0 although sadly there are some edge cases where its possible that the values get decrypted and then encrypted again on startup. These _shouldnt_ be visible by the UI though if I recall the bug correctly.

**Comment by chadlwilson** [comment]
The remaining issue is noted at https://github.com/gocd/gocd/issues/13067

**Comment by chadlwilson** [comment]
Ok, if you still have issues see if the other ticket more directly describes any remaining problem.
