### ISSUE TITLE
Implement a plugin and Go update check

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#1308]
Need to check at regular intervals, and notify users (or admins only) about newer releases of Go which are available.

Also, and maybe more importantly, do this for plugins. Plugins can and should be updated more frequently and at a cadence which is different from Go's own. This check should include version incompatibility checks, etc. This can be tricky, because, as it stands now, go.cd site does not have plugin files. They're all available in external repositories of the authors. Doing this right can eventually make a "Plugin Repository" to install plugins from within Go, easier.

**Comment by jyotisingh** [comment]
@kmugrage 's comment from From #1386 :

We hear on a regular basis that people do not know when a new version of Go is released. Go should let people know if there's a new version available so that they can download and install it. The notification should be fairly visible, but not overwhelming.

I think the first version of this is a simple notification.

**Comment by norcnorc** [comment]
Please do make this "phone home" feature opt-in. Not all users may be excited to have even the information that they are using Go broadcast into the world. Also, this can be a slippery slope leading to increasing amounts of "usage statistics" gathered and transmitted by ever more insidious means, such as https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/model/UsageStatistics/footer.jelly#L26-L28

**Comment by maheshp** [comment]
Tasks 
    1. Add a timer in GO server with a cadence of 1 day to fetch the latest GO version, this data should be available through a go.cd endpoint
        and persist the latest version in the DB.
    2. Add a visual clue on the web page to indicate if a new version is available.

**Comment by arvindsv** [comment]
Closing as the update check is fine. The plugin update check can be made a new issue when it needs to be done (maybe along with [plugin central](https://github.com/gocd/gocd/issues/156)).
