### ISSUE TITLE
Pipeline display: make information more visible

### ISSUE THREAD

**Issue by rprieto** [gocd/gocd#1311]
Hi, we've been using Go for a while, and find ourselves wishing the pipeline view gave us more information. What do you think of the idea below?

_Current:_
<img width="600" alt="go-cd-current" src="https://cloud.githubusercontent.com/assets/189105/8563449/d0683396-2582-11e5-982e-397f0d16327e.png">

_Proposed:_
<img width="600" alt="go-cd-more-visibility" src="https://cloud.githubusercontent.com/assets/189105/8563681/ea84680a-2585-11e5-9f6c-6077f082233b.png">

The idea is to:
- display the author and timestamp of every step in the pipeline
- replace the hoverable `view` and `re-run` buttons with actual links, for tablet devices

My understanding is that Go Plugins cannot modify the UI, so would something like this need a code change in Go itself?

Cheers

**Comment by vinasoni** [comment]
@rprieto Thanks for sharing your mockup. We are currently looking at redesigning the entire pipeline history page. Your feedback to display additional information about  every step in pipeline is a very valuable input for us. We will analyze and consider this  as one of the new requirement.

**Comment by rprieto** [comment]
Thanks for the very quick reply, looking forward to the next version. Do you usually have public/open conversations about these things?

**Comment by vinasoni** [comment]
@rprieto  - I am grouping all UX/UI issues related to Pipeline history under #1312 Please feel free to add to it.
