### ISSUE TITLE
Move Go's system properties to a file-system based config for user's to override

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1313]
System properties can currently be set while starting Go server in /etc/default/go-server(linux) and wrapper-properties.conf(windows). The idea is to allow users to override system properties through a file system based config file so its easy to backup and restore such configs. And also, it will become standard across all OSs.

TODO: 
Need to decide the structure. 
Should we take care of migration of existing system properties configured by users?

**Comment by ketan** [comment]
I looked up a couple of configuration "frameworks" for java -

* http://owner.aeonbits.org/ - looks very nice, drawback, no json support (yet)
* https://commons.apache.org/proper/commons-configuration/userguide/user_guide.html (like most commons project, have to write a lot of boilerplate code to bootstrap and serialize/deserialize into a config object)

Another option is to roll our own using Gson's custom serialization/de-serialization, but I feel that we'd just do what OWNER started out with.

Thoughts?

**Comment by arvindsv** [comment]
[FeatureToggleRepository](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/support/toggle/FeatureToggleRepository.java#L41) is kind of similar. Our own hand-written gson serialization of [FeatureToggle](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/domain/support/toggle/FeatureToggle.java#L24) objects. Owner looks nice. I wish it had JSON support.

**Comment by ketan** [comment]
> Owner looks nice. I wish it had JSON support.

Someone (cough) submitted lviggiano/owner#144 for this.

Here's a quick example that works (after applying lviggiano/owner#144 and lviggiano/owner#145)

```json
{
  "go": {
    "config_dir": "/etc/go",
    "jetty": {
      "plain": {
        "host": "jetty-plain-text-host",
        "port": 1234
      },
      "ssl": {
        "host": "jetty-ssl-host",
        "port": 1235,
        "ciphers": {
          "included": ["ECDHE", "ECDSA"],
          "excluded": ["RC4", "IDEA-CBC-MD5"]
        }
      }
    }
  }
}
```

```java
public interface GoConfig extends BaseConfig {
    @DefaultValue("go.jetty.plain")
    Jetty jetty();

    @Key("go.config_dir")
    File configDir();

    @DefaultValue("go.jetty.ssl")
    JettySsl jettySsl();

    @DefaultValue("go.db")
    Database db();

    interface Database extends BaseConfig {
        @Key("${ns}.host")
        @DefaultValue("localhost")
        String host();

        @Key("${ns}.port")
        @DefaultValue("")
        int port();

        @Key("${ns}.user")
        @DefaultValue("sa")
        String user();


        @Key("${ns}.password")
        @DefaultValue("")
        String password();
    }

    interface Jetty extends BaseConfig {
        @Key("${ns}.host")
        @DefaultValue("0.0.0.0")
        String host();

        @Key("${ns}.port")
        @DefaultValue("8153")
        int port();
    }

    interface JettySsl extends Jetty {
        @Key("${ns}.port")
        @DefaultValue("8154")
        int port();

        @Key("${ns}.ciphers.included")
        List<String> includedCiphers();

        @Key("${ns}.ciphers.excluded")
        List<String> excludedCiphers();
    }
}
```

**Comment by arvindsv** [comment]
> Someone (cough) submitted lviggiano/owner#144 for this.

You know ... I had a sneaky suspicion that would happen.

**Comment by zabil** [comment]
Alternatively, I think we can easily wire one up in spring. 
Here's what we did earlier.

Define interfaces that point to the config location and mark them with the key annotation. 
The interfaces can then proxied via [FactoryBean](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/beans/factory/FactoryBean.html) something like what [mybatis](https://mybatis.github.io/spring/apidocs/reference/org/mybatis/spring/mapper/MapperFactoryBean.html) does advantage is that they can be injecting into classes that require them in our auto-wire madness.

**Comment by ketan** [comment]
There's a few additional improvements I'd like for us to consider —

* ability to "document" all available switches and knobs in `SystemEnvironment`, along with their default values and behaviour of each
* ability to ensure that each platform uses the same config file
* allow for configuring not just the user properties via `-D` but also JVM properties to allow tweaking memory, GC, SSL, among other things
* consistent style of configuration across all OSes and distribution. No more `/etc/defaults/go-{server,agent}` and `config/wrapper-properties.conf`

Tanuki seems to be a nice fit that checks all of the boxes above and is something that we've been using with good success. I'd like for us to consider making it a default across all installers.

WDYT?

**Comment by arvindsv** [comment]
My initial reaction was: "Feel icky about using Tanuki on Linux". But, thinking more about it, I think it might be worth exploring. Keeping up with "improvements" in Linux startup scripts (*cough* systemd *cough*) is always an issue without something which can take care of it.

I have no idea how well it works there, though. Whatever we decide, we need to come up with a migration plan which involves the least amount of pain for existing users.

**Comment by arvindsv** [comment]
GoCD now uses Tanuki.
