### ISSUE TITLE
Add repository plugin for s3 polling

### ISSUE THREAD

**Issue by joawan** [gocd/gocd#1320]
We've written a s3 poller plugin that I would like to share.
https://github.com/schibsted/gocd-s3-poller/releases/tag/1.0.0

Difference from existing [s3 artifact](https://github.com/ind9/gocd-s3-artifacts/releases) plugin
* Build on the [JSON API](http://www.go.cd/documentation/developer/writing_go_plugins/package_material/json_message_based_package_material_extension.html)
* Not tied to a specific folder structure in the S3 bucket

**Comment by srinivasupadhya** [comment]
to do that:
* fork the repository - https://github.com/gocd/gocd.github.io
* add your plugin to [plugin.html](https://github.com/gocd/gocd.github.io/blob/master/community/plugins.html)
* send in a pull request

**Comment by joawan** [comment]
Great, thanks!
