### ISSUE TITLE
Starting up GoCD takes hours because of Database Migration

### ISSUE THREAD

**Issue by JochenLutz** [gocd/gocd#13214]
##### Issue Type

Bug Report

##### Summary

When (re-)starting GoCD, `DatabaseMigrator` takes 9 – 14 hours without apparent CPU or database activity. There are no log messages showing any issues. Next message is “Database upgrade completed successfully”.

##### Environment

* Oracle Linux 8.10
* H2DB, DB size ~ 2 GB

###### Basic environment details

* Go Version: `24.3.0 (19261-3d8bed12557f0b310a4bce58f076abbfc2841ae9)`
* JAVA Version: `17.0.13`
* OS: `Linux 4.18.0-553.22.1.el8_10.x86_64`

##### Expected Results
GoCD should restart quickly.

##### Actual Results
It takes 9 – 14 hours.

##### Our Research Results
A colleague found a [bug ticket](https://github.com/liquibase/liquibase/issues/6178) in Liquibase's Github project.
Short summary, details in the linked ticket:
* Apache Common changed random string generation, which now uses `/dev/random`.
* Therefore Liquibase's update mechanism depends on entropy available in `/dev/random`, which is quickly drained.
* GoCD startup hangs without CPU, network or database load waiting for entropy to come available.
* I verified that by watching `/proc/sys/kernel/random/entropy_avail` while starting GoCD.
* Installing and activating [haveged](https://github.com/jirka-h/haveged) (while GoCD hung on startup) refilled the entropy pool and the database upgrade finished within seconds.

##### Possible Fix
Liquibase fixed that in [PR 6179](https://github.com/liquibase/liquibase/pull/6179). This is already released as version 4.29.2.
So updating GoCD's dependency of Liquibase to this version should should fix this issue.

**Comment by chadlwilson** [comment]
24.4.0 is out now, so you can use an official release to validate.

**Comment by JochenLutz** [comment]
:+1: validated.

Startup without `haveged` works as expected.
