### ISSUE TITLE
Inconsistent & Incomplete error messages on editing environment variables.

### ISSUE THREAD

**Issue by chopraapooja** [gocd/gocd#1321]
I tried to edit environment variable on a **template** as in following screenshot -

<img width="1428" alt="screen shot 2015-07-09 at 2 11 36 pm" src="https://cloud.githubusercontent.com/assets/10117539/8591248/8923361c-2644-11e5-97b2-09a6fc6fc82f.png">

After saving, all the fields get cleared (which is very annoying  #1272) and showed **one** error message -

<img width="1440" alt="screen shot 2015-07-09 at 2 12 02 pm" src="https://cloud.githubusercontent.com/assets/10117539/8591336/3f17f070-2645-11e5-8e8d-db7033ef0a2b.png">

All fields are breaking validation so **ideally** it should show multiple error messages in the format like this -

<img width="1431" alt="screen shot 2015-07-09 at 2 23 12 pm" src="https://cloud.githubusercontent.com/assets/10117539/8591457/166d5f38-2646-11e5-8e3c-a0cce15575be.png">

 **QA Note** While testing bug fix, make sure that it doesnt happen while editing pipeline's environment variables on both stage and job level

**Comment by arvindsv** [comment]
@maheshp: Closing this. This UI is being replaced. So, no work will happen on this at this time.
