### ISSUE TITLE
Agent doesn't interprete environment variable if it's name has hash '#' . 

### ISSUE THREAD

**Issue by chopraapooja** [gocd/gocd#1322]
I tried setting environment variable with name '#goforcd' (you will have to specify '##goforcd' to escape hash). 
Echo '#goforcd displays zero, ideally it should display 'foobar' (value of variable) .
  
<img width="980" alt="screen shot 2015-07-09 at 3 07 12 pm" src="https://cloud.githubusercontent.com/assets/10117539/8592348/3b621314-264c-11e5-81b4-1e23ad03bfb0.png">

**Noticed in** -Go v15.2.0(2237-2fd095a5611938)

**Comment by arvindsv** [comment]
`${#` has special meaning in bash (length of substituted param). I don't think `#goforcd` should be considered a valid environment variable.

```
$ ABC=hello
$ echo ${#ABC}
5
```
