### ISSUE TITLE
Using passwordless ssh access

### ISSUE THREAD

**Issue by dsenecalb** [gocd/gocd#1323]
Hi All,

I posted this at the Google groups (https://groups.google.com/forum/#!topic/go-cd/YaXE8TcSsmI). And this, in  my opinion, is a feature that must be implemented

I realize one thing that it's raising some concerns from my side in terms of ssh access. 

In GoCD, accessing to another server with a passwordless ssh, by first providing a private key (a.k.a rsa_id file). [http://www.dotkam.com/2009/03/10/run-commands-remotely-via-ssh-with-no-password/]. 

However, in some companies like us, are enforcing LDAP login which, in my my opinion, could break the  private key access method Another concern of passwordless ssh is the maintenance of the file. 

Is there (any plan of this for future releases) a way that GoCD can ask username and password for SSH access, without the use of the private keys. Take as example on CI tools like Jenkins, Teamcity, Bamboo and others, which ask admins to use the username and password instead of passwordless access.

Thanks.

**Comment by dsenecalb** [comment]
Hi, is there any update on this ticket?

**Comment by arvindsv** [comment]
Isn't using ssh-agent a better approach? Any time you use passwords in the clear, they can be easily intercepted.

There's no immediate plan to do this. There was an SSH key management feature I [was working on](https://github.com/gocd/gocd/issues/430), which comes close (not passwords, keys only). But, I haven't had the time to finish it.

**Comment by ageekymonk** [comment]
+1

**Comment by arvindsv** [comment]
Closing as stale.
