### ISSUE TITLE
UX Patterns

### ISSUE THREAD

**Issue by vinasoni** [gocd/gocd#1327]
Help bring consistency in the UI interactions
- View History - Job history, stage history side bar
- Infinite Scrolling Interaction (as in pipeline/stage/job history)
- View Pipeline Details: On dashboard, clicking on label takes user to VSM, clicking on pipline-name navigates to pipeline-history. This confuses users. Each link takes users to different pages, but links look similar (maybe icon to differentiate)
- Display Hierarchy & Relationship - Pipelines which are inter-related
- someway to look at console.log page in maximize mode
- Auto complete/ auto suggest
- UX inconsistency between viewing and configuring pipelines, etc.
- Reduce 'clickiness' within UI. Make it easy to navigate between screens with less clicks
- Compare - Compare builds, etc.

**Comment by arvindsv** [comment]
Closing. Likely to change.
