### ISSUE TITLE
Console log - scroll to end of logs does not happen by default

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1335]
Hosted Go server on AWS, accessing it using google chrome v43 on fedora machine.
When I navigate to console logs from dashboard for a completed build, the "scroll to end of logs" is "green" by default, but the scrolling does not happen. One needs to click on the button twice for it to work.

Similar issue exist in IE9 and FF on fedora.

**Comment by zabil** [comment]
Also noticed this on Go Version: 15.2.0(2246-acdef8b3cb2771)
Mac: 10.10.4 (14E46)
Safari: Version 8.0.7 (10600.7.12)
Chrome: Version 43.0.2357.132 (64-bit)

**Comment by rajiesh** [comment]
verified on 15.3.0-2726(74fa3313ce429737cdc00a94d420b1fcc58dafe7) and is working as expected
