### ISSUE TITLE
Git Build Notification

### ISSUE THREAD

**Issue by nhudacin** [gocd/gocd#1339]
Hello, 

Any write-ups, blog posts, or documentation on how to integrate build statuses (passing, failing, pending) on git repo home pages? For example, on the knife-windows repo (along with tons of others), they have a git build status pointing to travis-ci... https://github.com/chef/knife-windows/ 

Could I do that with my repos pointing to a go cd pipeline?

**Comment by srinivasupadhya** [comment]
have a look at https://github.com/srinivasupadhya/gocd-build-status-notifier
that a plugin to update github pull requests with status. should be fairly straight forward to modify for your usecase.

**Comment by jyotisingh** [comment]
Looks like a query. Closing it. Reopen if you have a specific issue to report. You could post queries to go-cd@googlegroups.com
