### ISSUE TITLE
Plugin response codes could be named better

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1345]
``` java
public class DefaultGoPluginApiResponse extends GoPluginApiResponse {
    public static final int SUCCESS_RESPONSE_CODE = 200;
    public static final int VALIDATION_FAILED = 412;
    public static final int BAD_REQUEST = 400;
    public static final int INTERNAL_ERROR = 500;
}
```

The response codes do not follow any set naming convention here. Could we deprecate these constants and use better named constants?

A good example is the constants in [`HttpServletResponse`](https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletResponse.html)

/cc @srinivasupadhya

**Comment by srinivasupadhya** [comment]
sure. by renaming the constants you wouldn't be affecting behaviour in anyway so i don't have any concerns over this.
