### ISSUE TITLE
Fix functional test - 3 - Flaky - EnvironmentsScreenNavigation

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#1347]
EnvironmentScreenNavigation.scn [fails](https://build.go.cd/go/tab/build/detail/regression/354/twist/1/firefox-split-runInstance-4) like this sometimes:

![image](https://cloud.githubusercontent.com/assets/172235/8680344/c6bb138a-2a2e-11e5-91a3-29ae48b37360.png)

It looks like it is either slow to start (maybe a slow VM) or too fast (and has finished by the time the check happened). Either way, it's flaky. It should probably use other means to figure out whether the job ran on the correct agent (maybe check which agent picked it up, rather than going to the agents tab).

**Comment by zabil** [comment]
Works fine on the migrated gauge tests
