### ISSUE TITLE
Fix functional test - 4 - Flaky - AgentsWithSameUUID

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#1348]
AgentsWithSameUUID.scn [fails](https://build.go.cd/go/tab/build/detail/regression/354/twist/1/firefox-split-runInstance-9) like this, sometimes:

![image](https://cloud.githubusercontent.com/assets/172235/8680467/85c13bc4-2a2f-11e5-91f2-854aa6f08f6f.png)

- Is it waiting for the agent to come back up?
- Before failing, maybe it can print out the logs?

**Comment by zabil** [comment]
These now run fine on the migrated gauges tests
