### ISSUE TITLE
New console log - last lines obscured

### ISSUE THREAD

**Issue by paulclarkin** [gocd/gocd#1349]
When opening the console tab of a completed job, the bottom line is obscured by the grey translucent bar.

![log](https://cloud.githubusercontent.com/assets/1027095/8685028/e289918c-2a73-11e5-8ba9-20c072e4b143.jpg)

**Comment by whodafly** [comment]
This is really irritating :-( - makes it almost impossible to select the last line.

**Comment by ketan** [comment]
Sorry about this issue, if you're looking for a short term fix, I'd suggest using a user stylesheet using something like https://userstyles.org/. The following fix should work -

```css
.buildoutput_pre {
  padding-bottom: 35px;
}
```

I'm going to fix this for 15.3 (see #1408)

**Comment by zabil** [comment]
Verified working on 15.3.0(2361-15f38854eea874)
