### ISSUE TITLE
Deprecate old users, backup and agents API

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1354]
I'd like to propose that the old users backup and agents API be called out as deprecated.

I'd like to hear if anyone has any reservations for removing these old APIs as soon as 15.3. I think a few months should be enough for users to migrate off to using the new API endpoints going forward.

Thoughts?

**Comment by arvindsv** [comment]
If we do, we should mention a clear path, with some examples, showing the old way and the new.

**Comment by ketan** [comment]
I have a draft on a blog post about the announcement, I'll add some examples there.

This issue is more around figuring out what the timelines for deprecation should be than anything else.

**Comment by arvindsv** [comment]
I would have said, if we announced it in 15.2, we could have removed it in 15.3. I'd like to announce now, and remove after 15.3 (giving people one release), but I wanted to hear opinions.

**Comment by craiggenner** [comment]
Sounds reasonable to me.  Is there anyway you can add a 'deprecated' notice?

**Comment by arvindsv** [comment]
I guess we can start on the post, at least. When you say marking it deprecated, do you mean somewhere [here](http://api.go.cd/#backups)? There's no mention of the [old API](http://www.go.cd/documentation/user/15.1.0/api/backup_api.html) there, at this point.

**Comment by ketan** [comment]
The post is typed out and ready. I don't feel I've gotten enough opinions on whether removing the old APIs in 15.3 is OK, so I can't submit a PR.

As far as the documentation is concerned, I've submitted an (incomplete) [PR](https://github.com/gocd/api.go.cd/pull/37) to link to old docs here – just to ask for feedback. Haven't heard much there.

**Comment by ketan** [comment]
Marking closed.
