### ISSUE TITLE
Inconsistent request types recieved by a task plugin

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1355]
I'm seeing the following request types being sent to a plugin (I'm sure there are more request types not mentioned here). The request types could probably follow a set convention -

```
go.plugin-settings.get-configuration
go.plugin-settings.get-view
go.plugin-settings.validate-configuration
configuration
view
validate
execute
```

**Comment by srinivasupadhya** [comment]
plugin settings end-point:
```
go.plugin-settings.get-configuration
go.plugin-settings.get-view
go.plugin-settings.validate-configuration
```

authentication end-point:
```
go.authentication.plugin-configuration
go.authentication.authenticate-user
go.authentication.search-user
```

notification end-point:
```
notifications-interested-in
stage-status
```

scm end-point:
```
scm-configuration
scm-view
validate-scm-configuration
check-scm-connection
latest-revision
latest-revisions-since
checkout
```

repository end-point:
```
repository-configuration
package-configuration
validate-repository-configuration
validate-package-configuration
latest-revision
latest-revision-since
check-repository-connection
check-package-connection
```

task end-point:
```
configuration
view
validate
execute
```

the plugin settings & authentication end-point is namespaced while others are not. we realized namespacing is required a little late. we can think of deprecating old ones & introduce new ones which are namespaced.
