### ISSUE TITLE
Schedule pipeline using API doesn't use given material revision

### ISSUE THREAD

**Issue by aaujon** [gocd/gocd#1356]
When scheduling a pipeline using API :
POST https://GO_SERVEUR/go/api/pipelines/PIPELINE_NAME/schedule
with body : 
materials[MATERIAL_NAME]=10ba8765d1d7da9a46bb29d9ef71e50fd97f03e4

The pipeline is scheduled but it doesn't use the given revision (it uses last commit)
The pipeline is configured with 'poll for new changes' option and I can't change that because we are using this material in an other pipeline, can this be the problem ?

We are using go : 15.1.0

**Comment by dynaum** [comment]
+1

**Comment by Ajayc31** [comment]
Hey Hi Arnaud,

How you able to schedule pipeline using API? I am getting 404 error....

**Comment by ptriller** [comment]
@Ajayc31 My guess is you are using HTTP GET and not POST

**Comment by GaneshSPatil** [comment]
Hi,

Can you try using the versioned [Scheduling pipelines API](https://api.gocd.org/current/#scheduling-pipelines) to trigger a pipeline specifying the [`materials`](https://api.gocd.org/current/#the-scheduling-material-object)?
 
The newer Scheduling pipelines API `v1` has been introduced as part of the GoCD release `v18.2.0`.
