### ISSUE TITLE
custom command build fails silently if remote git branch does not exist

### ISSUE THREAD

**Issue by fdavis** [gocd/gocd#1361]
running go server 14.4.0-1356 on ubuntu 14.04 via vagrant on VirtualBox on Mac OSX 
after creating a simple pipeline that checks out a git repo and runs a command from that repo, I would attempt to build it and the web UI shows its being scheduled and suddenly the job disappears without a trace.
Would it be feasible for a build that fails to update materials to fail in the web UI?

error from go-server.log 
2015-07-15 06:43:40,224 WARN [90@MessageListener for MaterialUpdateListener] MaterialDatabaseUpdater:117 - [Material Update] Modification check failed for material: URL: https://github.com/ansible/ansible.git, Branch: master 
java.lang.RuntimeException: Failed to run git clone command STDERR: Cloning into '/var/lib/go-server/pipelines/flyweight/8680c9c3-1a3f-4bd1-9a91-87d766bf6d61'... 
STDERR: fatal: Remote branch master not found in upstream origin 
STDERR: Unexpected end of command stream

/etc/go/cruise-config.xml with branch changed to the proper branch name, 'devel'
```xml
<?xml version="1.0" encoding="UTF-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="74">
  <server artifactsdir="artifacts" commandRepositoryLocation="default" serverId="49fe8b39-5370-4524-918f-372508a328b3" />
  <pipelines group="defaultGroup">
    <pipeline name="e8-init" isLocked="false">
      <materials>
        <git url="https://github.com/ansible/ansible.git" branch="devel" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="bin/ansible">
                <arg>--help</arg>
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
  <agents>
    <agent hostname="vagrant-ubuntu-trusty-64" ipaddress="10.0.2.15" uuid="29b7f982-8980-4f9e-8887-014785c7b0a7" />
  </agents>
</cruise>
```

Best,

**Comment by arvindsv** [comment]
Closing. There should be an error shown at the bottom right. Also, because of [this recent change](https://github.com/gocd/gocd/pull/1842), the pipeline should show a little error icon in it.
