### ISSUE TITLE
agents api not working

### ISSUE THREAD

**Issue by xxfelixxx** [gocd/gocd#1362]
In our GoCD instance,  Go Version: 15.1.0(1863-42e58c22aefd03)
I am working through the API documentation, but the 'get_agent' request doesn't seem to be working.

The verison 1 API request
http://go.aws.tm0.com/go/api/agents
returns

[{"resources":[],"sandbox":"/var/lib/go-agent","os":"Linux","free_space":"14.7 GB","ip_address":"10.0.0.73","agent_name":"goagent.aws.tm0.internal","environments":["Ceci_nest_pas_une_pipe","TestEnv"],"status":"Idle","uuid":"1f579ee7-9a5d-44be-8265-f0333f11a04a","build_locator":""},{"resources":[],"sandbox":"","os":"","free_space":"Unknown","ip_address":"10.0.1.225","agent_name":"nfs01.dev01.aws.tm0.internal","environments":["AnotherEnv"],"status":"Disabled","uuid":"4166839d-7bcc-42e4-b312-a5c3814dce7b","build_locator":""}]

The following url gives me an Agent webpage (OK).
http://go.aws.tm0.com/go/agents/1f579ee7-9a5d-44be-8265-f0333f11a04a

The API version does not seem to work (NOT OK).
http://go.aws.tm0.com/go/api/agents/1f579ee7-9a5d-44be-8265-f0333f11a04a

I get the message:
The url [ /go/api/agents/1f579ee7-9a5d-44be-8265-f0333f11a04a ] you are trying to reach doesn't appear to be correct.

Any thoughts?

**Comment by ketan** [comment]
Hi -

The get agent API call is only available starting version 15.2. I'm going to update the new API docs to update the minimal version where the API is available.

In the meanwhile, 15.1 version api docs are available at http://www.go.cd/documentation/user/15.1.0/api/go_api.html

I'm going to close this ticket out unless you think it's a bug that needs addressing.

**Comment by xxfelixxx** [comment]
OK, thanks!
