### ISSUE TITLE
OS X Safari 7 & 8 ask for local key when connecting to go.cd server

### ISSUE THREAD

**Issue by stretch327** [gocd/gocd#1363]
We're a primarily mac shop starting to use go.cd. We followed the directions to use our SSL certificate for HTTPS connections, but are having problems because it asks:

com.apple.WebKit.Networking.xpc wants to sign using key "Apple ID Authentication" in your keychain.

Dismissing the dialog with Always Allow, Allow or Deny results in an error that says:

Safari can't open the page because Safari can't establish a secure connection to the server "zeus.xojo.com"

Safari 5 & 6 do not suffer from this problem.

**Comment by koswalds** [comment]
+1

**Comment by lenucksi** [comment]
I can also confirm this effect. It disappears once you put a reverse proxy such as Nginx in front of it which terminates the SSL at itself instead of the JVM running Go.
It appears to be related to the certificate authentication used for the Go Agents.

**Comment by arvindsv** [comment]
Closing as stale.
