### ISSUE TITLE
New console log - Grunt (time-grunt) output not rendered correctly

### ISSUE THREAD

**Issue by paulclarkin** [gocd/gocd#1376]
When in "Raw" mode the output from Grunt's execution bar (with the [time-grunt](https://github.com/sindresorhus/time-grunt) plugin) is rendered as:

![log1](https://cloud.githubusercontent.com/assets/1027095/8685154/c84fbe94-2a74-11e5-8654-ea2eef16b688.jpg)

In the new console log, with colours on, it is shown as:

![log2](https://cloud.githubusercontent.com/assets/1027095/8685182/f6356264-2a74-11e5-985d-2d049d1b340e.jpg)

When running grunt in a standard console (outside of Go) it renders like this:

![7e332e06ff8dee99ab7abb6441d0ea538eb839ac9198a87fc3 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/1027095/8804643/1e930202-2fc5-11e5-8f3a-6010a61f0779.jpg)

It would be great if Go could render it like this also.

Thanks

**Comment by juhijariwala** [comment]
We tried running a build with [time-grunt](https://github.com/sindresorhus/time-grunt) in the following way. 
We set up https://github.com/sindresorhus/time-grunt.git as a repo.
And we tried below commands:
```shell
npm install
```
```shell
grunt
```

It is working fine with the above setup. 

Here is what we see on console log.

![screen shot 2015-08-06 at 4 50 36 pm](https://cloud.githubusercontent.com/assets/4953510/9110527/0bab4426-3c5c-11e5-95c4-0937acf8967e.png)

![screen shot 2015-08-06 at 4 50 51 pm](https://cloud.githubusercontent.com/assets/4953510/9110531/16af301c-3c5c-11e5-99ca-ad83c2843589.png)

Raw mode output:

![screen shot 2015-08-06 at 4 51 14 pm](https://cloud.githubusercontent.com/assets/4953510/9110534/1c1a3588-3c5c-11e5-8ad2-0a8845fd7168.png)

**Comment by paulclarkin** [comment]
How odd. I'll look at mine again, but maybe close this if it's just happening for me.

**Comment by paulclarkin** [comment]
This seems to happen for me in pipelines where the output is the result of an SSH command. We have some pipelines where we run the jobs on an Agent, but the job itself SSHs to another server to run the command.

I suspect the SSH is messing with the output?

Strange though that Raw mode works - maybe thats the way the Browser (in this case Firefox) is handling it?

**Comment by ketan** [comment]
Perhaps it is the fonts that are unable to render the (unicode?) characters.

Is this reproducible across different browsers on the same machine.

Would you mind applying a different font in firebug on the console log HTML
element and see how it renders?

**Comment by paulclarkin** [comment]
Also happens on chrome on Windows and Mac, and safari on Mac.

I don't think its that important, and is probably caused by use running the command inside SSH. Feel free to close this if you wish.
