### ISSUE TITLE
[Bug] Task run before load environment variables

### ISSUE THREAD

**Issue by Ehekatl** [gocd/gocd#1380]
I put a curl job to call gocd's api, and use secure env for username and passwword, it always get failed that I use wrong credentials, finally I found that it just because curl task run before load env,  can't imagine what's the logical behind this.

**Comment by ketan** [comment]
I'm not sure I follow what you're trying to raise as an issue. Would you mind elaborating a bit with the relevant pieces of the pipeline configuration and the curl command that you refer to?

**Comment by Ehekatl** [comment]
@ketan 
    06:39:40.377 [go] Job Started: 2015-07-24 06:39:40 UTC

	06:39:40.377 [go] Start to prepare newtest/1/defaultStage/1/defaultJob on ip-10-0-7-123.ap-northeast-1.compute.internal [/var/lib/go-agent]
	06:39:40.383 [go] Start to update materials.

	06:39:40.383 [go] Start updating files at revision 54e41913e6d53527bfe027556c0052a52a9f7926 from git@github.com:**************
	06:39:40.393 Cloning into '/var/lib/go-agent/pipelines/newtest'...
	06:39:48.173 [GIT] Fetch and reset in working directory pipelines/newtest
	06:39:48.173 [GIT] Cleaning all unversioned files in working copy
	06:39:48.177 [GIT] Cleaning submodule configurations in .git/config
	06:39:48.179 [GIT] Fetching changes
	06:39:50.205 [GIT] Performing git gc
	06:39:50.206 [GIT] Updating working copy to revision 54e41913e6d53527bfe027556c0052a52a9f7926
	06:39:50.385 HEAD is now at 54e4191 fix
	06:39:50.385 [GIT] Removing modified files in submodules
	06:39:50.408 [GIT] Cleaning all unversioned files in working copy
	06:39:50.412 [go] Done.

	06:39:50.426 [go] Start to build newtest/1/defaultStage/1/defaultJob on ip-10-0-7-123.ap-northeast-1.compute.internal [/var/lib/go-agent]
	06:39:50.426 [go] Current job status: passed.

	06:39:50.426 [go] Start to execute task: <exec command="curl" >
	<arg>http://***********/go/api/pipelines/build_pixiebob/pause</arg>
	<arg>-u</arg>
	<arg>$GOCD_USER:$GOCD_PASS</arg>
	<arg>-X</arg>
	<arg>POST</arg>
	<arg>-d</arg>
	<arg>pauseCause=Pause build_pixiebob to ensure we use correct docker image version</arg>
	</exec>.
	06:39:50.427 [go] setting environment variable 'GO_ENVIRONMENT_NAME' to value 'uat'
	06:39:50.427 [go] setting environment variable 'GO_SERVER_URL' to value 'https://***************'
	06:39:50.427 [go] setting environment variable 'GO_TRIGGER_USER' to value '********'
	06:39:50.427 [go] setting environment variable 'GO_PIPELINE_NAME' to value 'newtest'
	06:39:50.428 [go] setting environment variable 'GO_PIPELINE_COUNTER' to value '1'
	06:39:50.428 [go] setting environment variable 'GO_PIPELINE_LABEL' to value '1'
	06:39:50.428 [go] setting environment variable 'GO_STAGE_NAME' to value 'defaultStage'
	06:39:50.428 [go] setting environment variable 'GO_STAGE_COUNTER' to value '1'
	06:39:50.429 [go] setting environment variable 'GO_JOB_NAME' to value 'defaultJob'
	06:39:50.429 [go] setting environment variable 'GO_REVISION' to value '54e41913e6d53527bfe027556c0052a52a9f7926'
	06:39:50.429 [go] setting environment variable 'GO_TO_REVISION' to value '54e41913e6d53527bfe027556c0052a52a9f7926'
	06:39:50.429 [go] setting environment variable 'GO_FROM_REVISION' to value '54e41913e6d53527bfe027556c0052a52a9f7926'
	06:39:50.430 [go] setting environment variable 'GOCD_USER' to value '********'
	06:39:50.430 [go] setting environment variable 'GOCD_PASS' to value '********'
	06:39:50.433   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
	06:39:50.433                                  Dload  Upload   Total   Spent    Left  Speed
	06:39:50.434 
	06:39:50.436 <html>
	06:39:50.436   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
	06:39:50.436 <head>
	06:39:50.436 100   692  100   615  100    77   196k  25254 --:--:-- --:--:-- --:--:--  300k
	06:39:50.437 <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	06:39:50.437 <title>Error 401 Invalid credentials. Either your username and password are incorrect, or there is a problem with your browser cookies. Please check with your administrator.</title>
	06:39:50.437 </head>
	06:39:50.437 <body><h2>HTTP ERROR 401</h2>
	06:39:50.437 <p>Problem accessing /go/api/pipelines/build_pixiebob/pause. Reason:
	06:39:50.437 <pre>    Invalid credentials. Either your username and password are incorrect, or there is a problem with your browser cookies. Please check with your administrator.</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>
	06:39:50.438 
	06:39:50.438 </body>
	06:39:50.438 </html>
	06:39:50.547 [go] Current job status: passed.

**Comment by Ehekatl** [comment]
look at my log, problem is that tasks run before load env.

**Comment by rarunkum** [comment]
I don't think the task runs before env load here, Can you try giving the  **-d 'pauseCause=Pause build_pixiebob to ensure we use correct docker image version'** as a single line in the task.

You can also try echoing the variables to console to verify if the environment is loaded while running the task.

**Comment by Ehekatl** [comment]
@rarunkum I've already checked, env load correctly, and if I use same task configuration with username, password instead of env variables, it works fine.
look at the timestamp that log shows, is there any explanation that why task before load env?

**Comment by zabil** [comment]
@Ehekatl like @rarunkum mentioned the task is NOT running before the environment variable are being set.


```
06:39:50.426 [go] Start to execute task: <exec command="curl" >
<arg>http://***********/go/api/pipelines/build_pixiebob/pause</arg>
<arg>-u</arg>
<arg>$GOCD_USER:$GOCD_PASS</arg>
<arg>-X</arg>
<arg>POST</arg>
<arg>-d</arg>
<arg>pauseCause=Pause build_pixiebob to ensure we use correct docker image version</arg>
</exec>.
```

Is info about the task that's about to be executed and from the logs the curl command executed here
```
06:39:50.433   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
```

**Comment by zabil** [comment]
What's happening here is that go treats the following ```<arg>$GOCD_USER:$GOCD_PASS</arg>``` as arg and that means the environment variable has not been evaluated.

Can you change the task to do be executed with command 
```
bash
```

arguments

```
-c 
curl -u $GOCD_USER:$GOCD_PASS -X POST -d pauseCause="Pause build_pixiebob to ensure we use correct docker image version" http://***********/go/api/pipelines/build_pixiebob/pause
```

Tell us if that works.

**Comment by zabil** [comment]
Meanwhile we'll consider this as feedback for better messaging probably changing the sequence to 
```
06:39:50.427 [go] setting environment variable 'GO_ENVIRONMENT_NAME' to value 'uat'
....
06:39:50.426 [go] Start to execute task: <exec command="curl" >
<arg>http://***********/go/api/pipelines/build_pixiebob/pause</arg>
<arg>-u</arg>
<arg>$GOCD_USER:$GOCD_PASS</arg>
<arg>-X</arg>
<arg>POST</arg>
<arg>-d</arg>
<arg>pauseCause=Pause build_pixiebob to ensure we use correct docker image version</arg>
</exec> with environment variables:
```

**Comment by Ehekatl** [comment]
@zabil thx
