### ISSUE TITLE
HTML escaping issues in trigger with options

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1383]
The commit message reads `#1334 Replaced 'eval' with 'exec'`

<img width="810" alt="screen shot 2015-07-27 at 1 32 25 pm" src="https://cloud.githubusercontent.com/assets/10598/8901573/9866187a-3467-11e5-8184-96137de28d7d.png">

**Comment by ketan** [comment]
Related issue #1472 & #1603

**Comment by arvindsv** [comment]
@zabil: Another one (like #304) related to escaping. Is this fixed as well?

**Comment by ketan** [comment]
@GaneshSPatil — can you look at this when you have some spare time?
