### ISSUE TITLE
Automate installer testing

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1388]
@arvindsv has done some work on automated solaris installer testing. Speak to him.

**Comment by arvindsv** [comment]
Assigning to @rajiesh since he's working on this.

**Comment by arvindsv** [comment]
This should start showing up here: https://github.com/gocd/installer-testing

**Comment by rajiesh** [comment]
Installer testing as of now takes care of fresh installation of deb and rpm packages on ubuntu 12.04/14.04 and centos -6 and 7. Pending to do are - 

- Fresh install of zip and exe installers
- Upgrade testing for all installers

**Comment by ketan** [comment]
@rajiesh - technically, the rpm and deb installers are derived from the zip installers (move files around and pack them) — as such, I'm not sure if testing zip installers will add any value

windows is a different ball-game altogether. They are painful to automate, and there's very sparse documentation on how to get it going. We can pair on this next week I'm there.

**Comment by zabil** [comment]
@rajiesh closing this, I am assuming this is done.
