### ISSUE TITLE
Handle authentication order when ldap, file-based and auth-plugin are all being used

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1389]
- Decide behavior for error scenarios in username & password login when ldap, password file & plugins are involved. (code: `PluginAuthenticationProvider`, `AuthenticationProcessingFilter`). fix [Twist test](https://build.go.cd/go/tab/build/detail/regression/288/twist/1/firefox-split-runInstance-15)
- Decide behavior for error scenarios in user search when ldap, password file & plugins are involved (code: `UserSearchService`)

**Comment by arvindsv** [comment]
Related to https://github.com/gocd/gocd/issues/1273.

**Comment by arvindsv** [comment]
Closing. Auth has been redone since this time.
