### ISSUE TITLE
Adde Plugin API to Maven Central

### ISSUE THREAD

**Issue by drrb** [gocd/gocd#139]
It would make plugin development a lot easier if the plugin API jars were available in the Maven Central Repository (including source and JavaDoc jars). As it is, they either need to be stored in source control with the plugin, or manually downloaded each time the plugin is worked on by a new person.

Details on how to do it are [here](http://central.sonatype.org/).

**Comment by arvindsv** [comment]
Lots and lots of things (unrelated to this) came in the way. Sorry for the delay. :(

Every experimental build on http://go.cd/download, starting from 15.1.0-1445, should have a corresponding plugin API jar, up on Maven Central. [Here is](http://search.maven.org/#browse%7C74987900) the first one.
