### ISSUE TITLE
Error scheduling pipeline, no compatible revisions

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1391]
Either since upgrading to 15.2 or since removing one of the dependencies my downstream pipelines no longer automatically trigger, due to the following error:

```
Error while scheduling pipeline: DownstreamPipeline as no compatible revisions was identified. [Jul-28 12:32:34]
Failed resolution of pipeline DownstreamPipeline : Cause : No valid revisions found for the upstream dependency: DependencyMaterialConfig{pipelineName='UpstreamPipeline', stageName='release'}
```

**Comment by JorritSalverda** [comment]
Could this be caused by the removed dependent material still being present in the db? Or is it a bug in 15.2?

**Comment by arvindsv** [comment]
I doubt it's a bug (not that I cannot be wrong). I don't think much was changed around that area - apart from adding some logging. Maybe it has something to do with removing triangle resolution as a fall back? /cc @srinivasupadhya?

**Comment by srinivasupadhya** [comment]
`DownstreamPipeline` has a dependency on `UpstreamPipeline - release` but there is not a single green build of it. this happens if you have created a pipeline newly / renamed the stage/pipeline.

**Comment by JorritSalverda** [comment]
It's actually a set of pipelines depending on each other.

a -> b -> c -> d -> e

Both **d** and **e** give the scheduling error. **d** used to depend on **a** as well, but I removed that dependency. No stages or pipelines have been renamed though. Now **d** only depends on **c** and a git repo.  **c** has a green build for the stage **d** depends on, although it's 20 builds back. But **e** should definitely kick in though with the last build of **d** being green.

Running them manually works fine though. And cloning the pipelines **d** and **e** didn't fix it, so deleted those again.

**Comment by JorritSalverda** [comment]
I have a workaround that fixes it for now, by setting the following cron timer specification in pipeline **d** and **e**

```
0 0/1 * * * ?
```

With **Run only on new material** checked.

**Comment by codemonkeycode** [comment]
@JorritSalverda did you ever make any more progress on this? I believe my team is having a similar issue #1529 

We got around the issue temporarily by creating identical pipelines (going through the initialization process if you will), not cloning, when we cloned the pipelines the downstream auto trigger issue remained. After a time though the new pipelines had the same issue

**Comment by joel74** [comment]
I believe I'm having the same issue as well with 3 different pipelines.

For example, I have a database warmup pipeline for my UAT environment that I want to trigger upon the successful completion of the 'Deploy database' stage of the 'Deploy UAT' pipeline.
However, it seems like the 'Warmup UAT Database' pipeline wants to be triggered perpetually, and (fortunately) it's failing.
Error while scheduling pipeline: WarmupDB_UAT as no compatible revisions were identified. [Jan-20 14:18:13] 
Failed resolution of pipeline WarmupDB_UAT : Cause : No valid revisions found for the upstream dependency: DependencyMaterialConfig{pipelineName='Atlas_Deploy_UAT_Chicago', stageName='Deploy_DB'}

This upstream dependency is the material that the WarmupDB_UAT pipeline should trigger based on, but this stage last ran over a week ago.

**Comment by manojtr** [comment]
I think I am also having the same issue. For me it loos like below. 

Before the error it was like 

a -> b. In this b depends on a stage in a and also a git repo. This was working. 

Then I changed this to 

c -> b. In this changed the dependancy from a  to c and stage name also changes. Now it always shows the error in the console as

```
Failed resolution of pipeline b : Cause : No valid revisions found for the upstream dependency: DependencyMaterialConfig{pipelineName='c', stageName='defaultstage'}
```

Manual run works but no automatic run.

**Comment by JorritSalverda** [comment]
It seems there are some serious edge cases where go.cd fails to do what it should. I haven't seen this particular issue any more but we do have frequent material polling hangs where only a restart suffices. See ticket https://github.com/gocd/gocd/issues/2092

**Comment by pracplayopen** [comment]
we also experienced this issue on svn pipelines with upstreams and downstreams.   it was also causing large amounts of unnecessary svn traffic, even when no changes to the materials occurred.

jorrit workaround of using chron scheduling and 'run on new materials' seems to have corrected both the console error about 'no valid revision' and the bandwidth utilization.

this error does not show up on any of our git repositories, even those which have upstreams and downstreams.

**Comment by brettcave** [comment]
We are experiencing the same thing. pipelineA has 1 stage with 1 job. pipelineB has a material of pipelineA/Stage (only - no other materials). PipelineB has `Automatic pipeline scheduling enabled`. Label template is `${pipelineAMaterialName}` so that the labels correlate. The only stage in pipelineB has `Fetch Materials` and `Clean Working Directory` enabled. Error dialog shows the following:


    Error while scheduling pipeline: PipelineB as no compatible revisions were identified. [Mar-19 07:15:55]
    Failed resolution of pipeline PipelineB : Cause : No valid revisions found for the upstream dependency: DependencyMaterialConfig{pipelineName='PipelineA', stageName='Stage'}

I have manually run PipelineA again to get a successful green `Stage` and PipelineB doesn't trigger. Running PipelineB manually works, although in Value Stream view, it shows `Built from incompatible revisions`. 

GoCD 16.7.0. 

PipelineA has 6 materials - 5 x pipelines (with 2 different upstream  git repos) and 1 x direct upstream git material (this upstream git is not any of the upstreams for the 5 pipeline materials).

**Comment by brettcave** [comment]
I think I found the issue. PipelineA actually has quite an intricate upstream mapping. It turns out that 1 of the git materials is used in 2 pipelines (e.g. pipelineX and pipelineY) with different triggers (1 is manual, the other on a weekly cron schedule). Both of these pipelines are mapped in upstreams somewhere (2 or 3 degrees up from pipelineA) and so there is a discrepency between the versions of git used in X and Y and ends with the incompatible build. 

A great feature in Go would be to somehow disable dependency validation in the upstream mapping on certain pipelines.

**Comment by vitorarins** [comment]
Hi, is there any progress on this from GoCD team? I feel the idea from @brettcave would fix it for now. So an option to disabe the dependency validation when needed.

**Comment by abbotware** [comment]
I am hitting this issue as well:

Pipeline A 
1 material: svn: server/repo/A
3 stages:  Build, Test, Deploy

Pipeline B 
2 materials:  svn: server/repo/B and  **Pipeline A [Deploy]**

if I switch pipeline B's svn path server/repo/A. the error goes away, but that makes the pipeline useless as I need to something with repo B not A..
