### ISSUE TITLE
Need a build queue

### ISSUE THREAD

**Issue by andreoid** [gocd/gocd#14]
There isn't a summary of what builds are currently waiting in a queue.

Via the agents tab you can see what agents are currently building, but you cannot see what other builds are queued up.

I've hit situations where builds would never be assigned an agent because I don't have an agent with any appropriate resources, or all agents are offline. Whatever. Having a build queue summary would give me a chance to spot these issues.

Even better would be the ability to move jobs up and down the build queue.
e.g. if I have 10 jobs queued, but one is really high priority, I should be able to bump it to the top of the queue.

**Comment by iliasbartolini** [comment]
Hi, we see that this feature request has been here for long time. Is there anyone else working on it?  @arvindsv mentioned it might require some re-architecture. If some more details to put us in the right direction I'd be happy to try to contribute on this.

**Comment by srinivasupadhya** [comment]
[related thread](https://groups.google.com/d/topic/go-cd/FF9eQunSmFY/discussion)

**Comment by arvindsv** [comment]
Always happy to help someone contribute!

Here's what exists today. The [scheduled jobs API](http://www.go.cd/documentation/user/current/api/job_api.html#scheduled-jobs) lists all the scheduled jobs currently in the queue.

If I were to work on this, I'd look at [tracing](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/config/routes.rb#L291) [through](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/controllers/api/jobs_controller.rb#L38) [that](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/JobInstanceService.java#L214) [code](https://github.com/gocd/gocd/blob/master/server/resources/com/thoughtworks/go/server/dao/maps/JobInstance.xml#L202) (4 links in the 4 previous words, for a start).

You'll then need to start looking at how work gets assigned to an agent, starting [here](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/messaging/scheduling/BuildAssignmentServiceAssigner.java#L42) and then, probably the method which will interest you most is [this one](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/BuildAssignmentService.java#L119).

You should probably think about:
* Whether starvation is a problem
* How a user sees and modifies this (rules or weights for a pipeline, at config time?)
* Should this information be persisted, along with the jobs (initial thoughts say no)
* Performance (it is happening in a [synchronized block](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/BuildAssignmentService.java#L100)

Let me know if you need any more help getting started, or during any part of this!

**Comment by JorritSalverda** [comment]
Look at the implementation in Teamcity, it's really useful to be able to change order and cancel awaiting jobs (or stages or pipelines). Combined with this dedicated queue page it would help if a waiting and running stage didn't show up with the same orange/yellow bar, but had different colors.

**Comment by sekhar0** [comment]
any more information on this ?

**Comment by arvindsv** [comment]
None. There's no one working on it right now. If you or someone else is willing to contribute or take a look at it, someone can definitely help you get started!

If not, no more news about this at this time.

**Comment by DonMartin76** [comment]
Another use case for this is when you build a library which is used by other pipes. If you have concurrent changes (e.g. due to a merge or such), it would totally make sense to prioritize the library/base image/base component as it might trigger additional rebuilds of depending pipelines after it has built.

**Comment by FredrikWendt** [comment]
@DonMartin76 I would argue the other way around - I could easily see how one of my clients would be stuck in "the core lib changes so fast, that nothing ever gets built all the way down the pipeline graph". I think the current scheduling/implementation is just fine.

I'd just like to get better insight into when jobs _don't_ kick off and there are free agents which _should_ pick up the work. This is usually because of resource needs, not available on any agent, but it's hard to spot and track down.

**Comment by MPV** [comment]
Until GoCD gets a built-in UI for this, maybe we (in this thread) could make use of this API?

>Lists all the current job instances which are scheduled but not yet assigned to any agent.
-- https://api.gocd.org/current/#get-scheduled-jobs

**Comment by evandam** [comment]
Are there any updates on this? It's been backlogged for over a year and I think this is a really important feature to be able to first see what jobs are queued, and then be able to manage priority of jobs in the queue.
