### ISSUE TITLE
Package repositories for Go packages

### ISSUE THREAD

**Issue by drrb** [gocd/gocd#140]
It'd be much easier to manage a Go installation if Go packages were published to YUM/APT repositories. They could then be installed and upgraded without downloading from the website.

**Comment by tiwoc** [comment]
There are now public APT and YUM repositories which are linked to in the upper part of the [go.cd download page](http://www.go.cd/download/), so this issue can be closed. I created a new issue for the [missing GPG key](https://github.com/gocd/gocd/issues/1091).
