### ISSUE TITLE
Make www.go.cd mobile friendly

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#1402]
Current PageSpeed insights for [go.cd](https://developers.google.com/speed/pagespeed/insights/?url=go.cd). It has some recommendations for changing the site to make it more mobile-friendly. Not doing this can affect search results.

**Comment by bamdadd** [comment]
it'll be great if GoCD provides a customisable UI config/template so that we can configure the UI based on our requirement (including Mobile friendly) , or expose enough information through the API so that we can build our interface with miumum amount of API calls .

**Comment by bamdadd** [comment]
just noticed #1205 which is going to be really helpful

**Comment by arvindsv** [comment]
Closing as the site has completely changed.
