### ISSUE TITLE
Make embedded SQL cross compatible

### ISSUE THREAD

**Issue by sandopolus** [gocd/gocd#1406]
There is some SQL embedded in the server project java code and some of it is not cross compatible with different databases. I am currently working on getting GoCD working with MySQL SQL compatible databases and i have identified some SQL which is currently not compatible.

MaterialRepository has 2 SQL statements at [SQL 1](https://github.com/gocd/gocd/blob/15.2.0/server/src/com/thoughtworks/go/server/persistence/MaterialRepository.java#L144-L148) and [SQL 2](https://github.com/gocd/gocd/blob/15.2.0/server/src/com/thoughtworks/go/server/persistence/MaterialRepository.java#L174-L179) which is a simple fix of changing the alias 'mod' as it is a reserved word in MySQL.

PipelineRepository has [SQL 3](https://github.com/gocd/gocd/blob/15.2.0/server/src/com/thoughtworks/go/server/persistence/PipelineRepository.java#L111-L116) which i would like to ask a question about the Cast statements.
My main question is do we need these cast statements at all?
According to the DB deltas Pipelines.name is already a VARCHAR and Materials.fingerprint is a CHAR.

It appears this code hasn't been changed since the initial commit to the github repo and so i don't know the reason/history for having it this way.
I have done some initial testing of the modified code and it seems to operate fine without the cast statements.
But thought i would get some feedback before issuing a pull request with the changes.

Thanks

**Comment by arvindsv** [comment]
I've replied on the [mailing list thread](https://groups.google.com/d/msg/go-cd-dev/DxJo-z0QpyY/li0X9Rc-AwAJ).

**Comment by sandopolus** [comment]
I have created pull request #1415 after the discussion on the [gocd dev mailing list](https://groups.google.com/forum/#!msg/go-cd-dev/DxJo-z0QpyY/li0X9Rc-AwAJ)

This extends the QueryExtensions interface to allow overriding of the retrieveTimeline query and fixes the queries which use the alias 'mod'
