### ISSUE TITLE
Spaces are not trimmed from environment variables

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1411]
I was under the impression I was overriding an environment variable, but judging from this log it turns out that one of the environment variables has a space at the end. I would expect that to be trimmed, as it's unlikely to be valid on any operating system.

14:30:09.878 [go] setting environment variable 'CACHE_CHECK_ERROR_ACTION' to value 'Stop'
14:30:09.893 [go] setting environment variable 'CACHE_CHECK_ERROR_ACTION ' to value 'Continue'

**Comment by rajiesh** [comment]
verified in GoCD version 16.10.0 (4129-e51ab2ff4bc66d88a93254c209ee60e42a1112bc). Working as expected
