### ISSUE TITLE
Easy access to configuration page.

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1419]
As a user of go I should have easy access to the configuration page so that I can configure a stage, job, or task without having to navigate back to the settings (cog) button on the go dashboard (landing page).

Part of what is being done by 
https://github.com/programmiersportgruppe/go-defrustrator

**Comment by reidca** [comment]
Possible duplicate/related to #305

**Comment by arvindsv** [comment]
Closing as stale.
