### ISSUE TITLE
Console output with ansi colors

### ISSUE THREAD

**Issue by selvakn** [gocd/gocd#142]
Like https://wiki.jenkins-ci.org/display/JENKINS/AnsiColor+Plugin

**Comment by scottmuc** [comment]
I would very much like this! Here's a snippet of output that we would like to see colourized:

    12:35:10.012 [32m12:35:10 [local] OUT[0m   libp11-kit0 libpopt0 libquadmath0

**Comment by ketan** [comment]
scott - this feature is currently behind a toggle. However it only works when the build is running, not after it is completed.

We're working on an alternative implementation that works both when the build is running as well as after it is completed - #1130

**Comment by chopraapooja** [comment]
I am picking this to test.

**Comment by chopraapooja** [comment]
ANSI colors, switching themes, GUI seems working fine.
Found two issues : [#1196] (https://github.com/gocd/gocd/issues/1196) and [#1221] (https://github.com/gocd/gocd/issues/1221)

**Comment by srinivasupadhya** [comment]
both #1196 and #1221 don't seem to be related to this story. closing this since @chopraapooja is done testing this.

**Comment by scottmuc** [comment]
Awesome! Hope to give go.cd another whirl on my project.
