### ISSUE TITLE
Create pipeline by code

### ISSUE THREAD

**Issue by eleite77** [gocd/gocd#1431]
hello
the documentation is very light about the ability to create a pipeline with a curl command

Where should i find detailled help for that command : 
POST /go/tab/admin/pipelines/:pipeline_name.json
My idea is creating dynamiccaly a lot of pipelines based to an existing one and just pull the good parameters on it...

thanks

**Comment by ketan** [comment]
I'm going to close this issue out. Please ask questions on the forums (https://groups.google.com/forum/#!forum/go-cd).
