### ISSUE TITLE
Auto-populate users email address from LDAP

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#144]
When users authenticate from LDAP the email address should be accessible to GO therefore GO should use this to field automatically. This would allow email notification to be setup much more simply and be less error prone.

**Comment by dsenecalb** [comment]
+1

**Comment by zabil** [comment]
This behavior comes up on authentication plugins too
https://groups.google.com/forum/#!topic/go-cd/_5J1cDcsIhk

**Comment by zabil** [comment]
Can be fixed by changing the behavior to use email id here
https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/security/providers/GoAuthenticationProvider.java#L40

**Comment by lenucksi** [comment]
:+1:
