### ISSUE TITLE
Operations on Pipelines, Stages and Jobs API 

### ISSUE THREAD

**Issue by juhijariwala** [gocd/gocd#1440]
I would like to propose a new format for different operations on pipelines, stages and jobs API. 

**Pipelines API operations:**
1. Schedule 
   
   ```
      PATCH http://ci.example.com/go/api/pipelines/pipeline1
      Content-Type: application/json
   
      {
        “operation”: “schedule”
      }
   ```
2. Release Lock
   
   ```
    PATCH http://ci.example.com/go/api/pipelines/pipeline1
    Content-Type: application/json
   
    {
        “operation”: “release_lock”
    }  
   ```
3. Pause
   
   ```
      PATCH https://ci.example.com/go/api/pipelines/pipeline1
      Content-Type: application/json
   
      {
         “operation”: “pause”,
         “operation-data” : {
           “reason”: “because i can”
          }
      }
   ```
4. Unpause
   
   ```
      PATCH https://ci.example.com/go/api/pipelines/pipeline1
      Content-Type: application/json
   
      {
         “operation”: “unpause”
      }
   ```

**Stages API operations:**
1. Cancel
   
   ```
    PATCH https://ci.example.com/go/api/stages/myPipeline/myStages
    Content-Type: application/json
   
    {
       “operation”: “cancel”
    }
   ```
2. Schedule/Rerun
   
   ```
      PATCH https://ci.example.com/go/api/stages/myPipeline/1/myStages
      Content-Type: application/json
   
      {
         “operation”: “schedule”
      }
   ```

**Jobs API Operation:**
1. Re-run
   
   ```
    PATCH https://ci.example.com/go/api/pipelines/myPipeline/1/stage1/1/job1
    Content-Type: application/json
   
    {
       “operation”: “rerun”
    }
   ```

**Comment by arvindsv** [comment]
Smells like @ketan's influence. Just saying.

I wonder if there's a bit of an existential question about the schedule operations. I don't think the resource exists, before schedule. So, is PATCH the right method for it?

**Comment by juhijariwala** [comment]
It is not @ketan's influence :)
We are not passing stage instance(counter) we are just passing pipeline instance.

**Comment by arvindsv** [comment]
> It is not @ketan's influence :)

It was not a complaint. :) But, if it's not, that's good too.

> We are not passing stage instance(counter) we are just passing pipeline instance.

Ok, that makes sense then.

**Comment by grahamc** [comment]
> > We are not passing stage instance(counter) we are just passing pipeline instance.
> Ok, that makes sense then.

I disagree, I think you were right. You're not altering an existing pipeline by saying "Schedule" you're instantiating that pipeline. I don't think PATCH is an appropriate verb here, but that POST would more likely be correct.

**Comment by arvindsv** [comment]
Well, it all comes down to whether the pipeline instance resource exists - before being scheduled. In a strict sense, it doesn't - it gets created on schedule. So, I think @grahamc is right.

**Comment by juhijariwala** [comment]
I also agree with @grahamc.
So Stage and Job schedule/rerun operation will look like below.

1. Stage Schedule/Rerun

  ``` 
     POST https://ci.example.com/go/api/stages/myPipeline/1/myStages
     Content-Type: application/json

     {
        “operation”: “schedule”
     }
   ```  


2. Job Re-run
   
    ``` 
     POST https://ci.example.com/go/api/pipelines/myPipeline/1/stage1/1/job1
     Content-Type: application/json

     {
        “operation”: “rerun”
     }
   ```

**Comment by zabil** [comment]
I agree with @grahamc on the POST bit for scheduling.  But posting RPC style (as mentioned above) to a resource ```https://ci.example.com/go/api/stages/myPipeline/1/myStages``` doesn't look right.

Can it be an instruction to a scheduler resource which can return a url to the pipeline to follow up on the status of the pipeline run?

```
POST https://ci.example.com/go/api/scheduler
   Content-Type: application/json

   {
      “link”: “/pipeline”
   }
```

Response 
```
202 Accepted
{
 // link to the created pipeline resource.
}
```

As for rerun operation it's on existing resource a PATCH operation is right because it's an instruction to a specific instance (which can be on counter 1,2).  

I also agree on DELETE a a better verb for canceling a run.

**Comment by ketan** [comment]
@zabil - I think there's some confusion about identifiers in the URLs -

The following HTTP request `https://ci.example.com/go/api/stages/myPipeline/1/myStage` basically suggests scheduling a stage named `myStage` in a pipeline called `myPipeline` with counter `1`. We are not providing a `stageCounter` in the URL, as such a `POST` indeed does make sense.

Ditto with the job re-run URL.

Does that clarification help?

As far as the response is concerned, a `202 Accepted` indicates to the client that the request is accepted and that the server **MAY** create the resource. I feel it is more appropriate to instead send a `201 Created` along with a `Location` header pointing to the resource that got created, along with the current state of the resource in the body. See [this page](https://developer.github.com/v3/repos/statuses/#create-a-status) for a good example of what I mean.

As a more concrete example, this is what I'm thinking about -


```HTTP
POST https://ci.example.com/go/api/stages/:pipeline_name/:pipeline_counter/:stage_name
Content-Type: application/json

{
    "operation": "schedule"
}
```

With the response being -

```
201 Created
Content-Type: '...'
Location: https://ci.example.com/go/api/stages/:pipeline_name/:pipeline_counter/:stage_name/:stage_counter

{
   // stage object here.
}
```

**Comment by Ajayc31** [comment]
Hey Hi, 

The Above proposed solution is ready to use yet? I tried to triggered jobs using above but was not worked

**Comment by kritika-singh3** [comment]
@Ajayc31 
 - The pipeline operations API were introduced in GoCD version 18.2.0 and is documented [here](https://api.gocd.org/current/#pause-a-pipeline)
 - The stage and job operations API were introduced in GoCD version 18.11.0 and is documented [here](https://api.gocd.org/current/#run-stage)
