### ISSUE TITLE
Artifacts with empty folder

### ISSUE THREAD

**Issue by eleite77** [gocd/gocd#1446]
Hello

i create a job with an artifact
the goal of this job is to generate sql files but not at each time. it depends of some changes in the database
the problem is when it not generate SQLfiles the folder is empty and this artifact can't be mounted correctly by go

I have this error "The rule [Deploy/*] cannot match any resource under [pipelines/xxx]"

thanks for your help

**Comment by zabil** [comment]
This is the expected behavior.

For ideas on how to work around this, please search/ask the gocd user forums.
