### ISSUE TITLE
Environment Variables OverWrite

### ISSUE THREAD

**Issue by mahesh3267** [gocd/gocd#1447]
Hi All, 

Myself looking for overwrite option for Template -> Stage Environment variables with Pipeline Environment Variables. 

having trouble to overwrite the Environment variables through pipeline. 

Kindly suggest. 

Regards,
Mahesh K

**Comment by ketan** [comment]
Please send any queries to the go-cd forum at https://groups.google.com/forum/#!forum/go-cd.
