### ISSUE TITLE
Viewing and changing 'Automatic pipeline scheduling' setting is not available in a pipeline template

### ISSUE THREAD

**Issue by joel74** [gocd/gocd#1449]
I've found that if I select 'Automatic pipeline scheduling' in a pipeline before I extract the template from it, this will be available and set for pipelines that use this template. However, I cannot edit the template to select or unselect 'Automatic pipeline scheduling.'

**Comment by leoanjossantos** [comment]
Is this issue solved?

**Comment by arvindsv** [comment]
@leoanjossantos No. This is the same as #3, I believe. So, I'll close this in favor of that. The UI of this gets a little tricky (it'll need to be a param, but sometimes a checkbox/radio button. Not worked on by anyone yet.

**Comment by arvindsv** [comment]
@leoanjossantos No. This is the same as #3, I believe. So, I'll close this in favor of that. The UI of this gets a little tricky (it'll need to be a param, but sometimes a checkbox/radio button). Not worked on by anyone yet.
