### ISSUE TITLE
Require login if no ldap or password file is set but oauth plugin is configured

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1453]
I've configured the Google Oauth plugin - https://github.com/srinivasupadhya/gocd-oauth-login/ - on a fresh machine but it doesn't present me a login. I would expect a login screen with just the Google Oauth button/logo.

How do I force gocd into authentication mode?

**Comment by srinivasupadhya** [comment]
explained here - https://github.com/srinivasupadhya/gocd-oauth-login/issues/8

**Comment by JorritSalverda** [comment]
Thanks that worked. Shall I put in an improvement to be able to get this to work without that trick and hiding the username/password fields if just oauth plugin is used? That would be nice.
