### ISSUE TITLE
Formatted console output with incorrect formatting

### ISSUE THREAD

**Issue by kwasniew** [gocd/gocd#1456]
After upgrade from 14.2 to 15.2.0(2248-c1f90a6aa3192a) I found that GoCD rich console output formatting breaks on Heroku logs that include [K (clear line from cursor right) ANSI escape sequence at the end of every single log line. 

E.g 
Raw output
14:01:00.828 remote: Compressing source files... done.[K
14:01:00.828 remote: Building source:[K
turns into
14:01:00.828 remote: Compressing source files... done.ote: Building source:ote:

**Comment by ketan** [comment]
Can you provide us the raw logs (or snippets of it?)

Could either be a dup of #1376 or an escape sequence that the ansi parser is unable to understand.

**Comment by kwasniew** [comment]
Gist with part of log file: https://gist.github.com/kwasniew/0d69c272ae8462ce665f
<img width="1132" alt="screen shot 2015-08-26 at 17 07 24" src="https://cloud.githubusercontent.com/assets/1394682/9497404/19670988-4c15-11e5-9cc8-af1c834ac708.png">
<img width="802" alt="screen shot 2015-08-26 at 17 07 04" src="https://cloud.githubusercontent.com/assets/1394682/9497409/1c348aa0-4c15-11e5-8f1b-1723fd2bb6d3.png">

**Comment by ketan** [comment]
Thanks for the input. I did manage to reproduce this issue. Here is the jsfiddle to reproduce the issue - http://jsfiddle.net/ketanpkr/m87rxnye/

The "fix" seems to be to upgrade `ansi_up` to a newer version. Here is the same fiddle  with a newer ansi up version - http://jsfiddle.net/ketanpkr/p7hhpL4r/

**Comment by kwasniew** [comment]
Yes, that's it :) Closing the issue. Thanks for a quick investigation.

**Comment by ketan** [comment]
Reopening, the issue us not fixed yet.

**Comment by rajiesh** [comment]
verified on 15.3.0-2672(47fd7343016e4a9cda3f8a871539007c2d1cf1b9) and is working as expected
