### ISSUE TITLE
Allow server to return external ssl port behind proxy or in docker container

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1459]
When using external port 443 for ssl while GO_SERVER_SSL_PORT is still set to 8154 internally the wrong port is returned to agents trying to connect. Instead of having a proxy rewrite all urls it should be possible to return the correct external port. With docker it's not possible to perform the rewrite, so it makes dockerizing the server practically impossible.

Setting the ports in /etc/defaults/go-server to 80 and 443 inside the docker container results in a socketexception as non-privileged users are not allowed to bind ports below 1024.

The url returned to the agents should be formed from the secure url in the server configuration instead of using the configured port.

**Comment by grahamc** [comment]
To be clear, you want the ability to specify the listen port separately from the advertise port?

What we do is:

1. GoCD listens on 8153 and 8154 as standard.
2. Agents connect to the GoCD server over 8153 / 8154
3. End-Users connect through a proxy / load balancer which handles 80 and 443 traffic and rewrites both ports to GocD's 8153 port.

Visually:

![](https://graphvizrender.herokuapp.com/render?url=https://gist.githubusercontent.com/grahamc/6cb486c1fba2728e7eb1/raw/a3e755fb8237b3bb700bdaf01674be8f18b79ade/gistfile1.txt)

**Comment by JorritSalverda** [comment]
In my case there's no load balancer but port mapping using docker. No offloading in that case either because 443 goes directly to 8154. However I want the agents to connect to 80 and 443 as well, so I do not additionally have to keep 8154 open as well.

**Comment by grahamc** [comment]
Right so I go back to the first bit, which is specifically what you're looking for is the ability to specify the listen port separately from the advertise port, so go will listen on 8153/8154 and still know to advertise :80 / :443?

**Comment by JorritSalverda** [comment]
Yep, that would be brilliant. Or maybe even better is the request from https://github.com/gocd/gocd/issues/35 so the port is defined on the agent side, instead of asking the server for its ssl port.

**Comment by JorritSalverda** [comment]
I've work around this by putting haproxy in front of it after all. And still letting the agents use port 8153 and 8154, which are only available internally.
