### ISSUE TITLE
Running 15.3.0(2409-0256d8f868257a) fails to start 

### ISSUE THREAD

**Issue by grahamc** [gocd/gocd#1460]
Starting the new servers ends up running:
```
exec /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java -jar '"/bin/agent-bootstrapper.jar"' server 8153
```
at the end of the startup script. Note the extraneous quotes on the bootstrapper.jar. This then elicits:

```
Error: Unable to access jarfile "/bin/agent-bootstrapper.jar"
```

Which looks right because you think the quotes are there to be helpful, but they're not, it is literally trying to execute a file located at `./"/bin/agent-bootstrapper.jar"`.

**Comment by ketan** [comment]
I don't recall anything having changed in there. @arvindsv ?

**Comment by grahamc** [comment]
Aye, I meant to link to this: https://github.com/gocd/gocd/pull/1379

**Comment by arvindsv** [comment]
Yes, that's the one I thought about as well. I'll take a look at it, in a few minutes, unless one of you is. Let me know.

**Comment by ketan** [comment]
I'm not looking at it.

**Comment by grahamc** [comment]
I will be, but not until this afternoon.

**Comment by arvindsv** [comment]
Ok, I'll take a look now.

**Comment by arvindsv** [comment]
Hmm, that won't work. Just using `exec`. Nothing is taking care of the quotes. @grahamc, when you try it, can you replace that line with:

```
eval exec "$CMD"
```

instead and try?

**Comment by arvindsv** [comment]
It'll finally use exec, and replace the shell process, as it should.

**Comment by rajiesh** [comment]
this has been QA tested on 15.3.0-2597 build on MAC OSX, linux(centOS and Ubuntu) and solaris
