### ISSUE TITLE
Turning on 256 colors in console logs

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1461]
Older versions of `ansi_up` only supported a few basic colors (black, red, green, yellow, blue, magenta, cyan, white). An upgrade post #1457, we can now use true 24 bit colors.

Here is a screenshot of the output from the old ansi parser - https://github.com/gocd/gocd/pull/1130#issuecomment-106939584. Here is how it looks now http://jsfiddle.net/ketanpkr/kvwzz1pq/.
### What will be affected with this change?

As of now, since we are only supporting 8 colors, this was done by using simple css classes. Ansi Up, would add a few select css classes to each HTML element having color, turning on full color would mean that we inline color as a `style` element on each element of color. This means that html elements will go from looking like `<span style='ansi-blue-fg ansi-bright-white-bg'>` to something like `<span style='color:rgb(0, 255, 0);background-color:rgb(85, 255, 255)'>`

However since this change only affects elements that have color (and even the largest builds have only small bits of colors), and may increase the memory footprint to render console logs with lots of elements of different color.

What does everyone think?

**Comment by arvindsv** [comment]
Since the assumption is that the colored lines won't be too many, this should be ok, I feel.

**Comment by grahamc** [comment]
How many do you think would be too many? One of my builds (packer) outputs a wall of green text.

**Comment by ketan** [comment]
One green wall of text is still just one color. This may severely affect users who have too many pieces of **different colors**, since each color needs to be in a `<span/>` of its own.

**Comment by arvindsv** [comment]
Yes, exactly. That's why I think it's going to be ok, since not too many builds have too many colors.

It need not only be different colors, though. It's more about contiguous blocks of colors. If you have a 1000 lines alternating between green and white, then there will be 1000 spans. Still not a common case, I feel, unless you regularly use [nyan](http://nyancat.dakko.us/) [cat](http://bruxy.regnet.cz/web/linux/EN/bash-nyan-cat/) as a part of your build.

**Comment by Webysther** [comment]
Force colors in terminal log show something like this:

![colors](https://cloud.githubusercontent.com/assets/750007/22848385/24640d48-efdb-11e6-8e50-3c3be737accf.png)

**Comment by ketan** [comment]
Would you mind downloading the raw console log (using curl) and attaching it here?

**Comment by Webysther** [comment]
@ketan i hope this help [output_console.log.zip](https://github.com/gocd/gocd/files/775719/output_console.log.zip)

**Comment by Webysther** [comment]
As a sample code, gitlab have in CI a great output of console log, see here:

https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/builds/10480546

**Comment by Webysther** [comment]
See code here: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/app/views/projects/builds/show.html.haml

**Comment by arvindsv** [comment]
I like Snap's as well: https://app.snap-ci.com/gocd/www.go.cd/branch/master/logs/defaultPipeline/297/Preview?back_to=build_history

We have some people from the Snap team helping out, to make GoCD console log better. So, expect to see improvements soon.

**Comment by Stono** [comment]
Hey, just wondering if there is any progress in this.
I see the console improving, which is great, however the output from my containers running things like grunt still don't show colours.

**Comment by Webysther** [comment]
Yes. On version 17.5 will mostly fixed:

![ascii](https://user-images.githubusercontent.com/750007/29134817-6513a9c8-7d0e-11e7-95bc-dff732486ce4.png)

There's a problem in some `eol` but work well in 95% cases:

![eol](https://user-images.githubusercontent.com/750007/29134867-962d2c64-7d0e-11e7-8d8b-ceb328d955d5.png)

[console.log.zip](https://github.com/gocd/gocd/files/1212341/console.log.zip)

**Comment by Webysther** [comment]
This issue can be closed and another with specific problems be open.

**Comment by Webysther** [comment]
With forced colors:

![forced](https://user-images.githubusercontent.com/750007/29135013-139a1e46-7d0f-11e7-938f-232a6fdf168e.png)

**Comment by Stono** [comment]
@webdevwilson how do you do forced colors?

I'm on 17.8
Go includes third-party software. Go Version: 17.8.0 (5277-32ff863cce99f97b76abb1b88469a793e3b1adc5).

**Comment by Webysther** [comment]
Normally:

```shell
npm install --color always
gulp --color always
```

Differs between tools, but mostly cases is `--color always` or `--colors` and `--ansi`

**Comment by ketan** [comment]
> how do you do forced colors?

Usually build tools detect presence of tty to determine if it should output colors. You will need to lookup the manual for the particular tool that does not output colors when a try is not present. Usually `--color` is supported by most popular tools, but YMMV

**Comment by ketan** [comment]
The eol problem is usually the tool assuming that the console is tty. So it ends up spitting out ANSI control characters which have no equivalent in the  HTML/browser world. `rsync` is one such example. See the output here https://build.gocd.org/go/tab/build/detail/UploadInstallers/408/UploadInstallers/1/UploadInstallers

**Comment by Webysther** [comment]
@ketan lack-of-tty detection if used pipe "|" on cli. Sometimes if you run like job from another cli tool will disabled detection and ANSI without color is forced. All my cases on GoCD and Gitlab put option.
