### ISSUE TITLE
Alpine packages do not exist

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1480]
I've created a gocd server and agent docker container - https://github.com/JorritSalverda/docker-gocd-server and https://github.com/JorritSalverda/docker-gocd-agent - which are based of off debian:jessie. They are still very large at 416 and 154 MB.

I'm trying to shrink those by another 79MB by basing them off of alpine linux, however there is not gocd package for neither the server and the agent on https://pkgs.alpinelinux.org/packages.

Could you provide packages for Alpine Linux? Instructions on how to create them are at http://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package. OpenJDK support used to be an issue on alpine, but is there these days and can be installed with ```apk --update add openjdk7-jre```. Thanks.

**Comment by zabil** [comment]
Have you tried using the zip installers? They are distribution agnostic and can be used for alpine linux.
Officially, we don't have the resources (build/test machines, test scripts etc) to add and maintain alpine packages. 

 Closing this for now. If someone wants to provide an un-official repo please feel free to do so.
