### ISSUE TITLE
Feature request: Get a list of the environment variables set by gocd.

### ISSUE THREAD

**Issue by sbuss** [gocd/gocd#1483]
Part of my deploy workflow involves invoking a `config:set key1=var1 key2=var2` command. Unfortunately I haven't found any way to get a list of environment & secure env vars set via a gocd pipeline. I've had to resort to setting a `CONFIG_VARS='key1 key2...'` variable and iterating through that.

Is there an undocumented hook or variable in gocd that exposes this information?

**Comment by ketan** [comment]
There is no API to get just the list of environment variables, there is an (undocumented) API to get the pipeline config xml but parsing it to make sense of environments after merging it across stages/jobs/pipelines/templates will be a PITA.

I'd suggest using a simple prefix based solution to this problem, assuming all your (go) variables are prefixed with `HEROKU_CFG_`. The following script should do the trick -

```bash
heroku config:set $(env | grep HEROKU_CFG_ | sed s/HEROKU_CFG_//g | tr '\n' ' ')
```

**Comment by sbuss** [comment]
Ha, of course! That's an embarrassingly simple solution which I didn't think of. That will work fine for me. Thanks, @ketan. Closing.
