### ISSUE TITLE
Ability to debug config save slower than X seconds

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#1488]
The ability to save the whole config that is taking more than X seconds, so that we can debug issues related to slow config save. Something like `-Ddebug.config.save.slower.than=3000` might be very useful.

Today, if a config save is slow, and it is slow when trying to save a change, there is no way to know what the change is (that is causing a slow config save), till it is done. If it fails to save, for whatever reason, then we will never know what took so long.

**Comment by rajiesh** [comment]
@arvindsv what is the status of this issue? is there a fix available?

**Comment by arvindsv** [comment]
Removed it from this milestone. #1664 will allow us to see slow config saves in logs and the users who made them, but won't help with content of the change.

**Comment by arvindsv** [comment]
With other config related API changes, etc. I'd like to wait before doing anything on this. It was just an idea. I'll actually close this for now. It needs more thought.
