### ISSUE TITLE
GoCD 15.2's config schema (cruise-config.xsd) causes validation errors

### ISSUE THREAD

**Issue by pepoirot** [gocd/gocd#1489]
### Context

A local build is used to validate changes to a shared Go instance's configuration before it is applied.

### Problem

Since switching from Go 14.2.0 to 15.2.0, the configuration of the Go config now fails to validate against the official schema ([cruise-config.xsd](https://github.com/gocd/gocd/blob/15.2.0/config/config-server/resources/cruise-config.xsd)).

The error is reproducible on either Mac (10.10.5) or Linux (Centos 6) with an empty configuration:

#### Centos 6 (libxml 2.6.26):

```sh
$ uname -rs
Linux 2.6.18-404.el5

$ xmllint --version 2>&1 | grep -Eo "libxml version [0-9]+"
libxml version 20626

$ curl -s https://raw.githubusercontent.com/gocd/gocd/15.2.0/config/config-server/resources/cruise-config.xsd > cruise-config-15.2.0.xsd

$ cat > test.xml << EOF
<?xml version="1.0"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="75">
</cruise>
EOF

$ xmllint --noout --schema ./cruise-config-15.2.0.xsd ./test.xml
./cruise-config-15.2.0.xsd:856: element complexType: Schemas parser error : complex type 'onCancelType': The content model is not determinist.
WXS schema ./cruise-config-15.2.0.xsd failed to compile
```

#### MacOS 10.10.5 (libxml 2.9.0):

```sh
$ uname -rs
Darwin 14.5.0

$ xmllint --version 2>&1 | grep -Eo "libxml version [0-9]+"
libxml version 20900

$ curl -s https://raw.githubusercontent.com/gocd/gocd/15.2.0/config/config-server/resources/cruise-config.xsd > cruise-config-15.2.0.xsd

$ cat > test.xml << EOF
<?xml version="1.0"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="75">
</cruise>
EOF

$ xmllint --noout --schema ./cruise-config-15.2.0.xsd ./test.xml
cruise-config-15.2.0.xsd:856: element complexType: Schemas parser error : complex type 'onCancelType': The content model is not determinist.
WXS schema cruise-config-15.2.0.xsd failed to compile
```

#### MacOS 10.10.5 (Java 8):

```sh
$ uname -rs
Darwin 14.5.0

$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

$ git clone -q -b master https://github.com/amouat/xsd-validator

$ ./xsd-validator/xsdv.sh ./cruise-config-15.2.0.xsd ./test.xml
Error reading XML Schema: ./cruise-config-15.2.0.xsd
cos-nonambig: baseTask and WC[##any] (or elements from their substitution group) violate "Unique Particle Attribution". During validation against this schema, ambiguity would be created for those two particles.
```

##### libxml: _The content model is not determinist_

From [Deterministic and Non-Deterministic Schemas](https://msdn.microsoft.com/en-us/library/9bf3997x%28v=VS.71%29.aspx), the two alternatives in the `xsd:choice` in the Go 15.2.0's `complexType` [definition](https://github.com/gocd/gocd/blob/15.2.0/config/config-server/resources/cruise-config.xsd#L856) would match a `<task>` sub-element.

```xml
<xsd:complexType name="onCancelType">
        <xsd:sequence>
            <xsd:choice>
                <xsd:element ref="baseTask" minOccurs="0" maxOccurs="1"/>
                <xsd:any minOccurs="0" maxOccurs="1"/>
            </xsd:choice>
        </xsd:sequence>
    </xsd:complexType>
```

##### Java8: _baseTask and WC[##any] [...] violate "Unique Particle Attribution"_

From [Unique Particle Attribution](https://en.wikipedia.org/wiki/Unique_Particle_Attribution), the cause appears identical. A `<task>` sub-element in a `<oncancel>...</oncancel>` node would match both alternatives (`<xsd:element ref="baseTask" ...>`) or `<xsd:any ...>`.

#### Workaround

Removing the second alternate (`<xsd:any minOccurs="0" maxOccurs="1"/>`) in the `onCancelType` declaration fixes the issue with `libxml`:

```sh
$ diff -U4 ./cruise-config-15.2.0.xsd ./cruise-config-15.2.0-modified.xsd
--- ./cruise-config-15.2.0.xsd	2015-09-14 15:00:10.000000000 +1000
+++ ./cruise-config-15.2.0-modified.xsd	2015-09-14 15:10:30.000000000 +1000
@ -856,9 +856,8 @@
     <xsd:complexType name="onCancelType">
         <xsd:sequence>
             <xsd:choice>
                 <xsd:element ref="baseTask" minOccurs="0" maxOccurs="1"/>
-                <xsd:any minOccurs="0" maxOccurs="1"/>
             </xsd:choice>
         </xsd:sequence>
     </xsd:complexType>
     <xsd:element name="oncancel" type="onCancelType"/>

$ xmllint --noout --schema ./cruise-config-15.2.0-modified.xsd ./test.xml
./test.xml validates
```

With Java8, the issue remains because the `taskType` declaration is also ambiguous:

```xml
<xsd:complexType name="tasksType">
    <xsd:sequence>
        <xsd:element minOccurs="0" maxOccurs="unbounded" ref="baseTask"/>
        <xsd:any minOccurs="0" maxOccurs="unbounded"/>
    </xsd:sequence>
</xsd:complexType>
```

**Comment by rusio** [comment]
We see another validation error on our schemaVersion=75 against the current schema published at this URL: http://www.go.cd/documentation/user/current/resources/cruise-config.xsd, which fixes this value to 72.

If you compare the published schema on the above URL with the one that is installed on the Go-Server via the current 15.2 RPM: http://download.go.cd/gocd-rpm/go-server-15.2.0-2248.noarch.rpm you will see many additions in the 75 version.

So it seems the schema, which is published on the above URL must be updated by the site admins.

**Comment by rajiesh** [comment]
verified on 16.1.0-2855 cruise-config.xsd with schemaVersion 77 and the xml validation using xmllint is successful

**Comment by arvindsv** [comment]
Closing this since it seems to be fixed.
