### ISSUE TITLE
Set Authorization for stages

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1492]
A sub-task of #1404

Design and implement a UI for the new pipeline config edit page to set roles and permissions for executing stages.
Validations: https://github.com/gocd/gocd/issues/2553
For old functionality refer 
http://www.go.cd/documentation/user/current/configuration/dev_authorization.html#adding-authorization-to-approvals

**Comment by varshavaradarajan** [comment]
Closing this as approval is already shown on the quick edit page.
