### ISSUE TITLE
Create a compact view for tasks on a job

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#1496]
This is a subtask of #1404 

Design and implement a compact view for tasks with support for quick re-ordering.
For old functionality refer.

This should not break existing task plugins.
It should also support the "on cancel" tasks. 
http://www.go.cd/documentation/user/current/configuration/admin_add_task.html#add-a-new-task-to-an-existing-job

**Comment by arvindsv** [comment]
@zabil: Can this be closed? I know @maheshp was working on this.

**Comment by zabil** [comment]
I don't think it's over yet.

**Comment by arvindsv** [comment]
Closing as stale.
