### ISSUE TITLE
Improve Email Notification filters

### ISSUE THREAD

**Issue by andreoid** [gocd/gocd#15]
Hey,

It would be great if the email notifications section was enhanced.

Currently you have to manually add a notification filter for every pipeline stage you are interested in.

For people who are interested in multiple stages, across multiple pipelines (we have around 300 pipelines), it is a painful process to add these in, one at a time.

Often users are interested in all stages of a given pipeline, or they are interested in all pipelines in a pipeline group.

A better selection process is needed.

**Comment by srinivasupadhya** [comment]
done with https://github.com/gocd/gocd/pull/229. can modify [email-notifier](https://github.com/srinivasupadhya/email-notifier) if customization is required.

**Comment by matt-richardson** [comment]
How was this done with #229? That appears it was closed without merging?

**Comment by srinivasupadhya** [comment]
someone from the community added feature where users can use wildcard matchers 'any pipeline' / 'any stage' like this:

![screen shot 2015-07-02 at 4 01 39 pm](https://cloud.githubusercontent.com/assets/1587661/8475195/c8a8915e-20d3-11e5-9efe-5ef333b675a1.png)

I assume thats the best could be done with filters?

**Comment by matt-richardson** [comment]
Ahh, it appears the change went in, but just not under #229. Ignore me :)
