### ISSUE TITLE
Report the version of the GO Agent from the Agents view in the server

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#150]
It would be very useful to see which version of the software agents are running from the agents view to ensure the versions are aligned and plan for upgrades where required.

**Comment by moritz** [comment]
I would also find this useful.

I just upgraded my GoCD server and agents (installed through Debian packages, so I don't think any automatic upgrading of agents is going on), and I'd like to find out if I missed any agents in the upgrade.

**Comment by moritz** [comment]
FTR GoCD Version: 20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0). doesn't show the agent version on the agent overview page.

**Comment by arvindsv** [comment]
In 20.5.0, via #8221, this should be available via the API. So, I'm going to close this, even though it is not in the UI. If anyone wants it in the UI, please use the API and submit a PR for that change. Thanks.
