### ISSUE TITLE
Remove undocumented old Dashboard API related code 

### ISSUE THREAD

**Issue by juhijariwala** [gocd/gocd#1504]
Remove old Dashboard API related views, controller, routes, java and helper code.#371

**Comment by GaneshSPatil** [comment]
@arvindsv @ketan  -- whats this issue is about? is it still relevant?

**Comment by arvindsv** [comment]
@GaneshSPatil Closing. It seems to have been removed in https://github.com/gocd/gocd/commit/accac4ebed9438d984cd570c058a03b2c20c6f43.
