### ISSUE TITLE
Task plugin configuration of properties not stored correctly

### ISSUE THREAD

**Issue by nstaeger** [gocd/gocd#1506]
Hi everybody,

I am currently working on a GO task plugin using the JSON API. When I get the [configuration](http://www.go.cd/documentation/developer/writing_go_plugins/task/version_1_0/configuration.html) request from the server, I return a response with the following body:

```
{
    "username": {
        "default-value":"admin",
        "value":null,
        "secure":false,
        "required":true
    },
    "password": {
        "default-value":"badger",
        "value":null,
        "secure":true,
        "required":true
    }
}
```

Later, when I receive the [validation request](http://www.go.cd/documentation/developer/writing_go_plugins/task/version_1_0/validate.html) I get the following request body.

```
{
    "username":{
        "secure":false,
        "value":"admin",
        "required":false
    },
    "password":{
        "secure":false,
        "value":"badger",
        "required":false
    }
}
```

You already see the problem. The validation request has different settings for the _secure_ and _required_ keys, than I set in the configuration request.

Can anyone help me out? What I am doing wrong? Or is this a bug?

Best

**Comment by zabil** [comment]
@nstaeger this might be a problem with how you are binding the fields on template.
Here's an [example](https://github.com/manojlds/gocd-docker/blob/8194bd6ef5b26c65faf6e492ea2878d99dd2e640/docker-task/src/main/resources/views/task.template.html#L28) for handling boolean fields. 
Can you modify your template to this and see if it helps?

**Comment by arvindsv** [comment]
Closing as stale.
