### ISSUE TITLE
Missing information about the package process

### ISSUE THREAD

**Issue by v1v** [gocd/gocd#151]
I haven't found any details about the package generation for redhat/centos/debian/osx/windows. 
After debugging a bit: https://build.go.cd/go/pipelines/distributions-all/3/dist-all/1, those are the list of commands in order to create installers:

```shell
   export GO_VERSION=14.0.1.1 
   ./bn clean cruise:prepare 
   tools/jruby/bin/jruby -J-Xmx1024m -J-Xms512m -S buildr cruise:pkg:zip cruise:pkg:windows cruise:pkg:redhat cruise:pkg:debian ratchet=no test=no DO_NOT_INSTRUMENT_FOR_COVERAGE=true --trace 
   ant build.xml dist.osx 
```

Using the VagrantFile: https://github.com/gocd/go-development-environment-setup/blob/master/Vagrantfile

But there are some missing packages:
```shell
  sudo apt-get install build-essential
  sudo apt-get install rpm
```

I wonder if you can publish further details about the rpm/exe/deb/... generation.

**Comment by arvindsv** [comment]
No action. Closing.
