### ISSUE TITLE
Option to automatically open various views in a new browser tab

### ISSUE THREAD

**Issue by joel74** [gocd/gocd#1513]
I find that I need to work in multiple browser tabs with Go - often one on a pipeline config page and another on a pipeline run page. It would be helpful if every time I clicked the gear to open a pipeline to configure it, it would open a new browser window/tab. It might also be helpful for clicking on a pipeline run to open a new tab.

**Comment by lisabaker3494** [comment]
I am doing that right now.  2 browsers open

**Comment by grahamc** [comment]
I would imagine there are keyboard keys which instruct your browser to open links in a new tab. Are these not sufficient?



- Graham

**Comment by joel74** [comment]
No, I don't think that's sufficient. I feel this should be controlled and controllable at the application level. I don't want to have to change a browser-wide setting just to accommodate one application.

**Comment by grahamc** [comment]
I mean, if I press the control key then click a link, it opens that link in a new tab. 



- Graham

**Comment by joel74** [comment]
Good point, though when I do that in chrome, the new tab doesn't automatically get focus. I can live with it and work around it, but it seems like it'd be nice for it to open with a new tab with focus as the default action.

**Comment by grahamc** [comment]
For whatever reason, my reply didn't get posted:

On a Mac in Chrome: Command + Shift will open a new tab and switch to it.
Windows (probably): Control + Shift

**Comment by joel74** [comment]
Confirmed - Ctrl-Shift does the trick in Windows. 
Thanks.

**Comment by ketan** [comment]
Closing issue
