### ISSUE TITLE
New Users Automatically Granted System Admin Priv!?

### ISSUE THREAD

**Issue by jhull123** [gocd/gocd#1515]
I have Go password file and LDAP user management configured and the "Allow users that exist in LDAP..." checkbox checked.

When a user (either from the password file or LDAP) logs in for the first time they are automatically granted the system administrator privilege.

This is very undesirable! How do I prevent this?

Go Version: 15.2.0(2248-c1f90a6aa3192a)

**Comment by zabil** [comment]
You can control LDAP user access.
http://www.go.cd/documentation/user/current/configuration/dev_authentication.html#controlling-user-access.

 Once you choose not to add users automatically manage them here.
http://www.go.cd/documentation/user/current/configuration/managing_users.html

**Comment by zabil** [comment]
Alternatively if you don't want to manually manage your users you have to explicitly
choose a user to be the super admin (Admin-User Summary tab)

<img width="415" alt="screen shot 2015-09-23 at 11 04 03 am" src="https://cloud.githubusercontent.com/assets/54427/10038393/edeab10e-61e2-11e5-8a05-60a31878b69f.png">

For a new setup if a super admin has not been set all users get admin access.

**Comment by jhull123** [comment]
Thanks, Zabil! I am poking around now and I think the way I am configuring system admins is not quite correct. When I create a new Go server I use the REST API (/go/admin/restful/configuration/file/) to add administrators.

```xml
<admins>
  <user>superadmin</user>
</admins>
```

Somehow this is not sufficient and not the same as giving a user sysadmin via the UI.

**Comment by jhull123** [comment]
So it looks like when you grant system admin priv in the UI, the Go server update cruise-config.xml and the server's Git repository.

I'm guessing that diddling the config XML via the REST API leaves out the Git repo part.

I'm creating my Go server with automation. Is there a way that I can seed the Go server with administrators in an automated way?

**Comment by ketan** [comment]
> When I create a new Go server I use the REST API (/go/admin/restful/configuration/file/) to add administrators.

Can you provide us a reproducible test, starting with a clean install of a go server and a bunch of curl commands that represent the edits you make?

> I'm guessing that diddling the config XML via the REST API leaves out the Git repo part.

That is not correct, whenever the config xmlchanges by whatever means, go will commit it to the git repo.

If you are automating setup of go servers, any means that you use to modify XML is OK, as long as the XML is legit.

**Comment by jhull123** [comment]
> Can you provide us a reproducible test, starting with a clean install of a go server and a bunch of curl commands that represent the edits you make?

Yes.

> If you are automating setup of go servers, any means that you use to modify XML is OK, as long as the XML is legit.

:sunglasses:

**Comment by jhull123** [comment]
I was able to track this down to an error on my side and confirm what @ketan stated. Thank you all for your input!
