### ISSUE TITLE
Cruisewrapper crashes on google compute engine windows 2012 r2

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1519]
When installing go.cd agent 15.2 (go-agent-15.2.0-2248-setup.exe) the installer crashes when cruisewrapper.exe is started.

It gives the following incomprehensible error:

Problem signature:
  Problem Event Name:   BEX
  Application Name: cruisewrapper.exe
  Application Version:  3.3.3.0
  Application Timestamp:    49a4bcbe
  Fault Module Name:    cruisewrapper.exe
  Fault Module Version: 3.3.3.0
  Fault Module Timestamp:   49a4bcbe
  Exception Offset: 00004247
  Exception Code:   c0000409
  Exception Data:   00000000
  OS Version:   6.3.9600.2.0.0.400.8
  Locale ID:    1033
  Additional Information 1: e967
  Additional Information 2: e9673545672d1e03790a1c4bcb93a6b0
  Additional Information 3: 4fb1
  Additional Information 4: 4fb13a0324342e11b2b35014b7a037fa

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\windows\system32\en-US\erofflps.txt

**Comment by JorritSalverda** [comment]
This seems to happen in an image I created from google's windows 2012 r2 base image (windows-server-2012-r2-dc-v20150909). Trying to find out which step in my process leads to this error. 

Any tips on how to find out what is the actual error?

**Comment by JorritSalverda** [comment]
It was caused by not sysprepping the base image. Not sure why cruisewrapper.exe craps out in that case, but my issue is resolved.

**Comment by JorritSalverda** [comment]
Not sure what fixed it before, but it's happening again. The installation acts like it's successful but only half of the files are installed and trying to run the service fails. Can the tanuki java wrapper either be updated or replaced with something more winrm friendly?

**Comment by ketan** [comment]
> The installation acts like it's successful but only half of the files are installed

Is it some sort of a permission issue, usually sysinternals can tell you what's happening.

> Can the tanuki java wrapper either be updated

I think it should be possible to update tanuki, it's been on my mind to update it for a while, but the team currently does not have enough bandwidth to test this out. Would you be willing to try it out?

Just updating the wrapper.exe file with a newer version and restarting may actually do the trick.

**Comment by arvindsv** [comment]
Closing as stale.
