### ISSUE TITLE
Add Environment to the parameters of the Update Agent API

### ISSUE THREAD

**Issue by rmarcinik** [gocd/gocd#1522]
Would it be possible to add the environment value to the API for updating an agent?  It is currently possible [with this method](http://www.go.cd/documentation/user/current/advanced_usage/agent_auto_register.html) but it is not totally reliable.  Sometimes the agent is still in a pending state afterwards, and has no resources or environment.  It would also be beneficial towards automation to control agents fully without the UI.
Thank you.

**Comment by arvindsv** [comment]
Auto register should be reliable. I haven't heard of it not working, unless the agent has the same GUID as another, or something of that sort. The issue with doing what you're talking about is that unlike any other part of the update agent API call, this one will need to send that information all the way to the agent. Also, it *might* need a restart of the agent, etc.

Not something that cannot be done, but it's a bit of work. If you're thinking about making such a change, let me know and I can help. But, in case you're looking for someone from the core team to work on it, it's probably not going to happen soon.

**Comment by arvindsv** [comment]
Actually, please ignore everything I said. I read what you wrote as "environment variable".

**Comment by ketan** [comment]
@rmarcinik - I'm assuming that you mean to say that you want to update add/remove agents from environments in go.

Ideally this api call should belong to environments, and not on an agent. That said, if you're willing to build the API, someone on the team will be very happy to work with you.

**Comment by rmarcinik** [comment]
Thanks for responding, I agree that updating the Environments would be a separate endpoint.  However I dont think there is an endpoint for environments yet, and I am not familiar with what it would take to develop.  
The autoregister method works for initializing agents but it depends on having access to the agents local filesystem, and is less than ideal for modifying the properties of an already enabled agent (or many agents).  I forgot to add, this is for windows agents; so it may work better on linux.

The goal in the end would be to:
* modify agent properties, without access to the local filesystem 
* modify agent properties, without going through the ui

If I had an idea of what this would take to accomplish I could make a proposal to include this in one of our sprints.

Thanks again for your time.

**Comment by ketan** [comment]
On second thought –

I feel that my previous statement a result of my understanding of the structure (less than ideal) `cruise-config.xml` and how `<agent/>s` belong to `<environment/>s` in there.

If I were to think of it in a slightly different manner — in that agents are associated with an environment (and that is really what I feel best describes the relationship between the two, irrespective of how the config file makes it look like).

I'm in favor of allowing the `environments` attribute on an agent to be modified by the agents API – any takers?

**Comment by arvindsv** [comment]
I can deal with that. From a user perspective, that makes sense. But, if an environment API does get created, will there be two ways of doing the same thing? Or, would it always be through the agents API? Would the pipeline API then have a way of associating it with an environment?

We would still need an environments API for environment variables of an environment.

**Comment by ketan** [comment]
Yes there will be multiple ways of achieving the same end result, I don't feel it's too bad because the end goal would be different.

With the agent API, you'd say agent "foo" belongs to environments "pre-prod" and "staging". Where as with the environments API, you'd say make sure that agents "foo" and "bar" are associated with the particular environment resource. Note that these agents *may* be part of other resources as well.

**Comment by ketan** [comment]
@rmarcinik since you opened #1522, would you have any final comments on this API (#1573)?

The API here now accepts an `environment` attribute, and behaves very much like the `resources` attribute. Note that this API is only available when used with `Accept: application/vnd.go.cd.v2+json`.

**Comment by rmarcinik** [comment]
This is great, thanks for taking my suggestion!

**Comment by ketan** [comment]
Reopening, someone on the team will verify this once before close.

**Comment by rajiesh** [comment]
verified it on 15.3.0-2663 and the environment update for agent works as expected. This issue can be closed
