### ISSUE TITLE
Pipeline status API to also get comment and paused by

### ISSUE THREAD

**Issue by therako** [gocd/gocd#1523]
current pipeline status api only gives Paused true/false. It's useful to also get the comment on the paused pipeline and who paused the pipeline.

**Comment by ketan** [comment]
Reopening, someone on the team will verify this (and add additional tests, if needed)

**Comment by ketan** [comment]
PR #1524

**Comment by rajiesh** [comment]
verified pipeline status api for paused and non- paused pipelines with cause message on 15.3.0-2663. Paused By user and paused cause both are availble now. The story can be closed
