### ISSUE TITLE
CentOS 7 go user isn't created

### ISSUE THREAD

**Issue by benhosmer** [gocd/gocd#1527]
According to the docs: http://www.go.cd/documentation/user/current/installation/install/server/linux.html

> The installer will create a user called go if one does not exist on the machine.

However, the installer doesn't actually create the user:

```
usermod: user 'go' does not exist
Installing : go-server-15.2.0-2248.noarch                                     66/66 
chown: invalid user: ‘go:go’
chown: invalid user: ‘go:go’
chown: invalid user: ‘go:go’
chown: invalid user: ‘go:go’
```

**Comment by ketan** [comment]
Dup of #1467 - do you have SELinux running?

**Comment by arvindsv** [comment]
Closing. Haven't heard back from the original author.
