### ISSUE TITLE
gocd server hangs without any and does not build any project

### ISSUE THREAD

**Issue by ranjib** [gocd/gocd#1535]
We are experiencing an issue, where GoCD server hangs, without any noticeable difference in the UI (i.e. ui works), but pipeline does not get executed upon material updates. Even if we force run (via the ui) the pipelines, nothing happens. The server has ample free memory and CPU (4 gigs out of 15gigs of free memory and 4 cpu). Log shows following, which indicates the material update service is working...

``` sh
 2015
2015-10-01 22:35:24,470  WARN [materialUpdateThread] MaterialUpdateService:155 - [Material Update] Skipping update of material GitMaterial{url=git@github.com:FooBar/xxx.git, branch='master', submoduleFolder='null'} which has been in-progress since Thu Oct 01 22:23:24 UTC 2015
2015-10-01 22:35:54,466  WARN [materialUpdateThread] MaterialUpdateService:155 - [Material Update] Skipping update of material GitMaterial{url=git@github.com:FooBar/xxx.git, branch='master', submoduleFolder='null'} which has been in-progress since Thu Oct 01 22:23:24 UTC 2015
```

The only error in the log is related to one pipeline where we are using  PR builder plugin. from @ashwanthkumar

``` sh

3 ERROR [qtp1941055697-1213] JobInstanceService:184 - error notifying listener for job JobInstance{stageId=5476, name='Unit-02', state=Completed, result=Passed, agentUuid='7de64b00-80a0-46a0-a2c5-ef1c14995860', stateTransitions=[com.thoughtworks.go.domain.JobStateTransition@1d7fdc3f[currentState=Scheduled,stateChangeTime=Thu Oct 01 21:25:40 UTC 2015,jobId=286358,stageId=5476,id=931388], com.thoughtworks.go.domain.JobStateTransition@151fd292[currentState=Assigned,stateChangeTime=Thu Oct 01 21:27:08 UTC 2015,jobId=286358,stageId=5476,id=931530], com.thoughtworks.go.domain.JobStateTransition@23192a84[currentState=Preparing,stateChangeTime=Thu Oct 01 21:27:19 UTC 2015,jobId=286358,stageId=5476,id=931563], com.thoughtworks.go.domain.JobStateTransition@445f6dfa[currentState=Building,stateChangeTime=Thu Oct 01 21:27:37 UTC 2015,jobId=286358,stageId=5476,id=931596], com.thoughtworks.go.domain.JobStateTransition@78e70010[currentState=Completing,stateChangeTime=Thu Oct 01 21:33:35 UTC 2015,jobId=286358,stageId=5476,id=931699], com.thoughtworks.go.domain.JobStateTransition@55cff284[currentState=Completed,stateChangeTime=Thu Oct 01 21:33:35 UTC 2015,jobId=286358,stageId=5476,id=931700]], scheduledDate=Thu Oct 01 21:25:40 UTC 2015, timeProvider=com.thoughtworks.go.util.TimeProvider@121a8849, ignored=false, matcher=com.thoughtworks.go.domain.BuildOutputMatcher@be979e8, log=com.thoughtworks.go.domain.NullJobInstanceLog@d427474, identifier=JobIdentifier[web, 654, 654, Tests, 1, Unit-02, 286358], plan=null, runOnAllAgents=false, runMultipleInstance=false}
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to copy full contents from 'data/console/8456fb1d900edb16371794a73b1a4e19.log' to 'artifacts/pipelines/web/654/Tests/1/Unit-02/cruise-output/console.log'
    at com.thoughtworks.go.domain.activity.ConsoleLogArtifactHandler.jobStatusChanged(ConsoleLogArtifactHandler.java:49)
    at com.thoughtworks.go.server.service.JobInstanceService$4.afterCommit(JobInstanceService.java:182)
    at org.springframework.transaction.support.TransactionSynchronizationUtils.invokeAfterCommit(TransactionSynchronizationUtils.java:133)

```

@ketan any thoughts? we are kinda stuck on this.

**Comment by ashwanthkumar** [comment]
@ranjib We once had a very similar issue and in that case we didn't have disk space for the Go server to copy the artifacts. Also a `jstack` report would also be helpful to figure out if something is blocked somewhere.

**Comment by ranjib** [comment]
@ashwanthkumar i have restarted gocd server and updated the github-pr related plugins. i'll get the jstack output next time i hit this. im curious whats the cause for second error. I think its related to projects with lots of PRs.

**Comment by ashwanthkumar** [comment]
You mean the copy error?
```
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to copy full contents from 'data/console/8456fb1d900edb16371794a73b1a4e19.log' to 'artifacts/pipelines/web/654/Tests/1/Unit-02/cruise-output/console.log'
```
I'm not quite sure. I had a similar error last time it was that we were out of disk space. From [this](http://stackoverflow.com/a/15805438), it looks like file length mismatch after moving. Could it be that the file was truncated by an external process, during move? 

Code path on GoCD - https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/ConsoleService.java#L181

**Comment by ketan** [comment]
> We are experiencing an issue, where GoCD server hangs, without any noticeable difference in the UI (i.e. ui works), but pipeline does not get executed upon material updates. Even if we force run (via the ui) the pipelines, nothing happens. The server has ample free memory and CPU (4 gigs out of 15gigs of free memory and 4 cpu). Log shows following, which indicates the material update service is working...

@ranjib - You can checkout the page at `/go/api/support`, when you think the server is "frozen" – it'll print out the stacktraces on all running threads that should shed some light.

You'd probably want to grab 3-4 such snapshots about 30 seconds apart (or more) to be able to see what's happening.

**Comment by zabil** [comment]
>  
```
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Failed to copy full contents from 'data/console/8456fb1d900edb16371794a73b1a4e19.log' to 'artifacts/pipelines/web/654/Tests/1/Unit-02/cruise-output/console.log' 
```

This happens when there's a disk space issue. Since 15.2 console logs are written to a temporary file on the server and then copied to the artifacts directory after job completion.

**Comment by etiennetremel** [comment]
could be related: https://github.com/gocd/gocd/issues/2092

**Comment by arvindsv** [comment]
Closing as stale.
