### ISSUE TITLE
Allow users to have an API key

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1541]
Users are currently allowed to login by passing in a username/password (or a cookie). These work fine from the browser, and even curl. However when building apps that allow users to login via OAuth, there are a couple of options.
- Improve go's OAuth documentation (even update the OAuth implementation, if possible). See related bug #1432, #741 and https://github.com/gocd/gocd/issues/1418#issuecomment-130154159
- Add the ability to allow users to have an API key for custom integrations

**Comment by zabil** [comment]
The second option is a duplicate of #1246

**Comment by GaneshSPatil** [comment]
\cc: @vishaldevgire @bdpiparva 
Related: [Access Token support](https://github.com/gocd/gocd/issues/5354)

**Comment by ketan** [comment]
Closing in favor of #5321
