### ISSUE TITLE
Users API need to send if a user is admin or not

### ISSUE THREAD

**Issue by timoa** [gocd/gocd#1543]
The current response of the "Get one user" doesn't send if the user has the admin rights on not.

If you use the API to do some operations like a backup or any operations that need the admin rights, you need actually to call first the endpoints and get a 401 or 403...

You can't build your UI with the backup button for example because you don't know if the current user can have access to this action or not...

For some endpoints, you can call silently, the endpoints and add or not the button but I can't do that with the backup endpoints :)

**Comment by ketan** [comment]
This is a fairly simple fix to apply, would you like to take this on?

One of us can help you out here :)

**Comment by timoa** [comment]
Hum... I can try but I'm more an iOS & Android / JavaScript (node.js) developer than a Ruby developer...

I will check the source code and the links you gave me on the CI Remote for Go announcement :)

**Comment by kritika-singh3** [comment]
The `admin` flag was introduced in Users API v3 as part of #5628 in GoCD version 19.1.0.
