### ISSUE TITLE
feature: provide instructions on setting up SCM hooks

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#1546]
As a SCM manager (developer), I want easily accessible instructions for how to setup triggering of my pipelines.
In Go.cd, this is done by detecting changes in materials. So just like GitHub, GitLab, Bitbucket and many other services provide instructions on how to clone a repo, or to push content to a newly created clean repo, Go.cd should provide instructions on how to setup hooks that triggers emmediate scanning of said material.

An example of "user friendly instructions":
![image](https://cloud.githubusercontent.com/assets/89504/10304349/db31a414-6c19-11e5-9d49-9e0941575140.png)

The proposed Materials page/view in https://github.com/gocd/gocd/issues/1545, could provide easy copy-and-paste instructions for how to setup up triggering a scan of the repo, so we can use hooks in git, hg, ... instead of this polling. The polling, together with the job polling of agents, as discussed in 

https://github.com/gocd/gocd/issues/1125
https://github.com/gocd/gocd/issues/1290
https://github.com/gocd/gocd/issues/1098

is related. And while we aim to automate and handle infrastructure as code, until Go.cd provides a DSL for expressing pipelines in code, we should provide human-friendly instructions to speed up feedback on the CI/CD jobs.

**Comment by vladistan** [comment]
+1

**Comment by lenucksi** [comment]
:+1:
