### ISSUE TITLE
Stage Type Always

### ISSUE THREAD

**Issue by alexsaare** [gocd/gocd#1548]
Consider the following pipeline

Run BBD Tests
Stage 1 > run tests
State 2 > create docs based on test results e.g. www.picklesdoc.com

I would like the second stage to run ALWAYS even if the first stage fails. 

Is it possible to add a stage type which executes regardless of outcome of the previous stage?

**Comment by arvindsv** [comment]
The mailing list is the right place for questions like this. I believe [this thread](https://groups.google.com/d/topic/go-cd/V6-LfGe1yjM/discussion) is relevant.

**Comment by arvindsv** [comment]
Also, in this case you probably want to model those two as jobs: "Run tests" job and "Create Docs" job. They'll both run always.

**Comment by alexsaare** [comment]
Thanks for taking the time to comment, 

I don't want them as jobs as jobs are run in parallel and "run tests" has to finish before "create docs".  

I also do not want them as tasks as I then lose visibility of which part has failed.  I end up having 1 job called "run" or "execute tests" which sucks as you lose all granularity in the results view.  

The scenario above is simplified to illustrate the problem and the real scenario is much more complex.
