### ISSUE TITLE
APT is not functional, update breaks

### ISSUE THREAD

**Issue by vedarthk** [gocd/gocd#1552]
I am not sure of reporting this issue here, I am not able to find any other relevant space to post this.
Since `apt-get update` is failing with following output:

```
Ign http://download.go.cd  InRelease
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Ign http://download.go.cd  Release.gpg
Ign http://download.go.cd  Release
Ign http://download.go.cd  Packages/DiffIndex
Err http://download.go.cd  Packages

Err http://download.go.cd  Packages

Err http://download.go.cd  Packages

Err http://download.go.cd  Packages

Ign http://download.go.cd  Translation-en_US
Ign http://download.go.cd  Translation-en
Err http://download.go.cd  Packages
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
W: Failed to fetch http://download.go.cd/gocd-deb/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I am using puppet to deploy the agent, it has created `apt` source file (`/etc/apt/sources.list.d/thoughtworks.list`) with following content:

```
deb http://download.go.cd/gocd-deb/ /
```

What is possibly going wrong

**Comment by ketan** [comment]
`http://download.go.cd` is not the right URL.

See [the ubuntu install docs](http://www.go.cd/documentation/user/current/installation/install/agent/linux.html#debian-based-distributions-ie-ubuntu) for correct URL.

I'm marking this issue as closed.
