### ISSUE TITLE
GO_SERVER_PORT being ignored for agent

### ISSUE THREAD

**Issue by CharlieC3** [gocd/gocd#1558]
It appears that the GO_SERVER_PORT variable is being ignored for GoCD agents. It always uses port `8154` despite me setting it some other value, like `8153`. This is preventing our agents from connecting to our server since it is not currently on SSL. I believe this is the offending line of code:

https://github.com/gocd/gocd/blob/f52a72f9b7c23919470dbdbc47139ef1dc95acf8/agent-common/src/com/thoughtworks/go/agent/launcher/ServerBinaryDownloader.java#L65

When the `serverBaseUrl` method is called, it subsequently will always call the `serverSslBaseUrl` method, even if the server is not using SSL.
This error is occurring on both Windows and Linux agents.

**Comment by arvindsv** [comment]
The idea is that the GO_SERVER_PORT is used to tell the agent the HTTP port of the Go Server. The Go Server will respond with its HTTPS port and then communication moves over to that (after setting up some certificates and starting secure communication). There's no way that the server cannot be using SSL. All agent communication will happen over SSL, whether you want it to or not. Go Server will open a second port (8154 by default) for SSL.

So, I'll close this ticket for now. I feel it's working as it should. But, we can open it if I've misunderstood.

**Comment by CharlieC3** [comment]
@arvindsv Thanks for the reply. Based on your response, it sounds like the GoCD server and Agents are supposed to automatically set up SSL certificates if they're not already in place, is that true? Because we do not have certs in place, and they aren't being automatically generated.

If creating/setting up the certs is a manual step, that is fine, I just want to know if the behavior we're seeing it 100% expected, or if it should all "just work" when it's not.

**Comment by arvindsv** [comment]
@CharlieC3: That's right. It should automatically set it up. The Go Server generates a self-signed certificate and uses that for its communication with users (through the browser). But, it also sets up a unique certificate for communication with every agent.

I feel it should all "just work", as long as you have not closed ports 8153 and 8154 (direction: From agent to server).

Here's [a blog post](http://www.go.cd/2014/06/05/using-go-cd-with-custom-certificates.html) about setting up custom certificates. But, that is to replace the certificate that is used by users (browser).

**Comment by lenucksi** [comment]
This might be related to #1114 .
