### ISSUE TITLE
Tests to fix for new machine images

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1565]
- https://build.go.cd/go/tab/build/detail/build-windows/561/build-server-windows/3/server-split-runInstance-13

**Comment by juhijariwala** [comment]
Also, https://build.go.cd/go/tab/build/detail/build-windows/562/build-non-server-windows/2/jasmine_tests fails on windows-agent 106 with `Selenium::WebDriver::Error::NoSuchDriverError`
