### ISSUE TITLE
Integrate periodic garbage collection for config.git 

### ISSUE THREAD

**Issue by lenucksi** [gocd/gocd#1567]
In case of a larger Go server one can incur extreme growth of config.git.
This is due to the fact that all changes lead to commits to config.git which in turn lead lead to loose objects in the git repository that are not compacted or garbage collected automatically.
This leads to high commit or checkout times and also to extreme delay or dysfunction in the "view difference" functionality with the configuration change notices.
More functionality might be impacted, however I cannot provide exact or reproducible data on them.

A shrinkage of two orders of magnitude was observed with a Go server that ran for about two years. 
Here are a few details on the server and its configuration:
* Pipelines: >500
* Lines in config.xml: >80k
* Size of config.xml: >3.5MB
* Size of the config.git **prior to git gc**: 33GB
* Size of the config.git **after git gc**: 336MB
* Time to view a config diff in the web interface **prior to git gc**: Exceeding two minutes, mostly failing with HTTP 50x
* Time to view a config diff in the web interface **prior to git gc**: about 4 seconds.

* git count-objects -v -H **prior to git gc**
 * count: 541298
 * size: 32.44 GiB
 * in-pack: 0
 * packs: 0
 * size-pack: 0 bytes
 * prune-packable: 0
 * garbage: 0
 * size-garbage: 0 bytes

* git count-objects -v -H **after git gc**
 * count: 222
 * size: 11.80 MiB
 * in-pack: 516835
 * packs: 1
 * size-pack: 324.73 MiB
 * prune-packable: 0
 * garbage: 0
 * size-garbage: 0 bytes

Measurements yield that config.git increases by about 52MB loose objects per day. 

I would therefore highly appreciate if Go would gain an automatic garbage collection on the config.git repository.

**Comment by lenucksi** [comment]
The mentioned GC example took about 35 minutes on a 36 core machine with 60GB of RAM.

**Comment by rajiesh** [comment]
verified it on 15.3.0-2724(0deb63cff58810076760a17bba4e6d855b12aa5f) with auto gc on and off and modifying the gc check intervals and thresholds and its working as expected
