### ISSUE TITLE
User experiance

### ISSUE THREAD

**Issue by scrubs767** [gocd/gocd#1569]
We currently have about 25 websites based off the same code, but require a lot of configuration and DB entries that are custom to each client. Each site goes through a staging (dev), review and production phase, each phase/site has its own VM. Our installation process uses the environment to set variables to our installer scripts, such as InstallationType=Staging and Site=staging.foo.com

With that setup we currently have 75 pipelines configured (or will when we get them all into GO from another CI) and it can get messy at times on the pipline page. If we had a way to choose from a set of predefined environment variables when we run a pipline it would greatly clean up the pipelines page.

**Comment by arvindsv** [comment]
Closing as stale. Probably recommended to use pipelines as code in this situation.
