### ISSUE TITLE
Provide plugin project creator with documentation

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#157]
### Description

Use Maven Archetype or some other template to create skeletal structure for plugins which authors could potentially create from commandline or IDE. 

Target users would be first time go plugin authors who might need some sample code to serve as example. Also, advanced users who are creating a new plugin would want to use this.

So, there could be 2 flags/options for creating the skeletal - one which would create the plugin structure with sample plugin in it which first time authors can modify to experiment and second one which would create just the plugin structure only (for advanced users).

**Comment by arvindsv** [comment]
This is happening [slowly](https://github.com/gocd-contrib/?utf8=%E2%9C%93&query=skeleton) and is being documented [here](https://plugin-api.go.cd/current/). Need help to finish the docs, though.
