### ISSUE TITLE
Sorting Pipelines groups

### ISSUE THREAD

**Issue by eleite77** [gocd/gocd#1572]
Hi
I have generated a new config.xml with a good sorting 
but the WEB UI doesn't display the same order we have in this config file

My question is : How can i sort the pipelines groups throught config.xml?
Is there any order parameter so pass?

thanks

**Comment by ketan** [comment]
I'm going to close this issue out. Please ask questions on the forums (https://groups.google.com/forum/#!forum/go-cd).
