### ISSUE TITLE
"The package is of bad quality" message while installing go-agent deb on ubuntu

### ISSUE THREAD

**Issue by redagito** [gocd/gocd#1574]
I tried to install the go-agent package go-agent-15.2.0-2248.deb on Ubuntu 15.04 64bit and got the message
"The package is of bad quality" with description
"non-etc-file-marked-as-conffile var/lib/go-agent/log4j.properties"
I ignored the warning and installed it anyway but this might scare some potential users away.

**Comment by arvindsv** [comment]
Closing in favor of #2585.
