### ISSUE TITLE
Official package fails to install on CentOS

### ISSUE THREAD

**Issue by blast-hardcheese** [gocd/gocd#1579]
So, I've got sort of a workaround, but first, here's the install log:
```
Downloading packages:
go-server-15.2.0-2248.noarch.rpm
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
'Go Server' installation will now use group 'go'
'Go Server' installation will now use user 'go'
  Installing : go-server-15.2.0-2248.noarch
Found Java /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-2.b17.el7_1.x86_64/jre in PATH, using it.
chown: cannot access ‘/var/lib/go-server/**’: No such file or directory
Installation of Go Server completed.
su: warning: cannot change directory to /var/go: No such file or directory
using default settings from /etc/default/go-server
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
Error trying to validate file agent-bootstrapper.jar: java.io.FileNotFoundException: /usr/share/go-server/agent-bootstrapper.jar (Permission denied)
Error trying to validate file agent.jar: java.io.FileNotFoundException: /usr/share/go-server/agent.jar (Permission denied)
Error trying to validate file agent-launcher.jar: java.io.FileNotFoundException: /usr/share/go-server/agent-launcher.jar (Permission denied)
Error trying to validate file cruise.war: java.io.FileNotFoundException: /usr/share/go-server/cruise.war (Permission denied)
Error trying to validate file historical_jars/h2-1.2.127.jar: java.io.FileNotFoundException: /usr/share/go-server/historical_jars/h2-1.2.127.jar (No such file or directory)
/usr/share/go-server/db/h2deltas/30_add_buildcause_message_to_pipeline.sql (No such file or directory)
/usr/share/go-server/db/h2db/cruise.h2.db (No such file or directory)
Error starting Go Server.
warning: %posttrans(go-server-15.2.0-2248.noarch) scriptlet failed, exit status 255
Non-fatal POSTTRANS scriptlet failure in rpm package go-server-15.2.0-2248.noarch
  Verifying  : go-server-15.2.0-2248.noarch

Installed:
  go-server.noarch 0:15.2.0-2248

Complete!
```

So, the workaround is to create the go user and group, create `/var/go` (and chown it to `go:go`), and create and chown `/usr/share/go-server`, _then_ install the package. It'll pick up on the user and use the directories. Furthermore, yum ends up hanging forever when trying to actually install the package, as it ends up actually starting the server without forking, which is generally unhelpful.

**Comment by ketan** [comment]
Dup of #1467 - do you have SELinux running?

**Comment by blast-hardcheese** [comment]
@ketan Good call! I do have SELinux running! The most recent installation attempt didn't end up cleaning up the go user or group, so when I tried to install again, it succeeded. Attempting to restart the service also no longer hangs, so that's nice as well. What's a good solution to this problem? Thanks for your speedy response as well!

**Comment by blast-hardcheese** [comment]
Entirely possible that we've got different levels of permission, but is #1527 really a dup of #1467? The installer actually created `go:go` for me, and even left them around after I `yum erase go-server`'d

**Comment by ketan** [comment]
@blast-hardcheese - It *may* have been because SELinux was preventing creation of the said files and/or dirs.

As regards the uninstallation leaving behind users, it is a standard practice to do so.
