### ISSUE TITLE
go cd website uses a GitHub certificate for HTTPS

### ISSUE THREAD

**Issue by darrenhaken** [gocd/gocd#1582]
Go CD should supply its own SSL cert or disable HTTPS traffic for now.

**Comment by matt-richardson** [comment]
Because?

**Comment by darrenhaken** [comment]
This means that when I tried to access the site via HTTPS my browser gives me a security warning telling me that the website should not be trusted.

Do you want to communicate this message to people?

**Comment by zabil** [comment]
@darrenhaken thanks for pointing this out. 
It's caused by the github logo that's being fetched from github via the github oauth plugin. It won't happen on a stock installation.

A long term solution, if feasible, is to figure out how the plugins can bundle certs.

**Comment by darrenhaken** [comment]
Thanks @zabil . Yep this is talking about go.cd

**Comment by arvindsv** [comment]
This is done. Closing this.
