### ISSUE TITLE
can't see who introduced config change

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#1588]
It's nice to see what changed between two runs of a stage, but we're lacking the ability to see who introduced the change. Could you use the Author section of the git commits to the config, in order to identify (and display) the logged in user that authored the change in configuration?

The screen here doesn't say who made the change (so I don't know how to talk to if this change needs to be discussed): 
![image](https://cloud.githubusercontent.com/assets/89504/10866696/a1977c42-803c-11e5-8fde-28c82663a802.png)

**Comment by aj-jaswanth** [comment]
I am working on it.
