### ISSUE TITLE
Maven clean up

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#159]
### Description

1) All jar dependancies which are not available in maven repo are checked in into  local-maven-repo folder under source code.  Move local-maven-repo to http based repo something like - http://google-caja.googlecode.com/svn/maven
2) MANIFEST.MF  is hardcoded for some module, need to find a way to generate MANIFEST.MF (ex agent-launcher & tfs-impl)
3) move version of all go modules from 1.0 -> current release (say 14.1.0) for consistency

**Comment by arvindsv** [comment]
Moving to gradle: #2010.
