### ISSUE TITLE
How to get current job status in task (plugin development)

### ISSUE THREAD

**Issue by paraplexed** [gocd/gocd#1590]
I am having some difficulty finding the current job status in a task. I want to make some changes to the hipchat plugin (the maintainers have switched to slack so I may pick it up if I can figure the API out). One of the changes I was looking at implementing was having default AND custom notification messages based on whether the previous task passed/failed. I don't want to have to create 2 separate tasks for the notifications. Having the option of just one that the plugin will check whether or not the job is failing/passing and behave appropriately based on that.

I found the com.thoughtworks.go.plugin.api.hook.joblifecycle package, but it seems the JobContext is never instantiated previously, so I only ever get 'Unknown' when I do a getJobStatus. I was hoping someone could tell me how this package is supposed to be used, or atleast point me in the right direction.

Also if there is a better place to post this message please let me know.

**Comment by arvindsv** [comment]
Hello @paraplexed: I'd say the best place to post is the [go-cd-dev mailing list](https://groups.google.com/forum/#!forum/go-cd-dev), for these kind of questions - the ones related to development of plugins and the codebase itself.

I'll close this, and post a message on the mailing list.

**Comment by paraplexed** [comment]
Thanks!

**Comment by arvindsv** [comment]
Since you saw this, can you post a message yourself? I'll reply later today.

**Comment by paraplexed** [comment]
Yep, will do. Thanks again!
