### ISSUE TITLE
Update the Git post-commit implementation to handle webhooks

### ISSUE THREAD

**Issue by rsouthgate** [gocd/gocd#1591]
The current GitPostCommitHookImplementer uses repository_url to resolve the material that has been updated. As far as I can tell this only works with the Github contributed Go service. But reading here: https://developer.github.com/webhooks/#payloads it seems the github services have been deprecated in favour of webhooks. The webhook seems to return a repository entity instead of the repository_url field. 

My particular interest is bitbucket and their webhook seems to return a repository entity too. It feels like part of the system that should be handles by plugins rather than the core code but perhaps the webhook response payload has been standardised so that multiple service handlers is unnecessary?

**Comment by FredrikWendt** [comment]
Please take a look at #217 and see if there's an overlap.

**Comment by ketan** [comment]
@rsouthgate every github like service renders the repo entity in a different manner, as things stand, it'll be difficult for go to play catch-up with those that are around.

The current implementation is meant to be platform agnostic and even works well for self hosted repos.

Would you like to contribute a patch or some research on various webhooks in the wild so that someone else may implement this?

**Comment by FredrikWendt** [comment]
GitLab docs: http://doc.gitlab.com/ce/web_hooks/web_hooks.html
```
{
  "object_kind": "push",
  "before": "95790bf891e76fee5e1747ab589903a6a1f80f22",
  "after": "da1560886d4f094c3e6c9ef40349f7d38b5d27d7",
  "ref": "refs/heads/master",
  "user_id": 4,
  "user_name": "John Smith",
  "user_email": "john@example.com",
  "project_id": 15,
  "repository": {
    "name": "Diaspora",
    "url": "git@example.com:mike/diasporadiaspora.git",
    "description": "",
    "homepage": "http://example.com/mike/diaspora",
    "git_http_url":"http://example.com/mike/diaspora.git",
    "git_ssh_url":"git@example.com:mike/diaspora.git",
    "visibility_level":0
  },
  "commits": [
    {
      "id": "b6568db1bc1dcd7f8b4d5a946b0b91f9dacd7327",
      "message": "Update Catalan translation to e38cb41.",
      "timestamp": "2011-12-12T14:27:31+02:00",
      "url": "http://example.com/mike/diaspora/commit/b6568db1bc1dcd7f8b4d5a946b0b91f9dacd7327",
      "author": {
        "name": "Jordi Mallach",
        "email": "jordi@softcatala.org"
      }
    },
    {
      "id": "da1560886d4f094c3e6c9ef40349f7d38b5d27d7",
      "message": "fixed readme",
      "timestamp": "2012-01-03T23:36:29+02:00",
      "url": "http://example.com/mike/diaspora/commit/da1560886d4f094c3e6c9ef40349f7d38b5d27d7",
      "author": {
        "name": "GitLab dev user",
        "email": "gitlabdev@dv6700.(none)"
      }
    }
  ],
  "total_commits_count": 4,
  "added": ["CHANGELOG"],
  "modified": ["app/controller/application.rb"],
  "removed": []
}
```

**Comment by arvindsv** [comment]
I believe this is done now, for Bitbucket, Gitlab and GitHub.
