### ISSUE TITLE
Pipeline history page needs a rewrite

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#1598]
- It's in Velocity macro with some more old JS templating in it, inside a textarea.
- It uses pipelineHistory.json, which escapes the JSON wrong (single quotes become backslash-single-quote, which is wrong.
- It doesn't use /go/api/pipelines/pipeline_name/history (which in itself needs to follow the newer API recommendations) and still gets the JSON escaping wrong.

[Here is](https://github.com/gocd/gocd/files/1626333/Currentfunctionalityofpipelinehistorypage.docx) all the (current) functionality of that page that will need to be replicated. This will take time and effort. I'm going to fix the JSON as a first step, and make it be valid for now.

The page needs to be moved over to Rails and should use some of the newer APIs.

**Comment by arvindsv** [comment]
Related to #1472 in a way (similar JSON issue).

**Comment by arvindsv** [comment]
Note: Consider #2784 as well, when doing this.

**Comment by adityasood** [comment]
Done via https://github.com/gocd/gocd/pull/7321
