### ISSUE TITLE
Can't consume JSON API from other domain

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#1602]
When serving this HTML:

```
<!DOCTYPE html>
<html lang="en">
    <body>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>
        $(document).ready(function (){
            $.ajax({
                url: 'https://view:password@build.go.cd/go/api/pipelines/build-linux/history',
                beforeSend: function(xhr) {
                    xhr.setRequestHeader("Authorization", "Basic " + btoa("view:password"));
                },
                type: "GET",
                success: function (data) {
                    console.log(JSON.stringify(data));
                },
                error: function(data){
                    console.log(JSON.stringify(data));
                }
            });
        });
        </script>
    </body>
</html>
```

In chromium, you'll get this error message:

> XMLHttpRequest cannot load https://build.go.cd/go/api/pipelines/build-linux/history. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://gotburh05p:8033' is therefore not allowed access. The response had HTTP status code 401.

(Console log gets this: `{"readyState":0,"responseText":"","status":0,"statusText":"error"}`.)

It would be very convenient to have a flag where you could set the `Acces-Control-Allow-Origin` header, and have gocd serve that for API endpoints. This would greatly simplify integration "in" the browser.

https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by pedrocarrico** [comment]
I would love to have this feature too but for artifacts.
A use case that I have is that at the end of a pipeline export a swagger template as an artifact and then we can easily import the URL in http://editor.swagger.io or other consumers.

**Comment by arvindsv** [comment]
@jsgar No. There hasn't been any change to this. No one has worked on it.
