### ISSUE TITLE
Feature Request: Email system administrators if errors occur longer than specified time

### ISSUE THREAD

**Issue by cholmes1111** [gocd/gocd#1606]
Currently, when system administrators perform a backup of the GO database, an email is sent indicating that the backup completed.

It would be very helpful if there was a configurable setting that emailed the system administrators if an error has persisted from more than the specified time. For example, I set the timer to 30 minutes, if the error lasts 31 minutes, I get an email.

Would be nice to have a separate setting for warnings lasting longer than specified as well.

This would need be tracked somehow (maybe database?) to prevent "spam-like" messages from being received. If it send an email at 31 minutes, I don't need another email at 32 minutes, then 33 minutes and so on. 1 email per incident.

**Comment by arvindsv** [comment]
@cholmes1111: When you say an "error has persisted", do you mean the "Errors and Warnings" box at the bottom right corner?

This has nothing to do with backup, right? I thought you were talking about an error during backup, but it looks like this is a feature request around email notifications for errors and warnings. Did I understand that right?

**Comment by cholmes1111** [comment]
Correct. The "Errors and Warnings" box in the bottom right corner. This has nothing to do with the backup, other than to point out that some functionality exists
 to email the system administrators now (when backups complete)

**Comment by arvindsv** [comment]
Great! Thanks. That makes sense. I've classified it as "notifications" (label in GitHub) and I think Go can provide much more in way of notifications than it does. The actual mechanism of sending an email or doing something else can be decided by a plugin. But, the ability to be notified itself, means a change in the notification endpoint.

**Comment by bmess** [comment]
As a regular user I think this change is warranted.  Email shouldn't be an alert mechanism, let alone alerting that a backup has been performed. It's a positive that's quickly lost in a stream of email. 
Does the current plugin system allow you to override this @arvindsv or would we need to have a new backup plugin?
