### ISSUE TITLE
MaterialUpdateService does not time out long-running plugin material modification checks 

### ISSUE THREAD

**Issue by pshelton-skype** [gocd/gocd#1607]
The go-server.log for our server indicates that very long-running material modification requests are never timed out and block other material update checks:

> 2015-11-09 23:09:55,448  WARN [materialUpdateThread] MaterialUpdateService:146 - [Material Update] Skipping update of material 'PackageMaterial{Repository: [qb_url=https://<REDACTED>] - Package: [qb_configuration_id=267080, version_format=\d{1}.\d{1}.\d+]}' which has been in-progress since Sat Nov 07 11:59:55 CET 2015

Our plugin code appears to have a bug where we may hang when reading from a SocketInputStream representing the response from an external [QuickBuild](http://www.pmease.com/features/) server if the server is unavailable: 

> 100, 100@MessageListener for MaterialUpdateListener, RUNNABLE
> Locked Monitors:
> java.lang.Object\@672a8798 at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)sun.security.ssl.AppInputStream@77ccec72 at sun.security.ssl.AppInputStream.read(Unknown Source)java.io.BufferedInputStream@7a6c4f95 at java.io.BufferedInputStream.read(Unknown Source)sun.net.www.http.ChunkedInputStream@3eb3e891 at sun.net.www.http.ChunkedInputStream.read(Unknown Source)java.io.InputStreamReader@d16ae98 at sun.nio.cs.StreamDecoder.read(Unknown Source)java.lang.String@1d297c34 at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:107)Locked Synchronizers:
> Stacktrace:
>   java.net.SocketInputStream.socketRead0(Native Method)
>   java.net.SocketInputStream.socketRead(Unknown Source)
>   ...
>   sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
>   sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
>   ...
>   java.util.Scanner.next(Unknown Source)
>   com.tw.go.plugin.material.artifactrepository.qbmonitor.NetUtils.convertStreamToString(NetUtils.java:46)
>   com.tw.go.plugin.material.artifactrepository.qbmonitor.QbApiConnector.getLatestGreenBuild(QbApiConnector.java:69)  com.tw.go.plugin.material.artifactrepository.qbmonitor.QbmonitorPackageMaterialPoller.getLatestRevision(QbmonitorPackageMaterialPoller.java:32)  com.tw.go.plugin.material.artifactrepository.qbmonitor.QbmonitorPackageMaterialPoller.latestModificationSince(QbmonitorPackageMaterialPoller.java:100)  com.thoughtworks.go.plugin.access.packagematerial.ApiBasedPackageRepositoryExtension$6.execute(ApiBasedPackageRepositoryExtension.java:91)  com.thoughtworks.go.plugin.access.packagematerial.ApiBasedPackageRepositoryExtension$6.execute(ApiBasedPackageRepositoryExtension.java:88)
>   com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:315)
>   com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:245)
>   com.thoughtworks.go.plugin.infra.DefaultPluginManager.doOn(DefaultPluginManager.java:114)  com.thoughtworks.go.plugin.access.packagematerial.ApiBasedPackageRepositoryExtension.latestModificationSince(ApiBasedPackageRepositoryExtension.java:95)  com.thoughtworks.go.plugin.access.packagematerial.PackageAsRepositoryExtension.latestModificationSince(PackageAsRepositoryExtension.java:68)
>   com.thoughtworks.go.server.service.materials.PackageMaterialPoller.modificationsSince(PackageMaterialPoller.java:63)
>   com.thoughtworks.go.server.service.materials.PackageMaterialPoller.modificationsSince(PackageMaterialPoller.java:41)
>   com.thoughtworks.go.server.service.MaterialService.modificationsSince(MaterialService.java:110)
>   com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:52)
>   com.thoughtworks.go.server.materials.PackageMaterialUpdater.insertLatestOrNewModifications(PackageMaterialUpdater.java:61)

This caused all pipelines using this material plugin to never get triggered without a reboot of the service.

The MaterialUpdateService should be robust against poorly-implemented material plugins and timeout long-running material modification checks instead of allowing the possibility of permanently blocking future material modification checks. This could be accomplished either with a time-based mechanism or a count-based mechanism based on the number of times the material modification check has been skipped due to another in-progress check.

**Comment by arvindsv** [comment]
Yes, agree. The material subsystem needs more visibility and control.

**Comment by arvindsv** [comment]
Oh, but, killing the plugin thread ... sounds dangerous and it can leave the material in an inconsistent state.

**Comment by lruslan** [comment]
Hi, we also experience similar issue with "Material - Git"

In a process list I see : 
ELAPSED COMMAND          COMMAND
52:55        ssh                       /usr/bin/ssh git@bitbucket.org git-upload-pack 'xivart/blahblah.git'

And GoCD log reports:

2018-04-10 07:28:42,165 WARN  [materialUpdateThread] MaterialUpdateService:181 - [Material Update] Skipping update of material GitMaterial{url=git@bitbucket.org:xivart/rwd_cheaptickets_nl.git, branch='master', submoduleFolder='null', shallowClone=true} which has been in-progress since Tue Apr 10 06:57:10 GMT 2018

Only solution is to "kill -TERM"

It looks like git-upload-pack has "timeout" which should interrupt transfer: https://git-scm.com/docs/git-upload-pack#git-upload-pack---timeoutltngt:
--timeout=<n>
Interrupt transfer after <n> seconds of inactivity.

Maybe you can enable timeout for git material ?

**Comment by MPV** [comment]
We've also experienced this issue today. 
https://github.com/gocd/gocd/issues/2827 seems related / the same issue?
