### ISSUE TITLE
Fetch latest release details from client(browser)

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1614]
As part of #1308 the server at a given cadence checks if there is a new version of GO available. There might be instances where the server would not be able to make calls to fetch the latest release details from go.cd as it might be behind a firewall. This leaves with the client(browser) making a call to go.cd to fetch the latest release and update the server.

Acceptance Criteria
  1. The latest release details should be fetched with a cadence of 1 day.
  2. Clients(Browser) should be used to fetch the latest release if not updated by server.
  3. Since browser would be used as a proxy, ensure only one request is made to fetch the latest release.
  4. This feature should be turned off on development Server and non production distributions(Developer boxes)
  5. Users should have an option to disable this feature.
  6. There should be visual cue on webpages to highlight a new GO version.
  7. Verify messages from the update server are not tampered.
  8. On failure of update, retry every half an hour.

**Comment by arvindsv** [comment]
Related PR is: #1651

**Comment by rajiesh** [comment]
verified it on 15.3.0-2757 (9a2bdcf7063d685239ccf7f9eeb63850bd007658) and update check and update notification works as expected
