### ISSUE TITLE
Feature Request: Schedule automatic backups from web interface

### ISSUE THREAD

**Issue by cholmes1111** [gocd/gocd#1618]
It would be nice for System Administrators to have the ability to schedule automatic backups from the web interface.

**Comment by arvindsv** [comment]
Yes, would be useful (along with the ability to ship the backup away to some other machine). There's no plan currently to enhance this, but I'm going to try and put together ideas like this into one place, that someone can pick up - with some details so that new contributors can also pick it up.

**Comment by marbis** [comment]
+1

**Comment by grahamc** [comment]
Note that without the part about shipping to another server, this isn't a particularly useful feature. I understand it is considered undesirable to have an agent running on the Go server, but if you do, you can have a scheduled pipeline backup and upload the backup somewhere.

**Comment by vivuu1989** [comment]
Can you please explain the steps to create a pipeline to backup GOCD

**Comment by cholmes1111** [comment]
I can tell you what we did to address this shortcoming. We created a powershell script that invokes the API (/go/api/backups) endpoint to create a backup. We then copy the backup file to a separate location. We currently just have it as a scheduled task on our Windows server.

**Comment by arvindsv** [comment]
This has been possible for a while: https://docs.gocd.org/19.11.0/advanced_usage/cron_backup.html
