### ISSUE TITLE
How to send packages to agent？ 

### ISSUE THREAD

**Issue by Aaron1989** [gocd/gocd#1620]
hey,guys,I meet some problems when I learn GO. I still don not know how to send packages to agent.And I didnot find any packages neither in my GO server,nor in my agent.There will be some pictures shown below about GO configuration,can u help me,I just want to know How GO works,how to selecte a package and let agent deploy it ,thank u very much！
![materials](https://cloud.githubusercontent.com/assets/7899710/11231474/cd520c6c-8de3-11e5-9f2b-4721e2b02e81.png)
![testhob-tasks](https://cloud.githubusercontent.com/assets/7899710/11231497/fd94b0f0-8de3-11e5-8e88-467fb581d777.png)
![pipeline dependencies](https://cloud.githubusercontent.com/assets/7899710/11231509/233d05d2-8de4-11e5-85e6-bbcc7e8c3bd3.png)
![artifaces](https://cloud.githubusercontent.com/assets/7899710/11231531/6f357ffa-8de4-11e5-8e60-caf1fb3824a0.png)

**Comment by zabil** [comment]
Hi Aaron,
 As mentioned here
<http://www.go.cd/documentation/user/current/extension_points/package_repository_extension.html#downloading-the-package>

 You've set up a custom command task in your job to download the package.
The "curl" downloads the package, however you've not used the right
 environment variable (GO_PACKAGE_REPONAME_PACKAGE_LOCATION) it should've
been whatever you've set your spring package repository as

 e.g. assuming your spring package repository is named "spring" and the
package to poll is "springcloud" the environment variable to be used  is
 "GO_REPO_SPRING_SPRINGCLOUD_LOCATION"
 It will be downloaded to the agent and available in it's working
directory. Note that it will *not* be visible on the artifacts tab unless
you publish
<http://www.go.cd/documentation/user/current/configuration/managing_artifacts_and_reports.html#publishing-artifacts>
it.

.

**Comment by zabil** [comment]
Closing this as its not an issue. Recommend using the gocd mailing list for these questions.
