### ISSUE TITLE
Go 15.2.0 now available banner broken on Safari

### ISSUE THREAD

**Issue by twchad** [gocd/gocd#1625]
The "Go 15.2.0 now available!" banner is broken on Safari...
<img width="1196" alt="brokenbanner" src="https://cloud.githubusercontent.com/assets/3914252/11273348/f68af928-8eb9-11e5-8c5c-e7775aded004.png">

**Comment by jyotisingh** [comment]
Fixed by https://github.com/gocd/gocd.github.io/pull/228
