### ISSUE TITLE
Issues Observed in Pipeline config API 

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#1630]
Tested pipeline config API on 15.3.0-2663 and below issues are observed,

~~Issue 1:~~
~~environment variables: Not validates for unique values, does not validate for special chars.if '#' char is present then it checks and throws error but other chars are not checked

eg:
```
"environment_variables": [
    {
      "secure": false,
      "name": "java%",
      "value": "java21"
    },
    {
      "secure": false,
      "name": "java",
      "value": "java2"
    }
  ]
```

```
"environment_variables": [
    {
      "secure": false,
      "name": "java",
      "value": "java21"
    },
    {
      "secure": false,
      "name": "java",
      "value": "java2"
    }
  ]
```

~~Issue 2~~:

working directory validation do not look for special chars: Below value is accepted
>"working_directory": "some../..rm” 

**Issue 3**:
* Create a pipeline with template(vis UI, config API still do not support create templates)
* Perform a GET on the config API
Json contains below stage value which needs to be removed in case of pipelines using template

> "stage" : null

* Similarly when pipeline is defined by stages, the template property should not be returned by the config API. Currently the response for GET API has

> "template": null

~~Issue 4:~~
* Add github-pr-poller plugin to the go server
* create a pipeline with GitHub material and no path blacklisted
* perform a GET on config API for this pipeline
* In the Json response Material contains the SCM ref and also "filter". Filter value is set to null
* Now make modifications to the pipeline and perform PUT 
* Response received is "500 Server Error" - since the filter value was null and API does not accpet null value for SCM filter
* 'null' value should be accepted for SCM filter ~~

Additional issues identified:

**Issue 5**:

GET Pipeline Config API do not have scm material destination.
* Create a pipeline with 2 materials - github material(precondition: add github.pr plugin to server) and another one
* Specify a destination folder for scm material
* Perform a GET pipeline config request
* response json do not contain the destination folder. here is the snippet of the response,

> {
      "type": "plugin",
      "attributes": {
        "ref": "b337590b-919f-41f7-91de-55aa5d805147",
        "filter": null
      }
    }

* Take this response json and do a PUT on pipeline config API -  Response is 422(Unprocessible entity) but the response body do not have any details of what is the failure
* Actually the failure is that since there are 2 materials and the scm material do not have destination set the request is not processed

**Issue 6**:

GET Pipeline config API returns 500 Server error if the pipeline has an On Cancel Task added for any task. Below exception observed in the logs,

> 2015-11-27 14:18:04,831 FATAL [qtp1963576789-24] Rails:? -
NameError (uninitialized constant ApiV1::Config::Tasks::OnCancelRepresenter::UrlBuilder):
  app/presenters/api_v1/config/tasks/on_cancel_representer.rb:30:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/controllers/api_v1/admin/pipelines_controller.rb:26:in `show'
  lib/jetty_weak_etag_middleware.rb:13:in `call'
  lib/catch_json_parse_errors.rb:8:in `call’

**Issue 7**:

Pipeline Config API allows pipeline to be created/updated with template AND stage defined. 

* Create a template via UI
* Create a pipeline with "template" property value set to the template created.
* Also define the stage object with proper stage items
* A POST or a PUT request for this request json will be successful
* The UI will show 2 stages on the pipeline dashboard page
* However the pipeline config page stage tab will show only the template

**Comment by ketan** [comment]
> environment variables: Not validates for unique values, does not validate for special chars.if '#' char is present then it checks and throws error but other chars are not checked

@rajiesh a `#` is treated as special **by go** (aka, not shell) for param expansion. Shell variables on windows and linux do not have any restrictions on what they can be named. If you want to use a literal `#` in go, I **think** it needs to be escaped as `##`.

**Comment by rajiesh** [comment]
Additional issues identified:

**Issue 5**:

GET Pipeline Config API do not have scm material destination.
* Create a pipeline with 2 materials - github material(precondition: add github.pr plugin to server) and another one
* Specify a destination folder
* Perform a GET pipeline config request
* response json do not contain the destination folder. here is the snippet of the response,

> {
      "type": "plugin",
      "attributes": {
        "ref": "b337590b-919f-41f7-91de-55aa5d805147",
        "filter": null
      }
    }

* Take this response json and do a PUT on pipeline config API -  Response is 422(Unprocessible entity) but the response body do not have any details of what is the failure
* Actually the failure is that since there are 2 materials and the scm material do not have destination set the request is not processed

**Issue 6**:

GET Pipeline config API returns 500 Server error if the pipeline has an On Cancel Task added for any task. Below exception observed in the logs,

> 2015-11-27 14:18:04,831 FATAL [qtp1963576789-24] Rails:? -
NameError (uninitialized constant ApiV1::Config::Tasks::OnCancelRepresenter::UrlBuilder):
  app/presenters/api_v1/config/tasks/on_cancel_representer.rb:30:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/presenters/api_v1/base_representer.rb:74:in `to_hash'
  app/controllers/api_v1/admin/pipelines_controller.rb:26:in `show'
  lib/jetty_weak_etag_middleware.rb:13:in `call'
  lib/catch_json_parse_errors.rb:8:in `call’

**Comment by juhijariwala** [comment]
**Issue 8:**
PUT/ POST Pipeline Config API does not give an error message if referred scmId or packageId is not found in the cruise config for PluggableSCM and PackageMaterial. 

```json
    {
      "type": "package",
      "attributes": {
        "ref": "invalid_package_id"
      }
    },
    {
      "type": "plugin",
      "attributes": {
        "ref": "invalid_scm_id",
        "filter": null,
        "destination": "destination1"
      }
    }
```


**Issue 9:**
PUT/ POST Pipeline Config API does not give an error message if the plugin is missing for PluggableTask, PluggableSCM and PackageMaterial. 


**Issue 10:**
PUT/ POST Pipeline Config API:  After successful update/create of pluggableSCM via API Go throws Null pointer exception and not able to load any page from UI.

```
Java::JavaLang::NullPointerException ():
  com.thoughtworks.go.config.materials.PluggableSCMMaterialConfig.isAutoUpdate(com/thoughtworks/go/config/materials/PluggableSCMMaterialConfig.java:164)
  com.thoughtworks.go.config.BasicCruiseConfig.getUniqueMaterials(com/thoughtworks/go/config/BasicCruiseConfig.java:991)
  com.thoughtworks.go.config.BasicCruiseConfig.getAllUniqueMaterials(com/thoughtworks/go/config/BasicCruiseConfig.java:982)
  com.thoughtworks.go.serverhealth.HealthStateScope$ScopeType$2.isRemovedFromConfig(com/thoughtworks/go/serverhealth/HealthStateScope.java:161)
  com.thoughtworks.go.serverhealth.HealthStateScope.isRemovedFromConfig(com/thoughtworks/go/serverhealth/HealthStateScope.java:122)
  com.thoughtworks.go.serverhealth.HealthStateType.isRemovedFromConfig(com/thoughtworks/go/serverhealth/HealthStateType.java:132)
  com.thoughtworks.go.serverhealth.ServerHealthService.removeMessagesForElementsNoLongerInConfig(com/thoughtworks/go/serverhealth/ServerHealthService.java:92)
  com.thoughtworks.go.serverhealth.ServerHealthService.getAllValidLogs(com/thoughtworks/go/serverhealth/ServerHealthService.java:76)
```

**Comment by ketan** [comment]
**Issue 10:**

Posting an ambiguous environment variable should fail with an error message —

```json
{
  "secure": true,
  "name": "PASSWORD",
  "value": "clearText"
  "encrypted_value", "c!ph3rt3xt"
}
```

In such a case, it's not entirely clear if the value of the "value" attribute should be encrypted, or the value of the `encrypted_value` attribute should be used as is.
