### ISSUE TITLE
[API] Dashboard: Error 404 if no "Accept: application/vnd.go.cd.v1+json" HTTP header

### ISSUE THREAD

**Issue by timoa** [gocd/gocd#1632]
Hi All,

I tried the new Dashboard API of the 15.3 but I get an error 404 only on this endpoint because it need the "Accept: application/vnd.go.cd.v1+json" HTTP header.

All the other endpoints works without it and you get a code 200.

It is a normal behaviour of the Dashboard endpoint?

Thank you!

**Comment by zabil** [comment]
Yes, this is the expected behavior. 
API's added from 15.2+ are versioned using this scheme.
Another end point that uses this scheme is http://api.go.cd/current/#get-all-agents

**Comment by timoa** [comment]
Ok. Thanks Zabil!
