### ISSUE TITLE
.sh files seem to lose the correct line endings when passed as artifact from one pipeline to another

### ISSUE THREAD

**Issue by rtaborda** [gocd/gocd#1642]
I was trying to only get the code from the Git repository in the first pipeline and then create an artifact and keep passing it from pipeline to pipeline, but for some reason the .sh files seem to be corrupted. At first I thought it was just because of Visual Studio putting some Windows line endings so I tried to convert them back to UNIX using notepad++ but the problem persisted.

After losing some time and trying different things to convert the file to unix, I decided to install a tool I found called dos2unix and when I used it directly in the folder in the server and then executed the script from the terminal everything worked, so it seems that somewhere along the process Go was corrupting the file.
I read somewhere online that when these files are copied they need to be copied as binary otherwise they lose the proper line endings.

So in the end what solved it was setting Git as a material for these pipelines instead of passing the artifact around, so it really seems that when Go copies the artifact from pipeline to pipeline it somehow corrupts these .sh files. But the also interesting part is that this doesn't seem to happen if the artifact is passed from stage to stage in the same pipeline.

Is this because of the way the artifacts are passed from pipeline to pipeline? I read in a different issue that it causes some problems with the file permissions, can it also be causing this?

**Comment by ketan** [comment]
This does not appear to be a go issue. Go merely executes git to perform clones, if your agent's pipeline directory contains the specific `.sh` files with a windows file ending, it is likely that checks out files with a windows line-ending.

See [this](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace) to change the behaviour.

**Comment by ketan** [comment]
[gitattributes](http://git-scm.com/docs/gitattributes) man page as an excellent article about the right way to setup `core.autocrlf`.

I'm marking this issue as closed, but please leave a comment if you think that is not the case.

**Comment by rtaborda** [comment]
I see what you mean, but then how does it work well in pipeline A, and then when it's passed as an artifact to pipeline B it becomes corrupt? The copy from pipeline A to pipeline B happens in the same Linux machine.
But you can keep it closed and will have a look at the links you provided and do some more tests.

Thank you for your time.

**Comment by ketan** [comment]
Is both your server AND agent running on linux?

Here's what I suggest —

When `pipelineA` executes on an agent, see the filesystem `AGENT_WORK_DIR/pipelines/pipelineA` and check what the line ending is.

When the artifact is uploaded on the go server, download it again, and check what the line ending is.

Rinse and repeat with `pipelineB`.
