### ISSUE TITLE
The Agents view should also show current running job

### ISSUE THREAD

**Issue by vraravam** [gocd/gocd#1653]
In the agents view/page, especially when the agent shows either a "building" or "building(cancelled)" status, it would be really helpful to provide a link to which job this status refers to. In most other states, this info is useless.

**Comment by GaneshSPatil** [comment]
The new agent's page shows the information about the building/building(canceled) job.
Attaching a screenshot for the reference:
![screen shot 2018-07-10 at 1 15 40 pm](https://user-images.githubusercontent.com/15275847/42496419-9845acaa-8443-11e8-9ed6-a340c799d7c5.png)

**Comment by GaneshSPatil** [comment]
This issue has been fixed via new agents page which was introduced as part GoCD version `v16.12.0`
