### ISSUE TITLE
Invalid URL in TFS connection returns wrong error message on check connection

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#1654]
Testing on build 15.3.0-2686(6922654e1949e3e19d0ac9b8426c418ba495c001)
- Create a pipeline
- Add a TFS material
- In the TFS material popup specify a invalid URL and click check connection. below error throws up

<img width="758" alt="screen shot 2015-11-27 at 4 49 59 pm" src="https://cloud.githubusercontent.com/assets/6533924/11440245/f140c510-9526-11e5-902c-453c13d4fcae.png">

Issue seen from regression-postgresql pipeline failure on go05 - https://go05.thoughtworks.com/go/tab/build/detail/regression-postgresql/150/twist/2/firefox-split-runInstance-10

**Comment by ketan** [comment]
Do you have a log from the server that'll help pinpoint the problem?

**Comment by ketan** [comment]
This **may** be related to #1635. Can you check if you can reproduce this issue pre and post #1635?

**Comment by rajiesh** [comment]
@ketan pls check the exception from go-server log file for this error https://gist.github.com/rajiesh/330fa60b616f598c9e6b

**Comment by rajiesh** [comment]
@ketan Yes it started from the PR #1635 is merged

**Comment by rajiesh** [comment]
@ketan identified another issue related to this bug -  When we create a new pipeline from 'Admin -> Pipeline -> Create new pipeline within Group' page and specify material details and perform "Check Connection" throws up error as below,

![image](https://cloud.githubusercontent.com/assets/6533924/11526441/87288162-9900-11e5-97a4-b232fe137d00.png)

**Comment by rajiesh** [comment]
As for the issue mentioned first regarding the TFS material the URL provided was junk - the value which twist test provides is "Invalid_URL", please check this test https://go05.thoughtworks.com/go/tab/build/detail/regression-postgresql/150/twist/2/firefox-split-runInstance-10

**Comment by rajiesh** [comment]
This issue occurs even when we specify valid format for the material URL. Tried with TFS url like 'http:// ServerName:8080/tfs/" this also returned error as "(NoMethodError) undefined method `getProcessNamespace' for #<Class:0x74f60fa4>"

**Comment by arvindsv** [comment]
Was this happening on 15.2 too?

**Comment by rajiesh** [comment]
this started occurring after PR #1635 is merged
