### ISSUE TITLE
Agent 'enable, disable' buttons are blocked by Ad Block chrome extension

### ISSUE THREAD

**Issue by aj-jaswanth** [gocd/gocd#1656]
In the agents page,

Without AdBlock,
![without adblock](https://cloud.githubusercontent.com/assets/7703387/11474071/c489833c-979b-11e5-9a46-d20216c90956.png)

With AdBlock,
![with adblock](https://cloud.githubusercontent.com/assets/7703387/11474061/bb653f44-979b-11e5-823c-44471379aae3.png)

We are using, Go Version: 14.1.0(18882-d0272e1d227b5e)

**Comment by ketan** [comment]
I'm able to see this just fine with 15.2 running when running adblock. Would you like to try reproducing this with a newer version, 14.1.0 is a very old version and you should upgrade to get a lot of [nice things](http://www.go.cd/releases/#15.2) :)

**Comment by aj-jaswanth** [comment]
Do you see any minor issues, that I must be aware of upgrading to the latest go server? Is it fully backward compatible? Given we are using a pretty old one.

**Comment by ketan** [comment]
> Do you see any minor issues, that I must be aware of upgrading to the latest go server? Is it fully backward compatible? 

There are some known limitations with regards to some old and insecure SSL ciphers (RC4, et.al)  being disabled by the JVM. The newer version of go may have issues with an older JDK.

I'd suggest that you upgrade to the latest java 7 (or better java 8) on your server and agents before upgrading.
