### ISSUE TITLE
Agent reporting incorrect IP address when having other network interfaces.

### ISSUE THREAD

**Issue by aj-jaswanth** [gocd/gocd#1657]
We have an agent having docker installed. Docker creates a network interface called Docker0. The agent is incorrectly reporting the address of the Docker0 network interface. It is being displayed in the IP address column of the agents page. It is able to pickup jobs though.

**Comment by darioblanco** [comment]
I have the same problem with Vagrant, it shows eth0 IP which is for NAT and `vagrant ssh`, I would like to show IP set in eth1

**Comment by aj-jaswanth** [comment]
I am working on it. Will update the progress.

**Comment by aj-jaswanth** [comment]
I hope that this https://github.com/gocd/gocd/commit/b283b426c678c94f83d1688e232a90c896fbd8e0 fixes the issue.

**Comment by ketan** [comment]
Reopening, @rajiesh will close this after a quick check
