### ISSUE TITLE
Pipeline with 9 stages wraps around to below

### ISSUE THREAD

**Issue by richard-hulm** [gocd/gocd#1663]
![wrapped around](https://cloud.githubusercontent.com/assets/11884765/11533028/73ce5458-98ff-11e5-9225-9824df734264.png)

Maybe allow the boxes to expand rather than forcing it onto a new line?

**Comment by GaneshSPatil** [comment]
This issue has been addressed as part of the GoCD new dashboard in version`18.3.0`.
Attaching a screenshot for reference:

![screen shot 2018-05-29 at 12 18 27 pm](https://user-images.githubusercontent.com/15275847/40642369-8ed3d5d6-633a-11e8-9ccd-1cd184143509.png)
