### ISSUE TITLE
Encoded routes can be used to access resources

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1665]
We can use an encoded route to access a resource,

e.g /go/api%2Fusers resolves to /go/api/users

Possible reason for this is could be way urlrewritefilter works. It decodes the url and then matches a rule.

This issue was reproducible on Go Version: 14.4.0(1356-86064ef5ee28e0)

**Comment by ketan** [comment]
Here's how I'm thinking about this situation —

What we absolutely MUST allow is for users to be able to craft a URL with a login name that contains characters that have a special meaning WRT urls (`?`, `&`, `=`...)

**Comment by ketan** [comment]
Here's how I'm thinking about this situation —

What we absolutely MUST allow is for users to be able to craft a URL with a login name that contains characters that have a special meaning WRT urls (`?`, `&`, `=`...)

If in doing so, we also also allow for users accidentally making mistakes and going to `/go/api/%2Fusers/:login_name`, it is probably not so much of an issue, but that is unintended behaviour that may not not work at a later point.

WDYT?

/cc @arvindsv
