### ISSUE TITLE
Accordion steps in build detail page

### ISSUE THREAD

**Issue by jamesob** [gocd/gocd#1672]
It'd be really nice if we could improve the UI on the build detail page to "fold" or accordion each shell command that's run [a la circleci](https://circleci.com/gh/nabeken/circleci-packer-example/4).

I spend a lot of time each day digging through console output to figure out exactly which part of a task failed, and the accordion design makes that very easy.

**Comment by arvindsv** [comment]
+1 and more. :) If anyone is looking to do some work around the UI (could be you, @jamesob), this would be nice and valuable.

**Comment by jamesob** [comment]
I might take a crack at it!

**Comment by arvindsv** [comment]
Console logs now have colors and folding. Closing this.
