### ISSUE TITLE
cruise.h2.db can not be opened outside of Go due to inaccessible class

### ISSUE THREAD

**Issue by johntoenail** [gocd/gocd#168]
# Rationale

I want to create statistics on the history and evolution of given Go-Pipelines (amongst others: build-health over time) in our Go-Server (Version 13.2.0)
Due to the fact that the Go-Feed-API turned out to not be the desireable method of choice in our case, I tried to open a copy of cruise.h2.db safely backed up with Go's integrated backup function with the most recent stable version of H2DB. 

```
java -Xms128m -Xmx2048m  -jar h2-1.3.176.jar -web
```
# Issue:

Opening the database fails with the following error message from H2DB-web interface:
(JDBC-URL given is: jdbc:h2:~/kit/go-server-db/cruise)

``` sql
Class "com.thoughtworks.cruise.server.sqlmigration.Migration_230001" not found; SQL statement:
SELECT ALIAS_CATALOG PROCEDURE_CAT, ALIAS_SCHEMA PROCEDURE_SCHEM, ALIAS_NAME PROCEDURE_NAME, COLUMN_COUNT NUM_INPUT_PARAMS, ZERO() NUM_OUTPUT_PARAMS, ZERO() NUM_RESULT_SETS, REMARKS, RETURNS_RESULT PROCEDURE_TYPE, ALIAS_NAME SPECIFIC_NAME FROM INFORMATION_SCHEMA.FUNCTION_ALIASES WHERE ALIAS_CATALOG LIKE ? ESCAPE ? AND ALIAS_SCHEMA LIKE ? ESCAPE ? AND ALIAS_NAME LIKE ? ESCAPE ? ORDER BY PROCEDURE_SCHEM, PROCEDURE_NAME, NUM_INPUT_PARAMS [90086-176] 90086/90086
```

The mentioned class is present in the cruise.war in 

```
WEB-INF/classes/com/thoughtworks/cruise/server/sqlmigration/Migration_230001
```

Adding the classes of Go-Server to the classpath of H2DB does not help the issue:

```
CLASSPATH=go-server/WEB-INF/lib/:go-server/WEB-INF/classes/
```

It does not help to switch off class deserializing and loading with "h2.serializeJavaObject=false"  in H2DB as described on:
http://www.h2database.com/html/advanced.html#java_objects_serialization
# Desired behaviour when fixed:

I'll be able to open and query the database free using H2DB outside of the go-server.

**Comment by maqdev** [comment]
Just FYI command line above doesn't help because migration classes are in another directory. Here is what fixed problem:
` java -cp "/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/lib/*:/var/lib/go-server/work/jett0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/classes/" org.h2.tools.Console`
