### ISSUE TITLE
Fan-in bug?

### ISSUE THREAD

**Issue by virtuald** [gocd/gocd#1680]
With pipelines A, B, and C.

    A -------------> C
      \             /
       ----> B -----

If someone manually triggers A, then I find that C immediately triggers without waiting for B to finish, and the upstream locators are A/2 and B/1. Is that expected behavior or a bug?

**Comment by srinivasupadhya** [comment]
Fan-in completely relies on SCM changes. If you manually trigger A & there
is no SCM change then A/2 & B/1 are still compatible (same SCM revisions)
and hence C can run with those revisions.

**Comment by ketan** [comment]
Marking as closed. @virtuald — please ask any further questions on the [forums](https://groups.google.com/d/forum/go-cd), there's a very high likelihood of finding answers there.
