### ISSUE TITLE
CCTray feed has 127.0.0.1:8153 in weburl instead of hostname used to fetch the feed

### ISSUE THREAD

**Issue by nurous** [gocd/gocd#1689]
Request to http://[go_server_external_hostname]/go/cctray.xml returns feed but with the 'weburl' set to http://127.0.0.1:8153/go/[rest_of_path] This makes linking to the build failures from the cctray feed not possible.

Ideally the 'weburl' in each entry would be http://[go_server_external_hostname]/go/[rest_of_path]

Version: 14.2.0(377-d8a2866d6af85e)

**Comment by zabil** [comment]
Version 15.2 does not have this problem. Marking this as fixed.
You can verify this on build.go.cd

**Comment by zabil** [comment]
Also please not the url used here comes from what you've configured here
https://www.go.cd/documentation/user/current/installation/configuring_server_details.html#configure-site-urls

**Comment by nurous** [comment]
Thanks, I didn't know about the config option. That worked fine.
