### ISSUE TITLE
Accept username/password as separate attributes for git and hg materials

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1696]
Make git and hg material configs accept a username/password instead of the username/password being part of the URL attribute.

It's probably OK if users enter it as such, but as far as the config is concerned the `url` attribute should not contain this information.

See also #1626

**Comment by gtrias** [comment]
I would like to have this feature as well

**Comment by zabil** [comment]
Consider as a part of #1724 ?

**Comment by ketan** [comment]
> Consider as a part of #1724 ?

I think not. This would only increase scope of #1724

**Comment by Boran** [comment]
Why was this closed, I don't see any other issue dedicated to allowing the git https URS username/password to come from secure environment variables, or other attributes that could be protected?

**Comment by ketan** [comment]
I'm going to be taking a stab at this.

**Comment by maheshp** [comment]
Not fixing this as we are introducing support for secret params as part of material url.

Refer https://github.com/gocd/gocd/issues/5830 & https://github.com/gocd/gocd/issues/5834

**Comment by maheshp** [comment]
Support for username/password attributes has been added as part of [GoCD 19.4.0](https://www.gocd.org/releases/#19-4-0)
