### ISSUE TITLE
Build, test and develop gocd in docker

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#1698]
Currently a community developer could have some difficulty when trying to develop gocd. Especially first time. There are some cookbooks available [here](https://github.com/gocd/go-dev-setup-cookbooks) and a [vagrant box](https://github.com/gocd/go-development-environment-setup). However these repositories are a little obsolete and presumably unused. I think this is natural process for repositories like these because core team or gocd CI infrastructure does not actually use them.

In my opinion - (in a perfect world) go-agent and all developers should use the same development environment. With an exception that developers need more tools - the graphical IDE, text editor, debugger, web browsers, etc.

I have been implementing this in my private build infrastructure (which also builds gocd from my fork).
My proposition is that we could develop a [docker image with all tools needed to build and test gocd](https://github.com/tomzo/docker-gocd-ide). Similarly like above obsolete projects meant to do.

Then we [develop a second image for community developers to use](https://github.com/tomzo/docker-gocd-workstation). It would have at least Intellij IDEA installed and configured. But ideally it has all the tools you can think of.

The critical part for this to work is that go agents in build.go.cd should use those images. This will enforce consistency among agents themselves and developers.

The way I see it is that `gocd` repository should have a versioned file (_Idefile_) that defines (references) what docker image is required to execute particular build jobs (compile, unit tests, integration tests and further). `docker-compose.yml` is also some option to use for _Idefile_. However I am trying a custom solution at the moment, hence all those _mystery IDE references_.
There can be more than one such image to execute entire gocd CI process, if necesary. 
The **agent should be a docker host**. When job starts to execute agent parses _Idefile_ to spin up a **correct container** with all the right tools to **build this exact commit**. Container lives as long as the job.

The benefits of this approach (in gocd case) are
- go-agent does not need anything installed except for docker - so when you _upgrade_ go-agents there is no avalanche of broken builds because all tools on agents have changed. Now the tools are fetched on each build.
- `gocd` repository (and therefore developer) must always define what is the right environment to execute the build job or otherwise job fails. This enforces consistency but also **allows developer to locally develop a new image before pushing changes to go-server**. This **shifts responsibility of setting up agents from CI-engineer/Go administrator to the developer**. In simple words when developer adds a new dependency then he must first build a new image that has the installed dependency. And he can verify if the _build to be pushed_ is going to pass.
- The further we progress on this, the more possible it becomes for anyone to easily recreate build.go.cd CI process .  (Don't know if that is in your intentions)

The **first step towards this** is what I initially proposed to @arvindsv on gitter - let developer run all tests that are in build-PR pipeline in a docker image.
### Problems and questions
1. We should probably forget about windows (until windows containers 2050)
2. I know how to graphical applications in docker, but with X running on the host. Considering that core team is all on Macs (right?) then I probably this limits the use of the graphical developer's image.
3. I don't know what is the right build/test environment for gocd. So this issue requires quite an involvement from go team. Considering that @ketan has setup everything with chef so far, we could provision the images with slightly modified cookbooks.
4. How far do you think could this be done? considering that acceptance tests are now open-source and (I think) all stages are actually on open tools.

This is just an idea that I wanted to share with you. I can help with this. Especially considering that I already started (only) building gocd in my pipelines this way. 

Who is for and who is against (and why)? :smile:

**Comment by arvindsv** [comment]
This is a good summary (and extension) of what we talked about and more, but just in case (and for history's sake), here's a link to the [conversation on gitter](https://gitter.im/gocd/gocd?at=566b459d187e75ea0e48436d), in case anyone is curious.

**Comment by ketan** [comment]
I'm all +1 on this. This also touches upon a lot of things @arvindsv has said he's like on the build agents, and also solves a lot of the existing maintenance issues with the vagrant box and the cookbooks.

I do have one concern about the cost of running each build if we're going to be provisioning containers on each build. (I don't think that is what you're suggesting).

Are you suggesting building a (public) docker image for the build agents and just running a build on it (no provisioning needed), and then version the docker images itself. In case we need new dependencies for newer versions of go, we'd just need to re-build the docker image? (I'm +1 on this too)

**Comment by tomzo** [comment]
> Are you suggesting building a (public) docker image for the build agents and just running a build on it (no provisioning needed), and then version the docker images itself. In case we need new dependencies for newer versions of go, we'd just need to re-build the docker image? (I'm +1 on this too)

Exactly like this. With emphasis on that this image should be public.
No need to provision on each build. Moreover you'll probably be able to do all provisioning on dockerhub and just pull the image to agents.

**Comment by matt-richardson** [comment]
Rather scared by the part
> We should probably forget about windows (until windows containers 2050)

If an entire OS (that a substantial part of the GoCD community uses) is skipped, it will be very painful to catch up later, and do a big disservice to the whole "GoCD is cross platform" idea.

**Comment by tomzo** [comment]
@matt-richardson You probably misunderstood what I meant. Nobody is dropping windows support in GoCD.
I only meant that we won't be able to implement a development environment described here on Windows, because there is nothing like docker on windows that allows to spin up provisioned, clean environment that fast. On windows there will just have to be an old-style CI agent that has everything installed.
And as for development of GoCD on windows, I really don't know if anyone is working from there. Are you?

**Comment by matt-richardson** [comment]
@tomzo - I'm not using windows for GoCD development - I was using the vagrant vm for a while, but haven't done any dev on it for a long while. Agreed that its probably not necessary to support GoCD development on a windows machine.

As for using docker to run the tests, I think it would probably be better to with windows containers in sync with linux containers, otherwise (once again) windows gets left behind. They aren't stable as yet, but they are in a good place to start experimenting with. 

Not sure I agree with 

> there is nothing like docker on windows that allows to spin up provisioned, clean environment that fast

For example, VMWare instant cloning can ([supposedly](https://blogs.vmware.com/PowerCLI/2015/08/vmware-instant-clone-now-fingertips-new-powercli-extensions-fling.html)) deliver a VM in as little as 0.6 seconds. Agreed that its not as sexy as docker though :)

**Comment by tomzo** [comment]
After reading https://www.go.cd/2015/12/22/gocd-in-2016.html I see that docker container per job will be an option supported natively by Go.

It makes me think that a good moment to develop the docker images would be when elastic agents are done and docker plugin is released. You'll probably want to run at least some jobs in build.go.cd anyway, right?

**Comment by ravenscar** [comment]
@tomzo 

Saw in gitter you asked for a link to the Vagrentfile gist I made, here it is: https://gist.github.com/ravenscar/3f615d18bd123fbbbf6c42875f984780

**Comment by arvindsv** [comment]
Closing. This seems to be done.
