### ISSUE TITLE
User API returns 404 for users with space in login name

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#1706]
- Create a user with space in the login name
-  Get all user using User API - GET http://localhost:8153/go/api/users/
- From the response get the link for user with space in login and perform get of single user - GET http://localhost:8153/go/api/users/test%20another
- the response is 404

**Comment by arvindsv** [comment]
@akshaydewan If you're looking for something small, this might interest you.

**Comment by ketan** [comment]
I believe we'd fixed this with https://github.com/gocd/gocd/issues/1650, but seems like something new has popped up...

**Comment by akshaydewan** [comment]
As per the [docs](http://cdn.rawgit.com/paultuckey/urlrewritefilter/master/src/doc/manual/4.0/index.html) of the latest UrlRewriteFilter, the escape function uses `URLEncoder.encode` which uses `application/x-www-form-urlencoded` encoding. So I guess we shouldn't be using `escape` for path params. Then the question is whether it is safe to pass a character like `>` in the URL path to the controller. ¯\_(ツ)_/¯

**Comment by akshaydewan** [comment]
There is a bug in the latest version of urlrewritefilter which prevents us from upgrading. I've sent a [PR upstream](https://github.com/paultuckey/urlrewritefilter/pull/223) with a fix.

**Comment by rajiesh** [comment]
Since we are depended on the PR upstream moving it to near term
