### ISSUE TITLE
Author(s) with special characters displayed incorrectly when comparing builds

### ISSUE THREAD

**Issue by qtiki** [gocd/gocd#1714]
When comparing two builds of a pipeline and the author in the listed changes contains special characters the display does not work as expected.

For example I see:
`Timo 'Tiki&#39; Kämäräinen &lt;timo.kamarainen@xxx.com> 
2015-12-15T17:19:25+00:00`

When it should say:
`Timo 'Tiki' Kämäräinen <timo.kamarainen@xxx.com> 
2015-12-15T17:19:25+00:00`

Note that this works correctly in all other places that display the author(s). I only see this when comparing changes.

**Comment by ketan** [comment]
I'm unable to see this issue with the latest build.

Would you mind sending a screenshot with the following information —

* go server version (/go/about) has this, so does each page footer
* Your browser, browser version and OS.

**Comment by tribetiki** [comment]
![image](https://cloud.githubusercontent.com/assets/752359/11838664/2d3584ec-a3f1-11e5-9216-9c2f0c01c92c.png)

OS: Windows 10
Browser: Chrome 47.0.2526.106 m

**Comment by tribetiki** [comment]
Looking at the page source explains why the characters are not rendered properly:

```
Timo &#39;Tiki&<wbr/>#39; Kämä<wbr/>räinen &l<wbr/>t;timo.ka<wbr/>marainen@...
```

It seems that the \<wbr/\> tags are incorrectly inserted inside the ampersand character definitions in the author's name.
