### ISSUE TITLE
Pre-execution pipeline errors (the red box)

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#1720]
This is a feature request.
It would be great if there was a clearer error in pipeline execution when the pre-execution fetch materials action occurs instead of having the pipeline card return to idle state and incrementing the number of errors in the red box.
Something like:
* grey out the stage bars (optional)
* Add "triggered by... Failed: fetch materials"

**Comment by arvindsv** [comment]
Is this a duplicate of #1595?

**Comment by benzvan** [comment]
Yes. Yes it is.
