### ISSUE TITLE
[PipelineConfig] General Options

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1722]
- Fix UI & UX
- Perform simple cron validation? Nothing comprehensive, just basic stuff like maybe if there are 
- #1495 Handle pipeline templates
- Automatic pipeline scheduling checkbox (map to stage)
- Do we want to use [pretty cron](https://github.com/azza-bazoo/prettycron) to help users figure out cron syntax? See [this page](https://snap-ci.com/gocd/api.go.cd/branch/master/configuration/cron) for an example.
  sufficient number of fields?

**Comment by arvindsv** [comment]
Closing. Will have to open new issues for a rewrite.
