### ISSUE TITLE
[PipelineConfig] Stages Configuration

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1725]
Acceptance Criteria
- [x] List existing stages and the order 
- [x] Ability to reorder stages 
- [x] Should be able to see the stages configuration type
- [ ] Should be able to use a template to define stages #1495 
- [x] Ability to add a new stage
- [x] Ability to delete a stage 
- [ ] Fix UI & UX
- [ ] Should validate fields and show appropriate error message

**Comment by arvindsv** [comment]
Closing. Will have to open new issues for a rewrite.
