### ISSUE TITLE
[PipelineConfig] Stage Configuration

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1726]
Acceptance Criteria
- [x] Ability to modify the Stage Settings 
  - [x] name,
  - [x] trigger type,
  - [x] Fetch Materials,
  - [x] Never Cleanup Artifacts
  - [x] clean working directory
- [x] Add Job
- [x] List Jobs
- [x] Remove Job
- [x] Ability to add plain and secure environment variables
- [x] Set permissions for the stage
  - [x] Specify locally
  - [x] Inherit from the pipeline group
- [ ] Fix UI & UX
- [ ] Validation and error messages
- [ ] #1492 Roles and permissions on stage trigger

**Comment by arvindsv** [comment]
Closing. Will have to open new issues for a rewrite.
