### ISSUE TITLE
[PipelineConfig] Tasks Configuration

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1727]
Acceptance Criteria

Should be able to ADD/Modify the below types of tasks
- [x] Ant 
- [x] Rake
- [ ] Fetch artifact 
- [x] Pluggable Tasks
- [x] Custom Command
- [x] Lookup Commands
- [x] Run if conditions
- [x] Advance options
- [ ] Fix UI & UX
- [ ] Enable validation

**Comment by arvindsv** [comment]
Closing. Will have to open new issues for a rewrite.
