### ISSUE TITLE
Create pipeline does not work through Go Server API

### ISSUE THREAD

**Issue by Kalle80** [gocd/gocd#1731]
I tried to test new Pipeline creation with newest 15.3 version but it seems there is a problem with "Create pipeline" api. 

Server writes this log when I POST to it:  
LOG: 2015-12-17 13:34:08,363  WARN [qtp2033287945-17] PageNotFound:1080 - No mapping found for HTTP request with URI [/go/tab/admin/pipelines/demo-service.json] in DispatcherServlet with name 'spring-tabs'

It works fine with 15.2...

**Comment by ketan** [comment]
Can you show us the curl request?

Is it similar to this request - https://api.go.cd/current/#create-a-pipeline

**Comment by Kalle80** [comment]
I used the old method: /go/tab/admin/pipelines/:demo-service.json?...

I did not even notice the create-a-pipeline request before! :) Is the old one going to be deprecated soon?

**Comment by ketan** [comment]
The old method will be deprecated very soon (we don't have a date yet, but I'd recommend using the new API)

The old method that you mention was an undocumented API meant to be used only by the UI (which is something that's going away soon)

**Comment by arvindsv** [comment]
Closing this, assuming the new way of doing this works for you. If not, happy to reopen it and talk about it.
