### ISSUE TITLE
[PipelineConfig] Job Configuration

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1733]
Acceptance Criteria
- [x] Ability to modify the Job Settings
  - [x] Name
  - [x] Resources,
  - [x] Job Timeout,
  - [x] Run type
- [x] List tasks by order
- [x] Reorder tasks
- [x] Remove tasks
- [x] Add new task and handle different type of task
- [x] Modify artifacts
- [x] Add artefacts 
- [x] Ability to add plain and secure environment variables
- [x] Ability to add custom tabs
- [x] Ability to modify custom tabs
- [ ] UI & UX
- [ ] Validation and error messages

**Comment by arvindsv** [comment]
Closing. Will have to open new issues for a rewrite.
