### ISSUE TITLE
Check connection on materials does not check branch name

### ISSUE THREAD

**Issue by gmacario** [gocd/gocd#1734]

**Comment by arvindsv** [comment]
I suppose it involves changing [this](https://github.com/gocd/gocd/blob/15cb1b8a92115e025b4b0ef39c500d3a0a45584c/common/src/com/thoughtworks/go/domain/materials/git/GitCommand.java#L224-L226) to make it do a:

```
git ls-remote URL refs/heads/BRANCH
```

**Comment by ketan** [comment]
@juhijariwala @maheshp can you take this up when working on the test connection?

**Comment by maheshp** [comment]
@ketan we will fix it
