### ISSUE TITLE
Old material is used for new trigger of pipeline after rerun of pipeline

### ISSUE THREAD

**Issue by lorijoan** [gocd/gocd#1735]
I have a pipeline setup that functions to increment the POM snapshot version number on an origin/master branch of git.  There are multiple materials configured in the pipeline that are repositories in GIT (a very large amount, 40+).  Each material has been set up via the default, so "poll for new changes" is ticked as true despite the fact this job will always be manually triggered.

There is a single stage.  This is set to fetch materials and clean the working directory.  We then have a job for each of the GIT materials.  The job runs a simple bash script that will do the increment of the version and then commit into master.

This has been working quite well.  Generally, if one of the jobs in the stage fails - we will retrigger the entire pipeline as usually it is a failure that a rerun will not be able to sort out.  (It would be nice in fact if I could make sure the job can't in fact be rerun, but that's another issue :smile:)

Recently, we've seen an issue in which the material version from GIT doesn't seem to have been updated when retriggering the pipeline.  This happened after a rerun had accidentally been done.

Thus, we had:
Run of a job within a pipeline: version 100 of git material used, changes applied, update to master creating version 101 of git material
Rerun of the job within a pipeline: version 100 of git material used again (which makes sense since it's a rerun), changes are applied and the push to master is rejected because it's on version 101 in master
Run of the job within a retrigger of the pipeline: version 100 of git material used again <---- this is an issue, this should have been version 101

Have you guys seen this before or have any clues why we would not have picked up the new material?

**Comment by worstadmin** [comment]
Bump - this is very annoying
