### ISSUE TITLE
Issue with regex commands

### ISSUE THREAD

**Issue by padmam** [gocd/gocd#1737]
Operating system:windows/Mac osx
Details: When a task is created and given regex command and when tried to save the task. The UI takes long time to save and freezes for a while leading to stackoverflow. The task accepts 530 characters. More then that leads to stackoverflow issue and the task is not saved.

Attached is the text(regex.docx) used to replicate the issue and log(go-server.log-issue.docx) indicate stackover flow error.
[error.docx](https://github.com/gocd/gocd/files/69480/error.docx)

Regex: 

```
powershell-java.lang.Thread.run(Unknown Source)28, qtp15955745-28, RUNNABLELocked Monitors:com.thoughtworks.go.config.GoConfigDataSource@4f32c1 at com.thoughtworks.go.config.GoConfigDataSource.writeWithLock(GoConfigDataSource.java:198)com.thoughtworks.go.config.CachedGoConfig@18d61d8 at com.thoughtworks.go.config.CachedGoConfig.writeWithLock(CachedGoConfig.java:97)java.lang.Object@abc9d2 at com.thoughtworks.go.config.GoConfigFileDao.updateConfig(GoConfigFileDao.java:178)Locked Synchronizers:Stacktrace:java.io.WinNTFileSystem.getBooleanAttributes(Native Method)java.io.File.exists(Unknown Source)
```

**Comment by ketan** [comment]
@padmam - can you paste the contents of the doc file inline?

**Comment by arvindsv** [comment]
Closing. I believe this was fixed in https://github.com/gocd/gocd/issues/3551
