### ISSUE TITLE
tag and release for version 15.3.0 missing on github

### ISSUE THREAD

**Issue by pniederlag** [gocd/gocd#1738]
According to the website there is a release 15.3.0 available https://www.go.cd/

However I can't find a corresponding tag or release on github

**Comment by ketan** [comment]
@zabil — we had this on the checklist, did we forget to do this?

**Comment by zabil** [comment]
I missed :-(

Here it is https://github.com/gocd/gocd/releases/tag/15.3.0

On Tue, Dec 22, 2015 at 6:32 PM, Ketan Padegaonkar <notifications@github.com
