### ISSUE TITLE
Give user ability to set timeout property for artifact upload

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#174]
### Description

Currently there is a connection timeout parameter whose default value is set to 5 mins. Unfortunately, this value is hard coded and cannot be configured from outside. Expose out this property as environment variable or in some other way to the user so that its value can be adjusted based on the speed of artifact repository.

**Comment by arvindsv** [comment]
Closing as stale.

**Comment by stretch327** [comment]
Why didn't this get fixed? It's still an issue for projects with large artifacts!

**Comment by chadlwilson** [comment]
Possibly because there had been a lot of change in the 5 years that had passed and it wasn't immediately clear that the configuration or issue was valid as described in 2014, plus didn't have much interest from the community.

If you can supply your GoCD version and confirm it's still the same issue on a recent version I can re-open it. If it's just a matter of making it configurable I can probably take a look at it.

**Comment by stretch327** [comment]
We're using 21.2 at the moment and yes, it's still a problem. Our pre-installer built package is just shy of 2GB and on at 30Mbps upload we timeout regularly. These are macOS builders here on-site. 

Thanks for taking a look at it.

**Comment by chadlwilson** [comment]
Ok, thanks - you're pretty confident it's still a 5 minute timeout?

**Comment by stretch327** [comment]
Yes. We encountered it again on Wednesday. The machines that we co-locate don't have this problem, only the machines that we have here where our upload bandwidth is limited. 

Doing the math:

2000MB / (40Mbps / 8) = 400 seconds = 6.67 Minutes

Basically, anything lower than 50Mbps and we get a timeout.

**Comment by chadlwilson** [comment]
I tried to replicate this and cannot replicate such a timeout being imposed by either GoCD agent or GoCD server. I managed to have an artifact take 13 minutes to upload (after 23 minutes zipping) and it worked just fine.

```
2022-06-14 13:33:22,883 INFO  [scheduler-1] HttpService:69 - Uploading file [/Users/chad/Projects/community/gocd/gocd/agent/data/cruise-12842c4c-1821-4ffa-bd0c-8e9aecd38a3b/bcf24ae4-ee19-41e3-85c9-f55d33adac8c/testfile.txt.zip] to url [http://localhost:8153/go/remoting/files/up42/6/up42_stage/1/up42_job/?attempt=1&buildId=37]
2022-06-14 13:46:25,795 INFO  [scheduler-1] HttpService:125 - Got back 201 from server
```

![image](https://user-images.githubusercontent.com/29788154/173502627-358468ff-79eb-4a3a-8497-7feacdcbcf25.png)


If someone is able to replicate this, can you please include the exception/error from your agent's `go-agent.log` (and/or server if relevant) so I can take a look?

Other than this, people may want to verify the settings on any reverse proxy or load balancer sitting in front of GoCD (e.g one that terminates TLS). Such proxies might have their own HTTP 1.1 request timeouts or something like that which may be causing issues here.
