### ISSUE TITLE
Can't use ssh config for multiple deploy keys

### ISSUE THREAD

**Issue by danielsomerfield** [gocd/gocd#1748]
I am struggling to set up configuration for multiple deploy keys and I'm starting to wonder if this isn't a bug. I chose the path of using the .ssh/config to define multiple keys and it seems like it should work.

For example if I define the following file at /var/go/.ssh/config:

```
Host my-git-config
    HostName my-internal-github.example.com
    IdentitiesOnly yes
    IdentityFile ~/.ssh/my-rsa-key
```

I can run the following command as the "go" user and receive a good result:
```
git ls-remote git@my-internal-github.example.com:/my-repo/path.git
```

However, if I configure material with the same path, I get the following error from go:

```
git@my-git-config:/my/repo.git

In config:
Host my-git-config
    HostName my-internal-github
    IdentitiesOnly yes
    IdentityFile ~/.ssh/my-rsa-key

    Repository git@my-git-config:/my-repo/path.git not found! : 
Error performing command: --- Command ---
git ls-remote git@my-git-config:/my-repo/path.git
--- Environment ---
{}
--- INPUT ----

--OUTPUT ---

--- ERROR ---
STDERR: ssh: Could not resolve hostname my-git-config: Name or service not known
STDERR: fatal: Could not read from remote repository.
STDERR: 
STDERR: Please make sure you have the correct access rights
STDERR: and the repository exists.
```

It appears not to be using the ~/.ssh/config file at all, which is odd given that it appears the code is shelling out to the git command line. I know it uses that .ssh directory because I was able to use it for a single key.

**Comment by danielsomerfield** [comment]
Nope. Not a bug. The problem is that I'm dumb.

Had it configured correctly on the agent and not on the server.

That said, if there is a canonical "right" way to do multiple repos with multiple deploy keys, definitely let me know. I'd even write up a little tutorial on it if there isn't one.

**Comment by ketan** [comment]
> That said, if there is a canonical "right" way to do multiple repos with multiple deploy keys, definitely let me know. I'd even write up a little tutorial on it if there isn't one.

There isn't one that I'm aware of. I've used and recommended what you have done and this works like a charm, is something that is easy to automate via chef or other tools -- but is not very intuitive at first.

Other alternatives include messing around with ssh-agent but there is no easy way to roll it out across multiple agent machines (and the go server).
