### ISSUE TITLE
Warn when 0 agents can perform scheduled work

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#1750]
When a job is scheduled, requiring a combination of environment and resources that no agent can meet, then GoCD should display a warning

Or if you prefer a user story:

> In order lead a happy life,
> As a developer using GoCD,
> I should be warned when there's scheduled work (a job) that will never be executed, due to the job requiring environment/resources that no agent can meet.

**Comment by KamilKopaczyk** [comment]
I got stuck with this problem while trying out gocd (which looks great btw. :+1:). It would improve transparency dramatically.

And... (maybe be this should be reported as a separate issue?)
when no agent is capable of running scheduled job, the job remains in the 'Building' phase. It suggests that something is actually going on, while there is no agent available. Can be confusing.

**Comment by marbis** [comment]
+1

**Comment by lenucksi** [comment]
:+1: 
I especially like the user story's motivation part! :D
