### ISSUE TITLE
Jobs with no tasks within should be invalid

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#1760]
The following should be invalid.
```
<jobs>
    <job name="defaultJob" />
</jobs>
```

**Comment by fabriciocduarte** [comment]
Would that cause a validation failure ?
If so it could potentially be a breaking change. 

I usually set jobs with no tasks for No op operations

**Comment by varshavaradarajan** [comment]
Well, yes, that's a good point. Adding a validation and a configuration migration to it will end up being a breaking change as it may cause the pipeline itself to be removed.

**Comment by varshavaradarajan** [comment]
Well yes, that's a good point. Adding a validation and a configuration migration can cause the pipeline itself to be removed. I will close this issue.
