### ISSUE TITLE
15.3.1 rpm package - CentOS 5 - rpm lib incompatibility

### ISSUE THREAD

**Issue by patrick92100** [gocd/gocd#1766]
at install command
rpm -i go-server-15.3.1-2777.noarch.rpm
error: Failed dependencies:
    rpmlib(FileDigests) <= 4.6.0-1 is needed by go-server-15.3.1-2777.noarch.rpm
    rpmlib(PayloadIsXz) <= 5.2-1 is needed by go-server-15.3.1-2777.noarch.rpm

it seems that the rpm package was build with rpm lib only supported on CentOS 6(7), and not supported by CentOS 5

**Comment by patrick92100** [comment]
CentOS 5 and CentOS 6 have wildly different versions of rpm (and rpmlib) and the CentOS 6 version has support for newer payload compression and a newer FileDigests version than the version of rpm (and rpmlib) on CentOS 5 can support

**Comment by ketan** [comment]
Can you try installing via `yum install go-server-15.3.1-2777.noarch.rpm` instead of `rpm -i go-server-15.3.1-2777.noarch.rpm` ?

**Comment by patrick92100** [comment]
Hello Ketan,
The server has no access on the public internet, the yum install cannot be done, sorry

**Comment by ketan** [comment]
> The server has no access on the public internet, the yum install cannot be done, sorry

You could try this on a different vagrant box and see what additional packages are needed.

Beyond that I can't really help you much if your server has no internet connection.

**Comment by patrick92100** [comment]
Yes , I understand.
i will use 7-zip to un-package the delivery on a PC, and upload the go.jar to the server(and eventually others delivery folders), should solve the issue...

**Comment by patrick92100** [comment]
by making folder comparaison on the 2 last delivery, only the server.sh and go.jar are differents

**Comment by ketan** [comment]
Related issues should help resolve CentOS 5 rpm errors.

* https://michaelheap.com/build-centos-5-generic-rpm-on-centos-6/
* https://github.com/jordansissel/fpm/issues/192

**Comment by rajiesh** [comment]
verified on go-server 16.1.0-2855 on centOS 5.7 and the rpm package installed without complaining about the dependency failure

**Comment by arvindsv** [comment]
Closing this, since it seems to be fixed.
