### ISSUE TITLE
Pipeline API: no way to delete a pipeline?

### ISSUE THREAD

**Issue by eugeneventer** [gocd/gocd#1773]
https://api.go.cd/current/#pipeline-config - there does not seem to be a way to delete a pipeline...

Is this correct or am I missing something?

Thanks!
Eugene.

**Comment by jyotisingh** [comment]
Pipeline deletion is not really supported in Go at the moment - through the UI as well as the API. Well you could go ahead to the config xml and remove the pipeline from there but it works with caveat. Look at the [documentation](https://www.go.cd/documentation/user/current/configuration/managing_pipelines.html#delete-an-existing-pipeline) and [this](https://github.com/gocd/gocd/issues/879) issue that provide more details about what I mean. 
Until #879 is addressed, it doesnot seem right to provide a way to delete the pipeline through the UI/API.

**Comment by eugeneventer** [comment]
@jyotisingh but I'm able to easily delete a pipeline via the UI, via /go/admin/pipelines - there is a 'Delete this pipeline' action icon and link?

**Comment by jyotisingh** [comment]
Sorry, I have been day-dreaming :disappointed: 

Renaming pipeline is not allowed for the reasons I mentioned earlier. And pipeline deletion (even though is allowed) suffers from the same issue. ie  it doesnot delete data from db or filesystem. So, if you create a pipeline with same name in future, then it picks historical data from older pipeline which could be mis-leading for the user. 

But sure I get your point, if it is allowed from UI then why not from API.

**Comment by jasonolmstead33** [comment]
Any movement on this? my team and I would love to star using Go, and the Go API, but would really need a way to delete pipelines, or at least move them to a new group.. through the API

**Comment by remiego** [comment]
We are looking at using go for pipeline management via the api and seems wrong that a pipeline can be created bit not removed. We are generating transient pipelines and need to remove these after they have been created and invoked, obviously this needs to be aware of downstream/upstream pipelines...

**Comment by yunlzheng** [comment]
Is there have any way to delete go pipeline through the API?

**Comment by zabil** [comment]
@yunlzheng not yet

**Comment by varshavaradarajan** [comment]
Delete pipeline API is available at: https://api.go.cd/current/#delete-a-pipeline

**Comment by arvindsv** [comment]
@varshavaradarajan: The doc page just says: "Deletes a pipeline". Do you think it's worth it to mention where it deletes it from? Meaning, that is deletes it only from config and not from DB.

**Comment by ByteFlinger** [comment]
I have been playing around with gocd lately and what jyotisingh seems to still hold. When I delete a pipeline through the UI (have not tested using the API),  creating a new pipeline with the same name just picks up the data from the old one meaning the pipeline is more or less just hidden from the UI rather than actually deleted.

**Comment by abhijeetahuja** [comment]
the issue still exists, even the delete options gives the warning `Are you sure you want to delete the pipeline 'xyz'? Pipeline history will not be removed from the database and artifacts will not be removed from storage, which may cause conflicts if a pipeline with the same name is later re-created.`
