### ISSUE TITLE
Plugin Infrastructure for Pipeline Label Templates

### ISSUE THREAD

**Issue by Drakekin** [gocd/gocd#1784]
To facilitate the extension of the pipeline label templates to support timestamps in pipeline labels, I am proposing an extension to the existing syntax for pipeline label templates, and the addition of a plugin interface to use it.

The major change to the label template syntax is the addition of passing input to a materialiash replacer.

```
build-${GO_TIMESTAMP(yyyy/MM/dd-HH:mm)}
```

The rounded brackets after the replacer name signify input. The replacer is passed the entire string. The input parameter is passed through as is, to avoid overcomplicating the syntax with the concept of strings or escaping. The output is returned as per any other replacer (such as a material or parameter) and can be truncated.

In addition, the truncation syntax will be extended to support a fuller subset of the python slice syntax, i.e.

```
${SOME_LONG_REPLACER[10:15]}
```

Which would select the 11th through 15th characters from `SOME_LONG_REPLACER`.

```
${REPLACER_WITH_MEANINGLESS_PREFIX[50:]}
```

Which would select the 51st character onwards.

```
${REPLACER_WITH_MEANINGLESS_SUFFIX[:15]}
```

Which would select the first 15 characters.

```
${FUNCTION(stuff)[10:20]}
```

Which would select the 11th to 20th characters of the output of `FUNCTION(stuff)`. In the event that the output of a replacer is not long enough for a given slice, the empty string is returned. In the event that a slice extends beyond the length of a string, the portion of the slice that is within the length of the string is returned. I.e. where `THING` is `123456789`:

```
${THING[5:15]}
```

Will be replaced with `6789`.

Negative slices are also allowed, and allow for the selection of substrings from the end of strings where the length is not known ahead of time. I.e.

```
${THING[-5:]}
```

Will return the last five characters of `THING`, `56789`.

```
${THING[-5:-7]}
```

Will return characters -5 through -7, `567`.

Finally, a plugin API would be added to allow plugins to provide additional replacers. These would follow a simple API and have access to some information about the current build, any materials or parameters available, as well as any information passed in.

Plugins would not be able to change the syntax of the pipeline label templates, and must register their names. Plugins would take priority over identically named materials or parameters, and plugin authors would have to be warned over the importance of selecting names that are unlikely to clash with material or parameter names. Namespacing (with `GO_` or similar) is suggested as a workaround.

A potential future improvement would be allowing the explicit addressing of functions, materials and parameters, but that is outside the scope of this improvement.

**Comment by matt-richardson** [comment]
Would it be easier to implement something like [TeamCity's build messages](https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingBuildNumber)? That way a build can specify  the label itself.

**Comment by donaldguy** [comment]
Another use case that I have: I want our pipeline labels to be (part of) the output of `git describe` rather than `git rev-parse HEAD` (or equivalent).

**Comment by tomzo** [comment]
+1 I support this functionality very much. 

@Drakekin how is your progress on it?

My use case for custom labels is using value from consul KV store, so plugins are a necessity for me.

As I said earlier I can help getting this done. If you get stuck for whatever reason let me know.

**Comment by Drakekin** [comment]
Work stopped for a while due to shifting priorities, but we're picking it back up now. We should have something to show of it in the Near Future:tm:.

**Comment by Painyjames** [comment]
+1
I would love to have that python truncation on my labels.

**Comment by donaldguy** [comment]
Any updates? - I went through a bit of a whacko time to jerry-rig #1576 so it would be nice to be able to use branch name labels at least

**Comment by rawouter** [comment]
+1 here, I'd like to label pipelines with git tags

**Comment by fragsalat** [comment]
+1 I would like to have the branch name in my label but as far as I checked the code this is not a simple change. It would require to extend the MaterialRevision concept by more information to be able to use it inside the updateLabel function.

Any plans to do so?^^

**Comment by magowant** [comment]
I would like to set the pipeline label template to a semantic version, automatically generated using git commit history.  I think @matt-richardson  [suggestion](https://github.com/gocd/gocd/issues/1784#issuecomment-170792124) of using a special tag in the build output to identify a new pipeline label is the most flexible option, and the easiest to implement from a developer perspective

**Comment by dlethin** [comment]
+1

**Comment by luizbezerra-pinheiro** [comment]
+1 Would be a good feature

**Comment by monikakatiyar16** [comment]
It would be really helpful, if we can have some way to customize the pipeline label. Either via a provided pre-run script or Build / version file contained in the artifact or material check out. We have been using gocd to generate a single build, which can be deployed to multiple environment (dev,qa, staging,production). One pipeline is for build. Another one has got 3 stages with manual gates in the order: qa > staging > production. The same artifact is propogated through these stages without any other build. Intent is to deploy the exact same artifact verified by QA/ passed in UAT to production. We have been using release versio param in build pipeline to identify whether it's a release or hotfix or regular sprint development deployment. We use this param in the pipeline label. The same pipeline label is being used in the downstream pipeline. So, even when the development/hotfixes/sprint releases - multiple deployments happen through these stages, we can go to history and click on next to move the artifact to next stage based on the pipeline label (which contains the semantic release version). We have the mechanism to auto increment the release numbers, but no good way to identify which particular pipeline run to propogate further to production.
If there is some way to customize the pipeline label to either pick values from some custom pre run script, we could get the latest tag and increment the values there. Otherwise, if it can be picked from a version or package.json kind of file, we can work through that too.
Is there any alternative for my use case to avoid manually putting in the release numbers before creating respective microservices builds?

**Comment by arvindsv** [comment]
@monikakatiyar16 Thank you for explaining your expectation. It is useful to know. As you probably know, it is now possible to use environment variables in pipeline label templates: https://docs.gocd.org/current/configuration/pipeline_labeling.html#using-pipeline-level-environment-variables

The challenge there, of course, is to get a useful pipeline-level environment variable to use. You can't run a git command for instance, and set it to an environment variable.

I think it should be possible to provide an API to update a pipeline's label (not label template). I checked the APIs on https://api.gocd.org/current and none of the APIs seemingly(thankfully) use the label in their URI. So, it should be safe to allow it to be modified by users without any consequences.

A challenge there, of course, is: Where do you call the API from? I suppose you can set up a task to update the label of the current pipeline. In this case, there will be a GoCD generated label for a short time, which then gets updated. The job will need to be provided with credentials to call the API though.

Another issue that will then come up is the space in the UI to show the (updated) label. There isn't much space right now and it'll need to be shown in full to be useful enough to convey information.

![image](https://user-images.githubusercontent.com/172235/74328155-55946880-4d85-11ea-9d5b-e84e533e9f5d.png)

By the way, the reason I'm not advocating for allowing a command to be allowed in the label template is security. The label of a pipeline is decided on the GoCD server, when a pipeline is created. Allowing a command to run there is a simple backdoor into running anything anyone wants on the GoCD server. This ability will be provided to all users who can modify pipelines. That's not a good idea to allow.

I think allowing the pipeline label to be updated is a workable compromise, along with a small improvement in the history page to show more of the label. What do you think?

/cc @gocd/committers What do you think?


Are there any takers from the people who have commented on this issue to attempt to implement this (unless anyone has objections).

PS: This conversation is actually better suited for https://github.com/gocd/gocd/issues/52.

**Comment by maheshp** [comment]
The pipeline label is passed as an environment variable for all the jobs in the  pipeline and its downstream pipelines. Changing the pipeline label post the runs would make it inconsistent with the environment variables in the job.

The pipeline history page has an ability to comment on a pipeline run. Users can use this to tag a pipeline run with an appropriate value.  Can this be an option over changing the pipeline label. The comment always shows up in a modal though, the UX needs to be improved.
