### ISSUE TITLE
Git material is always cloned if branch is set to empty string

### ISSUE THREAD

**Issue by juhijariwala** [gocd/gocd#1785]
`<git url="url" branch="" materialName="git" />` in config will cause the material to be always cloned durign MDU.
Go takes care of setting the default branch only when branch is set to null, but not empty string

**Comment by ketan** [comment]
Should we disallow blank branch names for git and strip out any blank branch names?

@varshavaradarajan want to take this up quick?

**Comment by mrmanc** [comment]
@ketan that makes sense to me, as there’s no valid use case for a blank branch. It would certainly be a good idea to fix any existing bad examples. Alternatively I could imagine it would be easier to simply treat empty branch names as master, then you won’t have to fix existing configuration.

**Comment by varshavaradarajan** [comment]
Yeah, sure. Was looking it up yesterday and @juhijariwala and I have looked into it. Met with some test failures with respect to https://github.com/gocd/gocd/issues/1372 while testing this issue. Looking into both.

**Comment by rajiesh** [comment]
Verified on 16.2.0-2996 (d4db1b5d626eee6065152dd980bb919d8a1cfd10), works as expected
