### ISSUE TITLE
Vague message about material when material API used to notify of a build

### ISSUE THREAD

**Issue by mrmanc** [gocd/gocd#1787]
I just spent a fair amount of time trying to work out why a GitHub Enterprise web hook wasn’t working. I ended up just trying the curl example from the API docs as I was confused by the message I was getting (a 404 with body: “Unable to find material.”). Unfortunately I could only see that with a bit of digging in GitHub… the message the pre-built web hook gave me was ‘Invalid Go server URL’.

I spotted this message in against the key `MATERIAL_NOT_FOUND` in https://github.com/gocd/gocd/blob/master/server/webapp/localize.xml#L64.

How would people feel about this message suggesting that perhaps the material needs to be set to `autoUpdate="false"` in the configuration XML (as gently suggested in the [docs](https://api.go.cd/current/#notify-git-materials))?

**Comment by arvindsv** [comment]
I'm all for better messages.

**Comment by grahamc** [comment]
+1 I was experimenting with notifications yesterday and got a 404, `Unable to find material.` as well.

This may be a different issue, but I was surprised to find I couldn't `notify` a material which was set to `autoUpdate`. It makes it difficult to start with autoUpdate and migrate to notifications, as I have to do a hard cutover on each material.

**Comment by mrmanc** [comment]
@grahamc yes, it does make it tricky—especially if you don’t have access to edit all the configuration XML so that you can make the change in one go… in fact it is potentially impossible for a user to change that property on a material if the material is in use by a pipeline in a different pipeline group, as each instance of the material has to have the same value.

@arvindsv should how would you suggest proceeding. I can make a small PR to change the message to something like `Unable to find material. Materials must be configured not to poll for new changes before they can be used with the notification mechanism.`, but I wasn’t confident that there wasn’t any other business logic that would be good to refer to in the message? It looks from [PipelineGroups.java](https://github.com/gocd/gocd/blob/ad8fc27d552f038fc8609c27cd0d6e4eadd90739/config/config-api/src/com/thoughtworks/go/domain/PipelineGroups.java#L162) that autoUpdate=false is the only relevant restriction.

**Comment by ketan** [comment]
> @arvindsv should how would you suggest proceeding. I can make a small PR to change the message to something like `Unable to find material. Materials must be configured not to poll for new changes before they can be used with the notification mechanism.`, but I wasn’t confident that there wasn’t any other business logic that would be good to refer to in the message? It looks from PipelineGroups.java that autoUpdate=false is the only relevant restriction.

If you submit a PR we can validate that it's not breaking anything.

**Comment by jyotisingh** [comment]
@mrmanc - The only place this message is used from is [MaterialUpdateService#notifyMaterialsForUpdate](https://github.com/gocd/gocd/blob/1323b840972b5540ab7ad993a260159e211ab3c3/server/src/com/thoughtworks/go/server/materials/MaterialUpdateService.java#L136), so feel free to change this to something that makes more sense. Could you also rename the key to something more appropriate as its not just a material-not-found case. Just perform a text search for "MATERIAL_NOT_FOUND" and you will find all places to fix the usage.

**Comment by mrmanc** [comment]
Thanks @ketan and @jyotisingh… I’ve done both of those :+1:
