### ISSUE TITLE
Enabling agents via Update Agent API has no effect

### ISSUE THREAD

**Issue by rmarcinik** [gocd/gocd#1794]
First, I want to thank you all for improving the go api in the latest release.  I am already using the new features to manage agent settings. (Go Version: 15.3.1) 
However I think there is a bug with updating an agent.  I am following the examples here:  [api.go.cd/current/#update-an-agent](https://api.go.cd/current/#update-an-agent ), and when I run the command it does not enable/disable the agent.  It does actually set the resources/environments so I know something is working behind the scenes.  
Here is the command:
```
curl 'http://my-server/go/api/agents/my-uuid' \
-u 'user:pw' \
-H 'Accept: application/vnd.go.cd.v2+json' \
-H 'Content-Type: application/json' \
-X PATCH \
-d '{ 
        "environments":"test",
        "resources":"blah",
        "enabled":true 
    }'
```

I am still able to toggle an agents status by hitting `/go/api/agents/my-uuid/enable`, but it looks like using update is the preferred method.

**Comment by arvindsv** [comment]
@ketan would know. Maybe some documentation about `agent_config_state` is missing?

**Comment by arvindsv** [comment]
I think it's related to: https://github.com/gocd/gocd/pull/1455, which says "enabled" and "state" are removed in v2 of the API.

**Comment by ketan** [comment]
@rmarcinik - what @arvindsv said is correct, you'd need to set `agent_config_state` to be one of `Enabled` or `Disabled`. I'll update the api documentation in a couple of hours.
