### ISSUE TITLE
Pipeline Api: Not able to create a pipeline using the api 

### ISSUE THREAD

**Issue by cw-deenbandhu** [gocd/gocd#1795]
I am using the api as shown in the docs https://api.go.cd/current/#create-a-pipeline but i am not able to create a pipeline any help on this

**Comment by jyotisingh** [comment]
Sorry, can't help unless you provide some more details. What does your request and response look like?

**Comment by cw-deenbandhu** [comment]
curl -k 'https://localhost:8153/go/api/admin/pipelines' \
>       -u 'username:password' \
>       -H 'Accept: application/vnd.go.cd.v1+json' \
>       -H 'Content-Type: application/json' \
>       -X POST -d '{ "group": "apitesting",
>                     "pipeline": {
>                     "label_template": "${COUNT}",
>                     "enable_pipeline_locking": true,
>                     "name": "new_pipeline",
>                     "template": null,
>                     "materials": [
>                       {
>                         "type": "git",
>                         "attributes": {
>                           "url": myurl,
>                           "destination": "dest",
>                           "filter": null,
>                           "name": null,
>                           "auto_update": true,
>                           "branch": "master",
>                           "submodule_folder": null
>                         }
>                       }
>                     ],
>                     "stages": [
>                       {
>                         "name": "defaultStage",
>                         "fetch_materials": true,
>                         "clean_working_directory": false,
>                         "never_cleanup_artifacts": false,
>                         "approval": {
>                           "type": "success",
>                           "authorization": {
>                             "roles": [],
>                             "users": []
>                           }
>                         },
>                         "environment_variables": [],
>                         "jobs": [
>                           {
>                             "name": "defaultJob",
>                             "run_instance_count": null,
>                             "timeout": 0,
>                             "environment_variables": [],
>                             "resources": [],
>                             "tasks": [
>                               {
>                                 "type": "exec",
>                                 "attributes": {
>                                   "run_if": [
>                                     "passed"
>                                   ],
>                                   "command": "ls",
>                                   "working_directory": null
>                                 }
>                               }
>                             ]
>                           }
>                         ]
>                       }
>                     ]
>                 }
>               }'
 this is my request i just replaced username and password with mine and and also url with mine

I am getting response error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

i also tried using https://github.com/gaqzi/py-gocd  a python wrapper for making request to go but still unable to create the pipeline

Thanks in advance

**Comment by cw-deenbandhu** [comment]
and if i use http instead https it gives error "message": "The resource you requested was not found!"

**Comment by zabil** [comment]
curl -k 'https://localhost:8153/go/api/admin/pipelines'

Should be

curl -k 'https://localhost:815*4*/go/api/admin/pipelines
<https://localhost:8153/go/api/admin/pipelines>'

**Comment by zabil** [comment]
Also can you tell us what version of Go CD you are trying this on?

**Comment by cw-deenbandhu** [comment]
I am using go 15.2.0

**Comment by zabil** [comment]
Ah that explains it.

https://api.go.cd/current/#create-a-pipeline


"Create a pipeline.

Available since v15.3.0.

HTTP Request

POST /go/api/admin/pipelines"

Hmm. Do you think there's something we can do to improve on that page to
make it evident?

**Comment by cw-deenbandhu** [comment]
Thank you so much i must have checked it before my mistake
