### ISSUE TITLE
Pipelines can subscribe to stage-status notifications but not pipeline-status notifications

### ISSUE THREAD

**Issue by lenucksi** [gocd/gocd#1798]
As a plugin developer I would like to be able to subscribe my plugin to notifications upon completion of a pipeline with the result of the entire pipeline.
Thus, Go needs a concept of pipeline completion and the creation and publication of events matching that concept.

**Comment by kszatan** [comment]
I'm working on integration with Phabricator and I realized I need 'pipeline-status' notifications to finish the job. Is anyone working on this?  If not I might give it a shot.

**Comment by arvindsv** [comment]
[Linking to the](https://groups.google.com/d/topic/go-cd/a2WFMrIgHJc/discussion) mailing list discussion. Just to make sure this is captured.

**Comment by lazara3** [comment]
Hi, I also need the 'pipeline-status' and the 'job-status'
is anyone working on it?
