### ISSUE TITLE
GoCD API: sometimes specifying protocol version does not work

### ISSUE THREAD

**Issue by virtuald** [gocd/gocd#1800]
GoCD 15.3. In particular, this works:

```
curl http://gocd/go/api/config/pipeline_groups
```

But this does not.

```
curl --header "Accept: application/vnd.go.cd.v1+json" http://gocd/go/api/config/pipeline_groups
```

**Comment by zabil** [comment]
This is expected.
```application/vnd.go.cd.v1+json``` is only applicable to the newer API's (15.2+)

**Comment by virtuald** [comment]
Then change your documentation:

> By default, all requests receive Version 1 of the API. It is recommended to explicitly request this version via the Accept header.

**Comment by zabil** [comment]
@virtuald you can check the pull request referenced here. Please feel free to make the message better.
