### ISSUE TITLE
Support API-only Authentication Tokens

### ISSUE THREAD

**Issue by grahamc** [gocd/gocd#1817]
I've talked to a number of people who see references to username and passwords in configurations. Here is one such example: https://github.com/ashwanthkumar/gocd-slack-build-notifier/issues/27

I think it would be preferable to have Go.CD support something like Github's Personal Access Tokens, or role-based tokens for use in plugins, to remove any ambiguity of what is happening there.

Also, Go.CD should support multiple tokens per user / role, so you can rotate them much more easily. Otherwise you have to update all the usages of that username and password at the same time.

**Comment by zabil** [comment]
We talk about this here #1246

**Comment by grahamc** [comment]
I'm terrible about searching for open issues. Sorry.

**Comment by ashwanthkumar** [comment]
@zabil Is there a way for Plugins to access API without authentication, given they're already running inside the server context? I'm not even sure if that makes sense, but almost every plugin I've written I take go credentials separately (as part of the config) and it kinda feels redundant.

**Comment by zabil** [comment]
@ashwanthkumar unfortunately no.
I don't think there are plans to change that as the idea is to sandbox plugin executions. 
Accessing go api's was not part of the original design, rather they were designed to send a receive messages on events.
Also our API's authorization is derived from the user trying to access the API. Like @grahamc mentioned a token based approach is probably the right way to go.

**Comment by arvindsv** [comment]
GoCD has supported tokens for a while now. Closing.
