### ISSUE TITLE
Provide Cucumber / BDD plugin

### ISSUE THREAD

**Issue by jacek99** [gocd/gocd#1819]
We run BDDs in Docker images prior to pushing them to our repo.

Unlike in Jenkins, there are no plugins out of the box to provide a test report for the BDD run.

Please provide one out of the box with GoCD, similar to the Jenkins one:
https://github.com/jenkinsci/cucumber-reports-plugin

**Comment by grahamc** [comment]
Hi, it is possible to output a report and have GoCD display it, no plugin required: 

https://www.go.cd/documentation/user/current/configuration/dev_upload_test_report.html

Does this do the trick?

**Comment by jacek99** [comment]
It is probably good enough to get going, but it does not have the same nice UI as the Jenkins plugin, with summary, drillable reports, etc.

We can probably live with it,but that Cucumber plugin was really liked by our QA and managers to see how the build was doing and what was getting tested.

**Comment by grahamc** [comment]
I can understand that. I wonder how much work it would be to extract the report generation into something for your project, and publish that as an artifact, or maybe even port this to be a Go plugin. I don't know, just theorizing. :)

**Comment by FredrikWendt** [comment]
https://github.com/jenkinsci/cucumber-reports-plugin/blob/master/src/main/java/net/masterthought/jenkins/CucumberReportPublisher.java#L112 is where the report is generated, and it uses the ReportBuilder from this repo/maven artifact: https://github.com/damianszczepanik/cucumber-reporting

**Comment by arvindsv** [comment]
Closing. Using an artifact, as @grahamc suggested is worth trying. It will be very unlikely for GoCD core to have such a direct integration.
