### ISSUE TITLE
UI for configuration repositories

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#1828]
Once all core parts of #1133 are merged, then feature is functional. Which should be very soon.

Currently the only way to add a configuration repository is by adding elements like this in XML config

``` xml
  <config-repos>
    <config-repo>
      <git url="https://github.com/tomzo/gocd-indep-config-part.git" />
    </config-repo>
    <config-repo plugin="gocd-xml">
      <git url="https://github.com/tomzo/gocd-refmain-config-part.git" />
    </config-repo>
    <config-repo plugin="gocd-xml">
      <git url="https://github.com/tomzo/gocd-refpart-config-part.git" />
      <configuration>
        <property>
          <key>pattern</key>
          <value>*.gocd.xml</value>
        </property>
      </configuration>
    </config-repo>
    <config-repo plugin="json.config.plugin">
      <git url="https://github.com/tomzo/gocd-json-config-example.git" />
    </config-repo>
  </config-repos>
```

It would be nice to have an UI. Probably a tab in Admin page would do it.
Ideally it should support
- list of all config repositories
- add/remove/edit config repository

It should allow to select material and key-value configuration of each repository.
Probably material selection code can be reused from pipeline material selection, with restriction that only SCM materials are allowed.

I am rather clusmy at frontend stuff so I am leaving this for somebody to pick up. I can definitely help to plan this.

**Comment by arvindsv** [comment]
Haven't added this issue to 16.2 or 16.3 release milestone yet. Once the main feature is in, let's take a look at this!

**Comment by arvindsv** [comment]
Closing. This was done recently.
