### ISSUE TITLE
Encrypt secrets over API

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#1829]
I propose Go API support for encrypting arbitrary string on request.

With request payload being something like

``` json
{
  "value" : "secret"
}
```

and response

``` json
{
   "encrypted_value" : "@#$FSDsd"
}
```

The first reason is that now when user commits pipeline configuration in SCM then secure variables should not be plain text. 
There is no way now to obtain encrypted values prior to saving it in configuration. (Except for a very long walkaround: Save some variable via UI, lookup how it looks in `cruise-config.xml` and copy-paste that into SCM code.)

Either API or small part in UI should make it much easier.

**Comment by Byron-TW** [comment]
GoCD seems to keep his DES cipher key in `/etc/go/cipher`, which can be used to encrypt and decrypt values.
When looking [at the code](https://github.com/gocd/gocd/blob/69a39af5c0d7202b505cdf5578cebcff85643103/config/config-api/src/com/thoughtworks/go/security/GoCipher.java), it appears there is nothing more to it.

**Comment by varshavaradarajan** [comment]
@tomzo , for scm and package repository plugins, if the plugin specifies a property (say, password) in the configuration as ```secure```, the APIs for scm and package repository(yet to be announced) return an encrypted_value for property password. Is this what you intended? Or do you think further work is required?

**Comment by tomzo** [comment]
@varshavaradarajan sorry for delayed response.
I don't think that it helps at all. A configuration repository can also have secure environment variables, not just scms and package passwords. IMO the best way to solve this is by adding an endpoint like
```
GET /go/api/secret?secret=<plain-text>
```
which responds with encrypted text. Then this encrypted text can be placed in a file in configuration repository.

Basically the point here is to be able to get properly encrypted value from Go server without altering current configuration. I don't see how  `APIs for scm and package repository`  would help with it. When I want to encrypt a secure variable, I don't want to add scm or package repository.

**Comment by varshavaradarajan** [comment]
@tomzo, thank you. Makes sense. I didn't think about the environment variables for pipelines in config repo.

**Comment by dudadornelles** [comment]
Wasnt this closed by https://github.com/gocd/gocd/pull/2977 ?

**Comment by ketan** [comment]
Thanks for pointing out, I'm closing this issue.
