### ISSUE TITLE
TFS does not create destination directory if project path is a file

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#183]
### Steps to Reproduce -

1) Create a pipeline based on TFS material
2) Specify project path to be a file rather than a directory. Ex - $/some_folder/some_file
3) Specify destination directory. Ex - tfs_dir
4) Run the pipeline
5) Look at the agent side
### Expected Result -

A folder called 'tfs_dir' should get created and file 'some_file' should get checked out in it
### Actual Result -

A file called 'tfs_dir' gets created and content of 'some_file' gets copied to it

**Comment by reidca** [comment]
This is causing us a real headache. Because we are having to use folders rather than files making changes to any file within the folder is triggering builds even though the file being changed is not used by that build. Are there any plans to fix this bug?
