### ISSUE TITLE
API for configuration repositories

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#1830]
I propose to add API for add/update/remove configuration repositories.

Add or edit could look like this:

``` json
{
   "plugin" : "config.json.plugin",
   "configuration": [
      {
         "key": "pattern",
         "value": "*.yaml"
      }
   ],
   "material" : {
      "type": "svn",
      "attributes": {
        "name": "svn",
        "url": "svn://svn.example.com/myProject/trunk",
        "username": "admin",
        "encrypted_password": "aSdiFgRRZ6A=",
        "destination": "myProject",
        "filter": null,
        "auto_update": true,
        "check_externals": true
      }
    }
}
```

Plugin name is optional, default is `gocd-xml` which is not a real plugin.
Material should be validated like standard pipeline material. 

Not sure how to handle edit and delete. In services material fingerprint uniquely identifies each config repository.

**Comment by arvindsv** [comment]
Should we provide each config-repo element with an ID? A generated one? This is what is done with package repositories. Currently, they don't even have a name.

**Comment by arvindsv** [comment]
Related to, and maybe a requirement for #1828.

**Comment by clearly** [comment]
Did this ever happen. Would love to have this right about now =)

**Comment by viniciusgama** [comment]
Hey, any update on this? Is it in the roadmap?

**Comment by arvindsv** [comment]
@viniciusgama - Unfortunately, not. If anyone wants to work on it, I'm sure there will be help provided. But, it's not planning right now, as far as I know.

**Comment by tomzo** [comment]
We just talked about this few days ago and decided that it is not a priority. 
I can help someone get it started and done but I won't implement it myself in the near future.

**Comment by arvindsv** [comment]
Closing in favor of https://github.com/gocd/gocd/issues/3656 and PR https://github.com/gocd/gocd/pull/3664 (merged!).
