### ISSUE TITLE
Check connection not working on 16.1

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#1835]
This fails for all TFS materials, and scm materials with encrypted passwords(such as svn, perforce and TFS).
This is an issue with check connections alone, material updates continue to work as expected.

**Comment by arvindsv** [comment]
@jyotisingh: Can this be closed as done?

**Comment by jyotisingh** [comment]
I think this can be closed as regression tests pass now, unless @rajiesh wants to run some of his own scenarios.

**Comment by arvindsv** [comment]
Ok. Assigning to @rajiesh to decide.

**Comment by rajiesh** [comment]
verified on 16.2.0-3018 (bf8cd734e38545871223b90c4a6c098d0de337ce) test connections works for TFS, Perforce and svn materials
