### ISSUE TITLE
Duplicate Endpoints

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1837]
While building the Pipeline Config SPA there have been instances where the existing endpoints were not usable for various reasons. In these cases news endpoints are added over modifying the old ones. 

This issue is to track the list of OLD vs NEW endpoints, so that the old ones can be deprecated/removed once the SPA page operational.
### OLD Endpoint > NEW Endpoint
1. Admin::CommandsController > ApiV1::Admin::CommandSnippetsController

**Comment by arvindsv** [comment]
Closing. Will need to reopen or open a new open closer to the time we can do this.
