### ISSUE TITLE
deploying from revisions that predate the Go installation

### ISSUE THREAD

**Issue by ghost** [gocd/gocd#184]
I'm using the "Trigger with Options" button to deploy from specific revisions of my subversion repository.

When I first configured my Go server, my repository was at revision 42. Deploying from revision 42 or any later revision works fine. But triggering with an earlier revision number fails with an error like "Unable to find revision [41] for material [SvnMaterial{url=https://svnserver/trunk, userName='go', checkExternals=false}]".

This article http://support.thoughtworks.com/entries/23291981 states that "the revisions available for selection will only be those that the Go server already knows about".

Go should "know about" older revisions, or at least there should be a way to tell it.

**Comment by macdiesel** [comment]
👍 Our organization just started using go and as we bring new teams in this issue has come up. It would be great if Go could build from revisions of materials that pre-date the piplines/materials creation date.

**Comment by arvindsv** [comment]
Closing as stale.
