### ISSUE TITLE
Log Entry Indicating Go-Server Is Up

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#1840]
I'd like go to output a line to the log file when the server is ready to accept incoming requests. I'm trying to automate a restart process and I can't find a way to know when the server is up and ready for a UI test.

**Comment by ketan** [comment]
Doesn't polling for port 8153/8154 work as expected?

My concern with grepping the log file is that if the log format changes, you'd end up getting false positives.

**Comment by benzvan** [comment]
Sure, that's a totally functional way to do it as long as you grep for the version string or something. Not very graceful though.
P.S. I no longer use GOCD so I won't be able to test anything.
