### ISSUE TITLE
Delete role

### ISSUE THREAD

**Issue by iliasbartolini** [gocd/gocd#1847]
Hi, 
currently we cannot find any way to delete a role from the Administration UI.

Apparently the possible way is to manually edit the config file.

Could we add this feature in the UI?

**Comment by arvindsv** [comment]
Deleting one, and not just [removing a user from a role](https://www.go.cd/documentation/user/current/configuration/managing_users.html#assigning-roles)? Yes, it's only from the config file for now. There's work going on around pipeline config, but not around roles or users, currently. I'll keep this open as a request. But, it's unlikely to be picked up soon. :(

**Comment by varshavaradarajan** [comment]
The roles API and the roles SPA can be used to delete a role from the config.

**Comment by zerolaser** [comment]
@varshavaradarajan Having a UI for roles would be a better way for adding/deleting users instead of API calls to GOCD.

**Comment by varshavaradarajan** [comment]
@zerolaser - Adding or removing users from a GoCD role can be done from the roles SPA - `https://<go_server_ip>/go/admin/security/roles`
