### ISSUE TITLE
Stage templates

### ISSUE THREAD

**Issue by jeremymv2** [gocd/gocd#186]
Just as important as Pipeline templates - Stage templates.  For example, I'd like to just be able to create one "Deploy" Stage (template) comprised of a series of Jobs, then be able to use that Stage in any number of Pipelines, but control the behavior through environment variables.  This way, I can achieve deterministic deployments into each of my different environments (DEV,QA,PROD) that all run the same steps; and only have to update those steps in one template.

**Comment by arvindsv** [comment]
Closing in favor of #2243 (they're almost duplicates, but that's newer and has some information related to newer features that are coming up and might help).
