### ISSUE TITLE
Pipeline Config API Endpoint doesn't return the pipeline group

### ISSUE THREAD

**Issue by henriquegemignani** [gocd/gocd#1875]
The information returned by the `/go/api/admin/pipelines/:pipeline_name` doesn't return the pipeline group the pipeline belongs to.

Part of my workflow resolves on creating a new pipeline based on another. I was fetching the configuration of one pipeline, changing some fields, and calling `POST /go/api/admin/pipelines` to create the new one, however the request fails because of missing pipeline group.

**Comment by ketan** [comment]
Conversation and context here — https://gitter.im/gocd/gocd?at=56b0d19e586242210ae10e0f
