### ISSUE TITLE
When installing multiple agents on a single machine, after a reboot only one agent is started

### ISSUE THREAD

**Issue by antonosmond** [gocd/gocd#1877]
I've set up a Go server - v16.1.0 (2855-ada9b36174cc069c860e7fa032cbf2857f135cfb) - on a Linux machine running Ubuntu 14.04 and followed the instructions [here](https://www.go.cd/documentation/user/current/advanced_usage/admin_install_multiple_agents.html) for adding multiple agents under Linux (RPM and DEB). It all works and I can start and stop individual agents, however if I reboot the machine, only one agent gets started automatically after boot. Is there anyway to have it start all agents after a reboot?

**Comment by zabil** [comment]
That's strange
The line
```
ln -s /etc/init.d/go-agent /etc/init.d/go-agent-1
```
Symlinks the init scripts for all the agents. Can you check if the symlinks are in place? Also what agent starts up (always the first one installed, specific or random)?

**Comment by arvindsv** [comment]
Is this the same as https://github.com/gocd-contrib/go-cookbook/issues/59? This was changed in the [agent README](https://github.com/gocd/gocd/pull/1736/files), but the [documentation PR](https://github.com/gocd/documentation/pull/205) does not seem to have been accepted. @ketan was looking at it.

**Comment by antonosmond** [comment]
@arvindsv Yes that's exactly the issue. Looks like the docs just need updating as per the readme you referenced

**Comment by antonosmond** [comment]
Just tested this using the instructions in the agent [readme](https://github.com/gocd/gocd/blob/master/installers/agent/release/README.md) and after copying the init.d script and replacing `go-agent` with `go-agent-1` using sed, it says to use `update-rc.d go-agent-1 enable` to enable starting the go-agent service during system boot. This doesn't actually work because `update-rc.d enable` fails with `System start/stop links for /etc/init.d/go-agent-1 do not exist.`
This is because the copies we've created don't yet have a link in `/etc/rc*.d` and `update-rc.d enable` only works if the link already exists. It seems to work if I replace `update-rc.d go-agent-1 enable` with `update-rc.d go-agent-1 defaults` as this actually creates the required links in `rc*.d`.
Perhaps the [readme](https://github.com/gocd/gocd/blob/master/installers/agent/release/README.md) could be updated to reflect this as well as the docs [here](https://www.go.cd/documentation/user/current/advanced_usage/admin_install_multiple_agents.html)
I'm actually scripting my go server setup and my working bash script to add 3 additional agents on my Ubuntu Go server looks like this:
```
for i in {1..3}; do
  cp "/etc/init.d/go-agent" "/etc/init.d/go-agent-$i"
  sed -i "s/# Provides: go-agent$/# Provides: go-agent-$i/g" "/etc/init.d/go-agent-$i"
  ln -s "/usr/share/go-agent" "/usr/share/go-agent-$i"
  cp "/etc/default/go-agent" "/etc/default/go-agent-$i"
  mkdir /var/{lib,log}/"go-agent-$i"
  chown go:go /var/{lib,log}/"go-agent-$i"
  update-rc.d "go-agent-$i" defaults
done
```

**Comment by arvindsv** [comment]
I think @tomzo and @ketan have better context about this.

**Comment by tomzo** [comment]
@antonosmond the readme says to do as below, which very much like the script you have presented.
```
cp /etc/init.d/go-agent /etc/init.d/go-agent-1
sed -i 's/# Provides: go-agent$/# Provides: go-agent-1/g' /etc/init.d/go-agent-1
ln -s /usr/share/go-agent /usr/share/go-agent-1
cp /etc/default/go-agent /etc/default/go-agent-1
mkdir /var/{lib,log}/go-agent-1
chown go:go /var/{lib,log}/go-agent-1
```

Except for the last line where. You say it should be
```
update-rc.d "go-agent-1" defaults
```
instead of
```
update-rc.d "go-agent-1" enable
```

Right?

Then we should update the readme in Ubuntu. 

I actually tested the procedure using chef recipe that does similar thing, when solving https://github.com/gocd-contrib/go-cookbook/issues/59 so I might have made the mistake of assuming that chef runs `update-rc.d "go-agent-1" enable`

**Comment by antonosmond** [comment]
@tomzo - yep that's right it needs to use `defaults` instead of `enable`.
Not sure if you can do anything about the instructions for multiple agents on Linux [here](https://www.go.cd/documentation/user/current/advanced_usage/admin_install_multiple_agents.html) but may be worth linking straight to the readme in git so the instructions are kept in one place as currently they're out of sync.
Thanks for your help!

**Comment by tomzo** [comment]
Those instructions are generated from [documentation repository](https://github.com/gocd/documentation/pull/205). 

PR is still pendending there, so I will rewrite the commit in a sec. @ketan that would be nice to merge before `16.2`

**Comment by ketan** [comment]
@tomzo — forgot about that PR completely, I've merged it now.
