### ISSUE TITLE
Attempting to update a pipeline params through the API

### ISSUE THREAD

**Issue by duffybelfield** [gocd/gocd#1878]
>  "message": "Someone has modified the configuration for pipeline 'my_pipeline'. Please update your copy of the config with the changes."

Attempting to update a pipeline's params via the API with this snippet:

`curl 'http://localhost:8153/go/api/admin/pipelines/my_pipeline' \
      -H 'Accept: application/vnd.go.cd.v1+json' \
      -H 'Content-Type: application/json' \
      -H 'If-None-Match: "3"' \
      -X PUT -d '{
                  "parameters": [
                    {
                      "name": "CORE_VERSION",
                      "value": "1.0.1.1"
                    }
                  ]
                }'`

I don't see the changes reflected in the Admin gui :(

**Comment by ketan** [comment]
That's usually an indication that you're not using the correct ETag in `If-None-Match`. In order to get the correct ETag, here's what you could do —

```
$ curl -s --netrc https://build.go.cd/go/api/admin/pipelines/build-linux -H 'Accept: application/vnd.go.cd.v1+json' -i | grep -i etag
ETag: "ea8c57c334f569556e675024312f48fb"
```

Also I'm assuming that you're submitting the rest of the pipeline payload, it's not possible to update just the part that you submit (this is perceived as ambiguous by the server), you have to submit the entire pipeline, with changes to just the attributes that you care about.

**Comment by duffybelfield** [comment]
After running that curl request I didn't get any response :( Is it because I'm using an anonymous user?

**Comment by ketan** [comment]
Yes you'd only have read-only access to the build.go.cd server. I'd suggest pointing to your own server with proper admin credentials.

**Comment by duffybelfield** [comment]
That's the response I get when I point to my local machine, do I need to
create an admin user for this functionality to work?

On Wed, Feb 3, 2016 at 3:45 PM, Ketan Padegaonkar <notifications@github.com>
wrote:

> Yes you'd only have read-only access to the build.go.cd server. I'd
> suggest pointing to your own server with proper admin credentials.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gocd/gocd/issues/1878#issuecomment-179004714>.
>



-- 
Chris Belfield - Open Source Enterprise Developer
*MongoDB, Laravel, Magento, Dev Ops.*
*P*: +61 416 577 941
@duffybelfield
http://www.linkedin.com/profile/view?id=3869269
https://github.com/duffybelfield
magento.com - Magento Certified
<http://www.magentocommerce.com/certification/directory/dev/546486/>

**Comment by jyotisingh** [comment]
No, it should work even if you do not have security turned on for your Go server instance.
`curl -s  http://localhost:8153/go/api/admin/pipelines/my_pipeline -H 'Accept: application/vnd.go.cd.v1+json' -i | grep -i etag`
That command should give you the required etag that you need to pass along during for the PUT operation.

Also, noticed that you are trying a PATCH, which is currently not supported for pipelines. You need to PUT the entire pipeline json with the edited params or anything else that you need to change. Check the [docs](https://api.go.cd/current/#edit-pipeline-config)

**Comment by arvindsv** [comment]
@duffybelfield: It might also be useful to run your curl command with the option `-v` to see what's really going back and forth. But, finding and using the right etag will probably fix it. The approach should be to fetch the current version, modify it and send it back with the right if-match header.

This might be easier with a proper scripting language. But, whenever I've had to do this, I do something like:

```
#!/bin/sh

# Exit on failure of any command
set -e

USER=admin
PASSWORD=badger

curl -s --user "${USER}:${PASSWORD}" -H 'Accept: application/vnd.go.cd.v1+json' -D headers -o pipeline 'http://localhost:8153/go/api/admin/pipelines/up42' 
ETAG=$(sed -n 's/^ETag: "\([^"]*\)".*/\1/p' headers)

# Make some change to the pipeline config. In this case, prepend "ABC" to the label template.
sed -e 's/"label_template": "/&ABC-/' pipeline >pipeline.for_update

curl -s --user "${USER}:${PASSWORD}" -o pipeline.after_update -X PUT -H 'Content-Type: application/json' -H "If-Match: \"$ETAG\"" -H 'Accept: application/vnd.go.cd.v1+json' --data-binary @pipeline.for_update 'http://localhost:8153/go/api/admin/pipelines/up42'

echo "Updated pipeline config is in the file pipeline.for_update"
```

**Comment by duffybelfield** [comment]
Thanks for the feedback I will give that a go.

@jyotisingh which part of my call is PATCH? Is it because its not an entire pipeline payload?

**Comment by jyotisingh** [comment]
> @jyotisingh which part of my call is PATCH? Is it because its not an entire pipeline payload?

Yes. Currently your request does not have the right etag that's why the API complains about updating your copy. However, once you start passing on the right etag, it will fail again because the API expects the entire pipeline json to be sent across.

**Comment by duffybelfield** [comment]
I was successful in updating using the exame provided by @arvindsv thanks all!
