### ISSUE TITLE
Changing a pipeline name form "DUMMY" to "dummy" gives SQL error 

### ISSUE THREAD

**Issue by shrechak** [gocd/gocd#1879]
when trying to access logs from console for "dummy", a.k.a the one with the new name, the following error pops up:

SqlMapClient operation; uncategorized SQLException for SQL []; SQL state [null]; error code [0]; Error: executeQueryForObject returned too many results.; nested exception is java.sql.SQLException: Error: executeQueryForObject returned too many results.

**Comment by ketan** [comment]
What version of GoCD are you on?

**Comment by ashwanthkumar** [comment]
@ketan an earlier version `15.1.0(1863-42e58c22aefd03)`. Is this fixed in the newer version?

**Comment by ketan** [comment]
I don't think this was fixed, but nonetheless I suggest you upgrade to 16.1 (16.2 will be out end of week, or early next week).

Can you also provide the full stack trace of the error and which page in go causes this error to show up?

A quick search shows that could be a dup of #710

**Comment by arvindsv** [comment]
Yes, it is.

**Comment by arvindsv** [comment]
So, I'll close it. Pipeline rename, as a concept, is not supported, unfortunately.
