### ISSUE TITLE
Proposal: New Job Run Type - Run once for each IP

### ISSUE THREAD

**Issue by Refresh06** [gocd/gocd#1885]
When installing multiple agents on each server to leverage the kernels, the Run on all agents option becomes pretty useless because this will start up the job multiple times on the same machine.

My proposal is simply to add the run type: Run once for each IP.

**Comment by grahamc** [comment]
I believe you could implement this now by adding a "resource" to one agent per host, and then make the job on run-all-nodes require that resource. Would that work for you for now?

**Comment by Refresh06** [comment]
Off cause this would be possible, but not very practical.

This would require that you plan which pipelines run simultaneously and assign the resources accordingly, almost certainly leading to a sub optimal execution.

I also believe that it would be a cleaner solution the add the option, since my agents do not have different resources, they are identical but allow multiple jobs to run in parallel.

Another option would be to redesign the Agents to make them configurable to fire up multiple worker threads that each request tasks from the server, but I guess the Run once for each IP is much simpler to implement.

**Comment by grahamc** [comment]
What are you wanting to use the run-on-all-agents job for? My understanding is it was either for making sure tests passed in a variety of resources (like on debian, redhat, osx, windows) or for pushing out software updates, but I'm getting the (perhaps false) impression you're using it for something else.

**Comment by Refresh06** [comment]
We are using the run-on-all-agents to distribute executables to multiple servers in a windows cluster.

The cluster is created as a resource (Cluster_1) and assigned to the agents running on each machine in the cluster.

The alternative would be to run the Job once and then do remote installation on the other machines, but that kind of defeats the purpose of having locally installed agents.

**Comment by arvindsv** [comment]
@Refresh06: I understand the case, but I feel it's too niche a case to add yet another kind of run-on-all option.

I know there are other similar requests such as https://github.com/gocd/gocd/issues/827 and https://github.com/gocd/gocd/issues/268. Maybe we should think of some more generic way of doing this, but as a product/project, adding an option for every use case makes it more complicated for usage as well as maintenance.

> but I guess the Run once for each IP is much simpler to implement.

Just for the record, this is not extremely straightforward because at the time the jobs are created (in the code), what is available to it is the AgentConfig instances. What is really needed here is the AgentRuntime instances (since the ip addresses might differ from the ones in the config). So, there will be "plumbing" that will need to be changed to do something like this. This is unlikely to happen in core anytime soon.

> Another option would be to redesign the Agents to make them configurable to fire up multiple worker threads that each request tasks from the server

This might actually become an easier option soon. With a lot of the websocket work, etc. being done, the idea is to allow writing agents in different ways. But, even with threads, they will probably still be seen as different agents by the server.

**Comment by Refresh06** [comment]
@arvindsv 

> I know there are other similar requests such as #827 and #268. Maybe we should think of some more generic way of doing this, but as a product/project, adding an option for every use case makes it more complicated for usage as well as maintenance. I think the current cases are already unwieldy.

I think you are absolutely right that some work is needed here. I don't see how the use case is niche in any way though. When dealing with hundreds of pipelines deploying to the same servers you find the single agent principle to be a bottleneck pretty fast. And since the multiple agent pr. machine solution clashes with the Run-on-all option we seem to be at a loss. I would imagine that countless users of the product find themselves in this situation or has migrated to another tool because of this limitation. I believe that the reason you don't see many more issues with this problem is that the running of multiple agents pr. machine is a bit tricky to setup and therefore not as common as it should be.

> This might actually become an easier option soon. With a lot of the websocket work, etc. being done, the idea is to allow writing agents in different ways. But, even with threads, they will probably still be seen as different agents by the server.

This would actually be my preferred solution, that when you install an agent it would ask how many tasks it should process at a time (defaulting to the number of kernels). This would bring scalability to the users in the simplest way possible and align nicely to other agent based products.

But this scenario does not solve the conflict with the Run-on-all option at all, and I'm inclined to think that the Run-at-all behaviour should actually be changed to do what I suggest, since I have a hard time imagining a use case for running the same job multiple times on the same machine.

**Comment by FredrikWendt** [comment]
Please correct me if I get this wrong!
So what you're doing is essentially modifying a system outside of the Go Agent's directory? That to me sounds like your doing sysadmin work: get on a node, modify the system (as opposed to "do some isolated work in a go agent's temporary directory"). Now, why would you want multiple sysadmin agents on a node? I would argue that you're mixing concepts.

Couldn't you put one agent on each machine into an Environment (or give it a special resource), which you use for system level tasks? Or are you saying that these jobs (distribute a binary) takes too long to only have one agent per system? Is that a property of the job or is this a property of the rate at which you need to distribute binaries?

**Comment by Refresh06** [comment]
@FredrikWendt 

> Or are you saying that these jobs (distribute a binary) takes too long to only have one agent per system?
This is exactly the case. In QA we share servers meaning we have a windows cluster of two machines running 15-20 ASP.NET web services and 20-30 windows services all deployed through seperate pipelines. A deployment takes between 1 and 4 minutes (due to the complexeties of Windows cluster services), which means that we often wait to have a service deployed even though the server has plenty of resources to install the services in paralel.
Sure we could configure environments or resurces to gain some level of paralelism, but it would be a hack to circumvent an underlying problem that realy should be solved (the run-on-all conflicting with multiple agents).

**Comment by wagnersza** [comment]
+1
