### ISSUE TITLE
OAuth implementation is not RFC 6739 compliant

### ISSUE THREAD

**Issue by henriquegemignani** [gocd/gocd#1888]
During the 'Get access token' step, Go expects the _grant_type_ field to be 'authorization-code', however the RFC defined value is 'authorization_code'.

Reference:
https://www.go.cd/documentation/user/current/faq/oauth_overview.html
https://tools.ietf.org/html/rfc6749#section-4.1.3

`$ curl https://gocd/go/oauth/token -d 'client_id=...&client_secret=...&code=...&grant_type=authorization_code'
{"error":"unsupported-grant-type","error_description":"Grant type authorization_code is not supported!"}`

**Comment by arvindsv** [comment]
Closing. This integration is gone.
