### ISSUE TITLE
notification feature/plugin

### ISSUE THREAD

**Issue by jasonxiu0723** [gocd/gocd#189]
the notification feature in GO is kind of TERRIBLE. Admins cannot even setup notification for users but only users can do by themselves.Can you add this feature or plugin as soon as possible? Jenkins is free but it has way much better features than GO, which has to be purchased!

**Comment by srinivasupadhya** [comment]
I have added [notification end-point](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html). Should be available in 15.1.0.

**Comment by srinivasupadhya** [comment]
this is possible through [notification end-point](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html) now. If more notification call backs are required (other than stage status change) please add separate issue.
