### ISSUE TITLE
Working Directory Pattern

### ISSUE THREAD

**Issue by jalleyne** [gocd/gocd#1900]
We have build related files abstracted in a hidden folder `.folder-name`, but the working directory file pattern does not match preceding `.`. This is presumably to avoid `./`, may i suggest something like this instead?

`\.?(?!\/)(([^. ].+[^. ])|([^. ][^. ])|([^. ]))`

I haven't been able to test it other than using http://fiddle.re/5qmhx6 . I can definitely setup the development environment at some point, but no time at the moment so i'll just log the issue.

**Comment by FredrikWendt** [comment]
what about windows paths, ie `.folder\name\`

**Comment by jalleyne** [comment]
Thanks @FredrikWendt

`\.?(?![\/\\])(([^. ].+[^. ])|([^. ][^. ])|([^. ]))` 

i think this should cover it. Tested with these paths:


- ./some/test/path
- .some/test/path
- /another/test/path
- \test\something
- .some\windows\path
- \\a\test\path
- C:\a\test\path

**Comment by xli** [comment]
@jalleyne it's just a bug need to be fixed, it should recognize hidden folders. 
I will send a pull request to fix hidden folder issue

**Comment by xli** [comment]
By the way, it has to be a relative path. The pattern you see in error, is designed to avoid an absolute path. 
So I won't do anything other than let hidden folder work.

**Comment by jalleyne** [comment]
thanks @xli that is correct, and thats exactly the functionality i was expecting.
