### ISSUE TITLE
[config-repos] On server start - invalid merged config or hung MDUs

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#1901]
I am publishing this for the record, while I am trying to figure out the solution.

This happens on code base made up from all my current PRs, so master + #1810 #1825 #1827 . Any of those might have introduced the bug. It is quite likely that fallback mechanism in #1827 caused it because I never saw this before merging it.

I am running a server with about 20 configuration repositories. Most of them are just single pipeline in repository. One case is more complex, it looks like this:
 * there are 3 configuration repositories - A, B, C. Each defines single pipeline, pipeA, pipeB, pipeC respectively.
 * the dependencies in pipelines are `pipeA -> pipeB -> pipeC`

All repositories are in git, half of them uses `go-xml` pseudo-plugin and other half uses extension point with json configuration plugin.

There are 2 issues (maybe related) that I experienced at Go server restart.

**Before restart the configuration is valid at merged and base scope**

## Missing dependency pipeline

I first noticed this issue:
Server starts, then after about 1-2 minutes when all MDUs are finished, there are only some configuration repos loaded and it reports on health error messages:
> pipeline 'pipeB' is does not exist; It is used from pipeline 'pipeC'

The expected behavior is that once all MDUs are finished then there are all most recent confiuration parts to merge a good configuration. We cannot predict in what order new partials are proposed for merge, but that should not matter, because on each new partial a new merge is attempted. Yet, result is different and cannot figure out why.

Although now I get this error on each start, I think there was just one time when simple restarting 'fixed it', which susggests that it is some sort of race condition.

Current workaround is to remove repository `C` from configuration, this causes new merged config to be successfully assembled, then add `C` back to configuration and again merged config is assembled. This is a tip that somehow order of merging matters. (But it shouldn't).

## Hung/Long MDUs

Restarting server several times, each time I experienced messages saying:
> [Material Update] Skipping update of material GitMaterial{url=<config repo url>, branch='ci', submoduleFolder='null'} which has been in-progress since Sun Feb 07 10:40:27 CET 2016

For all/most configuration repositories.

There was in fact no progress on those updates. Workaround is to start server without config-repos section and add it later.

## Debugging

Hopefully I can start development server on the full config and just try to catch it.
Other than that I think I need to add more logging to see in production server what those hung materials are actually doing when they are skipped.

@arvindsv @jyotisingh Is there something obvious to you from looking at this bug? Some tips on debugging?

**Comment by arvindsv** [comment]
I think [this conversation](https://github.com/tomzo/gocd/commit/e644a2dcd0933ed8a51403241672f01d9dd242b4#commitcomment-15947740) is relevant to this issue.

**Comment by tomzo** [comment]
This was most likely cause by stale cache issues which are now solved. I haven't seen this bug since I have merged jyotis work.

**Comment by nehac3110** [comment]
@tomzo could you please tell me in which version of gocd is this issue fixed - 
Missing dependency pipeline
I first noticed this issue:
Server starts, then after about 1-2 minutes when all MDUs are finished, there are only some configuration repos loaded and it reports on health error messages:

pipeline 'pipeB' is does not exist; It is used from pipeline 'pipeC'
