### ISSUE TITLE
[PipelineConfig] Exec Task Enhancement 

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#1902]
Currently Exec task on SPA works as in the old UI. This story is to add some enhancement to this feature. 

Acceptance Criteria
- [ ] Combine Command And Args into a single textbox or textarea
- [ ] Use textbox as default when a new Custom Command is added
- [ ] Ability to toggle between Single and Multiline args(Explore Shellwords for this)
- [ ] UI/UX - Only the header of tasks should be dragable
- [ ] UI/UX - Explore if Lookup and Working Directory sections can be closed by default

**Comment by arvindsv** [comment]
Closing. Will have to open new issues for a rewrite.
