### ISSUE TITLE
Environment variable for dependency pipeline name

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1907]
It's already possible to get the label from an upstream pipeline, but getting the name seems impossible.

Supporting something like **GO_DEPENDENCY_NAME_${pipeline name}**  - in addition to the already existing GO_DEPENDENCY_LABEL_${pipeline name} - would be awesome.

Is it possible to add this?

**Comment by xli** [comment]
What the value is "GO_DEPENDENCY_NAME_${pipeline name}"? Stage name? Job name? Material name?

**Comment by shameemz** [comment]
Hi, Any update on this issue? We also need the material name through 'pipeline instance' api

**Comment by kritika-singh3** [comment]
GoCD also publishes env var `GO_DEPENDENCY_LOCATOR_${material_name}` which contains a string with the format: `:pipeline_name/:pipeline_counter/:stage_name/:stage_counter`.
You can parse the given variable value and get the pipeline name.

**Comment by arvindsv** [comment]
Closing, based on the answer.
