### ISSUE TITLE
Disable gadgets

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1908]
Disable the gadget rendering server and the gadgets within Go.

GoCD currently uses the unmaintained apache shindig library to render gadgets, which has been abandoned and there are currently no maintained implementations of OpenSocial. [Apache Rave](https://rave.apache.org/downloads.html) is one such implementation that claims to want to do monthly releases until they get to a 1.0.

Their last release 0.23 was over a year ago, and the [vote](http://mail-archives.apache.org/mod_mbox/rave-dev/201511.mbox/browser) to move decommission rave was approved 10-to-0.

**Comment by arvindsv** [comment]
Closing. This is done.
