### ISSUE TITLE
API: cannot easily retrieve pipelines that were triggered by a pipeline instance

### ISSUE THREAD

**Issue by virtuald** [gocd/gocd#1911]
It is quite easily to 'walk upstream'... eg, start at a pipeline, look at its pipeline dependencies/revisions, retrieve those instances, look at its pipeline dependencies/revisions... etc. However, unless I'm missing something it's very difficult to go the other direction: find the latest pipeline(s) that were triggered by a build, find the latest pipeline(s) that were triggered by those builds...

This is basically the same thing that the value stream map does, so the information must exist somewhere. It would be great if the API could provide a way to get it.

**Comment by arvindsv** [comment]
Yes, this information is available, and should be made available as an API. The VSM page uses an internal end-point which gives out a JSON, but that is not pure information, as it should be. It has layout information for the VSM as well.
