### ISSUE TITLE
null username

### ISSUE THREAD

**Issue by scriby** [gocd/gocd#1918]
All users created by the github plugin on my instance have "null" as their name:

![image](https://cloud.githubusercontent.com/assets/815188/12963678/04e01e26-d01a-11e5-9853-d5d33f80f3b5.png)

Is there some way I can manually change this in the database? I don't see any way to update it through the UI.

**Comment by arvindsv** [comment]
@scriby: I'm closing this till https://github.com/gocd-contrib/gocd-oauth-login/issues/35 has been talked about, there. Maybe @ashwanthkumar or @srinivasupadhya have ideas. I think this is a plugin issue, and not a gocd core issue. That's why I want to close this till that is confirmed or rejected. Thanks!

**Comment by arvindsv** [comment]
It's not recommended to change it in the DB, but if you really really want to, then it is an H2 DB, available at `/var/lib/go-server/db/h2db/cruise.h2.db` and the `PLUGINS` table has the information you are looking for.

**Comment by jyotisingh** [comment]
This is not a plugin issue either. This happens when the person hasn't set his/her display-name on github profile. So, just set the display name on github, logout and log back in to Go, and you should start seeing user names there.

**Comment by arvindsv** [comment]
Shouldn't the plugin then set the username as the display name?

**Comment by jyotisingh** [comment]
sure, that is something that could be raised as an issue on the plugin.

**Comment by jgielstra** [comment]
The github user didn't set a `Name` in their github profile.
