### ISSUE TITLE
/etc/default/go-server uses the wrong path for JAVA_HOME

### ISSUE THREAD

**Issue by martinkaberg** [gocd/gocd#1920]
I installed a security upgrade on amazon linux that upgraded the open jdk.  The path the installer set during installation was /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.91.x86_64/jre

This jre  is not installed on my system any more and even if it was it might have contained a security flaw affecting the go-server.    I suggest setting the JAVA_HOME to /usr/lib/jvm/jre  which points to /etc/alternatives/jre

**Comment by ketan** [comment]
Every linux distribution seems to set this differently, plus a lot of our users happen to install sun's JDK via a zip file or something similar which makes it nearly impossible to determine `JAVA_HOME` correctly.

If you feel there's a better way to do this in a manner that's cross platform (CentOS, RH, Debian, Ubuntu, Fedora, Amazon Linux) we're happy to fix this.

**Comment by martinkaberg** [comment]
Yeah it's different on all system's i guess it needs to be added to the install script in the package.   On ubuntu its /etc/alternatives/java   I think .  Most systems would use a symlink to the jre though. Using that instead of the full path to a specific version would be better i guess.

**Comment by arvindsv** [comment]
For the record, here's [the code](https://github.com/gocd/gocd/blob/56da44bfc0c927b517262246a862189bfe0bd4af/installers/shared/shared_post.sh#L120-L131) which determines the `JAVA_HOME`. Feel free to try (anyone: I don't think @ketan plans to subject himself to that). I think it's a bit of a futile exercise to get it working correctly across these fast-moving targets.

A workaround is to set the `JAVA_HOME` to `/usr/lib/jvm/jre` after that JAVA_HOME line in `/etc/default/go-server`. There's a marker `# SET_BY_GO_INSTALLER__DONT_REMOVE` at the end of the line set by the installer. It will overwrite only that line, during an upgrade, when it needs to change the `JAVA_HOME`.

**Comment by arvindsv** [comment]
Closing. The expectation now is that JAVA_HOME is set properly in `/etc/default/go-server`. It's decided once at installation time, I think.
