### ISSUE TITLE
Weak Fan-In Issues

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#1924]
GoCD has great support for proper fan-out and fan-in - it's a unique selling point compared to other build automation tools. The Value Stream Map is a second one.

Both these features become flawed with manually triggered pipeline runs.

The actual scheduling of work, when caused by manually triggering a pipeline, will not honor the fan-in principles/framework built into the product. It will instead violate all such rules and pick whatever is latest from the configured materials.
There's no way to manually trigger scheduling of a pipeline which will respect the fan-in feature.

The Value Stream Map is limited to showing only one changeset from a source repo, although an UpstreamPipeline might've run with changeset r1, and a DownstramPipeline run with changeset r2. When the ValueStreamMap displays with focus set to the DownstreamPipeline run, instead of showing that UpstreamPipline pointing to r1 and DownstreamPipeline to r2, both runs point to r2 (which is incorrect for UpstreamPipeline).
The Value Stream Map feature also doesn't differentiate, visually, between pipeline runs which were scheduled honoring the fan-in rules, from those which were run with arbitrarily picked material (ie ignore fan-in).

Combined, this makes the two biggest selling points for GoCD voided.

**Comment by FredrikWendt** [comment]
Some solutions are outlined in https://www.go.cd/documentation/developer/5/5.2.html#5-2-5-a-name-extensions-a-extensions where manual triggers could be checked to respect fan-in.

**Comment by chrislovsund** [comment]
+1

**Comment by xli** [comment]
+1 about manual trigger. Could cause big mistake when deploying to production.

**Comment by arvindsv** [comment]
@maheshp is going to take a look at showing manual triggered pipelines on VSM. Making manual trigger respect fan-in is going to be a larger conversation and needs more thought.

**Comment by xli** [comment]
@arvindsv, @wpc and I had discussion about manual triggering expectation with fan-in, we think it biggest problem is confusion and misunderstanding, maybe disable, or with a big warning (like delete repo in github) may help. However, I can't find out any reason I want to trigger a build with the following secanio:
   
      Codebase A is material of pipeline p1 and p2, p1 is also material of p2.
      A's v1 triggered p1 and then following p2.
      A's v2 triggered p1, but failed at p1, hence p2 won't trigger.

      Manual trigger p2, this will cause p2 pick up p1's v1 result, and A's v2.

So we think maybe the best option is disallow manual trigger without specifying version.

**Comment by FredrikWendt** [comment]
Yes, as it is right now, this button is downright dangerous. Disabling it (or at least having a toggle for turning it off) would be a good thing, preventing people from doing bad things. I mean, in general GoCD makes it hard to implement bad CI/CD patterns, and rather forces you to(wards) good patterns. Except for this button.

One reason I've used this (manual trigger without options), is a scenario where I've pushed things to a source repo but don't want to wait out all time outs in GoCD (material polling, scheduling, job assignment, job pickup). I really thought that the Manual trigger button simply scanned all Material and calculated the latest fan-in compatible versions and scheduled a run with those versions, asap.

The Manual trigger with options-feature should warn if the combination of material have common upstream intersection, but the selected material doesn't share a common ancestor/VSM tree.

**Comment by arvindsv** [comment]
@maheshp, @jyotisingh and I had a conversation about this and the cases where it is meaningful to show a warning in the VSM.

@maheshp: I know it's probably not very easy to do this with images, but might be worth sharing that information so @FredrikWendt can verify.

**Comment by wpc** [comment]
@arvindsv, @maheshp, @jyotisingh:

It is actually very dangerous when the downstream pipeline is deployment pipeline.  It happened multiple times in my previous team: devs try to manual trigger deploy pipeline to recover from production environment issues, but it pull in wrong scripts or artifacts.

If warning is on VMS,  I am worried damages may already made before user see it. 

-- wpc

**Comment by arvindsv** [comment]
I agree with you and @xli's earlier comment about manual trigger. I think we can make it an optional setting at the pipeline level, to disable any kind of manual trigger. Second is making the force trigger or trigger with options respect fan-in. Finally, showing a warning on VSM, if you've enabled it and also forced it to ignore fan-in.

The third one (showing a warning on VSM) is going to be needed, unless we completely remove the ability to force trigger. That's why it's being worked on. I don't think we should remove the ability to force-trigger. Maybe we can change its behavior, but I think there can be cases where it is used (though not strictly correct).

**Comment by wpc** [comment]
@arvindsv  I agree remove manual trigger ability is probably too much. I am thinking if we can show a warning when it not respecting fan-in,  can we show it earlier upon user clicking the manual trigger button? So that user will aware what will happen.

**Comment by FredrikWendt** [comment]
I understand the maintenance burden introduced that comes with feature toggles, but I'd really like a "no, on this Go server, you _can't_ trigger a manual build (without options)" since that's what I'll always run with.

Sure, we could go over every pipeline and make sure you can't enable this is probably something we _could_ do, and _would_ do, but there'll still be a time gap when people can really mess things up. Especially with long pipes of pipelines.

There are two reasons why our people press this button:
a) after a new pipeline is created, with polling turned off (which is what we want and need), it'd be nice to schedule a first run without having to "touch" the Material. Manual trigger with options would be an OK workaround.
b) the delays built-in in Go's current scheduling makes us buy anti-depressants and blood pressure medication - pushing a button makes them at least get a sense of "this will now build as soon as possible, I've done what I can" Issues #1098  #1125 and #1290 and possible more, like a UI showing a build queue (https://api.go.cd/current/#get-scheduled-jobs) would help here too.

Both of these are understandable IMHO, and won't go away soon. In the mean time, I'd like to be sure developers won't accidentally screw up our customer deliveries by pushing unexpected and unwanted combinations of artifacts downstream: I'm hoping for a `DISABLE_MANUAL_TRIGGER=TRUE` or `-DdisableManualTrigger=true` flag.

**Comment by srinivasupadhya** [comment]
the 2nd extension in extensions section [here](https://developer.go.cd/current/5/5.2.html) could be useful?

> Provide "resolve & trigger" button. This is an extension of the first "resolve for trigger with options" feature. People want pipeline to be manual trigger but want it to be consistent.

**Comment by BrewRunner** [comment]
+1 re: providing some kind of mechanism for a manual trigger to respect fan-in.

I have numerous pipelines set on manual, because they have large quantities of frequently updating upstream pipeline dependencies.  These frequent updates would cause unnecessary spinning of the larger downstream dependency if they were not set to manual.  We currently cannot utilize fan-in/out on these larger downstream pipelines because of the manual trigger's inability to respect fan-in/out.
