### ISSUE TITLE
Windows headless install has an issue

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#1928]
I was attempting to install the go server via a cookbook, and noticed that although the install succeeds, the service is not registered. It seems we need some sort of error handling [here](https://github.com/gocd/gocd/blob/0946fc7a9a54555f437fda398fafde0fbc7985bd/installers/server/win/go-server.nsi#L32) but the funny thing is that the package installs just fine through the wizard.

**Comment by arvindsv** [comment]
[This](https://groups.google.com/d/topic/go-cd/8HKrnv7hnPY/discussion) *might* be somewhat relevant. Don't know for sure. The server was never setup for a silent install. Maybe there's something that is not set, like that environment variable mentioned in the post?

**Comment by ketan** [comment]
@rajiesh — you can now setup installer tests for this. Documentation [here](https://www.go.cd/documentation/user/16.3.0/installation/install/server/windows.html#silent-headless-installation)

**Comment by rajiesh** [comment]
verified on 16.3.0-3178(b9741c2e994d09b65debe5d836aa428fd928e6db) and working fine
