### ISSUE TITLE
Add support for Git hooks in config.git

### ISSUE THREAD

**Issue by dayglojesus** [gocd/gocd#1929]
Git hooks added to config.git repo which houses the cruise-config.xml are never executed.

It would be valuable to have this functionality.

**Comment by ketan** [comment]
This git repo is for internal use by GoCD.

Could you tell us a bit more about why you need this?

Since we use jgit to manage the repository, I don't think it supports post commit hooks and yet.

**Comment by matt-richardson** [comment]
We faced this issue a while ago, when trying to sync the config to a github repo. We ended up adding a remote to the repo, and then doing a push every 10 minutes with a cron job. Not as nice as a hook, but worked well for what we wanted.

**Comment by dayglojesus** [comment]
@ketan, @matt-richardson has outlined the reason perfectly. Using a post-commit hook would allow you to push the commits to a remote repo _on-demand_. We too are using cron for this and it's not ideal.

**Comment by aschrijver** [comment]
+1
