### ISSUE TITLE
Allow secure variables (environment) on environments, stages and jobs level

### ISSUE THREAD

**Issue by agileassistance** [gocd/gocd#194]
(enhancement)
Is there a good reason for only allowing secure variables (environment) on the pipeline level? If not it would be great also to have this option on pipeline group, stage and job level.

edit: pipeline group level does not support env. vars

**Comment by agileassistance** [comment]
I would really appreciate this feature in the upcoming release; it's vital for keeping sensitive information secured in the build and the lack of it leads to some convoluted/unnecessary workarounds that makes the pipelines hard to maintain.

**Comment by petergillardmoss** [comment]
+1 to this.

At the moment we have pipeline explosion as we need to create new pipelines every time we need to run the same job but with different secure variables.

**Comment by juhijariwala** [comment]
Picking this up!

**Comment by srinivasupadhya** [comment]
https://github.com/gocd/gocd/pull/1161 - implements support for environments, stage & job level secure env. vars.
