### ISSUE TITLE
Upgrading to agent 16.2.0 fails

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#1941]
I have agents that are originally installed as version 15.2.0 and when upgrading the server to version 16.2.0 the agents fail to upgrade with the following error

`Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'subprocessLogger' defined in class path resource [applicationContext.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.thoughtworks.go.util.SubprocessLogger]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: F:\Go-Agent\tmp\javasysmo6371476124035079021.dll: Can't load AMD 64-bit .dll on a IA 32-bit platform
`

It seems the bundled jre doesn't get updated at the same time and is still 32-bit.

**Comment by zabil** [comment]
This same problem is reported here #1936
We are working to fix this ASAP.

**Comment by zabil** [comment]
Closed via #1936
