### ISSUE TITLE
apt repository not updated for go-server 16.2

### ISSUE THREAD

**Issue by eugeneventer** [gocd/gocd#1955]
Hi there,

Now that 16.2 is available, I don't see the update coming through the apt repository for ubuntu.

Could someone have a look?

Thanks!
Eugene.

**Comment by arvindsv** [comment]
Hi! Have you [seen this mail](https://groups.google.com/d/topic/go-cd/nadSZDN4eM0/discussion) or updated the repo to the one mentioned on the [download page](https://www.go.cd/download/)? Does it still not work?

**Comment by eugeneventer** [comment]
Ah looks like the documentation has now been updated too at https://www.go.cd/documentation/user/current/installation/install/server/linux.html

Thanks - it works now :)
Eugene.
