### ISSUE TITLE
Ubuntu 12.04 install go-server error

### ISSUE THREAD

**Issue by wayde191** [gocd/gocd#1965]
I have installed go-server before in this instance. And i upgrade the apt-get source, the go-server upgraded to go-server-16.1.0-2855.deb, and it goes wrong with the following errors.

**Java:**
ava version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

I followed the install instruction right here:https://www.go.cd/documentation/user/current/installation/install/server/linux.html

**go-server messages:**
Selecting previously unselected package go-server.
(Reading database ... 67134 files and directories currently installed.)
Unpacking go-server (from go-server-16.1.0-2855.deb) ...
'Go Server' installation will now use group 'go'
'Go Server' installation will now use user 'go'
Setting up go-server (16.1.0-2855) ...
Found Java /usr/lib/jvm/java-7-oracle/jre in PATH, using it.
grep: /etc/default/go-server: No such file or directory
Appending to "/etc/default/go-server": export JAVA_HOME="/usr/lib/jvm/java-7-oracle/jre" # SET_BY_GO_INSTALLER__DONT_REMOVE
chown: cannot access `/var/lib/go-server/**': No such file or directory
Installation of Go Server completed.
using default settings from /etc/default/go-server
Error trying to validate file agent-bootstrapper.jar: java.io.FileNotFoundException: /usr/share/go-server/agent-bootstrapper.jar (Permission denied)
Error trying to validate file agent.jar: java.io.FileNotFoundException: /usr/share/go-server/agent.jar (Permission denied)
Error trying to validate file agent-launcher.jar: java.io.FileNotFoundException: /usr/share/go-server/agent-launcher.jar (Permission denied)
Error trying to validate file cruise.war: java.io.FileNotFoundException: /usr/share/go-server/cruise.war (Permission denied)
Error trying to validate file historical_jars/h2-1.2.127.jar: java.io.FileNotFoundException: /usr/share/go-server/historical_jars/h2-1.2.127.jar (No such file or directory)
/usr/share/go-server/db/h2deltas/2_create_indexes.sql (No such file or directory)
/usr/share/go-server/db/h2db/cruise.h2.db (No such file or directory)
Error starting Go Server.
invoke-rc.d: initscript go-server, action "start" failed.
Processing triggers for ureadahead ...
ureadahead will be reprofiled on next reboot

Anything I missed ?

Thanks a lot!

**Comment by Tpbrown** [comment]
Check your ownership of files & directories listed.

My guess is that your prior version of go was running as a different user.

~Sent from my mobile device. Please pardon any oddities :-)

**Comment by wayde191** [comment]
Thanks for your reply.
So I have checked the user "go", and i removed it from user and group, then reinstall it. Still got the issues.

**Comment by arvindsv** [comment]
I think @tpbrown was asking about permissions and ownership of files in /usr/share/go-server/. What do these commands output?

```
ls -ld /usr/share/go-agent/
ls -l /usr/share/go-agent/
```

These files are usually root owned, but have the right permissions to allow the go user to access them. If they're not, you'll need to remove them or change their permissions. Maybe the agent was manually installed into that location earlier? Is that true?

While you're at it, you might as well take a look at the ownership and permissions of /var/lib/go-agent, /var/log/go-agent. They're supposed to be go user owned.

**Comment by wayde191** [comment]
This is the permission:
drwxr-xr-x 2 root root 4096 Feb 21 11:51 /usr/share/go-server/

And here is the way I reinstall go-server:
echo "Removing go-server"
sudo apt-get remove go-server

echo "delete all the files..."
rm -rf /var/lib/go-server
rm -rf /etc/go
rm -rf /var/log/go-server
rm -rf /usr/share/go-server
rm -rf /etc/default/go-server

sudo apt-get install go-server


Thanks a lot.

**Comment by ketan** [comment]
> echo "delete all the files..."
> rm -rf /var/lib/go-server
> rm -rf /etc/go
> rm -rf /var/log/go-server
> rm -rf /usr/share/go-server
> rm -rf /etc/default/go-server

Perhaps append `sudo` here and try again?

**Comment by zabil** [comment]
No response from reporter. Closing this for now. Please feel free to open it if's not yet resolved.
