### ISSUE TITLE
FetchTask issue

### ISSUE THREAD

**Issue by omnidavesz** [gocd/gocd#1970]
Hi,

I've noticed an issue which may very well be something that I'm doing wrong but I would like some clarification on.

I've been trying to use the config API to create stages where the first task is a fetch task pulling an artifact from the previous stage in the same pipeline. I've tried passing in a pipeline name of "" as a CaseInsensitiveString but when I do that I get an error with the following message: "File path is invalid. "" should conform to the pattern - ([^. ].+[^. ])|([^. ][^. ])|([^. ])"

So then I had a look at the code for the FetchTask class and saw that I could omit providing a pipeline name. I then removed the pipeline name and tried using that but I got a RuntimeException instead caused by a NullPointerException.

Is there something in particular I'm doing incorrectly or is this an issue with the GoCD API?

**Comment by jyotisingh** [comment]
@omnidavesz  - Assuming you are referring to the pipeline config api, passing on a empty pipeline for fetch artifact should work. For the edit pipeline config API, the json would look something like the following json, note `pull_from_first_job` which fetches an artifact from the `first_stage`:

``` json
{"label_template": "${COUNT}",
  "enable_pipeline_locking": false,
  "name": "up42",
  "template": null,
  "parameters": [

  ],
  "environment_variables": [

  ],
  "materials": [
    {
      "type": "hg",
      "attributes": {
        "url": "../manual-testing/ant_hg/dummy",
        "destination": "dest_dir",
        "filter": null,
        "name": "dummyhg",
        "auto_update": true
      }
    }
  ],
  "stages": [
    {
      "name": "first_stage",
      "fetch_materials": true,
      "clean_working_directory": false,
      "never_cleanup_artifacts": false,
      "approval": {
        "type": "success",
        "authorization": {
          "roles": [

          ],
          "users": [

          ]
        }
      },
      "environment_variables": [

      ],
      "jobs": [
        {
          "name": "first_job",
          "run_instance_count": null,
          "timeout": null,
          "environment_variables": [

          ],
          "resources": [

          ],
          "tasks": [
            {
              "type": "exec",
              "attributes": {
                "run_if": [

                ],
                "on_cancel": null,
                "command": "ls",
                "working_directory": null
              }
            }
          ],
          "tabs": [

          ],
          "artifacts": [

          ],
          "properties": null
        }
      ]
    },
    {
      "name": "second_stage",
      "fetch_materials": true,
      "clean_working_directory": false,
      "never_cleanup_artifacts": false,
      "approval": {
        "type": "success",
        "authorization": {
          "roles": [

          ],
          "users": [

          ]
        }
      },
      "environment_variables": [

      ],
      "jobs": [
        {
          "name": "pull_from_first_job",
          "run_instance_count": null,
          "timeout": null,
          "environment_variables": [

          ],
          "resources": [

          ],
          "tasks": [
            {
              "type": "fetch",
              "attributes": {
                "run_if": [
                  "passed"
                ],
                "on_cancel": null,
                "pipeline": "",
                "stage": "first_stage",
                "job": "first_job",
                "is_source_a_file": false,
                "source": "console.log",
                "destination": ""
              }
            }
          ],
          "tabs": [

          ],
          "artifacts": [

          ],
          "properties": null
        }
      ]
    }
  ],
  "tracking_tool": null,
  "timer": null
}'
```

This seems to be working as expected in the latest build. Which version of Go are you  on? Can you provide the json you submitted to this API.

**Comment by omnidavesz** [comment]
Hi there. We're using version 15.3.0 of the config API and so we're submitting XML rather than JSON. I'm afraid I'm unable to get you the XML file as we use our own custom Java app and a Jenkins build to generate to file and because of the error the file isn't generated.

However the following code snippet is what we use to generate one of the tasks:

```java
FetchTask task1 = new FetchTask(new CaseInsensitiveString(""),
                new CaseInsensitiveString("Test_Stage"),
                new CaseInsensitiveString("Test_Job"),
                "setup.txt",
                "#{COMPONENT_NAME}");
```

**Comment by omnidavesz** [comment]
Hey, sorry to chase but does anyone have any further information on this?

**Comment by jyotisingh** [comment]
Looks like the value of param `COMPONENT_NAME` is an empty string which causes the destination for fetch task to be empty string. When trying to debug this locally by providing an empty string as the value of `dest` directory, I get the same error as you ie. `File path is invalid. "" should conform to the pattern - ([^. ].+[^. ])|([^. ][^. ])|([^. ])`. This is an issue with go (full) config api and needs to be fixed - Thanks for pointing out, and a PR would be more than welcome :).

Given that you are trying to edit pipeline, I would recommend moving to the [pipeline config api](https://api.go.cd/current/#edit-pipeline-config) which should a lot faster and easier to use compared to the the one you use currently.
If you are unable to move to the pipeline config api at this point, you could set the destination directory to `null` instead of an empty string, and that should fix things for you.

**Comment by omnidavesz** [comment]
Hello again. I actually thought the issue was with the pipeline name rather than the destination directory so thank you for clearing up my misunderstanding.

Using `null` in place of the blank string works for me as changing the api would require an overhaul of our pipeline generator application.

Once again, thanks for the support.
