### ISSUE TITLE
api go/properties returning "Job ... not found" if stage/jobs config changed

### ISSUE THREAD

**Issue by zpsean** [gocd/gocd#1971]
This is posted on https://groups.google.com/forum/#!topic/go-cd/XCf1dmof7tQ, paste it here as issue:

**A stage with config:**
when build 1, 2, it has one job (i.e. containeized) only
when build 3, 4, it has two jobs (i.e. containeized, sonar-check)
when build 5, it has one job (i.e. containeized) only

**However, when using the go/properties api:**
<http://host ip>:8153/go/properties/discovery-server/4/package/1/sonar-check

**got:**
Job discovery-server/4/package/1/sonar-check not found.

**1). Checking the go server, it has information on tab Properties:**
Property name   Property value  
cruise_agent    iZ28h2t7rzrZ  
cruise_job_duration 2  
cruise_job_id   219 
cruise_job_result   Failed  
cruise_pipeline_counter 4  
cruise_pipeline_label   4  
cruise_stage_counter    1  
cruise_timestamp_01_scheduled   2016-02-19T07:28:36Z  
cruise_timestamp_02_assigned    2016-02-19T07:30:12Z  
cruise_timestamp_03_preparing   2016-02-19T07:30:22Z  
cruise_timestamp_04_building    2016-02-19T07:30:31Z  
cruise_timestamp_05_completing  2016-02-19T07:30:33Z  
cruise_timestamp_06_completed   2016-02-19T07:30:33Z

**2). on tab Console:**
Job discovery-server/4/package/1/sonar-check not found.

**3). On tab Failures:**
Job discovery-server/4/package/1/sonar-check not found.

**Comment by akshaymankar** [comment]
I faced this issue yesterday. While I find it reasonable that the pipeline shows that error. But it is not correct for it to pass. It should've failed.
We are using quite an old version of  go (15.2), so there is a good chance this is already fixed.

**Comment by zabil** [comment]
@akshaymankar didn't understand what scenario you are talking about.

This issue talks about the job not being found on stage or job history when you change the configuration to rename or move the job.

**Comment by akshaymankar** [comment]
@zabil Yes, I'm talking about the same scenario. For example, if a pipeline has two stages say: A and B. I rename B to C, while A was running. In this case go tried running B (and not C) and printed that error message. But the pipeline went green, which IMO should've been red.
