### ISSUE TITLE
selecting range of agents and click on action(enable/disable/delete), action applies only to first and last agents

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#1974]
Raising this issue based on this comment https://github.com/gocd/gocd/pull/1808#issuecomment-184609732

When the user selects range of agents on agents page and clicks on any action(enable/disable/delete) immediately the action is applied only to the first and last selected agents and not to the range.

However if the action button is clicked after few secs, say 5 secs, the action applies on all agents

**Comment by GaneshSPatil** [comment]
This issue has been fixed as part of the new agents' SPA.
