### ISSUE TITLE
Firefox failing to download pipelines.json

### ISSUE THREAD

**Issue by blasterspike** [gocd/gocd#1987]
Hi,
whenever I view all the pipelines in 
https://$go_url/go/pipelines
Firefox freezes for 2-3 seconds, then it comes back to normal for 5 seconds, then it freezes again and so on.
Looking at the Network Monitor in Firefox, it happens because it can't download the pipeline.json.
See attachment for details.
The strange thing is that it doesn't break everything at the same line/column but at different points.

We have more than 600 pipelines and the json exceeds 1MB.

Google Chrome instead is able to download completely the json.

Versions used:
Mac OS X 10.11.1
Mozilla Firefox 44.0.2
Google Chrome 48.0.2564.116 (64-bit)
GoCD 15.2.0(2248-c1f90a6aa3192a)

<img width="1440" alt="screen shot" src="https://cloud.githubusercontent.com/assets/7162143/13317829/197f0914-dbaf-11e5-9dbe-fd68c5a78b03.png">

**Comment by zabil** [comment]
Can you tell us what string is at 169/1240 

Might be related to #1472

**Comment by blasterspike** [comment]
Thank you for your reply.
As I was saying, every time it gets stuck at a different line/column.

Here it is stuck at this line
`                "pipeline_env-redeploy-nats-usage-test_panel" : {"html" : "\u003Cdiv class=\"pipeline_header\"\u003E\n    \u003Cdiv class=\"pipeline_actions\"\u003E\n        \n            \u003Ca class=\"icon16 setting\" href=\"/go/admin/pipelines/env-redeploy-nats-usage-test/general\"\u003E\u003C/a\u003E\n    \u003C/div\u003E\n    \u003Cdiv class=\"pipeline_name_link\"\u003E\n        \u003Ch3 class=\"title entity_title \"\u003E\n            \u003Ca href=\"/go/tab/pipeline/history/`

<img width="1440" alt="screen shot 02" src="https://cloud.githubusercontent.com/assets/7162143/13318336/20bab004-dbb2-11e5-9a0c-64a271cfef42.png">

and just at the next GET here

`                "pipeline_hubot-deploy-hive_panel" : {"html" : "\u003Cdiv class=\"pipeline_header\"\u003E\n    \u003Cdiv class=\"pipeline_actions\"\u003E\n        \n            \u003Ca class=\"icon16 setting\" href=\"/go/admin/pipelines/hubot-deploy-hive/general\"\u003E\u003C/a\u003E\n    \u003C/div\u003E\n    \u003Cdiv class=\"pipeline_name_link\"\u003E\n        \u003Ch3 class=\"title entity_title \"\u003E\n            \u003Ca href=\"/go/tab/pipeline/history/hubot-deploy-hive\"\u003Ehubot-deploy-hive\u003C/a\u003E\n        \u003C/h3\u003E\n    \u003C/div\u003E\n\u003C/div\u003E\n\n\u003Cdiv class=\"alert\" id=\"trigger-result-hubot-deploy-hive\"\u003E\u003C/div\u003E\n\n    \u003Cdiv class=\"pipeline_instance\"\u003E\n            \u003Cdiv class='status details'\u003E\n                \n\u003Cdiv class=\"label\"\u003ELabel:        \u003Ca href=\"/go/pipelines/value_stream_map/hubot-deploy-hive/10\"  title=\"10.46\"\u003E10.46\u003C/a\u003E\n\u003C/div\u003E\n\n\n                \u003Cspan class=\"compare_pipeline dashboard\" \u003E\n                    \u003Ca href=\"/go/compare/hubot-deploy-hive/9/with/10\" title=\"Compare with the previous build\"\u003ECompare\u003C/a\u003E\n                \u003C/span\u003E\n\n                        \u003Cspan class=\"separator\"\u003E\u0026nbsp;\u003C/span\u003E\n\n                    \u003Cspan class=\"changes_button_wrapper\"\u003E\n                        \u003Ca class=\"show_panel submit_small dashboard_build_cause_button\" href=\"/go/pipelines/hubot-deploy-hive/10/build_cause\" id=\"show_changes_hubot-deploy-hive_10\"\u003EChanges\u003C/a\u003E                    \u003C/span\u003E\n\n                    \u003Cscript type=\"text/javascript\"\u003E\n                    \u003C/script\u003E\n                \u003Cdiv class=\"pipeline_instance_details\"\u003E\n    \u003Cdiv class=\"schedule_time\" title=\"Mon Sep 28 16:42:53 UTC 2015\"\u003E\n        (Triggered\u0026nbsp;by\u0026nbsp;\u003Cspan class='who'\u003Ej`

<img width="1435" alt="screen shot 03" src="https://cloud.githubusercontent.com/assets/7162143/13318387/5adf8a16-dbb2-11e5-91cb-0131e056c2f1.png">

We don't use any ' in the pipeline names so the issue is not related.

Thanks

Massimo

**Comment by arvindsv** [comment]
Closing as stale.
