### ISSUE TITLE
Error in fetching materials from TFS on agents installed on Windows Server 2012

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#199]
# Environment

Go version 14.1.0(18882-d0272e1d227b5e)
OS: Windows Server 2012 R2 64-bit (server and agents)
This problem affects multiple agent machines some pure vanilla build and some with Visual Studio 2013 installed.
# Problem

Running a job on an agent that needs to connect to TFS to fetch materials errors with the following:
[TFS SDK] Could not create TFS SDK Builder
## Exception

This problem does not occur on the agent installed on the machine where the GO Server was installed
## Analysis of problem

Looking in the go-agent.log the following error can be seen:
ERROR domain.materials.tfs.TfsCommandFactory:47 - [TFS SDK] Could not create TFS SDK Builder
java.io.IOException: The system cannot find the path specified
### Temp directory issue

Further investigation (with the help of Thoughtworks support) shows that JAVA is trying to access the TEMP directory but this directory does not exist and therefore this error is thrown.
The GO AGENT service runs as LOCAL SYSTEM and querying the 'java.io.tmpdir’ setting shows that the value is:
C:\Windows\system32\config\systemprofile\AppData\Local\Temp\
The Windows System environment variables TEMP and TMP also both show the same value.
LOCAL SYSTEM has full control to this directory therefore this was not a permission problem.
### 32bit redirection

The issue arises because the servers and workstations are running agents are 64-bit however the GO AGENT is a 32-bit process.
A peculiarity of Windows is that the 64-bit System folder is called SYSTEM32 and the 32-bit SYSTEM folder is called SysWow64. 
When 32-bit processes access certain 64-bit resources on Windows they get automatically redirected to the 32-bit version rather than the default 64-bit version.
Therefore a call to:
C:\WINDOWS\SYSTEM32\CONFIG\SYSTEMPROFILE\APPDATA\LOCAL\TEMP 
redirects to:
C:\WINDOWS\SYSWOW64\CONFIG\SYSTEMPROFILE\APPDATA\LOCAL\TEMP
Although the PATH C:\WINDOWS\SYSWOW64\CONFIG\SYSTEMPROFILE\APPDATA\LOCAL\ exists on the failing agent machines, there is no "Temp" directory. 
# Solution
1.  Create the directory 
   C: \WINDOWS\SYSWOW64\CONFIG\SYSTEMPROFILE\APPDATA\LOCAL\TEMP and grant LOCAL SYSTEM FULL CONTROL permission to it.
2.  Change the directory JAVA uses for temp to a known good directory where LOCAL SYSTEM has FULL CONTROL such as C:\WINDOWS\TEMP

To do this modify the **wrapper-agent.conf** file  
set.AGENT_STARTUP_ARGS=-Xms128m -Xmx256m %JVM_DEBUG% %GC_LOG% -Djava.io.tmpdir=C:\windows\temp"-DJAVA_SYS_MON_TEMP_DIR=%GO_AGENT_DIR%\tmp"
# Background

There are some discussions of similar problems here: 
http://wrapper.tanukisoftware.com/doc/english/prop-java-tmpdir-x.html 
http://stackoverflow.com/questions/1924136/environment-variable-to-control-java-io-tmpdir

**Comment by ketan** [comment]
@reidca — are you still seeing this issue, if yes, could you provide the gocd server and agent versions?

We suspect that this issue was fixed by #2490, but would like to confirm.

**Comment by HarinezumiSama** [comment]
I'm having the same issue, but the error in "go-agent.log" is different:

> 2018-08-15 09:48:08,567 INFO  [loopThread] TfsSDKCommandBuilder:124 - [TFS SDK] Extract tfssdk/native/win32/x86_64/native_auth.dll -> data\tfs-sdk\tfssdk\native\win32\x86_64\native_auth.dll
> 2018-08-15 09:48:08,567 ERROR [loopThread] TfsCommandFactory:46 - [TFS SDK] Could not create TFS SDK Builder
> java.io.FileNotFoundException: data\tfs-sdk\tfssdk\native\win32\x86_64\native_auth.dll (The process cannot access the file because it is being used by another process)
> 	at java.io.FileOutputStream.open0(Native Method)
> 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
> 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
> 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
> 	at com.thoughtworks.go.domain.materials.tfs.TfsSDKCommandBuilder.explodeNatives(TfsSDKCommandBuilder.java:125)
> 	at com.thoughtworks.go.domain.materials.tfs.TfsSDKCommandBuilder.initSdkLoader(TfsSDKCommandBuilder.java:104)
> 	at com.thoughtworks.go.domain.materials.tfs.TfsSDKCommandBuilder.<init>(TfsSDKCommandBuilder.java:50)
> 	at com.thoughtworks.go.domain.materials.tfs.TfsSDKCommandBuilder.getBuilder(TfsSDKCommandBuilder.java:86)
> 	at com.thoughtworks.go.domain.materials.tfs.TfsCommandFactory.getSDKBuilder(TfsCommandFactory.java:43)
> 	at com.thoughtworks.go.domain.materials.tfs.TfsCommandFactory.getTfsSdkCommand(TfsCommandFactory.java:38)
> 	at com.thoughtworks.go.domain.materials.tfs.TfsCommandFactory.create(TfsCommandFactory.java:32)
> 	at com.thoughtworks.go.config.materials.tfs.TfsMaterial.tfs(TfsMaterial.java:170)
> 	at com.thoughtworks.go.config.materials.tfs.TfsMaterial.updateTo(TfsMaterial.java:164)
> 	at com.thoughtworks.go.domain.MaterialRevision.updateTo(MaterialRevision.java:146)
> 	at com.thoughtworks.go.domain.materials.AbstractMaterialAgent.prepare(AbstractMaterialAgent.java:43)
> 	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:176)
> 	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:126)
> 	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:82)
> 	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:54)
> 	at com.thoughtworks.go.agent.AgentHTTPClientController.retrieveWork(AgentHTTPClientController.java:134)
> 	at com.thoughtworks.go.agent.AgentHTTPClientController.work(AgentHTTPClientController.java:109)
> 	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:85)
> 	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:273)
> 	at org.springframework.scheduling.support.MethodInvokingRunnable.run(MethodInvokingRunnable.java:65)
> 	at org.springframework.scheduling.timer.DelegatingTimerTask.run(DelegatingTimerTask.java:70)
> 	at java.util.TimerThread.mainLoop(Timer.java:555)
> 	at java.util.TimerThread.run(Timer.java:505)

**OS**: Windows Server 2012 R2 Standard (build 9600)
**Go version**: 18.5.0 (6679-a54c3fd44ef9ccbab1b0d856a8d735929eab97f7)

Not sure if I should open a separate issue.
