### ISSUE TITLE
Can not login using LDAP authentication if CN contains /

### ISSUE THREAD

**Issue by lenucksi** [gocd/gocd#1995]
##### Issue Type
- Bug Report
##### Summary

As a user using the LDAP authentication mechanism in Go 15.3.1 I can not login if my LDAP CN contains a "/".
###### Basic environment details

Go Version: 15.3.1
JAVA Version: OpenJDK 7
OS: CentOS 6
##### Steps to Reproduce

Connect Go to an LDAP containing the "/" character in a number of CNs.
Try to login with an account containing a "/" in the CN. It will not work.
Try to login with an account without a "/" in the CN. It will work.
##### Expected Results

Login should work independent of the presence of non-presence of "/" characters in the CN.
##### Actual Results

Login did not work in the presence of a "/" character in the CN.
##### Log snippets

Stacktrace show this unique element:

```
2016-02-16 08:52:16,689 ERROR [qtp1952645646-26] AuthenticationProcessingFilter:54 - Failed to parse DN; nested exception is org.springframework.ldap.core.ParseException: Encountered "\"" at line 1, column 1.
Was expecting one of:
    <ATTRIBUTE_TYPE_STRING> ...
    <LDAP_OID> ...
    " " ...
    ; nested exception is org.springframework.ldap.BadLdapGrammarException: Failed to parse DN; nested exception is org.springframework.ldap.core.ParseException: Encountered "\"" at line 1, column 1.
Was expecting one of:
    <ATTRIBUTE_TYPE_STRING> ...
    <LDAP_OID> ...
    " " ...

```
##### Any other info

The problem may be related to the usage of an old Spring LDAP / Spring Security version.
There are bug records related to similar behaviour here:
- https://github.com/spring-projects/spring-ldap/issues/93
- https://github.com/spring-projects/spring-ldap/issues/148

Spring LDAP 1.2.1 is currently used in Go, where as the similar Bugs have been fixed starting with 1.3.0RC.

**Comment by arvindsv** [comment]
Closing. The new plugin [uses apache ds](https://github.com/gocd/gocd-ldap-authentication-plugin/blob/a927bedacad890cf49121b6984c8754b56f23386/build.gradle#L103) and if this is still happening and relevant, please reopen an issue in the repo of that plugin. Thank you!
