### ISSUE TITLE
How get commit(s) that caused pipeline launch?

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [gocd/gocd#2001]
I'm using gocd continious delivery tool + git. My project consists of many subprojects. I don't want to rebuild all subprojects on each commit and thus created one pipeline for each subproject. I know, that for each pipeline, say for project1, I have to choose appropriate working dir and run smth like that:

1. get git commits which triggered gocd build.

2. for each commit - detect whether changes in that commit affected pipeline's working dir

3. If some subproject affected by commit run custom build command for approproiate pipeline.

Looks like I may resolve questions # 2,3 by some simple bash script involving git commands but what about  question # 1?

I thought I may use **git's latest commit but not sure it's correct** in case of many concurrent commits, that's why I want to get it directly from gocd.

Also asked [here](http://stackoverflow.com/questions/35642784/how-get-latest-commit-from-gocd-and-detect-did-it-change-some-specific-folder)

**Comment by jyotisingh** [comment]
To answer your first question, Go publishes a few environment variables which contains information about which what range of commits/revisions for each of the materials involved were being used for the run of pipeline. These environment variables are named based on your materialName, so a git material named as `foo` would lead to the following environment variables to be generated:
`GO_TO_REVISION_FOO` and `GO_FROM_REVISION_GOCD`. These would be passed along to the agent that picks up your job. 


I am closing this issue as this is a question and not an issue report. Please use mailing list (https://groups.google.com/forum/#!forum/go-cd) to ask questions.

**Comment by BaurzhanSakhariev** [comment]
Thank you!

**Comment by johnnywidth** [comment]
I have Go Version: 17.7.0, when pipeline is running i see GO_TO_REVISION and GO_FROM_REVISION env, but they're the same
