### ISSUE TITLE
Expose additional agent states via API

### ISSUE THREAD

**Issue by ashwanthkumar** [gocd/gocd#2004]
##### Issue Type

Feature proposal
##### Summary

Today couple of states of the agent is not exposed via [/go/api/agents](https://api.go.cd/current/#get-all-agents).

The following states needs to be exposed via the API
- Assigned
- Preparing

**Comment by arvindsv** [comment]
@andreybleme I don't have any objections to it. I remember some conversations around this with @ketan, who might know better. Thoughts, @ketan?

Just FYI, you can also ask the agent directly, whether it is connected to the server, now. See [this API method](https://api.gocd.org/current/#agent-health), for the _agent side_.
