### ISSUE TITLE
Agent API could not enable/disable agent or update environments

### ISSUE THREAD

**Issue by yoroto** [gocd/gocd#2007]
##### Issue Type
- Bug Report

##### Summary
I tried to use the agent API to approve a registered pending agent by setting the _agent_config_state_ attribute of it. However, it did not work. Even after I manually enabled/approved it through UI, the API still can only set the _resources_ attribute, but not _agent_config_state_ and environments.

###### Basic environment details

Go Version: 16.1.0-2855 running on Linux

JAVA Version: OpenJDK 1.7.0_91

OS: 3.8.13-98.5.2.el7uek.x86_64

##### Steps to Reproduce
Install a new agent on a client, and connect it to the GoCD server.
The new agent appears to be PENDING in the GoCD server UI.
Calling the API to update agent as documented in https://api.go.cd/current/#update-an-agent with the following value:
    { 'agent_config_state': 'Enabled', 'environments': 'NF1', 'resources': ['test_agent', 'test_rig'] }
Nothing happened. The agent was still pending.
Manually enabled the agent, and then call that API again. The resources tags had been added to the agent, but the environment has not been changed (it dose exist.).
Tried to disable to the agent through API by sending:
    { 'agent_config_state': 'Disabled' }
The agent was still enabled.
##### Expected Results
Should be able to approve a PENDING agent and update _agent_config_state_ and _environments_ attributes through API.

##### Actual Results

Could not approve a PENDING agent nor update _agent_config_state_ and _environments_ attributes through API.

##### Code snippets/Screenshots
headers = {'Accept': 'application/vnd.go.cd.v1+json'}
r = requests.get('http://goserver:8153/go/api/agents', headers=headers, auth=HTTPBasicAuth('user', 'password'))

print(r.cookies['JSESSIONID'])
for agent in json.loads(r.text)['_embedded']['agents']:
    if agent['uuid'] == 'd190574a-9f8f-4f7c-aedc-106d103718fb':
        print(agent)
        update_url = 'http://goserver:8153/go/api/agents/' + agent['uuid']
        update_headers = { 'Accept': 'application/vnd.go.cd.v1+json', 'Content-Type': 'application/json' }
        update_data = { 'agent_config_state': 'Enabled', 'environments': 'NF1', 'resources': ['test_agent', 'test_rig'] }
        update_cookies = { 'JSESSIONID': r.cookies['JSESSIONID'] }
        p = requests.patch(update_url, headers=update_headers, data=json.dumps(update_data), cookies=update_cookies)

**Comment by ketan** [comment]
> Code snippets/Screenshots
> 
> headers = {'Accept': 'application/vnd.go.cd.v1+json'}
> r = requests.get('http://goserver:8153/go/api/agents', headers=headers, auth=HTTPBasicAuth('user', 'password'))

Setting those attributes is supported in `v2` of the api. You seem to be using `v1`.

I'm going to close this issue, but please re-open if you think it's still not working.

**Comment by yoroto** [comment]
Shall I use 'application/vnd.go.cd.v2+json' to call V2?

**Comment by yoroto** [comment]
Yes, it is working now after I changed it to
'application/vnd.go.cd.v2+json'. Thanks!

Letu
