### ISSUE TITLE
Add feature to enable/disable Tasks

### ISSUE THREAD

**Issue by Matrikss** [gocd/gocd#2015]
##### Issue Type
- Feature proposal
##### Summary

Sometimes, during development, we have the use case where we want to temporarily disable a specific Task.

Currently, one of the ways to do this is:
1. Go to the configuration XML
2. Save the Task we want to skip somewhere else
3. Remove it
Then we have to put it back in a similar process.

It would be very useful to have a way to simply disable the Task directly in the pipeline's tasks configuration screen.

**Comment by siulung4073** [comment]
+1

**Comment by veeramanikandanvv** [comment]
It would be a great feature if we have disable feature in the task level and selected tasks for execution
