### ISSUE TITLE
Subversion externals get polled when material is not set to be polled

### ISSUE THREAD

**Issue by d-led** [gocd/gocd#2018]
##### Issue Type
- Bug Report
  or
- Feature enhancement
##### Summary
- There's a subversion material, which has externals
- Polling the material is turned off
- When "Check Externals" is turned on, the externals get polled, which is undesirable
- The pipeline is configured for automatic scheduling

In an attempt to mitigate for that, I've tried turning off automatic scheduling, which then breaks the REST API - the material update doesn't happen. For now I'm fine with automatic scheduling, and "Check Externals" turned off, but then the externals do not show up in the value stream map (not crucial).

I think, this could be a bug that the externals are polled when material polling is turned off. Unless someone has a use case for that, in which case, it should probably be configurable.
###### Basic environment details

Go Server Version:  16.2.1(3027-07834a1f2ce79a13d42b03601698ef48f128a012)
JVM version:    1.8.0_66-internal
OS Information: Linux 4.2.0-25-generic
Usable space in artifacts repository:   18.5 GB
Database schema version:    1503002

**Comment by d-led** [comment]
I tried to find the relevant bit in the code, and then tried reading a bit on the [MDU](https://developer.go.cd/current/4/4.2.html#423-material-update-sub-system), but am not yet successful. Could anyone perhaps point me to code responsible for polling svn externals? Or, perhaps, for the configuration of polling for externals?

**Comment by arvindsv** [comment]
Not exactly sure what you need, but I'd look at [this](https://github.com/gocd/gocd/blob/272051917395f22e4c6148399e0c32b00076b4c4/server/src/com/thoughtworks/go/server/service/MaterialExpansionService.java#L74-L86).

**Comment by arvindsv** [comment]
In MDU, it seems to be used [here](https://github.com/gocd/gocd/blob/272051917395f22e4c6148399e0c32b00076b4c4/server/src/com/thoughtworks/go/server/materials/MaterialDatabaseUpdater.java#L132-L140).

**Comment by d-led** [comment]
@arvindsv thanks, will look at it

**Comment by d-led** [comment]
will try to recreate the issue in docker when I get a couple of hours free

**Comment by d-led** [comment]
@arvindsv here's a config that can be used to reproduce the issue: https://github.com/d-led/gocd_svn_playground
checked again:
- pipeline scheduling is on automatic
- materials polling is off
- externals checking is on
&darr;
svn properties get polled.

**Comment by arvindsv** [comment]
@d-led Thank you. I'll take a look soon.
