### ISSUE TITLE
Git material clone with --no-checkout option on server still checks out files

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#2019]
##### Issue Type

- Bug Report

##### Summary

This PR https://github.com/gocd/gocd/pull/1983 even-though added the --no-checkout option still files are checked out on the server

###### Basic environment details

Go Version: 16.3.0(3145-41cb67ad26a6c09dfeb26566ffa775b6f4c0b19b)

JAVA Version: ava version "1.7.0_79"

OS: Mac OS X Yosmite

##### Steps to Reproduce

- Create a pipeline with Git Material
- After the MDU check the flyweight folder
- The folder contains the files from the repo

##### Expected Results

Expected to contain only the .git folder and not the files from the repo

##### Actual Results

Files from repo also checked out

**Comment by wpc** [comment]
@rajiesh: Thank you for verifying this. Turn out gitLog call in GitCommand is checking out working copy unnecessarily. Fixed it with PR with tests missed in original PR.
