### ISSUE TITLE
Cloning git repository reports error in console but seem ok

### ISSUE THREAD

**Issue by agileassistance** [gocd/gocd#202]
When an agent is cloning a git repository it reports errors in console but works fine. This is misleading and should be reported as information or verbose.

Example:

Cloning into 'H:\Go Agent\pipelines\CI-Master'...
ERROR: Checking out files:   0% (27/36858)   
ERROR: Checking out files:   0% (105/36858)   
ERROR: Checking out files:   0% (146/36858)   
ERROR: Checking out files:   0% (157/36858)   
ERROR: Checking out files:   0% (161/36858)   
ERROR: Checking out files:   0% (257/36858)   
ERROR: Checking out files:   0% (258/36858)   
ERROR: Checking out files:   0% (316/36858)   
ERROR: Checking out files:   0% (354/36858)   
ERROR: Checking out files:   1% (369/36858)   
ERROR: Checking out files:   1% (381/36858)   
ERROR: Checking out files:   1% (653/36858)   
ERROR: Checking out files:   2% (738/36858)   
ERROR: Checking out files:   2% (916/36858)   
ERROR: Checking out files:   3% (1106/36858)   
ERROR: Checking out files:   3% (1230/36858)   
ERROR: Checking out files:   3% (1321/36858)

**Comment by arvindsv** [comment]
Closing. No action.
