### ISSUE TITLE
Add new pipeline - materials page do not have shallow clone option

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#2021]
##### Issue Type

- Bug Report

##### Summary

When adding new pipeline from Admin->Pipelines tab on the materials page when selected 'git' as material, 'Shallow Clone' option not available

###### Basic environment details

Go Version: 16.3.0(3145-41cb67ad26a6c09dfeb26566ffa775b6f4c0b19b)

JAVA Version: ava version "1.7.0_79"

OS: Mac OS X Yoasmite

##### Steps to Reproduce

- Go to Admin - > Pipelines tab
- Click on Add new pipleine
- On the materials page select material type as 'git'

##### Expected Results

Checkbox for Shallow clone to be present, as it is present when user navigates to materials edit page from pipeline edit page

##### Actual Results

Shallowclone checkbox not available

**Comment by ketan** [comment]
See #2025
