### ISSUE TITLE
Remove old server/agent communication

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2029]
Placeholder issue to remove old agent/server communication over spring remoting, now that websockets has been merged in (not turned on by default yet)

/cc @xli

**Comment by xli** [comment]
I'll work on this after we turned on websocket by default next release.

**Comment by GaneshSPatil** [comment]
The newer WebSocket based agent-server communication has been removed as part of [this](https://github.com/gocd/gocd/commit/d45efb4d257b72bd0b801824404e785fc873e4de) commit (due to know issues/bugs).
Hence, the existing server-agent communication can not be removed.

Closing...
