### ISSUE TITLE
Shallow Clone on server after an upgrade do not make flyweight folder shallow

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#2030]
##### Issue Type

- Bug Report

##### Summary

During upgrade from 16.2.1 or earlier versions to 16.3.0(with shallow clone feature) the existing flyweight folders remains full clone and does not save space on server as expected by shallow clone

###### Basic environment details

Go Version: 16.3.0-3145(41cb67ad26a6c09dfeb26566ffa775b6f4c0b19b)

JAVA Version:java version "1.7.0_79"

OS: Windows/Centos/Ubuntu (where Go Support upgrade)

##### Steps to Reproduce

- Install Go version 16.2.1 version
- Create a pipeline with Git material
- Check the flyweight folder git history and its full
- Upgrade to 16.3.0(which supports shallow clone)
- After a MDU the flyweight folder is still full repo and the history is full

##### Expected Results

- Expected to delete the working copy and do shallow clone to save disk usage on the server

##### Actual Results

- The flyweight remains with full history

##### Any other info

The same behavior is seen on agents too.

**Comment by ketan** [comment]
@rajiesh — there's no way to "unshallow" an existing repository once it's cloned, we *could* automate this by deleting each flyweight and re-cloning, but that may incur a huge one-time cost at startup.

Something we may want to consider is to document this as something that end users should do while upgrading their go servers, like we did for config repository GC.

/cc @wpc

**Comment by wpc** [comment]
@rajiesh:  As @ketan said there is no good way to do re-clone on demand. For a fully cloned flyweight repository, we can not distinguish whether it is left from old version of Go or it was just automatically unshallowed when user trigged an old build.

Only way doing this is through someone time migrating process. But I am sharing same concern with @ketan that it maybe risky and have big one-time cost.

/cc @arvindsv and @jyotisingh who was on original discussion.

**Comment by arvindsv** [comment]
I agree about leaving it full, and not trying to convert it to shallow.

**Comment by jyotisingh** [comment]
Its not really mentioned on this issue, but I remember @rajiesh pointing out a case wherein the server copy was shallow but not *bare*. Even though the original clone was with no-checkout, there was a reset-hard being done a little later causing all the files to be checked out.

**Comment by ketan** [comment]
> Even though the original clone was with no-checkout, there was a reset-hard being done a little later causing all the files to be checked out.

I think this is a case for using `git clone --bare --depth 1` instead of `git clone --no-checkout --depth 1` :)

**Comment by wpc** [comment]
@jyotisingh 
> Even though the original clone was with no-checkout, there was a reset-hard being done a little later causing all the files to be checked out.

My bad for not doing enough test. Fixed by https://github.com/gocd/gocd/pull/2036.

@ketan 
> I think this is a case for using git clone --bare --depth 1 instead of git clone --no-checkout --depth 1 :)

we do have operation on server side need working copy ConfigMaterialUpdater#updateConfigurationFromCheckout.
