### ISSUE TITLE
Mac agent logs incorrectly documented

### ISSUE THREAD

**Issue by janfabry** [gocd/gocd#2033]
##### Issue Type

- Documentation Report

##### Summary

The [Go Agent docs for Mac OS X](https://docs.go.cd/current/installation/install/agent/osx.html) mention logs in `/var/log/system.log`, but useful logs are actually sent somewhere to the `~/Library/Application Support/Go Agent/*.log` files.

##### Environment
Running the Go agent and trying to debug connection problems.

###### Basic environment details

Go Version: 16.2.1.3027
JAVA Version: 1.8.0_40
OS: Max OS X 11.1

##### Steps to Reproduce
Start the Go agent, check `/var/log/system.log` for output.

##### Expected Results
Some output from the agent.

##### Actual Results
No output :-)

Useful logs are located in `~/Library/Application Support/Go Agent` in the following files:
 - `osx-app.log`: the main log file of the app
 - `go-agent-bootstrapper.log`
 - `go-agent-launcher.log`

I would certainly mention the `osx-app.log` file in the documentation.

**Comment by ketan** [comment]
@janfabry — would you like to submit a PR against the docs repository at http://github.com/gocd/docs.go.cd?

**Comment by arvindsv** [comment]
Hi @janfabry. I've moved this over to: https://github.com/gocd/docs.go.cd/issues/3. Thanks! I've also mentioned the file where the change can be made. If you can submit a PR, that would be great!
