### ISSUE TITLE
Init script - go-server says it's started, but there are still work remaining

### ISSUE THREAD

**Issue by andreitognolo** [gocd/gocd#2034]
##### Issue Type
- Feature enhancement
##### Summary

When I execute `service go-server start` it says "Started Go Server on" but it's still not ready to receive requests. As far as I could see it happens because the [init script](https://github.com/gocd/gocd/blob/eb43d86ebae7fc8d0e5a815a54c6f42b8c66d11d/installers/server/release/init.cruise-server#L81) just check for the process to be listed.

I believe that the right thing to do would be keep waiting until a http request returns 200. Does that make sense?
###### Basic environment details

Go Version: 16.1.0(2855-ada9b36174cc069c860e7fa032cbf2857f135cfb)
JDK: 1.8.0_31-b13
OS: CentOS release 6.6 (Final)
##### Steps to Reproduce

`sudo service go-server start`
##### Expected Results

Expected to be notified the server is up only when it's able to receive http requests.
##### Actual Results

It says "Started Go Server on" but I cannot access using the browser.

**Comment by arvindsv** [comment]
This has been revamped a while ago, with a better loading screen which works properly.
