### ISSUE TITLE
Job reschedules happening multiple time

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#2040]
##### Issue Type
- Bug Report

##### Summary
Job reschedules happening multiple time ~~when websocket communication is turned on~~. This has been spotted on both linux and windows. 
##### Environment

The log files for two such builds can be found in the links below. BTW, since the files are large, opening them from browser might cause your browser to hang. Use curl instead.

https://build.go.cd/go/pipelines/build-windows/784/build-server-windows/1/server-split-runInstance-11/cruise-output/console.log

https://build.go.cd/go/files/build-linux/851/build-server/1/server-split-runInstance-2/cruise-output/console.log

###### Basic environment details
Go Version: 16.3

JAVA Version: 1.7

OS: Linux (server)
Agent OS : both linux and windows

##### Steps to Reproduce
Not sure of the steps to reproduce, but many pipelines on build.go.cd were found to be rescheduled over and over. ~~The situation seems to have come back to normal after websocket was turned off. Since websockets would remain turned off for 16.3, we could defer the fix to 16.4. This is crucial to enable websockets by default.~~

**Comment by jyotisingh** [comment]
Turned out to be an issue with the test. Default constructor of`GoConfigFileHelper`  sets up a config with schemaVersion=6 and then runs xslt migration as well as validation for each of the versions between version 6 and the latest schemaVersion ie.81 as of now. Need to fix the tests. This is NOT a bug in the application.

**Comment by zabil** [comment]
There are two parts to this issues

* The mount of logs our tests generate
* The way we parse out test results

The first part the problem as @jyotisingh pointed out is with our [fixture](https://github.com/gocd/gocd/blob/6556eae0b6501e605d3acb0832cf8b4cf0e321e7/config/config-api/test/com/thoughtworks/go/helper/ConfigFileFixture.java). When using these fixtures we run our [migrations](https://github.com/gocd/gocd/blob/6556eae0b6501e605d3acb0832cf8b4cf0e321e7/config/config-server/src/com/thoughtworks/go/config/GoConfigMigration.java#L202) causing the dreaded 

```
[junit]   WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
[junit] Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
[junit] Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[junit] Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
```

to flood our logs. We need to upgrade the fixtures wherever necessary to the latest version. We must also fix our use of xerces to stop the warnings.

The second part to the problem happens [here] (https://github.com/gocd/gocd/blob/6556eae0b6501e605d3acb0832cf8b4cf0e321e7/config/config-api/src/com/thoughtworks/go/domain/UnitTestReportGenerator.java#L169) when we load the entire xml file (in our case a 20-30 mb file) to check validity and evaluate xpath blowing up the memory causing the agent to bomb and server to reschedule. We need to fix this maybe using stream parsing to check validity and a regex for tags.

**Comment by zabil** [comment]
Time savings before and after fixing one of the fixtures

Before:
![screen shot 2016-03-10 at 4 21 57 pm](https://cloud.githubusercontent.com/assets/54427/13667505/b3adc10a-e6dc-11e5-91e2-7f1292b1e6dc.png)

After:
![screen shot 2016-03-10 at 4 23 52 pm](https://cloud.githubusercontent.com/assets/54427/13667513/c0427014-e6dc-11e5-937a-8676948f6779.png)

**Comment by ketan** [comment]
:)

**Comment by zabil** [comment]
Finally, another breakthrough.

say good bye to 

```
[junit]   WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
[junit] Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
[junit] Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[junit] Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
```

When you set the following properties on startup up

```
        System.setProperty("javax.xml.parsers.DocumentBuilderFactory",
                "org.apache.xerces.jaxp.DocumentBuilderFactoryImpl");
        System.setProperty("javax.xml.parsers.SAXParserFactory",
                "org.apache.xerces.jaxp.SAXParserFactoryImpl");
        System.setProperty("javax.xml.transform.TransformerFactory",
                "org.apache.xalan.processor.TransformerFactoryImpl");
```
 
and add Xalan to your pom

```
        <dependency>
            <groupId>xalan</groupId>
            <artifactId>xalan</artifactId>
            <version>2.7.2</version>
        </dependency>
```

This means not using the internal ```com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl``` Xalan for xslt transformation, when on a newer version of xerces.

**Comment by zabil** [comment]
Log generation problem is fixed.

https://github.com/gocd/gocd/issues/2160 opened to follow up on memory efficient way of parsing test results.
