### ISSUE TITLE
Include Notification and Authentication plugin in Plugin list API

### ISSUE THREAD

**Issue by juhijariwala** [gocd/gocd#2041]
##### Issue Type

- Feature enhancement
##### Summary

[This](https://github.com/gocd/gocd/issues/1873) API list only SCM, Package Repository and Task Plugins. Enhance the existing API to support Notification and Authentication Plugin. 
##### Any other info

**Structure:**
URL: https://ci.example.com/go/api/admin/plugins/[notification/authentication] ```

JSON response for Notification/Authentication plugin list:

``` json
      {
        "_links": {
          "self": {
            "href": "http://localhost:8153/go/api/admin/plugins/notification/gitter.notifier"
          },
          "doc": {
            "href": "http://api.go.cd/#plugins"
          }
        },
        "plugin_id": "gitter.notifier",
        "version": "1.2.3",
        "type": "notification",
        "configurations": { }
      }
```

Note: Since Notification and Authentication plugin do not have configurations, we show empty hash for configuration.

**Comment by arvindsv** [comment]
Is it an enhancement, or a bug? :)

**Comment by juhijariwala** [comment]
It is feature enhancement.

**Comment by GaneshSPatil** [comment]
This issue has been fixed via [Plugin Infos](https://api.gocd.org/current/#plugin-info) API.
