### ISSUE TITLE
Cancelation of a waiting stage, cancel another running job on Agent

### ISSUE THREAD

**Issue by patrick92100** [gocd/gocd#2048]
- Bug Report

Cancelation of a waiting stage, cancel another running job on Agent
##### Environment

pipeline1/stage1/job1 is running on AGENT1

pipeline2/stage2/job2 with 'Run on all agents' checked is triggered, 
the job2 is executed on AGENT2, AGENT3...it remains in waiting state for AGENT1, waiting pipeline1/stage1/job1 to finish
##### Actual Results

On pipeline2/stage2 cancelation, the Pipeline1/stage1/job1 is canceled on AGENT1, the pipeline2/stage2/job2 is canceled on AGENT1
##### Expected Results

On pipeline2/stage2 cancelation, pipeline2/stage2/job2 is canceled on AGENT1 and Pipeline1/stage1/job1 continues on AGENT1

**Comment by zabil** [comment]
Before we take a look at this, please provide the following info

Go Version:
JAVA Version:
OS:

**Comment by patrick92100** [comment]
Server
Go Version: 16.2.1-3027
JAVA Version:jdk1.7.0_40
OS:CentOS 5.5

**Comment by GaneshSPatil** [comment]
This issue is reproducible on GoCD v19.10.0

**Comment by rajiesh** [comment]
Verified on  19.11.0 (10685-a26556d1f0e02fa2859d8996fa95b1c5731ec4dd)
