### ISSUE TITLE
Environment name gets set as resource tag on agent

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2059]
##### Issue Type
- Bug Report
##### Summary

When selecting and agent assigned to an environment, then clicking on the environment dropdown, then on the resource dropdown, selecting a resource and adding it, the production name is set as resource tag as well.
###### Basic environment details

Go Version:
16.2.1

JAVA Version:
openjdk 8 

OS:
debian jessie
##### Steps to Reproduce
- go to agent page
- select an agent already attached to an environment
- open environment dropdown
- open resource tag dropdown
- select resource tag
- click apply
##### Expected Results

Only the selected tags are added to the agent
##### Actual Results

The environment name is added as resource tag as well

**Comment by ashokgowtham** [comment]
I'm facing this as well. Reproducible consistently.

**Comment by zabil** [comment]
Check this on https://github.com/gocd/gocd/pull/2406

**Comment by GaneshSPatil** [comment]
This issue has been fixed as part of the new agents SPA.
Closing...
