### ISSUE TITLE
GoCD DSL?

### ISSUE THREAD

**Issue by djoos** [gocd/gocd#2064]
##### Issue Type

- Feature

##### Summary

Is there a DSL (~ Jenkins' Groovy DSL) available to script the setup of pipelines in GoCD?

##### Expected Results

It would be great to allow a feature like that to allow us to script up our pipelines, as we are currently doing for our (legacy) Jenkins jobs - even if we were to reimage the Jenkins node, we just reprovision it and we're back up and running without any manual setup.

##### Actual Results

It seems the only way to put pipelines together is by either doing it manually or via a template, or am I looking into the wrong place?

##### Any other info

Thanks in advance for your feedback!

Kind regards,
David

**Comment by ashokgowtham** [comment]
You can edit the configuration xml directly without needing to configure using the go gui.
Just go to Admin --> config xml --> edit
Edit the xml, put it back again and save it.
This helped me modify the configuration at a larger scale, using favourite editor.

There are also tools like [gomatic](https://github.com/SpringerSBM/gomatic) that allow us to generate the go's config xml from code.
It should be simple to have a DSL over these APIs.

**Comment by djoos** [comment]
Hi @ashokgowtham,

thanks for your reply!

Directly editing the XML is not really a "coded option", however indirectly via [gomatic](https://github.com/SpringerSBM/gomatic) sounds interesting - I'll have a further look at that project!

Kind regards,
David

**Comment by robsonpeixoto** [comment]
With jobdsl is possible to run any groovy code and is possible, for example, discover for any github repository that contains a `jobs.groovy` file and create the the job and configure the push hook.
So, if something get wrong I can restore all job/pipelines in one click.

Are there plans to add this kind of feature?

**Comment by arvindsv** [comment]
The config repo endpoint is used to write the [JSON](https://github.com/tomzo/gocd-json-config-plugin) and [YAML](https://github.com/tomzo/gocd-yaml-config-plugin) plugins. This endpoint should allow anyone to write a plugin which can do anything, as long as it gives back a pipeline definition. However, I am not aware of anyone who is writing a groovy-dsl like plugin. Not that it cannot be done.
