### ISSUE TITLE
Incorrect disk space warnings when plenty of space is present

### ISSUE THREAD

**Issue by aliensojurner** [gocd/gocd#2065]
##### Issue Type

- Bug Report
  ##### Summary

I am getting the normal 'This server has stopped scheduling because it has less than 100Mb of disk space available at F:\cruise-artifacts to store artifacts' error message. The problem though, is that F: has 570GB of free space out of a 1TB drive. It only stores artifacts. We have also gotten errors about the DB, and in a similar fashion, there are hundreds of gigs available on C:\

I am trying to figure out why we are getting these errors when there is a large amount of space on each drive no where near close to the amount needed for GO to send that error out.

I do not want to turn off the option to delete artifacts. I want the drive to fill with new artifacts and then clean up when the drive gets full.....My problem is that I'm getting errors when I should not be based on the available storage on my drives. 
###### Basic environment details

- Go Version: `16.1`
- JAVA Version: `1.7`
- OS: `Windows 7 Pro 32bit`
- Browser vendor and version (if relevant): `not sure`
###### Additional Environment Details

None. App supplied in main description. 

-->

**Comment by aliensojurner** [comment]
[go support output.txt](https://github.com/gocd/gocd/files/174415/go.support.output.txt)

Not sure why this didn't attach to the original

**Comment by aliensojurner** [comment]
Has anyone at all ever had this issue?

**Comment by ketan** [comment]
Closing as dup of #2797.
