### ISSUE TITLE
Feature Proposal - Option to allow agents to remove old builds from their working directory

### ISSUE THREAD

**Issue by dmcniven** [gocd/gocd#2070]
##### Issue Type

Feature proposal (Implemented)
##### Summary

When you have many pipelines >400, GO Agents quickly consume all their disk space as the data from previously built pipelines remain disk.
This feature will provide a Purge Agents Working Directory option that will delete the previous pipeline data from the agent before starting the new job.
##### More Information

Our feature adds a 'Purge Agent Working Directory' checkbox to the Stage Settings tab as shown below:
![new_purge_agent_option](https://cloud.githubusercontent.com/assets/12992523/13869544/1787e090-ed2a-11e5-96a7-131899158b88.png)

Enabling this option updates the config.xml with the following value:
`<stage name="my_stage" purgeWorkingDir="true">`

To demonstrate the functionality, 4 pipelines were built with out the 'Purge Agent Working Directory' option selected. After building had completed, the following folders were left on the agent:
![folders_before_purge](https://cloud.githubusercontent.com/assets/12992523/13869548/21b794b6-ed2a-11e5-8e97-6c71168c4018.png)

The working directory of the Go Agent after enabling the 'Purge Agent Working Directory' option and re-triggering all the pipelines is shown below. You can see that it only leaves the data of the most recent job on the agent.
![folders_after_purge](https://cloud.githubusercontent.com/assets/12992523/13869557/26e31898-ed2a-11e5-901d-69705d3d8369.png)

I have implemented the changes needed to support this feature, however I am having difficulty trying to run the tests for the gocd project. The 'go-development-environment-setup' project doesn't seem to work, failing with a chef error.

Manually testing indicates the changes seem to work correctly.

Is there any interest in the community to have this feature mainlined? If so, can you please advise how to best proceed with sufficiently testing the code.

Thanks,
-Dean

**Comment by ketan** [comment]
> Is there any interest in the community to have this feature mainlined?

I like this feature, I do see a lot of value in it. I'm not sure that purging everything else on the agent, all the time is a good solution. Checking out code afresh on agents can be a very demanding operation (both, on agents in terms of disk and network IO, and on the git/svn/hg/whatever server). This problem worsens when there are several jobs with `runInstanceCount` set on them. We've seen quite a few cases where users have had to go to great lengths to improve performance of checkout/update operations.

Possible alternatives, that I can think of —
*  Do something similar to how purging works on the server end, by specifying a `purgeStart` and `purgeEnd` attributes.
    ![screen shot 2016-03-18 at 9 24 15 am](https://cloud.githubusercontent.com/assets/10598/13868046/344aed1a-eceb-11e5-888b-f7d8c95c69b4.png)
* Button on the admin page that allows admins to request purging of working dir on specific (or all) agents
* Performing a "clean" like operation to get rid of generated code, like how we on startup for [git](https://github.com/gocd/gocd/blob/3981000187df0d7693226e7efbfdafc3663e726f/common/src/com/thoughtworks/go/domain/materials/git/GitCommand.java#L137-L147), [svn](https://github.com/gocd/gocd/blob/cb38b60c743707fca73a2b578a6d437f8f154576/common/src/com/thoughtworks/go/domain/materials/svn/SvnCommand.java#L198-L203) and others from [this method](https://github.com/gocd/gocd/blob/50fa9dc0ed23b9c9e505c992824ad397e9756812/common/src/com/thoughtworks/go/config/materials/ScmMaterial.java#L89-L89)

I'm sure there are other solutions to this problem that people have thought about. Perhaps you'd like to ask on the forums to see what others may think of it or if they have other solutions?

**Comment by arvindsv** [comment]
Might be worth restarting [this discussion](https://groups.google.com/d/topic/go-cd/fhlYvVcg5H4/discussion).

**Comment by ketan** [comment]
> The 'go-development-environment-setup' project doesn't seem to work, failing with a chef error.

I can see that you're running on linux. Your best bet is to install a (preferably) 1.7 JDK, nodejs, maven (latest) and intellij, and run `./bn clean cruise:prepare SKIP_WAR=Y`, followed by running `DevelopmentServer`

The 'go-development-environment-setup' instructions and setup is currently unmaintained.

**Comment by dmcniven** [comment]
Thanks for the feedback,

> I can see that you're running on linux. Your best bet is to install ...

I'll definitely try to get the tests running with those instructions.

> I like this feature, I do see a lot of value in it. I'm not sure that purging everything else on the agent, all the time is a good solution

I'll have to have more of a think about how to incorporate the deletion functionality in a way that doesn't expose users to the high clone cost.

**Comment by ketan** [comment]
Should you have any questions about the code, you can ask on gitter.im/gocd/gocd and someone should be able to sort you out. Most of the team is located in India (GMT+05:30), so that you know when to expect a response.

**Comment by FredrikWendt** [comment]
For git and mercurial, if you'd keep the `.git` or `.hg` folders, cloning/pull updates would be pretty fast. The local checkout may still take some time, but is hopefully acceptable.

**Comment by FredrikWendt** [comment]
Another option is to use elastic agents, or schedule a pipeline every hour that runs on each agent, which cleans the workspace up (or creates a new agent, and then terminates itself - this works pretty fine with Docker).

**Comment by ketan** [comment]
If there's enough interest in this feature, the team will be happy to work with willing whoever is looking to implement this.
