### ISSUE TITLE
Agent side git repo get unshallowed unnecessarily

### ISSUE THREAD

**Issue by wpc** [gocd/gocd#2071]
##### Issue Type

- Bug Report

##### Summary

Current git shallow clone implementation has a issue on agent side. After initial build on agent with  shallow clone, the following build on same agent will unshallow the local repository unnecessarily there is new changes pushed to remote git repository. This kind of defeat the purpose of shallow cloning.  

###### Basic environment details
* Go Version: current trunk

##### Steps to Reproduce

1.  Setup a pipeline with git material and shallow clone 
2.  Trigger first build
3.  Confirm repository cloned in agent working dir is shallow (git log show history is truncated)
4.  Push some changes to remote repository
5.  Check repository cloned in agent working dir is shallow

##### Expected Results
The repo should remain shallow.

##### Actual Results
The repos get unshallowed.

**Comment by ketan** [comment]
Reopening since it got closed automatically without QA

**Comment by rajiesh** [comment]
@wpc tested this fix on 16.3.0-3180(43dcad149f348aada3f38189e0fa7b983403c02f). The observation was that the repo cloned on agent remains shallow, but the git log history continues to grow from the commit it was first shallow cloned on that agent as many more checkins on to the repo and the pipeline is run again on the same agent. Can we maintain the depth at 2?

**Comment by ketan** [comment]
>Can we maintain the depth at 2?

AFAIK, this is not permitted by git (as yet).

**Comment by ketan** [comment]
Fat fingered, the intension of shallow clone is to reduce the cost of the initial clone, subsequent fetches behave like normal fetches and will pull subsequent history.

Ideally what we'd want is some other means keep disk space in check on agents (#2070, #2047)

**Comment by wpc** [comment]
@rajiesh 
thanks for testing it.

> Can we maintain the depth at 2?

As @ketan said, it is not possible without re-clone the repo. 
And for the disk space concerning, normally there is no big difference for couple of thousands commits.

-- wpc

**Comment by JorritSalverda** [comment]
This happens when Clean Working Directory is checked as well. I would say that's an initial clone, not a subsequent fetch, is it?

**Comment by wpc** [comment]
@JorritSalverda , 
> This happens when Clean Working Directory is checked as well.

by "This" do you mean the unnecessarily unshallowing bug, or just shallow clone feature? If later, yes, in "Clean Working Directory" case shallow clone can save a lot of cost. If you observe a bug, please let me know.

**Comment by JorritSalverda** [comment]
I meant the unnecessary unshallow bug.

**Comment by jyotisingh** [comment]
@JorritSalverda - unnecessary unshallow bug has been fixed as a part of https://github.com/gocd/gocd/pull/2072 which went out in 16.3, so it shouldn't happen. 
I think we should close this issue unless @rajiesh and @wpc think otherwise.

**Comment by JorritSalverda** [comment]
I'm running 16.3.0, I thought I saw it there, but can't find it right now. I'll keep an eye on it to see if it doesn't surface in some obscure scenario :)

Thanks for implementing shallow clones, it speeds things up by a large margin.
