### ISSUE TITLE
build.go.cd => credentials changed?

### ISSUE THREAD

**Issue by timoa** [gocd/gocd#2073]
##### Issue Type

- Bug Report

##### Summary

I use the http://build.go.cd server to provide a demo to my mobile app "CI Remote for GO" but I just saw that the credentials change (view/password).

I don't know if it's an issue with the authentification or if you have to remove this account.

I need to know if I need to remove this access (demo mode) from my mobile app soon as possible.

###### Basic environment details

* Go Version: 16.3.0(3178-b9741c2e994d09b65debe5d836aa428fd928e6db)
* JAVA Version: I don't know
* OS: I don't know

##### Steps to Reproduce

1. Connect to https://build.go.cd
2. Use the view / password credentials
3. You will get this message: "Your account has been disabled by the administrator" 

##### Expected Results
Login to the build.go.cd Go Server

##### Actual Results
Can't connect...

##### Any other info

**Comment by zabil** [comment]
@timoa Sorry about that, we are doing some house cleaning. 
Some of the functionalities on the site will be affected during this. We expect things to be back up by March 22nd.

**Comment by zabil** [comment]
@timoa the view user has now been enabled.

**Comment by timoa** [comment]
@zabil Thank you! It works again :)

If you need to remove this account, just let me know to find another way to give access to a Go Server demo from my mobile app.
