### ISSUE TITLE
accessing git freezes

### ISSUE THREAD

**Issue by mkuger** [gocd/gocd#2075]
##### Issue Type
- Bug Report
##### Summary

Checking connection to and cloning a git material doesn't return. Cloning the git repo as the go user on the machine works as expected. The repo is accessed using ssh.
##### Environment

gocd 16.2.1 in a docker container. See attached output of /go/api/support: [environment.txt](https://github.com/gocd/gocd/files/187410/environment.txt)
A proxy is configured using environment variables:
http_proxy=http://proxy:3128
https_proxy=http://proxy:3128
no_proxy=127.0.0.1,localhost

Git repo is also accessible without using the proxy.

**Comment by arvindsv** [comment]
Closing. Please reopen after checking whether this is an issue on a newer release. Thanks.
