### ISSUE TITLE
Integrate Artifactory's CI Support

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#2077]
##### Feature proposal

With three competitor products to GoCD, Artifactory provides integration which allows uploading artifacts, build environment info, bill of materials and more. Today, in order to accomplish similar feature set with GoCD+Artifactory (or Nexus), we need to write all the tooling ourselves (as GoCD's own artifact handling is inadequate on too many levels to be feasible), and thus all GoCD users will need to re-invent the wheel.

https://www.jfrog.com/artifactory/features/#addon-build
https://www.jfrog.com/article/continuous-integration-systems/

**Comment by christer79** [comment]
+1

**Comment by BrewRunner** [comment]
+1

**Comment by jcapitao** [comment]
+1

**Comment by chrislovsund** [comment]
+1

**Comment by sriramnrn** [comment]
See : https://groups.google.com/forum/#!topic/go-cd/4JY1DFGqHD4

On Fri, Apr 22, 2016 at 2:15 AM, Christian Lövsund <notifications@github.com

**Comment by FredrikWendt** [comment]
@sriramnrn That looks like a nice plugin, but doesn't really solve the problem I'm after with this integration.

For a fully integrated solution, downstream jobs should also be able to fetch artifacts in a predictable way from Artifactory. Today you can specify artifacts in the job configuration (pipeline config), and artifacts will be uploaded to the GoCD server. The Fetch Artifacts task can then be used to fetch artifacts. There's some duplication of effort though, as you need to specify your binary/artifact dependency handling in at least two, typically three or even four, locations:

* A) optional, but very common: the upstream job's gradle/maven/build tool typically can figure out what binaries/artifacts will be produced, or your specify this manually (ant)
* B) mandatory: pipeline configuration in GoCD specifies artifacts to manage
* C) mandatory: downstream pipeline configuration(s) in GoCD, specifies artifacts to download - possibly (probably) duplicated for each downstream pipeline
* D) optional but very common: the downstream job's gradle/maven/build tool typically lists upstream artifact dependencies

The plugin at https://github.com/tusharm/go-artifactory-plugin, is an alternative way to accomplish B. It provides a build tool agnostic way to publish artifacts to Artifactory: instead of depending on maven, gradle, ant, bash+curl,... to publish binaries to Artifactory, this plugin allows you to marry even deeper into your CI/CD tool, ie depend on GoCD instead of the build tool. (You essentially marry the publishing of your artifacts to GoCD, you can no longer reproduce this with another tool (Bamboo, Jenkins) or from command line. This is a "bad design" according to some, or at least a technical debt as you gain some speed now, but may have to pay back once you want to migrate to a new CI/CD tool.)

### Proposition

A plugin (or core GoCD) should provide a way to solve C:
* artifacts are stored in Artifactory instead of on the GoCD server
* a new Fetch Artifacts Task is provided, which downloads all the artifacts produced in the upstream Pipeline, automatically - no need to duplicate information about what artifacts should travel from upstream to downstream

### Considerations:

* Thought: for the uploading/managing of artifacts: this information of what artifacts to store, should be picked up from the build tool used (such as Gradle).
* Thought: for the downstream managing of artifacts: the information of what artifacts where pulled/downloaded, are made available to the build too used, if needed (say I want to update my pom.xml file with all the "versions" I just pulled from the upstream Pipeline).

What I'm picturing in my mind is really two plugins:
* a build tool specific plugin, which when enabled, asks the build tool (such as Gradle) for a list of artifacts, and uses this information to tell GoCD "hey, these are some artifacts/binaries to manage from this build"
* a Binary Repository Manager (such as Artifactory) specific plugin: which receives information from the above plugin, and uploads the artifacts to the BRM. The same plugin can also be feed with the same information, but in a downstream job, and use that information to fetch artifacts from the BRM.
* core GoCD would simply have to remember the information from these two plugins, which can then be used in downstream jobs, and manage which plugins are enabled per pipeline.

The out-of-the-box abilities of GoCD could then be implemented as two plugins, shipped by default, enabled by default, and thus be backwards compatible.

**Comment by BrewRunner** [comment]
+1

Very well put!!  This is exactly the kind of functionality I'd like to see.

**Comment by reidca** [comment]
This looks like a great feature request

**Comment by JobyBett** [comment]
+1

**Comment by sglyzewski** [comment]
@FredrikWendt - Did you ever find a solution to deploying artifacts from Artifactory to Go CD?

**Comment by akshaydewan** [comment]
GoCD introduced the concept of [Artifact Plugins](https://plugin-api.gocd.org/current/artifacts/) some time back. Would someone like to take a stab and see if a plugin can be implemented for Artifactory?
