### ISSUE TITLE
Support whitelist and/or blacklist for pipeline dependencies

### ISSUE THREAD

**Issue by BrewRunner** [gocd/gocd#2081]
**Issue Type**

Feature proposal

**Summary**

Would like to have the ability to blacklist pipelines that are dependencies for downstream pipelines.  This would provide the ability to selectively trigger based on changes in the material list instead of constantly triggering as a result of any dependent pipeline which completes.

For example, If pipeline X has a material list containing pipelines A, B, and C (because it requires artifacts from those pipelines) and an SCM material list:

A ---------------+------------------ X
B ---------------+
C ---------------+
SCM -----------+

I'd like to ignore runs of pipelines A, B, and C and only trigger if the SCM material list changes.

OR

Only trigger if the SCM material list changes or pipeline B completes, only ignoring pipelines A and C.

**Comment by BrewRunner** [comment]
Any interest on this front?  I see this as adding similar functionality as the SCM whitelist feature just released with 16.6 and the preexisting SCM blacklist feature.

**Comment by arvindsv** [comment]
Since 19.10, it is now possible to control whether a dependency material causes a trigger.
