### ISSUE TITLE
Slow and sometimes unresponsive

### ISSUE THREAD

**Issue by Aaronov** [gocd/gocd#2082]
##### Issue Type
- Bug Report
##### Summary

With a farm of around 30 agents the Web UI eventually becomes very slow and unresponsive. Other times jobs will just fail with a "Read Timeout". Sometimes restarting the Go server service will resolve this, other times the entire system needs to be rebooted.

Checking the memory/cpu resource usage does not indicate that the system is running out of resources.
##### Environment

Go 15.2.0
Go Server is Windows Server 2012 R2
Agents are Windows 7, Mac OS, Ubuntu 12.04, 14.04 
##### Expected Results

Web UI should not slow down over time and jobs should not timeout

**Comment by BrewRunner** [comment]
I too experience painfully slow and unresponsive web UI interactions.  

- Editing and saving the full config file via the UI is very slow.
- Viewing the console log with the new "colorized" theme takes several minutes to load. It would be nice to be able to turn this off and go back to the simple text console display.
- Routinely receive warning messages about agents not responding within X minutes.

**Environment**
Go Server - 16.1 - 125 pipelines - Windows Server 2008 R2
16 Agents - Windows 7

**Comment by zabil** [comment]
Linked to #1849

**Comment by etiennetremel** [comment]
@Aaronov could this issue https://github.com/gocd/gocd/issues/1044 be related?

**Comment by JSalverda** [comment]
I'm having similar issues, it seems to be highly related to the heap size, see https://github.com/gocd/gocd/issues/2092

**Comment by JorritSalverda** [comment]
What's the status on this ticket? The log console is totally unusable these days, it somehow freezes up Chrome, possibly due to the colorization of logs. Either reverting the colorization or making it possible to turn it off would be of much help. It's one of the biggest frustrations of all of our users.

**Comment by zabil** [comment]
@JorritSalverda we've done a profile and colorization is not the issue here.

The issue is because of a regression in chrome 49+
We'll have to wait for chrome to fix it. Alternatively you can use firefox or safari.

More details here #1849

**Comment by ketan** [comment]
Closing as dup of #1849

**Comment by Aaronov** [comment]
This isn't a duplicate.

The issue our team is having is with the entire website, not just the console page. When trying to load the Pipelines page it can take up to 10 minutes to become responsive and other times it just times out. This goes for loading any page.

**Comment by ketan** [comment]
@Aaronov 

What version of go are you on? Can you provide the output of `https://your-go-server/go/api/support` about 10 seconds apart when you notice slowdowns?

**Comment by Aaronov** [comment]
Version 16.4

[gosupport.txt](https://github.com/gocd/gocd/files/255826/gosupport.txt)

**Comment by Aaronov** [comment]
Here is another support output which took a few minutes to load the page
[gosupport2.txt](https://github.com/gocd/gocd/files/257523/gosupport2.txt)

**Comment by ketan** [comment]
@Aaronov — thank for the output, that looks quite helpful. I can see about 47 blocked threads in one of the outputs. However since the tread stacks are snapshots and point in time they are not helpful or useful without looking at a few snapshots about 5-10 seconds apart.

These snapshots over a few minutes usually tell us which specific threads are blocked or deadlocked over that period. It's usually the stuff that these threads may be doing that could cause your instance to slow down.

**Comment by jyotisingh** [comment]
> Here is another support output which took a few minutes to load the page
@Aaronov - which page was this?

**Comment by Aaronov** [comment]
@jyotisingh - the second output was when trying to load go/api/support and it took a few minutes to finally show the page

**Comment by jyotisingh** [comment]
@Aaronov - is the server installed on a physical machine or a VM? What kind of disk do you have? Have you checked disk IO? Most of the blocked threads are on db which is disk based. Wondering if disk IO is an issue here, as slow IO can cause everything to slow down. What else do you have running on the server box apart from Go server,eg. any other server or anti-virus etc?

Note for self:
Saw java8 in api-support, could it be causing any issue?

**Comment by Aaronov** [comment]
Physical system, SSD drives, no RAID. No anti-virus or anything else running except Go.

I had a look at the DB and it's about 2 GB. Is that large? Is there any way to clean/trim/optimize the DB?

**Comment by jyotisingh** [comment]
2GB does not seem large, but what matters is the number of records in db rather than the file size itself.

Did you check disk IO?

You mentioned that `Sometimes restarting the Go server service will resolve this, other times the entire system needs to be rebooted.`. If you have to restart machine to get it back to normal, it suggests there could be something else causing it. In cases when the entire system needs to be restarted, have you tried checking IO, CPU and memory stats with and without Go server? If it was being caused by Go, I would assume restarting Go would always work.

**Comment by Aaronov** [comment]
Disk IO was mostly used up by reading/writing artifacts and accessing the Go DB. Lately restarting the system hasn't been making a difference. CPU and Memory use is fine (below 10% CPU and maybe 16 GB out of 40 GB memory used).

Unfortunately as of yesterday Go has become so slow and unusable our decision now is to the nuke the DB and start fresh.

**Comment by wcurrie** [comment]
Looking at the gosupport.txt and gosupport2.txt dumps from @Aaronov I suspect contention on H2 is causing some slowness. Some [text wrangling](https://gist.github.com/wcurrie/b0b15a7e5d4179e83b0d24bfd82d195b) shows, [h2threads.txt](https://github.com/gocd/gocd/files/310119/h2threads.txt), 31 threads BLOCKED in org.h2 code. 1 is RUNNABLE. Further if you look for threads with getConnection on their stack you have 16 more are blocked trying to get a connection from the apache dbcp pool. Pool size [defaults](https://github.com/gocd/gocd/blob/master/base/src/com/thoughtworks/go/util/SystemEnvironment.java#L150) to 32 right?

I recently resorted to inserting new relic's javaagent into our go instance to hunt similar sounding slowness. I have some examples like a call to /go/cctray.xml taking 73 seconds. It seems we have contention on the h2 database. Amongst the strange things, we seem to be calling commit in a read operation [JdbcConnection.java#L441](https://github.com/h2database/h2database/blob/version-1.3/version-1.3.168/h2/src/main/org/h2/jdbc/JdbcConnection.java#L441). Doing so seems to aggravate results contention for a mutex in H2:

![image2016-6-10 16-27-14](https://cloud.githubusercontent.com/assets/2050920/15983292/c99056e8-2fe5-11e6-9ebb-7e97d5d6d2ac.png)

Any view to upgrade H2? Seems 1.4 is line up for release (improved multi-threading?). I have no evidence this would improve matters though...

Hibernate seems to do things that result in more blocking calls to H2. Eg [AbstractBatcher.java:299](https://github.com/hibernate/hibernate-orm/blob/3.3/core/src/main/java/org/hibernate/jdbc/AbstractBatcher.java#L299) causes [a SELECT for QUERY_TIMEOUT](https://github.com/h2database/h2database/blob/version-1.3/version-1.3.168/h2/src/main/org/h2/jdbc/JdbcConnection.java#L708):
![image2016-6-9 16-47-21](https://cloud.githubusercontent.com/assets/2050920/15983514/4106351a-2fed-11e6-84e4-b0e0052c9321.png)

I've seen another case where [JdbcConnection.java:530]( https://github.com/h2database/h2database/blob/version-1.3/version-1.3.168/h2/src/main/org/h2/jdbc/JdbcConnection.java#L530) is hit.

**Comment by wcurrie** [comment]
For any folks wanting to reproduce the profiling with newrelic you can get a free account for 14 days, [add](https://docs.newrelic.com/docs/agents/java-agent/installation/java-agent-manual-installation) a -javaagent:/path/to/newrelic.jar then add some custom instrumentation, [newrelic-custom-instrumentation.txt](https://github.com/gocd/gocd/files/310122/newrelic-custom-instrumentation.txt). 

I haven't tried to time the timing (the code newrelic adds for instrumentation) but given @Aaronov's stack traces from the /api/support page support a theory of thread contention in H2 causing slowness it seems the newrelic instrumentation didn't produce the problem for my case.

.

**Comment by wcurrie** [comment]
Some [context](https://groups.google.com/forum/#!topic/h2-database/VoE3AU7mSuM) about the H2 database and threads from the author (Thomas Mueller):

> > What does muti-threading inside database engine mean?
>
> There is no documentation about that, except that it's not fully
> tested. I will document it.
> 
> The default is "not multi-threaded" meaning only one statement can run
> at any time (per database). There is a synchronized block around
> running a statement. When multi-threaded is enabled, then the
> synchronized statement is on the session (connection) instead of on
> the database object.
> 
> The option is to increase concurrency, not throughput. The default
> setting is usually not a problem except if you have long running
> queries.

I suspect at least one cause of slowness, there may be a few, is some slow running query blocks access to H2. It seems many go UI operations involve butting up against a synchronized block inside H2 code. Eg (from [gosupport2.txt](https://github.com/gocd/gocd/files/257523/gosupport2.txt)):
```
org.h2.command.Command.executeUpdate(Command.java:223) <-- synchronized (sync) {
  org.h2.jdbc.JdbcConnection.commit(JdbcConnection.java:441)
  org.apache.commons.dbcp.DelegatingConnection.commit(DelegatingConnection.java:334)
  org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.commit(PoolingDataSource.java:211)
  org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:267)
  org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:754)
  org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:723)
  org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:147)
  com.thoughtworks.go.server.transaction.TransactionTemplate.execute(TransactionTemplate.java:35)
  com.thoughtworks.go.server.dao.UserSqlMapDao.load(UserSqlMapDao.java:189)
  com.thoughtworks.go.server.service.UserService.load(UserService.java:247)
  com.thoughtworks.go.server.security.UserEnabledCheckFilter.getUser(UserEnabledCheckFilter.java:73)
  com.thoughtworks.go.server.security.UserEnabledCheckFilter.doFilterHttp(UserEnabledCheckFilter.java:52)
  org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
```

Ideas: Do users need to be in the same database instance? Can we cache them? Why the calls to commit() when reading a user from the database? Seems some [user stuff](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/UserService.java) is in an H2 table and some is in config.xml. In any case it seems in face of database load when using H2 the wheels fall off the go server UI performance. 

We could try to tackle query performance but if there are going to be long(ish) running queries seems we have the following options:
* solve the User/H2 interaction problem?
* find a way to use H2 multi-threading
* use another DB? postgres or mysql (#1406)? [discussion](https://groups.google.com/forum/#!searchin/go-cd/mysql/go-cd/XFGlNicZxtc/pgvpZm5pAwAJ)
* nuke the contents of H2 when things slow down
* other?

**Comment by wcurrie** [comment]
Looking at /go/api/support dumps today seems we are definitely facing contention on the H2 database. Sometimes pages on the UI take 20/30+ seconds to load (up to minute+). We may have underlying disk I/O issues and are maybe hitting the limit of H2 but the synchronized blocks seem to pour oil on the proverbial flames.

We might try hacking in a cache of User objects to see it if alleviates the problem. Perhaps we'll try cherry picking in the additions to /go/api/support too.

There's some hokey code to visualise the dumps in [gocd-support](https://github.com/wcurrie/gocd-support).

**Comment by arvindsv** [comment]
Hello @wcurrie. I haven't had a chance to take a deeper look at what you've found, but just wanted to say "Thank you!" for looking into it.

Also, wanted to mention that H2 is used in MVCC mode (which changes how concurrency works, a little bit). When I get a chance, I'll see what you've found.

**Comment by NachbarsLumpi** [comment]
We experience a similar issue while go starts up. It starts up quickly within roughly 30 seconds, but then it uses very high cpu usage for about 45 minutes up to an hour. During that time it peaks the cpu usage with 90% on a dual core with 2.4Ghz. From then on it uses [10% .. 25%] on the dual core.

Further we can see that sometimes it consumes 70% cpu on average for 5 minutes and the web ui is unresponsive too during that time. The agents do not run on the same machine as the go server does and it seems to be unrelated with pipeline executions too.

**Comment by evernym-gocd** [comment]
We are also experiencing very bad performance with gocd console. Always getting "504 Gateway Timeout" error. Did anyone fixed the issue?

**Comment by serragnoli** [comment]
Still seeing `504 Gateway Time-out` on version 18.5.0
Is this issue to be fixed any time soon?

**Comment by arvindsv** [comment]
I don't think so. Because that's probably coming from some kind of a proxy in between. I could be mistaken.

**Comment by tormich** [comment]
> I don't think so. Because that's probably coming from some kind of a proxy in between. I could be mistaken.

of course it is! proxy in front of go can't wait forever.
is there anything to do with what you call "immutable" db? we don't need the history for last hundred of years, but we need the build numbers to continue increasing from where they are. and deleting db makes it start from the beginning.

**Comment by serragnoli** [comment]
@tormich I'm not sure what you mean by your comment. Could you expand on it?
