### ISSUE TITLE
Map validation errors on SPA

### ISSUE THREAD

**Issue by juhijariwala** [gocd/gocd#2086]
##### Issue Type
- Feature enhancement
##### Summary

Display validation errors on different section of SPA.
- Pipeline Settings
  - [ ] Label template
  - [ ] Cron timer specification 
  - [ ] Tracking Tool
  - [ ] Parameters
  - [ ] Pipeline Environment variables
- Materials
  - [ ] Git 
  - [ ] Hg
  - [ ] P4
  - [ ] TFS
  - [ ] SVN
  - [ ] Pluggable SCM
  - [ ] Package Repository
- Stages
  - [ ] Stage settings
  - [ ] Stage Operate Permission 
  - [ ] Stage environment variable
- Jobs
  - [ ] Job settings
  - [ ] Job environment variables
  - [ ] Artifacts
  - [ ] Tabs
  - [ ] Properties
- Tasks
  - [ ] Ant 
  - [ ] Nant
  - [ ] Fetch
  - [ ] Rake
  - [ ] Pluggable task
  - [ ] Exec
##### Any other info

Idea for enhancement: 

 Make the separate endpoint to perform validations at server side which will make the entire process of validation and error mapping faster.

**Comment by GaneshSPatil** [comment]
Pipeline config SPA needs to be reworked, we will create a separate issue for tracking work of new pipeline config SPA.

Also, with componentized form elements and model-mixin, error mapping from JSON response to the component view should work out of the box.
