### ISSUE TITLE
Shallow clone can cause hangs

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2090]
##### Issue Type

- Bug Report

##### Summary

The new shallow clone feature works really well, but due to how go.cd only has one clone for each repository setting the same repository in one pipeline to shallow clone and not in the other causes the non-shallow clone pipeline to hang. 

The start buttons are greyed out; seemingly the pipeline is going to start, but this never happens (no yellow bars).

###### Basic environment details

* Go Version: 16.3.0
* JAVA Version: openjdk version "1.8.0_72-internal", OpenJDK Runtime Environment (build 1.8.0_72-internal-b15), OpenJDK 64-Bit Server VM (build 25.72-b15, mixed mode)
* OS: Debian jessie

##### Steps to Reproduce

1. Create 2 pipelines that have the same git repository as material
2. Set 1 to use shallow clone, the other not to use shallow clone
3. Wait for pipelines to automatically start after a commit

##### Expected Results
Both pipelines to start

##### Actual Results
Only the pipeline with shallow clone starts

##### Possible Fix
Check out separate flyweights based on repository url + shallow clone ( + poll for new changes)

**Comment by arvindsv** [comment]
@wpc might be interested. @rajiesh too. I thought we thought about it. Maybe not.

**Comment by wpc** [comment]
@JorritSalverda:
Thank you for reporting bug. I have tried to follow the steps but cannot reproduce the bug. Could you attach the server log when the hanging happens?

Regarding flyweights, as design of the PR, flyweights on server-side are all cloned with shallow option. (original discussion here: https://github.com/gocd/gocd/pull/1846).  So there should not be collisions for different shallow clone flag.

**Comment by JorritSalverda** [comment]
We're still seeing some serious sluggishness in the interface and in pipeline starts, but it turns out it's probably not related to the shallow clone, because it's still happening even though we turned it off for all pipelines to see if that helped. 

I'll close this issue and once I have better logs and reproducibility for the slowness issue I'll create a new ticket.

Thx
