### ISSUE TITLE
Installer option to not immediately start Go Server service on upgrade

### ISSUE THREAD

**Issue by paulclarkin** [gocd/gocd#2091]
##### Issue Type
- Feature proposal

##### Summary

When upgrading Go, the `config/wrapper-server.conf` file is always overwritten.

We have customised our wrapper-server.conf (altering the amount of memory available to the JVM).

It would be good if the upgrade installer paused before starting the Go Server service, to give us a chance to update the wrapper-server.conf file with our customisations. This would avoid the start/wait/stop/update/start cycle we have to go through.

Alternatively, maybe do something to avoid overwriting this file?

**Comment by ketan** [comment]
As per [this document](https://docs.go.cd/current/installation/install/server/windows.html#overriding-default-startup-arguments-and-environment) — you're supposed to set overrides or additional config directives in `config/wrapper-properties.conf` that gets included from `config/wrapper-server.conf` that way any config survives an upgrade.

**Comment by paulclarkin** [comment]
Oh thank you, I didn't see that.
