### ISSUE TITLE
Server crashes with large heap size.

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2092]
##### Issue Type
- Bug Report
##### Summary

When bumping SERVER_MEM and SERVER_MAX_MEM to 5376m (out of 7.5GB total) the server crashes after about half an hour.

Lowering both values to 4096m keeps it alive, but has other side-effects like no longer detecting changes in git repositories.

Putting it back to 512m and 1024m makes the UI slower, but the server otherwise operational.

It runs on java-8-openjdk-amd64 version 1.8.0_72-internal-b15.

There's nothing to be found in the logs that explains the crashes with large heap size.
##### Environment

``` plain

Timestamp
==========
Wed Apr 06 17:10:18 UTC 2016


=================
Config Statistics
=================

Valid Config.
Number of pipelines: 263
Number of agents: 181
Number of environments: 2
Number of unique materials: 139
Number of schedulable materials: 139
Security:
LDAP: false, Password: true


=====================
Config file locations
=====================

loc.config.dir: /etc/go
loc.log.root.0: /var/log/go-server
loc.log.basename.0: go-server.log
loc.log.root.1: /var/log/go-server
loc.log.basename.1: go-shine.log


=================
Go Server Version
=================

16.3.0(3183-60d6fd31f00527da00f2affdd8f7f7732e7be103)


=========================
Server health information
=========================

Server Health Messages: [0 messages]


=================
Cache information
=================


Cache configuration information
-------------------------------
net.sf.ehcache.config.CacheConfiguration@2f700fd3[
  name=cruise
  maxElementsInMemory=100000
  maxElementsOnDisk=0
  memoryStoreEvictionPolicy=LRU
  clearOnFlush=true
  eternal=true
  timeToIdleSeconds=120
  timeToLiveSeconds=120
  overflowToDisk=false
  diskPersistent=false
  diskStorePath=<null>
  diskSpoolBufferSizeMB=30
  diskAccessStripes=1
  diskExpiryThreadIntervalSeconds=120
  loggingEnabled=false
  cacheEventListenerConfigurations=[]
  cacheExtensionConfigurations=[]
  bootstrapCacheLoaderFactoryConfiguration=<null>
  cacheExceptionHandlerFactoryConfiguration=<null>
  terracottaConfiguration=<null>
  cacheWriterConfiguration=net.sf.ehcache.config.CacheWriterConfiguration@7ee7aed7
  cacheLoaderConfigurations=[]
  listeners=[net.sf.ehcache.store.MemoryStore@539f3dc]
  frozen=false
  transactionalMode=OFF
  statistics=true
]

Cache runtime information
-------------------------
Statistics enabled? true
Average get time in milliseconds: 0.0015529046 [Min: 0, Max: 12]
Cache size: 3599 (Accuracy: Best Effort)
Cache counts: [Hits: 184173, Miss: 6746, Expired: 0, Eviction: 0, Put: 3641, Remove: 605]

Cache size (in-memory): 3599
Cache hit count (in-memory): 184173
Cache size (disk): 0
Cache hit count (disk): 0


==============
OS information
==============

Linux, amd64, 3.16.0-4-amd64, 2, 3.32


===================
Runtime information
===================

Name - 18@gocd-server-platform-dotnet-gocd-server
Uptime - 284889 [About 0 hours, 4 minutes, 44 seconds]
Spec Name - Java Virtual Machine Specification
Spec Vendor - Oracle Corporation
Spec Version - 1.8

Input Arguments
---------------
  -> -Xms512m
  -> -Xmx1024m
  -> -XX:PermSize=128m
  -> -XX:MaxPermSize=256m
  -> -Duser.language=en
  -> -Djruby.rack.request.size.threshold.bytes=30000000
  -> -Duser.country=US
  -> -Dcruise.config.dir=/etc/go
  -> -Dcruise.config.file=/etc/go/cruise-config.xml
  -> -Dcruise.server.port=8153
  -> -Dcruise.server.ssl.port=8154
  -> -Djava.security.egd=file:/dev/./urandom

System Properties
-----------------
  -> webapp.root=/var/lib/go-server/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp
  -> awt.toolkit=sun.awt.X11.XToolkit
  -> jruby.rack.request.size.threshold.bytes=30000000
  -> file.encoding.pkg=sun.io
  -> java.specification.version=1.8
  -> sun.cpu.isalist=
  -> sun.jnu.encoding=ANSI_X3.4-1968
  -> java.class.path=/usr/share/go-server/go.jar
  -> java.vm.vendor=Oracle Corporation
  -> sun.arch.data.model=64
  -> sun.font.fontmanager=sun.awt.X11FontManager
  -> java.vendor.url=http://java.oracle.com/
  -> user.timezone=Etc/UTC
  -> jetty.base=/var/lib/go-server
  -> jetty.home=/var/lib/go-server
  -> jruby.compile.invokedynamic=false
  -> os.name=Linux
  -> java.vm.specification.version=1.8
  -> user.country=US
  -> sun.java.launcher=SUN_STANDARD
  -> sun.boot.library.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
  -> sun.java.command=/usr/share/go-server/go.jar
  -> sun.cpu.endian=little
  -> user.home=/var/go
  -> user.language=en
  -> rails.use.compressed.js=true
  -> java.specification.vendor=Oracle Corporation
  -> net.sf.ehcache.skipUpdateCheck=true
  -> java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre
  -> jruby.management.enabled=true
  -> file.separator=/
  -> line.separator=

  -> java.vm.specification.vendor=Oracle Corporation
  -> java.specification.name=Java Platform API Specification
  -> java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
  -> cruise.server.port=8153
  -> java.awt.headless=true
  -> sun.boot.class.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes
  -> java.protocol.handler.pkgs=com.simontuffs
  -> sun.management.compiler=HotSpot 64-Bit Tiered Compilers
  -> cruise.config.file=/etc/go/cruise-config.xml
  -> cruise.server.ssl.port=8154
  -> java.runtime.version=1.8.0_72-internal-b15
  -> java.net.preferIPv4Stack=true
  -> user.name=go
  -> path.separator=:
  -> java.security.egd=file:/dev/./urandom
  -> os.version=3.16.0-4-amd64
  -> java.endorsed.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed
  -> java.runtime.name=OpenJDK Runtime Environment
  -> file.encoding=ANSI_X3.4-1968
  -> java.vm.name=OpenJDK 64-Bit Server VM
  -> jetty.xml.file.name=jetty.xml
  -> java.vendor.url.bug=http://bugreport.sun.com/bugreport/
  -> java.io.tmpdir=/tmp
  -> java.version=1.8.0_72-internal
  -> user.dir=/var/lib/go-server
  -> os.arch=amd64
  -> java.vm.specification.name=Java Virtual Machine Specification
  -> java.awt.printerjob=sun.print.PSPrinterJob
  -> sun.os.patch.level=unknown
  -> java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
  -> java.vm.info=mixed mode
  -> java.vendor=Oracle Corporation
  -> java.vm.version=25.72-b15
  -> cruise.config.dir=/etc/go
  -> java.ext.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext
  -> sun.io.unicode.encoding=UnicodeLittle
  -> java.class.version=52.0

Classpath
---------
  -> file:/usr/share/go-server/go.jar

Boot Classpath
--------------
  -> file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar
  -> file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar
  -> file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar
  -> file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar
  -> file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar
  -> file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar
  -> file:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar
  -> file:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes


==============
GC information
==============

PS Scavenge [PS Eden Space, PS Survivor Space] 109 : 6893 (Count : Time)
PS MarkSweep [PS Eden Space, PS Survivor Space, PS Old Gen] 7 : 5783 (Count : Time)


==================
Memory information
==================

Heap:
  init:      536870912
  used:      552004680
  committed: 981467136
  max:       981467136

Non-Heap:
  init:      2555904
  used:      264435960
  committed: 275816448
  max:       -1

Pending Finalization: 0


=======================
Memory pool information
=======================

Name: Code Cache, Type: Non-heap memory
  init:      2555904
  used:      86000832
  committed: 87883776
  max:       251658240

Name: Metaspace, Type: Non-heap memory
  init:      0
  used:      156425656
  committed: 163815424
  max:       -1

Name: Compressed Class Space, Type: Non-heap memory
  init:      0
  used:      22011056
  committed: 24117248
  max:       1073741824

Name: PS Eden Space, Type: Heap memory
  init:      134742016
  used:      56460888
  committed: 181403648
  max:       192413696

Name: PS Survivor Space, Type: Heap memory
  init:      22020096
  used:      9510240
  committed: 83886080
  max:       83886080

Name: PS Old Gen, Type: Heap memory
  init:      358088704
  used:      486057368
  committed: 716177408
  max:       716177408



==================
Thread information
==================

Current: 287, Total: 1846, Daemon: 75, Peak: 312

All thread stacktraces
----------------------
1859, ActiveMQ Session Task-28, TIMED_WAITING
Locked Monitors:
Locked Synchronizers:
Stacktrace:
  sun.misc.Unsafe.park(Native Method)
  java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
  java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
  java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
  java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)

1858, ActiveMQ Session Task-27, TIMED_WAITING
Locked Monitors:
Locked Synchronizers:
Stacktrace:
  sun.misc.Unsafe.park(Native Method)
  java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
  java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
  java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
  java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
  java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
```
###### Basic environment details

- Go Version: `16.3.0`
- JAVA Version: `openjdk amd64 1.8.0_72-internal-b15`
- OS: `debian jessie 3.16.0-4-amd64 in a docker container`
###### Additional Environment Details

GCE n1-standard-2 vm running container-vm-v20160217 image.

**Comment by wpc** [comment]
@JorritSalverda: 

In the case gocd server crashed, you may find more info in syslog (/var/log/messages)

I suspect it is GC related problem. Could you help turn on GC log (GC_LOG=true), and bump SERVER_MEM, SERVER_MAX_MEM back to 5376m?
If it crush again please post both server log and gc log. (named go-server-gc.log).

**Comment by arvindsv** [comment]
@wpc: One thing worth checking is whether GC_LOG works for Java 8. As you know, it sets these options: `-verbose:gc -Xloggc:go-server-gc.log -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCDetails -XX:+PrintGC`. I don't know if they're valid and proper for Java 8.

**Comment by wpc** [comment]
@arvindsv, just verified, works fine on 1.8 (both oracle jdk and openjdk)

**Comment by JorritSalverda** [comment]
I haven't enabled the gc log yet, but I now have it again with the lower heap size. It turns out the server continues to run, but the cpu load is so high that the UI doesn't respond in time.

This is something that started happening since version 16.3.0 on multiple of our clusters. It never happened in the last couple of versions so seems to be related to one of the fixes / features in 16.3.0.

I'll enable GC_LOG to see if anything interesting shows up.

**Comment by JorritSalverda** [comment]
@wpc Should I see the /var/log/go-server/go-server-gc.log directly after start? It doesn't show up at all. Neither does /var/log/messages. FYI we do run go.cd in a docker container.

It's built with this Dockerfile: https://hub.docker.com/r/travix/gocd-server/~/dockerfile/

**Comment by wpc** [comment]
@JorritSalverda  go-server-gc.log should be in /var/lib/go-server directory (where ever go server stared from).  I checked the docker image, seems like it does not have syslog daemon running, so /var/log/dmesg should be the one to look at when crush happens.

**Comment by wpc** [comment]
@JorritSalverda 

I have tried with same docker file and same memory settings (SERVER_MEM and SERVER_MAX_MEM to 5376m out of 7.5GB total),  run a go-server for 1 days, but can not reproduce either crashing or high cpu consumption. I only have setup 10 pipeline and 10 materials though. And I am not sure how to simulate load at your scale. 

So for solving this problem I need more help from you: next time when the high CPU consumption happens, could you attach to the container, use `jstack` dump go-server thread stack traces every 10 sencond for 5-10 times? (let's do a low tech sample profiling). Something like following

```
# in container
> apt-get update  
> apt-get -y install sudo
> apt-get -y install openjdk-8-jdk
> sudo -u go jstack -F $(pgrep java)
```
Please past the output here.

**Comment by JorritSalverda** [comment]
@wpc Over the weekend nothing has happened so far, but the load is very light. It'll probably happen during the week again, I'll follow your steps when that happens.

**Comment by etiennetremel** [comment]
@wpc thanks for looking into it. We have it happening again, but still we cannot find the source of the issue. As you requested, you can find some of the logs on this gist: 
https://gist.github.com/etiennetremel/19235522d8587dc4ffc1ee7686ae1b9e

Some of the logs contains sensitive data, so if you want a full list let us know we will send them in a different way.

**Comment by wpc** [comment]
@etiennetremel thank you for the info. The thread dump in the gist is truncated, important thread are missing there. Do you have a full copy?

You can direct the output to file during jstack, so that do not need copy it from terminal
```
sudo -u go jstack -F $(pgrep java) > threadump
```

**Comment by wpc** [comment]
@etiennetremel  3-5 thread dumps with about ten seconds interval would also be helpful

**Comment by etiennetremel** [comment]
@wpc looks like the file was truncated, I updated with full version:

https://gist.githubusercontent.com/etiennetremel/19235522d8587dc4ffc1ee7686ae1b9e/raw/d4e677ba83aab1de8981e990dbe6f269b22167e4/2016-04-11%2520-%2520JSTACK%2520profiling.log

**Comment by wpc** [comment]
Server seem like being busy on save certain large revisions 

```
89, 89@MessageListener for MaterialUpdateListener, RUNNABLE
Locked Monitors:
java.lang.String@4fe02ff9 at com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterial(MaterialDatabaseUpdater.java:107)Locked Synchronizers:
Stacktrace:
  java.lang.Object.hashCode(Native Method)
  java.util.HashMap.hash(HashMap.java:338)
  java.util.HashMap.put(HashMap.java:611)
  java.util.HashSet.add(HashSet.java:219)
  org.hibernate.util.IdentityMap.entrySet(IdentityMap.java:207)
......
  org.springframework.orm.hibernate3.HibernateTemplate.saveOrUpdateAll(HibernateTemplate.java:757)
  com.thoughtworks.go.server.persistence.MaterialRepository.saveModifications(MaterialRepository.java:840)
  com.thoughtworks.go.server.materials.ScmMaterialUpdater.insertLatestOrNewModifications(ScmMaterialUpdater.java:69)
  com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.insertLatestOrNewModifications(MaterialDatabaseUpdater.java:155)
  com.thoughtworks.go.server.materials.MaterialDatabaseUpdater.updateMaterialWithNewRevisions(MaterialDatabaseUpdater.java:147)
......
```

And there are two materials update didn't finish for long time
```
2016-04-12 09:23:22,042  WARN [materialUpdateThread] MaterialUpdateService:167 - [Material Update] Skipping update of material GitMaterial{url=git@bitbucket.org:user/repo-1.git, branch='master', submoduleFolder='null', shallowClone=false} which has been in-progress since Tue Apr 12 00:48:05 UTC 2016
2016-04-12 09:23:22,043  WARN [materialUpdateThread] MaterialUpdateService:167 - [Material Update] Skipping update of material GitMaterial{url=git@bitbucket.org:user/repo-2.git, branch='master', submoduleFolder='null', shallowClone=false} which has been in-progress since Tue Apr 12 07:41:15 UTC 2016
```

@etiennetremel  some question for you about two repo git@bitbucket.org:user/repo-1.git and git@bitbucket.org:user/repo-2.git in log:
* if you do a fresh clone, how many revisions do they have?
* can you locate the flyweights repo (/var/lib/go-server/pipelines/flyweights) of them, and see how many revisions the local repo has?
* In the flyweights repos, are there any recent revisions with large amount of changed files (```git log --stat```)? 
* has anyone did a force push or any other history manipulation on them recently?

**Comment by wpc** [comment]
Question for @arvindsv: are there any reason we save all modification (changed files) into database? Potentially it will insert/load hundreds of thousands of rows in database, right?

**Comment by arvindsv** [comment]
@wpc: It's needed to show files to the users as well as for the material blacklist.

Pipeline P1 has a dependency on git material M1 (and no blacklist).
Pipeline P2 has a dependency on pipeline P1 and git material M1 (with blacklist on a file).

Since MDU (material subsystem) and scheduling subsystem are separate, the file information needs to be be captured and persisted.

**Comment by etiennetremel** [comment]
@wpc Looking at the flyweight directory, I see 16 revisions, most of them have a large amount of changed file, see below the stats for some of them:

- hash 1: 137 files changed, 12724 insertions(+)
- hash 2: 9 files changed, 4589 insertions(+)
- hash 3: 17885 files changed, 374155 insertions(+)
- hash 4: 893 files changed, 1319512 insertions(+)
- hash 5: 24 files changed, 1458 insertions(+)
- hash 6: 32 files changed, 826 insertions(+)
...

If I'm not mistaken, both repo-1 and repo-2 have large amount of revisions: 
- repo-1: 21732
- repo-2: 12398

Would it be a good idea to squash them into larger one?

And we didn't do any force push or history manipulation lately.

**Comment by wpc** [comment]
Hi, @etiennetremel 
That' s good information. I can almost be certain ```hash 3: 17885 files changed``` are giving go server trouble for saving modification to the database. 

Can you help verify whether ```hash 3``` has 17885 files changes on a fresh fully clone the repository as well? We need know whether it is shallow clone caused the jumbo revision.

**Comment by etiennetremel** [comment]
Hi @wpc, on a fresh install we have something like 17932 files, this doesn't include submodules. Including all submodules, we reach 92116 files.

**Comment by etiennetremel** [comment]
@wpc what would be the procedure to roll back to 16.2.1 which is a more stable for us?
With that Docker image described above, we mount a persistent disk which contains all the configuration and database. By rolling-back to 16.2.1, would it cause any trouble with the database?

**Comment by wpc** [comment]
Hi, @etiennetremel 

@etiennetremel, I mean if you do a fresh git clone for the repo, and do 
```
% git log --stat
```
do you see 17885 files changed in hash 3?

if you do I suspect it will have trouble on 16.2.1 as well with the large change set.  But it worthing trying, so that we know whether is the upgrade causing problem.
For the rollback procedure, @arvindsv is a better person to answer it.  I know the configure schema changed from 16.2 to 16.3, not sure about database schema.

Quick summary for @arvindsv: there are 2 repos stuck update on server side, stacktrace is pointing to load and insert large modifications.  I still trying to confirm with @etiennetremel  whether the large modification is caused by shallow clone.

**Comment by etiennetremel** [comment]
@wpc yes, something like 17885.

**Comment by arvindsv** [comment]
@etiennetremel: It's about the top-most commit having 10s of thousands of files changed and not the total number of revisions that cause an issue.

@wpc:

> Quick summary for @arvindsv: there are 2 repos stuck update on server side, stacktrace is pointing to load and insert large modifications.

I don't see this being solved by going back to 16.2.1.

Here's what I would consider:

1. Make a commit which does not have that many files. Even a dummy commit.

2. Change the material in the config. Suppose it was: git://abc.com/def, change it to add a slash: git://abc.com//def. This makes GoCD see it as a new repository and it will fetch only the top commit from there (which will be small).

You might need to restart your server to get it to stop seeing the commit and trying to put it into the DB.

> I still trying to confirm with @etiennetremel whether the large modification is caused by shallow clone.

I doubt it very much. [This](https://github.com/gocd/gocd/issues/946) might be relevant.

**Comment by etiennetremel** [comment]
@arvindsv the server didn't crash since we deactivated the "fetch material" and instead use manual git clone in from in the task.

**Comment by etiennetremel** [comment]
@wpc @arvindsv The work around we have right now is to change the repository url with a different case on one of the character. This fix it for few days, then need to do it again. By doing that I suppose the FS DB size will considerably increase.. right now our h2db is is 2.9Go. Do you know if on the road map there a plan to have a cleaning system?

**Comment by JorritSalverda** [comment]
I have another hang where a number of pipelines haven't started for 24 hours where the material actually had multiple commits to the branch of the material. 

In the following 3 gists I have a snapshot of the support page after 80 seconds and after 9 minutes.

- https://gist.github.com/JorritSalverda/b5c4715a440c95b9cc6f945a318324da
- https://gist.github.com/JorritSalverda/8980f2ee807ecc8017f0f64e4b7f569c
- https://gist.github.com/JorritSalverda/2a2bdbbfffa5775edfdc6b757bea2cce

When comparing the snapshots most threads seem to be in the same TIMED_WAITING state.

**Comment by JorritSalverda** [comment]
@wpc @arvindsv are the support page snapshots I attached in the previous comment useful for finding out what's going on? The hangs always coincide with extremely high cpu usage, so either somethings looping really fast or there's a deadlock. However with a deadlock I wouldn't expect high cpu usage. But the support page shows a lot of threads remaining in the same state.

I remember we had these hangs a year and a half ago already, it really seems to be a well-hidden bug in go.cd that manifests when things turn slow - either by high disk I/O or high cpu.

**Comment by ketan** [comment]
> In the following 3 gists I have a snapshot of the support page after 80 seconds and after 9 minutes.

> @wpc @arvindsv are the support page snapshots I attached in the previous comment useful for finding out what's going on? The hangs always coincide with extremely high cpu usage, so either something's looping really fast or there's a deadlock. However with a deadlock I wouldn't expect high cpu usage. But the support page shows a lot of threads remaining in the same state.

Ideally when things are slow, we'd need those snapshots about 5-10 seconds apart for a few minutes. Usually using this script will capture the output for around 100 seconds when you experience an issue.

```shell
for i in {{1..10}}; do
  curl ---silent https://example.com/go/api/support -ubob:password > api-support-$(date --iso-8601=seconds).log
  sleep 10
done
```

I would also suggest running `sudo atop -a -w OUTPUT_FILE 60` so as to capture all performance metrics of your machine to isolate any other background jobs that may be spiking on the CPU (we've sometimes seen that simple stuff like cron jobs running logrotate can cause a lot of grief :))

Turn on jetty request logging, this will print detailed jetty request logs along with how long each request takes to render. Edit the file /etc/go/jetty.xml ensure that you uncomment the block of code that disables logging and make sure that logLatency is set to true. See https://github.com/gocd/gocd/blob/15.2.0/server/config/jetty.xml#L70 for the sample file that shipped with the version of GoCD you're on. These logs should generally indicate how long requests are taking, it might help identify some patterns about which specific pages take long to render, and how long they take to render.

> It's built with this Dockerfile: https://hub.docker.com/r/travix/gocd-server/~/dockerfile/

Have you allocated enough resources to the docker container are there other containers running on the host?

**Comment by arvindsv** [comment]
Closing as stale.
