### ISSUE TITLE
Check connection should check if branch name is valid

### ISSUE THREAD

**Issue by gunnarx** [gocd/gocd#2093]
##### Issue Type
- Feature enhancement
##### Summary
- When defining material type Git, the "check connection" button checks that the URL is valid but not the validity of the branch.   It would be useful if the  connection reports an error if the branch name is misspelled / does not exist.
###### Basic environment details
- Go Version: 15.2.0
- JAVA Version: N/A
- OS: N/A
- Browser vendor and version (if relevant): N/A
###### Additional Environment Details

N/A
##### Steps to Reproduce
- Define materials
- Select material type Git (the same might be for other types - have not tried)
- specify a branch name that does not exist
- Press "Check Connection"
##### Expected Results
- It would be useful if it reports "Branch does not exist"
##### Actual Results
- Reports "Connection OK"
##### Log snippets

N/A
##### Code snippets/Screenshots

N/A
##### Any other info

N/A

**Comment by gunnarx** [comment]
Corresponding shell example:    git ls-remote with --exit-code will return failure if no match.

$ git ls-remote --exit-code http://github.com/gocd/gocd update-issues-template || echo "Repo does not exist, or there is no matching branch"

**Comment by ketan** [comment]
> Corresponding shell example: git ls-remote with --exit-code will return failure if no match.

Hmm, that does look about right, unfortunately that is not a supported option with the version of git on one of the most popular linux distro among some of our users (centos/rhel). Might want to explore some other options as a fallback :-/

**Comment by ibnc** [comment]
@arvindsv This issue has been fixed since 16.5. So, I'm closing this issue; please reopen if I'm mistaken.

Other issue: https://github.com/gocd/gocd/issues/1734
Fixing PR: https://github.com/gocd/gocd/pull/2114
