### ISSUE TITLE
Feature enhancement : API : Add environment endpoint to add a pipeline

### ISSUE THREAD

**Issue by patrick92100** [gocd/gocd#2100]
##### Issue Type

- Feature enhancement

##### Summary

API : Add environment endpoint to add a pipeline

##### Environment

I have got an environment ENV1(a GO-CD one), all my agents are under this environment ENV1

I create a pipeline with the API, I unpause the Pipeline with the API
but I can't add the pipeline to the ENV1environment with the API
I can trigger it with the API but as far as the pipeline is not in any environment, stage/jobs are scheduled but never assigned to Agent...

###### Basic environment details

Go Server Version: 	16.3.0(3183-60d6fd31f00527da00f2affdd8f7f7732e7be103)
JVM version: 	1.7.0_40
OS Information: 	Linux 2.6.18-194.el5

##### Steps to Reproduce

1. create a Pipeline with the API
2. unpause the Pipeline with the API
3. trigger the createdPipeline with the API 
4. stage/jobs are scheduled but never assigned...(not set in any environment)

##### Expected Results
add a pipeline to an environment with the API

##### Actual Results
stage/jobs are scheduled but never assigned...(not set in any environment)

##### Possible Fix
add environment API or 'environment' parameter in create pipeline API endpoint

**Comment by herby** [comment]
+1000.
Pls, API for environment <-> pipeline relation is badly needed.

**Comment by FredrikWendt** [comment]
+1

**Comment by agustincastanio** [comment]
+1

**Comment by arvindsv** [comment]
Coming up in [16.7.0](https://api.go.cd/16.7.0/#update-an-environment)? @GaneshSPatil, can this be closed once 16.7.0 is released?

**Comment by GaneshSPatil** [comment]
@arvindsv -- yes

**Comment by arvindsv** [comment]
Closing this. [Will be](https://github.com/gocd/gocd/pull/2207) in 16.7.0. Documentation [here](https://api.go.cd/16.7.0/#update-an-environment).
