### ISSUE TITLE
Feature enhancement : API : Allow admins to assign a role to a user through the API

### ISSUE THREAD

**Issue by richard-hulm** [gocd/gocd#2118]
I've been reading a bit about "ChatOps" which is the act of using Chat tools as your deployment controller, so you can give a ChatBot the power to hand out a role ("deployment-master") which gives the ability to run certain deployment pipelines

Before this is a possibility in Go, the API would need to support the ability to add/modify roles.

**Comment by eatdrinksleepcode** [comment]
This is a must have for automated provisioning of our Go server.

**Comment by rajiesh** [comment]
@richard-hulm this should now be possible with the Role API - https://api.gocd.org/17.5.0/#update-a-role, which will be released in 17.5.0 release. Do let know if it helps what you are trying to build

**Comment by rajiesh** [comment]
@richard-hulm Closing the issue as this API will be available in 17.5.0 release, do reopen if you feel its not what you were looking for
