### ISSUE TITLE
Pipeline Config API does not allow Pipeline Group Admin to create/edit a pipeline.

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2119]
##### Issue Type

- Bug Report

##### Summary

A Pipeline Group Admin should be allowed to use the Pipeline Config API to create/edit/get a pipeline fr

###### Basic environment details

* Go Version: 16.3.0
* JAVA Version: 1.7

##### Steps to Reproduce

1. Add user 'operate'. 
2. Make 'operate' user a Pipeline Group Admin for an existing pipeline group, which would have a pipeline within, say 'foo'.
3. GET /go/api/admin/pipelines/foo

##### Expected Results
Pipeline Group Admin, that is the operate user must be allowed to get/edit/create pipeline within an existing group. If the group does not exist, it implies that the operate user is not a Pipeline group admin for a non-existent group and thus, should not be allowed to create a pipeline.

##### Actual Results
When using the Pipeline Config API as a Pipeline Group Admin of an existing group, access is denied to get/edit/create a pipeline within that group. As a Go Admin, when the Pipeline Config API is used to create a pipeline within a non-existent group, the pipeline group and the pipeline gets created. 
  
##### Possible Fix
2. Make Pipeline Config API accessible to Pipeline Group Admins and Go Admins. Disallow creation of a group from this API. Have a separate Group API, accessible only to Go Admins, to handle the creation of pipeline groups and to assign the user and role permissions. 

Notes: 
1.Disallow Pipeline Group Admin of another group should not have access to create/edit/get pipelines from a group that the user is not an admin of.
2. Allow users with view permissions to a pipeline group to use the GET request for Pipeline Group API. Pipeline group Admins can view, create or edit a pipeline.

**Comment by Aaronov** [comment]
I am running 16.4 and having similar issues. I can't GET a pipeline config (https://api.go.cd/current/#get-pipeline-config) and instead just get a 404 no matter what user I use. I don't know if this is the same problem or not but this is a roadblock for our team.

**Comment by zabil** [comment]
@Aaronov this issue is not related.

I suggest you mail the user groups with the problem you are facing and sharing more info about your configuration.

It will also help if you send a sample curl request (with sensitive info removed)

**Comment by Aaronov** [comment]
Sorry I may have jumped the gun. It appears to have started to work now so I'm not really sure what was happening before. I'll report back in a new ticket if I see the problem again and provide further details.

**Comment by GaneshSPatil** [comment]
A User with `VIEW` permissions for the pipeline should be allowed GET the pipeline

currently If the user has only view permissions (Not admin or pipeline_group_admin permissions) for the Pipeline , he is NOT able to get the pipeline.
