### ISSUE TITLE
Proposal to partially drop xml data store

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#2121]
Apparently most (all?) gocd developers agree that **storing** pipeline configuration
in xml is bad. Secondly we also agree that moving away from existing xml-based
configuration system is **way too much work** to even touch it.
This is a proposal on how we can _realisticly_ move away from xml.

I would say that theoretically **pipelines and environments and agents** are
candidates that should NOT be stored in xml. IMHO this is because these entities
are **user data/input**, not **server configuration**.

After working on #1133 and discussing it with many of you I had some ideas on
how we can move away from storing pipelines, (optionally) environments and agents.
## Brief overview
- continue to use `cruise-config.xml` as datastore for **server configuration** only. (`<server>`, `<repositories>`, `<config-repos>`, ...)
- **eventually** stop storing user data entities as xml (`<pipelines>`, `<agents>`, `<environments>`) in git config repository.
- **initially** add new, **second** data store for pipelines, agents and environments. (`ConfigOrigin=db`)
- store above entities as JSON in database. Means we don't use sql schema for pipelines.
- define JSON schemas, at least for pipelines.
- use something like [Jolt transformations](https://github.com/bazaarvoice/jolt) to handle configuration migrations instead of `xsl`.
- drop use of git merges to handle concurrent edits of configuration (pipelines only). Merge changes at object level instead.
- in UI add new Config JSON tab to allow editing pipelines and environments in json format.

For rather desired backward compatibility with xml:
- in general we still allow XML to be used for _transport_. I mean, XML as old API
  for users that depend on XML to change configuration.
- keep the Config XML tab with `<pipelines>` and `<environments>` rendered,
  but their actual source is db. We advertise that this tab is obsolete.
- similarly `/etc/go/cruise-config.xml` can still contain `<pipelines>`, `<environments>`,
  but that file is rendered lazily from database, it is not blocking actual
  configuration-changing operations.
## Benefits and why
- performance - #838 (still a problem right?).
- elastic agents will only add more load in the `agents` section. It needs to be moved.
- since #1133 now there is more than one **source of pipeline configuration**.
  There can more such sources. Not necessarily SCM-based, e.g. server fetches
  pipeline config from URL.
- Moreover we can standardize such source to reuse it in other tools. There can be
  web UI to edit such source (like one in #1404), or there can be a desktop application
  for editing configuration in local files. Both would use same format for storage
  and protocol (the pipeline config API?) for editing. Then SPA from #1404 can be
  used to build standalone application (out of gocd server) for editing pipelines.
- no one likes magical _too-much-reflective_ xml loader and writer. Hard to debug, hard to maintain.
- JSON is the new standard
### Why is this realistic?

In #838 there were some suggestions to drop xml and more to something else, e.g. database. But main problem was that we need backwards compatibility with XML. 
In #1133 we faced similar problem - there are other sources than XML which provide configuration to server. Apparently we can merge all these sources to provide consistent configuration service for Go server.
Presuming that we want to keep pipeline configuration in database, we can add new configuration source `db` and handle it similarly to the partials in config repos. The key is that **`db` source can exist simultanously with the current xml data store**, thus allowing to phase-out the old xml config. E.g. new users/servers would not have xml pipelines at all, because by default adding a pipeline would be _routed_ to db.
## Final notes
- So far I heard, the plan is to move agents from xml. But moving it to another
  xml file would be making the same error again.
- To me, current xml data store looks like a growing tech debt. Yes it might have been working once,
  few years ago, when there were less pipelines, they were less dynamic, there was no API,
  the XML was the standard.
- From user perspective this issue is not that important. I think it is more
  a question to gocd developers - do you want to drag this limited, slow,
  hard to maintain XML subsystem? Or would you rather work on top of new JSON-oriented
  system, designed for current/future needs?
- I don't feel strongly about moving away environments from xml, since they are
  rather small and not so dynamic. However for the sake of argument, they are
  same _configuration category_ as pipelines.
  
  I can elaborate on this some more if you're interested in moving into this direction.

**Comment by zabil** [comment]
Initial thoughts 

I see this as a yet another storage format change XML->JSON. I'd like to approach it like how we did with the new pipeline config [api](https://api.go.cd/current/#pipeline-config) on which the new config ui #1404 is built. The performance is much better in the new api.

Having a full config api allows migration away from xml making it easier to decide what the right storage mechanism.

**Comment by tomzo** [comment]
@zabil 

> I'd like to approach it like how we did with the new pipeline config api on which the new config ui #1404 is built.

You mean to build JSON API on top of *some* new config storage, regardless of its format (JSON or not)? I agree 

My main point here is to create second config storage next to current XML.

> The performance is much better in the new api.

BTW, the reason for that is because there is less update-config-commands sent from UI to config store, right? I understand that now there will be just one submit-new-pipeline-config when user finished updating single pipeline. But the underlying handling of xml did not change much yet.

**Comment by zabil** [comment]
> You mean to build JSON API on top of some new config storage
I mean build a complete JSON API on top of our *current* storage (XML) and *then* choose the best storage format.

> My main point here is to create second config storage next to current XML.

I think we should defer this decision until we finish writing the API and have more information on how the API's are being used.

> BTW, the reason for that is because there is less update-config-commands sent from UI to config store, right?

I was talking about a single save operating and this is because the new API https://github.com/gocd/gocd/issues/1417 by-passes the old save logic. Can't find the profiled data but  @jyotisingh sold us an 80% speed improvement for a single save.
