### ISSUE TITLE
Shallow clone doesn't apply to submodules

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2123]
##### Issue Type
- Bug Report
##### Summary

Shallow clone applies --depth 3 to the repository in the material, however the git submodule update doesn't get the --depth parameter added and thus clones the whole history of each submodule. This takes up a lot of time.
###### Basic environment details

- Go Version: `16.3.0`
- JAVA Version: `java-8-openjdk-amd64 jre`
- OS: `debian jessie`
##### Steps to Reproduce
1. set git repository with submodules as material and check shallow clone
2. set clean working directory on stage
3. set git log for git repo as task
4. set git log for submodule - by using it's path as executing directory as task
5. run the pipeline
##### Expected Results

The main git repo shows only 3 log items at most; I would expect the same for each submodule
##### Actual Results

The submodule has full history
##### Possible Fix

Pass --depth n to git submodule update if shallow clone is checked

**Comment by heaten** [comment]
Hi, 
Any idea that when this patched will be merged?

**Comment by arvindsv** [comment]
@heaten The PR was not merged, according to @GaneshSPatil. I've opened a new issue #5856, targeted at GoCD release 19.3, to take a look at some pending issues around git. So, I'll close this issue in favor of that. Thank you for bringing this up.
