### ISSUE TITLE
Skip git gc, resetting, cleaning if clean working directory is used

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2124]
##### Issue Type
- Feature enhancement
##### Summary

Currently cloning the git repository works the same regardless of whether you clean the working directory or not. Time can be saved by not running git gc, git clean, etc.
###### Basic environment details

- Go Version: `16.3.0`
- JAVA Version: `open jdk8 jre`
- OS: `debian jessie`
##### Steps to Reproduce
1. Create a pipeline with a git repository as material
2. Check clean working copy on the stage level
3. Run the pipeline
##### Expected Results

Only git clone, git submodule init and git submodule update (if submodules are present) is executed
##### Possible Fix

Run only the minimum amount of required task to clone the git repository
##### Log snippets

```
06:06:36.934 [GIT] Fetching changes
06:06:38.598 [GIT] Performing git gc
06:06:38.814 [GIT] Reset working directory pipelines/<pipeline name>
06:06:38.814 [GIT] Cleaning all unversioned files in working copy
06:06:39.019 [GIT] Cleaning submodule configurations in .git/config
06:06:39.121 [GIT] Updating working copy to revision <revision>
06:06:40.653 HEAD is now at 993fdc6 ...
06:06:40.658 [GIT] Removing modified files in submodules
06:06:41.268 [GIT] Updating git sub-modules
06:09:12.480 [GIT] Cleaning unversioned files and sub-modules
06:09:12.482 [GIT] Git sub-module status
```

**Comment by akshaydewan** [comment]
I was analyzing this, and it looks like the cleaning process is fast. It takes only about a second or lesser, but updating submodules (if any) takes longer. Git `gc` is called with the `--auto` flag, so in most cases, it does nothing.

While it's ideal to do the minimum amount of work, the implementation doesn't seem trivial - it requires a change in some interfaces to pass a flag from `BuildWork` to `GitCommand` and cascades into a rather large changeset. So I think we should ignore this for now and pick up some of the other issues in https://github.com/gocd/gocd/issues/5856 . We may very well rewrite some of the cleanup commands based on newer git features.
