### ISSUE TITLE
No "Fetch Artifact" option in "Add Stage" dialog

### ISSUE THREAD

**Issue by stevedesmond-ca** [gocd/gocd#2126]
##### Issue Type
- Bug Report
##### Summary

When adding a new stage to a pipeline, often our first step is to fetch a build artifact from a previous stage -- unfortunately this option is not currently there.
###### Basic environment details
- Go Version: 16.3.0
- JAVA Version: 1.8.0-45
- OS: RHEL 7
- Browser vendor and version (if relevant): Firefox 46
##### Steps to Reproduce

1. Create a new pipeline from the admin menu, or edit an existing pipeline, or create or edit a template
2. Click on the "Stages" tab
3. Click the "Add a stage" link
##### Expected Results

List of tasks to add includes "Fetch artifact" -- see screenshot 1, which is what clicking "Add a task" shows
##### Actual Results

List of tasks to add does not include "Fetch artifact" -- see screenshot 2
##### Possible Fix

List of tasks always contains all available items
##### Code snippets/Screenshots

Screenshot 1
![screen shot 2016-04-20 at 8 49 28 am](https://cloud.githubusercontent.com/assets/195896/14675051/163f09ba-06d5-11e6-8b7e-8343b6f430a1.png)

Screenshot 2
![screen shot 2016-04-20 at 8 42 34 am](https://cloud.githubusercontent.com/assets/195896/14675058/1a907a9e-06d5-11e6-908a-43aa82ee4f16.png)

**Comment by zabil** [comment]
We are working on a re-design of the pipeline create/edit page https://github.com/gocd/gocd/issues/1404.
This new pipeline wizard page will be deprecated in favor of the create page.
