### ISSUE TITLE
go-agent's environment leaks into jobs

### ISSUE THREAD

**Issue by FredrikWendt** [gocd/gocd#2134]
##### Summary

When setting up go-agents, all environment variables available to the go-agent process, leaks through to the tasks executed by that go-agent.
##### Environment

This is present int 16.4.0 and all previous versions.
##### Steps to Reproduce
1. Create a pipeline, with one stage, with one job, with one task being "/usr/bin/env"
2. Run it on any go-agent
##### Expected Results

The expected output from `/usr/bin/env` should only list all the `GO_*` environment variables, such as `GO_SERVER_URL`.
Other possible standard Linux env variables ($HOME for instance) might need to be setup too.
##### Actual Results

You see lots of things, even the `JAVA_HOME` setting, which clearly impacts java builds, such as Gradle and Maven.
##### Possible Fix

When forking a process, setup an explicitly configured environment, instead of "re-exporting" the current one.

Handling of SSH agent/keys is something to think about, since this may be impacted.
##### Additional information

There's been some discussion on the go-cd user mail list: https://groups.google.com/forum/#!topic/go-cd/PlT-HXUq_sk

**Comment by FredrikWendt** [comment]
Any quick fix here for not re-exporting JAVA_HOME would make a lot of noise in my setups go away. +1 for a quick fix.

**Comment by ketan** [comment]
@FredrikWendt — I'm considering adding [this snippet](https://github.com/gradle/gradle/blob/f85e4802991daec8cb97ad3fea65676afda1b992/gradlew#L69-L89) "AS-IS" into the agent and server startup scripts so as to pick up `java` from `PATH. This also has the advantage of users not having to set `JAVA_HOME`, and mess up the agent process.

You could (if you want) add `JAVACMD` to `/etc/default/go-{agent,server}` for GoCD to pick up a specific java executable that's not on `PATH`.

Do you have any concerns, or see any problems with this approach?

**Comment by FredrikWendt** [comment]
LGTM - it's going to fix the immediate problem.

Ideally, I'd make sure the environment is clean before adding things (ie https://docs.oracle.com/javase/8/docs/api/java/lang/ProcessBuilder.html#environment-- if you're driving things from Java), but we could split this story into two:
* removing the JAVA_HOME leakage
* providing a really clean run time environment for tasks

**Comment by ketan** [comment]
> if you're driving things from Java), but we could split this story into two:
> 
> removing the JAVA_HOME leakage
> providing a really clean run time environment for tasks

There's really no way to whitelist/blacklist specific variables via `ProcessBuilder#environment`. This may have severe unintended consequences including not being able to find basic programs because of missing `PATH` or an incorrect locale being loaded by programs because of missing `LC_*` variables, among others. I'm not sure how to go about providing a "really clean run time environment", whatever that means :) But I'm open to exploring options on how one may achieve this.

There's definitely a case to be made to allow users to `export` variables via `/etc/default/go-agent` so that all sub-processes see it, but I'm looking to tackle leakage of `JAVA_HOME` and other variables that are exported but are specific to just the agent, but don't need to be exported to the sub-processes.

**Comment by FredrikWendt** [comment]
So what's the different between JAVA_HOME leaking through, compared to LD_LIBRARY_PATH, LC_*, SHELL, PATH, DISPLAY, DBUS_SESSION_BUS_ADDRESS, ...?
All of these are local to the running process and I don't see why the _go agent_ should specify anything but
* GO_*
* PATH=/bin:/usr/bin:/usr/local/bin
* USER=go

To provide anything but the above, by default, would be to clutter the (build) environment for all the job/tasks that is execute by a particular go agent. That means we reduce the reproducibility of jobs, and that the rerunning a GoCD job may run differently depending on which agent gets to run the job.

If a job/task needs a specific environment variable setup, like LD_LIBRARY_PATH, it should be defined _with that job_, not _with the go agent_.
You could of course argue that agents' `resources` could mean that some specific environment is provided, which I assume then would be fine, but for the "out of the box" general experience, I consider providing anything but the above listed env variables to be a bug.

Yes, we use Docker for build environment isolation as far as possible (since we have the JAVA_HOME issue for many of our jobs), in order to make builds more reproducible and less receptive/sensitive to where/on which computer/in which environment it was built. But do we really think that GoCD should force everyone to clean their environment, or could we start from assuming/providing a clean environment?

I hope this explains my intention with this issue. :-)

**Comment by arvindsv** [comment]
The wrapper has been completely revamped and this should not be happening any more. Right, @ketan? Closing as stale for now.
