### ISSUE TITLE
RPM dependency on "which" added from 16.2

### ISSUE THREAD

**Issue by davelms** [gocd/gocd#2135]
Bug Report

Ref discussion on https://groups.google.com/forum/#!topic/go-cd/ekjwR13ta4c 

Operating System = SLES11 SP3.

Package Manager = RPM or Zypper.

Current version of Go Server installed was 16.1.

RPMs for go-server v16.2+ have added a dependency for "which".

```
$ rpm -qpR go-server-16.2.1-3027.noarch.rpm
warning: go-server-16.2.1-3027.noarch.rpm: Header V4 RSA/SHA1 signature: NOKEY, key ID 8816c449
/bin/bash
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/bin/sh
config(go-server) = 16.2.1-3027
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
which
```

"which" is installed on our server, but there is no package of that name. It was actually installed through the package "util-linux".

```
$ rpm -qf /usr/bin/which
util-linux-2.19.1-6.62.1
```

Unfortunately it seems that "util-linux" does not declare "which" as something it provides, even though it installs it.

The upgrade from 16.1 to 16.2+ fails with the missing "which" dependency.

```
D: ========== RSA pubkey id e3a5c360 307e3d54 (h#1)
D:  read h#    1270 Header V3 RSA/SHA256 signature: OK, key ID 307e3d54
D:  Requires: /bin/bash                                     YES (db files)
D:  Requires: /bin/sh                                       YES (db files)
D:  Requires: /bin/sh                                       YES (cached)
D:  Requires: /bin/sh                                       YES (cached)
D:  Requires: /bin/sh                                       YES (cached)
D:  Requires: /bin/sh                                       YES (cached)
D:  Requires: config(go-server) = 16.2.1-3027               YES (added provide)
D:  Requires: rpmlib(CompressedFileNames) <= 3.0.4-1        YES (rpmlib provides)
D:  Requires: rpmlib(PayloadFilesHavePrefix) <= 4.0-1       YES (rpmlib provides)
D: opening  db index       /var/lib/rpm/Providename rdonly:nofsync mode=0x0
D:  Requires: which                                         NO
D: package go-server-16.2.1-3027.noarch has unsatisfied Requires: which
```

The same problem occurs if using the zypper package manager.

I CAN upgrade by ignoring dependencies, but this is not preferable of course. Especially as "which" is installed on the server, all the dependencies are satisfied (although "util-linux" doesn't declare it), it's just that the install of which was not via a package of the same name.

**Comment by GaneshSPatil** [comment]
@ketan @davelms -- Is this issue still relevant after the latest GoCD installers changes (happened as part of GoCD release `v19.7.0`)?

**Comment by davelms** [comment]
Onto 19.7.0 ourselves and not had any issues since.
