### ISSUE TITLE
Number of pipelines retrieved via API does not match number of pipelines listed in support page

### ISSUE THREAD

**Issue by lenucksi** [gocd/gocd#2139]
##### Issue Type
- Bug Report
##### Summary

Go can report a number of pipelines via two ways. 
The first is to count the number of lines-3 via the /go/api/pipelines.xml endpoint and the second is the number reported bia /go/api/support.

I have observed different numbers being reported here, with the first method reporting significantly lower numbers than the second. It appears to me that the first method reports the active pipelines and the second reports the number of pipelines that are in the Go servers database, thus reports how many pipelines have existed in the server at all. 
##### Environment

Go 16.1, CentOS 7
##### Expected Results

The numbers should be similar or the support page should report the number with a correct label or even both numbers, labeled correctly.

**Comment by adityasood** [comment]
Couldn't replicate this issue on the latest GoCD v18.11.0-8024. Closing this out. Please feel free to re-open in case you observe this behavior.
