### ISSUE TITLE
/go/api/support should be available as JSON and with configurable scope

### ISSUE THREAD

**Issue by lenucksi** [gocd/gocd#2140]
##### Issue Type
- Feature enhancement

##### Summary
The /go/api/support endpoint outputs a lot of very valuable information. 
As a user operating a Go server I would like to be able to regularly ingest this information into my monitoring system.
For this I would like to be able to directly extract the desired information, ideally as JSON, without having to parse the natural language format it is delivered in now.
To be able to reduce the load of the server I would like to be able to specify which sections are included in the output using a parameter.

**Comment by ketan** [comment]
Related PR #2283

**Comment by ketan** [comment]
@GaneshSPatil — see https://github.com/gocd/gocd/issues/2285#issuecomment-225477870
