### ISSUE TITLE
TFS material checkout cleans working copy

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2150]
##### Issue Type
- Bug Report
- Feature proposal
- Feature enhancement
- Documentation Report
##### Summary

TFS material [checkouts](https://github.com/gocd/gocd/blob/d9e47c518617d94ffc912f22aedb598cdfefb4b5/common/src/com/thoughtworks/go/domain/materials/tfs/AbstractTfsCommand.java#L79-L81) perform an `rm -rf` on the working directory before checking out a fresh copy. Depending on the size of the working copy, this may cause a significant delay before the build kicks off.

It appears that this was done for the lack of a `git clean` or `svn cleanup` like alternative. We need to figure out a way to clean up working copy before performing a material update.

**Comment by eatdrinksleepcode** [comment]
Thanks for filing this @ketan. This is a pretty pressing need for us; is this something the core team can look at soon, or should we maybe look at fixing this ourselves and contributing it back (understanding that we have no context on the Go source and the ramp up might take a while)?
