### ISSUE TITLE
Checkout working copy only on the agent side.

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2152]
##### Issue Type

- Feature proposal

##### Summary

When a material is listed, on the server side, the flyweight directory is created for the new material. The clone command for the same is as follows
```
git clone --branch=<branchName> --no-checkout --depth=<depth> <url> <workingDirectory>
```

Although the --no-checkout and shallow clone flag improve the performance of the go-server greatly, having the flyweight folder as a bare repository can reduce the disk space and make the clone of large repositories faster than it is right now.

On the server side, the clone command could be 

```
git clone --bare --depth=<depth> <url> <workingDirectory>
```

##### Notes

The bare repository must only be on the server-side because the agent needs a working copy to perform the build operations.

**Comment by FredrikWendt** [comment]
+1

**Comment by varshavaradarajan** [comment]
Bare repository is not a feasible option for Go right now because of the difference in behaviour for the git commands. It involves a breaking change for the non-bare repositories on the server side. Needs to be analyzed further.
