### ISSUE TITLE
Command arguments with spaces gives an error

### ISSUE THREAD

**Issue by mribichich** [gocd/gocd#2153]
##### Issue Type:
- Bug Report
##### Summary

I'm creating a command Task and I'm trying to pass an argument which is a path with spaces, and when the task runs it gives an error.
It doesn't matter if I use quotes or double quotes.

`'C:\Program' is not recognized as an internal or external command`

```
<exec command="cmd" >
  <arg>/c</arg>
  <arg>%programfiles(x86)%\14.0\MsBuild.exe</arg>
  <arg>Sis.BioStarDbScraper.WinService.sln</arg>
  <arg>/T:clean;rebuild</arg>
  <arg>/P:Configuration=Prod</arg>
  <arg>/m"</arg> 
</exec>
```

```
<exec command="%programfiles(x86)%\14.0\MsBuild.exe" >
  <arg>Sis.BioStarDbScraper.WinService.sln</arg>
  <arg>/T:clean;rebuild</arg>
  <arg>/P:Configuration=Prod</arg>
  <arg>/m</arg> 
</exec>
```
###### Basic environment details
- Go Version: `16.4.0(3223-71ed3f0abf6ee673d1f0c7ca4e2262afae38dea6)`
- JAVA Version: `1.7`
- OS: `Windows Server 2012, x86, 6.2, 3, -1.0`
- Browser vendor and version (if relevant): `Chrome v50`

![edit job - go - google chrome](https://cloud.githubusercontent.com/assets/5748554/14984591/e99e773e-1119-11e6-882b-11d9d5aa22f2.jpg)

**Comment by fabriciocduarte** [comment]
I'm running into this same issue as well.
GoCD version 17.11 on windows

**Comment by arvindsv** [comment]
Closing as stale. Also there's a duplicate issue.
