### ISSUE TITLE
Manual trigger a pipeline through value_stream_map.

### ISSUE THREAD

**Issue by uncodead** [gocd/gocd#2163]
##### Issue Type
- Feature enhancement
##### Summary

Manual trigger a pipeline through value_stream_map. Respecting the user permissions.
##### Environment

I have two nested pipelines , and the latter needs to be manual. I would like to have a button to run the pipeline on the screen: value_stream_map:

![image](https://cloud.githubusercontent.com/assets/181846/15073717/7dd681a4-1371-11e6-8e10-9ba2d69d030a.png)
###### Basic environment details

Go Server Version: 16.4.0(3223-71ed3f0abf6ee673d1f0c7ca4e2262afae38dea6)
JVM version: 1.7.0_79
OS Information: Windows Server 2012 R2 6.3
Usable space in artifacts repository: 99.9 GB
Database schema version: 1503002
Browser: Chrome

**Comment by amlozano** [comment]
+1. In most of the cases that I have worked with in GO CD after 2 years, the VSM is much more visual and it is more expressive in information than the regular Pipelines View. Why?: In the regular pipeline view you don't easily know which pipeline has been executed already for a given dependency.

I would also consider even to add a top view with all the Value Stream Maps, but that is out of the scope of this ticket.

**Comment by arvindsv** [comment]
@amlozano We did consider a top-level VSM but it gets complicated very quickly. A new pipeline run will have a new VSM. So, there can be multiple concurrent VSMs at the same time, among other issues. So, it's not currently being considered.

**Comment by amlozano** [comment]
@arvindsv I get your point, but I see a lot of value on a view where you can select which pipelines you want to display the VSM for, and just with the last run, no more complex than that.

**Comment by arvindsv** [comment]
@amlozano Yes. I agree that there's value in a top-level VSM view, even if it is not comprehensive, especially if it refreshes automatically.

**Comment by amlozano** [comment]
@arvindsv anyway this ticket is to add a button to the VSM to deploy, which it is also really really helpful. Both settings together for us would put GO CD on the top of any CD/CI tool. Those are the two main cons we have with the usage of GO CD.
