### ISSUE TITLE
GoCD cannot access network shared drives via tasks.

### ISSUE THREAD

**Issue by smtechx5000** [gocd/gocd#2165]
GoCD Task
Bug report

- Bug Report
- Feature proposal
- Feature enhancement
- Documentation Report

##### Summary
GoCD 16.3.0
When I use the svn checkout command to check code out of a svn repository to a network shared drive I get the error "error resolving case of"  path to network share.   The paths are all correct with no typos. I have a batch file that has the same command in it and when I run it outside of GoCD it does the checkout to the shared drive just fine.   This also works if I run the same svn checkout in the command line.   Does not work when I run the command in Go eben if I use the call command instead to call the batch file I get the same error "error resolving case of..".      Note:  The command svn checkout works fine in Go if I checkout to the local C drive instead of the shared drive.

These are the paths:
svn://***.**.*.***/T4_SITES/TestGo
\\ssg-storage\SSGSTOR\TrunkBuilds\Ipayment

ssg is a shared network drive.  Running as shown I get the error I described above. If I remove the leading backslashes like this:

svn://172.16.1.141/T4_SITES/TestGo
ssg-storage\SSGSTOR\TrunkBuilds\Ipayment

The task completes successfully but nothing gets checked out to the shared drive.

I'm running this on a VM on Windows server 2008.

<!--- 
Describe the environment in which you encountered this issue.
Details of the environment GoCD is running in can be fetched from the GoCD support api - http://<go-server-host>/api/go/support.
If you are pasting plain text, please surround it with 3 backticks on each side

Expected results:  The svn checkout command with proper paths show checkout code to a network shared drive

**Comment by zabil** [comment]
Closing this as it's related permission on windows. There's nothing that can be fixed on GoCD to solve this.

**Comment by arvindsv** [comment]
@zabil: Not sure about closing this. I think it has something to do with backslashes being swallowed.

**Comment by zabil** [comment]
@arvindsv 

According to this https://www.tomred.net/devops/svn-error-resolving-case.html it's svn expecting forward slash while on windows.

**Comment by arvindsv** [comment]
I see. Ok.
