### ISSUE TITLE
No visual distinction between running & pending

### ISSUE THREAD

**Issue by logicbomb** [gocd/gocd#2173]
##### Issue Type

Bug Report
##### Summary

There is no visual distinction between pipelines that are executing on an agent vs. those that are pending to be run.
##### Environment

A simple single server environment with a single agent that runs a few pipelines.  If one pipeline is executing, and the other is waiting for the agent to become available they are both shown as yellow.  I need to click all the way down to the jobs page to see that none of the jobs have been scheduled on an agent.
- Go Version:`16.2.1(3027-07834a1f2ce79a13d42b03601698ef48f128a012)`
- JAVA Version: `Available from http://<go-server-host>/api/go/about` (_no available, that URL gives me a 404_)
- OS: `Available from http://<go-server-host>/api/go/about` (_ditto_)
##### Steps to Reproduce

1. Configure a server with a single agent & more than 1 pipeline
2. Start the first pipeline, wait a beat & start the second
3. Observe that both pipelines appear to be executing
4. Navigate to the 2nd pipelines job status and note it isn't executing
##### Expected Results

Visual confirmation that one is running, and one is waiting
##### Actual Results

Visually all pipelines appear to be executing
##### Possible Fix

Add a css style to the pipeline for waiting, perhaps #ccc

**Comment by eatdrinksleepcode** [comment]
Was planning on filing this exact issue from my experience setting up a new server in the last few weeks. Agreed that it would be good to easily distinguish running vs pending.

**Comment by BrewRunner** [comment]
+1

**Comment by wlsf82** [comment]
+1

**Comment by wlsf82** [comment]
+1

**Comment by arvindsv** [comment]
Closing in favor of #2603. The new dashboard should do this. It [says](https://github.com/gocd/gocd/issues/3872#issuecomment-337530250): "Waiting for agent".
