### ISSUE TITLE
Dashboard performance improvements

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#2178]
- Performance improvement
##### Summary

There have been instances where loading the dashboard has taken considerable amount of time. One of the reason for this is fetching the page involves loading all active pipelines and the associated modifications for the latest run. There doesn't seem to be any usage of the modifications on dashboard except for showing the `Changes` link which is shown conditionally on the presence of modifications.

On click of  `Changes`  a build_cause request is made which lists all the modifications.

To improve performance of the dashboard we can look at loading all active pipelines minus the modifications.

This requires further analysis.

**Comment by arvindsv** [comment]
Related to: #1097, #276 and #1841?

**Comment by arvindsv** [comment]
Closing in favor of #1841.
