### ISSUE TITLE
Required header Confirm: true blocks using gitlab post push hooks

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#2191]
##### Issue Type
- Bug Report
##### Summary

Post commit hooks now require `Confrim: true` header. E.g. This is a valid call

``` bash
curl 'http://localhost:8153/go/api/material/notify/git' \
> -u 'admin:badger' \
> -H 'Confirm: true' \
> -X POST \
> -d 'repository_url=http://gitlab.example.com/tomzo/gocd-example-xmlconfig.git'
The material is now scheduled for an update. Please check relevant pipeline(s) for status.
```

Such call is impossible to send from gitlab hooks, where user can only provide URL to which gitlab should talk to. E.g. so far this was a good hook configured in gitlab

```
http://admin:badger@go.example.com/go/api/material/notify/git/?repository_url=git@git.example.com:wiki/wiki.git
```
#### Workaround

Currently setting system property `go.api.with.safe.mode = false` "fixes" it

**Comment by AmShaegar13** [comment]
> Currently setting system property go.api.with.safe.mode = false "fixes" it

Even this stopped working in 16.5.0. See https://github.com/gocd/gocd/commit/ac2e8bab99b914975e475c65b90ffabd8f7ab929#diff-57598510f1f5d67cc8e20a7dc44561f8R160

**Comment by arvindsv** [comment]
Closing in favor of #3676.
