### ISSUE TITLE
Switch pipeline from "use template" to "define stages"

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#2196]
##### Issue Type
- Feature proposal
##### Summary

I would love to be able to convert a pipeline from using a template to defined stages. This would work by copying the template into the pipeline configuration in the reverse of the extract template process. It would make modifying a template's actions less dangerous and possible for unprivileged users to do.
##### Environment

```
N/A
```
###### Basic environment details

- Go Version: `16.3.0(3183-60d6fd31f00527da00f2affdd8f7f7732e7be103)`
- JAVA Version: `Java(TM) SE Runtime Environment (build 1.7.0_80-b15)`
- OS: `Linux, amd64, 2.6.32-504.8.1.el6.x86_64, 10, 1.71`
- Browser vendor and version (if relevant): `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/601.5.17 (KHTML, like Gecko) Version/9.1 Safari/601.5.17`
##### Steps to Reproduce

1. Edit a pipeline
2. Click the "Stages" tab
3. Notice the "Define Stages" radio button is unavailable.
4. 
##### Expected Results

It should be possible to set a pipeline currently based on a template to use it's own stages again. This would create the configuration by extracting the stages from the template and merging it with the existing pipeline configuration.
##### Actual Results

Nothing.

**Comment by zabil** [comment]
Some work done here https://github.com/gocd/gocd/pull/730
