### ISSUE TITLE
git material access

### ISSUE THREAD

**Issue by pshomov** [gocd/gocd#220]
It seems both the server and agents need access to the source code repository which makes things difficult with adding new agents since we need to deploy private keys to them in order to be useful(git materials). I think it would be both simpler and safer if only the server interacts with the repos and hands over the code to the agents.

**Comment by arvindsv** [comment]
Closing. Would be nice for sure, but there seems to be no appetite by anyone to pick this up. Especially since this is a major change. Also, need to think about reruns of old instances.
