### ISSUE TITLE
Add REST API to get GoCD version number

### ISSUE THREAD

**Issue by grundic** [gocd/gocd#2202]
##### Summary

I would like to get version number of running GoCD server. I found [this](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/models/api_v1/go_latest_version.rb), but looks like it used for automatic updates or something similar. Could you add additional endpoint to get version number?

##### Expected Results
It should return version number (maybe some additional info) of running GoCD server.

**Comment by arvindsv** [comment]
Closing, since #2239 is merged. Documentation PR is https://github.com/gocd/api.go.cd/pull/84.
