### ISSUE TITLE
Duplicate api requests in task extension

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#2206]
##### Issue Type

- Bug Report

##### Summary

Server sends too many requests to task plugin. First long ones, then short ones.

**All** of the following requests are used in task extension:
```
go.plugin-settings.get-configuration
go.plugin-settings.get-view
go.plugin-settings.validate-configuration
configuration
view
validate
```

##### Environment

Seen when debugging 16.5.0 (before release)

##### Steps to Reproduce

Start server with task plugin, with a breakpoint in plugin api request handling. E.g. at https://github.com/gocd-contrib/script-executor-task/blob/master/src/com/tw/go/plugin/task/GoPluginImpl.java#L63

Look at messages comming from server. First `go.plugin-settings.*` will be sent, then again `configuration`, `view`.

#### Possible fix

There are related issues  #2098 and #1355.
I found it out in #2203

**Comment by tomzo** [comment]
#2099 is also related.
I'd say there is quite a mess in plugin messages.

**Comment by arvindsv** [comment]
From what I know, this is what the messages look like and are for:

1. The [go.plugin-settings.* ones](https://developer.go.cd/current/writing_go_plugins/plugin_settings/plugin_settings_overview.html) are for a plugin to decide what settings it wants stored at the **plugin** level. This is what, I think, is supposed to decide whether a settings icon is shown next to the plugin's name in the plugin listing page.

    ![image](https://cloud.githubusercontent.com/assets/172235/15488997/bddd7878-2129-11e6-8497-8c5b7407ce9c.png)

2. The other (non-namespaced ones) are specific to the task, and it is supposed to be shown in the "Add task" dropdown in a job.

Ideally part 1 (the go.plugin-settings.* ones) are common to all plugins. However, I think maybe something changed and if it returns null (or doesn't handle it or throws an exception), it might be failing now (based on what @tomzo said).

**Comment by arvindsv** [comment]
Also, plugin settings happened after the task plugin and that's one of the reasons for it. Will be happy if someone wants to rethink it completely. Versioning might allow us to change this, though it'll be a little tricky.

**Comment by tomzo** [comment]
It makes more sense now, so these are not duplicates.
I'll have to fix script executor plugin then, in last PR I made responses to all namespaced and non-namespace messages the same, now there is script editor in plugin settings...

**Comment by ketan** [comment]
Sorry, I'm on too many pain killers and sedatives to think straight, and I was the one that asked @tomzo to file this request. @arvindsv does this mean that https://github.com/gocd-contrib/script-executor-task/pull/12 needs a revert?

**Comment by tomzo** [comment]
@ketan it does need a revert, I just checked that in my server there is task script editor when clicking on gear button of the plugin. I'll submit another PR, I think the plugin should just return `OK` for all `go.plugin-settings.*` so that there is no global settings.

**Comment by arvindsv** [comment]
Yes, that should do. I was worried that all task plugins were broken on 16.5. But, @jyotisingh checked just now and the behavior of the script executor plugin is the same as it was in 16.x (x < 5). Even though there is that exception when the plugin did not handle the go.plugin-settings.* message, it shows up in the dropdown as it should and works.

So, returning an empty view and configuration for the plugin should work. Maybe just a text message for the view: "This plugin has no settings"?

**Comment by arvindsv** [comment]
Closing since the messages were [inconsistent and confusing](https://github.com/gocd/gocd/issues/1355) but not duplicate.
