### ISSUE TITLE
Checking if a directory is a git repository

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2209]
##### Issue Type

- Bug Report
##### Summary

We consider a folder to be a git repository based on the existence of the .git directory according to [this](https://github.com/gocd/gocd/blob/f73c794a8cff084d1bf6c7a83c7b33f86af0a5ba/common/src/com/thoughtworks/go/config/materials/git/GitMaterial.java#L268).  However, it may not always be the case that the existence of the .git folder means that the directory is a git repository.
###### Basic environment details

- Go Version: 16.5
- JAVA Version: 1.7
##### Steps to Reproduce

1. List a repository as a material
2. While the git clone command runs, find out the pid. Do a `kill -9 pid` (simulating a git process crash).
##### Expected Results

The flyweight and the material folder are not git repositories.
##### Actual Results

The folders will have the .git folder. They will be considered as git repositories.

**Comment by arvindsv** [comment]
Closing as stale.
