### ISSUE TITLE
Provide the ability to rename pipelines and templates

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#221]
You do not always get the name of a pipeline or a templated right first time. The name is crucial in your modelling and helps convey what the pipeline is about so if the name is wrong then the meaning is unclear. Yet there is currently no easy way to rename them.

I know it is possible by editing the xml directly however this is a cumbersome operation and something that should be possible from within the user interface.

**Comment by jefftrimm** [comment]
+1 We are running into the this issue with our rollout.

**Comment by sublimino** [comment]
+!

**Comment by joel74** [comment]
+1

**Comment by steve-gray** [comment]
Proposed solution (if there's traction on this, I'll submit a pull request with this in it):

* Add a field to pipeline definition for 'Label'
* Allocate pipelines a guid during pipeline creation and store that as the pipeline name.
* User text entry during pipeline creation now sets the label for the pipeline, not the name.

The data-side work for this is to set the initial value of the label to be the same as the physical name for pre-existing pipelines on a version step-up.

The only downside is a scenario where:
* User renames 'my-pipe' to 'some-pipe'
* They create a new pipeline called 'my-pipe' that gets a Guid folder.

In this scenario anyone who looks at the agents /pipelines folder will be a little confused for legacy/pre-existing pipelines, but at least nothing breaks and nobody loses data.

**Comment by mrmanc** [comment]
I agree that separating the concerns of presentation and identification is the right way to go. What value do you propose using for the agents’ /pipelines folder then? I think it would be nice if that remained the pipeline label—you could store the guid inside the folder to let you check whether the pipeline matches, and start with a fresh workspace in the (unlikely) event that it doesn’t… That way it’s still a friendly file structure when you’re debugging / exploring.

**Comment by steve-gray** [comment]
The trouble with the naming rules would be that the display names of pipelines would be forced to meet the lowest common denominator for folder names on platforms. Thats why today it's only lowercase and hyphens. 

Something like a Guid cleanly divorces the two concepts and means you can put business-friendly names on the pipeline display that are able to say "Main Dev/Test Workflow". Alternatively we can let users set the 'physical name' as-is now up front, but then warn them of never being able to change it. I think if we did that there'd be an issue of people putting too much sentiment on those physical names and getting caught up in the same issue. A Guid or some other surrogate key takes away that 'ownership' of the folder names.

Having sat down with the codebase trying to bludgeon in a Display Name field last night and this morning, it seems that:

* A simple 'rename pipeline' operation would require masses of surgery.
* Adding a 'display name' field has so far required touching dozens of files.

I've got my fork at: https://github.com/eventual-consistency/gone-cd and will be probably throwing in my rough-as-balls version of this work later today.

**Comment by FredrikWendt** [comment]
+1 to the proposed solution, and the need for simpler renaming of work. Since there's no DSL, Go.cd is obviously created for having humans model pipelines manually, and humans rarely gets it right the first time. Changing things a pipeline/stage with downstream dependencies is increadibly tedious today.

**Comment by Oktaz** [comment]
+1

**Comment by anshulvij** [comment]
+1 for making the UI naming and logical name creation separate
Anyways the logical names can be choosen as random hash values, avoiding collision if pre-existing.
This way even when a new pipeline is created with a name that was used some time ago by some other pipeline, there will be no conflict.

**Comment by rkrisztian** [comment]
If feasible, I would suggest to identify pipelines with numbers, like in a database.

**Comment by DanielHilton** [comment]
I would find this feature very useful as my team's code is being renamed in line with our service catalogue naming rules and conventions. Our GoCD pipelines cannot be renamed without losing our audit trail for rollback purposes and are stuck on the old names.

**Comment by chambois** [comment]
We’re in a similar position - our initial naming of pipelines is not how we wish for them now and are stuck with them or facing the loss of history (which is highly undesirable).

We’d love to see this feature and agree with the above ideas of separating IDs from naming.

**Comment by wilmol** [comment]
> This can be achieved without editing the config by cloning the pipeline to your new name and then deleting the old one.

Not a solution, it fails to delete/clone when there are dependencies between pipelines.

**Comment by ZukkyBaig** [comment]
+1

**Comment by luisxkimo** [comment]
Hi,

I don't know if after last comment here something was implemented to solve this problem, but trying last version of GOCD server, I can't see any option to rename pipelines in the UI

**Comment by pkchandanam** [comment]
do we have any workaround ?
