### ISSUE TITLE
go server and agent deb installation does not allow ignoring of java installation

### ISSUE THREAD

**Issue by brettcave** [gocd/gocd#2210]
##### Issue Type
 - Bug Report

##### Summary

The go-server and go-agent deb installation packages force installation of java through a `Pre-Depends` and does not allow the use of a custom java installation.

##### Environment

Ubuntu (14.04 LTS, but expected across all dpkg / apt based package managed distros).

##### Additional Environment

An example use-case is when wanting to run GOCD with Oracle JDK 8 instead of openjdk 7 and the system is provisioned using Chef. Using the go-cookbook in conjunction with the Java cookbook, Java can be configured to install Oracle JDK8, but when go-server installs, it forces an installation of openjdk 7 because of `Pre-Depends` in the control file. 

If `Pre-Depends`  is changed to `Depends`, the options can be overridden through options, for example in a `package` resource in Chef:

```
package "go-server" do
    version [:go][:version]
    options "--force-yes -o Dpkg::Options::='--ignore-depends=java7-runtime-headless'"
   notifies :start, 'service[go-server]', :immediately
end
```

##### Possible Fix
https://github.com/gocd/gocd/blob/master/installers/server/deb/control.go-server
```
9  - Pre-Depends: java7-runtime-headless
 9 + Depends: java7-runtime-headless
```
and the same for https://github.com/gocd/gocd/blob/master/installers/agent/deb/control.go-agent

###### Current workaround
The deb file can be repackaged and go-server installed with Pre-Depends removed as follows for a deb-based system:
```
$ ar x go-server-xxx.deb
$ FILES=`tar zxvf control.tar.gz`
$ sed -r -i '/Pre-Depends: .+/d' control
$ tar zcf control.tar.gz $FILES
$ ar rcs go-server.deb debian-binary control.tar.gz data.tar.gz _gpgbuilder
$ sudo dpkg -i go-server.deb
```

##### More info

https://www.debian.org/doc/debian-policy/ch-relationships.html
```
Pre-Depends
    This field is like Depends, except that it also forces dpkg to complete installation of the packages named before even starting the installation of the package which declares the pre-dependency
```
The ignore-depends flag is not applied to pre-depends dependencies.

**Comment by brettcave** [comment]
Have not investigated RPM packaging, not sure if a similar issue is relevant to it.

**Comment by ketan** [comment]
> Have not investigated RPM packaging, not sure if a similar issue is relevant to it.

With RPM, we don't depend on java, because there's no one "java" package that we can definitively depend on that works across different versions of the various RPM distros (Fedora, RH, SUSE, OpenSUSE)
