### ISSUE TITLE
Upgrade windows JRE to java 8

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2213]
##### Issue Type
- Feature enhancement
##### Summary

Now that GoCD supports Java 8. Perhaps it's time to upgrade the windows JREs that are packaged to JRE 8, instead of JRE 7.

**Comment by jyotisingh** [comment]
Related: https://github.com/gocd/gocd/issues/1939 and https://github.com/gocd/gocd/issues/2171

**Comment by zabil** [comment]
Upgrade the [NSIS](http://nsis.sourceforge.net/Main_Page) installer version as a part of this upgrade.

**Comment by ketan** [comment]
@zabil — NSIS is already running at 2.51. Do we still need an upgrade to 3.0?

**Comment by zabil** [comment]
Yes they've fixed it on 2.51
Reference
http://nsis.sourceforge.net/Docs/AppendixF.html#v2.51
