### ISSUE TITLE
Windows 64 bit JRE for GoCD server

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2214]
##### Issue Type
- Feature proposal
##### Summary

Most heavily loaded GoCD servers running on Windows cannot use the bundled 32-bit JRE because they would likely require more than 4gb of memory. 4gb is the of the memory addressing limitation 32-bit JVM that we ship with.

If we were to ship with a 64-bit JRE, GoCD may not work on 32 bit machines (whoever even uses 32 bit anymore?).

I'd like for us to ship 2 variants of windows installers 32-bit and 64-bit and gradually phase out 32-bit if there's not enough downloads to justify the installers.

The agents on windows can definitely work within the memory constraints of the 32-bit JRE, so a 32-bit JRE is more than sufficient there, and there's no real need for a 64-bit JRE. However we may just want to ship one (for sake of consistency with the server)

WDYT?

**Comment by arvindsv** [comment]
> I'd like for us to ship 2 variants of windows installers 32-bit and 64-bit and gradually phase out 32-bit if there's not enough downloads to justify the installers.

Agree.

> The agents on windows can definitely work within the memory constraints of the 32-bit JRE, so a 32-bit JRE is more than sufficient there, and there's no real need for a 64-bit JRE. However we may just want to ship one (for sake of consistency with the server)

Agree (about shipping the same one for consistency). We do need to make sure that all combinations of the 64-bit server/agent work with 32-bit agent/server, right? Or, we document the fact that it does not.

**Comment by ketan** [comment]
> Agree (about shipping the same one for consistency). We do need to make sure that all combinations of the 64-bit server/agent work with 32-bit agent/server, right? Or, we document the fact that it does not.

I guess a lot of existing windows users are probably using a combination of a 64 bit server with 32 bit agents already, so I suppose in a way that it does work.

**Comment by fire** [comment]
I have an artifact folder with one file that is 13GB, will using a 64 bit client allow me to use the 13gb + etc zipped artifact? It appears that you don't want to ship a 32bit client. What is the decision on this?

**Comment by ketan** [comment]
Yes, I don't see why you'd not be able to use a large artefact. Our thought process is currently is that we'd be shipping both 32 and 64 bit JREs. 64 Bit will allow the gocd server to use more than 2GB of heap space, and 32 GB should be good enough for agents, but still allow users to install 64 bit if they prefer to use that.

**Comment by arvindsv** [comment]
To add to this, [PR #2788](https://github.com/gocd/gocd/pull/2788), merged a few days ago gets this part (most?) of the way there. It'll need to be shown on the downloads page soon, etc.

**Comment by jyotisingh** [comment]
@arvindsv - yes, @naveenbhaskar was working on getting some mockup done for the downloads page to accommodate this. Will check with him
