### ISSUE TITLE
Fail to start go-server due to use of deprecated PermSize/MaxPermSize

### ISSUE THREAD

**Issue by safl** [gocd/gocd#2220]
##### Issue Type

- Bug Report

##### Summary

go-server fails to start on Ubuntu Server 16.10 with below error-message from "go-server.out.log":

```
Unrecognized VM option 'PermSize=128m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

##### Environment

Ubuntu Server 16.04 64bit, install wizard selections:

```
Language: English
Location: United States
Keyboard: English (US)
Hostname: gocd
Full name: GO CD
Username: gocd
Password: <supersecret>
Encrypt home dir: NO
Timezone: Pacific
Partition: Guided -- use entire disk
Proxy: --leave blank--
Tasksel: No automatic updates
Software selection: standard system utilities, OpenSSH server
Install GRUB: YES
```

With **GoCD** repos:

```
echo "deb https://download.go.cd /" | sudo tee /etc/apt/sources.list.d/gocd.list
curl https://download.go.cd/GOCD-GPG-KEY.asc | sudo apt-key add -
```

And these packages:

```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
sudo apt-get install htop vim-nox go-server
```

###### Basic environment details

* Go Version: Installed form repos 25. May 2016
* JAVA Version:
```
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)

```
* OS:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
Linux gocd 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
* Browser vendor and version (if relevant): Irrelevant

##### Steps to Reproduce

See description of environment. Then execute:

```
sudo service go-server restart
```

##### Expected Results

Go-server should start

##### Actual Results

Go-server does **not** start

##### Possible Fix

Seems like the use of PermSize is changing:

https://archenroot.wordpress.com/2015/03/24/java-8-xxpermsize-and-xxmaxpermsize-disappearing/

So `server.sh` should probably stop using them, possibly replace with "MetaspaceSize/MaxMetaspaceSize ".

##### Log snippets

```
[Wed May 25 22:02:33 PDT 2016] Starting Go Server with command: /usr/lib/jvm/java-9-openjdk-amd64/bin/java -server -Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx1024m -XX:PermSize=128m -XX:MaxPermSize=256m -Duser.language=en -Djruby.rack.request.size.threshold.bytes=30000000 -Duser.country=US -Dcruise.config.dir=/etc/go -Dcruise.config.file=/etc/go/cruise-config.xml -Dcruise.server.port=8153 -Dcruise.server.ssl.port=8154 -jar /usr/share/go-server/go.jar
[Wed May 25 22:02:33 PDT 2016] Starting Go Server in directory: /var/lib/go-server
Unrecognized VM option 'PermSize=128m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

```
● go-server.service - LSB: Go Server
   Loaded: loaded (/etc/init.d/go-server; bad; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2016-05-25 22:04:47 PDT; 17min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 1288 ExecStart=/etc/init.d/go-server start (code=exited, status=255)

May 25 22:04:17 gocd systemd[1]: Starting LSB: Go Server...
May 25 22:04:17 gocd su[1292]: Successful su for go by root
May 25 22:04:17 gocd su[1292]: + ??? root:go
May 25 22:04:17 gocd su[1292]: pam_unix(su:session): session opened for user go by (uid=0)
May 25 22:04:17 gocd go-server[1288]: [Wed May 25 22:04:17 PDT 2016] using default settings from /etc/de
May 25 22:04:47 gocd go-server[1288]: Error starting Go Server.
May 25 22:04:47 gocd systemd[1]: go-server.service: Control process exited, code=exited status=255
May 25 22:04:47 gocd systemd[1]: Failed to start LSB: Go Server.
May 25 22:04:47 gocd systemd[1]: go-server.service: Unit entered failed state.
May 25 22:04:47 gocd systemd[1]: go-server.service: Failed with result 'exit-code'.
```

##### Code snippets/Screenshots

Not relevant.

##### Any other info

I think it is straightforward :)

**Comment by zabil** [comment]
We need the ```PermSize ``` setting for Java 7, It's been deprecated on Java 8 with a warning.
 Looks like it's removed on Java 9.

One way is to set the ```-XX:+IgnoreUnrecognizedVMOptions``` till we stop support for Java 7. 
But then it'll will let the wrong flags slip through.

**Comment by zabil** [comment]
Also ```Permsize``` cannot be converted to ```MetaspaceSize/MaxMetaspaceSize``` values.
Ideally we must skip setting the ```MetaspaceSize/MaxMetaspaceSize``` and the the app and os handle the memory instead.

**Comment by safl** [comment]
I tried a quick work-around with IgnoreUnrecognizedVMOptions but got a bunch of Java FileNotFound exceptions instead of go-server starting. Seems unrelated.

When are you releasing GoCD 16.6 and are you testing against Ubuntu 16.04?

**Comment by zabil** [comment]
Here's what we test

https://github.com/gocd/installer-testing/blob/9f58a6accadaf456b7e62f4e65163ec13a5f23b4/Vagrantfile#L22

**Comment by zabil** [comment]
> When are you releasing GoCD 16.6

The release schedule is monthly year = 16 and month = 6 so that's sometime in 2016 June

**Comment by zabil** [comment]
> got a bunch of Java FileNotFound exceptions

Strange, @safl do you mind sharing the errors stack trace?

**Comment by safl** [comment]
I just had to try out those emojis... I was eager to test out GoCD so I wiped the test-box and threw Ubuntu 14.04 on it. If I get to try it again I'll put 16.04 on, get the error and submit another bug-report.

I guess I am going of topic with all those questions, sorry about that and thanks for answering. Since I have more questions I'll post them on your community forum.

**Comment by misham** [comment]
I'm getting the same error on Ubuntu 16.04.  Any plans to support Ubuntu 16.04?

Would using Oracle Java instead of OpenJDK provide a solution?

**Comment by ketan** [comment]
Please use java 8. Java 9 is not supported.

**Comment by misham** [comment]
Looks like Java 9 is installed by default on Ubuntu 16.04.  Is it possible to pin the version of Java for the package on the PPA server?

**Comment by moritz** [comment]
I've had this on a fresh installation on Ubuntu 16.06 today, with go-server 16.9.0-4001.

If Java 9 is installed by default on Ubuntu, but go-server depends on java <= 8,  shouldn't the installer pick a supported version of Java to put into `/etc/default/go-server`? Right now the experience on Ubuntu is pretty bad; installation fails in the postinst, with no proper error message, and one has to dig through the logs to actually find the error message, and then Google that to find this issue to find a remedy.

Which, for the record, is putting `export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/` into `/etc/default/go-server/`.

Can somebody please re-open this issue? @ketan maybe?

**Comment by b-connect** [comment]
As workaround. 
http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/
