### ISSUE TITLE
Feature Request: parameter expansion in <resource> tags

### ISSUE THREAD

**Issue by moritz** [gocd/gocd#2222]
##### Issue Type
- Feature proposal
##### Summary

I'd like to be able to define a template, and let the pipeline using the template influence on what agents some jobs run. So I'd like to be able to use `#{param}` expansion in resource specifications, so I can say

```
 <resources>
    <resource>#{build_resource}</resource>
 </resources>
```

And in the pipeline using the template, I'd say

```
<params>
   <param name="build_resource">deb-jessie</param>
</params>
```

to for example nail down the OS version that build is supposed to run on.

Without that, I have to maintain multiple copies of a template just for the resource specification.

**Comment by benzvan** [comment]
We do this all the time. We define a parameter RESOURCE with the resource string (hostname, in our case) and use #{RESOURCE} in the configuration. I wonder if you're running into a bug. I don't think we have any resources used this way that are not alphanumeric only.

Pipeline:
```
      <params>
        ...
        <param name="RESOURCE">dvaswb</param>
        ...
      </params>
```

Template:
```
            <resources>
              <resource>#{RESOURCE}</resource>
            </resources>
```

**Comment by moritz** [comment]
We generate our configuration from jsonnet templates now, so we don't need this anymore. Haven't tested with a recent version of GoCD either.
