### ISSUE TITLE
Go Server not starting due to errors [16.5.0-3305]

### ISSUE THREAD

**Issue by Painyjames** [gocd/gocd#2231]
##### Issue Type

- Bug Report
##### Summary

It basically fails while trying to start the service through /etc/init.d/go-server start.
More to be found here:
https://raw.githubusercontent.com/Painyjames/dnx-docker/master/go-server.log
###### Basic environment details
- Go Version: 16.5.0-3305
- JAVA Version: 1.7.0_101
- OS: Ubuntu 14.04

**Comment by arvindsv** [comment]
Do you have a Dockerfile where this is happening?

**Comment by Painyjames** [comment]
Not really.
I got it on a puppet script but I don't think it matters since I'm just doing an apt-get install there (which is probably just installing the latest version).

**Comment by Painyjames** [comment]
Also can confirm that with previous version (16.4.0-3223) there is no error at all.

**Comment by arvindsv** [comment]
Closing. It has been a while. Please reopen if reproducible on a newer build and if this is still relevant. Thank you.
