### ISSUE TITLE
Unable to connect to git server

### ISSUE THREAD

**Issue by hassanfarid** [gocd/gocd#2232]
#documentation report

#summary

i have hosted git server. i have as setting up my first pipeline. unable to test git connection using simple authentication.
user@ip:repo.git

why i am missing? go uses any particular user to access git?

#environment

Ubuntu OS with latest version of GO.

**Comment by hassanfarid** [comment]
Some more details
===============

I get following error when connecting to git server, do I need to setup some user configuration and access rights?

![capture](https://cloud.githubusercontent.com/assets/782236/15650787/969438ae-2694-11e6-9506-4f1756efb222.JPG)

**Comment by zabil** [comment]
Refer this thread
https://groups.google.com/forum/#!searchin/go-cd/host$20key$20verification/go-cd/A4FRtBbzJm4/c8EQSOyB_aUJ

Closing this as it's a git configuration issue. Will open it if it's not solved after fixing the configuration.

**Comment by hassanfarid** [comment]
Quick question:

Do I need 'go' user for both system (Ubuntu) and git server? Can configure any other user to access git from goCD?

**Comment by arvindsv** [comment]
GoCD server runs by default under the "go" user account. It'll execute "git" (and "git clone", "git fetch", etc) and doesn't care what user the git server has. If you don't want the GoCD server to **run** under the "go" user account, it's best to use the zip package, instead of the .deb installer package.

**Comment by hassanfarid** [comment]
@arvindsv I am able to ssh to go user and run the command manually that appears in error screenshot above.

Can you suggest what might be wrong? I have git user go, with password go.

git ls-remote 10.34.21.21:/home/go/sme.git refs/heads/devel
![capture](https://cloud.githubusercontent.com/assets/782236/15679433/40fe111c-276b-11e6-8b74-5b16235bfa7f.JPG)

**Comment by arvindsv** [comment]
Well, what is happening here is that the protocol of the value you've entered is not ... obvious and the git command-line client is refusing to use it. That's because the GoCD server is (by default) disallowing any protocol other than http, https, ssh, etc. as you can see from the line about `GIT_ALLOW_PROTOCOL`.

Can you try putting in the value: `ssh://10.34.21.21:/home/go/sme.git` in the URL field?

As long as you can run: `git clone ssh://10.34.21.21:/home/go/sme.git` as the "go" user, and not have it ask you anything (like a password, etc), that value should work here.

Remember that the GoCD agents will also need the same setup (SSH keys, if that's what you're using) so that they can check out the code as well.

**Comment by hassanfarid** [comment]
Thanks for the quick response @arvindsv 

I tried value: `ssh://10.34.21.21:/home/go/sme.git` in the URL field, gives me same error.
![capture](https://cloud.githubusercontent.com/assets/782236/15681027/4328bd2e-2771-11e6-98a1-a8a80206df70.JPG)

I tried running command as go user on console: `git clone ssh://10.34.21.21:/home/go/sme.git`; it does ask me for password for go user on git server. Should this be a problem?

I will have to setup same for GoCD Agents, I think I will come to it - once I am able to setup first pipe line. Right? However, I don't know steps for this.

**Comment by arvindsv** [comment]
Oops. Saw the protocol part and got confused. You shouldn't need the `ssh://` bit. Sorry.

Anyway, getting back:

> I tried running command as go user on console: git clone ssh://10.34.21.21:/home/go/sme.git; it does ask me for password for go user on git server. Should this be a problem?

Yes. That is a problem. The GoCD server can't enter your password for you. You'll need to make sure that it doesn't ask for a password. You'll need to read about setting up ssh keys, if you don't know.

**Comment by arvindsv** [comment]
Also, if the user you use to connect to the git server is not "go", you can always use: `other-user@10.34.21.21:/home/go/sme.git`.

**Comment by hassanfarid** [comment]
Since my git server and goCD were running on the same server, I used `/home/go/sme.git` in URL; and it worked.

@arvindsv

**Comment by hassanfarid** [comment]
Now I am setting up first pipeline to build code using `/usr/bin/cmake .`

I get below error:
![capture](https://cloud.githubusercontent.com/assets/782236/15722449/39924528-2857-11e6-80de-adbb4dbc6775.JPG)


When I run same commend from console, it works fine.  `/var/lib/go-agent/pipelines/SME/> /usr/bin/cmake .`

**Comment by arvindsv** [comment]
The command shouldn't be "/usr/bin/cmake .". The command should be "/usr/bin/cmake" and the argument should be ".".

**Comment by arvindsv** [comment]
[This page](https://docs.go.cd/current/faq/environment_variables.html) talks about environment variables, but has some information about exec tasks as well.

**Comment by hassanfarid** [comment]
Thanks @arvindsv - it worked. :)

**Comment by arvindsv** [comment]
Cool. If you haven't tried it, take a look at the "Setup your first pipeline" set of articles in the [help page](https://www.go.cd/help/).

**Comment by hassanfarid** [comment]
HI @arvindsv  - I am following through guide page. [link](https://www.go.cd/getting-started/part-2/#concept_artifact)

I am setting Artifact as defined in help page. I get below error:
`05:47:33.757 [go] Start to create properties SME/28/defaultStage/1/defaultJob on satxeonphisrv [/var/lib/go-agent]`
`05:47:33.757 [go] Start to upload SME/28/defaultStage/1/defaultJob on satxeonphisrv [/var/lib/go-agent]`
`05:47:33.757 [go] The rule [my-artifact.html] cannot match any resource under [pipelines/SME]`
`05:47:33.757 [go] Uploading finished. Failed to upload [my-artifact.html]`
`05:47:33.787 [go] Job completed SME/28/defaultStage/1/defaultJob on satxeonphisrv [/var/lib/go-agent]`
