### ISSUE TITLE
problem with installing the go_agent => $Go_Server

### ISSUE THREAD

**Issue by naiduv** [gocd/gocd#224]
In the Agent Installer, when it asks for the Go Server, you do not provide any hint that mentions that the server url should not have http:// prefix or the :8153 suffix.

This makes it very frustrating since the only way to debug is to read the log and see the java error where it tries to connect to http://http://server:8153:8153.

You could try to fix it by checking for port or the prefix, or you could provide a simple example in the GUI.

It took me 4 tries to get it right and I knew what it might have been.

**Comment by arvindsv** [comment]
Documentation is hopefully more clear now. I haven't heard of this being a problem recently. Also, some of this is changing as a part of #2236.
