### ISSUE TITLE
Improvement: collapsed pipeline view

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2242]
##### Issue Type
- Feature proposal
##### Summary

Currently the homepage shows one big list of all pipeline groups and their respective pipelines. When the number of pipelines grows beyond a certain number this becomes practically unusable. The browser and server have trouble keeping all the information up to date.

Having a view where all groups are collapsed or presented as a single block with some information about how many pipelines are green, red and yellow with the possibility to click through and just see the pipelines for that particular group will make the interface faster and the burden on the server lower.

Although personalizing the page helps in reducing the load and improve the speed of the browser this is not a feature that works very well when you do actually need to switch between pipeline groups frequently. We use a group per application, so viewing just a single application and all it's pipelines at a time make sense.

**Comment by arvindsv** [comment]
Mentioning #1097, #1841 and #2178, so that this can be considered while rewriting the dashboard.

**Comment by benzvan** [comment]
One way to help this would be to add the ability to save dashboard views, so that you can have "application a" and "application b" as quick options in the personalize menu.

**Comment by arvindsv** [comment]
Closing in favor of: https://github.com/gocd/gocd/issues/3704
