### ISSUE TITLE
Feature Proposal: Templates for units of work smaller than "pipeline"

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#2243]
##### Issue Type

- Feature proposal
##### Summary

We have a number of pipelines that have overlap in what they do and have duplicated configuration as a result. It would be great if sets of tasks could be make into template fragments so that it was possible to create a pipeline that uses templates a, b, and d and another pipeline that uses templates a, b, c, and d.
##### Details

A simple example would be a Tomcat instance with an Apache httpd proxy for static content. Some applications would require a .war file deploy to Tomcat, some applications would require a static file deploy to the htdocs directory, some applications would require both. Rather than having 3 pipeline templates each with their own overlapping configuration, a user could create a pipeline or template that uses the tasks from a pipeline fragment template. This would be different from the command repository (unless I'm misunderstanding) in that it would be multiple tasks rather than a single command execution in a task.
##### Environment

Go-server pipelines
###### Basic environment details

Go 16.3, Java 1.8, RHEL

**Comment by BrewRunner** [comment]
+1

This is a great suggestion.  We currently have dozens of templates that are largely a copy of each other, but with minor changes to accommodate slightly different builds.  The ability to call multiple mini-templates or use an existing template plus add additional functionality specific to a pipeline would be a massive improvement.

**Comment by moonhound** [comment]
+1

Mini-templates or template-methods would make dealing with some of our more-irregular apps less of a headache.

**Comment by arvindsv** [comment]
Once config repo feature is released in the next version, some of this might not be needed. If a whole repo can be stored externally, either a plugin can be written which has smaller templates, or scripts can be written which put together templates into the expected JSON format of the JSON plugin, for instance.

Ref: https://www.youtube.com/watch?v=1AfBxCWRqD8

Let's take a closer look at this, once that is done.

**Comment by arvindsv** [comment]
> This would be different from the command repository (unless I'm misunderstanding) in that it would be multiple tasks rather than a single command execution in a task.

Your understanding is correct. Command repository is just for a single task. Your proposal is for it to be less granular (at a job or stage level).
