### ISSUE TITLE
Issue in scheduling the pipeline in queue

### ISSUE THREAD

**Issue by baskaran-md** [gocd/gocd#2253]
We are using the GoCD API for scheduling the pipeline. 
However, we had to wait for the pipeline to complete before scheduling the another one. How can we schedule the pipeline so that it gets queued up in the GoCD?

```
 curl -i https://gocd-server/go/api/pipelines/:myPipeline/schedule  \
        -X POST \
        -d "variables[ENV_VAR]=value1" \
        -H 'Confirm: true' \
        -u admin:admin
```
Getting `409 Conflict` with the below message.

```
HTTP/1.1 409 Conflict
Cache-Control: no-cache
Content-Type: text/html; charset=UTF-8
Date: Fri, 03 Jun 2016 02:46:43 GMT
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: JSESSIONID=123123123;Path=/go;Expires=Fri, 17-Jun-2016 02:46:43 GMT;Secure
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Request-Id: 8657e394-8206-4c1c-8dbc-123123123
X-Runtime: 0.009000
X-UA-Compatible: chrome=1
X-XSS-Protection: 1; mode=block
transfer-encoding: chunked
Connection: keep-alive

Failed to trigger pipeline [myPipeline] { Stage [defaultStage] in pipeline [myPipeline] is still in progress }
```
I also unchecked the "Automatic pipeline locking" in the pipeline settings.  What am I missing?

**Comment by madhurranjan** [comment]
@arvindsv  can you please take a look at this one ? Is this the expected behavior ? If so , why ?

**Comment by jkemp101** [comment]
Any progress on this?  I'm having the same issue.

**Comment by zabil** [comment]
The name's (schedule) is misleading. 
It's the same as 'triggering' and build from the UI.
And like in the ui you cannot trigger a pipeline when it's running.

**Comment by w3apps** [comment]
Is there a workaround for this? Can we use the API to use pipeline queue in the same way it does when pooling for changes from a git repo?

**Comment by vladistan** [comment]
There is a workaround that works for me.   What you do is create a dummy stage as the first stage of the pipeline.   The stage has to complete very quick so that pipeline will go into the second stage and be placed into the wait queue for the second stage.   You can have a lot of pipelines sitting in the second stage queue.

Not that you still have a problem of not being able to trigger pipeline while the first phase is preparing / executing.   This usually takes 10-30 seconds.

**Comment by w3apps** [comment]
I actually just did something similar, I created a first stage that just fetches the materials and a second stage where the important stuff happens. Now every time before I trigger the pipelines/schedule api, I trigger the stages/cancel api, and cancel the first stage (it returns 200 even if the stage si running or not).

**Comment by eraser88** [comment]
@zabil scheduling pipelines could have been a great feature. Is there a philosophy around it ?

**Comment by zabil** [comment]
@eraser88 The pipeline config API can set a timer for scheduling a build. But it sets that value for all future.

For one time trigger, It's about building the right API for scheduling. Which will be as follows
* Create a schedule request
* Respond with a link to another REST endpoint that shows the status of that request.
* Poll the new url to know the status of the trigger.

There's a lot of work around this. 

Looping in @

**Comment by Adnn** [comment]
@zabil So, it is still impossible to actually queue up Pipeline request from the GoCD API ?

**Comment by jstnkhoo** [comment]
Is there any workaround for this? the hack stated by vladistan  doesn't really work

**Comment by arvindsv** [comment]
Maybe #2329 will help.
