### ISSUE TITLE
Unable to generate artifact

### ISSUE THREAD

**Issue by hassanfarid** [gocd/gocd#2257]
Hi - I am following through guide page. link

I am setting Artifact as defined in help page. I get below error:
`05:47:33.757 [go] Start to create properties SME/28/defaultStage/1/defaultJob on satxeonphisrv [/var/lib/go-agent]`
`05:47:33.757 [go] Start to upload SME/28/defaultStage/1/defaultJob on satxeonphisrv [/var/lib/go-agent]`
`05:47:33.757 [go] The rule [my-artifact.html] cannot match any resource under [pipelines/SME]`
`05:47:33.757 [go] Uploading finished. Failed to upload [my-artifact.html]`
`05:47:33.787 [go] Job completed SME/28/defaultStage/1/defaultJob on satxeonphisrv [/var/lib/go-agent]`

**Comment by arvindsv** [comment]
Is that file generated as a part of that job, in a previous task? For instance, in that guide, the recommendation is to use the `./build` command, which does [this](https://github.com/gocd-contrib/getting-started-repo/blob/47b2644603f1cc0cbe0b5872b131dcc6655b0691/build#L15-L29) to generate a file called `my-artifact.html`. That is what is published later in the guide.

If you can paste the full console logs, I can help.

I am also going to close this issue, because it's not a GoCD issue in my opinion. If it turns out to be, then I can reopen it. I can continue to help you, even if it's closed. :)

**Comment by hassanfarid** [comment]
Thanks @arvindsv - I have used `cmake .` and `make` commands instead of `./build` mentioned in help guide.

I have pasted logs, see last few lines for error:

`07:39:49.300 [go] Job Started: 2016-06-06 07:39:49 EDT

07:39:49.300 [go] Start to prepare SME/40/Build-Project/1/make on satxeonphisrv [/var/lib/go-agent]
07:39:49.306 [go] Start to update materials.

07:39:49.307 [go] Start updating files at revision 4e3fbda14476d46eabf51638d4d4f54 from /home/go/sme.git
07:39:49.310 [GIT] Fetching changes
07:39:49.328 [GIT] Performing git gc
07:39:49.330 [GIT] Reset working directory pipelines/SME
07:39:49.330 [GIT] Cleaning all unversioned files in working copy
07:39:49.336 [GIT] Cleaning submodule configurations in .git/config
07:39:49.337 [GIT] Updating working copy to revision 4e3fbda14476d46eabf51638d4d4f54
07:39:49.341 HEAD is now at 4e3f82b Force failed Test case
07:39:49.441 [GIT] Removing modified files in submodules
07:39:49.461 [GIT] Cleaning all unversioned files in working copy
07:39:49.665 [go] Done.

07:39:49.666 [go] setting environment variable 'GO_SERVER_URL' to value 'https://127.0.0.1:8154/go/'
07:39:49.666 [go] setting environment variable 'GO_TRIGGER_USER' to value 'anonymous'
07:39:49.666 [go] setting environment variable 'GO_PIPELINE_NAME' to value 'SME'
07:39:49.666 [go] setting environment variable 'GO_PIPELINE_COUNTER' to value '40'
07:39:49.666 [go] setting environment variable 'GO_PIPELINE_LABEL' to value '40'
07:39:49.666 [go] setting environment variable 'GO_STAGE_NAME' to value 'Build-Project'
07:39:49.666 [go] setting environment variable 'GO_STAGE_COUNTER' to value '1'
07:39:49.666 [go] setting environment variable 'GO_JOB_NAME' to value 'make'
07:39:49.666 [go] setting environment variable 'GO_REVISION_SME_DEVEL_BRANCH' to value '4e3fbda14476d46eabf51638d4d4f54'
07:39:49.666 [go] setting environment variable 'GO_TO_REVISION_SME_DEVEL_BRANCH' to value '4e3fbda14476d46eabf51638d4d4f54'
07:39:49.666 [go] setting environment variable 'GO_FROM_REVISION_SME_DEVEL_BRANCH' to value '4e3fbda14476d46eabf51638d4d4f54'

07:39:49.675 [go] Start to build SME/40/Build-Project/1/make on satxeonphisrv [/var/lib/go-agent]
07:39:49.675 [go] Current job status: passed.

07:39:49.675 [go] Start to execute task: <exec command="/usr/bin/cmake" >
<arg>.</arg>
</exec>.
07:39:49.703 -- Performing Test COMPILER_SUPPORTS_CXX14
07:39:49.790 -- Performing Test COMPILER_SUPPORTS_CXX14 - Success
07:39:49.843 -- Boost version: 1.58.0
07:39:49.843 -- Found the following Boost libraries:
07:39:49.843 --   system
07:39:49.843 --   serialization
07:39:49.843 --   thread
07:39:49.843 --   iostreams
07:39:49.843 --   date_time
07:39:49.844 --   random
07:39:49.844 --   log
07:39:49.873 -- Configuring done
07:39:49.880 -- Generating done
07:39:49.881 -- Build files have been written to: /var/lib/go-agent/pipelines/SME
07:39:49.884 [go] Current job status: passed.

07:39:49.885 [go] Start to execute task: <exec command="make" />.
07:39:49.924 Scanning dependencies of target SMEServer
07:39:49.938 Linking CXX executable SMEServer
07:39:50.297 [ 50%] Built target SMEServer
07:39:50.311 Scanning dependencies of target UnitTest
07:39:50.325 Linking CXX executable UnitTest
07:39:50.725 [100%] Built target UnitTest
07:39:50.744 [go] Current job status: passed.

07:39:50.749 [go] Start to create properties SME/40/Build-Project/1/make on satxeonphisrv [/var/lib/go-agent]
07:39:50.749 [go] Start to upload SME/40/Build-Project/1/make on satxeonphisrv [/var/lib/go-agent]
07:39:50.749 [go] The rule [my-artifact.html] cannot match any resource under [pipelines/SME]
**07:39:50.750 [go] Uploading finished. Failed to upload [my-artifact.html]**
07:39:50.790 [go] Job completed SME/40/Build-Project/1/make on satxeonphisrv [/var/lib/go-agent]`

**Comment by arvindsv** [comment]
Then you need to change the artifact file. If you're not creating a file called "my-artifact.html" as a part of your make/cmake command, then it doesn't make sense to try and upload a file with that name. You can either remove that artifact declaration from the config, or change "my-artifact.html" to some other html file you generate.

At the end of the day, what you need to know is that it's a custom file, with a custom name that you either create as a part of the job or you have checked in. Then, you upload that artifact to the server (by declaring it as an [artifact](https://www.go.cd/getting-started/part-2/#concept_artifact)) and then it can be shown as a custom tab.

**Comment by hassanfarid** [comment]
I get following message, when I refer back to artifact creates in last stage of same pipeline.

Artifact 'test_output.txt' is unavailable as it may have been purged by Go or deleted externally.

**Comment by erIamshivani** [comment]
@arvindsv 
Hi, 
As a part of task I am generating artifacts in **.tar.gz** format. I am running bash command and i have all commands in `.sh` file. The command is `make clean build pkg` which generates package in "packages" folder. How can I specify that in Artifacts tab of GoCD? Can someone help with the steps required? I am absolutely new to GoCD.

**Comment by arvindsv** [comment]
@erIamshivani It probably makes sense for you to go through https://www.gocd.org/getting-started/part-1, if you're new to GoCD. It helps you understand some of the concepts (including artifacts). I'd recommend going through it step-by-step.

The documentation at https://docs.gocd.org/current/ also has some information which might be useful.
