### ISSUE TITLE
Bug: Showing dashboard errors

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#2262]
##### Summary

Seems to be a bug in the new pipeline-level errors that are shown. Here's what I see on build.go.cd (with view user):

<img width="292" alt="screen shot 2016-06-04 at 6 54 25 am" src="https://cloud.githubusercontent.com/assets/172235/15799181/a09a4df8-2a21-11e6-977c-cc448f598c14.png">

![screen shot 2016-06-04 at 6 54 19 am](https://cloud.githubusercontent.com/assets/172235/15799185/bb5b28b0-2a21-11e6-9f8f-7cb86078fa86.png)

<img width="762" alt="screen shot 2016-06-04 at 6 54 36 am" src="https://cloud.githubusercontent.com/assets/172235/15799186/bf29ad86-2a21-11e6-974b-7873cfb24f64.png">

[messages.json.txt](https://github.com/gocd/gocd/files/298785/messages.json.txt)

###### Basic environment details

* Go Version: `16.6.0 (3450-5feec49c4413035f71e8c0646502ee85287ad5d5)`
* Browser vendor and version (if relevant): `Google Chrome 50.0.2661.102`

##### Expected Results

Expected this to show the warning for that pipeline.

**Comment by arvindsv** [comment]
Related to #1842.

**Comment by GaneshSPatil** [comment]
Error icon disappears after few seconds

On the reloading dashboard page, the error icon on the pipeline seems to be disappearing after few seconds(may be 10 secs) even when errors are still there

**Comment by zabil** [comment]
Considering how we refresh the dashboard this can't be easily fixed.

Closing this in favor of using something new when the dashboard is re-designed.
https://github.com/gocd/gocd/issues/1841
