### ISSUE TITLE
Add icon in all buttons, links and navigation

### ISSUE THREAD

**Issue by ermauliks** [gocd/gocd#227]
Adding icons in meaningful places makes product more usable, Go has icons in a few places e.g. links. But still there are a lot of places where icons are still missing. What should we do is,

*  add icons in Navigation,
*  add icon in all Buttons,
*  add icon in Tabs,
*  and make all icons look similar, style-wise, probably should we go ahead with Flat icons?
*   and should we take help of [Fontello](http://fontello.com/) or [FontAwesome](http://fortawesome.github.io/Font-Awesome/).

Thoughts?

**Comment by arvindsv** [comment]
A little too vague. No conversation as well. :( Closing.
