### ISSUE TITLE
Use unique hashcode of object as etag for APIs

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2284]
##### Issue Type

- Feature proposal

##### Summary
We use etags to avoid the conflicts that arise while making simultaneous config change requests pertaining to specific objects like Pipeline Config.

Currently, we compute the etag for a specific object like this:
```
Digest::MD5.hexdigest(JSON.generate(object))
```

The above is done twice,  once when a ```GET``` is performed, And once during ```UPDATE``` to check if the header ```If-Match``` has the correct etag. So, the computation of etag incurs an overhead and degrades the performance of the API for large objects. 

##### Possible Fix

Since, each object has a unique hashcode associated with it, we can potentially use the hashcode as etag. 

Requires further analysis

**Comment by arvindsv** [comment]
Hashcode is never guaranteed to be unique. Be careful.

**Comment by ketan** [comment]
`object.hashcode()`s uniqueness is(should?) not going to be any different than `Digest::MD5.hexdigest(JSON.generate(object))`

**Comment by arvindsv** [comment]
We are talking about Java hashCode, right?

**Comment by ketan** [comment]
yes, java hashcode

**Comment by arvindsv** [comment]
The contract of hashCode is that it is (paraphrased): "Try and keep it different between objects, but if it's the same object, return the same hashCode ... *please*". Right?

So, given objects obj1 and obj2, this is what happens (and is possible and valid):

```
obj1.hashCode().equals(obj2.hashCode()) == true
obj1.equals(obj2) == false
```

This should never happen:

```
Given: obj1.equals(obj2) == true
Then: obj1.hashCode().equals(obj2.hashCode()) == false  [Should not happen]
```

**Comment by arvindsv** [comment]
The point is that hashCode can be generated without seeing all the parts of the object. "return 1" is a very valid hashCode. Not recommended.

**Comment by ketan** [comment]
I'm suggesting we build hashcode by looking at all parts of the object, in order to save on performance. Unless you have a better idea.

**Comment by arvindsv** [comment]
If you're sure that you're using all parts, then sure, there is no real difference between equals and hashCode. Then, you'll be ok. But, you need to ensure that all hashCode, all the way down the chain follows that. They need not. [Here's a test](https://github.com/gocd/gocd/blob/97905f733eec520fa25585d20cb31262a35240f8/common/test/unit/com/thoughtworks/go/domain/MaterialRevisionTest.java#L224) which is written to ensure that it doesn't, for instance.

In Java, using HashCodeBuilder is one way to make sure you're using it always, but if anyone has overridden hashCode and someone adds a field, we're in trouble.

**Comment by arvindsv** [comment]
I don't know the context of this fully. All I'm saying is that contractually hashCode does not make that promise. In this context, if you can guarantee that, sure. That's fine.

**Comment by varshavaradarajan** [comment]
@ketan, can we not use UUID.randomUUID().toString()? Perhaps having a static UUIDGenerator class?
