### ISSUE TITLE
GoCache - multiple keys for the same data

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2286]
##### Issue Type

- Bug Report

##### Summary

When data is put into the cache, a cache key is used to keep track of it. This cache is a string based on what is being added to the cache. Therefore, the cache key depends on user input. Sometimes, there will be different cache keys for the same object because of a case mismatch. 

###### Basic environment details

* Go Version: `16.6`
* JAVA Version: `1.8`
* OS: `OS independent`
* Browser vendor and version (if relevant): `N/A`

##### Steps to Reproduce

1. Create a pipeline with name: ```Case_sensitivity```
2. Run a build
3. Access the get pipeline instance API, **while its stage is building** like this ```http://ci.example.com/go/api/pipelines/case_sensitivity/instance/<counter>```
4. Access the get pipeline instance API again after completion of stage with the same url as above.

##### Expected Results

The API response returns the result that was cached when you accessed the pipeline instance API the first time and does not change subsequently.

##### Actual Results

The API response should report the correct result and state of the stage. This does not happen because there are two cache keys, namely ```PipelineSqlMapDao_cacheKeyForPipelineHistoryByName_Case_sensitivity_AndCounter_<counter>``` and ```PipelineSqlMapDao_cacheKeyForPipelineHistoryByName_case_sensitivity_AndCounter_<counter>``` . Note the case mismatch. The former cache key is being removed from the cache correctly while the latter( the one in the url) is not. The latter is the one being returned as the stale response because of the case mismatch in the url of pipeline instance API

##### Possible Fix

Make user inputs case insensitive.

**Comment by rajiesh** [comment]
Verified on 16.6.0-3590(af0f8b8ae8a4342ab748ce80224971887f018ccc) and working as expected
