### ISSUE TITLE
Feature Proposal: Webhooks and notifications

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#2287]
##### Issue Type

- Feature proposal
##### Summary

Add webhook notification plugin for generic integrations.
##### Expected Results

Notifications preference tab to include webhook. Payload would include pipeline name, executed by, label, etc. as options.

**Comment by arvindsv** [comment]
Is this similar to the [websocket notification plugin](https://github.com/matt-richardson/gocd-websocket-notifier) that @matt-richardson wrote?

**Comment by benzvan** [comment]
That kind of looks like the reverse of what I'm suggesting since it has a listener. I'm thinking of something similar to gitlab webhooks (which can execute post-commit) that can be used to send outbound messages from Go to a webservice when a pipeline completes, fails, etc.

gitlab webhooks docs:
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md

**Comment by DerFlatulator** [comment]
Any updates on this?

I have a script that is currently polling the GoCD REST API for pipeline completions but I would like to invert this, having the script listen to a webhook sent by GoCD on pipeline completion.

**Comment by arvindsv** [comment]
@DerFlatulator The closest I can think of for this is a [comment here](https://github.com/gocd/gocd/issues/217#issuecomment-287409560). Might be worth co-ordinating to see if it helps.
