### ISSUE TITLE
Pipeline Group maintenance via API

### ISSUE THREAD

**Issue by paulge1998** [gocd/gocd#2290]
##### Issue Type

- Feature proposal

##### Summary

Would like more API features added to help with scripted Pipeline group maintenance i.e Create, add role, add users to role etc etc

This would allow scripted creation of complex multi environment pipeline group set ups to save large amount of time clicking in GO UI. 

##### Environment

All GOCD API versions up to latest do not have this capability

###### Basic environment details

General requst for API enhancement to any or all GO versions and environments

###### Additional Environment Details

NA

##### Steps to Reproduce

NA
##### Expected Results
Should be able to hit API to perform the below: -
1. Create Pipeline Group by name
2. Create a riole and add users
3. Add role to pipeline group
4. permission role for pipeline group to be view, operate or admin

##### Actual Results
NA
##### Possible Fix
NA

##### Log snippets
NA

##### Code snippets/Screenshots
NA

##### Any other info
No

**Comment by zabil** [comment]
Closing this in favor of
https://github.com/gocd/gocd/issues/2404
