### ISSUE TITLE
Cannot assign resources, environments to agents in pending status but it gives no error

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#23]
#### Steps to Reproduce

1) Assign some resources or environment to the agent in pending status
#### Actual Result

It shows a success message but no change happens
#### Expected Result

Either it should update the resources or environment value for the agent or it should show a failure message

**Comment by arvindsv** [comment]
@rajiesh: Given some recent agent API changes, does this still need to be open?

**Comment by arvindsv** [comment]
Closing as stale.
