### ISSUE TITLE
SSL Certificate verify failed Mercurial

### ISSUE THREAD

**Issue by slahmar** [gocd/gocd#2303]
##### Issue Type

- Bug Report

##### Summary

I installed GoCD on two computers :
- my computer
- a remote server
On my computer I can't add my Mercurial material because it has a self signed certificate. I tried adding it to the trusted Java store but it doesn't solve the issue.
On the remote server GoCD doesn't raise this error but the polling task keeps going indefinitely without starting the pipeline.
How can I bypass this problem of certificate ?

###### Basic environment details

* Go Version: ` 16.5.0(3305-5f54cf4338eb2ff5c9f486ede6ae97e9aae51e82)`
* OS: `Windows 8`
* Browser vendor and version (if relevant): `Google Chrome 51.0.2704.84 m`

##### Steps to Reproduce

1. Create a pipeline
2. Add a Mercurial material with a self-signed certificate

##### Expected Results
The material is added and the pipeline is able to run.

##### Actual Results
Get a HG Error : "SSL certificate verify failed"

**Comment by ketan** [comment]
Not a GoCD issue.

Please make sure that the user running to (usually the system user under windows) can run the `hg clone` operation with the self signed certificate.

Usually this involves adding the [`hostfingerprints`](https://www.selenic.com/mercurial/hgrc.5.html#hostfingerprints) for your host or run `hg clone` on that instance beforehand.
