### ISSUE TITLE
Improvement: choose the next stage in your pipeline

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2304]
##### Issue Type

- Feature proposal

##### Summary

In the current implementation pipelines are linear which doesn't allow for slightly more complex deployment scenarios where you deploy a canary and in the next step want to choose whether to fully roll out the release or roll back.

In order to be able to do this it would make sense to allow for a workflow with multiple options for a next stage and label those.

For example 

- stage 1: deploy to canary
- stage 2a: deploy to all servers
- stage 2b: roll back canary

Between stage 1 and 2a and 2b would be 2 buttons to choose from.

**Comment by ketan** [comment]
Can you explain why 3 separate pipelines for each of the stages won't solve your problem?

**Comment by JorritSalverda** [comment]
That would work, but doesn't visualize nicely what happened to each release. It also makes it more difficult to explain to all the developers how to use it. And makes the homepage 3 times as busy with respect to the deployment pipelines.

**Comment by ketan** [comment]
> That would work, but doesn't visualize nicely what happened to each release.

Have you see the value stream map? [Here's an example](https://build.go.cd/go/pipelines/value_stream_map/PublishStableRelease/12) of what happened during the 16.6 release of GoCD :) (user: `view`, password: `password`)

**Comment by zabil** [comment]
@JorritSalverda 

You can use pipelines, environments, artifacts and trigger with options etc to achieve this. With the [Values Stream Map](https://docs.go.cd/current/navigation/value_stream_map.html) you'll now what's deployed.

Closing this as we won't be implementing this functionality for the sake of simplicity.
