### ISSUE TITLE
Pipeline cron timer problem 

### ISSUE THREAD

**Issue by TapioKoski** [gocd/gocd#2306]
##### Issue Type
- Bug Report

##### Summary

We are usingPipeline Configuration API go/api/admin/pipelines.
We set the cron timer by using Timer object into pipeline configuration.
In same way as other configurations of pipeline.

Configuration printed as JSON shows the timer.

But it will not be updated into GO server.
Pipelin Cron timer is empty.
No error messages.

Is this a bug or normal behavoiur?

###### Basic environment details

* Go Version: 16.5.0(3305-5f54cf4338eb2ff5c9f486ede6ae97e9aae51e82)
* JAVA Version: 1.7.0_101
* OS: Linux 3.19.0-61-generic
* Browser vendor and version (if relevant): Firefox 47.0

**Comment by ketan** [comment]
Can you provide us a reproducible steps, preferably using curl?

**Comment by TapioKoski** [comment]
Hi,

I started to create the asked steps and found the reason for the problem.

GOCD is working correctly and we had made a mistake in our java code.

This issue can be closed.

Terveisin / Best regards,

Tapio Koski, Senior Software Developer

Tieto Finland Oy
Consulting and System Integration
