### ISSUE TITLE
Should be able to define destination directory when defining a new pipeline

### ISSUE THREAD

**Issue by kmugrage** [gocd/gocd#232]
When creating a new pipeline, the following image shows up on the material step:

![image](https://cloud.githubusercontent.com/assets/3209933/3165880/3f2404cc-eb5a-11e3-9a82-bf7faee9ad27.png)

On an existing pipeline if you click on an existing material you have an option for "Destination Directory". Since Go requires different working directories when using multiple resources, this ends up being required.

![image](https://cloud.githubusercontent.com/assets/3209933/3165896/7efdb340-eb5a-11e3-8a37-51756b464c18.png)

As a Go Admin I want the ability to define a Destination Directory when creating a new pipeline so that I don't have to go edit it.

**Comment by arvindsv** [comment]
Closing. With #240 and #1404, all of this will change. Hopefully for the better.
