### ISSUE TITLE
All users are logged out after changing the role of a single user.

### ISSUE THREAD

**Issue by NickH-nz** [gocd/gocd#2324]
##### Issue Type
- Bug Report
##### Summary

After changing a users role, all users including me a logged out.
###### Basic environment details

``` plain
Go Server Version:  16.5.0(3305-5f54cf4338eb2ff5c9f486ede6ae97e9aae51e82)
JVM version:    1.7.0_101
OS Information: Linux 4.2.0-18-generic running in a Docker container
```
###### Other Environment Details

Auth System:    https://github.com/gocd-contrib/gocd-oauth-login using Google login
##### Steps to Reproduce

1. Have any number of users logged in and viewing the dashboard
2. As an administrator, under user summary change the role of any user
3. Observe that all users are logged out, including you
##### Expected Results

No users should be logged out when a role is changed. 
##### Actual Results

After changing the role of any user, all users are logged out, even if they are in the process of editing something.
##### Possible Fix

Actions should be authorised each time they are made, rather than authorising the user once on login.
If this is already the case, then there should be no reason to log users off.

**Comment by jyotisingh** [comment]
This seems to be a bug with the authentication plugin. LDAP and password file based auth seems to work as expected

**Comment by jyotisingh** [comment]
Will be fixed as a part of https://github.com/gocd/gocd/issues/2324

**Comment by arvindsv** [comment]
Closing as #2956 is done.
