### ISSUE TITLE
Sparse checkout from git repo's

### ISSUE THREAD

**Issue by armourtommy** [gocd/gocd#2327]
##### Issue Type

- Feature enhancement

##### Summary

Allow sparse checkout option from git repo's, so that a full clone is not required

**Comment by ketan** [comment]
This has already been implemented as of version 16.3.0. If this is not the case with a version after 16.3.0, you may need to provide more information on how to reproduce this problem.

See https://docs.go.cd/current/configuration/configuration_reference.html#git

**Comment by ketan** [comment]
I'm marking this issue as closed, however if you can provide a set of reproducible steps, someone can re-open it.
