### ISSUE TITLE
Server Health Messages - compiling the partial erbs

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2339]
##### Issue Type

- Bug Report
##### Summary

While building the Go Server, we make a call to inline the partial erbs so as to not compile them each time a request is made for a page to be rendered. However, during a performance run we saw that a thread was stuck at compiling a ruby block for 30 seconds. 

Reason: Some partials erbs not being inlined at the beginning degrades the compilation performance as the partials needs to be referenced each time a request for the page is made. 
For most cases, partials are **inlined** at the while the server is being built, by replacing `render :partial` with the partial html to be rendered.
However, cases such as `<%== render_json :partial -%>` (note the double equals) is not handled. 

Check: https://github.com/gocd/gocd/commit/8a71c9f8f3054fcd3dd49cf56cd7c023c060924a 
###### Basic environment details

- Go Version: `16.6`
##### Possible Fix

Handle cases where we use double equals (==) with care not to double escape the html tags and mess up rendering of the html.
##### Any other info

Depends also on the system's conditions like CPU and memory. Needs to be looked into further.
The stack trace for the thread taking 30s: https://gist.github.com/varshavaradarajan/d13c05484a59bdb8ecf5f6b4be21cce0

**Comment by arvindsv** [comment]
Closing. Server health messages no longer use ERBs.
