### ISSUE TITLE
Upgrade to TFS SDK 14.0.3

### ISSUE THREAD

**Issue by inforithmics** [gocd/gocd#234]
To connect to repository [company].visualstudio.com/DefaultCollection the TFS sdk needs to be updated to version 11 Version 10.1 cannot connect to the hosted tfs. Or can I replace the sdk version myself?

Latest available: http://www.microsoft.com/en-in/download/details.aspx?id=40785

The Error message is 

```
The SOAP endpoint https://[company].visualstudio.com/DefaultCollection/Services/v1.0/Registration.asmx could not be contacted. HTTP status: 302
```

**Comment by joshburt** [comment]
This is a big deal for our company.  We are in a hybrid configuration on and off-premise.  The need to integrate with VisualStudio online could make or break our adoption of Go.

**Comment by mikecg** [comment]
I was considering using GO at my company, and just spent a few hours troubleshooting this error to no avail, but now that I have seen this issue, I have no choice but to abandon GO. This is very disappointing.
