### ISSUE TITLE
Agent bulk edit API

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2340]
##### Issue Type

- Feature proposal

##### Summary

The current agents API does not allow for bulk edit operations that you can currently perform using the agents page. This prevents us from replacing the old agents page with one that uses nicer APIs.

Here's what I'd like to start as an initial conversation to get us thinking towards a bulk edit API —

#### Request:

```http
DELETE /go/api/agents
Accept: application/vnd.go.cd.v2+json
Content-Type: application/json

{
  "uuids": ["foo", "bar"]
}
```

#### Response:

```http
Content-Type: application/vnd.go.cd.v2+json

{
  "message": "Deleted 2 agent(s)."
}
```

#### Request:

```http
PATCH /go/api/agents
Accept: application/vnd.go.cd.v2+json
Content-Type: application/json

{
  "uuids": ["foo", "bar"],
  "agent_config_state": "Enabled|Disabled",
  "resources": {
    "add": ["linux", "java"],
    "remove": ["windows", "dot_net"]
  },
  "environments": {
    "add": ["blue"],
    "remove": ["green"]
  }
}
```

#### Response:

The a list of the [updated agent objects](https://api.go.cd/current/#the-agent-object)

```http
{
  "_links": {},
  "_embedded": {
    "agents": [
      {
        "uuid": "foo",
        ...
      },
      {
        "uuid": "bar",
        ...
      },
    ]
  }
}
```

**Comment by zabil** [comment]
This looks like the right use of ```PATCH```, we should get started with this.
