### ISSUE TITLE
Feature enhancement : Implement user authentication (htpasswd) by default

### ISSUE THREAD

**Issue by hassanfarid** [gocd/gocd#2347]
##### Issue Type
- Feature enhancement

##### Summary

Currently, the system works without setting up user accounts. In order to setup, LDAP / file authentication (a- system users, b- personal setup). Users get stuck implementing these features.

So this this implementation of user authentication should come as default, if LDAP is not used initially.

##### Expected Results
The default installation and setup of goCD should support user authentication. Which can be replaced by LDAP or system passwd file.

##### Any other info
This should help users start using other features right away, like:
+ email setup for each user
+ email alerts as described here https://docs.go.cd/current/faq/notifications_page.html

Currently, this page is not available, since by default user authentication is not setup.

**Comment by zabil** [comment]
Closing this in favor of https://github.com/gocd/gocd/pull/2096
The idea is to pull out authentication as a plugin, bundle defaults or use whatever suits.
