### ISSUE TITLE
configure the Pipeline Label with git command

### ISSUE THREAD

**Issue by loskylp** [gocd/gocd#2373]
##### Summary
As you can configure the Pipeline Label after the material version, i wish i can execute a command on the material (git)
I use git and a combination of tag and git-ref to name the versions of the packages
$git describe --tags --long --always
gives me something like 5-44-gd7aa5ce
the 5 is the last tag in history, and the 44 is the number of commits since the taged version
its very usefull

i wish i could label the builds like this

##### Environment
Pipelines with Git Material

**Comment by donaldguy** [comment]
pretty much: #1784

**Comment by arvindsv** [comment]
Yes. Closing as a duplicate. Also, #52.
