### ISSUE TITLE
Make new pipeline wizard fully capable

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#240]
It does not allow me to:
- add multiple materials
- defining parameters (which does not let me create pipelines off of template that require parameter definition), environment variables
- add multiple stages, jobs & tasks
  etc.

**Comment by aresok** [comment]
+1 and +1!

**Comment by richard-hulm** [comment]
+1

Cloning a pipeline template which depends on multiple materials would be very helpful

**Comment by martyn-t** [comment]
+1

**Comment by TrevorAMarshall** [comment]
+1

**Comment by alexsaare** [comment]
add multiple materials +1 - this is a significant limitation when using templates

**Comment by zabil** [comment]
This wizard will be deprecated and replaced by #1404

**Comment by arvindsv** [comment]
Closing as stale.
