### ISSUE TITLE
Pipeline Group API

### ISSUE THREAD

**Issue by iamsumanth** [gocd/gocd#2404]
##### Issue Type

- Feature proposal
##### Summary

Add an API to create, read, update, delete on resource `pipeline group`.

#### Request:

```
GET /go/api/admin/pipeline_groups
Accept: application/vnd.go.cd.v1+json
```
#### Response:

```
Content-Type: application/vnd.go.cd.v1+json
{
    "_links": {},
    "_embedded": {
        "groups" : [
            {
                "_links": {}, 
                "name" : "group_name",
                "authorization" : {
                    "view" : {
                        "role" : [],
                        "user" : []
                    },
                    "operate" : {
                        "role" : [],
                        "user" : []
                    },
                    "admins" : {
                        "role" : [],
                        "user" : []
                    }
                },
                "pipelines" : [
                    {
                        "_links": {},
                        "name" : "pipeline_name"
                    }
                ]
            }
        ]
    }       
}
```
#### Request:

```
POST /go/api/admin/pipeline_groups
Accept: application/vnd.go.cd.v1+json
Content-Type: application/json
{
    "name" : "group_name",
    "pipelines" : [
        {
            "name" : "pipeline_name"
        }
    ],
    "authorization" : {
        "view" : {
            "role" : [],
            "user" : []
        },
        "operate" : {
            "role" : [],
            "user" : []
        },
        "admins" : {
            "role" : [],
            "user" : []
        }
    }
}
```
#### Response:

```
{
    "_links": {},
    "_embedded": {
        "name" : "group_name",
        "authorization" : {
            "view" : {
                "role" : [],
                "user" : []
            },
            "operate" : {
                "role" : [],
                "user" : []
            },
            "admins" : {
                "role" : [],
                "user" : []
            }
        },
        "pipelines" : [
            {
                "_links": {},
                "name" : "pipeline_name"
            }
        ]
    }
}
```
#### Request:

```
GET /go/api/admin/pipeline_groups/:group_name
Accept: application/vnd.go.cd.v1+json
```
#### Response:

```
{
    "_links": {},
    "_embedded": {
        "name" : "group_name",
        "authorization" : {
            "view" : {
                "role" : [],
                "user" : []
            },
            "operate" : {
                "role" : [],
                "user" : []
            },
            "admins" : {
                "role" : [],
                "user" : []
            }
        },
        "pipelines" : [
            {
                "_links": {},
                "name" : "pipeline_name"
            }
        ]
    }
}
```
#### Request:

```
PATCH /go/api/admin/pipeline_groups/:group_name
Accept: application/vnd.go.cd.v1+json

{
    "name" : "group_name",
    "authorization" : {
        "view" : {
            "role" : [],
            "user" : []
        },
        "operate" : {
            "role" : [],
            "user" : []
        },
        "admins" : {
            "role" : [],
            "user" : []
        }
    } 
}
```
#### Response:

Updated authorization details

```
{
    "_links": {},
    "_embedded": {
        "name" : "group_name",
        "authorization" : {
            "view" : {
                "role" : [],
                "user" : []
            },
            "operate" : {
                "role" : [],
                "user" : []
            },
            "admins" : {
                "role" : [],
                "user" : []
            }
        },
        "pipelines" : [
        ]
    }
}
```
#### Request:

```
DELETE /go/api/admin/pipeline_groups/:group_name
Accept: application/vnd.go.cd.v1+json
```
#### Response:

```
{
  "message": "Pipeline group 'group_name' was deleted successfully."
}
```

**Comment by ketan** [comment]
LGTM, one nitpick — I don't see the need for `_embedded` when `:group_name` is being passed in.

`_embedded` makes sense for `index` API

**Comment by jesseadams** [comment]
Was this ever released?

**Comment by iamsumanth** [comment]
No. It hasn't been released yet.

**Comment by tonyzwei** [comment]
Hi, this feature is critical to our gocd practice. I would strongly suggest to add this feature to the coming release. Thanks very much!

**Comment by Nadiatcf** [comment]
Is there an update on this? It's really clunky needing sys admin to create a pipeline group and we were hoping to use this as a work-around.

**Comment by hanej** [comment]
> It's really clunky needing sys admin to create a pipeline group and we were hoping to use this as a work-around.

The permissions scheme in GoCD in general is horrible.  It's a very hard sell to ask your development team to move away from Jenkins, where they have access to do everything they need to do themselves, to use GoCD instead where they have to open up tickets to the local sysadmin for everything they need to do.

**Comment by brettcave** [comment]
We've found that we can create pipeline groups on the fly by creating pipelines via API that reference a group (that didn't previously exist). This works great for our integration except for when all pipelines are removed from a group and we have no way of removing that group besides manually by an Admin - leaves a lot of clutter.

**Comment by ByteFlinger** [comment]
This has actually become a bit of an issue for us. We manage GoCD instances for teams (Internally and customer) and make extensive use of Pipeline Groups with permissions.

The use case is that we seperate different functions within our project through permissions, environments and pipeline groups

So once we define a new function within the project we create the users, respective roles, environments and pipeline group. We are able to automate the whole thing except pipeline groups where we are left to create them by hand which is error prone and clunky.

An API for creating and managing pipeline group permissions would be very much appreciated

**Comment by nadiatcf** [comment]
> We've found that we can create pipeline groups on the fly by creating pipelines via API that reference a group (that didn't previously exist). This works great for our integration except for when all pipelines are removed from a group and we have no way of removing that group besides manually by an Admin - leaves a lot of clutter.

Thank you! We've implemented this workaround and it's working great for us!

**Comment by ccampanale** [comment]
👍 Bumping this feature request as it would be very helpful! Using the work around for now but doesn't offer a lot of flexibility as it only allows creation of the resource type and no modifications or permissions information.

**Comment by MHP47** [comment]
Bumping, this would be super useful

**Comment by gentzela** [comment]
Bumping this feature request.  We need this!

**Comment by ccampanale** [comment]
The most desirable feature of this resource being in the API, at least for our integrations, would be the ability to programmatically update the authorization configuration for pipeline groups. As outlined by @iamsumanth prototype, the PATCH request should allow us to assign [plugin roles](https://api.gocd.org/current/#create-a-plugin-role) dynamically to pipeline groups such that we can allow our users to control their team's access to their own pipelines. Additionally, the ability to create and eventually delete these (without the workaround of doing so by means of creating/deleting a pipeline) would be much cleaner for the long-term.

If I am missing something in the GoCD API that would currently allow for this level of interaction without needing to have an administrator manually make role authorization adjustments to pipeline groups through the UI, please let me know. Thanks!

**Comment by adityasood** [comment]
verified on 18.10.0-7703

**Comment by kamalika-majumder** [comment]
Hi Team,
Looks like the gocd yaml plugin can create pipeline groups from the scripts in git if we just declare it in config yaml. The issue I am facing is in an enterprise we are trying to group projects into pipeline groups and we donot want admins from one group create pipelines or new pipeline group by just declaring it in the yaml config.

**Comment by kamalika-majumder** [comment]
@arvindsv Is there any story in play for "Better authorization" feature.
