### ISSUE TITLE
Improvement: fetch artifact from indirect upstream pipeline

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2424]
##### Issue Type

- Feature enhancement

##### Summary

In order to be able to fetch an artifact from an upstream pipeline you have to define it as a material in the pipeline itself. However it doesn't allow you to fecth an artifact from an upstream pipeline that's indirectly (via another pipeline) referenced.

An example. If you have the following pipelines feeding into each other

A -> B > C

I would like to be able to fetch an artifact from pipeline **A** in pipeline **C** without adding pipeline **A** as a material in pipeline **C**. Doing that causes unwanted side-effects of pipeline **A** triggering pipeline **C** even if pipeline **B** fails.

**Comment by ketan** [comment]
I believe you can already do that. If you open up the fetch artifact dialog and start typing the upstream pipeline name, it'll start autofilling by suggesting possible paths to reach the upstream pipeline.

**Comment by ketan** [comment]
I'm marking this issue as closed, but please leave a note and we can re-open this.
