### ISSUE TITLE
Change developer setup docs to use gradle

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#2454]
https://developer.go.cd/16.7.0/2/2.1.html

Still mentions ./bn. See https://github.com/gocd/gocd/pull/2010 for commands, if you need them.

**Comment by ketan** [comment]
Closing a

**Comment by ketan** [comment]
Closing, opened https://github.com/gocd/developer.go.cd/issues/8 for improving the rspec docs wrt IDE support.
