### ISSUE TITLE
Change the entries in server's Info.plist to reference to new location of main class

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2455]
##### Issue Type

- Bug Report

##### Summary

Currently, the Info.plist has the following

```
<key>ClassPath</key>
 <string>$APP_PACKAGE/go.jar</string>
<key>MainClass</key>
<string>com.thoughtworks.go.server.util.GoMacLauncher</string>
```
GoMacLauncher has been moved from ```com.thoughtworks.go.server.util.GoMacLauncher``` to ```com.thoughtworks.go.server.launcher.GoMacLauncher``` 

Additionally, the built package no longer has ```go.jar``` in ```Go\ Server.app/Contents/Resources```. But, it has a ```server-launcher.jar```. Appropriate corrections need to be made in ```Info.plist``` and ```GoMacLauncher```

**Comment by ketan** [comment]
@varshavaradarajan I've pushed a fix, mind verifying?

**Comment by varshavaradarajan** [comment]
@ketan, Server starts now without any issues
