### ISSUE TITLE
Allow making cookie expiry time configurable

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2458]
##### Issue Type
- Feature enhancement
##### Summary

Currently the session cookie max age is set to 2 weeks, but should ideally be configurable to allow users to set it higher or lower per their needs.

See https://github.com/gocd/gocd/blob/e9aa072feee17e9b944ebfe207f8ded2b76e798f/server/src/com/thoughtworks/go/server/GoServer.java#L87-L93

**Comment by varshavaradarajan** [comment]
Closing via https://github.com/gocd/gocd/pull/3856
