### ISSUE TITLE
Build Tool for ./bn

### ISSUE THREAD

**Issue by CzarScar** [gocd/gocd#2472]
Hi 

I just want to set up the gocd develop environment.

However, I just run the command './bn clean cruise:prepare dist' failed. 

Just want to know ./bn is a build tool or a file?

And I have tried with gradle build. The output is

Build file '/Users/twer/pluginWork/gocd/build.gradle' line: 122

* What went wrong:
A problem occurred evaluating root project 'gocd'.
> Could not find property 'compileOnly' on configuration container.

So does this means that the doc should be updated?

Hope for someone's response.

**Comment by varshavaradarajan** [comment]
@CzarScar, The documentation is yet to be updated as we moved to gradle. Please refer to https://github.com/gocd/developer.go.cd/pull/7

**Comment by CzarScar** [comment]
@varshavaradarajan Thank you for your response. After I upgrade my gradle, the build is now running without any blocker.
