### ISSUE TITLE
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

### ISSUE THREAD

**Issue by rakesh0991** [gocd/gocd#2482]
AWS S3 Publish Issue

Hi,
    I am trying to publish my artifacts to a directory in S3.The publish is successful when no destination path is provided i.e it publishes file to bucket root directory.But whenever i try to publish to a branch inside S3,it throws error "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint."

I know its a region issue.My bucket is not US Standard.How can i specify S3 region in environment variables?

**Comment by arvindsv** [comment]
This doesn't have anything to do with this project (GoCD). Closing.
