### ISSUE TITLE
Resources separates by comma, doesn't allow start job

### ISSUE THREAD

**Issue by diego522** [gocd/gocd#2485]
Hi all, first of all, let me explain my environment:
I have 6 agents and I have them separated in two groups, every group associated a specific resource
 - agents-green
 - agents-blue

I have a pipeline associated to an environment and the agents are associated too. Inside this pipeline I have a stage and inside this stage I have a job that I need run in all my agents.
To do that, in the job settings, in the resources label, I put the resources separated by comma (agents-green, agents-blue), settings are saved well.

The problem is when I try to run the pipeline (pressing the trigger button), it doesn't start, it never colored in yellow (I don't get errors and anything).

Another thing is, I don't have access to GO server and Go agents log because I'm not the machines's owner.

My solution was create a new resource with the all agents, and I put the new resource name in the Job settings.

My questions is, Is an issue that the comma separations doesn't work well or I did something wrong.?

Thanks a lot.

**Comment by ketan** [comment]
> To do that, in the job settings, in the resources label, I put the resources separated by comma (agents-green, agents-blue), settings are saved well.

That tells GoCD that the job needs an agent that has both `agents-green` AND `agents-blue` to run. I don't suppose you have an agent that is marked with both resources?

If you're looking to run it on either of the set of agents, perhaps remove the resource on the job?

**Comment by diego522** [comment]
I don't have agents marked with both resources

My agents are A,B,C -> (green resource) , D,E,F -> (blue resource), are different machines.

I need to run my job in all machines (all agents). For this reason y select "Run on all agents" option in the Job settings.

**Comment by zabil** [comment]
As @ketan mentioned when your job requires the resources "agents-green, agents-blue" it will run only on agents marked with both "agents-green, agents-blue".

You can read about that here
https://docs.go.cd/current/configuration/managing_a_build_cloud.html#matching-jobs-to-agents

If the environment has only has green and blue agents and you want to run on all agents, you can leave the resources field empty.
Or
Like what you did i.e. use a separate resource tag.
