### ISSUE TITLE
http://dl.bintray.com/gocd/gocd-deb/ not up-to-date

### ISSUE THREAD

**Issue by cv** [gocd/gocd#2492]
##### Issue Type

- Bug Report

##### Summary

http://dl.bintray.com/gocd/gocd-deb/ hasn't been updated since 16.1. Are the debs being generated elsewhere, or are they not being generated anymore?

**Comment by arvindsv** [comment]
It's moved. Documentation has been updated for [server](https://docs.go.cd/current/installation/install/server/linux.html) and [agent](https://docs.go.cd/current/installation/install/agent/linux.html). Where did you come across the old repo? I wonder what we can do to turn it off.

**Comment by jsilverman-blispay** [comment]
Hi. I know you've closed this but there are still some issues around this.

We have the old repo URL listed in a puppet config in our environment. I'm sure others are in a similar situation -- i.e. local configs or documentation that don't know the gocd repo URL has changed. Perhaps a note in the documentation indicating that the server moved?

And, better yet, include a note on the old repo URL itself. Currently (as of 2016-09-21) the URL http://dl.bintray.com/gocd/gocd-deb/ results in a message "The requested path was not found."

**Comment by arvindsv** [comment]
@jsilverman-blispay: Unfortunately, we never had too much control over that bintray repository. It was automatically created and updated, and we cannot include a note on it.

I can (or you can!) add a note in the documentation. Where do you think it's appropriate?  Somewhere [here](https://github.com/gocd/docs.go.cd/tree/master/installation/install)? If so, please feel free to submit a pull request and sign the [CLA](https://www.go.cd/cla) (one time only). Thank you.
