### ISSUE TITLE
Unable to delete agents when there are multiple in the same box

### ISSUE THREAD

**Issue by amirdhagopal** [gocd/gocd#2493]
##### Issue Type

- Bug Report

##### Summary

Installed multiple agents on the same machine as per the documentation, [Install multiple agents on the same machine](https://docs.go.cd/current/advanced_usage/admin_install_multiple_agents.html) 

Later, when tried to delete the agent from goserver UI, it does not delete the agent. The corresponding agent service is still running in the box, and all the folders remain as they are.

What is the clean way to delete the agent in this case?  Even some script similar to the setup script in the documentation will do.

The goagents are in CentOS 7 box.

**Comment by zabil** [comment]
Deleting or disabling the agents from the UI will not delete the folders created in the agent.
You'll have to manually do that.

**Comment by amirdhagopal** [comment]
Thanks Zabil.

As I understand, the following statement should clear all traces of the agent from the machine without any issues.

`rm -rf /etc/init.d/go-agent-1 /usr/share/go-agent-1 /etc/default/go-agent-1 / var/{lib,log}/go-agent-1 `

Can this be added to the documentation?

**Comment by ketan** [comment]
> Can this be added to the documentation?

Yes, would you like to submit a PR?

**Comment by zabil** [comment]
You can send the PR to this repo http://github.com/gocd/docs.go.cd
