### ISSUE TITLE
Check: Rollover of logs on Windows

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#2494]
Does it work?

The default configuration seems to be:

```
log4j.appender.FileAppender=org.apache.log4j.RollingFileAppender
log4j.appender.FileAppender.File=go-server.log
log4j.appender.FileAppender.MaxFileSize=10240KB
log4j.appender.FileAppender.MaxBackupIndex=50
log4j.appender.FileAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.FileAppender.layout.conversionPattern=%d{ISO8601} %5p [%t] %c{1}:%L - %m%n
```

Which should keep 50 log files of 10MB each (named go-server.log.1, go-server.log.2, etc). But, does it really work?

**Comment by padmam** [comment]
Similar issue noticed, 

The log rotation in windows is not consistent. And, when the `go-server.log.2` is created, the `go-server.log.1` is not available anymore. The file type of the rotated log files is set to `2 File`, instead of file type to `log`.

Error in the wrapper.log :

> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR A "org.apache.log4j.RollingFileAppender" object is not assignable to a "org.apache.log4j.Appender" variable. 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR The class "org.apache.log4j.Appender" was loaded by 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR [nuget [2]] whereas object of type 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR "org.apache.log4j.RollingFileAppender" was loaded by [WebAppClassLoader=1340235335@4fe25e47].
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR Could not instantiate appender named "FileAppender". 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR A "org.apache.log4j.RollingFileAppender" object is not assignable to a "org.apache.log4j.Appender" variable. 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR The class "org.apache.log4j.Appender" was loaded by 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR [nuget [2]] whereas object of type 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR "org.apache.log4j.RollingFileAppender" was loaded by [WebAppClassLoader=1340235335@4fe25e47].
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR Could not instantiate appender named "ShineFileAppender". 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR A "org.apache.log4j.RollingFileAppender" object is not assignable to a "org.apache.log4j.Appender" variable. 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR The class "org.apache.log4j.Appender" was loaded by 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR [nuget [2]] whereas object of type 
> INFO | jvm 1 | 2016/08/15 09:40:12 | log4j:ERROR "org.apache.log4j.RollingFileAppender" was loaded by [WebAppClassLoader=1340235335@4fe25e47].

Steps to reproduce:

Change the log4j.properties file by changing the` log4j.appender.FileAppender.MaxFileSize=10KB` under "Rolling log file output.." and restart the go-server. After every restart new log file is created. If the go-server is running, then the existing go-server.log file is appended, without log rotation.

**Comment by rajiesh** [comment]
Moved to logback as logging framework for GoCD server and agent with this commit - https://github.com/gocd/gocd/commit/f501efc5a00519461fdf7d93081f83fcca7df2b9

RollingFilePolicy in logback.xml takes care of rolling of files in windows. Verified on 17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1)
