### ISSUE TITLE
Link to configure plugins is difficult to find

### ISSUE THREAD

**Issue by savaki** [gocd/gocd#2503]
##### Issue Type
- Bug Report
##### Summary

When looking at the plugins page, it doesn't appear that plugins are configurable.  The positioning of the gear icon leads one to believe it's an image that's part of the title rather than an active button to be clicked.
##### Environment

Happens in all environments
###### Basic environment details

Again, happens in all environments.
###### Additional Environment Details

n/a
##### Steps to Reproduce
1. Install any plugin that may be configured like the google-oauth-plugin
2. Go to the admin -> plugins page
3. Notice the google oauth plugin is present
4. Unless someone has told you, a settings icon in the title bar to the left of the name is not something you'd expect to click
##### Expected Results

Gear should be separated from the title and preferable right aligned in a more traditional settings location.  Even better, having text that explicitly said configure and was underlined would be better.
##### Actual Results

I spent a lot of time hunting for the plugin configuration and eventually went to the wrong place because I couldn't find the settings link.
##### Possible Fix

See above
##### Log snippets

n/a

**Comment by GaneshSPatil** [comment]
@savaki -- This issue has been fixed as part of new plugins SPA.
The plugin settings icon is right aligned.

![screen shot 2018-12-17 at 5 44 10 pm](https://user-images.githubusercontent.com/15275847/50086583-87fb1200-0223-11e9-8b45-d6b8bed9be06.png)
