### ISSUE TITLE
UI text tweak - change "Never Cleanup Artifacts" to something less confusing

### ISSUE THREAD

**Issue by sriramnrn** [gocd/gocd#2506]
##### Issue Type
- Bug Report
##### Summary

The text "Never Cleanup Artifacts" is a bit confusing when read alongside "Fetch Materials" and "Clean Working Directory". This text may give the impression that after artifacts are uploaded, this checkbox may permit them to remain in the workspace.

Some alternatives:
"Preserve Uploaded Artifacts during server-side auto-cleanup"
"Keep Uploaded Artifacts during server-side auto-cleanup"
"Preserve Uploaded Artifacts during server-side auto-cleanup"

I considered the following, and felt they'd be confusing as well:
"Never Cleanup Uploaded Artifacts"
"Preserve Uploaded Artifacts".

As I discovered during a recent GoCD training, there are people who take some time to understand the difference between artifacts kept locally vs the server side.

I considered sending a pull request, but I see that there are various locations in code where "neverCleanupArtifacts" is used, so I wanted to discuss this first.

**Comment by arvindsv** [comment]
I agree. Also, "Clean working directory" - many people seem to think that GoCD won't clean up before every build starts unless this is checked. But, as you all know, this empties the working directory and re-clones every material before starting off a job run.

/cc @maheshp @naveenbhaskar

**Comment by GaneshSPatil** [comment]
@akshaydewan @viraj2712 @vrushaliwaykole -- can we consider this as part of the pipeline config SPA?

**Comment by akshaydewan** [comment]
Yes, thank you! I've referenced this issue in the relevant story for Stage level settings
