### ISSUE TITLE
Unable to start Go Server service on windows

### ISSUE THREAD

**Issue by kakimanitrinath** [gocd/gocd#2508]
![f4b9d22a-5369-11e6-873d-7319b27b3a68](https://cloud.githubusercontent.com/assets/17175560/17287282/5535cae2-57ec-11e6-8af5-da4c578ad433.jpg)

**Comment by zabil** [comment]
Please provide information that's required like versions etc.
These are asked when you create a new issue. Please keep those section with the info.

**Comment by kakimanitrinath** [comment]
Version number is 0.6.16, I am a new user to Go and downloaded the latest version and installed. After installation is completed, i couldn't able to start the service.

**Comment by zabil** [comment]
Try with 16.7.0 which is the latest version.
https://www.go.cd/download/

There was a fix for windows installers
https://www.go.cd/releases/#16.7.0

**Comment by kakimanitrinath** [comment]
Hi I have updated to 16.7.0 and Go Server is started. However on same server I installed Go Agent. Now Agent is not starting. Please help.

**Comment by kakimanitrinath** [comment]
After giving Https:// on server name instead http it started. Thanks for your help
