### ISSUE TITLE
No username and password box in Go 16.7.0 for Material Git

### ISSUE THREAD

**Issue by kakimanitrinath** [gocd/gocd#2511]
I am using Go 16.7.0 version and im a beginner. I have selected Git as material type. There are no text box for user name and password. Attached the image.
![git_go](https://cloud.githubusercontent.com/assets/17175560/17294915/32b65c36-5817-11e6-98cb-c3af0716d94f.jpg)

**Comment by ketan** [comment]
Git uses basic auth so you're expected to provide the username and password as part of the URL.

`https://user:pass@host/path/to/repo.git`

**Comment by kakimanitrinath** [comment]
Hi Ketan,

Sorry i didn't get it. Is it like https://username:password/github.com/xyz.git. Please confirm

**Comment by arvindsv** [comment]
Yes. https://username:password@github.com/xyz.git should do.

Related issue is: https://github.com/gocd/gocd/issues/1696

**Comment by arvindsv** [comment]
Try it with: `git clone` first, locally. If that works, it should work in GoCD.
