### ISSUE TITLE
Rename API links

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2517]
Rename all api links in representers to https://api.go.cd from http://api.go.cd

**Comment by arvindsv** [comment]
Is this the same as https://github.com/gocd/gocd/pull/2378, without the changes to the footer?

**Comment by ketan** [comment]
Without the `/current` in the URL, since the redirects are already in place.

**Comment by arvindsv** [comment]
Can be closed now? Since #2521 is merged.
