### ISSUE TITLE
JSON API not operational: 'The resource you requested was not found'

### ISSUE THREAD

**Issue by Byron-TW** [gocd/gocd#2529]
##### Issue Type

- Bug Report

##### Summary

Our GoCD management is based on using the [GoCD pipeline-config JSON API](https://api.go.cd/current/#pipeline-config), and will issue `GET` and `PUT` requests.

We used GoCD version 16.3.0 beforehand, and everything worked as expected. After upgrading to 16.7.0, the system will neither get data, nor does putting configuration data have any effect.

Please note that it does not make a difference whether `Accept: application/vnd.go.cd.v1+json` or `Accept: application/vnd.go.cd.v2+json` is used.

###### Basic environment details

* We use [this docker image](https://hub.docker.com/r/gocd/gocd-server/) v16.7.0

It comes with the following versions:

* Go Version: `16.7.0 (3819-b0b9921bdea58101121cc181d697355177d2f197)`
* JAVA Version: ``
  * Please note that the snippet above didn't work for me
  * Thus I used the following
  ```bash
    root@0f7a54ad381a:/tmp# java  -version
    java version "1.7.0_101"
    OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)
    OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)  
  ```

##### Steps to Reproduce

```bash
curl -u "${user}:${pass}"\
  -H 'Accept: application/vnd.go.cd.v2+json'\
  "http://our-host/go/api/admin/pipelines/$pipeline"
```

where `$pipeline` is a name like `prefix.suffix`.

The expected output would be a JSON with all pipeline configuration for the specified one, the actual output is the following:

```json
{
  "message": "The resource you requested was not found!"
}
```

Interestingly, if I change the pipeline name from `prefix.suffix` to `prefix_suffix`, it will actually show the following:

```json
{
  "message": "Either the resource you requested was not found, or you are not authorized to perform this action."
}
```

This might mean that the resource name used previously (i.e. `prefix.suffix`) was actually correct, even though it made different claims.

I am skipping the PUT calls here, as I think they cannot work without get working as expected.

##### Log snippets
There seems to be no note of the GET calls in the log.

**Comment by maheshp** [comment]
@Byron-TW this is a valid issue and we have put a fix for this as part of https://github.com/gocd/gocd/pull/2531. This fix should be available as part of next release 16.8 which is due soon.

**Comment by rajiesh** [comment]
Verified on GoCD version 16.8.0 (3918-96bc1ad0bdcdd420b44e1552cfa1ab96936adf97), issue fixed

**Comment by Byron-TW** [comment]
Great to hear ! When do you think the docker images will be updated ? If that should take a while, I would consider just setting up an image on my own, as we need this update ASAP.
Thank you.

**Comment by arvindsv** [comment]
@Byron-TW: It should happen fairly soon once a 16.8 release candidate is decided. There is a commit that is going in now, which should be the one of the last ones for 16.8.

**Comment by Byron-TW** [comment]
@arvindsv Thanks, good to know. I was fooled by [the tag for 16.8 then](https://github.com/gocd/gocd/tree/16.8.0).

**Comment by ketan** [comment]
I'm not sure how that tag came into existance, removing it

**Comment by peterd550** [comment]
I am gertting this issue and I have upgraded to 16.8.0
im running this
https://api.go.cd/16.8.0/#get-pipeline-config

receiving this output
{
  "message": "Either the resource you requested was not found, or you are not authorized to perform this action."
}

Is there an ETA for this fix?

**Comment by ketan** [comment]
@peterd550 — can you provide us a curl request and response?

**Comment by peterd550** [comment]
Thanks for the quick response
Im using
curl 'http://hostname:8153/go/api/admin/pipelines/Release' \
      -u 'user:password' \
      -H 'Accept: application/vnd.go.cd.v2+json' \
      -i
and response is 
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   118    0   118    0     0   2565      0 --:--:-- --:--:-- --:--:--  2565HTTP/1.1 404 Not Found
Date: Mon, 29 Aug 2016 05:19:08 GMT
Set-Cookie: JSESSIONID=qfi437kemrlb8r58uy5emslm;Path=/go;Expires=Mon, 12-Sep-2016 05:19:08 GMT;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: chrome=1
Content-Type: application/vnd.go.cd.v2+json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 9d697961-9010-4e8c-a6fc-b0c9d872a531
X-Runtime: 0.009000
Transfer-Encoding: chunked

{
  "message": "Either the resource you requested was not found, or you are not authorized to perform this action."
}

**Comment by varshavaradarajan** [comment]
@peterd550, I verified a bunch of combinations and this particular error only comes when the pipeline is not found in the config. And its not even a case sensitive name issue. Are you sure that the pipeline exists?

Can you please try it with different pipelines in your config and check if this is the case for them as well?

**Comment by peterd550** [comment]
Thanks 
I have looked at the config XML and I can see this
  <pipelines group="Release">
    <pipeline name="CC-R" isLocked="true" template="CC_Build">
      <params>

**Comment by peterd550** [comment]
<pipelines group="Release">
    <pipeline name="CC-R" isLocked="true" template="CC_Build">
      <params>

**Comment by peterd550** [comment]
GGGRRR ok I can do it on the `<pipeline name="CC-R"`
Want to do it on the 
`<pipelines group="Release">`

**Comment by ketan** [comment]
@peterd550 — that's a pipeline group. Perhaps you're looking for the pipeline group api (https://api.go.cd/current/#pipeline-groups)?

**Comment by peterd550** [comment]
Thanks for that

what time trying to do is
in a pipeline group I have a number of piplelines

I need to update a parameter
The parameter has the same name in all pipelines
`<param name="GIT_BRANCH_CC">release-September</param>`

**Comment by varshavaradarajan** [comment]
@peterd550 , we do not have a group update API which will update some part of the pipeline config for all pipelines. You can have a script which will use the pipeline group api to get the list of pipelines and update each pipeline config in a loop.

**Comment by peterd550** [comment]
Ok is there a way of updating just one parameter in a pipline?

**Comment by varshavaradarajan** [comment]
@peterd550, you will have to do a get-pipeline-config before an update, you will get a JSON response along with the etag. In your script, edit the json response to change only the parameter and pass the whole thing as data to the update pipeline config call along with the etag.

**Comment by peterd550** [comment]
hey guys
I run my script and Im not getting
`HTTP/1.1 200 OK
Content-Type: application/vnd.go.cd.v2+json; charset=utf-8
ETag: "e064ca0fe5d8a39602e19666454b8d77"`
at the top is just the
`{
  "_links": {
    "self": {
      "href": "https://ci.example.com/go/api/admin/pipelines/my_pipeline"
    },`

**Comment by peterd550** [comment]
Hey guys is there an easier way then this?
It would be easier just update the paramater via the config xml in the GUI

**Comment by varshavaradarajan** [comment]
@peterd550, currently we do not support bulk updating of all pipelines in a group. The script is one way of doing it. If it is not working out for you, I can take a look at the script. You can attach the script with the sensitive information masked out. If not, updating it through the UI is easy but manual.
