### ISSUE TITLE
Plugin-level config is not easily change-able

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#2530]
It is not in the config XML. It's in the DB. Is there something we can do? Provide it as an API. Should we be messing with plugin data? If not, how can a user bootstrap that data (unattended). Needs discussion.

**Comment by maheshp** [comment]
While working on the PluginInfo [API](https://api.go.cd/current/#plugin-info) one of the thoughts was to have an API which allows CRUD operations on Plugin.

**Comment by varshavaradarajan** [comment]
Plugin settings API is available since 17.8.0 to configure plugin settings - https://api.gocd.org/current/#plugin-settings.
