### ISSUE TITLE
Feature enhancement: Notification filters based on pipeline groups

### ISSUE THREAD

**Issue by qtiki** [gocd/gocd#2538]
##### Issue Type

- Feature enhancement
##### Summary

Provide the possibility to add notification filters based on pipeline groups in addition to individual pipelines.
##### Any other info

In an environment with many different pipeline groups it is very painful to setup filtering for all pipelines in a specific group. Even more difficult is trying to keep up with the filters manually when multiple users have access to add new pipelines to the group.

**Comment by cholmes1111** [comment]
We would like this feature as well.
