### ISSUE TITLE
FreeBSD port for gocd / questions about the build process

### ISSUE THREAD

**Issue by beauby** [gocd/gocd#255]
Hi there,

I am in the process of making a FreeBSD port of gocd. In order to do this, I started skimming through the build process of gocd, and I have a few questions:
* Is the build process fully documented somewhere? I couldn't find any such resource but I have to admit I haven't spent hours on this.
* What is the reason behind the shipped jruby? Couldn't this be a simple dependency?
* Wouldn't it make sense to separate the build processes for go-server and go-agent?
* Currently the building process goes through a script (`bn`), which calls another script (`tools/bin/go.jruby`), which then calls `buildr`. I am not familiar with `buildr` but isn't this a bit cumbersome? (Here is a PR that allows for a direct build, calling `buildr cruise:prepare`: https://github.com/gocd/gocd/pull/258)

Cheers,

Lucas

**Comment by arvindsv** [comment]
Closing: #2010.

**Comment by rawzone** [comment]
@beauby did you ever get this running under FreeBSD?

**Comment by beauby** [comment]
@rawzone Nope, sorry. I fixed some issues upstream in jnr-ffi but then encountered other issues and abandoned. Best of luck!
