### ISSUE TITLE
Missing validation errors on pipeline_config API

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#2553]
##### Issue Type
- Bug Report

##### Summary

On pipeline_config update if validation fails in any of ```Tracking tool, Environment Variables, Parameters, Artifacts, Tabs, Properties``` the API returns a error response ```422``` and a generic error message. This does not give enough information bout the reasons for validation failure.

Return validation error messages for the above mentioned entities.

**Comment by rajiesh** [comment]
Validation for `properties` do not have the specific error on the element, just generic error at the pipeline level, need to be fixed

**Comment by varshavaradarajan** [comment]
Non-existent roles are validated but nor represented. @GaneshSPatil is looking into it

**Comment by varshavaradarajan** [comment]
Timer spec validation. Refer to the ```TimerConfig#validate()``` Error added but copied. @GaneshSPatil: similar to the parameter validation. Check your branch ```arguments-validation```

**Comment by rajiesh** [comment]
Verified on GoCD version 16.11.0 (4185-e7acc53aac8bb5ad2a7f306ca8f3e752855d844b), working as expected

**Comment by varshavaradarajan** [comment]
Mask password field for svn, tfs and perforce materials.
