### ISSUE TITLE
How to delete artifacts based on days

### ISSUE THREAD

**Issue by Sanket0510** [gocd/gocd#2555]
##### Issue Type

- Feature proposal
- Feature enhancement

Currently for GO CD we have feature of deleting artifacts once certain amount of memory is exceeded in server.
Consider a scenario in which we have more than 1 services pipelines. Now if we are going to use this feature how can we make sure it is going to delete old artifacts only. Do we have any surety for this??

Is it possible that we have functionality which will take number of days in places of memory so it is going to confirm delete older artifacts only??
##### Summary

Currently for GO CD we have feature of deleting artifacts once certain amount of memory is exceeded in server.
Consider a scenario in which we have more than 1 services pipelines. Now if we are going to use this feature how can we make sure it is going to delete old artifacts only. Do we have any surety for this??

Is it possible that we have functionality which will take number of days in places of memory so it is going to confirm delete older artifacts only??
##### Environment

production
###### Basic environment details

- Go Version: 16.1.0
- JAVA Version: 1.8
- OS: UNIX
- Browser vendor and version (if relevant): Google Chrome

**Comment by arvindsv** [comment]
Closing as stale.
