### ISSUE TITLE
PATCH support on enviroments API

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#2566]
##### Issue Type

Feature enhancement

##### Summary

The current API

https://api.go.cd/current/#update-an-environment

Only supports a PUT operation requiring you to make changes to the entire resource. This makes it hard to use the API when you need to make small modifications like adding a pipeline or agent to the environment. 

A PATCH API for this resource will require only posting the pipeline or agents being added or removed from the environment.

For e.g.

```http
PATCH /go/api/admin/environments/environment_name
Accept: application/vnd.go.cd.v2+json
Content-Type: application/json

{
  "pipelines": {
    "add": ["build", "smoke"],
    "remove": ["sample"]
  },
  "agents": {
    "add": ["linux"],
    "remove": ["windows"]
  }
}
```

This API can also be used on the current environment config UI to reduce conflicts while saving

**Comment by rajiesh** [comment]
Verified on GoCD version 16.10.0 (4129-e51ab2ff4bc66d88a93254c209ee60e42a1112bc), working as expected
