### ISSUE TITLE
First clone by go-server fails for git material if the URL is http(s)

### ISSUE THREAD

**Issue by gunnarx** [gocd/gocd#2571]
##### Issue Type

- Bug Report

##### Summary

Initial clone of Material by go-server fails for git material if the URL is http(s) because it uses --depth flag

###### Basic environment details

* Go Version: 16.3.0(3183-60d6fd31f00527da00f2affdd8f7f7732e7be103)

###### Additional Environment Details

Note that Checkbox "Shallow clone" was *unchecked* for this material.
(I also tried explicitly adding ShallowClone="false" to cruise-config.xml)

Note that /var/lib/go-server/pipelines/flyweight/* was cleared completely

##### Steps to Reproduce

1. Define a new pipeline with material URL http://<repo url>
2. Press Play button

##### Expected Results
* Pipeline should be scheduled on an agent

##### Actual Results
* Pipeline is not scheduled
* After a few seconds the pipeline box goes back to a white box saying "No historical data"
* Error and warning messages at lower right says:
```
Modification check failed for material: URL: http://<repo-url>.git, Branch: master [Aug-18 18:21:26]
Failed to run git clone command 
STDERR: Cloning into '/var/lib/go-server/pipelines/flyweight/1f96501d-e9b4-4715-bc35-925d95efb253'... STDERR: fatal: dumb http transport does not support --depth
```

##### Possible Fix
* Honor the "shallow clone" = false (unset checkbox) also for the go-server clone by doing a full clone ?
or
* Use shallow clone only if URL is git://   ?
(By the way... might something also fail on the agent if shallow clone is checked for an http(s) URL?)

##### Log snippets

sorry

##### Code snippets/Screenshots

sorry

##### Any other info

sorry

**Comment by varshavaradarajan** [comment]
@gunnarx , for go-server 16.3.0, the shallowClone checkbox that you see in the material form is for agents. By default, on the server, in the flyweight folder, its always going to be a shallow clone. 

We have changed this behaviour and replaced the shallow clone with no-checkout in the 16.7 release.

Will look into why the clone on the server side for a material with http(s) fails and update the issue.

**Comment by varshavaradarajan** [comment]
@gunnarx , do you mind telling us what version of git that the GoCD server uses?

As you can see from the error, ```STDERR: fatal: dumb http transport does not support --depth```,
The git server is using the dumb protocol. This has been superseded by the smart HTTP protocol since the release of git 1.6.6.

The minimum version of git that we support is 1.7.1 with the smart http protocol. 

Now, the problem could be the git version or the configuration of the git server that you are using as per [this](https://git-scm.com/book/en/v2/Git-Internals-Transfer-Protocols) documentation.

**Comment by gunnarx** [comment]
$ git --version

**Comment by gunnarx** [comment]
@varshavaradarajan  I guess the problem was on our end but thanks for the great information.  Without it we would be stumped.  

It seems that the git server that our Go server was contacting was only serving up dumb HTTP, as you said.  Everything is now working but with git:// protocol instead.  Since we switched over the problem pipelines to git:// protocol I can't confirm or deny anything more about shallow clones using (smart) HTTP, but I imagine there is no reason to think it does not work from Go.CD perspective so let's close it.
Sorry for the noise and thanks again.

**Comment by sudhanshu5533** [comment]
**Failed to run git clone command** error reported by GO-Agent. We are using BitBucket as repository. 
Sometimes it's works and sometime it's returns the error **Failed to run git clone command** Please help. This is appearing very frequently.

**Comment by adityasood** [comment]
@sudhanshu5533 for the times when it fails are you able to manually run a git clone for the bitbucket repository inside the agent box? Could this be a network or connectivity issue? 

The GoCD agent just runs a git clone and does nothing special.

**Comment by sudhanshu5533** [comment]
Yes @adityasood , If I run again without any changes then it's cloning. I have done manually in my local machine by using powershell to reproduce the issue and found the sometimes it's returning 401 and if again I will run the same git clone command then it's able to clone in my local machine.  I am sharing the power shell logs. 

STDERR: error: RPC failed; HTTP 401 curl 22 The requested URL returned error: 401
STDERR: fatal: The remote end hung up unexpectedly
Failed to run git clone command

**Comment by adityasood** [comment]
@sudhanshu5533 hmm, it does not look like a GoCD issue since you are getting 401 even when you run the command through Powershell.

What is your git client version? You can try upgrading your git client to the latest version and see if that helps.

**Comment by sudhanshu5533** [comment]
@adityasood My Git Client version is 2.7.4. It's a intermittent issue which I am facing.

**Comment by sudhanshu5533** [comment]
@adityasood  But In my local machine I am using updated version of Git and same issue is occurring in my local machine.

**Comment by adityasood** [comment]
@sudhanshu5533 I would suggest you check with BitBucket team in such case

**Comment by sudhanshu5533** [comment]
@adityasood Thanks for your suggestion. That was a Bug in Bitbucket and their engineering team has identified and resolved the issue.

**Comment by harikrishna309** [comment]
@sudhanshu5533  I am also facing the same issue. could you share me the solution for this issue
