### ISSUE TITLE
Issue with Gradle build script on Windows

### ISSUE THREAD

**Issue by padmam** [gocd/gocd#2574]
##### Issue Type
- Bug Report
##### Summary

Gradle build script have issue while running them on Windows
###### Basic environment details

- Go Version: `16.7.0`
- JAVA Version: `1.8.0_101`
- OS: `Windows 8.1 64 bit`
##### Steps to Reproduce

1) When tried to follow the steps provided in the developers document i.e. https://developer.go.cd/current/2/2.1.html to use gradle script to setup development environment on windows machine. 

2) Running gradle script on windows machine do not successfully install the agentGenericZip and ServerGenericzip on the windows machine.

List of issue:
1. Fixed via https://github.com/gocd/gocd/pull/2741 ~~server/build.gradle line 371: 
   setExecutable project.rootProject.file("tools/rails/bin/jruby"). 
   jruby.bat is not automatically selected in windows.~~
2. server/inline-partials.rake line 77. The path to partials is a mix of forward and backwards slashes which fails with some usages. Forcing everything to be a forward slash got us past this issue.
3. Fixed via https://github.com/gocd/gocd/pull/2741  ~~buildSrc/src/main/groovy/com/thoughtworks/go/build/WindowsPackagingTask.groovy line 62: 
   commandLine "bash", "-c", "set -o pipefail; curl --silent --fail ${jreLocation()} | tar -zxf - -C ${buildRoot()}" 
   buildRoot is cast to a string containing backslashes to separate path components. bash and tar expect forward slashes.~~
##### Expected Results

Gradle script should be executed on windows OS.

**Comment by brbutler** [comment]
There's potentially a new issue with the change to gradle 3.0.  I'm hitting the problem described here:
https://discuss.gradle.org/t/build-fails-with-unable-to-process-incoming-event-progresscomplete-progresscompleteevent/18434/25

According to this conversation, and update to 3.1 might resolve the issue.

**Comment by ketan** [comment]
@brbutler — would you mind upgrading locally `./gradlew wrapper --gradle-version 3.1` and letting us know if it works? We don't have reservations upgrading if someone could confirm if all is well.

**Comment by brbutler** [comment]
@ketan - Thanks for the upgrade instructions.  It turns out I still hit this problem with 3.1.  In light of that, there's no urgency in updating and I'll see if I can narrow down a repro. For now, I can workaround by always using --debug in local builds, and fortunately we don't hit this in our lab.
