### ISSUE TITLE
Provide Git and git-gc stats in support api 

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2578]
##### Issue Type

- Feature enhancement

##### Summary

The current `/go/api/support` does not contain any information about the `ConfigRepository`. I'd like to see the following information in the api support file —

* git gc stats `git.gc().getStatistics()`
* number of git commits

**Comment by rajiesh** [comment]
Verified on 16.9.0 (3981-aa488f618ca6c06932d605bf99dded2ffd604e9e) and the support api provides commit count and the git-gc stats
