### ISSUE TITLE
"The package is of bad quality" message while installing go-server deb on ubuntu 

### ISSUE THREAD

**Issue by lucafaggianelli** [gocd/gocd#2585]
##### Issue Type

Bug Report
##### Summary

When installing Go Server on Ubuntu 14.04 via software center it complains about missing maintainer address and dir-or-file-in-var-run
###### Basic environment details
- Go Version: 16.8.0-3929
- JAVA Version: --
- OS: Ubuntu 14.04
- Browser vendor and version (if relevant): --
##### Steps to Reproduce

1. Download server .deb from https://www.go.cd/download/
2. Open .deb with Ubuntu Software Center
3. Click Install
##### Expected Results

The install procedure should run
##### Actual Results

A popup alerts the user that the package is of "bad quality", thus you must click "ignore and install" to proceed.
##### Log snippets

Ubuntu Software Center log:

```
Lintian check results for /home/luca/Downloads/go-server_16.8.0-3929_all.deb:
E: go-server: maintainer-address-missing ThoughtWorks, Inc.
E: go-server: dir-or-file-in-var-run var/run/go-server/
```

**Comment by arvindsv** [comment]
Related to #1574. The first one is easy to fix. The second one, probably not so much. @ketan would know.

**Comment by arvindsv** [comment]
@rajiesh or @ankitsri11 - Can we take a look at this and see what the status is and decide what to do about it, if it's still an issue?
