### ISSUE TITLE
Material configuration labels misleading (was: hg whitelist not working)

### ISSUE THREAD

**Issue by garthk** [gocd/gocd#2592]
##### Issue Type

- ~~Bug Report~~
- Documentation Report

##### Summary

Inverted blacklists don't appear to work with `hg`. Consider:

```xml
      <materials>
        <hg url="ssh://hg@example.com/project" invertFilter="true">
          <filter>
            <ignore pattern="packages/first" />
          </filter>
        </hg>
      <materials>
```

In the UI, that looks like this in the material configuration:

> **Blacklist:**
> Enter the paths to be excluded. Separate multiple entries with a comma.
> `packages/first`
> - [x] Invert the file filter, e.g. a Blacklist becomes a Whitelist instead.

Expected behaviour:

* only `packages/first` is visible after checking out
* per #2144, only changes under `packages/first` will trigger the build

Actual behaviour in 16.8.0:

* the entire repository is visible after checking out

##### Environment

* Go 16.8.0
* Ubuntu 14.04.5 LTS
* Linux `738649c454dc` 4.2.0-42-generic
* Docker version 1.12.1, build `23cf638`
* JVM: 1.7.0_111

##### Steps to Reproduce

* Configure Mercurial repository with a few subdirectories
* Set up pipelines trying to whitelist just those subdirectories
* Make a change to one subdirectory and push it to the repository
* ~~Observe all pipelines active (expected: just one)~~ (#2596)
* Examine `pipelines` directories on the agents
* Observe full repository checked out for each pipeline (expected: just the whitelisted subdirectory)

##### Expected Results

* Only one pipeline building
* The `pipelines` subdirectory on the agent only containing the whitelisted subdirectory

##### Actual Results

* ~~All pipelines build~~ (#2596)
* The `pipelines` subdirectories on the agent contain the entire repository

**Comment by zabil** [comment]
> Expected behaviour:

> * only packages/first is visible after checking out

White lists are only for ignoring or watching folders to trigger a pipeline on a fully checked out repository. 
They are not for checking out parts of the repository.

**Comment by zabil** [comment]
https://docs.go.cd/16.9.0/configuration/admin_add_material.html#blacklist

Re-opening as we must fix the message/label on the text box.
It needs a better description so that it's not confused with excluding or including folders in a checkout.

**Comment by garthk** [comment]
I haven't seen any whitelisted materials trigger builds today, and raised #2596 after creating a dummy repository and running some tests. I now believe my report of automatic builds above was in error. Sorry about that.

The discrepancy between the labels and the activity of whitelists remains, and I'll happily take a doc-bug; thanks @zabil. I've changed the issue title to match.

**Comment by garthk** [comment]
Cheers.
