### ISSUE TITLE
Whitelists don't work with Mercurial

### ISSUE THREAD

**Issue by garthk** [gocd/gocd#2596]
##### Issue Type

- Bug Report

##### Summary

Whitelists don't appear to work with Mercurial.

##### Environment

* Go 16.8.0
* Ubuntu 14.04.5 LTS
* Linux `738649c454dc` 4.2.0-42-generic
* Docker version 1.12.1, build `23cf638`
* JVM: 1.7.0_111
* Mercurial 3.9
* Python 2.7.6

##### Steps to Reproduce

* Configure Mercurial repository with a few subdirectories `@a`, `@b`, `c`
* Set up pipelines for each, whitelisting them as `@a`, `@\b`, and `c`
* Make a change to all subdirectories and push

##### Expected Results

The pipelines for `c` and either `@a` or `@b` build.

##### Actual Results

None of the pipelines build.

##### Possible Fix

¯\_(ツ)_/¯

##### Log snippets

I'm running under Docker, and can't find anything useful through either `docker logs container -f` or `docker exec -ti container cat /var/log/go-server/go-server.out.log`.

**Comment by rajiesh** [comment]
@garthk, We are unable to reproduce this issue. To help us reproduce the issue could you please share the pipelines configuration(of the pipelines related to this issue) from the `/etc/go/cruise-config.xml` file? So that we can check  materials configuration and the filter pattern used. Please mask out any confidential information in the config.

**Comment by garthk** [comment]
@rajiesh no worries:
```xml
  <pipelines group="Experiments">
    <pipeline name="gocd-hg-whitelist-test-a">
      <materials>
        <hg url="ssh://hg@hg/gocd-hg-whitelist-test" invertFilter="true">
          <filter>
            <ignore pattern="@a" />
          </filter>
        </hg>
      </materials>
      <stage name="main">
        <jobs>
          <job name="cat">
            <tasks>
              <exec command="/bin/sh" workingdir="@a">
                <arg>-xc</arg>
                <arg>tail *</arg>
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
    <pipeline name="gocd-hg-whitelist-test-b">
      <materials>
        <hg url="ssh://hg@hg/gocd-hg-whitelist-test" invertFilter="true">
          <filter>
            <ignore pattern="\@b" />
          </filter>
        </hg>
      </materials>
      <stage name="main">
        <jobs>
          <job name="cat">
            <tasks>
              <exec command="/bin/sh" workingdir="@b">
                <arg>-xc</arg>
                <arg>tail *</arg>
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
    <pipeline name="gocd-hg-whitelist-test-c">
      <materials>
        <hg url="ssh://hg@hg/gocd-hg-whitelist-test" invertFilter="true">
          <filter>
            <ignore pattern="c" />
          </filter>
        </hg>
      </materials>
      <stage name="main">
        <jobs>
          <job name="cat">
            <tasks>
              <exec command="/bin/sh" workingdir="@b">
                <arg>-xc</arg>
                <arg>tail *</arg>
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
```

To prep the repository:

```
cd `mktemp -d`
mkdir gocd-hg-whitelist-test
cd gocd-hg-whitelist-test
for dir in @a @b c ; do mkdir "$dir" ; echo 1 > "$dir/generation" ; done
hg init
hg add .
hg commit -m "First generation"
hg clone --pull . ssh://hg@hg/gocd-hg-whitelist-test
```

Go server `Dockerfile` to get the same version of `hg`:

```Dockerfile
FROM gocd/gocd-server
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
        apache2-utils \
        python-dev \
        python-pip \
 && apt-get clean \
 && pip install --upgrade mercurial
```

**Comment by garthk** [comment]
Do you need me to gather any more detail, @rajiesh?

**Comment by rajiesh** [comment]
@garthk, As I can see from your pipeline config the ignore pattern do not follow the ant-style. The ignore pattern uses ant-style as given with examples [here](https://docs.go.cd/current/configuration/configuration_reference.html#ignore). To whitelist everything under a folder specify the pattern as `<ignore pattern="c/*" />`. Do try this and let know if you are facing any issues

**Comment by garthk** [comment]
I've tried `sub/**/*` and `sub/**`, without success. Both should match changes to files under `sub/src/` according to Ant and your documentation, but don't.

 I'm now trying `sub/*` as you advised, which if you followed Ant closely would match only files immediately under `sub`. So far, it's not picking up changes under `sub/src`, either.

Please re-open the ticket, @rajiesh. What additional information do you need to figure out why my deployment can't use the whitelist feature as documented?

**Comment by garthk** [comment]
FFS. Might be that polling itself is broken. So, first diagnostic steps: making sure it is.
