### ISSUE TITLE
Indicate if no agent with matching resouce requirements would be available for a job.

### ISSUE THREAD

**Issue by sriramnrn** [gocd/gocd#2603]
##### Issue Type
- Bug Report
##### Summary

At the moment, it is possible to set up a job such that there would be no agents available to run it. This could be due to configuration issues, or even simply due to no agents being registered with the GoCD server.

The pipeline may get triggered, but the job itself may never run for lack of an agent.

It can be really helpful to GoCD newbies and expereinced GoCD users alike to receive reminders or UI notifications that a job may not actually run when the time comes.
##### Environment

All
###### Basic environment details

All
###### Additional Environment Details

All
##### Steps to Reproduce

Set up a job to need a particular resource.
Ensure that there are no agents that can meet that resource
a. Have zero agents in total tagged with such a resource
or
b. Move the pipeline into an environment where there aren't any agent tagged with the resource the job needs.
or
c. Move the agent into an environment that the pipeline is not present in.
or
d. Disable all agents/Don't add any agents yet.
##### Expected Results

When the pipeline gets triggered, the job is waiting to get scheduled.
The GoCD UI gives the impression that things are happening.
##### Actual Results

In the absence of any matching agent, or even any agent even being present, the job would not be assigned, and there is no indication anywhere explaining that no matching agent is available or would ever be available to cater to the job.
##### Possible Fix
1. When setting up a job, if there are no resources that can run that job, provide a visual indication at design time.
   a. A text next to the resource reminding the user to ensure that the pipeline is in an environment where agents with matching resources would be available.
   b. An warning/error when the job is saved, reminding the user to ensure that agents with matching resources would be configured too.
2. Based upon certain events which would lead to a job not getting an agent, provide a visual indication + error message.
   a. When an agent goes missing or lost or is disabled or is deleted.
   b. When an agent is moved into an environment
   c. When the pipeline is moved into an environment without any agents that can run the jobs in the pipeline.
3. When a pipeline is started, if there are one or more jobs that won't have agents, indicate this.
   a. On the pipeline dashboard
   b. In the pipeline's view
   c. In the stage's view
   d. In the list of jobs (left page)
   e. In the detailed job view
   f. Next to or in place of the ""(not assigned)"" text in the job view.
4. Those used to other CI systems like Jenkins, don't immediately realize that GoCD works in a server-agent mode.
   It is currently possible to trigger a pipeline with zero agents registered with the GoCD server.
5. I am yet to explore the elastic agents capability, but I wonder if an agent could be instantiated to meet an unfulfilled resource match need. If this is not already possible, perhaps a notification mechanism could help some other system spin up agents.
   ##### Log snippets
   
   NA
##### Code snippets/Screenshots

NA
##### Any other info

NA

**Comment by sriramnrn** [comment]
As an early action, consider linking the user to the troubleshooting section (https://docs.go.cd/current/installation/troubleshooting.html#agent_assignment) via a link next to the "Not Assigned" text.

**Comment by reidca** [comment]
+1

I would love to see both an alert when no agents are available and a UI scheduling page which clearly shows the jobs and their requirements in terms of agents resources and environments and also whether there are agents available to satisfy those requirements. 

Also whether those agents are busy, idle etc. I know it is possible to view the queue using the /go/api/jobs/scheduled.xml however this is far from user friendly.
