### ISSUE TITLE
Make it easier to get to the pipeline settings.

### ISSUE THREAD

**Issue by sriramnrn** [gocd/gocd#2606]
##### Issue Type

- Feature enhancement

##### Summary
At the moment, the only way to get to a pipeline's settings is via the dashboard, or via the admin window.

It'd be useful to have the same settings "gear" icon + link in the pipeline detail view and the Value Stream Map Pipeline windows as well.

**Comment by varshavaradarajan** [comment]
Closing this as a duplicate of https://github.com/gocd/gocd/issues/2783
