### ISSUE TITLE
Pipeline config api: Validation missing for parameter name used in the custom task argument

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#2628]
##### Issue Type

- Bug Report

##### Summary

Parameter name used in a job is not validated to be present in the pipelined parameters before saving the pipeline

###### Basic environment details

* Go Version: `16.9.0 (3995-2584deab37edc05ffd02532370dc635bd1dc5a05)`

##### Steps to Reproduce

1. Do not define any parameter for the pipeline
2. Create a pipeline with the task defined as here,
```
"tasks": [
            {
              "type": "exec",
              "attributes": {
                "run_if": [
                  "passed"
                ],
                "on_cancel": null,
                "command": "ls",
                "arguments": [
                  "#{non-existing-param}"
                ],
                "working_directory": "workspace"
              }
            }
          ]
```
 

##### Expected Results

Pipeline creation should fail since the parameter `non-existing-param` is not defined at the pipeline level

##### Actual Results

Pipeline created successfully

**Comment by henriquegemignani** [comment]
This also happens if the stage was defined using a template.

**Comment by varshavaradarajan** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/2728
