### ISSUE TITLE
Agent API to assign resource

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#264]
Currently we have API's only to list, enable, disable and delete agents. 
Resource and environment edit API's will be good to have for dynamic agent management.

**Comment by jefftrimm** [comment]
The Agent API should also support assigning resources to an agent.

Consider this scenario: if the centralized list of deployment hosts for an application is managed in Puppet or some other external source of configuration, we want the creation of an application server instance running the Go Agent within the external application host list to trigger a pipeline in Go to both approve an agent and also define a resource tag on that Agent to target Go's deployment orchestration via Go's agents.

**Comment by srinivasupadhya** [comment]
You can assign resource & environment using an undocumented Agent API. [reference](https://groups.google.com/d/msg/go-cd/LT3ZUEn_kRE/Fw8euL3Tw3IJ)

**Comment by arvindsv** [comment]
https://api.go.cd/current/#update-an-agent
