### ISSUE TITLE
Quick Edit not working if Pipeline Name contains dots

### ISSUE THREAD

**Issue by paulclarkin** [gocd/gocd#2642]
##### Issue Type

- Bug Report

##### Summary

If you have a pipeline whose name contains dots (.) click Quick Edit results in 

> :(
> The url you are trying to reach appears to be incorrect.
> Go to Pipelines
> 

###### Basic environment details

* Go Version: `16.9.0 (4001-0af23a08078987314cb93012762688f1fd60680d).`
* JAVA Version: `1.7.0_75`
* OS: `Windows Server 2008 R2 6.1`
* Browser vendor and version (if relevant): `Chrome 52`

##### Steps to Reproduce

1. Create a pipeline called Test1, Test-2 and Test.3
2. Click the Quick Edit button on each - Test.3 will error

**Comment by maheshp** [comment]
@paulclarkin thanks for bringing this up. This issue is fixed as part of https://github.com/gocd/gocd/pull/2651 and it should be available in ```16.10.0```.

**Comment by rajiesh** [comment]
verified on 16.10.0 (4116-b8f1c5283cdec60ef25fbaf1a3b93dedaa76f975), working as expected
