### ISSUE TITLE
Make Edit/Admin page reachable from the pipelines view

### ISSUE THREAD

**Issue by sennerholm** [gocd/gocd#2650]
##### Issue Type
- Feature proposal
##### Summary

We would like to have a link to Edit View (goserver/go/admin/pipelines/PIPELINENAME) when we are viewing the pipeline (goserver/go/pipelines/PIPELINENAME) so you easily can change the pipeline if you find something in the output you need to change. 

Sincerely
Mikael

**Comment by varshavaradarajan** [comment]
Closing as this is a part of https://github.com/gocd/gocd/issues/2783
