### ISSUE TITLE
Move deleted pipelines into an archive of sorts

### ISSUE THREAD

**Issue by alethenorio** [gocd/gocd#2655]
##### Issue Type
- Feature proposal
- Feature enhancement
##### Summary

Deleting a pipeline through the UI (maybe through the API as well?) does not delete any data from database or configuration which makes it impossible to create a new pipeline with the same name without causing to become the old deleted pipeline. This needs to be improved to allow reusing pipeline names. 
###### Basic environment details

- Go Version: `16.9.0`
- JAVA Version: `1.8`
- OS: `Linux`
- Browser vendor and version (if relevant): `Firefox and Chrome`
##### Issue

As explained the summary, when a user deletes a pipeline, none of the data configuration or database data for that pipeline is deleted which essentially means that deleting a pipeline just hides it. When the user tries to create a new pipeline with the same name, the old pipeline with it's entire history is brought back to life and it can be very confusing if that was not what the user intended. 

This works the way it does today to address full auditability of the system however maybe there is a better way to handle this? 

Here are some ideas (Keep in mind I do not have a full understanding of the underlying Gocd design nor have I given too much though on the details of their implementation and impact on the design of the product). 
1. Make it clearer in the UI to the user that a pipeline with the same name already exists and the user will not be getting a new pipeline from scratch (Short time solution)
2. When the user deletes a pipeline,  move all configuration and relevant data for this pipeline into some sort of archive allowing for future auditing of all its history,  allowing users to create fresh new pipelines with the same name without having to load all the old history back up. It would also be of huge benefit to have somewhere in the UI that you can see all archived pipelines.
3. Improving further on number 2, when the user creates a new pipeline with the same name as an archived pipeline, create some of initial run for that new pipeline,  in the UI, which essentially leads back to the archived data with potential options to bring back the archived data into this pipeline (promoting the archive back into a 'proper' pipeline)

I think from an user experience point of view this could do with some improvement.

**Comment by arvindsv** [comment]
Feels like it is related to https://github.com/gocd/gocd/issues/221#issuecomment-143403650

**Comment by ccampanale** [comment]
:+1: 

Second this FR completely. I personally have some circumstances where I want to delete a pipeline since I have completely deprecated it and would prefer not to see it anymore but also want to be able to refer to it in the future in case I want to recall how something was done.

Furthermore, the ability to reuse the name of the pipeline as @ByteFlinger mentioned would be an appreciated side effect.
