### ISSUE TITLE
Junit integration with python nosetest isn't great

### ISSUE THREAD

**Issue by sgran** [gocd/gocd#266]
Hi,

I am running a python project which uses python nosetests with the xunit plugin.  This produces an XML output file, which I instruct go to retrieve as a test artifact.  We are seeing two issues:

The XML parser in Go fails if the XML file has stdout with a CDATA section
When XML parsing succeeds, I see the following behavior:
On the page for the stage, when I select the tab for tests (eg http://goserver/go/pipelines/mypipeline/8/py27/1/tests) I see correct output (Attached as Correct_test_output.png). 
![correct_test_output](https://cloud.githubusercontent.com/assets/1583277/3246851/222988ee-f17f-11e3-9808-5dd4fb186d56.png)
 When I go into the job detail for the stage and select the tab for tests, I see incorrect output listing no tests (Attached as Incorrect_test_output.png)
![incorrect_test_output](https://cloud.githubusercontent.com/assets/1583277/3246850/22297e08-f17f-11e3-96cc-c3752502390a.png)

**Comment by arvindsv** [comment]
@rajiesh: Can we re-check this? I remember someone (maybe @xli) changing this recently.

**Comment by Zaccc123** [comment]
@arvindsv @rajiesh Hi, came across this as i was testing. I believe this is not fix yet. I am trying out gocd on a toy django project before considering when to shift our other project from jenkins over.

This is what i have with a single test runnining. 
<img width="970" alt="stagepassedwith1test" src="https://cloud.githubusercontent.com/assets/11663635/24135005/af4f6e36-0e42-11e7-9795-8ec72f730adb.png">

In my job, in the `test` tab is not showing up:
<img width="934" alt="testinjobnotshown" src="https://cloud.githubusercontent.com/assets/11663635/24135019/bc0776b4-0e42-11e7-96b6-8eb1199dcaf6.png">

Artifacts did shown the `xunittest.xml` files.
<img width="934" alt="screen shot 2017-03-21 at 2 29 39 pm" src="https://cloud.githubusercontent.com/assets/11663635/24135062/f5f8e0a6-0e42-11e7-88d2-19097e57b3fb.png">

The contents of the files are as follow:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="nosetests" tests="1" errors="0" failures="0" skip="0">
<testcase classname="tasksapp.tests.HomeViewTests" name="test_get_all_tasks_at_home" time="0.219">
</testcase>
</testsuite>
```

The `nosetest` i run are as follow: 

`14:19:19.207 nosetests --cover-erase --cover-package=tasksapp --with-xunit --xunit-file=xunittest.xml --verbosity=1`

I am using Go Version: 17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45).

**Comment by ketan** [comment]
@Zaccc123 — the contents of the XML that you provided above, is that exactly identical to the file you have, including whitespaces and newlines? Could you throw it into a gist and provide a link here?

**Comment by Zaccc123** [comment]
I actually formatted it myself after pasting over. The original version in `.gist` [here.](https://gist.github.com/Zaccc123/bd151e0170763f0a6fcefcff42d64a87)

**Comment by cfriedt** [comment]
Unit test reporting could be vastly improved.
