### ISSUE TITLE
Creating a new user via API call succeeds but throws 409 conflict error

### ISSUE THREAD

**Issue by joel74** [gocd/gocd#2708]
##### Issue Type

- Bug Report

##### Summary

I can pass JSON to the /go/api/users endpoint and it successfully create the new users, but it also throws a 409 conflict error every time.

##### Environment

(http://<my-go-server>/api/go/support is not available to me - 404)

###### Basic environment details

* Go Version: 16.2.1
(http://<my-go-server>/api/go/about is not available to me - 404)

##### Steps to Reproduce

1. Post JSON to the /go/api/users endpoint, passing a login_name and email address, with the appropriate headers and content type.

##### Expected Results
A new user is created without error.

##### Actual Results
A new user is created, but the server returns (409) Conflict.

**Comment by varshavaradarajan** [comment]
@joel74, we were returning the wrong response on successfully creating a user. This has been fixed in GoCD 16.5: https://github.com/gocd/gocd/pull/2167 

Also, you said the ```api/go/support``` and ```api/go/about``` were not found. Are you sure you are accessing the right url? It should be ``go/api/support``` and ```go/about```

**Comment by joel74** [comment]
The new issue template references this:

* JAVA Version: `Available from http://<go-server-host>/api/go/about`

It should reference http://<go-server-host>/go/about
All the other references appear to be correct.
