### ISSUE TITLE
Agent SPA: Agents state summary on agents page not aligned properly on IE 10 and earlier versions

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#2727]
##### Issue Type

- Bug Report
##### Summary

Agents state summary on agents page not aligned properly on IE 10 and earlier versions
###### Basic environment details

- Go Version: `16.10.0 (4116-b8f1c5283cdec60ef25fbaf1a3b93dedaa76f975)`
- JAVA Version: `Available from http://<go-server-host>/api/go/about`
- OS: `Available from http://<go-server-host>/go/about`
- Browser vendor and version (if relevant): `IE 10 and earlier`
##### Steps to Reproduce

Start few agents and visit new agents page
##### Expected Results

Agent state summary should be aligned properly
##### Actual Results

<img width="782" alt="screen shot 2016-09-23 at 4 18 45 pm" src="https://cloud.githubusercontent.com/assets/6533924/18783647/a8b271b0-81aa-11e6-85cd-bff4d9a71362.png">

**Comment by GaneshSPatil** [comment]
IE 11 and older browsers are not supported by GoCD.

Closing this issue, marking as wont fix.
