### ISSUE TITLE
[Agent improvement] Spike out alternative HTTP client libraries

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2730]
##### Issue Type
- Feature enhancement
##### Summary

Current HTTP library that is used [httpcomponents](https://hc.apache.org/) is adding quite some bit of an overhead to the agent bootstrapper and the agent jar processes. This library is used for ongoing polls (ping thread, work thread), to upload/download artifacts and to upload properties at the end of the build.

This issue is to spike out some other alternatives that provide for a few things —
- Ease of use — DSLs, Fluent Interfaces, hassle free SSL setup
- Shared SSL contexts, to prevent overloading the server on each SSL/TLS connection that's made

**Comment by ketan** [comment]
F                   | OkHTTP | HttpClient | Jetty Client
--------------------|--------|------------|-------------
DSL                 | 👍     | 👍         | 👍
Ease of SSL         | 👍     | 👍         | 👍
Shared SSL Contexts | TBD    | TBD        | TBD
Memory Overhead     | TBD    | TBD        | TBD

**Comment by arvindsv** [comment]
I guess we need to continue the analysis and decide on the library. 

Another approach is to go big on golang. :)
