### ISSUE TITLE
Unable to run start-agent.bat in Windows

### ISSUE THREAD

**Issue by padmam** [gocd/gocd#2742]
##### Issue Type

- Bug Report

##### Summary

Unable to run agent using start-agent.bat in Windows machine. 

###### Basic environment details

* Go Version: `16.9.0`
* OS: `Windows`

##### Steps to Reproduce

1. Download and install 16.9 go-agent 
2. Try to run the go-agent using the start-agent.bat file as administrator

##### Expected Results
The start-agent.bat file should be able to find the agent.cmd in the existing directory and start the go-agent.

##### Actual Results
Go-agent is not started using start-agent.bat file and gives error "Windows Cannot find agent.cmd. Make sure you typed the name correctly, and then try again"

##### Log snippets
```
C:\>IF "" == "N" (START "go agent - C:\" /WAIT agent.cmd )  ELSE (START "go agen
t - C:\" /MIN agent.cmd )
The system cannot find the file agent.cmd.
```

##### Code snippets/Screenshots
<img width="720" alt="error" src="https://cloud.githubusercontent.com/assets/3272253/18902603/ab26e4ba-8571-11e6-910e-2b65a1d2ebc3.png">

**Comment by arvindsv** [comment]
Can you check if adding this line:

```
cd /d %~dp0
```

[here](https://github.com/gocd/gocd/blob/75ab9623541b1c9795896f660d1c5d99221ebce8/installers/go-agent/release/start-agent.bat#L16) helps?

**Comment by padmam** [comment]
Adding `cd /d "%~dp"` to start-agent.bat at [here](https://github.com/gocd/gocd/blob/75ab9623541b1c9795896f660d1c5d99221ebce8/installers/go-agent/release/start-agent.bat#L16 and ) helped

**Comment by arvindsv** [comment]
Fixed by https://github.com/gocd/gocd/pull/2750

**Comment by rajiesh** [comment]
Verified on GoCD version 16.11.0 (4174-cfb732397132b330e9786d1011c7dc3ba1c9f260), functionality working as expected
