### ISSUE TITLE
rendering {{ }} in json fails

### ISSUE THREAD

**Issue by rvarlikli** [gocd/gocd#2744]
##### Issue Type

- Bug Report
##### Summary

We defined a plugin which gets json string as parameter. If you have '{{' inside the json ,plugin page doesn't show what is stored as json before. It doesn't lose the data but only doesn't show what is entered before.

After playing with json for a while , we noticed {{}} characters causing the problem
##### Environment

``` plain
Centos, MacOS
```
###### Basic environment details
- Go Version: `16.10`
- JAVA Version: `1.7.0_80`
- OS: `Mac OS X 10.11.6`
##### Steps to Reproduce
1. Define a new plugin which gets a text parameter or use any existing plugin which require a text
2. Enter this json http://www.jsoneditoronline.org/?id=8573c353061cd15fbc1e3d27de80a162 as text
3. Click save
4. Try to edit plugin again. You won't see the json in the text area.
##### Log snippets

We didn't see any error messages in the logs

**Comment by arvindsv** [comment]
@rvarlikli What type of plugin did this happen in? And, what text area do you mean? The task text area in a plugin such as [this](https://github.com/gocd-contrib/script-executor-task)?

**Comment by rvarlikli** [comment]
Here is the excerpt from the plugin view..

<div class="form_item_block">
    <label>Template File Context:<span class="asterisk">*</span>
    </label>
    <textarea ng-model="TemplateContext" style="width: 250px; resize: both;" cols="50" ng-required="true">
    </textarea>
    <span class="form_error" ng-show="GOINPUTNAME[TemplateContext].$error.server">{{ GOINPUTNAME[TemplateContext].$error.server }}</span>
</div>

**Comment by rvarlikli** [comment]
I think there are more issues with rendering/parsing of any textarea within plugins... Here is another problem we are facing
`
# ami ids for instances
variable "aws_amis" {
 type = "map"
 description = "AWS region to launch servers."
 default = {
   eu-west-1 = "ami-ed82e39e"
   us-east-1 = "ami-de7ab6b6"
   us-west-1 = "ami-3f75767a"
   us-west-2 = "ami-21f78e11"
 }
}

`
Error when processing params for '# ' used in field 'value', # must be followed by a parameter pattern or escaped by another #
