### ISSUE TITLE
Sorting in new agents page jumps back to top of page

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2746]
##### Issue Type
- Bug Report
##### Summary

When scrolling slightly downwards on the new agents page and then clicking one of the column names to sort on it the page jumps back to the top.
###### Basic environment details

- Go Version: `16.10.0`
- JAVA Version: `OpenJDK 8`
- OS: `Debian 8.6`
- Browser vendor and version (if relevant): `Chrome Version 52.0.2743.116 (64-bit) in Mac OS X`
##### Steps to Reproduce
1. Go to the agents page
2. Click 'Check out the new agents page'
3. Scroll down keeping the table columns just in view
4. Click on column 'Agent Name'
##### Expected Results

The browser doesn't scroll up or down
##### Actual Results

The browser scrolls up to the top of the page

**Comment by kritika-singh3** [comment]
We have introduced a revamped Agents SPA in GoCD verison 19.10.0. I have verified that this issue is no longer present. Please update.
