### ISSUE TITLE
Keep action buttons, filter field and table headers in view when scrolling down on new agents page

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2747]
##### Issue Type
- Feature enhancement
##### Summary

When scrolling down through a long list of agents it would be very user friendly to be able to perform actions, filter or sort on columns without having to scroll back to the top. Keeping the purple bar up to and including the yellow header bar in view when scrolling down would take care of this.

PS The new agents page is awesome. So much faster than the old one and filtering is much easier.
###### Basic environment details
- Go Version: `16.10.0`
- JAVA Version: `OpenJDK 8`
- OS: `Debian 8.6`
- Browser vendor and version (if relevant): `Chrome Version 52.0.2743.116 (64-bit) on Mac OS X`

**Comment by JorritSalverda** [comment]
An article on how to do this can be found at http://creative-punch.net/2014/03/making-scroll-dependent-menu-bar-css3-javascript/. Not sure if this is the best way to do it these days as the article is already 2 years old. My frontend skills haven't been kept up to date.

@mAiNiNfEcTiOn are there better ways of doing a floating menu bar?

**Comment by ketan** [comment]
This was fixed a couple of release ago, not sure when.
