### ISSUE TITLE
Filter pipelines on dashboard page on status building, failed, passed

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2748]
##### Issue Type
- Feature enhancement
##### Summary

With a large number of pipelines on the dashboard page it would be useful to be able to quickly filter on status to see the failed or building pipelines. Successful builds are hardly interesting compared to failed builds.

I guess the dashboard page will be rebuild in a similar fashion as the new agents page. A single filter field that allows you to filter on name (of pipeline or pipeline group), build status and possibly other properties would make life much easier.

Keeping the filter in view when scrolling down - see https://github.com/gocd/gocd/issues/2747 for the new agents page - will be very useful as well.

**Comment by GaneshSPatil** [comment]
@JorritSalverda -- This can be achieved by creating a Dashboard personalization and setting the pipeline state as either `failed` or `building` in the personalization settings.

**Comment by NarimanAB** [comment]
what about stopped or paused pipelines? how to get them?
