### ISSUE TITLE
Add the ability to ignore certain commit message patterns when checking for changes

### ISSUE THREAD

**Issue by rduartes** [gocd/gocd#2751]
##### Issue Type

- Feature enhancement
##### Summary

Go currently supports setting up paths that should be ignored for changes when checking the scm. It would also be useful if a similar setting would exist to tell it to ignore specific commit message patterns like the ones that are generated by an automated release process.

**Comment by jogelin** [comment]
Any ideas when this feature could be added in the "pipeline" ?

It is really useful in case of an automated release. Usually, we want to tag, to commit and push a new version in the code and we don't want to re-run the build after that. 

For a first version, the checks could be only on the last commit (`git log -1`). A checkbox could be only checked if to ignore the poll if the committer/author is the same as the poller:
```
git log -1 --format='%an' == git config user.name
git log -1 --format='%ae' == git config user.email
```

Then, it could be possible to extends it to other fields (see [Git pretty format](https://git-scm.com/docs/pretty-formats)):

- message
- date
- tag
- ...

**Comment by tonyzwei** [comment]
Go CD should be developed this kind of feature just https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build, PLEASE. THIS IS CRITICAL!

**Comment by ryudice** [comment]
We need this as well, we use semantic-versioning npm package for building our libraries and whenever we do a push to update the version in package.json it starts rebuilding again.

**Comment by cfontes** [comment]
This would be great indeed

**Comment by capeflynn** [comment]
I know this is old, but it really would be great functionality.
