### ISSUE TITLE
Quick edit adds extra element to ant/rake tasks

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#2753]
##### Issue Type

- Bug Report

##### Summary

Quick edit adds optional attributes of tasks upon save, and defaults them to empty. This causes some tasks to become invalid when run.

###### Basic environment details

* Go Version: 16.10.0
* JAVA Version: 1.7
* OS: Linux

##### Steps to Reproduce

1. Have a config with these tasks:

    ```
    <ant target="dist" workingdir="somedir">
      <runif status="passed" />
    </ant>

    <ant buildfile="abc" target="dist">
      <runif status="passed" />
    </ant>
    ```

2. Open the "Quick Edit" for the pipeline.

3. Click "Save".

4. Check the XML.
 
##### Expected Results

No change in the XML.

##### Actual Results

The XML would have changed to:

```
<ant buildfile="" target="dist" workingdir="somedir">
  <runif status="passed" />
</ant>

<ant buildfile="abc" target="dist" workingdir="">
  <runif status="passed" />
</ant>
```

The workingdir is harmless (though wrong), but the "buildfile" attribute makes the ant task incorrect (won't run).

##### Any other info

This happens for Rake as well, and I guess Nant too. Maybe for anything (or just any task) which has an optional attribute?

**Comment by rajiesh** [comment]
Verified the fix on GoCD version 16.11.0 (4164-1d1fbc36cd04b463a8cf2142cb6eb1243023b412) and working as expected
