### ISSUE TITLE
Improve dashboard performance

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#276]
Currently Go dashboard does not scale too well if there are too many pipelines displayed on the dashboard. The idea is to come up with a new dashboard api which would help make small incremental updates to the dashboard making it more performant

**Comment by JorritSalverda** [comment]
Being able to collapse the pipeline groups on the pipelines might help. Groups should for example only open up if any pipeline failed. This in order to only show information that needs an action, not information that's 'normal'.

**Comment by arvindsv** [comment]
Closing in favor of #1841.
