### ISSUE TITLE
Unable to enable new Agents using the redesigned Agent UI.

### ISSUE THREAD

**Issue by tanderegg** [gocd/gocd#2762]
##### Issue Type
- Bug Report
##### Summary

When using the new Agent UI, I received the error message "Agent(s) with uuid(s) ... not found" when attempting to enable new agents that are currently "pending".  I switched to the old UI, and was able to enable the agents without issue.  This might be related to #2735.
##### Environment

GoCD Server is configured with default settings, the GoCD agents in question were running within Mesos containers using memory and cpu isolation only.
###### Basic environment details
- Go Version: 16.10
- JAVA Version: 1.8 (Oracle)
- OS: RHEL 6.8
- Firefox
##### Steps to Reproduce
1. Start up a 16.10 server
2. Start up a 16.10 agent (in a Mesos container in my case, not sure if that is relevant)
3. Switch to the new Agent UI
4. Select the new Agent, and click "Enable"
##### Expected Results

The agent should move from "Pending" to "Idle" status.
##### Actual Results

Received the error message "Agent(s) with uuid(s) {{ UUID }} not found"
##### Possible Fix

Switch to the old Agent UI.  I began looking through the code but did not find an obvious cause of the error.
##### Log snippets

Nothing related to this showed up in the Agent or Server logs, just the browser interface itself.

**Comment by rajiesh** [comment]
@tanderegg @gek0, yes its related to issue https://github.com/gocd/gocd/issues/2735 and we are working on the fix, this PR fixes the issue https://github.com/gocd/gocd/pull/2740. It will be available in the 16.11 release which is expected to be out anytime next week

**Comment by rajiesh** [comment]
@tanderegg @gek0, fix for this issue is not available in 16.11 release, we are working on it to handle in better way using the api as well as UI. Check the PR #2740 for the progress

**Comment by tanderegg** [comment]
Ok, thanks!

**Comment by betarelease** [comment]
thanks @arvindsv  for the update.

**Comment by rajiesh** [comment]
Verified on GoCD version - 16.12.0 (4305-25b6f3d9eef3f9b30acd65ac9965b8776a917e9d), working as expected
