### ISSUE TITLE
Feature request: Configure default setting of "Poll for new changes" flag

### ISSUE THREAD

**Issue by paulclarkin** [gocd/gocd#2766]
##### Issue Type
- Feature proposal
##### Summary

In our configuration we primarily use Git repos, in conjunction with Git webhooks to tell Go to trigger a build. When a commit is pushed, the Go pipeline is triggered via webhook. Without this, we have lots of git processes firing to poll for new changes.

However, when new pipelines are created, people frequently forget to turn off the Poll for new changes flag, as it is ticked by default.

Would it be possible to set a master override for this, so it was OFF by default?

**Comment by arvindsv** [comment]
Closing as 'WONT-FIX'. This isn't planned. Sorry.
