### ISSUE TITLE
how to reuse one pipeline on mutiple environment?

### ISSUE THREAD

**Issue by junneyang** [gocd/gocd#2770]
##### Issue Type
- Feature proposal/Problem

##### Summary

as the docs say:
An agent can belong to more than one environment. This means, for instance, the same agent can be used to deploy something into an UAT or a Performance testing environment. A pipeline can, however, only be assigned to a single environment.

so, if i have some pipeleines(pipelineA, pipelineB) and have assigned to an environment(envA) already, and now i have some new agents, i want to use these new agents to deploy a same environment as envA, how to achieve this goal as quick as possible?

thanks very much!

**Comment by zabil** [comment]
Use [pipeline templates](https://docs.go.cd/current/configuration/pipeline_templates.html) 
And make pipelineA, pipelineB refer to the newly created template. 

Modifying the template will apply changes to both pipelines. 
These pipelines now can belong to different environments.

**Comment by junneyang** [comment]
@zabil 
thanks, i see.
