### ISSUE TITLE
 Show that a pipeline has been configured via a non-GUI approach

### ISSUE THREAD

**Issue by sriramnrn** [gocd/gocd#2772]
##### Issue Type
- Feature enhancement
##### Summary

When one configures GoCD via the new yaml plugin, the Admin/Pipelines view shows the edit, etc buttons as grayed out. One is not sure why these are grayed out. 

If the UI were to show which yaml config file had an effect on configuring the pipeline, then the admin would know that the particular pipeline can only be edited via that yaml file. This would be helpful when going to edit pipelines, for new and experienced pipeline admins alike.

**Comment by ketan** [comment]
/cc @tomzo .

Sorry cc'd you on the wrong ticket earlier

**Comment by tomzo** [comment]
There quite a lot already implemented to make a such feature in UI. In particular plugins can optionally return location of each pipeline. Both JSON and YAML plugins actually return these locations. Then server understands this location already to display location of pipeline config errors. (Lookup `location` field in `CR*` classes such as `CRPipeline`.)
Having said all that, most work is in the UI and I am rather not likely to touch it. But I can help/explain with backend if someone commits to this.

**Comment by arvindsv** [comment]
This has been changed recently. Shows an info icon with information about which config repo it is defined in.
