### ISSUE TITLE
GoCD job restarts right after uploading the artifacts to the Go Server

### ISSUE THREAD

**Issue by kdhamo** [gocd/gocd#2774]
##### Issue Type

- Bug Report
##### Summary

GoCD Clover job restarts right after uploading the artifacts to the Go Server. Here is a snippet of what the logs look like:

16:32:35.583 [go] Uploading artifacts from /var/lib/go-agent/pipelines/PaymentServiceCloverBuild/payment-service-src/payment-service/target/surefire-reports/TEST-com.gsicommerce.payment.web.security.ldap.authentication.WebLdapSecurityApplicationConfigurationTest.xml to clover-tests/payment-service-src/payment-service/target/surefire-reports
16:32:35.739 [go] Uploading artifacts from /var/lib/go-agent/pipelines/PaymentServiceCloverBuild/payment-service-src/target/site/clover/clover.xml to clover-report
16:32:53.823 [go] Job Started: 2016-10-09 16:32:53 UTC

Note that the clover.xml is the last artifact uploaded, then there is a 18 seconds gap and then the job restarts again.

**Comment by arvindsv** [comment]
@kdhamo Can you check if there's an OutOfMemoryError or OutOfMemoryException in the agent logs? Something similar to [this](https://github.com/gocd/gocd/issues/2160). Is clover.xml marked as a test artifact? Can you check if marking it as a build artifact changes that behavior?

**Comment by arvindsv** [comment]
Also, maybe related to [this](https://github.com/gocd/gocd/issues/1202#issuecomment-241617487).

**Comment by kdhamo** [comment]
Yes! I already made the change yesterday from a test artifact to a build artifact that that resolved the issue. However, there is no out of memory issue on the logs. Maybe

**Comment by arvindsv** [comment]
Hmm, ok. Glad it is sorted out. If you don't mind, can you tell me how big the clover.xml was? Thanks!

**Comment by kdhamo** [comment]
I am actually copying the whole target/site/clover folder into the go server. That is about 1GB.

**Comment by arvindsv** [comment]
Oh wow. Ok. That could explain it. :) Strange you didn't see an out of memory message in the logs. Anyway, glad it's ok now.

**Comment by thenano** [comment]
I'm still seeing the same issue when uploading xml junit results as test artifacts, I'm running 16.9.0. I'm wondering if there are any other ways to prevent this apart from changing test to build artifact? I'm still keen to see results in the errors tab and test tab.
