### ISSUE TITLE
Improvements to EntityConfigUpdateCommand

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2780]
##### Issue Type

- Feature enhancement
##### Summary

There can be some improvements made to the EntityCommands to provide more clarity for validation.
1. Have a `preValidate` and `postValidate` call instead of just isValid(). The reason for this is that, there are some validations, without which the entity should not even be updated in the cruise config and based on which, the subsequent validations (that is, the post-update validations should happen.) Most common of the pre validate can be that the identifying attribute should not be null.
2. Pull a `isAuthorized` method out of the canContinue method. 
3. Move the isAuthorized method to goConfigService so that given the username and privileges we want, we can avoid duplication in all entity commands.
4. The `canContinue` method can deal with stale requests etc.

**Comment by akshaydewan** [comment]
I'm planning to pick this up and raise PRs in small chunks.
