### ISSUE TITLE
Pipeline edit link available only on dashboard

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#2783]
##### Issue Type
- Feature enhancement
##### Summary

Currently a pipeline can be edited only through the pipeline dashboard page. Having the edit links only on the dashboard is sometimes undesirable, especially in cases where the user is on the Job run page and sees a need for changing the pipeline. Doing this involves navigating through multiple pages to edit a pipeline.

Considering some of these use cases, come up with a better UX for editing pipelines.

**Comment by varshavaradarajan** [comment]
Related to https://github.com/gocd/gocd/issues/2650. 
Consider having the pipeline edit link in the history page.
