### ISSUE TITLE
Reason for pausing pipeline not shown on pipeline history page

### ISSUE THREAD

**Issue by mrmanc** [gocd/gocd#2784]
##### Issue Type
- Bug Report / Feature enhancement
##### Summary

I’m not sure if this is a regression or not, but didn’t the pipeline history page describe the reason the pipeline had been paused at some point? The ‘pipelines’ page does, but it would be useful to see in the history page too.
##### Environment

n/a
###### Basic environment details

- Go Version: `16.5.0`
- JAVA Version: `1.8.0_102`
- OS: `Linux 2.6.32-358.el6.x86_64` (CentOS)
- Browser vendor and version (if relevant): `Chrome 53.0.2785.116`
###### Additional Environment Details

n/a
##### Steps to Reproduce

1. From the pipeline history page, pause a pipeline, providing a reason
2. Note that the button has changed to ‘unpause’ but no reason is displayed next to the button
##### Expected Results

The reason the user entered should be described.
##### Actual Results

Nothing is shown next to the button.
##### Possible Fix

Show the reason next to the button
##### Log snippets

n/a
##### Code snippets/Screenshots

n/a
##### Any other info

n/a

**Comment by arvindsv** [comment]
I don't think this was showing, at any time. But, it will be useful. There are some page rewrites coming up and it'll probably include this page (after a dashboard rewrite, I guess). So, I'll link this to https://github.com/gocd/gocd/issues/1598.

**Comment by rajiesh** [comment]
Verified on 17.8.0 (5277-32ff863cce99f97b76abb1b88469a793e3b1adc5)
