### ISSUE TITLE
New api endpoint to support custom scm materials notification

### ISSUE THREAD

**Issue by PandaXass** [gocd/gocd#2796]
##### Issue Type

- Feature proposal

##### Summary

Currently GoCD api only supports 3 types of material notification: svn, git and mercurial.
And we would like to use some community SCM plugin, such as [Build Stash Pull Requests](https://github.com/ashwanthkumar/gocd-build-github-pull-requests), in order to trigger the pipeline according to each pull request.
However the periodic polling for pull requests will end up consistent high workload on GoCD server that will degrade the performance a lot (due to the huge amount of pipelines we have on a single server).
It will be much appreciated that GoCD can provide api endpoint to notify custom material, so we can do push to trigger (vs. poll).

###### Basic environment details

* Go Version: 16.6.0 (3590-af0f8b8ae8a4342ab748ce80224971887f018ccc)
* JAVA Version: 1.7.0_80
* OS: Linux 2.6.32-642.el6.x86_64

##### Expected Results

To be able to api endpoint to notify the custom scm material.

##### Possible Fix

New api:
`curl 'https://ci.example.com/go/api/material/notify/scm' -u 'username:password' -H 'Confirm: true' -X POST -d 'name=scm-name'`

##### Any other info

**Comment by arvindsv** [comment]
@PandaXass: It should already be present. See https://github.com/gocd/gocd/pull/913#issuecomment-92231030. I think it's missing in the documentation and I'd appreciate if it you were able to contribute to it. :)

Here's what I think it should try, to see if it works:

```
curl 'https://ci.example.com/go/api/material/notify/scm?scm_name=NAME_OF_THAT_MATERIAL' -u 'username:password' -H 'Confirm: true' -X POST
```

**Comment by PandaXass** [comment]
@arvindsv thanks for pointing out, seems to work as expected. I will try to create PR for the documentation.
