### ISSUE TITLE
Issue with Very Large filesystem (AWS efs)

### ISSUE THREAD

**Issue by richardvanbeers** [gocd/gocd#2797]
##### Issue Type
- Bug Report
## When specifying an AWS efs volume as the location of the artifacts directory (efs is Exabyte scale) after a go-server restart, the gocd console will throw an error in the gocd console:

Go Server has run out of artifacts disk space. Scheduling has been stopped [Oct-19 13:23:17]
###### Basic environment details

Go Server Version:  16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d)
JVM version:    1.7.0_111
OS Information: Linux 4.4.19-29.55.amzn1.x86_64
Usable space in artifacts repository:   -9223372036854775808 Bytes
Database schema version:    1610001

Browser: chrome
##### Steps to Reproduce
1. Run go server on aws linux
2. Mount an efs volume
3. Target  a directory for artifacts on the efs volume
4. 
##### Expected Results

Have Exabytes of storage for artifacts on a network filesystem. Have working schedules.
##### Actual Results

go-cd complains about:
Go Server has run out of artifacts disk space. Scheduling has been stopped
##### Possible Fix

Possibly increase the data type for disk space values.

**Comment by arvindsv** [comment]
Linking to the original conversation, which has some details: https://groups.google.com/d/topic/go-cd/055htMi1RiI/discussion

We can't change the data type, I think, because this is the response from an internal Java method call. I guess we need to handle the case where it returns a negative value specially, [somewhere here](https://github.com/gocd/gocd/blob/cfb732397132b330e9786d1011c7dc3ba1c9f260/server/src/com/thoughtworks/go/server/service/DiskSpaceChecker.java#L80).

**Comment by ketan** [comment]
From my email on the gocd groups —

```
[root@ip-172-31-57-237 ~]# df -k
Filesystem                                                  1K-blocks    Used        Available Use% Mounted on
devtmpfs                                                       498820      60           498760   1% /dev
tmpfs                                                          509664       0           509664   0% /dev/shm
/dev/xvda1                                                    8123812 1262760          6760804  16% /
us-east-1b.fs-1ac11453.efs.us-east-1.amazonaws.com:/ 9007199254740992       0 9007199254740992   0% /root/efs


[root@ip-172-31-57-237 efs]# ~/jruby-9.1.5.0/bin/jruby -e "puts java.io.File.new('/root/efs').getUsableSpace"
-9223372036854775808
```

It appears that the fix is to use apache commons IO. This implementation uses `df` or `dir /-c`

```
[root@ip-172-31-57-237 ~]# jruby-9.1.5.0/bin/jruby -r ./commons-io-2.5.jar -e "puts org.apache.commons.io.FileSystemUtils.freeSpaceKb('/root/efs')"
9007199254740992
```

However this will only get us so far as to 2<sup>63</sup>-1 K 😀

**Comment by richardvanbeers** [comment]
For my situation, an option to disable disk space checking would also work. Currently I cannot use efs unfortunately, and that would make a go install very powerful. But thanks for looking.

**Comment by ketan** [comment]
@richardvanbeers — the check exists to be able to ensure that the server has enough disk space to for the DB to ensure that it's not corrupted under certain circumstances where the server runs out of disk space to be able to write to the DB.

The "fix" above will require some careful thought. `FileSystemUtils` executes commands to check disk space. This may have an unanticipated overhead, the process may "hang" in certain edge cases, causing the server to behave in unexpected ways. The commands also need to work in constrained environment — aka docker, where the `df` executable may not be easily available.

Currently I can think of a couple of workarounds that may work for you —

* using a normal EBS volume
* write some bytes to the EFS volume to bring the available space down to a manageable positive 64 bit number. You may use the jruby script above (https://github.com/gocd/gocd/issues/2797#issuecomment-254859097) to measure if the disk space on your volume is a positive number.

**Comment by arvindsv** [comment]
Even `df -k` (and so the Apache Commons lib) is not providing the right value, right? They're just showing `2^63 / 1024  = 9007199254740992`. About your suggestion to add some bytes to the EFS volume, I don't think that will ever get it down below `2^63`. Do you? If so, how much?

I think handling the negative value is still a better option than using something which uses `df` internally. You mentioned most of the reasons not to do that.

**Comment by arvindsv** [comment]
Or, are you saying that adding a file with 1 byte of 2 bytes will change it to be below `2^63`?

**Comment by ketan** [comment]
> Or, are you saying that adding a file with 1 byte of 2 bytes will change it to be below 2^63?

@arvindsv — Yes, that's what I'm suggesting. This forum post (https://forums.aws.amazon.com/thread.jspa?threadID=234928) seems to suggest that 1 block ought to be enough to bring down the free space to something more "manageable", based on my calculation it seems about right —

`Long.MAX_VALUE` = 2<sup>63</sup>-1
1 exa byte = 2<sup>60</sup>, therefore an 8 exabyte EFS volume = 2<sup>60</sup>*2<sup>3</sup>, same as 2<sup>63</sup>.

So we need it to be shorter by just 1 byte to be able to work fine.

**Comment by arvindsv** [comment]
Cool. It's worth trying. Something like:

```
echo hello >/root/efs/dummy
```

**Comment by hutchy2570** [comment]
Hi,

We're hitting the same issue using EFS for artifact storage.  Is there any workaround we can employ until this is fixed?

Thanks.

**Comment by arvindsv** [comment]
@hutchy2570: @ketan was suggesting that doing something like this:

```
echo hello >/root/efs/dummy
```

That's just creating a dummy file with a few bytes in it, on that EFS volume.  This might help get the size down below `2 ^ 63`. Can you try that?

If it does not work, can you run these two commands, after you create that file and share the output?

```
df -k

jrunscript -e "println(new java.io.File('/').getUsableSpace())"
```

**Comment by hutchy2570** [comment]
I have around 320mb of files in the EFS mount at the moment, and the reported space free is always 9007199254419456 regardless of how much data I write.

**Comment by ketan** [comment]
@hutchy2570 and @richardvanbeers — I'm sorry but supporting EFS is not on our list of priority right now. It would be great if you could put together a pull request to fix the problem. If you need support in doing this please contact us and we try to guide you.

**Comment by hutchy2570** [comment]
Would a potential fix be to wrap the call in SystemDiskSpaceChecker.java to convert the overflowed negative value into an unsigned long?

Can anyone think of a legitimate situation where that would be expected to return a negative value?

**Comment by arvindsv** [comment]
@hutchy2570 - In my view, it should be an acceptable fix, since adding a few bytes to the file system doesn't help. Don't know what @ketan and others think.

**Comment by rajiesh** [comment]
Verified on 17.5.0 (4898-9cec83fd6dda71ea085525354ca201ab7e4d3dec)
