### ISSUE TITLE
Duplicate package error when existing package has been deleted

### ISSUE THREAD

**Issue by salliewalecka** [gocd/gocd#2802]
##### Issue Type
- Bug Report

##### Summary

When we delete a package material from NuGet and try and add it again, we get an error saying it is a duplicate package material.

###### Basic environment details
* Go Version: 16.11
* JAVA Version: 1.7
* OS: 
* Browser vendor and version (if relevant): Chrome  53.0.2785.143

###### Additional Environment Details
Running Locally from IntelliJ

##### Steps to Reproduce
1. Install NuGet Plugin
2.  Create Repository "http://nuget.org/api/v2" and save it
3.  Add material to pipeline with NUnit as package name and id (using the NuGet repo)
4.  Save Material
5.  Delete the material by clicking 'X'
6. Add NUnit material again using the same repo
7. See error : "Cannot save package or repo, found duplicate packages. [Repo Name: <reponame>, Package Name: 'NUnit'], [Repo Name: <reponame>, Package Name: 'NUnit']"

##### Expected Results
We should be able to add the package back if we accidentally deleted it.

##### Actual Results
It says the package material already exists

##### Code snippets/Screenshots
<img width="752" alt="screen shot 2016-10-20 at 5 39 37 pm" src="https://cloud.githubusercontent.com/assets/11946238/19583030/174f8b50-96ee-11e6-9ee2-82b32256d5b1.png">

**Comment by rajiesh** [comment]
@salliewalecka from your description I understand that you deleted the material from pipeline configuration, that will not delete the package definition created. So selecting the option `Choose Existing` should show up the `Nunit` package in the drop down. Please try it out and let know if facing any issues

**Comment by salliewalecka** [comment]
Got it! Sorry for the false alarm...
