### ISSUE TITLE
UrlRewrite showing errors for escape

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2822]
##### Issue Type

- Bug Report
##### Summary

Seeing unknown errors related to escape function on the go-server log. Check FunctionReplacer.java. 
###### Basic environment details

- Go Version: `16.10`
- JAVA Version: `1.8`
- OS: `WINDOWS`
- Browser vendor and version (if relevant): `Chrome`
##### Log snippets

```
2016-10-25 15:39:40,281  INFO [qtp67988628-17143] /go:2052 - org.tuckey.web.filters.urlrewrite.VariableReplacer ERROR: function ${escape:} type 'escape:' not a valid type
```

**Comment by dbalakirev** [comment]
GoCD version 18.6:

> 2018-07-20 10:21:11,918 ERROR [qtp1260134048-6919503] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
> 2018-07-20 10:21:12,218 ERROR [qtp1260134048-8386351] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type

**Comment by ketan** [comment]
@dbalakirev — what URL did you try and access?

**Comment by dbalakirev** [comment]
@ketan that is the thing a bit unfortunately. At the moment I don't know which users action lead to the error, or what URL they tried to access when this happened.

**Comment by maheshmadpathi** [comment]
@varshavaradarajan @arvindsv @ketan 
The issue still exists, any idea??

- Basic environment details
    GoCD Version: 19.11.0
    java version 1.7.0_231
    OS: Linux
    K8s Version: AWS EKS 1.14
    helm: 3
    Browser vendor and version (if relevant): Chrome

- Log snippet
  ``` bash
 jvm 1    | 2019-12-23 08:15:31,178  INFO [167@MessageListener for ServerPingListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:72 [plugin-cd.go.contrib.elasticagent.kubernetes] - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 0.
jvm 1    | 2019-12-23 08:15:41,381 ERROR [qtp2013268532-36] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:15:51,374 ERROR [qtp2013268532-27] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:16:01,398 ERROR [qtp2013268532-34] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:16:11,413 ERROR [qtp2013268532-33] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:16:21,427 ERROR [qtp2013268532-42] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:16:31,178  INFO [167@MessageListener for ServerPingListener] p.c.g.c.e.k.c.g.c.e.KubernetesPlugin:72 [plugin-cd.go.contrib.elasticagent.kubernetes] - [refresh-pod-state] Pod information successfully synced. All(Running/Pending) pod count is 0.
jvm 1    | 2019-12-23 08:16:31,447 ERROR [qtp2013268532-36] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:16:41,474 ERROR [qtp2013268532-33] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:16:51,509 ERROR [qtp2013268532-40] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:17:01,536 ERROR [qtp2013268532-31] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:17:11,550 ERROR [qtp2013268532-23] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
jvm 1    | 2019-12-23 08:17:21,569 ERROR [qtp2013268532-30] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
```

**Comment by eBeyond** [comment]
It seems that it's still there, or may be again... (In the latest available release)
2023-06-14 13:40:18,693 ERROR [qtp1970732060-40] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
2023-06-14 13:40:28,772 ERROR [qtp1970732060-32] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
2023-06-14 13:40:38,820 ERROR [qtp1970732060-43] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type
2023-06-14 13:40:48,900 ERROR [qtp1970732060-29] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type

**Comment by chadlwilson** [comment]
Yeah, it's still there, have seen it myself.

However, there is no obviously broken behaviour that has been associated with this it seems, and nor has anyone spent time tracing examples of the URL accessed that is triggering it, which it won't be addressed without. There are about 70 rewrite rules that use the `${escape:}` function so need to work out what it is.

There is a bug being triggered within [this library code](https://github.com/paultuckey/urlrewritefilter/blob/8d47a39f8ab4902350a48f894db6257c63e7cdc7/src/java/org/tuckey/web/filters/urlrewrite/utils/FunctionReplacer.java#L97-L133) by one of the rules containing `${escape:` within
https://github.com/gocd/gocd/blob/aca340bb65e4472ad9b0a3d1031e0d79656e12b5/server/src/main/webapp/WEB-INF/urlrewrite.xml#L25-L1220

From a brief read of the code and the error, I assume it's a bug triggered if the value of the "variable" part of the URL is empty or something like that. If the errors are coming every ten seconds consistently with a browser opened on a given page, it might might be one of the poll operations, possibly on the stage details or build details.

If someone wants to dig further and find a reproducer and some examples URLs via a browser network tab, or some other URL logging on server/backend, I can see if there is a workaround for the noise.

**Comment by eBeyond** [comment]
As far as I can see it's the call to 
`/go/api/internal/config_repos`
which leads to this message.

**Comment by chadlwilson** [comment]
That helps... is that the full URL that you think generated the error - i.e it's the listing of config repos?

From looking at the regex, the two related to that route do look a little mind boggling :-)

https://github.com/gocd/gocd/blob/aca340bb65e4472ad9b0a3d1031e0d79656e12b5/server/src/main/webapp/WEB-INF/urlrewrite.xml#L906-L916

**Comment by eBeyond** [comment]
Yes, that's the full URL (except hostname). There are no get-parameters appended to the url.

**Comment by chadlwilson** [comment]
Thanks! That helps - I'll look into it.

**Comment by chadlwilson** [comment]
After checking this, it seems this is fundamentally a bug in the library code - if a regex capturing group is empty, or has no 1+ char match the rewrite code does not handle the function mapping string manipulation correctly (or it becomes indeterminate). These optional pieces are intentional as there are optional parts of the URLs in same cases (say an optional end piece, or GET specific resources vs GET of collection of resources). However the behavior is a no-op, when it can't find a match it assumes the value is `""` which is the intent anyway, and why this doesn't lead to any issues - just logging noise.

The rules could probably be split into two rules to avoid the optional matches or we could just suppress the logging error by default to avoid this logging noise/confusion. Will think about and apply one of the fixes.
