### ISSUE TITLE
Add an `api/support` attribute to render available entropy (on systems with `/proc`)

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2831]

**Comment by ketan** [comment]
@arvindsv — can you close this if it's no longer needed, since we use the `/dev/urandom` — a comprehensive [blog post](http://www.2uo.de/myths-about-urandom/#low-entropy) that I'm reading seems to suggests that "It doesn't matter".

I'm also [reading that](http://security.stackexchange.com/a/86432)

> However, in "normal" Linux installations, a random seed is inserted early in the boot process; that seed was saved upon the previous boot, and is renewed immediately after insertion. That seed mostly extends the entropy of /dev/urandom across reboots. So the assertion becomes: if /dev/urandom had 200 bits of entropy at any point since the OS was first installed, then it still has 200 bits of entropy.

**Comment by arvindsv** [comment]
Yeah, I don't think this has been a concern since we moved to `/dev/urandom`. So, I will close it.
