### ISSUE TITLE
Introduce SPA for performing CRUD on elastic profiles

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2832]

**Comment by maheshp** [comment]
@ketan apart from this SPA, will there be an option to create/edit profiles from PipelineConfig SPA?

**Comment by ketan** [comment]
> @ketan apart from this SPA, will there be an option to create/edit profiles from PipelineConfig SPA?

TBD. Need to talk to @naveenbhaskar about it and see what he has to say.
