### ISSUE TITLE
API - Cannot get Pipeline Config if Name Contains Period

### ISSUE THREAD

**Issue by quater** [gocd/gocd#2833]
##### Issue Type

- Bug Report

##### Summary

This bug seems to be a **regression** of https://github.com/gocd/gocd/issues/1801, which is supposed to have addressed the problem with GoCD 16.3.0-3178. However I am encountering this same problem with version: 16.6.0 (3590-af0f8b8ae8a4342ab748ce80224971887f018ccc). The name of the pipeline is:
```
this_is_the.name
```
###### Basic environment details

* Go Version: `16.6.0 (3590-af0f8b8ae8a4342ab748ce80224971887f018ccc)`
* JAVA Version: `1.7.0_80`
* OS: `Linux 3.13.0-91-generic`

##### Steps to Reproduce

1. Create pipeline with name `this_is_the.name` via GUI
2. Use the API to get the pipeline config
```
╰─➤ curl 'https://blabla.com:8154/go/api/admin/pipelines/this_is_the.name' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v1+json' \
      -i \
      --insecure
HTTP/1.1 404 Not Found
Date: Wed, 02 Nov 2016 13:37:49 GMT
Set-Cookie: JSESSIONID=am7hl8nx1mw1bx1afasv3r9j;Path=/go;Expires=Wed, 16-Nov-2016 13:37:49 GMT;Secure
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: chrome=1
Content-Type: application/vnd.go.cd.v1+json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 9c065ad5-4a02-4603-878c-7d92f46fba54
X-Runtime: 0.006000
Transfer-Encoding: chunked

{
  "message": "The resource you requested was not found!"
}
```

##### Expected Results
It should return the pipeline config.

##### Actual Results
The resource is not found.

##### Any other info
I am currently not in the position to test with the latest GoCD version.

**Comment by varshavaradarajan** [comment]
@quater, this bug was fixed in GoCD release 16.8. You can see the issue [here](https://github.com/gocd/gocd/issues/2529) . In GoCD release 16.6.0, this was a regression bug and was not fixed until 16.8. Closing this as it is resolved.
