### ISSUE TITLE
Error page displayed when clicking on environment created by gocd-yaml-plugin

### ISSUE THREAD

**Issue by zerolaser** [gocd/gocd#2835]
##### Issue Type

- Bug Report

##### Summary

I was using the `Gocd-yaml-config plugin`  for creating pipelines and environments and adding them to the config xml. when i click on the environment, which i created this way, the go-server was throwing an error. 
![image](https://cloud.githubusercontent.com/assets/7926653/19936926/85acf112-a0dc-11e6-9b2c-32749615d1d8.png)

###### Basic environment details

* Go Version: ` Go Version: 16.11.0 (4185-e7acc53aac8bb5ad2a7f306ca8f3e752855d844b)`
* JAVA Version: `1.8.0_92`
* OS: `Linux 2.6.32-642.4.2.el6.x86_64`
* Browser vendor and version (if relevant): `Chrome 53.0.2785.143 m`
* Yaml configuration plugin: `0.2.0`

##### Steps to Reproduce

1.  Here's the GOcd yaml file https://gist.github.com/zerolaser/c814a3527e82aac7fe316e9050b8f202
2.  adding the following to the config xml
```xml
<config-repos>
  <config-repo plugin="yaml.config.plugin">
    <git url="https://git.example.net/user/Gocd-test.git" />
  </config-repo>
</config-repos>
```
Once the Go-server pick up the change it should be displaying the pipelines and environments. now when you navigate to the environment and click on the `example` environment, it throws the above error page.
##### Expected Results

 it should be displaying the environment as it is, except the edit option should be disabled.
##### Actual Results

error page

##### Log snippets

```
2016-11-02 16:32:34,484 FATAL [qtp1334729950-33] Rails:? - 
Java::JavaLang::RuntimeException (Object [com.thoughtworks.go.config.BasicEnvironmentConfig@dcd9415[name=example,
variables=[],agents=[com.thoughtworks.go.config.EnvironmentAgentConfig@5700bbd1],
pipelines=[],configErrors={},origin=com.thoughtworks.go.config.remote.FileConfigOrigin@5b9b],
 com.thoughtworks.go.config.BasicEnvironmentConfig@23f29318[name=example,variables=[],agents=[],
pipelines=[com.thoughtworks.go.config.EnvironmentPipelineConfig@c0ddd95a],configErrors={},origin=git@git.example.net:user/GoCd-test.git at 22d14d02fa0474a5773d4900b499f5047be69cd]] does not have a ConfigTag):
```

**Comment by rajiesh** [comment]
Verified on GoCD version 16.12.0 (4331-7cd56f28bf55417221a608140e72532de5501f5a), environments created from the config-repos are accessible now, however we need to disable the edit option on environments page as mentioned in this comment - https://github.com/gocd/gocd/pull/2867#issuecomment-262719664. Will create another issue to track that
