### ISSUE TITLE
Agent SPA page accessible only for admins

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#2845]
##### Issue Type

- Bug Report

##### Summary

Agent SPA page is accessible only for admin users. Non admin users should have access to view but not edit the agents

###### Basic environment details

* Go Version: `16.12.0 (4228-f7dde65070f0964bc9ea8643aa0b5c3c66332bb6)`

##### Steps to Reproduce

1. Visit agent SPA page as any non admin users

##### Expected Results

Non admin users should be able to view the agents, but not edit

##### Actual Results

403 Forbidden error shown

**Comment by ketan** [comment]
See #2879

**Comment by rajiesh** [comment]
Verified on 16.12.0 (4305-25b6f3d9eef3f9b30acd65ac9965b8776a917e9d), working as expected
