### ISSUE TITLE
Filtering enhancement on Agents SPA page

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#2852]
##### Issue Type
- Feature enhancement

##### Summary

On the old agent page it was possible to choose the type of filter to perform e.g.
name, os, ip, status, resource or environment. 

On the new page the filter is a general filter looking for any instance of the text regardless of where it appears. I find this behavior much less useful than the previous one, especially when the text being sought could appear in multiple columns.

##### Environment

Any

###### Basic environment details

Go Version: 16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d).
Go Server Version:	16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d)
JVM version:	1.7.0_111
OS Information:	Linux 3.16.0-4-amd64
Usable space in artifacts repository:	78.2 GB
Database schema version:	1610001

###### Additional Environment Details

n/a

##### Possible Fix
Allow filtering for specific columns by prefixing the search with the column type first in the same way as the previous page allowed e.g. name: myagent

**Comment by arvindsv** [comment]
Closing as 'WONT-FIX'. There have been many changes to make the agents page better and this isn't planned.
