### ISSUE TITLE
Error and warning messages in development environment

### ISSUE THREAD

**Issue by sadovnikov** [gocd/gocd#2854]
##### Issue Type

- Bug Report

##### Summary

When running both Server and Agent in a freshly created development environment, the following errors and warnings are seen

```
Command Repository [Nov-10 17:53:28]
Unable to upgrade command repository located at /jv-ration/projects/oss/thoughtworks/gocd/server/db/command_repository/default. Message: in is null

Command Repository [Nov-10 17:58:14]
Failed to access command repository located in Go Server Directory at db/command_repository/default. The directory does not exist or Go does not have sufficient permissions to access it.
```

![image](https://cloud.githubusercontent.com/assets/4749332/20186528/b1408376-a770-11e6-9cac-a21f79750cf5.png)

##### Environment

Build the project in IntelliJ and run both Server and Agent using instructions on https://developer.go.cd/current/2/2.1.html. I'm using commit `b417f9a`

###### Basic environment detail

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

###### Additional Environment Details

![image](https://cloud.githubusercontent.com/assets/4749332/20186777/944b9700-a771-11e6-913c-aef1e55024f2.png)

##### Steps to Reproduce

Open http://localhost:8153/ and "Errors and Warnings" appear in bottom right corner

##### Possible Cause

Possibly step https://developer.go.cd/current/2/2.1.html#2-1-2-setup-intellij to prepare database does not complete its job. However `null` is not handled correctly in the error message

**Comment by sadovnikov** [comment]
After changing the code in , the missing error message is about failure to find `/defaultFiles/defaultCommandSnippets.zip`

**Comment by sadovnikov** [comment]
Even explicit execution of `./gradlew server-launcher:defaultCommandSnippetsZip` does not create `defaultCommandSnippets.zip` anywhere...

I do find cloned "command repo" in `server-launcher/target/go-command-repo` and there is `defaultCommandSnippets-16.12.0-4245.zip` file generated in `server-launcher/target/libs`

Seems extending the generated filename with version is the problem.... or should the server be looking for "versioned" file?

**Comment by arvindsv** [comment]
I think the scripts can be changed to copy/link the snippets to a similarly named file without the version. The server shouldn't be looking for the versioned file, IMO. @ketan probably knows best, but [this line](https://github.com/gocd/gocd/blob/master/server-launcher/build.gradle#L223) is probably what needs to be looked at.
