### ISSUE TITLE
Gracefully handle Page load errors on SPA

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#2878]
##### Issue Type

- Bug Report

##### Summary

Loading the Pipeline_config and Agents SPA involves making multiple API calls to fetch resources. A spinner is shown on the page till all the required resources are loaded. In cases of failed API calls or JS errors during page load the spinner is continues to be shown for ever and the user is not indicated with any errors which seems misleading.

**Comment by GaneshSPatil** [comment]
We should render [Page load error](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/webpack/views/shared/page_load_error.js.msx) template page when resource API calls fail.

**Comment by GaneshSPatil** [comment]
As part of **SPA componentization**, we've introduced [Page](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails/webpack/views/pages/page.tsx) abstraction which will display [PageLoadError](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails/webpack/views/pages/page.tsx#L44), if the initial API call(s) fails.
