### ISSUE TITLE
UI issues on elastic agent profiles pages

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2883]
##### Issue Type

- Bug Report

##### Summary

**Alignment of the delete and edit icons seems off by a pixel.**

![screen shot 2016-11-22 at 10 01 18 am](https://cloud.githubusercontent.com/assets/10598/20511017/ba4042ee-b09a-11e6-94f6-d576ca24a0ec.png)

**The affordances on the buttons on modals seems off**

The bottom margin on the button is higher than the side margins. Plus no margin on top. Would be nice if we could demarcate the `modal-buttons` css class with a different background or a top border or something.

![screen-shot-2016-11-22-at-9 48 18-am](https://cloud.githubusercontent.com/assets/10598/20511045/ec7ebe5c-b09a-11e6-996e-1982b2341d66.png)

![screen shot 2016-11-22 at 10 02 59 am](https://cloud.githubusercontent.com/assets/10598/20511057/ffe27e48-b09a-11e6-819c-e9475374a1f1.png)

**Comment by ketan** [comment]
Also —

There's a scroll on the page, even when there's not enough content. Very similar to the scroll on the agent page https://github.com/gocd/gocd/issues/2855

**Comment by maheshp** [comment]
edit and delete icons need to be aligned
Modal close button needs to be aligned
