### ISSUE TITLE
Files or folders that contain two or more periods in an Artifact folder can't be uploaded to the server.

### ISSUE THREAD

**Issue by SanderVerkuil** [gocd/gocd#2894]
##### Issue Type

- Bug Report

##### Summary

The server throws an error when an agent tries to upload a folder which contains two periods (`..`). In both Windows 10 and Unix file systems these names are valid.

###### Basic environment details

* Go Version: `16.11.0 (4185-e7acc53aac8bb5ad2a7f306ca8f3e752855d844b)`
* JAVA Version: `1.7.0_80`
* OS: `Linux 4.4.0-45-generic`

##### Steps to Reproduce

1. Have a pipeline with a single stage, a single job and a two tasks.
  * `mkdir output`
  * `touch output/hello..world.txt`
2. Define output as an artifact directory
3. Trigger the pipeline.

##### Expected Results
I expect to see the in the artifacts folder the folder `output` with a single file `hello..txt`.

##### Actual Results
The server throws an IllegalPathException. 

##### Possible Fix
[The location where the exception is thrown](https://github.com/gocd/gocd/blob/master/base/src/com/thoughtworks/go/util/ZipUtil.java#L117)
I'm not much of a Java person myself, but I think that just checking if the filepath contains two periods is enough. As we can see in the above example, filenames can indeed contain two or more periods. I'm not even entirely sure how the Zip plugin handles files containing periods.

##### Log snippets
```
2016-11-23 18:03:14,552 ERROR [qtp290178723-32] ArtifactsService:107 - Failed to save the file to: [/var/lib/go-server/artifacts/pipelines/Test/1/test/2/test]
com.thoughtworks.go.util.IllegalPathException: File output/hello..world.txt is outside extraction target directory
```

**Comment by wlsf82** [comment]
+1
