### ISSUE TITLE
Cyrillic characters are not displayed correctly in the console

### ISSUE THREAD

**Issue by APshenkin** [gocd/gocd#2900]
##### Issue Type
- Bug Report

##### Summary

Cyrillic characters are not displayed correctly in the console. Looks like GO Server can't convert characters from Windows Agents because of difference in encoding
Here is an example:
String ```Проверка перехода на страницу о достижениях```
displays ```�?�?ове�?ка пе�?е�?ода на �?�?�?ани�?�? �? до�?�?ижени�?�?``` if English was setted for non-Unicode Programs (OEM encoding cp437)

displays ```?????????�?????� ???�???�???????� ???� ???????�???????? ?? ???????????�?�????????``` if Russian was setted for non-Unicode Programs (OEM encoding cp866)

###### Basic environment details
* Go Version: 16.7.0
* JAVA Version: 1.8.0_66
* OS: Ubuntu 14.04

###### Additional Environment Details
Windows 7 x64 and Windows 10 x64 agents

##### Steps to Reproduce
1.  Add any logs with Cyrillic symbols in your application
2. Set language for non-Unicode Programs (English or Russian)
3. Assign Job with your application to Windows agent
4. Check the console output on Go Server

##### Expected Results
Cyrillic characters are displayed in console with correct encoding

##### Actual Results
Cyrillic characters are displayed with broken chars

##### Possible Fix
Before sending the buffer with updated console log, convert encoding of it to UTF-8

**Comment by carrchang** [comment]
Chinese characters also, any way to set encoding of the console?

**Comment by arvindsv** [comment]
Unfortunately not. If you or someone else can dig into this a bit more and see where it is being forced to be UTF-8, then maybe we might be able to change it.

**Comment by ketan** [comment]
Closing as dup of #3926.
