### ISSUE TITLE
Docker CD with GO

### ISSUE THREAD

**Issue by saithala** [gocd/gocd#2906]
Issue Type

Question

Summary

I'm trying to explore the usage of Go for CD for dockerized applications. Any pointers and examples on how to achieve that would be really helpful 

Environment

Basic environment details

Go Version: 16.11
JAVA Version: 1.8.0_45
OS: Redhat 7

**Comment by arvindsv** [comment]
Hello @saithala. As I mentioned in #2904, this (GitHub issues) is a forum for issues in GoCD. Since this is a question, it's probably more appropriate in the [mailing list](https://groups.google.com/forum/#!forum/go-cd) (please search the archive before posting). So, I'm closing this.
