### ISSUE TITLE
New theme UI issues

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#2911]
##### Issue Type

- Bug Report

##### Summary

This is a place holder to capture all UI issues with the new theme. Please add and screenshot and a link to navigate to the page with issues.

**Comment by bdpiparva** [comment]
1) Error message position 
2) Plugin icon too close to border

<img width="1440" alt="screen shot 2016-11-30 at 2 29 14 pm" src="https://cloud.githubusercontent.com/assets/7871209/20745780/d1ee8670-b708-11e6-8f45-e2bd961f29ae.png">

**Comment by bdpiparva** [comment]
1) Click on Pipeline progressbar
2) From stage history click on  config changed
 Attached screen will appear.

Can we remove space marked in red ?

<img width="762" alt="screen shot 2016-11-30 at 4 38 31 pm" src="https://cloud.githubusercontent.com/assets/7871209/20750269/040853c6-b71c-11e6-9125-41f851c9c794.png">
<img width="763" alt="screen shot 2016-11-30 at 4 38 55 pm" src="https://cloud.githubusercontent.com/assets/7871209/20750270/040d6cda-b71c-11e6-9b61-9c5336b66814.png">

**Comment by maheshp** [comment]
Trigger with options on Chrome

![screen shot 2016-12-01 at 10 19 37](https://cloud.githubusercontent.com/assets/1061051/20782221/d3fdad86-b7af-11e6-8a76-6920df0398ed.png)

**Comment by maheshp** [comment]
Environments Page on Chrome

![screen shot 2016-12-01 at 10 15 35](https://cloud.githubusercontent.com/assets/1061051/20782266/68cf89a2-b7b0-11e6-80b5-129ffd3ac761.png)

**Comment by maheshp** [comment]
Job details page, alignment issue - Chrome

![screen shot 2016-12-01 at 10 35 48](https://cloud.githubusercontent.com/assets/1061051/20782452/0177dab4-b7b2-11e6-81c2-eac5ab162339.png)

**Comment by maheshp** [comment]
New agents page on chrome, ```(cancelled)```  text on multiline
![screen shot 2016-12-01 at 10 37 29](https://cloud.githubusercontent.com/assets/1061051/20782507/66faf86c-b7b2-11e6-83d4-4deb08937208.png)

**Comment by iamsumanth** [comment]
Suggestion to input box in plugin settings moves along with the curser.

<img width="1432" alt="elastic-agent" src="https://cloud.githubusercontent.com/assets/17640031/20782537/a937831c-b7b2-11e6-8068-f7f04ffbdc43.png">

**Comment by zabil** [comment]
Failure tab has white space around console log.
https://build.go.cd/go/tab/build/detail/installer-tests/156/upgrades/1/upgrade

![failuretab](https://cloud.githubusercontent.com/assets/54427/20783779/05e6d4d8-b7bc-11e6-8c3c-be7cb8da9bdf.png)

**Comment by zabil** [comment]
Firefox 50 has issues with agent status drop down when the text wraps
![agent arrow](https://cloud.githubusercontent.com/assets/54427/20783851/83ec1032-b7bc-11e6-8d8f-febc058d15d1.png)

**Comment by zabil** [comment]
Can we set some word break properties on the material changes pop up on the dashboard page?

![changes word break](https://cloud.githubusercontent.com/assets/54427/20784005/a0bc5324-b7bd-11e6-99c8-e35d1a72ccba.png)

**Comment by naveenbhaskar** [comment]
![image](https://cloud.githubusercontent.com/assets/1627961/20784733/2caaa166-b7c2-11e6-9a71-4e041472109e.png)

stage details page -> left panel broken

**Comment by naveenbhaskar** [comment]
alignment

**Comment by ketan** [comment]
Textareas are not high enough — They are forced to be 30px. **I'm fixing this**


![screen shot 2016-12-01 at 3 15 39 pm](https://cloud.githubusercontent.com/assets/10598/20789062/1f8dcb72-b7d9-11e6-8f98-fe1557b7345a.png)

**Comment by bdpiparva** [comment]
**Fixed Material popup**

![](https://cloud.githubusercontent.com/assets/54427/20784005/a0bc5324-b7bd-11e6-99c8-e35d1a72ccba.png)

**Comment by bdpiparva** [comment]
1) Go to job page
2) Change theme of console(just for better visibility)
3) Scroll the console(or Failures log if any) log

<img width="1082" alt="screen shot 2016-12-01 at 4 13 25 pm" src="https://cloud.githubusercontent.com/assets/7871209/20791073/4a312844-b7e1-11e6-9c13-92bd2a129454.png">

**Comment by bdpiparva** [comment]
Pipeline history page: Misaligned "PAUSE"
<img width="720" alt="screen shot 2016-12-01 at 4 26 44 pm" src="https://cloud.githubusercontent.com/assets/7871209/20791353/8dacde78-b7e2-11e6-8322-f3557cb297aa.png">
 button

**Comment by rajiesh** [comment]
Issue with the Custom Command Task  page in pipeline create and edit flow.
1. Create a pipeline
2. On Stage/Job setting page select the task type as 'more'
3. The arguments text box should be a multi-line text field with height enough to view the arguments, but we see it like this,(similarly on the task edit page for custom command tasks)

<img width="795" alt="screen shot 2016-12-01 at 4 39 18 pm" src="https://cloud.githubusercontent.com/assets/6533924/20791787/c0897d90-b7e4-11e6-9d7f-7e5d2787ec94.png">

**Comment by ketan** [comment]
**I'm fixing this** The breadcrumb on the job detail page is mis-aligned, renders fine on the stage details page.

![screen shot 2016-12-01 at 5 06 32 pm](https://cloud.githubusercontent.com/assets/10598/20792591/a0329ffa-b7e8-11e6-804d-7ac95d3e2a7c.png)
![screen shot 2016-12-01 at 5 06 37 pm](https://cloud.githubusercontent.com/assets/10598/20792592/a0364de4-b7e8-11e6-9a2e-79b7c8d90b4f.png)

**Comment by ketan** [comment]
Side margin on the job detail page is lot more than that on the stage detail page —


![stage detail go](https://cloud.githubusercontent.com/assets/10598/20792716/5a8556b8-b7e9-11e6-9751-0591a7defb13.png)
![up42_job job details go](https://cloud.githubusercontent.com/assets/10598/20792717/5ab02104-b7e9-11e6-83ad-bbb137b03e11.png)

**Comment by varshavaradarajan** [comment]
<img width="1440" alt="screen shot 2016-12-02 at 9 30 36 am" src="https://cloud.githubusercontent.com/assets/4715748/20822615/201e53e2-b872-11e6-9bf0-76b00dc2923b.png">

Header containing ```Change theme, raw output, scroll to the end of logs``` is at the center of console log instead of at the top.

Priority: High.

**Comment by bdpiparva** [comment]
Pipeline history: trigger this pipeline button is mis-aligned

<img width="690" alt="screen shot 2016-12-02 at 11 03 54 am" src="https://cloud.githubusercontent.com/assets/7871209/20823955/c1598716-b87e-11e6-8bce-dd6422b70b78.png">

**Comment by zabil** [comment]
https://build.go.cd/go/tab/mycruise/user

Tabs jumps because of missing padding while switching between notifications and oAuthAccess tokens
![notifications](https://cloud.githubusercontent.com/assets/54427/20824438/d30edcd2-b882-11e6-9fe6-65e4441a1c21.png)

![oauthaccesstokens](https://cloud.githubusercontent.com/assets/54427/20824445/dae0b110-b882-11e6-8c31-f8d511cd7bb8.png)

The same page has a problem with the "only if it contains" checkbox

![onlyifitcontains](https://cloud.githubusercontent.com/assets/54427/20824519/865b1bb6-b883-11e6-906b-75e97495f54f.png)

**Comment by bdpiparva** [comment]
https://github.com/gocd/gocd/pull/2926/ having issue with config.xml edit textarea

<img width="1420" alt="screen shot 2016-12-02 at 11 58 46 am" src="https://cloud.githubusercontent.com/assets/7871209/20824873/ffd9d98a-b885-11e6-9e4e-037dffb393d5.png">

**Comment by ketan** [comment]
Textareas have too much line height making it look like there's a carriage return —

This is the text area on an `<exec/>` task

![screen shot 2016-12-02 at 11 54 05 am](https://cloud.githubusercontent.com/assets/10598/20824895/256bdee6-b886-11e6-93b9-d986c9138ec9.png)

**Comment by ketan** [comment]
The floating toolbar on the console log is wrapping —

![screen shot 2016-12-02 at 11 56 51 am](https://cloud.githubusercontent.com/assets/10598/20824933/83a242ac-b886-11e6-820d-e7d335187769.png)

**Comment by ketan** [comment]
The console log is not occupying the full width on a smaller screen, looks fine once you start scrolling


![screen shot 2016-12-02 at 11 59 49 am](https://cloud.githubusercontent.com/assets/10598/20824982/f627aa24-b886-11e6-96de-615e82872ee2.png)

**Comment by bdpiparva** [comment]
https://github.com/gocd/gocd/pull/2926 Fixed 

![](https://cloud.githubusercontent.com/assets/7871209/20783829/6103f9ea-b7bc-11e6-960e-52908b9f59e8.png)

**Comment by bdpiparva** [comment]
https://github.com/gocd/gocd/pull/2926

![](https://cloud.githubusercontent.com/assets/7871209/20783833/6584c5b2-b7bc-11e6-893f-44f24f0484c3.png)
 Fixed

**Comment by bdpiparva** [comment]
https://github.com/gocd/gocd/pull/2926 Fixed

![](https://cloud.githubusercontent.com/assets/7871209/20788951/b180aa3c-b7d8-11e6-8b4a-a9a8ce378722.png)

**Comment by bdpiparva** [comment]
Pipeline quick edit: 
1. Icon mis-aligned in Save button
2. Save your changes button transform to green with check icon. Without reload/refresh make some changes still save button remains green.

<img width="1416" alt="screen shot 2016-12-02 at 12 29 42 pm" src="https://cloud.githubusercontent.com/assets/7871209/20825542/bd51d900-b88a-11e6-9264-3e08333c21f0.png">

**Comment by zabil** [comment]
The vsm does not display the progress bar when the build is in progress.

![vsm](https://cloud.githubusercontent.com/assets/54427/20915204/5671167e-bbaa-11e6-90ee-e259251e4ef3.png)

**Comment by zabil** [comment]
The padding between the header and tabs not consistent.
https://build.go.cd/go/admin/templates

![paddingtemplates](https://cloud.githubusercontent.com/assets/54427/20916161/5084791c-bbb0-11e6-8af8-9d126ebd1a36.png)

vs

https://build.go.cd/go/tab/mycruise/user
![paddingpreferences](https://cloud.githubusercontent.com/assets/54427/20916310/1aea5816-bbb1-11e6-80bb-e3ffa4feef9e.png)
