### ISSUE TITLE
Elastic agents don't work with pipelines configured via config repos

### ISSUE THREAD

**Issue by juhasipo** [gocd/gocd#2922]
##### Issue Type

- Feature enhancement

##### Summary

We have an environment using the JSON config repo plugin and Docker elastic agents.
I started testing the config repos in the environment but it seems that the config repo plugins can't configure jobs to use elastic agents yet. All the jobs are built with the regular agents instead of elastic ones even if the `elastic_profile_id` would be given in the job config.

The JSON plugin documentation doesn't really say how to configure the elastic agents to work so I assume this is still a missing feature rather than a bug.

###### Basic environment details

* Go Version: `GoCD Server 16.11.0`
* JAVA Version: `1.7.0_111`
* OS: `Linux 3.13.0-32-generic`
* JSON config repo plugin: `0.2`

##### Steps to Reproduce

1. Configure one elastic agent profile
2. Configure one pipeline with the JSON config repo plugin and try to configure it to use elastic agent via `elastic_profile_id` in JSON job config

##### Expected Results
Pipeline's job should be built using an elastic agent.

##### Actual Results
Pipeline's job is built using a normal agent.

**Comment by tomzo** [comment]
> The JSON plugin documentation doesn't really say how to configure the elastic agents to work so I assume this is still a missing feature rather than a bug.

Yes, there is no support for elastic agents. It requires to add on server side, then it will *magically* work in JSON plugin. Yaml plugin might need some update.

@ketan I only tried elastic agents once, just after first release. But lately there were elastic profiles added, so please correct me if I am wrong:
The only element to be specified **within pipeline configuration is the `elastic_profile_id`** in job config?
Profiles are specified in XML, so there is no need to specify them via configuration repositories.

If above is true, then it looks much easier than before profiles were introduced. One string field to be added in [CRJob](https://github.com/gocd/gocd/blob/master/plugin-infra/go-plugin-access/src/com/thoughtworks/go/plugin/access/configrepo/contract/CRJob.java) should do it.

**Comment by ketan** [comment]
> @ketan I only tried elastic agents once, just after first release. But lately there were elastic profiles added, so please correct me if I am wrong:

> The only element to be specified within pipeline configuration is the elastic_profile_id in job config?

That is correct — and associated validation, if any.

**Comment by juhasipo** [comment]
This works now as expected in 16.12.0. Thanks @tomzo @ketan !
