### ISSUE TITLE
Material URL's are case-sensitive

### ISSUE THREAD

**Issue by unixunion** [gocd/gocd#2931]
##### Issue Type

- Bug Report

##### Summary

Material trigger over REST fails with 404 if case-mismatch in git material URL.  

##### Environment

I am using bitbucket which is NOT case-sensitive for repository urls, and when using a hook to post the repository URL back to GoCD in order to trigger pipelines, I get a 404 if there is a case-mismatch. 

The API within bitbucket returns all lowercase repository urls.

###### Basic environment details

* Go Version: 16.11.0
* JAVA Version: 1.8
* OS: Linux RHEL 6.5

##### Steps to Reproduce

post a case incorrect git material url to the api.

##### Expected Results

Materials should trigger regarding of case.

##### Actual Results

Case mismatch returns a 404.

##### Possible Fix

case-insensitive match configuration option for GoCD

**Comment by ketan** [comment]
URLs are supposed to be [case sensitive](https://tools.ietf.org/html/rfc3986#section-6.2.2.1) — by definition. Sometimes hosting providers like github and bitbucket allow case-insensitive URLs — but that's upto the hosting provider —

Take the following example —

```
$ git ls-remote git://repo.or.cz/git.git
$ git ls-remote git://repo.or.cz/GIT.GIT
```

You'll notice that the second url `git://repo.or.cz/GIT.GIT` fails as expected (assuming you're running on a case-sensitive file system)

**Comment by unixunion** [comment]
Yes @ketan, but can we have an option to "allow" case-insensitive material triggers, otherwise GoCD does not work for my environment which currently has thousands of pipelines.

**Comment by ketan** [comment]
> Since BitBucket, when asked to pass a material url to Go, seems to generate the URL in all lowercase, even though a repo is created with specific capitalization.

Could you throw some light on how bitbucket is passing the material URL to Go?
