### ISSUE TITLE
Ability to cancel a build from pipeline dashboard

### ISSUE THREAD

**Issue by MattRiesterer** [gocd/gocd#2933]
##### Issue Type

- Feature proposal

##### Summary

To allow users to cancel a running build more quickly, there should be the possibility to cancel a running build from the pipeline dashboard.
Either the "Trigger" button is turned into a "Cancel" button or a new button "Cancel" next to the "Trigger" button. When pressing the "Cancel" button, the currently running stage is cancelled.

##### Code snippets/Screenshots
![image](https://cloud.githubusercontent.com/assets/6588730/20865002/3dfcbf94-ba06-11e6-9387-fa28a3c0f0d5.png)

**Comment by lobsterdore** [comment]
@MattRiesterer I think this would be a great addition, cancelling builds is quite clunky at the moment.
