### ISSUE TITLE
Ability to approve next stage from pipeline dashboard

### ISSUE THREAD

**Issue by MattRiesterer** [gocd/gocd#2934]
##### Issue Type

- Feature proposal

##### Summary

Provide the ability to trigger the next stage ("approve") from pipeline dashboard. That reduces the number of clicks a user has to perform an approval.

The "Approve" button is active/visible if:
- first stage did not yet run
- next stage is configured to wait for manual approval
- user is authorized to operate on a pipeline

##### Code snippets/Screenshots

![image](https://cloud.githubusercontent.com/assets/6588730/20865094/7b788630-ba08-11e6-8e6e-a14c29d7b7d6.png)

**Comment by varshavaradarajan** [comment]
Closing this as we're working on the dashboard UX through 
 https://github.com/gocd/gocd/issues/3872 and https://github.com/gocd/gocd/issues/4037
