### ISSUE TITLE
Issues with the new theme

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#2940]
Go Version: 16.12.0 (4331-7cd56f28bf55417221a608140e72532de5501f5a

**Comment by zabil** [comment]
The vsm does not display the progress bar when the build is in progress.

![vsm](https://cloud.githubusercontent.com/assets/54427/20915204/5671167e-bbaa-11e6-90ee-e259251e4ef3.png)

**Comment by zabil** [comment]
The padding between the header and tabs not consistent.
https://build.go.cd/go/admin/templates

![paddingtemplates](https://cloud.githubusercontent.com/assets/54427/20916161/5084791c-bbb0-11e6-8af8-9d126ebd1a36.png)

vs

https://build.go.cd/go/tab/mycruise/user
![paddingpreferences](https://cloud.githubusercontent.com/assets/54427/20916310/1aea5816-bbb1-11e6-80bb-e3ffa4feef9e.png)

**Comment by bdpiparva** [comment]
Build history page: trigger build icon

<img width="497" alt="screen shot 2016-12-06 at 12 54 46 pm" src="https://cloud.githubusercontent.com/assets/7871209/20916767/71d12e14-bbb3-11e6-959a-d520f8daeff5.png">

**Comment by bdpiparva** [comment]
Check height and font properties of highlighted part

<img width="581" alt="screen shot 2016-12-06 at 1 32 21 pm" src="https://cloud.githubusercontent.com/assets/7871209/20917504/efd5a19c-bbb7-11e6-9e5d-d135095842a8.png">

<img width="588" alt="screen shot 2016-12-06 at 1 32 34 pm" src="https://cloud.githubusercontent.com/assets/7871209/20917510/f7d1080a-bbb7-11e6-84d3-f589ce3cd463.png">
<img width="603" alt="screen shot 2016-12-06 at 1 32 49 pm" src="https://cloud.githubusercontent.com/assets/7871209/20917511/f7fddf56-bbb7-11e6-844b-eb706ec4b832.png">
<img width="525" alt="screen shot 2016-12-06 at 1 32 59 pm" src="https://cloud.githubusercontent.com/assets/7871209/20917512/f823b122-bbb7-11e6-9ab0-22f1118e5a19.png">

**Comment by iamsumanth** [comment]
Password filed is not aligned properly.
![password_field](https://cloud.githubusercontent.com/assets/17640031/20917832/c7ec780c-bbb9-11e6-83d0-aa43b11ed065.png)

**Comment by maheshp** [comment]
![screen shot 2016-12-06 at 14 04 50](https://cloud.githubusercontent.com/assets/1061051/20918434/fe806434-bbbc-11e6-92fe-040d1559df2e.png)

**Comment by zabil** [comment]
@maheshp apparently the width is intentional

**Comment by maheshp** [comment]
Oh, dint know that but it looks a bit wired. Anyways will talk to @naveenbhaskar bout it.

**Comment by ketan** [comment]
@maheshp @zabil — the width was intentionally set wider than what it used to be, along with some cleanup of the 3 columns in the popup.

Currently the modal is set to 80% of the screen width, I can see how it can look bad on big screens, perhaps set a max width on larger screens to cap it to say ~1000px?

**Comment by maheshp** [comment]
@ketan 80% seems wide on small screen as well. Also I see the SHA being truncated and the link to vsm next to the SHA not shown.

![screen shot 2016-12-06 at 15 19 24](https://cloud.githubusercontent.com/assets/1061051/20920922/f1795326-bbc7-11e6-90db-0b221487ce73.png)

**Comment by ketan** [comment]
Some parts of the console output that output color uses open sans —

See the green color output at https://build.go.cd/go/tab/build/detail/build-linux/1377/build-server/1/rspec-split-runInstance-3

**Comment by ketan** [comment]
Textarea on the Add pipeline wizard does not look like it's multiline —

<img width="613" alt="screen shot 2016-12-07 at 10 28 47 am" src="https://cloud.githubusercontent.com/assets/10598/20955284/19e2b898-bc68-11e6-8e38-39610ff7b487.png">

**Comment by ketan** [comment]
Also most select boxes look tiny compared to the textboxes.

**Comment by jaymed** [comment]
**Pipeline labels longer than 11 characters are obscured by stage status bar.** :unamused:

![image](https://cloud.githubusercontent.com/assets/6611080/21031897/db52810a-bd5a-11e6-9cf5-37561214de8f.png)
