### ISSUE TITLE
Page Autorefresh not working in version 16.11.0

### ISSUE THREAD

**Issue by prabhu43** [gocd/gocd#2944]
##### Issue Type

- Bug Report

##### Summary

If I trigger a pipeline from pipelines page, the status of pipeline is not automatically updated. Only after page refresh, it turns to status in-progress(yellow). Page AutoRefresh not working in Version 16.11.0. 

###### Basic environment details

* Go Version: 16.11.0(latest)
* JAVA Version: 1.8.0_66
* OS: Linux 2.6.32-642.6.2.el6.x86_64
* Browser vendor and version (if relevant): Chrome 54.0.2840.98

**Comment by zabil** [comment]
That's strange, this functionality has been tested thoroughly by our regression suite and daily usage. Is it only the in-progress state? Does it update automatically once the build passes or fails?

**Comment by prabhu43** [comment]
@zabil It is happening for all states. No, its not updating automatically even if build passes or fails. Not just home page(all pipelines page), even in the build page, the progress/status is not updating automatically.

**Comment by lenucksi** [comment]
@prabhu43 I was not able to reproduce this with a recent Firefox on OS X. Could it maybe be related to any Chrome plugins?

**Comment by prabhu43** [comment]
@lenucksi 
I tried in Safari and able to reproduce that issue. In firefox, I am having some other issue related to login. Login with valid credentials is consistently failing in firefox. When i checked network tab, there are many GET requests to url "https://<hostname>/go/auth/undefined" with response code 404.

**Comment by arvindsv** [comment]
I suspect this is some kind of a proxy related issue (do you have one?). Could also be related to a wrong ["Site URL"](https://docs.go.cd/current/installation/configuring_server_details.html#configure-site-urls). As far as I know, this functionality is working fine. Can you provide more details about these two aspects? Thanks!

**Comment by prabhu43** [comment]
The issue is with the apache configuration, behind which go-server is running. Its fixed now. Thanks
