### ISSUE TITLE
Custom SCM material plugins do not show up in the list of materials when creating a new pipeline

### ISSUE THREAD

**Issue by alethenorio** [gocd/gocd#2947]
##### Issue Type

- Bug Report

##### Summary

When creating a new pipeline and selecting a material type, a custom written SCM plugin does  not show up in the list of material candidates

##### Environment

Gocd server running in a docker container

###### Basic environment details

* Go Version: `16.11`
* JAVA Version: `1.8`
* OS: `Docker container running Ubuntu`
* Browser vendor and version (if relevant): `Chrome/Firefox`

##### Steps to Reproduce

1. Create a plugin using the SCM extension
2. Create a new pipeline and follow the wizard until the part you have to create or select a materi
3. Click on the drop down of materials to select one
4. Notice that the custom written SCM plugin is nowhere to be found in the list

##### Expected Results

The plugin type should appear in the list below the other supported SCM materials (such as git, svn and so on) 

##### Actual Results

The material type is not present in the list and therefore cannot be selected

##### Any other info

The custom material does show up in the list when you try to add a new material to an existing pipeline so I think this is an issue with the UI not presenting in the pipeline creation section.

This means it is possible to work around the issue by creating a dummy material and then switching after the pipeline has been created but it makes for a very broken user experience

**Comment by rogerioyuuki** [comment]
When I had this problem before, I found an old Github issue. I thought it was relevant to put the link here.

https://github.com/gocd/gocd/issues/976

**Comment by kszatan** [comment]
I'm working on this.

**Comment by mrmanc** [comment]
It looks like work on this issue in #3886 stalled, but this is still an issue and prevents you from creating a pipeline without supplying a dummy material which you then need to swap out once the pipeline is created. It would be great if anyone felt able to get #3886 merged in?

**Comment by arvindsv** [comment]
@mrmanc As a part of #7920, the behaviour shown in https://github.com/gocd/gocd/pull/7920#issuecomment-608255470 will be available in the new pipeline wizard as well (@kritika-singh3 tells me). So, it will be consistent across the new and edit pipeline pages.

Note that it won't allow you to _create_ this material during the pipeline creation (or during pipeline edit). The [new pluggable SCMs page](https://github.com/gocd/gocd/pull/7919) coming in 20.3.0 will be the place to manage all of them and see where they are used, etc.

**Comment by arvindsv** [comment]
@mrmanc Suggesting https://github.com/gocd/gocd/pull/7920#issuecomment-611368205 to see if we can make the process a little easier.

**Comment by mrmanc** [comment]
@arvindsv thanks… I spotted that PR eventually and looks like it will solve this problem. 👍

**Comment by arvindsv** [comment]
Closing this as https://github.com/gocd/gocd/pull/7920 is done.
