### ISSUE TITLE
Restructure/reorganize CSS files into SCSS

### ISSUE THREAD

**Issue by ermauliks** [gocd/gocd#295]
Hello,

IMO, Go needs of it style department to be reorganized, I felt its extremely cluttered at the moment, and many parts of it are not required anymore. Moreover, CSS files are lying in multiple folders. In addition to this, we can also take benefit of SCSS for reusability, ease of coding. 

Incase of restructure, many ways are possible, following is the file/directory structure I prefer for organizing front-end style (you can see the same under [sass](https://github.com/gocd/gocd/tree/master/server/webapp/sass) directory in codebase). 

Share your thoughts, ideas. 

```
base
  |--mixins.sass
  |--reset-g9.sass
  |--sprites.scss
  |--variables.scss
components
  |--alerts.scss
  |--labels-badges.scss
  |--messages.sass
  |--navbar.scss
  |--pagination.scss
  |--treenav.sass
  |--wizard.sass
gadgets
  |--breadcrumb.scss
  |--button-groups.scss
  |--docked-toolbar.scss
  |--dropdowns.scss
  |--forms.scss
  |--layouts.sass
  |--modals.scss
  |--popovers.scss
  |--progress-bars.scss
  |--scaffolding.scss
  |--tabs.sass
  |--tooltip.scss
global
  |--layout.scss
  |--reset.scss
  |--responsive.scss
  |--typography.scss
go-pages
  admin
      |--template.sass        
  |--agent.scss
  |--admin.scss
  |--admin/templates.scss
  |--vsm.scss
  |--history-panel.scss
  |--pipeline.scss
```

Thanks.

**Comment by arvindsv** [comment]
Needs smaller issues, if we're doing this.
