### ISSUE TITLE
Check Repository Connection Internal API

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2953]
##### Issue Type

- Feature proposal

##### Summary

Request: POST
Headers: 

1.  ```Accept: application/vnd.go,cd.v1+json```

2. ```Content-Type: application/json```

URL:```https://ci.example.com/go/api/admin/internal/repository_check_connection```

Data
```
{
  "plugin": "deb",
  "configuration": [
    {
      "key": "REPO_URL",
      "value": "http://repo"
    }
  ]
}
``` 

Response
```
{
  "message": "Connection OK."
}
```

**Comment by rajiesh** [comment]
verified on 17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69), working as expected
