### ISSUE TITLE
Authorization Plugin Endpoint

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#2956]
##### Issue Type

- Feature proposal

##### Summary

Here's a proposal to move the current LDAP and Password file auth into a file

LDAP and password is currently configured as follows —

```xml
<security>
  <ldap uri="ldap://ldap.example.com" managerDn="cn=Bob,ou=Users,dc=example,dc=com" password="s3cr3t" searchFilter="(sAMAccountName={0})">
    <bases>
      <base value="ou=skunkworks,dc=example,dc=com" />
      <base value="ou=area51,dc=example,dc=com" />
    </bases>
  </ldap>
  <passwordFile path="/etc/go/password.properties" />

  <roles>
    <role name="SpaceTiger">
      <user>bob</user>
      <user>alice</user>
    </role>
  </roles>
</security>


<pipeline>
  <authorization>
    <admins>
      <role>SpaceTiger</role>
    </admins>
  </authorization>
</pipeline>
```

This configuration will now become (along with a hypothetical github authorization plugin) —

```xml
<security>

  <authConfigs>
    <!-- The password file configuration -->
    <authConfig pluginId="cd.go.authorization.passwordFile" id="password">
      <property>
        <key>hashType</key>
        <value>md5|bcrypt|sha1</value>
      </property>
    </authConfig>

    <!-- The github configuration -->
    <authConfig pluginId="cd.go.authorization.github" id="github">
      <property>
        <key>apiKey</key>
        <value>....</value>
      </property>
    </authConfig>

    <!-- The ldap server and base configuration -->
    <authConfig pluginId="cd.go.authorization.ldap" id="ldap">
      <property>
        <key>uri</key>
        <value>ldap://ldap.example.com</value>
      </property>
      <property>
        <key>managerDn</key>
        <value>...</value>
      </property>
      <property>
        <key>bases</key>
        <value>
          ou=skunkworks,dc=example,dc=com
          ou=area51,dc=example,dc=com
        </value>
      </property>
    </authConfig>
  </authConfigs>

  <roles>
    <role name="blackbird" authConfigId="ldap">
      <property>
        <key>group</key>
        <value>ou=blackbird,ou=area51,dc=example,dc=com</value>
      </property>
    </role>

    <role name="oss" authConfigId="github">
      <property>
        <key>organization</key>
        <value>gocd</value>
      </property>
      <property>
        <key>team</key>
        <value>Committers,Owners</value>
      </property>
    </role>

    <role name="fallback" authConfigId="password">
      <property>
        <key>path</key>
        <value>/etc/go/password.properties</value>
      </property>
    </role>
    
    <role name="apiOnlyUsers" authConfigId="password">
      <property>
        <key>path</key>
        <value>/etc/go/apiUsers.properties</value>
      </property>
    </role>
  </roles>
</security>

<pipeline>
  <authorization>
    <admins>
      <role>SpaceTiger</role>
      <role>oss</role>
    </admins>
  </authorization>
</pipeline>
```

**Comment by bdpiparva** [comment]
Todo list —

- [ ] Plugin infrastructure, registries, metadata-stores, etc
- [ ] acegi changes to perform authentication, and apply right acegi roles, in addition to right gocd roles
- [ ] config change listener to clear out users in `PluginRoleConfig` belonging to a plugin if the `<pluginRole/>` or `<authConfig/>` element changes
- [ ] if any other parts of the config changes, we'd need to ensure that we do a "shallow copy" of the `PluginRoleConfig` instances from a previous copy

**Comment by bdpiparva** [comment]
@arvindsv @jyotisingh — regarding deleting of `<role/>` defined in the `<security/>` tag — we don't see a precedent here (this "feature" to delete admins simply does not exist).

We're tempted to simply remove all references to the role being deleted (stage approvals, pipeline groups, templates, server admins, etc). Reason being —

* it'll be too cumbersome to remove references from each resource that uses the role being removed
* removal of roles does not stop or prevent the "core-functionality" (to continue to build pipelines)

WDYT?

**Comment by bdpiparva** [comment]
Additionally — [this implementation](https://github.com/gocd/gocd/blob/fb24522bfd13b2ede736f98b7a7b7fce52563ea1/config/config-api/src/com/thoughtworks/go/config/BasicCruiseConfig.java#L666-L675) seems broken (and unused) since it does not deal with template authorization.

**Comment by arvindsv** [comment]
> WDYT?

I need more context about this. Let's talk later.

From what I understand, what you're proposing means that it'll change the meaning of existing configs. We can't do that, cumbersome or not. But, as I said, I don't have full context. Let's talk later.

**Comment by arvindsv** [comment]
Also, why do we need pluginId again in `</role>`? What if there's a mismatch? What does it mean?

**Comment by ketan** [comment]
> Also, why do we need pluginId again in </role>? What if there's a mismatch? What does it mean?

We don't need it — it was an oversight, me and Bhupendra talked about removing it yesterday.

**Comment by arvindsv** [comment]
This was something I brought up recently, with you. Consider this (in the old style):

```
<role name="SpaceTiger">
  <user>bob</user>
  <user>alice</user>
</role>
```

Assume that bob is defined in AD and alice in the password file.

What is the equivalent in the new style of config? I mean, what will be migrate such a config to? I understand that we can now have multiple password files, etc. But, this is a role with users coming from two different providers (or `authConfig`s).

**Comment by maheshp** [comment]
- All authentication and authorisation will be eventually moved to plugins
- Go Server can be configured to have multiple Authorisation plugins
- Authorisation plugins need to be configured in cruise-config.xml under ```<security/>```. In case of multiple plugins, the order of configuration in the config will be used to pick a plugin for authorisation.
- Deferring token based authentication for now
- Deprecate authentication plugin and move everything over to Authorisation plugins.

**Comment by jyotisingh** [comment]
Will be fixed as a part of https://github.com/gocd/gocd/issues/2324

**Comment by arvindsv** [comment]
Closing. This is done.
