### ISSUE TITLE
LDAP search timeout shouldn't be hard-coded

### ISSUE THREAD

**Issue by tpbrown** [gocd/gocd#2957]
##### Issue Type

- Bug Report
##### Summary

[LdapUserSearch is hard coding the LDAP search timelimit parameter](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/security/LdapUserSearch.java#L90) which prevents the administrator from tuning this parameter as appropriate for their environment.

I believe this is normally handled by the system property com.sun.jndi.ldap.read.timeout .

##### Steps to Reproduce

1. Find an LDAP server with over 100,000 entries with 'memberOf' overlay enabled
2. Add an LDAP filter in GoCD to use memberOf
3. wait 6 seconds

##### Expected Results
- Slow but working response

##### Actual Results
- Soft sobbing

##### Possible Fix
- Remove line 90 in above referenced file

##### Any other info
- I really do like you guys.  Ignore the snark.

**Comment by arvindsv** [comment]
:D

**Comment by arvindsv** [comment]
I guess it can be easily made an environment variable, instead of being hard-coded.

**Comment by bdpiparva** [comment]
Closing this in favor of  [Issue#2](https://github.com/gocd/gocd-ldap-authentication-plugin/issues/2).
