### ISSUE TITLE
Pipeline quick edit page: Look up(label/input mis-aligned)

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#2959]
##### Issue Type
- UI Issue

##### Summary

Pipeline quick edit page -> Task settings 
Look up(label/input mis-aligned)

<img width="1324" alt="screen shot 2016-12-08 at 11 25 45 am" src="https://cloud.githubusercontent.com/assets/7871209/20999528/1fe5ae3e-bd3b-11e6-83a3-badd832cc1df.png">

**Comment by naveenbhaskar** [comment]
fixed

**Comment by rajiesh** [comment]
verified on 17.1.0 (4495-d95a3882d7eadb84330b641744e9a937ef8ed834) and alignment is fine
