### ISSUE TITLE
Pipeline history page -> In search cross icon mis-aligned

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#2960]
##### Issue Type
- UI Issue

##### Summary

Pipeline history page -> In search cross icon mis-aligned

<img width="1431" alt="screen shot 2016-12-08 at 11 36 08 am" src="https://cloud.githubusercontent.com/assets/7871209/20999569/83a7db7c-bd3b-11e6-94b8-7b3deb7658b6.png">

**Comment by rajiesh** [comment]
@naveenbhaskar  On IE 11 browser I see the cross being duplicated like this

<img width="974" alt="screen shot 2017-01-16 at 6 19 47 pm" src="https://cloud.githubusercontent.com/assets/6533924/21983722/a636420e-dc18-11e6-8386-36d696e23f11.png">

**Comment by ankitsri11** [comment]
Still there on Go Version: 17.3.0 (4700-277f37e8b9775a203b73c2340f0cfb9e9f19c8be)

**Comment by ankitsri11** [comment]
@naveenbhaskar  Still there on Go Version: 17.4.0 (4892-ab17b819e73477a47401744fa64f64fda55c26e8)
