### ISSUE TITLE
Alignment of message after creating a pipeline

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#2964]
##### Issue Type

UI

##### Summary
Firefox 51 on Ubuntu

Create a new pipeline using the pipeline creation wizard.
Complete the steps. The creation screen ends up like this.

![pipelinewizardalignment](https://cloud.githubusercontent.com/assets/54427/21003012/f359611c-bd4e-11e6-8fde-23dce082e5ae.png)

**Comment by naveenbhaskar** [comment]
fixed

**Comment by rajiesh** [comment]
verified on 17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69), working as expected
