### ISSUE TITLE
New Theme: Issues in browser IE 11 and above

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#2966]
##### Issue Type

- Bug Report

##### Summary

These are open issues on GoCD pages with new theme on IE 11/edge browser which needs to be fixed(after 16.12 release)

###### Basic environment details

* Go Version: `16.12.0 (4339)`
* Browser vendor and version (if relevant): `Windows 10, IE 11 or Edge(issue applicable for both)`

##### Steps to Reproduce
* Login to GoCD server as any admin user and seelct the user options on the right side top corner and select the option - `Preferenes`. Below screen is shown, the header on the Notifications filter table can be properly sized

<img width="1044" alt="screen shot 2016-12-08 at 12 53 09 pm" src="https://cloud.githubusercontent.com/assets/6533924/21005145/a7bd948e-bd59-11e6-8161-f849f3e009b5.png">

* Select Admin -> Pipelines, Admin page tabs moves to another line. However this alignment of tabs is proper when select Admin -> Plugins tab. This is with the screen resolution of 1366 x 768

<img width="1039" alt="screen shot 2016-12-08 at 12 42 01 pm" src="https://cloud.githubusercontent.com/assets/6533924/21005214/e87463b8-bd59-11e6-9656-3cb097628853.png">

* On Environments page select Trigger with options button of any pipeline. The `Revision to Deploy` label and text box not aligned

<img width="592" alt="screen shot 2016-12-08 at 12 41 23 pm" src="https://cloud.githubusercontent.com/assets/6533924/21005279/2730a6f2-bd5a-11e6-8572-70f4abf36dcf.png">

* Agents SPA page header size hides the first agent on the list

<img width="1048" alt="screen shot 2016-12-08 at 12 40 52 pm" src="https://cloud.githubusercontent.com/assets/6533924/21005298/447cf1ca-bd5a-11e6-9616-0400252bd53a.png">

* On pipeline edit page(old page) on tasks page edit a custom command task. The Lookup Commands message is not properly aligned,

<img width="593" alt="screen shot 2016-12-07 at 4 15 43 pm" src="https://cloud.githubusercontent.com/assets/6533924/21005368/8ea04be4-bd5a-11e6-94ee-80508170b983.png">

**Comment by bormotov** [comment]
FireFox 50.0.2 win64, same issues at 
* Agents list
* Administration tab

**Comment by ankitsri11** [comment]
Go Version: 17.3.0 (4700-277f37e8b9775a203b73c2340f0cfb9e9f19c8be)
Verified on Chrome v56, IE edge, Firefox v52
