### ISSUE TITLE
Validation errors not aligned while creating a new pipeline

### ISSUE THREAD

**Issue by zabil** [gocd/gocd#2969]
Firefox 51 on Ubuntu 16.10

Create new pipeline group

![newpipelinegrouperror](https://cloud.githubusercontent.com/assets/54427/21006887/d4fc0eba-bd60-11e6-8a01-9aef0d1750cd.png)

Enter an invalid pipeline group name and the error message is displayed over the "Basic settings" header.

![newpipelineerroraftervalidation](https://cloud.githubusercontent.com/assets/54427/21006921/fd620440-bd60-11e6-9395-9fb9f3c3d651.png)

**Comment by naveenbhaskar** [comment]
done

**Comment by maheshp** [comment]
Change the top padding to 0 for error message
