### ISSUE TITLE
Job run details page is having padding issue

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#2972]
##### Issue Type
- UI/Ux

##### Summary
Job run details page is having padding issue

<img width="1440" alt="screen shot 2016-12-09 at 8 42 48 am" src="https://cloud.githubusercontent.com/assets/7871209/21036595/049dcf1e-bded-11e6-9447-5782a01033aa.png">

**Comment by naveenbhaskar** [comment]
fixed

**Comment by rajiesh** [comment]
verified on 17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69), working as expected
