### ISSUE TITLE
logs (go-server.log) written to the wrong directory

### ISSUE THREAD

**Issue by stackfull** [gocd/gocd#2982]
##### Issue Type
- Bug Report

##### Summary

Logs are being written to `/var/lib/go-server` instead of `/var/log/go-server` when installed via the deb file on ubuntu.

##### Environment

Ubuntu or docker image `gocd/gocd-server`
Version 16.11.0 (4185-e7acc53aac8bb5ad2a7f306ca8f3e752855d844b)

##### Steps to Reproduce

The best way to verify is to simply run the docker container: 
`docker run -d --name go-server -p 8153:8153 -p 8154:8154 -e MSG_TIME=0 gocd/gocd-server && docker logs -f go-server`

If you `docker logs -f go-server` it should complain about not finding the `go-server.log` file (because it is in the wrong place).

**Comment by jyotisingh** [comment]
`docker logs -f go-server` will tail all the logs from the container. Go-server logs seem to be at the right place. If you check `/var/log/go-server` the log files are indeed available there and not in `/var/lib/go-server`. Closing this issue, feel free to reopen if you think I misunderstood.

**Comment by stackfull** [comment]
I suspect I have docker permissions problems on the volumes then. Thanks for looking into it.
