### ISSUE TITLE
Template admin role validation and providing template admin authorization to users within a role. 

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#2989]
##### Issue Type

- Bug Report

##### Summary

```
<security>
      ...
      <roles>
        <role name="template-admin">
          <users>
            <user>jez</user>
          </users>
        </role>
      </roles>
...
  <templates>
    <pipeline name="template1">
      <authorization>
        <admins>
          <role>non-existent-role</role>
          <role>template-admin</role>
          <user>someUser</user>
        </admins>
      </authorization>
```
1. A non existent role configured at the template level is not validated.
2. When logged in as user ```jez```,   jez (who is a part of role ```template-admin```) is not a template admin.

###### Basic environment details

* Go Version: `16.12`

##### Steps to Reproduce

1. Setup configurations as shown above
2. Save the configuration 
3. Log in as user 'jez' (defined in the password properties file or LDAP)

##### Expected Results

1. Saving the configuration with non-existent-role should not be allowed.
2. User 'jez' should be a template admin 

##### Actual Results

1. Role configured for template admins should be validated.
2. Users with an existing role, which is configured to be template admin, should be giving the right permissions.

##### Possible Fix

1. For template level authorization, role should be validated. 
2. A role configured for template admin using a parameter should be ignored. (or not allowed)
3. A user configured for template admin using a parameter should be ignored. (or not allowed)
4. For existing configurations, since users within a role are not given the right authorization, having a role currently is meaningless. Specifying a non-existent role for a template admin in this case is a rare instance. Therefore, showing a validation error is better than having a config migration to remove such spurious entries.
5. Users within a role should be given the appropriate permission.

**Comment by rajiesh** [comment]
verified on 17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69), working as expected
