### ISSUE TITLE
Make 'material name' accessible through 'pipeline instance' api. 

### ISSUE THREAD

**Issue by tifigs** [gocd/gocd#2990]
##### Issue Type

- Feature enhancement

##### Summary

Make "material name" (dependency pipeline name) accessible through "pipeline instance" api. 

##### Details

Gocd has the nice habit to provide environment variables for all your dependencies named after the "material name". 
```
GO_DEPENDENCY_LABEL_BACKEND
GO_DEPENDENCY_LOCATOR_BACKEND
```
Thanks to this, you can create source-code-branches of whole pipeline hierarchies and you don't need to rename anything. So i can configure my pipelines `backend` and `backend.3.0.2` to both set the environment variable `GO_DEPENDENCY_LABEL_BACKEND` and not `GO_DEPENDENCY_LABEL_BACKEND_3_0_2`. 

Now the GoCD API does only provide the 'description', but not the 'name' of any matierals; 
https://api.go.cd/current/#get-pipeline-instance

So I propose to create a new version of the API which goes 

`$ curl 'http://ci.example.com/go/api/pipelines/PipelineName/instance/1'` 
```
[...]
        "material": {
          "description": "URL: https://github.com/gocd/gocd, Branch: master",
          "fingerprint": "61e2da369d0207a7ef61f326eed837f964471b35072340a03f8f55d993afe01d",
          "type": "Git",
          "name": "backend",
          "id": 4
        },
```
instead of 
```
[...]
        "material": {
          "description": "URL: https://github.com/gocd/gocd, Branch: master",
          "fingerprint": "61e2da369d0207a7ef61f326eed837f964471b35072340a03f8f55d993afe01d",
          "type": "Git",
          "id": 4
        },
```

Kind of related to #1907

cheers

**Comment by maheshp** [comment]
Changes done as part of - https://github.com/gocd/gocd/pull/7174
Needs additional changes to the API response which will be done in 19.12.0 as part of - https://github.com/gocd/gocd/issues/7360

**Comment by rajiesh** [comment]
Verified on 20.1.0 (11109-7a59f0f111d0d51960d0e3105d85d6e9585cb940)
