### ISSUE TITLE
4 pipeline width of new "home" page design leads to more scrolling

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2992]
##### Issue Type

- Feature enhancement

##### Summary

The new design looks really great, thanks for that. However we have lots of pipelines per pipeline group, which used to use full width, which had much better screen usage on big screens. Now only 4 columns are shown, which forces us to scroll much more to get to the pipeline groups we like to see.

Although the centered design looks cleaner for smaller pipeline groups it might make sense either to detect if there's groups with more pipelines and make it wider in that case or to make a much more condensed presentation of pipelines anyway, which can be shown in more detail by providing a "pipeline group" page that shows the current pipeline block.

###### Basic environment details

* Go Version: `16.12.0`

**Comment by naveenbhaskar** [comment]
@JorritSalverda , thank you for the feedback. we will look into this.

**Comment by naveenbhaskar** [comment]
Removed the center alignment for the homepage. Now it will take full page width

**Comment by maheshp** [comment]
Header needs to be alligned

**Comment by rajiesh** [comment]
Header alignment still not fixed moving to next release

**Comment by rajiesh** [comment]
verified on 17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45)
