### ISSUE TITLE
Search for build status on pipelines page

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#2993]
##### Issue Type

- Feature enhancement

##### Summary

The search box on the pipelines page allows you to quickly filter pipelines based on their name. It would be very useful to extend this with being able to search on build status: pending, building, failed, completed or something like that.

###### Basic environment details

* Go Version: `16.12.0`

**Comment by GaneshSPatil** [comment]
@JorritSalverda -- As of now it's not possible. Though, for getting failed or building pipelines a workaround would be to create a new personalized view with `failed` or `building` pipeline states.
