### ISSUE TITLE
Pipeline labels trimmed in history page

### ISSUE THREAD

**Issue by jaymed** [gocd/gocd#2996]
##### Issue Type
UI

##### Summary

Pipeline labels longer than 14 characters are trimmed unnecessarily. The label is on a separate line and a longer length should be supported. In our specific use-case, the truncation of long labels results in the removal of information that uniquely identifies a build.

![image](https://cloud.githubusercontent.com/assets/6611080/21111675/7d20eab8-c057-11e6-8b21-d35e52197e28.png)

**Comment by naveenbhaskar** [comment]
There is no enough space for the title to show in one line , if its big. I have increased the width of the column to accomadate bigger names.
![image](https://cloud.githubusercontent.com/assets/1627961/21172024/9cae928c-c1f5-11e6-8114-2c6c082080b8.png)

**Comment by arvindsv** [comment]
I think @jaymed is talking about this [line](https://github.com/gocd/gocd/blob/74fd806d1a8abbbd010949d4a7aee16ae950231e/server/webapp/WEB-INF/vm/pipeline/_pipeline_history_list_jstemplate.vm#L106) and the part which says: `pipeline.label.truncate(17)`. It causes the label - the part which is "1342", "1341", etc. in your image to be truncated when bigger than 17 characters.

**Comment by arvindsv** [comment]
Without it, it looks something like this (made-up-data):

![image](https://cloud.githubusercontent.com/assets/172235/21182392/df74bb2a-c1d0-11e6-9fa2-f0f7f1acd522.png)

**Comment by naveenbhaskar** [comment]
since I have increased the width, now it can hold more no of chars

![image](https://cloud.githubusercontent.com/assets/1627961/21378843/46f9adac-c76f-11e6-8294-5479a7245f97.png)

**Comment by naveenbhaskar** [comment]
Removed the center alignment for the homepage. Now it will take full page width

**Comment by maheshp** [comment]
Consider trimming the revision as earlier and change the width based on the label size
