### ISSUE TITLE
Use a template for both "on success" and "manual"

### ISSUE THREAD

**Issue by kmugrage** [gocd/gocd#3]
Currently a template controls whether the pipeline using it is automatic or manual. I think it would be better if you could use the same template in both ways.

For example, I have a process for installing my software and I want that process to be exactly the same in my staging environment as it is in my production environment. To help make sure it's the same, I'd like to use a Go template to manage the process. I want to only deploy to production when I say so, but have the staging deployments happen automatically.

**Comment by nbozic** [comment]
+1, have same problem, exactly as stated above, we have environment which should deploy manually and one that should deploy automatically, and pipelines are same

**Comment by christer79** [comment]
+1 Also has this issue. One use case is having a template for generic deployment using terraform. Sometimes I want to trigger on previous success and sometimes on timer. Now we need to have two templates with the same code for doing this.

**Comment by Vye** [comment]
I bumped into this as well. I had to make a separate "prod approval" pipeline with a dummy manual stage so I could reuse the template in dev,test, and prod but stop for approval only before prod.

**Comment by gibsonm** [comment]
+1  We could probably reduce the number of pipelines we have by about 150 if pipeline triggering was not solely configured on the template.
