### ISSUE TITLE
The green color(indicating stage/job is passed) is not consistent in the new theme

### ISSUE THREAD

**Issue by kashishm** [gocd/gocd#3001]
###### Basic environment details

* Go Version: `16.12.0 (4352-018c65856d46007240cc75577e9cc8535b44148d).`

##### Actual Results
<img width="865" alt="screen shot 2016-12-13 at 4 56 08 pm" src="https://cloud.githubusercontent.com/assets/5915802/21138843/fc8d2a1a-c155-11e6-99ba-89acb2c8c623.png">
<img width="714" alt="screen shot 2016-12-13 at 4 56 50 pm" src="https://cloud.githubusercontent.com/assets/5915802/21138844/fc8fe7be-c155-11e6-87b2-7e1cecf7d884.png">

##### Possible Fix
The green color(`#64dd17`) in the first image is too bright and I'd prefer the color(`#78C42D`) in the second image.

**Comment by arvindsv** [comment]
Assigning to @naveenbhaskar

**Comment by naveenbhaskar** [comment]
Have made it purposely bright. Will tone down the brightness  little bit.

**Comment by maheshp** [comment]
Green color on pipeline history page is different from the rest
