### ISSUE TITLE
Suggestion - Pipelines UI

### ISSUE THREAD

**Issue by rtaborda** [gocd/gocd#3005]
I know there has been some UI focus in the latest release, so I would just like to point out my biggest complaint with the UI since I started using GoCD. 
The UI block for each pipeline is just too big, if you have a project with a lot of pipelines (for example if you're working with microservices) you end up having dozens of pipelines and with the current UI in most screens you can only see 3 rows of them, which results in a huge scroll that is not user friendly at all imo (I do know you can Personalize to filter them out, but that still doesn't invalidate my point).

Couldn't these be reduced? Or maybe have a "compact view" option?
I've created a very simple mock with Paint just to illustrate what I mean.

Mock:
![image](https://cloud.githubusercontent.com/assets/12414897/21151279/cac292be-c159-11e6-8b24-bfcea645ef8f.png)

Currently:
![image](https://cloud.githubusercontent.com/assets/12414897/21151328/fc6817b2-c159-11e6-926b-bffbac65e057.png)

Thanks for your time

**Comment by arvindsv** [comment]
@naveenbhaskar will probably think about this. This release was a bit of a theme/UI refresh. I'd consider what you're saying as a part of the upcoming UX refresh (the difference is that the end-to-end usage is considered) and I think this feedback of yours is definitely an aspect that should be considered. My thought here is that there should be multiple views, not just these two.

**Comment by rtaborda** [comment]
> My thought here is that there should be multiple views, not just these two.

That would be even better. 
I'm definitely looking forward to see the improvements that will come with that UX refresh! :)
Thanks for the quick answer

**Comment by edoua** [comment]
Very glad to see the focus and change in the UI.

My team also identified the same annoyance described by @rtaborda as we have a great number of pipelines (micro servvices).

We use the following user style https://userstyles.org/styles/82927/thoughtworks-go-vertical-remix to make a usuable dashbaord out of Go. Could be used for inspiration.

Multiple views sounds great!

**Comment by arvindsv** [comment]
> Multiple views sounds great!

To me, as well. However, it is my opinion only. :) @naveenbhaskar with help from all of you will come up with ideas (after research) and he doesn't get influenced by me, unfortunately.

**Comment by naveenbhaskar** [comment]
@edoua  Liked the dashboard you guys are using. We have plans  for a new dashboard.

**Comment by naveenbhaskar** [comment]
@rtaborda @edoua ,
I would like to get in touch with you regarding UX refresh programe for GoCD app. Can you let me know how to contact you? My email is naveenb@thoughtworks.com

**Comment by arvindsv** [comment]
Closing. [This is](https://github.com/gocd/gocd/issues/3872#issuecomment-337530250) what the idea is, currently.
