### ISSUE TITLE
JIRA integration with Go

### ISSUE THREAD

**Issue by mtpcsam** [gocd/gocd#301]
Hi,

Is Atlassian JIRA integration with Go supported ?  If so, where I can get instructions on how to enable that ?

Thanks.

**Comment by betarelease** [comment]
page not found on the above linke @sriramnrn Can you please share the new link?

**Comment by sriramnrn** [comment]
https://www.go.cd/documentation/user/current/integration/go_integration.html

**Comment by arvindsv** [comment]
Closing: Seems like there's no contribution from anyone or interest to pick this up. Sorry.

**Comment by vaibhavparnalia** [comment]
We are interested to have a JIRA plugin integration with GoCD. We plan on moving about 20 developer teams to GoCD from Jenkins and manually configuring JIRA for each pipeline would be lot of work for us.

**Comment by arvindsv** [comment]
The [pipeline config API](https://github.com/gocd/gocd/issues/301#issuecomment-293704851) might be helpful in automating it.
