### ISSUE TITLE
Pipeline SPA Improvements

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#3010]
- [x] Change Save State of Pipeline Config Save Button to Default.
Issue:
1.Click save on pipeline config SPA (the save button will turn green). 
2.Change the PipelineConfig to some invalid config (For Example: Duplicate Environment Variables);
3.Click Save.(The SPA shows Errors, but the Save button is still Green)

- [x] Alignment of Remove Button (Remove Stage, Remove Job)
- [x]  Alignment of Tooltip Question Mark On Tabs Page

**Comment by maheshp** [comment]
@GaneshSPatil can you also look at fixing the alignment for secure environment variables

![screen shot 2016-12-16 at 10 35 21](https://cloud.githubusercontent.com/assets/1061051/21252271/85d9d710-c37b-11e6-99ae-89d5838ddf46.png)

**Comment by GaneshSPatil** [comment]
`Alignment of Tooltip Question Mark On Tabs Page`
and https://github.com/gocd/gocd/issues/3010#issuecomment-267518036
has been fixed by https://github.com/gocd/gocd/commit/e85f1bdf0fa16b35806ad6849e0ac7203a8a3c29 and
https://github.com/gocd/gocd/commit/07aae9772ddd78923b05834dfd097d9e876c63a1
