### ISSUE TITLE
Config Save error messages broken

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3012]
##### Issue Type

- Bug Report

![screen shot 2016-12-15 at 16 11 28](https://cloud.githubusercontent.com/assets/1061051/21220946/717b09fa-c2e1-11e6-858d-3163cd321d21.png)

**Comment by naveenbhaskar** [comment]
fixed

**Comment by maheshp** [comment]
@naveenbhaskar the success and warning messages are coming in different locations, this needs to be fixed

**Comment by ankitsri11** [comment]
Go Version: 17.3.0 (4700-277f37e8b9775a203b73c2340f0cfb9e9f19c8be)
Verified on Chrome v56, IE edge, Firefox v52
