### ISSUE TITLE
Cannot click on running/cancelled stage in VSM

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#3036]
##### Issue Type

- Bug Report

Since 16.12 (I think), you can not click on a running/cancelled stage bar in VSM. Sometimes, you can only click at the bottom of the stage bar, to take you to a stage. Most times you can't click at all.

##### Summary

See this:

![can-only-click-at-some-parts-of-vsm](https://cloud.githubusercontent.com/assets/172235/21454107/badf9f18-c8e3-11e6-91b0-aca9cb1229a4.gif)

You can't click on the whole yellow bar.

###### Basic environment details

* Go Version: 17.1.0-4396
* Browser vendor and version (if relevant): Chrome 55.0.2883, Firefox 50, Safari 10.0.1

##### Steps to Reproduce

See: https://build.go.cd/go/pipelines/value_stream_map/performance-benchmark/133
Username: view
Password: password

**Comment by arvindsv** [comment]
Assigned to you, @naveenbhaskar.

**Comment by ketan** [comment]
There's an element on top of the progress bar that's preventing the click. Clicking a few pixels below the progress bar seems to do the trick (most of the times).

**Comment by arvindsv** [comment]
Yes, I made a little gif for that too first. Then, saw that on cancelled stages, you can't click at all. So, picked that. Either way, it's wrong and needs to be fixed (even if we can click below the bar).
