### ISSUE TITLE
Git commit emails appear escaped (sometimes)

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#304]
Our environment (from the /go/about) page:

```
Go Server Version:	14.1.0(18882-d0272e1d227b5e)
JVM version:	1.8.0_05
OS Information:	Linux 2.6.32-042stab090.3
Usable space in artifacts repository:	11149 Mb
Database schema version:	1401001
```

I'm looking at the compare pipelines feature and on the pipelines page, some emails appear html escaped, others render fine –

I'm attaching screenshots and the relevant output of git log if it helps. Happy to provide more information (or access to our server - it's public) if it helps (emails obsfusated)

```
% git show 6790f42de296e8298ca075e1853107e04d345317
commit 6790f42de296e8298ca075e1853107e04d345317
Author: Marco Valtas <mavcunha@xxx>
Date:   Mon Jun 30 10:54:48 2014 -0300

    Do not output things when building on Snap
```

```
% git log c9d696b0e17d9ba3e344ac15bc923a1cf65faeb3..3fddfaab690781159a85f7fa6b76165459d3a618
commit 3fddfaab690781159a85f7fa6b76165459d3a618
Author: Rafael Garcia <rafbgarcia@xxx>
Date:   Mon Jun 30 17:53:37 2014 -0300

    Adds tabindex to the command input so pressing tab goes to the next input instead of the actions

commit b7421b4923d03c1282e2da2114184e2ceb49fad3
Author: Rafael Garcia <rafbgarcia@xxx>
Date:   Mon Jun 30 17:41:59 2014 -0300

    Adds a regular task and subscribe when unpin

commit 1872e8120810025928c8fb2876ea01a24d70ee3d
Author: Rafael Garcia <rafbgarcia@gmail.com>
Date:   Mon Jun 30 17:36:00 2014 -0300

    removes note margin

commit 7da09a8d51411c60b48b8a6c0efed672ac78518f
Author: Rafael Garcia <rafbgarcia@xxx>
Date:   Mon Jun 30 17:30:02 2014 -0300

    Doesn't subscribe setup tasks
```

![screen shot 2014-07-01 at 7 44 25 am](https://cloud.githubusercontent.com/assets/10598/3441995/13f29426-010d-11e4-8965-9a40e4c4f57e.png)
![screen shot 2014-07-01 at 7 46 27 am](https://cloud.githubusercontent.com/assets/10598/3441996/13f3ce7c-010d-11e4-8255-a06ae9020ab7.png)

**Comment by arvindsv** [comment]
@rajiesh, @zabil: After some of the recent security changes, I wonder what the state of this is. Only in case you have some time.

**Comment by zabil** [comment]
We've fixed this on all the pages. Will open another one if we find something new.
