### ISSUE TITLE
go.cd name resolution issues

### ISSUE THREAD

**Issue by bwarminski** [gocd/gocd#3040]
##### Issue Type

Bug report

##### Summary

Hard to tell where to report this, so please point me in the right direction. Most major providers are no longer resolving the go.cd domain, which means that most automation that uses download.go.cd to download binaries no longer work. 

##### Environment

Everywhere.

###### Basic environment details

curl

##### Steps to Reproduce

Go here https://www.whatsmydns.net/#A/download.go.cd

##### Expected Results
The DNS resolves to an IP address

##### Actual Results
It doesn't resolve

##### Possible Fix
Renew subscriptions for the domain and/or don't depend on a Democratic Republic of Congo root.

**Comment by varshavaradarajan** [comment]
Hi @bwarminski , the DNS registrar mistakenly marked ```go.cd``` as  "expired". You can follow the progress on the issue here - https://groups.google.com/forum/#!topic/go-cd/ssWT_krsLdM/discussion

I will be closing this issue now.
