### ISSUE TITLE
Provide access to Pipeline Admin from value stream view

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#305]
We need easy access to the Pipeline Admin from the Value stream view as per the following image.

![image](https://cloud.githubusercontent.com/assets/7325010/3455651/305b591c-01e5-11e4-8ed3-b5e6da3ff0bf.png)

It would also be useful to add this to stage/job view

**Comment by virtuald** [comment]
+1

**Comment by arvindsv** [comment]
Don't remember when, but this has been available for a while. Closing.
