### ISSUE TITLE
Report broken links on GoCD websites here

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#3052]
Any broken links you see, or links which go to go.cd instead of gocd.io are fair game.

**Comment by natvincent** [comment]
On https://gocd.io/help/, the "installation" link still links to https://docs.go.cd/current/installation/

**Comment by arvindsv** [comment]
@natvincent Thanks! Fixing it.

**Comment by ketan** [comment]
Here's the script I'm using —

```ruby
task :default do
  all_repos = %w(go.cd www.go.cd docs.go.cd developer.go.cd api.go.cd plugin-api.go.cd).reverse
  sed_replace_expressions = all_repos.collect do |old_repo|
    new_repo = old_repo.gsub(/go\.cd$/, 'gocd.io')
    ["-e 's@http://#{old_repo}@https://#{new_repo}@Ig'"]
  end

  all_repos.each do |repo|
    next if repo == 'go.cd'
    cd "/Users/ketanpadegaonkar/projects/gocd/#{repo}" do
      sh("git fetch upstream --prune")
      sh("git checkout master")
      sh("git checkout .")
      sh("git reset")
      sh("git merge upstream/master --ff-only")
      sh("git clean -fdx")
      all_branches = `git branch -a | grep remotes | cut -f3 -d/ | egrep '(release|master|gh-pages)' | sort | uniq`.lines.collect(&:strip)
      all_branches.each do |branch|
        sh("git branch -D replace-#{branch} || true")
        sh("git checkout upstream/#{branch} -b replace-#{branch}")
        sh(%Q{find ./ -type f ! -path .git -exec sed -i #{sed_replace_expressions.join(' ')} {} \\;})
        sh("(git commit -am 'Fix all URLs' && git push upstream replace-#{branch}:#{branch}) || true")
        sh("git branch -D replace-#{branch} || true")
      end
    end
  end
end
```

**Comment by natvincent** [comment]
Also, the 'GoCD is Open Source. Learn More' link at https://www.thoughtworks.com/go/ is wrong... Oh, and the link in Wikipedia ☺️

**Comment by ketan** [comment]
> Also, the 'GoCD is Open Source. Learn More' link at https://www.thoughtworks.com/go/ is wrong... Oh, and the link in Wikipedia ☺️

Fixed wikipedia and thoughtworks.com/go. Thank you very much reporting.

**Comment by anishvenkat** [comment]
This link: https://docs.go.cd/16.2.0/configuration/managing_pipelines.html breaks.

**Comment by ankitsri11** [comment]
Also, try now GoCD logo in the bottom of https://www.thoughtworks.com/products page.

**Comment by nyuday** [comment]
@ankitsri11 - Thanks! We fixed the references to go.cd on thoughtworks.com/products

**Comment by ketan** [comment]
Closing since there havent been any more reports.
