### ISSUE TITLE
Moving content over to gocd.io

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3053]
Here's the checklist for moving all websites over to gocd.io

- [x] Move over go.cd (and www.go.cd)
- [x] Move over docs.go.cd
- [x] Move over developer.go.cd
- [x] Move over api.go.cd
- [x] Move over plugin-api.go.cd
- [x] Move over microsite (commercial addons and documentation)

- [x] Tweak Snap pipelines for each of the above sites to push to S3. This is in addition to current behavior to push to `gh-pages` branch (for sake of keeping history)
  - [x] Push to gh-pages and S3 for www.go.cd 
  - [x] Push to gh-pages and S3 for api.go.cd 
  - [x] Push to gh-pages and S3 for docs.go.cd 
  - [x] Push to gh-pages and S3 for developer.go.cd 
  - [x] Push to gh-pages and S3 for plugin-api.go.cd 

- [x] Setup proper caching for CDNs

- [x] Setup CDN for downloads
- [x] Setup CDN for experimental downloads
- [x] Setup CDN for addons/experimental addons
- [x] Setup additional CDNs so that requests on `.cd` domains is redirected to `.io` domains.
- [x] Check that blog comments continue to work, after the move

Internal (and public facing servers)

- [x] build.go.cd

**Comment by timoa** [comment]
Hi Ketan!

Do you have the new alias for build.go.cd with the new domain name?

I use it for the demo on my CI Remote app (iOS & Android) and it doesn't work with the previous URL.

I can't do any update for now because the Apple Store reviews are closed this week but I need to prepare a new release ASAP with the new URL.

Thanks!

Damien

**Comment by ketan** [comment]
@timoa — We'll have build.gocd.io. But that's after we do the public facing websites first. Please bear with us for a few days 😭

**Comment by timoa** [comment]
No worries :)

I will add a notification system for the next CI Remote release, to give more information about new releases or outage.

New users always try the demo before putting their GO.CD credentials :(

Good luck with your registrar!

**Comment by ketan** [comment]
@timoa — build.gocd.io is the server now.

**Comment by timoa** [comment]
@ketan OK! I will update the URL and deploy a new release of CI Remote for that.
