### ISSUE TITLE
Add property validation on save of `Plugin Profile` from xml

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3056]
##### Issue Type

- Bug Report
- Feature enhancement

##### Summary

Add property validation on save of `Plugin Profile` (Elastic Profile, Authconfig Profile, Roles config) from cruise_config.xml.

If elastic plugin is not supporting property `foo`. I can still define it from xml(which is not validating properties with plugin). Which will cause issue later on while someones try to change it from SPA. 

Validation result from plugin in SPA:
```
{
  "errors": {
    "foo": [
      "Is an unknown property"
    ]
  },
  "key": "foo",
  "value": "bar"
}
```

**Comment by arvindsv** [comment]
When the XML is directly edited and saved (which is what I think you mean), won't *every* elastic profile need to be validated? That has some issues. Performance is a concern, for one. Also, it's possible that a plugin does not exist at all. That needs to be handled too. This is why it's not done for other types of plugin configuration. Is there any reason the SPA cannot handle it?

**Comment by bdpiparva** [comment]
We have added client side fix for this issue as @ketan suggested, so user  can still edit the `PluginProfile`.

According to fix SPA will submit only those properties which are part of `metadata` given by plugin.

**Comment by bdpiparva** [comment]
#3089
