### ISSUE TITLE
UI issues post fine tuning changes

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3062]
##### Issue Type

- Bug Report

##### Summary
Placeholder to log UI issues post the fine tuning changes

**Comment by maheshp** [comment]
![screen shot 2017-01-03 at 17 43 46](https://cloud.githubusercontent.com/assets/1061051/21607484/8231f7c2-d1dc-11e6-8b3d-18dd92308b6b.png)

**Comment by maheshp** [comment]
New agents page Sandbox column text is truncated.

![screen shot 2017-01-03 at 17 50 54](https://cloud.githubusercontent.com/assets/1061051/21607601/442d5538-d1dd-11e6-95c6-75bbf9b78c63.png)

**Comment by maheshp** [comment]
Tool tip icons are misaligned, this seems to be across multiple pages.
![screen shot 2017-01-03 at 17 53 08](https://cloud.githubusercontent.com/assets/1061051/21607643/98b5bd2a-d1dd-11e6-87e8-eec5be586963.png)

**Comment by rajiesh** [comment]
The `Add Pipeline Group` and `Add Template` links have moved to be a buttons, is this change intentional or accidental?

<img width="1401" alt="screen shot 2017-01-03 at 6 38 06 pm" src="https://cloud.githubusercontent.com/assets/6533924/21608754/67113f04-d1e4-11e6-9066-c50bf65b75ea.png">
<img width="1407" alt="screen shot 2017-01-03 at 6 38 22 pm" src="https://cloud.githubusercontent.com/assets/6533924/21608787/85dfb4c4-d1e4-11e6-88cd-f234a89cba05.png">

**Comment by naveenbhaskar** [comment]
@rajiesh ... yes its intentional, those are not supposed to be a link.

**Comment by varshavaradarajan** [comment]
@naveenbhaskar, Delete/Edit button not aligned with the input box

Pipeline Settings page: Environment variables tab - ```https://<go-server>/go/admin/pipelines/up42/environment_variables```

<img width="665" alt="screen shot 2017-01-09 at 2 24 38 pm" src="https://cloud.githubusercontent.com/assets/4715748/21761235/859aac2a-d677-11e6-970d-561ccac54117.png">

**Comment by rajiesh** [comment]
Remove button is missing on the pipeline group admin permissions page and template permissions page

Navigate to Admin -> Pipelines -> Click `Edit` on any pipeline group

<img width="1174" alt="screen shot 2017-01-13 at 2 24 58 pm" src="https://cloud.githubusercontent.com/assets/6533924/21923932/b6071740-d99c-11e6-90c2-bde009c5706c.png">


Navigate to Admin -> Templates -> Click `Permissions` on any existing template

<img width="1038" alt="screen shot 2017-01-13 at 11 57 05 am" src="https://cloud.githubusercontent.com/assets/6533924/21923953/d2e40a58-d99c-11e6-8bd2-ce8b7f23a236.png">

**Comment by rajiesh** [comment]
Console log when scroll to end of log misses the bottom padding which make the texts overlap with the footer

<img width="1109" alt="screen shot 2017-01-13 at 2 33 11 pm" src="https://cloud.githubusercontent.com/assets/6533924/21924033/429f7d28-d99d-11e6-9410-e6fd2ceb1f9c.png">

**Comment by rajiesh** [comment]
verified on 17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69), working fine
