### ISSUE TITLE
Provide system environment variables in /api/support

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3065]
##### Issue Type

- Feature proposal

##### Summary

The API support logs currently does not provide environment variables.

Although we do print environment variables in the server logs, they tend to get lost as part of the log rotation.

**Comment by rajiesh** [comment]
verified on 17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69) and environment variables available as part of /api/support
