### ISSUE TITLE
Uploading of artifacts should be allowed to fail without causing the job to fail

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#307]
We make use of pipeline templates which are very useful however on occasion it has been necessary for a particular pipeline to upload materials that other pipelines using the template do not.

An example is where a build stage may build 2 unit test projects on 1 pipeline but all others just have 1.  If we try to add the 2nd unit test project path as an artifact in the template then all other pipelines will report failure since this folder does not exists.

Rather than abandon the template and create a specific pipeline (when this is the only difference) it would be great if we could say that uploading the artifact can be allowed to fail without causing the job to fail.

A simple check box such as "Allow upload to fail" would suffice.

**Comment by arvindsv** [comment]
Closing as stale.
