### ISSUE TITLE
Provide local API for the agent

### ISSUE THREAD

**Issue by lenucksi** [gocd/gocd#3074]
##### Issue Type
- Feature proposal

##### Summary
To make usage with elastic agent deployments nicer I would like to be able to retrieve the current status of an agent via an API that is available on the machine the agents runs on. 
This would remove the need to ask the server for the agent's status when this knowledge is available locally and only needed locally.

Such an API would ideally allow the following:
 - Provide information similar to the agent object illustrated here: https://api.gocd.io/current/#the-agent-object
 - Provide measures to force an agent to stop taking new work or tell the server to retire it.

**Comment by moritzheiber** [comment]
A use-case for this would be environments where there are "native" ways for determining an instance's/service's "health" (akin to [AWS ASGs](http://docs.aws.amazon.com/autoscaling/latest/userguide/healthcheck.html), [Kubernetes liveness probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/)) but there is not way to reliably tell an agent's status from looking at the resources available on the host running the agent itself.

**Comment by ketan** [comment]
Would you like to provide examples of expected API responses (status+body) in various situations?

**Comment by moritzheiber** [comment]
I really like the way [Vault is handling health checks](https://www.vaultproject.io/api/system/health.html). Essentially, it would be a request to an endpoint exposed on the agent:

```
curl -X GET http://localhost:8155/health
```
with a few parameters perhaps:

- `notconnectedok`: Still return `200` if an agent is not connected to a server 
- `notactiveok`: Still return `200` when an agent is connected but inactive

but that would just be icing on the cake, honestly. For now, a simple endpoint telling me "I'm alive, connected to a server and ready to execute builds (i.e. "active"), would suffice.

**Comment by ketan** [comment]
> but that would just be icing on the cake, honestly. For now, a simple endpoint telling me "I'm alive, connected to a server and ready to execute builds (i.e. "active"), would suffice.

Are you sure that'll suffice?

On the server end, we publish multiple statues for the agent — Idle, Building, LostContact, Missing, Building, Unknown.

Most are self explanatory, but the `LostContact` and `Missing` are interesting in that `Missing` is when an agent first disconnects, if the agent stays `Missing` for about 5 minutes, we assume it to have `LostContact` this is to deal with situations like intermittent network outages, the server being unavailable for short intervals of time (restarts etc). Would you need something more detailed than a boolean indicating "active"?

**Comment by moritzheiber** [comment]
@ketan I think we are talking about two different perspectives.

For the server all of the states you mentioned are absolutely relevant. For the agent they are not. The agent wouldn't care if/how/when it lost contact with the server, it would all yield the same result ("agent inoperable"). However, the agent really cares about two states:

1. Am I connected to the server? ("Connected")
2. Am I, in theory, able to build stuff? ("Active")

Everything else would either be irrelevant ("LostContact", "Missing", "Building" etc.) because it's either covered by "Connected" or "Active" (e.g. when you're connected and active you're probably ready to build or even building right now).

**Comment by ketan** [comment]
@stono — may I ask for your opinion on this please?

**Comment by ketan** [comment]
See https://github.com/gocd/gocd/pull/3781

**Comment by Stono** [comment]
Hey, 
We currently run our GoCD agents health check by passing a username and password to the agents as a kubernetes secret, and then using that username and password to query the status of the agent from the GoCD master itself (by using the GUID of the agent):

```
#!/bin/bash
set -e
GUID_FILE=/godata/config/guid.txt
SECRET_MOUNT_DIR=/mounted/gocd-secret
GO_USERNAME=$(cat $SECRET_MOUNT_DIR/user)
GO_PASSWORD=$(cat $SECRET_MOUNT_DIR/pass)

if [ ! -f "$GUID_FILE" ]; then
  exit 1
fi
curl "http://gocd-master-internal:8153/go/api/agents/`cat $GUID_FILE`" -H 'Accept: application/vnd.go.cd.v4+json' -u "$GO_USERNAME:$GO_PASSWORD" | grep build_state | grep -v "unknown"
exit 0
```

If the curl returns "unknown" we know the agent isn't connected to the master (from the masters perspective) and we should `exit 1`, thus failing the health check.

**Comment by moritzheiber** [comment]
@ketan Brilliant, thanks!
