### ISSUE TITLE
Environment API should support patch for environment variables

### ISSUE THREAD

**Issue by mortenherman** [gocd/gocd#3080]
##### Issue Type

 Feature enhancement

##### Summary

When using the environment API of the go server, I noticed that if I want to create or change environment variables in an environment I can only use the put method on environments API. 
However this comes with the side effect, that to add environment variables I would also have to extract agents, pipelines and existing environment variables to patch the variables, and then "PUT" the entire environment specification to the GO server again.

the current PATCH /go/api/admin/environments/:environment_name does only support patching of pipelines and agents, and it would of great benefit to have support for patching environment variables as well.

##### Environment
GO Server 16.11

information on API can be found here:
https://api.gocd.io/current/#patch-an-environment

* Go Version: 16.11
* JAVA Version: 1.8.0_101
* OS:Windows Server 2012 R2 6.3

**Comment by ketan** [comment]
Hi — thank you for reporting this issue. This looks like a good candidate for outside contribution. The code change is fairly small and localized —

* The [controller](https://github.com/gocd/gocd/blob/76d576b9ce2b71854ea525eda76edf1268f9a293/server/webapp/WEB-INF/rails.new/app/controllers/api_v1/admin/environments_controller.rb#L47-L59)
* The [PatchEnvironmentCommand](https://github.com/gocd/gocd/blob/f8ab50a04773360edcdca09d01839aa1a02e16ff/server/src/com/thoughtworks/go/config/update/PatchEnvironmentCommand.java#L101-L115), which is [invoked here](https://github.com/gocd/gocd/blob/8952af2168feca77c1e2115d0300ae1e521fa5ff/server/src/com/thoughtworks/go/server/service/EnvironmentConfigService.java#L228-L228).

Would you be willing to submit a PR, the team is around to help you out with any questions that you might have.

**Comment by rajiesh** [comment]
Verified on GoCD version 17.3.0 (4701-42a55e643a6e6a39ca07ce6bc00df7b4be2a28df)
