### ISSUE TITLE
Templates API - Description of feature

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#3081]
There seems to be some confusion about some edge cases in the templates API. I'll write what I feel is the ideal API behavior and it can be critiqued / discussed here.

1. [Template administrators](https://docs.gocd.io/current/configuration/dev_authorization.html#specifying-permissions-for-templates) can be composed of users and/or roles.

2. Template administrators of a template should be able to GET, PUT and PATCH (?) an existing template by name.

3. *Any* pipeline group administrator should be able to POST (create) a new template, for which they automatically become template administrator.

4. Template API GET should provide a link to authorization (not embedded, but a sub-resource of the template). Template API PUT and PATCH should not allow those to be changed by a template administrator who is not a super-administrator.

5. Only super administrators should be able to GET, PUT, PATCH template authorization.

This allows any administrator of pipelines to create a template. It allows multiple administrators (pipeline group administrators) to collaborate and *use* a template. But, to add a second pipeline group administrator to a template created by one pipeline group administrator will involve a super administrator.

I feel this is a good balance between self-service templates and involving super administrators only in authorization related cases.

/cc @varshavaradarajan

**Comment by rajiesh** [comment]
@arvindsv isn't the template administrator permission one which a pipeline group admin should be granted by default. A pipeline administrator without template admin permissions and a template admin without pipeline admin permission is of less value.

IMO pipeline group admin should have permission to edit the templates in the group(irrespective of who created it) and an explicit authorization for templates can be avoided

**Comment by arvindsv** [comment]
> IMO pipeline group admin should have permission to edit the templates in the group(irrespective of who created it) and an explicit authorization for templates can be avoided

The problem is that templates are a global concept. They're not tied to a group. That's what point 3 looks to help with. It says that any pipeline group admin can create a template, and they will be granted admin permission on it.

Given that it is global, we can't get rid of explicit auth, because you might want to restrict certain templates to certain people.

Does that make sense?

**Comment by jyotisingh** [comment]
Would it make sense to allow a template admin to add more collaborators?

**Comment by arvindsv** [comment]
> Would it make sense to allow a template admin to add more collaborators?

It would make sense, to remove the super admin from the picture, essentially. But then, can those new collaborators add others? If so, everyone is a template admin. It's like the GRANT option in a relational DB. We don't have a "collaborator" as an option in auth currently (without GRANT, that is).

We could get very granular. But, it complicates things a bit. That's why I was thinking of super admin's only power is controlling the auth when multiple people want to collaborate on a template. Otherwise, a group admin can create a template and use it.

Ideally, it would be as you said. Differentiating between the two.

**Comment by varshavaradarajan** [comment]
### Authorization on the Existing UI:

INDEX (/go/admin/templates) : template admin (lists only the templates that the user is a template admin of), super admin
GET: template admin, super admin, **pipeline group admin** (implicitly granted)
PUT Stage configuration - template admin, super admin
POST, PUT template config (including auth) - super admin
DELETE: super admin

### Authorization for the APIs

INDEX: template admin (lists only the templates that the user is a template admin of), super admin
GET: template admin, super admin
POST: super admin
PUT stage config: template admin, super admin
PATCH authorization (to be implemented) : super admin
DELETE: super admin

Currently, the authorization on the template config allows for only admins.
```
<pipeline name="some_template">
  <authorization>
      <admins>
        <user>foo</user>
      </admins>
  </authorization>
```
And, all pipeline group admins are implicitly given access to view any template's configuration.

Questions for @arvindsv:
Do we allow the GET template API to be accessible by template admin, super admin and pipeline group admin?
OR 
Do we change the template authorization config to have view config? And to not break the existing behaviour on the UI, do we add all pipeline group admins to the view config? And for future, super admins should explicitly add users to the view config in template authorization?

**Comment by varshavaradarajan** [comment]
After discussion - 
1. We change the template authorization config to stop restricting view config. Don't know why the existing template auth config restricted view config. @jyotisingh , if you have any insights, please update the issue. Have an XSL migration to add all pipeline groups admins to the view config of template authorization to not break existing behaviour. From now on, users or roles need to be explicitly added to the template view config.

2. All template admins should be able to delete a template. We already perform checks to see if a template is not used by other pipelines before deleting it.

**Comment by varshavaradarajan** [comment]
@arvindsv, @jyotisingh, we discussed that template view users should be able to access the GET template API. The template index API response is a representation of template name and list of pipeline names of pipelines associated with the template. Should we allow template view users to access the template index?

**Comment by arvindsv** [comment]
My vote is "yes".

**Comment by jyotisingh** [comment]
yes

**Comment by maheshp** [comment]
Does that mean if a user is authorised to view one template gets to list all the templates through API?

**Comment by GaneshSPatil** [comment]
I think it should only list the templates for which the user is authorized,
Because, INDEX will return few templates which user can not GET, which seems wrong to me.

**Comment by varshavaradarajan** [comment]
@maheshp , no. It means that if a user has view access to certain templates, the API will list only the templates for which he has view access. So, its a filtered view. It currently does that for template admins.

But @arvindsv and @jyotisingh , if we allow the template index call, which lists all pipeline names to be accessible by template view users, then `/go/admin/templates` must also be made accessible to template view users. And, we only show on the dashboard the pipelines that a user can view. So, on the templates listing page, why should we show the pipeline names for a user that may not have view access to pipelines?

**Comment by varshavaradarajan** [comment]
Template Listing on `/go/admin/templates` and templates index call

- Super admins can see the list of pipeline names of all pipelines associated with the template.
- Currently, template admins can see the message `This template is used in (x) pipelines`. 
x = count of all pipelines associated with the template irrespective of authorization.

1. Should we allow template view users to access `/go/admin/templates` and give the message `This template is used in (x) pipelines`?

2. Should we change the index API to introduce a number_of_pipelines to give the same information for template admins and template view users? 

3. Suppose a template admin or a template view user has view access to a pipeline group, should we give a count of all the pipelines associated with the template and only list the pipeline names of pipelines the user has view access to?

**Comment by arvindsv** [comment]
@varshavaradarajan - One (last) update on this is probably needed. :)

**Comment by varshavaradarajan** [comment]
After discussion -

Current UI:
- Let `/go/admin/templates` be accessible by template view users.
- For template admins and template view users, instead of showing the message `This template is used by (x) pipelines`, show the pipeline names.
- If a template admin or a template view user is a pipeline group admin, enable the edit pipeline link for those specific pipelines.
- Disable all template related buttons for template view users.

API:
- Allow the template index call to be accessible by template view users. 
- Let the response be as it is right now all all users, that is, template name, list of pipeline names and links. Provide an additional attribute called `can_edit` on the pipelines, which indicates whether the user has permissions to edit the pipeline configuration. We'll have to introduce a new version for this.

**Comment by varshavaradarajan** [comment]
The pipeline creation wizard is can be accessed by super admins and pipeline group admins.
We decided to filter the template dropdown so that only templates that are viewable by group admins show up there.
 This takes care of the current UI. 
We need to take care of the following:
- API: When a user creates or updates a pipeline via API, we need to check whether the template associated with pipeline in request can be viewed by user.
- New UI: Will be based on the API.
- Full Config save `/go/admin/config_xml`: Can only be done by super admins and they can associate any pipeline with any template.
- Config Repo: Whoever has write access to the repo can associate a pipeline with any template. 
- Partial config save: `/go/admin/pipelines/snippet/:groupName`: Right now, a group admin can associate a pipeline with any template. 

Should we allow a group admin to associate with any template or make a check to restrict the association as well based on the `allGroupAdminsAreViewers` option?

**Comment by zerolaser** [comment]
I would like to suggest an improvement, if we create a new role like `Admin` which has lesser privileges than `system administrator`. Like the admin has full access to create/delete pipelines/templates. but has no access to add/delete users, modify config xml, package repositories/plugins and server configuration. These should be handled by only system administrators. Also a special pipeline group or environment which only system administrators should have control, which can be used for maintaining agents, running backups and others. 
better way of adding roles to the multiple pipeline groups is also required.

**Comment by varshavaradarajan** [comment]
> Template API GET should provide a link to authorization (not embedded, but a sub-resource of the template). Template API PUT and PATCH should not allow those to be changed by a template administrator who is not a super-administrator.

Endpoint - `/go/api/admin/authorization/templates/:template_name`
This endpoint will be a sort of flagship for authorization on other entities. 

GET, PUT - only template admins and super admins can get authorization on a template.
POST, DELETE - only superadmins can create or delete authorization on a template object. 
Response: 
```
"admin": {
    "users": ["foo", "bar"],
    "roles": ["role1", 'xyz']
},

view: {
    "users": ["view"],
    "roles": ["role4"] 
},
"allGroupAdminsAreViewers": true
```

@arvindsv - I know you had some opinions about the authorization doing much more than what it allows users to do right now. Will update those concerns once we discuss them.

**Comment by rajiesh** [comment]
Authorization API verified on 18.2.0 (6211-48d5a54cd6525e54b4692cb757a6ad9896e46392). Only Super admin can now GET and PUT template authorizations
