### ISSUE TITLE
svn: E175002: Unable to connect to a repository. from windows, CERT problem 

### ISSUE THREAD

**Issue by keszi** [gocd/gocd#3093]
##### Issue Type
- Bug Report

##### Summary

I have installed go-server and go-client on my windows machine. I try to add materials to a pipeline. I want to connect to an svn repository but, but when I check the connection I get the:
```svn: E175002: Unable to connect to a repository at URL: https.....
Server certificate verification failed: certificate issued for a different hostname, issuer is not trusted```

I know there was an issue: #303 but it didnt helped  me.  
I dont know exactly what svn client GOCD uses. Does it has its internal svn client? 
I have connected whit my slikSVN client and executed: svn list https..
but it did not resolved the issue.

please help me, how to resolve this.

##### Environment

server and agent on same windows 10 machine. 
remote svn: on linux

###### Basic environment details

<!--- We recommend providing the for us to reproduce the issue quicker -->

* Go Version: 16.12.0
* JAVA Version: 1.8.0_102
* OS: Windows 10 10.0
* Browser vendor and version (if relevant): chrome

**Comment by arvindsv** [comment]
@keszi GoCD does not use its own SVN client, but I think the difference between you checking using silkSVN and the GoCD server doing it is that the server usually runs as the local system administrator. If you go look at the service, you'll see that it doesn't run as you.

I've had success using [psexec](https://technet.microsoft.com/en-us/sysinternals/pxexec) from Microsoft SysInternals with the `-s` option to run `svn list`. That should allow you to accept the certificate and add it to the *local system administrator's* collection of SVN certificates. Maybe that'll help?

**Comment by keszi** [comment]
@arvindsv 
o well, I understand it now. And yes it helped, many thanks.
