### ISSUE TITLE
Cleanup config save old code

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3094]
Config Save Optimisation https://github.com/gocd/gocd/pull/2912 adds a new flow for config save, with this there is duplicate code to save config. 

With 17.1 users have an option to toggle between optimised flow or the old flow using the system environment ```optimize.full.config.save```. The reason to retain the old flow was to take feedback on the new changes for few releases and then cleanup the old code.

The cleanup should be done as part of 17.3 or 17.4 release unless we find any issues with the new changes.

**Comment by arvindsv** [comment]
I believe this is done. Closing.
