### ISSUE TITLE
Pipeline Quick Edit loading forever

### ISSUE THREAD

**Issue by markus2810** [gocd/gocd#3097]
##### Issue Type

- Bug Report

##### Summary

Click on quick edit of a pipeline. The editor will never load. Progress is shown forever.

###### Basic environment details

Server Info
Go Server Version:	16.12.0 (4352-018c65856d46007240cc75577e9cc8535b44148d)
JVM version:	1.8.0_111
OS Information:	Linux 3.10.0-327.36.2.el7.x86_64
Usable space in artifacts repository:	1.99 GB
Database schema version:	1610001
* Browser vendor and version (if relevant): `Firefox, Chrome and Edge`

##### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by maheshp** [comment]
@markus2810 do you see any errors in the browser console?

**Comment by markus2810** [comment]
I see the following error:
Failed to load resource: the server responded with a status of 401 (Unauthorized)
general:1 XMLHttpRequest cannot load http://192.168.178.221:8153/go/api/version_infos/stale. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://nefario.xeam-solutions.com' is therefore not allowed access. The response had HTTP status code 401.

I do not know why a request is send over IP and port. Server is running at http://nefario.xeam-solutions.com
Configuration:
![image](https://cloud.githubusercontent.com/assets/2051899/21978896/f1a53ff6-dbdc-11e6-8ed3-6fc2d5653209.png)

**Comment by ketan** [comment]
You probably have a mis-configured reverse proxy — see https://docs.gocd.io/current/installation/configure_proxy.html.

**Comment by ketan** [comment]
I'm going to close this issue out. However if you still see an issue, please let us know and we'll re-open this issue and figure out how to investigate further.
