### ISSUE TITLE
Missing parameter in dependent pipeline leads to unknown error in template configuration

### ISSUE THREAD

**Issue by lenucksi** [gocd/gocd#3103]
##### Issue Type
- Bug Report

##### Summary
I have pipelines **A, B** and **X** which depend on template **T**.
X defines parameter _foo_, A and B do not.
T uses foo in its resource section, it defines, "#{foo}, git" as required resources. (As described in  https://docs.gocd.io/current/configuration/admin_use_parameters_in_configuration.html
However, upon saving only a red bar appears with "Save failed, see errors below” appears on top with no errors shown below.
An attempt to save an explicitly wrong resource  such as  ‘#{foo$}’ gets the expected "Resource name ‘#{foo$}' is not valid. Valid names can contain valid parameter syntax or valid alphanumeric with hyphens,dots or pipes” below and the red bar above.

As suggested by @varshavaradarajan and @jyotisingh this appears to be due to the parameter not being present on A and B, i.e. not on all dependent pipelines. 
The actual is error thus occurs on a dependent pipeline and is not propagated to the template view.

This has also been discussed on Gitter here: https://gitter.im/gocd/gocd?at=587f82a861e516c157916bda

###### Basic environment details
* Go Version: 16.11
* JAVA Version: OpenJDK 7
* OS: Linux

##### Steps to Reproduce

Described above in summary

##### Expected Results
Pipelines (in the example A and B) which do not specify the parameter (in the example T) would have it defaulted to “blank"
There is a ticket suggesting this here: https://github.com/gocd/gocd/issues/829

##### Actual Results
See above

##### Code snippets/Screenshots
http://pasteboard.co/nBhf876Kq.png

**Comment by arvindsv** [comment]
Closing as fixed through https://github.com/gocd/gocd/pull/7688
