### ISSUE TITLE
Many pages not using full width

### ISSUE THREAD

**Issue by thomaslloyd** [gocd/gocd#3108]
##### Issue Type

- Bug Report

##### Summary

We have noticed that on many pages the css is only rendering a narrow, centre aligned viewport and not using the full screen. This is possibly related to the following issue: https://github.com/gocd/gocd/issues/2992

The following pages have this problem (and possibly others):

- Environment page (/go/environments/ENV_NAME/show)
- Agents page (/go/agents)
- Agent page (/go/agents/AGENT_ID/job_run_history)
- all admin pages (/go/admin/...)

###### Basic environment details

* Go Version: 17.1.0

##### Steps to Reproduce

1. Go on any of these pages listed above on a screen with resolution width greater than approximately 1600px.

##### Expected Results

Full width display of page.

##### Actual Results

Page width is very restricted.

##### Code snippets/Screenshots

![image](https://cloud.githubusercontent.com/assets/15194064/22148750/d2944c46-df07-11e6-8651-6467b6870d8f.png)

**Comment by maheshp** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/3186

**Comment by rajiesh** [comment]
verified on 17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45) and all pages width is 100% now

**Comment by thomaslloyd** [comment]
Thanks for the speedy fix guys, much appreciated!
