### ISSUE TITLE
Missing Validation Error on PATCH Environments API

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#3110]
##### Issue Type

- Bug Report

##### Summary

Environments PATCH API returns 200 (Success) while trying to remove Agents/Pipelines/Environment Variables which does not exists in Environment.

##### Expected Results
It should throw a Bad Request Error Message.

##### Actual Results
It completes with status 200.

**Comment by rajiesh** [comment]
Verified on GoCD version 17.3.0 (4701-42a55e643a6e6a39ca07ce6bc00df7b4be2a28df)
