### ISSUE TITLE
High CPU load w/ Chrome

### ISSUE THREAD

**Issue by zanseb** [gocd/gocd#3112]
##### Issue Type

- Bug Report

##### Summary

I have noticed a high CPU load when opening the WebUi with Chrome.
I was able to reduce the load by disabling the css animation.

###### Basic environment details

* Go Version: `17.1.0`
* JAVA Version: `1.8.0_102`
* OS: `Windows 8.1 6.3`
* Browser vendor and version (if relevant): `Google Chrome 55.0.2883.87 m (64-bit)`

##### Steps to Reproduce

1. Open `http://<go-server-host>/go/pipelines` with Chrome
2. Trigger a pipeline
3. Wait until the animation shows up

##### Expected Results

Slight or no CPU impact

##### Actual Results

High CPU load

##### Code snippets/Screenshots

![cpu_load](https://cloud.githubusercontent.com/assets/8336867/22199155/0400f6c2-e15a-11e6-9d61-8ea8abb1ed96.PNG)

**Comment by KlemensE** [comment]
I am having the same issue. 

When I disable the animation in the css class `.Building>span:after,.building-stage>span:after ` the issue resolves.

**Comment by zanseb** [comment]
I tried with `Microsoft Edge 38.14393.0.0` now. The CPU usage is slightly lower but still relatively high (15-20%).

**Comment by maheshp** [comment]
@zanseb I could see a spike in CPU between 16.11.0 and latest build. This is after the changes we have done to introduce the new theme for GoCD. 

Will talk to @naveenbhaskar and keep you posted.

**Comment by maheshp** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/3169 by turning off animation.

**Comment by rajiesh** [comment]
verified on 17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45). Pipeline building animation is off
