### ISSUE TITLE
Add support for managing email notification filters via API

### ISSUE THREAD

**Issue by mortenherman** [gocd/gocd#3118]
##### Issue Type
- Feature proposal
##### Summary

We have created some scripts in an organisation that keeps users from an active directory in sync with go user list and permissioning in our setup. 
I can see from the API that I can specify the email_me property on a user, that enables user to receive email notifications. For transparency reasons we would like to configure some default email filters for all users, so that they are notified when pipelines fail and are fixed again.

it would be really awesome if those filters that you can add from the user preference page can be set via the API, so that when creating suers through the API, we could also attach default mail filters.

##### Environment
N/A

###### Basic environment details
N/A
###### Additional Environment Details
N/A
##### Steps to Reproduce
N/A
##### Expected Results
When using the user API create and patch could support adding notification filters, or a new notification API could be created for manipulating user notification filters

##### Actual Results
N/A

##### Possible Fix
N/A
##### Log snippets
N/A
##### Code snippets/Screenshots
N/A
##### Any other info
N/A

**Comment by arvindsv** [comment]
This has been possible since 17.5.0: https://api.gocd.org/current/#notification-filters

Closing.
