### ISSUE TITLE
Go server linux installers should not automatically start the Go server service

### ISSUE THREAD

**Issue by vivekprahlad** [gocd/gocd#3119]
##### Issue Type
- Feature proposal
##### Summary

Currently, according to https://github.com/gocd/gocd/blob/master/installers/linux/shared/partials/_after_install_go-server.sh.erb, the Go server is automatically started once it is installed via linux installers. 

This is problematic in situations where Go server AMIs or Docker containers are built using the linux installers (automatically starting the server leads to non-deterministic builds, as the server takes a while to do so, and makes a number of changes to the file system as it boots), and this leaves the zip file based install as the only option.

IMHO, it is trivial to explicitly start the service. However, the opposite is not true: it is currently not possible to prevent the service from automatically starting. Interestingly, the go agent installer does not have this behaviour.

Other open source packages (for example, ElasticSearch) used to have this behaviour as well, but have since disabled it. Please see [this issue](https://github.com/elastic/elasticsearch/issues/3722) as an example.

**Comment by arvindsv** [comment]
I think @ketan had a thought similar to this. I remember talking about installation vs. upgrade.

**Comment by ketan** [comment]
@vivekprahlad — this has been discussed a number of times before. I will get back to you with something in a couple of days.

PS: Hi!

**Comment by ketan** [comment]
@vivekprahlad — could you take a look at https://github.com/gocd/gocd/pull/3133 and see if it's in line with what you expect?

**Comment by vivekprahlad** [comment]
@ketan - Thanks, looks good!

**Comment by rajiesh** [comment]
Verified on GoCD version 17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45). In debian and rpm based installers after fresh install the go-server and go-agent do not start automatically. In upgrade scenario the state of the service before upgrade is maintained
