### ISSUE TITLE
Resource and Environments on agents page selector dropdown are not sorted.

### ISSUE THREAD

**Issue by iamsumanth** [gocd/gocd#3134]
##### Summary
Resources and environments to select on agents page are not sorted in dropdown list.

##### Code snippets/Screenshots

<img width="1432" alt="resources_not_sorted" src="https://cloud.githubusercontent.com/assets/17640031/22415985/67e46240-e6f1-11e6-87fd-b49133c64a61.png">

**Comment by arvindsv** [comment]
They do seem to be sorted now. Closing this.
