### ISSUE TITLE
Support for java 9, 10 and beyond

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#3136]
Latest versions of Ubuntu comes bundled with java9 by default, moreover java9 will get tentatively released in July, so we should start working towards supporting java 9 for both server and agent.

**Comment by Webysther** [comment]
In Ubuntu 16.04 (wich is LTE) use OpenJDK 8, Java 9 maybe take some time to have wide support.

**Comment by ketan** [comment]
@Webysther — 

Ubuntu 16.10 (something that a lot of users use), seems to come with Java 9 in the default ubuntu repositories, and causes bad starting experience for lack of Java 9 support in GoCD.

This issue is about ensuring that users who install GoCD with Java 9 have a good experience.

**Comment by fireundubh** [comment]
Java 8 reached [end of life in September](http://www.oracle.com/technetwork/java/javase/eol-135779.html) and Oracle is now focused on Java 9.

Java 9 support would be appreciated.

**Comment by bdpiparva** [comment]
Quick update on progress towards JAVA 9-10

- Getting away from old spring acegi [PR#4611](https://github.com/gocd/gocd/pull/4611)
- Upgrade jetty to v9.4.9 [PR#4630](https://github.com/gocd/gocd/pull/4630)
- Upgrade to Rails 5 and JRuby 9k [PR#4012](https://github.com/gocd/gocd/pull/4012)
- Move to mybatis [PR#4731](https://github.com/gocd/gocd/pull/4731)
- Upgrade spring
  1. Upgrade to latest of 3.2.x [PR#4740](https://github.com/gocd/gocd/pull/4740)
  2. Upgrade spring to latest of 4.x.x and hibernate 4 [PR#4749](https://github.com/gocd/gocd/pull/4749)

**Comment by arvindsv** [comment]
Quick update on this: We are aware of the timelines around EOL/end of support of Java 8 and 9 (soon).

We had to do a big Rails upgrade while doing a JRuby upgrade to make sure it works with Java 9, 10 and beyond. We are currently monitoring the performance impact of these upgrades.

We are targeting support for newer versions of Java in GoCD release 18.9, in late September or early October. The pull request that will be merged is [#4987](https://github.com/gocd/gocd/pull/4987/commits). It's a big one and involves a lot of changes. So, we want to make sure that it is really good enough for production, while making sure that it continues to support Java 8, 9, 10 and soon 11.

**Comment by arvindsv** [comment]
For the record, #4987 is merged.

**Comment by adityasood** [comment]
GoCD with v18.10.0 now supports Java10 and 11.
