### ISSUE TITLE
Pipeline goes into non-playable mode

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3139]
Issue Type: Bug

Summary :
Pipeline goes into non-playable mode if you rename the pipeline (mostly to from uppercase to lower and vice versa) from config.xml while a pipeline is running.

Steps to reproduce:
1. Run a pipeline
2. While it is running go to config XML page and rename the pipeline

<img width="855" alt="pipeline" src="https://cloud.githubusercontent.com/assets/6838313/22453968/bed13d78-e7a8-11e6-8c07-5cdafb211eb3.png">

* Go Version: 17.2.0 (4536-583666e6545ee87d9e4d15360304cd90df668d18)
* JAVA Version: 1.8.0_111
* OS Name: Mac OS X
* OS Version: 10.11.6
* Browser vendor and version (if relevant): Chrome Version 55.0.2883.95 (64-bit)

Fix/Workaround:

Restart go server

**Comment by GaneshSPatil** [comment]
@ankitsri11 -- I was unable to reproduce this issue with the new dashboard. 
Can you verify if it is fixed as part of the new dashboard (introduced in GoCD v18.3.0)

**Comment by ankitsri11** [comment]
Not able to replicate on the latest version. Closing it out. 

Verified on GoCD Version: 19.2.0 (8559-38e68d0ca9dfce367dd1d9a380e824595cd87d34)
