### ISSUE TITLE
Pass/Fail a Stage as per my scripts output

### ISSUE THREAD

**Issue by Xhings** [gocd/gocd#3151]
##### Issue Type

- How To

##### Summary

I have a Groovy Script task which runs as part of a pipeline among other tasks. I want to fail/pass the entire pipeline as per the flag set in the script variable. How to do this? Any documentations?

**Comment by maheshp** [comment]
@Xhings do you mind asking this question on the GoCD [forum](https://groups.google.com/forum/#!forum/go-cd) please? We use issues mostly for tracking bugs, feature requests.
