### ISSUE TITLE
Ask for password on the pipeline console.

### ISSUE THREAD

**Issue by zerolaser** [gocd/gocd#3152]
Is there any way, the console on the go pipeline  will ask for users to enter the credentials to run the job?
we can use Secure variables but Most of our users have System administrative access and we do not want everybody who have this administrative access accidentally run certain pipelines ?

**Comment by maheshp** [comment]
@zerolaser do you mind asking this question on the GoCD [forum](https://groups.google.com/forum/#!forum/go-cd) please? We use issues mostly for tracking bugs, feature requests.
