### ISSUE TITLE
Authentification/Authorisation with HTTP

### ISSUE THREAD

**Issue by mat44444** [gocd/gocd#3154]
##### Issue Type

- Feature enhancement

##### Summary

We currently acces Go under a nginx reverse-proxy with an SSO(lemonldap-ng) who can handle (OnpenIdConnect/CAS/HttpHeader/SAML). Most of ours application could be secured under HTTP Header between ReverseProxy and WebServer...

##### Environment

Go version 16.11, under centos7 and WebPortal access under openresty(nginx)

###### Basic environment details

* Go Version: 16.11
* JAVA Version: 1.8.0_101
* OS: Linux 3.10.0-327.el7.x86_64
* Browser vendor and version (if relevant): Chrome
##### Steps to Reproduce

Add Authentification/Authorisation(Acces Group) that could be cutumize and retrieved by http header

##### Expected Results
Authentification/Authorisation handled by http_header

**Comment by maheshp** [comment]
Hello @mat44444, we are moving towards delegating authentication/authorization to plugins, with this in mind we have introduced the [authorization plugins endpoint](https://plugin-api.gocd.io/current/authorization/) which is in beta as of now. Few more details of the plugin can be found [here](https://github.com/gocd/gocd/issues/2956).

Briefly, the idea is to have plugins handle authentication/authorization with flexibility of using any identity service provider.

Do you think this plugin endpoint can be used/extended for your use case. Your comments/feedback would be appreciated.
 
With respect to your feature request, can you give some more details. What will be the http_headers passed from the proxy servers to GoCD server? Do you expect Go server to verify the headers passed against the LDAP server(something similar to oauth)?

**Comment by mat44444** [comment]
Details:

We use LemonLdap who drive acces below NGINX(Reverse Proxy). So the Authentification/Authorisation aprt is embeded in NGINx and a could simply past custum HEADER in HTTP TRAFFIC between NGINX and GO SERVER...

The DNS who refere Go server is setted over the NGINX, who relay to the GO server...

So when user attempt to connect to GO, the dns send him on NGINX, NGINX check the SSO token and send user to the authentification portal if the token is not define/expired. When the token is set, NGINX send user over the reverse-proxy to the GO serveur and adding cutomized http header like username, Name, email, Role ... Those Header could be completly cutomized....

This kind of setup could used by GLPI, GRAYLOG ect... because they are all under a reverse-proxy and communication between reverse-proxy and server on a isolated VLAN could be considered secure and non accessible to users.

**Comment by maheshp** [comment]
Thanks for the details @mat44444. With Authorization Plugins, the idea was plugins would talk to the SSO but your requirement seems a bit different.

Anyways this would be a use case to keep in mind while we work on the Authorization changes.
