### ISSUE TITLE
Anonymous access for GoCD

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#3155]
##### Issue Type

- Feature proposal

##### Summary

Admins should be able to enable anonymous access for GoCD.

More information to come (discussion below).

**Comment by varshavaradarajan** [comment]
@arvindsv , @ketan - is this for the guest login?

**Comment by arvindsv** [comment]
Yes, but without having to log in.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan @arvindsv -- now we have guest login plugin so can we close this issue marking as resolved?

**Comment by arvindsv** [comment]
@GaneshSPatil No. This is about enabling anonymous access by default. Without even having to click on a button (no login page by default).

I'm not sure whether the changes we've made around authorization endpoint makes this easier than before.
