### ISSUE TITLE
UI Misalignment across GoCD

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3156]
##### Issue Type

- Bug Report

##### Summary

Placeholder ticket to capture UI issues.

**Comment by maheshp** [comment]
![screen shot 2017-02-06 at 17 57 31](https://cloud.githubusercontent.com/assets/1061051/22647135/ccb9844e-ec95-11e6-89d4-7afdd64ddfc7.png)

On Stage details page

**Comment by maheshp** [comment]
![screen shot 2017-02-06 at 17 58 54](https://cloud.githubusercontent.com/assets/1061051/22647159/f50003ba-ec95-11e6-9464-b0ea419536ea.png)

Materials edit page

**Comment by maheshp** [comment]
![screen shot 2017-02-08 at 09 24 50](https://cloud.githubusercontent.com/assets/1061051/22722945/808c0aaa-ede0-11e6-824c-c61e23df27ab.png)

On quick edit page, configuring git material

**Comment by bdpiparva** [comment]
![screen shot 2017-02-10 at 10 41 00 am](https://cloud.githubusercontent.com/assets/7871209/22814923/88129b56-ef7d-11e6-8eaf-380778b6b850.png)

 on admin/pipelines/up42/stages/up42_stage/settings page

**Comment by rajiesh** [comment]
verified on GoCD version 17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45)
