### ISSUE TITLE
Unable to add existing PR material using plugin 

### ISSUE THREAD

**Issue by ghost** [gocd/gocd#3157]
##### Issue Type

- Bug Report

##### Summary

A user was not able to add a Github pull request material to a second pipeline. They see the error "can not save SCM. Duplicate SCM". 

The workaround is to use "quick edit" to add the PR material to an existing pipeline. "Quick edit" gives you the option to "Select existing SCM".

Screenshot of error message:
![screenshot](https://cloud.githubusercontent.com/assets/4401585/22669385/2c4254b2-ec79-11e6-8c8d-1fa7258797ad.png)

Attached my cruise-config.xml after getting it to work. See PRtest and PRtest2 pipelines.
[cruise-config.txt](https://github.com/gocd/gocd/files/756033/cruise-config.txt)

**Comment by arvindsv** [comment]
@iamsumanth Can you do a quick analysis of this issue and when it was introduced? Quick Edit works fine, but the old one doesn't. As far as I know, it used to work fine before.

**Comment by iamsumanth** [comment]
It was never a feature @arvindsv. Once we reference SCM material to both the pipelines it will allow us to edit the configuration in UI but referencing is always done through editing config xml. We introduced it as a feature with Quick Edit.

**Comment by arvindsv** [comment]
I see. Ok. @ErinJoan - If that's the case, since we're getting rid of the old config UI, I'll leave this issue open for now, just to show we know. Once the old UI is gone and quick edit is the default, this should be ok.

**Comment by maheshp** [comment]
These views have changed now. There is new SCM's page[https://<gocd_server_url>/go/admin/scms] to create Pluggable SCMs. Closing the issue.
