### ISSUE TITLE
Top row in the agent view was covered and the agent info cannot be seen

### ISSUE THREAD

**Issue by barrowkwan** [gocd/gocd#3163]
##### Issue Type
- Bug Report

##### Summary

Top row in the agent view was covered 

##### Environment

build.gocd.io

-->

###### Basic environment details

Mac OSX
Chrome

##### Steps to Reproduce

1.  Login to build.gocd.io and go to "Agents" view 

##### Code snippets/Screenshots

![screen shot 2017-02-09 at 1 25 13 pm](https://cloud.githubusercontent.com/assets/972191/22803948/d0fcff8a-eecb-11e6-8114-1c8fa63d9553.png)

**Comment by barrowkwan** [comment]
It looks like the problem is with the width of the Browser window

![screen shot 2017-02-09 at 1 58 12 pm](https://cloud.githubusercontent.com/assets/972191/22804872/e6f92b16-eecf-11e6-9b36-e4cf774b9e0b.png)

![screen shot 2017-02-09 at 1 58 27 pm](https://cloud.githubusercontent.com/assets/972191/22804876/ed326f6a-eecf-11e6-9989-725116fb3248.png)

**Comment by maheshp** [comment]
@barrowkwan this has been reported earlier https://github.com/gocd/gocd/issues/2961 and @naveenbhaskar is looking into it.

Will be closing issue for now, since its a duplicate

**Comment by naveenbhaskar** [comment]
The lowest resolution we are supporting is the mac air resolution which is 1388X768. This page works fine till that resolution and will break in lower resolutions.
