### ISSUE TITLE
Presentation mode

### ISSUE THREAD

**Issue by MarkTickner** [gocd/gocd#3170]
##### Issue Type

- Feature proposal

##### Summary

A presentation mode for displaying pipelines on large screens. Currently there is a lot of empty space on both sides, meaning multiple pipelines cannot be shown together.

**Comment by maheshp** [comment]
@MarkTickner which version of GoCD are you on? There were changes made in 17.1.0 to show the pipelines dashboard in full screen.

**Comment by MarkTickner** [comment]
Update today and that has fixed the problem, thanks
