### ISSUE TITLE
allow for multiple tracking tools

### ISSUE THREAD

**Issue by nathanhruby** [gocd/gocd#3172]
##### Issue Type

- Feature enhancement

##### Summary

Please allow for multiple custom tracking tools to be configured on a pipeline (Project Management -> Tracking Tool Integration)

My use-case is that we use GitHub who generates a issue for Pull Requests, as well as Jira for internal tickets.  It would be useful to be able to configure both so we could click on merges to look at the PR with code review, or the ticket to learn more about the context of the change.

##### Environment

N/A

###### Basic environment details

* Go Version: `17.1.0`
* JAVA Version: `1.8.0_111`
* OS: `CentOS 7`
* Browser vendor and version (if relevant): `Firefox 51`

##### Steps to Reproduce

1.  Try to config multiple custom tracking tools
2. 
3. 
4. 

##### Expected Results

You can do this

##### Actual Results

You can not do this

**Comment by lobsterdore** [comment]
I have a need for this well, we are trialing new PM tools, at the moment we can only link to our current one via GoCD.
