### ISSUE TITLE
Server installation failing on Ubuntu VM

### ISSUE THREAD

**Issue by arunvelsriram** [gocd/gocd#3173]
##### Issue Type

- Installation Issue

##### Summary

Installation on Ubuntu VM fails.

###### Basic environment details

* Go Version: `17.1.0`
* JAVA Version: `1.7.0_121`
* OS: `vagrant-ubuntu-trusty-64`

##### Steps to Reproduce

Install using `apt-get` or `dpkg`

##### Log snippets

```
[Tue Feb 14 02:55:12 UTC 2017] Starting Go Server with command: java -server -Djava.security.egd=file:/dev/./urandom -Xms512m -Xmx1024m -XX:PermSize=128m -XX:MaxMetaspaceSize=256m -Duser.language=en -Djruby.rack.request.size.threshold.bytes=30000000 -Duser.country=US -Dcruise.config.dir=/etc/go -Dcruise.config.file=/etc/go/cruise-config.xml -Dcruise.server.port=8153 -Dcruise.server.ssl.port=8154 -jar /usr/share/go-server/go.jar
[Tue Feb 14 02:55:12 UTC 2017] Starting Go Server in directory: /var/lib/go-server
Unrecognized VM option 'MaxMetaspaceSize=256m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by maheshp** [comment]
@arunvelsriram with GoCD 17.1.0 we have removed support for Java 7, the Go-server and agent would require Java 8 now. Can you upgrade to Java 8 and try installing.

I will be closing this ticket for now, if you face issues with installing with Java 8 you can reopen this ticket with relevant details.

**Comment by arunvelsriram** [comment]
Hi @maheshp

I have upgraded to Java 8. Now facing another issue during installation. Some output from installation are as follows:

```[Tue Feb 14 09:15:56 UTC 2017] using default settings from /etc/default/go-server
Error starting Go Server.
dpkg: error processing package go-server (--configure):
 subprocess installed post-installation script returned error exit status 255
Errors were encountered while processing:
 go-server
E: Sub-process /usr/bin/dpkg returned an error code (1)```
