### ISSUE TITLE
Add the possibility to retrieve template parameters through the template API

### ISSUE THREAD

**Issue by alethenorio** [gocd/gocd#3194]
##### Issue Type

- Feature proposal
- Feature enhancement

##### Summary

Currently, the only way to retrieve all parameters set in a template via the API (In the form of `#{...}`) is to perform a GET in the template and parse the answer for all #{..} or try to create a pipeline with it and see if it fails. It would be very useful to include the parameters required by a template in the template GET API (Or a separate API to ask specifically for the parameters)

**Comment by arvindsv** [comment]
Closing this based on https://github.com/gocd/gocd/pull/7670#issuecomment-597034987
