### ISSUE TITLE
Cannot enable LDAP authentication

### ISSUE THREAD

**Issue by tpbrown** [gocd/gocd#3197]
##### Issue Type

- Bug Report

##### Summary

Attempting to enable LDAP in 17.2.0 causes a fatal exception in Rails when using Chrome, and generates a different error in the UI if using Safari. LDAP auth does not enable in either.

##### Environment

Docker 1.13 using official GoCD server image. 

##### Steps to Reproduce

docker run --detach -p 8153:8153 gocd/gocd-server:17.2.0

In either browser navigate to http://localhost:8153/go/admin/config/server

Under LDAP settings enter a URI, search base, and search filter.  Mine were:
URI - ldaps://myldapserver.mycompany.com
base - cn=users,dc=mycompany,dc=com
filter - (uid={0})

Press CHECK LDAP button or press SAVE

##### Expected Results
LDAP connectivity is verified, or User is redirected to the auth page to login.

##### Actual Results
In Chrome no UI change occurs, but go-server.log emits:
```
LOG: 2017-02-22 20:59:58,990  WARN [qtp1104106489-26] Rails:? - Can't verify CSRF token authenticity
LOG: 2017-02-22 20:59:58,998 FATAL [qtp1104106489-26] Rails:? -
LOG: ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
LOG:   lib/jetty_weak_etag_middleware.rb:35:in `call'
LOG:   lib/catch_json_parse_errors.rb:8:in `call'
```

 In Safari no errors appear in the log, but the UI reports:
```
Cannot connect to ldap, please check the settings. Reason: simple bind failed: myldapserver.mycompany.com:636; nested exception is javax.naming.CommunicationException: simple bind failed: myldapserver.mycompany.com:636 [Root exception is javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty]
```

**Comment by bdpiparva** [comment]
Hello @tpbrown, The errors you are seeing in Safari, it looks like an issue where certificate is not properly configured. 

Add your ldap server certificate to java default truststore where your GoCD server is running.

**Comment by tpbrown** [comment]
@bdpiparva that's rather odd. Does the GoCD official image no longer contain the CAs?  (as in, i just docker run them; i'm not configuring a server)

Also note that Chrome/Safari are hitting the exact same GoCD server container...

**Comment by bdpiparva** [comment]
@tpbrown GoCD docker image is already having required CAs. 

Since you are using ldaps:// instead of ldap:// as your server url, that means the communication between Go server and the ` ldaps://myldapserver.mycompany.com` is through `SSL` and for that you have to import your Ldap server cert to truststore.

**Comment by arvindsv** [comment]
Closing this. Can reopen if it's not solved.
