### ISSUE TITLE
Failed to upload; Could not create temp folder

### ISSUE THREAD

**Issue by garthk** [gocd/gocd#3200]
##### Issue Type

- Bug Report

##### Summary

* Job tasks pass
* Artifact upload fails
* Job fails
* Job console indicates: `Failed to upload /var/lib/go-agent/pipelines/project/tarball.tgz`
* The file does exist: `-rw-r--r-- 1 go go 170965982 Feb 23 04:10 /var/lib/go-agent/pipelines/project/tarball.tgz`
* The agent's log file adds: `Could not create temp folder`
* It doesn't say which folder
* It doesn't say why
* `mktemp -d` does work

##### Environment

```
  "Go Server Information": {
    "Version": "17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69)"
  },
  "OS Information": {
    "OS Name": "Linux",
    "OS Version": "4.4.0-53-generic",
    "System Architecture": "amd64",
    "Available Processors": 23,
    "Average System Load": 0.49
  },
  "Runtime Information": {
    "Name": "28@8cc271e86d6e",
    "Uptime": 1399835725,
    "Uptime (in Time Format)": "[About 388 hours, 50 minutes, 35 seconds]",
    "Spec Name": "Java Virtual Machine Specification",
    "Spec Vendor": "Oracle Corporation",
    "Spec Version": "1.8",
```

##### Steps to Reproduce

Perform any build uploading results. I'm not especially sure when this broke, nor what had changed. GoCD isn't giving me much help.

##### Expected Results

* Upload the artifact, or
* Give me enough information to troubleshoot

##### Actual Results

* Didn't upload the artifact
* Told me it couldn't create a temporary directory
* Didn't tell me the directory's path, or what the error was

##### Possible Fix

* Tell me the directory's path
* Tell me the error message
* In general, don't wrap informative errors with less informative errors

##### Log snippets

`console.log`:

```
04:09:53.126 [go] Current job status: passed.

04:09:53.129 [go] Start to create properties project/6/archive/3/tar on 707e769b1d2e [/var/lib/go-agent]
04:09:53.129 [go] Start to upload project/6/archive/3/tar on 707e769b1d2e [/var/lib/go-agent]
04:09:53.131 [go] Failed to upload /var/lib/go-agent/pipelines/project/tarball.tgz
04:09:53.133 [go] Failed to upload /var/lib/go-agent/pipelines/project/tarball.tgz
04:09:53.134 [go] Failed to upload /var/lib/go-agent/pipelines/project/tarball.tgz
04:09:53.134 [go] Uploading finished. Failed to upload [tarball.tgz]
```

`go-agent.log`:
```
017-02-23 04:09:53,134 [loopThread] ERROR thoughtworks.go.publishers.GoArtifactsManipulator:111 - Failed to upload /var/lib/go-agent/pipelines/project/tarball.tgz
java.lang.RuntimeException: FileUtil#createTempFolder - Could not create temp folder
    at com.thoughtworks.go.util.FileUtil.createTempFolder(FileUtil.java:422)
    at com.thoughtworks.go.publishers.GoArtifactsManipulator.publish(GoArtifactsManipulator.java:79)
    at com.thoughtworks.go.work.DefaultGoPublisher.upload(DefaultGoPublisher.java:71)
```

**Comment by garthk** [comment]
Rebuilding my agent containers with `go-agent` 17.2.0 and `strace`…

**Comment by ketan** [comment]
Based on the stacktrace, and [this method](https://github.com/ketan/gocd/blob/7403f84b0d6bbc328ba59e71fb2e31d1467c016d/base/src/com/thoughtworks/go/util/FileUtil.java#L417-L425), it appears like the folder is created under the directory `data/cruise-RANDOM_UUID`. This is  and relative to the working directory of the agent. So `/var/lib/go-agent/data/cruise-RANDOM_UUID`

It looks like [this line](https://github.com/ketan/gocd/blob/7403f84b0d6bbc328ba59e71fb2e31d1467c016d/base/src/com/thoughtworks/go/util/FileUtil.java#L420) returns a false because the directory already exists and raises an incorrect exception. Could you confirm if that's the case?

**Comment by garthk** [comment]
There's no `data` directory. Surely it couldn't be _that_ simple. ツ

**Comment by garthk** [comment]
Yep. Ok, how do we ensure that's created?

**Comment by jyotisingh** [comment]
Wondering if the agent is running out of disk space or inodes. Could you try `touch /var/lib/go-agent/please_delete_me` and see if the file gets created?

**Comment by garthk** [comment]
Clarifying: after `mkdir -p /var/lib/go-agent/data ; chown -R go:go /var/lib/go-agent/data`, all of my jobs are able to create their `/var/lib/go-agent/data/cruise-$UUID` directories and successfully upload their artifacts.

I'm not out of disk space or inodes. Looks like the root cause was that `/var/lib/go-agent` is owned by `root`, which would explain why `go` couldn't create `/var/lib/go-agent/data`. It just took looking at the source to figure that out because of the way we wrapped the error.

**Comment by jyotisingh** [comment]
The installation/upgrade scripts ensure that /var/lib/go-agent is owned by 'go' user so thats unexpected unless that was manually changed by someone.
