### ISSUE TITLE
Login page error message is misaligned.

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3203]
##### Issue Type

- Bug Report

##### Summary

Authentication error message in login page is misaligned

![screen shot 2017-02-24 at 10 19 10 am](https://cloud.githubusercontent.com/assets/7871209/23291331/c817e7d2-fa7d-11e6-98a9-0ce875eb6283.png)
 

##### Environment

GoCD server 17.2

**Comment by ankitsri11** [comment]
Go Version: 17.3.0 (4700-277f37e8b9775a203b73c2340f0cfb9e9f19c8be)
Verified on Chrome v56, IE edge, Firefox v52
