### ISSUE TITLE
Notification to slack, gitter, flowdock, etc

### ISSUE THREAD

**Issue by ageekymonk** [gocd/gocd#3205]
##### Issue Type
- Feature proposal
##### Summary

Add support for sending notification via webhooks to slack, gitter, etc. 
Allow them to be configured per pipeline, pipeline group, Template level, environment. 
Allow users to configure their slack, gitter, id as user profile. 
Allow users to set notification filter to send notification to their custom slack, gitter id, etc per pipeline/pipelinegroup/environment

**Comment by arvindsv** [comment]
@ageekymonk: These will not be in GoCD core. There are notification plugins which do this ([here](https://www.gocd.io/plugins/)). Admittedly, they're not as flexible as you propose, right now. But, doing this in core and supporting multiple different clients is a losing proposition (there are always new ones). So, I'll close this. Thank you!
