### ISSUE TITLE
Add User modal works, but can't actually add a user.

### ISSUE THREAD

**Issue by spacepants** [gocd/gocd#321]
I've just installed Go and it's running behind Nginx. Most everything seems to be working fine, but when I attempt to create a user via the Add User modal, the POST request to `https://server.name/go/admin/users/create` is rejected with a 400 error.

**Comment by serret887** [comment]
I try to add an user to GOCD and I get the following error in my console 

Failed to load resource: http://localhost:8153/go/admin/users/create the server responded with a status of 400 (Bad Request)

I am using the GOCD 17.3

**Comment by hateonion** [comment]
Got the same issue 

GOCD 17.4

**Comment by luisribeiro** [comment]
Same here

GOCD 17.8.0

**Comment by arvindsv** [comment]
I tried this just now and it works. Are you all (@luisribeiro and @hateonion) seeing this on localhost only? And, using what kind of auth plugin? I mean, is it file based auth or ldap auth that you've set up?

**Comment by varshavaradarajan** [comment]
Can @hateonion or @luisribeiro  paste a log snippet that might be helpful in debugging this?
