### ISSUE TITLE
Server startup script uses deprecated JVM option

### ISSUE THREAD

**Issue by edysli** [gocd/gocd#3216]
##### Issue Type

- Bug Report

##### Summary

The server startup script uses deprecated JVM option `-XX:PermSize=128m`.

##### Environment

- go-server 17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45)
- OpenJDK 1.8.0_121
- Ubuntu 16.04

##### Steps to Reproduce

1. `unzip -e go-server-17.2.0-4587.zip`
2. `cd go-server-17.2.0`
3. `./server.sh`

##### Expected Results

The server starts without any warning or error.

##### Actual Results

The JVM emits a warning:

> OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0

##### Possible Fix

Since version 17 requires Java 8, you should make sure to not use options that were deprecated in Java 8... :wink:

**Comment by ketan** [comment]
This seems like a low hanging fruit for someone looking to contribute to GoCD. Would you be interested in submitting a PR? Should be as easy as searching the codebase and removing the argument.

**Comment by edysli** [comment]
`git grep PermSize` is easy enough. However, running your CLA by my legal team is going to take longer...

**Comment by rajiesh** [comment]
verified on GoCD version 17.3.0 (4700-277f37e8b9775a203b73c2340f0cfb9e9f19c8be)
