### ISSUE TITLE
Emoji in console output rendered as ‘?’

### ISSUE THREAD

**Issue by mrmanc** [gocd/gocd#3218]
##### Issue Type

- Bug Report

##### Summary

In the past we were able to see emoji output properly in our console log. At some point one of the upgrades broke this, and now emoji output renders as question marks.

###### Basic environment details

* Go Version: `16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d)`
* JAVA Version: `1.8.0_102`
* OS: `Linux 2.6.32-358.el6.x86_64`
* Browser vendor and version (if relevant): `Chrome  56.0.2924.87 (64-bit)`

##### Steps to Reproduce

Create a pipeline with a job which runs a command like this: `

```
<job name="test-output">
            <tasks>
              <exec command="/bin/echo">
                <arg>-e</arg>
                <arg>"😍"</arg>
                <runif status="passed" />
              </exec>
            </tasks>
            <resources>
              <resource>bash</resource>
            </resources>
          </job>
```

##### Expected Results
A 😍 should appear on the console out

##### Actual Results
This appears:

`20:47:04.061 "?"`

Inspecting the page and altering the character in the dom to the correct emoji works, so this is not a typeface issue.

##### Possible Fix
Using the wrong character encodings?

**Comment by arvindsv** [comment]
cc @marques-work and @ibnc - Thought this might interest you, since you're working on https://github.com/gocd/gocd/pull/3199.

**Comment by marques-work** [comment]
Definitely interesting - but I'll probably make it a separate PR as the code for #3199 is ready (IMO) for merge now.

**Comment by marques-work** [comment]
Definitely an encoding issue. I was able to reproduce this on MacOS X. This issue doesn't happen when logs are transmitted from agent -> server via WebSockets, which forces UTF-8, so the problem probably occurs in the RemoteAppender (or in its vicinity).

**Comment by ibnc** [comment]
@marques-work The websocket shouldn't be forcing UTC-8 encoding. It'll use whatever the system default is on that machine (which I assume is UTC-8 on your mac)

**Comment by marques-work** [comment]
Right - which is what I meant; MacOS X's default is UTF-8. Sorry that wasn't more clear. I've submitted #3241 so that RemoteConsoleAppender does the same thing.

**Comment by mrmanc** [comment]
Thanks for such a quick fix! 😍

**Comment by ankitsri11** [comment]
Go Version: 17.3.0 (4700-277f37e8b9775a203b73c2340f0cfb9e9f19c8be)
Verified on Chrome v56, IE edge, Firefox v52
