### ISSUE TITLE
Ansi bold in console output is not supported

### ISSUE THREAD

**Issue by mrmanc** [gocd/gocd#3219]
##### Issue Type

- Bug Report
- Feature enhancement

##### Summary

The console log output is parsed to convert ANSI colour codes into coloured text. It would be good to be able to also support bold text using `\e[1m`.

###### Basic environment details

* Go Version: `16.10.0 (4131-730ff1867576754414cc632957f344d0263bc06d)`
* JAVA Version: `1.8.0_102`
* OS: `Linux 2.6.32-358.el6.x86_64`
* Browser vendor and version (if relevant): `Chrome  56.0.2924.87 (64-bit)`

##### Steps to Reproduce

Create a pipeline with a job which runs a command like this: `

```xml
          <job name="test-output">
            <tasks>
              <exec command="/bin/echo">
                <arg>-e</arg>
                <arg>"\e[1mThis should be bold\033[0m and this should not be bold"</arg>
                <runif status="passed" />
              </exec>
            </tasks>
            <resources>
              <resource>bash</resource>
            </resources>
          </job>
```

##### Expected Results
The first part of the sentence should be rendered bold in the console output

##### Actual Results
The whole sentence looks the same and is not bold

##### Possible Fix
Only colour codes (foreground and background) are being intercepted at the moment?

**Comment by arvindsv** [comment]
cc @marques-work and @ibnc - Thought this might interest you, since you're working on https://github.com/gocd/gocd/pull/3199.

**Comment by marques-work** [comment]
I've included a fix for this in https://github.com/gocd/gocd/pull/3199 because it depends on the latest version of AnsiUp, which is part of that PR.

**Comment by mrmanc** [comment]
This is **awesome**. Thanks!

**Comment by marques-work** [comment]
Now that https://github.com/gocd/gocd/pull/3199 is merged, this should be fixed
