### ISSUE TITLE
Garbage collection for config.git should default to running automatically

### ISSUE THREAD

**Issue by tpbrown** [gocd/gocd#3220]
##### Issue Type

- Bug Report
- Feature enhancement

##### Summary

>

> So, GoCD has in-built garbage collection for this git repository and it can be configured to run on a periodic basis. However, since **_this activity can potentially take a long time_** to run when GC happens for the first time around, the feature is turned off by default. GoCD server periodically checks if the loose-object count exceeds a preset threshold and displays a warning message. This is a cue for **_users to enable periodic GC_** on their servers. Here are the steps you need to follow (and in this order) to enable periodic GC for the config repository:
> 
> **1. Stop the GoCD server**

^^^ Given that step 1 is a service interruption the current default isn't logical. If by default period GC is enabled then the _*potentially*_ long time is avoided as is the outage window to turn it on for the first time.

Flipping the default will indeed cause disruption but that is a one time disruption. Not doing so just means that more and more instances are deployed..  self-fulfilling prophecy and all that.

**Comment by jyotisingh** [comment]
@tpbrown - What if step 1 wasn't a service interruption, but the default continues to false? I know the self-fulfilling prophecy point wouldn't be take care of.

@arvindsv - I was thinking about moving the GC configuration to Go's config, and setting up a scheduler to use that. This should take care of not forcing a server restart when periodic GC is enabled by an enduser. If we head down this path, we need to take care of using the JVM args with cron settings setup by instances so far and pushing them into their respective Go configs. Lets assume we find someway of doing that. 
Now the thing thats left to be figured out is the default value - true or false. The reason for keeping the default was to make sure that the server startup doesn't take forever upon next upgrade. We spoke about a bunch of these things while the feature was originally being developed, but somehow I cannot find them anymore. Anyway, would putting up a notice on release notes be enough of a warning for the users or do you suggest keeping the default as false (same as today). Even with the value turned off, it would still be a benefit over what we have today ie. a restart of Go server is not required when periodic GC is enabled or cron settings are changed. What do you think?

**Comment by arvindsv** [comment]
How about just copying the directory at some point and try to do a `git gc` in the middle of the night? No locks. If a config save happens during that time, throw away the attempt (remove dir) and start over again in an hour. Try 5 times a day and give up - try next day. Eventually, it'll complete. Replace the directory once complete.

**Comment by arvindsv** [comment]
Then we can figure out a good default for the periodic value.
