### ISSUE TITLE
Error "Failed to update environment 'XXXX'. null" , while editing  environment via UI

### ISSUE THREAD

**Issue by nserebry** [gocd/gocd#3221]
##### Issue Type
 

- Bug Report

##### Summary

Getting Error "Failed to update environment 'XXXX'. null"  while editing Environment from UI.

###### Basic environment details

* Go Version: 17.1.0
* JAVA Version: 1.8.0_91
* OS: Linux 3.13.0-74-generic
* Browser vendor and version (if relevant): Chrome latest

###### Additional Environment Details

Using JSON Configuration Plugin 0.2 [json.config.plugin]. 
##### Steps to Reproduce

1. goCD and plugin already set, config-xml modified as well. 
2. In GH created pipeline with *.goenvironment.json  and test-pipeline.gopipeline.json
*.goenvironment.json example:
```
 {
  "name": "default",
  "pipelines": [
    "test-pipeline"
  ]
}
```
3. After commiting code , open UI and try to modify "default" (e.g.: by clicking "Edit"  and trying to add another pipeline) . Click "Save"
4. See  attached 
<img width="687" alt="default_-_environment_-_go" src="https://cloud.githubusercontent.com/assets/5048814/23487332/2ba84f1a-fe9a-11e6-96da-af31c410920c.png">

##### Expected Results

Should be able to modify env using UI 
##### Actual Results

Error "null"
##### Log snippets

```
2017-03-02 00:03:00,668  INFO [qtp2143192188-2226] GoConfigDao:91 - Config update for pipeline request by com.thoughtworks.go.server.domain.Username@185223c3[displayName=XXXX,username=XXXX] is in queue - com.thoughtworks.go.config.update.UpdateEnvironmentCommand@487815a8
2017-03-02 00:03:00,669  INFO [qtp2143192188-2226] GoConfigDao:93 - Config update for pipeline request by com.thoughtworks.go.server.domain.Username@185223c3[displayName=XXXX,username=XXXX] is being processed

``` 
Browser console:
> Request URL:https://gocd.vevodev.com/go/environments/XXXXX
> Request Method:POST
> Status Code:400 Bad Request

##### Any other info

Only Env mentioned in *goenvironment.json file is affected.

**Comment by varshavaradarajan** [comment]
@nserebry , in release 17.1.0, environments specified via a config repo *cannot* be edited via the gocd UI. We made a change in 17.2.0 to allow editing parts of the environment config specified in the main `cruise-config.xml` file. Please refer to [this](https://github.com/gocd/gocd/issues/2943) issue and [this](https://github.com/gocd/gocd/pull/3122) for more details.
