### ISSUE TITLE
Broken functionalities on SPAs after mithril upgrade

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#3227]
### Pipeline Config SPA
- [x] Disable `save` button after onClick, until the AJAX finishes.

### Agents SPA
- [x] Retail Sort Order after page reload(the sort order should be persisted even after the page reload).

### Elastic Agents Profiles SPA
- [x]  2 tooltip icons on profileId.

**Comment by rajiesh** [comment]
verified on 17.3.0 (4700-277f37e8b9775a203b73c2340f0cfb9e9f19c8be)
