### ISSUE TITLE
Initial login redirects from https to http AWS CloudFront

### ISSUE THREAD

**Issue by dratak-invrs** [gocd/gocd#3229]
##### Issue Type
 Bug Report

##### Summary

Have an ec2 instance running with GoCD and have a CloudFront distribution setup as front end for ssl termination.  it communicates on with the go-server via port 8153.
When attempting to go to build server via default url e.g. **https**://buildserver.domian.com
the request is redirected to **http**://buildserver.domain.com/go/auth/login

after reading issues #741 and #1432 I configured Cloudfront to include the X-Forwarded-Proto :https header.
I can manually login by changing the url to  **https**://buildserver.domain.com/go/auth/login
and login fine. but of course when signing out or if there are any login errors I get redirected back to **http**

##### Environment
 Amazon Linux AMI
Go Version: 17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45)

**Comment by ketan** [comment]
Have you tried setting the `serverUrl` and `secureServerUrl` parameters at `https://buildserver.domain.com/go/admin/config/server`?

**Comment by ketan** [comment]
I'm going to close this issue, but if this persists after the configuration change, please let us know so we can re-open the ticket.

**Comment by dratak-invrs** [comment]
I already set  both the serverUrl and secureServerUrl to use https and yes its still happening.  
And actually although I can manually go to the login page via https.  After logging in I realized that I am no longer using an https connection.
I have restarted the go server as well to ensure the serverUrl and secureServerUrl have taken effect and they have but I still have the problem.

Let me know if you need any other information.

**Comment by ketan** [comment]
Is cloudfront forwarding to ELB or an ec2 instance? Do you happen to have any other reverse proxies in between that may be swallowing headers?

**Comment by dratak-invrs** [comment]
forwarding to an ec2 instance.  I have no other reverse proxies in between although the instance does reside inside an aws VPC.
