### ISSUE TITLE
Support label template based on Date-Time

### ISSUE THREAD

**Issue by fire** [gocd/gocd#3236]
##### Issue Type

- Feature enhancement

##### Summary

It make our releases better if there was a way to encode the date-time into the label template. We would use iso date-time, but it would help others to have it be templated.

Something like:

"a-9.0.${count}.${perforce} ${iso_date}" 

or

"a-9.0.${count}.${perforce} ${YYYYMMDD}"

**Comment by jithin6384** [comment]
hi any update here

**Comment by arvindsv** [comment]
No, but there's a [PR opened yesterday](https://github.com/gocd/gocd/pull/5180) which introduces `${env:ENV_VAR}`, which might make introducing `${date:YYYYMMDD}` easier if anyone wants to contribute a change right after it is merged.

**Comment by arvindsv** [comment]
Closing as stale.
