### ISSUE TITLE
Adding user through modal box throws 500 Internal Server Error

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#324]
# Steps to reproduce
- Click on "ADD USER" button on user summary page
- Search with some text that results in more than one user
- Select an user (say user1)
- Select another user (say user2)
- Click on "ADD USER" in the modal box (Submit)
## Expected Behaviour

Only user2 should be added
## Current Behaviour

The modal box displays a message saying "Server error occured. Check log for details." (500 Internal Server Error is thrown). However, both user1 and user2 get added - these newly added users are shown on page refresh.

**Go Server Version** : 14.2

**Comment by varshavaradarajan** [comment]
Can be closed. Fixed via https://github.com/gocd/gocd/pull/4182
