### ISSUE TITLE
Upgrading the Log4j version

### ISSUE THREAD

**Issue by padmam** [gocd/gocd#3243]
##### Issue Type

- Feature enhancement

##### Summary

Upgrading and supporting the newer version of log4j i.e. log4j version 2 or above has features which allows zipping of the log files and force roll over the log based on size and time.

##### Expected Results
Supporting the latest version for user compatibility

##### Actual Results
The log4j version being supported is 1.2.17. 

##### Possible Fix
Upgrading and supporting version above log4j 2.

**Comment by arvindsv** [comment]
Moved to logback. Closing this.
