### ISSUE TITLE
Pipeline Trigger with options page UI misalignment 

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#3260]
##### Issue Type

- Bug Report

##### Summary

For pipelines with more than 5 or 6 dependencies the trigger with options page UI's text and the auto-suggestion are misaligned

###### Basic environment details

* Go Version: `17.3.0 (4652-d37834a6dc961a8c102a4304f4d36f7074c3ea4f)`
* Browser vendor and version (if relevant): `Chrome 56`

##### Steps to Reproduce

1. Create a material with 5-6 materials
2. Click on trigger with options page

<img width="843" alt="screen shot 2017-03-14 at 2 20 33 pm" src="https://cloud.githubusercontent.com/assets/6533924/23892932/956b334a-08c2-11e7-8bb3-a96a6d73e522.png">

**Comment by ankitsri11** [comment]
Go Version: 17.3.0 (4700-277f37e8b9775a203b73c2340f0cfb9e9f19c8be)
Verified on Chrome v56, IE edge, Firefox v52
