### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3262]
##### Issue Type

- Feature enhancement

##### Summary

Identified several issues with agent-bootstrapper, agent-launcher and agent logging —

* no documented way to configure logging
* a lot of setup is "programatic", with little ways to configure it
* inconsistent how logging is configured across the 3 systems

After some thought here's what I think will work well —

There will be 2 files —

* `config/agent-bootstrapper-log4j.properties`
* `config/agent-log4j.properties`

If the file is present, the bootstrapper and agent will load it up, if not they will gracefully fallback to loading the same files from the classloader, and print a message (to stderr?) that indicates how logging may be configured.

Since the agent-launcher works in the same process as the bootstrapper, we need to ensure that `config/agent-launcher-log4j.properties` does not mess up the log4j configuration via either

* classloader isolation (already in place), might mean multiple copies of logging jars [NOT DONE]
* threadgroup isolation

**Comment by jyotisingh** [comment]
Will this also take care of the configuring the logs directory for the agent (bootstrapper+launcher+real_agent) for all supported platforms?

**Comment by ketan** [comment]
Yes, I'm hoping to be able to configure it via `-Dgocd.agent.log.dir=...` and set it in the appropriate log4j file —

```properties
log4j.appender.FOO.File=${gocd.agent.log.dir}/go-agent.log
```

**Comment by varshavaradarajan** [comment]
Multiple agents on the same machine ended up logging to /var/log/go-agent/go-agent.log, I think, because somewhere we are hardcoding the location to be /var/log.. mostly in agent.sh. That should also be taken care of, I think. This comes into picture for deb and rpm installations and not for zip.

**Comment by jyotisingh** [comment]
PR - https://github.com/gocd/gocd/pull/3267
