### ISSUE TITLE
Dynamic agent cleanup

### ISSUE THREAD

**Issue by Stono** [gocd/gocd#3264]
Hey guys, 
This isn't so much an issue for you, as it is for me (see https://github.com/Stono/ci-in-a-box/issues/1).

I would love some advice though, quite simple - is there an easy way to periodically clean up agents that have gone into `lost contact`?

**Comment by arvindsv** [comment]
No. :( I know of no easy way.

**Comment by jyotisingh** [comment]
Would a kubernetes elastic agent plugin solve this problem? Elastic agent plugins get callbacks to deal with spinning up of an agent when a job is scheduled. Such plugins get periodic callbacks to initiate spinning down of the agents. As a part of the cleanup, they could initiate agent-cleanup from Go's config as and when the agent is being torn down. Check [docker-elastic-agent](https://github.com/gocd-contrib/docker-elastic-agents) for an example. 

If writing an elastic agent plugin for kubernetes doesn't work for you, then you could make use of Go's APIs to do the same. You need to first [disable](https://api.gocd.io/current/#update-an-agent) the agent and then [delete](https://api.gocd.io/current/#delete-an-agent) it. This however requires you to pass along admin credentials while invoking the APIs.

**Comment by Stono** [comment]
@jyotisingh I went down the route of writing a shell script to clean up the agents after a kubectl deployment rollout is completed, he it is for others who may need it (ps you'll need to do apt-get install jq)
```
#!/bin/bash
set -e
API_URL="http://gocd-master:8153/go/api"
GOCD_PASSWORD=
GOCD_USERNAME=
gocd() {
  curl -s -X $1 "$API_URL/$2" \
    -H 'Accept: application/vnd.go.cd.v4+json' \
    -H 'Content-Type: application/json' \
    -u "$GOCD_USERNAME:$GOCD_PASSWORD"
}

get() {
  gocd "GET" "$1"
}

delete() {
  gocd "DELETE" "$1"
}

disable_agent() {
  curl -s -X PATCH "$API_URL/agents/$1" \
    -H 'Accept: application/vnd.go.cd.v4+json' \
    -H 'Content-Type: application/json' \
    -u "$GOCD_USERNAME:$GOCD_PASSWORD" \
    -d '{
          "agent_config_state": "Disabled"
        }'
}

delete_agent() {
  disable_agent "$1"
  delete "agents/$1"
}

get_agents() {
  get "agents"
}

export API_URL
export -f delete_agent
export -f disable_agent
export -f get_agents
export -f delete
export -f get
export -f gocd

get_agents | jq  -c '._embedded.agents[] | select(.agent_state | contains("LostContact")) | .uuid' | xargs -r -n 1 bash -i -c 'delete_agent $@' _
echo "Cleanup complete."
exit 0
```

**Comment by MPV** [comment]
Maybe this could also be of help? https://github.com/gocd/gocd/pull/5189
