### ISSUE TITLE
Elastic Profile Id scroll down doesn't scroll through all the elastic agent profiles.

### ISSUE THREAD

**Issue by Junaidshah** [gocd/gocd#3265]
Issue Type: Bug.

 Summary

Elastic Profile Id scroll down under job settings doesn't scroll through all the elastic agent profiles. Only the first 9 elastic agent profiles are listed there. 

 Basic environment details

* Go Version: 17.3.0
* JAVA Version: 1.8.0_121
* OS: Linux 3.10.0-514.10.2.el7.x86_64
* Browser vendor and version (if relevant): Google chrome - version 56.0.2924.87

Steps to Reproduce
1. Login to the go dashboard. 
2. Inside any pipeline , under job settings try to add a elastic agent profile using auto correct scrolling through the available profiles in the dropdown.

Expected Results
All the available profiles should be listed in the dropdown.

Actual Results
Only first 9 profiles get shown in the dropdown.

Code snippets/Screenshots
<img width="1006" alt="screenshot 2017-03-15 10 49 55" src="https://cloud.githubusercontent.com/assets/5434680/23934945/c760b90e-096e-11e7-86a9-4369dc5a42f6.png">
-->

**Comment by arvindsv** [comment]
Closing. Checked and I see 10. Haven't tried more.
