### ISSUE TITLE
Stage Status is incorrect when navigating backwards

### ISSUE THREAD

**Issue by salliewalecka** [gocd/gocd#3283]
##### Summary

It seems like clicking the 'back' button to return to the dashboard displays incorrect status of the current build until you reload the page or wait ~20 seconds.  This is very confusing when you are navigating through your pipelines and the information is no longer accurate.

###### Basic environment details

This is occurring on build.gocd.io

* Go Version:  17.3.0 (4676-b022920df0e4d8164bd0f509aaa3e9d90b2798f6)

* Browser vendor and version (if relevant): Chrome 56

##### Steps to Reproduce

1.  Trigger a build from the dashboard see that it is building, wait for it to pass the first stage.
2.  Inspect a downstream pipeline->stage
3.  Click the back button until you are back to the dashboard
4. Observe the first stage is "building" even though there wasn't a reason for it to be kicked off again
5. Refresh the page
6.  See that the stage has completed that stage and the next stage!

##### Expected Results
Clicking the back button should accurately reflect the state of the pipeline

##### Code snippets/Screenshots
State right after clicking the back button
<img width="857" alt="screen shot 2017-03-17 at 1 59 26 pm" src="https://cloud.githubusercontent.com/assets/11946238/24063162/bd3c9c1e-0b1b-11e7-84fe-e6d6981b11d6.png">

Refreshed state 10 seconds later 
<img width="862" alt="screen shot 2017-03-17 at 1 59 36 pm" src="https://cloud.githubusercontent.com/assets/11946238/24063195/e6fd3716-0b1b-11e7-8c19-fccbf2b1c349.png">

I wish my pipelines were that fast :)

**Comment by GaneshSPatil** [comment]
@salliewalecka -- This issue has been fixed as part of the new dashboard introduced in GoCD `v18.3.0`.
