### ISSUE TITLE
CA Certificates in docker container have broken gocd notification plugin (and probably others)

### ISSUE THREAD

**Issue by Stono** [gocd/gocd#3290]
Hey, 
I don't suppose any of the gocd devs would be able to answer https://github.com/ashwanthkumar/gocd-slack-build-notifier/issues/68 for me?

Thanks!

**Comment by Stono** [comment]
This is a bug in your base container guys, please see https://github.com/Stono/gocd-master/blob/master/Dockerfile in particular:

```
RUN update-ca-certificates -f 
RUN /var/lib/dpkg/info/ca-certificates-java.postinst configure
```

These two lines resolve the issue

**Comment by varshavaradarajan** [comment]
@Stono , We are using [this](https://github.com/gocd/docker-gocd-server) repository for the new alpine server image we are building. I'll be moving this issue there so that we can keep track of it. Closing it here.
