### ISSUE TITLE
Redundent Object Clone for Environments API

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#3292]
##### Issue Type

- Code Level Fix

##### Summary

In environments controller, to get the existing environment entity we call [`getEnvironmentForEdit `](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/controllers/api_v1/admin/environments_controller.rb#L70)
which internally does [an object clone](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/EnvironmentConfigService.java#L164-L166).
Object clone was needed by the [old controller](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/controllers/environments_controller.rb#L50-L58) as it modifies the the object which it receives.

In APIs, we don't need to do a object clone because on every request a new object is created, also it might be an overhead and can cause slowness depending upon the size of the environment config.

**Comment by kritika-singh3** [comment]
Is this still relevant?

**Comment by GaneshSPatil** [comment]
@kritika-singh3 -- this issue is not relevant anymore. This issue has been fixed as part of migration from rails to spark.

Closing...
