### ISSUE TITLE
Encrypt secure plugin configuration for Elastic Agent and Authorization Plugins

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3294]
Plugin configurations marked as ```secure``` need to be encrypted before saving to config xml.

- [ ] Move Elastic Agent and Authorization metadata stores to plugin-metadata-store package
- [ ] Ensure secure plugin configurations for Elastic Agent and Authorization plugins are encrypted before saving to xml through API or config save.

**Comment by rajiesh** [comment]
This [PR](https://github.com/gocd/gocd/pull/3356) fixes this issue, verified on 17.4.0 (4888-cbd790d635c52dc6e0765cc2b4c8e52745e00271)
