### ISSUE TITLE
Support GET/INDEX API calls for Remote Environments.

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#3295]
##### Issue Type

- Feature enhancement

##### Summary

Currently, the GET/INDEX call returns the partial environment from cruise-config.
Add ability to get merged environment config (cruise-config + config-repo) using API.

##### GET environment (merged)

```
curl 'https://ci.example.com/go/api/admin/environments/my_environment' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v2+json'
```

##### GET local environment (cruise-config)

```
curl 'https://ci.example.com/go/api/admin/environments/my_environment?remote=false' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v2+json'
```

##### GET remote environment (config-repo)

```
curl 'https://ci.example.com/go/api/admin/environments/my_environment?remote=true' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v2+json'
```

**Comment by GaneshSPatil** [comment]
@jyotisingh @ketan -- can you look at the query param and give some feedback regarding the API calls?

**Comment by ketan** [comment]
LGTM. Do we have a situation where one might need to see the remote environment in a specific origin, perhaps by passing `origin_name=xxx` param?

**Comment by GaneshSPatil** [comment]
@ketan -- _origin type_ is necessary for getting the editable part(when origin is local) or the entire config(when the origin is merged) of the environment.

There could be a situation where a single environment is defined in multiple origins (cruise-config, multiple config-repos, etc), in such cases, user might want to see the partial environment based on the origin, such as,
`origin_name=local` - to get the editable part of the environment.
`origin_name=config_repo1, config_repo2` - to get the remotely defined part of the environment.

**Comment by GaneshSPatil** [comment]
The point of adding support to **GET environment along with the remote information** is to get the entire environment config using API (current API only returns the partial environment from config.xml even if the same environment is defined in multiple origins).

For Environments specified in multiple origins (`config repository` + `config.xml`),
API should return :
- Editable part of the environment config
- Entire environment config

##### GET editable part of the environment:
```
curl 'https://ci.example.com/go/api/admin/environments/my_environment' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v3+json'
```

##### GET the entire environment:
```
curl 'https://ci.example.com/go/api/admin/environments/my_environment?withremote=true' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v3+json'
```

@ketan @jyotisingh -- i didn't find any specific use case for getting only the `remote` part of environment or specific the origins by specifying `origin_name`.
If there are any, we could add an extra query-param (`remote=true` or `origin_name=XXX`) to support getting partial environment configs.

**Comment by GaneshSPatil** [comment]
All the environments (config+merged) could be fetched using the following internal API endpoint:
```terminal
curl 'http://localhost:8153/go/api/admin/internal/environments/merged' \
      -u 'admin:badger' \
      -H 'Accept:application/vnd.go.cd.v1+json'
```
