### ISSUE TITLE
Canceled tasks still continue to run and produce log output

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#3298]
##### Summary

Canceling a build does not appear to kill running tasks; running tasks continue to generate output to logs even after a build is marked as canceled/complete. Presence of an onCancel task does has no effect either, as the running task continues to generate output even after a cancel task finishes, until the running task naturally exits.

##### Environment

I've noticed this behavior in development. Probably happens in real instances too. I'm running MacOS X, but I would guess this at least affects Linux as well. Unsure about Windows. I've tested this with tasks that exit properly on SIGTERM (and saw the aforementioned behavior), as I've been told that is the signal sent to tasks when a build is canceled.

##### Steps to Reproduce

I created a job with the following task:

```xml
              <exec command="bash">
                <arg>-c</arg>
                <arg>for i in $(seq 1 20); do echo $i; sleep 5; done</arg>
                <runif status="any" />
                <oncancel>
                  <exec command="bash">
                    <arg>-c</arg>
                    <arg>echo "some STDOUT"; echo "more STDOUT"; echo "some STDERR" &gt;&amp;2; echo "more STDERR" &gt;&amp;2</arg>
                  </exec>
                </oncancel>
              </exec>
```

  1. Run the build
  2. While the `for` loop is executing, cancel the build
  3. Watch the logs (you will have to refresh every 5 or 6 sec as the console data polling stops, even though additional output continues to be generated)

##### Expected Results

One should see the onCancel task output, then "Job complete". The `for` loop should be terminated and cease generating output.

##### Actual Results

One sees the onCancel task output, but the for loop continues to generate output until the loop finishes naturally.

Here's a snippet:

```text
11:38:23.350 [go] Start to execute task: bash -c "for i in $(seq 1 20); do echo $i; sleep 5; done".
11:38:23.365 1
11:38:28.368 2
11:38:33.371 3
11:38:38.378 4
11:38:43.386 5
11:38:48.391 6
11:38:52.729 [go] Start to execute cancel task: bash -c 'echo "some STDOUT"; echo "more STDOUT"; echo "some STDERR" >&2; echo "more STDERR" >&2'
11:38:52.744 some STDOUT
11:38:52.745 some STDERR
11:38:52.746 more STDOUT
11:38:52.746 more STDERR
11:38:52.849 [go] Task is cancelled
11:38:53.395 7
11:38:58.398 8
11:39:03.406 9
11:39:08.409 10
11:39:13.416 11
11:39:18.420 12
11:39:23.422 13
11:39:28.427 14
11:39:33.431 15
11:39:38.435 16
11:39:43.438 17
11:39:48.442 18
11:39:53.454 19
11:39:58.461 20
11:40:03.611 [go] Job completed up42/1/up42_stage/1/up42_job on marques-lee.local [/Users/marqueslee/repos/go/gocd/agent]
```

**Comment by rajiesh** [comment]
@marques-work This behavior is observed only for tasks with on-cancel task defined, tasks without on-cancel task will be terminated ones the stage is cancelled. 
The behavior you experienced is the way current implementation is for a task which has On-Cancel task defined. The expectation is that the on-cancel tasks take care of cleanup and terminating any running process that the task has created, however that assumption is debatable.

I prefer the current behavior, If a user is defining what need to be done in event of cancel it should take care of terminating processes too.

cc @jyotisingh  and @arvindsv for comments

**Comment by arvindsv** [comment]
Oh. Yeah, you're right. This caught us unawares a little while ago, too, right? The [documentation](https://docs.gocd.io/current/advanced_usage/dev_clean_up_when_cancel.html) doesn't call it out very explicitly, but the behavior is that the existence of an on-cancel task creates the expectation that the task will take care of any "killing" it needs to do.

It's surprising behavior. But, it is what it is. I'll close this issue for now. If anyone has suggestions to make this clear in the app or documentation, we should consider those.

Changing this behavior at this time is not an option, because it will be a significant break from (opposite of) what used to happen. :(

**Comment by arvindsv** [comment]
@marques-work said:

> Presence of an onCancel task does has no effect either ...

Can we confirm this? If there is no on-cancel task, does it kill the bash process? If so, we can reopen this.

**Comment by marques-work** [comment]
@arvindsv ok I'll test this out this week and post my findings here.

**Comment by marques-work** [comment]
@arvindsv indeed, works as @rajiesh indicated; process was killed when on-cancel task was not present.

**Comment by arvindsv** [comment]
Hmm. Ok. I'll close it then. As I said, surprising and catches me out too, all the time. But, it is legacy behavior. If we change something around this area, I'll think about whether it makes sense to change it. Thank you for verifying it!
