### ISSUE TITLE
Admin navigational tab is not styled correctly on the Agents SPA

### ISSUE THREAD

**Issue by kyleolivo** [gocd/gocd#3309]
##### Summary

The "Admin" tab/link at the top is in black text (for non-admin users)

See here:
![image](https://cloud.githubusercontent.com/assets/229792/24266703/025d42d2-0fc5-11e7-9011-07bfb56e66a0.png)

**Comment by GaneshSPatil** [comment]
Fixed as part of new headers introduced in GoCD version `v18.12.0`
