### ISSUE TITLE
Agent Does Not Check In/Show Up On Server

### ISSUE THREAD

**Issue by thedavidscherer** [gocd/gocd#3316]
##### Issue Type

- Bug Report

##### Summary

After installing the Go Server to evaluate Go, I installed the Debian agent via Aptitude using the instructions in the documentation.

##### Environment

**Comment by thedavidscherer** [comment]
The rest of the bug report didn't fit: 

[GoCD_Bug_RestOfReport.htm.md.txt](https://github.com/gocd/gocd/files/868908/GoCD_Bug_RestOfReport.htm.md.txt)

**Comment by ketan** [comment]
It seems you're using java 9. It's currently not support. Please downgrade to java 8 instead.
