### ISSUE TITLE
Invalid branch specification as a material does not specify the pipeline where the issue exists

### ISSUE THREAD

**Issue by mikhailadvani** [gocd/gocd#3319]
##### Issue Type

- Bug Report

##### Summary

Invalid branch specification as a material shows error in the "Errors" modal but does not specify which pipeline has the invalid configuration
<img width="762" alt="screen shot 2017-03-27 at 11 21 08 am" src="https://cloud.githubusercontent.com/assets/2051423/24343067/1ad31e0c-12e2-11e7-872c-04e1d8f1ee97.png">

###### Basic environment details

* Go Version: `17.2`
* JAVA Version: `1.8.0_91`
* OS: `Linux 3.13.0-29-generic`

##### Steps to Reproduce

1. Specify an invalid branch in a git material
2. Check the errors tab

##### Expected Results

1. The "Errors" modal should specify the pipeline(s) with the invalid materials

##### Actual Results

1. The "Errors" modal specifies the invalid materials but not the pipelines where the material is defined

**Comment by kritika-singh3** [comment]
We have pushed in a fix via https://github.com/gocd/gocd/pull/6131 in GoCD version 19.4.0. Can you update your GoCD server and verify that this has been resolved.
