### ISSUE TITLE
Go API define page size

### ISSUE THREAD

**Issue by marko-milenkovic-myob** [gocd/gocd#3326]
##### Issue Type

- Feature proposal

##### Summary

As an API user, I would like to have the ability to define "Page Size" in endpoints that provide paging, e.g.

GET /go/api/pipelines/:pipeline_name/history[/:offset]
GET /go/api/stages/:pipeline_name/:stage_name/history[/:offset]
GET /go/api/jobs/:pipeline_name/:stage_name/:job_name/history[/:offset]

At the moment, only 10 can be retrieved per request.

Thank you!

**Comment by CheolminConanShin** [comment]
I have same question!

**Comment by victor-sim** [comment]
Me too. It's critical for us.

**Comment by Stono** [comment]
Ditto, this frankly sucks :D
