### ISSUE TITLE
Go API - provide failed job error messages

### ISSUE THREAD

**Issue by marko-milenkovic-myob** [gocd/gocd#3327]
##### Issue Type

- Feature proposal

##### Summary

Provide the ability to retrieve failed job error messages, the ones provided in the Go software, job failures tab.

Thank you!

**Comment by ketan** [comment]
> Provide the ability to retrieve failed job error messages, the ones provided in the Go software, job failures tab.

Could you provide an example of the error message, and who (or what) needs the ability to retrieve the message?

**Comment by marko-milenkovic-myob** [comment]
Hi Ketan,

Thank you for the response and sorry if I was unclear.

There is a Failures tab in the Go Software when you drill down to the failed job. I was wandering if whoever is building the Go API can provide that information as a feature in one of the endpoints. I would assume the information can be provided in one of the endpoints related to job history:

https://api.gocd.io/16.12.0/#get-job-history

**Comment by marko-milenkovic-myob** [comment]
I just found out how to do this, through the job artifacts, wasn't aware that is is already provided as part of the Go API.

https://api.gocd.io/16.12.0/#the-artifact-object

Thank you!
