### ISSUE TITLE
Modify cr­uise-­confi­g.xml with  API call

### ISSUE THREAD

**Issue by nserebry** [gocd/gocd#3328]
##### Issue Type

- Feature proposal

##### Summary
Modify cr­uise-­confi­g.xml with  API call
##### Steps to Reproduce

1. Trying to automate pipeline creation using gocd-json-plugin, and reduce manual step for editing xml.config.  Would be nice to edit config.xml with API.

##### Expected Results

No easy way to modify (manage) config.xml file

**Comment by ketan** [comment]
You can modify specific parts of the config xml using a lot of [documented apis](https://api.gocd.io)

Is there a specific part that you want to edit to narrow the scope of this feature request?

**Comment by nserebry** [comment]
@ketan We trying to use https://github.com/tomzo/gocd-json-config-plugin and it requires https://github.com/tomzo/gocd-json-config-plugin#add-configuration-repository  editing the config XML.

**Comment by arvindsv** [comment]
Closing in favor of https://github.com/gocd/gocd/issues/3656
