### ISSUE TITLE
Need extension to get all configured elastic profile from plugin

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3336]
##### Issue Type

- Feature enhancement

##### Summary

Running EC2 instances will need to validate over period of time(running idle ?, when to terminate?). 
This needs to be done for each EC2 instance running in cluster. Profile may have changed after creation of EC2 instance.

Or 

Send all profiles with server ping call ?

**Comment by arvindsv** [comment]
Closing as stale. Also, I think the elastic agent plugins take care of this now. Looks like the ping call does send all profiles: https://plugin-api.gocd.org/current/elastic-agents/#server-ping
