### ISSUE TITLE
Allow agent filter to filter on plugin id

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3338]
##### Issue Type

- Feature proposal

##### Summary

It is currently not possible to lookup just docker agents or openstack agents with the search. Since the agent api already provides the plugin info, it should be possible to filter based on elastic agent plugin id.

**Comment by GaneshSPatil** [comment]
This issue has been fixed via https://github.com/gocd/gocd/pull/3342 as part of GoCD release `v17.4.0`
