### ISSUE TITLE
Fix rspecs to mock services

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#3346]
A whole bunch of specs which do not mock the services involved end up calling the actual services. They expect certain setup to be available, and fail if that is not the case. 

Some of them are listed out in this run
https://build.gocd.io/go/tab/build/detail/build-linux-PR/1419/build-server/1/rspec-split-runInstance-1. These started failing after [this](https://github.com/maheshp/gocd/commit/d0a8a58114579ae3f2d94baa95512722c4b3293b#diff-b4d9fb736e97b32e8ada7cb66411854dR115) specific change was done. 

Intent of this card is to find such tests and fix them.

**Comment by varshavaradarajan** [comment]
https://github.com/gocd/gocd/pull/3465
