### ISSUE TITLE
Provide API to configure plugins

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3354]
##### Issue Type

- Feature proposal

##### Summary

In order to automate provisioning and configuration of GoCD along with all plugins, it would be nice to see an API to be able to configure plugins, this is currently possible only via the UI.

**Comment by ketan** [comment]
Depends on #3354

**Comment by varshavaradarajan** [comment]
The API response -
```
{
    "plugin_id": "foo",
    "settings_properties": [
        {
            "key": "username", #User will pass this based on the "plugin_settings" in the plugin info API response
            "value": "admin"
        },
       {
             "key": "password",
             "value": "badger"
       }
   ]
}
```

We need to think of a strategy to accept encrypted values from users for secure plugin settings properties.

**Comment by ketan** [comment]
> We need to think of a strategy to accept encrypted values from users for secure plugin settings properties.

Whatever we do, can we keep the properties structure to be the same as the one used on the pipeline config API?

**Comment by varshavaradarajan** [comment]
You mean the above structure, right? 
```
"properties": [
    {
         "key": "foo",
         "value": "bar"
         "secure": false
    },
   {
       "key": "baz"
       "encrypted_value": "some encrypted value",
       "secure": true
   }
]
```

**Comment by ketan** [comment]
> You mean the above structure, right?

If you mean "below structure", yes.

**Comment by varshavaradarajan** [comment]
That's the same as the structure I posted before. :)
