### ISSUE TITLE
Pipeline history page navigation link not working

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3357]
Issue Type: Bug

##### Summary
Unable to navigate to any of the pipeline history page.

###### Basic environment details

* Go Version:  17.4.0 (4798-df9e0ad5e9cac6124b3a6bcb186f5ca92ec61b3f)
* Browser vendor and version (if relevant): Chrome Version 57.0.2987.133 (64-bit)

##### Steps to Reproduce

1. Click on the pipeline name
2. Try to click on any navigation link (page 1,2,3... or next link)
3. It doesn't navigate to any of the pages

Expected results:
It should take you to the desired pipeline history page.

**Comment by arvindsv** [comment]
@rajiesh @ankitsri11 This needs a functional test - or some test at some level. I can't believe this is broken!

**Comment by GaneshSPatil** [comment]
##### Other related issues:

* Broken pipeline history search functionality on pipeline history page

**Comment by rajiesh** [comment]
Verified on 17.4.0 (4888-cbd790d635c52dc6e0765cc2b4c8e52745e00271)
