### ISSUE TITLE
Allow cloning templates in GUI

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#336]
Currently, cloning a pipeline template requires direct editing of the underlying XML. This should be an option nearly identical to cloning a pipeline.

**Comment by kcormier** [comment]
@arvindsv: When you said it needs interest from someone, does that mean someone interested in using the feature, or someone interested in doing the work?

I am definitely interested in using the feature.  I don't have the bandwidth to implement it now, but may try to pick it up in the future.

We copy templates when we want to test changes to the build pipeline before fully implementing them.  While way outside the scope of this, an alternative for this use case would be versioned templates (independently or with the code).  AFAIK those don't exist but supporting build configuration in the source repo is in the roadmap for this year?

**Comment by benzvan** [comment]
Better access to the version system would be amazing. I know all the configuration is versioned in Git behind the scenes in Go, but there's no good way to access them except through the API. Even then, every change to the config is a commit, which makes it very hard to separate out only the things you want. Unless there's some super secret mechanism for reverting changes to a template.

**Comment by flewid-cd** [comment]
+1

**Comment by dzschille** [comment]
+1
