### ISSUE TITLE
On Job Details -> Console log tab the "Back to Top" link not accessible when health message is shown

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#3363]
##### Issue Type

- Bug Report

###### Basic environment details

* Go Version: `17.4.0 (4819-af91a90e96c75469ad2857ce0fea83f23edfb236)`

##### Steps to Reproduce

1. Navigate to Job Details -> Console log tab of any job
2. Ensure the server health message shows up with Error & Warnings
3. The "Back to Top" link on bottom right corner of the console logs hides behind the health message.

Here is the screenshot from build.go.cd

<img width="1385" alt="screen shot 2017-04-05 at 6 53 18 pm" src="https://cloud.githubusercontent.com/assets/6533924/24707579/cc412e6c-1a31-11e7-8d6b-6d81401ce347.png">

**Comment by ibnc** [comment]
@naveenbhaskar What're your thoughts on how to resolve this issue?

I'm thinking one of the two solutions:

Move the errors/warnings box to the bottom left of the page:


<img width="1440" alt="errors_to_left" src="https://cloud.githubusercontent.com/assets/5726224/24766968/3ce99912-1ab2-11e7-9764-cf8458e20220.png">

Moving the back to the top button to the bottom left of the console area:

<img width="1440" alt="back_to_top_to_left" src="https://cloud.githubusercontent.com/assets/5726224/24766972/3f43c6ce-1ab2-11e7-9aca-23bd6896c1cd.png">


Thoughts?

**Comment by arvindsv** [comment]
@naveenbhaskar Let's discuss this tomorrow. We need a resolution one way or another.

**Comment by naveenbhaskar** [comment]
I was thinking of moving the error/warning to the top of navigation bar. The existing position is not very noticeable.

![image](https://cloud.githubusercontent.com/assets/1627961/24846724/0d479fd0-1dda-11e7-9888-7899c48dce28.png)

Another option could be moving "back to top" to the top sticky panel of the console and rename to "scroll to top". reachability for "back to top" is same if its bottom or top if console. Actually its easy if somebody want to move top and bottom at once to check things. 

![image](https://cloud.githubusercontent.com/assets/1627961/24846811/a103553e-1dda-11e7-82a5-5fb0b64739f7.png)

what do you think?

**Comment by ibnc** [comment]
I like the first option @naveenbhaskar. It makes it more noticeable, and I don't think changing the way that people use the console area should be done lightly.


I'll start working on this

**Comment by ibnc** [comment]
@arvindsv @naveenbhaskar @rajiesh I believe this issue can be closed now that my changes have been merged.

**Comment by arvindsv** [comment]
For some reason, this is not yet deployed on build.gocd.io. Let's wait for someone to see why that is. /cc @rajiesh

**Comment by arvindsv** [comment]
It got deployed, just a few minutes ago. I'm fine with closing this. I think @rajiesh should, if he's ok with it.

**Comment by arvindsv** [comment]
I assume that the notification of a new version of GoCD (that little bell) doesn't get hidden by this. :)

**Comment by ibnc** [comment]
@arvindsv I'm unfamiliar with this little bell. Do you have a screenshot? Or maybe a css class for it so I can confirm that it won't get hidden by it?

**Comment by arvindsv** [comment]
Try this on the dashboard page:

```javascript
jQuery(".application_nav ul.user").after('<div class="notifications"><span class="bell"></span><div class="hover-container"><div class="hover"><span>Some message here.</span></div></div></div>')
```

**Comment by ibnc** [comment]
@arvindsv Thanks!

I can confirm that it does not hide the bell:

<img width="1423" alt="error_box_with_bell" src="https://cloud.githubusercontent.com/assets/5726224/25054987/1e2f8a90-2115-11e7-97d5-b18e50d514a3.png">

**Comment by arvindsv** [comment]
👍

**Comment by rajiesh** [comment]
Verified on 17.4.0 (4888-cbd790d635c52dc6e0765cc2b4c8e52745e00271)
