### ISSUE TITLE
AGENTS page not scale to device width because meta viewport is wrong in single_page_app.html.erb

### ISSUE THREAD

**Issue by carrchang** [gocd/gocd#3385]
##### Issue Type

- Feature enhancement

##### Summary

Sometimes, we use GoCD from mobile device, AGENTS page not scale to device width because meta viewport is wrong in single_page_app.html.erb. 

###### Basic environment details

* Go Version: `17.3.0`
* JAVA Version: `1.8.0_91`
* OS: `Linux 3.16.0-4-amd64`
* Browser vendor and version (if relevant): `Safari/Chrome iOS`

**Comment by naveenbhaskar** [comment]
Can you tell me which device you are using. GoCD is optimized for devices which have more than 1300px width.

**Comment by carrchang** [comment]
iPhone 7

**Comment by naveenbhaskar** [comment]
Currently GoCD doesn't have support for mobile devices.

**Comment by carrchang** [comment]
I know GoCD doesn't have mobile UI, and now on iPhone, other pages look like,
![img_0165](https://cloud.githubusercontent.com/assets/614483/25233118/3d8a42cc-2610-11e7-8639-524e01559597.PNG)

but AGENTS page look like,
![img_0167](https://cloud.githubusercontent.com/assets/614483/25233227/b7cbe0cc-2610-11e7-9e2b-2a0530ecd8ea.PNG)

we can make it look like,
![img_0166](https://cloud.githubusercontent.com/assets/614483/25233320/0d18291e-2611-11e7-83e9-312fee2e3ae9.PNG)

just by removing viewport config in single_page_app.html.erb.
