### ISSUE TITLE
Issues in quick edit page after Mithrill upgrade

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3387]
This is the placeholder for all issues identified in Quick Edit page after Mithrill upgrade

Issue Type: Bug

Summary:
Stage/Jobs and tasks drag and drop feature is not working in pipeline quick edit page.

Steps:
- Click on pipeline settings gear icon
- Click on "quick edit" link
- try to re-order the stages by drag and drop
- Also try re-ordering jobs/tasks by drag and drop

Expected behaviour:
It should allow to re-order stages/jobs/tasks 

* Go Version: 17.4.0 (4832-8d0eebe4f8ca201d9d79c82586e34a64ff83b12b)
* Browser vendor and version (if relevant): Chrome Version 57.0.2987.133 (64-bit)

Workaround:
Use 'old_view=true' query param to switch the pipeline config page and it should work

**Comment by ankitsri11** [comment]
https://github.com/gocd/gocd/pull/3359

**Comment by maheshp** [comment]
Unable to toggle to Normal Edit

**Comment by maheshp** [comment]
Elastic Profile Id autocomplete not working

**Comment by maheshp** [comment]
Job settings alignment 

![screen shot 2017-04-12 at 3 17 16 pm](https://cloud.githubusercontent.com/assets/1061051/24951777/34ca7982-1f93-11e7-8778-cae758968c85.png)

**Comment by maheshp** [comment]
Cannot drag tasks.

**Comment by maheshp** [comment]
Stage operate permissions, users autocomplete not working

**Comment by maheshp** [comment]
Command lookup autocomplete needs to be fixed

**Comment by ankitsri11** [comment]
Job deletion is not working properly. Throws below exception:

```
vendor-and-helpers.chunk-14e1271….js:24 Uncaught TypeError: t.isBlank is not a function
    at Object.changed (vendor-and-helpers.chunk-14e1271….js:24)
    at Object.remove (vendor-and-helpers.chunk-14e1271….js:24)
    at Object.removeJob (pipeline_configs-0bf74dde66628da03f03.js:1)
    at HTMLButtonElement.N.r (vendor-and-helpers.chunk-14e1271….js:1)
```

In order to delete job, you will need hover on the job name after deleting it.

**Comment by rajiesh** [comment]
Just Consolidating the auto-complete issue which @maheshp raised

Auto-Complete feature is broken at all places(user do not get auto-complete suggestions), Verified for,

* Command Lookup
* Stage operate permissions - Users field
* Elastic Profile Id field in job settings
* Dependency Materials - Pipeline name field

**Comment by ankitsri11** [comment]
Here is the checklist of the issues to be fixed on quick edit page. Please add issue here to the list instead of comments.

- [ ] Drag and drop feature broken on stage,job and task
- [ ] Unable to toggle to Normal Edit
- [ ] Auto complete feature broken at command lookup, Stage operate permissions  - Users field, Elastic Profile Id field in job settings, Dependency Materials - Pipeline name field
- [ ]  Job deletion is not working properly. (Check exception on the above [link](https://github.com/gocd/gocd/issues/3387#issuecomment-293567536))
- [ ] Job settings alignment (check this [comment](https://github.com/gocd/gocd/issues/3387#issuecomment-293528092) for screen shot)

**Comment by arvindsv** [comment]
It looks like secure environment variables, at least at the stage level, are not shown. I've added it to the task list.

**Comment by rajiesh** [comment]
Moving it to 17.5 milestone. All the issues listed [here](https://github.com/gocd/gocd/issues/3387#issuecomment-293571513) are fixed and verified. However will do a round of dog fooding on build.go.cd environment before making it a default page. Currently build.go.cd is toggled on to use Mithril 1.0.1. In 17.4.0-4888 release its toggled off

**Comment by ketan** [comment]
@rajiesh — can we get this done sooner than later?

**Comment by rajiesh** [comment]
Verified on 17.5.0 (5094-facde1c814310d1f9c463c8945c5145a994d0f39)
