### ISSUE TITLE
Optional 2-factor authentication

### ISSUE THREAD

**Issue by agileassistance** [gocd/gocd#34]
It would be nice to have an option to enforce 2-factor authentication for all users using e.g. Google Authenticator or SMS.

**Comment by srinivasupadhya** [comment]
You should be able to write an [authentication plugin](http://www.go.cd/documentation/developer/writing_go_plugins/authentication/authentication_plugin_overview.html) with [web request handling ability](http://www.go.cd/documentation/developer/writing_go_plugins/handling_web_requests.html). Reference -[Sample plugin](https://github.com/gocd/go-plugins/tree/master/plugins-for-tests/test-authentication-plugin), [GitHub OAuth plugin](https://github.com/srinivasupadhya/gocd-oauth-login)

**Comment by srinivasupadhya** [comment]
authentication end-point will be available in 15.2 & this should be straight forward to implement this.
