### ISSUE TITLE
Share go server info (UUID, Site URL, Secure Site URL etc..)with plugin

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3401]
##### Issue Type

- Feature proposal

##### Summary

Share go server identity with plugins to tag plugin generated resources for go server.

#### Why we need it ?

Consider that two go server(for two different team) running and ECS plugin installed on both the server and configured using AWS credentials.

There is no way to identify resources are created using which plugin.

#### Why plugin is not taggin resource with self generated UUID ?

* Plugin will lose it state on go server restart load or unload of plugin

**Comment by Qinmu-Xie** [comment]
#3341

**Comment by ketan** [comment]
Added via #3732.
