### ISSUE TITLE
"Scroll to end of logs" doesn't work properly

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3404]
Issue Type : Defect

Summary:

"Scroll to end of logs" doesn't work properly. By default it is enabled for the collapsed logs. User needs to click on twice to make it work.

![scroll logs](https://cloud.githubusercontent.com/assets/6838313/25082691/0c429176-2370-11e7-92f9-ff578b35553c.gif)

Basic environment details

* Go Version:  17.4.0 (4862-d660bcff2a92c18a18703018bb3091a18634aaa3)
* Browser vendor and version (if relevant): Chrome Version 57.0.2987.133 (64-bit)

Steps to Reproduce

1. Click on the job console logs
2. You should see "Scroll to end of logs" is enabled
3. Expand any task logs and click on "Scroll to end of logs" and it will not work
4. Click it again and it will be enabled

Expected Results
By default "Scroll to end of logs" should be disabled for the collapsed logs.
Single click should make it enable and help you scroll it to the end of the logs.

**Comment by marques-work** [comment]
@ankitsri11 hey Ankit, I have another suggestion as a solution to the behavior.

For some context, logs are only fully collapsed when all tasks were successful. Thus, requiring that the auto scroll behavior depend on this state means that the scrolling code would essemtially be aware of whether or not the build passed. It seems odd that this logic is part of the scrolling behavior.

Rather, I would suggest that expanding a collapsed section should automatically disable the auto scroll. This solves the problem by giving the user the correct visual feedback that matches their expectations (the scroll to end link turns off, so users do not expect the window to scroll). This kind of fits with the current scheme, where any manual interaction (manually scrolling, or clicking tabs) disables the auto scroll. So in other words, I'm suggesting that interacting with the collapsible sections should also be one of the interactions that cancels the auto scroll behavior.

**Comment by marques-work** [comment]
Another reason to go this route is that we can't predict which section the user expands and scrolling to the bottom may actually go against what the user wants (it may scroll past the expanded section entirely, depending on which section was expanded). Better leave the decision to the user.

**Comment by marques-work** [comment]
@ankitsri11 @rajiesh I created a simple pull request to demonstrate the suggested solution outlined above.

**Comment by rajiesh** [comment]
@marques-work I agree with this [reasoning](https://github.com/gocd/gocd/issues/3404#issuecomment-294608066). Lets have the `Scroll to end of logs` off when there is an expanded task in the log(usually in the failed jobs)

**Comment by marques-work** [comment]
@rajiesh I'd opt for the simplest logic possible; leave the scroll to end behavior when entering a build as it is (disable auto scroll when logs are fully downloaded). If autoscroll is on, and a user interacts with the expand/collapse widget of a section, then turn off.

**Comment by marques-work** [comment]
In other words, I don't think autoscroll should have any knowledge other than knowing when the incoming log stream stops. And then, any user interaction should stop the autoscroll, much like the OS X Terminal.

**Comment by marques-work** [comment]
And https://github.com/gocd/gocd/pull/3406 does just that :)

**Comment by rajiesh** [comment]
Verified on 17.4.0 (4888-cbd790d635c52dc6e0765cc2b4c8e52745e00271), working as expected
