### ISSUE TITLE
Pipeline name should not be capitalized on pipeline history page

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#3407]
##### Issue Type

- Bug Report

##### Summary

As mentioned by @arvindsv :

On [pages like this one](https://build.gocd.io/go/tab/pipeline/history/gocd-www.go.cd), because of this [line](https://github.com/gocd/gocd/blob/35776381e8e217183c67dfd97d57c3231c8d16c6/server/webapp/WEB-INF/rails.new/app/assets/stylesheets/css/global.scss#L48), the title (pipeline name) is capitalized. That's wrong. What should show as: gocd-www.go.cd shows up as: Gocd-Www.Go.Cd

##### Proposed solution

This issue was existing on older builds too(verified on 16.5.0). Discussed with @naveenbhaskar and decided to make the title as `Pipeline: <pipeline-name>` by preserving the case of the pipeline name

**Comment by marques-work** [comment]
@rajiesh should be fixed now
