### ISSUE TITLE
Pipeline config API should support patch for attributes

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3411]
##### Issue Type

Feature enhancement

##### Summary

Currently, only edit pipeline config API is supported - where one have to pass the entire pipeline config while updating one or multiple attributes. The side effect of this might lead to unwanted updates. 

It would be great if there is patch support for pipeline config like we have for environments (https://github.com/gocd/gocd/issues/3080).

**Comment by ketan** [comment]
Environments have pipelines, agents and jobs, and the only "batch" operations you can do is add/remove references to these objects, which are defined elsewhere (except for environment variables)

In case of pipeline configs, the object graph is deeply nested, and except for plugin scm materials there are no references to other kinds of objects in the JSON (viz stages, jobs). As such a batch operation which operates at multiple levels (pipelines, materials, stages, jobs, tasks) makes the API lot more convoluted to use and implement than is worth the effort.

**Comment by tonyzwei** [comment]
It would be great if this feature is added on. Thanks.
