### ISSUE TITLE
Low artifacts disk space warning message from Go Server

### ISSUE THREAD

**Issue by TechCowboy** [gocd/gocd#3413]
##### Issue Type

- Bug Report

##### Summary

Receiving emails of low artifacts disk space, however, there is 800+Gb of space available.
Warning is set for 1024Mb

###### Basic environment details

* Go Version:  17.3.0  Server with 64 bit JRE and an Agent with 32 bit JRE.
* JAVA Version: (version included in 17.3.0)
* OS: `Available from Windows 7 64-bit
* Browser vendor and version (if relevant): n/a

###### Additional Environment Details

NOTE: System has all drives Bit Locked.

##### Steps to Reproduce

1. 
2. 
3. 
4. 

##### Expected Results
I expect no emails with the amount of space I have available.

##### Actual Results
Constantly getting low disk space emails

##### Possible Fix
Unknown, since both drives have plenty of space.

**Comment by TechCowboy** [comment]
![storage](https://cloud.githubusercontent.com/assets/2847372/25242757/a5a181ec-25af-11e7-8be8-fc2704986343.JPG)
Don't know why capture did not show up previously.
As shown here, lots of space on all partitions.   Artifact directory is D:\artifacts
As mentioned before, all drives are encrypted.

**Comment by ketan** [comment]
I believe this was fixed in 9cec83fd6dda71ea085525354ca201ab7e4d3dec in release 17.5. Can you confirm if you're still seeing this in a newer version?

**Comment by helmesjo** [comment]
I'm running v18.1.0 of the docker server, however I noticed some issues with my volume mount (/godata), which most definitely is related...

I'll come back! :)

**Comment by ketan** [comment]
Allright, I'll close this issue out. But if you find something amiss, open another new issue with as many details as you can provide.

**Comment by nrajakumar** [comment]
I am seeing the same issue in 18.7. There is more than 200G of space available and its throwing a ARTIFACTS_DISK_FULL  error message.

**Comment by helmesjo** [comment]
Just had this issue again myself. Reinstalling docker solved it (might be enough to disable/re-enable shared drives, and thus re-enter credentials when prompted).
