### ISSUE TITLE
Task screen issue

### ISSUE THREAD

**Issue by padmam** [gocd/gocd#3419]
##### Issue Type

UI issue

- Bug Report

##### Summary

UI Issue of alignment in task screen.

###### Basic environment details

* Go Version: ` go-server_17.4.0-4888_all.deb`
* JAVA Version: `1.8.0_111`
* OS: `MacOSX`
* Browser vendor and version (if relevant): Mozilla Firefox and version 52.0.2(64 bit)

##### Steps to Reproduce

1. While creating a pipeline and adding task click on the `on-cancel` option
2. Choose the `more` option.
3. The alignment of the lookup command,command and arguments overlap
4. Below is the screenshot for reference 
![image](https://cloud.githubusercontent.com/assets/3272253/25275185/995f1c2a-26b1-11e7-95cb-233b18bd5603.png)

##### Expected Results
The screen alignment should not be overlapped. Like  below

![image](https://cloud.githubusercontent.com/assets/3272253/25275276/0298daa0-26b2-11e7-9e63-d68239e29bee.png)

**Comment by marques-work** [comment]
seems fixed as of now (May 10, 2017 -- I'm on 05ee1231b69c6296f7f721dd0842426da3011d4c)

**Comment by arvindsv** [comment]
Closing.
