### ISSUE TITLE
Windows silent installation of gocd-agent does not work with powershell.exe

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#3420]
##### Issue Type

- Bug Report

##### Summary

The silent installation of windows gocd agent as detailed by [this](https://docs.gocd.io/current/installation/install/agent/windows.html#silent-headless-installation) only works when using `cmd.exe` and not `powershell.exe`
###### Basic environment details

* Go Version: `17.4.0`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. Download the gocd agent windows installer
2. Open powershell
3. Run `go-agent-17.4.0-4888-setup.exe /S /SERVERURL="https://<go_server_ip>:<go_server_ssl_port>/go" `
4. 

##### Expected Results

GoCD Agent to start on windows with the go server url being `https://<go_server_ip>:<go_server_ssl_port>/go`

##### Actual Results

Error in the go-agent-bootstrapper-wrapper.log

##### Log snippets

```
INFO   | jvm 1    | 2017/04/22 19:25:13 | logFile Environment Variable= null
INFO   | jvm 1    | 2017/04/22 19:25:13 | Logging to go-agent-bootstrapper.log
INFO   | jvm 1    | 2017/04/22 19:25:13 | -serverUrl must end with '/go' (https://localhost:8154/go)
INFO   | jvm 1    | 2017/04/22 19:25:13 | Usage: java -jar agent-bootstrapper.jar [options]
```

**Comment by joel74** [comment]
I repro'd a similar, probably related issue. When installing both the 17.3 and 17.4 agents with PowerShell, I found that including forward slashes (/) in the /SERVERURL parameter caused all values after the forward slash to be dropped from the %GO_SERVER_URL% environment variable. I.e. 

(.exe) /S /SERVERURL="https://go2.atlas.cm.com/go" /GO_AGENT_JAVA_HOME="C:\Progra~1\Java\jre1.8.0_121" /D="E:\GoAgent"

produced a %GO_SERVER_URL% environment variable with the value https:

Changing SERVERURL to "https:\\go2.atlas.cm.com/go" for testing purposes
produced a %GO_SERVER_URL% environment variable with the value https:\\go2.atlas.cm.com

It's like the installer isn't honoring the fact that it's in quotes and is treating forward slashes as a special character.

**Comment by varshavaradarajan** [comment]
Closing as a duplicate of https://github.com/gocd/gocd/issues/3527
