### ISSUE TITLE
Previous pipeline runs with failing stage is not shown on dashboard

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3428]
##### Issue Type

- Bug Report

##### Summary

For pipelines with multiple stages, the dashboard shows the latest instance of pipeline and all the previous pipeline instances which has Stage with the state ```Building```. 

However if a previous pipeline run has a stage which is still running but with a state ```Failing``` this pipeline does not show up on the dashboard.  This leads to incomplete information on the dashboard and leads to confusion.

**Comment by GaneshSPatil** [comment]
@maheshp -- is it still the case, with the new dashboard, I can see both `building` as well as `failing` stages from different pipeline instances.
Here is the screenshot for the same:
<img width="1391" alt="screen shot 2018-10-26 at 12 00 45 pm" src="https://user-images.githubusercontent.com/15275847/47548523-fc49c100-d916-11e8-9e93-bb0fe3614dd7.png">

**Comment by GaneshSPatil** [comment]
Fixed as part of the new dashboard, introduced in GoCD release `v18.3.0`
