### ISSUE TITLE
Updating env variables and parameters via a task in a job

### ISSUE THREAD

**Issue by hawky93** [gocd/gocd#3429]
In GOCD we are able to define env variables and parameters for the entire pipeline, stage and individual jobs. Is it possible to update those already defined env variables and parameters via a task in a job when running the pipeline?

**Comment by varshavaradarajan** [comment]
@hawky93 , can you specify your use case? I am not sure why you would want to update the env vars after triggering a pipeline with some values for env vars.

**Comment by EbenZhang** [comment]
@varshavaradarajan  How do you guys usually pass the parameters to stages?
Will the ability to change variable value be useful to provide input for tasks in next stages?
