### ISSUE TITLE
Pipelines page hanging frequently in Chrome browser with 400+ pipelines

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#3431]
##### Issue Type

- Bug Report

##### Summary

On the pipelines page - if you have a very high number of pipelines - the browser tab very frequently hangs while it consumes large amounts of cpu.

##### Environment

https://gist.github.com/JorritSalverda/2bf6d2815176b84c9ef6214cdf3da6b6

###### Basic environment details

* Go Version: `17.3.0`
* JAVA Version: `1.8.0_121`
* OS: `Linux 4.4.21+`
* Browser vendor and version (if relevant): `Google Chrome 57.0.2987.133 on Windows 7 Professional`

##### Steps to Reproduce

We're running multiple go.cd servers, but this one has the most number of pipelines, **417** in total.

1. Load the pipelines page with this many pipelines all visible
2. Open a couple of pipeline edit screens in separate tabs
3. Look at the Chrome Task Manager and see the load for those tabs combined go up to the max percentage for a single core (25% on a quad core).

##### Expected Results
The interface to stay responsive.

##### Actual Results
The interface locks up for dozens of seconds until you can interact with it again.

##### Any other info
Profiling the pipelines page with the Chrome profiler shows when it hangs it spends the most time on loading `/go/pipelines.json` as can be seen in the attached screenshot.

![gocd-17 3 0-chrome-hangs-issue](https://cloud.githubusercontent.com/assets/136472/25441110/a167367a-2aa1-11e7-95d1-0981b015d085.png)

The loading of the pipelines.json doesn't seem to take into account either whether you filtered the visible pipelines with the _Search for pipeline_ field. It always loads the full _pipelines.json_.

The profile file itself is 580MB large, but I can provide it to anyone looking into this issue if needed.

**Comment by JorritSalverda** [comment]
The purple _Recalculate style_ at the bottom has a warning linking to https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing#avoid-forced-synchronous-layouts

**Comment by GaneshSPatil** [comment]
@JorritSalverda -- The dashboard pipelines performance problem has been fixed as part of new dashboard implementation, introduced as part of GoCD v18.3.0.

Closing this issue, marking as fixed.

Please reopen the issue if you're facing the performance problem with the new pipelines dashboard.
