### ISSUE TITLE
Investigate compatibility with TFS 2017

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3434]
TFS 2017 was released a couple of months ago, and while we tested with visualstudio.com (assuming that it ran with newer TFS), we'd need to investigate whether we support TFS 2017 and build support for it, in case it is not.

See this comment for possible issue and workarounds for TFS TEE and TFS 2017 - https://github.com/Microsoft/team-explorer-everywhere/issues/160#issuecomment-284342439

**Comment by arvindsv** [comment]
Closing in favor of #3726.
