### ISSUE TITLE
How to secure password providing on git material?

### ISSUE THREAD

**Issue by nitink85** [gocd/gocd#3435]
##### Issue Type

- Feature proposal

##### Steps to Reproduce

Add a git material in a new or existing pipeline.
Provide the username, password and url of git repository.

##### Ask
How to protect/secure git password here?

##### Expected Results
We should able to protect Git material password from everyone. Even if someone has access to see the configuration using Go dashboard, they won't able to see password.

##### Actual Results
Current Git material passwords are not secured

**Comment by zabil** [comment]
Closing this in favor of cleaner implementation via #1696

**Comment by RameshBahavathi** [comment]
is it resolved in the latest gocd version ?
Please confirm for the latest solution to secure password providing on git material
