### ISSUE TITLE
Go on Kubernetes: Automatically remove missing agents

### ISSUE THREAD

**Issue by schlomo** [gocd/gocd#3446]
##### Issue Type

- Feature proposal

##### Summary

Automatically remove missing agents

##### Environment

Running Go on [Kubenertes](kubernetes.io), agents are deployed as a [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/). When we update the agent then the old agents are left as *Missing* agents in Go.

Go 17.4 on Ubuntu with JDK 8.

###### Goal

As missing agents are normal in this situation it would be nice if Go could automatically remove such agents after some time.

**Comment by ketan** [comment]
Closing as dup of #3264
