### ISSUE TITLE
Go on Kubernetes: Elastic agent plugin

### ISSUE THREAD

**Issue by schlomo** [gocd/gocd#3447]
##### Issue Type

- Feature proposal

##### Summary

Provide an elastic agents plugin for Kubernetes

##### Environment

Running Go on [Kubenertes](kubernetes.io), agents are currently deployed as a [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/). The amount of agents that are running is set in the Deployment as `replicas` parameter. We currently manually adjust the amount of agents.

Go 17.4 on Ubuntu with JDK 8.

###### Goal

* Go should automatically start and stop agents on Kubernetes as needed
* It should be able to easily update the underlying Kubernetes artifacts, e.g. Deployment, ReplicaSet ... For example use a label to find the "right" artifact.
* Use Kubernetes credentials injected into the server when running the server on Kubernetes - no static credentials should be required.

**Comment by GaneshSPatil** [comment]
@schlomo -- GoCD has a [Kubernetes elastic agent plugin](https://github.com/gocd/kubernetes-elastic-agents) which provides running GoCD agents in a kubernetes cluster.

From the proposed goals, Kubernetes elastic agent plugin is currently able to:
* start and stop agents on Kubernetes as needed.
* Use Kubernetes credentials injected into the server as part of the plugin settings. (**note**: GoCD server needn't be running on same kubernetes cluster, it can run anywhere, i.e. same/another kuberenetes cluster or bare metal).


For GoCD agent to operate on kubernetes resources  (such as pod, deployment, etc.) requires kubernetes cluster access using credentials. Currently, there isn't a way to pass along creds from server to an agent running inside kubernetes cluster.  One needs to create a [kubernetes secret](https://kubernetes.io/docs/concepts/configuration/secret) and use PV while defining a [GoCD kubernetes elastic agent profile](https://github.com/gocd/kubernetes-elastic-agents/blob/master/install.md#create-an-elastic-profile) which allows GoCD agents to have control over the running kubernetes cluster.

Also, there is work going on to simplify GoCD deployment on kubernetes using a [GoCD Helm Chart](https://github.com/kubernetes/charts/pull/2632)

**Comment by varshavaradarajan** [comment]
Closing this issue. Please raise feature requests and provide feedback on https://github.com/gocd/kubernetes-elastic-agents.
