### ISSUE TITLE
Ru with options doesn't fetch latest versions of materials

### ISSUE THREAD

**Issue by hydra-gce** [gocd/gocd#3449]
##### Issue Type
- Feature enhancement

##### Summary
When triggering a pipeline with options, Go doesn't try to fetch the latest versions of the materials you don't explicitly select a version to use, instead, it seems to use the versions it used the last time the pipeline was triggered.

This is a problem because trigger with options is the only way users have to change environment variables, which in turn are the mechanism to tune the behaviour of the pipeline. Most of our main pipelines have more than 15 materials, and even if we wanted to go one by one setting the latest version for each of them, Go doesn't show the pop-up with the last 5 versions when the number of materials exceeds a certain number.
It would be desirable to have the option to trigger a pipeline with the latest version of its materials and having the chance to change its environment variables.

**Comment by varshavaradarajan** [comment]
@hydra-gce , are you sure that the "poll for new changes" option is enabled on the material?

**Comment by hydra-gce** [comment]
Hi @varshavaradarajan, 

Thanks for your response.
Yes, I'm certain the "poll for new changes" option is enabled for every material (of many) the pipeline has configured. And it also seems enabled because when the run with options pop-up window shows up, new versions of the materials appear in the corresponding lists, ready to be selected. 

The problem is that if the user doesn't select those new available versions of the materials manually, Go uses the version it shows in the "Last run with:" field, that's what çi've seen testing several times this behaviour.  Apparently, the only way to make Go use the *latest* versions of the materials is running the pipeline straight without options .

Does it make sense to you?


Arturo.

**Comment by abelboldu** [comment]
I can confirm this issue.

This is a problem because users are supposed to enter a variable to deploy a given tag, but they may forget to select last revision of the drop down material list.

I think the manual trigger should also select last revision of the materials by default. @varshavaradarajan

**Comment by hydra-gce** [comment]
Hello @varshavaradarajan,

Any chance this issue/problem could be scheduled anytime soon? What do you reckon?

Thanks

Arturo.

**Comment by varshavaradarajan** [comment]
@hydra-gce, 

I agree that there are cases the trigger with options showing the latest revision to run with (instead of the last revision that it ran with) makes sense. Especially when you would want to just change an environment variable before triggering. However, this issue is not in priority at this moment. But if you want to send a PR for it, please do. And if anyone else have a problem with this change in behaviour, they'll comment on it.

**Comment by craig-duffin** [comment]
This is causing a big problem for us as well. What's the reason for using the revision of the last pipeline run instead of the latest version as the default?
It especially does not make sense considering if I trigger the pipeline without options, the latest is in fact used. The behaviour should be consistent across both methods of triggering.

**Comment by craig-duffin** [comment]
@varshavaradarajan 
Is there any plan to make this behaviour configurable?

**Comment by varshavaradarajan** [comment]
@craig-duffin - yes, the pipeline schedule API now accepts a flag `update_materials_before_scheduling` to perform MDU when triggered with options - https://api.gocd.org/current/#scheduling-pipelines. This flag helps GoCD find out if there are newer revisions (latest) for which to trigger the pipeline instance. See https://github.com/gocd/gocd/issues/4319 and https://github.com/gocd/gocd/issues/4273 for details on the behaviour. Currently, this is unsupported in the UI. PRs and ideas are welcome to use the schedule API's flag in the UI. 

cc @arvindsv 

P.S: Can someone please update the api doc to explain what `update_materials_before_scheduling` does in various cases like multiple materials, default value, etc?

**Comment by arvindsv** [comment]
@varshavaradarajan I'll do it. Just need to go back and think about the different cases ... :)

**Comment by craig-duffin** [comment]
@varshavaradarajan  @arvindsv 
I'm happy to try and work on this feature. How would you envisage a configurable option like this working? 
Would you view a system wide option to set the behaviour of retrieving revisions "Trigger of options" as being acceptable? Or would this be something which would make more sense to be set on a per pipeline/per material basis?

**Comment by arvindsv** [comment]
@craig-duffin If this is during "Trigger with options", wouldn't it be a checkbox in the "Trigger with options" modal? Specific to that run is what I was thinking. Is that wrong?
