### ISSUE TITLE
No builds triggered when using Whitelist

### ISSUE THREAD

**Issue by fatmanmclone90** [gocd/gocd#3451]
##### Issue Type

Bug Report

##### Summary

When using a whitelist on a GIT material, no builds are triggered when changes are checked into the repository.

##### Environment

``` "Version": "17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45)"

###### Basic environment details

Go Server Version:	17.2.0 (4587-442a7d67087844e44a2dcf5824164e1dfe00cc45)
JVM version:	1.8.0_121
OS Information:	Linux 3.13.0-74-generic
Usable space in artifacts repository:	19 GB
Database schema version:	1702001

##### Steps to Reproduce

1. Pipeline using an inverted Blacklist (aka Whitelist) as
```
    <materials>
        <git url="https://blah@bitbucket.org/company/repo.git" invertFilter="true">
          <filter>
            <ignore pattern="**/Folder.Web/**" />
            <ignore pattern="**/Folder.Web.Test/**" />
            <ignore pattern="Source/Folder.Web/**" />
            <ignore pattern="Source/Folder.Web.Test/**" />
             <ignore pattern="Source/Folder.Web/" />
            <ignore pattern="Source/Folder.Web.Test/" />
          </filter>
        </git>
      </materials>

```
2. Check-in changes to files under folder Folder.Web and/or Folder.Web.Test

I've tried all possible combinations of wildcards that I could think of, hence the duplication in patterns.

##### Expected Results
Triggers pipeline

##### Actual Results
No builds are ever triggered

##### Any other info
When checked out the repository has the specified folder structure of ./Source/Folder.Web and ./Source/Folder.Web.Test.

Each of these folders has further sub-directories and files.

**Comment by ankitsri11** [comment]
Hi there - Can you try with below pattern and then try to commit a file under folder Folder.Web and/or Folder.Web.Test. I believe GoCD treats '**' as a folder/path and '*" for files.

You can refer [this link](https://docs.gocd.org/current/configuration/configuration_reference.html#ignore) for the ignore pattern reference.

```
<materials>
    <git url="https://blah@bitbucket.org/company/repo.git" invertFilter="true">
      <filter>
        <ignore pattern="**/Folder.Web/*" />
        <ignore pattern="**/Folder.Web.Test/*" />
        <ignore pattern="Source/Folder.Web/*" />
        <ignore pattern="Source/Folder.Web.Test/*" />
         <ignore pattern="Source/Folder.Web/" />
        <ignore pattern="Source/Folder.Web.Test/" />
      </filter>
    </git>
  </materials>
```

**Comment by fatmanmclone90** [comment]
Thanks @ankitsri11 

Using your reference I found a combination that worked.

  ```
<materials>
        <git url="https://blah@bitbucket.org/company/repo.git" invertFilter="true">
          <filter>
            <ignore pattern="**/Folder.Web/*" />
            <ignore pattern="**/Folder.Web/**" />
            <ignore pattern="**/Folder.Web.Test/*" />
            <ignore pattern="**/Folder.Web.Test/**" />
          </filter>
        </git>
      </materials>
```
