### ISSUE TITLE
Unable to connect to private github repo after upgrading to version 17.4

### ISSUE THREAD

**Issue by maknahar** [gocd/gocd#3457]
##### Issue Type
- Bug Report

##### Summary
Go server is not able to connect my github repo. Server has proper ssh keys set on the server at location /var/go/.ssh/ . I am able to run the command on server over ssh which are failing on CI.

Output when I click on check connection
Error performing command: --- Command ---
git ls-remote git@github.com:RealImage/jt-payments.git refs/heads/staging
--- Environment ---
{GIT_ALLOW_PROTOCOL=http:https:ssh:git:file:rsync}
--- INPUT ----

--OUTPUT ---

--- ERROR ---
STDERR: Host key verification failed.
STDERR: fatal: Could not read from remote repository.
STDERR: 
STDERR: Please make sure you have the correct access rights
STDERR: and the repository exists.
---

##### Environment
```
Version: "17.4.0 (4892-ab17b819e73477a47401744fa64f64fda55c26e8)"
Config file locations: {
loc.config.dir: "/etc/go",
loc.log.root.0: "/var/log/go-server",
loc.log.basename.0: "go-server.log",
loc.log.root.1: "/var/log/go-server",
loc.log.basename.1: "go-shine.log"
},
OS Information: {
OS Name: "Linux",
OS Version: "3.14.42-31.38.amzn1.x86_64",
System Architecture: "amd64",
Available Processors: 2,
Average System Load: 0.01
},
```

**Comment by arvindsv** [comment]
> I am able to run the command on server over ssh which are failing on CI

I don't think there should be any difference between those versions. Are you able to run that command on the server *as the go user*? Assuming the server is running under the "go" user, of course.

**Comment by maknahar** [comment]
As it turn out, There was an issue in file permission in /var/go/.ssh/ file were owned by root instead of user go.

Generating the news ssh keys in the client as user go resolved the issue.

**Comment by rahulgupta20d** [comment]
I am unable to connect jenkins with Git repo (private) using ssh key. showing below error
Failed to connect to repository : Command "git ls-remote -h git@git.corp.xxxx/name.git HEAD" returned status code 128:
stdout:
stderr: fatal: cannot exec '/tmp/jenkins-gitclient-ssh8472673677931395997.sh-copy': Permission denied
fatal: unable to fork
