### ISSUE TITLE
Unable to manually schedule a pipeline

### ISSUE THREAD

**Issue by dforste** [gocd/gocd#3459]
Pipeline is scheduled manually and does not proceed. Can we improve logging to show why? 

Output from the Status API shows: 
```
{
  "pausedCause":"",
  "pausedBy":"",
  "paused":false,
  "schedulable":false,
  "locked":false
}
```
A request to the schedule api returns: 
```
Failed to trigger pipeline: PaymentServiceTrunkBuild { Pipeline already triggered }
```
No runs of it appear to be in process with nothing logged saying why it was not triggered. 

When I went to the support section for creating this issue I see this: 
```
      {
        "message": "Material update for https://gitlab.example.net/service.git hung:",
        "detail": "Material update is currently running but has not shown any activity in the last 3009 minute(s). This may be hung. Details - URL: https://gitlab.example.net/service.git, Branch: master",
        "level": "WARNING"
      },
```
Maybe changing this from warning to error would be a good start so that it is shown in the UI as well.

**Comment by arvindsv** [comment]
That warning should show in the bottom right in a little red box which says something like: "Errors and warnings".

The ideal approach would be to show this against the pipeline and I believe an upcoming rewrite of the dashboard might make that happen. So, I'll close this - while agreeing with you that it should show why it is not triggering in a better way. Thanks!
