### ISSUE TITLE
Stage shows up as passed even when the job failed

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#3464]
##### Issue Type
- Bug Report

##### Summary

Stage is showing up as passed when one of the jobs inside it fails.  Basically, the stage failed, but rerun of the job fixed the build. While looking at job instance 1, the stage status should show up as failed and only the second run should show up as passed, but both the runs show up as passed. That seems wrong.

##### Environment
go05

https://go05.thoughtworks.com/go/pipelines/peg-gocd-in-enterprise/138034/defaultStage/1 (Run 1 should show as failure)
https://go05.thoughtworks.com/go/pipelines/peg-gocd-in-enterprise/138034/defaultStage/2 (Run  2 passed)

**Comment by ketan** [comment]
Reproducible on `16.7.0` as well. I took a current DB dump and applied the following SQL to rollback to a schema that's compatible with 16.7.0.

```sql
ALTER TABLE pipelines ADD locked BOOLEAN DEFAULT false NOT NULL;

```
