### ISSUE TITLE
Change duration format

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3472]
##### Issue Type

- Feature enhancement

##### Summary

Currently, GoCD formats durations using `hh:mm:ss` format in most places. This is done using the [`fromSecondsToHHMMSS`](https://github.com/gocd/gocd/blob/3bf6e2d6a7a0710abc28ea2859fd22e5240d247c/server/webapp/WEB-INF/rails.new/app/assets/javascripts/time_converter.js#L18) helper method.

We now have an [improved duration formatter](https://github.com/gocd/gocd/blob/3bf6e2d6a7a0710abc28ea2859fd22e5240d247c/server/webapp/WEB-INF/rails.new/spec/javascripts/human_readable_duration_spec.js) that can be used instead.

**Comment by rajiesh** [comment]
Verified on 17.5.0 (5094-facde1c814310d1f9c463c8945c5145a994d0f39)
