### ISSUE TITLE
Filter error messages and warnings based on pipeline access

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3477]
##### Issue Type
- Feature enhancement

##### Summary

Currently the Errors and Warnings messages lists messages across all pipelines irrespective of whether a given user has access to the said pipeline or not. 

Even though sensitive information is masked users get to view information about pipelines they are not authorized to and also showing this extra information might be confusing to users. 

Ideally, users should see errors and warnings only for pipelines they have access to.

**Comment by aamattos** [comment]
Hi, any update on this issue ? 
When you have lot of teams working with different levels of access, this can be very confusing.

**Comment by arvindsv** [comment]
@aamattos No update at this time. I understand it's useful, but it's not being worked on right now. There are some challenges we'd need to figure out when this is picked up. For instance, not all messages are scoped at the pipeline level and there could be caching and performance implications. Anyway, this issue will be updated if it is picked up.
