### ISSUE TITLE
Option to make the plugin/GoCD role into super admin

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3479]
##### Issue Type

- Feature enhancement

##### Summary

Currently, from the role configuration SPA page user can create GoCD and plugin roles but in order to provide super admin (GoCD system administration) access user needs to make an update in cruise-config.xml.

Below entry needs to be added to add role to admin tag:

```
      <admins>
        <user>user</user>
        <role>go-role</role>
      </admins>
```

Above can be avoided by providing an option under role config SPA.

**Comment by arvindsv** [comment]
@GaneshSPatil Do any of the changes happening now around users and roles allow this?

**Comment by arvindsv** [comment]
Closing as stale.
