### ISSUE TITLE
Error message doesn't go away when auth config attribute is updated

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3481]
##### Issue Type

- Defect
 
##### Summary

Updating any attribute in auth config page doesn't make the associated error message go away.

![error](https://cloud.githubusercontent.com/assets/6838313/25885537/8ea3d040-3576-11e7-9904-d11819c27518.gif)

###### Basic environment details

* Go Version: 17.5.0 (4969-3714bf330aa7bffdf26b46d83b56b997eb813d12)

##### Expected Results

It should not show the message once the attribute is updated with the correct value.

**Comment by bdpiparva** [comment]
Fixed in PR #3500.

**Comment by rajiesh** [comment]
Verified on 17.5.0 (5094-facde1c814310d1f9c463c8945c5145a994d0f39).
