### ISSUE TITLE
GoCD role icon image broken under role configuration page

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3498]
##### Issue Type

- Defect

##### Summary

![screen shot 2017-05-12 at 14 38 30](https://cloud.githubusercontent.com/assets/6838313/25991486/ee276490-3720-11e7-9f71-eccd2ffe3fb9.png)

###### Basic environment details

* Go Version: 17.5.0 (4980-3bf6e2d6a7a0710abc28ea2859fd22e5240d247c).

**Comment by bdpiparva** [comment]
Fixed in PR #3504

**Comment by ankitsri11** [comment]
Verified on  Go Version: 17.5.0 (5094-facde1c814310d1f9c463c8945c5145a994d0f39).
