### ISSUE TITLE
Remove user functionality broken under role configuration

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3499]
##### Issue Type

- Bug Report

##### Summary

Remove user functionality broken under role configuration. All users gets removed while removing one user from GoCD role.

![remove_user](https://cloud.githubusercontent.com/assets/6838313/25991594/6429a04a-3721-11e7-9a2c-e05a9b4cd6eb.gif)

###### Basic environment details

* Go Version:  Go Version: 17.5.0 (4980-3bf6e2d6a7a0710abc28ea2859fd22e5240d247c)

##### Expected Results
It should only remove the selected user not the others.

**Comment by bdpiparva** [comment]
PR #3494 will fix the issue.

**Comment by ankitsri11** [comment]
Verified on  Go Version: 17.5.0 (5094-facde1c814310d1f9c463c8945c5145a994d0f39).
