### ISSUE TITLE
Misleading message after deleting role

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3501]
##### Issue Type

- Defect

##### Summary

While deleting a role from role config SPA, user gets a misleading message saying "You are not authorized to perform this action" and the role gets deleted.

![del_role](https://cloud.githubusercontent.com/assets/6838313/25993928/6cd88622-3729-11e7-801a-920164bf5c44.gif)

###### Basic environment details

* Go Version: 17.5.0 (4980-3bf6e2d6a7a0710abc28ea2859fd22e5240d247c)

##### Steps to Reproduce

1. Create a role (GoCD or plugin role) from role config SPA
2. Add a user if it is a GoCD role
3. Add this role under admin tag of cruise-config.xml
4. Login with that user (which is part of that role) and delete the role

##### Expected Results
User should get logged out and should not see that message

**Comment by GaneshSPatil** [comment]
Fixed as part of the new Server Roles SPA.
Closing...
