### ISSUE TITLE
Any change to auth config doesn't logout associated users

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3502]
##### Issue Type

- Defect

##### Summary

Any change made to auth config doesn't logout user like it does for cruise-config.xml changes. User still has admin/operate permission even there is a change and can trigger/change pipeline configuration.

###### Basic environment details

* Go Version: 17.5.0 (4980-3bf6e2d6a7a0710abc28ea2859fd22e5240d247c)

##### Expected Results
User should get logged out.

**Comment by bdpiparva** [comment]
Fixed in #3512

**Comment by ankitsri11** [comment]
Verified on Go Version: 17.5.0 (5094-facde1c814310d1f9c463c8945c5145a994d0f39).
