### ISSUE TITLE
Please fix the silent installation on Windows

### ISSUE THREAD

**Issue by joel74** [gocd/gocd#3527]
##### Issue Type

- Bug Report

##### Summary

When specifying the SERVERURL parameter in a silent install on Windows, the installation truncates the value at the forward slash. Hence the environment variable GO_SERVER_URL is never correctly set.

###### Basic environment details

* Go Version: 17.3 / 17.4 ...
* JAVA Version: JRE 8.0.121
* OS: Windows Server 2012 r2

##### Steps to Reproduce
Execute:
& e:\_ops\install\go\go-agent-17.4.0-4892-jre-64bit-setup.exe /S /SERVERURL="https://go2.atlas.cm.com/go" /GO_AGENT_JAVA_HOME="C:\Program Files\Java\jre1.8.0_121" /D=E:\GoAgent

##### Expected Results
The Go_Server_URL variable is set correctly.

##### Actual Results
The Go_Server_URL variable is truncated at the forward slash.

**Comment by varshavaradarajan** [comment]
@joel74 , can you try doing the following in powershell - 
``.\go-agent-{version}-setup.exe /S /SERVERURL=`"https://ip:port/go`" /D=E:\GoAgent``

Note the backticks in SERVERURL and the order of the command line arguments should be the same (don't know why but giving /D before /SERVERURL results in the go agent working directory being ``<value_you_specified> SERVERURL=https:ip:portgo``

**Comment by joel74** [comment]
Thanks, @varshavaradarajan, I'll try that.

**Comment by varshavaradarajan** [comment]
Closing this, please reopen it if you face any issues while trying the silent installation on windows.

**Comment by joel74** [comment]
I'm not sure I have permissions to re-open but I'm still experiencing a problem with this. If I use backticks, it messes up other parameters. If the GO_SERVER_URL param is not the last passed in, the value of that environment variable is set to the url plus everything after it in the command as the value. If I make it the last param in the command, the target directory value gets messed up and isn't just E:\GoAgent. Even if I wrap the backticked quotes in other quotes, i.e. /SERVERURL="`"https://go2.atlas.cm.com/go`"" I experience the same problem. I think this might be an issue with how PowerShell encodes things. I don't think the same thing occurs with backticks in a DOS shell

**Comment by varshavaradarajan** [comment]
@joel74 , what do you mean by messes up other parameters? Can you please paste the exact commands (and the resultant GO_SERVER_URL and AGENT_WORK_DIR)  that you are trying to run using powershell? 

You will find the values set for GO_SERVER_URL and AGENT_WORK_DIR in wrapper.log in the agent installation directory.

**Comment by joel74** [comment]
@varshavaradarajan  ,
If I execute this: 
```
& e:\_ops\install\go\go-agent-17.4.0-4892-jre-64bit-setup.exe /S /SERVERURL=`"https://go2.atlas.cm.com/go`" /GO_AGENT_JAVA_HOME="C:\Program Files\Java\jre1.8.0_121" /D=E:\GoAgent
```

the value of the GO_SERVER_URL is set to:
```
https://go2.atlas.cm.com/go" "/GO_AGENT_JAVA_HOME=C:\Program Files\Java\jre1.8.0_121
```

If I execute either this: 

```
& e:\_ops\install\go\go-agent-17.4.0-4892-jre-64bit-setup.exe /S /GO_AGENT_JAVA_HOME="C:\Program Files\Java\jre1.8.0_121" /D=E:\GoAgent /SERVERURL=`"https://go2.atlas.cm.com/go`"     
```

or 
```
& e:\_ops\install\go\go-agent-17.4.0-4892-jre-64bit-setup.exe /S /GO_AGENT_JAVA_HOME="C:\Program Files\Java\jre1.8.0_121" /D=E:\GoAgent /SERVERURL="`"https://go2.atlas.cm.com/go`""
```


The Go agent is installed in 
```
E:\GoAgent SERVERURL=httpsgo2.atlas.cm.comgo
```


The wrapper.log file is complaining:
`Unable to write to the configured log directory: logs (The system cannot find the path specified. (0x3))`

Thanks,
Joel

**Comment by varshavaradarajan** [comment]
@joel74 ,

> If I execute this:
```
& e:\_ops\install\go\go-agent-17.4.0-4892-jre-64bit-setup.exe /S /SERVERURL=`"https://go2.atlas.cm.com/go`" /GO_AGENT_JAVA_HOME="C:\Program Files\Java\jre1.8.0_121" /D=E:\GoAgent
```

The /GO_AGENT_JAVA_HOME's value is also surrounded by quotes that you need to escape with  backticks `` ` ``  , or do not have quotes at all for /GO_AGENT_JAVA_HOME (if you don't have spaces in the value), like this:

```
& e:\_ops\install\go\go-agent-17.4.0-4892-jre-64bit-setup.exe /S /SERVERURL=`"https://go2.atlas.cm.com/go`" /GO_AGENT_JAVA_HOME=`"C:\Program Files\Java\jre1.8.0_121`" /D=E:\GoAgent
```

**Comment by joel74** [comment]
Verified. If I backtick the other param with quotes as well, it works for me. Thanks for your help, and for updating the docs! Maybe your merge request should cover all params that require quotes. 

Cheers,
Joel
