### ISSUE TITLE
Progress indicator for save of job config

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#353]
Pointed out by Vipul.

I was trying to modify the resources under job settings and clicking the save button seemed non-responsive. I tried in Chrome, Firefox and Safari and had the same experience. I just didn't get the feedback from Go weather its still making the change, loading something etc. If I tried to navigate away from the page, it said there are unsaved changes but never indicated that it's doing something and I should wait for that to finish.

A wait indicator/spinner might help to know if a save is in progress or if the screen is frozen.

**Comment by arvindsv** [comment]
@maheshp: Please close once the [new config UI](https://github.com/gocd/gocd/issues/1404) is done. Thanks!

**Comment by arvindsv** [comment]
Closing as stale.
