### ISSUE TITLE
Role config SPA has display issue on IE11

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#3532]
##### Issue Type

- Bug Report

##### Summary

Role config SPA shows up as in this gif on IE 11 browser in Windows 8/10 machine

![ie11-editroleconfigpage](https://cloud.githubusercontent.com/assets/6533924/26203194/eb5a96de-3bf7-11e7-8cc6-fdf6c19f6bdc.gif)

Discussed with @bdpiparva and tried on different machines - whats observed is that the issue exists on Windows 8/10 IE11 , but not on Windows 7 IE11

Not sure about whats causing this issue, keeping this issue open for investigation

**Comment by GaneshSPatil** [comment]
IE11 and older versions of IE are not supported by GoCD.
Closing this issue as `WONT-FIX`
