### ISSUE TITLE
ManagerDN field need not have to be mandatory for LDAP auth plugins

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#3538]
##### Issue Type

- Bug Report

##### Summary

ManagerDN field on LDAP auth plugins is currently mandatory. This was not the behavior in the inbuilt LDAP configuration. Also OpenLDAP allows authentication without ManagerDN, so should maintain the same behavior

###### Expected Behavior

As per the current LDAP configuration - ManagerDN should not mandatory field, Manager Password field is mandatory only when ManagerDN is provided

###### Basic environment details

* Go Version: `17.5.0 (5053-c8660def29487a9722395b9ba42179af65e24c62)`

**Comment by maheshp** [comment]
This needs a plugin change and its fixed as part of https://github.com/gocd/gocd-ldap-authentication-plugin/pull/18

**Comment by rajiesh** [comment]
Verified on 17.5.0 (5094-facde1c814310d1f9c463c8945c5145a994d0f39)
