### ISSUE TITLE
Message on Role Config SPA page could be better worded to communicate the intent

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#3539]
##### Issue Type

- Bug Report

##### Summary

Currently users see this message by default on Role configuration SPA page, until install a authorization plugin. However this message is bit confusing as it does not appropriately convey the message.

<img width="543" alt="screen shot 2017-05-23 at 12 15 14 pm" src="https://cloud.githubusercontent.com/assets/6533924/26341746/dcd65b66-3fb2-11e7-8132-610865dbec17.png">

When user clicks `Add Role` the config page shows 2 options - GoCD Role/ Plugins Role. `Plugins Role` will be disabled on GoCD server which do not have Authorization plugin installed. However the message in the image above do not clearly convey that message. 

Suggestion for the message is `Please checkout the Authorization plugins(link). Plugins Role will be enabled only if Authorization plugins are enabled`

###### Basic environment details

* Go Version: `17.5.0 (5053-c8660def29487a9722395b9ba42179af65e24c62).`

**Comment by kritika-singh3** [comment]
The page was revamped in GoCD server 19.1.0 and now the message shown is `None of the installed plugin supports role based authorization.` which conveys the intent clearly. Closing this issue.
