### ISSUE TITLE
Enable (read-only) view of external pipelines

### ISSUE THREAD

**Issue by helmesjo** [gocd/gocd#3549]
##### Summary

It should be possible, in read-only mode, to view a pipeline regardless of it's origin. This is useful to verify that an external configuration repository has been setup correctly (more than just by the absence of errors), or if you don't even have access to the actual repository but want to understand what the pipeline does.

Something like this (currently there is nothing):

![tmp1](https://cloud.githubusercontent.com/assets/2501070/26464331/b05ba5d8-4187-11e7-862e-5d724a3f2efc.PNG)

**Comment by bizmate** [comment]
I am pretty sure that several people might be against this but what if you want to test pipeline changes where usually the configuration is held on a separate repository? Then you start committing changes for basic tests like "echo branch version to see if it is fetched right?". I would rather like to have the ability to run a volatile version of my pipeline than having to commit every single test. I am also in favour of your approach and I see this must be addresses in 17.4 based on https://github.com/gocd/gocd/issues/3064

**Comment by kritika-singh3** [comment]
This issue has been addressed in GoCD version [19.12.0](https://www.gocd.org/releases/#19-12-0). Closing this issue.
Please reopen if you find any bug/issue.
