### ISSUE TITLE
Git repo is always cloned (not fetched) on both server and agent machine

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#355]
Go should clone a given git repo for the first time and then perform a fetch operation thereafter. However, this is not the case if case of material url differs from that mentioned in /git/config file. GitMaterial.isRepositoryChanged return true if the result of "git config remote.origin.url" does not match the material url configured in Go. This comparison is currently case sensitive.

**Comment by worstadmin** [comment]
Bumping this

**Comment by arvindsv** [comment]
Closing as stale.
