### ISSUE TITLE
config using include

### ISSUE THREAD

**Issue by trinitro73** [gocd/gocd#3554]
##### Issue Type

- Bug Report
- Feature proposal
- Feature enhancement
- Documentation Report

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by arvindsv** [comment]
No info.
