### ISSUE TITLE
Updating environment variables that GoCD sets from outside?

### ISSUE THREAD

**Issue by ZukkyBaig** [gocd/gocd#3555]
##### Issue Type

- Question

##### Summary

This is more of a question, is it possible to set the environment variables that GoCD has in its "environment variables" tab for stages from the outside? I.e. a script which can update the values of the written environment variables? I am trying to automate a monotonous process of updating environment variables without manual intervention, this will aid in getting that done faster.

**Comment by zabil** [comment]
Check the documentation at
https://api.gocd.io/current/#update-an-environment
