### ISSUE TITLE
Pipeline 'move to' action only lists the first 9 groups

### ISSUE THREAD

**Issue by tpbrown** [gocd/gocd#3563]
##### Issue Type

- Bug Report

##### Summary

When using the GoCD UI to move a pipeline from one group to another the list of choices presented is only the first nine groups, not all.

##### Environment

GoCD 17.4.0 4892
Linux
Java8

**Comment by tpbrown** [comment]
additionally, this list isn't sorted -- it's the order listed in config XML :-(

**Comment by varshavaradarajan** [comment]
@tpbrown , you can scroll through the dropdown provided when you click on 'Move To'

**Comment by arvindsv** [comment]
Closing this. Can be reopened later, if we hear anything back.
