### ISSUE TITLE
Pipelines not positioned properly in pipeline group

### ISSUE THREAD

**Issue by thomaslloyd** [gocd/gocd#3565]
##### Issue Type
- Bug Report

##### Summary

- Pipelines not positioned properly in pipeline group
- When scrolling the pipelines jump around within the group

###### Basic environment details

* Go Version: `17.4.0`
* Browser vendor and version (if relevant): `Chrome v58 (and possibly others)`

##### Code snippets/Screenshots
![image](https://cloud.githubusercontent.com/assets/15194064/26677715/09b14060-46c5-11e7-9db5-54c3c3d86c93.png)

**Comment by GaneshSPatil** [comment]
This issue has been fixed as part of new dashboard introduce in GoCD `v18.3.0`
