### ISSUE TITLE
Support for Load Balancing

### ISSUE THREAD

**Issue by benzvan** [gocd/gocd#357]
Our Go instance is very slow. We have 300 enabled agents and 125 pending with 1400 pipelines and templates and 1.6T of artifact repository for 1 year of history. We are currently running on a 10-core machine with 8GB of RAM.

I see a lot of code in this repository referencing built-in load balancing functionality in the libraries, but my understanding is that allowing load balancing is not in the plan. So here's my story:

"As a system administrator, I want to run Go on multiple servers so that I have enterprise-level redundancy and processing power."

**Comment by srinivasupadhya** [comment]
It would be interesting to get see performance related data for the server. Can you please share `<go-server>/api/support` with us?

Also since you have 425 agents have you considered [dynamic agents](https://groups.google.com/d/topic/go-cd/LT3ZUEn_kRE/discussion)? Go should provide first-class support for it, some discussion [here](https://groups.google.com/d/topic/go-cd/WgSYU5OTGpk/discussion).

**Comment by benzvan** [comment]
Okay...that's thousands of lines of output. I pulled out the most performance-related of the data below. As far as setting up dynamic agents, that's an interesting idea, but I'm not sure reducing the number of agents would make anything faster and it certainly wouldn't make it more redundant.

=================
Config Statistics
=================

Valid Config.
Number of pipelines: 1109
Number of agents: 337
Number of environments: 56
Number of unique materials: 845
Number of schedulable materials: 806

=================
Go Server Version
=================

14.3.0(1186-65818fec82f654)

=================
Cache information
=================


Cache configuration information
-------------------------------
net.sf.ehcache.config.CacheConfiguration@29e913d1[
  name=cruise
  maxElementsInMemory=100000
  maxElementsOnDisk=0
  memoryStoreEvictionPolicy=LRU
  clearOnFlush=true
  eternal=true
  timeToIdleSeconds=120
  timeToLiveSeconds=120
  overflowToDisk=false
  diskPersistent=false
  diskStorePath=<null>
  diskSpoolBufferSizeMB=30
  diskAccessStripes=1
  diskExpiryThreadIntervalSeconds=120
  loggingEnabled=false
  cacheEventListenerConfigurations=[]
  cacheExtensionConfigurations=[]
  bootstrapCacheLoaderFactoryConfiguration=<null>
  cacheExceptionHandlerFactoryConfiguration=<null>
  terracottaConfiguration=<null>
  cacheWriterConfiguration=net.sf.ehcache.config.CacheWriterConfiguration@69224934
  cacheLoaderConfigurations=[]
  listeners=[net.sf.ehcache.store.MemoryStore@49f42ad8]
  frozen=false
  transactionalMode=OFF
  statistics=true
]

Cache runtime information
-------------------------
Statistics enabled? true
Average get time in milliseconds: 0.001271265 [Min: 0, Max: 48]
Cache size: 26894 (Accuracy: Best Effort)
Cache counts: [Hits: 825108850, Miss: 607933, Expired: 0, Eviction: 0, Put: 37484, Remove: 477858]

Cache size (in-memory): 26894
Cache hit count (in-memory): 825108850
Cache size (disk): 0
Cache hit count (disk): 0


==============
OS information
==============

Linux, amd64, 2.6.32-431.17.1.el6.x86_64, 10, 5.67

===================
Runtime information
===================

Name - 26844@prtwwb01
Uptime - 235128409 [About 65 hours, 18 minutes, 48 seconds]
Spec Name - Java Virtual Machine Specification
Spec Vendor - Oracle Corporation
Spec Version - 1.7

Input Arguments
---------------
  -> -Xms512m
  -> -Xmx4096m
  -> -XX:PermSize=128m
  -> -XX:MaxPermSize=256m
  -> -Dcruise.material.update.interval=120000
  -> -Duser.language=en
  -> -Dorg.mortbay.jetty.Request.maxFormContentSize=30000000
  -> -Djruby.rack.request.size.threshold.bytes=30000000
  -> -Duser.country=US
  -> -Dcruise.config.dir=/opt/thoughtworks/go-server/config
  -> -Dcruise.config.file=/opt/thoughtworks/go-server/config/cruise-config.xml
  -> -Dcruise.server.port=8153
  -> -Dcruise.server.ssl.port=8154

==============
GC information
==============

PS Scavenge [PS Eden Space, PS Survivor Space] 38722 : 1573684 (Count : Time)
PS MarkSweep [PS Eden Space, PS Survivor Space, PS Old Gen, PS Perm Gen] 930 : 586251 (Count : Time)


==================
Memory information
==================

Heap:
  init:      536870912
  used:      2044335256
  committed: 2607808512
  max:       3817865216

Non-Heap:
  init:      136773632
  used:      158161432
  committed: 175439872
  max:       318767104

Pending Finalization: 0


=======================
Memory pool information
=======================

Name: Code Cache, Type: Non-heap memory
  init:      2555904
  used:      40562176
  committed: 41222144
  max:       50331648

Name: PS Eden Space, Type: Heap memory
  init:      135266304
  used:      1167055432
  committed: 1358430208
  max:       1361051648

Name: PS Survivor Space, Type: Heap memory
  init:      22020096
  used:      20624704
  committed: 35127296
  max:       35127296

Name: PS Old Gen, Type: Heap memory
  init:      358088704
  used:      856655120
  committed: 1214251008
  max:       2863136768

Name: PS Perm Gen, Type: Non-heap memory
  init:      134217728
  used:      117600112
  committed: 134217728
  max:       268435456

**Comment by bf16574403** [comment]
Intrest!
