### ISSUE TITLE
"No authorization plugin installed" bubble in the roles view

### ISSUE THREAD

**Issue by d-led** [gocd/gocd#3572]
##### Issue Type

- Bug Report

##### Summary

the following message appears, even though the two bundled authorization plugins are there

![image](https://cloud.githubusercontent.com/assets/1716584/26817504/2d944830-4a97-11e7-8018-e15efbff74b1.png)

![image](https://cloud.githubusercontent.com/assets/1716584/26817535/4c6d5684-4a97-11e7-9441-ad6c3d95624b.png)

this doesn't disrupt anything, and authorization seems to work fine, but some people will probably be surprised to see it

###### Basic environment details

```plain
Go Server Version:	17.5.0 (5095-3130b5ba96f8155ae86fefb261a559d4c7493326)
JVM version:	1.8.0_131
OS Information:	Linux 4.4.0-78-generic
Usable space in artifacts repository:	.... GB
Database schema version:	1704003
```

###### Steps to reproduce

Go to `/go/admin/security/roles` after the 17.5 update

**Comment by maheshp** [comment]
@d-led the message `No Authorization Plugin installed` shows up if none of the installed authorization plugins have capability to [authorize](https://plugin-api.gocd.org/current/authorization/#get-plugin-capabilities). 

The bundled LDAP/AD and File based plugins do not have the capability to `authorize`   hence the message. I agree the message is misleading, which will be changed.

**Comment by d-led** [comment]
@maheshp ok! Thanks for the clarification. Indeed, a different message could reduce the surprise

**Comment by rajiesh** [comment]
@d-led there is [this](https://github.com/gocd/gocd/issues/3539) issue created to change the message. So closing this issue

**Comment by maheshp** [comment]
@d-led unlike the existing GoCD roles which is a group of users, the plugin provides an ability to add a pluginRole which maps to a role defined in an external authorization service. e.g  LDAP/AD group. This will help admins manage roles in a single location.

However, GoCD will continue to enforce authorization by restricting certain operations/resources to specific users and roles.
