### ISSUE TITLE
materials filter UI

### ISSUE THREAD

**Issue by bormotov** [gocd/gocd#3573]
##### Summary

current "Blacklist" not clean for usage

##### Environment

any

##### Actual Results

![2017-06-06_13-14-56](https://cloud.githubusercontent.com/assets/75397/26824481/3e2e6e0a-4aba-11e7-802b-43ab3f98ff04.png)

- section "Blacklist" in dialog
- single line for filters
- checkbox with long label

##### Possible Fix
- Name section "Filter"
- replace checkbox with radiobutton: two elements with labels "blacklist" and "whitelist"
- use multiline textbox, with one filter in row (like at other places, such command arguments)

for example fast-sketch

![2017-06-06_13-13-01](https://cloud.githubusercontent.com/assets/75397/26824403/f0623e2c-4ab9-11e7-92fc-4648959648fb.png)

add text with examples typical filters from [this link](https://docs.gocd.org/current/configuration/configuration_reference.html#ignore)  may help, or link for examples, at least

**Comment by arvindsv** [comment]
/cc @naveenbhaskar 

@bormotov - Thank you! I like this idea.

**Comment by naveenbhaskar** [comment]
Shall discuss this. Need context.

**Comment by fbarnard** [comment]
What about something like gitignore pattern then you can include and exclude or will that be a little difficult

**Comment by bormotov** [comment]
@fbarnard current patterns syntax (*, **)  same as gitignore

This issue only about UI.
now:
* we have one list of pattterns for filter
* list is used in two modes: blacklist or whitelist (exclude or include)
* in other places of GoCd UI for lists input used textbox

it is therefore proposed to bring UI into compliance with the current implementation and UX-uniformity
