### ISSUE TITLE
Avoid starting up gocd windows service by default

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3577]
##### Issue Type

- Feature enhancement

##### Summary

Currently installing the GoCD agent on windows will bring up the agent process, and create a guid.txt and possibly autoregister with the server (if the file is present).

This makes it very difficult to bake an AMI out of the windows instance with just the gocd agent and relevant configuration to bring up the instance later.

**Comment by rajiesh** [comment]
Verified on 17.6.0 (5142-be1ff52e07d80323fcc615864a64f3afe83b7016)
