### ISSUE TITLE
Stage duration seems incorrect

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3586]
##### Issue Type

- Bug Report

##### Summary

Duration shows up as `4:51` [here](https://build.gocd.org/go/pipelines/build-windows-PR/1499/build-server/2/jobs) when individual jobs took much longer.

Go Version: 17.6.0 (5110-e06f8526b4b3effa2604c96940256a928ff45137)

<img width="1101" alt="screen shot 2017-06-14 at 11 38 07 pm" src="https://user-images.githubusercontent.com/10598/27147456-7fd104d4-515a-11e7-848b-678466357fab.png">

**Comment by arvindsv** [comment]
I took a quick look. That's the duration for "Run 2 of 2" which is just a rerun of rspec-split-runInstance-2, which took 4m 31s.

If you go to ["Run 1 of 2"](https://build.gocd.org/go/pipelines/build-windows-PR/1499/build-server/2/jobs), you see that the duration is 24m 12s.

So, it is misleading but not wrong.

**Comment by arvindsv** [comment]
Closing as it's misleading but "intended" in a way.
