### ISSUE TITLE
Support colour schemes/themes

### ISSUE THREAD

**Issue by gunnarx** [gocd/gocd#3594]
##### Issue Type

- Feature proposal

##### Summary

Support colour schemes/themes.

##### Expected Results

Under Admin->Servier Configuration, provide a drop-down menu for a few predetermined colour themes.  Depending on the implementation method (e.g. a CSS file), possibly allow adding new choices to the installation which would also be provided as choices in the drop-down menu.

Preferrably the theme immediately takes effect without the need for a server restart (but even with a restart it is better than nothing).

The purpose is to easier distinguish between them, when interacting with multiple different Go.CD servers.

**Comment by creativie** [comment]
+1
