### ISSUE TITLE
GoCD 'clean working directory' error does not provide details.

### ISSUE THREAD

**Issue by gajwani** [gocd/gocd#360]
Occasionally on our agents, we see this error:

```
[go] Start to prepare TestPipeline/35/UnitTests/2/UnitTests on f333bb68-509d-46ed-b47f-9ba095b30774 [/data/gocd-agent] at Tue Jul 22 22:02:55 UTC 2014
Clean working directory is set to true. Unable to clean working directory for agent: /data/gocd-agent/pipelines/TestPipeline

[go] Job completed TestPipeline/35/UnitTests/2/UnitTests on f333bb68-509d-46ed-b47f-9ba095b30774 [/data/gocd-agent] at Tue Jul 22 22:02:57 UTC 2014
```

We want more information about the IOException that is happening internally. This information isn't being printed as part of the error message at [this line](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/remote/work/BuildWork.java#L281). 

There should really be more information, for example like this:

```
bomb("Clean working directory is set to true. Unable to clean working directory for agent:" + buildWorkingDirectory.getAbsolutePath() + ", with error " + e.getMessage());
```

Without that, we can't diagnose what is happening, other than that the pipeline cannot continue because it can't delete files.

/cc @mmb

**Comment by unkinected** [comment]
We're still experiencing this buy pretty regularly, on 19.12.0. It will randomly fail and a retry (or three) will fix it.

**Comment by dzschille** [comment]
Same here. The third retry mostly fixes it.

**Comment by chadlwilson** [comment]
This is a 7 year old issue - you're probably seeing something different. If you have symlinked dirs to other nested symlinks (outside a git repo) on 21.3 or 21.4, you are possibly seeing https://github.com/gocd/gocd/issues/9927 (probably not limited to MacOS)

If you would like to help, please report the specific GoCD version, OS and some details of the types of files/dirs/links it is getting stuck on (on a new or the linked issue if it seems similar) so your issue can be verified as resolved.
