### ISSUE TITLE
Add a notification processor for all plugins to publish notification from plugin to GoCD server

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3603]
##### Issue Type

- Feature proposal

##### Summary

Allow plugins to send notifications for critical updates. This allows admin/ user to take quick action if something is wrong based on notification. Going through the logs is not good options.GoCD admin/user may not have the access of the physical machine to get the plugin logs.

**Comment by arvindsv** [comment]
We should have a conversation about two-way communication with the plugin, before we do this. For instance, I don't think we should extend the `goApplicationAccessor` to do this. We should move away from it.

**Comment by arvindsv** [comment]
@bdpiparva Closing since we implemented a way for plugins to send server health messages which shows in the "Errors and Warnings" modal.
