### ISSUE TITLE
If pipeline "a" is running, lock pipeline "b".

### ISSUE THREAD

**Issue by ZukkyBaig** [gocd/gocd#3607]
##### Issue Type
Question

##### Summary

If you are running pipeline "a" and want to lock pipeline "b" until "a" completes with either a fail or pass. Is this achievable?

**Comment by arvindsv** [comment]
Questions in the [mailing list](https://groups.google.com/forum/#!forum/go-cd), please.

The answer is likely to be "No", though. I think there is an older post on the mailing list about this.
