### ISSUE TITLE
Add ability to provide plugin order for authentication 

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3608]
##### Issue Type

- Feature enhancement

##### Summary

In `17.5.0` GoCD core support for File based and LDAP/AD authentication is moved to plugins which implement the new Authorization Plugin Endpoint. Previously GoCD provided support for these authentication mechanism through Spring `AuthenticationProvider` which had a specific order in which they were executed, the FileBased AuthProvider was executed before the LDAP provider. 

With authentication moved to plugins there is no way for users to define the order of plugins to be used for authentication which is undesirable.

Possible solutions,
-  Honour the order of `<authConfig>` defined in the config while authenticating.
- To be more explicit give an option in `<authConfig>` to define the order, 
`<authConfig id="file" pluginId="cd.go.authentication.passwordfile" order="1">`
`<authConfig id="ldap" pluginId="com.thoughtworks.gocd.authorization.ldap" order="2">`

**Comment by ketan** [comment]
i thought we were authentication in the order defined in the config file. And was assuming there would be some ability to "drag and re-order" instead of explicitly setting an `order` attribute..

**Comment by maheshp** [comment]
No we are not using the order defined in the config file. We spoke about few options for ordering but nothing was finalised. This issue can help us capture the desired behaviour.

**Comment by maheshp** [comment]
After discussing with @arvindsv we have decided on relying on `<authConfig/>` order in config_xml to determine the order in which plugins will to be used for authentication.

```
<authConfigs>
  <authConfig id="file1" pluginId="cd.go.authentication.passwordfile">
   ...
  </authConfig>
  <authConfig id="ldap" pluginId="cd.go.authentication.ldap">
  ...
  </authConfig>
  <authConfig id="file1" pluginId="cd.go.authentication.passwordfile">
  ...
  </authConfig>
</authConfigs>
```
For the above example authConfigs, the order in which plugins would be called for authentication would be,
1. Password file plugin with authConfig id `file1`
2. LDAP plugin with authConfig id `ldap`
3. Password file plugin with authConfig id `file2`

**Comment by jyotisingh** [comment]
Sounds fair. Just one thing to point out. Earlier on password file auth used to happen first and then ldap. Config migration migrates ldap first (91.xsl) and then password-file (92.xsl). So, the order would be inverted from what it used to be. Not sure if that would be an issue, just thought I would point out.

**Comment by maheshp** [comment]
I don't think there will be an issue, just that user would be authenticated against LDAP first. Since this is a migration, we would need to manually change the order if required.

**Comment by arvindsv** [comment]
Good points, both. There was another thing we talked about: The fact that a failing auth (wrong password) will go through all providers/auth configs. There's no way currently for a plugin to signal that it found a user and the auth failed and nothing else should be tried. This requires bigger changes (to the endpoint too) if we need to do this. We have decided not to, at this point.

**Comment by rajiesh** [comment]
Verified on 17.8.0 (5277-32ff863cce99f97b76abb1b88469a793e3b1adc5)
