### ISSUE TITLE
Custom email notification

### ISSUE THREAD

**Issue by gdbtek** [gocd/gocd#361]
I went through email notification config (http://go.my.com:8153/go/help/admin_mailhost_info.html) and was able to get it to work.

I'm wondering if it is possible that I can customize how email output will look like  such as adding logos, reduce list of git-changes in the emails, and so on.

Thanks!

**Comment by srinivasupadhya** [comment]
I have added [notification end-point](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html). Should be available in 15.1.0. Hopefully you should be able to write a plugin for this.

**Comment by gdbtek** [comment]
:+1:

**Comment by srinivasupadhya** [comment]
should be easy to implement this with some modifications to [email-notifier](https://github.com/srinivasupadhya/email-notifier)
