### ISSUE TITLE
LDAP/AD login without password

### ISSUE THREAD

**Issue by SezBulent** [gocd/gocd#3617]
##### Issue Type

- Bug Report

##### Summary

I recently updated my GoCD server, and i mistakenly found out that the existing users on the LDAP server can also login without entering any password.I was using LDAP/AD plugin before getting deprecated, and as it states in the release notes from version 17.5.0 "Existing passwordFile and ldap configuration would be migrated to make use of these plugins", so the configurations automatically updated after the go-server update.
###### Basic environment details

* Go Version: 17.5.0 and 17.6.0
* JAVA Version: 1.8.0_131
* OS: CentOS 7 (Linux 3.10.0-514.16.1.el7.x86_64)

##### Steps to Reproduce

1. Have a server with LDAP/AD login (even a fresh one)
2. Access the GoCD link
3. Write a random user name existing in the AD
4. Login without entering any password

##### Expected Results

The user should not be able to login without entering any password
##### Actual Results

The user successfully logins.

**Comment by ketan** [comment]
Could you try one of the releases at https://www.gocd.org/download/?experimental=true and let me know if it fixes the issue?

We're going to push out a stable release with a fix today.

**Comment by SezBulent** [comment]
I'm going to try it immediately, i'll be back with an edit.

**Comment by ketan** [comment]
We've pushed a stable release for this particular fix — next time, please report security issues to "support at thoughtworks.com"

Thank you for reporting the issue.

**Comment by SezBulent** [comment]
Great, i'll surely do.Thank you for solving this issue quick enough!
