### ISSUE TITLE
Users can't login on http (port 8153) link

### ISSUE THREAD

**Issue by SezBulent** [gocd/gocd#3618]
##### Issue Type

- Bug Report

##### Summary

The login does not work on the http ( with port 8153) link.
###### Basic environment details

* Go Version: 17.5.0 and 17.6.0
* JAVA Version: 1.8.0_131
* OS: CentOS 7 (Linux 3.10.0-514.16.1.el7.x86_64)

##### Steps to Reproduce

1. Have a server with LDAP/AD or File Based Authentication login (even a fresh server)
2. Access the GoCD http link (with port 8153)
3. Write the username and password
4. Try to login

##### Expected Results

The user should be able to login on the server
##### Actual Results

The login page reloads.

**Comment by NickH-nz** [comment]
Seeing the same issue. 
The changelog mentioned upgrading from SHA1 to BCRYPT, so I tried migrating passwords and saw no change.

**Comment by ketan** [comment]
I just executed this and I'm able to login using username `admin` and password `p@ssw0rd`. Can you provide us a similar command that can demonstrate this issue?

```bash
rm -rf godata && \
  mkdir -p godata godata/config && \
  echo '<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="93">
  <server artifactsdir="artifacts" commandRepositoryLocation="default">
    <security>
      <authConfigs>
        <authConfig id="9cad79b0-4d9e-4a62-829c-eb4d9488062f" pluginId="cd.go.authentication.passwordfile">
          <property>
            <key>PasswordFilePath</key>
            <value>/godata/config/gocd.passwd</value>
          </property>
        </authConfig>
      </authConfigs>
      <admins>
        <user>admin</user>
      </admins>
    </security>
  </server>
</cruise>
' > godata/config/cruise-config.xml && \
  htpasswd -nbB admin 'p@ssw0rd' > ./godata/config/gocd.passwd && \
  docker run -v $(pwd)/godata:/godata -p8153:8153 -p8154:8154 gocd/gocd-server:v17.6.0
```

**Comment by SezBulent** [comment]
I'm not running the go-server as a docker container, my server is installed through yum package on my Centos machine, and the file based login was set up through the Authorization Configurations.As test i used the user admin, and the password "ThmbShxAtJepX80c2JY1FzOEmUk=" which is "badger"(as it says in Authentication documentation version 17.4.0)

**Comment by ketan** [comment]
Can you paste the contents of your `cruise-config.xml` and password file?

**Comment by SezBulent** [comment]
**cruise-config.xml:**
```
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="93">
  <server artifactsdir="artifacts" agentAutoRegisterKey="a804ed9e-5fec-497b-aa78-bc244ff5d845" webhookSecret="4db4e8c9-78f5-446b-bd64-79b651b546eb" commandRepositoryLocation="default" serverId="72af3f25-253f-43c9-a5f4-7c31ae221ca8">
    <security>
      <authConfigs>
        <authConfig id="PTEst" pluginId="cd.go.authentication.passwordfile">
          <property>
            <key>PasswordFilePath</key>
            <value>/etc/go/password.properties</value>
          </property>
        </authConfig>
      </authConfigs>
    </security>
  </server>
  <pipelines group="testGroup">
    <pipeline name="Test">
      <materials>
        <git url="https://github.com/gocd/gocd" />
      </materials>
      <stage name="Build" cleanWorkingDir="true">
        <approval type="manual" />
        <jobs>
          <job name="Build">
            <tasks>
              <exec command="/bin/bash">
                <arg>echo 'Test'</arg>
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
</cruise>
```

**password.properties:**
```
admin:ThmbShxAtJepX80c2JY1FzOEmUk=
```

**Comment by ketan** [comment]
This config works for me, along with the password you specified. Are there any more details in the server logs as to what's happening?

**Comment by SezBulent** [comment]
There is nothing that suggests there is an error.If i check the plugin-cd.go.authentication.passwordfile.log
with `tail -f` the login is successfull but the login page still reloads.

```
2017-06-28 11:49:15,638  INFO [qtp1512981843-27] PasswordFilePlugin:52 - [Authenticate] Authenticating User: admin using auth_config: PTEst
2017-06-28 11:49:15,643  INFO [qtp1512981843-27] PasswordFilePlugin:52 - [Authenticate] User `admin` successfully authenticated using auth config: PTEst
2017-06-28 11:49:15,644  INFO [qtp1512981843-27] PasswordFilePlugin:52 - [Authenticate] User `admin`'s password is hashed using SHA1. Please use bcrypt hasing instead.
```

**Comment by ketan** [comment]
Do you want to try it in incognito mode in chrome? If that works, perhaps you may need to clear cookies for the server hosting your gocd instance.

**Comment by SezBulent** [comment]
Hm, it works, it looks like in incognito, and clearing the cache and everything on normal browsing mode solved the issue.But Its kind of not normal, in the previous versions this issue didn't exist.

**Comment by ketan** [comment]
Ok, we're going to investigate why this is happening, I've noticed this a couple of times in the past as well.

We're keeping this ticket open until we get a resolution.

**Comment by SezBulent** [comment]
Ok, thank you for your help.

**Comment by cnorthwood** [comment]
This sounds related to the issue I have here: https://groups.google.com/forum/#!topic/go-cd/la2lmt7C07U
