### ISSUE TITLE
Slow Fetch Task on Local Docker

### ISSUE THREAD

**Issue by rightisleft** [gocd/gocd#3625]
##### Issue Type

- Bug Report

##### Summary

I'm running the latest 17.7 Agent and Server on my macbook pro. I have a job that uses 3 Fetch Tasks to grab upstream artifacts. They are each about 50MB. It's taking upwards of 2 minutes.

[go] Job Started: 2017-06-29 16:59:56 UTC
[go] Start to prepare DevDeployer/19/OnAssetsCompiled/1/Bundler on 65929eb5e2ca [/go]
[go] Start to build DevDeployer/19/OnAssetsCompiled/1/Bundler on 65929eb5e2ca [/go]
[go] Task: fetch artifact [web] => [] from [Web/CommitHandler/AngularBuild]took: 1m 41.207s
[go] Task: fetch artifact [api] => [] from [API/CommitHandler/CompileAPI]took: 52.500s
[go] Task: pwdtook: 0.112s
[go] Task: cat nginx.conftook: 0.110s
[go] Task: cat dist/src/server.jstook: 0.102s
[go] Task: cat restful.pytook: 0.104s
[go] Current job status: passed
[go] Start to create properties DevDeployer/19/OnAssetsCompiled/1/Bundler on 65929eb5e2ca [/go]
[go] Start to upload DevDeployer/19/OnAssetsCompiled/1/Bundler on 65929eb5e2ca [/go]
[go] Job completed DevDeployer/19/OnAssetsCompiled/1/Bundler on 65929eb5e2ca [/go]

###### Basic environment details

* Go Version: `Available in the footer`
Go Version: 17.7.0 (5147-53fdb1b15184f93966059a42429bf9ed0bfdee59).* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
Go Server Version:	17.7.0 (5147-53fdb1b15184f93966059a42429bf9ed0bfdee59)
JVM version:	1.8.0_131
OS Information:	Linux 4.9.27-moby
Usable space in artifacts repository:	394 GB
Database schema version:	1704003

* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Expected Results

This should be a few second transfer

**Comment by rightisleft** [comment]
Not sure if its related, but my connection time to look at a job and its artifacts is also incredibly slow. Im not sure where to get a timestamp on that in the logs.

**Comment by ketan** [comment]
From the agent machine the server machine (using localhost), can you run a quick curl to fetch the same artifact using the [get artifact file](https://api.gocd.org/current/#get-artifact-file) or [get artifact dir](https://api.gocd.org/current/#get-artifact-directory) as the case may be and post the result?

```
$ time curl --silent --user bob:password https://your-url > /dev/null
```

Do you see the commands take similar time to fetch the file when executed on the server and agent? If it takes the same time, perhaps that's something we may need to look at, else it's probably a network issue at your end...
