### ISSUE TITLE
GoCD fails to update git submodules

### ISSUE THREAD

**Issue by dyang** [gocd/gocd#3635]
##### Issue Type

- Bug Report

##### Summary

We have a git repository with several submodules. One of the submodule has a logical name that is different from its path, i.e. it was added with the --name option, so the resulting .gitmodule looks something like this:

```
[submodule "SharedRepo"]
        path = ios-common
        url = <the git url>
```
Note that the logical name "SharedRepo" differs from the path "ios-common".

When GoCD tries to update materials, it fails with the following logs:

```
pr|15:48:23.993 [GIT] Updating git sub-modules
pr|15:48:49.459 [GIT] Cleaning unversioned files and sub-modules
pr|15:48:49.460 [GIT] Git sub-module status
pr|15:48:49.587  6a92a728d8a8466aacdfdfbb3660b1c132d89e56 ios-build (6a92a72)
pr|15:48:49.668  80d52a724db33739024564b93d3a854749e327e5 ios-common (RELEASE_3_9_0)
pr|15:48:49.771 [GIT] Cleaning all unversioned files in working copy
&2|15:48:49.891 Working directory "/Users/dyang/Library/Application Support/Go Agent/pipelines/testpipeline/SharedRepo" does not exist!
```

###### Basic environment details

* Go Version: 17.7.0 (5147-53fdb1b15184f93966059a42429bf9ed0bfdee59)
* JAVA Version: 1.8.0_91
* OS: Mac OS X 10.12.5

##### Steps to Reproduce

1. Create a dummy git repo to use as material
2. Add a submodule to this repo by running `git submodule add --name <some_name> <git_repo>`
3. Commit the submodule addition to the dummy git repo
4. In GoCD, set up a pipeline that uses the dummy git repo
5. Trigger the pipeline

##### Expected Results

GoCD should be able to update to the correct git and submodule commits.

##### Actual Results

GoCD fails at fetching material with an error message 'Working directory ..../<pipeline_name>/<logical_name> does not exist!'

**Comment by dyang** [comment]
Any update on this please?

**Comment by helmesjo** [comment]
Have you tried running directly with git from commandline? Seeing the same issue with modules with name "module1" and path "path/module1" (eg. boost), so it might be an issue with git itself.

**Comment by dyang** [comment]
@helmesjo I can run `git update --init --recursive` etc with this submodule from command line without any problem.

**Comment by hraphrap** [comment]
I think, it happens, cos gocd uses _name_ of your submodule as path, when git itself uses _path_ option. I think gocd doesn't use GIT commands as _git submodule update --init_, but some wrappers, that inteprets .submodule as they undestand it.

You can use path as the name of your submodule as temporary solution.

**Comment by jonathantorley** [comment]
So.. what should I do to work around this?

**Comment by erIamshivani** [comment]
Hi,
Is there a way to **NOT LET** GoCD execute this command `git submodule init`. I have a repository which I don't want the above command to be executed for. When I clone this repository from a bash script, I do not face any problem, but when I mention the repository in Materials, I get following error:
```
Error performing command: --- Command ---
git submodule init
--- Environment ---
{}
--- INPUT ----


--- EXIT CODE (128) ---
--- STANDARD OUT ---

--- STANDARD ERR ---
STDERR: fatal: No url found for submodule path 'store/include/common' in .gitmodules
---
```

**Comment by alexmozejko** [comment]
hello, is there any way to disable gocd from trying to checkout submodules?

**Comment by chadlwilson** [comment]
> hello, is there any way to disable gocd from trying to checkout submodules?

Don't believe so, no.

**Comment by alexmozejko** [comment]
oh ok, thanks anyway @chadlwilson.

maybe you know or can provide some input, we're facing an issue where gocd is unable to update a submodule from a private repo over https (ie username & password / PAT auth). 

should this work? or this is method (private submodule over https) unsupported?

**Comment by chadlwilson** [comment]
Don't know, as never use submodules personally. Probably better to ask a wider audience on the Google Groups forum rather than an old closed issue.
