### ISSUE TITLE
Agent should go into a `LowOnDiskSpace` state when not enough disk is available

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3637]
##### Issue Type

- Bug Report
- Feature proposal (?)

##### Summary

See also #2146

When an agent runs low on disk space, it continues to build, and send back results to the server, until it can no longer write to disk.

At this point one of the two threads in the agent the `pingThread` continues to tell the server that it's building. However the `loopThread` that performs the actual build bails out because it can possibly not log anymore.

There is a possibility that this makes the server think that the agent is still building, when perhaps the agent itself is not sure what's happening.

The point of introducing the `LowOnDiskSpace` flag would help in two ways:

* if an idle agent is `LowOnDiskSpace`, the server can choose to not assign work to it
* if a building agent is `LowOnDiskSpace`, the server can flag that error to end users in an appropriate manner (the job detail page, agents page or server health messages)

Obviously, we also need to make sure that any threads that may have bailed out because of lack of disk space, need to somehow recover, preferably without the user having to restart the process. (just clearing disk space ought to be enough).

**Comment by aklint** [comment]
This would be very handy indeed. Any signs of this happening?

**Comment by arvindsv** [comment]
@aklint No one is working on it, afaik.
