### ISSUE TITLE
GoCD backup mails having IP address, good to have ServerName instead of IP address

### ISSUE THREAD

**Issue by amarshaw** [gocd/gocd#3653]
##### Summary
Hi team,

Is there a way to get ServerName in GoCD backup mail subject line and ServerName instead of IP address in GoCD backup mail body.

Current Mail subject: Server Backup Completed Successfully 
Good to have ServerName in mail subject. 
Example: Server Backup Completed Successfully: ServerName

Current body message: Backup of the Go server at 'x.x.x.x' was successfully completed. 
Good to have ServerName instead of IP address. 
Example: Backup of the Go server at 'ServerName' was successfully completed.

Regards 
Amar

**Comment by amarshaw** [comment]
Whats is the status of this story ?

**Comment by arvindsv** [comment]
If there's no comment, then there is no update. :)

I did take a [stab at it](https://github.com/gocd/gocd/issues/3653#issuecomment-328926647), but I haven't polished it and thought about any cases I've missed. So, no update on this.
