### ISSUE TITLE
DB migration when rolling back

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3657]
##### Issue Type

- Bug Report

##### Summary

When rolling back a deployment, the DB migrations from an older release are applied.

##### Environment

Steps to reproduce

```shell
rm -rf godata && mkdir -p godata

# install new version of gocd
docker run --name gocd -d -v$(pwd)/godata:/godata -p8153:8153 -p8154:8154 gocd/gocd-server:v17.7.0
sleep 60 # wait a minute for the db migrations to execute
docker stop gocd && docker rm gocd
rm -rf godata/{config,logs} godata/db/{h2db,config.git} # pretend that you put in an old db and config from a backup in that location

# rollback to older release
docker run --name gocd -d -v$(pwd)/godata:/godata -p8153:8153 -p8154:8154 gocd/gocd-server:v17.3.0
sleep 60 # wait a minute for the db migrations to execute
docker stop gocd && docker rm gocd
less godata/logs/go-server.out.log #look out for DB exceptions
```

**Comment by varshavaradarajan** [comment]
This happens because the h2deltas directory contains the additional db migrations that are left behind when the server version was 17.7.0

Since we don't have a "official" downgrade procedure, I think that we have been recommending to remove the h2deltas directory before starting a lower version of the gocd server till now. I don't see any other better workaround for it.

**Comment by ketan** [comment]
A fix is to not extract the deltas dir in the first place. We should be able to point dbdeploy to whatever is in a jar IMO. Having to remove the deltas directory is a very poor workaround.

**Comment by ketan** [comment]
Also, this is not just about downgrade, but a downgrade with a restore from backup. I can always backup, upgrade, break something, rollback the DB and the software and still be accidentally applying db migrations that may cause silent corruption of the DB...

**Comment by ketan** [comment]
Looking at the source code for dbdeploy, it only seems to understand deltas from `File` objects. So perhaps the fix is to extract deltas to a temp dir and remove the dir after deltas have been applied.
