### ISSUE TITLE
Select all agent checkbox doesn't work on environment

### ISSUE THREAD

**Issue by wlsf82** [gocd/gocd#3662]
##### Summary
In the editing agents modal of an environment, when clicking in the select all agents checkbox, nothing happens.

###### Basic environment details
* Go Version: `17.7.0`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.13.0-121-generic`

##### Steps to Reproduce
1. Go to https://go-server-address/go/environments
2. Open one of the available environments
3. Click the Edit button from the Agents
4. Click the checkbox in the header to select all agents

##### Expected Results
All agents should be selected

##### Actual Results
Nothing happens

**Comment by varshavaradarajan** [comment]
Fix - https://github.com/gocd/gocd/pull/3737
