### ISSUE TITLE
Refactor Localize Messages

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#3666]
There are couple of entity specific `create`/`update`/`delete` messages defined in [localize.xml](https://github.com/gocd/gocd/blob/master/server/webapp/localize.xml).
`for example`:
[Environment Config Messages](https://github.com/gocd/gocd/blob/master/server/webapp/localize.xml#L155-L159)
[Environment Operate Permissions](https://github.com/gocd/gocd/blob/master/server/webapp/localize.xml#L151-L153)
[Template Operate Permissions](https://github.com/gocd/gocd/blob/master/server/webapp/localize.xml#L151-L153)

**Change entity specific messages to generic messages.**
`for example`:
[Not Found](https://github.com/gocd/gocd/blob/master/server/webapp/localize.xml#L739)
[Delete Successful](https://github.com/gocd/gocd/blob/master/server/webapp/localize.xml#L526)
[No Permissions to Operate](https://github.com/gocd/gocd/blob/master/server/webapp/localize.xml#L795)

**Comment by varshavaradarajan** [comment]
No need, thanks to @ketan :)
