### ISSUE TITLE
Gitlab webhook support

### ISSUE THREAD

**Issue by bynare** [gocd/gocd#3676]
##### Issue Type
Feature enhancement

##### Summary

Currently, it does not look like POSTs coming from gitlab webooks are supported in the latest stable version of GoCD (17.7).

Would it be possible to add support for Gitlab webhooks?

I tried @FredrikWendt 's suggestion here https://github.com/gocd/gocd/issues/217, but to no avail...

Thanks!
Eugene.

**Comment by FredrikWendt** [comment]
May be related to #1591

**Comment by ketan** [comment]
Support for github webhooks was added here https://github.com/gocd/gocd/pull/3437. It is fairly straightforward forward to add support for gitlab, would you be interested in submitting a PR?

The team is here to help if you have questions...

**Comment by stephen-murby** [comment]
I was going to look at adding this myself, although I have never used GitLabs I assume there docs are good enough to get the integration going. However, it's not something I can pick up for a few weeks, so if someone else was interested in making a PR that would be cool.

**Comment by varshavaradarajan** [comment]
Taken care of by https://api.gocd.org/current/#hosting-your-repository-on-gitlab

**Comment by FredrikWendt** [comment]
Yes, this is great, if only #3980 / #3985 was fixed, it would also be nice to use: no polling on the server.
