### ISSUE TITLE
[Web-based Authentication] Multiple plugin icons on login page

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3677]
##### Issue Type

- Bug Report/Feature enhancement

##### Summary

For Authorization Plugins which support web-based authentication a plugin icon is displayed on the login screen. If a plugin is configured with multiple `<authConfig/>` a plugin is displayed for each of them on the login screen. 

Even though a icon is displayed for each `<authConfig/>` the icons do not have context of a specific `<authConfig/>`. Since the same plugin icon is displayed multiple time there is no way to distinguish which auth_config is used for authentication. And since the  [fetch-access-token](https://plugin-api.gocd.org/current/authorization/#fetch-access-token ) takes all the auth_configs it is not possible to force a specific auth_config to be used for authentication.

**Comment by ketan** [comment]
This will get addressed by #5920. Can someone confirm if the behavior is OK if we don't pass in an auth config ID to the plugin. I don't think end users understand what auth config ID is, so for the plugin to try all possible auth configs makes sense. I think the plugins already do that.

/cc @bdpiparva

**Comment by bdpiparva** [comment]
@ketan - For web-based authentication plugin there no way for the plugin to try out all the auth_configs as it involves redirect to external URL. I am okay with showing only one icon per plugin. We can address this issue later. 

PS:
Ideally showing multiple icons with the auth config name(not auth config id) make sense when multiple auth configs are there. So far we never received a request to support the feature. So I think it is fine to not address right away.
