### ISSUE TITLE
Don't open the artifacts tab - go directly to console when clicking on a job name

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#3684]
Most times, when clicking on a job name anywhere, the console log is what people want. Now, depending on the status of the job, it goes to the console log or artifacts or tests tab. It's surprising and surprise is not always good in UX. Removing functionality should be quick. Need to think about functional tests.

**Comment by arvindsv** [comment]
This came from feedback from UI/UX interviews, by the way. I didn't just make it up. :)

**Comment by maheshp** [comment]
On the job details page, on opening a tab the selected tab name is stored in the cookie thereby when the users opens the job detail page in future the tab is decided based on the value in the cookie.

Do we know if the users find this behaviour useful or should we always open the console by default?

**Comment by arvindsv** [comment]
Yes, we're going to try going to console by default, always.
