### ISSUE TITLE
Trailing slashes in GitHub material URLs break webhook notifications

### ISSUE THREAD

**Issue by mrmanc** [gocd/gocd#3690]
##### Issue Type

- Bug Report

##### Summary

GitHub webhook notifications will not trigger materials whose URL ends in a `/`. 

##### Environment

n/a

###### Basic environment details

* Go Version: `17.7.0`

##### Steps to Reproduce

1. Create a pipeline using a material in the format `https://github.com/gocd/gocd/`
2. Create a webhook for the repository to notify GoCD of pushes
3. Push a commit to the repository
4. Note that the pipeline **does not** trigger
5. Change the material to be in the format `https://github.com/gocd/gocd`
6. Push a commit to the repository
7. Observe that the pipeline **does** trigger

##### Possible Fix
Add variants of the possible URLs for a repository to [this list](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/controllers/api/git_hub_controller.rb#L30) including trailing URLs.

**Comment by ankitsri11** [comment]
It doesn't trigger even the case of Material URL is different from what is there in Github.

For example - https://github.com/gocd/GoCD won't trigger the pipeline.

Response body of webhook says - 
```
No matching materials!
```

**Comment by stephen-murby** [comment]
@ankitsri11 I'm not sure that it should match the material in your case, since everything after the domain is case sensitive in a URL. I am open to changing it though if it is unlikely that anyone has such name clashes.

@mrmanc I could look at adding that fix, but I don't have time for a couple of weeks.

**Comment by ketan** [comment]
In addition to adding a trailing slash to the URL list pointed by @mrmanc, we might need to change the signature of `MaterialUpdateService#updateGitMaterial()` to be `public boolean updateGitMaterial(String branchName, Collection<String> possibleUrls, boolean caseSensitive)`. This should allow us to use the same method for case sensitive and insensitive matching based on the hosting provider...

**Comment by stephen-murby** [comment]
@ketan How would we decide which hosts have a case sensitive url and which do not? I think the spec is anything after the domain name `google.com/` is case sensitive. Surely we have to be consistent?

**Comment by ketan** [comment]
> How would we decide which hosts have a case sensitive url and which do not?

We have a separate controller for each hosting provider, so if a hosting provider requires case-sensitive URLs (launchpad for e.g.), they could pass an appropriate boolean to `MaterialUpdateService#updateGitMaterial`

**Comment by arvindsv** [comment]
The spec ([this one?](https://www.w3.org/TR/WD-html40-970708/htmlweb.html)) says: "URLs in general are case-sensitive (with the exception of machine names). There may be URLs, or parts of URLs, where case doesn't matter, but identifying these may not be easy. Users should always consider that URLs are case-sensitive."

That is mostly all about the users. For a server, it's undefined, as far as I know. That means, it can decide to do whatever. Treating URLs as case-insensitive is more the norm, as far as I know.

My opinion is that we should ignore case.

**Comment by arvindsv** [comment]
Just so it is clear, the recommendation: "Users should always consider that URLs are case-sensitive" is because they can't know how a server handles it (and it is not mandated that servers handle it as case-sensitive).

**Comment by mrmanc** [comment]
@stephen-murby understood—I’ve suggested to someone else that they submit a PR for this anyway :)

Feels like it might be worth splitting the conversation about case off into a new issue so that the conversation isn’t lost in this one. For what it’s worth, I think that if it’s going to be case insensitive then it would make sense to make that clear at the point the user is supplying the material URL, and lowercasing the URL supplied by the user in those cases. It feels weird though, as it would be possible to validly have repos with URLs which only differ by case, but it’s probably worth considering what would happen in the case that the wrong material was notified.

**Comment by arvindsv** [comment]
@mrmanc - That's a valid point. If we're treating the material URL as case-sensitive everywhere else, there's no point in making it be case-insensitive here.

I think it will all come down to whether GoCD handles: `https://github.com/abc` different from `https://github.com/ABC`. I don't know the answer to that, offhand. A quick look at the code suggests that case matters. The fingerprint generation code doesn't seem to lowercase anything. I could be wrong.

**Comment by stephen-murby** [comment]
@arvindsv @mrmanc I think knowing that GitHub handles those things case sensitively means that (for this endpoint at least) we should do the same. We can still change the signature of  `updateGitMaterial` to take a case-sensitive flag; but I would recommend having it true for GitHub. So to @ankitsri11's point, his 'issue' would remain.

**Comment by arvindsv** [comment]
@stephen-murby That makes sense. @ankitsri11 and I had a conversation about it earlier, and I was the one who had said it should be case-insensitive earlier. I agree that it looks like it should be case-sensitive, if GitHub itself treats it that way.
