### ISSUE TITLE
Generate the encrypted SECURE variable from GOCD UI 

### ISSUE THREAD

**Issue by gakshay** [gocd/gocd#3698]
##### Issue Type

- Feature enhancement

##### Summary

Ability to generate the encrypted SECURE Variable from GOCD UI for admins. 

Currently we use [gocd yaml](https://github.com/tomzo/gocd-yaml-config-plugin) for writing pipeline as code across all our projects. However in order to use the secure variables it's required to encrypt the variable on GO Server before checking in the code. The process to generate the encrypted value is quite cumbersome.
1. Someone need SSH access on the Go Server. This is separate than having access on the GOCD UI (done via LDAP today)
2. Run the command `sudo -u go bash -c 'echo -n 'YOUR-INPUT' | openssl enc -des-cbc -a -iv 0 -K $(cat /etc/go/cipher)'` [reference](https://github.com/tomzo/gocd-yaml-config-plugin#environment-variables)

Providing a simple GOCD UI based solution to generate the encrypted variable for admins will be very helpful.

**Comment by ketan** [comment]
[This](https://api.gocd.org/current/#encrypt-a-plain-text-value) might be of help. I'm closing this ticket, but if you think that the API does not suffice, please let me know.

**Comment by ketan** [comment]
I've also submitted a PR https://github.com/tomzo/gocd-yaml-config-plugin/pull/30 for the next person to not be tripped with the same issue.

**Comment by naveenmt99** [comment]
ketan,

I am getting the 404 while post to /go/api/admin/encrypt with version 17.3.0 sever. please suggest.

**Comment by varshavaradarajan** [comment]
@naveenmt99, can you please provide the request for which you're getting a 404? Please mask the value you want to encrypt and then share the request. I think you would get a 404 if the `Accept` header is not passed.

**Comment by venkatanathen** [comment]
Hi, 
I'm using pl.gocd.yaml goCD config file for create the pipelines. I've generated the secure_variable password. How to use the variable and decrypt the password and pass it as in input parameter ?

Please advice.

Thanks,
VK

**Comment by arvindsv** [comment]
@venkatanathen You don't need to decrypt it. You should just use the encrypted one as in: https://github.com/tomzo/gocd-yaml-config-plugin#stage. If the result of the encrypted variable was: `aes:fjsksd938rnwd`, then you'd use:

```json
  secure_variables:
    PASSWORD: "aes:fjsksd938rnwd"
```

**Comment by arvindsv** [comment]
Also, it might be useful to ask questions here: https://gitter.im/gocd/configrepo-plugins

**Comment by venkatanathen** [comment]
Thank you so much. 
I'm executing the below statement in a make file
      git push --tags  http://Gocd-agent:$(param1)@githuben.com/td-cloud/aws-module-vpc.git 
I need to input the password which I've encrypted above when the pipeline job runs.

Please let me know.

Thanks,
VK
