### ISSUE TITLE
Expand and Sort Pipeline Group

### ISSUE THREAD

**Issue by naveenbhaskar** [gocd/gocd#3704]
scope:
1) Expand collapse for pipeline groups
2) Sort pipelines within the group 
3) Sort the pipeline group
-----------------------------------------------------------------------------------------------

_**1. Expand collapse for pipeline groups**_

**solution:** Added plus-minus icons at the pipeline group name header. user can click on the header and expand-collapse it
There is an collapse icon added next to personalise option. on click of this, all pipeline groups will be collapsed , and the icon change to expand icon.

![image](https://user-images.githubusercontent.com/1627961/28667035-5d8cfe7e-72e7-11e7-838b-0b88ed429656.png)

**_2. Sort pipelines within the group_** 

 User should be able to drag a pipeline and change the order within a group

**_3. Sort the pipeline group_** 

**solution:** As mentioned on point 1, user can collapse all pipeline groups in the dashboard, then drag the pipelines to change the order. the three dots on the left of the pipeline group header denotes that the group is draggable. once sorting is over, user can click on the top right icon in the pipeline header to expand all the pipeline groups 

![image](https://user-images.githubusercontent.com/1627961/28667095-a2f82858-72e7-11e7-92d6-390bd18eb4ba.png)

**Comment by streisguth** [comment]
I like the interaction to drag to rearrange, I think that will be a great benefit. The expand/collapse icons should not be pluses and minuses; that will cause confusion as those symbols are traditionally associated with adding and removing.

The collapse/expand all sounds like a good feature, but I would try and explore ways to place it more directly in the context of the pipeline groups; right now I would expect that button to affect the header in some way. I could be easily convinced otherwise though.

**Comment by eeluke** [comment]
Thanks, Naveen.

"2. Sort pipelines within the group: User should be able to drag a pipeline and change the order within a group"
How will the user know he/she can drag the pipeline? Will we include those three dots or other symbol to convey this message?

Agreed that icons should be conventional expand/collapse up & down arrows.

Right now, the headers feel a bit disjointed from the pipeline tiles. Maybe you can play with a couple other options for them?

**Comment by eeluke** [comment]
One last thing - I think by "sort" you mean "move". As far as I see from the mockups, this isn't sort functionality (providing a way to order the pipelines and/or groups by date, name, etc.) But maybe I missed something...

**Comment by naveenbhaskar** [comment]
plus/minus and up/down , both are equally used for expand-collapse components. I am fine with both.
ref: https://www.smashingmagazine.com/2017/06/designing-perfect-accordion-checklist/

- The expand-collapse icon has to be above all pipeline groups because its meant for all the groups in the dashboard, same as personalised option. Throughout the application, the page title header act as a place for  page related actions.

- sort pipelines within the group : I think this is re arranging the order of pipelines. Thats what users have asked for. we can use the three dots here , next to the title. Do we need to use an icon for the pipeline title? . it doesn't serve any purpose there.. in the mockup below, i have removed pipeline icon and added 3 dots.

![image](https://user-images.githubusercontent.com/1627961/28706602-b1427994-7392-11e7-9b42-0277a61f92c8.png)

**Comment by streisguth** [comment]
I would keep the pipeline icon; we're addressing the icons across the platform in a second story and can think about it more holistically in that context.

**Comment by naveenbhaskar** [comment]
Anything to add/modify on this?

**Comment by eeluke** [comment]
No, I think we are good. I think we should use the up/down carrots for now.
Looks like +/- are okay too ONLY if the application doesn't use them in
other ways. I don't think we do, but until we can check, we should use the
carrots. I like the light gray shading on each section.

Thanks.

Emily Luke
Head of User Experience,
ThoughtWorks Studios <http://www.thoughtworks.com/products>
Email eluke@thoughtworks.com
Telephone +1 908 209 6204 <+1+908+209+6204>
[image: ThoughtWorks]
<http://www.thoughtworks.com/?utm_campaign=emily-luke-signature&utm_medium=email&utm_source=thoughtworks-email-signature-generator>

**Comment by mmindenhall** [comment]
I'm not sure if this is the right place to mention this, but it would be good to drive the initial sort order of pipelines from the configuration.  For example, we could have a parameter or a new field in a pipeline (this example in yaml since we're using [that plugin](https://github.com/tomzo/gocd-yaml-config-plugin)):

```yaml
# new field option
pipelines:
  mypipe1: # definition of mypipe1 pipeline
    group: mygroup 
    group_sort: 00001 # string, case-insensitive sort within pipeline group

# parameter option
pipelines:
  mypipe1: # definition of mypipe1 pipeline
    group: mygroup 
    parameters: # list of parameters that can be configured for a pipeline
      group_sort: 00001 # string, case-insensitive sort within pipeline group
```

**Comment by mbotmcc** [comment]
any updates on this? Would also like to see this as the order of pipelines configured via config repos changes whenever they're updated which is annoying

**Comment by arvindsv** [comment]
@mbotmcc https://github.com/gocd/gocd/pull/6043 and https://github.com/tomzo/gocd-yaml-config-plugin/pull/114 should allow that in 19.3.

**Comment by chadlwilson** [comment]
Hi @arvindsv - the `display_order` addresses the ordering within a group or environment; however is there a way to change the ordering of groups themselves? It doesn't seem that the group's display ordering on the dashboard is affected by the `display_order` of the pipelines within that group.

Without explicit group ordering, one can image that if you have two groups, each with one pipeline; the ordering could be inferred by treating the `display_order` globally.

eg with
```yaml
pipelines:
  mypipe1:
    group: group1
    display_order: 2
  mypipe2:
    group: group2
    display_order: 1
```

the dashboard would look like

```
group2:
  mypipe2

group1:
  mypipe1
```

**Comment by arvindsv** [comment]
@chadlwilson Yes. I understand. I think the order of the pipeline groups is based on their ordering the config XML and cannot be controlled using anything else.

**Comment by chadlwilson** [comment]
Thanks for the clarification @arvindsv - that's our observation from active use; that pipeline groups are effectively ordered by creation time and/or pipeline yaml import time.

**Comment by asyafoek** [comment]
is the expand and collapse feature in the latest version of GoCD, I do not see the +/- sign in the right corner of the pipeline group?

**Comment by chadlwilson** [comment]
No, it is not. This was closed as a stale ticket, as you should be able to see above.

**Comment by asyafoek** [comment]
What can I do to reopen, I am new to the community and I would realy like this feature
