### ISSUE TITLE
Roles UI missing

### ISSUE THREAD

**Issue by zerolaser** [gocd/gocd#3712]
Is there any way to add a role and assign it to all pipelines/users at once?
I feel we are missing the roles UI page. 
Currently to a add a role to a pipeline group, we need to go each pipeline group then add there. 
It would be nice if we had a page to a role to mulitple pipeline groups. just like we have adding role to multiple users.

**Comment by motorstorm** [comment]
I feel the same. Also, we can't remove a role unless we modify the XML manually.

**Comment by varshavaradarajan** [comment]
On the user summary page, individual users can be specified as go system admins. There is no UI for specifying roles as go system administrators.

**Comment by aqneves** [comment]
I don't think this is about Go System Administrators. This has to do assigning a role to multiple pipelines / pipeline groups at once without having to go through each pipeline group manually. That is probably what @zerolaser was referring to.

Regarding assigning roles to users that's possible by selecting multiple users in the "User Summary" page.

**Comment by varshavaradarajan** [comment]
@aqneves - I meant that in addition to the original UI issue for roles, this needs to be taken care of. 

> Regarding assigning roles to users that's possible by selecting multiple users in the "User Summary" page.

Sure, but you can't select a role and assign the role as go system administrator.

**Comment by zerolaser** [comment]
@aqneves Correct. That's what i was hoping, Instead of each time going into a pipeline group and then selecting each role or user that needs to have access. A role or user page  with a select dropdown that granting access to all the pipeline groups. but there might be an issue on how to give the view, operate admin to that pipeline group.

It would really help us migrate from AD authentication to Single sign-on.  
Not sure if it is fixed in version > 18.9.0 
@varshavaradarajan its been more than an year and any update on this issue ?

**Comment by arvindsv** [comment]
@zerolaser No. There's no UI. [Granular auth](https://github.com/gocd/gocd/issues/4735#issuecomment-465892486) is the one coming up next, which will be handling it. It'll allow the  ability to add a policy to a role, which will allow it to administer all pipeline groups, etc.

**Comment by zerolaser** [comment]
@arvindsv When is this expected to release ?

**Comment by arvindsv** [comment]
@zerolaser Probably over the next couple of months. Depends on other work in progress, such as support for secrets management.
