### ISSUE TITLE
Pipeline quick edit doesn't save the job with empty task

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#3713]
##### Issue Type

Bug

##### Summary

Pipeline quick edit doesn't save the job with empty task whereas normal edit save the  job with empty task.

![quick-edit](https://user-images.githubusercontent.com/6838313/28738840-d46279fc-73aa-11e7-97e0-765973335563.gif)

###### Basic environment details

* Go Version: 17.8.0 (5275-95e3f80dc99a41d4a5f512b01842b30915b5eed5)

**Comment by arvindsv** [comment]
I can't think of a good reason to allow saving an empty job. Do you?

**Comment by ankitsri11** [comment]
There is no necessity of having an empty job. Its just it works on normal edit.
Either it should throw an error while clicking on save button or should save the job as it does in normal edit with default ant task.

![normal-edit](https://user-images.githubusercontent.com/6838313/28747603-2c88555e-7458-11e7-8d3f-9c24f305e07e.gif)

**Comment by GaneshSPatil** [comment]
@arvindsv @ankitsri11  -- The current GoCD UI has a default task set to `ant`. So the creation of a new job will always submit `ant` as the default task under the new job.

But yes, I agree with you that the behavior of the new and old page can be consistent.

---

Closing this issue as the old quick edit SPA is removed. This issue will be addressed as part of pipeline config SPA redesign.
