### ISSUE TITLE
After renaming job, history for all the previous job runs is missing

### ISSUE THREAD

**Issue by ayatsynych** [gocd/gocd#3725]
##### Issue Type

- Bug Report

##### Summary

If there is job "TestJob" in GoCd and I rename it to "TestJob-1", on the Dashboard, browsing through the previous runs of "TestJob" (before the rename happened) will show the job run itself but not the artifacts and console output, instead error "Job Pipeline/780/Stage/1/TestJob not found." is shown.

Please NOTE: when looking into "artifacts" folder on GoServer itself, all the artifacts and pipeline configs are in place.

###### Basic environment details

* Go Version: 17.4
* JAVA Version: 1.8.0_102
* OS: Windows Server 2012 R2 6.3

##### Expected Results
Job history should be available for jobs with both - old and new names.

##### Actual Results
Job history is gone for all the runs that happened before renaming

**Comment by arvindsv** [comment]
@ayatsynych - Thanks. Yes, this has been reported before (see https://github.com/gocd/gocd/issues/1575). So, I'll close this as a duplicate. But, this should be fixed. Unfortunately, no one is working on this, at this time.

Anyone ( not just you :) ) willing to work on it will definitely get help to submit a PR.
