### ISSUE TITLE
Group name is not present in templates or pipeline_groups api call 

### ISSUE THREAD

**Issue by 99** [gocd/gocd#3738]
##### Issue Type

- Bug Report

##### Summary
If pipeline using template there is no way to get a group name. None of the api calls contains this information. 
`/config/pipeline_groups` will return template name vs group name

###### Basic environment details

* Go Version: ` 17.3.0 (4704-3c7d8f7e5d78e46f72ff1194bb322c6b5d72a90f).`
* JAVA Version: `1.8.0_111`
* OS: `Linux 3.13.0-74-generic`
* Browser vendor and version (if relevant): `Not related , but chrome`

##### Steps to Reproduce

If pipeline using template there is no way to get a group name using the api calls. None of the api calls contains this information. 
`/config/pipeline_groups` will return template name vs group name

##### Expected Results

I'm using gocd json plugin so I'm writing a script to convert templated pipelines into the json-formatted once. So expecting that   below code will return pipeline group name vs template name
   ```
def _get_pipeline_group(self):
        url = f'{self.url}/config/pipeline_groups'
        response = get(url, auth=self.config)
        decoded_response = response.json()
        for resp_item in decoded_response:
            pipelines = resp_item.get('pipelines')
            for pipeline in pipelines:
                if pipeline['name'] == self.old_name:
                    return resp_item['name']
```

**Comment by varshavaradarajan** [comment]
Hi,

Can you please provide the specific steps for the scenario you are describing? 

I have a pipeline X using a template Y in group A. When I make the API call `api/config/pipeline_groups`, the name returned for the group is A, which is the expected value. However, I noticed that the pipeline using a template doesn't provide the template name but instead provides the stages in the template.

**Comment by arvindsv** [comment]
Closing as stale.
