### ISSUE TITLE
Console log doesn't show last few lines when the build state changes from "running" to "completed". (Browser WebSockets only)

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#3740]
##### Issue Type

- Bug Report

##### Summary

While connected over browser WebSockets, if the build is running and the state changes from 'running' to 'completed', last few lines of console logs are not shown.

##### Steps to Reproduce

1.  Turn on browser WebSockets
2.  Trigger a pipeline
3. Go to the Job details page, console tab, you will see output of the job has been produced
4. But, when the job completes, last few lines are not shown. Check the status of the job at the top right corner (icon which represents the current state of job)

##### Expected Results
It should show all the lines of the console output

##### Actual Results
It does not show the last few lines of console output

![screen shot 2017-08-08 at 12 36 47 pm](https://user-images.githubusercontent.com/15275847/29060194-4fc9ef24-7c36-11e7-956e-a4005350b29e.png)

**Comment by arvindsv** [comment]
Saw this too! Quite irritating.

**Comment by varshavaradarajan** [comment]
Fixed by https://github.com/gocd/gocd/pull/3743
