### ISSUE TITLE
Environmental variables descriptive feature

### ISSUE THREAD

**Issue by agerro** [gocd/gocd#3741]
##### Issue Type

- Feature enhancement

##### Summary

Possibility to add descriptive text, or hint, about the environment variables.

###### Basic environment details

* Go Version: `17.8.0`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.10.0-693.el7.x86_64`

##### Any other info

Just being able to explain what the environment variables that is available, stand for and what they are. That is sometimes hard to to in only the variable name, and since the project I'm working on has customers that is changing them, they also have a hard time knowing what to change.

**Comment by arvindsv** [comment]
These are explained in the documentation: https://docs.gocd.org/current/faq/dev_use_current_revision_in_build.html#standard-gocd-environment-variables

So, I'm closing this. Can reopen if I mistook the request. Thanks!

**Comment by agerro** [comment]
@arvindsv Might have been a bad explanation of the feature.
As you can see in the following picture, from the link you gave me: 
https://docs.gocd.org/current/resources/images/env_variables_environment.png

When you set custom variables for an environment, I want to be able to specify what type the variable can be in, or, set a hint for that variable so that when someone else then me can edit the variables without asking me. Does that make more sense? :)

**Comment by arvindsv** [comment]
I see. In config. Sure.

We are hesitating to make changes to config a little currently, because config save performance when there are thousands of pipelines can be slow and become slower by adding more, but the feature request makes sense. This ability to describe different parts (such as a pipeline, stage, env vars, etc.) can be useful. Reopening.

**Comment by agerro** [comment]
Fully understandable.
And sure, if you give the variable a good enough name that dosent need any more explanation, the current setup works more than fine. 

This is more of a "Nice to have" feature :)
