### ISSUE TITLE
Flaky PR test in build-linux-PR pipeline

### ISSUE THREAD

**Issue by yankurk** [gocd/gocd#3744]
Tests in DefaultExternalPluginJarLocationMonitorTest are flaky (com/thoughtworks/go/plugin/infra/monitor/DefaultExternalPluginJarLocationMonitorTest.java)

Steps to reproduce:
In your localbox run the tests multiple times. Some tests fail after few runs. 
![image](https://user-images.githubusercontent.com/23699743/29067355-f17bf560-7c4f-11e7-8da7-2176134de12c.png)
![image](https://user-images.githubusercontent.com/23699743/29067369-fae11cb6-7c4f-11e7-8761-cb8fa39608cb.png)

**Comment by arvindsv** [comment]
Closing as stale.
