### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by darshanj** [gocd/gocd#3748]
##### Issue Type
- Bug Report

##### Summary
When we try to save config.xml from admin tab, we get following error:
413 Request Entity Too Large
URL: http://<goserver_url>:<port>/go/admin/config_xml

Note: XML of our pipelines is about 

##### Environment
We have hosted go server in CentOS 7.2

###### Basic environment details

* Go Server Version: | 17.3.0 (4704-3c7d8f7e5d78e46f72ff1194bb322c6b5d72a90f)
-- | --
* JVM version: | 1.8.0_131
* OS Information: | Linux 3.10.0-514.16.1.el7.x86_64
* Usable space in artifacts repository: | 221 GB
* Database schema version: | 1702001
* Browser vendor and version (if relevant): Chrome Version 59.0.3071.115 (Official Build) (64-bit)

##### Steps to Reproduce

1. Go to Admin -> Config XML tab (URL : http://<goserver_url>:<port>/go/admin/config_xml) 
2. Click Edit
3. Paste a valid pipeline xml of 25814 lines. (This are number of lines we have in xml)
3. Click Save

##### Expected Results
Config XML should be saved without problems

##### Actual Results
We get '413 Request Entity Too Large'

##### Possible Fix
Need to increase payload limit in http post on http://<goserver_url>:<port>/go/admin/config_xml route.

##### Any other info
We can change any feature from admin console but not from xml.

**Comment by sedatsencan** [comment]
I still have the same problem in GoCD Version: 19.10.0. Is there any way to fix it without updating?

**Comment by arvindsv** [comment]
How big (size in bytes) is the config? Do you have a proxy in between?

There used to be a 30MB limit [set here](https://github.com/gocd/gocd/blob/3e948218bfb163c5c3d2bf5140cb4a12f110769e/server/config/jetty.xml#L44). If your config is smaller (I would hope), it might not be GoCD complaining about it (maybe a proxy in between is).
