### ISSUE TITLE
Show Runtimes and Durations in VSM

### ISSUE THREAD

**Issue by tinozza** [gocd/gocd#3750]
Scope:
1) Show pipeline duration in VSM.
2) Highlight pipelines which take longer time.
3) Show runtimes and duration for stages on hover - Note: Currently, the hover takes some time to show the tooltip. This behavior has to be fixed.

Solution:
1) Add duration for the pipeline below 'RUN'
2) Highlight pipelines with longer duration - using red color for the time and timer/clock icon.
![vsm duration _without hover](https://user-images.githubusercontent.com/16536421/29119472-e0e6cf0c-7d23-11e7-8807-97838171007d.png)

 - On hover over the highlighted duration a tooltip explaining the reason for which the pipeline has been highlighted appears. ( yet to determine the content for this)
![vsm duration highlight](https://user-images.githubusercontent.com/16536421/29119611-7284466a-7d24-11e7-8f86-8c95a93af6c2.png)

3) On hovering over the stages,  a tooltip with the details regarding the trigger time and duration appears.

<img width="983" alt="screen shot 2017-08-09 at 5 04 46 pm" src="https://user-images.githubusercontent.com/16536421/29119724-f2b57278-7d24-11e7-923d-3d24fab2b0d7.png">

**Comment by tinozza** [comment]
@all: we can also add the story for removing the gray bar from VSM along with this story. 
Scope: Remove the gray bar on pipeline card in VSM view

**Comment by tinozza** [comment]
option for showing duration for pipelines with multiple instance 

![image](https://user-images.githubusercontent.com/16536421/31121872-7cc14534-a857-11e7-8001-da21af3b244b.png)
![image](https://user-images.githubusercontent.com/16536421/31121923-a88886b4-a857-11e7-8cfc-8859526ce8e6.png)

**Comment by eeluke** [comment]
This solution works for me - though there is a lot of white space in the
top pipeline panel below the "1 more". Also, do you think the # is
relevant? Or can we just say "more" and "less" - maybe with our
expand/collapse arrow too?

Emily
