### ISSUE TITLE
How to backup GoCD automatically

### ISSUE THREAD

**Issue by vivuu1989** [gocd/gocd#3770]
##### Issue Type

- Security issue? [**DO NOT** report it here. Use [hackerone](https://hackerone.com/gocd) or send a mail to support@thoughtworks.com]
- Bug Report
- Feature proposal
- Feature enhancement
- Documentation Report

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by arvindsv** [comment]
Closing this. This is a place for issues. Not questions. Try the mailing list or [other resources](https://www.gocd.org/resources.html) instead.

**Comment by vivuu1989** [comment]
This is not question. This is an issue which we are facing currently

I couldn't find any source to automate good backup. Doing it manually is
not a solution.
