### ISSUE TITLE
When console logs are not available, no message is shown

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#3773]
##### Issue Type

- Bug Report

##### Summary

Console logs of jobs with purged logs don’t show any message. Compare [this](https://build.gocd.org/go/tab/build/detail/build-linux/1832/build-non-server/1/agent) and its [raw logs](https://build.gocd.org/go/files/build-linux/1832/build-non-server/1/agent/cruise-output/console.log).

###### Basic environment details

* Go Version: 17.8

##### Expected Results

A message which says that the logs are not available, because they were removed.

##### Actual Results

Empty. No message.

##### Any other info

Related: #3650 #3695

**Comment by arvindsv** [comment]
Added 17.9 as milestone, just so we don't lose it. Not that urgent. Should be in the next one, at least, though.

**Comment by GaneshSPatil** [comment]
Reproducible on both
  - [ ] Console log Polling
  - [ ] Console log Websocket

**Comment by rajiesh** [comment]
Verified on 17.12.0 (5621-158fee2729f0a07475594782e6a5716ac3154f8a)
