### ISSUE TITLE
Job waiting for manual trigger if previous failed

### ISSUE THREAD

**Issue by gentitope** [gocd/gocd#3774]
Hello,
Anyone can help?
I have set the "Run If Conditions*" to Any but job still waiting for manual trigger when previous job stage fialed.
When the previous stage job passed build pipelines run successfully.

![screen shot 2017-08-23 at 12 12 00 pm](https://user-images.githubusercontent.com/8830762/29606325-f4b91f4a-87fe-11e7-937e-8c6e12bfbf28.png)

**Comment by varshavaradarajan** [comment]
Hi,

Run if conditions are configured on a **task**. Tasks are configured for a job and run sequentially in a job. Based on the run if condition, the tasks following a failed task may or may not run.  A *stage* fails when one or many jobs in it fails. And subsequent stages will not be triggered. [This](https://www.gocd.org/getting-started/part-1/#concept2) will help you understand the concepts in GoCD to get started with.
