### ISSUE TITLE
Edit gear on VSM page takes to the normal edit page even when Quick edit is enabled

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#3777]
##### Issue Type

- Bug Report

##### Summary

Edit gear on VSM page takes to the normal edit page even when Quick edit is enabled

###### Basic environment details

* Go Version: `17.9.0 (5340-dc39953b086ce672a090dcd90e45bd3fe0c3ee76)`

##### Steps to Reproduce

This is observed on the build.gocd.org environment where Quick edit page is enabled. The edit gear on VSM page still takes you to the normal edit page

**Comment by varshavaradarajan** [comment]
@yankurk is looking into it.
