### ISSUE TITLE
Is there a way to specify charge balance between agents?

### ISSUE THREAD

**Issue by ximbal** [gocd/gocd#3778]
I want to know how the mechanism works on chosing to which agent the server will assign a job, it is obviously acordingly to the agent capacities (if it has package A or B or is has Operating System A or Z), but then what happens? is it a round robin like a DNS? is there any way to ponder send 60% of the charge to this agents and the rest to others? any business rules?

**Comment by adityasood** [comment]
@ximbal currently you can assign agents to specific jobs in one of the following ways

1. Assign an agent to an environment and all Pipelines in this environment can run using these agents. Please read the documentation [here](https://docs.gocd.org/current/configuration/managing_environments.html)

2. Use resources to Manage agents. Please read the documentation [here](https://docs.gocd.org/current/configuration/managing_a_build_cloud.html)

3. Use GoCD elastic agents to bring up dynamic agents for a job. Pleas read the documentation [here](https://docs.gocd.org/current/configuration/elastic_agents.html)


This repo is for feature requests or issues related to GoCD. Please redirect all how-to-questions to [GoCD Gitter channel](https://gitter.im/gocd/gocd?at=5d2eb334e190903936fd1f93).
