### ISSUE TITLE
'SCHEDULED ON' timestamp is not updated for re-runs of same job. 

### ISSUE THREAD

**Issue by mahsoud** [gocd/gocd#3780]
Issue Type: 
- Bug Report

Summary:
- If a job is reschedule for re-run, second run of the job will show 'SCHEDULED ON' timestamp of the first run.

Basic environment details:
- Go Server Version:	17.4.0 (4892-ab17b819e73477a47401744fa64f64fda55c26e8)
- JVM version:	1.8.0_102
- OS Information:	Windows Server 2012 R2 6.3
- Usable space in artifacts repository:	13.9 GB
- Database schema version:	1704003

**Comment by GaneshSPatil** [comment]
@mahsoud -- I tried reproducing this issue. However, on a job rerun, the `scheduled_date` timestamp was updated and pointing to the appropriated scheduled on time.

\cc: @adityasood

**Comment by GaneshSPatil** [comment]
Didn't hear from the user. Marking as `stale`.
