### ISSUE TITLE
document unit of go.security.reauthentication.interval

### ISSUE THREAD

**Issue by juliantaylor** [gocd/gocd#3782]
##### Issue Type

- Documentation Report

##### Summary

The reauthentication docs mention the interval but do not specify the unit the setting:
https://docs.gocd.org/current/configuration/dev_authentication.html
According to the code it seems to be milliseconds.
Please document the unit and maybe also how one can actually change it for people less familiar with configuration.

**Comment by GaneshSPatil** [comment]
@juliantaylor -- Thanks for reporting this issue.
It has been fixed as part of https://github.com/gocd/docs.go.cd/pull/357 PR.
