### ISSUE TITLE
Authorization plugins do not have access to the request headers

### ISSUE THREAD

**Issue by cnorthwood** [gocd/gocd#3784]
##### Issue Type

- Feature Enhancement

##### Summary

I have [a plugin](https://github.com/cnorthwood/gocd-tls-auth) that uses TLS client certificates to authenticate users. This works by a proxy which terminates SSL setting headers on the proxied request. The current version of the plugin is an authentication plugin which reads those headers. In moving to the authorization plugin, this is no longer possible as the headers are not available at the "go.cd.authorization.fetch-access-token" stage.

Would it be possible to enhance this to pass through headers from the browser to the plugin?

###### Basic environment details

* Go Version: 17.8.0 (5277-32ff863cce99f97b76abb1b88469a793e3b1adc5)
* JAVA Version: 1.8.0_131
* OS: Linux 4.4.0-81-generic

**Comment by bdpiparva** [comment]
@cnorthwood --- Thanks for reporting. The [PR#3787](https://github.com/gocd/gocd/pull/3787) is opened in favor of it. Please do let us know if this resolves the issue.

**Comment by varshavaradarajan** [comment]
@cnorthwood , experimental builds are available for this at https://www.gocd.org/download/?experimental=true 

We will be making a release shortly.

**Comment by cnorthwood** [comment]
Yes, that resolves my issue, thanks :)
