### ISSUE TITLE
Show build times - stage details page

### ISSUE THREAD

**Issue by tinozza** [gocd/gocd#3786]
**Scope:**

Show the actual build time and the build time with the agent wait time for the jobs in the stage details page.
**Context:** 
attached below a screenshot which shows the actual transitions in a job ( bookmarklet view)

<img width="1146" alt="screen shot 2017-08-28 at 11 16 12 am" src="https://user-images.githubusercontent.com/16536421/29768077-812c90d6-8c02-11e7-9ba1-de21473767b6.png">
----------------------------------------------------------------------------------------------------

**Proposed solution**

1) On clicking on the stage in the pipeline view, the jobs tab opens by default(currently it's the overview tab).

2) The quick view shows the total build time as a horizontal stacked bar which shows the agent wait time(total time the job to be scheduled and assigned to the agent) and the actual build time

![stage details page_jobs](https://user-images.githubusercontent.com/16536421/29768543-44adc790-8c04-11e7-86f1-6a844df68cc7.png)

3) A detailed view of the actual tranisitions in the job can be viewed by clicking on the detailed view link. This view opens as an overlay.
![stage details page](https://user-images.githubusercontent.com/16536421/29768544-44d7188e-8c04-11e7-8535-5ca704d99200.png)

Please Note:
For the detailed view the titles for the transitions are just indicative as of now and have to be rephrased to be made more intuitive for the users.

Please do share your feedback/concerns for the mockup proposed above.

**Comment by eeluke** [comment]
@tinozza I really like this. I like that you only show the relevant info on the jobs screen and then allow the user to dig in deeper in the detail view. My only question is why the orange color shading to indicate that the first job "jetty9" is selected. Is there some behavior that occurs upon selection (mouse click) of a job? Maybe you can add some notes to these mockups as to what the behavior will be when a user clicks and hovers?

**Comment by tinozza** [comment]
>My only question is why the orange color shading to indicate that the first job "jetty9" is selected. Is there some behavior that occurs upon selection (mouse click) of a job? Maybe you can add some notes to these mockups as to what the behavior will be when a user clicks and hovers?

My mistake, I attached the wrong screenshot... I was just trying to see if we need to highlight rows with failed jobs. Attaching the correct screenshot below.

![image](https://user-images.githubusercontent.com/16536421/29936594-72e12262-8ea0-11e7-8573-6de5fa1fdaa4.png)
Notes:
1) On clicking on the stage in the pipeline view, the jobs tab opens by default(currently it's the overview tab) in the stage details page. 

2) The quick view shows the total build time as a horizontal stacked bar chart which shows the agent wait time(total time the job to be scheduled and assigned to the agent) and the actual build time

3) On hovering over the stacked bar chart a tooltip appears - showing the duration/time for both the agent wait time and the actual build time.


**Overlay with the detailed view of actual transitions:**

![image](https://user-images.githubusercontent.com/16536421/29938598-f67d289a-8ea6-11e7-999c-6663868e6aad.png)
1) by clicking on the detailed view link this view opens as an overlay. 
2) on hovering over the stacked bar chart - tooltip with the duration for each transition appears. 


Link to the invision prototype : https://invis.io/YUDAJKCG5

**Comment by arvindsv** [comment]
@tinozza: In the overlay, you'll need to consider how reruns show. A job (or jobs) can be rerun much later. In those cases, the "From time to time" part might become less relevant.

**Comment by eeluke** [comment]
Thanks, Tina. I don't have any additional questions. I think this looks
great!

Emily

**Comment by tinozza** [comment]
@all attaching mockup for stages with jobs in progress.
![stage details page _stage in progress](https://user-images.githubusercontent.com/16536421/30103320-e97f048e-930f-11e7-97ad-87c9b0c487f6.png)

@arvindsv Couple of questions: 
<img width="1440" alt="screen shot 2017-09-06 at 2 32 37 pm" src="https://user-images.githubusercontent.com/16536421/30103441-4c5154b8-9310-11e7-9dec-0d01c559658e.png">

1) In case of rerun is the expected behavior to show the duration of the rerun for the job(s)? In that case should we make it clear it is only for the specific rerun  and not for the stage. Currently it mentions the run number but this bit can be missed/overlooked.

2) In case of reruns should we remove the "from time to time" in the detailed overview?  Is there a need here to see the other jobs in the stage or just the job(s) that have been rerun or should we show the timestamp with the date  for all the transitions?

**Comment by arvindsv** [comment]
@tinozza:

1. Yes, it is confusing. I agree that we should make it clear, for sure. Good catch.

2. Yes, I think should remove the "from time to time" part. We should continue to show the other jobs (not just the rerun ones). I'm not sure showing the date and time for each job will fit.

**Comment by tinozza** [comment]
#3586
Updated the mockup - removed the "from time to time" part.

1.**Jobs tab within the stage details page- with a job rerun** 
![image](https://user-images.githubusercontent.com/16536421/30531706-9ea58430-9c6d-11e7-9646-93e7605e2d3e.png)
2. Detailed view with actual tranisitions on clicking the detailed view link:
![image](https://user-images.githubusercontent.com/16536421/30533285-2966cc0c-9c76-11e7-8a45-b5f47de611d1.png)
Note: Removed the "from time to time" part here. 

**Link to the invision prototype:** https://invis.io/YUDAJKCG5#/251336717_stage_Details_Page_Detailed_Overlay
