### ISSUE TITLE
Single agent update API does not unset resources/environments by passing empty list

### ISSUE THREAD

**Issue by mikhail-advani** [gocd/gocd#3796]
##### Issue Type

- Bug Report

##### Summary

**API:** `PATCH` /go/api/agents/:uuid

The [update an agent API](https://api.gocd.org/17.1.0/#update-an-agent) does not allow removal of resources/environments by passing an empty array.

###### Basic environment details

* Go Version: 17.1.0 (4511-c7c379ff500a5ae70c8cd7a49f936595c6bd2d69). Documentation says that the API hasn't changed since
* JAVA Version: 1.8.0_91
* OS: Linux 3.13.0-29-generic
* Browser vendor and version (if relevant): NA

##### Steps to Reproduce

**Setup body:**
```
{"resources": ["r1", "r2"] }
```

**Update body 1:**
```
{"resources": [] }
```

1. PATCH an agent using `Setup body` specified above
2. PATCH the agent using `Update body 1` specified above

##### Expected Results

The resources of the agent should have been unset

##### Actual Results

The resources of the agent remain unchanged

##### Any other info

**Update body 2:**
```
{"resources": "" }
```

**Update body 3:**
```
{"resources": [""] }
```

1. PATCH an agent using `Setup body` specified above
2. PATCH the agent using `Update body 2` specified above. The resources of the agent get unset
3. PATCH an agent using `Setup body` specified above
4. PATCH the agent using `Update body 3` specified above. The resources of the agent get unset

**Comment by ketan** [comment]
The root cause of this bug here the behavior of `deep_munge` in rails. Details at https://github.com/rails/rails/issues/13420#issuecomment-31023144
