### ISSUE TITLE
Does GoCD support "ci skip" tag to skip a build?

### ISSUE THREAD

**Issue by jcalonso** [gocd/gocd#3810]
##### Issue Type

- Question / Feature proposal

##### Summary

Does GoCd has a way to skip a build similar to Gitlab Ci `[skip ci]` ?
https://docs.gitlab.com/ee/ci/yaml/#skipping-jobs

**Comment by arvindsv** [comment]
Not in the built in materials, but it is possible in material plugins.

**Comment by vishwanatharondekar** [comment]
If someone could answer this here that would be great https://groups.google.com/forum/#!searchin/go-cd/skip$20ci%7Csort:date/go-cd/Pw8N5W7eR40/Ds2659eQAAAJ
