### ISSUE TITLE
GET Environment config API returning 500 instead of 404

### ISSUE THREAD

**Issue by ByteFlinger** [gocd/gocd#3812]
##### Issue Type
- Bug Report

##### Summary
I am trying to query for an existing Environment using the `GET /go/api/admin/environments/:environment_name` API but when I supply an environment that does not exist I get a 500 back when using `application/vnd.go.cd.v2+json` as Accept header however when using `application/vnd.go.cd.v3+json` it seems to work as intended. 

This seems to not be according to documentation https://api.gocd.org/current/#get-environment-config

###### Basic environment details

* Go Version: `17.8`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.10.0-693.1.1.el7.x86_64`

##### Steps to Reproduce

1. Login to Go using curl and save local cookies
`curl --fail -sS -H 'Accept: application/vnd.go.cd.v4+json' -c gocd-cookies --cacert gocd_ca_bundle.crt -u username:password -X GET https://gocd.example.com/go/api/agents`
2. Attempt to get a non-existant pipeline
`curl --fail -sS -H 'Accept: application/vnd.go.cd.v2+json' -b gocd-cookies --cacert gocd_ca_bundle.crt -X GET https://gocd.example.com/go/api/admin/environments/environment.that.does.not.exist`

##### Expected Results
Get a 404 since the environment does not exist

##### Actual Results
Get a 500 with the following error in the logs

##### Log snippets

```
==> /var/log/go-server/go-server.log <== 2017-09-04 11:42:56,035 FATAL [qtp1512981843-20] Rails:? - NoMethodError (undefined method `setOrigins' for nil:NilClass): app/controllers/api_v2/admin/environments_controller.rb:80:in `load_environment' lib/jetty_weak_etag_middleware.rb:35:in `call' lib/catch_json_parse_errors.rb:8:in `call'
```

##### Any other info
It seems that using v3 accept header `vnd.go.cd.v3+json` perform the correct behaviour even though that is not documented

**Comment by ketan** [comment]
> It seems that using v3 accept header vnd.go.cd.v3+json perform the correct behaviour even though that is not documented

@GaneshSPatil confirmed that there was an in-progress, unreleased v3 api that he was working on, that has been yanked in 17.9, so v3 requests for environment api will fail the next release.

**Comment by varshavaradarajan** [comment]
Fixed by https://github.com/gocd/gocd/pull/3813 . @ByteFlinger , you can verify the fix with the latest experimental build from https://www.gocd.org/download/?experimental=true. We will be making a release shortly.
