### ISSUE TITLE
Change logging framework from log4j 1.2

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#3814]
##### Issue Type

- Feature enhancement

##### Summary

We've pretty much moved off log4j 1.2 to slf4j for the `Logger` interface, except for these 3 places:

- [`LogConfigurator`](https://github.com/gocd/gocd/blob/6aef9b9b1414cff903ac3b60826d012d52f2abe1/base/src/com/thoughtworks/go/logging/LogConfigurator.java)

    This one merely reloads the log configuration automatically when things change, something that comes out-of-the-box with log4j2 and logback

- [`DefaultPluginLoggingService`](https://github.com/gocd/gocd/blob/6aef9b9b1414cff903ac3b60826d012d52f2abe1/plugin-infra/go-plugin-infra/src/com/thoughtworks/go/plugin/infra/service/DefaultPluginLoggingService.java)

    Removing this would mean either:

    - (preferred approach) all logs go to the same file (`go-server.log`), probably with a marker containing the plugin ID

   -OR-

    - we can apply a NDC/MDC+filter to send plugin logs to a single `plugin.log` file

    For developers building plugins, they can always specify additional appenders to filter their own log files to help ease development. For end users wanting to diagnose problems they may either grep for plugin markers in the main log, or use a (temporary) appender for a specific plugin.

- [`AgentOutputAppender`](https://github.com/gocd/gocd/blob/6aef9b9b1414cff903ac3b60826d012d52f2abe1/agent-process-launcher/src/com/thoughtworks/go/agent/AgentOutputAppender.java)

    This currently uses log4j's `RollingFileAppender` because there's no other library (that I'm aware of) which offers a similar capability, but this can be replaced with another (custom?) implementation fairly easily without affecting any end-user configuration.

Since log4j1.2 has been EOL'ed for the past 2 years and we've suffered a few bugs to classloader leaks along with issues like [this](#3521).

The choice of logging frameworks leave us with 2 possible options logback(preferred) and log4j2, both of which will require a migration of the `log4j` properties that are shipped with GoCD. For most users who do not change these files, the change in the underlying framework will not affect an upgrade. For users who have customized the log4j.properties files for some reason, they will have to "migrate" over their changes to a newer (xml?) format that's compatible with log4j2 or logback.

Both these logging frameworks allow specifying an XML configuration, with support for `<including/>` other configuration files. This opens up another interesting possibility that allows GoCD to ship with a hard-wired log config file (on the classpath, so users cannot mess with it), with the possibility of specifying an include in a known location `<include file="${go.config.dir}/log.xml"/>` which allows users to pretty much override everything in the main log file and add more appenders, and loggers as needed.

/cc @arvindsv @jyotisingh WDYT?

**Comment by jyotisingh** [comment]
`DefaultPluginLoggingService` : Given that none of the log4j classes are exposed to the plugins, the  only thing that they have access to is [com.thoughtworks.go.plugin.api.logging.Logger](https://github.com/gocd/gocd/blob/fd43db656e9d9b32d7ab9be1785208f346e9b1be/plugin-infra/go-plugin-api/src/com/thoughtworks/go/plugin/api/logging/Logger.java#L29) and the methods on that class, changing the logging library to something else shouldn't affect/break the plugins.  Am I missing something? The only thing an end user of a plugin can change today is the log-level via a [system-property](https://github.com/gocd/gocd/blob/fd43db656e9d9b32d7ab9be1785208f346e9b1be/base/src/com/thoughtworks/go/util/SystemEnvironment.java#L697) which we could continue to use for whichever logging framework we choose to move to.  So, there is no need for a migration for this case.

`AgentOutputAppender`:
>This currently uses log4j's RollingFileAppender because there's no other library (that I'm aware of) which offers a similar capability, but this can be replaced with another (custom?) implementation fairly easily without affecting any end-user configuration.

I guess Logback has its own implementation of RollingFileAppender, and ofcourse log4j 2 would have one as well.

Migration (if we choose to do it) is going to be some work. If we dont, it would be a breaking change that we need to callout. Also, many users seem to be parsing their logs for things, we need to ensure that we use exactly the same pattern that is being used today, else it breaking their scripts/tools which consume the logs.

**Comment by ketan** [comment]
https://github.com/gocd/gocd/blob/6aef9b9b1414cff903ac3b60826d012d52f2abe1/plugin-infra/go-plugin-infra/src/com/thoughtworks/go/plugin/infra/service/DefaultPluginLoggingService.java#L95-L109

@jyotisingh I'm familiar with the api logger interface and how it works. My point about `DefaultPluginLoggingService` were lines shown above, that directly invoke the log4j api and and setup log4j appenders for these specific loggers. WRT these lines, we have the two options:

- add a marker to the logger to make the log statement look like this

    ```
    2017-09-04 20:31:17+05:30 [Thread-0] [main] WARN [plugin-com.example.myplugin] - some log message
    ```

-OR-

- write all log messages with a specific filter to a separate appender —

    ```xml
    <!-- logback example -->
    <appender name="plugin-appender" class="ch.qos.logback.core.rolling.RollingFileAppender">
      <filter class="com.thoughtworks.gocd.PluginLogFilter" />
      ...
    </appender>
    ```

    ```xml
    <!-- log4j example, assumes an `isPlugin` added to MDC in `DefaultPluginLoggingService` -->
    <ContextMapFilter onMatch="DENY" onMismatch="NEUTRAL" operator="or">
      <KeyValuePair key="isPlugin" value="true"/>
    </ContextMapFilter>
    ```

**Comment by jyotisingh** [comment]
Yes, thats exactly I was trying to say. While the above code uses log4j api, it is not really available for endusers to tinker around. So, we should be able to change this anything else we like that may be configured programmatically or via a config file from classpath.

> add a marker to the logger to make the log statement look like this
> 20:31:17+05:30 [Thread-0] [main] WARN [plugin-com.example.myplugin] - some log message

Something like this would make it difficult for users when they are looking for some debug logs wrt to a specific plugin. Also, on larger instances, the go-server logs tends to get written more often, so chances are they will miss many of the plugin related log entries.

Sure, we could add the filter you are talking about, but we should be able to retain the existing behavior too, right? I haven't tried it out myself, but the logback API seems very similar to log4j, so it seems almost all of that code that you pointed out can be ported over to logback retaining the existing behavior, no?

**Comment by ketan** [comment]
> Sure, we could add the filter you are talking about, but we should be able to retain the existing behavior too, right? I haven't tried it out myself, but the logback API seems very similar to log4j, so it seems almost all of that code that you pointed out can be ported over to logback retaining the existing behavior, no?

I suppose so. I'll submit a PR to port to logback keeping existing behavior

**Comment by rajiesh** [comment]
Verified on 17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1)
