### ISSUE TITLE
JSONify Pipeline schedule and pause APIs

### ISSUE THREAD

**Issue by mikhailadvani** [gocd/gocd#3816]
##### Issue Type

- Feature enhancement

##### Summary

The pipeline schedule and pause APIs are form based. For consistency and better usability, a JSON based API would be better

**Comment by mikhailadvani** [comment]
Can look to pick it up but would like to discuss the solution first

**Comment by varshavaradarajan** [comment]
Closing as it will be taken care of with https://github.com/gocd/gocd/issues/4076
