### ISSUE TITLE
Plugin remains in a block state when multiple agents are having same `elasticAgentId`

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3828]
##### Issue Type

- Bug Report

##### Summary

Plugin remains in a block state when multiple agents are having same `elasticAgentId`

As part of `ServerPing` plugin makes a disable agent call to server with list of elastic agent ids. In case of multiple agents are having same UUID, server fails to disable the agents and throws an `IllegalStateException`. This will prevent plugin to delete old container and plugin can not start new containers.

### Possible fix:

1. Put check on agent registration, if agent with same `elasticAgentId` exist then do not register the new agent.
2. Ignore the agents with duplicate `elasticAgentId` and disable the other agents.

### Action needed at plugin

Make sure plugin always creates container with `unique id`

**Comment by GaneshSPatil** [comment]
@jyotisingh -- Yes. There won't be multiple agents with the same elasticAgentId. So this issue won't happen.
