### ISSUE TITLE
32 bit Agent on 64 bit machine - Go Version 16.9.0-4001

### ISSUE THREAD

**Issue by Nagendira** [gocd/gocd#3835]
Bug Report

When calling an exe passing the location of a XML file as input to the  agent  version 16.9.0-4001 running on 64 bit Windows, getting below error

Error Loading XML File: 
Could not find a part of the path 'C:\Windows\system32\config\systemprofile\AppData\Local\Temp\ybwczkdv.tmp'.

I referred https://github.com/gocd/gocd/issues/199 and followed the steps, but issue still persists. The exe and the input xml is placed in D:\ of the agent. Calling the exe like D:\FOLDER\SAMPLE.exe "D:\SAMPLE\TEST.xml" , it works perfectly from command line of the agent machine, but when called from Go, I'm getting the error.

* Go Version: 16.9.0 (4001-0af23a08078987314cb93012762688f1fd60680d)
* JAVA Version: 1.8.0_102
* OS: SERVER: Linux 3.10.0-514.el7.x86_64
* OS: AGENT : Windows server2008 R2 Standard -64 bit OS
* Browser vendor and version (if relevant):  Mozilla firefox 55.0

**Comment by arvindsv** [comment]
Closing as stale.
