### ISSUE TITLE
[Rails 4 issue] Issue with pipeline locking

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#384]
1) Enable pipeline locking for a pipeline. Let one of the stages of the pipeline fail. Pipeline on the dashboard starts showing error as below. Also the lock icon is not visible

![pipeline-locking issue](https://cloud.githubusercontent.com/assets/6175869/3720589/010f63e8-1657-11e4-8eda-7352c2ddc3e1.png)

**Comment by arvindsv** [comment]
@rajiesh: Can this be closed? I would think so.
