### ISSUE TITLE
go-agent list disappers from the UI

### ISSUE THREAD

**Issue by benkisan** [gocd/gocd#3844]
##### Issue Type
- Bug Report

##### Summary
The go-agent list in the UI go blank and we wont be able to work on any of the agent like assigning resources etc

##### Environment
Production Build 

###### Basic environment details

* Go Version:  Go Server Version: | 17.3.0 (4704-3c7d8f7e5d78e46f72ff1194bb322c6b5d72a90f)
* JAVA Version: 1.8.0_51
* OS: Linux 2.6.32-504.23.4.el6.x86_64
* Browser vendor and version (if relevant): NA

##### Steps to Reproduce

1. Clone a Linux go Agent
2. Start the Agent [ Don't delete the guid]
3. When the new agent starts successfully, the Agent list in the GO goes missing.
4. Now even after stopping the newly created agent/ restarting the GO server, the problem remains. 

##### Expected Results
There shouldn't be any impact on the agent list. 

##### Actual Results
All the agents dis-appeared 

##### Possible Fix
UI

##### Log snippets

```
 FATAL [qtp999661724-6576104] Rails:? - 

ActionController::UrlGenerationError (No route matches {:action=>"update", :controller=>"api_v4/agents", :uuid=>""} missing required keys: [:uuid]):

  app/controllers/application_controller.rb:196:in `url_for'

  app/presenters/api_v4/agent_representer.rb:27:in `AgentRepresenter'

  app/presenters/api_v3/base_representer.rb:102:in `to_hash'

  app/presenters/api_v3/base_representer.rb:102:in `to_hash'

  app/controllers/api_v4/agents_controller.rb:27:in `index'

  lib/jetty_weak_etag_middleware.rb:35:in `call'

  lib/catch_json_parse_errors.rb:8:in `call'
```
![screen shot 2017-09-12 at 10 21 43 pm](https://user-images.githubusercontent.com/4407446/30338298-d20988a8-9808-11e7-8481-0de6965dbded.png)

##### Any other info

Please call me @  9845234517 so that i can share a screen and we can debug it better.

**Comment by benkisan** [comment]
This issue seems to happen when there is a conflicting GUID, mostly happens when the the agents are clones VMs. But identifying this is not possible. The way we got the list was to shutdown all the agents and get back the list.

**Comment by arvindsv** [comment]
@benkisan I'm closing this. I tried it on 17.11 and 17.12 (experimental). What happens is that the cloned agent which starts later shows up in the agents tab. If you can try in 17.11 and can still see it happening, I'll happily reopen it. Thank you.

**Comment by benkisan** [comment]
The issue was still existing in 17.11. Had to follow the below steps to fix the issue. 

1. Stop all the registered Go agents [ available in the config.xml ], [which included our production deployment agents ] 
2. Restart the go server 
3. identify the agents which are getting registered back to the server by refreshing the agent list.[This needs to be acquired within very short span (less than 2 minutes after server restart) as the corrupt agent will make the list disappear.
4. Stop all the agent which got listed in the above step. 
5. Repeat 2,3,4 steps until we have none of the agents getting registered to GO.
6. Post final restart start registering the agents Fresh from the UI. 

It was a downtime of almost 9 hours for us to get this back to shape, which was very tiring and bought the thought of moving out to Jenkins as we don't see much of community support with GO. 

This is what we have decided now to make sure we don't face this problem again. 

1. Any agent which gets into the system will do an auto-register to the server with his hostname+IP as the server name assuming that the "unique" hostname among the multiple VM's was the real cause for the issue.

**Comment by benkisan** [comment]
<img width="1512" alt="screen shot 2017-12-09 at 10 25 08 pm" src="https://user-images.githubusercontent.com/4407446/33797531-f5ce6198-dd2f-11e7-9df2-29433dce7999.png">
