### ISSUE TITLE
Consolidate Material definitions to single location or allow different settings for same repo in each pipeline.

### ISSUE THREAD

**Issue by PredatorVI** [gocd/gocd#3848]
One of the challenges when configuring GoCD is the handling of a material (e.g., Git material) that is shared across multiple pipelines.

Since all material definitions have to seemingly be the same for every pipeline that needs it, it becomes a challenge to change a setting across all definitions, usually resulting in an error similar to the following:

> Material of type Git (git@gitlab:continuous-deployment.git) is specified more than once in the configuration with different values for the autoUpdate attribute. All copies of this material must have the same value for this attribute.

Maybe there are use cases I'm not seeing where the material definition could be different in some way on eachpipeline.  But from my current experience, they are all the same but if I need/want to try a different setting, I have to manually edit the config.xml and change ALL definitions.

I'm also experiencing conflicts while trying to use the the JSON pipeline as code plugin and am tripping over trying to translate the material settings from XML to JSON to avoid the annoying conflict issues.

Being required to define the material on a per-pipeline basis, but forcing all materials of the same name to have identical settings seems inefficient at best.

There are two ways to potentially look fix this:

1. Centralize material definitions to a single common global location and then allow them to be referenced or linked in a pipeline.
2. Allow the same material to have different options on a per-pipeline basis.

Hoping this can be made a little easier to manage and keep straight.

Thanks

**Comment by chadlwilson** [comment]
Related to #1033, #1080, #3880
