### ISSUE TITLE
Support for configuring parameters in the Configuration repository Extension 

### ISSUE THREAD

**Issue by PredatorVI** [gocd/gocd#3849]
I'm looking at using the JSON pipeline as code plugin to migrate my pipeline definitions to a JSON format in GIT.  However, we use "parameters" to make the tasks more generic.  As an example, each deployment pipeline has the following (or simliar) defined:
```
      <params>
        <param name="DEPLOY_ENV">acc</param>
      </params>
```
Subsequently this value is passed as a parameter or command-line argument to the various tasks using #{DEPLOY_ENV}.  However, because this feature isn't supported for some reason, It is complicating our pipeline definitions.  

It would be nice to have this supported and available ultimately through the pipeline as code mechanisms.

**Comment by rajiesh** [comment]
Verified on 17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1)

**Comment by varshavaradarajan** [comment]
The json expected by the GoCD server from any config repo plugin is - 

```
{
  "group": "...",
  "name": "...",
  "label_template": "...",
  "template": null,
  "enable_pipeline_locking" : false, # boolean
  "parameters": [
    {
      "name": "param",
      "value": "parameter_value"
    }
  ],
  "mingle": {
    "base_url": "...",
    "project_identifier": "..."
  },
  "tracking_tool": null,
  "timer": {
    "spec": "..."
  },
  "environment_variables": [],
  "materials": [
    ...
  ],
  "stages": [
    ...
  ]
}
```
#### Referencing an existing template 

```
{
  "group": "...",
  "name": "...",
  "label_template": "...",
  "enable_pipeline_locking" : false,
  "template": "existing-template",
  "parameters": [
    {
      "name": "param",
      "value": "parameter-value"
    }
  ],
  "materials": [
    ...
  ]
}
```
