### ISSUE TITLE
Get rid of intermediate config xmls stored while config migration

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#3854]
##### Issue

While introducing the config migrations for auth config, we left behind `config-before-migration-91.xml` and `config-before-migration-92.xml` in case users had to rollback. Now that there haven't been any reports of failing migrations, we can remove these files.

**Comment by ketan** [comment]
I've asked @bdpiparva to address this.

**Comment by bdpiparva** [comment]
Yes, I will do this as part of removing password file support from core.

**Comment by rajiesh** [comment]
Verified on 17.12.0 (5605-89a5ade1e9497ffc255dfa744476466c09beca06)
