### ISSUE TITLE
New plugin-settings page issues.

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3866]
- [x] Footer on new plugin-settings page is broken

![screen shot 2017-09-18 at 10 29 45 am](https://user-images.githubusercontent.com/7871209/30529603-a0dd5df6-9c5c-11e7-8497-912b0b5b3d09.png)

**Comment by bdpiparva** [comment]
- [ ] Bundled plugin icon is not same as the old view

![screen shot 2017-09-18 at 1 38 13 pm](https://user-images.githubusercontent.com/7871209/30533381-ad7c2e60-9c76-11e7-8935-e54c7a3c06d5.png)

- [ ] In old view, Plugin with error is already expanded. Can we keep the same behaviour on new page?

### Old view with error message

![screen shot 2017-09-18 at 1 34 31 pm](https://user-images.githubusercontent.com/7871209/30533461-0e253586-9c77-11e7-865d-b2a850bd589a.png)

### New plugin settings page

![screen shot 2017-09-18 at 1 34 10 pm](https://user-images.githubusercontent.com/7871209/30533465-135b39ce-9c77-11e7-9055-586137dcdd9a.png)

**Comment by varshavaradarajan** [comment]
Pipeline group admins should not see the settings icon.

**Comment by GaneshSPatil** [comment]
@varshavaradarajan -- I guess everyone should see all the icons and buttons, and depending on the privileges, the buttons/icons should be **disabled/enabled**.

**Comment by varshavaradarajan** [comment]
@GaneshSPatil , makes sense only for group admins. 👍

**Comment by rajiesh** [comment]
The settings gear icon is showing up for all the plugins now,

<img width="1421" alt="screen shot 2017-10-27 at 1 30 37 pm" src="https://user-images.githubusercontent.com/6533924/32093744-2bbb04a0-bb1b-11e7-9a73-979a8b487941.png">


Also for plugins with no icon provided, we can use the jigsaw icon we had in old page rather than the question mark. Talked to @naveenbhaskar he is fine with that

**Comment by varshavaradarajan** [comment]
@rajiesh, @naveenbhaskar - We still cannot rely on the plugin icon to determine whether the plugin is bundled. 

@rajiesh - https://github.com/gocd/gocd/pull/3956 to fix the gear icon.

**Comment by rajiesh** [comment]
Gear icon issue is fixed. Just need to fix the default icon to be used for plugins without icons. Will keep it open for that. Will plan it done in 18.1

**Comment by rajiesh** [comment]
Closing this issue as there was no user mention about the need for better default icon for plugins, will reopen if any such request comes in
