### ISSUE TITLE
Windows agent auto registers without resource tags 

### ISSUE THREAD

**Issue by crohacz** [gocd/gocd#3871]
##### Summary
When trying to register a windows Go agent with a linux Go Server, the agent auto registers with the Go Server successfully but it is not tagged with the resources specified in the autoregister.properties file. 

###### Basic environment details

* Go Version: `17.7.0`
* JAVA Version: `1.8.0_131`
* OS: `Linux 4.9.38-16.35.amzn1.x86_64`

* Go Agent Version: `17.7.0`
* OS: `Windows 2012R2 provided by Amazon AWS`

##### Expected Results
The agent should appear with a resource tag named `windows` 

##### Actual Results
The agent appears with no resource tag

##### Log snippets
After we manually enable the agent, the go-agent.log file shows that the agent has successfully registered: 
```
2017-09-18 20:25:04,864 [loopThread] INFO  go.agent.service.SslInfrastructureService:88 - [Agent Registration] Starting to register agent.
2017-09-18 20:31:37,220 [loopThread] INFO  go.agent.service.SslInfrastructureService:190 - This agent is now approved by the server.
2017-09-18 20:31:37,252 [loopThread] INFO  go.agent.service.SslInfrastructureService:120 - [Agent Registration] Retrieved registration from Go server.
2017-09-18 20:31:37,252 [loopThread] INFO  go.agent.service.SslInfrastructureService:128 - [Agent Registration] Stored registration for cert with hash code: *************************** not valid before: Thu Jan 01 00:00:00 UTC 1970
2017-09-18 20:31:37,283 [loopThread] INFO  go.agent.service.SslInfrastructureService:92 - [Agent Registration] Successfully registered agent.
2017-09-18 20:31:37,283 [loopThread] INFO  thoughtworks.go.agent.AgentHTTPClientController:105 - About to get cookie from the server.
2017-09-18 20:31:37,455 [loopThread] INFO  thoughtworks.go.agent.AgentHTTPClientController:108 - Got cookie: *******************************
```
* Additionally, the go-server.log file shows no errors.

##### Code snippets/Screenshots
This is the powershell script being run on the GoCD agent to autoregister it with the server.
```
<powershell>
Import-Module bitstransfer
start-bitstransfer -source https://download.gocd.org/binaries/17.7.0-5147/win/go-agent-17.7.0-5147-jre-64bit-setup.exe -destination C:\go-agent-setup.exe
C:\go-agent-setup.exe /S /SERVERURL=`"https://xx.xx.x.xxx:8154/go`"
mkdir "C:\Program Files (x86)\Go Agent"
mkdir "C:\Program Files (x86)\Go Agent\config"
mkdir "C:\Program Files (x86)\Go Agent\logs"
echo "agent.auto.register.key=**********************” > "C:\Program Files (x86)\Go Agent\config\autoregister.properties"
echo "agent.auto.register.resources=windows" >> "C:\Program Files (x86)\Go Agent\config\autoregister.properties"
echo "agent.auto.register.hostname=win-agent-sandbox" >> "C:\Program Files (x86)\Go Agent\config\autoregister.properties"
net start "Go Agent"
</powershell>
```
When the agent appears in GoCD, it appears in a state “pending” as shown below, however, we expected to appear as already enabled and in the state "idle": 
<img width="1593" alt="screen shot 2017-09-18 at 1 30 04 pm" src="https://user-images.githubusercontent.com/4735087/30564057-9867b1f0-9c78-11e7-8fce-63f39d713f85.png">

**Comment by twjjwxzq** [comment]
This still seems to be happening with GoCD 19.5.0, running on Windows Server 2019 (AWS EC2 instance).
My GoCD installation directory is `c:\go\agent`, and I create the following autoregistration config:

**Comment by ketan** [comment]
@ankitsri11: mind taking a look, please?

**Comment by ankitsri11** [comment]
@twjjwxzq I tried replicating it locally but couldn't able to do so.

I followed below steps:

Step 1: Created `C:\agent` as the GoCD agent directory.

Step 2: Created a `config` folder inside the agent directory (C:\agent) and added the `autoregister.properties` file with below content.

```
agent.auto.register.key=agentAutoRegisterKey
agent.auto.register.resources=windows
agent.auto.register.environment=qa-one
agent.auto.register.hostname=Agent-Windows-qa-one
```

Step 3: Ran below script

```
Invoke-RestMethod https://download.gocd.org/binaries/19.5.0-9272/win/go-agent-19.5.0-9272-jre-64bit-setup.exe -OutFile go-agent.exe
.\go-agent.exe /S /SERVERURL=`"https://my.server.url/go`" /D=C:\agent
```
I could see that the agent was able to start and register successfully with the server. I could also see it picked the resource and environment specified in the autoregister.properties file. 

Can you let me know the state of the agent from the GoCD agent page once it is started? Is it showing idle or pending? If it is pending, you might need to store `autoregister.properties` under config folder inside the agent directory.

**Comment by twjjwxzq** [comment]
@ankitsri11 Apologies, just resolved it, turned out to be a problem with file encoding. I was actually creating the `autoregister.properties` file through a terraform script, within a EC2 instance powershell userdata script like so:

```
mkdir C:\go\agent\config
$goagent_autoregister_config = @'
agent.auto.register.key=${var.go_agent_autoregister_key}
agent.auto.register.resources=windows
agent.auto.register.environments=qa-one
agent.auto.register.hostname=Agent-Windows-qa-one
'@
$goagent_autoregister_config | Out-File -FilePath C:\go\agent\config\autoregister.properties
```

The agent wasn't picking this up despite it looking correct when manually inspected on the Windows instance with Notepad. I modified the script to encode with ASCII with the `Out-File` command instead:

```
mkdir C:\go\agent\config
$goagent_autoregister_config = @'
agent.auto.register.key=${var.go_agent_autoregister_key}
agent.auto.register.resources=windows
agent.auto.register.environments=qa-one
agent.auto.register.hostname=Agent-Windows-qa-one
'@
$goagent_autoregister_config | Out-File -FilePath C:\go\agent\config\autoregister.properties -Encoding ASCII
```

and this now works :)

**Comment by arvindsv** [comment]
Thanks for getting back and confirming that, @twjjwxzq. Closing this.
