### ISSUE TITLE
Updating auto_update material attribute is not possible in the API when multiple pipelines depends on the material

### ISSUE THREAD

**Issue by drewsonne** [gocd/gocd#3880]
##### Issue Type

- Bug Report
- Feature enhancement

##### Summary

When toggling the `auto_update`/`Poll for new changes` flag on a material for a git repository, if the material is shared by other pipelines:
 - in the gui this is will result in an error being returned informing the user that all git materials of this endpoint must be updated at the same time
 - in the api, the update will not appear to perform a change. That is, when calling `PUT /go/api/admin/pipelines/:pipeline_name` to change the `auto_update` flag, the response pipeline config object will discard any changes for the `auto_update` which were provided in the request.
 - `auto_update` must be the same for all vcs's within a gocd installation, and all materials must have the `auto_update` value updated atomically. As there is no way to atomically update the value for all materials, through the rest API, it is not possible to update the `auto_update` value for a specific material if it is shared by pipelines.

##### Environment

This can be reproduced with a base gocd installation.
Instructions for provisioning an environment can be found in the gist:

https://gist.github.com/drewsonne/1325943c5d8f194a261b48887bac279a#file-0-start-docker

###### Basic environment details

* Go Version: `17.10.0 (5380-05598d88fd4dabdde1184faa4fbffc5f9406d0dc)`
* JAVA Version: `1.8.0_130`
* OS: `Linux 4.9.41-moby`
* Browser vendor and version (if relevant): API based so not applicable

##### Steps to Reproduce

Can be reproduced with the details found in the gist:
https://gist.github.com/drewsonne/1325943c5d8f194a261b48887bac279a#file-1-gocd-issues-recreation

##### Expected Results
An api endpoint should be available to change the polling method for all materials with a common material type. 

##### Actual Results
It is not possible to modify the `auto_update` attribute  through the API if a material is depended on by two or more pipelines

##### Possible Fix
I assume that modifying the polling method on a per material per pipeline basis is not possible, but perhaps having a PUT endpoint in the materials api (https://api.gocd.org/current/#materials) to allow toggling of the autoUpdate value in the config xml a manner similiar to `https://api.gocd.org/current/#pause-a-pipeline`

##### Log snippets
```
"Material of type Git (https://github.com/gocd/gocd) is specified more than once in the configuration with different values for the autoUpdate attribute. All copies of this material must have the same value for this attribute."
```

**Comment by drewsonne** [comment]
I would like to have a try (again) at a PR on the gocd core repo.

My draft plan would be:

1. Modify the material object as such:
```json
{
    "description": "URL: https://github.com/gocd/gocd, Branch: master",
    "fingerprint": "03c8d2a131154436b6ef2d621c6f773837481aaea8c5c1bb9c0cb9b5bc64a2f1",
    "type": "Git",
    "auto_update": false
}
```

2. Add a PATCH method/resource which takes a subset of the material object:
```bash
curl 'https://ci.example.com/go/api/materials/:fingerprint' \
  -u 'username:password' \
  -H 'Accept: application/vnd.go.cd.v4+json' \
  -H 'Content-Type: application/json' \ 
  -X PATCH \
  -d '{
    "auto_update": false
}'

And the backend implementation would update the Polling value for all repositories matching the fingerprint.

Does this seem like a reasonable method

**Comment by ketan** [comment]
I think your general approach is good - a patch endpoint for a material.

However the existing material api is in not versioned. So you may want to consider building a versioned materials API from scratch with the usual CRUD stuff.

It might be of help to just open another issue to address a material API, than just a limited update API.

**Comment by maheshp** [comment]
The way I look at it, SCM materials today are not an independent entity and they are part of the pipeline. In that case, having material endpoints to update materials would end actually updating multiple pipeline which doesn't look right to me.

Ideally, having global SCM materials(similar to pluggable `scms`) with crud API makes sense to me but that would be a bigger change.

**Comment by ketan** [comment]
> Ideally, having global SCM materials(similar to pluggable scms) with crud API makes sense to me but that would be a bigger change.

I believe that change makes sense — it's much simpler to do the config migration (we've done that for elastic profiles for e.g.), however making a change in the config UI is an altogether different matter.
