### ISSUE TITLE
Gear icon should not appear on a config repo pipeline in VSM

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#3881]
##### Issue Type

- Bug Report

###### Basic environment details

* Go Version: `17.10.0`

##### Steps to Reproduce

1. Login as admin
2. View the VSM for a pipeline which has the config repo pipeline as an upstream/downstream

##### Expected Results

Gear icon should not be present on the config repo pipeline

##### Actual Results

Settings icon is present on the config repo pipeline

**Comment by FredrikWendt** [comment]
It would be great to show something, such as the repo, file and changeset/commit that the current pipeline definition came from.
