### ISSUE TITLE
Material Cloning Stalls On Single Agent

### ISSUE THREAD

**Issue by rightisleft** [gocd/gocd#3885]
##### Issue Type

- Bug Report

##### Summary

Ive had my agents running normally for a few weeks. Today i started seeing 1 of my agents with a stalled build:

```
[go] Job Started: 2017-09-22 16:09:33 UTC
[go] Start to prepare fishAPI/57/CommitHandler/1/CompileAPI on 2e2462b9b5ec [/go]
[go] Cleaning working directory "/go/pipelines/fishAPI" since stage is configured to clean working directory
[go] Start to update materials.

[go] Start updating files at revision XXXXXXXXXXX from https://fish_charles:******@gitlab.com/qbu/api.git
Cloning into '/go/pipelines/fishAPI'...
```

Each agent is a docker container, the server is a docker container, they are all on the same host. I cant seem to get this pipeline to continue. Even after killing and triggering a new build i get: 

`Job fishAPI/CommitHandler/CompileAPI is currently running but has not shown any console activity in the last 32 minute(s). This job may be hung.`

The other agents are all working fine. Please advise. 
 

##### Environment

```
Go Server Information: {
Version: "17.7.0 (5147-53fdb1b15184f93966059a42429bf9ed0bfdee59)"
}
```
###### Basic environment details

* Go Version: `Go Version: 17.7.0 (5147-53fdb1b15184f93966059a42429bf9ed0bfdee59).`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.10.0-514.16.1.el7.x86_64`

**Comment by arvindsv** [comment]
If you docker exec into it, and run a `ps -ef`, what do you see? What is that git process doing?

Also, if you docker exec into it and run a `git clone`, does it work?

**Comment by arvindsv** [comment]
Closing as stale.
