### ISSUE TITLE
Show manual gates in VSM

### ISSUE THREAD

**Issue by tinozza** [gocd/gocd#3889]
Scope:
Show manual gates in b/w stages in a pipeline - in the VSM view.

Find below the option for showing manual gates in VSM.

![image](https://user-images.githubusercontent.com/16536421/30800801-d9c9f316-a1fe-11e7-8d3c-86fb7576cc45.png)

The icon represents manual gate and is highlighted for stages with manual trigger in a pipeline - For stages that are awaiting manual approval -"awaiting approval" message appears on hovering over the manual gate icon.

--------------
![image](https://user-images.githubusercontent.com/16536421/30800830-f291e458-a1fe-11e7-9b95-e34a9f89972c.png)

For stages that have been triggered manually- "approved by username/anonymous" message appears on hovering over the manual gate icon.

Please note:  The icon style is not finalized and is just representative. For icon style referencing this issue  #3872 - with proposal for different icons to show manual gate.

**Comment by eeluke** [comment]
I will reply about icons themselves on the other issue. For this issue,
behavior and design make sense to me. Thanks.

Emily

**Comment by MattRiesterer** [comment]
I'd like to see the VSM to become the main view for pipelines. Thus not only showing gates but also to be able to trigger and cancel them would be great. Also there should be a "static" URL which gives you the most recent state.

**Comment by eeluke** [comment]
@MattRiesterer This is great feedback and something we have been thinking about. We will keep you updated with any progress we make here. Thanks!
