### ISSUE TITLE
Environment agent functionality not working correctly

### ISSUE THREAD

**Issue by jaheikki** [gocd/gocd#3890]
##### Issue Type

- Bug Report

##### Summary

Two issues:
1. The static go agent I've configured in Environments section in yml (tomzo/gocd-yaml-config-plugin) will not ever appear in Environments menu in GoCD UI (=agent is not used for Environment pipelines, see figure)? Don't know if this is tomzo/gocd-yaml-config-plugin bug or GoCD bug :
![image](https://user-images.githubusercontent.com/8567508/30846623-100a4b22-a2a1-11e7-8c12-6ce4933348e8.png)

2. I have elastic go agents in use and they will be automatically set as Environment agents when looked in GoCD UI, which is strange (see figure where none of the agents are set manually). Why GoCD wants to set elastic agents as Environment agents automatically, I believe it is a bug?
![image](https://user-images.githubusercontent.com/8567508/30846757-85484fd8-a2a1-11e7-8043-b3dc5c6eb397.png)

###### Basic environment details

* Go Version: 17.10.0 (5380-05598d88fd4dabdde1184faa4fbffc5f9406d0dc)
* JAVA Version: 1.8.0_131
* OS: Linux 4.4.0-83-generic
* Browser vendor and version (if relevant): Google Chrome Version 60.0.3112.113 (Official Build) (64-bit)

##### Steps to Reproduce

For the Environment agent not visible by using tomzo/gocd-yaml-config-plugin:
1. Take plugin into use
2. Create yml like in following figure:
![image](https://user-images.githubusercontent.com/8567508/30847125-056cbf4a-a2a3-11e7-97d3-db2e8e0b1ac4.png)
3. Import pipelines and environment from yml.

For the elastic agents appearing in Environment automatically:
1. Setup GOCD using elastic agents
2. Create one static go agent and enable it in GoCD UI
3. Create 2 pipelines
4. Create environment having 2 pipelines and attach newly created static agent to it
5. Start running pipelines, expecting static agent used for running 2 pipelines attached to environment.

##### Expected Results

Expecting that one static agent would be used for running 2 pipelines attached to environment, meaning one pipeline at a time (since only one agent). So I would need to run 2 pipelines sequentially (with one static agent) and not parallelly (with 2 elastic agents).
##### Actual Results

One static go agent is not used for running 2 above mentioned pipelines sequentially, but instead of two elastic agents are used for running 2 pipelines parallelly. I would not expect elastic agents to be used for environment agents since they are not manually configured in Environment menu in GoCD UI.
##### Any other info

Do not know whether these  problems mentioned in this issue are more issues of tomzo/gocd-yaml-config-plugin, so I raised an issue in the tomzo plugin side also: https://github.com/tomzo/gocd-yaml-config-plugin/issues/42

**Comment by jaheikki** [comment]
Update:
Now that we have investigated more of this, it seems almost everything is working if configurations are created correctly :) My problem was that I had configured elastic agent in my job causing elastic agent to be used in my Environment instead of static agent. In other words the static agent configured in Environment yml (see figure above) is used correctly if job contains no elastic agent.

But one minor problem still exists related to GoCD UI:

The static agent id is not shown in GoCD UI in Enviroments tab, even the agent is:
![image](https://user-images.githubusercontent.com/8567508/31071962-bcd794c8-a76e-11e7-9072-07ea040dbad7.png)

**Comment by arvindsv** [comment]
Please check again. The UI has been changed recently.
