### ISSUE TITLE
it failed by hard code in test DiskSpaceFullCheckerTest 

### ISSUE THREAD

**Issue by qiaoliang** [gocd/gocd#3896]
##### Summary

Run tests with `./gradlew clean prepare server:test` on the machine with large space(more than 1TB), Then the tests in DiskSpaceFullCheckerTest will be failed.

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. 
2. 
3. 
4. 

##### Possible Fix

Change the number to 100T   :)

**Comment by arvindsv** [comment]
Closing as stale.
