### ISSUE TITLE
User permissions and cookie

### ISSUE THREAD

**Issue by jackTheRipper** [gocd/gocd#3899]
##### Issue Type

Bug Report

##### Summary

When you set some credentials to a user, the cookies aren't cleaned properly.

Because of it, it creates multiple redirections and makes the Gocd's UI unavailable until you cleaned manually the cookies

##### Environment

Chrome Version 61.0.3163.100 (Official Build) (64-bit)

###### Basic environment details

* Mac OS

###### Additional Environment Details

none
##### Steps to Reproduce

1. Ask a new user to login using his Gmail account
2. Grant him access to some specific roles
3 Try to login in Gocd again

##### Expected Results

We should be able to log in again in Gocd after setting the roles without having to clean up the cookies.

##### Actual Results

The browser complains about too many redirections

##### Possible Fix

clean up the browser cookies before redirecting to the login page

##### Log snippets

none

##### Code snippets/Screenshots

none

##### Any other info

none

**Comment by jackTheRipper** [comment]
This issue becomes really annoying. Any updates?

**Comment by jackTheRipper** [comment]
The new release doesn't help. The issue is still here. Will it be fixed at some point?

**Comment by maheshp** [comment]
@jackTheRipper can you let us know the plugin used for authentication. And is this issue only for a first time login?

**Comment by jackTheRipper** [comment]
Hi @maheshp, the plugin we use is the one for the OAuth with Google. It happens everytime we change / update the user roles.

**Comment by maheshp** [comment]
@jackTheRipper I was not able to reproduce this issue, need some help with reproducing it.

These are the steps I followed,
1. I am using version 2.0.0 of [Google OAuth Plugin](https://github.com/gocd-contrib/google-oauth-authorization-plugin/releases/tag/2.0.0) built using the new Authorization Plugin Endpoint. 
2. I was able to configure the plugin as per the given [instructions](https://github.com/gocd-contrib/google-oauth-authorization-plugin/blob/master/INSTALL.md)
3. Post all the configuration I am able to login to application using my google credentials.
4. Upon login a user is created(say `google_user`)  and I can see the user details in the User Summary page.
5. Now as an admin (on a different browser) I add roles to the user `google_user`.
6. As a `google_user` I am able to logout and login multiple times without deleting any of the cookies.

Please let me know the steps followed by you were different from what I have mentioned.

**Comment by jackTheRipper** [comment]
@maheshp : we are using the plugin `Google oauth authorization` for Go 17.5.0 (version 1.0.0-1)

I can try to update the plugin if you think it helps

**Comment by maheshp** [comment]
I don't think this could be an issue with plugin, anyways I tried with version 1.0.0-1 of `Google Oauth Authorization` against GoCD 17.5.0 but was not able to reproduce the issue.

Are you following the steps mentioned by me to reproduce this issue or am I missing anything?

Will you be able to check if this can be reproduced on latest GoCD 17.11.0 with the plugin version 2.0.0.

**Comment by jackTheRipper** [comment]
Hi @maheshp, sorry for being that long for coming back to you.

We upgraded our module for OAuth such as what you mentioned.

However, we are still facing this issue saying "too many redirects"

It seems that we should be redirected to "go/auth/logout" after editing the roles for a given user but it's still not happening.

Where can I find the logic in the source code for the logout in order to open a PR for fixing it?

**Comment by maheshp** [comment]
@jackTheRipper I haven't got a chance to look at this issue again, so I don't have any inputs as of now.

For pointers in code for logout functionality, there is a spring security filter which handles the logout - https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/security/GoLogoutFilter.java#L45

The filter is configured here - https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/applicationContext-acegi-security.xml#L73

This also seems related to https://github.com/gocd/gocd/issues/4247

**Comment by bdpiparva** [comment]
@jackTheRipper --- [PR#4274](https://github.com/gocd/gocd/pull/4274) has A fix for the issue. Once we have experimental build out we will let you know.

**Comment by bdpiparva** [comment]
Experimental build for this fix is available on [https://www.gocd.org/download](https://www.gocd.org/download) under **experimental** section
