### ISSUE TITLE
Custom sort order in Pipelines view

### ISSUE THREAD

**Issue by agileassistance** [gocd/gocd#39]
It would be great if we could set the display/sort order for the pipelines within a pipeline group so the layout roughly follows the way we have chained them together in the materials dependencies.

**Comment by conan** [comment]
+1 for this, we use microservices and have a lot of pipelines.  It's getting really difficult to find them on the dashboard - I have to remember what order they were created in!  We can sort the XML in the config, but that's a one-off solution and won't stay up to date.

**Comment by zmingxie** [comment]
Any updates on this feature?

**Comment by joerayme** [comment]
:+1:

**Comment by mnbittorrent** [comment]
+1

**Comment by jcastilloa** [comment]
+1 please!.

**Comment by darrenr** [comment]
+1

**Comment by thiagocotting** [comment]
+1

**Comment by geoffweatherall** [comment]
+1 please.

In a large organisation the xml is huge, and it's very beneficial to be able to sort the order within a pipeline group.

**Comment by pjreid** [comment]
+1

**Comment by patforna** [comment]
+1 not having this is rather annoying. i've triggered wrong pipelines, because their order seems to change randomly...

**Comment by 240ch** [comment]
I'm always trying to drag & drop pipelines and am disappointed every time it doesn't work.

**Comment by gawainedwards** [comment]
+1

**Comment by cnatan** [comment]
+1

**Comment by rglas** [comment]
This should be a very basic feature, how many years should it still take? :/
👍 
+1

**Comment by gpthome** [comment]
+1

**Comment by arvindsv** [comment]
Closing this. This is happening soon, as a part of: #3872, #3842 and #3704 - and those have more details and discussions.

**Comment by alcidessd37** [comment]
+1

**Comment by christabone** [comment]
@arvindsv , I've read through the threads you included above but couldn't find any mention of pipeline ordering in an upcoming release.

The closest answer I can find is your reply here: https://github.com/gocd/gocd/issues/3704#issuecomment-554987873

This leads me to believe that ordering the pipelines outside of directly editing the XML will not be implemented?

**Comment by arvindsv** [comment]
@christabone When pipelines are defined in code, as in the JSON, YAML or Groovy plugins, the display order can be controlled. See: https://github.com/tomzo/gocd-json-config-plugin#controlling-the-display-order

But for pipelines defined in XML, they can't be re-ordered. I believe this is a comment which mentions what I'm saying here: https://github.com/gocd/gocd/issues/7687#issuecomment-580658386

**Comment by christabone** [comment]
@arvindsv, thanks so much for the reply and the information, much appreciated!
