### ISSUE TITLE
GoCD API returning 404 in head but returns content

### ISSUE THREAD

**Issue by sebradloff** [gocd/gocd#3901]
##### Issue Type

GoCD API Bug

##### Summary

Using the GoCD API and checking for response status returns 404s on every request, even those that are valid and return content.

##### Environment

On GoCD server, ubuntu 16.04, GoCD server version 17.10.0 (5380-05598d88fd4dabdde1184faa4fbffc5f9406d0dc)

When the GoCD server is up and running, as well as having a user defined via password file, I can't get back a non 404.

```bash
$ curl http://localhost:8153/go/api/version -H "Accept: application/vnd.go.cd.v1+json"
{
  "_links": {
    "self": {
      "href": "http://localhost:8153/go/api/version"
    },
    "doc": {
      "href": "https://api.gocd.org/#version"
    }
  },
  "version": "17.10.0",
  "build_number": "5380",
  "git_sha": "05598d88fd4dabdde1184faa4fbffc5f9406d0dc",
  "full_version": "17.10.0 (5380-05598d88fd4dabdde1184faa4fbffc5f9406d0dc)",
  "commit_url": "https://github.com/gocd/gocd/commit/05598d88fd4dabdde1184faa4fbffc5f9406d0dc"
}

$ curl --head http://localhost:8153/go/api/version -H "Accept: application/vnd.go.cd.v1+json"
HTTP/1.1 404 Not Found
Date: Fri, 29 Sep 2017 15:12:25 GMT
Set-Cookie: JSESSIONID=mfw8kge1uznm3t9swsrkxx5z;Path=/go;Expires=Fri, 13-Oct-2017 15:12:25 GMT;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-UA-Compatible: chrome=1
Content-Type: application/vnd.go.cd.v1+json; charset=utf-8
Cache-Control: no-cache
X-Request-Id: 5312ad6c-a9e3-43b6-a071-6b8cefee57ef
X-Runtime: 0.012000
Content-Length: 0
```

###### Basic environment details

* Go Version: 17.10.0
* JAVA Version: 1.8.0_131
* OS: Linux 4.4.0-1035-aws
##### Steps to Reproduce
1. $ curl --head http://localhost:8153/go/api/version -H "Accept: application/vnd.go.cd.v1+json"

##### Expected Results
I expect to see a 200 in the head when I'm getting content back

##### Actual Results
I get a 404 resource not found

**Comment by ketan** [comment]
Changing this line to `match ..., via: %w(head get)` should do the trick. https://github.com/gocd/gocd/blob/38e7babbe60c92a36e57ae441c73bcb75990bf88/server/webapp/WEB-INF/rails.new/config/routes.rb#L272

Kind of like this line here: https://github.com/gocd/gocd/blob/38e7babbe60c92a36e57ae441c73bcb75990bf88/server/webapp/WEB-INF/rails.new/config/routes.rb#L344
