### ISSUE TITLE
Seeing error while adding user from `user summary` page

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3908]
##### Issue Type

- Bug Report

##### Summary

Trying to add ldap user from user summary page. I am seeing error  while adding a user in below mentioned scenario

1) Click on `Add User` button on on `User Summary` page
2) Search for a user
3) Select any user using radio button from list
4) Select different user from list
5) Click on `ADD USER` button

#### Result

This displays error on that model box but after refreshing that page I can see both the user added in the users list

#### Expected Result

It should add currently selected user.

**Comment by rajiesh** [comment]
Verified on 18.4.0 (6640-1fb2812cfa45eee8502e420443f2b46d81c51f98)
