### ISSUE TITLE
Pipeline-as-Code dry-run mode for PSV use

### ISSUE THREAD

**Issue by lenucksi** [gocd/gocd#3911]
##### Issue Type

- Feature proposal
- Feature enhancement

##### Summary
There's the very nice Pipeline-as-Code feature. As far as I understood it, upon change to a config repo the config chunks are picked up an attempt to merge them with the main config.xml configuration and if successful the change is made live.

Imagine the use of e.g. GitHub PRs or a review tool such as Gerrit for those said config repos. This could happen if pipelines are more complicated or have a longish value stream involving different people.
In such cases a pre-submit verification (PSV) is run on the PRs or changesets.

To be able to do PSV with such changes to config repos it would be required to get a verdict from GoCD if any given changeset / PR would result in a healthy configuration merge and change.

##### Expected Results
I would like to suggest an API endpoint that has the config changes / a changeset or PR URL / ... submitted and responds with a verdict.

**Comment by GaneshSPatil** [comment]
\cc: @marques-work @ankitsri11

**Comment by GaneshSPatil** [comment]
This is done as part of GoCD config repo preflight API https://api.gocd.org/current/#preflight-check-of-config-repo-configurations

More information can be found:
- https://api.gocd.org/current/#preflight-check-of-config-repo-configurations
- https://github.com/gocd/gocd/pull/5579
- https://github.com/gocd/gocd/issues/5175
