### ISSUE TITLE
Error message for incorrect Docker Elastic agent plugin profile configuration

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#3914]
##### Issue Type
- Feature enhancement
##### Summary

Currently, we do not have any error messages on the UI when there is some error in the elastic agent profile configured by the user. This causes the user to go back and forth into the server logs and elastic agent plugin logs to check for the errors.

For example:

1. Go-Server URL: The URL if incorrect causes the elastic agent plugin to be unable to register to the Go server. Currently, the user is unable to receive this information on UI and must check the server and elastic agent plugin logs to determine the root cause for this and rectify the same.

2. Elastic agent Docker Image: Similarly in case of an incorrect image tag provided there are no intuitive errors on the UI for the user to take corrective measures.

###### Basic environment details

* Go Version: 17.10.0
* JAVA Version: 1.8.0_131
* OS: Linux 4.4.0-93-generic
* Browser vendor and version (if relevant): Google Chrome Version 61.0.3163.100 

##### Steps to Reproduce

1.  Configure Elastic Agent (tried with docker elastic agent )
2.  Provide incorrect Go server URL
3. Configure a job to use this elastic agent profile ID
4. Check for any intuitive errors provided by Go server to rectify the error

##### Expected Results
An error should be available on the home page for user to easily identify and correct the issue

##### Actual Results
Currently, user has to check server and plugin logs to ascertain the possible errors

**Comment by GaneshSPatil** [comment]
Related to https://github.com/gocd/gocd/issues/5372

@adityasood -- can this be added to the same list?

**Comment by adityasood** [comment]
closing this, will track this as part of #5372
