### ISSUE TITLE
Running Newman from gocd

### ISSUE THREAD

**Issue by pradeepkusingh** [gocd/gocd#3921]
##### Issue Type

- Bug Report 👍 

(https://groups.google.com/forum/#!forum/go-cd)].

##### Summary

I am trying to run "newman -c demo.postman_collection --exitCode 1" and it seems GOCd can't capture the exit code valud and display pipeline failures where else it works in Jenkins.

##### Environment
Linux

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by ketan** [comment]
Closing since most information that was asked for has not been provided.

**Comment by pradeepkusingh** [comment]
Please lose it. found that I have an issue with my scripts.
