### ISSUE TITLE
BUG: GoCD.org Getting Started Page not Anchoring on Click

### ISSUE THREAD

**Issue by eeluke** [gocd/gocd#3927]
##### Issue Type

Bug

##### Summary

https://www.gocd.org/getting-started/part-1/# When clicking through left hand nav, page does not anchor based on section that has been selected. Guessing this might have to do with the code removed by @streisguth and @marques-work last week to stop the anchoring on the downloads page.

##### Steps to Reproduce

1. https://www.gocd.org/getting-started/part-1/#

##### Expected Results
User should be brought to relevant content in page when clicking on navigation on left side.

##### Actual Results
Page content remains static.

**Comment by arvindsv** [comment]
Opened issue on www.go.cd repo: https://github.com/gocd/www.go.cd/issues/692
