### ISSUE TITLE
Pipeline quick edit page: Expand appropriate accordion when there is a error.

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#3931]
##### Issue Type

- Bug Report

##### Summary

Go to Pipeline `Quick edit` page. Add two different material without specifying destination directory and save it.

That will display a error message on top saying validation failed without any contextual help.

![screen shot 2017-10-10 at 4 05 09 pm](https://user-images.githubusercontent.com/7871209/31382335-ef37ab80-add4-11e7-8d79-1e6b8d4f2f98.png)

When I expands the appropriate accordion I can see the error on `destination directory` field. This validation currently happening on server side. I think few of the validations can be done using javascript.

![screen shot 2017-10-10 at 4 05 18 pm](https://user-images.githubusercontent.com/7871209/31382428-4445d57a-add5-11e7-91a0-2568837ee982.png)

**Comment by GaneshSPatil** [comment]
Closing this issue. Will be addressed as part of designing the pipeline config SPA.
