### ISSUE TITLE
[Authorization Plugin] ReAuthenticating a logged in user returns a 404

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3936]
##### Issue Type
- Bug Report

##### Summary
Re-authenticating a logged in user returns a 404 while using a web based authorization plugin.

This can be reproduced by making a  request to `/go/plugin/<plugin_id>/authenticate`  in a logged in users session.

**Comment by bdpiparva** [comment]
https://github.com/gocd/gocd/pull/3940

**Comment by rajiesh** [comment]
Verified on 17.12.0 (5619-a6ab0a1d67176cbacde21a29f9b9b778c655e88c)
