### ISSUE TITLE
VSM changes - pending items from https://github.com/gocd/gocd/pull/3858

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#3944]
1.  As part of #3858 - we added a page header for VSM for material which includes the material url. Should we also include say branch information on that page as suggested [here](https://github.com/gocd/gocd/pull/3858/files#r144261995). Copying that comment here for ease of reading: 
> Since we are doing this, do we have enough space to display some extra info?
This shows up a URL which is definitely an improvement over what we have right now, but would be nice to see the branch info too. `MaterialConfig#getLongDescription` gives the required information for each of the materials so there is nothing new to implement if we can manage the space required to display the info.

From this PR:
<img width="901" alt="screen shot 2017-10-12 at 4 59 24 pm" src="https://user-images.githubusercontent.com/1046342/31493894-c3d6859c-af6e-11e7-8201-4e34ca63fbb2.png">

Attaching a screenshot to explain what I am proposing:
<img width="1090" alt="screen shot 2017-10-12 at 4 57 58 pm" src="https://user-images.githubusercontent.com/1046342/31493850-8f38fa9a-af6e-11e7-9b74-cb2fb2d973a8.png">

2. As part of #3858 all links to VSM have been made explicit apart from the VSM link for materials. Should we make this explicit too?
<img width="494" alt="screen shot 2017-10-18 at 12 29 26 pm" src="https://user-images.githubusercontent.com/1046342/31704779-6ef209f2-b400-11e7-9099-83c47b8ce7df.png">

**Comment by eeluke** [comment]
@jyotisingh I'm not keen on adding so much information to a header - it should be clear and simple. But I'm not sure if I understand the use case enough. Can you work with @tinozza on this to determine the best approach?

**Comment by rajiesh** [comment]
While verifying the PR #3858 noticed few places where the word `Label` is used still,

1. When a pipeline has a upstream pipeline dependency the Stage Overview and Materials tabs still show `label`

<img width="1005" alt="screen shot 2017-10-23 at 6 31 21 pm" src="https://user-images.githubusercontent.com/6533924/31890378-8bc6b590-b820-11e7-82ed-8492ddcb291a.png">

2. Pipeline Edit page (Quick Edit and Normal Edit) still shows as `Label template`

<img width="709" alt="screen shot 2017-10-23 at 6 33 38 pm" src="https://user-images.githubusercontent.com/6533924/31890452-d3b2e8f6-b820-11e7-9280-08ba5fb67751.png">

3. @arvindsv, the job properties still named as `cruise_pipeline_label`, should it continue to be so?

<img width="968" alt="screen shot 2017-10-23 at 6 36 17 pm" src="https://user-images.githubusercontent.com/6533924/31890843-364ae422-b822-11e7-9013-88ee156d2ec7.png">

**Comment by maheshp** [comment]
@rajiesh renamed `Label` to `Instance` on Stage Details page as part of #3949 
1. Overview Tab
![screen shot 2017-10-25 at 10 01 13 am](https://user-images.githubusercontent.com/1061051/31980774-8dd02a68-b96c-11e7-9b85-7a0d23be99de.png)
2. Pipeline Dependencies Tab
![screen shot 2017-10-25 at 10 01 22 am](https://user-images.githubusercontent.com/1061051/31980784-a05f3ca0-b96c-11e7-9b23-d8d1e7305f88.png)
3. Materials Tab
![screen shot 2017-10-25 at 10 01 31 am](https://user-images.githubusercontent.com/1061051/31980787-aada0c6e-b96c-11e7-9e19-fc519924b849.png)

**Comment by jyotisingh** [comment]
@maheshp , @rajiesh - Compare pipeline page would also need this change in that case.

**Comment by maheshp** [comment]
@jyotisingh my bad missed mentioning bout the compare page changes, its been renamed there as well.
