### ISSUE TITLE
CCtray does not list pipelines for users in PluginRole

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#3954]
##### Issue Type

- Bug Report

##### Summary
There are actually 2 issues with cctray authorization.

1. Pipeline group authorization can be specified for a `user` or 'role`(gocd_role/pluignRole) . While generating the cctray.xml authorization defined using the `pluignRole` is not applied. Hence  users belonging to a pluginRole which is authorized to view a pipeline_group do not get to see the pipelines. 

2. Changes to SecurityAuthConfig(Role and AuthConfig) through API does not invalidate the cctray pipeline cache. Thereby, if a user is assigned view permission for a pipeline_group through  a Role gets to view all the pipelines even after revoking the role through the API.

**Comment by rajiesh** [comment]
Verified on 17.12.0 (5605-89a5ade1e9497ffc255dfa744476466c09beca06) and working as expected
