### ISSUE TITLE
add pidfile to initscript

### ISSUE THREAD

**Issue by juliantaylor** [gocd/gocd#3957]
Please add the pidfile entry to the sysv init script provided in the debian package. 
That way systemd will create a more correct service file automatically.
When the pidfile entry is missing systemd will create a RemainAfterExit job which means the service remains active when gocd crashes. With a pidfile systemd can correctly mark the service failed.

E.g. like this for the default installation, maybe the pid location should be fixed into the `/run` folder to make it more resilient to reboots and fix the location.
```patch
--- a/installers/go-server/release/go-server.init
+++ b/installers/go-server/release/go-server.init
@@ -17,6 +17,7 @@
 
 # chkconfig: 2345 90 90
 # description: Go Server
+# pidfile: /var/lib/go-server/go-server.pid
 ### BEGIN INIT INFO
 # Provides: go-server
 # Required-Start: $network $remote_fs
```
The same applies to the agent init script.

Note that the PID_FILE variable in that same init script is incorrect, `/var/run` is only used in service mode.

Even better would of course be a proper systemd service file.

**Comment by arvindsv** [comment]
Closing. GoCD 19.7.0 and newer support systemd.
