### ISSUE TITLE
Support whitelists for pluggable scm materials

### ISSUE THREAD

**Issue by sandro-h** [gocd/gocd#3962]
##### Issue Type

- Feature enhancement

##### Summary

For standard scm materials (git, svn, etc) you can use a whitelist instead of blacklist to trigger pipelines when those files matching the pattern changed.

For pluggable scm materials this is currently not possible but would be useful e.g. for the pull request plugin when working with a monorepo project where individual modules are developed independently.

Is there a particular reason this is not supported? Would you accept a PR to enable it?

**Comment by arvindsv** [comment]
@sandro-h - I can see it being useful. Would there be a reason that it is not part of the plugin configuration (and so, controlled by the plugin) itself?

Having said that, I can't think of any reason that it should not be supported. Maybe someone else can? /cc @GaneshSPatil @bdpiparva

**Comment by sandro-h** [comment]
Hi @arvindsv,

Thanks for the response.

> Would there be a reason that it is not part of the plugin configuration (and so, controlled by the plugin) itself?

I see the following reasons not to do it per SCM plugin:
- Why duplicate the logic (even if it's fairly simple)?
- If a plugin needs more advanced filtering based on its domain, then it can still provide that.
- There is already a blacklist option for SCM plugins so allowing to invert that like with the standard materials would be consistent, IMO
- Having it in core gocd allows for easy configuration with the YAML configrepo plugin. SCM Plugin-specific properties cannot currently be specified in YAML.

**Comment by arvindsv** [comment]
@sandro-h I agree about not duplicating it. And the rest of your comment.

I didn't realize that you were talking specifically about whitelists, and that [blacklists are already supported](https://github.com/gocd/gocd/blob/10d4f4da8a0e4e8f89fd98b47978bc321b158dc1/config/config-server/resources/cruise-config.xsd#L462-L474). `invertFilter` is not an option for scm materials only. I don't see why they should not.

Unless @GaneshSPatil and @bdpiparva have any objections, I think a PR would be appreciated.

Link to some [dev docs](https://developer.gocd.org/current/2/2.3.html), in case you need them.

**Comment by sandro-h** [comment]
@arvindsv Thanks, yes that's what I meant. My initial post wasn't 100% clear about only the _whitelist_ specifically missing :-) I'll get back to you once I have a PR.

**Comment by dziemba** [comment]
Any update on this?

It seems that if you specify a `whitelist` with an SCM material, it gets parsed as a blacklist instead. That's very confusing.

**Comment by arvindsv** [comment]
@dziemba I don't think anyone has opened a PR or anything related to this, as far as I know.

**Comment by dziemba** [comment]
This is still relevant. If there is no intention on fixing this ever, I'm happy to close this though.

**Comment by maheshp** [comment]
Done as part of https://github.com/gocd/gocd/pull/8523
