### ISSUE TITLE
[Feature enhancement] Pipeline created via UI depending on a pipeline configured yaml file

### ISSUE THREAD

**Issue by remy-tiitre** [gocd/gocd#3972]
##### Issue Type
- Feature enhancement

##### Summary

We have a practice that all build and test pipelines have been written in an yaml and commited to the same repository as source code. But Deploy pipelines have been set up via UI. We would like to make those deploy pipelines dependent on build/test/release pipelines but GoCD does not allow that right now. Or to be more precise it is possible to set it up like that via Pipeline Quick Edit functionality but it will experience git merge conflicts later and official documentation sais that its not supported.

###### Basic environment details

* Go Version: 17.11.0
* JAVA Version: 8u151
* OS: CentOS 7

##### Any other info
I was just wondering that Templates and Parameters integration has been implemented in 17.11.0, maybe its not that difficult to add the support for the materials dependencies between server xml and git repo configuration as well

**Comment by arvindsv** [comment]
Hi @remy-tiitre. Unfortunately, this cannot be done. It is a design decision taken early on (see "Limitations" in [this comment](https://github.com/gocd/gocd/issues/1133#issuecomment-109785886)).

The design decision I mention is: "The config XML file cannot be invalid, even if the external config repo cannot be found/resolved".

This will break that principle. @tomzo or @jyotisingh might have more thoughts, but that's what I remember. So, I'm closing this for now. Thank you.
