### ISSUE TITLE
Improve material url heuristic for webhooks.

### ISSUE THREAD

**Issue by joharohl** [gocd/gocd#3973]
##### Issue Type

- Feature enhancement

##### Summary
The webhook integration with services like GitHub and Gitlab are a bit too restrictive in it's material url heuristic. Materials defined with e.g. `ssh://...` cannot be triggered via a webhook. As far as I can tell, nonstandard ports (80, 443 for http(s) or 22 for ssh ) will not work as well.

###### Basic environment details

* Go Version: `17.11.0`

##### Steps to Reproduce

E.g:
1. Add `test-repo` to gitlab and configure the webhook to gocd.
1. Configure a pipeline using a material pointing to `test-repo` using url: `ssh://git@<xyz>:10022/test-repo.git`
2. Push to said repo.

##### Expected Results
The pipeline should be triggered. Giving result: `OK!` in the webhook response.

##### Actual Results
Pipeline is not triggered. Giving result: `No matching materials!` in the webhook response.

##### Possible Fix
It all comes down to the heuristic in [/server/webapp/WEB-INF/rails.new/app/controllers/api/web_hooks/web_hook_controller.rb](https://github.com/gocd/gocd/blob/f72cdb4d7d456cb27394cea2f42b8d367f2772a5/server/webapp/WEB-INF/rails.new/app/controllers/api/web_hooks/web_hook_controller.rb#L21). 

I know it's really hard to guess urls, but could we at least add the `ssh://...` urls as they are pretty common? Parsing for custom ports is doable, but the list of combinations get's pretty long. A possiblilty to support custom ports would be to provide a method which each webhook subclass can use to give the heuristic a few more urls. Gitlab does provide both the http and ssh urls in it's webhook payload:

    "git_http_url": "https://<host>:<port>/<group>/<repo>.git",
    "git_ssh_url": "ssh://git@<host>:<port>/<group>/<repo>.git",

Ideally, the heuristic should be documented in the API documentation as well.

**Comment by ketan** [comment]
Do you want to submit a PR?

**Comment by joharohl** [comment]
Yeah, I can give it a go.

**Comment by ketan** [comment]
> I know it's really hard to guess urls, but could we at least add the ssh://... urls as they are pretty common? Parsing for custom ports is doable, but the list of combinations get's pretty long. A possiblilty to support custom ports would be to provide a method which each webhook subclass can use to give the heuristic a few more urls. Gitlab does provide both the http and ssh urls in it's webhook payload:
> 
> "git_http_url": "https://<host>:<port>/<group>/<repo>.git",
> "git_ssh_url": "ssh://git@<host>:<port>/<group>/<repo>.git",
> Ideally, the heuristic should be documented in the API documentation as well.

Please note that this implementation was a first-attempt at getting something out there so we can gather feedback. This is exactly the feedback we are looking for so we can improve the endpoints.

I suppose allowing implementations to add heuristic urls would be acceptable, so would anything you'd like to add to the API documentation. The API documentation for webhooks [is here](https://github.com/gocd/api.go.cd/tree/master/source/includes/materials) in case you'd like to make improvements to it.

Thank you.

**Comment by joharohl** [comment]
Ok. Thanks for the feedback.

The webhooks are an awesome first step. We can convert most of our materials to use Https URLs. It's just a few of them were we need to use SSH for pushing changes to the repos. And unfortunately we use a nonstandard SSH port.

We are really liking the other changes in the latest version as well. Keep up the good work!

**Comment by DavidWylie** [comment]
If you are changing this file could you add support for the gitlab user also or even better a username that can be set in the server config.

**Comment by ketan** [comment]
Are you referring to basic auth username for http(s) clones?

**Comment by DavidWylie** [comment]
Im refering to the git user on the gitlab server used in the ssh connection as part of the git operations in gocd.
e.g. use:
"git_ssh_url": "ssh://<git_user>@<host>:<port>/<group>/<repo>.git",
instead of 
"git_ssh_url": "ssh://git@<host>:<port>/<group>/<repo>.git",

or add gitlab@<host> to the list.

Thanks
