### ISSUE TITLE
Allow configRepos to be non autoUpdateable

### ISSUE THREAD

**Issue by zach-dunton-sf** [gocd/gocd#3980]
##### Issue Type

- Feature enhancement

##### Summary

When trying to set a config repository material to be autoUpdate="false" I get an error like the one below. 

```plain
1+ errors :: Configuration repository material cam_redirector must have autoUpdate enabled;;
```
This would be useful for repositories such as github with webhooks where the updates are triggered instead of polled.

##### Possible Fix

Allow plugin ScmMaterial to be autoUpdate=false for configRepos

**Comment by maheshp** [comment]
@zach-dunton-sf there was some discussing around it earlier with @tomzo. Links to the discussion.
https://gitter.im/gocd/gocd?at=59faef9d32e080696e560bfb
https://gitter.im/gocd/gocd?at=59faf0735a1758ed0f7c4219

To summarise the conversation,
> It is mandatory to ensure server always polls the latest configuration from repo.
> Some corner cases in which turning off auto_update will have bad consequences:
> - when somebody deletes the flyweight folder with the checkout and then server restarts, there is no mechanism that will get the latest checkout. And missing config from repo causes invalid merged config.
> - when server was down, then someone pushes changes, which break things.

**Comment by tomzo** [comment]
@zach-dunton-sf do you really want `autoUpdate=false` or just the [webhooks for config repos](https://github.com/gocd/gocd/issues/2193)?

**Comment by zach-dunton-sf** [comment]
@tomzo That seems like it will solve my problem. I thought I had tried that, but had not. Thanks
