### ISSUE TITLE
GO_SERVER_PORT environment variable is not honored

### ISSUE THREAD

**Issue by EbenZhang** [gocd/gocd#3982]
##### Issue Type

- Bug Report

##### Summary

After upgraded to v17.11.0, GO_SERVER_PORT environment variable is not honored.

###### Basic environment details

Go Server Version: | 17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1)
JVM version: | 1.8.0_102
OS Information: | Windows 10 10.0
Usable space in artifacts repository: | 503 GB
Database schema version: | 1708001
GOCD Service command line: `E:\GoServer\cruisewrapper.exe -s E:\GoServer\config\wrapper-server.conf`

###### Additional Environment Details

See attached:  [goenv.txt](https://github.com/gocd/gocd/files/1444684/goenv.txt)

##### Steps to Reproduce

- Make sure port 80 is not occupied
- Make sure the logon user for GOCD Server Service has the admin permission
- Start the GOCD service

##### Expected Results
The server is listening on port 80

##### Actual Results
The server is listening on port 8153

##### Any other info
It was working well before I upgraded it to v17.11.0

**Comment by akshaydewan** [comment]
Hi @EbenZhang, which version of Go Server were you using before upgrading to v17.11.0? (This seems to be broken in v17.10 as well)

**Comment by varshavaradarajan** [comment]
Closing as 17.12.0 was released.

**Comment by EbenZhang** [comment]
Tried on 17.12.0 (5626-cb7df2ffe421e43f2a682a7a323cb3a3e30734cc).  It still doesn't work.

**Comment by ketan** [comment]
In 17.12.0 We've changed how port numbers assignment works on windows:

Please edit the file `config/wrapper-properties.conf` in the server install directory and add the following to override the defaults:

```
wrapper.java.additional.9=-Dcruise.server.port=8153
wrapper.java.additional.10=-Dcruise.server.ssl.port=8154
```

**Comment by EbenZhang** [comment]
it works with the configuration in the wrapper-properties.conf.  Thanks.

**Comment by EbenZhang** [comment]
@ketan every time after upgraded the config file gets overwritten to default port. Is there a way to keep the port settings?

**Comment by ketan** [comment]
@EbenZhang — can you confirm what file you've edited again. You're supposed to edit the file `config/wrapper-properties.conf` and it is not supposed to be overwritten — since it's not packaged with the gocd server installer. Editing the `wrapper-server.conf` will be cause the file to be overwritten on an upgrade.

**Comment by EbenZhang** [comment]
ya, I changed the setting in `wrapper-server.conf`. The `wrapper-properties.conf` works fine. Thanks.
