### ISSUE TITLE
[Websocket] Console log does not appear if the job is assigned late.

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#3986]
##### Issue Type

- Bug Report

##### Summary
For the time frame between job scheduling and job assignment, the console-log file won't be available.
Websocket waits for the console log file to be available within 10sec (500ms _delay_ * 20 _times_), if not, the ConsoleLogSender closes the connection with message saying `waiting for console log to exist for job123` error code: `4004`.
And expects the client to handle the reconnect logic.

[here](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/websocket/ConsoleLogSender.java#L78-L84) is the current check

##### Steps to Reproduce

1.  Disable all agents.
2. Trigger a pipeline and open job details page
3. Open new tab and enable agents.
4. On Job details page, the job finishes, showing the status on top right corner, but the console log still says, `Waiting for console logs…`

##### Expected Results
Job details page should show "Console logs" for the current job

##### Actual Results
Job details page shows message saying `Waiting for console logs…`

##### Possible Fix
Retry connection if job logs does not exists and job is still in progress.

**Comment by arvindsv** [comment]
I think this happens outside of websockets too.

**Comment by GaneshSPatil** [comment]
@arvindsv -- this issue is specific to websocket.
There are other issues where job details pages always shows `Waiting for console logs..` - #3650 and #3773

**Comment by arvindsv** [comment]
Those are different. But, I might have seen this same issue then, since you mentioned that console log in 17.11 was using websockets by default (mistakenly).

**Comment by rajiesh** [comment]
Verified on 17.12.0 (5621-158fee2729f0a07475594782e6a5716ac3154f8a)
