### ISSUE TITLE
Elastic agents status report page: property content - text alignment

### ISSUE THREAD

**Issue by tinozza** [gocd/gocd#3996]
##### Issue Type

- Bug Report

##### Summary

The properties in status report page is center aligned currently. The text would read better if it is left-aligned. 
Existing:
![image](https://user-images.githubusercontent.com/16536421/32595686-d36114ca-c556-11e7-9ebe-20efcbe7c7fc.png)

Proposed:
![image](https://user-images.githubusercontent.com/16536421/32595631-a2f0c52e-c556-11e7-869c-c5333a03d041.png)
Note: Color of the table header has been changed to be make it consistent with the rest of the application.

**Comment by bdpiparva** [comment]
@tinozza --- The UI is comming from plugin so I have created issue on plugin repo https://github.com/gocd-contrib/docker-swarm-elastic-agents/issues/51.
