### ISSUE TITLE
Go is also a programming language

### ISSUE THREAD

**Issue by ianlancetaylor** [gocd/gocd#4]
Since you routinely call this Go in your description, I wanted to make sure you are aware that there is a popular programming language called Go (http://golang.org) (nearly 10,000 projects on Github use the Go programming language).  Since your project is not a programming language this is not necessarily an issue--after all, there is also a board game called Go--but I wanted to make sure you are aware of it.  Thanks.

**Comment by JohnMorales** [comment]
I think that decision is unfortunate.
