### ISSUE TITLE
upgrade jetty from 6.1.23 (Apr, 2010) to 9.2.3.v20140905 (September 2014)

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#400]
http://mvnrepository.com/artifact/org.mortbay.jetty/jetty
6.1.23

http://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server
9.1.5.v20140505

**Comment by mrmanc** [comment]
It would be awesome if this could be an upgrade to [Jetty 9.2.6](http://mvnrepository.com/artifact/org.eclipse.jetty/jetty-server/9.2.6.v20141205), as it includes [Slf4jRequestLog](http://download.eclipse.org/jetty/9.2.6.v20141205/apidocs/org/eclipse/jetty/server/Slf4jRequestLog.html), which we should be able to use to output Jetty’s request log over the network using syslog by configuring the [SyslogAppender](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/net/SyslogAppender.html) in log4j.properties.

This would facilitate all sorts of performance / stability monitoring :+1: :chart_with_upwards_trend: :vertical_traffic_light:

**Comment by arvindsv** [comment]
I think it was also in 9.1.5. See [this](http://grepcode.com/file/repo1.maven.org/maven2/org.eclipse.jetty/jetty-server/9.1.5.v20140505/org/eclipse/jetty/server/Slf4jRequestLog.java?av=f).

**Comment by ketan** [comment]
Tested, verified works on 15.1.0(1825-4f2609acf598d7).
