### ISSUE TITLE
Whitelist/blacklist does not get evaluated if pipeline has an upstream pipeline as material depending on the same SCM repo

### ISSUE THREAD

**Issue by rkrisztian** [gocd/gocd#4004]
##### Issue Type

Feature enhancement

##### Summary

I've got 3 projects in the same repository, each having its own pipeline for build. One project is a dependency of the other two. I would like to use the filtering feature to skip building a leaf project if it has not changed, except for its dependency.

###### Basic environment details

* Go Version: 17.8.0

##### Any other info

My problem is fully described and already discussed here: https://github.com/tomzo/gocd-yaml-config-plugin/issues/50

(I opened that ticket first because I wasn't sure where to do it.)

**Comment by arvindsv** [comment]
[Continuing from there] I think this is being affected by fan-in. This is documented [here](https://docs.gocd.org/current/advanced_usage/fan_in.html#limitations).

Might be a good time to mention the community-maintained [git-path-material](https://github.com/TWChennai/gocd-git-path-material-plugin), which seems to have been created for this monorepo case. But, I can't say I've used it.
