### ISSUE TITLE
Is the VNC option necessary on Go Agents? 

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4005]
##### Summary

Currently, while starting the go agent via  https://github.com/gocd/gocd/blob/master/installers/go-agent/release/agent.sh , if VNC is set to Y, an attempt is made to start the vnc server with display number 3. 

Issues: 

1. Suppose vnc is not installed, this script proceeds with starting the agent anyway. 
2. Suppose the go user doesn't have the vnc password set yet, then, it gets prompted and unless someone enters the password, the go agent does not get started
3. Suppose the display is not available, the script proceeds with starting the agent.

While 1 and 3 require some configuration to be done outside of go and 2 hinders automation, is it necessary to take care of starting the vnc server  while starting the go agent? 
I think that this option was provided in case the agent was running some tests which needed a display. But the argument is that anything that is needed on the agent is to be maintained completely by the user. We don't install any other package or configure anything else while starting the go agent, so why should vnc be an exception? Why start the vnc server when the user has to anyway take care of making sure its starts properly? 

If we do get rid of this, the users who have been using this won't get affected until they upgrade the bootstrapper. Thoughts?

**Comment by arvindsv** [comment]
I don't mind getting rid of it. It does seem out of place.

**Comment by ketan** [comment]
# Alternatives to the `VNC` flag

This flag was introduced in the configuration file to 

(a) allow the GoCD agent process to be able to access an X11 window system for running UI tests and
(b) to allow users to connect to the running vnc server remotely to diagnose problems

This added an additional overhead on having to **interactively** setup a VNC password the first time VNC was executed by the GoCD agent.

It is now recommended that users wrap their tasks with the [`xvfb-run`](http://manpages.ubuntu.com/manpages/xenial/man1/xvfb-run.1.html) command as follows:

**Before:**

```bash
rake ci:jasmine
```

**After:**

```bash
xvfb-run rake ci:jasmine
```
