### ISSUE TITLE
Upgrade `roar` gem to latest version

### ISSUE THREAD

**Issue by yankurk** [gocd/gocd#4006]
##### Issue Type
Upgrade

##### Summary
Currently the project uses `roar` version `1.0.1`. The latest version is `1.1.0`. There could be possible breaking changes upon upgrade as described in their [Changelog](https://github.com/trailblazer/roar/blob/master/CHANGES.markdown).

**Comment by varshavaradarajan** [comment]
I guess we won't be doing this. Since we are moving the APIs to java.
