### ISSUE TITLE
Get Pipeline Config API failed to find pipeline for remote configured pipelines

### ISSUE THREAD

**Issue by victor-sim** [gocd/gocd#4008]
##### Issue Type
- Bug Report

##### Summary
Get Pipeline config API does not work for pipeline as a code plugin pipelines, once agent status has been changed.

###### Basic environment details
* Go Version: 17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1)
* JAVA Version: 1.8.0_102
* OS: Windows Server 2012 R2 6.3
* Not related with Browser

##### Steps to Reproduce
1. Create a pipeline with 'json.config.plugin' plugin
2. Try Get Pipeline config API for the created pipeline (GET `/go/api/admin/pipelines/:pipeline_name`)
    - It works
3. Update any on agents status (Disable agent, or delete agent), or update any Elastic Agent Profile
4. Try Get Pipeline config API for the same pipeline again (GET `/go/api/admin/pipelines/:pipeline_name`)
    - It does not work returns
> {
>   "message": "Either the resource you requested was not found, or you are not authorized to perform this action."
> }
5. Update any on Config XML (or update nothing but save unchanged configuration file)
6. And then re-try Get Pipeline config API for the same pipeline again
    - It works again

##### Expected Results
`/go/api/admin/pipelines/:pipeline_name` API should work consistently.

##### Actual Results
`/go/api/admin/pipelines/:pipeline_name` API does not work fine for Pipelines as a code pipelines whenever something changed on agent status

**Comment by rajiesh** [comment]
Verified on 18.1.0 (5932-46938d88757632f7c20e899e682181862bf4296b)
