### ISSUE TITLE
IE11 blank notifications tab

### ISSUE THREAD

**Issue by ngolikov** [gocd/gocd#4013]
##### Summary

UI browser bug - notifications tab under preferences is blank. Reproducible using IE11.

##### Environment

Go version: 17.8.0
Java: openjdk version "1.8.0_141"
OS: Linux 3.10.0-514.16.1.el7.x86_64
Browser: IE11

##### Steps to Reproduce

Navigate to "Preferences" page using any user.

##### Expected Results
Notifications tab should show "email settings" and "create notification filter" UIs

##### Actual Results
Blank page is shown

##### Code snippets/Screenshots
![screen shot 2017-11-14 at 2 56 56 pm](https://user-images.githubusercontent.com/2593819/32802494-2fe6555c-c94e-11e7-8702-e2efbe1307ff.png)

**Comment by GaneshSPatil** [comment]
IE11 and previous IE versions are not supported by GoCD.
Closing this issue as `WONT-FIX`
