### ISSUE TITLE
Prevent unauthorized agents to register to a GoCD server

### ISSUE THREAD

**Issue by wlsf82** [gocd/gocd#4016]
##### Summary
Today it is possible that anyone that knows the address of a GoCD server to register an agent on it, even if it will not be enabled.
The idea here is to prevent such behavior for security reasons.

###### Basic environment details
* Go Version: `17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1)`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.13.0-123-generic`

##### Steps to Reproduce
Refer to the bellow Gitter conversation:
```
Walmyr @wlsf82 15:27
Hi. I have a question that maybe someone here could answer.
Is it possible to prevent that someone registers an agent to my GoCD server? I mean, if someone knows the address where the server is running, he or she can create an agent and point it to my server.
This person will not be able to enable such agent because he or she will not be able to log in, but anyway, the agents' Dashboard would be polluted, and this seems not to be a very secure thing.
What do you suggest to avoid it?

Ketan Padegaonkar @ketan 15:35
no way to avoid it.
one could possibly have a feature where only agents with an auto-register key can register, anything else is not able to register, or show up in the UI (or anywhere else, for that matter)

Walmyr @wlsf82 15:38
Can I create an issue on Github for it? I really think such thing should be prevented.

Ketan Padegaonkar @ketan 15:38
it may be useful to some.
```

##### Possible Fix
Have a feature where only agents with an auto-register key can register, anything else is not able to register, or show up in the UI, as suggested by @ketan.

**Comment by jyotisingh** [comment]
@wlsf82 - Setting `max.pending.agents.allowed` to `0` would disallow addition of agents in pending state, it leads to the same result that you are looking for from this feature. Adding the feature that you request makes sense but I guess someone would get to it only if there is enough interest from the community. Meanwhile you should be able to make use of the above JVM flag.

**Comment by wlsf82** [comment]
@jyotisingh, my agents are replaced every day by a schedule and they automatically assigned to the server. Should I expect any issue in such behaviour if I set `max.pending.agents.allowed` to `0`?

**Comment by jyotisingh** [comment]
@wlsf82 - that depends on how do `they automatically assigned to the server`?
As long as you use `autoregister.properties` or the auto-registration feature in GoCD, you would be sorted.

**Comment by wlsf82** [comment]
@jyotisingh, yes, I'm doing it with `autoregister.properties` and property `agent.auto.register.key=<my-key>`.

**Comment by jyotisingh** [comment]
If that's what you do for all your agents then you should safely be able to set `-Dmax.pending.agents.allowed=0`. The only thing to keep in mind is this completely turns off scope for manual registration, but I guess that's exactly what you wanted.

**Comment by wlsf82** [comment]
Yeah, that's what I need. Thanks!

**Comment by wlsf82** [comment]
@jyotisingh, one last question, how do I set the `-Dmax.pending.agents.allowed=0` JVM flag?

**Comment by jyotisingh** [comment]
For Linux:
Update `/etc/default/go-server` to add:
```
GO_SERVER_SYSTEM_PROPERTIES="$GO_SERVER_SYSTEM_PROPERTIES -Dmax.pending.agents.allowed=0"
```
