### ISSUE TITLE
Duplicated logs at the console on GoCD v17.11.0 on Safari and Firefox browsers

### ISSUE THREAD

**Issue by wlsf82** [gocd/gocd#4018]
##### Issue Type
- Bug Report

##### Summary
On v17.11.0 of GoCD, when running a pipeline and visualizing the logs in the console on Safari (or Firefox) browser, they get duplicated.
Note: After refreshing the page, the duplications are gone.
Note 2: This is not perceived in Chrome, for instance.

###### Basic environment details
* Go Version: `17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1)`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.13.0-123-generic`
* Browser vendor and version: `Safari version 11.0.1 (13604.3.5)`

##### Steps to Reproduce
1. Run any pipeline on Safari (or Firefox) with GoCD v17.11.0 and start looking at the console tab of the running job.

##### Expected Results
No duplications should be displayed in logs of the console.

##### Actual Results
Duplications are displayed in the logs of the console.
Note: Sometimes duplications are displayed while the job is running and sometimes they are only displayed after the job is finished.

##### Screenshots
<img width="695" alt="screen shot 2017-11-16 at 10 22 03" src="https://user-images.githubusercontent.com/2768415/32886947-a66a834a-cac2-11e7-9600-2fc6537752b1.png">
<img width="497" alt="screen shot 2017-11-16 at 10 21 56" src="https://user-images.githubusercontent.com/2768415/32886948-a6828f26-cac2-11e7-98c5-de394a77c64f.png">

##### Other info
Notes from Gitter conversation:
```
Ketan Padegaonkar @ketan 10:37
what browser are you on, BTW?

Walmyr @wlsf82 10:38
I’m using Safari. Let me test on Chrome

Ketan Padegaonkar @ketan 10:38
that might be a culprit.
safari is known to have several issues with websockets (which is what accidentally got turned on in 17.11)

Walmyr @wlsf82 10:40
yeah, it doesn’t seem to happen on Chrome

Vierbergen Tim @VeeTeeDev 10:41
I think I was on Chrome or Firefox
not sure
but I'll check later

@wlsf82 — we can reproduce the issue on firefox. Its due websocket connection dropping off while the console logs are streamed.
`The connection to wss://build.gocd.org/go/console-websocket/<BUILD_URL>?startLine=0 was interrupted while the page was loading.`
```

**Comment by GaneshSPatil** [comment]
@wlsf82 -- This issue has been fixed as part of PR: https://github.com/gocd/gocd/pull/4024

**Note**: In GoCD version `17.11.0` browser WebSockets were turned on by default. (issue: https://github.com/gocd/gocd/issues/3993) which is fixed as part of PR: https://github.com/gocd/gocd/pull/3995. 

To verify this fix, please download the latest experimental build at https://www.gocd.org/download (`Version: 17.12.0-5590` or above) and enable browser WebSockets. 

To enable browser WebSockets toggle:

```
curl 'https://<GO_SERVER_URL>/go/api/admin/feature_toggles/browser_console_log_ws_key'  
        -u 'USERNAME:PASSWORD'  
        -H 'Confirm: true'  
        -H 'Content-Type: application/json'  
        -X POST 
        -d '{"toggle_value": "on"}'
```

**Comment by wlsf82** [comment]
@GaneshSPatil, the issue seems not to be fixed in version 17.12.0 (5597-ab1ccf83aa90dfa3fc916ca892592e6db81717fc).
I've tested in both Safari and Firefox, and I'm still getting duplicated results.

**Comment by GaneshSPatil** [comment]
Hello @wlsf82 -- can you provide the **detailed steps** and an example `cruise-config.xml` to reproduce the same issue? 
It would be helpful if you attach some screenshots of the build details page with duplicated logs along with page footer with sensitive information masked out(as footer contains the exact GoCD version, which will be useful to reproduce the same issue).

**Comment by wlsf82** [comment]
Here we go, @GaneshSPatil. Let me know if you need anything else.

**Steps to reproduce:**
Simply starts a pipeline and follow a job being executed on the console tab.
When the job is finished the duplicated logs can be seen.
Note: after refreshing the page there are no more duplications.

**Example of our `cruise-config.xml` file:**
```
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="100">
  <server artifactsdir="artifacts" purgeStart="5.0" purgeUpto="10.0" jobTimeout="5" agentAutoRegisterKey="<key-here>" webhookSecret="<webhookSecret-here>" commandRepositoryLocation="default" serverId="<serverId-here>" tokenGenerationKey="tokenGenerationKey-here">
    <security>
      <authConfigs>
        <authConfig id="foo" pluginId="cd.go.authentication.passwordfile">
          <property>
            <key>PasswordFilePath</key>
            <value>/foo/bar/htpasswd</value>
          </property>
        </authConfig>
      </authConfigs>
    </security>
  </server>
  <scms>
    <scm id="<scmId-here>" name="example-repo">
      <pluginConfiguration id="github.pr" version="1" />
      <configuration>
        <property>
          <key>url</key>
          <value>git@github.com:example/example.git</value>
        </property>
      </configuration>
    </scm>
  </scms>
  <config-repos>
    <config-repo pluginId="yaml.config.plugin" id="<yamlConfigPluginID-here>">
      <git url="git@github.com:yaml-example/example-pipelines.git" />
    </config-repo>
  </config-repos>
  <pipelines group="pull-requests" />
  <pipelines group="merges-to-master-branch" />
  <pipelines group="deployments" />
  <pipelines group="periodic" />
  <environments>
    <environment name="example">
      <agents>
        <physical uuid="<agentId-here>" />
      </agents>
    </environment>
  </environments>
  <agents>
    <agent hostname="ip-here" ipaddress="ip.here" uuid=""<agentId-here>" />
  </agents>
</cruise>
```
<img width="255" alt="gocd duplicated logs" src="https://user-images.githubusercontent.com/2768415/33485750-dd03c8c6-d6a7-11e7-93b8-90d6e9072e09.png">

**Comment by GaneshSPatil** [comment]
Hello @wlsf82,

We weren't able to reproduce the duplicate console log issue with the provided cruise config. We think that it's been fixed as part of GoCD version `17.12.0`.

can you verify whether the issue is reproducible on the latest stable version ([`v18.1.0`](https://www.gocd.org/download)) of GoCD ?

**Comment by wlsf82** [comment]
HI @GaneshSPatil, this still happens on v18.1.0.

**Comment by ketan** [comment]
Does this happen with all console logs, or console logs for particular jobs?

**Comment by wlsf82** [comment]
All of them

**Comment by ketan** [comment]
Can you click on the "raw" link on one of the console logs and attach it here (or put it in a gist?)

**Comment by wlsf82** [comment]
![screen shot 2018-02-06 at 13 15 27](https://user-images.githubusercontent.com/2768415/35859333-eb61402a-0b3f-11e8-8449-7fdc3437906e.png)

**Comment by wlsf82** [comment]
https://gist.github.com/wlsf82/d74c06a482feb2c75a3794ac749d1737

**Comment by ketan** [comment]
Thank you, I can confirm this is reproducible on all browsers (not just safari as originally reported).

For now there's a feature toggle to turn this behavior off and we recommend that users use that toggle while we investigate the issue.

**Comment by wlsf82** [comment]
I knew the issue happens on Firefox and Safari, on Chrome it was not reproducible.
But good to know that you are working on it.
What is the feature flag and how do I set that?

**Comment by ketan** [comment]
> What is the feature flag and how do I set that?

https://github.com/gocd/gocd/issues/4018#issuecomment-346527844

Set the `toggle_value` accordingly.

**Comment by wlsf82** [comment]
I'll wait for the release that fix this since this is not critical.
