### ISSUE TITLE
Override keep count for pipeline artifacts

### ISSUE THREAD

**Issue by thomasf1234** [gocd/gocd#4022]
##### Issue Type
- Feature proposal

##### Summary

Hi, 

Currently if I have a pipeline that produces artifacts (pipeline name ApplicationX for example) then disk space will fill without limit as this pipeline is constantly triggered - 1000 pipeline runs produces 1000 artifacts. 

Can a "keep count"  configuration setting please be introduced for a pipeline that can override this default behaviour? 

##### Example usage:

"keep count" defaults to unlimited
"keep count" can be set to a positive integer

Setting "keep count" to 10 for ApplicationX in the above scenario keeps only the artifacts for pipeline counters 991 - 1000

##### Reason

Effectively manage disk space for pipelines 

Daily pipelines creating large artifacts.

##### Notes

I am aware of the ability for go-server to keep disk above N(MB), but this does not offer control (a particularly large artifact may force removal of smaller overshadowed artifacts that might be business essential)

**Comment by d-led** [comment]
If keeping one artifact helps, I've written a small service to trigger the pipeline if a pre-configured artifact has been GC'ed https://github.com/d-led/gorebuild

**Comment by thomasf1234** [comment]
Thank you for your response. I do not think this is a viable solution to my problem because there are pipelines where I am required to keep 30 for example, and which cannot be removed at all -  a retrigger after artifact removal would not be sufficient. I believe your solution would be very useful for pipelines that are idempotent.

**Comment by d-led** [comment]
Perhaps, publishing into a binary repository, such as Nexus OSS is a better strategy, as these are optimised for such logic and can run custom cleanup scripts
