### ISSUE TITLE
Plugin Settings API - Error codes

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4032]
##### Issue Type

- Bug Report

##### Summary

Currently the plugin settings API returns 404 if the plugin is not present and the same error code if the plugin is present, but the plugin settings is not found for it. 

##### Possible Fix

- Return 424 when the plugin is not found
- Return 404 when the plugin settings is not found for a specific plugin. 

This does not need a new version of the plugin settings API. Since the entity and response remain the same.

**Comment by maheshp** [comment]
Wondering if the API should return a `404` in absence of the plugin. I think the settings update or create should return an error in absence of plugin. But fetching plugin settings in absence of the plugin should be fine as GoCD maintains a record of the settings.

Thoughts?

**Comment by ketan** [comment]
In the current situation, a 404 can indicate 2 things:

- plugin is missing
- plugin settings for plugin do not exist

So reason for this issue was to see what status codes we can possibly use to disambiguate the two.

**Comment by varshavaradarajan** [comment]
Yes, but the plugin settings get doesn't have to be ambiguous in the first place. It can either get the *settings* or not. Currently, post or update returns 422 when the plugin in not available to perform the necessary validations. And that should be good enough?

**Comment by ketan** [comment]
Maybe I understood this wrong, but wasn't the issue that you'd have to do a `get` when a user hits the "edit" button and a 404 at that point is what is ambiguous, so you'd not know if the form should be rendered in the first place, because a 404 can also indicate that the plugin is not present?

**Comment by varshavaradarajan** [comment]
@ketan, on the plugins SPA, if the plugin is present, then it is listed. If someone wants to configure plugin settings for the first time, then the get plugin settings API returns a 404 for the absence of the *plugin settings*. We go ahead with creating the form and rendering the view at this point. Suppose the plugin goes missing during the time of saving the plugin settings, then we show a 422 with the message - `Save failed, plugin not found` or something to that effect.  

So, for the plugins page, two APIs come into picture. The plugin info API (which lists the plugin if present) and the plugin settings API (which shows the settings if present). Now, the plugin settings API need not have to return a 404 at the time of doing a GET operation while showing the modal if the plugin is not present since the settings is stored in the db. 

The same goes for the plugin settings API used alone (not on the SPA) since the get does not need to have the plugin present. 

Does that make sense or did I muddle it up? 😅

**Comment by varshavaradarajan** [comment]
@maheshp - we need the plugin info to be loaded to display the plugin settings. Otherwise, we don't know which property is secure. So, if the plugin is missing but the plugin settings is present in the db, we still can't show the plugin settings. So, we'd need to differentiate between plugin being missing and plugin settings missing. So, as per the original error codes, 424 if the plugin is missing and 404 if the plugin settings missing sounds good?
