### ISSUE TITLE
Incorrect logs shown for pipeline

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#4033]
##### Issue Type

- Bug Report

##### Summary

After chasing for a long time why an older git revision was executed in a pipeline it turned out that the correct one was executed, but the build detail page shows the incorrect logs, namely one from an older run.

##### Environment

https://gist.github.com/JorritSalverda/7ddf2cd2ad9dd649ab2847f25daea6ad

###### Basic environment details

* Go Version: `17.11.0`
* JAVA Version: `1.8.0_131`
* OS: `Linux 4.4.64+`
* Browser vendor and version (if relevant): `Chrome for Mac Version 62.0.3202.94 (Official Build) (64-bit)`

##### Expected Results

The logs from the actual pipeline run to show

##### Actual Results

Older logs are shown

**Comment by ketan** [comment]
Did you purge history, without purging the artifact dir?

**Comment by arvindsv** [comment]
Can you provide some more details about this? For instance, are you saying that you go to a page like: `http://your-server/go/tab/build/detail/PIPELINE/1/STAGE/1/JOB` and you see logs from `http://your-server/go/tab/build/detail/OTHER_PIPELINE/1/STAGE/1/JOB` ? Or from: `http://your-server/go/tab/build/detail/PIPELINE/1/STAGE/2/JOB` ? Something else?

1. Does this happen for every pipeline? Or just some?

2. Is there a job or stage rerun involved?

3. Can you check on the filesystem and provide the path of the expected file and the actual file?

4. Do you see any files in /var/lib/go-server/data/console/ that correspond to what you're seeing?

**Comment by GaneshSPatil** [comment]
@JorritSalverda -- We were unable to reproduce/see this issue at our end.
Are you still facing this issue? If so, can you provide the detailed steps to reproduce the above-mentioned scenario along with the information asked from @arvindsv?

**Comment by JorritSalverda** [comment]
Haven't seen this again, so feel free to close the issue.
