### ISSUE TITLE
Tile design

### ISSUE THREAD

**Issue by naveenbhaskar** [gocd/gocd#4037]
Dashboard list view thread is [here](https://github.com/gocd/gocd/issues/3872)

for reference the design is given below
![image](https://user-images.githubusercontent.com/1627961/33207624-689809f2-d134-11e7-8e1b-1b3cc5b0454a.png)

_**style 1**_
![image](https://user-images.githubusercontent.com/1627961/33207192-c6ab7a30-d132-11e7-81d3-68ee1b0c8cb6.png)

_**style 2**_
same as style 1 , but with a header background color.
![image](https://user-images.githubusercontent.com/1627961/33207330-43f067c6-d133-11e7-9fcc-27a8d13fe0f4.png)

_**style 3**_
![image](https://user-images.githubusercontent.com/1627961/33207358-63404cb8-d133-11e7-80c0-059d4c9381b1.png)

**_style 4_**
made the actions bit prominent 

![image](https://user-images.githubusercontent.com/1627961/33207523-06fc9f8c-d134-11e7-8338-20b36f39d993.png)

**_style 5_**

![image](https://user-images.githubusercontent.com/1627961/33208173-8cfd5250-d136-11e7-8ffe-7dfc31da9550.png)

**Comment by eeluke** [comment]
Style 3 makes the most sense to me. Though I don't think we need the drop shadow behind the gray. The only piece that still seems strange to me is that link to history. But I don't know where it should go so I'm fine trying it there for now. We should continue to test the new dashboard once it's live.

**Comment by yankurk** [comment]
In style 3 (and the others as well) each tile shows changes for the pipeline in the tile itself. In the mockups we have considered github materials in which the first column is the author name and the second the commit message. However, a pipeline can also be triggered by another pipeline. How would we represent such changes? 

To illustrate more, I have attached a screenshot containing a pipeline with both types of materials. Currently, the material whose change actually triggered the pipeline is highlighted in yellow and italicized. How would we represent the same in the new tile view?

<img width="890" alt="screen shot 2018-01-30 at 12 31 21 pm" src="https://user-images.githubusercontent.com/23699743/35552346-8afe4d44-05b9-11e8-8e31-c03900ab7d64.png">


For pipeline materials, the first column contains a link to the overview section of stage details page for the stage that triggered the pipeline:
<img width="1439" alt="screen shot 2018-01-30 at 1 11 11 pm" src="https://user-images.githubusercontent.com/23699743/35553741-18e05dbe-05bf-11e8-927e-5186caeae2fd.png">

The second column contains a link to the pipeline dependency section of stage details page which displays a graphical visualization of the pipeline dependency chain:

<img width="1438" alt="screen shot 2018-01-30 at 1 13 32 pm" src="https://user-images.githubusercontent.com/23699743/35553822-69561252-05bf-11e8-9e24-24d609912df9.png">

**Comment by kierarad** [comment]
@naveenbhaskar I know this issue is old but I thought I would provide some related feedback we recently received. 

We had 2 GoCD users (out of 8 participants) comment completely unprompted during usability testing for Pipelines as Code say that they did not recognize the green rectangles with checkmarks were representative of stages. 

We also had 2 users try to click on the pipeline name (as if it was a link). One was expecting the link to go to the pipeline history and the other seemed to hope it would go to the console (I should've clarified with him but didn't want to derail him)
