### ISSUE TITLE
Support for release branches (suggestion)

### ISSUE THREAD

**Issue by hakito** [gocd/gocd#404]
I have seen discussions on this topic in google groups https://groups.google.com/forum/#!topic/go-cd-dev/e0dbLDUsMK8 and also found a similiar issue #298.

But to avoid pipeline dependency problems i suggest to clone the whole set of pipelines for a new release branch.

Sample usecase:
* For a pipeline (next to _Trigger with options_) choose: _Branch from here_. => Branch dialog opens
* User enters a branch name. 
* Optional checkbox: Automatically create branches for all repositories
* Click confirm. => Go adds an entry to the menubar for the new branch.
* When a commit appears on a _release branch_ only the branch pipelines will be triggered.
* When a material does not have a branch with the given name go automatically uses the revision of the material when the pipeline was branched.

**Comment by srinivasupadhya** [comment]
this has been implemented for git with [git feature branch](https://github.com/ashwanthkumar/gocd-build-github-pull-requests) plugin.
