### ISSUE TITLE
Publish a artifact to an external store

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#4051]
##### Issue Type
- Feature proposal

Proposal:

Happens in 2 steps-
1. We make a request to the plugin to publish to an external store. Plugin completes upload
2. We generate the metadata file to upload to the GoCD server. We use the same mechanism that exists today to upload regular artifacts. Metadata file provides the traceability of the artifacts even though the artifact is in an external store. 
3. The checking of md5 for artifacts uploading by the plugin to be fetched later should be handled by the plugin. 

Currently, we have artifact type to be `file` (build) and `unit` (test). We could classify all plugin handled artifacts as build artifact only. 

Metadata - 
1. Artifact id or artifact configuration
2. Store id or store configuration
2. Artifact type
4. buildLocator

Should we pass along the whole configuration (that's present at the time the upload finishes) or just the id? If we pass just the id, the configuration might have changed for the store or artifact and by the time the downstream (or same pipeline) runs, the artifact or store config could have changed. @gocd/committers ?

Failure scenarios
1. If upload of artifact by the plugin fails, the job should fail. @rajiesh, can you think of any other solution? Currently, if upload of artifact fails, for some conditions, the job passes. 
2. If upload by plugin succeeds, but upload of metadata to Go server fails, should we fail the job? Or just let the fetch artifact downstream to fail?

**Comment by bdpiparva** [comment]
Currently, we are making on publish artifact call to the plugin with list of artifacts corresponding to the plugin and in return we are expecting response in following format - 

```json
{
  "metadata": {
       // This is up to plugin
  	"filenaem-1" : {
    	"name": "filename-1",
    	"version": "17.12"
	},
	"filename-2" : {
    	"name": "filename-1",
    	"version": "17.12"
	}
  },
  "errors": ["Foo","Bar"]
}
```

This will be uploaded to server in `pluggable-artifact-metadata` folder with `plugin-id.json`.

**Comment by arvindsv** [comment]
Closing. This is done.
