### ISSUE TITLE
Fetch artifact using artifact plugin

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#4053]
##### Issue Type
- Feature proposal
##### Summary
Use artifact id to fetch artifact from external repository 

As per https://github.com/gocd/gocd/issues/4050 , we will have a artifactId provided for each artifact. Use the id to fetch the artifact normally or via the plugin. Fetch Artifact request must first download the metadata file uploaded (look at https://github.com/gocd/gocd/issues/4051) to provide information to the plugin to download the right artifact. 

The metadata file could be downloaded normally as part of the built in fetch artifact capabilities and users can use the information provided here in the subsequent tasks (custom task or task plugins)  to perform other operations like a deploy. 

The metadata file should be used by the plugin to perform the download (docker pull, downloading a binary, etc).

**Comment by varshavaradarajan** [comment]
As part of the fetch task, plugin can also need some configuration as to what to do with the artifact fetched from the external store.

```xml
<fetchartifact pipeline="" stage="backup" job="default" artifactId="s3">
  <property>
    <key>dest</key> -- provided by plugin (optional)
    <value>where-the-artifact must be stored on the agent</value>
  </property>
</fetchartifact>
```
Problem - For regular file artifacts, today we validate that it shouldn't be outside the sandbox directory. If the destination is configured because the plugin requires it, how should Go handle this validation for regular artifacts fetched from an external store? @gocd/committers

**Comment by arvindsv** [comment]
It's completely up to the plugin, what it does with the keys (which it defines) and the values it expects. If it wants to store it outside the sandbox, it's up to it.

**Comment by arvindsv** [comment]
Treat all plugin configuration properties as off-limits.

**Comment by varshavaradarajan** [comment]
The configuration for fetch artifact will be something like this - 
```xml
<fetchPluggableArtifact pipeline="" stage="backup" job="default" storeId="s3">
  <property>
    <key>dest</key> -- provided by plugin (optional)
    <value>where-the-artifact-must-be-stored-on-the-agent</value>
  </property>
</fetchPluggableArtifact>
```

This involves having a new task called FetchPluggableArtifactTask. 
Validations: 
- The upstream dependency validations will be the same as the FetchTask
- Check whether the artifact store is present in the config, blank and invalid characters in store id. 
 
In addition,
- [ ] Pipeline config API v6 should support the new task
- [ ] Quick edit should support the new task
- [ ] JSON and YAML config repo plugins should support the new task

**Comment by arvindsv** [comment]
Shouldn't that be `artifactId` instead of `storeId`? As mentioned [here](https://github.com/gocd/gocd/issues/4050#issuecomment-349869752). If not, then a mismatch of `storeId` between a published artifact and an artifact being fetched would be fatal. There's no need to allow that mismatch.

**Comment by arvindsv** [comment]
`fetchartifact` feels nicer than `fetchPluggableArtifact`. If it has an ID, then it is a fetch pluggable artifact. Isn't it?
