### ISSUE TITLE
Rotate go-server-wrapper.logs

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#4054]
##### Issue Type

- Bug Report

##### Summary
Currently the go-server-wrapper.logs file is not rotated and tends to grow in size significantly with several plugins writing to this file.
###### Basic environment details

* Go Version: 17.11.0
* JAVA Version: JDK8
* OS: Windows,linux

##### Expected Results
go-server-wrapper.logs should rotate similar to go-server.logs

##### Actual Results
currently go-server-wrapper.logs doesnt rotate.

**Comment by rajiesh** [comment]
Verified on 17.12.0 (5626-cb7df2ffe421e43f2a682a7a323cb3a3e30734cc)
