### ISSUE TITLE
Perforce material handling on the agent side needs to be relooked at for BuildComposer flow

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#4058]
##### Issue Type

- Bug Report

##### Summary

* GO_P4_CLIENT environment variable is being set on the server side
* The value of this environment variable doesn't match the one being used for material checkout on the agent side when a destination directory is mentioned
* It uses the server hostname to determine the clientName that would be used by the agent. This would be problematic when multiple agents are trying to access the repo server at the same time.

**Comment by GaneshSPatil** [comment]
Stale as [Build Session is removed](https://github.com/gocd/gocd/commit/d45efb4d257b72bd0b801824404e785fc873e4de)

Closing.
