### ISSUE TITLE
Console log for BuildComposer flow doesnot get colored/formatted correctly

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#4060]
##### Issue Type
- Bug Report

##### Summary

When a job is run on an agent that support build-command feature, the logs that get uploaded are not colored or formatted properly. Check the attached image:
<img width="1383" alt="screen shot 2017-12-06 at 2 52 11 pm" src="https://user-images.githubusercontent.com/1046342/33654180-4f0ac942-da95-11e7-8f87-01f5942a4331.png">

The same job when run on a regular http agent produces the below console log:
<img width="1406" alt="screen shot 2017-12-06 at 2 54 21 pm" src="https://user-images.githubusercontent.com/1046342/33654216-6eab1900-da95-11e7-91ab-e105edf86fed.png">

**Comment by GaneshSPatil** [comment]
Issues with Console Log with BuildComposer flow:
- [ ] No Coloured Output
- [ ] Broken expand/collapse Formatting
- [ ] status reporting of job before running task
- [ ] Missing Task status

**Comment by arvindsv** [comment]
All of this is done in https://github.com/gocd/gocd/pull/3520. However, it's done in a way that I'm not comfortable with.

**Comment by arvindsv** [comment]
I had expected the change to be a little smaller, and something which doesn't affect the existing commands so much.

**Comment by GaneshSPatil** [comment]
Stale as [Build Session is removed](https://github.com/gocd/gocd/commit/d45efb4d257b72bd0b801824404e785fc873e4de)
