### ISSUE TITLE
Notification Filters not functioning in Safari

### ISSUE THREAD

**Issue by eravenelle** [gocd/gocd#4065]
##### Issue Type

Bug Report

##### Summary

Clicking the 'Add' button under 'Create Notification Filter' in User Preferences does not add the notification filter in Safari.  It is working for me in Firefox.  

###### Basic environment details

* Go Version: `17.11.0 (5520-9f6909e2f64b07d2dce5cecd4ea5b92b8e19d6b1). `
* JAVA Version: `1.8.0_144`
* OS: `Linux 4.9.62-21.56.amzn1.x86_64`
* Browser vendor and version (if relevant): `Latest Safari (Version 11.0.1 (13604.3.5))`

##### Steps to Reproduce

Prerequisites:  
1. Use Safari

Steps:
1.  Click Username > Preferences
2. Select any options for notification filter
3. Click 'Add' button

##### Expected Results
A notification filter is added

##### Actual Results
A notification filter is not added

##### Possible Fix
Browser differences, works fine in Firefox

**Comment by GaneshSPatil** [comment]
Hello @eravenelle,

I tried adding a notification filter on Safari `Version 12.1 (14607.1.40.1.4)` with GoCD version `v19.3.0`. It worked for me.

Can you try reproducing the issue with Safari `Version 12.1 (14607.1.40.1.4)`  and GoCD version `v19.3.0`?

**Comment by GaneshSPatil** [comment]
Didn't hear from the user. Marking as `stale`.
