### ISSUE TITLE
State exhibited by Agent and pipelines in various scenarios

### ISSUE THREAD

**Issue by anishvenkat** [gocd/gocd#4067]
##### Issue Type

- Bug Report
##### Summary

Logging an issue for the various state exhibited by the Agent and the pipeline when the Agent is stuck in Building(Cancelled) state.

###### Basic environment details

* Go Version: 17.7
* JAVA Version: 1.8.0_151
* OS: Ubuntu 16.04

**Case 1**: Have a task that does not respond well to being killed. For instance, a config such as this:

> <pipeline name="pipeline2">
      <materials>
        <git url="https://github.com/anishvenkat/python.git" />
      </materials>
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="bash">
                <arg>-c</arg>
                <arg>trap "" INT TERM HUP; while sleep 2; do date; done</arg>
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>

##### Expected Results
On canceling the task, we expect the Agent to come back into the idle state.

##### Actual Results
On canceling the run, the `On Cancel Task: Kills child process` kicked in and it ignored the SIGTERM and went on a forever loop and the Agent was hung in Building(Cancelled) state. I had to kill the process manually by running - `pkill -9 -f 'INT TERM'`
After which the Agent returned back to idle state.

##### Code snippets/Screenshots
 Console output screenshot:
<img width="1440" alt="screen shot 2017-12-06 at 11 57 12 2" src="https://user-images.githubusercontent.com/11550439/33700639-70d52d0a-db40-11e7-8b27-48b6c6473f55.png">

Agent Dashboard page:
<img width="1440" alt="screen shot 2017-12-07 at 11 21 07" src="https://user-images.githubusercontent.com/11550439/33700698-cb25fb54-db40-11e7-893a-0d8c50995c6c.png">

**Case 2**: Restarting Go server when the Agent is stuck on Building(Cancelled) state

For this case I have used the same pipeline config as in case 1.

##### Expected Results
On restarting Go server, the Agent should have killed the job.

##### Actual Results
I could see that the job was still running after the restart(even though it shows that the pipeline run was canceled). The console output was constantly printing the output. I had to manually kill the job from the command line. 

##### Log snippets
The logs show the below two errors.

1) Error occurred when agent tried to ping server.
2) Could not send console output to server.

##### Code snippets/Screenshots
Pipeline state screenshot:
<img width="1425" alt="screen shot 2017-12-07 at 12 09 26" src="https://user-images.githubusercontent.com/11550439/33702003-99bd205e-db47-11e7-8f16-25c4b445fbf4.png">

**Comment by mrmanc** [comment]
Something I think it is important to think about here is that restarting the agent without intervening to address the process which would never complete could cause issues with future job—the agent is in an error state at this point and I wouldn’t want it to pick up more jobs until someone has intervened. It would be nice to see clearly that the agent requires intervention though, and this could be based on the amount of time that the process has been running since being signalled.
