### ISSUE TITLE
Issues getting logback working as docs

### ISSUE THREAD

**Issue by BarryGr** [gocd/gocd#4074]
##### Issue Type

Extended logging

- Documentation Report 

##### Summary

https://docs.gocd.org/current/advanced_usage/logging.html#advanced-logging-features

this is partial information trying to implement advanced logging, appears to show that logback isnt actually inplemented.

###### Basic environment details

* Go Version: `17.10.0`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.16.0-4-amd64`
* Browser vendor and version (if relevant): `n/a (chrome latest)`

##### Steps to Reproduce

1. follow the steps as discribed in the document 
2. logback-include.xml is not read (can insert bad xml and there is no impact)

##### Expected Results
logs should be shipped also tried to implement this to log to a file, nothing happens

##### Actual Results
nothing happens - xml document can be in a known bad state and nothing occurs

**Comment by arvindsv** [comment]
Closing. You're looking at 17.12.0 documentation and trying this on 17.10.0. Logback was introduced in 17.11.0 (see [release notes](https://www.gocd.org/releases/#17-11-0)).

17.11.0 docs: https://docs.gocd.org/17.11.0/advanced_usage/logging.html
17.12.0 docs: https://docs.gocd.org/17.12.0/advanced_usage/logging.html (/current/ also works at this time).
