### ISSUE TITLE
Invalid Destination Directory. Every material needs a different destination directory and the  directories should not be nested.

### ISSUE THREAD

**Issue by bormotov** [gocd/gocd#4075]
##### Issue Type

Bug Report

##### Summary

After updating to 17.12.0-5626  go-server dont start

go-server.out.log report 

```
There are errors in the Cruise config file.  Please read the error message and correct the errors.
Once fixed, please restart Cruise.
Error: Invalid Destination Directory. Every material needs a different destination directory and the
 directories should not be nested.
```

cant find any problems in cruise-config.xml and cruise-config.xml.invalid.2017-12-08* created after each start attempt

##### Environment

no changes 

###### Basic environment details

* Go Version: `17.12.0-5626`
* JAVA Version: `java 8.0.121-b13`
* OS: `Linux, Fedora 27`

##### Expected Results

server start properly

##### Actual Results

server not start

##### Log snippets
```
There are errors in the Cruise config file.  Please read the error message and correct the errors.
Once fixed, please restart Cruise.
Error: Invalid Destination Directory. Every material needs a different destination directory and the
 directories should not be nested.
ERROR: Failed to start Go server. Please check the logs.
java.lang.RuntimeException: Failed to start Go server.
        at com.thoughtworks.go.server.GoServer.startServer(GoServer.java:77)
        at com.thoughtworks.go.server.GoServer.go(GoServer.java:64)
        at com.thoughtworks.go.server.util.GoLauncher.main(GoLauncher.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.thoughtworks.gocd.Boot.run(Boot.java:104)
        at com.thoughtworks.gocd.Boot.main(Boot.java:55)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Peer (vm://go-server#1) disposed.
        at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(Applica
tionInitializer.java:143)
        at com.thoughtworks.go.server.initializers.ApplicationInitializer.onApplicationEvent(Applica
tionInitializer.java:47)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(Simple
ApplicationEventMulticaster.java:97)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractAppli
cationContext.java:327)
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractAppl
icationContext.java:941)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicatio
nContext.java:475)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(Co
ntextLoader.java:383)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:283)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderLis
tener.java:111)
```

##### Any other info

Can GoCd privode pipeline name, materials name with invalid materials?

**Comment by bormotov** [comment]
another friendly way: instead stop starting server, xclude "brocken pipeline" from runtime config

**Comment by jyotisingh** [comment]
@bormotov - Is this fixed? Were you able to spot what the issue was?

**Comment by bormotov** [comment]
*this* - unused log message and stop service instead fix-and-continue- not fixed.

I got pipeline with two materials in config with nested destination, remove one and start service.

**Comment by jyotisingh** [comment]
Ah so it was a case of nested directories, then the error is expected. Ofcourse, we need to fix the error message, but I was worried if the error was thrown in a case when the directories were not nested. Thanks for confirming.

**Comment by bormotov** [comment]
fix log message - minimum.
fix start logic - will be good. 
Previous version works fine and after update server don't even start - it's very strange

**Comment by jyotisingh** [comment]
We made some fixes around the validation of destination directories in 17.12. This shouldn't have been allowed in the first place, but there could have been some loops holes in the previous versions which allowed that. That's the reason why you see the validation error with the newer version. 

Regarding the startup logic - the server validates the config file and if it finds it to be invalid, it tries using the last-known-good-config from the internal git repo. Stops the server startup if that is found to be invalid too. Excluding a pipeline definition from the config and bringing up the server wouldn't work for many reasons such as another pipeline could be dependent on it and it is plain wrong to ignore a pipeline just like that. So, that is something we might never do. 

However, what you say about fixing the error message to allow users to spot the pipeline/material that contains the error makes sense.

**Comment by bormotov** [comment]
I have no much time to research problem, in my case server not started.

/etc/go/cruise-config.xml was current, with problem.

and now

```
-rw-r--r-- 1 go   go   378499 Dec 11 11:51 cruise-config.xml
-rw-rw-r-- 1 go   go    93505 Jun 22  2016 cruise-config.xml.2016-06-24-07-53-52
-rw-rw-r-- 1 go   go   130668 Aug 16  2016 cruise-config.xml.2016-08-18-20-09-23
-rw-rw-r-- 1 go   go   129591 Sep 26  2016 cruise-config.xml.2016-09-27-21-51-02
-rw-rw-r-- 1 go   go   360809 Dec  6 01:27 cruise-config.xml.invalid.2017-12-08-22-55-01
-rw-rw-r-- 1 go   go   360809 Dec  8 22:55 cruise-config.xml.invalid.2017-12-08-23-13-57
-rw-rw-r-- 1 go   go   360809 Dec  8 23:13 cruise-config.xml.invalid.2017-12-08-23-35-08
-rw-rw-r-- 1 go   go    47548 Mar 31  2016 cruise-config.xml.original.2016-03-31-19-08-50
```
I think, because, this config broken for 17.12, but fine for 17.11

Of course, we make changes in 2017.  Of course, we update GoCd all this time.
No any log messages about "we try to use previouse work version of config" with details: config date, validation result, git revision, etc.  
No any visible try to solve problem.  Just traceback and unusable message.

Ok, exclude pipeline - bad idea.  
Disable pipeline and provide message to human in UI? When I pause pipeline, I can write message why.  Can validation procedure similary pause pipeline and write message "nested distination for materials m1 (some_path), m2 (some_path/inside) not allowed in GoCd 17.12", for example?

Provide backward compatibility - not easy, yes, but it is very valuable
