### ISSUE TITLE
Pipeline Pause/Unpause API

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4076]
##### Issue Type

- Feature enhancement

##### Summary

Create a new Pipeline Pause/Unpause API.

Problems with current API:
- [x]  Current API is not versioned under API namespace.
- [x] Returns empty response body ("") in case of success.
- [x] Returns a text response in case of errors.
- [x] Allows pausing a pipeline even when the pipeline is already paused.
- [x] Allows unpausing a pipeline even when the pipeline is already unpaused.

These problems should be fixed as part of the newer version of API.

**Comment by ketan** [comment]
@rajiesh — can we get a round of testing on this and close?

**Comment by rajiesh** [comment]
Verified on 18.2.0 (6208-f0f03120fc42d2ae1f230dd89996a3dc086912c5)
