### ISSUE TITLE
SPAs - Stale plugin info being shown.

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4078]
##### Issue Type

- Bug Report
##### Summary

All the SPAs which need the plugin infos API call to be made (elastic, plugin settings, auth config, role config), should all make a get plugin info call to the specific plugin at the time of displaying the modal form, or there is a possibility that the form being displayed in the modal is stale. 

###### Basic environment details

* Go Version: `17.12.0`
##### Steps to Reproduce

1. Start the GoCD server with the system property `pluginLocationMonitor.sleepTimeInSecs` set to 30s (not required on the development server) and with an old version of elastic agent plugin.
2. Go to the elastic profile page. Click on edit profile for a plugin. 
3. Remove the plugin and copy over the new updated version of the plugin (where you know the plugin view and configuration is changed).
4. Click on edit elastic profile again.

##### Expected Results

New profile view must be shown.
##### Actual Results

Old profile view is shown.
##### Possible Fix

Make a get plugin info API call at the time of showing the modal.

**Comment by arvindsv** [comment]
IMO, we should consider the `pluginLocationMonitor.sleepTimeInSecs` property to be development-only. I'd not fix any issues because of it being turned on. We should rewrite that and make plugin loads API based (upgrade plugin API, etc) and then we can see if this kind of thing happens.

**Comment by arvindsv** [comment]
Closing since it's related to a development-mode feature.
