### ISSUE TITLE
How to export a report of users , who accessed the GOCD past 30 days with user ID, Email address and Last login date colums.

### ISSUE THREAD

**Issue by vivuu1989** [gocd/gocd#4080]
##### Issue Type

- Security issue? [**DO NOT** report it here. Use [hackerone](https://hackerone.com/gocd) or send a mail to support@thoughtworks.com]
- Bug Report
- Feature proposal
- Feature enhancement
- Documentation Report
- Question? [**DO NOT** ask it here. Ask in the [mailing list](https://groups.google.com/forum/#!forum/go-cd)].

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by arvindsv** [comment]
Closing. As mentioned **clearly** above, this is a question and not an "issue".

> - Question? [**DO NOT** ask it here. Ask in the [mailing list](https://groups.google.com/forum/#!forum/go-cd)].
