### ISSUE TITLE
Console log over websockets (browser) renders incorrect logs in some cases

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#4088]
##### Issue Type

- Bug Report

##### Summary

Console log over websockets (browser) renders incorrect logs. It uses the pipeline label instead of the counter to fetch the logs . 

##### Environment

This issue was seen with https://build.gocd.org/go/tab/build/detail/acceptance_pg_gauge/41/gauge-priority/1/firefox-split-runInstance-1 pipeline 

##### Description

* Configure a pipeline P1, set label as $COUNTER.
* Configure a downstream pipeline P2, set label as ${P1}
* Enable feature toggle for `browser_console_log_ws_key` 
* Let both pipelines run atleast once, and check console logs show up as expected.
Retrigger P2. Second run of P2 has a label `1` since there is no new run of P1 so it uses the same revision. 

At this point when you check the console logs for P2 run1 and run2, they both show the same console logs. The artifacts tab/raw logs continue to show the right logs , but the console tab displays incorrectly.

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/5880

\cc: @adityasood @rajiesh @rahulpargaonkar
