### ISSUE TITLE
Personalized pipeline view to show only certain projects' pipelines

### ISSUE THREAD

**Issue by rkrisztian** [gocd/gocd#4089]
##### Issue Type

Feature enhancement

##### Summary

I am interested in seeing pipelines of certain projects only. Whether they're newly created or not, should not matter, but uninteresting projects' pipelines tend to sneak in with "Show newly created pipelines", and it's getting tedious to clean up my view after each and every change. Also, if I turn it off, then I won't be able to track changes like renamings, splitting of groups, etc.

###### Basic environment details

* Go Version: 17.11.0

##### Steps to Reproduce

1. Project A creates pipeline group `PROJECT_A` with pipelines `projectA-pipeline1` and `projectA-pipeline2`.
2. I personalize my view on all pipelines of group `PROJECT_A`.
3. Then later they add `projectA-pipeline3`, which I see. => OK.
4. Then Project B comes and creates pipeline group `PROJECT_B` with pipeline `projectB-pipeline1. To me that's uninteresting. => NOK.
5. I'm getting too many new uninteresting pipelines like in the previous step, so I disable "Show newly created pipelines."
6. Then Project A splits its group to `PROJECT_A1` with pipelines `projectA-pipeline1x` and `projectA-pipeline1y`, as well as `PROJECT_A2" with pipeline `projectA-pipeline2`. I won't be notified about the change. => NOK

##### Possible Fix

For me it would be more efficient to have a feature to be able to track projects' pipelines identified by one of the following methods:

* By Git repository URLs.
* By the repository URLs of the YAML file(s) created for the [gocd-yaml-config-plugin](https://github.com/tomzo/gocd-yaml-config-plugin). (Of course this is not generic enough, I know.)

But even if filtering by SCM URL is not going to be accepted, I would also be happy to see a feature like:

* Show newly created pipelines from groups I already selected at least one pipeline from.
* Or, show newly created pipelines matching the given group or pipeline name pattern.

**Comment by arvindsv** [comment]
/cc @naveenbhaskar @tinozza 

Apart from https://github.com/gocd/gocd/issues/3842, I remember there was some idea of multiple dashboards with personalization. Can't find the issue for it.

**Comment by naveenbhaskar** [comment]
@arvindsv @tinozza @eeluke .. Updated [#3842.](https://github.com/gocd/gocd/issues/3842) with new changes
