### ISSUE TITLE
Did nor receive successfull HTTP response - error - 403

### ISSUE THREAD

**Issue by Prabhu2430** [gocd/gocd#4096]
When we are trying to access the GoCD server, from the Go agent via proxy, we are getting the below error.

Did nor receive successfull HTTP response - error - 403

Attached the error screenshot for reference.

![image](https://user-images.githubusercontent.com/30456768/33988028-fea95702-e0e8-11e7-90cb-50df19d60957.png)

**Comment by arvindsv** [comment]
Closing as stale.
