### ISSUE TITLE
Create delete artifacts extension point

### ISSUE THREAD

**Issue by pravds** [gocd/gocd#410]
Whenever Go finds disk space to be lower than what is configured, it will try to delete artifacts for each stage run instance in their chronological order (unless stage is marked as 'never delete artifacts for this stage'). 

It would be useful to provide an extension point around this behavior so that plugins can be written to cater different artifact cleanup strategy.

**Comment by aramprice** [comment]
+1 for this. One strategy I would hope to see supported is "never delete artifacts from the last successful build".

thanks

**Comment by christrotter** [comment]
+1 for this.  We have a CI pipeline that rapidly fills up the disk.  When Go purges, all of the non-CI pipelines are dumped.  

Further (this is probably another issue...), when we re-run the necessary 'build' pipeline to re-create the artifact, it tends to still give 404s until I move the files around back into the specific pipeline run directory.  i.e. if run #2 contains the files, Go is looking for the stuff from run #1, and gives 404s until I copy the files in #2 into #1.  

So pretty much if there is a way to have it keep any artifacts that are being used (for example Dev has v3, QA has v2, UAT v1, Prod v1 - Go should keep v1, 2, and 3).

Alternatively, if there was a way to specify artifact retention per-pipeline, this could be alleviated.

**Comment by rnjn** [comment]
We face the same issue, slow moving pipelines get their artefacts purged from Go, since the artefacts are months old. We need to rebuild them for new releases, for they are purged. We can put these artefacts out of Go, but that's not really a good solution. 
It would be great if we can keep last artefacts on all pipelines safe from the purge monster.

**Comment by tomas-forsman** [comment]
Is this meant to be released any time soon?
Actually what we would need is #1207 - just keep the x latest artifacts form every pipeline

**Comment by NachbarsLumpi** [comment]
We were just hit by this because go decided to delete the latest artifacts from several pipelines and thus our downstream pipelines began to fail with 404.

Since such a happening requires a lot of manual intervention, we would like this to be released with the next update.

**Comment by jsilverman-blispay** [comment]
Is this released yet? Is it on the release roadmap? We currently use a find script to manually delete old artifacts, and have been considering writing something "smart" enough to keep X last artifacts of pipelines deployed to production.

Any progress on a smarter artifact cleanup strategy, built into Go.cd itself, would be awesome.

**Comment by arvindsv** [comment]
Unfortunately not. It's not being worked on at this time. The [gocd-janitor](https://github.com/ashwanthkumar/gocd-janitor) might be of interest to you, instead of writing something on your own.

**Comment by NachbarsLumpi** [comment]
jsilverman-blispay, it's bad news to hear that you run into the same issue as we do.

Not knowing the gocd-janitor existed, we have written a some 100 lines large script of python that frees up disk space by deleting artifact files. The script preserves files from the latest pipeline labels. Ping back if you would like to see it attached to this issue.

The clean up process is still a manual process like it is with the gocd-janitor and both solutions are therefore time consuming, error prone and done very sporadically.

It is my impression that the gocd team should increase the priority of this issue.

**Comment by jsilverman-blispay** [comment]
@NachbarsLumpi I'm interested in seeing the python script if you can make it available.

Thanks

**Comment by NachbarsLumpi** [comment]
@jsilverman-blispay, I'll see to make that happen tomorrow around 10AM UTC.

**Comment by NachbarsLumpi** [comment]
Here it is:

[cleanupPipelineArtifacts.py.txt](https://github.com/gocd/gocd/files/641902/cleanupPipelineArtifacts.py.txt)

**Comment by arvindsv** [comment]
Closing as stale.
