### ISSUE TITLE
Allow tasks to be executed/tested independently of a job execution

### ISSUE THREAD

**Issue by evan-ravenelle** [gocd/gocd#4101]
##### Issue Type

Feature Enhancement/Proposal

##### Summary

When creating tasks as part of a job, it would be beneficial to be able to test the task in place with the current workspace without executing the existing job.  In cases where a job has multiple tasks which take time to complete, time is wasted waiting for these tasks to complete in order to get to the last task.  I understand one could simply re-order the tasks but this has its own issues, such as the job cleaning out the workspace which may contain necessary resources for the task to be tested, or having to monitor execution so that other tasks in the job don't execute when not needed.

A suggestion to deal with the potential problem of workspaces not containing the necessary dependencies for the task to complete:  allow the user at task execution to select the agent they want to test the task on, which would allow that user to stage the agent for task testing.  Ideally the user would be able to see a directory hierarchy of the sandbox environment on the selected agent to ensure the sandbox is staged correctly for the test execution.

Another, perhaps simpler, option would be to allow disabling of individual tasks within a job so that when the job is executed only the enabled tasks would execute.

**Comment by arvindsv** [comment]
Closing as stale.
