### ISSUE TITLE
"Pipeline as code"- Successful message once partials from repo are synced

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#4102]
##### Issue Type
- Feature proposal
- Feature enhancement
##### Summary
Currently, once a user makes changes to pipelines in his repo, there is no way to validate if the changes are correct and the syn is successful. However we do give out a message if something is wrong

###### Basic environment details

* Go Version: 17.11
* JAVA Version: Java8

##### Steps to Reproduce
1. Configure "pipeline as code" in GoCD setup
2. Make some changes in your repo where your pipeline code resides
3. GoCD Server does not show any success message of the changes (if accepted or the sync is complete)
4. Make some errors in the pipeline code and GoServer shows error message

##### Expected Results
Some indication of the successful sync of the Pipeline code

##### Actual Results
No indication for end user

**Comment by arvindsv** [comment]
There are now messages and better UX around this.
