### ISSUE TITLE
[Feature request] Add separate environment variable for server url that can be configured via server config

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#4106]
##### Issue Type

- Feature proposal

##### Summary

Currently, we have an environment variable for server url (GO_SERVER_URL). But, GoCD site URL and secure site URL might be different. These should also be another environment variable available  which can be used during job execution or sent to third party applications.

**Comment by dirkschneemann** [comment]
Another use case for this: I am deploying my `GoCD` master on different machines every now and then (think Docker Swarm, Kubernetes, ...) and the `Site URL` and `Secure Site URL` settings might not yet be known at build time of my Docker image.
