### ISSUE TITLE
Show pipeline instance material changes information on dashboard SPA

### ISSUE THREAD

**Issue by yankurk** [gocd/gocd#4114]
Pipeline instances should include `Changes` link which users can click on to view changes that triggered the pipeline instance. Based on the trigger type the changes should include relevant information.

* For SCM materials the following details must be shown:
    - [ ] Repository name
    - [ ] Committer name + timestamp of commit
    - [ ] Commit message
    - [ ] Material fingerprint
    - [ ] VSM of the scm material

* For Pipeline dependency the following details must be shown:
	- [ ] Name of upstream pipeline
	- [ ] Link to stage details page of the stage of the upstream pipeline that triggered the pipeline instance
	- [ ] Link to dependency map of the upstream pipeline instance
	- [ ] Material fingerprint

**Comment by varshavaradarajan** [comment]
There is also the material name for pipeline dependency - this need not always be pipeline name

**Comment by varshavaradarajan** [comment]
And people have asked for material name to be included as part of pipeline instance API. So, consider that as well? 
https://github.com/gocd/gocd/issues/2990

**Comment by ketan** [comment]
@yankurk — I was told you're working on this, so assigning this to you.

**Comment by yankurk** [comment]
There are a couple of functionalities missing:
- [ ] Adjustment of changes popup position based on where it is inside the window. Currently, the changes popup introduces a horizontal scroll if it is positioned on the far right of the window.
- [ ] The comment section in the changes popup does not include tracking tool related information. Currently, comments are plain text. (Related: #4192)

**Comment by yankurk** [comment]
Build cause popup for new dashboard has been implemented. Thus closing this issue.
