### ISSUE TITLE
I would like my developers to be able to add their pipelines to an environment without having to involve the Go admins.

### ISSUE THREAD

**Issue by vivuu1989** [gocd/gocd#4132]
We ave a number of GOCD pipelines which were created across different environments by different teams.

But now we have only one role as admin and we have to give admin previlege to all the developers inorder to make them trigger pipeline which is not a safety way and we came into a lot of issues as all are having admin access.

So we have to have some more Roles in GOCD(Eg: Pipeline_admin, Template_admin). So for trigering pipelines , we can assign the the first role and for template editing the second role , etc....

But how to create a new role in GOCD ?
How to make the roles the specified access\permission only . 
eg: only pipeline triggering previlege for Pipeline_Admin Role.
Only template ediing previlege for template_admin Role.

**Comment by ketan** [comment]
Closing. As mentioned **clearly** in the template, this is a question and not an "issue".

Please ask on the [mailing list](https://groups.google.com/forum/#!forum/go-cd)].
