### ISSUE TITLE
Support NUnit 3.x for test artifacts. 

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4136]
##### Issue Type

- Feature proposal

##### Summary

Currently, GoCD recognizes only files which have the NUnit 2.x xml format for test results as test artifacts. NUnit 3 has been introduced and users have to convert the test results in nunit 2.x format for the unit test report generator to identify the test results xml as a test artifact. 

##### Steps to Reproduce

1. Configure a simple job in a pipeline
2. Upload the attached file as a test artifact
3. Trigger the pipeline

##### Expected Results

GoCD recognizes the attached file as a test artifact

##### Actual Results

GoCD throws the error - `it is not a recognized test artifact`
[TestResults.xml.txt](https://github.com/gocd/gocd/files/1592810/TestResults.xml.txt)

**Comment by fomenta** [comment]
Any progress on this?

**Comment by voltcode** [comment]
any updates on this?
