### ISSUE TITLE
Trigger with options - hover, select

### ISSUE THREAD

**Issue by jasonduff** [gocd/gocd#414]
Currently, when you hover over a selection in the dropdown, it continues to be highlighted even when the mouse leaves.  So, you think you selected something but you really didn't.  

We should with un-highlight when the mouse leaves the drop-down or select as the mouse hovers over the field.

Thanks.

**Comment by GaneshSPatil** [comment]
This issue has been resolved as part of the GoCD new dashboard released in `v18.3.0`.
