### ISSUE TITLE
System wide environment variables

### ISSUE THREAD

**Issue by jasonduff** [gocd/gocd#415]
We should add the ability to have system wide environment variables.  This would help cleanup the situation (common) where we are using and have to copy variables for each separate environment when they are often the same.

Thanks.

**Comment by iboppana** [comment]
+1

**Comment by dayglojesus** [comment]
Agreed, this feature request would allow administrators to publish a consistent global ENV variable across any pipeline regardless of environment. I would very much like to see this feature.

**Comment by arvindsv** [comment]
Closing as stale.
