### ISSUE TITLE
Sub-menu (Admin->Security) mis-aligned

### ISSUE THREAD

**Issue by oxinabox** [gocd/gocd#4158]
##### Issue Type
Bug Report

##### Summary

I think the picture tells 1000 words.
Red markings are added to show where.

![image](https://user-images.githubusercontent.com/5127634/34594659-54e1ea1e-f20d-11e7-9fc0-6c344dda8e65.png)

In Firefox 57 (full details below), this occurs.
It makes it impossible to actually access items in the submenu, since the mouse point leaves the menu on its path to the submenu, thus making it close.
It works fine in Chrome.

###### Basic environment details

* Go Version: `17.12.0 (5626-cb7df2ffe4…682a7a323cb3a3e30734cc)`
* JAVA Version: `1.8.0_151`
* OS: `Linux 4.10.0-42-generic`
* Browser vendor and version (if relevant): `57.02.2 (64bit, on Window 7)`

##### Steps to Reproduce

1.  Connect to server, with Firefox web-browser
2. hover over (expand) "Admin" menu at the top
3. Move down and hover over (expand) "Security submenu"

Note the location where the submenu opens.

##### Expected Results
Submenu should be immediately next to main menu,
like it is in Chrome (pictured below).

![image](https://user-images.githubusercontent.com/5127634/34594964-19deebc2-f20f-11e7-86cc-662949b1b0ec.png)

##### Actual Results
![image](https://user-images.githubusercontent.com/5127634/34594659-54e1ea1e-f20d-11e7-9fc0-6c344dda8e65.png)

**Comment by oxinabox** [comment]
I just tried on my laptop;
which was running Firefox 57.0.3 (not 57.0.2)
and I can not reproduce in this environment -- everything works correctly
since there is no changed to that kind of processing in the release notes: https://www.mozilla.org/en-US/firefox/57.0.3/releasenotes/

I thus conclude that the firefox version is not reposible, and nor is the sever version.
I will have to investigate further, it could be I have a plug-in or something interfering.

**Comment by ketan** [comment]
It could be an issue with the resolution you are on. Could possibly try FF
in incognito mode to avoid any addons or plugins.

**Comment by oxinabox** [comment]
>It could be an issue with the resolution you are on. Could possibly try FF in incognito mode to avoid any addons or plugins.

I have now tried these things and it did not solve. 
I tried lowering my deskop resolution to be as low as my laptop,
and tried various window resizings and it still occurs.

**Comment by GaneshSPatil** [comment]
Fixed as part of new headers introduced in GoCD version `v18.12.0`
