### ISSUE TITLE
Use tooltips everywhere

### ISSUE THREAD

**Issue by oxinabox** [gocd/gocd#4165]
##### Issue Type
- Feature enhancement

##### Summary

Tool tips are great.
We should have more of them.
They greatly enhance the understand-ability of icons.

###### Basic environment details

* Go Version: `17.12.0 (5626-cb7df2ffe4…682a7a323cb3a3e30734cc)`
* JAVA Version: `1.8.0_151`
* OS: `Linux 4.10.0-42-generic`
* Browser vendor and version: `Vivaldi | 1.13.1008.40 (32-bit)` and `Google Chrome Version 63.0.3239.84 (64-bit)`

##### Steps to Reproduce

Mouse over an icon. 
Notice its lack of tool-tip.
**Optional:** Be confused as to what it does.

##### Expected Results
Almost all icons should have tool tips
![pipeline edit with tooltip](https://user-images.githubusercontent.com/5127634/34669999-60277872-f4af-11e7-952c-e256e137bfc1.png)

##### Actual Results
Many icons do not have tool tips.

![pipeline edit no tooltop](https://user-images.githubusercontent.com/5127634/34669879-ddcc6a9a-f4ae-11e7-85ee-1b091f17b2d4.png)

##### Possible Fix
add `title` attribute to elements to give them tool tips.
This may or may not improve accessibility for screen readers -- but that is just a side benefit. 

  
#### Some icons that could do with tool tips
A probably incomplete list.

  - [x]  `/pipelines`
![image](https://user-images.githubusercontent.com/5127634/34670152-0ee14b90-f4b0-11e7-86e2-277d158faa11.png) edit pipeline
- [ ] `/admin/security/auth_config` 
 ![image](https://user-images.githubusercontent.com/5127634/34670116-e15419be-f4af-11e7-8c8c-f39d77180720.png)  edit config,  duplicate, delete

**Comment by ankitsri11** [comment]
Pointing out few more icons where tooltip would be useful.

GoCD version - 18.6

Pipeline trigger, trigger with options and pause button.

<img width="288" alt="screen shot 2018-06-19 at 11 23 28" src="https://user-images.githubusercontent.com/6838313/41616805-c5e169ec-73b3-11e8-9c05-069538c46b80.png">

Edit pipeline group

<img width="266" alt="screen shot 2018-06-19 at 11 23 43" src="https://user-images.githubusercontent.com/6838313/41616822-d4dfd2bc-73b3-11e8-86ca-b991947a0266.png">

Cancel/ re-run stage

<img width="1385" alt="screen shot 2018-06-19 at 11 24 15" src="https://user-images.githubusercontent.com/6838313/41616863-ec566384-73b3-11e8-9432-c708da03f759.png">

**Comment by alan-ghelardi** [comment]
Besides adding titles some buttons should be properly labeled with aria-label property. When browsing with the tab key screen readers read those tooltips, but when navigating with arrow keys (what blind users do very often - I'm a blind engineer) they don't read them at all. From the accessibility perspective, providing correct labels (either via aria-label or hidden span elements) is more important than titles. For example, currently when I'm reading a pipeline in the dashboard I can't understand, at a first moment, which was the result of the last execution of its stages. I need to tab through the stages to "force" the screen reader to read the titles that contain the stage name and its state, what is very tedious. If there were labels for those buttons I would be able to get those information faster.

**Comment by alan-ghelardi** [comment]
Just a small complement: what I said above is particularly true for links; for traditional buttons (the HTML tag button) when there is a title but not a text, the screen reader always interprets the title as the button label regardless the navigation mode.

**Comment by arvindsv** [comment]
Moved to 18.7 milestone - but it might not happen in 18.7. Might get pushed one release. We should work with @alan-ghelardi and get feedback as it is being worked on.

**Comment by maheshp** [comment]
Refer https://github.com/gocd/gocd/pull/5046

**Comment by rajiesh** [comment]
Tool tips added as part of #5046 . More things can be done to improve application accessibility which will be tracked with separate issues

**Comment by adityasood** [comment]
@alan-ghelardi we have made some accessibility improvements as part of our latest release [v18.8.0](https://www.gocd.org/download/#windows).

**Comment by ketan** [comment]
For anyone reading this: This issue is closed not to say that we've 'fixed' usability everywhere, but to say that for specific places identified in this issue. If there are specific pages and places within GoCD which are missing tooltips, a new issue should be opened and someone can help address it.

Thanks

**Comment by alan-ghelardi** [comment]
@adityasood awesome. Thank so much for the update. I'll have a look at the improvements.
