### ISSUE TITLE
Validate roles assigned to stage authorization on template update through API

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#4176]
##### Issue Type

- Bug Report

##### Summary

Template update through API does not validate presence of a role. Thereby a non-existent role can be added to the template. 

This leads to validation errors while saving the template from UI or updating the config-xml. Since the config_xml has errors a server restart would fail as well.

**Comment by rajiesh** [comment]
Verified on 18.1.0 (5932-46938d88757632f7c20e899e682181862bf4296b)
