### ISSUE TITLE
Server configuration API endpoint

### ISSUE THREAD

**Issue by anishvenkat** [gocd/gocd#4189]
##### Issue Type

- Feature proposal

##### Summary

Currently, a user has to manually login to the dashboard to update the `security` configuration attributes or edit it from the cruise-config.xml file locally. Creating a placeholder for having an API endpoint to update these attributes via an API call.

**Comment by inge4pres** [comment]
Hi :) the API is already there. 
See https://api.gocd.org/current/#authorization-configuration 

The way I'm using it for example is to configure password-file auth after the server boots in a container, mounting the file as a volume and running

```
curl 'http://localhost:8153/go/api/admin/security/auth_configs' \
      -H 'Accept: application/vnd.go.cd.v1+json' \
      -H 'Content-Type: application/json' \
      -X POST -d '{
    "id": "password-file",
    "plugin_id": "cd.go.authentication.passwordfile",
    "properties": [
      {
        "key": "PasswordFilePath",
        "value": "/godata/credentials.txt"
      }]
  }'
```

**Comment by GaneshSPatil** [comment]
Hello @inge4pres, the authorization-configuration API allows admin users to manage authorization configuration. It is used to manage authConfigs under `<server>` tag.

This is the placeholder issue to create an API which will allow admin users to manage attributes of the `<server>` tag. For Example: `artifactsdir`, `agentAutoRegisterKey`, `webhookSecret`, etc

**Comment by akshaydewan** [comment]
Wondering what would be the right endpoint for this. `/api/config/server` would imply that everything under `server` will be configurable from this API.

Maybe we can group them into entities. From what I see, we have this structure:
- Server
  - Urls
    - siteUrl
    - secureSiteUrl
  - Artifacts
    - Purge Settings
      - purgeStart
      - purgeUpto
    - ArtifactsDir
  - DefaultJobTimeout
  - CommandRepository
    - location
    - reload cache (action)

And then have enpoints for:
`/api/config/server/urls`
`/api/config/server/artifacts`
`/api/config/server/defaultJobTimeout`
`/api/config/server/commandRepository`

Although everything just goes in as attributes for the `<server>` tag in config-xml. And the current UI just has one Save button. So this approach may be more *purist* than *practical*

Thoughts?

**Comment by ketan** [comment]
> So this approach may be more _purist_ than _practical_

Should we re-configure how the config XML looks in a manner that makes sense and then see how the API fits on top of that?

**Comment by akshaydewan** [comment]
> Should we re-configure how the config XML looks in a manner that makes sense and then see how the API fits on top of that?

Yeah, we should probably re-organize the attributes in the config XML. Though I would be wary of the underlying XML structure influencing the design of the API. I think of them as belonging to different layers. (But the fact that we let users edit the XML directly makes things a bit tricky.)

**Comment by msaurabh1978** [comment]
My two cents - Considering two main concerns here 1) current constraints and 2) making sure we maintain the sanctity of the API, what works for me keeping myself in the shoes of this API consumer, is having one configurable resource available at <code>/api/admin/config/server</code>.

When I as a consumer sees a resource like <code>/api/admin/config/server</code>, assumption that I have is not everything under the server is configurable but everything that is configurable under the server is available for configuration (that may not be the whole list).

Another obvious (un-called for) complexity with supporting sub-resources like <code>/api/admin/config/server/urls</code> etc is when multiple sub-resources are expected together to be read/written, then multiple API calls are the only way out.

**Comment by akshaydewan** [comment]
Although we lump all these configs together in the UI, I doubt if the user would want to change *all* of them at the same time. (Maybe just during the first time server setup)

Right now I'm leaning towards having the smaller API endpoints, with the groupings in my previous comment. For the UI, maybe we can make an `internal` endpoint that makes just one call (bit like a [BFF](https://samnewman.io/patterns/architectural/bff/)). We can also to re-think the UI and have smaller sections each with their own Save buttons.

**Comment by maheshp** [comment]
@akshaydewan how bout having one endpoint to configure the entire server `/api/admin/config/server` and another endpoint to `PATCH` specific entities. 

I am thinking of a scenario where a user tries to configure a new GoCD server using the API, having multiple entities for each endpoint would require a user to make multiple calls to configure it.

**Comment by akshaydewan** [comment]
> how bout having one endpoint to configure the entire server /api/admin/config/server and another endpoint to PATCH specific entities.

Server includes security, authConfigs, roles, backups etc. Do you mean these as well? Or just the ones listed above (urls, artifacts, etc)?

**Comment by maheshp** [comment]
> Server includes security, authConfigs, roles, backups etc. Do you mean these as well? Or just the ones listed above (urls, artifacts, etc)?

I meant just the ones listed above, not security, roles etc.

**Comment by akshaydewan** [comment]
Ok, I like the PATCH idea. Since all the other server configs are under `/api/admin/security`, (except `mailhost` and `backups`), I guess it should be OK and not confusing for users.

**Comment by akshaydewan** [comment]
Based on my discussion with @ketan we're thinking of having the smaller API endpoints as described in https://github.com/gocd/gocd/issues/4189#issuecomment-501597056 We'll also be reorganize the XML

**Comment by akshaydewan** [comment]
Updated API -

```
Endpoint /api/admin/config/server/site_urls
Payload:
{
  "siteUrl": "http://example.com/go",
  "secureSiteUrl": "https://example.com/go"
}
Verbs: GET, PUT, POST
```

```
Endpoint /api/admin/config/server/artifacts
Payload: (purgeSettings is optional)
{
  "purgeSettings": {
    "purgeStart": 10
    "purgeUpto": 20
  },
  "artifactsDir": "foo/bar/"
}
Verbs: GET, PUT
POST won't work because artifactsDir is already set on a new server
```

```
Endpoint /api/admin/config/server/default_job_timeout
payload
{
  "defaultJobTimeout": "15"
}
Verbs: GET, POST, PUT
```

```
endpoint /api/admin/config/server/command_repository
{
  "commandRepositoryLocation": "/foo/bar/repo"
}
Verbs: GET, PUT
POST won't work because commandRepositoryLocation is already set on a new server
```

Updated cruise-config.xml
```xml
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="124">
  <server jobTimeout="10" commandRepositoryLocation="default">
    <siteUrls>
      <siteUrl>http://build.gocd.org</siteUrl>
      <secureSiteUrl>https://build.gocd.org</secureSiteUrl>
    </siteUrls>
    <artifacts>
      <artifactsDir>artifacts</artifactsDir>
      <purgeSettings>
        <purgeStart>50.0</purgeStart>
        <purgeUpto>100.0</purgeUpto>
      </purgeSettings>
    </artifacts>
    ...
  </server>
</cruise>
```
We can do the xml migration as part of this issue or another.
