### ISSUE TITLE
Tracking tool related information missing in dashboard api

### ISSUE THREAD

**Issue by yankurk** [gocd/gocd#4192]
##### Issue Type

- API enhancement

##### Summary

[Tracking tool](https://docs.gocd.org/current/integration/index.html) related information is not present in dashboard api response. The api is consumed by dashboard SPA. Without tracking tool related information, one cannot link commit messages shown in SCM material related modification popups to external tools such as mingle or github.

##### Possible Fix

Tracking tool related information could be a part of comment section inside modifications as such:

```
{
  "material_type": "Git",
  "material_name": "bar",
  "changed": false,
  "modifications": [
    {
      "_links": {
        "vsm": {
          "href": "http://localhost:8153/go/materials/value_stream_map/fdf48a277a6f2ddf250b35d8e34ac9497971b7b742261e3d10be4f423ffb730c/963eb239c7b91eac2e15c727e06e908fd334e6f9"
        }
      },
      "user_name": "xyz<xyz@gmail.com>",
      "revision": "963eb239c7b91eac2e15c727e06e908fd334e6f9",
      "modified_time": "2016-12-13T22:09:14.000Z",
      "comment": "Add link in README <a href=\"https://github.com/gocd/gocd/issues/59\" 
                           target=\"story_tracker\">#59</a>"
    }
  ]
}
```

**Comment by yankurk** [comment]
This issue is related to #4121

**Comment by arvindsv** [comment]
One possible change would be to represent the comment not as HTML. As a list of fragments. Something like:

```json
comment: [
  {
    "type": "text",
    "value": "Add link in README "
  },
  {
    "type": "link",
    "value": "#59",
    "href": "https://github.com/gocd/gocd/issues/59"
  },
  {
    "type": "text",
    "value": "... anything else that follows."
  }
]
```

However, it does seem like overkill for this. Feel free to keep it simple instead.

**Comment by maheshp** [comment]
How bout?

```
"modifications": [
    {
     ....
      "comment": "Add link in README #59 and #60",
      "issue_tracker": [
        {"issue_no": "#59", "link": "https://github.com/gocd/gocd/issues/59"},
        {"issue_no": "#60", "link": "https://github.com/gocd/gocd/issues60"}
      ] 
    }
```

We can think of better keys, but the idea is to keep the comment as is and represent the issue tracker links separately.

**Comment by yankurk** [comment]
I think comments should include links because a comment in plain text doesn't make sense. However, due to all the escaping that needs to be done (and also as @arvindsv said, it doesn't force the client to use HTML), I think avoiding anchor tags in json strings is better. I prefer @maheshp's structure but with `issue_tracker` within `comment` since it is only relevant to comments. This structure makes it clear to an api consumer what the comment text is and what are it's tracking related information, if any. Any consumer concerned only about comment as a plain string will be able to use it directly (although the same is possible in @arvindsv's structure but it seems less clearer). The structure I'm thinking of looks like this:
```
"modifications": [
    {
     ....
      "comment": {
      "text": "Add link in README #59 and #60",
      "trackers": [
        {"pattern": "#59", "link": { "href": "https://github.com/gocd/gocd/issues/59"}},
        {"pattern": "#60", "link": { "href": "https://github.com/gocd/gocd/issues/60"}}
      ] 
    }
```
I'm not sure about the key names, specifically `pattern`. Thoughts?

**Comment by yankurk** [comment]
There is also a need to represent multi line comments. Currently, the api returns a single string containing `\n` for new lines. I guess we could do the same in the `text` section as such:
```
"comment": {
      "text": "Add link in README #59 and #60\n another line \n another line",
      "trackers": [
        {"pattern": "#59", "link": { "href": "https://github.com/gocd/gocd/issues/59"}},
        {"pattern": "#60", "link": { "href": "https://github.com/gocd/gocd/issues/60"}}
      ] 
    }
```

We can then substitute the `\n`s with `<br/>` tags on the client side using javascript.

**Comment by ketan** [comment]
My understanding is that this becomes to complex to render if pieces of information come from the server. IMO, sending the raw commit message, along with the tracking tool config, should be sufficient to render the raw commit message in the view. This also guarantees that apis render raw commit message without any post-processing.

Additionally, we should be able to throw in some client side markdown library to render the commit message in markdown.

FYI. Here is how github shows the commit API renders the commit:

```
$ curl -s https://api.github.com/repos/gocd/gocd/commits/23eb465f0b366378c526c70642c3d0748ce47e2e | jq '.commit.message'
"Delete entities associated with a job\n\nWhen a job completes, a lot of entities are left behind in the DB. These\npersisted entities are copies of the config at the time the job was\nscheduled, and is not used once the job completes.\n\nFor jobs that are already completed (as per DB), and for those jobs that\nwill complete from this point onwards:\n\n* delete environment variables that are not trigger-with-options\n* delete all artifact plans that are of type `file`. Artifact plans of\n  type `unit` are retained for shine.\n* delete all artifact properties generators\n* delete all (agent) resources associated with a job\n* delete all elastic agent metatada\n\nSince some of the data in the DB will eventually go missing, the job\nfeed api will break. We will no longer render the environment variables,\nresources and build artifacts in the job xml api."
```

**Comment by arvindsv** [comment]
Pick whatever is simple. If it's a lot of trouble to send it in pieces and combine it on the client side, something simpler like Markdown is fine too. It's one thing to be "pure", but it can end up being hard to consume even for external consumers.

**Comment by jyotisingh** [comment]
I think the `text` field should contain the entire comment/commit-message. Most API consumers would definitely care about the full comment I think, so (to me) it doesn't sound right to make all of them implement the logic of appending all the pieces of text. For those who care about the link to tracking tool, we could send across the information required for them to do that. 

I am not sure if I fully understand the difference between what @maheshp, @yankurk and @ketan are suggesting. To me it seems that all three of them are suggesting sending across the full comment along with the information which would be used on the client side to add the links. The only difference that I can see is about sending across the tokens which need to be replaced and their replacements vs sending across the config ie. the regex and replacement format. Either of them sound okay to me. 
One of the other things to consider would be GoCD supports two kinds of tracking tools - Mingle and custom. Just check how would that be taken care of if we choose to send across the config information to the client, and if it would be too much work for the clients.

**Comment by ketan** [comment]
@yankurk — all yours
