### ISSUE TITLE
Improve: email notification

### ISSUE THREAD

**Issue by v1v** [gocd/gocd#42]
It would be useful to have email notifications of build status similar to what CC provided.

The emails would be sent per job when
- the build fails
- the build goes from failed to fixed

The email would have 
- a link to the job
- for all platforms the build stderr
- the test results
- Any Go failures
- a list of the materials that caused to the build

**CC email example**
##### SUBJECT

Subject: datasrc 259127 Build Fixed
###### Summary

View results here -> http://cruisecontrol/buildresults/datasrc?log=log20130
BUILD COMPLETE -  259127 
Date of build:  2013-05-07T12:13:54
Time to build:  5 minutes 13 seconds
Last changed:   2013-05-07T10:23:32
Last log entry: PDSDK-294: Upgrading OpenSSL to version 0.9.8y. Jobs fixed ... PDSDK-294 on 2013/05/07
###### Errors/Warnings: (3)

cygwin warning:
MS-DOS style path detected: \software\cruisecontrol/test_kits
Preferred POSIX equivalent is: //software/cruisecontrol/test_kits
CYGWIN environment variable option "nodosfilewarning" turns off this warning.
WARNING: No DataSourceSDK44Overview.pdf
###### Unit Tests: (44)

All Tests Passed        
###### Modifications since last successful build:  (1)

259119  andys    PDSDK-294: Upgrading OpenSSL to version 0.9.8y.
 Files affected by this changelist:  (17) 
    edit    //XXX/V-4_4/datasrc/RELEASENOTE.txt  65 
    branch  //XXX/V-4_4/libs/openssl/check-version.sh  1 

Thanks

**Comment by srinivasupadhya** [comment]
I have added [notification end-point](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html). Should be available in 15.1.0. Hopefully you should be able to write a plugin for this. What do you think?

**Comment by dsenecalb** [comment]
+1

**Comment by arvindsv** [comment]
Closing as stale.
