### ISSUE TITLE
Pipeline Operations API does not pause/unpause a pipeline provided case insensitive name.

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4200]
##### Issue Type
- Bug Report

##### Summary
Pipeline Operations API does not pause/unpause a pipeline provided case insensitive name.
For pipeline `Up42`, when `up42` name is used to pause/unpause a pipeline, the API returns 200, but the pipeline is not paused/unpaused.

##### Steps to Reproduce

1. Create a pipeline with capital name say `UP42`
2. Use [Pipelines API](https://api.gocd.org/current/#pipelines) to pause the pipeline using `up42` name
3. The API returns 200. but the pipeline is not paused.

##### More Information

On the [`pipelineLabelCounts` table](https://github.com/gocd/gocd/blob/a32356ba7c450fc299401c64146429f0f5e4717a/server/db/migrate/h2deltas/7_add_pipeline_label_counters.sql#L17-L21) (which stores the pause/unpause information), the type of the `pipelineName` field is set to `VARCHAR` instead of `CITEXT`, which causes the lower case `pipelineName` to differ from the upper case `pipelineName`.

The type of the field can't be directly changed to `CITEXT` due to [`UNIQUE KEY` constraint](https://github.com/gocd/gocd/blob/a32356ba7c450fc299401c64146429f0f5e4717a/server/db/migrate/h2deltas/7_add_pipeline_label_counters.sql#L23) on the `pipelineName`.

##### Possible Fix
Add a database migration to remove all the entries from the `pipelineLabelCounts` table where the `pipelineName` does not match the pipelines defined in `config.xml` (considering the case) and alter the `pipelineName` field type to `CITEXT`.

**Comment by varshavaradarajan** [comment]
Fixed by @jyotisingh in https://github.com/gocd/gocd/pull/4690
