### ISSUE TITLE
Usage of artifact.warning.size.limit - stops building/scheduling?

### ISSUE THREAD

**Issue by abracadv8** [gocd/gocd#4224]
##### Issue Type

Bug Report

##### Summary

The GoCD UI allows you to set a "cleanup threshold" where if disc space gets to a certain threshold, it will delete files to gain space back.  Unfortunately, it doesn't warn you when it will happen.

I saw the property `-Dartifact.warning.size.limit=111111` and assumed it could send a warning to let us know before the disk gets low enough for a purge.

Unfortunately, the property does more than just send a warning email, it *completely stops pipeline scheduling*.  Is this intentional?  

I would assume "warning" means send an email or log a warning, and continue as normal.

###### Basic environment details

* Go Version: 16.6.0 (3590-af0f8b8ae8a4342ab748ce80224971887f018ccc)
* JAVA Version: 1.8.0_40
* OS: Linux 3.10.0-123.20.1.el7.x86_64
* Browser vendor and version (if relevant): Firefox Quantum

###### Additional Environment Details

None - basic Gocd environment

##### Steps to Reproduce

1. Set -Dartifact.warning.size.limit= to some value
2. Run below that value on disk space

##### Expected Results

Expect:  Get warning logs and emails, but builds continue as normal

##### Actual Results

Actual: Got warning logs and emails, and pipelines stopped scheduling.

##### Possible Fix

Should warning states on the disk space cause a failure?  

DiskSpaceOperationResult.java should be `canContinue=true` for warning messages.

From my limited ability to trace the issue:

ArtifactsDiskSpaceWarningChecker 
* createFailure sets a bunch of warnings for OperationResult that disk space is getting low: - result.warning("Go Server's artifact repository is running low on disk space", msg, ARTIFACTS_DISK_FULL_ID); 
https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/service/ArtifactsDiskSpaceWarningChecker.java#L44-L48

DiskSpaceOperationResult
* result of warning has canContinue = *false* by default  *is this correct?*
https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/service/result/DiskSpaceOperationResult.java#L49-L52

MaterialUpdateListener
* The materials update fails becuase isLowOnDisk is true, with a reason of `Cruise server is too low on disk to continue with material update`
https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/materials/MaterialUpdateListener.java#L49

GoDiskSpaceMonitor
* Monitor calls list of checkers using resultFor()
* Note, if canContinue() is false, then !result.canContinue == outOfDisk == true
https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/cronjob/GoDiskSpaceMonitor.java#L90-L96

##### Log snippets

```
2018-01-24 18:49:42,873  WARN [goDiskSpaceMonitorThread] ArtifactsDiskSpaceWarningChecker:45 - Go has less than 468000M of disk space available to it.
2018-01-24 18:49:45,438  INFO [qtp787604730-1128562] PipelineScheduler:137 - [Pipeline Schedule] [Requested] Manual trigger of pipeline 'service_name-build' requested by **USER_REMOVED**
2018-01-24 18:49:45,440  INFO [qtp787604730-1128562] PipelineScheduler:143 - [Pipeline Schedule] [Accepted] Manual trigger of pipeline 'service_name-build' accepted for user **USER_REMOVED**
2018-01-24 18:49:45,441  INFO [qtp787604730-1128562] PipelineScheduler:146 - [Pipeline Schedule] [Processed] Manual trigger of pipeline 'service_name-build' processed with result 'com.thoughtworks.go.serverhealth.ServerHealthState@4ec932ad[healthStateLevel=OK,type=<HealthStateType DATABASE_DISK_FULL LogScope[GLOBAL, scope=GLOBAL]>,message=,description=,expiryTime=<null>,timestamp=Wed Jan 24 18:49:45 UTC 2018]'
2018-01-24 18:49:45,442 ERROR [62@MessageListener for MaterialUpdateStatusNotifier] BuildCauseProducerService:349 - not scheduling pipeline service_name-build after manual-trigger because update of material failed with reason Cruise server is too low on disk to continue with material update
2018-01-24 18:49:47,874  WARN [goDiskSpaceMonitorThread] ArtifactsDiskSpaceWarningChecker:44 - Go has less than 468000M of disk space available to it.
2018-01-24 18:49:47,874  WARN [goDiskSpaceMonitorThread] ArtifactsDiskSpaceWarningChecker:45 - Go has less than 468000M of disk space available to it.
```

**Comment by ketan** [comment]
> Expected Results
> Expect: Get warning logs and emails, but builds continue as normal
> 
> Actual Results
> Actual: Got warning logs and emails, and pipelines stopped scheduling.

This is intentional. The reason we stop scheduling with low disk space is that this can potentially cause the built-in DB to get corrupted because there is no more disk space available, this can also cause other issues when artifacts are constantly being uploaded from agents, and some of these artifacts on the server become corrupted because the server runs out of disk space when writing to them.

I'm going to mark this as closed. But if you think this is in error let us know and we can re-open this issue.

**Comment by arvindsv** [comment]
@ketan I don't know if this value has been changed, but my only concern would be that it's complaining about wanting "468000M". That's 468GB.

But, I agree that it's expected behavior.

**Comment by abracadv8** [comment]
That number was was just an example I was testing with.  

Is there any feature that will warn a user that disk space is filling up before the artifact purge task deletes artifacts?

Some of our pipelines only build once in a long while so the more recent pipelines can cause the old ones to be purged.  It would be nice if there were an actual message to warn the user that the purge might occur soon.

**Comment by ketan** [comment]
I think you may be interested in subscribing to https://github.com/gocd/gocd/issues/410

> It would be nice if there were an actual message to warn the user that the purge might occur soon.

I think that's a reasonable ask. Would a message in the errors and warnings popup (top right) help?

This is currently not on the radar for the GoCD team, but if you're interested in contributing some code, someone can point you as to how you can get a message shown in there.

**Comment by abracadv8** [comment]
Thanks -- that is similar to our use case - some sort of strategy to delete only the oldest files first, excluding any pipelines 'in flight'.  I'll take a look at that.
