### ISSUE TITLE
GO Admin notifications

### ISSUE THREAD

**Issue by jasonduff** [gocd/gocd#423]
Would be nice to have the ability to add more admin notification functionality.  This is especially useful in a compliance heavy environment where there needs to be governance of activity that could lead to issues.  Or, for general housekeeping of GO (especially agents).  For instance:
- when a user is added
- when a user is given "admin" permissions
- when an agent is added
- when an agent's status goes to "missing" or "lost contact" (this can lead to big deployment issues if missed, btw)
- when a pipeline is triggered or fails in a certain environment (e.g. Production)

Think enterprise mgmt here and we could probably come up with more.

Thanks.

**Comment by srinivasupadhya** [comment]
I have added [notification end-point](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html). Should be available in 15.1.0. Currently it only supports "stage status change" event notification. Hopefully I should be able to add more events soon.

**Comment by arvindsv** [comment]
Closing, since the notification endpoint is the way to do this.
