### ISSUE TITLE
Introduce an errors and warnings API

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4231]
##### Issue Type

- Feature enhancement

##### Summary

Introduce an errors and warnings endpoint so that we can show it on the dashboard. None of the newer SPAs have errors and warnings on them, because the current `messages.json` endpoint is not an API endpoint and renders HTML inside a JSON payload.

Note:

For the first cut, we'll render this using an API that renders the current server health messages as JSON. Authorization will be tackled on in a later story, as this requires significant efforts on the backend where server health messages are being generated (by sending information about specific entities where the error is at).

**Comment by rajiesh** [comment]
Verified on 18.2.0 (6215-1a3f4adf5f908dcf4186c24f65c24fcda50d8e78)
