### ISSUE TITLE
Pipeline unlocking API

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4237]
##### Issue Type

- Feature enhancement

##### Summary

Add ability to unlock a pipeline using an API endpoint.

**Comment by ketan** [comment]
Use this controller https://github.com/gocd/gocd/blob/master/api/api-pipeline-operations-v1/src/main/java/com/thoughtworks/go/apiv1/pipelineoperations/PipelineOperationsControllerV1Delegate.java

**Comment by ketan** [comment]
@rajiesh — can we get a round of testing on this and close?

**Comment by rajiesh** [comment]
Verified on 18.2.0 (6215-1a3f4adf5f908dcf4186c24f65c24fcda50d8e78)
