### ISSUE TITLE
remove "Environment" page, merge features with others

### ISSUE THREAD

**Issue by jasonduff** [gocd/gocd#424]
Seems like the Environment page could be removed completely.  The few benefits it provides (adding pipeline to an env, indication of material change...) could be added elsewhere.  The env page literally takes minutes to load when you have over 1000 pipelines which makes it almost unusable.

For instance:
- adding a pipeline to an env -> This could be added as a select list from the pipeline page.  This could show up for admins and not for others.
- indication of material change (The "i" icon) -> This could be added to the pipeline page
- ability to view by env -> This could be added to the pipeline admin page.  Instead of a staic page, put the info into a grid, add a "env" & "pipeline group" columns.  Then you can sort by either and get the info you need in one page.

Thanks.

**Comment by arvindsv** [comment]
This was done a while ago. Closing.
