### ISSUE TITLE
Webhook support for hosted BitBucket server

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#4241]
##### Issue Type

- Bug Report

##### Summary

Currently, below is configurable for the BitBucket SaaS version (Bitbucket.org) but not for the hosted instance.

https://{webhookSecret}:x@gocd.example.com:8154/go/api/webhooks/bitbucket/notify

For hosted instance, GoCD expects (refer [this](https://github.com/gocd/gocd/blob/cba9fd72860ec1858d63ea27a8251275da6b1fcd/server/webapp/WEB-INF/rails.new/app/controllers/api/web_hooks/bit_bucket_controller.rb)) event-key, body with payload in a json format and user agent which is specific to bitbucket when a post request is received from Bitbucket. If any of the element is missing, you will see an error something like below.

###### Basic environment details

* Go Version: All versions

###### Workaround 

Use below curl command to notify request:

curl -H 'Content-Type: application/json' -H 'X-Event-Key: repo:push' -v --user SECRET:x -d @payload.json  -X POST -A 'Bitbucket-Webhooks/2.0' https://gocd.example.com:8154/go/api/webhooks/bitbucket/notify

Attached payload.txt file can be used as reference. 

[payload.txt](https://github.com/gocd/gocd/files/1665614/payload.txt)

**Comment by renaldrozario** [comment]
Do you have webhooks in pipeline for hosted bitbucket?

**Comment by joedai** [comment]
Do we have any roadmap items created to support hosted bitbucket in the future? If so will that be in a recent release?

**Comment by bashazaid** [comment]
Any support for the Hosted Bitbucket server in latest GoCD versions?
We are using GoCD v20.9 and trying to configure webhooks for pipeline from hosted bitbucket server but the end points are not working.
Endpoints tried are :
https://user:passwd@gocd.example.com:8154/go/api/webhooks/bitbucket/notify/

https://user:passwd@gocd.example.com:8154/go/api/material/notify/bitbucket/?repository_url=repo.url.git

both are not working for me, giving the 400 error, not supported.

Any other ways we can do the webhook configuration with bitbucket server, I also tried with SCM and SCM plugin, not working for bitbucket server.

**Comment by piyushsh** [comment]
Any update on this issue, we are also facing similar issue on our side. Any support would be really appreciated.

**Comment by sriramnrn** [comment]
Per the documentation at https://api.gocd.org/current/#hosting-on-bitbucket

one should use https://{
***@***.***:8154/go/api/webhooks/bitbucket/notify


To secure the http endpoint, the webhook configuration on bitbucket must
specify a Basic Authentication User, the value of the Basic Authentication
User should be same as the value of the webhookSecret attribute on the
<server/> element in the file cruise-config.xml. Do not specify any basic
authentication credentials in the webhook URL.

Here's an example of webhookSecret:
https://github.com/gocd/gocd/blob/3e948218bfb163c5c3d2bf5140cb4a12f110769e/server/config/cruise-config.xml#L3

Could you try that and report?

-- Ram

**Comment by piyushsh** [comment]
Replied here https://github.com/gocd/gocd/issues/9087#issuecomment-814276896

**Comment by sriramnrn** [comment]
I've responded to [#9087](https://github.com/gocd/gocd/issues/9087#issuecomment-815068554) where I've provided information on troubleshooting. Essentially, Bitbucket seems to make providing a secret to be optional and sends a required header only if this optional secret is made available.

**Comment by chadlwilson** [comment]
If anyone comes across this see https://github.com/gocd/gocd/issues/9087#issuecomment-1027682844 - make sure you are using the right notification URL. I will try and get the documentation corrected to avoid this confusion.

**Comment by chadlwilson** [comment]
I've now properly documented configuration for self-hosted Bitbucket Server at https://api.gocd.org/22.1.0/#hosting-on-bitbucket-server
