### ISSUE TITLE
GoCD Helm chart release

### ISSUE THREAD

**Issue by sheroy** [gocd/gocd#4242]
##### Issue Type
- Feature proposal

##### Summary

This issue tracks the work remaining to release the GoCD Helm chart 
- [x] [Better UX] Update defaults in the Helm chart
   - [x] Disable static agents 
   - [x] Enable ingress
   - [x] Fix API versions
   - [x] Enable persistence: Be default, all GoCD configuration should be stored on PVs, upgrading a helm chart shouldn't wipe out configuration. 
---
- [x] Merge Helm chart to stable    
- [x] Docker in Docker support:
    - [x] [Better UX] Enable privileged mode for the GoCD agent image - DinD images shouldn't necessitate a pod yaml
    - [x] Publish a DinD GoCD agent image based on `docker:dind` base image.
    - [x] Accessing artifacts (such as test reports) 
    - [x] Test edge cases - SELinux based agents, 
    - [x] Documentation for using monster image if DinD doesn't work for you

---
- [ ]  Elastic Agent - remaining work
    - [x] Update EA plugins to conform to the new API 
        - [x] Kubernetes plugin
        - [x] ECS plugin
        - [x] Docker swarm plugin
    - [x] Status report page usability improvements  
       - [x] "no assigned agent yet" message 
       - [ ] Suffers from all the clickety clickety drilling down that anything associated with a job suffers from
       - [ ] Loads of information, how do you know if good things are happening?
       - [ ] High-level status and the rest is detail? Or maybe put the task status at the top. 

    - [x] 24 hour performance test. Discuss the outcomes of the previous performance run and the resolution of issues. 
    - [x] [Better UX] Error reporting on the status report page
---
- [x] Documentation:
    - [x] Getting Started guide for using the helm chart and the elastic agent. Should probably also talk about the DinD build workflow. 
    - [x] Sample pipeline that deploys a demo app to K8S 
    - [x] Recommendations for bundling build time dependencies with custom GoCD agent Docker images if the DinD workflow doesn't work for you. 
    - [x] Recommendations for size of K8s cluster to run GoCD. 
    - [x] Troubleshooting guide
---
- [x] Marketing: 
    - [x] Landing page 
    - [x] Blog post

---

- [x] Pre-configure elastic agent (2nd iteration):
    - [x] [Better UX] Includes the GoCD agent Docker image and the K8S cluster url 
    - [ ] Explore `PersistentVolumeClaimResize`
---

**Comment by bdpiparva** [comment]
# Improvements for `NOTES.txt`
  * helm install --name gocd-app --namespace gocd incubator/gocd
   1. Get the go-server ip using 
       `$ ip=$(kubectl get ingress gocd-app-gocd-server -o jsonpath="{.status.loadBalancer.ingress[0].ip}")` (put --namespace)
        
         - [ ] Update it with --namespace gocd
        
   2. Get a GoCD internal URL for plugin settings
       `$ echo "https://$(kubectl --namespace gocd get service gocd-app-gocd-server  -o jsonpath='{.spec.clusterIP}'):8154/go"`
       
         - [ ] Update a note.txt with above command how to get GoCD SSL url for agents
   3. Get Cluster url `kubectl cluster-info`
         - [ ] Put on note.txt
         
   4. Get token `kubectl --namespace=gocd get secret -o jsonpath='{.items[1].data.token} ' | base64 --decode`
         - [ ] `kubectl get some-command` always returns base64 encoded values for secretes and certs. Update command with `base64 --decode` to decode the values
         
   5. Get a certificate `kubectl --namespace=gocd get secret -o jsonpath='{.items[1].data.ca\.crt}' | base64 --decode`

**Comment by GaneshSPatil** [comment]
@bdpiparva @varshavaradarajan @sheroy -- any updates on this?

**Comment by ketan** [comment]
Closing most of the bigger points are done. Can open specific issues for additional features or improvements.
