### ISSUE TITLE
Go.cd server returns 500 errors after a time of inactivity

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#4247]
##### Issue Type

- Bug Report

##### Summary

After leaving go.cd server open in a tab for more than 30 minutes without interaction on the pipelines page the /go/pipelines.json and /go/server/messages.json request start throwing 500 errors.

The logs show the following error:

##### Environment

```plain
  "Go Server Information": {
    "Version": "18.1.0 (5937-8a847b96ee8d38173f80178ed1285f0e53a970e0)"
  },
  "Config Statistics": {
    "Valid Config": {
      "Number of pipelines": 458,
      "Number of agents": 23,
      "Number of environments": 0,
      "Number of unique materials": 133,
      "Number of schedulable materials": 120
    },
    "Security": {
      "Plugins": [
        {
          "Google oauth authorization plugin": true
        },
        {
          "Password File Authentication Plugin for GoCD": true
        },
        {
          "LDAP Authentication Plugin for GoCD": false
        }
      ],
      "Enabled": true
    }
  }
```

###### Basic environment details

* Go Version: `18.1.0 (5937-8a847b96ee8d38173f80178ed1285f0e53a970e0)`
* JAVA Version: `1.8.0_131`
* OS: `Linux 4.4.86+`

##### Steps to Reproduce

1. Run a go.cd server with Google Oauth set up
2. Open the pipelines tab and open Chrome's network tab
3. Wait for more than 30 minutes

##### Expected Results

Api requests either return successfully or the browser redirects to the login page

##### Actual Results

Api requests fail with 500 error. When clicking on another tab in go.cd server returns a too many redirects error and only cleaning cookies gets rid of the redirects

##### Log snippets

```
2018-01-29 12:40:25,515 ERROR [qtp1399499405-52162] BasicAuthenticationFilter:64 - java.lang.RuntimeException: Interaction with plugin with id 'cd.go.authorization.google' implementing 'authorization' extension failed while requesting for 'go.cd.authorization.authenticate-user'. Reason: [java.lang.RuntimeException: Api call to `/oauth2/v1/userinfo` failed with error: `{
"error": {
"errors": [
{
 "domain": "global",
 "reason": "authError",
 "message": "Invalid Credentials",
 "locationType": "header",
 "location": "Authorization"
}
],
"code": 401,
"message": "Invalid Credentials"
}
}
`]
```

**Comment by ketan** [comment]
Did you upgrade the plugin or gocd recently? What was the previous version of the plugin and GoCD that you upgraded from?

**Comment by JorritSalverda** [comment]
I upgrade go.cd with every version, so the previous one was 17.12.0. The google oauth authorization plugin is the latest available, see https://github.com/Travix-International/docker-gocd-server/blob/18.1.0/Dockerfile#L24. Not entirely sure whether I used previous versions of the authorization plugin, since we used to use the deprecated auth plugin before.

**Comment by ketan** [comment]
Do you happen to have a stacktrace from the server during the time this error happened?

**Comment by JorritSalverda** [comment]
The logs don't show more than what's already in the issue description. Can I change log verbosity to get more detail?

**Comment by ketan** [comment]
Can you send across all the logs in a zip file over to support (@)
thoughtworks.com with a link to this issue? Someone can take a look and see
if there is anything relevant there. Also knowing the specific time window
when this happened would be useful to drill logs further.

**Comment by JorritSalverda** [comment]
Thanks, I just mailed the log files from the go.cd server to support. Hope it helps figure out the cause.

**Comment by arvindsv** [comment]
Looks to be fixed in https://github.com/gocd/gocd/pull/4274
