### ISSUE TITLE
Value stream map - add map for pipelines that have not been triggered

### ISSUE THREAD

**Issue by jasonduff** [gocd/gocd#425]
Currently, the Value Stream Map is for historical purposes (after a pipeline has been run once).  Would be nice to have a VSM after the pipelines have been built but before it/they have been run.  This is helpful to visualize and verify that it is setup as expected at a glance before running.

Thanks.

**Comment by FredrikWendt** [comment]
Simply being able to see a "skeleton" VSM from config only, would be very useful.
