### ISSUE TITLE
No indication of a successful checkout done by SCM plugins

### ISSUE THREAD

**Issue by yankurk** [gocd/gocd#4253]
##### Issue Type
- Feature enhancement

##### Summary

Currently no indication is provided on job consoles upon checkout (successful or not) of a material using SCM plugins. A message indicating success (or failure) will help reduce confusion for end users.

##### Steps to Reproduce
1. Download any [SCM plugin](https://www.gocd.org/plugins/#scm)
2. For a pipeline, setup a material using the plugin
3. Run the pipeline
4. Open job console for one of the jobs in the pipeline

##### Expected Results

There needs to be a message indicating completion of the material checkout.

##### Actual Results

There are no messages indicating completion of the material checkout.

**Comment by arvindsv** [comment]
Closing as stale.
