### ISSUE TITLE
Dashboard tile

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4254]
##### Issue Type

- Feature enhancement

##### Summary

List of things we need on the dashboard tile:

- [x] Show Pipeline Name.
- [x] Pipeline Name redirects to Pipeline History Page.
- [x] Show Pipeline Settings icon (Depending on the Pipeline permissions).
- [x] Show Pipeline Instance label.
- [x] Show Compare Pipeline Link.
- [x] Show Changes drop-down. As part of changes, show which material caused the pipeline to trigger. (#4114)
- [x] Linkify issue numbers in changes dropdown (#4192)
- [x] Show VSM link
- [x] Show Triggered By Information
- [x] Show Triggered On Information
- [x] Show Stages Status
- [x] Show pipeline paused by and pipeline paused cause when pipeline is paused
- [x] Show Pipeline operations response message.
    - `Operations`: Trigger, pause, unpause pipeline
    - `Example`: `Request for scheduling pipeline up42 accepted successfully.`
- [x] Show multiple stages instance for parallel pipeline executions. (Multiple stages instance).

**Comment by arvindsv** [comment]
When a pipeline has never run, it looks like this:

<img width="291" alt="2018_02_02_15-37-44" src="https://user-images.githubusercontent.com/172235/35753791-100c5b30-082f-11e8-98a7-70796eb6ac06.png">

Should we consider showing a message?

**Comment by eeluke** [comment]
Yes, we should. White area below action buttons should contain a short message like "You haven't run this pipeline yet. Click the play button to run pipeline."

**Comment by GaneshSPatil** [comment]
##### Show on hover information for:
- [ ] Pipeline Name. (In case of long pipeline name, last few characters of pipeline name are stripped. On hover of the pipeline name, show the entire pipeline name).
- [ ] Scheduled at server time.
- [ ] Stage Instance Status.

**Comment by FredrikWendt** [comment]
Regarding "You haven't run this pipeline yet. Click the play button to run pipeline." <- can we turn this off? The play button doesn't respect fan-in-fan-out, which cause confusion (much later when things don't work as expected, so the cost is really high for this). See #1924

I'm asking for the default "call to action" to NOT trigger the one flaw that breaks the biggest, single (unique) selling point of GoCD over other tools.

**Comment by GaneshSPatil** [comment]
Done as part of **New Dashboard** feature in GoCD `v18.3.0`
