### ISSUE TITLE
Extend Notifications endpoint to add agent status change notifications 

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#4260]
##### Issue Type
- Feature enhancement

##### Summary
Enhance Notification endpoint to notify plugins with agent status change. This information could be useful to build metrics around agent utilisation.

**Comment by maheshp** [comment]
Scenarios to notify agent status change.

1. Server starts and agent instances are created
  - **Ignore** As part AgentService sync AgentInstance are created using AgentInstance#createFromConfig - do not notify agent state change wait for the next ping from agent to send the notification
  - **Ignore** When an AgentInstance is created its intial runtime status would be missing, and on subsequent update it would change 

2. Running Server and new agent auto registers
  - **Ignore** Post agent creation in config AgentInstance sync is called and we do not need to notify 
  - **Ignore** Post creation of agent in config agent instance is refreshed and we do not notify as the agent runtime status is still missing

3. Running Server and new agent registers (non-auto)
  - **Ignore** Do not post notifications for Pending agents

4. Running server and existing agent pings
  - **Notify** Agent ping updates the agent runtime status, notify on change of of runtime status

5. Server agent instance refresh
  - **Notify** Refresh is called from a spring timer - notify if the agent goes missing or lost contact 

6. Agent config change
  - **Notify** Also, AgentChangeListener class AgentService#sync which is passed with all the agents in config - this would do a AgentInstance#syncConfig if the instance is already in 
memory. We should notify in AgentInstance#syncConfig only if the agent config status has changed.

7. Full config change
  - **Notify** Also, AgentChangeListener class AgentService#sync which is passed with all the agents in config - this would do a AgentInstance#syncConfig if the instance is already in memory. We should notify in AgentInstance#syncConfig only if the agent config status has changed.

8. How do we handle elastic agents, do we need to notify on agent delete?


9. Agent update runtimeinfo

10. Disable agents
  - **Notify** Notify if an agent is disabled

11. Enable agents
  - **Notify** Notify if an agent is enabled

**Comment by GaneshSPatil** [comment]
@maheshp -- can we consider this feature request as implemented and close the issue?

**Comment by maheshp** [comment]
Yes, done as part of `18.3.0`
