### ISSUE TITLE
Feature proposal - notifications

### ISSUE THREAD

**Issue by HayleyMcM** [gocd/gocd#4285]
##### Issue Type

- Feature proposal

PUSH NOTIFICATION/ALERTS

##### Summary

When a deployment is going through the pipeline, it is easy to then get sidetracked and begin another task.

Therefore it would be helpful to receive an alert/push notification when a  specific deployment has gone through or if the pipeline has failed.

###### Basic environment details

n/a

###### Additional Environment Details

n/a

##### Steps to Reproduce

n/a

**Comment by ChennyBaBy** [comment]
If the setup stage for GoCD can configure in a step for hooking up your own push notification would be cool~! 👍 
![bitmoji](https://render.bitstrips.com/v2/cpanel/78048204-cb40-44e7-ace4-a0064c4af63f-2500389d-4018-4645-9664-7b4b57bd239d-v1.png?transparent=1&palette=1&width=246)

**Comment by arvindsv** [comment]
Thank you for this. This is unlikely to be in GoCD core. So, I will close this. But, have you tried any of the [notification plugins](https://www.gocd.org/plugins/#notification)? That's probably the right place for this. Either an existing one or a custom one.

**Comment by arvindsv** [comment]
Oh, also, you can setup [email notifications](https://docs.gocd.org/current/configuration/dev_notifications.html) if you like.
