### ISSUE TITLE
Resolve upstream materials to consistent revisions in 'trigger with options' popup

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#429]
Add fan-in resolution for trigger with options. User can open the revision selection popup, select revisions for the materials user cares for & click 'resolve revisions' which could resolve the revisions for other upstream materials & fill the pop-up. This would help users select consistent upstream revisions without having to manually resolve them.

Provide "resolve & trigger" button. This is an extension of the first "resolve for trigger with options" feature. People want pipeline to be manual trigger but want it to be consistent.

**Comment by orfjackal** [comment]
I'd like the ability to configure per material whether it should use the latest revision or resolve by default. Like this:

    <git url="https://github.com/example/sourcecode.git" defaultRevision="latest" />
    <git url="https://github.com/example/sourcecode.git" defaultRevision="resolve" />

In Go 14, when a pipeline is triggered automatically, it works like the "resolve" setting, and when a pipeline is triggered manually, it works like the "resolve" setting. Thus maybe there should also be a setting `defaultRevision="auto"` which would maintain the current behavior and would be the default value. Alternatively this could be split into two parameters for automatic and manual triggering, where the default values would be `autoDefaultRevision="resolve" manualDefaultRevision="latest"` (though the names could be better).

This should solve the use cases mentioned in #237 and https://groups.google.com/d/msg/go-cd/a7G9BK0SEBk/EZxlqM_rWJEJ

This solution might also work for #437

**Comment by tifigs** [comment]
+1 (does this count as 'interest from someone?' :) )

**Comment by tifigs** [comment]
for anyone stumbling on this issue: what kind-of-works as a workaround (at least for my use case):

* create a no-op stage that automatically triggers (with the dependencies you want)
* keep your follow-up stages on manual, so you can still manually approve steps. The first, automatically triggered stage has the 'auto' semantics as described by @orfjackal

**Comment by chadnash** [comment]
This has been around for 4 years any chance it might get done?

**Comment by arvindsv** [comment]
@chadnash Unlikely any time soon. No one I know is working on any area close to it. It's a complicated area, to say the least.

**Comment by arvindsv** [comment]
Stale.
