### ISSUE TITLE
Browser Server Websocket for Dashboard and Agents Page

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4291]
##### Issue Type

- Feature proposal

##### Summary
Implement browser server WebSockets for dashboard, agents and other pages which do ajax polling.

for Websocket communication between browser and server (for quicker dashboard page),
When the cache is updated, the updated pipeline(s) information is remembered by the WebSocket implementor (using listeners) and flushed to the browser after a specific period of time.

**Comment by GaneshSPatil** [comment]
@arvindsv @maheshp @ketan  -- we discussed the delta API for the new dashboard. With WebSocket communication, the overhead of computing delta goes away (as on each update, the WebSocket implementor remembers the changeset).

We still need to implement [Dashboard should return 304 if unchanged](https://github.com/gocd/gocd/issues/4289), as few [browsers does not support websockets](https://caniuse.com/#search=websocket).

thoughts? comments?

**Comment by arvindsv** [comment]
So, you're saying: Don't implement an actual delta API. Instead only users who use websockets will get the deltas pushed to them?

Either way, what is needed for right now is [#4289 - Dashboard should return 304 if unchanged](https://github.com/gocd/gocd/issues/4289). Delta is optional + later?

**Comment by GaneshSPatil** [comment]
@arvindsv -- Alright, for now, we'll do #4289, and will discuss Delta API/WebSocket later (if needed).

Thanks.

**Comment by GaneshSPatil** [comment]
We haven't seen any performance issues with the newer APIs and mithril based SPAs.
Implementing WebSockets for SPA pages is not required (as of now).
Closing...
