### ISSUE TITLE
cctray - pipeline summary

### ISSUE THREAD

**Issue by andreoid** [gocd/gocd#43]
Currently you export cctray.xml which details every single stage and job of a pipeline.
http://mygoserver/go/cctray.xml

It would be great if there were variants on cctray so that it could just display the state of the pipeline rather than each individual job.

i.e.
pipeline 1, failed.
pipeline 2, passed.
pipeline 3, passed.

That would be very useful to plug into our build monitors (e.g. https://github.com/AdamNowotny/BuildReactor)  where we just see what pipelines are passed/failed, rather than drill down into each individual job/stage.

**Comment by duaneedwards** [comment]
I'd like to see this happen, can you please provide some guidance on whereabouts in the code this would make sense to belong?

**Comment by srinivasupadhya** [comment]
you have a look at PR https://github.com/gocd/gocd/pull/877 for reference

**Comment by matt-richardson** [comment]
Hi @andreoid, @duaneedwards 

You might be interested in https://github.com/matt-richardson/gocd-websocket-notifier/, which publishes stage status notifications over websockets - might be easier (better?) than polling.

**Comment by arvindsv** [comment]
Hi @duaneedwards: Yes, if possible, I'd definitely use @matt-richardson's plugin. It should be better than polling.

If you're looking to poll, I'd start looking at whether writing any new code can be avoided. For instance, can you use the dashboard JSON at https://your-server:8153/go/dashboard.json instead? It has most of the information you're looking for. I need to do more work on caching it properly. So, it is not yet a properly published API. But, it's a start.

If you're really looking to write code, I'd start looking at [this](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/CcTrayService.java#L41). That's where the cctray XML is created. You can use the ccTrayCache again, just like it is done in that method. Calling ```ccTrayCache.allEntriesInOrder()``` will give you information for every pipeline, stage and job. You can use it to aggregate at the level you want.

I'd definitely look at the first two options, as I said, before getting to that. To get into the core, we should start a conversation about what the format is, whether it is going to make sense for other users, etc. I hope that makes sense, that a feature will get into the codebase largely based on its applicability to a lot of users. :)

**Comment by duaneedwards** [comment]
Thanks guys, now that I'm aware there is a dashboard.json / web socket notifier, the cctray.xml route doesn't actually seem like the best option.

@arvindsv Correct me if I'm wrong, but it looks like the dashboard.json exposes the endpoints for triggering / scheduling a build ... do you just need to post to these endpoints to trigger these actions or is it a bit more involved than that?

**Comment by arvindsv** [comment]
@duaneedwards: It does expose those endpoints. Triggering them is not always just POSTing to them. For schedule pipeline, pause pipeline and unpause pipeline operations, the three API endpoints are provided, [this](http://www.go.cd/documentation/user/current/api/pipeline_api.html#scheduling-pipelines), [this](http://www.go.cd/documentation/user/current/api/pipeline_api.html#pause-a-pipeline) and [this](http://www.go.cd/documentation/user/current/api/pipeline_api.html#unpause-a-pipeline). So, using them is as described in the documentation (POST to them). For trigger_with_options operation, you need to call the schedule API, as earlier, with options specified in the documentation.

dashboard.json is an API in progress, as I said. I have to work on its caching a little more, sometime soon. So, be careful about using it too much. Try it and evaluate, please.

**Comment by arvindsv** [comment]
Closing this. OP found a different (better) way. :)
