### ISSUE TITLE
Filter message is not correctly shown on Safari because of overlapping element

### ISSUE THREAD

**Issue by wlsf82** [gocd/gocd#4301]
##### Issue Type
- Bug Report

##### Summary
When using the filter in the right top corner a message is displayed saying how many matches were found, but this message is not correctly visible because the PERSONALIZE element is on top of it.

##### Basic environment details
Go Server Version: 18.1.0 (5937-8a847b96ee8d38173f80178ed1285f0e53a970e0)
JVM version: 1.8.0_131
OS Information: Linux 3.13.0-123-generic
Browser: Safari 11.0.3

##### Steps to Reproduce
1. On Safari, access the GoCD dashboard
2. Use the right top corner filter to filter something

##### Expected Results
No element should be overlapping the displayed message

##### Actual Results
The PERSONALIZE element is not displayed in the correct place and then it overlaps the message saying how many matches were found.

###### Additional information:
The issue is not reproducible on Chrome and Firefox

**Comment by wlsf82** [comment]
![screen shot 2018-02-06 at 13 43 03](https://user-images.githubusercontent.com/2768415/35860632-0ac29e5a-0b45-11e8-8840-f81c8f0ca7d8.png)

**Comment by arvindsv** [comment]
<img width="528" alt="2018_02_06_08-07-29" src="https://user-images.githubusercontent.com/172235/35861208-d90a0388-0b14-11e8-8b51-9338c3198e51.png">

Are you sure you don't have any extensions or something messing it up? I took a quick look just now and it looks ok to me.

**Comment by arvindsv** [comment]
Ah, I was checking in 18.2. Sorry!

**Comment by arvindsv** [comment]
I see that it was fixed in https://github.com/gocd/gocd/pull/4251 based on an original issue reported at https://github.com/gocd/gocd/issues/4250. Should be fixed in 18.2. So, I'll close this as a duplicate. Thank you!
