### ISSUE TITLE
New dashboard: Bug around pipeline pause / unpause

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#4309]
##### Issue Type

- Bug Report

##### Summary

1. Pause a pipeline. Enter a message, say, "Test123".
2. Unpause it.
3. Pause it again.

You'll see "Test123" already available in the textbox.

Expected: It should be empty.

###### Basic environment details

* GoCD Version: 18.2.0 (6029-dab2c7c92fc28db35cbc7600b4366197cff99ce1)
* Browser vendor and version (if relevant): Firefox 58

**Comment by rajiesh** [comment]
Verified on 18.2.0 (6208-f0f03120fc42d2ae1f230dd89996a3dc086912c5)
