### ISSUE TITLE
Errors on executing commands - Please make sure [***] can be executed on this agent.

### ISSUE THREAD

**Issue by scazzy** [gocd/gocd#4313]
Suddenly today I see this error for most commands I'm trying to run.
Received same error for gulp and yarn. Things wore working perfect till yesterday. Is there any breaking change?

![image](https://user-images.githubusercontent.com/1681586/35964061-9d8a9dda-0cdc-11e8-829a-b4ef10ab2641.png)

While I was able to make things work using
command: `/var/go/.nvm/nvm-exec`
arguments: `yarn install, or gulp something..`

**Comment by ketan** [comment]
There is no breaking change on the GoCD end, chances are that the tools are no longer on the `PATH` of the agent process.

**Comment by scazzy** [comment]
@ketan it happened after updating goCD.

**Comment by ketan** [comment]
Can you execute the `env` command via gocd and inspect the value of `PATH` to see if the binary is on path?

I suspect that the agent was likely run with some different environment variables before the upgrade.

**Comment by varshavaradarajan** [comment]
Closing this as there has been no response.

**Comment by a14m** [comment]
What is the prefered method for installing `nvm` on agents... I'm still new and trying to get it working (need to run `nvm use <version>` on agents for different projects)

**Comment by arvindsv** [comment]
@a14m I'd say:

1. Create a bash script which works anywhere, which does the initialization needed by nvm. 
2. Check that into a repo and use it.

Something like this:

```
#!/usr/bin/env bash

source /your/path/to/nvm.sh

nvm "$@"
```

If you save this script as `mynvm.sh` or something and check that in, then you can use it as: `./mynvm.sh run node --version` (for instance).

Another option would be to use the script to do more (this way, you get to track changes easily and keep your CI/CD process independent of GoCD):

```
#!/usr/bin/env bash

source /your/path/to/nvm.sh

nvm use my-node-v10
nvm install ...
nvm exec ...
```

**Comment by arvindsv** [comment]
Just for the record: This is because `nvm` use shell functions etc. to work and it's not just a straightforward command. So, it depends on the shell. Since GoCD tasks run as independent processes, just doing an `nvm use` in one task won't affect the next.

So, in the first of the two approaches shown above, even if you create `mynvm.sh`, running `./mynvm.sh use abc` won't affect the next task. You're better off with option 2.
