### ISSUE TITLE
Option to clean up workspace at the end of a job

### ISSUE THREAD

**Issue by wilddeej** [gocd/gocd#4316]
##### Issue Type
- Feature proposal

##### Summary
An option is needed to clean up an agent's working copy at the end of a job (after artifact publishing is complete).  The main reason for this need is to help detect "bad pipeline behavior" at its source, so that it can be rectified (other benefits could also be postulated).  Consider the following scenario (given a build job that uses the option to clean up on start, and is configured to publish artifacts):

1. During the execution of the job, files are created that are not writable by the agent process (due to a bad "chown" or "chmod" operation, or perhaps created within a Docker container running as the root user).
2. The build completes successfully and publishes its artifacts.
3. The next build job that attempts to use that agent fails because it cannot clean up the working copy due to the errant files mentioned in 1 above.

If a post-clean operation were available that could be run between steps 2 and 3, the failure would occur there, rather than in the next attempt to build on that agent, and the proper pipeline could be identified as the "problem child" and the issue could then be speedily resolved.  As it is now, it can be very difficult to track down the actual culprit.
There are other reasons that a post-cleanup option could be useful, but the above is the use case that I am most keenly needing resolved.  There is no way to resolve this now because any cleanup done within the job tasks would also negatively affect the artifacts that are published as well (a full cleanup means no artifacts would be available to be published, obviously).

##### Environment
As described above

###### Basic environment details
N/A

###### Additional Environment Details
N/A

##### Steps to Reproduce
See Summary

##### Expected Results
Working space cleaned up at end of job execution

##### Actual Results
No facility for this function currently exists;  no results

##### Possible Fix
Usage of elastic agents would remove the issue, but this is not an option on all operating systems/releases;  a GoCD job functionality solution is needed

##### Log snippets
None

##### Code snippets/Screenshots
None

##### Any other info
None

**Comment by jwatson0** [comment]
Potential duplicate of #2070

**Comment by wilddeej** [comment]
Nope, not a duplicate.  #2070 provides the very useful feature for cleaning
up a workspace at the BEGINNING of a job, #4316 cleans up at the end (after
all other configured/defined steps have executed).  The underlying
functionality is likely very similar if not identical, but this one has
potential issues with respect to artifacts that need to be out of the way
before cleanup.

**Comment by csomakk** [comment]
agree, this would be nice

**Comment by Vye** [comment]
My build agents had excessively high disk usage. I searched for a post cleanup feature and discovered this closed request. :(

I wrote a [simple cron](https://github.com/Vye/sandbox/blob/master/notes/gocd/gocd-workspace-cleanup.cron) to keeps things tidy.
