### ISSUE TITLE
Pipeline schedule API - proposed changes in behavior

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#4319]
Based on some initial discussion between @arvindsv and me regarding https://github.com/gocd/gocd/issues/4273, we have the following proposal for the behavior of the schedule API. 
Please note: this is going to apply to the new schedule API alone. The existing one would continue to behave as-is. It would be deprecated and then eventually be phased out.

** Check existing behavior section (As of 18.1) for details about the existing implementation and some issues with the same.

### Trigger button in the UI:
[Continues to work as before]
* Do an MDU.
* Trigger with latest of all.

### Trigger with options in the UI:
Has to make it clear what it is doing (which revisions it is triggering with).

#### When nothing has been chosen: (No material revisions pegged)
* Continue using the previous run’s material revisions.
* Do NOT do an MDU.

#### When 2 out of 5 materials have been chosen:
* Use previous run’s material revisions for the other 3 materials.
* Use specified material revisions for those 2 of 5 materials.
* Do NOT do an MDU.

### Trigger API:
Existing behavior seems ok.

### Trigger with options API: 

Do an MDU based on a new flag (described below):

###### 2 materials:
* Git material “G”: Commits g1, g2, g3 seen by GoCD and in the DB. Commit g4, g5 not yet seen. Polling is off.
* Git material “H”: Commits h1, h2, h3 seen by GoCD and in the DB. Commit h4, h5 not yet seen. Polling is off.
###### API call: Params are:
* material[G]=g2
* material[H]=h2
* do_mdu=false
###### What it should do:
* Don’t do an MDU (flag is false).
* Peg revisions at g2 and h2. They’re in the DB. Run. Done.

###### 2 materials:
* Git material “G”: Commits g1, g2, g3 seen by GoCD and in the DB. Commit g4, g5 not yet seen. Polling is off.
* Git material “H”: Commits h1, h2, h3 seen by GoCD and in the DB. Commit h4, h5 not yet seen. Polling is off.

###### API call: Params are:
* material[G]=g4
* material[H]=h2
* do_mdu=false

###### What it should do:
* Don’t do an MDU.
* Fail. g4 is not known.

###### 2 materials:
* Git material “G”: Commits g1, g2, g3 seen by GoCD and in the DB. Commit g4, g5 not yet seen. Polling is off.
* Git material “H”: Commits h1, h2, h3 seen by GoCD and in the DB. Commit h4, h5 not yet seen. Polling is off.

###### API call: Params are:
* material[G]=g4
* material[H]=h2
* do_mdu=true

###### What it should do:
* Do an MDU. See g4 and g5.
* Then, run once with g4, h2.
* Run once more with g5, h2. [Document this]

###### 3 materials:
* Git material “G”: Commits g1, g2, g3 seen by GoCD and in the DB. Commit g4, g5 not yet seen. Polling is off.
* Git material “H”: Commits h1, h2, h3 seen by GoCD and in the DB. Commit h4, h5 not yet seen. Polling is off.
* Config-repo material X which has pipeline P1.

###### API call: To trigger with options for P1. Params are:
* materials[G]=g2
* materials[H]=h2
* do_mdu=false

###### What it should do:
* Since P1 is part of a config repo material, do an MDU of that material (X).
* X is not the same as G or H. So, no effect on them.
* Don’t do MDU of G and H.
* Peg revisions at g2 and h2. They’re in the DB. Run. Done. [Same as Case 1]

###### 3 materials
* Git material “G”: Commits g1, g2, g3 seen by GoCD and in the DB. Commit g4, g5 not yet seen. Polling is off.
* Git material “H”: Commits h1, h2, h3 seen by GoCD and in the DB. Commit h4, h5 not yet seen. Polling is off.
* Config-repo material G which has pipeline P1.

###### API call: To trigger with options for P1. Params are:
* materials[G]=g2
* materials[H]=h2
* do_mdu=false

###### What it should do:
* Since P1 is part of a config repo material, do an MDU of that material (G).
* Don’t do an MDU of H.
* Peg revisions at g2 and h2. They’re in the DB. Run.
* Now, since MDU of G happened, g4 and g5 are seen. P1 triggers again with g5 and h2.

### Out of scope:
* “Run with latest for all, except for these two materials”
* Manual Trigger with Fan-in resolution(https://github.com/gocd/gocd/issues/1924)

### Trigger button in the UI:
* Does a full MDU.
* Then, triggers with the latest known of all materials.

#### When nothing is selected (no materials are changed):
* Does an MDU.
* Triggers with previous run’s revisions.
* If the MDU ends up finding new revisions, it triggers again with properly fan-in resolved revisions.

#### When something is selected: Say 2 out of 5 materials have been selected by the user to have a revision different from that of the previous run:
* Does an MDU.
* Triggers with specified revisions for the 2 selected. Uses previous run’s revisions for the rest.
* If the MDU ends up finding new revisions, it triggers again with properly fan-in resolved revisions.

### Trigger API:
* Always does an MDU.
* Picks the latest once the MDU has finished.

### Trigger with options API: 
This is just the trigger API with some material revision data passed in.
* It’ll trigger with the material revisions provided and the latest for all materials without a specific revision provided.
* It does an MDU.
* If the MDU ends up finding new revisions, it triggers again with properly fan-in resolved revisions.

**Comment by jyotisingh** [comment]
@tomzo - As you know, manual trigger forces MDU of all associated materials. We were thinking about providing an *option* to not perform an MDU, if that's what the users want. 
While looking at the code, I came across [this](https://github.com/gocd/gocd/blob/1a0ecc08c3374f9fa387492f352be7aad3d69dce/server/src/main/java/com/thoughtworks/go/server/scheduling/BuildCauseProducerService.java#L279) check in the schedule flow for remote materials. 

As per the commit message for that change
>    #1133 handle manual pipeline trigger when one of materials has config
    When user triggers a pipeline manually then materials are updated. There
    is a case when one of those materials has configuration of that pipeline.
    These changes ensure that we (try to) reload configuration before
    pipeline gets scheduled.

Updating config-repo before the rest of the materials make sense, but not sure if I understand the reason for not updating the definition when pipeline is defined remotely but configured with a different material. For some reason, I thought we always updated the pipeline definition for remote pipelines, but that doesn't seem to be the case. Could you help me understand that better?

**Comment by tomzo** [comment]
> Updating config-repo before the rest of the materials make sense, but not sure if I understand the reason for not updating the definition when pipeline is defined remotely but configured with a different material

I totally agree. I keep looking at that block in `if (isConfigurationInMaterials())` and it seems that it should be more general `isRemoteConfiguration`.

I have also read your proposition above. It looks good, but I hope you realize that there are few corner cases for `4.` and `5.` when after updating material with pipeline config:
 a) the `do_mdu` flag has been changed
 b) materials of the pipeline have changed, a new material was added.
 c) pipeline has been removed/renamed. (That one, I covered somewhere already)

It seems it would be sensible to re-evaluate if MDU should be done for pipeline materials right after pipeline config material was updated.

**Comment by jyotisingh** [comment]
> I totally agree. I keep looking at that block in if (isConfigurationInMaterials()) and it seems that it should be more general isRemoteConfiguration.

Thanks for confirming @tomzo . I will update the implementation.

About the corner cases:
> a) the do_mdu flag has been changed

The flag is set by the user while making a schedule API call, so this doesn't really change for a given API invocation. 

> b) materials of the pipeline have changed, a new material was added.

Actually, I was thinking about case `b` in the sense that it can happen even today, and couldn't find a place where it's handled.  

> c) pipeline has been removed/renamed. (That one, I covered somewhere already)

This is handled in [BuildCauseProducerService#newProduceBuildCause](https://github.com/gocd/gocd/blob/0ab5c241e920fb32214b6c8ffcda3a04298fcf67/server/src/main/java/com/thoughtworks/go/server/scheduling/BuildCauseProducerService.java#L152), the failure would be updated in the `Error & Warnings` popup, so we are good there.

**Comment by rajiesh** [comment]
Given that Schedule API support an option as below,

**Not-seen materials + do MDU flag+Environment variables**

2 materials:

- Git material “G”: Commits g1, g2, g3 seen by GoCD and in the DB. Commit g4, g5 not yet seen. Polling is off.
- Git material “H”: Commits h1, h2, h3 seen by GoCD and in the DB. Commit h4, h5 not yet seen. Polling is off.

API call: Params are:

- environment_variable[Foo]=changed
- do_mdu=true

What server does:

- Do an MDU for G. See g4 and g5.
- Do an MDU for H. See h4 and h5.
- Run oncewith latest commits g5, h5 with new value for environment variable 'Foo' as 'changed'

However this option is not available from the UI, If user do not specifically select commits for the materials, always last triggered with commit is used. Good to provide an option(may be a simple checkbox on new dashboard trigger with options modal saying `Trigger with latest commits for all materials` which by default is unchecked).. Checking the option `Trigger with latest commits for all materials` will trigger with latest changes for all materials, otherwise current behavior will continue(trigger with commits last run with). Will help users who requested this option https://github.com/gocd/gocd/issues/3449

**Comment by rajiesh** [comment]
Verified on 18.2.0 (6211-48d5a54cd6525e54b4692cb757a6ad9896e46392). Works as per the description on the issue. For support on UI to run with latest and not last run with will use #3449 to track
