### ISSUE TITLE
GO should notify pieline breakers regardless of their notification subscriptions

### ISSUE THREAD

**Issue by chumanocm** [gocd/gocd#432]
I have added some logic to the UserNotificationService to allow for this to happen.  it compares the breaker name or email address to the user list, and adds any matches to the list of users to receive notifications.  I plan to issue two (or more) pull requests, an initial one for the supporting code, which should be non-disruptive, and a second one for the actual change in notification behavior.  

I have not yet looked at adding a configuration mechanism to enable/disable this feature.  I'm not sure if I should wait until the that step is completed before issuing my initial pull requests.

**Comment by srinivasupadhya** [comment]
I have added [notification end-point](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html). Should be available in 15.1.0. Hopefully you should be able to write a plugin for this.

**Comment by srinivasupadhya** [comment]
should be easy enough to implement with small modifications to [email-notifier](https://github.com/srinivasupadhya/email-notifier).
