### ISSUE TITLE
Git material poll does an anonymous connection attempt when it should use a username and password attempt

### ISSUE THREAD

**Issue by karelbemelmans** [gocd/gocd#4331]
##### Issue Type

- Bug Report

##### Summary

We have pipelines configured to poll changes in Git repo. We have configured the repo url's as follows:

https://username@gitserver/repo.git

The Go agents have a .netrc file that contains an entry for server "gitserver" for user "username" with a specific password.

The expected behaviour would be that Go uses the username login right away when making polling requests to the git server. What we see however is that it first tries an anonymous request (which always fails with a 401) and then uses the username login correctly with the credentials from the .netrc file.

So the problem is that the .netrc system works like it should, but it should not use the anonymous connection attempt first, since we provide a specific username in the git material string.

##### Environment

We tested this behaviour on a 18.1.0

**Comment by ketan** [comment]
This is actual expected behavior with git, git will not send credentials unless asked for.

```
$ GIT_CURL_VERBOSE=true git fetch
...
...
< HTTP/1.1 401 Authorization Required
< Server: GitHub Babel 2.0
< Content-Type: text/plain
< Content-Length: 21
< WWW-Authenticate: Basic realm="GitHub"
...
...
* Server auth using Basic with user 'ketan'
> GET /gocd-private/enterprise/info/refs?service=git-upload-pack HTTP/1.1
Host: github.com
Authorization: Basic [SNIPPED]
User-Agent: git/2.16.0
Accept: */*
Accept-Encoding: gzip
Accept-Language: en-US, *;q=0.9
Pragma: no-cache
```
