### ISSUE TITLE
Personalize API improvement 

### ISSUE THREAD

**Issue by yankurk** [gocd/gocd#4339]
##### Issue Type

- Feature enhancement

##### Summary

The personalize API returns selected pipeline names based on blacklist value. The list should contain names of pipelines that the user had previously checked, regardless of blacklist value.

##### Steps to Reproduce

1. Create three pipelines, say `one`, `two` and `three` under a pipeline group say `first`.
2. Under personalize dropdown select checkbox for `Show newly created pipelines`
3. Also check pipelines `one` and `two`
4. Click on apply.
4. Make an api call as such:
```
curl 'http://localhost:8153/go/api/internal/pipeline_selection' -H 'Accept: application/vnd.go.cd.v1+json' -u 'username:password'
```

##### Expected Results

The api response should be:
```
{
  "selections": [
    "one",
    "two",
  ],
  "blacklist": true,
  "pipelines": {
    "first": [
      "one",
      "two",
      "three",
    ]
  }
}
```

##### Actual Results

The api response is:
```
{
  "selections": [
    "three"
  ],
  "blacklist": true,
  "pipelines": {
    "first": [
      "one",
      "two",
      "three",
    ]
  }
}
```

**Comment by GaneshSPatil** [comment]
This issue has been fixed via https://github.com/gocd/gocd/pull/4354 as part GoCD release `v18.2.0`
