### ISSUE TITLE
Migrating job details page from velocity to rails-erb

### ISSUE THREAD

**Issue by sachinsudheendra** [gocd/gocd#434]
This issue is specific to moving the job-details page, which currently is one among the few pages using velocity templates into rails-erb. Also, redesigning of the page might occur in this process.

I've moved the console tab and few details specific to a job - and will be using a combination of rails-erb and angularjs to achieve this. The changes are being done on my [fork](https://github.com/sachinsudheendra/gocd/tree/jobs-rails4) (branch: jobs-rails4) and will be submitted to #gocd when done.

With my limited CSS skills, I've come up with the below first-cut of the page. Any feedback is welcome.

![proposed](https://cloud.githubusercontent.com/assets/52740/3859892/0b27d250-1f1e-11e4-8b87-6974eb923c0c.png)

For comparison, here's the current page

![current](https://cloud.githubusercontent.com/assets/52740/3859895/34050bf2-1f1e-11e4-8e98-3d1e9284bc3c.png)

/cc #427

**Comment by srinivasupadhya** [comment]
[discussion thread](https://groups.google.com/d/topic/go-cd/RE7V5CavdNc/discussion)

**Comment by arvindsv** [comment]
Cleanup: Stale. Closing.
