### ISSUE TITLE
[New Dashboard] Pipeline Group Links

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4347]
##### Issue Type

- Feature proposal

##### Summary
Change the pipeline groups links:
- [x] Pipeline Group Name should link to pipeline group index page (`go/admin/pipelines`)
- [x] Pipeline Group Icon should link to pipeline group settings page (`go/admin/pipeline_group/<PIPELINE_GROUP>/edit`)

##### Old Pipeline Group Name View:
![screen shot 2018-02-14 at 1 29 13 pm](https://user-images.githubusercontent.com/15275847/36193248-2e8657c2-118b-11e8-8fe5-8eeb2607a6ef.png)

##### Proposed Pipeline Group Name View:
![screen shot 2018-02-14 at 1 31 43 pm](https://user-images.githubusercontent.com/15275847/36193322-77dd9a84-118b-11e8-8ccd-1ac11af21732.png)

**Comment by rajiesh** [comment]
Verified on 18.2.0 (6208-f0f03120fc42d2ae1f230dd89996a3dc086912c5)
