### ISSUE TITLE
New Dashboard Issues

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4348]
#### Issues with new Dashboard:

- [x] Performance issues with stage status animation. (`Building`, `Failing`).
- [x] Changes popup positioning issue in case of multiple pipeline instances.
- [x] Show server Scheduled at time on hover of local scheduled_at time.
- [x] Show action disabled mouse on hover of disabled gear icon.
- [x] Implement Etag for Dashboard API.
- [x] Disable Trigger buttons when the first stage is building.
- [x] Disable Trigger buttons when the pipeline is locked.
- [x] Disable Trigger buttons when the pipeline is paused.

**Comment by yankurk** [comment]
Some other issues:

- [ ] Remove pipeline operations related buttons (trigger, trigger-with-options and pause/unpause) for users who don't have operate permissions (#4376)
- [ ] If no permissions is setup for a pipeline group, by default, all users should have operate permissions (#4374)
