### ISSUE TITLE
[New Dashboard] Edit options shown for Config repo pipelines

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#4351]
##### Issue Type

- Bug Report

##### Summary

Edit pipeline gear is shown for Config repo pipelines

**New Dashboard**

<img width="578" alt="screen shot 2018-02-14 at 3 43 51 pm" src="https://user-images.githubusercontent.com/6533924/36198922-faa1c41a-119d-11e8-8780-e6a2a269ad36.png">

**Old Dashboard**

<img width="596" alt="screen shot 2018-02-14 at 3 44 07 pm" src="https://user-images.githubusercontent.com/6533924/36198928-fee0e0c4-119d-11e8-84ff-050d49dda67c.png">

**Comment by yankurk** [comment]
Related to #4348

**Comment by rajiesh** [comment]
Verified on 18.2.0 (6211-48d5a54cd6525e54b4692cb757a6ad9896e46392), Edit option is disabled for config repo pipelines
