### ISSUE TITLE
Dashboard animations eating too much CPU

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4353]
##### Issue Type

- Performance

##### Summary

On the new dashboard, enabling the progress bar animations as a severe impact on the CPU usage.

On my 8 core machine, the baseline idle CPU usage is around 7%, when I enable CSS animations in the dashboard, the usage goes up to an average of 20% — much higher than the average CPU usage of the IDE :-/ This is especially hurtful when running on batteries, as the battery drops by about 1% per minute with the dashboard idling.

**Comment by naveenbhaskar** [comment]
Will try making svg/gif animations for this.

**Comment by ketan** [comment]
You want to throw a few thousand of these on a single page and see if your CPU usage spikes and by how much.

**Comment by arvindsv** [comment]
You don't need a thousand. All you need is about 6. I see one of my cores go up to 50% for that. [Submitted PR #4418](https://github.com/gocd/gocd/pull/4418) to remove it.

**Comment by rajiesh** [comment]
Verfiied on 18.2.0 (6228-fbb379a451871b29aa47aef907a78dc64379233f)
