### ISSUE TITLE
Package Repository Material optional and editable configuration aspects

### ISSUE THREAD

**Issue by agerro** [gocd/gocd#4355]
##### Issue Type
- Feature proposal
- Feature enhancement

##### Summary
Allaow for having optional and editable parameters in the package repository matierla configuration, allowing for changing the parameter after creation.
One use case it to have a limitiation on which is the highest allowed (for example) highest verison of a tag on a docker image.
Our use case is that we have a 1:1 mapping so that one pipeline only uses one Package Repository Material, so changes won't effect other pipelines since not more than one pipeline uses the same package.

Original question raised towards Go.CD:
*we are writing a plugin for our Go.CD server to use for polling images from AWS ECR. 
We would like to somehow parameterize the material so that we have an optional part of the package configuration. Creating the field is no problem (configured to be NOT "part-of-identity" and optional). Is there a way to make it "editable" as well? So that it is possible change it in "Edit Package - Material" view after it's created?*

##### Environment
1 Go.CD server on one VM
3 Go.CD agent running on their own  separate VM's
One AWS ECR containing repositories for each application
One material per repository
Development pipelines (first in the flow for an application) using our own plugin as a Package Repository Plugin.
The following pipelines in the flow is using the pipeline plugin as material.

###### Basic environment details
* Go Version: `17.11`
* JAVA Version: `1.8.0_131`
* OS: `Linux 3.10.0-693.11.6.el7.x86_64`

##### Steps to Reproduce
1. Assumes preconfigured Package repository 
2. Adding the Material configuration on the pipeline using the Package repository plugin
3. Attempt to change the (as of right now) not existing optional/editable field
4. See that you are not able to change any values of a Package repository configuration after creation.

##### Expected Results
Being able to change an optional parameter to package material configuration

##### Actual Results
Not being able to change an optional parameter to package material configuration

**Comment by maheshp** [comment]
Pluggable SCM or Package materials are created at a global level and referred to in pipelines. 

Currently the Pluggable SCM materials can be edited in context of a pipeline. Upon editing the material there is a warning which mentions that the material being updated is a global copy with an option to view the pipelines using this material.

![screen shot 2018-02-20 at 4 25 20 pm](https://user-images.githubusercontent.com/1061051/36420639-b45155c6-165b-11e8-8720-1047e3ae32d1.png)


The Package materials do not give an option to edit the global copy of the material. Can't think of a  reason why the  behaviour of editing a package material should not be same as Pluggable SCM material.

**Comment by ankitsri11** [comment]
Currently, package material configuration is stored at the global level and its configuration is referenced by all the associated pipelines.

For instance, pipeline configuration only has the package reference id which is referred through **ref** attribute.

```
 <pipeline name=“webproject”>
        <materials>
            <package ref=“1234-12242-232312" />
        </materials>
```

If there is any change to package configuration, it reflects in other pipelines.
