### ISSUE TITLE
ability to turn off fan-in for a pipeline instead of system wide turn off

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#437]
This would come in handy where pipelines hit a corner case related to blacklist / change in material config in upstream etc.

refer https://developer.gocd.org/current/5/5.2.html#5-2-4-a-name-corner-cases-a-corner-cases corner cases section for details.

**Comment by srinivasupadhya** [comment]
It should be straight forward to implement it.

Add config read write ([Reference](https://github.com/srinivasupadhya/gocd/commit/ae33c4b792417f676cef78d020160ab1d04de316)):

- Introduce a config migration to introduce attribute at pipeline tag for config XML.
- Ability to read XML into Java class [here](https://github.com/gocd/gocd/blob/master/config/config-api/src/com/thoughtworks/go/config/PipelineConfig.java). 
- Add test here.

Skip resolution:

- [Here](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/AutoBuild.java#L70) check if fan-in is turned off for the pipeline in question.
- Add test [here](https://github.com/gocd/gocd/blob/master/server/test/integration/com/thoughtworks/go/server/service/FaninDependencyResolutionTest.java).

Add UI:

- Add checkbox [here](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/views/admin/pipelines/general.html.erb).
- Add test [here](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/spec/views/admin/pipelines/general_html_spec.rb).

**Comment by maximus8891** [comment]
Fan-in does not apply when material urls are different.
Those who are struggling with this issue can present the same material with different urls.

For example,
`https://bitbucket.org/repoA.git`
and
`https://bitbucket.org//repoA.git`

Notice the double slash in the second url.

**Comment by Kristina001** [comment]
workaround proposed by @maximus8891 helped, thanks !

**Comment by arvindsv** [comment]
Stale. Closing.
