### ISSUE TITLE
Is there a way to make particular folders `allowed` for DirectoryCleaner? 

### ISSUE THREAD

**Issue by yaman** [gocd/gocd#438]
I am trying to build a project written in golang. To build golang projects, you need to define `GOPATH` and checkout code you want to build into `$GOPATH/src/gitlab.fancycompany.com/yourgroup/yourproject` in order to make your golang imports work.

Thus I set `$GOPATH` to my agents build root, like `GOPATH=/var/go-agent/myapi` . And define checkout folder of git material relative to agents build root as `src/gitlab.fancycompany.com/yourgroup/yourproject` which checks out to `$GOPATH/src/gitlab.fancycompany.com/yourgroup/yourproject` . And `cleanup working directory` option is unchecked.

I don't want `go get` to get dependencies everytime I run it, instead, I want `go get` to leverage existing(already downloaded) dependencies under `$GOPATH/src/github...` and not to download again  and again to shorten build process, otherwise getting some dependencies takes 10 minutes...

But my agent removes files it seems irrelevant to build, like, it deletes `src/github.com` but it keeps `src/gitlab.fancycompany.com`. I checked the DirectoryCleaner code several times with tests but could not understand the logic behind. What is the reason it is allowing or not allowing is a mystery to me.

Is there a way to tell agent not to delete particular files under build root folder?

**Comment by webmaster128** [comment]
Did you solve the problem or did you give up expecting a solution? I think the issue is very much valid. I also have different projects in my GO CD setup that randomly run and don't run working directory cleanups. In some cases the Cleaning step is entirely skipped and sometimes build files I want to keep are deleted.

**Comment by abdulkadiryaman** [comment]
no couldnt solve it. changed the way we implemented the pipeline at the
end....
