### ISSUE TITLE
Enhance 'Config XML' editor

### ISSUE THREAD

**Issue by ermauliks** [gocd/gocd#439]
Our existing Config editor is just a plain text-area. We still miss following features to make it really cool.
- Code folding,
- Coloring tags, attributes, values, etc,
- Auto complete quotes.

I like this [lib - ace(c9)](http://ace.c9.io), did a small spike to see how it feels here at 'Admin/Config XML' tab. Check this [video](https://www.dropbox.com/s/sy4wvunr27igp92/ConfigXml.mp4).

If we'd like to take this forward, these are few most important things needed to be done,
- Have a single page for read/write config - a button will switch.
- Have messages for failure/success. 
- Editor during conflict scenario. 
- Add/remove relevant tests.

Thoughts on this?

**Comment by srinivasupadhya** [comment]
we could do this by allowing users to edit `<pipeline />` part of config. we can then enhance the editor for it + add pipeline edit API

**Comment by arvindsv** [comment]
Cleanup: Stale. Closing.
