### ISSUE TITLE
Allow custom tab names to contain anything

### ISSUE THREAD

**Issue by rkrisztian** [gocd/gocd#4397]
##### Issue Type

- Feature enhancement

##### Summary

Names of custom tabs for jobs cannot contain spaces and their length cannot exceed 15 chars. I find this a too painful limitation, because we would have tab names like "Acceptance Test Report", which is:

* Proper English as in the names of regular tabs,
* Does not make us have to resort to tab names like "Integration" which is way too vague from a usability point of view.

###### Basic environment details

* Go Version: 17.12.0 (5626-cb7df2ffe421e43f2a682a7a323cb3a3e30734cc)
* JAVA Version: 1.8.0_111
* OS: Linux 3.10.0-514.6.1.el7.x86_64

##### Steps to Reproduce

Add a tab configuration to a job that takes an HTML page as an artifact.

##### Code snippets/Screenshots

```
Tab name should not exceed 15 characters
```

**Comment by kritika-singh3** [comment]
The tab names length limit has been increased to 64 chars and the format was updated to include letters, numbers, spaces, and punctuation marks in #4922 in GoCD version 18.8.0.

**Comment by rkrisztian** [comment]
Can someone close this ticket as resolved? The PR has already been merged.

**Comment by GaneshSPatil** [comment]
Thanks @rkrisztian for pointing this out.
Removing the `stale` label and closing it.
