### ISSUE TITLE
Possible corner case with new dashboard

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#4398]
##### Issue Type

- Bug Report

##### Summary

This is unverified, but I just thought about it and felt it is good to capture it.

1. Have a GoCD server with a few pipelines.
2. Run a pipeline (or do something) to decrease the usable size on disk (in either the DB volume or artifacts volume).

I expect that the old dashboard will recognize this and make all pipelines un-trigger-able. I don't think the new dashboard will. Admittedly, this is a corner case. Also, upon a trigger, it will be rejected. However, there will be a difference in the two dashboards.

We need to talk about it and decide what to do, if it really does happen.

In code, we need to [consider all of these](https://github.com/gocd/gocd/blob/b85614cc0c132563e24c27a7febfc88e0ab9bb1c/server/src/main/java/com/thoughtworks/go/server/service/SchedulingCheckerService.java#L179-L193) (AboutToBeTriggeredChecker, ArtifactsDiskSpaceFullChecker and DatabaseDiskSpaceFullChecker).

/cc @rajiesh

**Comment by varshavaradarajan** [comment]
This is handled in the BuildCauseProducerService - https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/scheduling/BuildCauseProducerService.java#L152

**Comment by varshavaradarajan** [comment]
Ah, you mean disable the trigger buttons.

**Comment by arvindsv** [comment]
Yes. As [this](https://github.com/gocd/gocd/blob/b85614cc0c132563e24c27a7febfc88e0ab9bb1c/server/src/main/java/com/thoughtworks/go/server/service/PipelineHistoryService.java#L552) would have done in the old dashboard.

**Comment by arvindsv** [comment]
I'm ok if we say that we won't disable it. There are ways of disabling it without causing the crippling performance of running `DiskSpaceChecker` for *every* pipeline, for every dashboard request. We can talk about those if we want to.

**Comment by varshavaradarajan** [comment]
Yes, I think @ketan and I had spoken about not running the disk checkers for every pipeline that gets triggered. If we can get a list of pipelines that are meant to be scheduled and run the disk space checker, it should be fine, I think? Because all we are checking is that the space available is not below the configured threshold. Not what happens when one of those triggered pipelines uploads lots of artifacts.

**Comment by arvindsv** [comment]
I would just run the disk space checkers outside of this whole process, every 10 seconds or every minute, and then send that as an event to the `GoDashboardActivityListener`. The disk space checkers are not really tied to any pipeline. The `AboutToBeTriggeredChecker` can be properly handled too, when the pipeline is added to the queue. Don't know if it is. That one might not matter much.

**Comment by arvindsv** [comment]
By the way, the disk space checker gets run for *every pipeline* in every dashboard call. Not only when triggered.

**Comment by ketan** [comment]
Discussed this with @arvindsv when we paired on #4411 — the disk space checks have been effectively cached [`OutOfDiskSpaceChecker`](https://github.com/gocd/gocd/pull/4411/files#diff-0b09d7dc18d3f66fa45ede433f6ffce9R25) internally uses [`GoDiskSpaceMonitor`](https://github.com/gocd/gocd/pull/4411/files#diff-3ce96d197818302b671726519edd68eaR104) which caches results for `disk.space.cache.refresher.interval` period (defaults to 5s).

We will be additionally handling disk space check when the trigger API is called to prevent a trigger from happening if the server is out of disk space.

**Comment by arvindsv** [comment]
Yes. I'm fine closing this, since the trigger API already takes care of it.
