### ISSUE TITLE
Support agent side plugin for BuildSession workfolw.

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#4401]
##### Issue Type
- Feature enhancement

##### Summary

Agent side plugins(Task, SCM...) are not supported when is agent set to use build session.

This should also take care of providing access to console log processor or equivalent for agent side plugins so that the plugins can choose to write to the console.log.

**Comment by GaneshSPatil** [comment]
Build session has been removed as part of [this](https://github.com/gocd/gocd/commit/d45efb4d257b72bd0b801824404e785fc873e4de) commit.
This issue is no longer relevant.
Closing...
