### ISSUE TITLE
Config repository Status API/Page

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4402]
##### Issue Type
- Feature proposal

##### Summary
Along with an SPA for managing config repository, introduce an API/SPA for config repo status.

#### A config repository status page:
- [ ]  should show the current state of the config repository. (SUCCESS/FAILED)
- [ ] should show information about the last known revision. (GOOD/BAD/IN-PROGRESS)
- [ ] should show the last good revision (REVISION-ID, ENTITY-LIST)
- [ ] should show errors (if any) (CHECKOUT-ERROR/CONFIG-VALIDATION-ERROR)

**Comment by GaneshSPatil** [comment]
@arvindsv  @marques-work @ibnc @kierarad -- Something related to [config repo](https://github.com/gocd/gocd/issues/5175) work?
Can we close this issue, marking duplicate?

**Comment by arvindsv** [comment]
Yes. Thank you! Closing.
