### ISSUE TITLE
Allow users to configure polling interval and timeout value of SPAs

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4404]
##### Issue Type

- Bug Report
- Feature proposal

##### Summary

Currently, for all the new SPA pages, the `API polling interval` and the `API timeout` is set to fixed values `10` secs and `5` secs respectively.

On a heavily loaded server,
- the API could take more time to respond which may result in canceled API calls due to shorter timeout value.
- to reduce the load on the server, the page can be refreshed less frequently by increasing polling interval.

###### Basic environment details

* Go Version: `18.1.0`

###### Additional Environment Details

Agents Page Screenshot when server fails to respond within 5 secs
![screen shot 2018-02-22 at 12 38 30 pm](https://user-images.githubusercontent.com/15275847/36524791-5c1cf694-17cd-11e8-9539-4bf1d9ff904e.png)

##### Possible Fix
Allow users to configure polling interval and timeout values of SPAs using system environments

**Comment by rajiesh** [comment]
Verified on 18.2.0 (6211-48d5a54cd6525e54b4692cb757a6ad9896e46392)
