### ISSUE TITLE
Github integration won't deliver wbhooks: last delivery was not successful invalid go server url

### ISSUE THREAD

**Issue by BurkovBA** [gocd/gocd#4431]
##### Issue Type
Bug Report

##### Summary

I'm trying to setup a Github integration with GoCD to notify GoCD server of commits/PRs on Github and re-build my project on every Github hook delivery. Unfortunately, hooks fail to deliver messages to my server with the error message

`last delivery was not successful invalid go server url`.

Here's my Github integration configuration:

![screen shot 2018-02-26 at 10 06 50](https://user-images.githubusercontent.com/7602655/36664522-df58227e-1adc-11e8-80bd-9d723699f3c5.png)

##### Environment

* Go Version: 18.1.0
* JAVA Version: 1.8.0_151
* OS: Linux 4.9.0-5-amd64 (Debian 9.3)
* Browser vendor and version (if relevant): Chrome/Chromium

My GoCD server is listening on http://borisburkov.net:8153, go-agent is successfully connecting to it. I didn't configure any firewall on the system - it's just an out-of-the-box Debian 9.3 without any tweaks, so I suppose there should be no problems with hooks delivery from the OS side. 

`siteUrl` in GoCD server is also configured for http://borisburkov.net:8153. My github repository (https://github.com/BurkovBA/BurkovBA.github.io.git) is configured as a material for my GoCD pipeline. Do I need any additional configuration on GoCD side?

**Comment by arvindsv** [comment]
@BurkovBA Where are those install notes / instructions from?

GoCD's official GitHub webhook documentation is [here](https://api.gocd.org/current/#hosting-your-repository-on-github-or-github-enterprise). It can be improved and linked to from docs.gocd.org, for sure. But, I'm not sure where those install notes are coming from.

Since the documentation I linked to is different, I'm going to close this issue for now. I'm happy to reopen it if it's a real issue. Thank you!

**Comment by ketan** [comment]
GitHub in the early days allowed customizing webhooks which are available
under the project settings. Apparently someone had built the webhooks
integration for GoCD here.

https://github.com/github/github-services/blob/master/lib/services/gocd.rb

I think it may make sense to fix it to use the webhooks secret, or remove
it altogether.

**Comment by BurkovBA** [comment]
@arvindsv Thank you for the link, you provided.

@ketan Yes, I think, it makes sense to fix that integration. Does this hook have anything to do with [Stephen Murby's work](http://engineering.autotrader.co.uk/2017/08/29/adding-github-organisation-webhook-support-to-gocd.html)?

**Comment by BurkovBA** [comment]
Update on my current progress: 

1.  I was able to successfully deliver webhooks to my GoCD server as described in [your documentation](https://api.gocd.org/current/#hosting-your-repository-on-github-or-github-enterprise), thank you @arvindsv.

2. I forked this legacy [github-services](https://github.com/github/github-services/blob/master/lib/services/gocd.rb) project as suggested by @ketan. I think I'm going to be able to fix it to replicate webhooks behaviour. I'll also need to write a test for it afterwards, which is a bit harder for me, as I'm not very verse in Ruby. When I'm done, I'll send a PR to that repo and paste a link to it here, so that you, guys, could check it.

Thank you for your help!

**Comment by BurkovBA** [comment]
@arvindsv, @ketan 

Guys, please, take a look at my Pull Request to github GoCD service integration: https://github.com/github/github-services/pull/1238.

I introduced the necessary changes to github-services integration, but I'm not sure, how to run test suite for these changes. Can you help me with those?
