### ISSUE TITLE
Errors and Warnings Modal - Close button misaligned

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4438]
##### Issue Type

- Bug Report

###### Basic environment details

* Go Version: `18.2.0-6174`
* Git SHA: `4e872cc57bc5ee2504bd652de75794438d04bbde`

##### Any other info

<img width="1200" alt="screen shot 2018-02-27 at 11 55 56 am" src="https://user-images.githubusercontent.com/4715748/36713911-cc7a860e-1bb5-11e8-8a8d-43b2436262f3.png">

**Comment by ketan** [comment]
Is this on the new or old pages?

**Comment by varshavaradarajan** [comment]
Old pages. Saw this on the `/go/pipelines` page. Just checked the agents page and that's fine.

**Comment by varshavaradarajan** [comment]
Seems fixed in `18.2.0-6175`
