### ISSUE TITLE
[UI Bug] Autofill entry doesn't go away on page scroll up/down 

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#4445]
##### Issue Type

- Bug Report

##### Summary

Autofill entry doesn't go away on page scroll up/down.

![ui_bug](https://user-images.githubusercontent.com/6838313/36762867-77d44bba-1bda-11e8-8d4b-53de7d2d6a33.gif)

###### Basic environment details

* Go Version:  18.2.0 (6175-1058e75b18e8a645dd71702851994a010789f450
* OS: All
* Browser vendor and version (if relevant): ALL

**Comment by neoprez** [comment]
Assign this issue to me. It is for Hacktoberfest
