### ISSUE TITLE
[New Dashboard] Trigger with options do not trigger with specified revisions

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#4449]
##### Issue Type

- Bug Report

##### Summary

Trigger with options do not trigger with specified revisions. Even if user selects specific revisions(any known revisions) on the trigger with options modal and triggers pipeline still pipeline runs with latest known revision

###### Basic environment details

* Go Version: `18.2.0 (6175-1058e75b18e8a645dd71702851994a010789f450)`

##### Steps to Reproduce

1. Create a pipeline with any material
2. Create some revisions to the materials and wait for the pipeline runs to complete for all of them
3. Open trigger with options and select a known revision(not the latest)
4. Trigger the pipeline

##### Expected Results

The pipeline runs with latest revision of the materials and not the ones which slected

##### Actual Results

Pipeline should run with selected revisions

**Comment by rajiesh** [comment]
Verified on Schedule API and it works as expected, trigger is with the specified revisions, however on UI it doesn't work

**Comment by GaneshSPatil** [comment]
@rajiesh -- the issue occurs only when the material is searched with exact revision without selecting one of the results from the material search.

### Scenario 1 (Works as expected):
1. Open Trigger with options modal.
2. Search for a revision.
3. Select the revision from the displayed searched results by clicking on them.
4. Trigger a Pipeline.

Result: Triggers the pipeline with the selected material revision.

### Scenario 2 (Bug):
1. Open Trigger with options modal.
2. Paste exact revision in the material search input.
4. Trigger a Pipeline.

Result: Does not trigger the pipeline with the selected material revision. Runs with the latest revision of the material.

**Comment by rajiesh** [comment]
Just for record: Expected behavior - If user specifies the revision and its in the list of known revisions run with that, and if the specified revision is invalid then do not schedule(but currently also we do not show any message to suggest that the revision selected is wrong, so keep it like that for now)

**Comment by rajiesh** [comment]
Issue is partially fixed,

**Issue fixed** : Revision provided by the user and not selected from the list of suggestion was not getting picked up while scheduling(the new revision is always picked up). This issue is fixed

**Issue not fixed** : If user specify an invalid revision number the pipeline is still scheduled. Expected that its not scheduled(even current dashboard behavior is the same). It would be nice to have some message too with information why schedule failed(current dashboard don't have that message). Will raise separate issue for that

Closing this issue
