### ISSUE TITLE
[New dashboard] Trigger with options - horizontal scroll in materials popup

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#4452]
##### Issue Type

- Bug Report

##### Summary

![](https://files.gitter.im/gocd/tw-private-chat/3Hvc/2018_02_28_07-08-08.png)

###### Basic environment details

* Go Version: 18.2.0 (25072-f8093bbfc729dc30eb2ae7b868747137c1c1bb93)
* Browser vendor and version (if relevant): Pristine (no extensions) Firefox (58.0.2) and Chrome (64.0.3282.186). Happens on Safari (11.0.3) too.

**Comment by arvindsv** [comment]
For me, this seems to happen when you've set: "Show scroll bars" set to "Automatically based on mouse or trackpad" in System Preferences -> General on a Mac.

If I set it to "When scrolling", it works fine. Should close if it's only something to do with me.

**Comment by ketan** [comment]
Should probably have this tested on IE 11 and Edge
