### ISSUE TITLE
Add value stream map including all pipelines

### ISSUE THREAD

**Issue by dpsenner** [gocd/gocd#447]
Currently the pipelines view is selected as primary view, but this does not give a good overview of the state of the pipelines. A value stream map based on the current configuration and the last build information would give a much better overview.

**Comment by amlozano** [comment]
+1 after some years...

The pipeline view doesn't give any information as soon as you get into a complicated setup with tens  of pipelines. 

In our case we have around 60 pipelines. Some of those pipelines are triggered automatically, and others are triggered manually . 

In the current pipeline view you can only see the last execution status, but you don't know if a given pipeline was triggered for a given execution of a dependant pipeline. Example (all names represent pipelines):

Build => Integration Test => Deploy to Development -> Deploy to Production

=> represents automatic trigger, -> represents manual trigger

In the pipeline view, we will always see every status in green, with different information, and dates. But Deploy to Production could not be triggered for the last build, which is something that you can only see if you go to the VSM view. 

Another thing that would be useful also to have in that view is the option to manually trigger any pipeline (https://github.com/gocd/gocd/issues/2163). From the VSM there is no option to trigger, so in our case we have to check that the last step was not triggered, go back to the pipeline view, look again for the pipeline name called Deploy to Production, and click on it.
