### ISSUE TITLE
Add a link to the plugin status report from agent status report page.

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4476]
##### Issue Type

- Feature enhancement

##### Summary

Since we have enough information about the elastic agent, we will certainly know which plugin brought it up. How does adding a link to the plugin status report sound, @gocd/committers ? 

The agent status report will (or should) be made accessible to group admins and group view users. We would need to provide the plugin status button on the agent status page only for admins.

**Comment by ketan** [comment]
❤️ more links please.

**Comment by GaneshSPatil** [comment]
Following GoCD implemented plugins has a link to go from `cluster-status-report-page`  to `agent-status-report-page`.
1. Amazon ECS Elastic Agent Plugin.
2. Docker Elastic Agent Plugin
3. Docker Swarm Elastic Agent Plugin.
4. Kubernetes Elastic Agent plugin.

---

Also, adding a link to go to different GoCD Pages from the status report page is up to the plugin authors.

Closing this issue. If required, a separate issue should be opened on plugin's repository.
