### ISSUE TITLE
Allow pipelines without material

### ISSUE THREAD

**Issue by NachbarsLumpi** [gocd/gocd#448]
That would allow one to create a pipeline that has to be triggered manually, which can be useful if one wants to automate some initialization/setup that has to be done on agents but should be run only when a user wants it to be run.

**Comment by mingfang** [comment]
+1

**Comment by praveenpatidar007** [comment]
+1

**Comment by jmassara** [comment]
+1 Any consideration for this request? It's fairly old...

**Comment by etiennetremel** [comment]
+1

**Comment by virtuald** [comment]
+1

**Comment by baspeti** [comment]
+1

**Comment by selimekizoglu** [comment]
+1

**Comment by arvindsv** [comment]
Closing as a duplicate of newer issue #876.
