### ISSUE TITLE
How to call API from GOCD

### ISSUE THREAD

**Issue by tejas27** [gocd/gocd#4482]
##### Issue Type
Hi, 
I have to call an API from GOCD to track my daily deployments.
I have to send my buildversion, application name, Environment name, deployment status as parameters to the API url to which I need to hit.
Can someone please help me here.

- Feature enhancement

###### Basic environment details

* Go Version: `18.1.0`
* JAVA Version: `8`
* OS: `Windows Server 2012 R2`
* Browser vendor and version (if relevant): `IE 11`

**Comment by arvindsv** [comment]
Closing this. As the issue template clearly says, the [mailing list](https://groups.google.com/forum/#!forum/go-cd) is the right place for questions. You might want to look at the [API documentation](https://api.gocd.org/current/) too.
