### ISSUE TITLE
Do not show database ID on agent status report

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4486]
##### Issue Type

- Bug Report

##### Summary

The breadcrumbs show the DB id of the job, when it's an internal state shared between the server and plugin, users don't know what that is and should not have to care about it.

![screen shot 2018-03-06 at 7 47 27 am](https://user-images.githubusercontent.com/10598/37010712-d0466dfe-2112-11e8-8a28-9366367e08d0.png)

**Comment by rajiesh** [comment]
Verified on 18.2.0 (6228-fbb379a451871b29aa47aef907a78dc64379233f)
