### ISSUE TITLE
[pipeline template] a user which is not admin for a pipeline is able to create a template based on it

### ISSUE THREAD

**Issue by aqneves** [gocd/gocd#4496]
##### Issue Type

- Bug Report

##### Summary

Any user can create a template based on a template for which he is not an Admin. This removes the capability of the owners of those pipelines to modify them - as they won't have by default access to the pipeline template - and allows the user which created the template to modify it influencing the origin pipeline.

###### Basic environment details

* Go Version: 18.1
* JAVA Version: 1.8.0_131
* OS: Linux 3.10.0-514.26.2.el7.x86_64
* Browser vendor and version (if relevant): any

##### Steps to Reproduce

1. Pipeline U1 is created, a certain role is created and assigned to both the user and the pipeline (Admin permissions).
2. User U1 is now Admin for pipeline X.
3. User U2 is NOT Admin for pipeline X, he users other pipeline groups / pipelines.
4. User U2 decides to create a template for a pipeline and uses the “Extract from pipeline” option, selecting pipeline X as source.
5. A template is created and now, U1 can’t edit the pipeline because it’s now based on a template and he won’t be able to do so until the GO System Administrator provides access to the template itself. U2, which created the pipeline template is now admin for it.
6. U2 has now removed the capability for U1 to modify the pipeline X for which U1 is the owner. More, U2 can now edit the template and influence a pipeline for which he is not the Administrator.

##### Expected Results
A user should only be able to create a pipeline template based on templates for which he is an Admin.

##### Actual Results
A user sees the full list of pipelines when creating a template using as source another pipeline.

**Comment by rajiesh** [comment]
Verified on 18.3.0 (6537-931d914224566c5e5069d1e3c583aba8a4bfc414)
