### ISSUE TITLE
New dashboard uses localhost rather than the proxied hostname in VSM links

### ISSUE THREAD

**Issue by fire** [gocd/gocd#4503]
##### Issue Type

Bug Report

##### Summary

New dashboard uses localhost rather than the proxied hostname.

##### Environment

```plain
  "Go Server Information": {
    "Version": "18.2.0 (6228-fbb379a451871b29aa47aef907a78dc64379233f)"
  },
    "OS Information": {
    "OS Name": "Linux",
    "OS Version": "3.10.0-693.17.1.el7.x86_64",
    "System Architecture": "amd64",
    "Available Processors": 4,
    "Average System Load": 0.07
  }, "Runtime Information": {
    "Name": "3806@gocd.54.208.234.225.xip.io",
    "Uptime": 3540895,
    "Uptime (in Time Format)": "[About 0 hours, 59 minutes, 0 seconds]",
    "Spec Name": "Java Virtual Machine Specification",
    "Spec Vendor": "Oracle Corporation",
    "Spec Version": "1.8",
    "Input Arguments": [
      "-Dgocd.redirect.stdout.to.file\u003d/var/log/go-server/go-server.out.log",
      "-Djava.io.tmpdir\u003d/var/lib/go-server/tmp",
      "-Djava.security.egd\u003dfile:/dev/./urandom",
      "-Xms1536m",
      "-Xmx1536m",
      "-XX:MaxMetaspaceSize\u003d256m",
      "-Didle.timeout\u003d3600000",
      "-Duser.language\u003den",
      "-Djruby.rack.request.size.threshold.bytes\u003d30000000",
      "-Duser.country\u003dUS",
      "-Dcruise.config.dir\u003d/etc/go",
      "-Dcruise.config.file\u003d/etc/go/cruise-config.xml",
      "-Dcruise.server.port\u003d8153",
      "-Dcruise.server.ssl.port\u003d8154"
    ],
```

Latest chrome browser Version 64.0.3282.186 (Official Build) (64-bit)

##### Steps to Reproduce

1. Open new dashboard 
2. Click on vsm.
3. The address does not exist error in web browser.

##### Expected Results

VSM link should go to https://go.example.com/go/pipelines/xxx/xxx/77

##### Actual Results

VSM link goes to https://localhost:8154/go/pipelines/xxx/xxx/77

##### Possible Fix

Document proxy server changes. 

Configuration option? Force hostname?

##### Other comments

History link works.

In the previous release, clicking on the agent's status on the agent's page also has the same error.

**Comment by ketan** [comment]
> **Possible Fix**
> Document proxy server changes.

This is already documented https://docs.gocd.org/current/installation/configure-reverse-proxy.html. Marking as closed.

**Comment by ketan** [comment]
If you're using a reverse proxy that is not apache or nginx, the tl;dr; is that your reverse proxy must send the `X-Forwarded-Proto`, `Host` and `X-Forwarded-For` headers upstream to the GoCD server.
