### ISSUE TITLE
Fetch artifact in combination with run on all agents

### ISSUE THREAD

**Issue by dpsenner** [gocd/gocd#451]
Fetching artifacts when run on all agents is selected in the upstream pipeline is counter-intuitive when configuring it. For one it does not list the jobs that are autogenerated with the suffix "-runOnAll-X".

The easiest solution would be to require one to select one artifact that should be fetched, but that produces problems when agents are unavailable.

The solution which is probably more correct, could be to fetch all artifacts that were generated by all agents such that one can do operations on all of them in the pipeline.

Open for discussion!

**Comment by dharmarth** [comment]
We recently had a similar needs of collecting artifacts from all agents. We achieved the same using [gocd artifacts API](https://github.com/gocd/documentation/blob/master/user/api/artifacts_api.md)  

@NachbarsLumpi you can give it a try

Hope this helps

**Comment by NachbarsLumpi** [comment]
Did you script and configure a custom task that fetches artifacts into an upstream pipeline? The odd about that is its intransparency on dependencies. Despite that this might even work, it feels like being more a hack to work around another issue.

**Comment by dharmarth** [comment]
Your guess is right. Go sets few env variables, which became handy to determine pipeline name, counter etc in our script. I do understand its a workaround, my purpose is to collect all artifacts, not worried about dependency tracking. 

You can do one more workaround which may help in dependency tracking - create placeholder job configured to be run on any agent and fetch artifact from that job as well.
