### ISSUE TITLE
[New Dashboard]  Header (with search and Filter View) isn't pinned and scrolls out of view

### ISSUE THREAD

**Issue by PredatorVI** [gocd/gocd#4511]
##### Issue Type

- Bug Report

##### Summary

When viewing the new dashboard, the header isn't pinned to the top like the legacy dashboard and scrolls out of view.

##### Expected Results
Header should remain pinned and stay visible when view is scrolled

##### Actual Results
Header scrolls w/ page

##### Code snippets/Screenshots
View from the top:
![image](https://user-images.githubusercontent.com/1933277/37235588-fb7d850a-23bc-11e8-865b-ea16177737bc.png)

View when scrolled down:
![image](https://user-images.githubusercontent.com/1933277/37235603-0f255498-23bd-11e8-9094-1a433e95a352.png)

**Comment by rajiesh** [comment]
verified on 18.3.0 (6530-f9dc89e397d1b134f4d124e6381f8764e38e0a1d)
