### ISSUE TITLE
Dynamic agents and Config Change messages

### ISSUE THREAD

**Issue by remy-tiitre** [gocd/gocd#4513]
##### Issue Type

- Feature enhancement

##### Summary

When you use dyncamic agents (Swarm or Kubernetes etc) every time agent is created it will create "Config Changed" message for pipeline. Which makes it really difficult to pinpoint those changes that really are done to the system or pipeline.

**Comment by arvindsv** [comment]
Agents have been moved into the DB, a little earlier in the year.
