### ISSUE TITLE
Pipeline pause API throws a NullPointerException

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4515]
##### Issue Type

- Bug Report

##### Summary

If the pipeline pause API documented in https://api.gocd.org/18.2.0/#pause-a-pipeline is used with the `X-GoCD-Confirm` and no data like below, the response returns a NullPointerException: 

```
curl 'http://localhost:8153/go/api/pipelines/up42/pause' \
      -H 'Accept: application/vnd.go.cd.v1+json' \
      -H 'Content-Type: application/json' \
      -H 'X-GoCD-Confirm: true' \
      -X POST
```
Response: 

```
{"error":"Payload data is not valid JSON: java.lang.NullPointerException"}
```

**Comment by ketan** [comment]
A workaround currently would be to submit an empty JSON "{}" with a content-type of `application/json`.

**Comment by rajiesh** [comment]
Verified on 18.3.0 (6578-31b0ad88fec5af12e88b913612eb6c141abaee0e)
