### ISSUE TITLE
Go error: Could not find modification 1048

### ISSUE THREAD

**Issue by RhondaBailey** [gocd/gocd#4530]
Good morning.  We created a pipeline that relies on materials from another pipeline.  This was working fine but suddenly started getting the above error.  We have several other pipelines that rely on the same materials, are configured exactly the same and all are working.  We can't figure out what is wrong or what the error message means.  Any help would be greatly appreciated.

Thanks,

Rhonda Bailey

Error while scheduling pipeline: API_Build_Validate_Deploy_Feature [Mar-16 15:36:07]
Could not find modification 1048 in [Material: com.thoughtworks.go.domain.materials.dependency.DependencyMaterialInstance@6ec629a1[url=<null>,username=<null>,pipelineName=Fetch_AWS_Scripts,stageName=Fetch-Scripts,view=<null>,useTickets=<null>,branch=<null>,submoduleFolder=<null>,flyweightName=3e3f584c-f2af-4787-b488-67288c98187a,fingerprint=120a5b78a3bca9878c54a97a40d6ef9d0f42d38b4ebfba6bc0b0c41e80676fbc,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=30] Last Modified: 2018/03/16 14:59:29 Revision: Fetch_AWS_Scripts/95/Fetch-Scripts/1 UserName: Unknown EmailAddress: null Comment: Unknown PipelineLabel: 1efcd19cefdc6c085d9dc55d00952f559664c6b3 , Material: com.thoughtworks.go.domain.materials.dependency.DependencyMaterialInstance@6ec629a1[url=<null>,username=<null>,pipelineName=Fetch_AWS_Scripts,stageName=Fetch-Scripts,view=<null>,useTickets=<null>,branch=<null>,submoduleFolder=<null>,flyweightName=3e3f584c-f2af-4787-b488-67288c98187a,fingerprint=120a5b78a3bca9878c54a97a40d6ef9d0f42d38b4ebfba6bc0b0c41e80676fbc,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=30] Last Modified: 2018/03/16 00:01:46 Revision: Fetch_AWS_Scripts/94/Fetch-Scripts/1 UserName: Unknown EmailAddress: null Comment: Unknown PipelineLabel: 1efcd19cefdc6c085d9dc55d00952f559664c6b3 , Material: com.thoughtworks.go.domain.materials.dependency.DependencyMaterialInstance@6ec629a1[url=<null>,username=<null>,pipelineName=Fetch_AWS_Scripts,stageName=Fetch-Scripts,view=<null>,useTickets=<null>,branch=<null>,submoduleFolder=<null>,flyweightName=3e3f584c-f2af-4787-b488-67288c98187a,fingerprint=120a5b78a3bca9878c54a97a40d6ef9d0f42d38b4ebfba6bc0b0c41e80676fbc,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=30] Last Modified: 2018/03/15 23:57:58 Revision: Fetch_AWS_Scripts/93/Fetch-Scripts/1 UserName: Unknown EmailAddress: null Comment: Unknown PipelineLabel: 1efcd19cefdc6c085d9dc55d00952f559664c6b3 , Material: com.thoughtworks.go.domain.materials.dependency.DependencyMaterialInstance@6ec629a1[url=<null>,username=<null>,pipelineName=Fetch_AWS_Scripts,stageName=Fetch-Scripts,view=<null>,useTickets=<null>,branch=<null>,submoduleFolder=<null>,flyweightName=3e3f584c-f2af-4787-b488-67288c98187a,fingerprint=120a5b78a3bca9878c54a97a40d6ef9d0f42d38b4ebfba6bc0b0c41e80676fbc,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=30] Last Modified: 2018/03/15 23:21:30 Revision: Fetch_AWS_Scripts/92/Fetch-Scripts/1 UserName: Unknown EmailAddress: null Comment: Unknown PipelineLabel: 3f612ecc9b78b1a07fbc0e99d77499c781b6da27 , Material: com.thoughtworks.go.domain.materials.dependency.DependencyMaterialInstance@6ec629a1[url=<null>,username=<null>,pipelineName=Fetch_AWS_Scripts,stageName=Fetch-Scripts,view=<null>,useTickets=<null>,branch=<null>,submoduleFolder=<null>,flyweightName=3e3f584c-f2af-4787-b488-67288c98187a,fingerprint=120a5b78a3bca9878c54a97a40d6ef9d0f42d38b4ebfba6bc0b0c41e80676fbc,checkExternals=<null>,workspace=<null>,projectPath=<null>,domain=<null>,configuration=<null>,additionalData=<null>,additionalDataMap=<null>,id=30] Last Modified: 2018/03/15 23:01:33 Revision: Fetch_AWS_Scripts/91/Fetch-Scripts/1 UserName: Unknown EmailAddress: null Comment: Unknown PipelineLabel: df95ad16d78179738554bb8e71e45b6286b8a89c ]

**Comment by varshavaradarajan** [comment]
@RhondaBailey - do you mind attaching the go server log for when this error occurs?

**Comment by RhondaBailey** [comment]
There was no server log.  The error occurred before any logging.  What is posted above is all I have.

Rhonda
