### ISSUE TITLE
 How agents perform tasks in order

### ISSUE THREAD

**Issue by xuejipeng** [gocd/gocd#4533]
I have 100 servers that want to deploy the same service, but I want to deploy the second one after the deployment is completed on the first one, and then deploy the third server after the second  is deployed and so on， but I don't seem to find this one Function, how do I configure it?

If this feature is available, I think it will be a better CD tool

**Comment by arvindsv** [comment]
Each task runs after the previous one in a job. Closing for now, as stale.
