### ISSUE TITLE
Define different filter-chain for routes having IS_AUTHENTICATED_ANONYMOUSLY access

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#4541]
##### Issue Type
- Bug Report

##### Summary
Currently, `applicationContext-acegi-security.xml` defines the filter chain for `apis`, `agent-remoting` calls, `cctray.xml` and `/files`. All other request is using filter chain defined using `/**`. 

Not all the URLs which fall under `/**` have to go through all the filters in the chain. 
e.g. `admin/latest-agent.status (HEAD)` should not use `UserEnabledCheckFilter` filter.

This is also true for other routes which users can access `ANONYMOUSLY`.  Define a separate filter chain for all routes that can be accessed `ANONYMOUSLY`.
All the urls that an agent calls would fit into this category, but there are other urls too.

###### Basic environment details

* Go Version: ` Go Version: 18.3.0 (6283-70d20f60b800af5fa458126a871b01350ef30e7f)`

**Comment by arvindsv** [comment]
Closing. I believe we've changed this completely. cc: @bdpiparva
