### ISSUE TITLE
[Place holder] Allow different encryption at pipeline/stage level alongwith instance level using cipher

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#4547]
##### Issue Type

- Feature proposal

##### Summary

When GoCD instance is shared among multiple projects, its hard to manage secret keys using only instance level encryption scheme.

**Comment by remmeier** [comment]
gocd primarly supports a centralized configuration in a single xml file. Further allows gocd to encrypt secrets to savely store in the xml file. The encrypt/decryption key is savely stored within the gocd setup.

However, more and more people move the pipeline configurations into the code (Jenkins, Travis, etc.). In gocd there is such a plugin as well: https://github.com/tomzo/gocd-yaml-config-plugin. Unfortuntely, with this the current secret setup is not adequate anymore. The encrypted secrets are stored along with the pipeline configuration in the code. Any user having write access to at least a single repository can view and update the pipeline configuration. This means he can also copy/past and this way access secrets from other pipeline configurations as long as he has read access to that git repository. Gocd will decrypt the secret for him and make it accessible as environment variable.

To prevent this kind of attacks, one could restrict access to all the git repository. But for many scenarios this is probably impractical. Code should be open, but the secure variables secure. One possibility would be to add a salt to the encryption process that would limit the use of secrets to a giving pipline and maybe stage. This way secrets cannot be copy/pasted to other pipeline configurations.

**Comment by ketan** [comment]
@remmeier — where do you propose the salt, or cipher per pipeline (or pipeline group) be stored?

**Comment by remmeier** [comment]
it does not need to be stored, the salt would have to be something project related like the project name or maybe better the git url. When encrypting/decrypting a secret for a pipeline, the concatenation of salt and master password is used as encryption key. This way the decryption will only work for that one specific pipeline. 

Not sure what to best take as salt. The git url of the pipeline config may the one thing that cannot be tampered with. Things like pipeline group and names are not "protected" and can be freely chosen.

**Comment by ketan** [comment]
Thanks — let me think about this for some time.
