### ISSUE TITLE
Should format the error message in Cron Timer Specification

### ISSUE THREAD

**Issue by ShilpaGopal** [gocd/gocd#4548]
##### Issue Type
- Bug Report

##### Summary

When an Invalid syntax is specified in the Cron Timer Specification(Eg: 0 0 19 ? * SUN-TH) results in error "Invalid cron syntax: Illegal cron expression format (java.lang.StringIndexOutOfBoundsException: String index out of range: 7)"

##### Expected Results
 Should format the error message not to display the exceptions 

##### Any other info
![screen shot 2018-03-22 at 8 25 24 am](https://user-images.githubusercontent.com/13718648/37749825-cda66c12-2daf-11e8-90dc-cc5e10d43739.png)

**Comment by varshavaradarajan** [comment]
@ShilpaGopal - Shouldn't the days be `SUN-THU` ?

**Comment by ShilpaGopal** [comment]
Yes It suppose to be. Above Is an example of invalid format where I can see
the exceptions in the error message.
