### ISSUE TITLE
Do not hardcode `/go` webapp context path at all places

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4558]
##### Issue Type

- Bug Report

##### Summary
`cruise.server.context` can be used to change the default webapp context path from `/go` to something else. Although, at many places in the GoCD codebase the webappContext path is hardcoded to `/go`.

**note:** Users are not expected to override the default webapp context path, as many of the pages might not work.

##### Possible Fix
* Do not allow users to override the default webapp context path, by removing `cruise.server.context` system environment.
* Define the default webapp context at only one place, which gives the flexibility to change the webapp context path easily by changing it at only one place.

**Comment by arvindsv** [comment]
Closing as stale. This is unlikely to be changed.
