### ISSUE TITLE
ellipsize the pipeline name on the dashboard

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4561]
##### Issue Type

- Bug Report

##### Summary

For a long pipeline name, it gets overlapped with the analytics icon:

<img width="288" alt="screen shot 2018-03-27 at 8 55 04 am" src="https://user-images.githubusercontent.com/10598/37945197-a7d9775e-319c-11e8-9e04-d18d97fb2422.png">

**Comment by GaneshSPatil** [comment]
@ketan @naveenbhaskar -- I guess we need to rethink about the positioning of the plugin icons.
There could be minimum 2 icons (always) if one has analytics plugin installed.
The number of the icons could increase, based on:
* Pipeline is locked
* More analytics plugins are installed.

In the above-mentioned scenarios, there will always be a slight possibility of pipeline-name overlapping with the icons.

**Note**: As of now, we just have analytics plugin icon displayed on the pipeline, going forward we might have more plugin icons, example: icons indicating: deployment-pipeline, config-repo-pipeline, etc

**Comment by rajiesh** [comment]
verified on 18.3.0 (6530-f9dc89e397d1b134f4d124e6381f8764e38e0a1d)
