### ISSUE TITLE
Material Revision under trigger with options should default to latest if not present

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4565]
##### Issue Type

- Bug Report

##### Steps to Reproduce

1.  Click on trigger with options for a pipeline which is never ran
2. material revision under the tabular box does not contain material revision information

###### Old page
![screen shot 2018-03-27 at 10 54 49 am](https://user-images.githubusercontent.com/15275847/37948429-e5050c18-31ad-11e8-9959-914edc2c371b.png)

###### New page
![screen shot 2018-03-27 at 10 55 05 am](https://user-images.githubusercontent.com/15275847/37948433-e84b15de-31ad-11e8-9ce8-4e0f0e7399f0.png)

**Comment by GaneshSPatil** [comment]
Also, the ellipses shown for the material name is right stripped on the new dashboard, whereas on the old dashboard it was middle stripped.

**Comment by rajiesh** [comment]
Verified on 18.3.0 (6530-f9dc89e397d1b134f4d124e6381f8764e38e0a1d)
