### ISSUE TITLE
[New Dashboard] Change font of commit message to be the same as commit author and SHA

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4567]
##### Issue Type

- Bug Report

##### Summary

To maintain uniformity on the new dashboard, the font-family of the commit message should be the same as the commit author and the material revision.

**Comment by rajiesh** [comment]
Verified on 18.3.0 (6530-f9dc89e397d1b134f4d124e6381f8764e38e0a1d)
