### ISSUE TITLE
Redirect to first stage details page breaks when no data is available

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4572]
##### Issue Type
- Bug Report

##### Summary

`/go/internal/pipelines/<PIPELINE_NAME>/<PIPELINE_COUNTER>` redirects to `/go/internal/pipelines/<PIPELINE_NAME>/<PIPELINE_COUNTER>/<FIRST_STAGE_NAME>/<FIRST_STAGE_COUNTER>`

when no pipeline instance information is not available for the provided pipeline_name or pipeline_counter, the page throws a 500.

**Note:** The internal redirect link was added mainly for analytics plugin. There might be a situation where the plugin can have the pipeline instance analytics, but the core GoCD data (for the same pipeline instance) might have been deleted. 
In such scenarios, the page should render an appropriate error message.

##### Steps to Reproduce

1.  Visit URL: https://build.gocd.org/go/internal/pipelines/build-linux/21960

##### Expected Results
The page should show no data available for the current pipeline instance message.

##### Actual Results
The page returns an internal server error message.

**Comment by rajiesh** [comment]
Verified on 18.4.0 (6640-1fb2812cfa45eee8502e420443f2b46d81c51f98)
