### ISSUE TITLE
Have the same xml tag to represent fetch task for built in artifact and pluggable artifacts

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4577]
##### Issue Type

- Feature enhancement

##### Summary

Currently, the fetch tasks look like - 

Built in fetch tasks 
```xml
<fetchartifact pipeline="pipelineName" stage="stageName" job="jobName" srcdir="dirName" dest="dest" />
<fetchartifact pipeline="pipelineName" stage="stageName" job="jobName" srcfile="fileName" dest="dest" />
```

Pluggable Artifact's fetch task
```xml
<fetchPluggableArtifact pipeline="pipelineName" stage="stageName" job="jobName" artifactId="artifactId">
  <configuration>
    <property>
      <key>plugin_provided_configuration_key</key>
      <value>foo_what_else</value>
    </property>
  </configuration>
</fetchPluggableArtifact>
```

Since the above two aren't different kinds of tasks, having different xml tags to represent them seems wrong. Planning on having an additional `type` attribute to distinguish between  - 

```xml
<fetchartifact type="external" pipeline="pipelineName" stage="stageName" job="jobName" artifactId="artifactId">
  <configuration>
    <property>
      <key>plugin_provided_configuration_key</key>
      <value>foo_what_else</value>
    </property>
  </configuration
</fetchartifact>
<fetchartifact type="builtin" pipeline="pipelineName" stage="stageName" job="jobName" srcdir="dirName" dest="dest" />
<fetchartifact type="builtin" pipeline="pipelineName" stage="stageName" job="jobName" srcfile="dirName" dest="dest" />
```

Need to take care of
1. The pipeline config API
2. Quick edit view to show the type attribute while configuring the fetch tasks
3. Old fetch task view to show the type attribute. 

Pending discussion with @naveenbhaskar around how the view should look like. We'll update this issue with mockups.

**Comment by rajiesh** [comment]
Verified on 18.4.0 (6640-1fb2812cfa45eee8502e420443f2b46d81c51f98)
