### ISSUE TITLE
Add an SPA to configure Artifact Stores

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#4580]
##### Issue Type
- Feature enhancement

##### Summary
Artifact Stores need to be configurable from the UI. We plan to add a menu item under Admin to link to an SPA for this. 

##### Wireframe
The main page will look like:
![screen shot 2018-03-28 at 15 25 11](https://user-images.githubusercontent.com/6024038/38022141-5c3fc84c-329c-11e8-8e24-025ac36a14f3.png)

On clicking the Add button, a modal will pop up which will look like:
![screen shot 2018-03-28 at 15 25 17](https://user-images.githubusercontent.com/6024038/38022176-75979cac-329c-11e8-853c-6a91e052a0a6.png)

The styling will be similar to the Elastic Agent Profiles page.

Suggestions and comments welcome.

/cc: @naveenbhaskar

**Comment by varshavaradarajan** [comment]
Can we add a message if not plugins of artifact type are found? 
https://user-images.githubusercontent.com/15275847/37595902-6b8b6dd6-2ba0-11e8-8e2a-07fc65a141c2.png

**Comment by varshavaradarajan** [comment]
Verified on 18.4.0-6640.
