### ISSUE TITLE
Material revision suggestion dropdown in trigger with option touches bottom of the screen

### ISSUE THREAD

**Issue by yankurk** [gocd/gocd#4599]
##### Issue Type

UI improvement

##### Summary

Material revision suggestion dropdown touches the bottom of the screen. There should ideally be a gap between the dropdown and the bottom of the screen.
![screen shot 2018-04-03 at 10 22 25 am](https://user-images.githubusercontent.com/23699743/38229927-ef37c948-3728-11e8-91f5-1e55e0ebe2ce.png)

**Comment by GaneshSPatil** [comment]
This has been fixed as part of GoCD release v18.3.0 (New Dashboard).

Adding a screenshot of the dashboard after the fix:
![screen shot 2018-07-05 at 10 01 03 am](https://user-images.githubusercontent.com/15275847/42302756-793740ba-803a-11e8-9fb4-7f4aeeea1bea.png)
