### ISSUE TITLE
Support label template based on environment variables and property
files

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#46]
Currently Go only supports label template based on \$(COUNT), changelists from version controls and labels from upstream pipelines, but label template should start supporting either of the following (and
of course preferably both)

1) Environment variables\
 e.g. < pipeline name=”ABC” labeltemplate=”${env.XXX}” >
 where XXX is defined on the build machine

2) Property from a file
 e.g. <pipeline name=”ABC” labeltemplatefile=”xyz.txt”>

**Comment by JorritSalverda** [comment]
Some extra variables on Go itself would make sense as well. For example to be able to create a version with year and month in the format of YYYY.M.{counter that resets if YYYY or M changes}.{COUNT} leading to something like 2015.4.55.19238. Right now there are too few options to control the label other than updating it manually or through the api.

**Comment by kargs** [comment]
Any updates on this?

**Comment by vaibhavparnalia** [comment]
Interested!

**Comment by EbenZhang** [comment]
Interested!

**Comment by Sendami** [comment]
Yes, please!

**Comment by remy-tiitre** [comment]
Why we still don't have this? Do really all users keep their version numbers in gocd configuration and not in git repo or properties file etc.

**Comment by vaibhavparnalia** [comment]
Still waiting for this or #52

**Comment by paulwinning** [comment]
This is something that we're really interested in.  For a given RTL deployment, we use the same pipelines and then specify HOTFIX or RELEASE as an environment variable at runtime.  We'd love to be able to customise the label depending on the type of deployment specified.

**Comment by adityasood** [comment]
Pipeline level Environment Variable Reference Support for Pipeline Label is available from GoCD v18.10.0.

Verified on 18.10.0-7703
