### ISSUE TITLE
SPA or API: to download api-support and GoCD server log

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#4618]
Provide a way for GoCD user to generate and download an API support and server log of same time span. This will make sure that the api-support and the logs shared by the customer is from the same time span. 

Considering that not all users will have a access to the physical machine for downloading log files, this could be a simple SPA or an API, using which a user should be able to download the `zip` file and send it over to the support team.

It can be generated with the following information -

- Environment information
  * Platform
  * Operating system
  * Memory
  * CPU
  * Go Version
  * JAVA Version including minor version
  * Browser vendor and version
 
- API support  from  `go/api/support`

- Logs (`go-server.log` and `plugin*.logs`)

Still, need to figure out steps to be taken when the gocd server is under heavy load and it fails to generate the `zip` file on time.

**Comment by bdpiparva** [comment]
@gocd/committers --- WDYT?

**Comment by arvindsv** [comment]
I think this will be good. Also, we often ask that people provide multiple outputs of this - spread out across time. I expect that this will take care of that too.

**Comment by ketan** [comment]
It would be preferred if there was some API to be able to capture thread dumps programmatically. That way we can use better tooling for analyzing the dumps, than writing our own.
