### ISSUE TITLE
Revert temporary admin check for analytics plugins

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#4619]
**Needs** to be removed before 18.3 is released.

Allow all users to be able to see the charts. Top-level charts will still be restricted, at least for now. Till we figure out authorization for top-level concepts.

**Comment by GaneshSPatil** [comment]
@arvindsv @maheshp @marques-work @ibnc -- Authorization Checks:

|Analytics Chart| Permissions |
|---------------|-------------|
|Pipeline Level | Pipeline Group Admin|
|Analytics Page | Super Admin|


As of now, I am not too worried about Pipeline group admins not able to see the _Analytics Page Pipeline Tab_ Analytics, as they will be seeing the same information as they can see on the pipeline tile. Going forward if we add more things to the pipeline level analytics, we should consider authorization.

**Comment by arvindsv** [comment]
👍 

We should leverage the work that @varshavaradarajan and @akshaydewan are planning around authorization. Hopefully, it is flexible enough to allow this.

**Comment by arvindsv** [comment]
@GaneshSPatil @maheshp This needs to be fixed. Currently, it looks like user permissions for the pipeline [are not checked](https://github.com/gocd/gocd/commit/b34e9e6dfb52b7670f504976fbc581e0b24af0e2#diff-d5e2db84cfed933b97290dcb8a157d34R102).

**Comment by GaneshSPatil** [comment]
@arvindsv @maheshp -- can this issue be closed?
We've taken care of the permissions for the charts of different level.

**Comment by arvindsv** [comment]
As long as users without permissions to a pipeline cannot see pipeline-level analytics for it, I think it's ok. I believe this is the case. Closing.

/cc @Rajiesh
