### ISSUE TITLE
Introduce the `<configuration>` subtag on `<artifact type="external">`

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4627]
##### Issue Type

- Feature enhancement

##### Summary

In order to be consistent with https://github.com/gocd/gocd/issues/4577, introduce the `<configuration>` subtag on `<artifact type="external">`. 

This includes a config migration to push the `<property>` to the `<configuration>` subtag

**Comment by rajiesh** [comment]
Verified just the validation around configuration sub tag added as part of 18.4.0 release
