### ISSUE TITLE
Build cause popup + project tracker - Formatting issue

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#4637]
##### Issue Type

- Bug Report

##### Summary

XML entities in the build cause popup are confused as targets for project tracker integration. See this image:

<img width="820" alt="2018_04_09_16-20-26" src="https://user-images.githubusercontent.com/172235/38520961-4b218ae4-3c12-11e8-919f-3a18802303e3.png">

The apostrophe was converted to `&#39;` which is fine. However, the `#39` was seen as a number which should be linked using the project tracker mechanism and that led to the build cause popup shown.

###### Basic environment details

* Go Version: `18.3.0 (6470-3f710d8f2a51c60ceffbebeadf9c482d6314cb5a)`

**Comment by ketan** [comment]
@akshaydewan can you take a look, or I can do this if you are in the middle.of something.
