### ISSUE TITLE
Trigger with options modal doesn't show material info when new material is added.

### ISSUE THREAD

**Issue by AksMKR** [gocd/gocd#4643]
##### Issue Type

- Bug Report

##### Steps to Reproduce

1. Add new pipeline. 
2. Add material to pipeline.
3. On dashboard click trigger with options button.

##### Expected Results
At 4th step, it should show spinner. Once the material information is received from server, it should hide spinner and show material information.

##### Actual Results
At 4th step, its not hiding the spinner.

**Comment by GaneshSPatil** [comment]
Fixed as part of GoCD release v18.3.0 via https://github.com/gocd/gocd/pull/4654
