### ISSUE TITLE
Dashboard API returns empty for pipeline groups even if a pipeline group is present in the config

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4645]
##### Issue Type

- Bug Report

##### Summary

If a pipeline group is configured and it contains no pipelines, the dashboard API response does not contain the pipeline group. This could be inconvenient for pipeline groups configured with config repos.

###### Basic environment details

* Go Version: `18.3.0`

##### Steps to Reproduce

1. Start the go server with the following config - 
```
 <pipelines group="first">
    <authorization>
      <view>
        <user>operate</user>
      </view>
      <admins>
        <user>operate</user>
      </admins>
    </authorization>
  </pipelines>
``` 
2. Go to /go/dashboard

##### Expected Results

An empty pipeline group with settings icon.

##### Actual Results

No pipeline groups are present.

**Comment by varshavaradarajan** [comment]
This seems like an expected behaviour. @arvindsv - care to comment? I was using this to redirect to the pipeline creation wizard to retain the behaviour of the old dashboard - https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/app/controllers/pipelines_controller.rb#L38

**Comment by arvindsv** [comment]
I have no thoughts about this. It didn't seem like an empty group was necessary. But, if it's needed, we should remove the check in `allPipelineGroupsForDashboard` I suppose.

**Comment by varshavaradarajan** [comment]
Closing this as not showing the pipeline group when there are no pipelines in that group is intentional and the behaviour is retained from the old dashboard.
