### ISSUE TITLE
[New Dashboard] Trigger and edit options disabled for admin users if using same browser session 

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#4648]
##### Issue Type

- Bug Report

##### Summary

On a browser session if view user is logged in and see trigger and edit pipeline options disabled. Then logout and login as admin user in the same session, the trigger and edit pipeline options are disabled for admin user too

###### Basic environment details

* Go Version: `18.3.0 (6516-1fd1587429dda01496b19eff7752fb64c072526e)`
* Browser vendor and version (if relevant): `Chrome Version 65.0.3325.181`

##### Steps to Reproduce

1. Login as view user of pipeline P1
2. P1 trigger and edit options are disabled
3. Now on logout and login as admin on the same browser session
4. P1 trigger and edit options are disabled for admin user too

It happens other way around too, If the view user logins on the same session which was logged in by admin user, view user can see trigger and edit options enabled for them. However the API calls fail, so view user cannot perform any operations

**Comment by arvindsv** [comment]
For the sake of completeness, this happens only if the view user and admin user can see the same list of pipelines.

**Comment by rajiesh** [comment]
Verified on 18.3.0 (6530-f9dc89e397d1b134f4d124e6381f8764e38e0a1d)
