### ISSUE TITLE
Move tasks is rather slow and tedious when having to move a lot of tasks

### ISSUE THREAD

**Issue by NachbarsLumpi** [gocd/gocd#467]
Specifically, we have several components that are aggregated in one job into a single deployable unit. Therefore every component must be downloaded by using FetchArtifact and after that there are three commands to be run. Adding new tasks adds them to the bottom and requires us to click them three times just to have them in the right spot. There would be nice to have either one of those:

* drag and drop with multiselection or an equivalent alternative (like having checkboxes and a button "add after" / "add before")
* add at specific position

**Comment by zabil** [comment]
This might be solved with #1404

**Comment by zabil** [comment]
There's a new task to keep track of design and implementation on this in the new configuration UI #1496

Closing it as it will be solved as a part of that.

**Comment by zabil** [comment]
The proposed UI

![taskdragdrop](https://cloud.githubusercontent.com/assets/54427/10512215/658a59dc-735c-11e5-8b4a-c94f4e199b9f.gif)

**Comment by NachbarsLumpi** [comment]
Wow, this looks promising. Do you have plans to make this work with
multiselection? Note also that this might not work well on touch devices,
but that's not an issue to me.
