### ISSUE TITLE
Using gocd python library with correct credentials getting status code 401

### ISSUE THREAD

**Issue by vkrisha** [gocd/gocd#4682]
Bug

i have a script using gocd python library to connect to goserver and get pipeline status, it was working fine on GOCD 16.x but when i upgraded to 18.3 it always throwing 401 with correct credentials. can you help me on this.

**Comment by ketan** [comment]
Can you provide more details on what API calls the library is making? The issue template asks for steps to reproduce that you've not provided — so I don't think we can provide a fix without that information.

**Comment by ketan** [comment]
I'm sorry I don't know what python module you're referring to. Can you provide a curl or a simple script that I can run locally?

**Comment by vkrisha** [comment]
i'm not using curl for this, well the script is simple
if you want to try in python,

pip install gocd
then

save the below code in a ex.py file (change server, user , password and pipline name)

from gocd import Server
  server_connection = Server("http://localhost:8153", user = "abc", password = "Enp1")
  a = server_connection.pipeline("Test1")
  b = a.history()
  print b.status_code

**Comment by varshavaradarajan** [comment]
@vkrisha - are you sure the user `abc` has still got the right permission to access the API?

**Comment by vkrisha** [comment]
yes, as i said it was working in go 16.x and when i have upgraded to 18.3 it is not working, even if manually login with "abc" its success.

**Comment by varshavaradarajan** [comment]
@vkrisha - this python library is maintained by a community member @gaqzi . Please raise the issue there - https://github.com/gaqzi/py-gocd/issues

**Comment by standingb76** [comment]
Here is the exception in debug mode:
send: 'GET /go/api/config/pipeline_groups HTTP/1.1\r\nAccept-Encoding: identity\r\nHost: something:8153\r\nConnection: close\r\nUser-Agent: py-gocd\r\n\r\n'
reply: 'HTTP/1.1 401 Unauthorized\r\n'
header: Date: Wed, 25 Apr 2018 14:57:33 GMT
header: Set-Cookie: JSESSIONID=qwdwdwd;Path=/go;Expires=Wed, 09-May-2018 14:57:33 GMT;HttpOnly
header: Expires: Thu, 01 Jan 1970 00:00:00 GMT
header: X-XSS-Protection: 1; mode=block
header: X-Content-Type-Options: nosniff
header: X-Frame-Options: SAMEORIGIN
header: X-UA-Compatible: chrome=1
header: Connection: close
Traceback (most recent call last):
  File "gocdAdmin.py", line 58, in <module>
    pipeGroups = getPipelines()
  File "gocdAdmin.py", line 17, in getPipelines
    data = gocdMan.pipelineGroups()
  File "./lib/gocdManage.py", line 39, in pipelineGroups
    return response.is_ok, response.body
  File "/Library/Python/2.7/site-packages/gocd/api/response.py", line 98, in payload
    if self.is_json:
  File "/Library/Python/2.7/site-packages/gocd/api/response.py", line 67, in is_json
    return (self.content_type.startswith('application/json') or
AttributeError: 'bool' object has no attribute 'startswith'

**Comment by ketan** [comment]
See [this url](https://api.gocd.org/current/#authentication) for details about authentication. I'm going to mark this issue as closed, unless there's a demonstrable way to reproduce some issue. Please respond if you have something and I can reopen the issue.

**Comment by standingb76** [comment]
I suspect the problem is somewhere here: HTTPBasicAuthHandler. Here is a supporting issue:
https://stackoverflow.com/questions/3530910/python-auth-handler-not-working-for-me?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by standingb76** [comment]
You can close this, the issue has been raised with supporting team of the gocd python library:
https://github.com/gaqzi/py-gocd/issues/20

**Comment by varshavaradarajan** [comment]
This was due to a bug introduced #4585 because of https://github.com/gocd/gocd/pull/4585/files#diff-cacd1001d9392bd437508c2c92816b5fR51 and https://github.com/gocd/gocd/pull/4585/files#diff-10f894ef12c1ff6e9c8dac675693e03cR46. Adding the `cruiseLoginOrBasicAuthenticationFilter` (which is badly named) ensured that the request was served  before the `WWW-Authenticate` header could be set. This will be fixed by #4611 when we release 18.4
