### ISSUE TITLE
Missing job run estimates on elastic agents

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4685]
##### Issue Type

- Bug Report

##### Summary

The job run duration is basically performed using "yesterday's weather" and "on the same agent" ([code here](https://github.com/gocd/gocd/blob/949fa6043f4c0fbe96cdbad30820f370f846ce62/server/src/main/java/com/thoughtworks/go/server/dao/StageSqlMapDao.java#L258-L264)). A lot of this seems to assume [snowflake](https://martinfowler.com/bliki/SnowflakeServer.html) build machines. However this metric fails to provide any build estimate for elastic agents because they only ever run one job.

Given the push to elastic agents and k8s, I'm wondering whether we should either:

1. Redefine the metric as "last runtime of this job, on any agent" — this assumes that agents are homogenous. Even the snowflake ones
2. Redefine the metric as "average of last X jobs, on any agent" — this should help bring the estimates closer to what users would expect if there's some difference of build times on different machines
3. Redefine the metric only for elastic agents using the definition(1) above

Thoughts?

**Comment by arvindsv** [comment]
My preference would be option 2 and then option 1.
