### ISSUE TITLE
Remove the /about page?

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4694]
The page seems to now be mostly irrelevant to me.

Unless anyone has objections to removing it, I'm going to remove it.

**Comment by varshavaradarajan** [comment]
@ketan - @jyotisingh added the count of pipelines and other details for the sales team.

**Comment by varshavaradarajan** [comment]
Closing this as the about page was kept intentionally as a quick way to get some information. @ketan , please reopen if you consider this is needed to be done.
