### ISSUE TITLE
Enhancement: Fix stage rerun and Job Rerun bug in VSM

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#47]
### Description

In case of stage rerun/ job re-run, while showing the value stream map,
we should pickup the stage details from the cruise-config while the
pipeline is running. Right now we are picking up the previous run
details and displaying them as run details for the downstream
pipelines.

This issue is pronounced only when the pipeline is running

**Acceptance Criteria:**
-   In case of stage re-runs, the latest stage runs need to be shown for
  that instance
-   All downstream pipelines that have not run need to show stages from
  the configuration
  **Verification:**
1.  Rerun an existing stage and verify if stages ofdownstream pipelines
   are being shown as blank while the stage is in progress. Also verify
   after the completion of run of all stages, proper revisions and
   stage status is being shown
2.  Rerun a job and verify if stages of downstream pipelines are being
   shown as blank while current pipeline stage is in progress. Also
   verify after the completion of run of all stages, proper revisions
   and stage status is being shown
3.  Pause couple of downstream pipelines, re-run a job or pipeline for
   the pipeline context and verify if the stages are blank since they
   can't be triggered.

**Comment by arvindsv** [comment]
Closing. This has been open for too long with no interest. :(
