### ISSUE TITLE
LDAP doesn't work for Active Directory with referrals

### ISSUE THREAD

**Issue by fleipold** [gocd/gocd#470]
Active Directory (which is probably the most commonly used ldap server in the entreprise) referrals are not handled automatically. This leads PartialResultExceptions, which then prevents go from authenticating properly.

There is a workaround in the Spring LdapTemplate. Quote from the LdapTemplate javadocs:

```
Note for Active Directory (AD) users: AD servers are apparently unable to handle referrals 
automatically, which causes a PartialResultException to be thrown whenever a referral is 
encountered in a search. To avoid this, set the ignorePartialResultException property to true. 
There is currently no way of manually handling these referrals in the form of ReferralException, i.e.
either you get the exception (and your results are lost) or all referrals are ignored (if the server is 
unable to handle them properly. Neither is there any simple way to get notified that a 
PartialResultException has been ignored (other than in the log). 
```

**Comment by tobowers** [comment]
:+1: on this - just ran into this. Is there a place I can add this to the go server properties?

**Comment by lenucksi** [comment]
:+1:

**Comment by arvindsv** [comment]
Closing. https://github.com/gocd/gocd-ldap-authentication-plugin is the right place for this, but it probably needs a PR from someone.
