### ISSUE TITLE
Agent - not honoring GO_AGENT_LOG_DIR directive in "service_mode"

### ISSUE THREAD

**Issue by ralcini** [gocd/gocd#4718]
##### Issue Type
- Bug Report

##### Summary

We tried to configure the new version of gocd agent 18.1 in service mode in order to save agent logs in a custom directory using the GO_AGENT_LOG_DIR environment variable, but the option seems to be not sent to the agent process.

###### Basic environment details

* Go Version: 18.1.0 (5937-8a847b96ee8d38173f80178ed1285f0e53a970e0)
* JAVA Version: 1.8.0_161
* OS: Linux 3.10.0-693.21.1.el7.x86_64

##### Steps to Reproduce

1. yum install go-agent #18.1 but go-agent-18.3.0-6540.noarch too
2. vi /etc/default/go-agent
3. fill the conf file as follow: 
```[root@os ~]# vi /etc/default/go-agent
GO_SERVER_URL=https://<server_address>:8154/go
AGENT_WORK_DIR=/var/lib/${SERVICE_NAME:-go-agent}
DAEMON=Y
GO_AGENT_LOG_DIR=/var/log/go-agent/`
```
4.  systemctl restart go-agent.service 

##### Expected Results
We are expecting to see agent logs on /var/log/go-agent/go-agent.log

##### Actual Results
Logs are written on /var/lib/go-agent/logs/go-agent.log

##### Possible Fix
Fix in https://github.com/gocd/gocd/blob/master/installers/go-agent/release/agent.sh the index argument used for service_mode check. From ```[ "$1" == "service_mode" ];``` to ```[ "$2" == "service_mode" ];```

https://github.com/gocd/gocd/blob/1fb2812cfa45eee8502e420443f2b46d81c51f98/installers/go-agent/release/agent.sh#L115
https://github.com/gocd/gocd/blob/1fb2812cfa45eee8502e420443f2b46d81c51f98/installers/go-agent/release/agent.sh#L127

**Comment by arvindsv** [comment]
@ralcini Thanks! I think your suggested fix makes sense. Do you want to submit a small PR for it? Someone will be able to review and merge it later today. If not, that's ok.
