### ISSUE TITLE
Authorization on pipeline groups, templates and other global entities

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4735]
##### Issue Type

- Feature enhancement

##### Summary

The current implementation of authorization deals with authorization at the pipeline group level and template level. While this is okay to grant permissions to users and roles to access the corresponding resource, a lot of the times it has proven to be insufficient when it comes to dealing with other global entities like config repos, environments, etc

Problems with the current implementation of authorization:

1. Global entities such as scm, package-repo, elastic agent profiles, artifact stores are entities that can be referred to by pipelines or templates. The current auth implementation does not provide an option to specify which pipelines or templates can refer to them. 
Pluggable SCMs and package repos are global resources that can be created by group admins while configuring materials for the pipeline. Today, they can be referred by other pipeline groups and edited by any group admin. The same goes for elastic agent profiles. Artifact stores can only be accessed by admins at this point (needs to change in order to make it consistent with the other entities).

2. Environments - Today, only admins can associate a pipeline with an environment. This can be inconvenient when a group admin has to contact the super admin to add a pipeline to an environment every time a new pipeline is created.  
 
##### Proposal

1. Have authorization on all global entities - pipeline group, template, scm, package-repo, config-repo, environment, elastic agent profile, artifact store. 

2. Wherever relevant, have the appropriate tag to denote a particular privilege (for lack of a better word). For example the `<operate>` tag doesn't make sense at the template level and this is restricted at the xsd. Similarly, we can add a `<can-be-referred-by>` tag for scm, package-repo, elastic profile, artifact store. This tag can indicate the pipeline or template that can refer to the entity. 

```
<authorization>
  <admin>
    <user>user1</user>
    <role>other-people</role>
  </admin>
  <can-be-referred-by>
    <pipeline>pipelineName</pipeline>
    <pipelineGroup>groupName</pipelineGroup>
     <template>templateName</template>
   </can-be-referred-by>
  <some-other-privilege>
    ...
  </some-other-privilege>
</authorization>
```

3. The above authorization object on individual entities makes sense only once the entity is created. It defines who can get, update and delete (template admins can do a delete) an entity. Pipeline group admins cannot perform a delete operation from the UI or through `admin/config_xml` today. 

4.  Have a `creators` section on the collection of entities. Example:

```
<templates>
  <creators>
    <user>user2</user>
    <role>user2-clones</role>
  </creators>
  <pipeline name="template1">
    <authorization>
      ...
    </authorization>
  </pipeline>
</templates>
```
Since authorization on individual entities comes into picture only if the entity exists, who gets to create the entity is also important. The only exception to this is the creation of a pipeline group. Pipeline group can only be created by super admins. The reason for this exception is that we have to come up with the xsd for collection of pipeline groups that can be created by super-admins only to have the `<creators>` section. We could do that but doesn't seem necessary at this point. Other collection of entities can be created by super admins and super-admins have to configure the `creators`. Once creators are configured, they can create individual entities. All group admins can become creators for all global entities by default. 

@arvindsv - anything else?

**Comment by arvindsv** [comment]
@varshavaradarajan - Can you edit this to change all mentions of admins to either "super admin" or "group admin"? Instances like these:
- `Today, only admins can associate ...`
- `... can only be accessed by admins at this point ...`

Two thoughts:
- Should we then have authorization itself at the top-level, as an entity that can be shared by different entities?

    ```
    <templates authorization="auth-id-1">
    ...
    </templates>
    ```

    That can go well with our idea of treating authorization as an entity in the API. It could lead to a "Who creates an authorization?" question, of course.

- What if these are not XML tags, controlled by the XSD? I'd prefer something more fluid. Like the `Resource` in [AWS IAM policies](https://aws.amazon.com/blogs/security/writing-iam-policies-how-to-grant-access-to-an-amazon-s3-bucket/). Seems like it'll be less troublesome to extend.

**Comment by gibsonm** [comment]
+1 here to indicate interest in a revamp of the permission handling.  Currently, I have to give super admin to folks that need to be able to create pipeline groups and assign pipelines to environments.  That's generally a really bad idea.

**Comment by zerolaser** [comment]
for large teams it would be stopper for them to contact the CI/CD admins to grant them permissions to add their pipeline to an environment. I believe the CI/CD system administrators should only manage the CI/CD but not restrict the users to build anything. 
I understand that once a user has greater permissions to do, he'll be able to delete stuff. but one should be in a place to restrict them to their team namespace and such people's permissions should be handled at read only level.

**Comment by zerolaser** [comment]
I think restrict the users to add pipeline to an environment to which they're admins to the pipeline could help.

**Comment by GaneshSPatil** [comment]
## Granular Authorization:

### Access Policy
Granular authorization can be achieved by defining access policies.
An access policy is a global config entity, consisting of a set of **`permission to users`** map.

Each access policy can be consisting of one or more following permissions:
1. Admin
2. View
3. Operate (for pipeline, pipeline-groups and environments)
4. (If applicable) Anything entity specific.

A permission needs to be granted to a set of users from the system. Hence, to each permission a list of users needs to be associated.

Here is an example of the global access policy:
```xml
<access-policies>
	<access-policy id="microservice-1-admin-team">
		<admin>
			<user>bob</user>
			<user>john</user>
		</admin>
		<view>
			<user>drake</user>
		</view>
	</access-policy>
</access-policies>
```

### referencing Access Policy

A defined access policy later can be associated with an config entity.
Eg:

```xml
<pipelines group="microservice-1">
	<access-policies>
		<access-policy ref="microservice-1-admin-team" />
	</access-policies>
    <pipeline name="up43" />
</pipelines>
```

### Inline Access Policy

One of the problems with global access policy is, unnecessary global entity when its referenced only once.

Imagine a situation where we want to add extra admin user to a policy only for a particular config entity. Creating one more global access policy to achieve this will cause duplication and redundency. Instead, we can let admin users define inline access policy.
Eg:

```xml
<pipelines group="microservice-1">
	<access-policies>
		<access-policy ref="microservice-1-admin-team" />
		<access-policy>
			<admin>
				<user>tina</user>
			</admin>
		</access-policy>
	</access-policies>
    <pipeline name="up43" />
</pipelines>
```

Supporting both policy-reference and inline policy definition might cause following problems:
1. Duplication of user permissions
2. Privilege escalation via inline policy definition
3. Dropping/Downgrading privileges via inline policy definition


### Privilege chain
1. An access policy privileges defined at a config group entity can be overridden by specifying access policy per entity.
2. Only privilege escalation should be allowed for nested config entities.

### Predefined/Inbuilt access policies?

As Access Policy will be the first class entity in GoCD, do we still need to specify system admins as part of `<admins>` tag?
Can it be a predefined/inbuilt access policy? with name `system-admins`?

### Unknowns:
1. What happens to roles? Do we still need them after access policies?
2. Backward compatibility with existing authorization
3. Backward compatibility with system admins.
4. How the association between config entity and access policy should be defined?

---

**Note:** This issue just deals with access policies. It does not take care of reference policies (who can refer/consume this entity). To know more about reference policies see https://github.com/gocd/gocd/issues/5832

\cc: @rajiesh @ketan @gocd/committers

**Comment by arvindsv** [comment]
In the spirit of #5832, I was wondering if it could be attached at the level of a GoCD role. Then, it would be something like:

```
<role name="role1">
  <policy>
    <allow action="edit" type="environment">env_1</allow>
    <allow action="admin" type="pipeline_group">pg_1</allow>
    <allow action="view" type="pipeline_group">pg_2</allow>
    <allow action="operate" type="pipeline_group">pg_3</allow>
    <allow action="edit" type="scm">scm_2</allow>
    <allow action="edit" type="role">role2</allow> <!-- !!! -->
  </policy>
  <user>...</user>
</role>
```

That way it seems:

1. Easier to apply and at one place.
2. It's flexible enough to allow different kinds of entities.
3. Adding a new kind of entity doesn't need to change that entity.
4. We don't need to worry about whether pipeline group admins should be able to automatically change access policy.
5. Reasonably easy to move existing pipeline group level authorization to this model.
6. Most importantly: You could also attach a policy at the level of an auth token, to further reduce the permissions of the auth token. No need to change entities.

One thing to remember: The success or failure of whatever approach we pick will depend on how easy or difficult it is for users to understand it, edit it and figure out what permissions someone has.

For simplicity, I'd suggest allowing a policy only at a role and at auth token. Not at user level.

Somewhat unknown but can easily pick a way: Users can be part of multiple roles.

Credit: Much of this is based on discussions with @maheshp

**Comment by bjorn-spire** [comment]
Any movement on this one? :) 

Like many others in this thread, I'm seeing an issue because while my users can create a new pipeline they can't get any agents to run them unless a global admin adds them to the environment. Slowing things down since they're now potentially stuck until the next day when an admin is awake and back at work.

**Comment by adityasood** [comment]
Policy to be inlined at a Role level:

```xml
<role name="config-repo-admins">
    <policy>
        <allow action="create" type="configRepo"/>
        <allow action="view" type="configRepo">*</allow>
        <allow action="edit" type="configRepo">*</allow>
        <allow action="delete" type="configRepo">*</allow>
    </policy>
    <users>
        <user>foo</user>
        <user>bar</user>
    </users>
</role>
```
With the above policy all users belonging to the role config-repo-admins will be able to create, view, edit and delete any ConfigRepo.

Pros for allowing policies inside roles:

1. Allowing policy definition inside a role would allow for a better user experience
2. We will be allowing for a policy definition on the roles page and reduce too and fro
3. A holistic view on the roles page.

Cons:

1. Might cause duplication (We can maybe allow for a clone of a policy to ease this)

Questions:

What happens if a user belongs to more than one role?

For e.g

```xml
<role name="config-repo-admins">
    <policy>
        <allow action="view" type="configRepo">*</allow>
    </policy>
    <users>
        <user>foo</user>
        <user>bar</user>
    </users>
</role>
```

```xml
<role name="config-repo-admins">
    <policy>
        <deny action="view" type="configRepo">abc*</allow>
    </policy>
    <users>
        <user>foo</user>
    </users>
</role>
```

For user “foo” what should we consider?

We are currently thinking of a restrictive model wherein in the above example, the user foo will not be able to view any config-repos which match the pattern abc*

@arvindsv @maheshp

**Comment by adityasood** [comment]
closing this, next steps to be followed at https://github.com/gocd/gocd/issues/7222

**Comment by adityasood** [comment]
@bjorn-spire we have made some progress on this and are documenting the approach and changes [here](https://github.com/gocd/gocd/issues/7222). It would be great to know what you think about it and if you have any feedback/suggestions for us.
