### ISSUE TITLE
After fetching external artifact, console logs do not show correct color

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#4736]
##### Issue Type
- Bug Report

##### Summary
On fetching an external artifact, the console logs continue to show the "In progress" color. It should show the "completed" color after the job is completed.

##### Code snippets/Screenshots
![screen shot 2018-05-14 at 14 08 48](https://user-images.githubusercontent.com/6024038/39986892-adfea726-5780-11e8-93fa-4ee0666d2b94.png)

**Comment by varshavaradarajan** [comment]
@akshaydewan - it should also not show 2 expandable sections for the task and the progress of the pull. The section beginning with `Pulling docker image...` should be part of the task.

**Comment by arvindsv** [comment]
@marques-work knows a lot about this. In case you need help.
