### ISSUE TITLE
secure variables are not masked in task plugins

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#4737]
##### Issue Type
- Bug Report
##### Summary
Secure variables are not masked in task plugins.
###### Basic environment details

* Go Version: 18.5.0 and 18.4.0
* JAVA Version: Java8
* OS: Mac and Linux

##### Steps to Reproduce

1. Start a GoCD server
2. Configure a pipeline to use a task plugin ( tested with groovy plugin and script executor plugin) and add a secure variable to the job and pipeline
3. Echo or use printenv to print the values of secure variables on the GoCD UI job console
4. The values are not masked

##### Expected Results
The secure variables should be masked as they are masked when using the "More" task command in GoCD 

##### Actual Results
The secure variable values are visible on the job console

##### Possible Fix
mask the secure variable values

<img width="1146" alt="screen shot 2018-05-11 at 11 17 20" src="https://user-images.githubusercontent.com/17826464/39991151-39a8c2ba-578c-11e8-8ad1-72a3e6171813.png">
<img width="1348" alt="screen shot 2018-05-14 at 3 28 07 pm" src="https://user-images.githubusercontent.com/17826464/39991172-4244ace0-578c-11e8-9554-91b29d1077e0.png">

**Comment by rajiesh** [comment]
verified on 18.6.0 (6883-1013a67ccf0cda9c87e6361286708b584be42338)
