### ISSUE TITLE
Secure environment variable are auto-filled with user credentials on edit to env variables

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#4744]
##### Issue Type
- Bug Report

Whenever auto-fill for user credentials in enabled in a browser and user tries to edit environment variables, the secure environment is auto-filled with logged in user credentials. A subsequent save errors out with an error of duplicate environment variable.

###### Basic environment details

* Go Version: 18.5.0
* JAVA Version: Java8
* OS: Mac, windows
* Browser vendor and version (if relevant): Firefox (60.0 (64-bit)), firefox(53.0.2 (32-Bit)), Chrome Version 66.0.3359.139 (Official Build) (64-bit)

##### Steps to Reproduce

1.  Start a fresh browser window and check your browser settings for auto-fill form data enabled.
2. Have some authentication enabled for your GoCD server. 
3. Login to GoCD and let the browser save user credentials
4. Create a pipeline and edit environment variables.
5. You should see your user credentials as secure variables
6. Trying saving the edited env variables

##### Expected Results
The secure variables should not be auto-filled with user credentials

##### Actual Results
The secure variables should are auto-filled with user credentials

<img width="1435" alt="screen shot 2018-05-16 at 11 48 06 am" src="https://user-images.githubusercontent.com/17826464/40100055-38785b74-5900-11e8-952d-b5bd8f703c01.png">
<img width="1440" alt="screen shot 2018-05-16 at 11 47 12 am" src="https://user-images.githubusercontent.com/17826464/40100056-38ad0342-5900-11e8-8e9f-09f4b199ccb2.png">

**Comment by arvindsv** [comment]
Ugh. Browsers. Wonder if we need to do something like [this](https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c106). Anyway, will wait for @adityasood to try this out with some local pages to understand this behavior better.

**Comment by adityasood** [comment]
I tested this with some local pages. The browsers seem to autofill the password and corresponding texts field if you have any credentials saved for a domain. They seem to override the "autocomplete=off" property.

This looks like a browser specific change as stated in a few conversations [here](https://bugs.chromium.org/p/chromium/issues/detail?id=468153#c106). 

Currently trying some workarounds.

**Comment by adityasood** [comment]
Currently came across the following workaround

`<input type="password" name="password" autocomplete="new-password">`

Now when Chrome attempts to autocomplete the field it will not auto-fill this field with a password. This worked for me on Chrome version Version 66.0.3359.181 (Official Build) (64-bit) and Firefox 60.0.1 (64-bit).

Since this is a browser tag attribute, this can change, will look at some other industry used workarounds.

**Comment by maheshp** [comment]
I spent sometime on this, there doesn't seem to be a standard way of turning off autocomplete  across all browsers. Each browser seems to define a different way of doing it. Not fixing this for.

**Comment by ProcessMaster** [comment]
Is there any solution to this issue now?

**Comment by capeflynn** [comment]
Are there any plans to fix this issue?

**Comment by arvindsv** [comment]
No. There are comments above where people have tried to fix it / look into it. Nothing seems to work across browsers. PRs are welcome.

**Comment by akshaydewan** [comment]
IMO, `autocomplete="new-password"` seems to be the best compromise right now. It's [supported](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Browser_compatibility) on Chrome and Firefox since the last few major versions. And although not documented, it worked on Safari 12.1.2 as well.

I can send a PR if y'all agree.

**Comment by arvindsv** [comment]
@akshaydewan I think anything that works is worth putting there. This behavior can be irritating, I'm sure.

**Comment by brendanheywood** [comment]
Can this please be reopened, and can @akshaydewan can you please put together that pr? This seems like a low hanging fruit and its a really annoying bug when people inadvertently change secrets, even the thought that it can happen erodes trust in the system

This is well documented:

https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

**Comment by arvindsv** [comment]
@brendanheywood This whole page has been rewritten in GoCD 20.4.0, and maybe this is not a problem any more. Not sure. I'm happy to reopen it if someone takes a look and sees if it's still an issue.

If it's still an issue, maybe someone can submit a PR. It might not be @akshaydewan, since he's no longer working on GoCD.

**Comment by akshaydewan** [comment]
😢

**Comment by arvindsv** [comment]
@akshaydewan :) It's still open-source ...
