### ISSUE TITLE
User Preferences cannot be edited when using Microsoft Edge browser

### ISSUE THREAD

**Issue by MarcKamradt** [gocd/gocd#4746]
##### Issue Type

- Bug Report

##### Summary

User Preferences cannot be edited when using Microsoft Edge browser.

##### Environment

Fresh Windows 10 Pro installation only used for Go Server and 1 Agent. A second agents connects from a different machine.

###### Basic environment details

* Go Version: 18.3.0 (6540-1e79bb6dc4f01f6ccd71c2b5aa0fbefa0b3eb92d)
* JAVA Version: 1.8.0_102
* OS: Windows 10 10.0
* Browser vendor and version (if relevant): Microsoft Edge 42.17134.1.0

##### Steps to Reproduce

1. Start Edge
2. Log into Go Server with user added from password-file (was done on localhost)
3. Go to [Username] -> Preferences
4. Notice that you cannot edit your preferences (they are not shown at all)
5. Repeat the above with Google Chrome and notice that your preferences are shown

##### Expected Results

User preferences should be shown and be editable when using Microsoft Edge as browser.

##### Actual Results
User preferences are not shown and cannot be edited.

**Comment by bdpiparva** [comment]
@MarcKamradt - Thank for the bug report. The issue is reproducible on edge. 
@naveenbhaskar - Please can you investigate the issue?

**Comment by rajiesh** [comment]
Verified on 18.6.0 (6883-1013a67ccf0cda9c87e6361286708b584be42338)
