### ISSUE TITLE
Publish External Artifact Config View

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4752]
This is a placeholder issue for the publish artifact config views

**Comment by naveenbhaskar** [comment]
![image](https://user-images.githubusercontent.com/1627961/40227026-fb07a450-5aaa-11e8-95c6-09d72864779f.png)

![image](https://user-images.githubusercontent.com/1627961/40227194-6f748204-5aab-11e8-8825-dbef9b6b4fe9.png)

if the value of store ID is a parameter, it automatically fetches the plugin id , show the value in the box below and load the form based on it.
![image](https://user-images.githubusercontent.com/1627961/40227760-026c9352-5aad-11e8-841c-1f3a37a8a328.png)

**Comment by naveenbhaskar** [comment]
update:

- moved add type to the bottom so that user doesnt have to scroll always to add new type.
- separated plugin id with other form fields , since its not a part of the view.

![image](https://user-images.githubusercontent.com/1627961/40410746-20b50802-5e8c-11e8-9c97-68c3b7604875.png)
