### ISSUE TITLE
Global agent pre/post job scripts

### ISSUE THREAD

**Issue by dziemba** [gocd/gocd#4753]
##### Issue Type

- Feature proposal

##### Summary

For a large GoCD setup it would make sense to have globally defined commands than run on agents before and/or after each job execution. This is useful for cleaning up global state, i.e. docker containers, leftover forked processes etc.

###### Basic environment details

* Go Version: 18.5.0
* OS: Linux

##### Expected Results

When running jobs that change global state of the agent, i.e. docker containers, forked processes, temporary files, I want to be able to define a global cleanup script or command that runs before and/or after each job execution. This script can then take care of cleaning up leftover resources/processes/files/containers.

##### Actual Results

This functionality is not available at the moment. Right now we have > 500 pipelines where each job definition starts with a "remove-containers" task that cleans up leftover docker containers. This works, but is hard to maintain and very verbose.

##### Possible Fix

Allow a custom script to be executed on the agents before and after each job. Could be passed in as a configuration setting to the Go agents (i.e. via `/etc/default/go-agent`), which is probably the easiest solution. Setting this in the global XML config is also fine.

**Comment by arvindsv** [comment]
@dziemba I can see why you want this, since you have so many pipelines. However, it feels like an anti-pattern to me. Apart from encouraging sloppiness ("something will clean it up anyway"), it feels like the cleanup happens too far from what made the "mess" in the first place.

Have you considered tasks whose "Run If Condition" is set to "Any"? Or even "Failure", so that the run after failures and clean up?

**Comment by dziemba** [comment]
Yes, we have considered this. It works as expected, but it adds a lot of boilerplate to our pipeline definitions. 

We have > 500 pipelines, with around 10 tasks per pipeline, and pipelines are maintained by the teams that own the services. This basically means that we have to change thousands of places where we now just do:
```xml
 <tasks>
  <exec command="make">
    <arg>compile</arg>
  </exec>
</tasks>
```

into at least:

```xml
 <tasks>
  <exec command="remove-containers" />
  <exec command="make">
    <arg>compile</arg>
  </exec>
  <exec command="remove-containers">
    <runif status="any" />
  </exec>
</tasks>
```
            
I can see how the global cleanup idea might be considered an anti-pattern, but it would be very useful for our use-case. 

If this can't be implemented in core GoCD, maybe it could be a plugin? How difficult would that be?

**Comment by arvindsv** [comment]
@dziemba It should be easy enough to write a task plugin, but it won't help a lot in reducing the *volume* of configuration. What you pasted up there will be replaced by (possibly):

```xml
<task>
  <pluginConfiguration id="magic-cleaner-plugin" version="1" />
  <configuration>
    <property>
      <key>command</key>
      <value>make compile</value>
    </property>
  </configuration>
</task>
```

[Here are the docs](https://plugin-api.gocd.org/current/tasks/#task-plugins) about the task extension. A working plugin which people use is [this](https://github.com/gocd-contrib/script-executor-task).

You might also want to consider [pipelines as code](https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html).

**Comment by dziemba** [comment]
@arvindsv Ah yes, a task plugin would work but not actually provide much benefit. I was rather thinking about a "global" plugin, either hooking in on the agents directly or somehow modifying the task-list on-the-fly. Is that something that could be implemented with reasonable effort?

Pipelines as code is a very cool feature, we're definitely looking into that. Still doesn't solve the problem though unfortunately.

**Comment by arvindsv** [comment]
@dziemba Not really. There's no extension point to do something like that. Introducing one will not be a reasonable amount of effort. Putting aside the fact that the extension point is very specific. I'll think about this some more.

**Comment by dziemba** [comment]
Any updates on this? @arvindsv

**Comment by grobie** [comment]
> However, it feels like an anti-pattern to me. Apart from encouraging sloppiness ("something will clean it up anyway"), it feels like the cleanup happens too far from what made the "mess" in the first place.

I see where you're coming from, but I think there are more aspects here. Even if I ensure my own pipeline doesn't leave around any state / artifacts / processes / containers / etc., GoCD still forces me to clean up any possible leftovers from other pipelines not under my control. Having to think about and guard against every possible way how another pipeline can modify state, while a noble goal, requires a lot of time and effort. Other build system like Travis, CircleCI, Drone, etc. ensure every build starts at a deterministic, consistent state, it would be great to have such option in GoCD as well.

**Comment by ketan** [comment]
> Other build system like Travis, CircleCI, Drone, etc. ensure every build starts at a deterministic, consistent state, it would be great to have such option in GoCD as well.

They containerise your builds using docker or something similar. See the [docker elastic agent plugin](https://github.com/gocd-contrib/docker-swarm-elastic-agents) for doing just that.

**Comment by arvindsv** [comment]
Yes. That's what I was about to say. They (Travis, CircleCI, etc) do that by throwing away the environment after a build. I feel that it's a nice and sane way of cleaning up. Any kind of pre- and post- hooks will have the possibility of leaving behind some mess. As I said earlier, I understand the desire, but if using docker elastic agents is a possibility for you, I'd highly recommend using them. Or, the Kubernetes elastic agents (see [helm chart](https://github.com/kubernetes/charts/blob/master/stable/gocd/README.md) or the [elastic agent itself](https://github.com/gocd/kubernetes-elastic-agents)).

**Comment by dziemba** [comment]
We already run most of our builds in docker containers. We then use docker-compose to spin up daemonized dependencies (i.e. mysql, memcached). The problem now is that there is no good way to ensure that there are no running docker containers left over from previous builds (of potentially other pipelines). Containerizing the whole container setup does not work well (there is docker-in-docker, but that's not really meant for production use).
