### ISSUE TITLE
Provide an option to sort by duration on the job run history page

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4756]
##### Issue Type

- Feature enhancement

##### Summary

For all static agents, the job run history page provides some tabular data about the job and duration. Provide an option to sort the jobs based on the duration of the jobs.

https://build.gocd.org/go/agents/b9a506d0-1443-40ab-81a0-225c13c453a3/job_run_history

**Comment by neoprez** [comment]
This url gives me a 403. Cant really understand the ask given that I can't view the url. Any instructions?

**Comment by varshavaradarajan** [comment]
@neoprez - you need to have admin permissions to access the above URL. Sorry. 
If you are trying to contribute for hacktoberfest, I suggest you bring up your own GoCD setup - a GoCD server and a GoCD agent to reproduce this and then work on this issue.

https://developer.gocd.org/ gives you information on how to setup your dev environment.

**Comment by neoprez** [comment]
I’ll install it on my local. This is for Hacktoberfest  

Best,
Rodny Perez

**Comment by neoprez** [comment]
Please see:

https://github.com/gocd/gocd/pull/7069

**Comment by GaneshSPatil** [comment]
Done as part of https://github.com/gocd/gocd/pull/7069 in GoCD release v19.10.0
