### ISSUE TITLE
Configuring go agent using rest api returns Payload data is not valid json

### ISSUE THREAD

**Issue by danielmclaugh** [gocd/gocd#4765]
Hi peoples,
    We are trying to use the bulk update agents rest api for GOCD v18.3.0 and it doesn't seem to work. See the powershell script below:

$payload = @{
        agent_config_state = 'disabled'
        uuids = '9938716c-7c21-4782-adc0-0301dcda8564', '24e9c92f-85e3-4842-9713-8a8a0070b547'
        operations = @{
            environments = @{}
            resources    = @{}
        }
    } | ConvertTo-Json'       
    
curl.exe -k --insecure 'https://xxxxxxxxxxxx.com:8154/go/api/agents' -u 'username:password' -H 'Accept: application/vnd.go.cd.v4+json' -H 'Content-Type: application/json' -X PATCH -d $payload

Here is the response:
{"error":"Payload data is not valid JSON. Error message: unexpected token at '{\r\n  agent_config_state: disabled,\r\n  uuids: [\r\n    9938716c-7c21-4782-adc0-0301dcda8564,\r\n    24e9c92f-85e3-4842-9713-8a8a0070b547\r\n  ],\r\n  operations: {\r\n    environments: {\r\n      \n    },\r\n    resources: {\r\n      \n    }\r\n  }\r\n}'"}

Any help would be greatly appreciated

**Comment by ankitsri11** [comment]
Hi Daniel - It looks like  the convert (ConvertTo-Json) is making it a string with JSON in it. With newlines as “\n” etc. Which is not a valid JSON for GoCD.

However, I tried with Invoke-WebRequest method in my script and it worked.

```
$payload = @"
{
"uuids":
[ "de98298a-ed7e-46e3-8294-9e3e8dcc544f",
 "bee8fe71-5757-4599-99a8-1b650dd71a89"
],
"operations": {
"environments": {
"add": ["QA"]
}
},
"agent_config_state": "enabled"
}
"@

$encodedCreds = [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes("username:password"))
$basicAuthValue = "Basic $encodedCreds"
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Authorization", $basicAuthValue)
$headers.Add('Accept', 'application/vnd.go.cd.v4+json')
$headers.Add('Content-Type', 'application/json')

$response = Invoke-WebRequest 'http://localhost:8153/go/api/agents' -Method Patch -Body $payload -Headers $headers

Write-Host $response
```

**Comment by danielmclaugh** [comment]
Thanks for that. It’s definitely a Microsoft power shell formatting issue. Did the same thing in Linux and worked fine as well as using postman. If I find the right configuration I will update this post

Daniel

**Comment by GaneshSPatil** [comment]
@danielmclaugh -- I am closing this issue as it seems to be with related with the platform. 
Feel free to reopen the issue if it is not the case.
