### ISSUE TITLE
View for Fetch External Artifact

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#4767]
This is to document the changes to External Artifact view.

Current View:
![screen shot 2018-05-22 at 14 18 02](https://user-images.githubusercontent.com/6024038/40351837-fb904f94-5dca-11e8-90f1-bba042948d90.png)

Changes needed:
- An option to indicate whether the artifact is Internal or External
- Add `Artifact ID` textbox for External Artifacts
- If the plugin ID cannot be determined (in case of templates), allow the user to select a plugin ID and render the view.

cc: @naveenbhaskar

**Comment by naveenbhaskar** [comment]
user has to select whether its an external or internal artefact and based on the selection , other form fields will load

![image](https://user-images.githubusercontent.com/1627961/40356489-ce9c2f92-5dd6-11e8-820b-2359223bb848.png)

**Comment by varshavaradarajan** [comment]
@naveenbhaskar - Thank you. Do you remember us discussing that the plugin id is a secondary input that needs to be provided only in certain cases? That's why for publish, we chose to have the plugin id in a separate line. Can we do something similar here as well? 

![](https://user-images.githubusercontent.com/1627961/40227760-026c9352-5aad-11e8-841c-1f3a37a8a328.png)

**Comment by naveenbhaskar** [comment]
updated view

![image](https://user-images.githubusercontent.com/1627961/40412725-bb1347c4-5e91-11e8-8638-d5bd50d7ffe6.png)

**Comment by varshavaradarajan** [comment]
@naveenbhaskar - one more thing, there is the config for run_if and on cancel that should also be shown. Earlier in the normal fetch form, they were at the bottom. Should these 2 options appear after the plugin form for fetch external artifacts?

**Comment by naveenbhaskar** [comment]
yes... after the plugin form

**Comment by varshavaradarajan** [comment]
And, @naveenbhaskar - we chose the radio options to be `gocd` and `external`. So that it will read like fetch artifact from gocd or an external store.

**Comment by naveenbhaskar** [comment]
yes .. make sense

**Comment by rajiesh** [comment]
Verified on 18.7.0 (7117-1709149e6946f9cec95e4a8e914a47c7806f0672)
