### ISSUE TITLE
Allow javascript to be executed in the plugin settings modal

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4797]
##### Issue Type

- Bug Report

##### Summary

On the old plugins page, we had explicitly rendered the modal contents without escaping (https://github.com/gocd/gocd/pull/4226/files#diff-768a61bc4d59d2c699d5f45a6da3dd03L15). This meant that any script that was present in the plugin view template could be executed. After upgrading the mithril 1.1.6, this behaviour was broken even though we use `m.trust` for rendering the plugin view template.  This is due to a breaking change introduced when we moved from mithril 0.2.3 to 1.1.6. It is being followed in https://github.com/MithrilJS/mithril.js/issues/2168. Once there is a resolution upstream, we can upgrade.

###### Basic environment details

* Go Version: `18.5.0`
* Browser vendor and version (if relevant): `Google Chrome 66.0.3359.139, Firefox 59.0.2`

##### Steps to Reproduce

1. Refer to https://github.com/MithrilJS/mithril.js/issues/2168 

@GaneshSPatil , @arvindsv - please add/edit this if I have missed any details. Thank you.

**Comment by arvindsv** [comment]
@GaneshSPatil At some point soon, we should see if [this workaround](https://github.com/MithrilJS/mithril.js/issues/2168#issuecomment-434457083) works ...

/cc @maheshp

**Comment by adityasood** [comment]
fixed by #5361
