### ISSUE TITLE
Param Error Shown Multiple times - once for each pipeline not
defining the parameter

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#48]
### Steps to reproduce
- Define a new pipeline template.
- Create 4 pipelines using the template.
- Go to task of the Pipeline and use parameter in argument.
- Click on Save.
#### **Expected result**
- Error should be shown only once.
#### **Current result**
- Error shown 4 times.
  
  ![dependent_build](https://cloud.githubusercontent.com/assets/1577718/2716569/7edc02e8-c52d-11e3-8607-fd1c62fee555.png)

**Comment by arvindsv** [comment]
Closing as stale.
