### ISSUE TITLE
[Rails 4 issue] Error in go-server logs

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#480]
Go-server logs is showing following error -

Java::JavaLang::RuntimeException (Renderer '#<ErbRenderer:0x1ad46fd4>' for type 'erb' is already registered. Cannot register '#<ErbRenderer:0x70f9d50e>' as the renderer):

1bf10a5f18b0d8a029b4fa07395ac27e6051f094 seems to the cause for it. 

Explaination: commit (1bf10a5f18b0d8a029b4fa07395ac27e6051f094) changed the way beans are loaded, i.e., self.get_service which tends to call context on spring.rb which does some mumbo-jumbo with mutex, bean inits and explicitly calling registerRenderer. Anyway, this seems be causing the issue because there is some race-condition with the @@services cache

**Comment by arvindsv** [comment]
Closing. No action.
