### ISSUE TITLE
Artifact reports not showing up in tabs

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4807]
##### Issue Type

- Bug Report

##### Summary

The `FastUnit` tab on build.gocd.org does not render the css/js correctly and shows the following errors:

<img width="1116" alt="screen shot 2018-06-04 at 3 02 41 pm" src="https://user-images.githubusercontent.com/10598/40909901-61e8e58e-6808-11e8-9aea-4dc96f3ba052.png">

Removing the `sandbox="allow-scripts"` attribute on the `<iframe/>` seems to fix the problem.

/cc @varshavaradarajan

**Comment by varshavaradarajan** [comment]
Fixed via https://github.com/gocd/gocd/pull/4829
