### ISSUE TITLE
Better error message when backup is in progress

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#4833]
##### Issue Type

- Bug Report

##### Summary

Currently the dashboard, and other SPAs simply say "There was an unknown error" when a backup is in progress, perhaps the message could mention that a backup is in progress based on the (json) message from the server.

<img width="1130" alt="screen shot 2018-06-07 at 10 32 00 pm" src="https://user-images.githubusercontent.com/10598/41114698-ca83c586-6aa2-11e8-947d-4f95fc1dafb2.png">

**Comment by GaneshSPatil** [comment]
All the SPA's should render a pretty message for backup in progress!
Maybe we can handle it at the `ajax_helper` level or a seperate interceptor for backup_in_progress.

**Comment by GaneshSPatil** [comment]
@gocd/committers -- currently, it's little inconsistent the way we are handling backup in progress error. 
On old pages, if any request fails for backup in progress error, we render the responseHTML as it is. whereas, currently, each SPA has its own way of handling the backup in progress error.

Ideally, we should send enough information along with a 503 response to tell the browser client about application backup in progress (to separate out 503 from nginx and other proxies response) and handle it better on SPAs too.

**Comment by arvindsv** [comment]
@GaneshSPatil @ketan I see that the message is now changed to say: "Server is under maintenance mode. Please try again later", at least on the dashboard and agents pages. So, can this be closed? Or, do we need to keep this open till we get consistency across everything?

**Comment by GaneshSPatil** [comment]
@arvindsv -- can we create an UnderMaintainanceMode component, use it on the new SPAs (plugins and config repo page), so we have only one way of rendering 503. And then close the issue.

\cc: @akshaydewan @ketan

**Comment by arvindsv** [comment]
@GaneshSPatil Your decision. :)

**Comment by GaneshSPatil** [comment]
@gocd/committers -- With the new way of writing SPAs, we've handled showing the appropriate message in case any of the AJAX calls fail, [here](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails/webpack/helpers/api_request_builder.ts#L116-L119).

Closing this issue as the backup-in-progress situation doesn't need to be handled specially for each page.

Verified On: GoCD Version: 19.2.0 (8562-ab441595ee501940d050c10361728a11bbf02648).
