### ISSUE TITLE
Need ability to configure location of pipelines directory on agent

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#484]
Currently the agents use a directory below the path of the executable for the pipeline jobs.

This directory is used to store fetched materials and is the default working directory for the job execution.

On windows the default install path is "C:\Program Files (x86)\Go Agent" which means the pipeline location is "C:\Program Files (x86)\Go Agent\pipelines" .

There are THREE  problems with this location:
1. The path to the pipelines is quite long and since TFS and other .NET based programs have a bug where paths exceeding 260 characters in length do not work, this causes a number of problems when for example downloading materials from TFS.
2. The PROGRAM FILES location is a well known path which is used to store programs however the pipeline folder really contains data, temporary data in fact. If you run the GO Agent a user other than LOCAL SYSTEM or an Administrator then these users do not have write permission to the PROGRAM FILES location and this must be assigned manually.
3. The pipelines folder can take up a very large amount of disk space however it is quite hidden in its current location. System Administrators and users not familiar with GO who are looking to recover disk space are unlikely to consider deleting the contents of this folder even though it is a temporary data folder.

Adding a configuration property to the GO configuration files that allow this directory to be specified for each agent and defaulting it to the TEMP location would resolve these three issues.

**Comment by pmcgrath** [comment]
+1 Having the same issue with running pipelines where file paths are long on Windows systems

**Comment by arvindsv** [comment]
Does the core.longpaths option mentioned [here](https://groups.google.com/d/msg/go-cd/qPAMe9kgvlM/pCoZ4rLmCQAJ) help?

**Comment by efaruk** [comment]
All windows user's have the same problem, please someone!? make that pull request...

**Comment by manojjenago** [comment]
Hi ,

I am getting error "C:\RIT_Build_Process\eBayProject-build.xml:11: Could not create parameter file in default temporary-file directory" .
It seems that GOCD is trying to create files in Temp directory. I changed the System properties to point to the location where I have the access. (TEMP= C:\Temp) .Still it fails.

Is there any way to mention the temp dir for GOCD . Is there any file that can be set for Temp dir??
As "reidca" mentioned creating a configuration property to the GO should solve the issues. Please let me know when I should create it.

Thanks in advance,
Manoj

**Comment by arvindsv** [comment]
Can you provide some more information about where you see this error? In the console log? If so, can you provide some more lines for context. I'm trying to see if it is happening from the GoCD side, or from a custom command.

**Comment by reidca** [comment]
@manojjenago The problem you are seeing may be as a result of the SYSTEM user not having access to its temporary path or that path not existing.

We have seen issues where the folder does not exist and have had to create it manually.

The standard GO agent is 32-bit. If you are running this on a 64 bit system then the TEMP path will be redirected to SysWow64.

Make sure that the following two paths both exist on the machine where you are seeing the error:
"c:\windows\System32\config\systemprofile\AppData\Local"
"c:\windows\sysWOW64\config\systemprofile\AppData\Local"

And grant "NT Authority\SYSTEM" has FULL CONTROL permissions to both of the paths.

Hope that helps

Carl

**Comment by manojjenago** [comment]
Also if you want to change the default location of the TEMP directory then
, please change the Environment variable in your system ( TEMP and TMP).

Also be care-ful sometimes the GOCD looks for the TEMP directory but it is
Java TEMP directory. Please find the them and create the folders if not
created.

In my case there are issues where GOCD complains for the TEMP directory and
Even I change the TEMP dir under Env variable , it did not help. After I
change the TEMP dir of the JAVA and I created the folder manually under the
JAVA temp then it worked. Hope this helps

Thanks,
Manoj

**Comment by arvindsv** [comment]
@rajiesh and others: I’m testing out my changes for this change, and I thought about these scenarios. Can you think of any other obvious ones?

- Custom task pwd should use specified dir on agent side
- Fetch artifact should fetch into specified dir on agent side
- Upload artifact should upload from specified dir on agent side
- Nant task pwd should use specified dir on agent side
- Ant task pwd should use specified dir on agent side
- Rake task pwd should use specified dir on agent side
- Plugin task pwd should use specified dir on agent side
- Build command task pwd should use specified dir (when Java agent is used with build commands rather than RPC)
- Server side flyweight directory should use specified dir (different property for server side)
- Pipeline with perforce material: GO_P4_CLIENT environment variable is dependent on directory name. It should remain the same in the default case (when no new directory is specified)
- All the above cases should work exactly as it does today, when no override is specified.
- Agent status: "Free Space" should get free space of newly specified agent work dir.

**Comment by arvindsv** [comment]
From @rajiesh: Agent sandbox directory (shown on the agents page) should also show this path.

**Comment by timnielsen** [comment]
Hi,

Any plans on getting this into a release anytime soon? 
We have a very large and deep codebase structure, with many files causing path names of 200+ characters, the longest is 233. I'm currently testing GO CD, and it looks very promising, as it can automate many of our processes. However, the missing configurability of workingdir for both agent and server, combined with current naming (pipelines\flyweight\<GUID>) is preventing us from using GO CD completely. Renaming 1000+ files in our codebase is unfortunately not an option at this time.
