### ISSUE TITLE
Publish external artifact config id cannot be a parameter currently

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4876]
##### Issue Type

- Bug Report

##### Summary

The xsd restricts the pluggable artifact config id from being a parameter.  If the publish config is at a template level, then, the id could be provided as a parameter. 
 Since the artifact id at the publish level is only for checking uniqueness within a job, its okay if we restrict this to not be a parameter. 

WDYT @jyotisingh, @maheshp, @bdpiparva ?
 
To do (if we decide to allow id to be a parameter):
- xsd migration to change the type from `nameType` to `xsd:string`
- remove the name type validator check on PluggableArtifactConfig on `id`

**Comment by bdpiparva** [comment]
@varshavaradarajan -- I don't see any strong reason to parameterized artifact id. Artifact id will be always unique for the job. I think it is fine to keep the behavior as it is for publishing artifact.

**Comment by varshavaradarajan** [comment]
Agreed.
