### ISSUE TITLE
Pipelines defined in config repo does not allow multiple values for task's run_if attribute

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4890]
##### Issue Type

- Bug Report

##### Summary
Pipelines defined in config repository can not specify multiple values for run_if task attribute.
A task's run_if attribute can have values: 
- "passed"
- "failed"
- "passed", "failed"
- "any"

Currently, one can specify run_if value in string, but it needs to be an array.

**Comment by tomzo** [comment]
> Currently, one can specify run_if value in string, but it needs to be an array.

But why it needs to be an array? 
`"passed", "failed"` gets the same result as `any`.

**Comment by arvindsv** [comment]
@tomzo I agree. It looks like "any" should be equivalent to "passed, failed".

@GaneshSPatil Isn't that right?

**Comment by varshavaradarajan** [comment]
@arvindsv - Wouldn’t ‘any’ in run if config include cancelled?

**Comment by arvindsv** [comment]
@varshavaradarajan Hmm. Maybe.
