### ISSUE TITLE
No proper error msg is shown when a user's operate permission is
removed from pipeline group when that user has also been given stage
operate permission

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#49]
## 
### Steps to reproduce
1.  Give user1 and user2 operate permissions to pipeline group PG1
2.  Give user1 stage operate permission forpipeline P1 in PG1
3.  Try to remove operate permissions of user1 from PG1
#### Expected result

This should not be allowed and a proper error message should be given for that
#### **Current result**

It just says Save failed, see errors below but does not show any error

**Comment by kritika-singh3** [comment]
Can still be reproduced:

1. Give user1 and user2 operate permissions to pipeline group PG1
2. Give user1 stage operate permission for a pipeline P1 in PG1
3. Go to pipeline group edit on Pipelines page and remove the operate permission (or remove the user).

#### Expected Result

Error should be thrown as the user is still present on as a stage operate user in a pipeline P1

#### Actual Result

The updated authorization for the pipeline group gets saved. But any further update call to the pipeline P1 fails. 
The cruise-config is rendered invalid (try to save the config without changes or restart the server - it won't come up).
