### ISSUE TITLE
Cannot access the stage details page from VSM

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4909]
##### Issue Type

- Bug Report

##### Summary

If the stage is in state `Failing`, then we cannot click on the stage bar and go to the stage details page.
If the stage state is passed, failed, or building, then the stage bar can be clicked and we can access the stage details page.

###### Basic environment details

* Go Version: `18.7.0-6690`

##### Steps to Reproduce

1. Go to build.gocd.org 
2. Click on the VSM for any `failing` pipeline
3. Try to access the stage details page by clicking on the stage bar

##### Expected Results

Should be able to access the stage details page.

##### Actual Results

Nothing happens.

There is no error on the browser console.

**Comment by GaneshSPatil** [comment]
Verified on:  Go Version: 18.7.0 (7080-088d0a9fe3c12c93300a48e9e80e0afb61e43b66).
