### ISSUE TITLE
Get rid of historical data from the job related tables 

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#4917]
##### Issue Type
- Tech debt
##### Summary

@ketan had worked on removing data from the following tables after a specific job is completed. (https://github.com/gocd/gocd/pull/2875)  We should delete the data that has been retained for previous job runs.

- artifactplans
- environmentvariables
- artifactpropertiesgenerator
- resources
- jobagent metadata

**Comment by varshavaradarajan** [comment]
@ketan - Can the drain mode be used to do this? We had seen that the delete on pg for a huge table was taking 52s (after many query rewrites) and so avoided doing it at startup.

**Comment by ketan** [comment]
IIRC, one of the reasons we decided not to do it in any post-startup scenario (like drain mode, in this case) was in-memory caches which may possibly hold references to one of these objects which gets dropped from the DB. If we don't hold any of this information in memory today, there's still no guarantee that it may continue to do so in a later version.

I'd think the simplest thing would be drop this at startup, even if it takes a bit longer to startup. @arvindsv has put in a server starting banner page which tells the user that the server is booting up, perhaps we could use that to convey what the server is doing (as long as it's not something sensitive).

**Comment by varshavaradarajan** [comment]
> was in-memory caches which may possibly hold references to one of these objects which gets dropped from the DB. 

Can't the cache be updated when the data is deleted? Like now, when a job completes and all corresponding entries are removed from the table because of https://github.com/gocd/gocd/pull/2875/files#diff-9843073d619f1e9587f4ac8bf8576dddR373 for example. 

> If we don't hold any of this information in memory today, there's still no guarantee that it may continue to do so in a later version.

_If_ that happens, you'll anyway have to deal with the data deleted after completion of every job since #2875 got merged, right? This is historical data about jobs that were completed before #2875 got merged if I understand #2875 correctly. 

I was thinking about providing Go admins some option on the drain mode SPA to run this purging after displaying the amount of rows in each table to delete. It can be their decision.

**Comment by arvindsv** [comment]
Is done in https://www.gocd.org/releases/#19-10-0 . Closing.

**Comment by arvindsv** [comment]
cc: @varshavaradarajan @ketan
