### ISSUE TITLE
Analytics Plugin doesn't works for GoCD windows instance

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#4923]
##### Issue Type

- Bug Report

##### Summary
Windows GoCD server fails to load any analytics chart to the path issue.
This issue is while creating an URI from a file path. The system-dependent default name-separator character needs to be used instead of hardcoding it to `/`.
On UNIX systems `/`, whereas, on windows systems `\\` is used as name-separator character.

Go Server Log:
```
2018-07-05 15:55:48,037 ERROR [qtp1697511312-49] AnalyticsDelegate:106 - Encountered error while fetching analytics 
java.lang.IllegalArgumentException: Illegal character in path at index 6: assets\plugins\com.thoughtworks.gocd.analytics\B31EA0A3366304AFA5C012D7250339F125C132BC6DA9599541318B40982EEB90/agent-with-highest-utilization-chart.html
```

###### Basic environment details

* Go Version: `v18.6.0`
* Plugin Version: `1.0.0-683`

##### Expected Results
GoCD Server should load all the analytics charts on windows operating systems.

##### Actual Results
GoCD Server fails to load all the analytics charts on windows operating systems.

##### Possible Fix
Replace [`/`](https://github.com/gocd/gocd/blob/master/plugin-infra/go-plugin-domain/src/main/java/com/thoughtworks/go/plugin/domain/analytics/AnalyticsData.java#L46) with the operating specific name sepearator character.
Use [`File.separator`](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#separator) which is returns system-dependent default name-separator character.

**Comment by rajiesh** [comment]
Verified on 18.7.0 (7107-ca37138fb0de89afb2f607cb57de22478550f8ac
