### ISSUE TITLE
Optional upstream dependencies

### ISSUE THREAD

**Issue by Stono** [gocd/gocd#4931]
Hola folks!
We have a dependency that we *do not* want to trigger all of the downstream pipelines, but we do want it to pull that dependency when the downstream pipelines trigger of their own accord.

If you look at this screenshot, we want:

  - platform-helm-at-service *not* to trigger docker.mercury-admin-tool (and the other apps)
  - docker.mercury-admin-tool to only trigger of their git repo, and when doing so, will consume the latest upstream of platform-helm-at-service

<img width="1067" alt="screen shot 2018-07-09 at 19 13 42" src="https://user-images.githubusercontent.com/1486729/42468262-463559ca-83ac-11e8-8174-c02c6d999d12.png">

So basically, it's like "configurable upstream material triggers", we want to control which materials cause a pipeline to build.

Is there any way to do this, or is this a feature request we could get in?

**Comment by Stono** [comment]
ping.... I can't tell you how valuable this feature would be.  Deterministic yet not auto-triggering upstream dependencies

**Comment by remy-tiitre** [comment]
Yeah, same here. With docker image build flow its really problematic, when your base images (os, java etc) trigger new builds. For example, when you are a Java house and you update your Java base images it could start building all your applications at the same time. (Sometimes this might be something you want - if java has some serious security vulnerability for example). But in most cases it would be fine when application plan picks up the new version when they release new version of the app. Yet, I would still want to have VSM support to see what plans have used the latest version or any previous versions.

**Comment by Stono** [comment]
Exactly!

**Comment by akshaydewan** [comment]
The most straightforward way I can think of is to add an option at the material level to toggle whether the pipeline should be triggered when a new revision is available. 
For e.g.
```
      <materials>
        <git url="https://github.com/gocd/ruby-functional-tests" shallowClone="true"/>
        <pipeline pipelineName="installers" stageName="docker" materialName="docker-images" triggerOnNewRevision="false" />
      </materials>
```
The `triggerOnNewRevision` (or whatever we choose to call it) attribute can be set to false.


From a UX point of view, we have a lot of options that determine whether a pipeline will be triggered:
- On the pipeline level, we have "Automatic Pipeline Scheduling"
- Making the first stage manual is the same as above
- A timer can be specified, which can optionally trigger only when new material is available.
- On the material level, we have an option to "Poll for new changes". My understanding is that this relates to server-side polling (MDU), but it can have implications on whether the build is automatically triggered too.

As a user, this might make things a bit complex and bring in uncertainty about when a build is or isn't triggered. We should probably take a look at the UX in #6362

**Comment by arvindsv** [comment]
The flag being at the dependency level makes sense to me.

**Comment by rajiesh** [comment]
Verified on 19.10.0 (10333-9cb3d874fca187b08d7661c8fd3f11a9b9e9696d)
