### ISSUE TITLE
Go Agent is unable to fetch my new git repo changes

### ISSUE THREAD

**Issue by shru9289** [gocd/gocd#4932]
##### New git repo changes are not picked up by my Go Agent , i see the file present in my repo but that file is added in my local Go agent git repo.

- Bug Report

##### Summary

I have a git repo which contains all my new file changes and couple of new files added in it.

When i goto my pipeline and run the job, it cannot find the new files in Go Agent/pipelines/Unitests/start.sh No file or directory. I can see that my local repo is not updated.

How do i go about this issue? Please help

**Comment by ankitsri11** [comment]
@shru9289 - Where did you add those new files? Did you committed those files under git repo?
Can you make sure these are not part of blacklisted files as mentioned here - https://docs.gocd.org/current/configuration/admin_add_material.html#blacklist

**Comment by shru9289** [comment]
Hi,
Yeah it worked..I could figure out the issue. Thank you for following up. I
will come to you with new issue which I'm currently facing.



Regards
Shruthi
