### ISSUE TITLE
Configure admin users via API

### ISSUE THREAD

**Issue by dziemba** [gocd/gocd#4936]
##### Issue Type

- Feature proposal

##### Summary

I would like to configure the list of users with admin privileges via an API endpoint.

##### Expected Results
Have an endpoint to add or remove users from the list of system-wide admins. Or extend the user-CRUD endpoints to include a flag that represents admin privileges.

##### Actual Results
No API endpoint available, only configurable through editing the XML config.

**Comment by anisharoofiTW** [comment]
We are planning to implement a Admin API  which will have three endpoints

1. Get all Users and Roles
2.Add List of User and Roles
3.Remove List of User and Roles

1. Get all users and roles : This endpoint will fetch the list of user and roles as response which have admin privileges.

2. Add List of Users and Roles : This endpoint will accept a list of user names and role names validate it and add them to the Config XML under admins tag.

3. Remove List of Users and Roles : This endpoint will accept a list of user names and role names and if present under admins tag in Config XML will remove them.

**Comment by maheshp** [comment]
@anisharoofiTW can you please provide more details of the API, specifying the URL and the structure of the JSON would help.

**Comment by anisharoofiTW** [comment]
The URL and structure of the JSON for each endpoint will be as follows:


1.Get all users and roles

GET /go/api/admins
curl 'https://ci.example.com/go/api/admin' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v2+json'
will fetch the response
{
    "_links": {
        "self": {
            "href": "https://ci.example.com/go/api/admins"
        },
        "doc": {
            "href": "https://api.gocd.org/#admins"
        }
    },
    "roles": [
        "role_1",
        "role_2"
    ],
    "users": [
        "user_1",
        "user_2"
    ]
}


2.Add List of Users and Roles : 
POST /go/api/admins
curl 'https://ci.example.com/go/api/amins' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v2+json' \
      -H 'Content-Type: application/json' \
      -X POST \
      -d '{
             "roles": [
 	             "role_1",
 	              "role_2"
              ],
              "users": [
 	             "user_1",
 	             "user_2"
               ]
          }'
will fetch the response
{
    "_links": {
        "self": {
            "href": "https://ci.example.com/go/api/admins"
        },
        "doc": {
            "href": "https://api.gocd.org/#admins"
        }
    },
    "roles": [
        "role_1",
        "role_2"
    ],
    "users": [
        "user_1",
        "user_2"
    ]
}

3.Remove List of Users and Roles : 
DELETE /go/api/admins

curl 'https://ci.example.com/go/api/admins' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v4+json' \
      -H 'Content-Type: application/json' \
      -X DELETE \
      -d '{
             "roles": [
 	             "role_1",
 	              "role_2"
              ],
              "users": [
 	             "user_1",
 	             "user_2"
               ]
          }'
Will fetch a Response

HTTP/1.1 200 OK
Content-Type: application/vnd.go.cd.v2+json; charset=utf-8
{
  "message": "Users '[\"user_1\", \"user_2\"]' were deleted successfully.Roles '[\"role_1\", \"role_2\"]' were deleted successfully."
}

Please let me know your views.

**Comment by anisharoofiTW** [comment]
As Per discussion , the following editions in the API.

1.Get all users and roles

GET /go/api/admins
curl 'https://ci.example.com/go/api/admin' 
-u 'username:password' 
-H 'Accept: application/vnd.go.cd.v2+json'
will fetch the response

```
{
"_links": {
"self": {
"href": "https://ci.example.com/go/api/admins"
},
"doc": {
"href": "https://api.gocd.org/#admins"
}
},
"roles": [
"role_1",
"role_2"
],
"users": [
"user_1",
"user_2"
]
}
```

2.Put List of Users and Roles :
POST /go/api/admins
curl 'https://ci.example.com/go/api/amins' 
-u 'username:password' 
-H 'Accept: application/vnd.go.cd.v2+json' 
-H 'Content-Type: application/json' 
-X PUT 
-d '{
"roles": [
"role_1",
"role_2"
],
"users": [
"user_1",
"user_2"
]
}'
will fetch the response
{
"_links": {
"self": {
"href": "https://ci.example.com/go/api/admins"
},
"doc": {
"href": "https://api.gocd.org/#admins"
}
},
"roles": [
"role_1",
"role_2"
],
"users": [
"user_1",
"user_2"
]
}

3.BULK EDIT :
PATCH /go/api/admins

curl 'https://ci.example.com/go/api/admins' 
-u 'username:password' 
-H 'Accept: application/vnd.go.cd.v4+json' 
-H 'Content-Type: application/json' 
-X PATCH 
-d '{
"roles": {
                "add": ["role1", "role2"],
                "remove": ["role3"]
              },
              "users": {
                "add": ["user1", "user2"],
                "remove": ["user3"]
              }
}'
Will fetch a Response

HTTP/1.1 200 OK
Content-Type: application/vnd.go.cd.v2+json; charset=utf-8
{
"message": "Updated Admins successfully."
}

**Comment by ketan** [comment]
LGTM. The only suggestion I have is that the PATCH call returns the final object state, instead of the message.

**Comment by maheshp** [comment]
Done as part of https://github.com/gocd/gocd/pull/5009.

**Comment by rajiesh** [comment]
Verified on 18.8.0 (7433-4bf750d09bf4dba76a2b7ce0d72e88ecdfdbd96a)
