### ISSUE TITLE
Feature request: github pull request builder

### ISSUE THREAD

**Issue by virtuald** [gocd/gocd#494]
Jenkins already has a plugin to do this, seems like it would be a great thing to add to gocd. 

https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

**Comment by srinivasupadhya** [comment]
There is an update on #298. Would be great if someone could use the plugins & provide feedback.

**Comment by srinivasupadhya** [comment]
This is implemented through ashwanth's [plugin](https://github.com/ashwanthkumar/gocd-build-github-pull-requests).
