### ISSUE TITLE
Feature to set default permission for all pipeline groups

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#4940]
##### Issue Type

- Feature proposal

##### Summary

Currently, when a pipeline group is create all the instance users have view and operate permission to the group by default. Having a feature to set default permissions to all pipeline groups would be useful.

**Comment by chadlwilson** [comment]
it seems this is still not possible? Would be good to somehow re-open this if not.

**Comment by arvindsv** [comment]
@chadlwilson Sure. I'll re-open it.

**Comment by arvindsv** [comment]
If [using the API](https://api.gocd.org/current/#create-a-pipeline-group) is an option, then it can allow this to be changed. However, from the UI, yes there is no way to default this permission.

**Comment by chadlwilson** [comment]
@arvindsv are you saying that there is a way from the API to specify default permissions to apply to pipeline groups that don't have specific roles/user restrictions applied? If you have a simple JSON example that'd be awesome.

We do actually use automation via the API to apply our permissions to groups; but wanted a way to set a catch-all default permission when new pipeline groups are defined via a config repo.

**Comment by arvindsv** [comment]
@chadlwilson No, unfortunately not. When creating pipeline groups through the API, it is possible to restrict them, of course. Right? By providing permissions.

However, it seems you want permissions which apply to groups with no permissions. That's not possible, even through the API.

**Comment by chadlwilson** [comment]
Sure, but that's what this ticket is asking for - a way to set "default permissions" to fall back to if none are defined. :)

The most common use case is pipeline groups that are defined dynamically by config repos. In `20.2.0` these need to be whitelisted in config repo configuration (my understanding, we are still on `20.1.0` due to the changes to TLS making the upgrade painful) however I still don't think that allows you to impose a requirement that pipeline groups have permissions assigned; or a way to provide default "secure by default" fallback permissions.

**Comment by arvindsv** [comment]
> Sure, but that's what this ticket is asking for - a way to set "default permissions" to fall back to if none are defined. :)

Yes, understood. I thought it meant something else. :) Now, I know.

> The most common use case is pipeline groups that are defined dynamically by config repos. In 20.2.0 these need to be whitelisted in config repo configuration (my understanding, we are still on 20.1.0 due to the changes to TLS making the upgrade painful) however I still don't think that allows you to impose a requirement that pipeline groups have permissions assigned; or a way to provide "secure by default" fallback permissions.

Yes, you're right.

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.4.0 (11669-dcb1fc4c5a26445c1091b81acc326d7219a53eed)
