### ISSUE TITLE
Improved Pipeline Tile Design

### ISSUE THREAD

**Issue by naveenbhaskar** [gocd/gocd#4944]
**Existing Tile design**

After we implemented the existing design, some functionalities are added.

1. pipeline name name is shown in two lines now
2. No of icons increased - edit config, lock pipeline and analytics

because of this, the alignment of various elements goes off.
The pipeline paused message can be longer and that also disturbs the layout.

![image](https://user-images.githubusercontent.com/1627961/42562164-a0d346c2-8518-11e8-88df-07ebd8d53d41.png)

**Proposed Tile Design**

1. Moved all the pipeline related actions to one place and will always show at the bottom.
2. Pause pipeline message moved to a popup.
3. we can have more icons at the bottom.
4. Action button placement is consistent
5. Hover state for pipeline tile.

![image](https://user-images.githubusercontent.com/1627961/42562542-9de3ef56-8519-11e8-88d4-b11eb9eabdcb.png)

**Comment by arvindsv** [comment]
@naveenbhaskar Two thoughts:

1. The history icon seems to be "floating". Doesn't seem to belong to anything. Seems a little weird to me.

2. The pause message (and the fact that a pipeline is paused) seems to get lost. Especially in a busy pipeline like the second one in the first row shown there.

**Comment by naveenbhaskar** [comment]
_History_ link is suppose to be near to the pipeline name, as it is the history for the pipeline. In the existing design, its far from the name and out of context. I believe , below the pipeline name is the right place for _history_ link

I totally agree with the second point. Somehow I missed it. Here is the updated design.

![image](https://user-images.githubusercontent.com/1627961/42614541-f6ee8020-85c3-11e8-9205-e97a3d6f91e5.png)

and here is the list view for the same

![image](https://user-images.githubusercontent.com/1627961/42630562-c99fc21a-85f4-11e8-9fbc-13c7da7c3df3.png)

**Comment by arvindsv** [comment]
About history link, I think what is weird for me is that it's unlike anything else there. The rest of the pipeline level actions are icons in the bottom-right. History seems special.

However, I think it's ok. We don't need to change it. Coming up with a new icon for history seems like it'll make it less clear.
