### ISSUE TITLE
Bitbucket webhook no longer works on v18.6.0

### ISSUE THREAD

**Issue by jackjacek** [gocd/gocd#4945]
##### Issue Type

- Bug Report

##### Summary

Bitbucket webhook no longer works on v18.6.0, downgrading to v18.5.0 solved the problem.

Posting to https://{webhookSecret}:x@gocd.example.com:8154/go/api/webhooks/bitbucket/notify returns 401 and following message: `Basic authentication credentials are not required, since security has been disabled on this server.`
Removing auth bit from the link resulted in 400 and following message: `No token specified via basic authentication!`
Then I attempted to enable user authentication and:
- use original details which returned `Invalid credentials. Either your username and password are incorrect, or there is a problem with your browser cookies. Please check with your administrator.`
- use user's details which returned `Token specified via basic authentication did not match!`

###### Basic environment details

Using docker image gocd/gocd-server:v18.6.0

**Comment by ketan** [comment]
Thanks for reporting the issue. For whoever is looking at the issue. The fix is to add the following line to `AuthenticationFilterChain`:

```java
addFilterChain("/api/webhooks/*/notify", assumeAnonymousUserFilter)
```
This will skip authentication for these filter and let the controller deal with the authentication using the webhook secret.

**Comment by bdpiparva** [comment]
@jackjacek -- Experimental build with the fix is available [here](https://download.gocd.org/experimental/binaries/18.7.0-7116/generic/go-server-18.7.0-7116.zip). Please can you verify the fix?

**Comment by rajiesh** [comment]
Verified on 18.7.0 (7117-1709149e6946f9cec95e4a8e914a47c7806f0672). Closing the issue. @jackjacek - Do let us know if you see the fix not working, will reopen the issue

**Comment by joedai** [comment]
Hi,

Can we confirm when this bug is introduced? I am on 18.5.0 and it seems to have the exact same issue.
