### ISSUE TITLE
Pipeline history for pipelines in group gocd-website fails to appear

### ISSUE THREAD

**Issue by nyuday** [gocd/gocd#4946]
##### Summary

Accessing: build.gocd.org for the GoCD Website

When accessing the 'History' link for the 2 pipelines under the Pipeline group: `gocd-website` on build.gocd.org, an error appears: 

![screen shot 2018-07-11 at 3 22 36 pm](https://user-images.githubusercontent.com/18002645/42564438-6238f1f4-851e-11e8-8da3-f40a1ecf539e.png)

##### Steps to Reproduce
1. Go to build.gocd.org
2. Login and land on 'Pipelines' page
3. Under the pipeline name `gocd-www.go.cd` or `www.go.cd-PR`, click on the 'History' link
4. You'll see the error message in the screenshot 

Expected Result is to see the history of the pipeline.

**Comment by rajiesh** [comment]
Fixed after the revert. Closing the issue
