### ISSUE TITLE
Clean gitignored files before building

### ISSUE THREAD

**Issue by dziemba** [gocd/gocd#4948]
##### Issue Type

- Feature enhancement

##### Summary

Files that are ignored by git (via .gitignore) are not cleaned up before builds. 

###### Basic environment details

* Go Version: 18.6.0
* JAVA Version: 8
* OS: Linux

##### Steps to Reproduce

1. Create a pipeline that writes to a file that's present in .gitignore and lists all files
2. Run a build
3. Run another build - the file from the first build is still present in the working directory

##### Expected Results

I expect gitignored files to be cleaned up, so that previous (potentially faulty) builds do not affect my current build.

##### Actual Results

gitignored files are not being cleaned up.

##### Possible Fix

Add `-x` flag to `git clean`

**Comment by varshavaradarajan** [comment]
More conversation: https://github.com/gocd/gocd/pull/1059

**Comment by dziemba** [comment]
This is now fixed in 19.3.0. Thanks! 👍
