### ISSUE TITLE
use pipeline parameter as approval method

### ISSUE THREAD

**Issue by plainsane** [gocd/gocd#4959]
##### Issue Type
- Feature proposal
- Feature enhancement

##### Summary

it would be nice to parameterize the approval type of a stage with pipeline parameters.
im heavily using the yaml pluging to configure pipelines as well as anchors to provide recipes for different stages.  it would be nice if the stages defined in a yaml anchor could reference a pipeline parameter for its approval type since i usually have to perform the same stages and tasks for dev -> qa -> prod, but do not need any type of approval for dev stages, whereas i need approvals for qa and prod.

**Comment by keithy** [comment]
would still be nice
