### ISSUE TITLE
Delete SCM objects over the API

### ISSUE THREAD

**Issue by dbalakirev** [gocd/gocd#4967]
##### Issue Type
- Feature enhancement

##### Summary
According to the documentation, I can create and update scm objects.
https://api.gocd.org/current/#create-a-scm-object

Would it be possible to also delete them via the API (like for config repositories)?

**Comment by kritika-singh3** [comment]
Fixed in https://github.com/gocd/gocd/pull/6838 as a part of GoCD version 19.8.0
