### ISSUE TITLE
Race condition between stages of a pipeline

### ISSUE THREAD

**Issue by dpsenner** [gocd/gocd#497]
Consider 2 pipelines with 3 stages each:

pipeline1
-stage1
-stage2
-stage3

If one schedules the pipeline a typical order of execution would be:
- run1: stage1
- run1: stage2
- run1: stage3

Now if one schedules pipeline1 again while stage2 is executing, the order of execution changes to:
- run1: stage1
- run1: stage2
- run2: stage1
- run1: stage3
- run2: stage2
- run2: stage3

The intermittent execution of stage1 between stage2 and stage3 of the first run can yield bad/broken/incorrect results and offends the definition of "stages are always executed in order".

IMHO, the job scheduling should delay the execution of a previous stage in a single pipeline until the previous execution is finished or the behaviour should be at least configurable such that the order of execution is:
- run1: stage1
- run1: stage2
- run1: stage3
- run2: stage1
- run2: stage2
- run2: stage3

**Comment by jramapuram** [comment]
This is a problem for me as well. We have one initial pipeline that:

 - destroys a container
 - rebuild a container
 - start a container

This causes issues if we are later in the pipeline chain as the agent drops off.
