### ISSUE TITLE
Move Update check to aws lambda

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#4976]
##### Issue Type

- Feature proposal

##### Summary

On sidelines of the Data sharing story it was discussed if Update check can also be moved to aws lambda. This is the placeholder issue for further discussion and implementation of decided solution

**Comment by GaneshSPatil** [comment]
@arvindsv @ibnc -- as we are using the same usage-data-collector-app DB for both (data-sharing and update-check), does it make sense to introduce a new lambda function in the same app and completely remove the dependency from s3-access-logs?
