### ISSUE TITLE
Unable to connect to github through windows machine where gocd server is running

### ISSUE THREAD

**Issue by shru9289** [gocd/gocd#4978]
##### Issue Type

Unable to connect to Github repo . Connection is failing with below reason

Error performing command: --- Command ---
git ls-remote git@github.corp.ebay.com:kabothu/recsvc.git refs/heads/release-gocd
--- Environment ---
{GIT_ALLOW_PROTOCOL=http:https:ssh:git:file:rsync}
--- INPUT ----

--- EXIT CODE (128) ---
--- STANDARD OUT ---

--- STANDARD ERR ---
STDERR: Host key verification failed.
STDERR: fatal: Could not read from remote repository.
STDERR: 
STDERR: Please make sure you have the correct access rights
STDERR: and the repository exists.
---

Gocd server is running on windows machine. I am trying to connect to my github repo by providing ssh path. It cannot connect to github. Could you please help. As this is critical project. I need to go ahead and get this running at the earliest.

**Comment by shru9289** [comment]
I have generated ssh key on that windows machine by installing git . And added that ssh key to my github . Still having issues in connecting to my repo when i am creating pipeline

**Comment by shru9289** [comment]
@varshavaradarajan Can you please help me in this. I followed couple of your posts , could not find a solution

**Comment by varshavaradarajan** [comment]
> Still having issues in connecting to my repo when i am creating pipeline

@shru9289 - I assume you get this error when you click on check connection while adding the material.  Can you confirm that? If that's the case, the error is on the gocd server.

How have you installed the gocd server? If you have used the windows installer, then the gocd server is run by the local system account. Else, it will be run as the user who installed it. In both cases, log on to the windows instance as the user running the go server and then try doing `git ls-remote git@github.corp.ebay.com:kabothu/recsvc.git refs/heads/release-gocd`. It should fail with the same error as above. Then, generate the ssh keys for the right user and add it to github and execute the same command again.

**Comment by shru9289** [comment]
@varshavaradarajan - Yes the error i get when i click on check connection while adding material 
I have installed Gocd server and agent on my virtual windows machine. i have generated ssh key and added that to my github account . Did all hacks , still i face connection issue

**Comment by shru9289** [comment]
@varshavaradarajan - I see this error after executing git ls-remote


 git ls-remote git@github.corp.ebay.com:shrujain/recsvc.git refs/heads/release-gocd-project
The authenticity of host 'github.corp.ebay.com (10.254.180.205)' can't be established.
ECDSA key fingerprint is SHA256:BJamnZU+s3Xtgo/m13oBw9hw6CBdMUtnkCKeZJq0knU.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.corp.ebay.com,10.254.180.205' (ECDSA) to the list of known hosts.

**Comment by arvindsv** [comment]
@shru9289 The git process on the Windows virtual machine (GoCD server machine) will need access to the SSH public key to be able to connect to the GitHub repo.

In the command-line, *as the user that the GoCD server runs as*, if you run the git ls-remote that @varshavaradarajan asked you to, what happens? When you pasted the error above, are you sure you were running as the GoCD server's user?

Is GoCD server running as a Windows service?

**Comment by arvindsv** [comment]
It might be easier to use a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) and connect over https.

**Comment by shru9289** [comment]
@arvindsv - Windows virtual machine instance is created on my corp id and password. When a instance is created , the login account name and password is different than my corp account. [This should not be a problem i think] . Now  i have installed go Server and agent on this machine. And trying to access my github corp repo . Then i get this error. Is this because you cannot connect to the corp network?.

**Comment by arvindsv** [comment]
@shru9289 It's hard to say without seeing it / knowing more.

However, at the end of the day, GoCD does not do anything special when checking connection. All it does it run: `git ls-remote ...` when you click the button. It uses the installed git command-line client. So, if it works there - it should work through GoCD.

Here's what I would try:

1. Ensure that your user, when logged in, can run: `git ls-remote git@github.corp.ebay.com:shrujain...` without any prompts, etc.
2. Bring down the GoCD server.
3. Download the [GoCD server zip](https://www.gocd.org/download/#zip)
4. Start it from the command prompt as you (the regular login user) by running `start-server.bat`. This starts GoCD locally, without a Windows service.
5. Try and see if check connection works.

If it does, then what's happening is that the fact that the GoCD server is running as a different user is causing a problem.

**Comment by arvindsv** [comment]
I'm closing this issue, since I believe it's an environment/OS-setup related problem and not something wrong with GoCD. Happy to reopen if we find it's not, at any time. Thanks.

PS: You can still reply/comment, of course.

**Comment by shru9289** [comment]
@arvindsv - How do you bring down gocd server which is running?. I just close that browser. Could you please provide information on this .

**Comment by shru9289** [comment]
I am unable to run .bat file also 


C:\Program Files (x86)\Go Server>start-server.bat

C:\Program Files (x86)\Go Server>REM *************************GO-LICENSE-START**
******************************

C:\Program Files (x86)\Go Server>REM Copyright 2014 ThoughtWorks, Inc.

C:\Program Files (x86)\Go Server>REM

C:\Program Files (x86)\Go Server>REM Licensed under the Apache License, Version
2.0 (the "License");

C:\Program Files (x86)\Go Server>REM you may not use this file except in complia
nce with the License.

C:\Program Files (x86)\Go Server>REM You may obtain a copy of the License at

C:\Program Files (x86)\Go Server>REM

C:\Program Files (x86)\Go Server>REM    http://www.apache.org/licenses/LICENSE-2
.0

C:\Program Files (x86)\Go Server>REM

C:\Program Files (x86)\Go Server>REM Unless required by applicable law or agreed
 to in writing, software

C:\Program Files (x86)\Go Server>REM distributed under the License is distribute
d on an "AS IS" BASIS,

C:\Program Files (x86)\Go Server>REM WITHOUT WARRANTIES OR CONDITIONS OF ANY KIN
D, either express or implied.

C:\Program Files (x86)\Go Server>REM See the License for the specific language g
overning permissions and

C:\Program Files (x86)\Go Server>REM limitations under the License.

C:\Program Files (x86)\Go Server>REM *************************GO-LICENSE-END****
******************************

C:\Program Files (x86)\Go Server>IF "" == "N" (START "Go server" /WAIT server.cm
d )  ELSE (START "Go server" /MIN server.cmd )

C:\Program Files (x86)\Go Server>

**Comment by arvindsv** [comment]
You can google to find out how to bring down a Windows Service. You'd just search for "Services" or something in the search in the start menu and you'll find "Go Server" as a service there.

Once that is stopped, if the command fails to run, take a look at the server logs.

**Comment by shru9289** [comment]
@arvindsv @varshavaradarajan  - Could you please provide me this information on GOCD. Say when i first create pipeline within a pipeline group. I need to give material there. So i select git as the type. Do we have any option to provide our own command?. Like where it can run the command what we provide instead of git ls-remote ?. Because in my virtual machine through command prompt i can access github and my repo but git ls-remote do not work. So it looks like GOCD is running command git ls-remote to get access on the git repo. SO i need to know is there any other way to provide our git commands?

**Comment by ChedomirNikolikjLexis** [comment]
Upgrade to latest git version on your agent
