### ISSUE TITLE
GOCD Server Slow Performance

### ISSUE THREAD

**Issue by markrjamieson** [gocd/gocd#4979]
##### Issue Type

Bug Report

##### Summary

Upgraded Go Server from 16.4.0 to 18.6.0 as the old instance was quite slow and brittle. We had the older version dockerized, server and two agents in their own containers. But the new installation is the server and two agents all installed straight onto an AWS Ec2 instance. The H2 database behind Go is over 30G, and we suspect this has been an issue previously with performance, and also now. Post-Upgrade, we are still having performance issues, no longer shutdowns, but it's consistently slow in loading in the server console and performing most actions.
We've found in the Support API output that there's a lot of open/waiting threads, but not sure how these are being created etc.

[support-api.log](https://github.com/gocd/gocd/files/2226531/support-api.log)

##### Environment

See attached support api output file:
[support-api.log](https://github.com/gocd/gocd/files/2226531/support-api.log)

###### Basic environment details

* Go Version: `18.6.0 (6883-1013a67ccf0cda9c87e6361286708b584be42338) `
* JAVA Version: `1.8.0_171`
* OS: `Linux 3.10.0-514.el7.x86_64`
* Browser vendor and version (if relevant): `Google Chrome Version 67.0.3396.99`

###### Additional Environment Details

Usable space in artifacts repository: | 5.2 GB
Database schema version: | 1805001
Pipelines Count: | 262

See attached support api output file:
[support-api.log](https://github.com/gocd/gocd/files/2226531/support-api.log)

##### Steps to Reproduce

Can share a backup of the server to reproduce if this is to progress. But I'll hold off for now as it's quite large.

##### Expected Results
Improve in Go Server performance

##### Actual Results
All pages in the console load slowly or never load sometimes. Sometimes the console is unavailable.

##### Possible Fix
Management of H2 might be a solution, but unsure how this is possible without corruption or breaking the data. 

##### Log snippets

Not provided for now, but might be able to make these available.

##### Any other info
Properties:
SERVER_MEM=8192m
SERVER_MAX_MEM=8192m

**Comment by markrjamieson** [comment]
Slowness is throughout the GO Server Console interface, no specific pages really. Sometimes it's slow sometimes it's not, can't really find a pattern with it.

The instance it's running on is.. 
m4.xlarge | vCPU 4 | Memory 16GB | EBS-only | Dedicated EBS Bandwidth (Mbps) 750

I'll add that config you mentioned and come back with more info.

**Comment by markrjamieson** [comment]
@ketan I have the web request log, can I send this directly to you via email? What's your email address?

**Comment by markrjamieson** [comment]
Hi @ketan Any update?

**Comment by markrjamieson** [comment]
We've solved this issue by taking a backup of the DB, but creating a brand new one. Then using the old config to reinstate the pipeline versioning. This means it's running on a clean DB, with the correct config and versioning. It's now running very quickly.

**Comment by nadavwr** [comment]
Hi @markrjamieson 
Can you please tell a bit more about how you ended up handling this?

1) It's not clear from your last message—did you end up using the backup db in the later steps?
2) we thought about reloading pipeline configuration over a clean db, but are concerned that all pipelines will start firing right away—how did you reinstate pipeline versioning?

(/CC @gkid)
