### ISSUE TITLE
Client certificate was found to be invalid error

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#4980]
##### Issue Type
- Bug Report

##### Summary

GoCD server continuously complains about invalid client certificate when a fresh instance of GoCD server 18.7.0 is brought up. 

##### Environment
Tried with the latest zip installers and and Mac OSX installers.

###### Basic environment details

* Go Version: 18.7.0
* JAVA Version: Java8
* OS: Mac OS
* Browser vendor and version (if relevant):Chrome Version 67.0.3396.99

##### Steps to Reproduce

1. Bring up a fresh instance of GoCD server using the latest installers
2. The server logs should start showing up the error "Client certificate was found to be invalid"
3. Try deleting the agent and server certs and restart the server. The error should persist.

##### Expected Results
The error/exception should not be thrown.

##### Actual Results
The server keeps throwing the exception

[go-server.log](https://github.com/gocd/gocd/files/2227398/go-server.log)

**Comment by arvindsv** [comment]
@adityasood I brought up a completely new 18.7.0 server and agent combination, using the zip installer. I didn't see this. I saw another warning around cookie:

```
2018-07-25 07:48:53,514 ERROR [qtp1154002927-15] BuildRepositoryRemoteImpl:57 - Error occurred in com.thoughtworks.go.server.service.AgentRuntimeInfo@3723bf52[identifier=Agent [dev.local, 127.0.0.1, 79075500-636b-488e-b8a1-88b60181b063],runtimeStatus=Idle,buildingInfo=AgentBuildingInfo[, ],location=/private/var/folders/vt/5wgr6fyj1791pr5p7n3fprj00000gn/T/go-agent-18.7.0,usableSpace=11614011392,operatingSystemName=Mac OS X,cookie=<null>,supportsBuildCommandProtocol=false] ping.
com.thoughtworks.go.server.service.AgentNoCookieSetException: Agent [Agent [aravindsv.local, 127.0.0.1, 79075500-636b-488e-b8a1-88b60181b063, null]] has no cookie set
	at com.thoughtworks.go.server.service.AgentService.updateRuntimeInfo(AgentService.java:279)
	at com.thoughtworks.go.remote.BuildRepositoryRemoteImpl.ping(BuildRepositoryRemoteImpl.java:52)
	at com.thoughtworks.go.server.messaging.BuildRepositoryMessageProducer.ping(BuildRepositoryMessageProducer.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

which fixed itself and the agent came back up.

Can you see if you have some old agent running?

**Comment by adityasood** [comment]
@arvindsv I was able to replicate this when an older agent (earlier registered with another server) tries to register itself with GoCD server 18.7.0. The clean up of agents wasn't successful and hence I ran into this issue.

**Comment by arvindsv** [comment]
In your scenario, you say "... and restart the server". You shouldn't need to. But, this (below) should work. Can you check?

1. You have an agent registered with another server.
2. You bring up a new 18.7.0 server.
3. It shows this error (which is correct).
4. Bring down agent (**important**).
5. Delete the config/ directory.
6. Bring up the agent. It should register without an error (except maybe a warning about the cookie I mentioned earlier).

**Comment by adityasood** [comment]
@arvindsv after deleting the config/ directory on the old agent it registered. This works as expected.

**Comment by arvindsv** [comment]
@adityasood Good. FYI, the agent needs to be restarted so that it sees that the certificates are missing and it re-registers with the server.

If you think there is no other problem, please close this issue.
