### ISSUE TITLE
Sort the environment variable by alphabetical order

### ISSUE THREAD

**Issue by olive007** [gocd/gocd#4988]
##### Issue Type
- Feature proposal
##### Summary

Is it possible to sort the environment variable by alphabetical order ?

##### Code snippets/Screenshots
![gocd screenshot](https://user-images.githubusercontent.com/4058645/43374546-906c190a-93f3-11e8-92f9-52d9731cf231.jpg)

**Comment by arvindsv** [comment]
No, it isn't part of the operations possible in the UI. Might have to use the API or the config.
