### ISSUE TITLE
GO agent network "madness"

### ISSUE THREAD

**Issue by shindelhu** [gocd/gocd#4990]
##### Issue Type

- Bug Report

##### Summary

Hi,

I'm here to ask some help from you.
We've a GO server and several agents, we recently realized, that the agents making a hell lot of connections to the server, then leave them open. Because of that the connections table on the router filled up daily and dropping new requests.
Could someone tell me, how/where can we configure the agents, to not create new connections in every 10s?
Thanks in advance!
Log attached.

###### Basic environment details

* Go Version: 18.7.0 (7121-75d1247f58ab8bcde3c5b43392a87347979f82c5)
* JAVA Version: 1.8.0_131
* OS: RHEL 7.5 (Linux 3.10.0-862.2.3.el7.x86_64)
* Browser vendor and version (if relevant): any

![image](https://user-images.githubusercontent.com/26737842/43391090-06b20f56-93f0-11e8-8458-a104c2b8ff85.png)

**Comment by arvindsv** [comment]
@shindelhu That does seem like a lot of connections. Some questions / thoughts:

1. It's hard to say from this snippet of logs from an unknown system, but it looks like all the connections are from 10.10.100.3. Or is that your router? Is there a load balancer, NAT or proxy involved here?

2. How many agents do you have? If you bring down all of them, and keep one up, does this behavior get reproduced?

3. Do you see anything in the agent logs? Can you run tcpdump on the agent side to see what connections it's creating?

Usually, an agent creates a long-lived connection and continues to use it. It shouldn't make so many (there's no reason for it to). It might be possible that it's making a connection and thinking it's failing and tries to make anything about 10 seconds later. If so, it should show up in the logs.

**Comment by shindelhu** [comment]
@arvindsv Here are my answers:

1. 10.10.100.3 is a go agent machine, there is no loadbalancer, proxy, etc.
2. We've tried that, got the same result.
3. I can't see any unusual in the logs. I've attached the tcpdmup log.
[tcpdump.txt](https://github.com/gocd/gocd/files/2256856/tcpdump.txt)

**Comment by shindelhu** [comment]
Hi @arvindsv,

Is there any update on this?

Thanks,
Imre

**Comment by arvindsv** [comment]
No. I don't know what's going on. Can you upload your agent logs somewhere and link to it? Maybe to gist.github.com?

Did you say that this agent works properly? It connects to GoCD and picks up jobs?

If we find nothing in the logs, I plan to do two things:

1. Ask you to [enable debugging logs](https://docs.gocd.org/current/advanced_usage/logging.html#gocd-agent) on the agent (and share them).

2. Run tcpdump myself, to compare.

**Comment by shindelhu** [comment]
@arvindsv in the meantime, we did a complete fresh install. New server and new agents installed with the latest version of GO, the issue is the same.
I've started a tcpdump on the server, inspecting connections from one of the agents, see the screenshot.
![screen shot 2018-10-15 at 13 06 16](https://user-images.githubusercontent.com/26737842/46947681-e537e300-d07b-11e8-9537-f9a0780c833d.png)
