### ISSUE TITLE
Redesign Subversion Material Blacklist

### ISSUE THREAD

**Issue by stretch327** [gocd/gocd#4991]
##### Issue Type

- Feature enhancement

##### Summary

Right now, the Subversion Material Whitelist/Blacklist functionality is a simple comma-delimited list with no validation that is easy to get wrong. It would be nice if you could also list items one on each line and a "Check Blacklist" button to have it check the repository to make sure that the paths that were entered actually exist in the format they need to be in. As it is now, because I configure blacklists so rarely I have to go look up the documentation each time (when a new excluded item gets added to trunk and then on all of the current feature and release branches, usually about 6, or when they suddenly start failing).

**Comment by arvindsv** [comment]
@stretch327 This seems similar to #3573. So, I'll close this as a duplicate.

There hasn't been a lot of traction on it, since there isn't much work happening on that part at this time.
