### ISSUE TITLE
Allow only trigger with options

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#50]
### Description

As a Go Administrator
-   I want to be able to disable the trigger with no option
  button(pipeline trigger button) on a pipeline
-   so that i can avoid accidental triggers

**Comment by srinivasupadhya** [comment]
suggestion: can do something similar to this [post](https://groups.google.com/d/msg/go-cd/KgsOGTPGqpM/UsR0HvfH9UkJ)?

**Comment by arvindsv** [comment]
Closing as stale.
