### ISSUE TITLE
Unable to access git config repo over api

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5013]
##### Issue Type

- Bug Report

##### Summary

Git clone of `go/api/config-repository.git` fails with a 404 error. It seems the error is because of a missing whitelist in `SparkPreFilter`.

```
git clone https://build.gocd.org/go/api/config-repository.git
Cloning into 'config-repository'...
fatal: repository 'https://build.gocd.org/go/api/config-repository.git/' not found
```

**Comment by arvindsv** [comment]
@ketan Can we consider removing this API completely? The fact that it is broken and we haven't heard any complaints suggests to me that it is under-used, if used at all.

**Comment by ketan** [comment]
Hmm. I personally find this useful do `git blame` and figure out changes in the config repo, which are otherwise not possible from the UI.

I'm going to fix this issue on the weekend, we seem to have broken this in the last one or two releases.

**Comment by ketan** [comment]
I can confirm that this broken in 18.6.0. Likely because of the spring upgrade at the time.
