### ISSUE TITLE
Update parameter API

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#5016]
##### Issue Type

- Feature proposal

##### Summary

Currently, only edit pipeline config API is supported - where one have to pass the entire pipeline config while updating parameter. The side effect of this might lead to unwanted updates.

**Comment by arvindsv** [comment]
@ankitsri11 Closing this as wont-fix. Parameters are not a top-level entity in GoCD. They belong to a pipeline. A pipeline PATCH API would have been useful, sure.
