### ISSUE TITLE
Updating a pipeline attribute seems to make gocd think that I want to rename it

### ISSUE THREAD

**Issue by aerostitch** [gocd/gocd#5030]
##### Issue Type

- Bug report

Or maybe I'm doing something that became wrong with 18.7.0.

##### Summary

When running acceptance tests on our library, every time we try to update any of the attributes of a pipeline config via the API we get the following error:
```
Received HTTP Status '422 Unprocessable Entity': {
    "message": "Renaming of pipelines is not supported by this API."
}
```
It's as if the pipeline name was not retrieved properly here maybe? https://github.com/gocd/gocd/blob/master/api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/PipelineConfigControllerV6Delegate.java#L137

It was working before we upgraded to api v6 on 18.7.0.
The same tests work against a api v5.

##### Environment

We are using the gocd-server docker image for our acceptance tests, nothing really specific.

###### Basic environment details

* Go Version: `18.7.0 (7121-75d1247f58ab8bcde3c5b43392a87347979f82c5)`
* JAVA Version: `1.8.0_171`
* OS: `Linux 4.17.0-1-amd64`

##### Steps to Reproduce

1. Create a pipeline (using the API here)
2. Try to update any field of the pipeline (which is not the name)
See the comment bellow for the full bash scripts to reproduce that.

##### Expected Results

No error, the field that is supposed to be updated should be updated.

##### Actual Results

See Summary, I get a 422.

**Comment by aerostitch** [comment]
I'm also able to reproduce it with curl.

Creating the pipeline:
```
curl 'http://localhost:8153/go/api/admin/pipelines' \
      -H 'Accept: application/vnd.go.cd.v6+json' \
      -H 'Content-Type: application/json' \
      -X POST -d '{ "group": "first",
                    "pipeline": {
                    "label_template": "${COUNT}",
                    "lock_behavior": "none",
                    "name": "new_pipeline",
                    "template": null,
                    "materials": [
                      {
                        "type": "git",
                        "attributes": {
                          "url": "git@github.com:sample_repo/example.git",
                          "destination": "dest",
                          "filter": null,
                          "invert_filter": false,
                          "name": null,
                          "auto_update": true,
                          "branch": "master",
                          "submodule_folder": null,
                          "shallow_clone": true
                        }
                      }
                    ],
                    "stages": [
                      {
                        "name": "defaultStage",
                        "fetch_materials": true,
                        "clean_working_directory": false,
                        "never_cleanup_artifacts": false,
                        "approval": {
                          "type": "success",
                          "authorization": {
                            "roles": [],
                            "users": []
                          }
                        },
                        "environment_variables": [],
                        "jobs": [
                          {
                            "name": "defaultJob",
                            "run_instance_count": null,
                            "timeout": 0,
                            "environment_variables": [],
                            "resources": [],
                            "tasks": [
                              {
                                "type": "exec",
                                "attributes": {
                                  "run_if": [
                                    "passed"
                                  ],
                                  "command": "ls",
                                  "working_directory": null
                                }
                              }
                            ]
                          }
                        ]
                      }
                    ]
                }
              }'
```

Now try to update the pipeline:
```
etag=$(curl 'http://localhost:8153/go/api/admin/pipelines/new_pipeline' -H 'Accept: application/vnd.go.cd.v6+json' -i | awk '$1 ~ /^ETag:$/ {gsub( "\r", "" ); printf("If-Match: %s",$2)}')

curl -i 'http://localhost:8153/go/api/admin/pipelines/new_pipeline' \
      -H 'Accept: application/vnd.go.cd.v6+json' \
      -H 'Content-Type: application/json' \
      -H "${etag}" \
      -X PUT -d '{ "group": "first",
                    "pipeline": {
                    "label_template": "Updated_${COUNT}",
                    "lock_behavior": "none",
                    "name": "new_pipeline",
                    "template": null,
                    "materials": [
                      {
                        "type": "git",
                        "attributes": {
                          "url": "git@github.com:sample_repo/example.git",
                          "destination": "dest",
                          "filter": null,
                          "invert_filter": false,
                          "name": null,
                          "auto_update": true,
                          "branch": "master",
                          "submodule_folder": null,
                          "shallow_clone": true
                        }
                      }
                    ],
                    "stages": [
                      {
                        "name": "defaultStage",
                        "fetch_materials": true,
                        "clean_working_directory": false,
                        "never_cleanup_artifacts": false,
                        "approval": {
                          "type": "success",
                          "authorization": {
                            "roles": [],
                            "users": []
                          }
                        },
                        "environment_variables": [],
                        "jobs": [
                          {
                            "name": "defaultJob",
                            "run_instance_count": null,
                            "timeout": 0,
                            "environment_variables": [],
                            "resources": [],
                            "tasks": [
                              {
                                "type": "exec",
                                "attributes": {
                                  "run_if": [
                                    "passed"
                                  ],
                                  "command": "ls",
                                  "working_directory": null
                                }
                              }
                            ]
                          }
                        ]
                      }
                    ]
                }
              }'
```

Result (I called the 2nd script `update.sh`):
```
$ bash update.sh 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1847    0  1847    0     0   450k      0 --:--:-- --:--:-- --:--:--  450k
HTTP/1.1 100 Continue

HTTP/1.1 422 Unprocessable Entity
Date: Thu, 16 Aug 2018 01:12:34 GMT
Set-Cookie: JSESSIONID=node0a8n4gade9vc7b1n51u70c7bg42.node0;Path=/go;Expires=Thu, 30-Aug-2018 01:12:34 GMT;Max-Age=1209600;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/vnd.go.cd.v6+json;charset=utf-8
X-Runtime: 8
Transfer-Encoding: chunked

{
  "message" : "Renaming of pipelines is not supported by this API."
}
```

**Comment by aerostitch** [comment]
Not that I've used the exact same scripts, just replacing the api v6 by v5 against a gocd server 18.6.0 and the update works fine, so I guess it's really something specific to api v6 of the pipeline config.

**Comment by ketan** [comment]
I'm looking into this issue.

**Comment by ketan** [comment]
Hi @aerostitch —

It looks like the behavior with v5 was an unintended side-effect of how rails works.

According to the documentation for the [`PUT` call](https://api.gocd.org/18.7.0/#edit-pipeline-config) — you're expected to submit the `pipeline` object, this is different from the object you submit to the `POST` endpoint for create. I applied the following patch to the script you attached above, and it worked. This is also in-line with what the documentation says. I'm going to mark this issue as closed.

```patch
7,8c7,8
<       -X PUT -d '{ "group": "first",
<                     "pipeline": {
---
>       -X PUT -d '{ 
>                    
66c66
<                 }
---
> 
```

**Comment by aerostitch** [comment]
So that's a regression from before, that means you can't actually change the pipeline group of a pipeline?
That was possible before. :(

**Comment by ketan** [comment]
Changing the pipeline group was never supported and it never worked — the `group` attribute on the `PUT` call was simply being ignored. Do you have a reproducible test case with api v5?

**Comment by aerostitch** [comment]
I don't remember trying but that's fine. I've wasted way too much time on this already.
It's just really misleading that those objects used to work and don't anymore, but that's my bad to have taken bad habits in the first place.
Thanks for looking into this.

**Comment by arvindsv** [comment]
@aerostitch Having said that this is working as documented, we don't like that the GET/PUT are not proper opposites of each other. We will fix it so that they work like that. We're figure out how to model it properly so that the action of moving a pipeline across groups is allowed.

Thank you for spending that time, and submitting a useful issue. It is much appreciated.

**Comment by arvindsv** [comment]
To provide a little more information, the thoughts are around:

1. Pipeline creation/updating shouldn't, as a side-effect, create a group and assign the pipeline to it.

2. Pipeline group API should be a proper top-level API which allows associating pipelines with it and allow editing authorization. Something like POST/PUT/GET on `/go/api/admin/GROUP`.

3. If so, maybe the pipeline config API should be (url) namespaced as: `/go/api/admin/GROUP/PIPELINE` and then POST on that creates a pipeline there. Assuming the group has been created.

4. Actions like moving pipelines across groups are not easily modeled in this situation. We might need to model them differently.

**Comment by moritzheiber** [comment]
I welcome the idea of pipeline groups as a first class citizen here. It always felt like they were merely a label rather than a way of grouping pipelines. As a proper first level entity they might be more useful.

I acknowledge that restructuring the internal data model to conform to this effort might take some time though. Especially when it comes to moving one pipeline to a different group.

**Comment by aerostitch** [comment]
Thanks for catching the issue @ketan and for the infos @arvindsv .
Yeah, that would probably be kind of a headache. Maybe we should just have the pipeline group as an attribute of a pipeline so the pipeline would attach itself to a group? It would probably be less changes that way.
But a pipeline group api with more action would for sure be interesting.

**Comment by aerostitch** [comment]
For example, the json pipeline plugin does have the group as an attribute of the pipeline itself.

**Comment by arvindsv** [comment]
> Maybe we should just have the pipeline group as an attribute of a pipeline so the pipeline would attach itself to a group?

Yes, it probably would. However, we would still need to verify authorization. Not everyone who can change a pipeline can change its group. If they don't have permissions to a group, they shouldn't be able to add to it.

We will need to decide whether it is _good enough_ to do that, to make it work, though.
