### ISSUE TITLE
Can't logout when using touch screen

### ISSUE THREAD

**Issue by kmugrage** [gocd/gocd#5034]
##### Issue Type

- Bug Report
- Feature enhancement

##### Summary

When using a touch screen the user cannot log out using the menu in the UI.

##### Environment

GoCD 18.7 (build.gocd.org and others)
Windows 10 Home
Windows 10 Enterprise
iPad w/ iOS 11
Microsoft Edge
Safari
Chrome

##### Steps to Reproduce

1. Log into a GoCD instance
2. Using the touch screen, click the user menu
3. Choose log out (nothing happens)

Log out does work on the same systems with a mouse / trackpad. 

##### Expected Results

User should be logged out

##### Actual Results

Nothing happens

**Comment by GaneshSPatil** [comment]
@naveenbhaskar -- Can you take a look at this?

With the new GoCD header, on mobile, it shows the menu options, but nothing happens even after clicking on it.

None of the application menus (pipelines, agents, admin), neither the user menus (preferences, log-out) are visible on mobile.

**Comment by naveenbhaskar** [comment]
sure.. will look into this
