### ISSUE TITLE
Console Log unable to parse "\n" 

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5037]
##### Issue Type
- Bug Report
##### Summary

Currently, if a user has a script which uses "\n" character set in their task execution, the console log fails to parse and does not show up from this task onwards. This can easily be reproduced with the YAML file attached with the issue

###### Basic environment details

* Go Version: 18.7.0
* JAVA Version: Java8
* OS: MacOs
* Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

1. Create a YAML pipeline using the attached YAML file
2. Run the task. The console logs does not show up
3. Inspect using the browser developer tools, you will observe parse failure error (attached)
4. Edit the YAML file to remove "\n" from the task. The console log will now show up

##### Expected Results
The console logs should show up.

##### Actual Results
The console logs do not show up. There is a parse error

<img width="1376" alt="screen shot 2018-08-17 at 11 11 38 am" src="https://user-images.githubusercontent.com/17826464/44249705-b681c580-a20e-11e8-8c5c-6563dcafa09d.png">
[sample-yaml-file.txt](https://github.com/gocd/gocd/files/2296105/sample-yaml-file.txt)
[console.log](https://github.com/gocd/gocd/files/2296107/console.log)
<img width="1440" alt="screen shot 2018-08-17 at 11 04 25 am" src="https://user-images.githubusercontent.com/17826464/44249747-e92bbe00-a20e-11e8-991f-1fac608ab29f.png">

**Comment by GaneshSPatil** [comment]
For users facing this issue, Please use the `console.log` artifact to see the job console.

Navigate to `Artifacts Tab`  -> `cruise-output/console.log`

**Comment by GaneshSPatil** [comment]
@adityasood -- @vrushaliwaykole  and I will be taking a look at this issue.

**Comment by ankitsri11** [comment]
Fixed as part of this PR: https://github.com/gocd/gocd/pull/5877

Verified on GoCD Version: 19.2.0 (8559-38e68d0ca9dfce367dd1d9a380e824595cd87d34)
