### ISSUE TITLE
[Personalization view] Config repo pipeline changes takes time to update on pipeline selections modal

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#5044]
##### Issue Type

- Bug Report

##### Summary

When user create/update(name)/delete pipeline defined in config repo, pipeline selection modal does not reflect the change

###### Basic environment details

* Go Version: `18.8.0-7274-1e0f9762873bbe0955e421eb8ea7e57691d6dbc6`

##### Steps to Reproduce

1. Add Config repository to GoCD server config xml
2. Wait for the pipelines to show up on dashboard
3. Create personalization views which included pipelines defined in config repo
4. Now update the name of the pipeline defined in config repo
5. Wait till dashboard reflects the change
6. Now edit the view created or create new view to open personalization modal to show up list of pipelines
7. The name change for config repo pipeline is not reflected on the pipeline selection modal
8. Need to refresh page to see the change

Similar behavior for new pipeline added to config repo or deletion of pipeline in config repo

**Comment by ibnc** [comment]
I'm taking a look at this issue
