### ISSUE TITLE
Issue while installing gocd server on windows 8 system

### ISSUE THREAD

**Issue by satyajeetkumar** [gocd/gocd#5045]
##### Issue Type
Issue while installing gocd server on windows 8 system

bug Report

##### Summary

Issue while installing gocd server on windows 8 system :+1: 

while starting the server, it is failing with log message " java.io.FileNotFoundException: C:\Program Files (x86)\Go Server\work\jetty-0.0.0.0-8153-cruise.war-_go-any-\webapp\WEB-INF\rails.new\vendor\bundle\jruby\1.9\gems\thor-0.19.1\spec\fixtures\command.thor (Access is denied)"

when i explore the above path, i can see that there is only one file named "application.rb". there is no any command.thor file.

Please guide us to resolve the issue

Log in go-server-log :+1: 

2018-08-21 00:05:37,500 WARN  [WrapperJarAppMain] WebAppContext:554 - Failed startup of context o.e.j.w.WebAppContext@298240d1{/go,null,UNAVAILABLE}{cruise.war}
java.io.FileNotFoundException: C:\Program Files (x86)\Go Server\work\jetty-0.0.0.0-8153-cruise.war-_go-any-\webapp\WEB-INF\rails.new\vendor\bundle\jruby\1.9\gems\thor-0.19.1\spec\fixtures\command.thor (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)

##### Environment
windows 8

###### Basic environment details
windows 8

* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`

##### Steps to Reproduce

1.  Download the GO CD server Version: 18.7.0
2.  Install it to windows 8 system
3.  Failed to start server 
4.  check the log in go-server.log

##### Expected Results

GO CD server should be started on http://localhost:8153/go 

##### Actual Results

Failing to start server and throwing java.io.FileNotFoundException 
there is no command.thor file under the below path

\Go Server\work\jetty-0.0.0.0-8153-cruise.war-_go-any-\webapp\WEB-INF\rails.new\vendor\bundle\jruby\1.9\gems\thor-0.19.1\spec\fixtures\command.thor

##### Log snippets

2018-08-21 00:05:37,500 WARN  [WrapperJarAppMain] WebAppContext:554 - Failed startup of context o.e.j.w.WebAppContext@298240d1{/go,null,UNAVAILABLE}{cruise.war}
java.io.FileNotFoundException: C:\Program Files (x86)\Go Server\work\jetty-0.0.0.0-8153-cruise.war-_go-any-\webapp\WEB-INF\rails.new\vendor\bundle\jruby\1.9\gems\thor-0.19.1\spec\fixtures\command.thor (Access is denied)

**Comment by adityasood** [comment]
@satyajeetkumar I was able to install GoCD server on a windows 8 VM and was able to create pipelines. I also navigated to the path ` C:\Program Files (x86)\Go Server\work\jetty-0.0.0.0-8153-cruise.war-_go-any-\webapp\WEB-INF\rails.new\vendor\bundle\jruby\1.9\gems\thor-0.19.1\spec\fixtures\` and was able to see `command.thor` file.

Could you please verify that the account used to perform the GoCD server installation has the right set of permissions? Also could you let us know if the same user has permissions on the work directory?

Please find attached some screenshots for your reference.

<img width="1214" alt="screen shot 2018-08-22 at 10 40 46 am" src="https://user-images.githubusercontent.com/17826464/44444434-6e8de480-a5fa-11e8-9e74-1fc56fdf1234.png">
<img width="933" alt="screen shot 2018-08-22 at 10 33 17 am" src="https://user-images.githubusercontent.com/17826464/44444435-6f267b00-a5fa-11e8-83cf-6f890b47f559.png">
<img width="1024" alt="screen shot 2018-08-22 at 11 00 25 am" src="https://user-images.githubusercontent.com/17826464/44444469-a137dd00-a5fa-11e8-83cc-77eb6248fd93.png">

**Comment by satyajeetkumar** [comment]
@adityasood,
I have admin access on my system. I downloaded GOCD server from this link (64 bit jre : https://www.gocd.org/download/#windows ) and then run the exe file. but still not able to find file "command.thor" in my windows 8 system.

**Comment by adityasood** [comment]
@satyajeetkumar could you please share `go-server.log` and `go-server-wrapper.log` files with us?

**Comment by satyajeetkumar** [comment]
Please find go-server-wrapper.log attached here

**Comment by satyajeetkumar** [comment]
Please find go-server.log attached here

**Comment by adityasood** [comment]
@satyajeetkumar we suspect this to be a permission issue. Is this the same user which installed GoCD server? Or do you have enough permissions to start this windows service? Can you verify if the user has permissions on the GoCD server installation directory?

**Comment by bdpiparva** [comment]
Sure - closing the issue as of now.
