### ISSUE TITLE
[Personalization View] Personalization Tab drop down goes out of view

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5047]
##### Issue Type
- Bug Report
##### Summary

The drop-down list on the personalization view goes out of view and user will have to scroll to look at the drop-down list. 

###### Basic environment details

* Go Version: 18.8
* JAVA Version: Java8
* OS: MacOs
* Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

1. Create a few personalizations tabs
2. Click on the drop-down list
3. Click on any tab in the list
4. You can see the drop down going out of view

##### Expected Results
The drop-down should not go out of view

##### Actual Results
The drop down goes out of view

##### Log snippets
From browser console 
```
Tried to initialize dropdown-menu on an element that already has a Foundation plugin
```
-->
<img width="1440" alt="dropdown" src="https://user-images.githubusercontent.com/17826464/44383667-1346ee00-a537-11e8-96a3-98d767e7ea9d.png">

**Comment by arvindsv** [comment]
@adityasood This seems to be fixed.

**Comment by adityasood** [comment]
verified on `18.8.0 (7405-918ce4e304d5dcf9ff543561ce56d180eaabc533)`
