### ISSUE TITLE
[Personalization View] Unable to perform multiple saves on the Personalization tab due to expired user data filter

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5048]
##### Issue Type
- Bug Report
##### Summary

The user-data filter appears to be invalid when multiple saves are tried on the personalization tab

###### Basic environment details

* Go Version: 18.8.0
* JAVA Version: Java8
* OS: MacOS
* Browser vendor and version (if relevant): Chrome

1. Create multiple tabs using the personalizaiton view
2. Drag and drop a tab and save the new order
3. Try editing one of the tabs
4. You will see error "Update failed because client filter data is out-of-date"

##### Expected Results
A user should be able to perform multiple saves in quick successions.

##### Actual Results
The user filter seems to be out of date

<img width="1439" alt="screen shot 2018-08-21 at 11 43 51 am" src="https://user-images.githubusercontent.com/17826464/44383978-2dcd9700-a538-11e8-89a4-f3bbe2cae78b.png">

![etag-issue](https://user-images.githubusercontent.com/17826464/44384015-52c20a00-a538-11e8-8000-5d379df092e6.gif)

**Comment by ibnc** [comment]
I'm looking into this issue
