### ISSUE TITLE
[Personalization View] Disable failed/building filters until a pipeline is selected in pipeline selection view

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5049]
##### Issue Type
- Bug Report

##### Summary

Using the current pipeline selection filters (failed/building) the user can create a view with no pipelines selected. However, the filters need atleast one pipeline/pipeline-group to filter on the pipeline status.

This is misleading for the end-user and might lead to the creation of empty views

###### Basic environment details

* Go Version: 18.8.0-7286
* JAVA Version: Java8
* OS: MacOS
* Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

1. Click to create a new personalization tab
2. Click on failed/building in the pipeline selection filters
3. Click on none in the pipeline selection filters
4. Save the tab
5. This tab will always be empty as the user is not prompted for selecting atleast one pipeline

##### Expected Results
either disable the filter until a pipeline is selected or make the filter dynamic to show all pipelines in the selected state ( until atleast one is selected)

##### Actual Results
View with no pipelines is created

**Comment by arvindsv** [comment]
As discussed, "Add" button will be disabled with a tooltip, when no pipelines are selected in the view modal. If "New" pipelines is chosen, then the "Add" is allowed even with no pipelines.
