### ISSUE TITLE
Allow setting a cron timer for periodic backups

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5059]
##### Issue Type

- Feature request

##### Summary

While setting up backups with GoCD, usually via cron, or other similar tools. It's always a problem as to who monitors that the backups are actually happening.

Additionally any backup failures, can be immediately flagged via email — or — the errors and warnings modal.

I'd like to think that a feature in GoCD where we setup a cron timer to perform a periodic backup would be highly useful for a lot of GoCD admins. This feature should consist of two things:

- A timer specification of the backup
- A "post-backup" script. This should hopefully allow pushing the backup to an external location (s3, rsync etc)...

I don't know if a pre-backup script would be useful here — but I'm open to the idea if someone can come up with some use-cases where this may be useful to them.

**Comment by ketan** [comment]
After further discussion with @arvindsv, here's what we're considering for the first cut:

- User specifies something in the config XML: `<backup schedule="CRON_TIMER" postBackup="SOME_SCRIPT" />`
- We'll probably expose these parameters on the existing backup page as well (or maybe server config?)
- The script will receive the following as environment variables:
  - `INITIATED_VIA=cron|api|console`
  - `INITIATED_BY_USER=bob` (unless via cron)
  - `BACKUP_BASE_DIR=/var/lib/go-server/.../serverBackups`
  - `BACKUP_PATH=/var/lib/go-server/.../serverBackups/backup_20150807-153719`
  - `BACKUP_TIMESTAMP= 2015-08-07T10:07:19.868Z ` - for vanity?
- The script will be expected to return a zero/non-zero status for success.
- Any errors from the script will be shown on the errors and warnings modal (The errors won't survive a restart). @arvindsv @maheshp — can you confirm if it should?

At a later point. We can consider adding email notifications only for backup failures.

```xml
<backup ... notificationOnFailures="bob@example.com, alice@example.com"/>

<backup ...>
  <failureNotifications>
    <!-- Unsure if we should accept emails or usernames here -->
    <user>bob</user>
    <email>alice@example.com</email>
  </failureNotifications>
</backup>
```

**Comment by rajiesh** [comment]
Verified on 18.9.0 (7478-f202ea9416939d7ce356cf3939239ef953ec423b)

**Comment by monikakatiyar16** [comment]
Is it possible to pass environment variables or bash script arguments to this post backup script? I don't want to hardcode certain sensitive information in the post backup script. (also since this script is checked into git & automatically deployed to the machine in case of any changes)

If I try to pass arguments along with the script, I see the following error:
`Cannot run program "/<path-to-script>/post-script.sh --server-backup s3-bucket-name access-key secret-key": error=2, No such file or directory`

Alternatively, I cannot see any place where i can define these parameters as an environment variable which can be fetched in the post backup script. Am I using it the wrong way?

**Comment by arvindsv** [comment]
@monikakatiyar16 No. It's just setup to be one script, with no arguments. You'll need to (maybe) setup a file on the GoCD server, in a secure location, and then source the file to read the sensitive information.

**Comment by monikakatiyar16** [comment]
@arvindsv If it's possible some time down the line, it would be really great if you guys can provide some secure environment variable support for the post backup script as well. 

Even if the script is not checked in git, still storing sensitive information in a file on the system seems a little difficult to imagine. In our current setup, we don't have any sensitive information (like aws profiles, user creds, etc) stored on the agent or the server machines. We have secured all gocd agents/server with instance hardening scripts as well to ensure nothing wrong happens. All env vars are encyrpted in gocd pipelines as well. Agreed that we might be still skeptical about keeping S3 bucket name, access keys/secret keys (even with restricted iam profiles) on disk.

Triggering a pipeline via the post backup script would still have the access token with operate / view access to the pipeline's environment variables, so we skipped that scenario.

For the time being, maybe setting up a timer based pipeline to store the backup on S3 could be the solution for us (timer with a little offset from the automated backup cron expression).

**Comment by arvindsv** [comment]
If you don't mind setting an environment variable at the GoCD server level,  it might be worth it to see if a server-level environment variable (can be set in wrapper-properties.conf) shows up in the script. However, even that will be on the filesystem and won't be encrypted within GoCD.

Playing a bit of a devil's advocate, even if it is stored as a secure environment variable within GoCD, there will be a decryption key which it will use to decrypt the value to pass it into a script at a later time (script or a pipeline task). So, if you're considering access to the filesystem as a part of your threat model, then the encryption within GoCD won't overcome that.

Not a lot will overcome that anyway. The only reasonably secure approach could be to use IAM roles or such to remove the need for credentials to be stored at all. If all you're thinking about is backing up to S3, then IAM roles might be something to look into.

**Comment by monikakatiyar16** [comment]
Makes sense! Thanks for the prompt responses!
