### ISSUE TITLE
[Data Sharing]File not found exception for datasharing.pem file on windows 

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5071]
##### Issue Type
- Bug Report
##### Summary
java.io.FileNotFoundException: C:\Program%20Files%20(x86)\Go%20Server\work\jetty-0.0.0.0-8153-cruise.war-_go-any-\webapp\WEB-INF\classes\datasharing-public.pem (The system cannot find the path specified)
###### Basic environment details

* Go Version:18.7
* JAVA Version: Bundled Java8
* OS: Windows 8.1 64bit OS
* Browser vendor and version (if relevant): IE-11

##### Steps to Reproduce

1.  Start a GoCD server 
2. Allow Data Sharing on this server
3. You should see the error in go-server.log file, when the server tries to post the data 

##### Expected Results
The file is present and GoCD server is able to locate it

##### Actual Results
The file is present but the GoCD server is unable to locate it

##### Possible Fix

[go-server.log](https://github.com/gocd/gocd/files/2323340/go-server.log)

**Comment by GaneshSPatil** [comment]
We've verified that GoCD's data sharing was broken on GoCD `v18.7.0`. 
No data has been received from windows instances who are on GoCD `v18.7.0`.

**Comment by GaneshSPatil** [comment]
This was broken due to: https://github.com/gocd/gocd/pull/4968
Also, has been fixed as part of https://github.com/gocd/gocd/pull/4998
