### ISSUE TITLE
[Personalization View] Newly created pipelines with no history and selected to run manually show up under "failed/building" filtered views

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5075]
##### Issue Type
- Bug Report
##### Summary

Newly created manual pipelines with no history should not show up if the pipeline is selected in a view filtered by "failed/building" status.

###### Basic environment details

* Go Version: 18.8.0-7325
* JAVA Version: Java8
* OS: MacOS
* Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

1. Create a manual pipeline 
2. Create a view and filter the view (failed/building)
3. The pipeline shows up with no run in these views

##### Expected Results
The pipeline should not show up until "Show newly created pipeline" filter is also selected

##### Actual Results
The pipeline is shown

**Comment by arvindsv** [comment]
@adityasood Can you please re-check this?

**Comment by adityasood** [comment]
verified on `18.8.0 (7405-918ce4e304d5dcf9ff543561ce56d180eaabc533)`. This works as expected. Closing this issue.
