### ISSUE TITLE
Current Material is not highlighted in VSM

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5095]
##### Issue Type

- Bug Report

##### Summary
When looking at the VSM for a particular entity (pipeline or material), the entity should be highlighted to indicate that the current VSM is rendered in the context of the pipeline or material.

Material tile is not highlighted, when the given VSM is rendered for a material.
**Note:** Works for pipeline though.

##### Expected Results
The material should be highlighted for which the VSM is rendered.

##### Actual Results
No material is highlighted.

**Comment by GaneshSPatil** [comment]
This issue has a side-effect, which causes the source material not being highlighted in the VSM mode.

Required for release: `v18.8.0`

**Comment by rajiesh** [comment]
Verified on 18.8.0 (7433-4bf750d09bf4dba76a2b7ce0d72e88ecdfdbd96a)
