### ISSUE TITLE
[Personalization View] User data filter is not updated across multiple browser session/tabs

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5099]
##### Issue Type
- Bug Report

##### Summary

If a user is logged-in from two separate browser sessions, the tabs created in one browser are not updated and user is unable to update the tabs in the second without force refresh.

###### Basic environment details

* Go Version: 18.8.0 (7365
* JAVA Version: Java8
* OS: MacOs
* Browser vendor and version (if relevant): Chrome and Safari

![user-data-filter](https://user-images.githubusercontent.com/17826464/44844273-11cca280-ac68-11e8-8bf5-4d0e7609bf23.gif)

**Comment by marques-work** [comment]
@adityasood @GaneshSPatil @arvindsv  also worth noting, I think they will update upon the next dashboard data poll. So it may not be immediate, but it does eventually happen IIRC. I think the interval is several seconds (5?).

**Comment by arvindsv** [comment]
10, I believe. Closing this. Let's hear from people first.
