### ISSUE TITLE
[Personalization View] Anonymous User personalization views are not retained across sessions

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5100]
##### Issue Type
- Bug Report
##### Summary

The anonymous user can save multiple tabs and then clear cookies. The created tabs no longer show up. These are persisted in db with a `null` user entry. This can potentially bloat a db. We should also treat anonymous as a user and show up the tabs.

###### Basic environment details

* Go Version: 18.8.0 (7371
* JAVA Version: Java8
* OS: MacOs
* Browser vendor and version (if relevant): Chrome and Safari

##### Steps to Reproduce

1. Start a new server without authentication
2. Create several personalization dashboard views
3. Open a new browser window
4. Save the same named tabs. 
5. This creates a separate selection in the database

##### Expected Results
The anonymous user PV selection should be saved 

##### Actual Results
The PV for anonymous are not retained across sessions

![anonymous-user](https://user-images.githubusercontent.com/17826464/44846430-f2387880-ac6d-11e8-9eaa-f2f131564905.gif)

<img width="1174" alt="screen shot 2018-08-30 at 3 35 47 pm" src="https://user-images.githubusercontent.com/17826464/44845913-7c7fdd00-ac6c-11e8-8a0f-f20e33c48183.png">

**Comment by ketan** [comment]
Based on my conversation with @arvindsv — we were of the opinion that anonymous users should not have any personalization associated with them.

**Comment by arvindsv** [comment]
@ketan We said that it doesn't need to (shouldn't) be tied to an anonymous user's "session". There can be one for all anonymous users and they'll all see the same set of views.

**Comment by ketan** [comment]
@adityasood since you opened this, wanted to see if you're OK closing based on the last comment?

**Comment by adityasood** [comment]
@ketan I remember some conversation around this in one of our standups

1. we wanted to allow all anonymous users to share the PV. Today the PV from an anonymous user is saved in db but no user id is associated with it and hence these are not shown across sessions. We were thinking of persisting the anonymous user PV with a user ID, to allow the view to be available to all anonymous users.

since this is not yet implemented we should keep this issue open. Thoughts?

**Comment by adityasood** [comment]
@ketan I remember some conversation around this in one of our standups

1. we wanted to allow all anonymous users to share the PV. Today the PV from an anonymous user is saved in db but no user id is associated with it and hence these are not shown across sessions. We were thinking of persisting the anonymous user PV with a user ID, to allow the view to be available to all anonymous users.

since this is not yet implemented we should keep this issue open. Thoughts?

**Comment by adityasood** [comment]
@ketan I remember some conversation around this in one of our standups

1. we wanted to allow all anonymous users to share the PV. Today the PV from an anonymous user is saved in db but no user id is associated with it and hence these are not shown across sessions. We were thinking of persisting the anonymous user PV with a user ID, to allow the view to be available to all anonymous users.

since this is not yet implemented we should keep this issue open. Thoughts?

**Comment by adityasood** [comment]
@ketan I remember some conversation around this in one of our standups

1. we wanted to allow all anonymous users to share the PV. Today the PV from an anonymous user is saved in db but no user id is associated with it and hence these are not shown across sessions. We were thinking of persisting the anonymous user PV with a user ID, to allow the view to be available to all anonymous users.

since this is not yet implemented we should keep this issue open. Thoughts?

**Comment by adityasood** [comment]
@ketan I remember some conversation around this in one of our standups

1. we wanted to allow all anonymous users to share the PV. Today the PV from an anonymous user is saved in db but no user id is associated with it and hence these are not shown across sessions. We were thinking of persisting the anonymous user PV with a user ID, to allow the view to be available to all anonymous users.

since this is not yet implemented we should keep this issue open. Thoughts?

**Comment by adityasood** [comment]
@akshaydewan @arvindsv do we plan on making this change?

**Comment by arvindsv** [comment]
@adityasood I don't think we need to - we need to rethink anonymous users and provide a proper anonymous user (without having to log in, even if security is enabled). Maybe we can look at this at that time?

**Comment by adityasood** [comment]
@arvindsv yes I think we can do that. I am closing this out for now and will track it once we play out that story.
