### ISSUE TITLE
Reason for the settings icon being disabled on the dashboard flickers on Chrome

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#5110]
##### Issue Type

- Bug Report

##### Summary

When pipelines on the dashboard are grouped by environments or pipeline groups by a user that does not have permissions to edit the environment, then the reason "You do not have permissions to edit" keeps flickering on Chrome. The reason does not even appear in Firefox on hover. Do you think its better to change the message to `You do not have permissions to edit the environment`, @akshaydewan? 

![issue-with-tooltip](https://user-images.githubusercontent.com/7871209/44967995-be599d80-af62-11e8-8096-6ddee114320c.gif)

###### Basic environment details

* Go Version: `: 18.8.0 (7411-b0568a4a35db79fc5b83d5e5d5f03db545c945d1)`
* Browser vendor and version (if relevant): 

- Chrome: 68.0.3440.106
- Firefox Quantum: 61.0.2  

##### Steps to Reproduce

1. Navigate to build.gocd.org
2. Use the guest login
3. Hover over the settings icon next to the pipeline group or environment name

##### Expected Results

Reason why the settings is disabled should appear clearly

##### Actual Results

The whole reason is not fitted within the black background. Keeps flickering in Chrome.

**Comment by akshaydewan** [comment]
Flickering is fixed as part of #5112. We can certainly improve the tooltip text as you suggested. Will make that change as well.

**Comment by rajiesh** [comment]
Verified on 18.8.0 (7433-4bf750d09bf4dba76a2b7ce0d72e88ecdfdbd96a)
