### ISSUE TITLE
[User Preferences page] Indefinite server requests when the user visits the page causes the GoCD server to be unresponsive

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5117]
##### Issue Type
- Bug Report
##### Summary

The user preference page makes indefinite server requests for `/go/api/current_user` and `/go/api/notification_filters`. This causes the server to be unresponsive.

###### Basic environment details

* Go Version: 18.8.0-7415
* JAVA Version: Java8
* OS: MacOs
* Browser vendor and version (if relevant): Chrome and firefox

##### Steps to Reproduce

1. Start your GoCD server with some authentication (e.g. file based)
2. Go to user preferences windows
3. Open the developer's console
4. Refresh the page. You will notice indefinite server requests.
5. Try editing anything on the page, UI will be unresponsive

##### Expected Results
the user should be able to interact with the UI as is and there should not be indefinite server calls

##### Actual Results
The UI becomes unresponsive and there are indefinite server calls being made
![user-preference-page](https://user-images.githubusercontent.com/17826464/44973657-f1a82680-af7a-11e8-999e-dc14ed72c248.gif)

**Comment by maheshp** [comment]
This issue was introduced in 18.7.0 and has been fixed in 18.8.0 as part of https://github.com/gocd/gocd/pull/5121

**Comment by rajiesh** [comment]
Verified on 18.8.0 (7433-4bf750d09bf4dba76a2b7ce0d72e88ecdfdbd96a
