### ISSUE TITLE
[Personalization View] Personalization filter tool tips break the view when there is a scroll

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5119]
##### Issue Type
- Bug Report
##### Summary

The tooltips on the personalization view filters break the view when there is a scroll.

###### Basic environment details

* Go Version:  18.8.0-7425
* JAVA Version: Java8
* OS: MacOs and Windows 8.1
* Browser vendor and version (if relevant): Chrome v67,v68, IE 11, Firefox
##### Steps to Reproduce

1. Create several pipelines and pipelines group such that there is a scroll in Create PV modal
2. Try expanding a group such that a scroll is introduced
3. The personalization view filter tooltips break the view

##### Expected Results
The tooltips should not break the view and is difficult to select the tooltip

##### Actual Results

The tooltips  breaks the view and is difficult to select the tooltip

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17826464/44978123-94ff3880-af87-11e8-960c-423c5be4b481.gif)

**Comment by akshaydewan** [comment]
I have a fix for this locally, will push it shortly
