### ISSUE TITLE
A section 'VSM Trend Across Multiple Runs' on VSM page is not pinned to screen when user scrolls the page

### ISSUE THREAD

**Issue by rahulpargaonkar** [gocd/gocd#5136]
##### Issue Type

- Bug Report

##### Summary
Currently, on VSM page, when user click on 'View Analytics' button then a section i.e. 'VSM Trend Across Multiple Runs' appears just below it and in which user can select a source or destination for particular pipeline in order to view VSM Analytics. 
But when user scroll down to below then the section disappears.

##### Environment

- Go Version: 18.8.0 (7421
- JAVA Version: Java8
- OS: MacOs
- Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

1.  Go to VSM of any Pipeline
2.  click on Analytics button, a  section i.e. 'VSM Trend Across Multiple Runs' appears just below to it
3.  move curser to that section and scroll down to see below.
4. The section mentioned in step 2 would disappears.

##### Expected Results
The Section below Analytics button should be pinned or sticked to the screen even though user scrolling down.

##### Actual Results
The Section below Analytics button is not pinned or sticked to the screen even though user scrolling down.

##### Screenshots

![vsm trends section is not pinned to screen](https://user-images.githubusercontent.com/33080845/45094972-78573200-b13a-11e8-8bc0-559ad22c78e5.gif)

**Comment by GaneshSPatil** [comment]
@rahulpargaonkar -- This issue has been fixed as part https://github.com/gocd/gocd/commit/91a0ef35a9cf9668a0d0b1e4c47c6fb10173a765 commit.

Verified on build.gocd.org
GoCD Version: 19.2.0 (8562-ab441595ee501940d050c10361728a11bbf02648).
