### ISSUE TITLE
[Backup via a cron] Update Server health message when the postbackup script is not present in the configured location

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5143]
##### Issue Type
- Bug Report

##### Summary
when the `postBackupScript` is not present, we say `Post backup script exited with an error, check the server log for details` whereas we could not run the script, server logs have the correct error `No such file or directory`, we should say the same in `serverHealthMessage`

###### Basic environment details

* Go Version: 18.9.0-7446
* JAVA Version: Java8
* OS: MacOs and Ubuntu 14.04
* Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

1. Configure a `postBackupScript` of a location where the file is not present
2. Trigger a backup (through UI/API/Cron)
3. Since the file is not the server health message is misleading
4. The server logs has the correct message pf file not present

##### Expected Results
The server health message should indicate that the file is not present

##### Actual Results
The server health message gives a generic message 'Post backup script exited with an error'

**Comment by ketan** [comment]
@adityasood — I don't believe this would be possible, without possibly breaking a lot of other things.

**Comment by jameszelada** [comment]
Where should the script be located?
