### ISSUE TITLE
[VSM Analytics] pipeline box is pinned wrongly on VSM analytics

### ISSUE THREAD

**Issue by rahulpargaonkar** [gocd/gocd#5150]
##### Issue Type

Bug Report

##### Summary

If a pipeline has multiple instances then it can be expanded to see more so the box would be bigger and in position user select this pipeline in order to view VSM analytics and clicks on VSM analytics button then currently the same pipeline box is pinned wrongly on VSM analytics page.

###### Basic environment details

- Go Version: 18.9.0 7457
- JAVA Version: Java8
- OS: MacOs
- Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

1.  Go to VSM of any pipeline & click on 'Analytics' button
2.  Select the pipeline who has multiple instances 
3.  click on VSM analytics button

##### Expected Results
pipeline box should not be appeared on VSM analytics page when reproduced by above mentioned steps

##### Actual Results
pipeline box wrongly appeared on VSM analytics page when reproduced by above mentioned steps

##### Code snippets/Screenshots

![pipeline box pinned on vsm analytics page](https://user-images.githubusercontent.com/33080845/45203825-034f3e00-b29b-11e8-93f2-495169b927bb.gif)

**Comment by GaneshSPatil** [comment]
This issue has been fixed as part of PR: https://github.com/gocd/gocd/pull/5148

**Comment by rahulpargaonkar** [comment]
The issue has been fixed.
