### ISSUE TITLE
Potential dashboard bug relating to MDU

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#5153]
##### Issue Type

- Bug Report

##### Summary + steps to reproduce

1. Create a pipeline - make sure it works.
2. Bring down the network (or somehow) make material check fail (preferably with a 403, but other statuses should be fine).
3. Trigger the pipeline.

In the dashboard, when you trigger, it’ll make the trigger and trigger with options buttons disabled.

But, it never seems to enable them again.

The errors and warnings modal will contain the MDU (material check) failure.

###### Basic environment details

* GoCD Version: `18.9.0 (7446-410d0db84e70331fb86f22d1e8f0abf02e1da183)`
* Browser vendor and version (if relevant): Firefox 61.0.2

##### Possible Fix

Maybe a missing event into the dashboard activity listener?

**Comment by arvindsv** [comment]
@adityasood Was this the issue you were talking about earlier?

**Comment by adityasood** [comment]
@arvindsv yes this what I also observed. The options remain disabled until after a user refreshes the browser window.

**Comment by adityasood** [comment]
verified on 18.11.0-7723
