### ISSUE TITLE
Configure data sharing over the API

### ISSUE THREAD

**Issue by dbalakirev** [gocd/gocd#5159]
##### Issue Type

- Feature enhancement

##### Summary

Recently the data sharing configuration was added to GoCD, enabled by default. We can turn it off on the GUI, but that is not the approach we try to follow (infra as code).

###### Basic environment details
* Go Version: 18.8

##### Expected Results
We would like to use the API to configure this. Is it possible to do this over the REST API? I did not find the proper way.

**Comment by ketan** [comment]
Hi there —

We missed out on documenting this API. We will document this API in a few hours from now. For now, you can send this HTTP request to disable/enable data collection:

```shell
curl https://ci.example.com/go/api/data_sharing/settings \
      -H 'Accept: application/vnd.go.cd.v1+json' \
      -H 'Content-Type: application/json' \
      -X PATCH \
      -d '{"allow": false}'
  ```

I'll keep the issue open while we document the API (and update the release notes).

**Comment by dbalakirev** [comment]
Thank you (especially for the super fast feedback)! We will use this approach. Cheers!

**Comment by arvindsv** [comment]
@dbalakirev FYI, the docs PR is https://github.com/gocd/api.go.cd/pull/245. You might want to take a look, because it seems that the PATCH call will need an `If-Match` header sent too, with the `ETag` from a `GET`. There's an issue opened now around it (https://github.com/gocd/gocd/issues/5162), which asks about removing that requirement.

**Comment by arvindsv** [comment]
@dbalakirev I'm going to close this - since there is a way to configure this using an API. #5162 will continue to be open, to decide whether we need to change the API a bit (to simplify it).

The documentation is now at: https://api.gocd.org/current/#data-sharing-settings

**Comment by dbalakirev** [comment]
Perfect, thank you.
