### ISSUE TITLE
Pipeline stages fail with no logs after nuget poller plugin upgrade

### ISSUE THREAD

**Issue by gauravnagar1981** [gocd/gocd#516]
Hi,

Whenever we upgrade nuget poller plugin any pipeline which have stages which are not triggered they all fail and if we go to logs there are no logs. Can you please investigate and look at it.
![go error](https://cloud.githubusercontent.com/assets/5796911/4285561/1a726b20-3d88-11e4-88d5-c8577180d54e.jpg)

**Comment by arvindsv** [comment]
Conversation did not go anywhere. No resolution. Closing.
