### ISSUE TITLE
Exception thrown by ldap plugin when passwordfile also configured

### ISSUE THREAD

**Issue by brydoncheyney-slc** [gocd/gocd#5163]
##### Issue Type

- Bug Report

##### Summary

Configuring both ldap authentication plugin and passwordfile authentication plugin will log errors in `plugin-cd.go.authentication.ldap.log` when authenticating using users stored in the password file.

When users are configured for repeated automated tasks (for example, build monitors polling the cctray every 10s) this results in huge amounts of errors logged.

###### Basic environment details

* Go Version: 18.8.0
* JAVA Version: 1.8.0_181
* OS: RHEL6

##### Steps to Reproduce

1. Configure config XML with auth plugins -
```
      <authConfigs>
        <authConfig id="..." pluginId="cd.go.authentication.ldap">
          ...
        </authConfig>
        <authConfig id="..." pluginId="cd.go.authentication.passwordfile">
          ...
        </authConfig>
      <authConfigs>
```
2. Authenticate using a user stored in a password file
3. Exception thrown
4. user authenticated against passwordfile

##### Expected Results

Authentication made using passwordfile plugin.

##### Actual Results

Exception thrown by ldap plugin.

##### Log snippets

```
2018-09-11 17:48:50,911 ERROR [qtp245475541-4927009] LdapPlugin:128 - [Authenticate] Failed to authenticate user build_monitor on ldaps://ldap-server.internal/.
java.lang.RuntimeException: User build_monitor does not exist in ldaps://ldap-server.internal/
        at cd.go.framework.ldap.Ldap.authenticate(Ldap.java:50)
        at cd.go.authentication.ldap.LdapAuthenticator.authenticateWithAuthConfig(LdapAuthenticator.java:58)
        at cd.go.authentication.ldap.LdapAuthenticator.authenticate(LdapAuthenticator.java:44)
        at cd.go.authentication.ldap.executor.UserAuthenticationExecutor.execute(UserAuthenticationExecutor.java:50)
        at cd.go.authentication.ldap.LdapPlugin.handle(LdapPlugin.java:69)
```

**Comment by brydoncheyney-slc** [comment]
This is actually down to the ordering of the authentication plugins... which makes sense. There's no way to ldap plugin can know if the user exists unless it attempts to authenticate against the ldap server.

If the authentication plugins are ordered `passwordfile` before `ldap` then the action of checking whether the user exists in the password file does not log an error if the user doesn't exist, before it attempts the next authentication plugin.

I couldn't see anywhere in the documentation of either the [gocd-ldap-authentication-plugin](https://github.com/gocd/gocd-ldap-authentication-plugin) or [GoCD](https://docs.gocd.org/current/configuration/dev_authentication.html) but if multiple authentication plugins are being used - and some of them will log errors on failed authentication before moving to the next - then this should be documented.

Happy for someone to close this and redirect the issue as a documentation issue - I'm not sure where that would be best placed?

**Comment by ankitsri11** [comment]
Raised a [PR/216](https://github.com/gocd/docs.go.cd/pull/216) to add note in the GoCD documentation. 

@arvindsv Can you review and close. Thanks.

**Comment by arvindsv** [comment]
Based on our conversation, I've made changes in gocd/docs.go.cd#217 and it's deployed to: https://docs.gocd.org/18.10.0/configuration/dev_authentication.html

I might backport it a bit. Closing this issue.
