### ISSUE TITLE
[Java-10-upgrade] Update startup scripts to include additional JVM arguments to run GoCD server with Java10

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5167]
##### Issue Type
- Bug Report
##### Summary
The startup scripts **server.sh** or **start-server.bat** should be able to identify the java version and pass on the additional JVM arguments for the GoCD server startup. For example to run the server on Java version>=9 following arguments need to be added 

` --add-modules=java.se,java.xml.bind,java.xml.ws.annotation`

###### Basic environment details

* Go Version:  18.10.0-7486
* JAVA Version:Java10
* OS: MacOs
* Browser vendor and version (if relevant): Chrome

**Comment by ketan** [comment]
This is no longer needed, I killed those dependencies.
