### ISSUE TITLE
[Java-10-upgrade] GoCD Server startup takes a while when running on latest Java versions

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5186]
##### Issue Type
- Bug Report

##### Summary

Running GoCD server with latest java versions seems to have increased the server startup time.

###### Basic environment details

* Go Version: 18.10.0-7490
* JAVA Version: Java10
* OS: MacOs
* Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce
1. Start GoCD by pointing Java_home to JDK10 and observe server startup time

##### Expected Results
This should be as quick as on earlier Java versions (Java8)

##### Actual Results
The server startup takes considerable time.

**Comment by bdpiparva** [comment]
I did some analysis about how much time application spends in loading the gems. Here is the list of gems and time it took to `require` the gem file in code.

### GoCD master with java 10

```
6.3538395    rails/commands
4.25942838    /Volumes/Data/Projects/go/gocd/server/webapp/WEB-INF/rails/config/application
1.40576754    /Volumes/Data/Projects/go/gocd/server/webapp/WEB-INF/rails/config/environment.rb
1.05031784    rails/application
0.83463815    jopenssl/load
0.64475424    rails/command
0.45724327    sprockets/rails/context
0.3905067    action_view/helpers/form_tag_helper
0.37713137    rails-html-sanitizer
0.37106503    loofah
0.33656476    nokogiri
0.27793345    active_support/railtie
0.27550661    active_support/i18n_railtie
0.26543561    sass/rails
0.2380521    active_support/logger
0.23224195    active_support/logger_silence
0.2172255    pry-debugger-jruby/cli
0.20391671    sass/engine
0.19893045    nokogiri/nokogiri
0.19816351    pry-debugger-jruby/pry_ext
0.19568753    pry
0.15394253    jasmine/runners/selenium
0.15258118    selenium-webdriver
0.15166421    selenium/webdriver
0.1346995    action_controller
0.12901526    rails/configuration
0.12808214    psych
0.12560953    selenium/webdriver/common
0.12497371    active_support/core_ext/object
0.1158011    thor/base
0.10193219    sprockets/environment
0.09224157    thor/line_editor
===========================
Total time  24.617 seconds
Total files loaded 1267
```

Rest of the files has a load time of 0.0x seconds hence I ignored it from listing.

Note: in above example `rails/commands` is loaded twice.

--- 

### GoCD 18.8.0 with Java 1.8

with old application load time of gem file was very low.

```
0.995    rails/application
0.723    active_support/key_generator
0.72    openssl
0.719    jopenssl/load
0.267    rails/engine
0.212    sass/rails
0.209    active_support/core_ext/object
0.174    nokogiri/nokogiri
0.159    sass/engine
0.153    sprockets/rails/helper
0.12    active_support/core_ext/object/conversions
0.093    rspec/core
===============================
Total time   7.638 seconds
Total files loaded 911
```

**Comment by bdpiparva** [comment]
## Result from jruby profiler

In following results we noticed that first 3 row in the list has double number of calls in new application.

### GoCD master with java 10

main profile results:
Total time: 7.92

     total        self    children       calls  method
----------------------------------------------------------------
      7.64        0.04        7.60        7366  Kernel.require
      6.35        0.00        6.35        2302  #<Class:0x84f0686>#require
      6.35        0.00        6.35        4604  Benchmark.realtime
      5.71        0.00        5.71           1  Rails::Command.invoke
      5.68        0.00        5.68           1  Rails::Command::Base.perform
      5.68        0.00        5.68           1  Thor.dispatch
      5.67        0.00        5.67           1  Thor::Invocation.invoke_command
      5.67        0.00        5.67           1  Thor::Command#run
      5.67        0.00        5.67         359  BasicObject#__send__
      5.67        0.00        5.67           2  Rails::Command::RunnerCommand#perform
      5.67        0.00        5.67           1  Rails::Command::Actions.require_application_and_environment!
      2.93        0.05        2.88        9026  #<Class:0x7b6846c6>#each
      2.01        0.00        2.01          43  Kernel.require_relative
      1.55        0.18        1.37          52  Kernel.load
      1.42        0.00        1.42           9  TSort.tsort_each
      1.42        0.00        1.42           5  TSort.each_strongly_connected_component
      1.42        0.00        1.42         370  Method#call
      1.42        0.00        1.42         365  TSort.each_strongly_connected_component_from
      1.41        0.00        1.41           1  Rails::Application#require_environment!
      1.40        0.00        1.40           1  Rails::Application#initialize!
      1.40        0.00        1.40           1  Rails::Initializable.run_initializers
      1.38        0.00        1.38           1  TSort.tsort_each
      1.34        0.00        1.34          97  Rails::Initializable::Initializer#run
      1.34        0.03        1.31         102  BasicObject#instance_exec
      1.05        0.00        1.04         264  ActiveSupport::Dependencies::Loadable.load_dependency
      0.98        0.00        0.98           1  Bundler.require
      0.98        0.00        0.98           1  Bundler::Runtime#require
      0.94        0.00        0.94       69329  Kernel.send
      0.93        0.00        0.93          15  ActiveSupport::Dependencies::Loadable.load
      0.90        0.00        0.90         113  Kernel.require
      0.90        0.01        0.89       61844  Proc#call
      0.86        0.14        0.73       14827  Class#new
      0.82        0.00        0.82           2  ActiveSupport::FileUpdateChecker#execute
      0.82        0.00        0.82           1  Rails::Application::RoutesReloader#execute
      0.82        0.00        0.82           1  Rails::Application::RoutesReloader#reload!
      0.82        0.00        0.82           5  #<Class:0x71103416>#eval_block
      0.80        0.00        0.80           1  Rails::Application::RoutesReloader#load_paths
      0.79        0.00        0.79           1  #<Class:0x71103416>#draw
      0.77        0.00        0.76         336  ActionDispatch::Routing::Mapper::Resources.match
      0.76        0.01        0.75         336  ActionDispatch::Routing::Mapper::Resources.map_match
      0.75        0.00        0.75         325  ActionDispatch::Routing::Mapper::HttpHelpers.map_method
      0.75        0.75        0.00         388  Java::JavaPackage#method_missing
      0.73        0.00        0.73         338  ActionDispatch::Routing::Mapper::Resources.decomposed_match
      0.73        0.00        0.72         336  ActionDispatch::Routing::Mapper::Resources.add_route
      0.71        0.00        0.71           2  Bundler.setup
      0.63        0.62        0.01           1  Java::OrgJrubyExtOpenssl::OpenSSL.load
      0.46        0.00        0.46           1  Bundler::Runtime#setup
      0.44        0.00        0.44         183  ActionDispatch::Routing::Mapper::HttpHelpers.get
      0.42        0.00        0.42         336  #<Class:0x71103416>#add_route
      0.41        0.00        0.41           1  Bundler::Runtime#requested_specs



### GoCD v18.8.0

main profile results:
Total time: 4.23

     total        self    children       calls  method
----------------------------------------------------------------
      4.07        0.04        4.02        4841  Kernel.require
      2.64        0.00        2.64        1483  Object#require
      2.64        0.00        2.64        2966  Benchmark.realtime
      1.42        0.02        1.41        3652  Array#each
      1.20        0.00        1.20           1  Bundler.require
      1.20        0.00        1.20           1  Bundler::Runtime#require
      0.87        0.00        0.87          50  Kernel.require_relative
      0.78        0.00        0.78         142  Kernel.require
      0.72        0.03        0.69          35  Kernel.load
      0.68        0.00        0.68         455  ActiveSupport::Dependencies::Loadable.require
      0.68        0.00        0.68         455  ActiveSupport::Dependencies::Loadable.load_dependency
      0.62        0.62        0.00           1  Java::OrgJrubyExtOpenssl::OpenSSL.load
      0.52        0.00        0.52           2  Bundler.setup
      0.42        0.02        0.40        4371  Class#new
      0.31        0.00        0.31           2  Bundler.definition
      0.25        0.00        0.24           1  Bundler::Definition.build
      0.24        0.00        0.24           1  Bundler::Dsl.evaluate
      0.21        0.00        0.21           1  Bundler::Runtime#setup
      0.18        0.00        0.18           1  Bundler::Dsl#initialize
      0.18        0.00        0.18           1  Bundler::Environment#requested_specs
      0.18        0.00        0.18           1  Bundler::Definition#requested_specs
      0.18        0.00        0.18           1  Bundler::Definition#specs_for
      0.18        0.00        0.17           1  Bundler::SourceList#initialize
      0.17        0.00        0.17           1  Bundler::Definition#specs
      0.15        0.14        0.01        9726  Hash#[]=
      0.13        0.00        0.13           1  Bundler::SpecSet#materialize
      0.13        0.00        0.13         838  Array#map!
      0.13        0.01        0.12        1792  Array#map
      0.12        0.00        0.12          73  Bundler::LazySpecification#__materialize__
      0.12        0.00        0.11         957  Kernel.send
      0.11        0.00        0.11          75  Bundler::Source::Rubygems#specs
      0.11        0.00        0.11           1  Bundler::Source::Rubygems#installed_specs
      0.11        0.00        0.11           1  Bundler::RubygemsIntegration::Future#all_specs
      0.11        0.00        0.11           1  Enumerable.to_a
      0.11        0.00        0.11          84  Gem::Specification.load
      0.11        0.00        0.11           1  Gem::Specification.each
      0.11        0.00        0.11           1  Gem::Specification._all
      0.10        0.00        0.10           5  IO.open
      0.09        0.00        0.09         931  Proc#call
      0.09        0.00        0.09          80  Gem::StubSpecification#to_spec
      0.09        0.00        0.09           2  Rails::Engine.isolate_namespace
      0.08        0.00        0.08           2  Rails::Railtie::Configurable::ClassMethods.method_missing
      0.08        0.00        0.08           2  Rails::Engine#routes
      0.08        0.00        0.08          38  RSpec::Support.require_rspec_core
      0.08        0.08        0.00          44  JavaUtilities.get_proxy_or_package_under_package
      0.08        0.00        0.08           3  Gem::Specification.each_gemspec
      0.07        0.03        0.05         209  Kernel.eval
      0.06        0.06        0.00         164  File#initialize
      0.06        0.06        0.00         116  Kernel.caller
      0.06        0.01        0.04          91  BasicObject#instance_eval

**Comment by bdpiparva** [comment]
## GoCD Master

### Stratup time results
On `Java 10` subsequent startup time(in millis) is  94807, 93864, 106469

### Spring init time
Time 26.865 seconds


### LoadService Time
- Time: 64.770 seconds
- Services found: 225
- Tried loading services(builtinLib, fileResource): 71579

```
29238 - [main] org.jruby.runtime.load.LoadService:80 - trying builtinLib: jruby/kernel/jruby/type.rb
29238 - [main] org.jruby.runtime.load.LoadService:80 - trying fileResource: uri:classloader:/META-INF/jruby.home/lib/ruby/2.5/site_ruby/jruby/kernel/jruby/type.rb
29239 - [main] org.jruby.runtime.load.LoadService:80 - trying fileResource: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jruby/kernel/jruby/type.rb
29239 - [main] org.jruby.runtime.load.LoadService:80 - trying fileResource: ./jruby/kernel/jruby/type.rb
29239 - [main] org.jruby.runtime.load.LoadService:80 - trying fileResource: uri:classloader:/jruby/kernel/jruby/type.rb

```

Here Loadservice is took about 64 seconds and most of the time it spend loading following services

1. cparse-jruby.jar -> 7.277 seconds
2. giber.rb   -> 32.00 seconds



## GoCD 18.9

### Stratup time
On `Java 1.8` subsequent startup time(in millis) is  44634, 38723

### Spring init time
21.036 seconds

### LoadService Time
- Time: 16.831 seconds
- Services found: 1430
- Tried loading services(builtinLib, fileResource): 73198

```
2018-10-05T14:42:12.647+05:30: LoadService: trying builtinLib: rubygems/deprecate.rb
2018-10-05T14:42:12.647+05:30: LoadService: trying fileResource: file:/private/tmp/work/go-server-18.9.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/lib/jruby-complete-1.7.26.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby/rubygems/deprecate.rb
2018-10-05T14:42:12.647+05:30: LoadService: trying fileResource: file:/private/tmp/work/go-server-18.9.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/lib/jruby-complete-1.7.26.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/deprecate.rb
2018-10-05T14:42:12.647+05:30: LoadService: found fileResource: file:/private/tmp/work/go-server-18.9.0/work/jetty-0.0.0.0-8153-cruise.war-_go-any-/webapp/WEB-INF/lib/jruby-complete-1.7.26.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/deprecate.rb

```
