### ISSUE TITLE
Bug: Fetch external artifact - does not validate

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#5194]
##### Issue Type

- Bug Report

##### Summary

If you have a fetch external artifact plugin and you've set it up to [validate configuration during fetch artifact](https://plugin-api.gocd.org/current/artifacts/#validate-fetch-artifact-config), it never makes that call, when creating or editing a fetch artifact task from the UI.

###### Basic environment details

* Go Version: 18.9.0
* JAVA Version: 1.8

##### Steps to Reproduce

1. Use this plugin tree: https://github.com/sheroy/docker-registry-artifact-plugin/tree/master
2. Use this tree for GoCD codebase: https://github.com/arvindsv/gocd/tree/allow-artifact-plugins-to-introduce-new-env-vars (or use your own, but have a plugin which validates fetch artifact view - the current, stable docker registry artifact plugin does not).
3. Create a fetch artifact task. Put in a space in the prefix field (of the custom plugin).
4. Save.
5. Edit the task.
6. Save.

##### Expected Results

No validation message shows up.

##### Possible Fix

It's a bug. The fix for update, at least, looks [something like this](https://github.com/arvindsv/gocd/commit/86085544f13c6d044e5cb034a9e1bc14c2cdbcf4#diff-769ff536bbe6d6eeca69644673260d6c), but I haven't been able to get the specs to pass. There were no specs testing this functionality.

##### Any other info

Config to use:
```xml
<?xml version="1.0" encoding="utf-8"?>
<cruise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="cruise-config.xsd" schemaVersion="113">
  <server artifactsdir="artifacts" agentAutoRegisterKey="2b110569-cf92-40ff-af9d-cc89fc6f2d70" webhookSecret="627843e4-b257-469a-84ae-5b6dfffcc506" commandRepositoryLocation="default" serverId="bd42e53a-f5e1-4e07-9600-9df205a5b409" tokenGenerationKey="37ad75a4-0e64-47eb-a831-5f7b4558534c">
    <backup emailOnSuccess="true" emailOnFailure="true" />
  </server>
  <artifactStores>
    <artifactStore id="abc" pluginId="cd.go.artifact.docker.registry">
      <property>
        <key>RegistryURL</key>
        <value>https://index.docker.io/v1/</value>
      </property>
      <property>
        <key>Username</key>
        <value>your-username</value>
      </property>
      <property>
        <key>Password</key>
        <value>Your password</value>
      </property>
    </artifactStore>
  </artifactStores>
  <pipelines group="defaultGroup">
    <pipeline name="Abc">
      <materials>
        <git url="git@github.com:arvindsv/faketime.git" />
      </materials>
      <stage name="stage1">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
            <artifacts>
              <artifact type="external" id="abcdef" storeId="abc">
                <configuration>
                  <property>
                    <key>BuildFile</key>
                    <value />
                  </property>
                  <property>
                    <key>Image</key>
                    <value>sheroy/bulletin-board</value>
                  </property>
                  <property>
                    <key>Tag</key>
                    <value>v${GO_PIPELINE_COUNTER}</value>
                  </property>
                </configuration>
              </artifact>
            </artifacts>
          </job>
        </jobs>
      </stage>
      <stage name="stage2">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <fetchartifact artifactOrigin="external" artifactId="abcdef" pipeline="Abc" stage="stage1" job="defaultJob">
                <configuration>
                  <property>
                    <key>EnvironmentVariablePrefix</key>
                    <value>THIS HAS A SPACE</value>
                  </property>
                </configuration>
                <runif status="passed" />
              </fetchartifact>
              <exec command="/bin/bash">
                <arg>-c</arg>
                <arg>env</arg>
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
</cruise>
```

**Comment by varshavaradarajan** [comment]
@arvindsv - no plugin validations happen when directly editing the XML. The reason being that validations for _all_ plugins must happen while directly editing the xml. This could delay config save. And at server startup if the plugin is missing, then, it backtracks to a valid version of config xml in config.git which could result in loss of config. The validation call happens for when the task config is edited through the UI and the API. I checked  https://github.com/sheroy/docker-registry-artifact-plugin/tree/environment_variables_after_fetch and did not find that the fetch artifact view has been changed and so, assumed that the bug you reported is for config XML. Can you clarify the config save method?

**Comment by arvindsv** [comment]
@varshavaradarajan Sorry, I linked to the wrong branch. It's on master.

https://github.com/sheroy/docker-registry-artifact-plugin/tree/master

It does not call it, when called from the UI. [These changes](https://github.com/arvindsv/gocd/commit/86085544f13c6d044e5cb034a9e1bc14c2cdbcf4#diff-769ff536bbe6d6eeca69644673260d6c) make it work (only update, I didn't fix create).
