### ISSUE TITLE
Support Btrfs quotas

### ISSUE THREAD

**Issue by guedressel** [gocd/gocd#5196]
##### Summary

Query [Btrfs quotas](https://btrfs.wiki.kernel.org/index.php/Quota_support) for artifacts storage disk usage calculation - if storage resides within a btrfs mountpoint.

##### Our use case

Our agents run on `btrfs` file systems. Though Btrfs allows to control usage quotas quite granular it is useless for us since gocd is not querying the quota rules and just runs blindly into "disk full" situations when quota limits reached.

###### Basic environment details

* Go Version: 18.3.0 (6540-1e79bb6dc4f01f6ccd71c2b5aa0fbefa0b3eb92d).
* JAVA Version: 1.8.0_151
* OS: Linux 4.4.0-101-generic

**Comment by arvindsv** [comment]
This is too filesystem-specific a request, unfortunately. ZFS and every other modern filesystem has different ways of implementing quotas. Java provides [a FileSystem class](https://docs.oracle.com/javase/10/docs/api/java/nio/file/FileSystem.html), but doesn't seem to allow accessing quotas or limits through it.

Maybe you can use GoCD's [artifact purge limits](https://docs.gocd.org/current/configuration/delete_artifacts.html)?

Also, as an aside: You mentioned agents, but artifact storage happens on GoCD server side.

Closing as wont-fix.

**Comment by guedressel** [comment]
Regarding purge limits: that's exactly the issue - GoCD seems to see a lot of free space which actually isn't available because of quota limits - hence GoCD doesn't trigger purging of artifacts before the quota limit is reached.
