### ISSUE TITLE
Increase meta-space to 400mb?

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5211]
##### Issue Type

I remember @rajiesh mentioning that the perf runs required the meta-space to be set to 400mb with newer jruby+rails+java. Might need to bump up the default value in the shell, batch and wrapper-server.conf files. Look for `MaxMetaspaceSize` in the code.

**Comment by maheshp** [comment]
Done in https://github.com/gocd/gocd/pull/5213

**Comment by rajiesh** [comment]
Verified on 18.10.0 (7698-96e8d80a2107afb6e78e79fe8a4cca60403e97af)
