### ISSUE TITLE
Pause, unpause, trigger of Pipeline is broken on Pipeline History Page

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5217]
##### Issue Type
- Bug Report
##### Summary

The trigger pipeline and pause-unpause pipeline functionality is broken on pipeline history page. The API triggered for the functions return `404`. This could be caused due to the changes made as part if this PR https://github.com/gocd/gocd/pull/4827

###### Basic environment details

* Go Version: 18.10.0 -7575
* JAVA Version: Java10
* OS: MacOs
* Browser vendor and version (if relevant): Chrome69

##### Steps to Reproduce

1. Naviagte to history page of a manual pipeline
2. Try pausing the pipeline. Inspect and see network console
3. Try triggering the pipeline. Inspect and see network console
4. Pause pipeline from the pipeline dashboard page. Visit pipeline history page and try unpausing the pipeline.

##### Expected Results
The pause and trigger actions should work as exepected.

##### Actual Results
The actions are not being executed as the API call returns `404`

##### Possible Fix
Change the usages of these actions to utilize the new API's

**Comment by maheshp** [comment]
Fixed by https://github.com/gocd/gocd/pull/5219

**Comment by adityasood** [comment]
Verified the fix. Closing this issue.
