### ISSUE TITLE
Graceful shutdown of Docker GoCD agent

### ISSUE THREAD

**Issue by MPV** [gocd/gocd#5218]
##### Issue Type

- Feature proposal / Feature enhancement

##### Summary

Today when using Docker containers for GoCD agents, they can auto-register themselves, but before shutting down the containers they currently don't disable/remove themselves.

Also, it might be nice if they attempt to finish ongoing jobs before shutting down.

##### Steps to Reproduce

1. Set up GoCD server + agents in Kubernetes (using static/non-elastic agents).
2. Assign long-running jobs to all agents.
3. Make changes to the chart values for the agents (let's say decreasing the `replicaCount`).
4. Do an upgrade of the helm release.
5. A rolling update starts (as per [rolling update deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#rolling-update-deployment)).
6. The Kubernetes pods with the containers for the old abundant GoCD agent(s) are asked to shut down.

##### Expected Results

The abundant GoCD container:

A) ...receives SIGTERM but keeps running until it's finished its ongoing pipeline jobs.
B) ...marks itself as `Disabled` on the GoCD server.
C) ...removes itself from the GoCD server agents list. (optionally?)

##### Actual Results

The abundant GoCD container:

A) ...receives SIGTERM and shuts down despite running a job.
B) ...eventually becomes `Idle` / `LostContact` on the GoCD server.
C ...stays around in the GoCD server agents list.

##### Possible Fix

What do you think of this flow for solving this?

1. The abundant agent pod is asked to shut down.
2. Inside the pod, this happens:
2.1. SIGTERM received.
2.2. Tell GoCD server to disable this agent (itself).
2.3. Loop:
2.3.1. Ask GoCD server if I am `Idle`.
2.3.2. If I'm running jobs, keep waiting (~5 sec back-off).
2.4. Tell GoCD server to delete this agent.
2.5. Send SIGTERM to the working process (`tini`/`gosu`/`agent-bootstrapper.jar` or just kill `PID 1`?)
3. The abundant agent pod dies, rollout complete.

##### Any other info

Some hints on how graceful shutdown happens in Kube:
https://pracucci.com/graceful-shutdown-of-kubernetes-pods.html

I'm thinking that the container could trigger "disable myself + finish ongoing jobs" when receiving a `SIGTERM` — but after the grace period (`spec.template.spec.terminationGracePeriodSeconds` in the Deployment) it would just kill itself instead.

**Comment by MPV** [comment]
...maybe by adding some code in [`docker-entrypoint.sh`](https://github.com/gocd/docker-gocd-agent/blob/master/docker-entrypoint.sh.erb) that does this?

A rough draft:

```bash
disable_agent() {
    curl -s -X PATCH "$GO_SERVER_URL/api/agents/$AGENT_UUID" \
    -H 'Accept: application/vnd.go.cd.v4+json' \
    -H 'Content-Type: application/json' \
    -u "$GOCD_ADMIN_USERNAME:$GOCD_ADMIN_PASSWORD" \
    -d '{
          "agent_config_state": "Disabled"
        }'
}

wait_until_agent_disabled_and_idle() {
    # ...curl API and check if this agent has `agent_config_state = Disabled` and `agent_state = Idle`.
    # ...back-off/wait a few seconds and loop.
}

kill_gocd_agent_process() {
    kill -- -$$ # sends SIGTERM to child/sub processes
    # ...or whichever way you think makes sense?
}

delete_agent() {
    # TODO: ...lookup out agent uuid...
    curl -s -X DELETE "$GO_SERVER_URL/api/agents/$AGENT_UUID" \
    -H 'Accept: application/vnd.go.cd.v4+json' \
    -H 'Content-Type: application/json' \
    -u "$GOCD_USERNAME:$GOCD_PASSWORD"
}

gracefully_shutdown_gocd_agent() {
    disable_agent
    wait_until_agent_disabled_and_idle
    kill_gocd_agent_process
    delete_agent
}

kill_gocd_agent() {
    disable_agent
    kill_gocd_agent_process
    delete_agent
}

# Shut down gracefully if given SIGTERM:
trap gracefully_shutdown_gocd_agent SIGTERM

# Shut down quickly if given SIGKILL:
trap kill_gocd_agent SIGKILL
```

**Comment by balboah** [comment]
Here is a lifecycle docker that solves this problem when using a docker in docker agent together with kubernetes preStop lifecycle: https://github.com/pagero/gocd-lifecycle

But I would expect the agent itself to also implement graceful shutdown when receiving SIGTERM

**Comment by varshavaradarajan** [comment]
Since EA plugins handle termination of containerized agents gracefully and the above issue of k8s is addressed by https://github.com/helm/charts/pull/12008, closing this. Please re-open if needed.
