### ISSUE TITLE
include all the branches in Material

### ISSUE THREAD

**Issue by renaldrozario** [gocd/gocd#5229]
Have been using GoCD v16.12 for a while now and in need of testing an use case for building an app from various branches. I am aware that we can specify one branch in material. Is there a way to mention the branch value with regexp? This feature is available in other CI's . would like to know if this is supported in GoCD?

**Comment by ankitsri11** [comment]
Currently, you can only track one branch per material. However, you can use [this](https://github.com/ashwanthkumar/gocd-build-github-pull-requests#gocd---git-feature-branch-support) SCM plugin to track other Git branches of the same material. This also support glob syntax (*, ?, [...], {...}) and multiple branch patterns can be given as a comma-separated list.

**Comment by DennisBoege** [comment]
Is it posible to bring this very helpful feature on 18.12 ?
