### ISSUE TITLE
Question regarding systemd service files

### ISSUE THREAD

**Issue by mkrogemann** [gocd/gocd#523]
I have written systemd service files for go-agent and go-server. The need arose when I installed both products on a CentOS 7 box (same would work on RHEL 7).
I am happy to share these but I am not sure that I can put in enough testing on real systems to confidently include the files in the RPM spec for automatic installation.
Maybe adding them to the documentation would be appropriate?
What is your view?

**Comment by arvindsv** [comment]
Conversation did not happen. Closing this. We should test the installers with a newish distribution with systemd as the default, if we're not. @rajiesh, is this being done as a part of the automated installer tests?
