### ISSUE TITLE
Broken css on elastic profiles page

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5254]
##### Issue Type

- Bug Report

##### Summary

<img width="1000" alt="screen shot 2018-10-10 at 2 41 22 pm" src="https://user-images.githubusercontent.com/10598/46767754-bc3dd980-cc9a-11e8-8e04-0eaf74a79915.png">

**Comment by rajiesh** [comment]
Verified on 18.10.0 (7698-96e8d80a2107afb6e78e79fe8a4cca60403e97af)
