### ISSUE TITLE
Go.cd pipelines console has "localhost:8153" in URLs for links instead of server FQDN

### ISSUE THREAD

**Issue by jsilverman-blispay** [gocd/gocd#5271]
##### Issue Type

Go.cd UI has "localhot" URLs for some links, but correct server FQDN URLs for others

- Bug Report

##### Summary

The UI on our Go.cd server has the correct FQDN URLs for links "History" and on the pipeline stages (the green/yellow/red boxes)

However, the UI has "localhost:8153" for the "Compare" and "VSM" links -- in the same Pipeline tile.

We have our Go server behind a reverse proxy. I've read some docs to "fix" the link by adding additional headers to the rp but this seems like as bug in that some, but not all, links are correct.

##### Environment

I'm not sure which details are most relevant here, and the /support output is **huge**

###### Basic environment details

* Go Version: `18.9.0`
* JAVA Version: `1.8.0_181`
* OS: `Linux 4.15.0-36-generic` (Ubuntu 18.04)

###### Additional Environment Details
I'm currently using the following nginx rp config for this host:

```
server {
    listen 443 ssl;

    server_name <server_fqdn>;

    ssl_certificate /path/to/certificate.crt;
    ssl_certificate_key /path/to/certificate.key;
    ssl_password_file /path/to/certificate.key.pass;
    ssl_trusted_certificate /path/to/ca_certificate.crt;
    ssl_protocols TLSv1.2;
    ssl_prefer_server_ciphers on;

    client_max_body_size 100M;

    location / {
        proxy_pass http://localhost:8153;
    }
}
```

##### Steps to Reproduce

1. Go to Go.cd "Pipeline" page (https://<server_fqdn>/go/pipelines#!/)
2. Examine URL under links for
    * History
    * VSM
    * Compare
3. Note that URL has "localhost:8153" not "<server_fqdn>"

##### Expected Results
Link URLs should all have "<server_fqdn>"

##### Actual Results
described above

##### Possible Fix
na

##### Log snippets
na

##### Code snippets/Screenshots
na

##### Any other info
This was working until we upgraded to 17 (from 16) in July

Also, it strikes me as weird that *some* of the links are fine while some are noet

**Comment by arvindsv** [comment]
@jsilverman-blispay Have you configured [site URLs](https://docs.gocd.org/current/installation/configuring_server_details.html#configure-site-urls)?

**Comment by ketan** [comment]
@jsilverman-blispay You need to ensure to forward the `Host`, `X-Forwarded-For` and `X-Forwarded-Proto` headers. Without these headers, the server does not know what the incoming hostname is. See https://docs.gocd.org/current/installation/configure-reverse-proxy.html#gocd-with-nginx.

I'm marking this as closed, but if the NGINX config in the document does not work, please let me know, and I can re-open this issue.
