### ISSUE TITLE
Simplify release activity pipelines

### ISSUE THREAD

**Issue by vishaldevgire** [gocd/gocd#5273]
1. Create a separate jobs in a pipeline for bumping up various docs versions:
   - docs.go.cd
   - developer.go.cd
   - api.go.cd
   - plugin-api.go.cd
   - extension-docs.go.cd

2. Create a docs pipeline in a separate job for each of the following:
   - docs.go.cd
   - developer.go.cd
   - api.go.cd
   - plugin-api.go.cd
   - extension-docs.go.cd

2. Simplify Publish Cloud based Artifact pipeline
   - Autodetect installer version from `version.json` from upstream pipeline

3. Github credentials are provided at multiple places in single pipeline.

4. All release activity related scripts should be in a single repository

**Comment by adityasood** [comment]
@vishaldevgire @bdpiparva can we make this a checklist and track what all has already been done. We can close this if everything was implemented

**Comment by bdpiparva** [comment]
@adityasood - This is done. Closing the issue.
