### ISSUE TITLE
Document dashboard v2 (and deprecate v1)

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5276]
We've had the v2 in production since the new dashboard came out, as such, I feel it's time to christen this as "api" and sunset the rails based v1 api.

**Comment by GaneshSPatil** [comment]
@ketan -- We definitely should. we were waiting for some [cleanup](https://github.com/gocd/gocd/issues/4121) on Dashboard API v2.
Once that is done, we can announce the API v2.

Also, going to job-details-page directly from the dashboard can cause the response to change slightly. We can wait for this to be picked-up and done or we can make v3 later if required.

**Comment by GaneshSPatil** [comment]
[Dashboard API v2](https://api.gocd.org/18.12.0/#dashboard) has been documented as part of V2, with the fixes mentioned as part issue: https://github.com/gocd/gocd/issues/4121.
