### ISSUE TITLE
GoCD server sends notifications to disabled users

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5277]
##### Issue Type
- Bug Report

##### Summary

If a user is disabled within GoCD, the server still sends notifications based on user preferences. Disabled users should not get email notifications.

###### Basic environment details

* Go Version: 18.10.0-7703
* JAVA Version: Java10
* OS: MacOs
* Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

1. Create a user "emailUser" within GoCD using an authentication plugin
2. Login as emailUser and set preferences to receive notifications for a pipeline run
3. Login as GoCD server admin and disable the emailUser from Admin -> User Summary
4. Trigger the pipeline for which emailUser subscribed for.
5. You will receive email notifications for the disabled emailUser

##### Expected Results
The server should check for disabled users before sending notifications

##### Actual Results
The server today sends notifications to all subscribed users

**Comment by bdpiparva** [comment]
This is a bug with GoCD server. The server always sends a notification to all the users having notification enabled.

**Comment by adityasood** [comment]
Fixed by https://github.com/gocd/gocd/pull/5279

**Comment by adityasood** [comment]
verified on 18.11.0 (7724-49d741308cbbb499554e4e2843f0812e2e9b8460).
