### ISSUE TITLE
Make sure cache key generated using pipeline name, stage name and job name should be  case insensitive.

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#5303]
##### Issue Type

- Bug Report

##### Summary
Cache key generation is case sensitive that means if pipeline name, stage name of job name is submitted in the different case while making API calls can end up corrupting in-memory cache.

For example, cache key generated using the following code will generate different if pipeline name or stage name is submitted in a different case.

- [x] Fix cache key generation for stage history(#5295)

**Comment by maheshp** [comment]
Fixed by https://github.com/gocd/gocd/pull/5295

**Comment by rajiesh** [comment]
Verified on 18.11.0 (7922-f0e186d3909c6e86817d05ec6a6f903df6324f9a)
