### ISSUE TITLE
"Auto delete artifacts" broken! Purges newest artifacts first

### ISSUE THREAD

**Issue by sailtwist** [gocd/gocd#531]
"Auto delete artifacts" features is enabled.
Stage 1 configured to archive artifacts.
Stage 2 configured to fetch archived artifacts
WHEN out of space on server (where artifacts are stored), purge kicks off and deletes Stage 1 artifacts
Stage 2 fails!

In my opinion "Auto delete artifacts" is broken because it causes my pipelines to fail when artifacts store is out-of-space.

**Comment by hcsaustrup** [comment]
We're seeing issues with GoCD being unable to see old artifacts when attempting to purge, and - as a result - it purges the newly created to free up space. Artifacts are still available when browsing old builds, so it appears that GoCD is keeping track on artifacts in a couple of different ways, and at leat one of those ways broke at some point - possibly when we updated GoCD and switched from H2 to Postgres. Deleting old artifacts seems like the only way out.
