### ISSUE TITLE
Cannot fetch artifacts from multiple agents

### ISSUE THREAD

**Issue by Caian** [gocd/gocd#5346]
##### Issue Type

- Bug Report

##### Summary

I have a Pipeline with 2 stages and one job each. Stage 1 executes for each agent in the environment and produce non-conflicting uniquely identifiable data that I must pass on to Stage 2 so it can be processed altogether in a single agent. Each agent has a different set of resources.

In my first Stage, I save my artifacts from `data/*` to the destination `data/`, and I can confirm this is working because I can check the artifacts for each individual agent after the Stage completes:

The problem is retrieving this data in the next Stage, I am using a Fetch Artifact task with the Source field configured as `data/` because that's the destination directory in the previous Stage, but I am having the following error in the agent when I run the Pipeline (I edited out sensitive information):

```
[go] Could not fetch artifact <my server>/go/remoting/files/artifact_test_pipeline/10/build/latest/build/data/.zip. Pausing 10 seconds to retry. Error was : Unsuccessful response '404' from the server
[go] Could not fetch artifact <my server>/go/remoting/files/artifact_test_pipeline/10/build/latest/build/data/.zip. Pausing 27 seconds to retry. Error was : Unsuccessful response '404' from the server
[go] Could not fetch artifact <my server>/go/remoting/files/artifact_test_pipeline/10/build/latest/build/data/.zip. Pausing 38 seconds to retry. Error was : Unsuccessful response '404' from the server
[go] Failed to save artifact [data] to [data/]
```

It is important to note that the pipeline **succeeds** if I run the first stage in a single agent only.

###### Basic environment details

I am using the server and agent dockers :

- `gocd/gocd-server:v18.7.0`
-  `gocd/gocd-agent-ubuntu-16.04:v18.7.0`

* Go Version: `18.7.0 (7121-75d1247f58ab8bcde3c5b43392a87347979f82c5)`
* JAVA Version: `1.8.0_171`
* OS: `Linux 4.4.0-137-generic`

##### Steps to Reproduce

1. Create an environment;
2. Add more than one agent to that environment;
3. Export a variable in each environment so it can be uniquely identifiable (e.g. BUILD_UID);
3. Create a pipeline associated with that environment;
4. Add a stage with a single job set to run on all agents;
5. Add a script task that creates a directory "data" and a test file "$BUILD_UID" in that directory;
6. Configure the artifacts for the jobs so the source is `data/*` and the destination is `data/`;
7. Add another stage with a single job that runs on a single agent;
8. Add a Fetch Artifact task pointing to the job of the previous stage and whose source is the directory `data/`;
9. Execute the pipeline.

##### Expected Results

The job in the second stage should be able to access the `data` directory with the artifacts generated from all of the agents executed in the previous stage.

##### Actual Results

The second stage fails because of the following error (I edited out sensitive information):

```
[go] [WARN] The md5checksum property file was not found on the server. Hence, Go can not verify the integrity of the artifacts.
[go] Could not fetch artifact https://<my server>/go/remoting/files/artifact_test_pipeline/12/build/latest/build/data/.zip. Pausing 19 seconds to retry. Error was : Unsuccessful response '404' from the server
[go] Could not fetch artifact https://<my server>/go/remoting/files/artifact_test_pipeline/12/build/latest/build/data/.zip. Pausing 21 seconds to retry. Error was : Unsuccessful response '404' from the server
[go] Could not fetch artifact https://<my server>/go/remoting/files/artifact_test_pipeline/12/build/latest/build/data/.zip. Pausing 38 seconds to retry. Error was : Unsuccessful response '404' from the server
[go] Failed to save artifact [data/] to [./]
```

##### Possible Fix

After some fiddling I think the issue is caused because the server renames the jobs when `runOnAll` is set to `true`.

As can be seen in the screenshots attached further below, when running on a single instance, the name given to the job is the same as specified in the configuration (`build`), but, when running on more than one instance, the job gets renamed to `build-runOnAll-*`.

When the agent from the second stage queries for the data, it does not exist because `build` does not exist and the Fetch Artifact task does not provide options to handle the modified job name.

At this point I imagine two possible situations:

1. The server handles the process of merging the results from multiple agents into a single directory that can be accessed using the unmodified job name.

2. The agent identifies (through API calls) that the previous job executed in several agents and fetches iteratively from each agent.

Both alternatives will have to deal with the problem of conflicting artifacts being generated by agents.

I prefer the second alternative because it requires less modifications to the server and also allows more interesting features, for instance: 

 - The Fetch Task can have a "filter by resource", so it will only bring artifacts generated by specific agents
 - A "conflict resolution" option where the user can specify if conflicting files will be replaced, ignored, or cause the job to fail.

##### Code snippets/Screenshots

Single agent:
![screenshot from 2018-10-29 14 16 56](https://user-images.githubusercontent.com/2220062/47667678-5c459f00-db85-11e8-8bf3-edc414576e26.png)

Multiple agents:
![screenshot from 2018-10-29 14 16 46](https://user-images.githubusercontent.com/2220062/47667680-5c459f00-db85-11e8-8ba5-3ca55b7ba0ad.png)

##### Any other info

```xml
    <pipeline name="artifact_test_pipeline">
      <stage name="build" artifactCleanupProhibited="true">
        <jobs>
          <job name="build" runOnAllAgents="true" timeout="15">
            <tasks>
              <task>
                <pluginConfiguration id="script-executor" version="1" />
                <configuration>
                  <property>
                    <key>script</key>
                    <value>DATA_NAME=$(python -c "print('$HPG_AGENT_RESOURCES'.replace(',','-'))")&#xD;
DATA_DIR="$PWD/data/$DATA_NAME"&#xD;
DATA_STATUS_FILE="$DATA_DIR/status"&#xD;
&#xD;
if [ "$DATA_NAME" == "" ] ; then&#xD;
    echo "Variable DATA_NAME not specified!"&#xD;
    echo "HPG_AGENT_RESOURCES=$HPG_AGENT_RESOURCES!"&#xD;
    exit 1&#xD;
fi&#xD;
&#xD;
echo "Build name is $DATA_NAME."&#xD;
echo "Build directory is $DATA_DIR."&#xD;
&#xD;
mkdir -p "$DATA_DIR" || exit 1&#xD;
&#xD;
echo "OK!"&gt;"$DATA_DIR/result"</value>
                  </property>
                  <property>
                    <key>shtype</key>
                    <value>bash</value>
                  </property>
                </configuration>
                <runif status="passed" />
              </task>
            </tasks>
            <artifacts>
              <artifact type="build" src="data/*" dest="data/" />
            </artifacts>
          </job>
        </jobs>
      </stage>
      <stage name="merge" artifactCleanupProhibited="true">
        <jobs>
          <job name="merge">
            <tasks>
              <fetchartifact artifactOrigin="gocd" srcdir="data/" dest="./" pipeline="artifact_test_pipeline" stage="build" job="build">
                <runif status="any" />
              </fetchartifact>
              <task>
                <pluginConfiguration id="script-executor" version="1" />
                <configuration>
                  <property>
                    <key>script</key>
                    <value>cd data &amp;&amp; ls</value>
                  </property>
                  <property>
                    <key>shtype</key>
                    <value>bash</value>
                  </property>
                </configuration>
              </task>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
```

**Comment by Caian** [comment]
As an additional information, the Fetch Artifact task accepts the `build-runOnAll-N` notation, but this method allows fetching from one agent only, which is not desirable. Perhaps changing to a regex notation?

**Comment by arvindsv** [comment]
@Caian I misunderstood your question (in [the mailing list](https://groups.google.com/d/msg/go-cd/6xfEEi4Nl9Y/FK6CtC_uCQAJ)).

The fetch is not restricted to _respective_ agents, but will be fetching only from one agent. So, you will have to have `N` number of fetch artifact tasks. You might be able to use the [YAML](https://github.com/tomzo/gocd-yaml-config-plugin) or JSON defined pipelines, and that might make it slightly easier. But, there's no getting around the fact that you fetch from one upstream job.
