### ISSUE TITLE
Go Server doesn't re-use cloned repositories

### ISSUE THREAD

**Issue by splatteredbits** [gocd/gocd#535]
We have a 7GB+ repository. On our build server VMs this repository takes 2 hours to clone. On fast servers, this takes 30 to 60 minutes. Because Go doesn't re-use cloned repositories, and clones fresh each time, each build will not take an additional 30 to 120 minutes (depending on our VM host hardware). That's a non-starter for us to switch to Go. I'm fine with a one-time clone cost, but not for every build.

Please expose a way to tell the Go Server (and Client, if applicable) to re-use repositories and not re-clone them.

**Comment by jyotisingh** [comment]
@splatteredbits  Can you tell what version of mercurial you use and if you have authentication enabled on the repo? 
I have been able to replicate the issue when using hg version 2.0 or above for repos with authentication enabled.

**Comment by arikagoyal** [comment]
This issue is fixed for the scenario @jyotisingh mentioned. Not sure if there are other situations where this happens. For now closing it. Works fine on 15.1.0(1528-11c3045bb72f5f).
