### ISSUE TITLE
Access Token APIs

### ISSUE THREAD

**Issue by vishaldevgire** [gocd/gocd#5354]
## Issue Type

- Feature proposal

## Summary

Access token APIs to allow the user to generate, list, get and delete token.

Epic: https://github.com/gocd/gocd/issues/5321

### Generate the token
A user can generate access token in exchange of username and password credentials. 
 - A user can specify a name, expiration time and optional value for description. The name will be used to uniquely identify token for the user
 - Allow the user to generate multiple tokens.
 - Token will inherit all the access of the user (until we have an infrastructure for granular authorization).

<details>
	<summary>API example</summary>

> Request

```bash
curl -X POST 'http://localhost:8153/go/api/tokens/generate' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v1+json' \
      -H 'Content-Type: application/json' \
      -d '{
      	"name": "Personal", 
      	"expires_in_hours": "4"
      }'
```

> Response

```text
83D1BDC521E44CC9A8905EBF9459A75B
```
</details>

---

### Get Token
This API will be useful to retrieve previously created token value in exchange of token name and user credentials. The response will have a token in `text/plain` form. So that it can be used directly without any need for parsing on the client side.

<details>
	<summary>API example</summary>

> Request

```bash
curl -X GET 'http://localhost:8153/go/api/tokens/PersonToken' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v1+json'
```

> Response

```text
83D1BDC521E44CC9A8905EBF9459A75B
```
</details>

---

### Get token details
This API will allow user to get details about a particular token like name, description, expiration time.

<details>
	<summary>API example</summary>

> Request

```bash
curl -X GET 'http://localhost:8153/go/api/tokens/PersonToken/details' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v1+json'
```

> Response

```json
{
  "_links": {
    "self": {
      "href": "http://test.host/go/api/tokens/PersonToken"
    },
    "doc": {
      "href": "https://api.gocd.org/current/#api-access-token"
    },
    "find": {
      "href": "http://test.host/go/api/tokens/:token_id"
    }
  },
  "name": "PersonToken",
  "description": "Personal Token",
  "expires_at": 987654321
}
```
</details>

---

### List tokens
The API will allow users to list their own tokens. 

Response will contain following properties:
 - name
 - description
 - expires_at (time in linux epoch)

This API will behave differently for admin users in that they can list tokens for all the users including their own.

<details>
	<summary>API example to get user's own token</summary>

> Request 

```bash
curl -X GET 'http://localhost:8153/go/api/tokens' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v1+json'

```

> Response

```json
{
  "_links": {
    "doc": {
      "href": "https://api.gocd.org/current/#api-access-token"
    },
    "find": {
      "href": "http://test.host/go/api/tokens/:token_id"
    },
    "self": {
      "href": "http://test.host/go/api/tokens"
    }
  },
  "_embedded": {
    "tokens": [
      {
        "_links": {
          "doc": {
            "href": "https://api.gocd.org/current/#api-access-token"
          },
          "find": {
            "href": "http://test.host/go/api/tokens/:token_id"
          },
          "self": {
            "href": "http://test.host/go/api/tokens/PersonToken"
          }
        },
        "description": "Personal Token",
        "expires_at": 987654321,
        "name": "PersonToken"
      },
      {
        "_links": {
          "doc": {
            "href": "https://api.gocd.org/current/#api-access-token"
          },
          "find": {
            "href": "http://test.host/go/api/tokens/:token_id"
          },
          "self": {
            "href": "http://test.host/go/api/tokens/WorkToken"
          }
        },
        "description": "Token for work only",
"expires_at": 876543219,
        "name": "WorkToken"
      }
    ]
  }
}
```
</details>

<details>
	<summary>API example for Admin user to get token for other users</summary>

> Request 

```bash
curl -X GET 'http://localhost:8153/go/api/tokens?username=tez' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v1+json'

```

> Response

The response will be same as list all tokens API.

</details>

---

### Delete token
This API will allow a user to delete their own token by specifying a token name.

<details>
	<summary>API example</summary>

> Request 

```bash
curl -X DELETE 'http://localhost:8153/go/api/tokens/PersonToken' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v1+json'
```

> Response

```json
{
	"message": "Token successfully deleted."
}
```
</details>
 
--- 

### Implementation considerations

1. Access token generation is allowed only when security is enabled.
2. An only authenticated user is allowed to generate the token (No token for the anonymous user)
3. The token should have information about authentication source e.g. if the token is generated using `LDAP` plugin authentication then the source should be recorded as `LDAP`. This will allow the server to perform authorization against it. The is required as the different user may have the same username across multiple authentication providers. (PS: We will put more information about this in different issue and link it here)

### Open questions

1. Should users be allowed to `disable/enable` their tokens?
2. Should admin be allowed to `delete/disable/enable` other user's token?

**Comment by ketan** [comment]
Questions/oddities:

- what happens if a non-admin passes the `username` option to the list tokens api? Do we silently fail, and return the users token, error out with a 401/403. Perhaps consider a different URL to do this?
- The `expires_at` renders seconds since epoch — all other places seem to use the standard ISO8601 format. Was there a specific reason to render an int/long. Its confusing what the unit of the number is.
- I found the `expires_in_hours` to be a bit odd as well, but I guess it kind of makes sense in a way, given that users don't really know what TZ the server is in. Could users instead specify a timestamp in ISO8601 (with their local timezone) which can be interpreted by the server correctly. (I'm not suggesting we do this yet).
- The get-token felt odd because an `Accept: json` header caused the server to render a plain text token :). I'm assuming that was a typo.
- Can tokens be used to authenticate with the token API? Should we allow this? (I don't know the answer to this one)

**Comment by GaneshSPatil** [comment]
* Create an Auth Token API for following operations:
	- CREATE, GET, LIST, REVOKE


* Auth Token Entity should contain following information:
	- name
	- optional description
	- digest (Token) value
	- meta
		- is revoked?
		- last used?
		- created time?

* Tasks:
	- [ ] Allow users to create a new auth token.
	- [ ] Allow users to get the metadata about the existing auth token.
	- [ ] Allow users to get the metadata about all auth tokens.
	- [ ] Allow super-admin users to get the metadata about all auth tokens.
	- [ ] Allow super-admin users to get the metadata about all auth tokens belonging to a user.
	- [ ] Allow users to revoke an auth token.
	- [ ] Allow super admin users to revoke an auth token of another user.
	- [ ] APIs should respond based on the AcceptHeader for create call:
		- [ ] Should send just the Token value when `acceptHeader` is `Accept: application/vnd.go.cd.v1+text` (Is this API Header right?)
		- [ ] Should send the entire token information when `acceptHeader` is `Accept: application/vnd.go.cd.v1+json`
 
* Internals
	- [ ] Persist the auth token information in DB in encrypted/hashed form

**Comment by ketan** [comment]
IIRC. We discussed rendering the token only on creation and not after that.
So in that sense the POST call should return a json response with the token
in it.

No content type negotiation would be supported, since we would not render
the token again.

Can someone confirm if my understanding is right?

**Comment by rajiesh** [comment]
Test Scenarios:

Test Data:

Users with below roles
- Admin
- Group Admin
- Template Admin
- View
- Operate
- Users without any roles defaults to view user for groups which are not provided with authorization
- Combination of above roles

Users from below authentication plugins:
- Password file
- LDAP
Users from Web auth plugins cannot use API to generate tokens, so scenarios related to web auth users will be covered in the SPA story

Scenarios:

- [ ] Users in all roles with any of the above mentioned roles should be able to create access token for themselves
- [ ] Users in all roles should be able to create multiple access tokens
- [ ] Users in all roles should be able to get list of access tokens created by itself
- [ ] Users in all roles should be able to revoke any of its own access token only
- [ ] Admin ONLY can get list of all user access tokens in the system
- [ ] Admin ONLY can revoke access token of other users
- [ ] Access tokens should provide only permissions for application APIs allowed for the user who created it, no other API should be accessible. Request should fail with Forbidden error
- [ ] API responses should be according to the contract documented(will put in a link for documentation once its available)
- [ ] GET/LIST access tokens API response should provide correct metadata values about the token - `created_time`, `last_used_time`, `is_revoked`, `revoked_time`
- [ ] DB should store only encrypted value of access token

**Comment by arvindsv** [comment]
@rajiesh Not sure if it belongs here (or anywhere), but access tokens should not be allowed for any non-API requests (and also not for logging in).

**Comment by bdpiparva** [comment]
####  APIs:

##### Users
	- CREATE, GET, REVOKE, LIST token created by the user.
        - Base api url for the user is `/api/current_user/access_tokens`

##### Super Admins
      - LIST all tokens
      - REVOKE tokens for the user
      - Base api url for admin actions is `/api/admin/access_tokens`

* Auth Token Entity should contain following information:
	- name
	- description
	- digest (Token) value (only on creation)
	- created time
	- is revoked?
        - revoked by
        - revoked cause
        - username
        - last used?

- [x] Allow user to access only APIs and `cctray.xml` using access token. Login and UI access is not allowed.
    **Note:** *Accessing access token API using an access token is not allowed

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8610-4713200bc880ce17014d826e20a30ed032e3ac26)
