### ISSUE TITLE
GOCD failed to come up after an upgrade from v18.3.0 to v18.10.0 

### ISSUE THREAD

**Issue by bdonth** [gocd/gocd#5359]
##### Issue Type

After Gocd upgrade Application is not coming

##### Summary

GOCD is not coming up for an upgrade from v18.3.0 to v18.10.0 

##### Environment

Steps to Reproduce
Create a backup from a running server (v18.3.0)
Upload backup to a remote location
Create a new VM and install the latest version of GoCD Docker Image (v18.10.0)
Restore from the backup and start the server

###### Basic environment details

* Go Version: `Gocd Docker veriosn-18.10.0`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Ubuntu-16.04`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

java.lang.RuntimeException: org.springframework.jdbc.BadSqlGrammarException: 
### Error querying database.  Cause: org.h2.jdbc.JdbcSQLException: Column "CASEINSENSITIVEPIPELINENAME" not found; SQL statement:
SELECT caseInsensitivePipelineName FROM PIPELINELABELCOUNTS GROUP BY caseInsensitivePipelineName HAVING COUNT(*) > 1; [42122-168]
### Cause: org.h2.jdbc.JdbcSQLException: Column "CASEINSENSITIVEPIPELINENAME" not found; SQL statement:
SELECT caseInsensitivePipelineName FROM PIPELINELABELCOUNTS GROUP BY caseInsensitivePipelineName HAVING COUNT(*) > 1; [42122-168]
; bad SQL grammar []; nested exception is org.h2.jdbc.JdbcSQLException: Column "CASEINSENSITIVEPIPELINENAME" not found; SQL statement:
SELECT caseInsensitivePipelineName FROM PIPELINELABELCOUNTS GROUP BY caseInsensitivePipelineName HAVING COUNT(*) > 1; [42122-168]

##### Expected Results
Application should come up 

##### Actual Results
 Application is not coming up

**Comment by bdonth** [comment]
can any one please help on above issue, we struck with Production go-server upgrade

**Comment by bdonth** [comment]
@ankitsri11 i have executed below queries to bring my GO server up

ALTER TABLE PIPELINELABELCOUNTS ADD COLUMN caseInsensitivePipelineName varchar_ignorecase(255);
UPDATE PIPELINELABELCOUNTS set caseInsensitivePipelineName = pipelinename;
CREATE INDEX idx_pipelinelabelcounts_caseinsensitivepipelinename ON PIPELINELABELCOUNTS(caseInsensitivePipelineName);


but i can't see all my Jobs in pipelines, out of  600 jobs  i can see only 2 jobs

**Comment by ankitsri11** [comment]
@bdonth are the pipeline configuration stored in a config-repo? Or these are pipelines configured in GoCD cruise-config.xml?

It looks like you ran into similar issue reported here: https://github.com/gocd/gocd/issues/4723

Do you see any warning/error message on the dashboard?

In order to troubleshoot further, we would require below information:

- go/api/support page output
- Go Server logs
- 18.3 config and DB backup

If it is possible to share above information, could you please write to support@thoughtworks.com mentioning this issue number. We can share the instructions for collecting the details over there.

**Comment by ankitsri11** [comment]
@bdonth I noticed in the logs that you are running on 18.5.

`2018-11-01 18:50:00,875 INFO  [main] ServerVersion:39 - [Startup] Go Version: 18.5.0 (6679-a54c3fd44ef9ccbab1b0d856a8d735929eab97f7)`

Can you upgrade to the latest version 18.10 as we made some fix around PipelineLabelCorrector in 18.6. You can read more [here](https://github.com/gocd/gocd/issues/4723#issuecomment-390189519).

**Comment by bdonth** [comment]
after upgrading go-server to 18.10 i am able to see all Jobs, thanks for support

**Comment by ketan** [comment]
Thanks for confirming. Closing issue.
