### ISSUE TITLE
email notification not sent when pipeline is cancelled due to reaching the job timeout

### ISSUE THREAD

**Issue by aqneves** [gocd/gocd#5370]
##### Issue Type

- Bug Report

##### Summary

Email notification not sent when pipeline is cancelled due to reaching the job timeout despite having subscribed all email notifications for that pipeline and having an email associated with the account. All other notifications are properly received.

##### Environment

Any environment.

###### Basic environment details

* Go Version: 18.3.0
* JAVA Version: 1.8.0_181
* OS: RHEL 7.5

###### Additional Environment Details

n/a

##### Steps to Reproduce

1. create pipeline X
2. subscribe to all notifications of pipeline X
3. configure a job for pipeline X that is a sleep of 2 minutes 
4. configure the job timeout to expire after 1 minute
5. run the pipeline

##### Expected Results
We should be notified that the pipeline has started and then we should be notified that the pipeline was cancelled

##### Actual Results
Email notification for pipeline starting was received.
Email notification for pipeline cancelling was not received.

##### Possible Fix
n/a

##### Log snippets
n/a

##### Code snippets/Screenshots
n/a

##### Any other info
n/a

**Comment by rajiesh** [comment]
Verified on 18.12.0 (8203-bbeebad6c03497cf3f5bf0bcddbe13bbc08a11c8)
