### ISSUE TITLE
Expose CR contract to plugins

### ISSUE THREAD

**Issue by ibnc** [gocd/gocd#5374]
Epic: #5175 (Thoughts about improving pipelines as code (config-repo))

Proposal/idea for improving pipeline as code. See https://github.com/gocd/gocd/issues/5338#issuecomment-437125598 and https://github.com/gocd/gocd/issues/5338#issuecomment-437133247

## summary
I'd like to propose that we expose the config repo contract (aka the [CR models](https://github.com/gocd/gocd/tree/master/plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/configrepo/contract)) to the the plugins.  

There are a few possible benefits to doing this that I can see: 
*  It'd make serialization/deserialization easier on the plugin side ([example where it would help](https://github.com/tomzo/gocd-yaml-config-plugin/blob/master/src/main/java/cd/go/plugin/config/yaml/YamlConfigPlugin.java#L82))
*  It'd make it easier to create new repo config plugins. 
*  It'd help ensure the data structure is consistent/correct across the plugins.
   * along these same lines make it easier to test/validate  (instead of doing this: [test](https://github.com/tomzo/gocd-yaml-config-plugin/blob/master/src/test/java/cd/go/plugin/config/yaml/transforms/PipelineTransformTest.java) and [test files](https://github.com/tomzo/gocd-yaml-config-plugin/tree/master/src/test/resources/parts) seeing if it can be serialized to the CR model would likely be sufficient to validate)
* it'd help simplify exporting gocd structures on the plugin side

@ketan @arvindsv @marques-work @kierarad @tomzo

**Comment by tomzo** [comment]
I am buying all the benefits for having the classes available as public library.
IMO the best solution is to create a separate module with CR classes, which has its own release cycle, meaning independent from GoCD core.
Then it is a reference for server or plugins or any tool that needs it.

I wouldn't fall back to using class-based plugin API, if that's what you are proposing.

**Comment by ibnc** [comment]
@tomzo 

At this point, I don't care about the specifics until we decide to do this work. I'm just proposing that the classes are available to the plugins.

**Comment by arvindsv** [comment]
Sorry to be caring only about the specifics. I don't see any harm in moving them out to their own module, which can be spun off as a separate module in https://search.maven.org/search?q=g:cd.go.plugin.

I don't know about it being outside of GoCD core, but if it is versioned properly, then GoCD core can treat it as a dependency. That should be ok too.

**Comment by ibnc** [comment]
Personally, I like the idea of having them be in a separate module too
