### ISSUE TITLE
Issues related to componentization story 

### ISSUE THREAD

**Issue by rahulpargaonkar** [gocd/gocd#5401]
##### Issue Type

- Bug type

##### Summary
Below are some issues observed on plugins page & config repo page.
1. UI: Plugin Icon is not properly aligned with plugin name on plugin page

      
<img width="1424" alt="alignment_issue" src="https://user-images.githubusercontent.com/33080845/48527633-e134f600-e8b1-11e8-95bc-026a6c55c3b9.png">

2. VSM analytics plugin settings are not opening after clicking on settings button ( @akshaydewan  is already looking into it)

3. Docker elastic agent plugin is giving "Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)" on console log on clicking 'save' button. 
<img width="1440" alt="docker elastic agent unprocessedentity" src="https://user-images.githubusercontent.com/33080845/48527663-f4e05c80-e8b1-11e8-926e-907f464aef87.png">

4. UI: Extra whitespace appears  after all fields on 'plugin setting' pop-up & 'Create new configuration repository' pop-up, due to which UI doesn't looks good.

<img width="1440" alt="extra space plugin setting popup" src="https://user-images.githubusercontent.com/33080845/48527720-193c3900-e8b2-11e8-9d0d-759ae48ebdbb.png">

<img width="1376" alt="extra whitespaces in conf repo popup" src="https://user-images.githubusercontent.com/33080845/48527718-18a3a280-e8b2-11e8-9ce8-ed732df8bc51.png">

The above issues are related to #5232 

##### Environment
GO Version: Go Version: Go Version: 18.11.0 (7929-d3a45368ff9e1639ec33b1c3b9b310c74a48fe6a)

**Comment by ketan** [comment]
I'm looking at point (1)

**Comment by akshaydewan** [comment]
Updates:
(2) should be fixed on master - PR #5400
(3) will be fixed by PR #5403

**Comment by rahulpargaonkar** [comment]
Adding new UI issues:
Issue: 1) UI issues on Microsoft edge 18 browser:
  A) On Config repo SPA page;  fields like dropdown, textbox & chexbox are not displaying correctly. please refer attached screenshot.
<img width="1158" alt="screen shot 2018-11-20 at 12 29 50 pm" src="https://user-images.githubusercontent.com/33080845/48756803-83911700-ecc0-11e8-81e0-6789ac5e3c99.png">

Issue: 2) Config repo SPA & plugins page not loading on IE 11 browser.
please see the screenshot attached
<img width="1214" alt="screen shot 2018-11-20 at 12 39 10 pm" src="https://user-images.githubusercontent.com/33080845/48757039-66a91380-ecc1-11e8-83cf-fe8d45959c41.png">
<img width="1167" alt="screen shot 2018-11-20 at 12 38 31 pm" src="https://user-images.githubusercontent.com/33080845/48757040-66a91380-ecc1-11e8-92bf-840edd4ed982.png">

**Comment by rahulpargaonkar** [comment]
verified. issues seems fixed
