### ISSUE TITLE
Broken link to Pipeline Dependency VSM from Pipeline Modification

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5406]
##### Issue Type

- Bug Report

##### Summary
If a pipeline is depending upon another pipeline, the changes popup instance counter used to link to pipeline-dependency graph vsm.
Pipelines Tab (pipeline dependency graph) has been removed as part of GoCD version `18.10.0`.

###### Basic environment details

* Go Version: `Go Version: 18.11.0 (7953-0d78001a6f683549e64575e46eb0957fa0aafd34)`

##### Steps to Reproduce

1. Create a pipeline having another pipeline as the dependency.
2. Let both the pipelines build at least once.
3. Open the changes popup for the dependent pipeline.
4. Click on the pipeline instance counter from the changes popup.

##### Expected Results
The link should take us to VSM.

##### Actual Results
Throws 404.

##### Possible Fix
Link to the actual VSM of the pipeline instead of going to pipeline-dependency graph vsm

**Comment by GaneshSPatil** [comment]
I will be sending a PR to fix this bug after #5405 is merged, as the changeset is dependent on the PR

**Comment by rajiesh** [comment]
Verified on 18.12.0 (8203-bbeebad6c03497cf3f5bf0bcddbe13bbc08a11c8)
