### ISSUE TITLE
Migrate versions api from rails to spark

### ISSUE THREAD

**Issue by sanaj7** [gocd/gocd#5408]
##### Issue Type

- Feature enhancement

##### Summary

Migrate the version api from rails to spark.

###### Basic environment details

* Go Version: `18.11.0 (7941-d152a7802acb9c7c75ed6b845ba907dcbb550725)`
* JAVA Version: `JDK 8`

**Comment by maheshp** [comment]
Done as part of https://github.com/gocd/gocd/pull/5409

**Comment by adityasood** [comment]
@rajiesh @maheshp I guess this can be closed?

**Comment by maheshp** [comment]
@adityasood yes can be closed if verified the changes.

**Comment by adityasood** [comment]
verified on 18.12.0-8158
