### ISSUE TITLE
Could /go/api/v1/health return a 200 during backups please?

### ISSUE THREAD

**Issue by aerostitch** [gocd/gocd#5416]
##### Issue Type

- Feature enhancement

##### Summary

I recently discovered the availability of the `/go/api/v1/health` to check the health of the server.
So I started using it as a livenessProbe (I'm using a local kubelet to manage my server in a container).
The problem is that this endpoint throws a 503 when the backup starts so k8s sees it as an error and recreates the pod, making the backup fail.
It would be good to have it return a 200 with a message that says the backup is in progress instead.

##### Environment

Using the gocd official image version `18.10.0 (7703-42d1cbe661161b5400289ead86c0447c84af8c0a)`

###### Basic environment details

* Go Version: `18.10.0 (7703-42d1cbe661161b5400289ead86c0447c84af8c0a)`
* JAVA Version: `1.8`
* OS of the host (the container is the alpine one of the official gocd image: `Linux 4.19.1-coreos`

##### Steps to Reproduce

1. Start a backup
2. Hit the `/go/api/v1/health` endpoint

##### Expected Results

It would be nice if it returns a 200 during normal backup operations.

##### Actual Results

A 503

**Comment by arvindsv** [comment]
Makes sense to me. @ketan ?

**Comment by ketan** [comment]
I'll take this up today.

**Comment by arvindsv** [comment]
@ketan Moving to 18.12. I think we have too much to finish for 18.11.

**Comment by ketan** [comment]
Sorry, I did not see your message earlier. I fixed this issue while on my way to work.

**Comment by adityasood** [comment]
This is verified to be working Go Version: 18.11.0-7970
