### ISSUE TITLE
Functional issues related to config repo spa

### ISSUE THREAD

**Issue by rahulpargaonkar** [gocd/gocd#5422]
##### Issue Type
- Bug Type

##### Summary

 Go Version: 18.11.0 (7970-a55f4b2199e30c0a9570b448eb35793faeeaacaa)

Issue 1) Moved to #5492

- ~~Issue: 2) The auto-update checkbox always remains selected in config repo popup even though its not selected before.~~

 Steps:
 1. start gocd server & toggle on the config_repos
 2. click on add new config repo, popup will be displayed
 3. select checkbox for auto update
 4. click save button
 5. click on edit button
 6. Unselect the checkbox 
 7. again click the edit button & look for checkbox, this time its selected.
 8. Moreover, on expanding the config repo, value for auto-update is displaying as "(Not specified)" which should be either true or false.
Please refer the below screenshot:

<img width="645" alt="screen shot 2018-11-19 at 3 51 43 pm" src="https://user-images.githubusercontent.com/33080845/48764787-ad553880-ecd6-11e8-805c-56d788595301.png">

- ~~Issue: 3) It is a similar issue with above issue 2,  the update is not working for all fields except dropdown on config repo SPA popup,  fields like  'plugin id', 'material' ,'Repo URL' & 'Branch' are not getting updated to newer values.~~

**Comment by rajiesh** [comment]
Issue 4:

On config repo update from SPA if server returns 422 response, UI does not show the error on UI.
Simple step to reproduce this is 
- Click on update for existing config repo, 
- uncheck AutoUpdate checkbox and click on OK. 
- The server responds with 422 and appropriate error but UI doesnt show any message

**Comment by rajiesh** [comment]
Also is AutoUpdate field needed in UI as well as in API? Since we anyways do not allow for autoUpdate to false?

**Comment by ketan** [comment]
> Also is AutoUpdate field needed in UI as well as in API? Since we anyways do not allow for autoUpdate to false?

This was an open question in my mind as well. I rendered it in the UI because the API rendered it. If we remove it from the UI, we should remove it from the API as well. @maheshp ?

**Comment by ketan** [comment]
Disabled checkboxes are a bit of a pain to implement. For now I'll remove the checkbox.

**Comment by akshaydewan** [comment]
Added another issue in #5508

**Comment by rahulpargaonkar** [comment]
verified. issues are fixed.
