### ISSUE TITLE
TFS checkout fails when material points to a single file

### ISSUE THREAD

**Issue by jsmythsci** [gocd/gocd#5427]
##### Issue Type

- Bug Report

##### Summary

TFS checkout fails when material points to a single file

##### Environment

GoCD is running on a Linux server and the affected agents are running Windows Server 2012R2.

###### Basic environment details

* Go Version: `18.10.0 (7703-42d1cbe661161b5400289ead86c0447c84af8c0a)`
* JAVA Version: `1.8.0_191`
* OS: `Linux 2.6.32-754.6.3.el6.x86_64`
* Browser vendor and version (if relevant): `N/A`

###### Additional Environment Details

This issue has been encountered on a copy of our production system that we created to test upgrading to the latest version of GoCD. The affected pipelines all work as intended on the following system:

* Go Version: `15.2.0(2248-c1f90a6aa3192a)`
* JAVA Version: `1.8.0_181`
* OS: `Linux 2.6.32-754.6.3.el6.x86_64`

Agents in the working environment are also running Windows Server 2012R2 but would be using an older version of Java since they are running an older version of the agent.

##### Steps to Reproduce

1. Create a new pipeline.
2. Add a TFS material.
3. Set the Project Path to a single file (e.g. $/TeamProjectName/AssemblyInfo.cs)
4. Set the Destination Directory to a single file (e.g. tfs/AssemblyInfo.cs)
5. Trigger the pipeline

##### Expected Results
Pipeline should check the file out of TFS and launch its first task.

##### Actual Results
Pipeline fails with an error like the following:

```Failed while checking out into Working Folder: pipelines\MyPipeline\tfs\AssemblyInfo.cs, Project Path: $/TeamProjectName/AssemblyInfo.cs, Workspace: bb18a58c6abfa36db84643de09258c86feaa48bc711174334eaea61594b9623f, Username: BuildUser, Domain: mydomain, Root Cause: java.io.FileNotFoundException: E:\GoCD\Go Agent\pipelines\MyPipeline\tfs\AssemblyInfo.cs\$tf\5\377de3f5-a6f8-41ed-970a-9b0bbf2c1a50.gz (The system cannot find the path specified)```

##### Possible Fix
This appears to be an extension of #183 (TFS does not create destination directory if project path is a file). It seems that TFS is trying to create a local workspace and is failing because:

1. It creates a file object instead of a directory.
2. It tries to create the local $tf directory inside the file object.

If TFS were to create a server workspace instead of a local one (as it does in 15.2), this issue would likely not exist.

##### Log snippets
Here is the stack trace from go-agent.log when the exception is thrown:
```
2018-11-20 17:09:00,480 ERROR [scheduler-2] DefaultGoPublisher:140 - Failed while checking out into Working Folder: pipelines\Test-FileCheckout\tfs\AssemblyInfo.cs, Project Path: $/MyTeamProject/AssemblyInfo.cs, Workspace: 25cc73c9040762d24de5895df1c97c2ead948fa4a0c852b0fcd9efad4fa6487c, Username: myServiceAccount, Domain: mydomain, Root Cause: java.io.FileNotFoundException: E:\GoCD\Go Agent\pipelines\Test-FileCheckout\tfs\AssemblyInfo.cs\$tf\9\6a260479-6aa8-42e4-9d56-a0a03a82cc52.gz (The system cannot find the path specified)
java.lang.RuntimeException: Failed while checking out into Working Folder: pipelines\Test-FileCheckout\tfs\AssemblyInfo.cs, Project Path: $/MyTeamProject/AssemblyInfo.cs, Workspace: 25cc73c9040762d24de5895df1c97c2ead948fa4a0c852b0fcd9efad4fa6487c, Username: myServiceAccount, Domain: mydomain, Root Cause: java.io.FileNotFoundException: E:\GoCD\Go Agent\pipelines\Test-FileCheckout\tfs\AssemblyInfo.cs\$tf\9\6a260479-6aa8-42e4-9d56-a0a03a82cc52.gz (The system cannot find the path specified)
	at com.thoughtworks.go.domain.materials.tfs.AbstractTfsCommand.checkout(AbstractTfsCommand.java:96)
	at com.thoughtworks.go.tfssdk.TfsSDKCommandTCLAdapter.checkout(TfsSDKCommandTCLAdapter.java:43)
	at com.thoughtworks.go.config.materials.tfs.TfsMaterial.updateTo(TfsMaterial.java:165)
	at com.thoughtworks.go.domain.MaterialRevision.updateTo(MaterialRevision.java:146)
	at com.thoughtworks.go.domain.materials.AbstractMaterialAgent.prepare(AbstractMaterialAgent.java:43)
	at com.thoughtworks.go.remote.work.BuildWork.prepareJob(BuildWork.java:174)
	at com.thoughtworks.go.remote.work.BuildWork.build(BuildWork.java:126)
	at com.thoughtworks.go.remote.work.BuildWork.doWork(BuildWork.java:82)
	at com.thoughtworks.go.agent.JobRunner.run(JobRunner.java:54)
	at com.thoughtworks.go.agent.AgentHTTPClientController.retrieveWork(AgentHTTPClientController.java:134)
	at com.thoughtworks.go.agent.AgentHTTPClientController.work(AgentHTTPClientController.java:109)
	at com.thoughtworks.go.agent.AgentController.loop(AgentController.java:85)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.tfs.core.clients.versioncontrol.exceptions.VersionControlException: java.io.FileNotFoundException: E:\GoCD\Go Agent\pipelines\Test-FileCheckout\tfs\AssemblyInfo.cs\$tf\9\6a260479-6aa8-42e4-9d56-a0a03a82cc52.gz (The system cannot find the path specified)
	at com.microsoft.tfs.core.clients.versioncontrol.internal.localworkspace.LocalWorkspaceProperties.moveBaselineFolderStructure(LocalWorkspaceProperties.java:721)
	at com.microsoft.tfs.core.clients.versioncontrol.internal.localworkspace.LocalWorkspaceProperties.doBaselineFolderMaintenance(LocalWorkspaceProperties.java:1131)
	at com.microsoft.tfs.core.clients.versioncontrol.UpdateLocalVersionQueue$4.invoke(UpdateLocalVersionQueue.java:711)
	at com.microsoft.tfs.core.clients.versioncontrol.internal.localworkspace.LocalWorkspaceTransaction.execute(LocalWorkspaceTransaction.java:350)
	at com.microsoft.tfs.core.clients.versioncontrol.UpdateLocalVersionQueue.sendToServer(UpdateLocalVersionQueue.java:708)
	at com.microsoft.tfs.core.clients.versioncontrol.UpdateLocalVersionQueue.flush(UpdateLocalVersionQueue.java:461)
	at com.microsoft.tfs.core.clients.versioncontrol.UpdateLocalVersionQueue.close(UpdateLocalVersionQueue.java:409)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.processOperations(GetEngine.java:1054)
	at com.microsoft.tfs.core.clients.versioncontrol.engines.internal.GetEngine.processGetOperations(GetEngine.java:808)
	at com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Workspace.get(Workspace.java:2463)
	at com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Workspace.get(Workspace.java:2345)
	at com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Workspace.get(Workspace.java:2335)
	at com.thoughtworks.go.tfssdk14.wrapper.GoTfsWorkspace.get(GoTfsWorkspace.java:42)
	at com.thoughtworks.go.tfssdk14.TfsSDKCommand.retrieveFiles(TfsSDKCommand.java:94)
	at com.thoughtworks.go.domain.materials.tfs.AbstractTfsCommand.checkout(AbstractTfsCommand.java:90)
	... 23 common frames omitted
Caused by: java.io.FileNotFoundException: E:\GoCD\Go Agent\pipelines\Test-FileCheckout\tfs\AssemblyInfo.cs\$tf\9\6a260479-6aa8-42e4-9d56-a0a03a82cc52.gz (The system cannot find the path specified)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at com.microsoft.tfs.jni.helpers.FileCopyHelper.copy(FileCopyHelper.java:151)
	at com.microsoft.tfs.core.clients.versioncontrol.internal.localworkspace.LocalWorkspaceProperties.rename(LocalWorkspaceProperties.java:1219)
	at com.microsoft.tfs.core.clients.versioncontrol.internal.localworkspace.LocalWorkspaceProperties.moveBaselineFolderStructure(LocalWorkspaceProperties.java:719)
	... 37 common frames omitted
```

##### Code snippets/Screenshots
Here is the full XML of the pipeline used to test this issue:

```xml
    <pipeline name="Test-FileCheckout">

      <materials>

        <tfs url="http://tfs.mydomain.com:8080/tfs/DefaultCollection" username="myServiceAccount" domain="mydomain" encryptedPassword="REDACTED" projectPath="$/MyTeamProject/AssemblyInfo.cs" dest="tfs/AssemblyInfo.cs" materialName="AssemblyInfo" />

      </materials>

      <stage name="defaultStage" cleanWorkingDir="true">

        <jobs>

          <job name="defaultJob" />

        </jobs>

      </stage>

    </pipeline>
```

**Comment by arvindsv** [comment]
@jsmythsci Thank you for doing all that investigation!

About having the agent create a server workspace, I don't know for sure. Maybe something changed in the SDK between those versions?

Most of the code related to this seems to be around: [this](https://github.com/gocd/gocd/blob/af6493b7c787c66fd29129e38b73a9ff5d2d4977/common/src/main/java/com/thoughtworks/go/domain/materials/tfs/AbstractTfsCommand.java#L83) and [this](https://github.com/gocd/gocd/blob/af6493b7c787c66fd29129e38b73a9ff5d2d4977/tfs-impl/tfs-impl-14/src/main/java/com/thoughtworks/go/tfssdk14/TfsSDKCommand.java#L75-L98).

You might learn something by turning on debug logs. In versions such as 16.12, there was probably a log4j.properties in the agent's config/ directory.

In my view, this looks like an unsupported case. I would assume that the working directory (called a "directory") is not a file. I wouldn't be surprised if GoCD code or the TFS SDK code has a call to `mkdir` somewhere.

**Comment by jsmythsci** [comment]
@arvindsv Thank you for taking the time to respond.

Could you clarify which case you believe is unsupported? I can see 2 different examples of unusual behaviour here and I am not sure which you are referring to.

1. TFS material's Project Path points to a single file in the TFS repository.
2. TFS material's Destination Directory points to a single file.

I can understand the latter not being supported but, in my opinion, it is not an actual use case but rather a workaround for the bug that is documented in #183.

**Comment by jsmythsci** [comment]
I think the simplest thing to do would be to replace the hard-coded `null` with a hard-coded value for creating a server workspace. The following should do it (not sure why GitHub isn't letting me upload it as an attachment):

    --- GoTfsVersionControlClient.java	2018-12-04 09:07:24.432449300 -0500
    +++ "GoTfsVersionControlClient - Copy.java"	2018-12-04 09:13:19.856552100 -0500
    @@ -20,6 +20,7 @@
     import com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Changeset;
     import com.microsoft.tfs.core.clients.versioncontrol.soapextensions.RecursionType;
     import com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Workspace;
    +import com.microsoft.tfs.core.clients.versioncontrol.soapextensions.WorkspaceLocation;
     import com.microsoft.tfs.core.clients.versioncontrol.specs.version.ChangesetVersionSpec;
     import com.microsoft.tfs.core.clients.versioncontrol.specs.version.LatestVersionSpec;
     
    @@ -57,7 +58,7 @@
         }
     
         public GoTfsWorkspace createWorkspace(String workspace) {
    -        return new GoTfsWorkspace(client.createWorkspace(null, workspace, null, null, null, null));
    +        return new GoTfsWorkspace(client.createWorkspace(null, workspace, null, WorkspaceLocation.SERVER, null, null));
         }
     
         public Changeset[] queryHistory(String projectPath, ChangesetVersionSpec uptoRevision, int revsToLoad) {
    
I'm assuming the only use-case for this code is the following workflow on GoCD agents:

1. Create workspace.
2. Get source at appropriate version.
3. Destroy workspace.
4. Move to next task.

According to [Microsoft's documentation](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/decide-between-using-local-server-workspace?view=vsts), the reasons for using a local workspace all relate to making it easier to work offline; if that never comes up in our workflow then I don't see any downside to hard-coding a server-side workspace.

I am not a developer by trade, though, and there may very well be things I have not thought of.

I am interested to know what other people think.

**Comment by jsmythsci** [comment]
@arvindsv Any feedback on the patch or the thought process around it? Are there any use-cases other than fetching the file(s) from source at pipeline run time that need to be considered?

Unfortunately I don't know how to set up a development environment so I can't apply the patch and run the tests myself at this point. I could take the time to figure it out but it would be nice to know whether or not I am on the right track before making that commitment.

**Comment by arvindsv** [comment]
@jsmythsci I'll apply the patch and make an installer available to you tomorrow (or later today). Maybe you can set it up and take a look?

If that works for you, I'll look at what it can affect. My guess is that if multiple agents (maybe in the same machine) are all trying to use the same server workspace, it could be a problem. We will figure out what to do, in that case. For a start, let's go with the patch you have and see if it helps in any way.

**Comment by arvindsv** [comment]
@jsmythsci Here are the links:

[Server](https://www.dropbox.com/s/24vl44jahnd08ad/go-server-18.12.0-8187.zip?dl=1)

[Agent](https://www.dropbox.com/s/7hduuy3xli00qqq/go-agent-18.12.0-8187.zip?dl=1)

You will need both. You can't use this agent with your current server. Bring up the server first and then the agent and once they're connected to each other, you can try this out.

I had to change the patch a bit:

```diff
diff --git a/tfs-impl/tfs-impl-14/src/main/java/com/thoughtworks/go/tfssdk14/wrapper/GoTfsVersionControlClient.java b/tfs-impl/tfs-impl-14/src/main/java/com/thoughtworks/go/tfssdk14/wrapper/GoTfsVersionControlClient.java
index 81fdadbe9..f04b63249 100644
--- a/tfs-impl/tfs-impl-14/src/main/java/com/thoughtworks/go/tfssdk14/wrapper/GoTfsVersionControlClient.java
+++ b/tfs-impl/tfs-impl-14/src/main/java/com/thoughtworks/go/tfssdk14/wrapper/GoTfsVersionControlClient.java
@@ -20,6 +20,7 @@ import com.microsoft.tfs.core.clients.versioncontrol.VersionControlClient;
 import com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Changeset;
 import com.microsoft.tfs.core.clients.versioncontrol.soapextensions.RecursionType;
 import com.microsoft.tfs.core.clients.versioncontrol.soapextensions.Workspace;
+import com.microsoft.tfs.core.clients.versioncontrol.WorkspaceLocation;
 import com.microsoft.tfs.core.clients.versioncontrol.specs.version.ChangesetVersionSpec;
 import com.microsoft.tfs.core.clients.versioncontrol.specs.version.LatestVersionSpec;
 
@@ -57,7 +58,7 @@ public class GoTfsVersionControlClient {
     }
 
     public GoTfsWorkspace createWorkspace(String workspace) {
-        return new GoTfsWorkspace(client.createWorkspace(null, workspace, null, null, null, null));
+        return new GoTfsWorkspace(client.createWorkspace(null, workspace, null, WorkspaceLocation.SERVER, null, null));
     }
 
     public Changeset[] queryHistory(String projectPath, ChangesetVersionSpec uptoRevision, int revsToLoad) {
```

**Comment by jsmythsci** [comment]
@arvindsv Thank you very much for this. I grabbed both files and will test the build out over the next couple of days.

**Comment by jsmythsci** [comment]
@arvindsv I ran some tests today and the test build you provided seems to be working as expected.

### Test Summary
Here is a summary of my test results:

1. Build 18.11, bundled Java: bug exists.
1. Build 18.12.0-8187 (test build), standalone Java: bug does not exist.
1. Build 18.11, standalone Java: bug exists.

### Test Details
My tests were performed on a new VM running Windows 2012 R2 using a snapshot to restore state between each test. Here is the process I followed:

1. Confirm existing bug:
   1. Download and install go-server 18.11.
   1. Download and install go-agent 18.11.
   1. Connect agent to server.
   1. Create test pipeline as described in initial post.
   1. Run pipeline.
   1. Confirm pipeline fails during file checkout with error message documented in initial post.
1. Test fix:
   1. Download and install Java 1.8.
   1. Download and run go-server (test version).
   1. Download and run go-agent (test version).
   1. Connect agent to server.
   1. Create test pipeline as described in initial post.
   1. Run pipeline.
   7. Confirm pipeline succeeds.
3. Reconfirm bug using standalone Java:
   1. Download and install Java 1.8.
   1. Download and install go-server 18.11.
   1. Download and install go-agent 18.11.
   1. Connect agent to server.
   1. Create test pipeline as described in initial post.
   1. Run pipeline.
   1. Confirm pipeline fails during file checkout with error message documented in initial post.

**Comment by jsmythsci** [comment]
Regarding the impact of using server vs local workspaces, I believe the only technical difference between the two is whether or not the client downloads repository metadata to enable offline work.

My understanding of the limitations of TFS workspaces is that:

1. A workspace owner/name combination must be unique: a single TFS user cannot have more than 1 TFS workspace with the same name.
1. Workspace physical location (hostname + local path) must be unique across all of TFS: 2 users on a shared workstation, for example, cannot both work out of the same shared local directory, even if it maps to the same TFS location for both of them.

To the best of my knowledge workspace location (server vs local) is not a factor in any limitation so any potential for conflict between multiple agents running concurrently will likely exist regardless of workspace location.

**Comment by arvindsv** [comment]
@jsmythsci Thank you for checking that.

You might be right. Your knowledge of server workspace location is probably more up to date anyway. :) I'll read about it some more and think about the code a bit more. If I don't see anything that can go wrong, I might make the change. In the worst case, I'll probably make this an option that can be turned on. Either way, you should get this change in the 19.1 release in January. I won't be able to analyze it in time for the current release (this week).

**Comment by arvindsv** [comment]
Umm. Also, in case you don't see me say anything by first week of January or so, please feel free to remind me about this.

**Comment by arvindsv** [comment]
Looking at some articles such as [this](https://docs.microsoft.com/en-us/azure/devops/repos/tfvc/decide-between-using-local-server-workspace?view=vsts) and [this](https://blogs.msdn.microsoft.com/phkelley/2013/05/28/server-workspaces-vs-local-workspaces/), it looks like server workspaces were the default in TFS 2010. TFS 2012 introduced local workspaces and it seems to be, as you said, all about being able to work offline.

My suspicion is that we were using server workspaces before the upgrade to TFS SDK 14 (since there was no such thing as a local workspace before). If that's the case, I'm less worried about making this change to use server workspaces.

Some things you might have to check, @jsmythsci, when you find the time:

1. Ability to create a directory in the working directory.

2. Ability to change an existing locally checked out file (might not be allowed, since it's a server workspace and it's supposed to be read-only).

3. Making sure that a change in a file is seen by GoCD properly and the number of open workspaces as seen on the server (is there even such an ability?) doesn't keep increasing.

The last one: My thought is - a local workspace is like a full checkout. A server workspace is partial and is still "connected" to the server, in a sense. Does it cause extra load (mostly memory or filesystem) on the server.

**Comment by jsmythsci** [comment]
Thank you for your continued attention to this, @arvindsv.

I can confirm that GoCD uses server workspaces prior to the TFS SDK update. There was a bug (#2840) whereby agents were silently failing to delete their workspaces and when I check our TFS server for workspaces owned by our GoCD user I can see that they are all server workspaces. This visibility helped me when investigating for this current issue because, if I checked quickly enough, I could see that the workspaces created on newer versions of GoCD were local rather than server workspaces.

Here are my thoughts on the points you raise:

1. I have not explicitly tested this but I believe it would work as expected. We have some workflows that depend on copying files into working directories after fetching materials and I can't see why creating a directory would be any different from creating a file in this context. If you think it's valuable then I would be happy to create a pipeline to explicitly test creating directories.
1. When using server workspaces (GoCD v16.11) all files are checked out read-only and cannot be modified without removing the read-only attribute (Windows agent). I can see how this could be an issue for anyone who is using the current version of GoCD with TFS; hard-coding the use of a server workspace would cause errors if they have Tasks in their Jobs that modify files without first removing the read-only attribute. With that in mind it may be better to add a configuration parameter and retain the current default behaviour.
1. I'm not sure what scenarios you are thinking of here. My understanding is that the GoCD server is responsible for detecting changes to files and that it polls the TFS server directly, without using a workspace. For agents, a workspace is created for each TFS material when a Stage is configured to fetch materials and is destroyed as soon as the files have been downloaded from TFS.
1. (Unnumbered in your post.) I think that, given GoCD's workflow (create workspace -> get files -> delete workspace), extra load would be placed on the network and maybe the TFS server with a _local_ workspace since the client (GoCD agent) must download repository metadata that is not required with a server workspace. I believe that any additional load caused by a server workspace would stem from the client's need to communicate with the server for every TFS operation but my understanding is that there are no such operations in GoCD's workflow.

Thank you again for your time and effort. Let me know your thoughts and if there are any tests you would like me to run.

**Comment by arvindsv** [comment]
@jsmythsci 

1. Yes, please. A confirmation, either way, should be fine. I would expect it works, as well.

2. Ok.

3. That's right. This change is supposed to only happen on the agent side. So, it should be fine. What I was thinking about was probably similar to #2840. We could check this scenario: Agent creates a server workspace. New commit happens. Agent uses the same server workspace and doesn't create another. I'm not sure how the connection to the TFS server works. If it's just a matter of having some metadata around to say that this is a server workspace, that's fine. If it's more, then it might be worth it to check that this change doesn't keep anything open on the TFS server side. I understand that the behavior will revert to whatever was happening in earlier versions of GoCD - and so, should be the same. I'm just taking this chance to document some of that, if possible.

4. You're probably right about that.

I've opened https://github.com/gocd/gocd/pull/5608 which should allow me to make a simple change to put in a temporary toggle for this, controlled from the server side (assuming that change is accepted). Once the toggle is in place and works for a while, we can look for a more permanent solution (maybe by changing the TFS material config), unless we decide to default to server workspaces.

If you can check point (1) above, just for completeness' sake, that would be good. If possible, please check point (3) too. I understand it's more involved and if you cannot, that's ok. I'm asking only because you have seem to have easier access to a TFS server and probably know more about it than I do. :)

**Comment by ketan** [comment]
I feel that an agent should delete the server workspace at the end of a
build. Not deleting would cause several server workspaces to be created (I
believe there was a bug that we fixed regarding this.)

Also, this problem will just get worse with elastic agents, where a server
workspaces will be created for every job that runs.

**Comment by arvindsv** [comment]
Yes, we will need to understand what is happening first (and how a server workspace is "connected" to the TFS server - and what it leaves behind if it is not removed). Of course, removing it every time might also mean slower checkouts every time, etc.

**Comment by arvindsv** [comment]
@jsmythsci I forgot to mention that the latest experimental installers (`19.1.0-8395`) on https://www.gocd.org/download/ should have the changes for this. You'll need to set a system property as mentioned here: https://github.com/gocd/gocd/pull/5693

It'll also be released as a part of 19.1  and if all goes well, we can turn it on by default in 19.2 or 19.3 and remove the need for the system property soon after that.

**Comment by rajiesh** [comment]
Keeping this issue open for @jsmythsci to confirm if the fix helped solve the problem

**Comment by jsmythsci** [comment]
Sorry to take so long to follow up on this. Our work on GoCD stalled while waiting for version 19.01 and other projects took priority.

I just tested upgrading from 16.11 to 19.01 and my test builds are working as intended. This was unexpected, however, as I did not set the following system property, which I believed would be required:

`gocd.agent.extra.properties=toggle.agent.tfs.use.server.workspace.location=Y`

Was this done intentionally?

Either way, I'm glad that it is working for us now. I am eager to get our system current so we can start leveraging the improvements the GoCD team has made over the past 2 years.

**Comment by arvindsv** [comment]
@jsmythsci That's indeed strange. I double-checked the logic just now and it should be defaulting to using `null` for the server workspace location.

**Comment by jsmythsci** [comment]
@arvindsv Thank you for confirming.

I must have set the system property ahead of time on our test system.

I confirmed that removing it resulted in the same failures I initially reported and that when I added it back to the server configuration the builds completed as expected.

Thank you again for the help and support working through this issue with us.

**Comment by arvindsv** [comment]
@jsmythsci You're welcome. :) I'll setup a reminder to change the `false` to `true` by default, in a couple of releases and then remove the toggle altogether a couple of releases after that.

**Comment by unkinected** [comment]
Hey everyone. I just upgraded server and agents to 19.2 today and I'm still having this problem; when pointing to a single file for the material, the pipeline downloads a file named after the destination directory and breaks.

I see comments about needing to toggle a system problem, but I'm not quite sure what that means. I don't see anything like the above settings in the wrapper-server.conf file (I'm on Windows). Do I need to set an environment variable? What am I missing?

Thanks!

**Comment by jsmythsci** [comment]
Hello @unkinected,

To get this working there are 2 things that you need to do:

1. The material's Destination Directory attribute must include a file name. It doesn't necessarily have to be the same as the file name in TFS but unless there is a good reason that it must be changed, it probably should be kept the same. This is a workaround for #183.
1. The GoCD server needs to be started with the following system property set:
`gocd.agent.extra.properties=toggle.agent.tfs.use.server.workspace.location=Y`

As documented [here](https://docs.gocd.org/current/installation/install/server/windows.html#overriding-default-startup-arguments-and-environment), the way to do this on Windows is to add a line like this to the **wrapper-server.conf** file:

`wrapper.java.additional.XX=-Dgocd.agent.extra.properties=toggle.agent.tfs.use.server.workspace.location=Y`

where **XX** represents the next wrapper.java.additional index.

Hope this helps.

**Comment by unkinected** [comment]
Thanks. I tried all that... if I do NOT change the destination directory to a file name, I get the same problem before but at least it doesn't error out. When I try to change the dest directory to a filename with no folder path, it works. However, if I specify a folder path, I get this message:

Invalid directory name '.\folder\filename.ext' It should be a valid relative path.

Mostly there, but this will do for me for now. Thanks!

**Comment by jsmythsci** [comment]
I think it might be a Windows vs Unix thing.

Try setting it to `./folder/filename.ext` (forward slashes instead of backslashes) to see if that helps.

**Comment by arvindsv** [comment]
FYI: I've opened #6283 to change the default value of this to use SERVER.
