### ISSUE TITLE
Job Run History endpoint implementation is missing after moving the agents API to Spark

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5437]
##### Issue Type
- Bug Report

##### Summary

The [Job Run History Endpoint ](https://api.gocd.org/18.11.0/#agent-job-run-history)for an agent is giving " The url you are trying to reach appears to be incorrect."

###### Basic environment details

* Go Version: 18.11.0-8014
* JAVA Version: Java10
* OS: MacOS
* Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

1. Get the agents using the [Get all agents API endpoint ](https://api.gocd.org/18.11.0/#get-all-agents)
2. Collect an agent UUID 
3. Query the Job run history API endpoint 

##### Expected Results
Should return the job run history for the corresponding agent

##### Actual Results
The endpoint is not present 

![screen shot 2018-11-22 at 3 31 20 pm](https://user-images.githubusercontent.com/17826464/48896359-75ccc480-ee6d-11e8-824b-a1bb5ffa5017.png)

**Comment by bdpiparva** [comment]
Added a rule(PR #5443) to get job run history using rails API as it is not versioned API.

**Comment by adityasood** [comment]
verified on 18.11.0-8024
