### ISSUE TITLE
Remove `materialName` attribute on config repos

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5457]
I'd like to remove the redundant `materialName` attribute(s) on SCM materials in config repos.

https://github.com/gocd/gocd/blob/856759c755566a4bcd78bf4f1385141853e81701/config/config-server/src/main/resources/cruise-config.xsd#L164-L205

The attribute primarily exists in the context of pipeline configs to refer to materials in the pipeline config. However in this context, the name is not used (unless the user wants to explicitly name the material). Arguably the naming can be done via the `<config-repo/>`s `id` attribute as well.

So:

```xml
<config-repo ...>
  <git url='...' materialName="something"/>
</config-repo>
```

will become:

```xml
<config-repo ...>
  <git url='...' />
</config-repo>
```

/cc @arvindsv @tomzo

**Comment by tomzo** [comment]
Sounds right. This is not used in anyway.
I wouldn't make `id` meaningful as material name. There is just no point.
