### ISSUE TITLE
Oauth token in material urls show up in logs

### ISSUE THREAD

**Issue by prateekbaheti** [gocd/gocd#5471]
##### Summary
If a material URL has an oauth token, GoCD job logs show the token. It should be hidden as in the case of basic auth credentials.

###### Basic environment details

* Go Version: 18.12.0
* JAVA Version: 10.0.2
* OS: Linux 4.14.77-81.59.amzn2.x86_64
* Browser vendor and version (if relevant): All browsers

##### Steps to Reproduce

1. Create a new pipeline, setup material with oauth token. Example: https://randonAuthToken1234@github.com/prateekbaheti/gocd-example
2. Trigger that pipeline

##### Expected Results
The token should be hidden in logs.

##### Actual Results
Token is hidden in logs

##### Possible Fix
Improve pattern matching that hides credentials in material URL

##### Code snippets/Screenshots
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/1955832/49203447-48809900-f3ce-11e8-96b1-ea830d8ee3b6.png">

**Comment by prateekbaheti** [comment]
Quick workaround is to use any usernamein the URLs with the token. Verified for Github.
Example : https://username:randonAuthToken1234@github.com/prateekbaheti/gocd-example

**Comment by GaneshSPatil** [comment]
@tetrohed -- Please do.
Let us know if you require any help.

**Comment by arvindsv** [comment]
@tetrohed Thank you for picking this up!

This [developer setup doc](https://developer.gocd.org/current/2/2.1.html) will be useful, for you to set up to build it. You might also be interested in [UrlArgumentTest.java](https://github.com/gocd/gocd/blob/master/config/config-api/src/test/java/com/thoughtworks/go/util/command/UrlArgumentTest.java).

**Comment by tetrohed** [comment]
hi @arvindsv thanks for the links, I have been trying to sort out my intelliJ env, hitting a roadblock when trying to install some of the gems: 
    Error:Cannot run program "bundle" (in directory "~/gocd/server/webapp/WEB-INF/rails/gems/jruby/2.5.0/gems/rainbow-3.0.0"): error=2, No such file or directory

not sure if this is an intellij bug, any ideas?

**Comment by tetrohed** [comment]
Hello @GaneshSPatil and @arvindsv  I am trying to get the developer setup working but webapp tests are failing with this [output](https://pastebin.com/tBV2KBHD)

**Comment by arvindsv** [comment]
@tetrohed - @GaneshSPatil would be a better person for this. But, I'll try and take a look later today. What command did you use?

Also, did you run `./gradlew clean prepare` first?

**Comment by arvindsv** [comment]
@tetrohed - By the way, for this particular test, I believe you should be able to run it in IntelliJ and it should work.

**Comment by tetrohed** [comment]
I have executed ./gradlew but does not help with the issue. I am still working on setting up IntelliJ, but the ruby plugin gem manager is giving me difficulties.

**Comment by arvindsv** [comment]
@tetrohed I've never really been able to get the ruby plugin gem manager to work with IntelliJ. I've never needed it to work. The gems are installed externally, usually, and it works for me. Maybe @GaneshSPatil can help?

Which version of IntelliJ are you using?

**Comment by GaneshSPatil** [comment]
@tetrohed -- I've seen this happening when no gems are installed.

> I have executed ./gradlew but does not help with the issue.

Just to clarify. Did you just run `./gradlew` or the clean prepare command `./gradlew clean prepare`, as mentioned by @arvindsv ?

A couple of things:
* Intellij's Ruby gem plugin manager does not work as expected, Please dont use it. Prepare command will install the gems externally.

* IntelliJ versions below `2017.2` don't work with GoCD setup. We should be using the latest IntelliJ version `2018.2`.

**Comment by tetrohed** [comment]
got things working, but I broke the linux build, I will try to reproduce the linux build on a VM, since I dont have a Linux machine at hand, you guys mind look in the pipeline and post what broke the build? @GaneshSPatil

**Comment by arvindsv** [comment]
@tetrohed One of us will take a look.

**Comment by GaneshSPatil** [comment]
Fixed as part of PR: https://github.com/gocd/gocd/pull/5574
