### ISSUE TITLE
Config Repo configurations are not validated

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#5478]
##### Issue Type
- Feature enhancement

##### Summary

The config_repos can be provided with additional configuration while configuring through the Config Repo [API](https://api.gocd.org/current/#create-a-config-repo) or while editing the CONFIG xml. Unlike other plugins, GoCD does not expose a plugin endpoint to fetch the required configurations from the plugin and these configurations are not validated against the plugin. 
These configurations are however passed as part of the [Parse Directory](https://plugin-api.gocd.org/current/config-repo/#parse-directory) request from GoCD to plugin.

Enhance the config repo plugin endpoint, 
1. To add ability to fetch the required configurations from the plugin.
2. Add an endpoint to validate the configurations with plugin.
3. The configurations should be validated when an config_repo is created/updated through the config_repo [API](https://api.gocd.org/current/#create-a-config-repo).

**Comment by ibnc** [comment]
I'll work on this

**Comment by ibnc** [comment]
I think a question we need to address is what level of validation we want to happen up front. 

Do we, for example, want to validate that the `file_pattern` property will actually match a file in the repo? If so, then that complicates matters significantly. It'd require us to do a clone of the repo each time a config repo is created/updated.

**Comment by arvindsv** [comment]
@ibnc That's left to the plugin to decide. Not really a concern for this issue. I don't think the plugin should bother with verifying that.

This issue is only about providing the infrastructure to check connection, whatever that means. It could just be syntax validation and a `git ls-remote`.

**Comment by arvindsv** [comment]
@ibnc - @maheshp and I talked. You'd mentioned yesterday (offline) that you think we might not need this. We agree. The rationale was:

> None of the current plugins really have any configuration which can be validated (or need validation). Do we really want to put in that framework for some hypothetical plugins of the future?

> The material-level check connection has to be implemented by GoCD. Since it is the only one which knows about the different kinds of materials. So, we should just have a normal check connection.

I think that's almost exactly what you were saying. Since the material-level check connection is being implemented as a part of https://github.com/gocd/gocd/issues/5650, I'm closing this.
