### ISSUE TITLE
Polling and builds fail when a git submodule URL changes

### ISSUE THREAD

**Issue by mmb** [gocd/gocd#548]
This causes `git submodule update --init` to fail which means material updates fail and builds running on the agent fail if they have the stale submodule url:

```
git submodule update --init
--- Environment ---
{}
--- INPUT ----


--OUTPUT ---
<cut>
ERROR: fatal: reference is not a tree: 176026c856dd4cecd80fcdd5fe904fbc9f4c1385
ERROR: Unable to checkout '176026c856dd4cecd80fcdd5fe904fbc9f4c1385' in submodule path 'src/gnatsd'
```

`git submodule sync` is needed to refresh the submodule url.

This is time consuming to recover from because the fix involves running git submodule sync on the flyweights on the server and all copies on the agents which have stale urls.

**Comment by ketan** [comment]
Bump. @arvindsv See http://go05/go/tab/build/detail/go-postgresql-build/387/build-addons/1/postgresql
