### ISSUE TITLE
when I run my pipeline this error will occur.

### ISSUE THREAD

**Issue by chetangehlot** [gocd/gocd#5487]
go] Task: bash -c "docker build -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL . -f Dockerfile.application"took: 0.117sexited: 127
bash: docker: command not found
[go] Task status: failed, took: 0.117s, exited: 127
[go] Current job status: failed

I am following this tutorial :--- https://docs.gocd.org/current/gocd_on_kubernetes/designing_a_cd_pipeline/creating_a_build_pipeline.html

**Comment by ankitsri11** [comment]
Where are you running this pipeline? Can you make sure the pipeline job is associated with an elastic agent  profile as mentioned here: https://docs.gocd.org/current/gocd_on_kubernetes/designing_a_cd_pipeline/creating_a_build_pipeline.html#associate-job-with-the-elastic-profile

**Comment by chetangehlot** [comment]
I am not using kubernetes. But I can install docker elastic agent on gocd pipeline docker server

**Comment by ankitsri11** [comment]
You can use any agent which has Docker installed on it. If you plan to use docker elastic agent, I would recommend using this image: https://hub.docker.com/r/gocd/gocd-agent-docker-dind/

You can read more [here](https://github.com/gocd-contrib/docker-elastic-agents/blob/master/INSTALL.md) about docker elastic agent setup.

**Comment by chetangehlot** [comment]
Okay. At this time I am using kubernetes so I can deploy on kubernetes.

**Comment by chetangehlot** [comment]
hi @ankitsri11 Can you send me the full running process of nginx on GOCD env.
