### ISSUE TITLE
Config-repo: helper tool

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#5489]
CLI tool to assist in parsing and validating JSON/YAML config-repos. Should help in parsing the syntax of config-repo files and does a pre-flight check whether config-repo is ready to use.

### User experience:

   - Need: Shorter feedback loop for errors in JSON/YAML config.
  - User can validate both new and existing config-repos
  - User doesn't care whether the preflight check happens locally or not.
  - User can run this tool anywhere, as long as they can reach the GoCD server (for running checks against it).

  ### Usage:
  
  - Needs to have some property file which decides which server to connect to (and how - 
     credentials).
  - Clone/connect to config-repo
  - Define the plugin type (yaml, json etc) and parse accordingly 
  - Ability to correct syntax? 
  - Ability to merge or update on the GoCD side?

  Workings of the utility:
Sends content of files (full response https://plugin-api.gocd.org/current/config-repo/#parse-directory) to the GoCD server alongwith the config repo-id

```
$ ls
  01_a.gopipeline.json  02_b.gopipeline.json  03_env1.goenvironment.json
```
```
 $ git status
    On branch master
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)
    
      modified:   01_a.gopipeline.json
      modified:   03_env1.goenvironment.json
    
    no changes added to commit (use "git add" and/or "git commit -a")
```
 ```
$ gocd check .
    01_a.gopipeline.json:10:Pipeline name is not valid (format is ...).
    03_env1.goenvironment.json:22:Agent does not exist in GoCD.
```
     $ ... fix it ...
     $ git add . && git commit -m ...

### Thoughts about implementation:

 **Part 1:** Check syntax (locally)

        - Valid JSON/YAML
        - Matches schema (what is allowed in JSON/YAML, etc)
        - Error messages which show filename, at least. Line numbers would be a nice to have.

 **Part 2:** Validate whether the changes work when merged (server)

        - Pipeline dependency etc

**Scenario 1:** New config-repo validation

Entities to be passed: Content, Type of repo

- Helper tool parse the syntax (https://plugin-api.gocd.org/current/config-repo/#parse-directory) and sends the full json response to GoCD server
- Throws error on the terminal in case of any syntax error
- GoCD validates the full response json and send backs the success/failure message to tool

**Scenario 2:** config-repo modification check 

Entities to be passed: Content, config-repo-id (config-repo-id configured in GoCD)

- Helper tool parse the syntax (https://plugin-api.gocd.org/current/config-repo/#parse-directory) and sends the full json response to GoCD server
- Throws the error on the terminal in case of any syntax error
- GoCD validates the full response json across all the other pipelines and send backs the success/failure message to tool

### More considerations:
Authorization: Who can run the preflight check? Anyone?
Credentials store. Where? Auth tokens are in progress.

Epic: #5175

**Comment by arvindsv** [comment]
> Will need to validate the plugin versions though.

Yes, that is the tricky / necessary part.

**Comment by arvindsv** [comment]
@ankitsri11 

1. What do you mean by "User can validate both new and existing config-repos"?

2. The credentials question is important and might need to wait till https://github.com/gocd/gocd/issues/5321. I see you mentioned it at the end.

3. I don't understand the difference between scenarios 1 and 2.

4. What does this mean: "Ability to merge or update on the GoCD side" ?

**Comment by ankitsri11** [comment]
@arvindsv 

> What do you mean by "User can validate both new and existing config-repos"?

I meant to say that user should be able to validate the new config-repo code as well as if there is any existing dependency with other pipelines etc

> I don't understand the difference between scenarios 1 and 2.

Scenario 1 is for the new config-repo setup where as Scenario 2 talks about any update/modification to existing config-repo. In case of Scenario 2, tool will check and make sure there is no dependency broken after the updates.

> What does this mean: "Ability to merge or update on the GoCD side" ?

Once the config-repo code is parsed and validated, whether tool should provide ability to add config-repo to GoCD configuration. Its more of a thought.

**Comment by marques-work** [comment]
@arvindsv

> > Will need to validate the plugin versions though.
> 
> Yes, that is the tricky / necessary part.

It may not be terrible; the CLI tool already knows how to inspect jars for `plugin.xml` and parse it. I need to think about the correct flow of logic around when to validate (and the CLI parameters, etc), but I'm hoping it's as straightforward as that.

**Comment by arvindsv** [comment]
> Scenario 1 is for the new config-repo setup where as Scenario 2 talks about any update/modification to existing config-repo. In case of Scenario 2, tool will check and make sure there is no dependency broken after the updates.

I'm not sure it has the ability to differentiate between the two. You could break dependencies as soon as you introduce it too, right?

**Comment by ankitsri11** [comment]
Its more from a use case point of view, not the tool ability.

**Comment by marques-work** [comment]
Current code available at https://github.com/gocd-contrib/gocd-cli

**Comment by kierarad** [comment]
Should the preflight endpoint be restricted to Admins?

**Comment by ankitsri11** [comment]
@kierarad based on the type of error messages we can decide the restriction. 

For now, as mentioned by @arvindsv, let's start with admin only access and later we can loosen restrictions.

**Comment by ankitsri11** [comment]
Closing it out as the helper tool is available here: https://github.com/gocd-contrib/gocd-cli
