### ISSUE TITLE
Changing plugin ID of config repo seems to have no effect

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5492]
##### Issue Type

- Bug Report

##### Steps to reproduce

 1. Create a config repo plugin.
 2. wait for few seconds & go to pipeline dashboard to check whether the pipeline is displayed.
 3. If pipeline displayed on dashboard, then go to config repo page again 
 5. Change the plugin type for the config repo (choose any other plugin), so that the plugin is unable to now parse the config repo files in the repo
 6. when user go back to dashboard page then the same pipeline is still displayed even though the wrong plugin data is provided.

**Comment by akshaydewan** [comment]
Just documenting what we've found out so far -- 
After an MDU happens, `ConfigMaterialUpdater:80` runs this code:

```
if (lastParseRevision == null) {
    //never parsed
    updateConfigurationFromCheckout(folder, revision, material);
} else if (latestModification.findRevisionFor(material.config())
        .hasChangedSince(lastParseRevision)) {
    // revision has changed. the config files might have been updated
    updateConfigurationFromCheckout(folder, revision, material);
} else {
    // revision is the same as last time, no need to parse again
}
```

Since the revision is the same as last time, it doesn't parse the config repo, even if the plugin ID has changed.

**Comment by ankitsri11** [comment]
Fixed as part of this PR: https://github.com/gocd/gocd/pull/5816

Verified on GoCD Version: 19.2.0 (8559-38e68d0ca9dfce367dd1d9a380e824595cd87d34)
