### ISSUE TITLE
Wrong screenshot excerpt image for Parameters tab documentation

### ISSUE THREAD

**Issue by jmmygoggle** [gocd/gocd#5503]
##### Issue Type
- Documentation Report

##### Summary
The screenshot excerpt image for Parameters tab UI in "Parameterize your Configuration" section  incorrectly displays the Environment Variables tab UI.

##### Environment
docs.gocd.org
https://docs.gocd.org/current/configuration/admin_use_parameters_in_configuration.html#using-web-interface

###### Basic environment details
* macOS Sierra Version 10.12.6
* Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

##### Steps to Reproduce
1. Visit https://docs.gocd.org/current/configuration/admin_use_parameters_in_configuration.html#using-web-interface
2. Observe that the screen shot excerpt displays the "Environments" tab UI as active instead of the "Parameters" tab UI.

##### Expected Results
An image with "Parameters" tab UI should be shown to illustrate the prior "Edit the Parameters tab when defining a pipeline" text and the subsequent parameter-related documentation.

##### Actual Results
An image with "Environments" tab UI screenshot excerpt is shown.

##### Possible Fix
Replace [current image](https://github.com/gocd/docs.go.cd/blob/master/resources/images/use_parameters_in_configuration.png) with a "Parameters" tab UI screenshot excerpt.

![use_parameters_in_configuration](https://user-images.githubusercontent.com/18149553/49471073-cf63b600-f7c0-11e8-81ae-800cf5f31f26.png)

##### Log snippets
N/A

##### Code snippets/Screenshots
![use_parameters_in_configuration bad](https://user-images.githubusercontent.com/18149553/49471164-10f46100-f7c1-11e8-8534-16ea24ca704d.png)

**Comment by ankitsri11** [comment]
This has been taken care by this PR: https://github.com/gocd/docs.go.cd/pull/223

Thanks for pointing it out @jmmygoggle 

Documentation is updated here:  
https://docs.gocd.org/18.12.0/configuration/admin_use_parameters_in_configuration.html
