### ISSUE TITLE
Personalization tab(the left most tab) shows all pipelines before updating it to show relevant pipelines

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#5512]
##### Issue Type

- Bug Report

##### Summary

This is an issue reported by @ibnc on https://github.com/gocd/gocd/issues/5464. Moving it here since this issue will be worked on separately.

**Note:** This issue is not reproducible in a local setup with few pipelines. In build.gocd.org we can observer it but intermittently. If anyone can reproduce it consistently please add more info.

Personalization tab(the left most tab) shows all pipelines before updating it to show relevant pipelines.

When user click the Go icon on the top left, it takes me back to the furthest left tab, but the content of the page is incorrect.

<img width="1438" alt="isabelle-issue-5464" src="https://user-images.githubusercontent.com/6533924/49566488-c73a8080-f950-11e8-8b87-f5b55aa9cc2d.png">

<img width="778" alt="issue-54640-ss-2" src="https://user-images.githubusercontent.com/6533924/49566495-cb669e00-f950-11e8-9ba7-723cd51ac490.png">

A GIF which shows the issue,

![issue-5464-gif-3](https://user-images.githubusercontent.com/6533924/49566502-d3264280-f950-11e8-8f79-18010cc4d791.gif)

**Comment by adityasood** [comment]
verified on 18.12.0-8222
