### ISSUE TITLE
Error message in VSM is going under settings icon.

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#5514]
##### Issue Type
- Bug Report

##### Summary

Error message `Built from incompatible revisions.` is going behind settings icon. 

![screen shot 2018-12-06 at 2 12 54 pm](https://user-images.githubusercontent.com/7871209/49572372-a4649800-f961-11e8-9985-a83fa628d0df.png)

**Comment by GaneshSPatil** [comment]
Verified on build.gocd.org. Go Version: 18.12.0 (8139-005f4fd80bafd2efd1d413537368156303f6ef6e).

Refer: https://build.gocd.org/go/pipelines/value_stream_map/UploadInstallers/815
