### ISSUE TITLE
Ability to broadcast message within GoCD

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#5521]
##### Issue Type

- Feature proposal

##### Summary

Feature request to broadcast message to the users within GoCD. 
For example, GoCD admins can alert users about downtime or raise awareness about known issue/s etc.

**Comment by GaneshSPatil** [comment]
Hi @ankitsri11,

Could you explain more around the "_broadcast message to the users within GoCD_".
Should we be sending an email notification? System Notification on web UI? Or something else?

It would be better to know the expected result :)
