### ISSUE TITLE
Job settings link on Elastic profile usages modal broken if stage defined in template

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#5541]
##### Issue Type

- Bug Report

##### Summary

Elastic agents profile [usage API](https://github.com/gocd/gocd/pull/5299) returns pipeline/stage/job name. If the stage and job is defined in a template and used in pipeline still this API returns Pipeline/Stage/Job names. That breaks the Go to job settings link on the profile usages modal as url constructed using pipeline name

###### Basic environment details

* Go Version: `18.12.0 (8139-005f4fd80bafd2efd1d413537368156303f6ef6e)`

**Comment by adityasood** [comment]
fixed in #5555
