### ISSUE TITLE
Remove support for DES

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#5554]
##### Summary

Support for AES encryption/decryption was introduced in release 18.7.0, with that, support for DES was deprecated. Support for DES was retained to support DES cipher-texts configured in config-repos. 

Support for DES needs to removed for 19.1.0

**Comment by akshaydewan** [comment]
Since we still need to support the upgrade path from pre 18.7 to 19.1+, we'll keep the migration code and `DESEncrypter` in place. 
We can remove the System property `gocd.des.cipher.enabled` and remove support for encrypting and decrypting using DES, except in the upgrade scenario.
