### ISSUE TITLE
Introduce users API v3

### ISSUE THREAD

**Issue by vrushaliwaykole** [gocd/gocd#5558]
##### Issue Type

- Feature proposal

##### Summary

Users API v2 has a few limitations that prevent us from replacing the current users page:

- Lack of bulk operate APIs. In particular, bulk enable/disable and role assignment
- Lack of search API to allow searching for users in the backends supported by the authorization plugins.

----

<details>
  <summary>List users</summary>

**Changes from previous version**: Introduce new attributes `admin` (`boolean`) and `roles` (`Array<String>`)

```
GET /go/api/users
```

```json
{
  "_embedded": {
    "users": [
      {
        "login_name": "jdoe",
        "display_name": "John Doe",
        "enabled": true,
        "email": null,
        "admin": true,
        "roles": ["deployers", "manager"],
        "email_me": false,
        "checkin_aliases": [
          "jdoe",
          "johndoe"
        ]
      }
    ]
  }
}
```
</details>

<details>
  <summary>Get a single user</summary>

**Changes from previous version**: Introduce new attributes `admin` (`boolean`) and `roles` (`Array<String>`)

```http
GET /go/api/users/jdoe
```

```json
{
  "login_name": "jdoe",
  "display_name": "John Doe",
  "enabled": true,
  "email": null,
  "admin": true,
  "roles": [
    "deployers",
    "manager"
  ],
  "email_me": false,
  "checkin_aliases": [
    "jdoe",
    "johndoe"
  ]
}
```
</details>

<details>
  <summary>Create/Update a single user</summary>

See `GET` call above for the payload to submit

</details>

<details>
  <summary>Delete a single user</summary>

```http
DELETE /go/api/users/jdoe
```

```json
{
  "message": "User 'jdoe' was deleted successfully."
}
```
</details>

<details>
  <summary>Bulk delete users</summary>

Same as [previous version](https://api.gocd.org/current/#bulk-delete-users). No change.

</details>

<details>
  <summary>Bulk update users</summary>

```
PATCH /go/api/users
{
  "ids": [
    "jdoe",
    "alice"
  ],
  "operations": {
    "roles": {
      "add": ["Dev", "Test"],
      "remove": ["Production"]
    },
    "enabled" : true,
    "admin:": true
  }
}
```

```json
{
  "message": "Updated users(s) with id(s): [jdoe, alice]."
}
```
</details>

### Open questions that need answering

- The `admin` flag is "synthetic" in nature — in that the user record does not contain this information, and the information needs to be pulled in from the plugin.
- Need to decide if we need to allow updates with the `admin` field on the user (when creating, updating, or bulk updating). This field affects the config file. See #4936. We can possibly use the update [system admins api](https://api.gocd.org/18.12.0/#update-system-admins) instead of the `admin` flag.

**Comment by GaneshSPatil** [comment]
Users API v2 does not create a user with the provided `display_name` from the request. 
The display name is defaulted to the `login_name`. Should we allow admin users to specify `display_name` while creating the user?

**Comment by GaneshSPatil** [comment]
Users API v2 silently ignores `login_name` attribute passed while updating a user. Ideally, it should send a `422` response saying `Updating login_name of a user is not allowed.`

**Comment by GaneshSPatil** [comment]
@ketan @vrushaliwaykole -- Introducing update endpoint will cause the service to deal with both config_xml and DB in the same call. It's harder to guarantee the atomicity of the API call as we need to make sure API call succeeds with both config-file and DB updates.
As per the Users SPA (consumer of the API), the page does not perform multiple updates at the same time. A user can either enable, disable, make admin, or update roles from the user SPA, but only one operation at a time. hence, we are going ahead with separate endpoints for each operation.

Instead of update users endpoint, we will have:
* Bulk Enable Users endpoint
* Bulk Disable Users endpoint
* Bulk Make Admin endpoint
* Bulk Update Roles endpoint

\cc: @gocd/committers

**Comment by GaneshSPatil** [comment]
The new Users API endpoints:

##### Enable/Disable Users
Changes the state of a user. (enable or disable).

```curl
 curl 'http://localhost:8153/go/api/users/operations/state' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v3+json' \
      -H 'Content-Type: application/json' \
      -X PATCH \
      -d '{
      	"users": ["jez", "tez"],
      	"operations": {
      		"enable": true
      	}
      }'
```
---
##### Update Roles of Users
Adds or removes roles from a set of users.

```curl

curl 'http://localhost:8153/go/api/users/operations/roles' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v3+json' \
      -H 'Content-Type: application/json' \
      -X PATCH \
      -d '{
      	"users": ["jez", "tez"]
      	"operations": {
      		"add": ["role1", "role2"]
      		"remove": ["role3"]
      	}
      }'
```

---

##### Change Super Admin Permissions of Users
Makes a list of users super admins or removes them from super admins.

```curl
curl 'http://localhost:8153/go/api/users/operations/admin' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v3+json' \
      -H 'Content-Type: application/json' \
      -X PATCH \
      -d '{
      	"users": ["jez", "tez"]
      	"operations": {
      		"isAdmin": true
      	}
      }'
```

**Comment by akshaydewan** [comment]
For **Change Super Admin Permission of Users**, we can instead use the [System Admins endpoint](https://api.gocd.org/current/#system-admins)

```bash
curl 'http://localhost:8153/go/api/admin/security/system_admins' \
      -u 'admin:badger' \
      -H 'Accept: application/vnd.go.cd.v2+json' \
      -H 'Content-Type: application/json' \
      -X PATCH \
      -d '{
      	"users": ["jez", "tez"]
      	"operations": {
      		"isAdmin": true
      	}
      }'
```

**Comment by adityasood** [comment]
this was done as part of 19.1.0 release
