### ISSUE TITLE
Memory leaks (possibly with the errors/warnings modal)

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5559]
##### Issue Type

- Bug Report

##### Summary

Leaving the browser open for a few minutes seems to cause a browser tab to freeze. To test locally, we throttled the ajax poller to use 100ms polling interval (instead of 10s). We noticed that the JS heap, DOM elements remained more-or-less the same (they spike up and get GCed). However the number of listeners seems to consistently increase and does not go back to the original value after a GC. It seems some listeners are being leaked, I'm unsure which listeners are leaking.

**Comment by vrushaliwaykole** [comment]
Screenshot of the profiler:

![screen shot 2018-12-12 at 4 22 42 pm](https://user-images.githubusercontent.com/2168315/49865149-310fca00-fe2a-11e8-9249-a71ab09b157e.png)

Closer look at the listeners:

![screen shot 2018-12-12 at 4 22 50 pm](https://user-images.githubusercontent.com/2168315/49865157-379e4180-fe2a-11e8-9c6f-4107e4d73458.png)

Copy of the profiler output that can be loaded in the browser:

[Profile-leaks.zip](https://github.com/gocd/gocd/files/2671589/Profile-leaks.zip)

**Comment by adityasood** [comment]
the fix on this PR (https://github.com/gocd/gocd/pull/5591) has reduced the number of listeners generated and has helped in the performance. Closing this out for now.
