### ISSUE TITLE
Introduce search API for user search

### ISSUE THREAD

**Issue by vrushaliwaykole** [gocd/gocd#5560]
##### Issue Type

- Feature proposal

##### Summary

Need an API for user search in new users summary page.

- API to find users in authentication providers (github, LDAP, file...) using the [plugin api](https://plugin-api.gocd.org/current/authorization/#search-users) according to search string

### JSON response

```http
GET /go/api/users_search?q=j
```

```json
{
  "_embedded": {
    "users": [
      {
        "login_name": "jdoe",
        "display_name": "John Doe",
        "email": "john@example.com"
      }
    ]
  }
}
```

**Comment by adityasood** [comment]
verified on 19.1.0-8424
