### ISSUE TITLE
Config Repo Trigger Update doesn't work

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#5562]
The "refresh" button on the config repo is supposed to call `/api/internal/config_repos/:id/trigger_update`, but currently it is calling the wrong endpoint `/api/admin/config_repos/:id`.

I thought this would be a quick fix, but the URL for trigger_update is returning a 404, because it ends up going to the wrong controller. (The "Internal" controller instead of the "Operations" controller). My guess is that the regex in urlrewrite.xml is matching both the controllers.

```bash
~ » curl 'http://localhost:8153/go/api/internal/config_repos/test/trigger_update' -i \                                akshayd@in-akshaydewan
        -H 'Content-Type: application/json; charset=UTF-8' \
        -H 'Accept: application/vnd.go.cd.v1+json' \
        -u admin:badger
HTTP/1.1 404 Not Found
Date: Wed, 12 Dec 2018 11:30:16 GMT
Set-Cookie: JSESSIONID=node01w73236m5mlpm10a7izxyg090z6.node0;Path=/go;Expires=Wed, 26-Dec-2018 11:30:16 GMT;Max-Age=1209600;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: JSESSIONID=node0zu5u5sumftcm15cl563rak0gw7.node0;Path=/go;Expires=Wed, 26-Dec-2018 11:30:16 GMT;Max-Age=1209600;HttpOnly
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/vnd.go.cd.v1+json;charset=utf-8
X-Runtime: 1
Transfer-Encoding: chunked

<html><body><h2>404 Not found</h2></body></html>%
```

Interestingly, the `/status` and `/last_parsed_result` work fine.

**Comment by akshaydewan** [comment]
I guess the issue is not with `urlrewrite.xml`, but with the fact that we have ambiguous base URLs in two controllers: `ConfigReposInternalControllerV1` and `ConfigRepoOperationsControllerV1`

I'm not sure why we have split up these two controllers. @marques-work @kierarad @ibnc can one of you take a look?

**Comment by marques-work** [comment]
@akshaydewan well, @kierarad and I actually moved the trigger_update and the status endpoints to the internal controller in #5551. We could repurpose that PR to fix this issue (it's the only commit there at the moment).

**Comment by akshaydewan** [comment]
@marques-work Yes, you're right. I totally missed that

**Comment by marques-work** [comment]
@akshaydewan all good my friend :). I missed it myself the first time (and I wrote that endpoint) but caught it when I came back to it.

**Comment by rahulpargaonkar** [comment]
verified the issue. now the URL in API call is changed  as per /api/internal/config_repos/:id/trigger_update. closing it.
