### ISSUE TITLE
prevent running when  "gocd Built from incompatible revisions" might happen

### ISSUE THREAD

**Issue by chadnash** [gocd/gocd#5576]
##### Issue Type
 Feature proposal
##### Summary
allow pipelines to specify that they will not run if they are asked to run with incompatible revisions even if they are manually started or at least a warning BEFORE you force the run manually

I have found and implemented the several work arounds available like passing hashes in the pipeline label or putting auto stages ahead of manual ones. But these are unsatisfactory.

**Comment by arvindsv** [comment]
@chadnash I agree. I'm going to mark it as a duplicate of https://github.com/gocd/gocd/issues/429, though, which is very similar and has a bit more conversation. The final workaround mentioned there might also help, imo. It helps you stay consistent and remove the need to force trigger. But, it is a workaround, I understand.
