### ISSUE TITLE
UI Issues for 19.1.0

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#5585]
##### Issue Type

- Bug Report

##### Summary

Placeholder issue for all UI fixes we need in 19.1.0. Since we are near 18.12.0 release, any UI issues which are not mandatory to fix for 18.12 will be added to this issue

**Comment by GaneshSPatil** [comment]
Improve plugin description on plugins SPA:
  - [ ] Is the `Target Go Version` the right wording? As the value of the `Target Go Version` represents the minimum supported GoCD version. (>= `version`). Can it be `Minumum required GoCD version`?
  - [ ] replace `Go` with `GoCD`.

**Comment by GaneshSPatil** [comment]
Assigned to @vishaldevgire, As he is working on it.

**Comment by rajiesh** [comment]
Verified on 19.1.0 (8417-bc5413918eb9c792352710a4b6b79c64cea4f439)
