### ISSUE TITLE
Disable Job Settings button for Pipelines Defined in Config Repo on Elastic Profile Usage

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5604]
##### Issue Type
- Bug Report
##### Summary

The Job Settings link on elastic profile usage for pipelines defined in config repo currently gives a 403, it would be ideal to disable this button option altogether for such pipelines

###### Basic environment details

* Go Version: 18.12.0
* JAVA Version: Java10
* OS: MacOs
* Browser vendor and version (if relevant): Chrome71

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8603-c23c0aa4b894b1f75c24046060a1fd10328c2b25)
