### ISSUE TITLE
Show a warning if installed plugin is not supported by the current GoCD version

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5614]
##### Issue Type

- Feature enhancement

##### Summary

Each GoCD plugin defines, the minimum required GoCD version. There is no visual indication, that the installed plugin is not supported by the current GoCD version

###### Basic environment details

* Go Version: `18.12.0`

##### Steps to Reproduce

1. Start GoCD server
2. Install any incompatible version plugin

##### Expected Results
GoCD should show a visual indication (warning or gray out) of the installed plugin is not supported by the current version.

##### Actual Results
No visual distinction between a supported plugin and unsupported plugin

##### Possible Fix
Gray out the plugin box.

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8610-4713200bc880ce17014d826e20a30ed032e3ac26)
