### ISSUE TITLE
Do not cache elastic profile view or make this configurable for an Elastic agent plugin

### ISSUE THREAD

**Issue by prateekbaheti** [gocd/gocd#5617]
##### Summary

Do not cache elastic profile view or make this configurable for an Elastic agent plugin. 

When elastic profile settings depend on plugin settings (e.g. its values are a subset of a plugin setting value), fields in the profile can change depending on the plugin settings. 

Currently the profile view is loaded once when plugin is loaded and cached. Any change in plugin settings (or any other state) does not let you modify the profile's page. 
If the view was not not cached, that would help plugin developers build better a user experience.

P.S. This could be extended to other cached views

##### Environment

Basic environment details
- Go Version: `18.12.0`

##### Steps to Reproduce
1. Setup plugin setting with property `subnets = "subnet1, subnet2"`
2. Create Elastic profile view that depends on a subnets value and renders a dropdown with the 2 values.
3. Modify plugin setting, `subnets = "subnet1, subnet2, subnet3"`
4. Reload the elastic profile view

##### Expected Results
Profile view will render dropdown with all 3 subnet values

##### Actual Results
Profile view renders dropdown with initial 2 values

##### Possible Fix
* Cache views based on content hash.
* Cache view based on configuration (Plugin Capabilities ?)
* Do not cache the view

**Comment by arvindsv** [comment]
Count they use Javascript instead, to change the view? I feel that caching the view allows us to not have to keep going back to it again and again. That was, at least, the original idea.
