### ISSUE TITLE
Possible Perf Issue with Server Drain Mode

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5627]
##### Issue Type

- Bug Report

##### Summary

  - [x] DB call every 10 secs. **FIX:** _make ajax call every 30 secs instead of 10 secs_
         Server Drain Mode SPA polls for in-progress sub-systems every 10 secs, which makes a DB call to fetch all the running jobs information.  Fetching all the running jobs information every 10 secs from DB causes DB load. (Maybe we can cache this information at service)

  - [ ] ~~Server in-progress subsystem API should implement ETag~~ ETag won't help much as this is dynamic information and will keep changing.

  - [x] Do not send in-progress subsystem information when the server is not in drain mode.

**Comment by arvindsv** [comment]
@GaneshSPatil 

> Fetching all the running jobs information every 10 secs from DB causes DB load. (Maybe we can cache this information at service)

Don't we having a running jobs list in cache somewhere, already? To show in the agents page or for agent assignment or something?

**Comment by GaneshSPatil** [comment]
@arvindsv -- We don't have running jobs information at the Agent or BuildAssignment Service. 
As the job running by an agent is stored as part of `agentRuntimeInfo.AgentBuildingInfo`.

Though, we can consider following approaches:

#### Approach 1: Using Dashboard Cache.
* We've all the pipelines information in dashboard-cache. How about using dashboard cache to get the information about the running stages/jobs?
* It's little expensive to go over all the **_dashboard_pipelines_ -> _instances_ -> _stages_ -> _jobs_** and find the running jobs. But for sure less expensive than DB call over all the builds.

#### Approach 2: Using AgentRuntimeInfo and BuildAssignmentService
* Each agent knows what job it is building (if any) and BuildAssignmentService knows the jobs that needs to be scheduled. Using this combination, we can find all (building + pending) jobs.
* Scheduled jobs are not removed from BuildAssignmentService until its assigned to an agent.
* If an agent stop pinging the server in the middle of the building job, the agentInfo at the server side will still contain the `AgentBuildingInfo` until the job is rescheduled. And the rescheduled job will be in the pending jobs list of BuildAssignmentService

IMO, relying on dashboard cache is simpler and performant.

\cc: @bdpiparva

**Comment by arvindsv** [comment]
Alright, thank you!

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/5629 and https://github.com/gocd/gocd/pull/5641

Verified on GoCD Version: 19.1.0 (8315-49ddcb8a0a7c3c8fe85025b8ca2b443a5dfdbd62).
