### ISSUE TITLE
Do not validate plugin properties while deleting a plugin profile entity

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#5667]
##### Issue Type

- Bug Report

##### Summary

ArtifactStore, ElasticAgentProfile and SecurityAuthConfig all implement PluginProfile which validates the plugin properties by making a request to the plugin during deletion when it shouldn't - https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/service/PluginProfilesService.java#L91.

The update method is called from:
- https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/service/ElasticProfileService.java#L60
- https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/service/SecurityAuthConfigService.java#L70
- https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/server/service/ArtifactStoreService.java#L62

###### Basic environment details

* Go Version: `18.12.0`

**Comment by maheshp** [comment]
Done as part of https://github.com/gocd/gocd/pull/6053
