### ISSUE TITLE
Artifact Store SPA - no error if store cannot be deleted. 

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#5668]
##### Issue Type

- Bug Report

##### Summary
When an artifact store that is referenced in a pipeline is to be deleted, there is no error shown on the page. The delete prompt stays on, but doesn't show why the artifact store can't be deleted. 

###### Basic environment details

* Go Version: `19.1.0 (8304-8d0b69529a6f2bd8e8b8450e47cd01a1d68a67eb)`

##### Steps to Reproduce

1. Install some artifact plugin.
2. Configure an artifact store
3. Configure an external artifact in some pipeline using the above store.
4. Navigate to `go/admin/artifact_stores`, click on delete. A prompt appears, click on delete.

##### Expected Results

Should show why the artifact store can't be deleted.

##### Actual Results

The prompt stays on. Shows no error.

**Comment by rajiesh** [comment]
Verified on 19.1.0 (8417-bc5413918eb9c792352710a4b6b79c64cea4f439)
