### ISSUE TITLE
Add validation for PATCH endpoint in System Admins API

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#5682]
Related to #5558
Validations to be added:
- When trying to remove a user/role from the list of admins, verify that the user/role is actually an admin. This applies only to the API, and is not relevant when doing a config xml save.
- Verify that the role exists when trying to add it to the list of admins. This validation should already be implemented on the config-xml save, and so it should automatically work for the API as well.

Since we don't validate usernames in the config-xml while adding or removing admins, we won't validate them in the API either.

**Comment by adityasood** [comment]
Verified on 19.1.0-8424. The messaging needs to be improved for the following

1. When trying to add a non-existent role as an admin, today the API does not give back a meaningful message. Issue to track this is https://github.com/gocd/gocd/issues/5742
