### ISSUE TITLE
Functionality to add new role and assign it to users on User summary page

### ISSUE THREAD

**Issue by vrushaliwaykole** [gocd/gocd#5690]
##### Issue Type
- Feature enhancement

##### Summary

Functionality by which admin user can add a new role of type gocd in the system and assign new added role to selected users.

- Add a text box in Roles dropdown on user summary page.
- After adding the role, roles dropdown should be updated so that admin user can assign that role to selected user.

**Comment by adityasood** [comment]
verified on 19.1.0-8442
