### ISSUE TITLE
All Personalization tabs shows same pipelines as the default

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#5696]
##### Issue Type

- Bug Report

##### Summary

Creating a new personalization tab with selected list of pipelines still shows up all pipelines as in `Default` tab

###### Basic environment details

* Go Version: `19.1.0 (8380-4bc5d15ab9abbcfd5bb44ef482af1c090c6cd112)`

##### Steps to Reproduce

1. Create 2 pipeline P1 and P2 in pipeline groups G1 and G2 respectively
2. Ensure both pipeline groups shows up on Default personalization tab
3. Create new personalization view say V1 and select pipeline group G1 only and save the view
4. View V1 shows up groups G1 and G2(this is not expected. View V1 should show only G1)
5. Update default view to show only G2
6. Now view V1 will also show only G2(this is not expected. View V1 should show only G1)

**Comment by GaneshSPatil** [comment]
Broken after: https://github.com/gocd/gocd/pull/5683
Needs to change [this](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts#L73-L75) function to accept view-name and pass it as a query param.

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/5699

Verified on: GoCD Version: 19.1.0 (8413-45aab5e40d991f427cfb35a10463be3e9d58193b).
