### ISSUE TITLE
Major degradation of /goapi/admin/environments performance in gocd 18.10

### ISSUE THREAD

**Issue by m-johansson** [gocd/gocd#5698]
##### Issue Type
Bug Report

##### Summary
The /go/api/admin/environments request in previous gocd versions executed with a pretty much constant time irregardless of the complexity of the environments. In 18.10 and later versions (still present in 18.12) the time of the api call seems to scale linearly with the amount of pipelines present in the environment. The request execution time quickly becomes unusable.

The following is measured using the bare official docker images of the versions, adding 501 pipelines from the config xml, placing them in 1 environment.

18.9
Response times
0.916825
0.295599
0.28083
0.365918
0.307528

18.10
3.049708
1.6858
1.598177
1.559482
1.591198

The prompt of this investigation is that in our production environment we have a much more complex setup with a significant load - and there we have seen that this api call  increased it's execution time with more than 20x when we upgraded from 18.2 to 18.10. Issue is persistent in 18.11 which is our current production version. Doing the above test on 18.12 confirms that issue is still present.

##### Environment

The issue is reproduced by running the bare official docker images with 500 pipelines added to a single environment. The pipelines were added through the cruiseconfig.xml.

###### Basic environment details
Original setup from official docker images.
1.  Start docker image from docker hub
2.  Add 1 pipeline manually
3.  Add 1 environment manually, add the pipeline above to it
4.  Using a scripting language, multiply the xml specification of the pipeline to 501 and paste it into the xml
5. Also add the 501 pipelines to the environment in the xml, again using a scripting language.
6. Measure response time of the go/api/admin/environments api

##### Expected Results
No degredation in request execution time when upgrading version

##### Actual Results
Major degradation in request execution time.

**Comment by GaneshSPatil** [comment]
Hi @m-johansson,

Thanks for reporting the performance issue with Environments API.
We've faced a similar [performance issue with Agents API](https://github.com/gocd/gocd/issues/5399). 
We've upgraded a bunch of libraries, rails, JRuby and java as part of GoCD release `v18.10.0`. Upgrading the libraries have significantly affected the object serialization time (while making an API call) causing the performance regressions. 

As of now, there is no workaround for this problem. We request you to downgrade your GoCD instance to version <= `v18.9.0`.

We've considered this issue and will be putting in a fix for it in one of the upcoming releases of GoCD.
