### ISSUE TITLE
Improve error logging for authentication plugin

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#5701]
##### Issue Type

- Feature enhancement

##### Summary

Currently, unnecessary ERROR trace is logged in the authentication plugin logs when a user tries to login and part of the lower order authentication plugin user.

For instance, file-based authentication plugin is configured higher in the order than LDAP authentication, and if LDAP user logs in, GoCD sends it to file-based authentication first and logs an authentication ERROR in the logs and then goes to LDAP authentication plugin. or vice versa 
This causes unnecessary noise in the file-based authentication plugin logs.

**Comment by maheshp** [comment]
Done as part of 
https://github.com/gocd/gocd-ldap-authentication-plugin/pull/43 for LDAP plugin 
and 
https://github.com/gocd/gocd-filebased-authentication-plugin/pull/34 for file based plugin.

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.1.0 (8417-bc5413918eb9c792352710a4b6b79c64cea4f439).

**Comment by arvindsv** [comment]
@ankitsri11 If you verified both, can you also close https://github.com/gocd/gocd/issues/5714 ?
