### ISSUE TITLE
High cpu

### ISSUE THREAD

**Issue by greuelpirat** [gocd/gocd#5705]
##### Issue Type

- Bug Report

##### Summary

Viewing Tests-Tab results in High CPU Usage with low respondence in Chrome.

###### Basic environment details

Go Server Version: | 18.12.0 (8222-e6778f1cc84bf91e323d337c876046167da36985)
-- | --
JVM version: | 11.0.1
OS Information: | Windows Server 2016 10.0
Usable space in artifacts repository: | 948 GB
Database schema version: | 1808002
Pipelines Count: | 14

Chrome 71.0.3578.98 (Windows)

##### Steps to Reproduce

1.  Open Tests-Tab with failed Unittests

##### Expected Results
Viewing Unittests. CPU free

##### Actual Results
Viewing Unittests. CPU under full load

**Comment by arvindsv** [comment]
@greuelpirat When the CPU is under load, can you save the output of: http://your-server:8153/go/api/support ... every 10 or 20 seconds, 3 or 4 times and zip it up and provide it in a [gist](https://gist.github.com)?

That might help see what the server is doing. Without that, it's hard to understand what is happening - since it obviously doesn't happen to everyone (for instance, it's working fine with me).

Thank you!

**Comment by greuelpirat** [comment]
The CPU-Load happens not on the server. It is in the browser while viewing the Tests-Tab.

Here is a screenshot with Chrome.

![image](https://user-images.githubusercontent.com/16866222/51120123-b402b680-1814-11e9-8a23-5f3b3de859c4.png)

Can I send you the corresponding test-artifact?

**Comment by greuelpirat** [comment]
Here are the files. Hope you have everything.

[data.zip](https://github.com/gocd/gocd/files/2755789/data.zip)

Thank you for your help

**Comment by ketan** [comment]
@greuelpirat — Are you able to reproduce this in incognito mode, with all extensions disabled?

**Comment by greuelpirat** [comment]
The cpu load also occurs in incognito mode (with all extensions disabled)

I have also tried the docker-image, but there seems the test-pipeline to be missing:

    2019-01-28 08:55:25,552 ERROR [qtp2028371466-16] JobController:176 - Job detail page error:
    java.lang.RuntimeException: Job Test/2/defaultStage/1/defaultJob not found
        at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:30)
        at com.thoughtworks.go.server.controller.JobController.jobDetail(JobController.java:126)

**Comment by arvindsv** [comment]
@greuelpirat Oops. Small mistake in the commands:

```bash
git clone https://github.com/arvindsv/2019_01_24_data_to_help_with_gocd_issue_5705.git

cd 2019_01_24_data_to_help_with_gocd_issue_5705

docker run -it -p 8153:8153 -v `pwd`/data:/godata gocd/gocd-server:v18.12.0
```

**Comment by greuelpirat** [comment]
Docker image runs. With your image there is no issue.

But when I replace the files in `data\artifacts\pipelines\Test\2\defaultStage\1\defaultJob\` with the attached [defaultJob.zip](https://github.com/gocd/gocd/files/2803468/defaultJob.zip) the CPU load increases dramatically.

**Comment by arvindsv** [comment]
I updated the files in the repo with yours and I can reproduce this.

1. Do this:

```bash
git clone https://github.com/arvindsv/2019_01_24_data_to_help_with_gocd_issue_5705.git

# Just to confirm
git reset --hard 40792a958c43caa10625de96472441865b42c9cb

cd 2019_01_24_data_to_help_with_gocd_issue_5705

docker run -it -p 8153:8153 -v `pwd`/data:/godata gocd/gocd-server:v18.12.0
```

2. Use Chrome, not Firefox. First open the console log page: http://localhost:8153/go/tab/build/detail/Test/2/defaultStage/1/defaultJob#tab-console

3. Then, open the tests tab: http://localhost:8153/go/tab/build/detail/Test/2/defaultStage/1/defaultJob#tab-tests

... listen to the fans start up.

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8576-004ea5ec2257f2ef7bfbddfbf74ffa952ecb6dca)
