### ISSUE TITLE
Improve Config Repo Related Error Messages

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5712]
epic: #5650

Improvements:
  - [x] Render invalid merge configuration errors on separate line.
  - [ ] Avoid duplicate error messages
      -  [ ] Duplicate Message for `No profile defined corresponding to profile_id foo`

**Comment by GaneshSPatil** [comment]
Item 1 is done as part of PR: https://github.com/gocd/gocd/pull/5717

**Comment by FernandaCG** [comment]
Hi!, can I work on this?

**Comment by GaneshSPatil** [comment]
@FernandaCG - Sure! I will assign this issue to you.

The first point from the issue checklist has been fixed as part of #5717 (as mentioned in https://github.com/gocd/gocd/issues/5712#issuecomment-490005916). So we'll need to fix the point 2 from the checklist.

Here are some links that can help you get started with GoCD development setup:
1. [Setting up your development environment](https://developer.gocd.org/current/)
2. [Concepts in GoCD](https://docs.gocd.org/current/introduction/concepts_in_go.html)

For this particular issue, we need to create config repository which contains pipelines with duplicate errors, such as: 
More than 1 job using the same non-existing `elastic agent profile`. In such case `No profile defined corresponding to profile_id myprofile` error would be repeated for times equal to the number of jobs referring to `myprofile`.

Do reach out to us in case you need further help with this issue.

**Comment by FernandaCG** [comment]
Hi @GaneshSPatil ! 
I have a question, while I was setting up the environment, I got this error:

 > Could not GET 'http://rubygems-proxy.torquebox.org/releases/velocity-tools/velocity-tools-view/1.4/velocity-tools-view-1.4.pom'. Received status code 503 from server: Service Temporarily Unavailable

I don't know if you have some suggestions.

**Comment by GaneshSPatil** [comment]
Hi @FernandaCG -- This error possibly could happen due to torquebox.org maven mirror repository being down.
As mentioned in the [README.md](https://github.com/torquebox/jruby-maven-plugins#gem-artifacts), this repository delivers gem from rubygems.org as gem-artifacts.

I would suggest we try to rebuild the project.

**Comment by GaneshSPatil** [comment]
Hello @FernandaCG, I hope you're doing well. 

Following up to check if you're able to build the project as per the docs. 
Do let us know if you need any help with it.

Thanks and stay safe!
