### ISSUE TITLE
Update bundled versions of auth plugins to 1.0.3

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#5714]
##### Summary

This is done in https://github.com/gocd/gocd/pull/5713. This issue is a placeholder for testing it and making sure it works well in the final installer.

/cc @rajiesh @adityasood @ankitsri11

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.1.0 (8417-bc5413918eb9c792352710a4b6b79c64cea4f439).
