### ISSUE TITLE
Dashboard UI - provide option to create a pipeline under a pipeline group

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#5715]
##### Issue Type

- Feature enhancement

##### Summary

If the pipelines are grouped by pipeline groups on the dashboard, then provide an option to create a pipeline within that group from the dashboard for admins and group admins. This will avoid users having to go to `/go/admin/pipelines`, search for the specific group and then clicking on `Create a pipeline within this group.`

**Comment by GaneshSPatil** [comment]
Done as part of PR: https://github.com/gocd/gocd/pull/5885 in GoCD `v19.3.0`
