### ISSUE TITLE
Improvements to how users become admins

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5720]
##### Issue Type

- Feature enhancement

##### Summary

As things stand, not defining an [`<admins/>`](https://docs.gocd.org/current/configuration/configuration_reference.html#admins) tag, makes all enabled users in the DB system admins on GoCD.

This may be surprising for a lot of users who're attempting to setup GoCD for the first time. I'd like to consider changing how users become administrators.

/cc @arvindsv @maheshp

---

### For new installations, obviously with no users in the `<admins/>` section

The server comes online as before. There are no enabled users in the DB and the first user logs in as "anonymous" and sets up auth using an authorization plugin. When the first user actually performs a valid login, and there are no users in the `<admins/>` section, the first user that logs in will be added as an administrator.

All subsequent new users that get created by whatever means will no longer be admins. This will be a breaking change from the current behavior.

### For existing installations, with no users in the `<admins/>` tag, having authentication configured, with some enabled users in the db

All users enabled users in the DB will be copied into the `<admins/>` tag.

All subsequent new users that get created by whatever means will no longer be admins. This will be a breaking change from the current behavior.

### For existing installations, with no users in the `<admins/>` tag, having authentication configured, with no enabled users in the db

Same case as new installation described above.

**Comment by arvindsv** [comment]
Sounds good. About the "Make admin" and "Revoke admin": We could just have a rule that you are not allowed to make yourself admin or revoke admin permissions from yourself. Someone else needs to. That could make things easier. I know there are probably still corner cases around roles as admin, etc.

**Comment by arvindsv** [comment]
One aspect to explicitly call out:

If an instance already has security set up (authorization config exists) and there are real system administrators (if the `<admins/>` section exists in the config), then there will be _no change_ at all in behaviour.

**Comment by ketan** [comment]
The implementation here would involving adding listeners on the users "table" and `<admins/>` config entity and making decisions on whether users needs to be copied to the `<admins/>` tag.

Taking a look at the code, it appears that we'll have to change `UserSqlMapDao` to add `afterCommit` transaction callbacks which may update the config XML. The config XML update may take an unspecified amount of time, and hold possibly hold up DB connections, and directly impact performance by preventing any requests from being processed (every request hits the users table/cache to determine if a user is enabled).

We're shelving this for now, for lack of clarity on how to proceed further. Possible solutions is to add a separate poller thread which monitors the config and users table for changes and synchronizes them (either directly, or via a message added to a queue)

**Comment by arvindsv** [comment]
Closing for now based on Ketan's message.
