### ISSUE TITLE
Material URL in pipeline history API username is obfuscated

### ISSUE THREAD

**Issue by awangptc** [gocd/gocd#5727]
##### Summary

Fix for https://github.com/gocd/gocd/issues/5471 is overly greedy in obfuscating secure information.  The username of a ssh://user@host/repo URL is being obfuscated with `******`.

##### Environment

* Go Version: 18.12.0
* JAVA Version:  1.8.0_191
* OS: Linux 4.14.88-72.76.amzn1.x86_64
* Browser vendor and version (if relevant): Definitely not Internet Explorer 7 :)

##### Steps to Reproduce

1. curl https://go-server/go/api/pipelines/pipeline/history/0

##### Expected Results
We expected the material url to continue tto be
ssh://user@gitserver/repo

##### Actual Results
Instead we got something like
`"description": "URL: ssh://******@gitserver/repo.git, Branch: master",`

##### Any other info

We use the pipeline API for archive scripts to archive the git repositories that are referenced by each pipeline.  Obfuscating the repo URL makes this more difficult

**Comment by arvindsv** [comment]
@awangptc This should be changed in 19.1, through #5733. I can tell you when an experimental build for this is available, if you like.

**Comment by arvindsv** [comment]
Will keep this issue open till it is verified.

**Comment by rajiesh** [comment]
Verified on 19.1.0 (8460-9a992a31c0f1ae39d7b58b718bc4b5f9eca5ca8e)
