### ISSUE TITLE
oncancel task does not execute if original task hadn't yet started

### ISSUE THREAD

**Issue by jeremymv2** [gocd/gocd#573]
The oncancel task creation is a nice feature to have in lieu of a lack of a user not really being able to "Deny" an artifact's progress through a stage in a pipeline.  We have a "QA-Approval" Stage that ideally would have a way in which QA's can "Deny" acceptance.  I was thinking of using the "Cancel" feature of the Stage for this, by creating a oncancel task that would send emails stating that the Stage was "Not Approved".  However, if the user clicks the "Cancel" immediately after triggering it, prior to it being assigned to an agent and beginning, the oncancel Task never executes.

Regardless of how the oncancel task is used in a workflow, it if is ever defined, I think that when a user clicks the "Cancel" of a Stage Task, Go should ALWAYS still assign the oncancel task to an Agent and execute it.

**Comment by arvindsv** [comment]
Closing as stale.
