### ISSUE TITLE
Is there any GoCD plugin to send pipeline status to microsoft teams

### ISSUE THREAD

**Issue by harish123321** [gocd/gocd#5747]
##### Issue Type

- Security issue? [**DO NOT** report it here. Use [hackerone](https://hackerone.com/gocd) or send a mail to support@thoughtworks.com]
- Bug Report
- Feature proposal
- Feature enhancement
- Documentation Report
- Question? [**DO NOT** ask it here. Ask in the [mailing list](https://groups.google.com/forum/#!forum/go-cd)].

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. 
2. 
3. 
4.

**Comment by ketan** [comment]
Closing. The template clearly says:

> Question? [DO NOT ask it here. Ask in the mailing list]
