### ISSUE TITLE
Remove hard-wired icons on the config repos page

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5751]
##### Issue Type

- Feature enhancement

##### Summary

Because config repo plugins now implement the `get-icon` call.

**Comment by GaneshSPatil** [comment]
@ketan -- Do we still need to bump up the plugin_infos API? 
As there is no structural change in the plugin_infos API response.

Plugin Infos API will add the image href URL of the plugin icon if the plugin supports get-icon call.

As adding the support of get-icon plugin-api call for config repos plugin has a side effect on the plugin_infos API content, but not on the structural change of the API response.

**Comment by ketan** [comment]
> @ketan -- Do we still need to bump up the plugin_infos API?
> As there is no structural change in the plugin_infos API response.

We don't need this. The plugin infos seems to render the icon url just fine.
