### ISSUE TITLE
Environments page: Not showing agents through config-repos?

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#5761]
##### Issue Type

- Bug Report

##### Summary

See: https://github.com/tomzo/gocd-json-config-plugin/issues/36

When agents are assigned to environments through a config-repo, they don't seem to be showing in the environments page: `http://gocd-server/go/admin/environments`

###### Basic environment details

* Go Version: 18.12

/cc @mbotmcc @tomzo @ketan

**Comment by akshaydewan** [comment]
We probably need to think a bit about the interaction between Agents, Environments and Pipelines between config-repos and those configured from the UI. (Apologies if this has already been discussed)

Let's consider that we have:
2 pipelines: one configured from config-repo (named `firstpipe`), the other configured from the UI (named `up42`).
2 environments: one configured from config-repo (named `dev`), the other configured from the UI (named `test`). `firstpipe` belongs to `dev` environment and `up42` belongs to `test`
1 agent: Shared between both the environments/pipelines.

What I see on my box is that the sharing of agent does not work - As long as the agent has the `test` environment assigned from the UI, the `firstpipe` pipeline doesn't get assigned to the agent. When I remove the `test` environment from the agent, the job gets picked up without re-triggering it. (I didn't debug it, so I don't know what's causing this behaviour).

From the UI point of view, should the `dev` environment defined from the config-repo show up in the dropdown for Envrionments assignment on the Agents page?

**Comment by ketan** [comment]
> From the UI point of view, should the `dev` environment defined from the config-repo show up in the dropdown for Envrionments assignment on the Agents page?

Doing that would affect the config XML (by defining a "new" `dev` environment in the config xml), if that's what you're asking/implying. This is already doable by editing the config xml.

I'm not sure if it will be obvious to the end user that this assignment may actually end up creating a new environment. So IMO, the questions really should be:

- do we want to make it obvious that assignment will end up creating a new `<environment/>` in the config xml?
- do users really care where the environments are defined, or do they just care about the end result — that the agent is assigned to the environment?

**Comment by tomzo** [comment]
In older UI the environments page was showing environments, pipelines and agents which are defined via config-repo in grayscale and user could not change those. But then it got lost at some point when UI was updated.
I think user does not care unless something is impossible to change. I guess we should be displaying which elements of the config are read-only due to config-repo definition.

**Comment by arvindsv** [comment]
### Current state:

1. Assigning a pipeline to an environment: Can be done in the UI only through the environments edit page (`Admin -> Environments`). This adds a `<pipeline>` tag into `<environments><environment name="ABC"><pipelines>`.

2. Assigning an agent to an environment in the UI: Can be done in two ways. First: by editing in the environments page, similar to how you associate pipelines.  This adds an `<agent>` tag into `<environments><environment name="ABC"><pipelines>`.

3. Second way of assigning an agent to an environment in the UI: Select an agent (or agents) in the `Agents` page and choose an environment from the dropdown.

4. You can also assign an agent or pipeline to an environment through the config-repo plugins. This can be done to environments defined in the repo or to environments defined in the XML. The merge takes care of this.

5. You cannot assign a pipeline defined in a repo through the UI (in environments edit page), since the XML is not allowed to reference pipelines defined in repos.

### Beyond current state:

1. If we allow editing of an environment defined in the config repo, in the environments edit page, then there's the possibility of users removing pipelines from it, which won't be reflected in the source of truth (the config repo). So, that _part_ doesn't make sense to me. However ...

2. If we do want to allow it, we should allow them to only add existing pipelines and agents to it. The merge will take care of it. As @ketan said, this is already allowed by editing the XML. So, we might as well allow it in the UI. I don't think it matters that it adds a new tag to the XML.

3. If we are saying we will allow editing one of those environments, then we should also allow assigning an agent to a config-repo defined environment. Right? It's true that it will create a new environment _tag_ (but not really a new environment, since it already existed in the repo).

**Comment by maheshp** [comment]
@arvindsv from what I understand and tested, when an environment is added in ConfigRepo upon merge an empty `<environment/>` tag is created in XML. 
Even though the environment is defined in ConfigRepo, currently we allow users to edit the environment through GoCD to add/remove pipelines, agents and env variables defined only in the XML, which seems right to me.

For me the original issue wherein the agents coming through config_repos not listed is something we need to fix.

The other issue is on the agents page, on this page users are given an option to edit the environment for an agent added through ConfigRepo, but users cannot actually edit it. This behaviour seems wrong to me.

**Comment by arvindsv** [comment]
> The other issue is on the agents page, on this page users are given an option to edit the environment for an agent added through ConfigRepo, but users cannot actually edit it. This behaviour seems wrong to me.

I see what you're saying. An agent has been associated with an environment, through a config repo. But, in the agents tab, we need to decide what to do, when they dis-associate it or associate it with other environments.

I think, again, it goes back to the concept of a merge: If there are two places that the information comes from, and a merge decides the final state, then weird things like this should be expected to happen.

In this case, either we identify that this environment was associated with this agent via a repo, or we ignore it completely and allow a user to un-check it (dis-associate it), but it'll get assigned to that environment right after the merge again. That might be confusing, but there is a valid reason for it.

So, in my opinion, what should be fixed is what you mentioned: The fact that agents associated through config-repos don't show up in the environments page.

I'll try it out - I think there might also be a bug around assigning pipelines in this page (considering a case where a pipeline is already associated with an environment through a config-repo).

**Comment by arvindsv** [comment]
@maheshp This video shows what happens now: https://www.dropbox.com/s/wdlqak5pqvflm5n/2019_01_25_Issue_with_association_agents_with_envs_in_config_repos.mov?dl=1

I think most of it is ok. Issues:

1. In the Admin -> Environments page, agents associated using config repos do not show in the summary view. Once you click "Edit", they show.

2. When editing, it is allowed to dis-associate an agent. But, as soon as you save, the agent will come back (as the config repo is where it is associated from). This is correct, but could be a little confusing, since unchecking the checkbox is allowed.

3. When you try to make any other changes to the agents (associating new agents), it should be allowed, but it throws an error. This should probably be silently allowed (or, we should mark those agents properly and disregard them from all further edits).

**Comment by arvindsv** [comment]
I'd say point (1) in the list above is the one that needs to be fixed first. (2) and (3) are related.

**Comment by maheshp** [comment]
@arvindsv the video was helpful. I agree with the proposed fixes on the environments page. I would prefer an approach where we disabled editing agents associated through the ConfigRepo similar to how pipelines are disabled. But we need to have some indicator/tool-tip which indicates why editing is disallowed.

On the similar lines we need to fix dis-associating environments on agents page where the association is through ConfigRepo,

**Comment by rajiesh** [comment]
Environments page changes to show environment from config repos with a tool tip and disabled for edit is verified on 19.2.0 (8576-004ea5ec2257f2ef7bfbddfbf74ffa952ecb6dca). Will wait for the agents page changes before closing this issue
