### ISSUE TITLE
Pipeline or Stage creation fails with 500 on gocd 18.11.*

### ISSUE THREAD

**Issue by brewkode** [gocd/gocd#5773]
##### Issue Type

Pipeline/Stage creation fails with 500. The server log says ```Could not find task of type: null```.
```
2019-01-25 12:56:01,300 ERROR [qtp1166151249-6132523] Rails:-1 - Java::JavaLang::RuntimeException (Could not find any task of type: null):
2019-01-25 12:56:01,301 ERROR [qtp1166151249-6132523] Rails:-1 -   
2019-01-25 12:56:01,301 ERROR [qtp1166151249-6132523] Rails:-1 - com.thoughtworks.go.server.service.tasks.TaskViewService.taskInstanceFor(com/thoughtworks/go/server/service/tasks/TaskViewService.java:88)
com.thoughtworks.go.config.Tasks.setConfigAttributes(com/thoughtworks/go/config/Tasks.java:108)
com.thoughtworks.go.config.JobConfig.setConfigAttributes(com/thoughtworks/go/config/JobConfig.java:460)
com.thoughtworks.go.config.JobConfigs.setConfigAttributes(com/thoughtworks/go/config/JobConfigs.java:113)
com.thoughtworks.go.config.StageConfig.setConfigAttributes(com/thoughtworks/go/config/StageConfig.java:335)
java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:470)
org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:328)
RUBY.create(app/controllers/admin/stages_controller.rb:43)
org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:525)
org.jruby.RubyBasicObject.send(org/jruby/RubyBasicObject.java:1752)
org.jruby.RubyKernel.send(org/jruby/RubyKernel.java:2182)
```

##### Summary

We recently ugraded our GoCD from 15.x to 18.11 and then to 18.12.0. Followed the steps for migration as outlined in the docs and found that the upgrade went through and the server started up. We have a bunch of plugins that we use internally and those also got registered properly. Pipeline triggers / alerts work fine. 

We found out that pipeline creation fails, so does stage creation to existing pipelines. Task addition succeeds though. 

##### Environment

Full Environment details from GoCD support api - https://gist.github.com/brewkode/acebc39b5704bad16d28be3d29aba710

###### Basic environment details

* Go Version: 18.12.0
* JAVA Version: 1.8.0_151
* OS: Linux 2.6.32-431.1.2.0.1.el6.x86_64
* Browser vendor and version : Latest Firefox 64.0

##### Steps to Reproduce
Setup GoCD 18.11.* version. Download the latest release of s3.fetch plugin from https://github.com/indix/gocd-s3-artifacts and add it to the plugin dir of your gocd installation.

Now, try adding a stage to the existing pipeline or create a new pipeline. You will see a 500 error on your browser. If you look at the server logs, you will see the error trace which leads you to this cause 
"Could not find task of type: null" 

We tried the same thing on 18.7.x version of gocd and things worked perfectly fine with the same plugin. I tried tracing the network call from both these versions and tried tracing it.

From GoCD - 18.7 - Inspect Element - Network tab - Params tab
```
utf8    ✓
authenticity_token    ...
config_md5    fa1753eb2919be55b0f43972e38cc198
current_tab    stages
stage[name]    test123
stage[approval][type]    success
stage[jobs][][name]    test123
stage[jobs][][tasks][taskOptions]    ant
stage[jobs][][tasks][ant][buildFile]    
stage[jobs][][tasks][ant][target]    
stage[jobs][][tasks][ant][workingDirectory]    
stage[jobs][][tasks][nant][buildFile]    
stage[jobs][][tasks][nant][target]    
stage[jobs][][tasks][nant][workingDirectory]    
stage[jobs][][tasks][nant][nantPath]    
stage[jobs][][tasks][rake][buildFile]    
stage[jobs][][tasks][rake][target]    
stage[jobs][][tasks][rake][workingDirectory]    
stage[jobs][][tasks][pluggable_task_indix_s3publish][sourceDestinations]    
stage[jobs][][tasks][pluggable_task_indix_s3publish][destinationPrefix]    
stage[jobs][][tasks][pluggable_task_indix_s3publish][artifactsBucket]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][MaterialType]    Package
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Repo]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Package]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Material]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Job]    […]
0    
1    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][SourceType]    Default
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Stage]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][SourcePrefix]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Source]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Destination]    
```
and the corresponding `params` object in the rails layer in `admin/stages_controller.rb` looks like 
```
  {
   "name": "test123",
   "approval": {
     "type": "success"
   },
   "jobs": [
     {
       "name": "test123",
       "tasks": {
         "taskOptions": "ant",
         "ant": {
           "buildFile": "",
           "target": "",
           "workingDirectory": ""
         },
         "nant": {
           "buildFile": "",
           "target": "",
           "workingDirectory": "",
           "nantPath": ""
         },
         "rake": {
           "buildFile": "",
           "target": "",
           "workingDirectory": ""
         },
         "pluggable_task_indix_s3publish": {
           "sourceDestinations": "",
           "destinationPrefix": "",
           "artifactsBucket": ""
         },
         "pluggable_task_indix_s3fetch": {
           "MaterialType": "Package",
           "Repo": "",
           "Package": "",
           "Material": "",
           "Job": "",
           "SourceType": "Default",
           "Stage": "",
           "SourcePrefix": "",
           "Source": "",
           "Destination": ""
         }
       }
     }
```

From GoCD - 18.11 - Inspect Element - Network tab - Params tab
```
utf8    ✓
authenticity_token   ...
config_md5    b310c50052ef27d919ceb80da5ae18d0
current_tab    stages
stage[name]    test
stage[approval][type]    success
stage[jobs][][name]    test
stage[jobs][][tasks][taskOptions]    ant
stage[jobs][][tasks][ant][buildFile]    
stage[jobs][][tasks][ant][target]    
stage[jobs][][tasks][ant][workingDirectory]    
stage[jobs][][tasks][nant][buildFile]    
stage[jobs][][tasks][nant][target]    
stage[jobs][][tasks][nant][workingDirectory]    
stage[jobs][][tasks][nant][nantPath]    
stage[jobs][][tasks][rake][buildFile]    
stage[jobs][][tasks][rake][target]    
stage[jobs][][tasks][rake][workingDirectory]    
stage[jobs][][tasks][pluggable_task_indix_s3publish][sourceDestinations]    
stage[jobs][][tasks][pluggable_task_indix_s3publish][destinationPrefix]    
stage[jobs][][tasks][pluggable_task_indix_s3publish][artifactsBucket]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][MaterialType]    Package
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Repo]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Package]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Material]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Job]    […]
0    
1    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][SourceType]    Default
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Stage]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][SourcePrefix]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Source]    
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Destination] 
```
and its corresponding `params` object from `admin/stages_controller.rb`

``` 
 {
   "name": "test",
   "approval": {
     "type": "success"
   },
   "jobs": [
     {
       "name": "test",
       "tasks": {
         "taskOptions": "ant",
         "ant": {
           "buildFile": "",
           "target": "",
           "workingDirectory": ""
         },
         "nant": {
           "buildFile": "",
           "target": "",
           "workingDirectory": "",
           "nantPath": ""
         },
         "rake": {
           "buildFile": "",
           "target": "",
           "workingDirectory": ""
         },
         "pluggable_task_indix_s3publish": {
           "sourceDestinations": "",
           "destinationPrefix": "",
           "artifactsBucket": ""
         },
         "pluggable_task_indix_s3fetch": {
           "MaterialType": "Package",
           "Repo": "",
           "Package": "",
           "Material": "",
           "Job": "",
           "SourceType": "Default",
           "Stage": ""
         }
       }
     },
     {
       "tasks": {
         "pluggable_task_indix_s3fetch": {
           "Job": "",
           "SourcePrefix": "",
           "Source": "",
           "Destination": ""
         }
       }
     }
   ]
 }
```

Now, if we look at this, the `18.11` has an extra `job` definition related to `s3 fetch plugin`, which is not being generated in `18.7` version. We noticed there has been a huge set of changes on the rails and other areas between 18.7 & 18.11, so we wanted to check whats happening here and how could we resolve this?

Thanks in advance.

**Comment by arvindsv** [comment]
@brewkode It [looks like](https://github.com/indix/gocd-s3-artifacts/commit/636708bbf5b02f6d358d5336332e8bb17b4033a3#diff-ce93394cfaecff6434c5aced0bf0b63bR76) the plugin is making changes to the context of the form it is in. That is not recommended. It's probably causing a side effect.

So, I'm closing this issue for now. You should probably open an issue over on the plugin's repository.

Since I don't have enough context on this change, this is just based on a cursory glance. If you and/or @manojlds believe it is a problem with GoCD core itself, I'm happy to reopen this. Thank you.

**Comment by brewkode** [comment]
@arvindsv I noticed that with the plug-in but I didn't raise it was because it was working with 18.7. So, I presumed something about how the server handles it has changed. 

Now, if you look at my report, you will see that the form params on both versions are same. However as it enters the rails layer, the input payload has got restructured a bit. If you can help me with how the request gets processed until the rails controller part, it would help me debug this further too. 

I can revert to an older plug-in version as a workaround before either fixing here or in the plug-in. 

Let me know.

**Comment by arvindsv** [comment]
@brewkode Yes, that's what I mentioned in the "Edit" part. I think it's fair. I'll reopen it and we (someone or I) can look more into it.

**Comment by arvindsv** [comment]
@brewkode 

> If you can help me with how the request gets processed until the rails controller part, it would help me debug this further too.

That happens deep inside Rails + Rack. As far as I can see, it looks like it's happening because of some changes in how jruby-rack works across the different versions used between 18.7 and 18.11, _along with_ the submitted form data having some inconsistencies which might be because of the plugin.

To reproduce this, you can use this: [gh_5773_files.zip](https://github.com/gocd/gocd/files/2799533/gh_5773_files.zip). You can see the difference in the output of the form data parsing between the two versions:

```bash
docker run --rm=true -v `pwd`/gh_5773_files:/tmp/files gocd/gocd-server:v18.7.0 /tmp/files/for.18.07.sh
```

```bash
docker run --rm=true -v `pwd`/gh_5773_files:/tmp/files gocd/gocd-server:v18.11.0 /tmp/files/for.18.11.sh
```
As you can see, in 18.11, the extra node appears in the output. This seems to be because of this duplication in the submitted form data (which I think is happening because of the plugin's code):

```
stage[jobs][][tasks][pluggable_task_indix_s3fetch][Job]    […]
0    
1
```

If you look at the raw output, it looks like this (duplicate lines marked by me):

```
$ tr '&' '\n' <gh_5773_files/body.original.txt | sed -e 's/%5B/\[/g' -e 's/%5D/\]/g' | tail
pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][Repo]=
pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][Package]=
pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][Material]=
>>> DUPLICATE: pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][Job]=**
pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][SourceType]=Default
pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][Stage]=
>>> DUPLICATE: pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][Job]=**
pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][SourcePrefix]=
pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][Source]=
pipeline_group[pipeline][stage][jobs][][tasks][pluggable_task_indix_s3fetch][Destination]=
```

If you remove the duplication, which you can do by:

```
cp gh_5773_files/body.corrected.txt gh_5773_files/body.txt
```

... then, the two docker commands shown above will return identical output.


If you're debugging this further, something like this might help too:

```bash
./server/scripts/jruby -rrack/utils -rpp -e 'pp Rack::Utils.parse_nested_query(File.read("./gh_5773_files/body.txt"))'
```

In my view, even though this looks like an incompatibility between versions of Rack, it's unlikely to be fixable by making changes in GoCD core, easily. It's also probably not the right place to do that. Unless, it is the code in core (on the view side) which is adding that extra part to the input.

I think a better fix would be to check if the plugin is messing with the form data (by adding a new text field with the same name) or something, and see if it can be fixed there. What do you think?

PS: I _think_ it's happening through [this line](https://github.com/rack/rack/blob/90afdf309b4c0665f542579a21fbd1c285d05083/lib/rack/request.rb#L215). Rack version 1.6.8 used by jruby-rack-1.1.21. Not sure.

**Comment by brewkode** [comment]
@arvindsv Great analysis. I will try repro-ing this and get back to you. We can fix the plugin now more confidently, if that's what is needed. Thank you. Let me do try repro-ing this, will post plugin related analysis as well and then we could close this. Appreciate your time.

**Comment by brewkode** [comment]
@arvindsv We've now created an [issue](https://github.com/indix/gocd-s3-artifacts/issues/67) against the plugin and will track the resolution there. Thanks for helping out on this. Much appreciated.
