### ISSUE TITLE
For Group Admin role,Status report button is disabled for Docker elastic plugin on plugin page.

### ISSUE THREAD

**Issue by rahulpargaonkar** [gocd/gocd#5776]
##### Issue Type

- Bug Report

##### Summary
For Group Admin role,Status report button is disabled for Docker elastic plugin on plugin page.
But same button is enabled on elastic profile page and when clicked  a 403 error is displayed

##### Environment

* Go Version: 19.1.0 (8460-9a992a31c0f1ae39d7b58b718bc4b5f9eca5ca8e

##### Steps to Reproduce

1.  Login as Group admin user
2.  go to plugins page
3.  see the 'Status Report' button is disabled for docker elastic plugin but the same button is enabled on elastic agent profile page.

##### Expected Results
The behaviour  should be consistent on both plugin page and elastic profile page or the button should not be disabled on plugins page as the same group admin page has an access of elastic profile page.
 

<img width="1440" alt="screen shot 2019-01-28 at 12 47 44 pm" src="https://user-images.githubusercontent.com/33080845/51820203-fb9c3e80-22fa-11e9-90d6-0e59afbd2f57.png">
<img width="1440" alt="screen shot 2019-01-28 at 12 47 15 pm" src="https://user-images.githubusercontent.com/33080845/51820204-fb9c3e80-22fa-11e9-9630-da13ccc7c1d2.png">

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8525-905b1b4cb27ef7b34d632336ecb76cfd97697d0d)
