### ISSUE TITLE
Add debug logs for backup process

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5779]
This is required to help troubleshoot issues faced during the GoCD server backup process.

**Comment by ketan** [comment]
Do you have specific examples of what sort of log statements you'd like to see?

**Comment by adityasood** [comment]
@ketan the following is what would be nice to have if we enable debug logs

1. Start and end time messages for the backup
2. Start and end time for different parts (config,DB etc.)
3. If there could be a bit more granular logging that would be great.

**Comment by maheshp** [comment]
Done as part of https://github.com/gocd/gocd/pull/6129
