### ISSUE TITLE
Improve backup API.

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5781]
##### Issue Type

- Feature enhancement

##### Summary

The backup HTTP API call (and the backup button) is blocking in nature, so the HTTP connection is not closed until the backup is completed. This is particularly problematic for a couple of reasons:

- the HTTP connection remains open during the period the backup is in progress, with no HTTP data-transfer. This causes the client/server/reverse proxy to drop the connection, depending on the timeout settings
- There's no guarantee to the end user if the backup completed in case the connection drops (for whatever reason)

A better alternative might be to offline the backup process in a separate thread/queue, with an HTTP 202 (accepted) response containing a resource URL that can be polled on. See [Request/Acknowledge/Poll](http://servicedesignpatterns.com/clientserviceinteractions/requestacknowledge).

**Comment by prateekbaheti** [comment]
## Proposed solution:
- When a backup creation request is received, ServerBackup object is created and persisted in the db. Backup processing is started asynchronously. A 202 response is sent with a Location header with a URL for polling for the ServerBackup object. We can return a polling interval in payload using the Retry-After header.
- ServerBackup will have 2 new attributes:
     - **state**: It could have the values "in-progress, successful or error"
     - **message**: This could have a message about what part of the processing is in progress or the error that occurred.
These 2 new attributes could be persisted in memory too, happy to discuss either approaches. DB made more sense if were to return the entire object in the polling request.

- Client can poll the returned URL from the 202 response to get the ServerBackup object with its state and message. This path will have to be whitelisted in BackupFilter so it does not give a 5XX response.
- On success state the client can choose to update the UI accordingly with the backup information which will now also have the file path.
- While backup is in progress we can update the backup page with the state of the backup.
- If another request for creating a backup is received while already processing, the current behavior continues where the response says its in maintenance mode.

**Optimization**: BackupFilter is run on each request and an additional DB call will be needed on every request to check if Backup is in progress. To optimize, we can track the in-progress state in the BackupService also (like done currently).

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)
