### ISSUE TITLE
Back button does not work on dashboard

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5788]
##### Issue Type

- Bug Report

##### Summary

Using the back/forward button to switch between views on the dashboard seems to have stopped working at some point in the last month or so.

**Comment by akshaydewan** [comment]
I tried this, and it takes a good 5-10 seconds for the view to change, but it does change eventually (I think when the next call is made by the poller).

I remember seeing this filed as a bug somewhere, but I can't find it now.

**Comment by arvindsv** [comment]
@akshaydewan Maybe https://github.com/gocd/gocd/issues/3283 ?

**Comment by akshaydewan** [comment]
@arvindsv That wasn't the one. It was probably on a checklist of "known issues" with the new dashboard.

**Comment by arvindsv** [comment]
Ok.

**Comment by varshavaradarajan** [comment]
Closing this as fixed. By #5810. Please re-open if needed.
