### ISSUE TITLE
Problem starting Go Agent on Windows

### ISSUE THREAD

**Issue by NDaves** [gocd/gocd#5802]
##### Summary
I have installed Go Server and Go Agent 19.1 64 bit on Windows 10 64bit and getting the following error 
while trying to start Go Agent. Both, Go Server and Agent are installed on the same separate Windows 10 in the same network.

**The Go Agent service terminated with the following service-specific error: 
Incorrect function.**

##### Environment
```Go Server and Go Agent 19.1 64 bit on Windows 10 64bit```

###### Basic environment details
* Go Version: `19.1 64 bit`
* JAVA Version: `1.8`
* OS: `Windows 10 64bit`

##### Steps to Reproduce
1.  Install Go Agent
2.  Start Go Agent service

##### Expected Results
Go Agent should start without error

##### Actual Results
Getting error as below.
**The Go Agent service terminated with the following service-specific error: 
Incorrect function.**

**Comment by ankitsri11** [comment]
@NDaves Do you see any log files (go-agent-launcher.log, go-agent-bootstrapper.log, go-agent.log etc) under Go Agent log directory (C:\Program Files\Go Agent\logs)?  
If yes, can you share it with us? Thanks.

**Comment by NDaves** [comment]
Yes, I have attached the files for your review.

[go-agent-launcher.log](https://github.com/gocd/gocd/files/2830918/go-agent-launcher.log)
[go-agent-bootstrapper.log](https://github.com/gocd/gocd/files/2830919/go-agent-bootstrapper.log)
[go-agent-bootstrapper-wrapper.log](https://github.com/gocd/gocd/files/2830920/go-agent-bootstrapper-wrapper.log)

**Comment by ankitsri11** [comment]
@NDaves It looks like you have GoCD server URL pointed as http (http://172.20.11.6:8153/go). Could you update server as https://172.20.11.6:8154/go.

```
INFO   | jvm 1    | 2019/02/04 22:49:44 | [Mon Feb 04 22:49:44 IST 2019]   Application arguments: [-serverUrl, http://172.20.11.6:8153/go]
INFO   | jvm 1    | 2019/02/04 22:49:44 | [Mon Feb 04 22:49:44 IST 2019]            GoCD Version: 19.1.0-8469
INFO   | jvm 1    | 2019/02/04 22:49:44 | -serverUrl must be an HTTPS url and must begin with https://
```

**Comment by arvindsv** [comment]
No update. Closing.
