### ISSUE TITLE
SPA to list, generate and revoke access token

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#5803]
##### Issue Type

- Feature proposal

### List access tokens
- [ ] A user should be able to see a list of access token created by him/her.
- [ ] As a user I should be able to see when the token is last used.
- [ ] An admin user should able see and revoke the access token created by other users.
- [ ] As an admin user should be able to search for access tokens for the user

### Generate access tokens
- [ ] As a user I should be able to create access token(s) with name and description.

### Revoke access tokens
- [ ] A user should be able to revoke access token created by him/her.
- [ ] Optionally, A user should be able to provide a reason of revoking an access token
 	- Not in scope. need to discuss with the team, but this is good to have along with who revoked the access token.
- [ ] A user should get a confirmation dialog when he/she revokes the token
- [ ] A user should be able to see revoked access token in the list with revoked time.

/cc @naveenbhaskar

**Comment by bdpiparva** [comment]
@gocd/committers - As per discussion, we decided to do the two separate views -

1. View to list tokens created by the user. The link for this will be available in `Username` dropdown after the `Preferences`  link

2. View for the admin to manage system-wide tokens. The link for this will be available under `SECURITY` in the `Admin` menu.

**Comment by rajiesh** [comment]
Test Scenarios:

Test Data:

Users with below roles

* Admin
* Group Admin
* Template Admin
* View
* Operate
* Users without any roles defaults to view user for groups which are not provided with authorization
* Combination of above roles

Users from below authentication plugins:

* Password file
* LDAP
* Web auth plugin

Scenarios:

* [ ]  Users in all roles should have access to access tokens page
* [ ]  Users in all roles should have option to generate access tokens by providing appropriate description
* [ ]  SPA should display the token only ones at the time of creation for user to copy and save it and never again. Tokens list view should only show description and other metadata.
* [ ]  Users in all roles except admin should view ONLY tokens created by them
* [ ]  Users in all roles except admin should be allowed to revoke ONLY their own token
* [ ]  SPA should provide option to fill in revoked reason
* [ ]  Super admin users should be able to view all tokens in the system
* [ ]  Super admin users should be able to revoke any tokens
* [ ] Admin's view of SPA should have easy way(the word "easy" mentioned here is relative, how its implemented to be decided in the UX discussions) to list Admin's own tokens, Others Tokens, revoked tokens. Its all about the UX, more details will be included in the UX discussions on this story
* [ ] Users should not be able to use the access token as password for web logins. Access tokens are exclusively for API calls
* [ ] SPA should be verified on all supported browsers which are mentioned [here](https://docs.gocd.org/current/installation/system_requirements.html)

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8639-9ba73d561b80d9d4e20dbf903aaeb3d29fcd3ab4)
