### ISSUE TITLE
Show warning if plugin extension is not supported by GoCD version

### ISSUE THREAD

**Issue by vrushaliwaykole** [gocd/gocd#5804]
##### Issue Type

- Feature enhancement

##### Summary

Enhancement related to issue #5614. Currently, there is no check for maximum supported GoCD version for extension used by plugin.

###### Basic environment details

* Go Version: `19.1.0`

##### Steps to Reproduce

1. Start GoCD server
2. Install any plugin with extention which is incompatible with current GoCD version (which was supported in earlier version but support was removed in recent version)

##### Expected Results
GoCD should show a visual indication (warning or gray out) of the installed plugin is not supported by the current version.

##### Actual Results
No visual distinction between a supported plugin and unsupported plugin

##### Possible Fix
Gray out the plugin box.

**Comment by arvindsv** [comment]
Remember that a single plugin can now support multiple extensions.

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8639-9ba73d561b80d9d4e20dbf903aaeb3d29fcd3ab4)
