### ISSUE TITLE
Pipeline export should consider exec tasks with args as attribute

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#5814]
##### Issue Type

- Bug Report

##### Summary

Currently we still allow a task to be created as below by directly editing the cruise-config.xml - 
```
<tasks>
    <exec command="ls" args="-l" />
</tasks>
```
When we export pipeline with this task the resulting JSON is -

```
"tasks": [
            {
              "command": "ls",
              "timeout": -1.0,
              "arguments": [],
              "run_if": "passed",
              "type": "exec"
            }
          ]
```

Arguments is empty as its defined in the attribute of exec task. Similar result on YAML config too.

Currently from UI we cannot create a config with args in attribute, but from cruise-config.xml we can. This issue was encountered on one of our internal GoCD server instance which is running for years. So this can be faced by old installation of GoCD server when they come to use the export feature. Need to find a way to handle it.

###### Basic environment details

* Go Version: `19.1.0-8469`
* JSON config repo plugin: `0.3.6`
* YAML Config repo plugin: `0.8.6`

**Comment by ibnc** [comment]
Looking into this

**Comment by ibnc** [comment]
@rajiesh I'm closing this issue. If you notice any issues please reopen it
