### ISSUE TITLE
Deletion of auth config should revoke access token

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5819]
##### Issue Type

- Feature enhancement

##### Summary

Upon deletion of the auth config id, all the access token belonging to that auth config id should be revoked.

**Comment by GaneshSPatil** [comment]
##### Edge Case Scenario:
Let's say, an auth config is deleted from GoCD, all the access token belonging to that auth config id will be revoked.
But, if administrators adds another auth config with the same id, should the access token work again?

**Comment by maheshp** [comment]
The auth_config id can be renamed by editing config.xml.

**Comment by rajiesh** [comment]
Currently not planned to be fixed as per the comment [here](https://github.com/gocd/gocd/issues/5321#issue-373778685). So closing it, will reopen when planned to fix
