### ISSUE TITLE
Allow specifying reason for revoking access token, and username that revoked the token

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5821]
##### Issue Type

- Feature enhancement

##### Summary

Allow users to specify (an optional) reason for revoking access token.

**Comment by GaneshSPatil** [comment]
@ketan -- Also does it make sense to store the username who has revoked the token?
As the owner of the accesstoken or the system admin can revoke the token.

**Comment by ketan** [comment]
> @ketan -- Also does it make sense to store the username who has revoked the token?

I think that makes sense. I'll add that to the scope here.

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8610-4713200bc880ce17014d826e20a30ed032e3ac26)
