### ISSUE TITLE
Disallow users to use Access Token APIs in case plugin does not have capabilities.

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5822]
##### Issue Type

- Bug Report

##### Summary

For using access tokens, the API requires plugins to have the capability to `get-roles` and `is-valid-user`  extension API calls.

If the plugin does not support fetching roles and validating the existence of a user. The access token is not useful. As the user won't be able to use it to access GoCD APIs.

Hence, if the user tried to create an access token for an auth config id belonging to a plugin which does not have capabilities required for access token feature, GoCD server should not allow the creation of access token against such auth config id.

**Comment by GaneshSPatil** [comment]
This issue needs to be relooked again. For some reason, this feature has been reverted.

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8639-9ba73d561b80d9d4e20dbf903aaeb3d29fcd3ab4)
