### ISSUE TITLE
Add a cache store for access token related plugin calls

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5823]
##### Issue Type

- Feature enhancement

##### Summary

Currently, when an access token is used, the GoCD server makes a call to the plugin to check the user belonging to the access token is still valid (the `is-valid-user` call) and if the user is valid, it makes a call to fetch the roles belonging to the user (the `get-roles` call). Making these calls to the plugin on each use of access token is expensive, as the plugin needs to talk to the remote provider(LDAP or Github) to fetch this information.

Making this request on every API call might cause rate limiting or performance problems. Hence, we should cache this information for some interval (expecting it to be `30 mins`).

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8610-4713200bc880ce17014d826e20a30ed032e3ac26)
