### ISSUE TITLE
Update last used time for access token

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5824]
##### Issue Type

- Bug Report

##### Summary

Access token GET API has `last_used` metadata field which specifies the last used time for the given access token. 
But even after using the access token, the last used time for the token is not updated.

##### Things to watch out for which implementing this feature:
1. The last used time of an access token should be logged regardless of the GoCD endpoint it is used for. (regardless of method type as well)
2. Need to think about throttling it for a while as making a DB call for updating it on every API request will cause DB performance problems.

**Comment by bdpiparva** [comment]
#### 1. What can be logged/stored when the access token is used for the API authentication?
|   **Data Type**   |                      **Description**                                               |
|:-----------------:|:----------------------------------------------------------------------------------:|
| API name          | Information about which api is accessed.                                           |
| API Client        | Client information (e.g. browser info)                                             |
| Scope             | Scope of access token when it is used (e.g. User was an admin when token is used.) |
| Date              | Date and time the token is used.                                                   |
| IP address        | From which IP request was made. This may reveal user physical location.            |

Above mentioned information is useful to log. 

## This can be done using the following approaches -

### 1. Timer based

Have a timer(e.g. every minute) in place which periodically dumps the `last used` information to the database. 

### 2. Eviction based

Have a self-expiring cache in place, which dumps `last_used` information to the database on cache eviction.

Currently,  Going ahead with `Spring Timer Based` implementation later we can change it if needed.

**Comment by arvindsv** [comment]
You might need to have a shutdown hook too, to _try_ and add info of the last minute, etc. to the DB upon shutdown.

**Comment by rajiesh** [comment]
Created a separate issue for logging improvements for access token requests [here](https://github.com/gocd/gocd/issues/5923). Closing this issue
