### ISSUE TITLE
Elastic Agent Extension: Add console log request processor to write to job console

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#5829]
##### Issue Type

- Feature enhancement

##### Summary

While the EA plugin is in the process of creating an agent for a job, it can write some information about the agent being created, errors during the creation process to the job console? This will help keep users informed of what is happening while the agent is being created by the plugin. If there are errors during the creation process, it can be seen only in the plugin logs currently and is not an ideal experience to figure out what is wrong when a job is scheduled but an elastic agent is never assigned. 

Related: https://github.com/gocd/kubernetes-elastic-agents/issues/78#issuecomment-456860128

**Comment by bdpiparva** [comment]
I submitted the PR #4277 for this a long ago. It did not make it to master because of a few concerns and one of the concern was https://github.com/gocd/gocd/issues/4578.

**Comment by arvindsv** [comment]
@bdpiparva I see. Ok. I'd like us to take a look to see if we can get past those concerns. I don't see why the job console should be off limits and why we even need different kinds of processors. I feel there should be one, for the job console and plugins can write to it.

**Comment by maheshp** [comment]
Done as part of - https://github.com/gocd/gocd/pull/6299 in 19.5.0
