### ISSUE TITLE
Stage history and job history UI does not look good in IE

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#583]
I checked it on IE9 and IE11

![job-history-details-ie](https://cloud.githubusercontent.com/assets/6175869/4399625/f03d7414-446f-11e4-9617-7893cf0f87ed.png)

![stage-history-details-ie](https://cloud.githubusercontent.com/assets/6175869/4399627/0251948c-4470-11e4-984c-9852c1623c05.png)

**Comment by GaneshSPatil** [comment]
IE11 and older versions of IE are not supported by GoCD.
Closing this issue as `WONT-FIX`.
