### ISSUE TITLE
Secrets Management [EPIC]

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#5830]
##### Issue Type

- Feature proposal

##### Summary

Currently secrets in GoCD are managed by encrypting them as secure environment variables or as secure configuration properties. While the secrets are encrypted there is scope for managing them better. Some of current pain points with managing secrets are,

1. Secrets are all over the place. The same secret can be defined across multiple environments, pipelines etc. Not centralized.
2. Secrets visibility. There is no good place to view all the secrets defined and where they are used.
3. Any time a secret is rotated, things would break in GoCD till the secrets are not updated manually in GoCD.
4. Access control to secrets is blurred and manual.

**Proposed solution**
1. Use an external secrets manager e.g Vault, AWS Secrets Manager etc to define secrets and manage in a centralized location. The external secrets manager would provide the following,
    - Centralized location for all secrets
    - Ability to rotate secrets
    - ACL
    - Auditing
2. GoCD to provide new Secrets Management plugin endpoints. Using these endpoints plugin authors can support an external secret manager of their choice. #5831
  a. Enhance Secrets Management Plugin Endpoint https://github.com/gocd/gocd/issues/6018
3. GoCD provides an ability to define and configure secrets_config. The secrets configuration would be specific to a plugin to would be used to lookup for secrets. #5832
4. How to use external secrets in GoCD? https://github.com/gocd/gocd/issues/5834
GoCD to introduce a concept of secret_params. The secret_params are resolved at runtime. e.g If a param is defined in a job, just before assigning the job to an agent, the server makes a request to the plugin to lookup for the secrets and the appropriate value is passed to the agent.
~~- #{SECRET[secret_identity_id][lookup_string]} (this can be changed appropriately)~~
Agreed secret param format `{{SECRET:[secret_config_id][lookup_string]}}`
5. Support secret params in Materials - #6014 
6. Support secret params in Materials enhancements - #6136
7. Support for Rules in SecretConfig #6095
8. API which supports CRUD operations for secrets_config. https://github.com/gocd/gocd/issues/5835
9. SPA which supports CRUD operations for secrets_config. https://github.com/gocd/gocd/issues/5837
10. Secret Params configuration and UX https://github.com/gocd/gocd/issues/5836
11. File based secrets management plugin https://github.com/gocd/gocd/issues/5838
12. Implement support to return plugin info for secret extension plugins https://github.com/gocd/gocd/issues/6079
13. Documentation

**Comment by rajiesh** [comment]
Verified on 19.6.0 (9492-738c70cbc80a2d13eea09e5b1c9432a175a0f5b7) of GoCD server and 1.0.0-33 version of file based secret plugin
