### ISSUE TITLE
Secrets Management Plugin Endpoint

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#5831]
Part of https://github.com/gocd/gocd/issues/5830

##### Summary

Provide the following endpoints to support secrets management.
1. Get Plugin Icon
2. Get Secrets Configuration
3. Get Secrets Configuration View
4. Validate Secrets Configuration
5. Lookup Secret(s) (Validate the look response for https://github.com/gocd/gocd/issues/5831#issuecomment-480740743)
6. List secrets in path. - Should list all secret keys in a path with the lookup string. This will be used on the UI.
6. Validate secret - This would be required when defining secrets through UI, users would want to validate if the secret key provided is valid while configuring.

**Comment by arvindsv** [comment]
Capability?

**Comment by maheshp** [comment]
> Capabilities call?

Capabilities is still an open question. I was considering all the call listed here needs to be mandatory, some are required for better UX. We can add capabilities if required.

**Comment by bdpiparva** [comment]
Added following validation on lookup secret response - 

- Error out with `SecretResolutionFailureException` if plugin sends
  additional secret params in lookup secret response.
  
  > Lookup request
   ```
   requestBody = ["key1", "key2"]

   ```
  > Response with addtional secret params
  ```
   responseBody = [
	{key: "key1", value="value-1"},
	{key: "key2", value="value-2"},
	{key: "key3", value="value-3"}
   ]
   ```
   This will throw `SecretResolutionFailureException` with the message -

   ```
    Expected plugin to resolve secret(s) `key1, key2` but plugin sent addition 
    secret param(s) `key3`.
   ```

- Error out with `SecretResolutionFailureException` if plugin fails to
  resolve one or more secret params as part of lookup secret response
  and sends partially resolved secret params in response.

   > Lookup request 
   ```
     requestBody = ["key1", "key2", "key3"]
   ```
   >  Response with partially resolved secret params
   ```
  responseBody = [
	{key: "key1", value="value-1"}
   ]
   ```
   This will throw `SecretResolutionFailureException` with message -
   ```
   Expected plugin to resolve secret(s) `key1, key2, key3` but plugin failed resolve secret 
   param(s) `key2, key3`. Please make sure that secret with same name exist in 
   your secret management tool.
   ```

**Comment by adityasood** [comment]
verified on 19.3.0-8914
