### ISSUE TITLE
Secrets Configuration

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#5832]
Part of #5830

##### Summary

1. Provide an ability to define secrets_configuration in config_xml. A configuration will have the following,
- id
- pluginId
- description
- plugins secrets_configuration
- rules
```xml
<secretConfig id="my_secret" pluginId="gocd_file_based_plugin">
    <description>All secrets for env1</description>
     <configuration>
        <property>
            <key>PasswordFilePath</key>
            <value>/godata/config/password.properties</value>
        </property>
    </configuration>
    <rules>
        <allow action="refer" type="environment">env_*</allow>
        <deny action="refer" type="pipeline_group">my_group</deny>
        <allow action="refer" type="pipeline_group">other_group</allow>  
    </rules>
</secretConfig>
```

2. Rules defines where a Secrets configuration can be used. e.g using rule one should be able to define which environment, pipeline or pipeline_group can use the secret configuration to lookup for secrets.
The rule should be deny by default and users should provide appropriate configuration to allow use of the configuration.

3. Rules needs to be validated for proper syntax. Also validate the env or pipeline_group used are valid.

4. What else can be the scope of the secrets, pipeline_group, environment?

**Comment by varshavaradarajan** [comment]
> 4\. What else can be the scope of the secrets, pipeline_group, environment?

Templates. :) 

Will there be authorization on secrets_config to restrict some users or roles from accessing some secrets?

**Comment by maheshp** [comment]
@varshavaradarajan 

> Templates. :)

Yes, we need to support templates, https://github.com/gocd/gocd/issues/5834 has few more details.

> Will there be authorization on secrets_config to restrict some users or roles from accessing some secret configurations?

I think there are two things to consider, first, we are introducing the concept of `scope` using which admins can define where a particular secret_config can be used, probably they might consider restricting it to a specific pipeline_group or environment.

The other thing bout authorization, currently most of the operations are very restrictive, e.g config_repo, elastic_profiles etc can be configured only by System Admins, we are considering changing the authorization model which would let System Admins allow specific users or roles to configure some of these entities. WDYT?

**Comment by akshaydewan** [comment]
When we pick this up, we should give some thought to the syntax we want to use, so that it can be de/serialized and validated easily.

For e.g.
```xml
<scope> 
    <deny>
       <pipelines group="pg1"/>
    </deny>
    <allow>
        <pipelines group="*"/>
    </allow>
  </scope>
```

**Comment by arvindsv** [comment]
@akshaydewan I feel that it's too verbose and a little rigid. If we wanted to allow something like: `reference_to:elastic_profiles:*` or something, this (non-)format is open, in a sense. It needs to be deserialized strictly (so this "language" should be defined properly) but we need to think about what shows here from a user's perspective - not a code perspective.

I'm not sure that the format shown is the right one, of course. It might be too open and confusing too. But, it'll need to be documented well.

**Comment by arvindsv** [comment]
Only super admins can create secrets configuration?

**Comment by arvindsv** [comment]
Of course, I understand that not defining it as a proper XML will limit our ability to do migrations, which is troubling. Do we have any thoughts about how to keep it easy for usage, while allowing that flexibility?

**Comment by maheshp** [comment]
> Only super admins can create secrets configuration?

For now yes, once we implement granular authorization we should be able to extend it to secrets config as well.

**Comment by prateekbaheti** [comment]
What about something like this ?
```
<scope>
    <pipeline_group effect="deny">dev</pipeline_group>
    <pipeline_group effect="allow">prod</pipeline_group>
    <pipeline_group effect="allow">*</pipeline_group>
<scope>
```
The effect attribute is inspired by AWS policies.

**Comment by arvindsv** [comment]
@prateekbaheti Yes, we should consider something like this. Can we come up with a (made up) list of possible actions and effects to see how this approach could look? That list might be useful to see if slight variations work better or worse, say `<allow entity="pipeline_group">...`.

**Comment by arvindsv** [comment]
@maheshp says above: "Scope defines where a Secrets identity configuration can be used". Some of our entities in the configuration are: Global SCMs, templates, pipeline groups, pipelines, environments, elastic agent profiles, auth configs, package repository configs, config repos.

**Comment by maheshp** [comment]
@arvindsv and I had a discussion around this. The term `<scope/>` seems very restrictive to just `Secrets`. We might want a similar model for other global entities like SCM's, Elastic agent profiles etc. Considering this requirement, we were thinking of the below structure,

```
<rules>
   <allow action="refer" type="environment">env_*</allow>
   <deny action="refer" type="pipeline_group">my_group</deny>
   <allow action="refer" type="pipeline_group">other_group</allow>  
</rules>

```

**Comment by prateekbaheti** [comment]
In terms on config repo the rule defines what the repo is allowed to refer as oppose to where it can be referred. I feel the refer action be misunderstood there.
At the risk of making it more verbose, how about actions being
- reference-by
- reference-to (in case of config repo)

**Comment by arvindsv** [comment]
@prateekbaheti Yes. In the case of config repo, it means:

- A pipeline can be defined in this config repo, which can be part of pipeline group X.
- A pipeline can be defined in this config repo, which can be associated with environment Y.

I agree we should choose the right names. However, each entity we apply this to will have a separate set of actions with different meanings. If we feel it's better to make it more verbose to be more clear, I think that's fine.

**Comment by vishaldevgire** [comment]
Can there be a use case similar to Elastic Agents clusters here? where we have two or more instances of same type of secrets vault/source? Example: For file based secrets plugin, we have two different files containing secrets.

**Comment by bdpiparva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Foo https://github.com/gocd/gocd/pull/5952](https://trello.com/c/000PaOwb/1-foo-https-githubcom-gocd-gocd-pull-5952)

**Comment by bdpiparva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Foo https://github.com/gocd/gocd/pull/5952](https://trello.com/c/000PaOwb/1-foo-https-githubcom-gocd-gocd-pull-5952)

**Comment by rajiesh** [comment]
Verified on 19.6.0 (9484-0a730da3fc38b435e1e70ef4084a32ec0757b7e8)
