### ISSUE TITLE
Support for Secrets Params

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#5834]
Part of #5830

##### Summary

GoCD should provide an ability to support Secret Params. Unlike the normal params the secret params should be evaluated only during runtime. e.g If the value of an environment variable is defined as a secret param, when a job is scheduled before assigning a job to an agent the GoCD server should make a request to the appropriate plugin to lookup for secret using the key provided in the secrets_param. The returned secret value would be passed to the agent.
    e.g {{SECRET:[teamX_vault][staging.db_password]}}
    For the above example the GoCD server will derive the plugin from the secret_configuration_id 'teamX_vault' and make a request to the plugin to lookup for secret using the lookup string staging.db_password.

1. Add an ability to define secret params in GoCD. The format for secret param - `{{SECRET:[secret_configuration_id][lookup_string]}}`

## Support for Secret Params in Environment Variables

- [x] 1. Provide ability to define secret params in environment variable value.
- [x] 2. Users can configure secret_params in either normal or secure environment variable, in either case the environment variables need to be masked.
- [x] 3. A environment variable can have multiple secret params defined, it should be appropriately resolved.
   e.g value = "{{SECRET:[id][key1]}}-{{SECRET:[id][key2]}}" should resolve to foo-bar  where key1 -> foo and key2 -> bar
- [x] 4. Secrets Param resolution for environment variables (PR #6072)
	a. The secret params should be resolved just before assigning a job to an agent.
	b. A given job can have multiple secrets params defined, we should lookup for all the secrets in one request rather than making a request per secret_param.
	c. On secret param resolution failures we should do the following,
	   - Fail the job
	   - Job console log should have appropriate error message.
	   - If an elastic agent is created for the job, the plugin should get a job completion message 
- [x] 5. Validation (#6085)
    a. Ensure the secret param has a valid secret_config_id

- [x] 6. Support for Secret Param defined in config_repos.
- [x] 7. Validate environment variable when a pipeline is triggered with option

**Comment by arvindsv** [comment]
Secrets can also be used in config repo pipelines, right? In materials and environment variables (at this point).

**Comment by maheshp** [comment]
> Secrets can also be used in config repo pipelines, right? In materials and environment variables (at this point).

Yes, anything supported in config.xml should be extended to ConfigRepo pipelines as well.

**Comment by maheshp** [comment]
> Secrets can also be used in config repo pipelines, right? In materials and environment variables (at this point).

Yes, anything supported in config.xml should be extended to ConfigRepo pipelines as well.

**Comment by vishaldevgire** [comment]
I don't know if we have considered this or not, so I will post it here:

1. From user experience point of view, UI should provide the ability to validate `secret_param` from where it's being used. So that user wont have to wait for pipeline to fail, can be sure that the secret is accessible and has right scope. 
  OR 
User never composes secret param but just copies it from some SPA (where we define secrets configuration?)

2. From what I understand, the lookup_string in `secret_param` is going to be some kind of path and it's actual syntax depends on the plugin(vault implementation), this can create problems if that path's syntax has symbols that we are using in `secret_param` syntax.  e.g. lets say in `{SECRET[secret_configuration_id][lookup_string]}` if lookup_string is `secrets[foo]{bar/baz}`
   - We can have one level of redirection for lookup_string.

**Comment by arvindsv** [comment]
Since the secret param can be used from many places, say within in a task, it won't be possible to provide validation in all places, I think.

It's true, we will need to have some restrictions within the lookup string. We might need to disallow `[`, `]`, etc. `lookup_string` is itself a level of redirection. Adding one more level (and so, introducing a concept in between) would be overkill, imo.

**Comment by adityasood** [comment]
Scenarios:
Pre-requisites
With Security ( have a password file)
Create a secret-param conf file with four env variables

1. api-user - A user with admin priviledges defined in the password file
2. api-user-password - Password of the above mentioned admin user
3. git-password- Password for one of your git repos
4. api-user-2 - A user with admin priviledges defined in the password file and same password as api-user

Steps:

1. Create an environment named secret_param_env.
2. Create a pipeline named secret_param_pipeline.
3. Assign secret_param_pipeline to secret_param_env environment.
4. Define two Environment Variables for secret_param_env environment:
    a.) DEPLOYMENT_PASSWORD = {{SECRET:[my_secret1][api-user-password]}}
    b.) DEPLOYMENT_USER = {{SECRET:[my_secret1][api-user]}}
5. Create a task to curl the version of the current GoCD sever:

```curl -k 'https://localhost:8154/go/api/version' -u $DEPLOYMENT_USER:$DEPLOYMENT_PASSWORD -H 'Accept: application/vnd.go.cd.v1+json'```

6. Assert for text on job console :  "version" : "19.3.0" and "build_number" : "8777" update the version and build number as per the current setup

7. Add two environment variables for the current stage:

    a.) git_password={{SECRET:[my_secret][git-password]}}
    b.) DEPLOYMENT_USER = {{SECRET:[my_secret1][api-user-1]}} // overriding the env here

8. Add another task to git clone of one of your repos and use envrionment variable git_password

`git clone https://<your-git-username>:$git_password@github.com/<your-git-repo-url>.git
`
9. Run the pipeline and assert for text "SecretParam 'api-user-1' is used before it is resolved."

10. Add one envrionment variable for the current job:

  a.)  DEPLOYMENT_USER = {{SECRET:[my_secret1][api-user-2]}}

11. Assert for text on job console :  "version" : "19.3.0" and "build_number" : "8777" update the version and build number as per the current setup.

12. Define a config repo with one envrionement two envrionment variables (with secret param as values) and use these env variables in the pipeline defined in config-repo

13. Define another cruise-config.xml pipeline, add it to env defined via config-repo and use the env variables defined in config-repo in a task.

The above setup was manually verified on both linux and windows system.
