### ISSUE TITLE
Secret Params configuration and UX

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#5836]
Part of https://github.com/gocd/gocd/issues/5830

##### Summary

A secrets param will have a lookup_string e.g ```#{SECRET[secret_identity_id][lookup_string]}```
The lookup string is specific to a plugin, for example a vault can have multiple secrets defined in a path ```secret/hello```. Now the plugin is at liberty to define the lookup string for a key under the path ```secret/hello```. For example it could be one of the below,
  a. [secret/hello.key1]
  b. [hello.key1]

While configuring secret_params through UI, provide an ability to lookup for available keys for a given path. There will be multiple places wherein we could be using the secrets_param, would it be feasible to provide an ability to lookup for secrets in multiple places or provide a single place to lookup probably in the Secrets Configuration SPA.

**Comment by arvindsv** [comment]
I suppose it's fair to say that the lookup string will not be allowed to have a `[` or `]` character.
