### ISSUE TITLE
SPA to manage Secrets Configuration

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#5837]
Part of https://github.com/gocd/gocd/issues/5830

##### Summary

Provides ability for the following,
1. List all secret configurations
2. Provide ability create, edit, view and delete secrets_config
3. Add an ability to list all usages of a secret configuration.

#### Rules support for secret config
1. Add support to define rules while adding/updating/cloning secret configs
2. List existing rules on secret config while editing
3. Add support to ordering the rules within the secret config

**Comment by bdpiparva** [comment]
- [ ] Create a new spa for `secret configs` using gradle task `./gradlew newSPA -PspaName=secret_configs`
- [ ] Understand the files generated by above classes
- [ ] Change a title of the page to `Secret Configs`
- [ ] Add a `ADD` button in header panel


- [ ] Write a model for secret configs(take reference from [Access Token](https://github.com/gocd/gocd/blob/3b679bc498e0af3d84204bca0c81a156930b5431/server/webapp/WEB-INF/rails/webpack/models/access_tokens/types.ts))
- [ ] Add a api call to -
	- [ ] get all secert config
	- [ ] get a secret config
	- [ ] delete a secret config
	- [ ] update a secret config

- [ ] Implement fetchData to get secret configs data using API calls
- [ ] Make a widget to list all secret configs

**Comment by viraj2712** [comment]
> * [x]  Create a new spa for `secret configs` using gradle task `./gradlew newSPA -PspaName=secret_configs`
> * [x]  Understand the files generated by above task
> * [x]  Change a title of the page to `Secret Configs`
> * [x]  Add a `ADD` button in header panel
> * [ ]  Write a model for secret configs(take reference from [Access Token](https://github.com/gocd/gocd/blob/3b679bc498e0af3d84204bca0c81a156930b5431/server/webapp/WEB-INF/rails/webpack/models/access_tokens/types.ts))
> * [ ]  Add a api call to -
>   
>   * [ ]  get all secert config
>   * [ ]  get a secret config
>   * [ ]  delete a secret config
>   * [ ]  update a secret config
> * [ ]  Implement fetchData to get secret configs data using API calls
> * [ ]  Make a widget to list all secret configs

**Comment by bdpiparva** [comment]
Implemented in PR #6235 and #6253

**Comment by rajiesh** [comment]
Verified on 19.6.0 (9492-738c70cbc80a2d13eea09e5b1c9432a175a0f5b7)
