### ISSUE TITLE
File based secrets management plugin

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#5838]
Part of https://github.com/gocd/gocd/issues/5830

##### Summary
This would be required for testing while we build the entire secrets manager feature.
Also, derive a skeleton plugin.       

##### Secrets file
Plugin will read secrets from a file, this file will have following JSON structure, note that the `cipher-key` and `secrets` are stored in the same file. Plugin will receive path to this file as a parameter from GoCD.

```json
{
  "secret_key": "<encoded-cipher-key>",
  "secrets": {
    "username": "<encrypted-secret>"
  }
}
```

##### Command line utility 
In order to help user generate and update secrets file, we have implemented a command line utility which will be part of the plugin jar (executable jar).

This utility will allow users to do following:
1. `init`: This operation will generate a secrets file with following JSON structure along with a cipher-key.

    ```json
    {
      "secret_key": "<encoded-cipher-key>",
      "secrets": {}
    }
    ```
2. `add`: Allows user to add/update secrets in existing secrets file
3. `remove`: Removes secret from a existing secret file
4. `show`: Prints a decrypted secret value on console

 <details><summary>Usage</summary>
 <p>

```bash
Usage: <main class> [options] [command] [command options]
  Options:
    --help, -h
      Prints this help.
  Commands:
    init      Initialize the secret database file
      Usage: init [options]
        Options:
        * --file, -f
            The path to the secret database file.

    add      Adds a secret
      Usage: add [options]
        Options:
        * --file, -f
            The path to the secret database file.
          --name, -n
            The name of the secret to remove.
          --value, -v
            The value of the secret.

    remove      Removes given secret
      Usage: remove [options]
        Options:
        * --file, -f
            The path to the secret database file.
          --name, -n
            The name of the secret to remove.

    show      Returns value for given secret
      Usage: show [options]
        Options:
        * --file, -f
            The path to the secret database file.
          --name, -n
            The name of the secret to remove.
```

 </p>
</details>

**Comment by adityasood** [comment]
@vishaldevgire are we capturing the discussion around this somewhere?

for e.g  I remember some conversation in the standup where we said we will encrypt the entire file.

If it is captured somewhere can you point me to it?

**Comment by vishaldevgire** [comment]
File based plugin will read/write secrets to and from a file. This file will have secrets stored on each line in the format `key encrypted(value)`. In order to help user generate and update this file we are  implementing a command line utility which will be part of the plugin jar. 

This command line utility will allow users to do following:

1. Generate a key for cipher: We are going to use an AES cipher, this command will generate a file with key(encoded in base64).
2. Add a secret: This command will accept secrets-file-path, cipher-key-file-path, key and value.  it will perform one of the following operation:
   - If file exists, Add/Update a secret
   - If file does not exist, create the file and add secret
3. Lookup a secret: This command will accept a secret-file-path, cipher-key-file-path and key of the secret and will return decrypted secret value
4. Delete secret?

**Comment by adityasood** [comment]
> File based plugin will read/write secrets to and from a file. This file will have secrets stored on each line in the format key encrypted(value). In order to help user generate and update this file we are implementing a command line utility which will be part of the plugin jar.

@vishaldevgire @kritika-singh3 what will be the scope of the plugin itself? The description says the plguin will be able to read/write secrets to and from a file. Will this also be able to generate a cipher file? My guess is not, do you think we should define a flow of how the user can use the plugin and utility together?

**Comment by vishaldevgire** [comment]
> > File based plugin will read/write secrets to and from a file. This file will have secrets stored on each line in the format key encrypted(value). In order to help user generate and update this file we are implementing a command line utility which will be part of the plugin jar.
> 
> @vishaldevgire @kritika-singh3 what will be the scope of the plugin itself? The description says the plguin will be able to read/write secrets to and from a file. Will this also be able to generate a cipher file? My guess is not, do you think we should define a flow of how the user can use the plugin and utility together?

Hey Aditya, the secrets plugin will only read (lookup) secrets, however command line utility will read/write secrets from file. I will change the text to reflect that.

**Comment by vishaldevgire** [comment]
This is how the command line utility looks:

`java -jar build/libs/file-based-secrets-plugin-0.0.1.jar`
```
usage: java -jar plugin_jar option [arguments]
 -a,--add <SECRETS-FILE-PATH> <CIPHER-FILE-PATH> <KEY> <VALUE>   Updates a secrets file with given secret(key=value)
 -d,--delete <SECRETS-FILE-PATH> <KEY>                           Deletes a secret with the given key from secrets file
 -g,--generate-key <CIPHER-OUT-FILE-PATH>                        Creates a cipher file at given location containing 128 bit key encoded as base64
                                                                 string
 -l,--lookup <SECRETS-FILE-PATH> <CIPHER-FILE-PATH> <KEY>        Returns  plain text value for a secret
```

@arvindsv Multiline secret values work because the values are encrypted and base64 encoded.

**Comment by adityasood** [comment]
@vishaldevgire following is the current list of issues with the plugin

1. Add option: Without the -v or -n flag the utility currently throws a null pointer exception. This should ideally be handled and we should show usages.

2. Show option: Without -n option the utility currently returns with message "Secret name null was not found". This should show up usages.

3. Remove option:  Without -n option the utility currently returns with message "Secret name null was not found". This should show up usages.

**Comment by vishaldevgire** [comment]
> @vishaldevgire following is the current list of issues with the plugin
> 
> 1. Add option: Without the -v or -n flag the utility currently throws a null pointer exception. This should ideally be handled and we should show usages.
> 2. Show option: Without -n option the utility currently returns with message "Secret name null was not found". This should show up usages.
> 3. Remove option:  Without -n option the utility currently returns with message "Secret name null was not found". This should show up usages.

PR to fix these: https://github.com/gocd/gocd-file-based-secrets-plugin/pull/12

**Comment by rajiesh** [comment]
Verified plugin version `1.0.0-33`
