### ISSUE TITLE
Discard changes does not work in a given scenario

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#584]
Steps to Reproduce:

1) Make some changes on a page. Ex - 'General Options' tab on pipeline edit
2) Without saving the changes, try to click on Admin menu
3) A pop up appears asking 'There are unsaved changes on your form. Proceed will discard your changes' 
4) Click on Proceed and it doesn't do anything

Essentially you are stuck till you reset changes on that form in order to proceed ahead.

**Comment by arvindsv** [comment]
Closing as stale.
