### ISSUE TITLE
Allow filtering tokens based on whether they are revoked

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#5844]
##### Issue Type

- Feature enhancement

##### Summary

The API currently lists all tokens for a user, this can get particularly long for users that periodically revoke tokens.

Would be nice to only list "active" tokens by default, and provide a query param to list all/revoked tokens:

* Show active tokens: `curl https://ci.example.com/go/api/access_tokens`
* Show all tokens: `curl https://ci.example.com/go/api/access_tokens?all=true`
* Show only revoked tokens: `curl https://ci.example.com/go/api/access_tokens?revoked=true`

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8634-eea0ba2e4dff49c50e6f01e3804b1b9ef4b96444)
