### ISSUE TITLE
Change authorization extension contract for get-user-roles

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5846]
##### Issue Type

- Bug Report

##### Summary

Currently, for fetching roles for a user, GoCD server makes `get-user-roles` call to the authorization plugins implementing authorization extension v2.

Plugins can fetch roles for a user against a single auth config, hence only single auth config should be sent to the plugin instead of sending a list as part of this request.

##### Current Plugin API call:
```
public AuthenticationResponse getUserRoles(String pluginId, String username, List<SecurityAuthConfig> authConfigs, List<PluginRoleConfig> roleConfigs);
```
##### Proposed Plugin API call:
```
public AuthenticationResponse getUserRoles(String pluginId, String username, SecurityAuthConfig authConfig, List<PluginRoleConfig> roleConfigs);
```

**Comment by GaneshSPatil** [comment]
### Need to explicitly fix following plugins as they are using old extension contract:
- [ ] ldap authorization
- [ ] filebased plugins

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8610-4713200bc880ce17014d826e20a30ed032e3ac26)

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8610-4713200bc880ce17014d826e20a30ed032e3ac26)
