### ISSUE TITLE
Command "ndk-build" can't be executed on Go agent

### ISSUE THREAD

**Issue by holphi** [gocd/gocd#585]
Tried run ndk-build on correct working dir, I will receive below errors:

If go to the working dir and run the command manually, it will be executed successfully

[go] setting environment variable 'GO_P4_CLIENT_SQLI_CI_DEV' to value 'cruise-SQLI-LAPTOP1-sqli_CI_Dev-LPmScBvM3RSvfCqBRtWy5PzLKFw'
Android NDK: WARNING:D:/Go/GoAgent/pipelines/MyTrialPipeline/sqli_CI_Dev/dope/build/android//jni/Android.mk:dope: non-system libraries in linker flags: ../../../../udc_lib/lib/android/32/ddp_udc_lib_armv7int_neon_release.a ../../../../ac4_dec_lib/lib/android/32/ac4declib_armv7int_release.a ../../../../ac4_dec_lib/lib/android/32/ac4dec_extcomps_armv7int_release.a    
Android NDK:     This is likely to result in incorrect builds. Try using LOCAL_STATIC_LIBRARIES    
Android NDK:     or LOCAL_SHARED_LIBRARIES instead to list the library dependencies of the    
Android NDK:     current module    
[armeabi-v7a] Compile++ thumb: dope <= Player.cxx

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
make.exe: *** [D:/Go/GoAgent/pipelines/MyTrialPipeline/sqli_CI_Dev/dope/build/android//obj/local/armeabi-v7a/objs/dope/__/__/__/__/dope/src/player/Player.o] Error 255

[go] Start to create properties MyTrialPipeline/22/CompileAndBuild/1/defaultJob on SQLI-LAPTOP1 [D:\Go\GoAgent] at Thu Sep 25 13:31:25 CST 2014

[go] Start to upload MyTrialPipeline/22/CompileAndBuild/1/defaultJob on SQLI-LAPTOP1 [D:\Go\GoAgent] at Thu Sep 25 13:31:25 CST 2014

[go] Job completed MyTrialPipeline/22/CompileAndBuild/1/defaultJob on SQLI-LAPTOP1 [D:\Go\GoAgent] at Thu Sep 25 13:31:25 CST 2014

**Comment by arvindsv** [comment]
Closing. Does not seem like a GoCD issue.
