### ISSUE TITLE
MacOS 

### ISSUE THREAD

**Issue by vasilecristian** [gocd/gocd#5857]
##### Issue Type

- Bug Report

##### Summary
Go Agent will generate an error that says:
`go-agent[40603:352741] Requested but did not find extension point with identifier Xcode.IBBuildSupport.AssetCatalog.AssetTagScanner.TypeExtension
go-agent: error: Initialization failed.
Reason: Required content for platform watchOS is missing.`

every time when command xcodebuild is called. 
Example of command `xcodebuild -target Game -sdk iphoneos -configuration Debug -arch armv7 -scheme Game`

###### Basic environment details

* Go Version: 19.1.0
* JAVA Version: 11.0.2
* OS: macOS Mojave Version 10.14.2 & XCode 10.1 .
* Browser vendor and version (if relevant): Chrome

##### Steps to Reproduce

The problem is generated by the environment variable CFProcessPath .

In file JavaApplicationStub64 there is
`# enable drag&drop to the dock icon`
`export CFProcessPath="$0"`

##### Possible Fix
The workaround that i found is to execute the command `unset CFProcessPath` before the xcodebuild .

**Comment by arvindsv** [comment]
@ketan For GoCD agent, we definitely don't need the capability to drag and drop. We should be able to remove it, if that's the only reason for it. Thoughts?

**Comment by ketan** [comment]
Looking at https://github.com/tofi86/universalJavaApplicationStub/issues/10, it seems that the solution (to `unset`) is workable. I'll give this a shot.
