### ISSUE TITLE
Access token api Bugs

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#5859]
##### Current
POST `http://localhost:8153/go/api/access_tokens/id/revoke` returns 401(`Unauthorised`) if a token is already been revoked. 

##### Expected
It should return 409(`Confilct`).

---

##### Current
POST `http://localhost:8153/go/api/access_tokens` returns 422 with errors but also contains access token in response.

```json
{
  "_links" : {
    "self" : {
      "href" : "http://localhost:8153/go/api/access_tokens/-1"
    },
    "doc" : {
      "href" : "https://api.gocd.org/19.2.0/#access-token"
    },
    "find" : {
      "href" : "http://localhost:8153/go/api/access_tokens/:id"
    }
  },
  "id" : -1,
  "description" : "",
  "auth_config_id" : "9cad79b0-4d9e-4a62-829c-eb4d9488062f",
  "_meta" : {
    "is_revoked" : false,
    "revoked_at" : null,
    "created_at" : "2019-02-15T07:30:42Z",
    "last_used_at" : null
  },
  "token" : "aec1d071a9a1298c0280205b6de691249ece0320",
  "errors" : {
    "description" : [ "must not be blank" ]
  }
}
```

##### Expected
The response must not have access token in case of API errors.

### 3. list access token
It should include the revoke cause for the access token if the token has been revoked.

**Comment by maheshp** [comment]
Check with @ketan before picking this up.

**Comment by bdpiparva** [comment]
- Allow to get `cctray.xml` through access token

**Comment by bdpiparva** [comment]
-  Should not allow access token APIs using an access token (@kritika-singh3 is looking at the issue)

**Comment by bdpiparva** [comment]
Closing the issue as all the listed issues are addressed.
