### ISSUE TITLE
Placeholder for all access token API and SPA related issues

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#5871]
##### Issue Type

- Bug Report

##### Summary

All issues related to Access Token API and SPA will be captured here, summary of the issue to be provided n below section, any details like screen shots and scenario descriptions can be provided in comments and linked to the summary here,

Below issues are observed on,

GoCD server version : 19.2.0 (8545-1b3e3bff714d2a98a545898edcdd41e11289f0f3)
File based plugin version: 1.0.3-60
Github oAuth plugin: 3.0.0-42

- [x] Access token with same description can be created multiple times - should it be allowed? - Update: Not doing check for description uniqueness as per below discussion
- [x] Group admin and template admins do not have access to Access token SPA page. Clicking on `Personal Access Tokens` link returns 403 Forbidden error
- [x] After [this](https://github.com/gocd/gocd/pull/5865) PR there are 2 API namespaces for access token `current_user` and `admin`. While the `admin` namespace makes sense, the `current_user` seems redundant. So when user need to get/create an access token the request has to be on `api/current_user/access_tokens` with basic auth credentials provided. Discussed this with @bdpiparva and @ketan and its decided to for all users can get/create their user specific tokens on `api/access_tokens` and admins will use `api/admin/access_tokens` with necessary filters to get/revoke tokens - Update: Continuing to use 2 namespaces

**Comment by maheshp** [comment]
>  * Access token with same description can be created multiple times - should it be allowed?

@rajiesh I don't think description should be unique.

**Comment by bdpiparva** [comment]
> * Group admin and template admins do not have access to Access token SPA page. Clicking on `Personal Access Tokens` link returns 403 Forbidden error

Fixed in https://github.com/gocd/gocd/pull/5872

**Comment by rajiesh** [comment]
> @rajiesh I don't think description should be unique.

@maheshp @arvindsv IMO access token description has to be unique given that user cannot see the actual token value. However if all feel its not necessary to include a validation for that we can leave it as it is.

**Comment by arvindsv** [comment]
@rajiesh I understand that it feels weird, because the token cannot be seen. Would it be possible to show a timestamp of when it was created?

That could help to differentiate between the tokens. When we allow a user to modify the description, forcing it to be unique seems confusing to me. Almost as if we're treating it as an ID.

**Comment by bdpiparva** [comment]
@arvindsv - We do show the creation time of token. The way I look at the description is to way to define what is that token for and what it will be that is up to the user. 

<img width="1384" alt="screen shot 2019-02-21 at 10 14 28 am" src="https://user-images.githubusercontent.com/7871209/53144251-881be300-35c1-11e9-8668-a5166d0aa012.png">


We already have help text `What is this token for?` under the description.

<img width="754" alt="screen shot 2019-02-21 at 10 13 04 am" src="https://user-images.githubusercontent.com/7871209/53144253-8c480080-35c1-11e9-8913-5246706738ba.png">

**Comment by rajiesh** [comment]
Verified on 19.2.0 (8639-9ba73d561b80d9d4e20dbf903aaeb3d29fcd3ab4)
