### ISSUE TITLE
Maintenance Mode Banner should show maintenance mode updated-by and updated-on timestamp

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5874]
##### Issue Type

- Feature enhancement

##### Summary

Currently, maintenance mode updated-by and updated-on information are only shown on the maintenance mode SPA which is accessible only by the system admins. for a normal user, this information isn't available.
If the GoCD server is in maintenance mode, it shows a banner at the bottom saying "GoCD Server is in Maintenance Mode".
Add additional information, such as `maintenance mode updated by and updated on` to this banner.

**Comment by rajiesh** [comment]
Verified on 19.6.0 (9438-bec8bc92121ef301fc489aa3badc5fe4e9b686fd)
