### ISSUE TITLE
One click trial download zip

### ISSUE THREAD

**Issue by kierarad** [gocd/gocd#5912]
##### Issue Type

- Feature enhancement

##### Summary

In an effort to make it easier for someone to try out GoCD (at an experimental level), the current agent and server downloads will be replaced with one zip (for each OS). 

It could contain: 
 - OS-specific-JRE  
 - GoCD server zip 
 -  GoCD agent zip  
 - db/ 
 - config/ 
 - a small launcher which will work on that OS and bring up the server, agent

This installation would not be intended for production users, but to make the 'trial' experience easier by alleviating some of the current install pain points.

**Comment by arvindsv** [comment]
https://github.com/gocd-contrib/gocd-trial-launcher
