### ISSUE TITLE
Ease the create & run first pipeline experience

### ISSUE THREAD

**Issue by kierarad** [gocd/gocd#5913]
##### Issue Type

- Feature proposal 

##### Summary

We would like to make creating and running a pipeline more accessible for first time users in an effort to get them closer to understanding the value of GoCD. 

Ideas Brainstormed:
- revisit tab layout of quick add
- better progress indicator 
- change tab names
- remove hover state for non-clickable items (tabs)
- add hover state to clickable items (next button)
- scroll to top after click 'next'
- better/more help (tool tips? links?) #5926 
-- add info for pipeline as a material (improve linking of pipelines together)
-- fix tooltip behavior
- add placeholders in fields
- fields size dependent on expected length (e.g. larger field for urls)
- group and order fields in a more meaningful way #5925 
-- visual organization of stage -> job -> task to map to concepts and relation to each other
-- hide/collapse/remove non required fields (add advanced section)
-- remove trigger type in stage (since there is no proceeding stage)
-- move 'check connection' near url
-- make stage/job distinct (currently ambiguous if synonymous)
- make 'required' more prominent/obvious than * footnote (perhaps explicit text)
- option to add more jobs or tasks
- visual indicator as to what part you're configuring (diagram? picture?)
- change task type 'more' to 'custom command'
- add 'job is a set of steps called tasks'
- add option 'save and run/build' which goes to dashboard or vsm #5927 
-- replace finish with 'save and edit' (goes to edit config)
- more informative text for paused pipeline (on dashboard)
- more accessible add pipeline (on dashboard) -  issue #5715  PR #5885 
- add indicator you are on dashboard
- better indicator pipeline is running (static yellow stage isn't clear)
- fix race condition with agent updating config xml while user is in process of adding new pipeline

Alternatively (or additionally) we could a walk-through to help guide users

**Comment by arvindsv** [comment]
Makes sense. I guess it needs to be prioritized and then we need to pick a few to start with.

Also, we should look at what kind of broader, bigger changes we can make to improve the user experience. @naveenbhaskar might be interested in this as well.

**Comment by kierarad** [comment]
@arvindsv got it. I think we were trying to "scope" the ideas, but maybe we were thinking to narrowly. 

As far as picking a few to start with, we were leaning towards- 
> 
>* group and order fields in a more meaningful way
>* visual organization of stage -> job -> task to map to concepts and relation to each other
>* hide/collapse/remove non required fields (add advanced section)
>
Which we feel are similar enough that we could bunch them together. 
> 
>* add option 'save and run/build' which goes to dashboard or vsm 
> * replace finish with 'save and edit' (goes to edit config)
>
Obviously the new button's behavior would not pause the pipeline and would trigger it to run. 
>
>* better/more help (tool tips? links?)
>* add info for pipeline as a material (improve linking of pipelines together)
>* fix tooltip behavior
>
Again we grouped these.

**Comment by arvindsv** [comment]
> I think we were trying to "scope" the ideas, but maybe we were thinking to narrowly.

@kierarad That makes sense for this - to start with. We can start with some low-hanging fruit, but if it looks like we need to make some medium-sized or bigger changes, we can look at the whole experience to understand whether it is the right longer term change to make.

The rest makes sense to me. If you are going to prototype (on paper or something) how these will look, please share those. If not, that's ok.

**Comment by rajiesh** [comment]
Closing the issue as most of the points discussed here are implemented. Any new work on the first pipeline creation and run experience will be captured on a new issue
