### ISSUE TITLE
The UI for view template with task plugins does not show up correctly

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#592]
View template looks broken -

a) When the magnifying glass on the left panel is clicked

![view_templates_is_broken](https://cloud.githubusercontent.com/assets/6175869/4301592/f5ee6a82-3e50-11e4-8d81-cadfb955d3da.png)

b) Navigate to Admin > Pipelines > (Pipeline name) > Stages > View (template) is clicked

![view-template-from-stages-tab](https://cloud.githubusercontent.com/assets/6175869/4331220/f2a0b120-3fc0-11e4-9b15-7905479fd0be.png)

**Comment by arvindsv** [comment]
Closing as stale.
