### ISSUE TITLE
Add option to add + run pipeline

### ISSUE THREAD

**Issue by kierarad** [gocd/gocd#5927]
##### Issue Type
- Feature enhancement
##### Summary

Currently when you "Finish" adding a pipeline you are taken to the pipeline edit to further configure the pipeline and the pipeline is paused. 

We would like to add an option that when selected would save the pipeline and immediately trigger it. Instead of directing you to the edit configuration it would direct you to somewhere that would more easily show you that the pipeline was created and running. We are tentatively thinking the dashboard which should accomplish this for the trial experience with a relatively "clean" instance. We are weighing this against the experience for existing users realizing that the pipeline they create may not be visible on the dashboard (depending on if they've personalized the view).

**Comment by arvindsv** [comment]
There is a "Save + Run pipeline" button now. Closing. cc: @marques-work @loudaTW
