### ISSUE TITLE
allow ENV variables in fetch artifact task

### ISSUE THREAD

**Issue by jeremymv2** [gocd/gocd#593]
Fetch Artifact  Passed  Pipeline Name: FetchChefGoArtifacts Stage Name: defaultStage Job Name: defaultJob Source File: chefgo-artifacts/chef-go/scheduled/${go.CHEF_GO_ARTIFACT}

It would be really nice and useful if GO allowed you to either define environment variables in the source of the fetch artifact task.  Currently only parameters are supported.  If an organization has hundreds of pipelines, updating the values of each one of the pipeline's paramter isn't feasible.  Whereas, if either the parameter or the task itself could directly use a global environment variable, it would be just one place to update and would result in an update to all pipelines.

**Comment by gkid** [comment]
+1 Would also like to be able to define global environment vars, both plaintext and encrypted, which are accessible in all pipelines. 
One example: things like api keys which are commonly used in many of our pipelines. It would be great to be able to define or update them in just one place (and not once in each Environment).

**Comment by vspiewak** [comment]
+1

**Comment by moritzheiber** [comment]
Isn't this what GoCD environments are for? You can define variables for "Environments" pipelines can be associated with: https://docs.go.cd/current/configuration/managing_environments.html

**Comment by vaibhavparnalia** [comment]
+1

**Comment by hamza-tumturk** [comment]
+1
Is there any update on this issue?

**Comment by gmywq392** [comment]
+1
