### ISSUE TITLE
Support for cluster config entity in GoCD

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5938]
##### Issue Type

- Feature proposal

##### Summary

Allow users defining new cluster configurations.

- [x] Add an XSLT migration to support cluster config entity in cruise-config.xml.
- [x] Allow users to perform CRUD operations on cluster config entity.

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)
