### ISSUE TITLE
/etc/init.d/go-agent script should give appropriate message when a user stop/status when no PID file exists

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#5945]
##### Issue Type
- Bug Report

##### Summary
The functionality of the script is not compromised. However if a user

1. Tries to stop a newly installed agent which has never been started and a PID file does not exist then they will see an error

2. Tries to know the status of a newly installed agent which has never been started and a PID file does not exist then they will see an error

This is because the check_proc function has ps -p "$(cat "/var/run/go-agent/${SERVICE_NAME}.pid")" which when the PID file does not exist errors out.

**Comment by rajiesh** [comment]
@adityasood Think this issue is fixed by this commit - https://github.com/gocd/gocd/commit/7f78b1155d31ab268444a7effe89bb301933656a#diff-48385395d62c8d5e49e9612b048e274d - Can you quickly verify?

**Comment by adityasood** [comment]
@rajiesh the fix you pointed to suppresses the message only in startup, however there can be edge cases on stop and status as well.

**Comment by adityasood** [comment]
With the release v19.6.0, all installers now use the tanuki wrapper to manage the GoCD server and agent process and OS services. 

The wrapper scripts provide appropriate information on the above-mentioned cases. The service manager on the OS used for the installation of go-{server,agent} also give appropriate information in this regard.

Verified with: 19.6.0-9515
