### ISSUE TITLE
Features enhancements for Config Repo SPA (Remaining improvements)

### ISSUE THREAD

**Issue by vishaldevgire** [gocd/gocd#5947]
##### Issue Type

- Feature enhancement

##### Summary

Feature enhancement for Config Repo SPA

1. Last checked: show a label describing last time a config repo was scanned for updates.

![image](https://user-images.githubusercontent.com/24635164/53867890-c3370100-401a-11e9-99f5-2053780a520b.png)

2. Meaningful tooltips for Latest commit ... and Last known good commit.... to describe what they mean

**Comment by adityasood** [comment]
Epic #5175
