### ISSUE TITLE
'more' link is not aligned for 'REVOKED MESSAGE' column. 

### ISSUE THREAD

**Issue by rahulpargaonkar** [gocd/gocd#5949]
##### Issue Type

- Bug Report

##### Summary

'more' link is not aligned for 'REVOKED MESSAGE' column. 

##### Environment

- GoCD Version: 19.2.0 (8641-db17f5840f9d1c6838add93af050b812bbdf5c68).

##### Steps to Reproduce

1. Login into application
2. go to active token tab on Access token management page
3. Revoke token with very large string as message
4. go to Revoked tab and look into 'REVOKED MESSAGE'  column for the same token
5. also after clicking on more link, the revoked message it not properly aligned

##### Expected Results
'more' link and revoked message should be properly aligned

##### Actual Results

please refer step 4 & 5 in the steps to reproduce

<img width="1425" alt="screen shot 2019-03-06 at 4 26 45 pm" src="https://user-images.githubusercontent.com/33080845/53876414-ba4f2b00-402c-11e9-8564-b0c7bad7c747.png">
<img width="1430" alt="screen shot 2019-03-06 at 4 26 33 pm" src="https://user-images.githubusercontent.com/33080845/53876415-bae7c180-402c-11e9-9e46-ba0a6e6e6ded.png">

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8949-6e5f96a9d1b37e9b8e2037a606114ae3ca58bf67)
