### ISSUE TITLE
Misleading Elastic Agent Profile API documentation

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#5959]
##### Issue Type

- Bug Report

##### Summary

Elastic Agent Profiles API requires Id to be sent as part of request-body, but the documentation says it is not required.

Similar documentation bug holds true for Authorization Configuration API.

--

Either the documentation needs to be fixed to say "id" is a mandatory field in the Update API request body. Or the relevant code needs to be changed to make "id" an optional field.

\cc: @bdpiparva

**Comment by bdpiparva** [comment]
@GaneshSPatil - I think documentation LGTM. See https://api.gocd.org/19.2.0/#create-an-elastic-agent-profile.

**Comment by GaneshSPatil** [comment]
@bdpiparva -- I was referring to https://api.gocd.org/19.2.0/#update-an-elastic-agent-profile and https://api.gocd.org/19.2.0/#update-an-authorization-configuration

Where an update call does not expect "id" to be passed along for the **_Update_** API call. But the actual API call requires it.

**Comment by bdpiparva** [comment]
Yes, the document is right, in update call `id` is passed in URL so it is not required as part of the payload. If that is the case then we have to change it.

**Comment by bdpiparva** [comment]
https://github.com/gocd/gocd/blob/master/api/api-elastic-profile-v1/src/main/java/com/thoughtworks/go/apiv1/elasticprofile/representers/ElasticProfileRepresenter.java#L50 should be `optString`

**Comment by GaneshSPatil** [comment]
Not sure if that can be changed.
As in the controller, we check for [`isRenameAttempt`](https://github.com/gocd/gocd/blob/master/api/api-elastic-profile-v1/src/main/java/com/thoughtworks/go/apiv1/elasticprofile/ElasticProfileControllerV1.java#L119-L120).

Making "id" an optional field will result in API to respond `rename attempted` for all the update requests.

---

Either we can document that specifying "id" in request body will not be considered for updates. Or we can be smart and check for rename attempts, only when the id is specified.

**Comment by bdpiparva** [comment]
I don't think so [isRenameAttmpt](https://github.com/gocd/gocd/blob/master/api/api-elastic-profile-v1/src/main/java/com/thoughtworks/go/apiv1/elasticprofile/ElasticProfileControllerV1.java#L119-L120) check is needed at all. Profile Id is there in the request -

- If a profile with specified Id exists in sever then update
- If not then record not found
