### ISSUE TITLE
GoCD shows HTTP Basic Auth dialog when user gets logged out

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#5962]
##### Issue Type
- Bug Report

##### Summary
On build.gocd.org, I've been getting a authentication popup when I get logged out. See screenshot.

On Firefox, the popup doesn't go away. But on Chrome, the popup flashes and goes away when redirected to the login page.

This has happened from the Dashboard page, as well as the old pages like Stage Run Details

Browser: Firefox 65.0.1

##### Code snippets/Screenshots
<img width="1436" alt="screenshot 2019-03-08 at 16 10 34" src="https://user-images.githubusercontent.com/6024038/54024402-b868a180-41bd-11e9-97dc-0b9e872768e9.png">

**Comment by ketan** [comment]
Fixed via #5981. Closing as I've not seen this issue since quite some time now.
