### ISSUE TITLE
Notifications don't work? e.map is not a function

### ISSUE THREAD

**Issue by dzek69** [gocd/gocd#5968]
##### Issue Type

- Bug Report

##### Summary

Console throws an error on each page refresh. This probably blocks some UI interactivity (like websockets for live console logs, not sure about that as I'm new to GoCD)?

##### Environment

Docker images ver. 19.2.0
Docker host runs on Debian 9.

###### Basic environment details

* Go Version: `19.2.0 (8641-db17f5840f9d1c6838add93af050b812bbdf5c68)`
* JAVA Version: `1.8.0_191`
* OS: `Linux 4.9.0-8-amd64`
* Browser vendor and version (if relevant): `Chrome 72.0.3626.121`

###### Additional Environment Details

Nope.

##### Steps to Reproduce, Expected Results, Actual Results & Possible Fix

As I'm not sure what expected result should be I'd just describe all I know.

I'm getting is console error on each page refresh. JavaScript code expects an array in one place but gets a string instead. This is why `.map` is crashing.
Error is here:
```
system_notifications.ts:75 Uncaught (in promise) TypeError: e.map is not a function
    at new e (system_notifications.ts:75)
    at Function.e.fromJSON (system_notifications.ts:86)
    at system_notifications.ts:81
    at new Promise (<anonymous>)
    at Function.e.all (system_notifications.ts:79)
    at Object.repeaterFn (index.tsx:27)
    at t.fire (ajax_poller.ts:95)
```

And from what I've debugged - instead of array I'm getting string with JSON encoded array:
![image](https://user-images.githubusercontent.com/4936805/54128779-1808bc00-440d-11e9-998c-83ed117bcbd5.png)

But not always. I also received one notification just right. This one seems broken.

This notification seems to be a "welcome, here's some info" kind of notification so it probably only happens on fresh install.

```json
[{"id": "5546a717-8b06-4a4e-bd7c-6708fbdd185e", "message": "GoCD shares data so that it can be improved.", "read": false, "type": "DataSharing_v18.8.0", "link": "/go/admin/data_sharing/settings", "linkText": "Learn more ..."}]
```

**Comment by arvindsv** [comment]
There's some information about this in: #5970. @GaneshSPatil is this issue going to be solved in that PR?

**Comment by arvindsv** [comment]
Also: @dzek69 Thanks for taking the time to submit an issue and dig into it!

**Comment by GaneshSPatil** [comment]
@arvindsv -- Yes, as part of PR: https://github.com/gocd/gocd/pull/5970, we've fixed this issue.

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)
