### ISSUE TITLE
Feature request: Restore from backup - Import backup

### ISSUE THREAD

**Issue by okproject** [gocd/gocd#5971]
##### Issue Type

- Feature proposal

##### Summary

Install from backup is really problematic. So install from backup or import - load backup feature sounds nice

##### Environment

18.9.0 - ubuntu 16.04LTS

##### Steps to Reproduce

1. Create a backup
2. Install GOC to another server
3. Try import backup or restore from backup
4. You can see it is really complicated process.
5. If you fail, you lose your history.

##### Expected Results
After restore from backup - import backup feature implemented, production environments will be happy with their history.

##### Actual Results
Too many problems during loading from backup.

##### Possible Fix
Creating import backup or install from backup feature should fix the problem

**Comment by arvindsv** [comment]
@okproject What problems do you face with backups?
