### ISSUE TITLE
Row elements expansion in GUI doesn't handle environment names containing special characters

### ISSUE THREAD

**Issue by agerro** [gocd/gocd#5973]
##### Issue Type
- Bug Report

##### Summary

Expansion of rows in environment (perhaps even more elements) view not working due to jQuery not being able to handle environment names with "." in them due to http://api.jquery.com/category/selectors/

This is probably since GoCD moved in to using expandable elements in the GUI.

##### Environment

```Found in: 19.1.0

```
-->

###### Basic environment details

* Go Version: `19.1.0 (8469-3885582184c6f7c4bbbeb94239e5dba6f5f772f4)`

##### Steps to Reproduce

1. Create an environment named "foo.bar"
2. Create an environment named "foo-bar"
3. Go to Admin -> Environment
4. Try to expand environment ""foo-bar" and verify it is working 
5. Try to expand environment "foo.bar" and verify it is not working

##### Expected Results
Environments with "." (dots) in the names should be able to be expandable

##### Actual Results
Row elements in GUI should be able handle environments consisting of "." (dots)

##### Possible Fix
The expansion script should handle excaping of characters in the following set if some elements contains them: [ !"#$%&'()*+,./:;<=>?@[\]^`{|}~]

**Comment by GaneshSPatil** [comment]
@agerro -- Thanks for reporting the bug. Someone from the team will take a look at it.

This issue is reproducing on latest master: `GoCD Version: 19.3.0 (8671-b201bad65babb392daf3d81d3fdcad222b12f8a4)` as well.

**Comment by GaneshSPatil** [comment]
#### Issue
An onclick handler for each environment row was added using jquery selector ([code block](https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails/app/views/environments/_show_env.html.erb#L77-L78)).

For an environment with name "foo.bar", The selector would be `#foo.bar`. In such scenario, Jquery would assume the selector to be any html element having `foo` as id and `bar` and class.

#### Possible Fix 1:
Escape all the special character from the selector.
Eg: Change the selector `#foo.bar` to `#foo\\.bar`

#### Possible Fix 2:
Use element attribute selectors
Eg: Change the selector `#foo.bar` to `div[id="foo.bar"]`

**Comment by agerro** [comment]
@GaneshSPatil Is this a problem on more places than the environment page?
Does more "expandble" row exists?
We would like to have it fixed for our coming release, so it would be nice not to have it found in more palces afterwards :)

**Comment by GaneshSPatil** [comment]
@agerro -- The row expansion problem was specific to jQuery selector. 
The environments page is the only page which uses jQuery to do dom manipulation, whereas most of our other pages which have expand/collapsible panels are written using [mithril](https://mithril.js.org) framework.
We don't expect this problem to exist on any other pages.

**Comment by childsc** [comment]
We have the same issue. Our current workaround is to access the environment with the following
https://ci.example.com/go/admin/environments/this.is.my.environment/show otherwiser we are forced to re-create. I would not mind if we can not use "." but it would be nice if there was validation so it does not accidentally happen.

**Comment by arvindsv** [comment]
@childsc https://github.com/gocd/gocd/pull/5974 should take care of it, in 19.3.

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)

**Comment by rajiesh** [comment]
@agerro Thanks for pointing out this issue, the environment Edit is also fixed now in 19.4.0 release
