### ISSUE TITLE
Show status agent "Not yet assigned (Unknown)" on dashboard

### ISSUE THREAD

**Issue by greuelpirat** [gocd/gocd#5976]
##### Issue Type

- Feature proposal

##### Summary

On dashboard there is no way to see what pipelines are actually building. Because pipelines that are not assigned to an agent are shown as "Building"

###### Basic environment details

Go Server Version: | 19.2.0 (8641-db17f5840f9d1c6838add93af050b812bbdf5c68)
-- | --
JVM version: | 11.0.2
OS Information: | Windows Server 2016 10.0
Usable space in artifacts repository: | 941 GB
Database schema version: | 1902008
Pipelines Count: | 14

##### Steps to Reproduce

1.  Trigger multiple Pipelines that have to wait for an agent

##### Expected Results

"Building"-Pipelines that are not assigned to an agent are shown as "Waiting" or something like that

##### Actual Results

"Building"-Pipelines that are not assigned to an agent are shown as "Building" (which is in fact wrong)

**Comment by arvindsv** [comment]
@greuelpirat I agree with the premise. One of the challenges here is that what is shown in the dashboard is a pipeline (and stage). The stage can have multiple jobs, some of which are building and some which are not yet assigned (waiting for an agent).

/cc @naveenbhaskar is the right person for this conversation.

**Comment by greuelpirat** [comment]
@arvindsv Thats true. We currently have only stages with single jobs. But I think, there must be already some logic for that. If a stage has multiple jobs, then when is it shown as failed? as soon as one has failed or is it showing "building" until all jobs finished building and then shows failed if one failed?

**Comment by arvindsv** [comment]
@greuelpirat There is a state called "Failing" which shows a red building bar in that case. These are [all the states](https://github.com/gocd/gocd/blob/2491750010a52bedee628a6a2116d52e0d33e370/domain/src/main/java/com/thoughtworks/go/domain/StageState.java#L22) available at a stage level. There's no "Waiting for agent" equivalent. So, we'd need to go down to the jobs and find that state and bubble it up to the dashboard API.

The [dashboard activity listener](https://github.com/gocd/gocd/blob/2491750010a52bedee628a6a2116d52e0d33e370/server/src/main/java/com/thoughtworks/go/server/dashboard/GoDashboardActivityListener.java#L89) will also need to listen to job activity and update itself. It's doable but some work.
