### ISSUE TITLE
for reporting, configure agent network interface or IP address

### ISSUE THREAD

**Issue by greenmoss** [gocd/gocd#599]
I am running Docker on my GoCD agents, which makes them report their Docker IP address as the agent address to the GoCD server. However I want my agents to instead show their routable IP address on the server agent list.

Please update the [agent self-reporting code](https://github.com/gocd/gocd/blob/master/base/src/com/thoughtworks/go/util/SystemUtil.java#L69) to allow admins to configure either a network interface or an IP address. This could be done alongside other daemon settings such as GO_SERVER, etc.

**Comment by nicolaasuni** [comment]
I am experiencing the same issue.

In my case the [getFirstLocalNonLoopbackIpAddress()](https://github.com/gocd/gocd/blob/master/base/src/com/thoughtworks/go/util/SystemUtil.java#L69) method is returning the IP address of the *docker0* interface, that is the same for all agents and is not the external routable IP address of the go-agent.

An host could have multiple network interfaces, and an interface could be bound to more than one IP address. Additionally you may have a load balancer or router between the go-agent and go-server.

This means that the strategy to obtain the go-agent IP address from the list of its network interfaces works only in specific conditions and fails in multiple scenarios.

My advice is to add a parameter in the go-agent configuration file to explicitly define the go-agent IP address to be used by the go-server. Something like:

GO_AGENT_IP=123.123.123.123

Some fallback mechanism can be put in place in case this parameter is not defined. For example trying to get the IP from the hostname if this is set in the DNS server (i.e. hostname --ip-address).

**Comment by greenmoss** [comment]
Another strategy I have seen for determining the "primary" IP address is to use the IP address associated with the default route. Just an idea.

**Comment by steven-collins-omega** [comment]
Me too. If I could vote this up I would.

The funny thing, I think, is that the agent IP address is reported correctly _until_ the admin actually enables that agent. Would it not be OK to interpret the admin enabling the agent as also confirming that the IP address is as expected, and therefore correct?

**Comment by nicolaasuni** [comment]
As a collateral bug of this one, I noticed that sometimes the go-server raise the following exception that seems due to the change of IP between registering and enabling phase:
com.thoughtworks.go.server.service.AgentWithDuplicateUUIDException

**Comment by nicolaasuni** [comment]
Why this issue has not been marked as a bug?

**Comment by mattcl** [comment]
I am also hitting this issue using a multi-machine Vagrant setup (Vagrant sets the same eth0 NAT address for all nodes, which might be an issue in itself). The network adapter/ip address should be a configurable option.

**Comment by lcacciagioni** [comment]
Any way to fix this guys?

**Comment by darioblanco** [comment]
Would be nice and very appreciated to have a fix.

When running my local saltstack set up that provisions gocd, the agent connects using eth1 (eth0 is used in vagrant for NAT), I noticed that after my gocd server restarted, the agent switched to eth0!!! This made my configuration a nightmare, as I am using salt mine to handle ips from the agents and automatically subscribe them to the XML config.

Is there a way to force the gocd agent to use always a specific interface?

**Comment by arvindsv** [comment]
@darioblanco: I've asked about this issue over in #2390, since there is some work in a similar area.

**Comment by darioblanco** [comment]
Thanks @arvindsv !

**Comment by aj-jaswanth** [comment]
Would this fix the problem? 
https://github.com/gocd/gocd/pull/2390
https://github.com/gocd/gocd/commit/b283b426c678c94f83d1688e232a90c896fbd8e0

**Comment by maheshp** [comment]
Fixed as part of https://github.com/gocd/gocd/issues/1657
