### ISSUE TITLE
[Config Repo SPA] In case of an error on merging a new commit on Config Repo, last known good commit is not shown

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#6003]
##### Issue Type
- Bug Report

##### Summary

If we have an invalid merge due to a commit to the config repository, we only show the bad commit. The last know good commit is not shown, while we continue to show config from the last known good commit. Please see the attached gif.
![config-repo-spa-issue](https://user-images.githubusercontent.com/17826464/54664654-e083c900-4b0a-11e9-82ec-86f61db247bd.gif)

**Comment by GaneshSPatil** [comment]
@adityasood -- Recently, GoCD has changed the way `Latest Commit In the Repository` and `Last Known Good commit` information is shown.

GoCD now shows information only about the `latest commit in the repository`.
Last known good commit information has been removed and it can be inferred based on the Groups, pipelines, and environments defined by a config repository.
