### ISSUE TITLE
go-server can't install on redhat 32 bit system

### ISSUE THREAD

**Issue by elkan1788** [gocd/gocd#601]
Today when i download a release version go-server on my machine, the system environment is :
1. JDK version is 1.7.0_67;
2. RAM 2G
3. 2.4GHZ （4 Nuclear 8 thread）
4. System: Linux RedHatEnterprise4 2.6.9-55.ELsmp #1 SMP Fri Apr 20 17:03:35 EDT 2007 i686 i686 i386 GNU/Linux

then i run command: rpm -ivh go-server-14.2.0-377.noarch.rpm, that echo some information like this:

'Go Server' installation will now use group 'go'
'Go Server' installation will now use user 'go'
在 cruise-server 服务中读取信息时出错：没有那个文件或目录
chmod: 无法访问‘/etc/init.d/cruise-server’: 没有那个文件或目录
Found Java /usr/java/jdk1.7.0_67 in environment variable JAVA_HOME, using it.
chown: 无法访问‘/var/lib/go-server/**’: 没有那个文件或目录

go doesn't support Chiness??

**Comment by arvindsv** [comment]
No response. Closing.
