### ISSUE TITLE
User management - delete user confirmation

### ISSUE THREAD

**Issue by mbotmcc** [gocd/gocd#6013]
##### Issue Type

- Feature proposal

##### Summary

When deleting a user, it'd be good to have a popup with a confirm/cancel button on it and the name of the user. When a user or users are deleted a confirmation message should also include the usernames that were removed. Right now it just says "User was deleted...."

The top bar with enable/disable/delete is not visible when you scroll down the page it'd be good if it remained at the top when scrolling.

**Comment by naveenbhaskar** [comment]
@mbotmcc , Both these suggestions make sense. we will work on this soon.

**Comment by naveenbhaskar** [comment]
Hello @mbotmcc , 

we have worked on this and will be available soon. You can have a look at the demo image shown in this PR . https://github.com/gocd/gocd/pull/6036

**Comment by maheshp** [comment]
Done as part of #6036
