### ISSUE TITLE
Enhance Secrets Management Plugin Endpoint

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#6018]
Part of EPIC #5830

##### Issue Type
- Feature enhancement

##### Summary

As part of https://github.com/gocd/gocd/issues/5831 & PR https://github.com/gocd/gocd/pull/5881 the Secrets Management plugin endpoint to lookup for secrets was introduced.

As part of the secrets lookup request GoCD makes a request to the plugin with a secret configuration and list of keys to lookup. A bulk lookup is done to avoid a lookup for each key which might not be optimal. Upon a bulk lookup the plugin should not partially resolve the secrets, it should either resolve all the secrets or should return an error response. Change the lookup endpoint to the following,

### Message from GoCD 
```json
{
  "configuration": { 
    "FilePath": "/var/lib/secret.config"
  }, 
  "keys": [ 
    "username",
    "password" 
  ] 
}
```

#### Success Response
Response Code: **200**
```json
[
  {
    "key": "username",
    "value": "secret1"
  },
  {
    "key": "password",
    "value": "secret2"
  }
]
```

#### Error Response
Response Code: **404**
```json
{
   "message": "Unable to looup for secrets for 'username'"
}
```

**Comment by vishaldevgire** [comment]
Instead of reporting error for a single lookup key should the error return all non resolvable keys:

```json
{
   "message": "Unable to lookup for secrets",
   "keys": ["username", "deployKey"]
}
```

**Comment by maheshp** [comment]
> Instead of reporting error for a single lookup key should the error return all non resolvable keys:

The message should ideally have details of all the un-resolvable  keys, the example showed just one. Do you still see a reason to list `keys` separately.

**Comment by vishaldevgire** [comment]
> > Instead of reporting error for a single lookup key should the error return all non resolvable keys:
> 
> The message should ideally have details of all the un-resolvable keys, the example showed just one. Do you still see a reason to list `keys` separately.

IMO, Having unresolved_keys as a separate list will be much more convenient on server side. 

For example, on server for some reason if you want the list  of unresolved_keys, you will have to parse the message.
