### ISSUE TITLE
Auto scroll-down on console view

### ISSUE THREAD

**Issue by varac** [gocd/gocd#602]
When you have a long console output of a build that takes long, you need to manually scroll down in order to see latest output. It would be great to let the browser always display the latest messages.

**Comment by matthauck** [comment]
:+1:

**Comment by ketan** [comment]
This one is fairly simple to implement, and I have a working prototype. However, I'm not sure where this button can go.

**Comment by arvindsv** [comment]
I remember it used to be like this, before. If you were at the bottom of the page, it would keep scrolling to the bottom, and if not, it wouldn't. How about doing that, and not having a button? I haven't fully looked at 1138, yet. I see there's a button there.

**Comment by srinivasupadhya** [comment]
@ketan - is this done? can you move it in zenhub

**Comment by ketan** [comment]
@srinivasupadhya, @zabil - can you look into #1281 and merge it? I know we have a small merge window, but there are a couple of PRs that could use a push.

**Comment by arvindsv** [comment]
This is done. It's been like this for a year or so now.
