### ISSUE TITLE
Plugin docs mention beta plugin quick load, which is not part of the beta feature list

### ISSUE THREAD

**Issue by m-johansson** [gocd/gocd#6028]
##### Issue Type
Documentation Report
##### Summary
Docs for latest released (19.2)

According to the docs for plugins available here: https://docs.gocd.org/current/extension_points/plugin_user_guide.html

> You may also use this beta feature to quick load plugins without restarting GoCD server.

Where this is a link to https://docs.gocd.org/current/beta/plugin_upload.html which gives a 404.

Is this beta feature removed? If so the quote from plugin_user_guide should go as well, otherwise the 404 URL should be fixed.

**Comment by ankitsri11** [comment]
@m-johansson thank you for pointing it out. Currently, it is not supported. I've raised a PR https://github.com/gocd/docs.go.cd/pull/274 to update the docs.
