### ISSUE TITLE
better pipeline material errors

### ISSUE THREAD

**Issue by mbotmcc** [gocd/gocd#6031]
##### Issue Type

- Feature proposal

##### Summary

We have a few projects sharing the same repo. Recently I've tried adding a new pipeline material and get the following error.... 

>  _is specified more than once in the configuration with different values for the autoUpdate attribute. All copies of this material must have the same value for this attribute

._But there's no mention what pipeline has a different value for autoupdate. This means I now need to go through all the repos and check where it might be. It'd be good if the error included the pipeline which has the different autoupdate setting

**Comment by arvindsv** [comment]
Makes sense. No one is working on this area, @mbotmcc, as far as I know. We should pick this up when re-doing pipeline config.

For the record, this will need some changes around [MaterialConfigs.java#L267](https://github.com/gocd/gocd/blob/2be3951f5dc2b2ce07f5ddd34a314305834550ca/config/config-api/src/main/java/com/thoughtworks/go/config/materials/MaterialConfigs.java#L267) and then [ConfigSaveValidationContext.java#L254](https://github.com/gocd/gocd/blob/2be3951f5dc2b2ce07f5ddd34a314305834550ca/config/config-api/src/main/java/com/thoughtworks/go/config/ConfigSaveValidationContext.java#L254) and possibly [PipelineConfigSaveValidationContext.java#L230](https://github.com/gocd/gocd/blob/2be3951f5dc2b2ce07f5ddd34a314305834550ca/config/config-api/src/main/java/com/thoughtworks/go/config/PipelineConfigSaveValidationContext.java#L230).
