### ISSUE TITLE
Stage History API Returns Instances in Wrong Order Under Certain Conditions

### ISSUE THREAD

**Issue by jsmythsci** [gocd/gocd#6041]
##### Issue Type

- Bug Report

##### Summary

Under certain (as yet unknown) conditions, the Stage History API returns the _first_ 10 stage instances instead of the 10 most recent. Offset then works "as expected" by walking forwards through the history instead of backwards.

###### Basic environment details

* Go Version: `19.1.0 (8469-3885582184c6f7c4bbbeb94239e5dba6f5f772f4)`
* JAVA Version: `1.8.0_201`
* OS: `Linux 2.6.32-754.11.1.el6.x86_64`
* Browser vendor and version (if relevant): `N/A`

##### Steps to Reproduce

1. Set up a GoCD server instance where the bug manifests (circumstances as yet undetermined)
2. Call the Stage History API (`GET /go/api/stages/:pipeline_name/:stage_name/history`) for the affected stage

##### Expected Results
API should return the 10 most recent instances of the requested stage in reverse chronological order (most recent in the set first).

##### Actual Results
API returns the first 10 instances of the requested stage in reverse chronological order (most recent in the set first).

##### Log snippets
I'm not sure what logs I should be checking but I can add some later if we discover anything relevant.

##### Code snippets/Screenshots
This PowerShell code uses a custom PS module to call the API:
```powershell
$gshParams = @{
    PipelineName = 'ResponseDriver-Integration'
    StageName = 'Deploy'
}
$soParams = @{
    First = 5
    Property = 'id','pipeline_counter','counter'
}

'Offset: 0'
(Get-GoCDStageHistory @gshParams).stages | Select-Object @soParams
'Offset: 3'
(Get-GoCDStageHistory @gshParams -Offset 3).stages | Select-Object @soParams

```

The code above produces the following output:
```
Offset: 0

   id pipeline_counter counter
   -- ---------------- -------
51684               10 1      
51674                9 1      
51664                8 1      
51661                7 1      
51655                6 1      
Offset: 3
51716               13 1      
51704               12 1      
51689               11 1      
51684               10 1      
51674                9 1
```
This shows that the stage IDs increase when an offset is added, rather than decreasing. It also shows that this bug does not affect the order of the instances in the result set (they are still in decreasing order, as expected), it only affects the instances selected to be included.

That is to say, the nature of this bug is that the instances seem to be sorted in ascending order when selecting which to include in the result set and then the result set itself is resorted in descending order before being returned by the API.

##### Any other info

Our GoCD instance contains about 650 pipelines, most of which consist of multiple stages. I have only tested the Stage History API with a handful of stages and so far have only found 1 stage that is affected by this bug. Even the second stage of the same pipeline is unaffected.

We have a second instance (test) instance of GoCD that was cloned from our production instance and the affected stage exhibits the same behaviour in the cloned instance as well. So `/go/api/stages/myAffectedPipeline/stage1/history` is affected by the bug but `/go/api/stages/myAffectedPipeline/stage2/history` works normally.

In the UI (`/go/pipelines/myAffectedPipeline/{{counter}}/stage1/{{counter}}`) the Stage History panel on the right shows the expected content (most recent history).

**Comment by jsmythsci** [comment]
It looks like this bug may be related to the total number of instances for a given stage.

I wanted to know just how many pipelines/stages across my GoCD server instance were affected so I wrote a PowerShell script to loop through every (currently existing) stage in my configuration and test each one:

```powershell
$pipelineGroups = Get-GoCDPipelineGroups

$stageHistory = foreach ($pipelineGroup in $pipelineGroups) {
    $pipelines = $pipelineGroup.pipelines
    foreach ($pipeline in $pipelines) {
        $stages = $pipeline.stages
        foreach ($stage in $stages) {
            $gshParams = @{
                PipelineName = $pipeline.name
                StageName = $stage.name
            }
            $totalCount = (Get-GoCDStageHistory @gshParams).pagination.total
            $base = (Get-GoCDStageHistory @gshParams).stages | Select-Object -First 1 -Last 1
            $offset = (Get-GoCDStageHistory @gshParams -Offset 1).stages | Select-Object -First 1 -Last 1

            if ($totalCount -le 1) {
                $sortOrder = 'Undetermined'
            }
            elseif ($base[0].id -lt $offset[0].id) {
                $sortOrder = 'Ascending'
            }
            elseif ($base[0].id -gt $offset[0].id) {
                $sortOrder = 'Descending'
            }
            else {
                $sortOrder = 'Undetermined'
            }

            $gshParams.Add('SortOrder',$sortOrder)
            $gshParams.Add('TotalCount',$totalCount)

            New-Object -TypeName psobject -Property $gshParams
        }
    }
}
```

The above code dumps the full result into a variable (`$stageHistory`) which I was then able to manipulate in different ways to find out more about my instance.

The first thing I wanted to know was how many stages did not have the expected "Descending" sort order:

```powershell
$stageHistory |
    Where-Object { $_.SortOrder -ne 'Descending' } |
    Sort-Object -Property SortOrder,PipelineName,StageName
```

This showed me that we have 4 stages that are affected (sort order "Ascending") and a dozen or so undetermined because of having less than 2 stage instances in the history. This got me thinking about the number of instances in a stage's history so I tried sorting my unfiltered result set based on this:

```powershell
$stageHistory | 
    Sort-Object -Property TotalCount -Descending |
    Select-Object -first 10 -Property SortOrder,TotalCount
```

The code above produced the following result:
```
SortOrder  TotalCount
---------  ----------
Ascending       17252
Ascending       13354
Ascending       12325
Ascending       10842
Descending       7747
Descending       7619
Descending       6932
Descending       5250
Descending       4318
Descending       3819
```

This shows that the 4 affected stages are the also the 4 with the highest total number of instances.

This is certainly not conclusive but I thought it was interesting enough to be worth adding to the discussion.

**Comment by arvindsv** [comment]
@jsmythsci When you see the stage history in the UI (right-side of the stage details page at /go/pipelines/:pipeline_name/:pipeline_counter/:stage_name/:stage_counter), is the order right or wrong?

**Comment by jsmythsci** [comment]
Stage history in the UI is shown correctly. That is, page 1 shows the most recent 10 instances and page (max) shows the first X instances where X equals the mod10 result of the total number of instances.

### Examples
Currently our stage with the highest number of instances has 17255 instances and this is what is returned in the UI and the API:

* UI Page 1 (`/go/pipelines/:pipeline_name/:pipeline_counter/:stage_name/:stage_counter/overview.json?stage-history-page=1`)
  * Expected instances: 17255-17246 (10 most recent)
  * Actual instances : 17255-17246
* UI Page 3 (`/go/pipelines/:pipeline_name/:pipeline_counter/:stage_name/:stage_counter/overview.json?stage-history-page=4`)
  * Expected instances: 17225-17216 (offset of 3*10 instances)
  * Actual instances : 17225-17216
* UI Page 1726 (`/go/pipelines/:pipeline_name/:pipeline_counter/:stage_name/:stage_counter/overview.json?stage-history-page=1726`)
  * Expected instances: 5-1 (offset of 1725*10 instances)
  * Actual instances : 5-1
* API no offset (`/go/api/stages/:pipeline_name/:stage_name/history`)
  * Expected instances: 17255-17246 (10 most recent)
  * Actual instances : 10-1
* API offset of  30 (`/go/api/stages/:pipeline_name/:stage_name/history/30`)
  * Expected instances: 17225-17216 (offset of 30 instances)
  * Actual instances : 40-31
* API offset of  17250 (`/go/api/stages/:pipeline_name/:stage_name/history/17250`)
  * Expected instances: 5-1 (offset of 17250 instances)
  * Actual instances : 17255-17251

Hopefully this is clear.

**Comment by arvindsv** [comment]
@jsmythsci That's strange. @ankitsri11 tried to reproduce this and it was not reproducible.

Would you be able to run some queries against the DB? If you'd like to and can, instead, share the DB dump with us, that would work. Assuming that's not possible, here's what could help:

**Step 1**: Take a GoCD backup. Do not run this on a live instance.

**Step 2**: Unzip the backup and find the file `cruise.h2.db`. It'll be in a directory called: `db/h2db`.

**Step 3**: Download the H2 jar from maven: https://repo1.maven.org/maven2/com/h2database/h2/1.3.168/h2-1.3.168.jar (it is linked from: https://search.maven.org/artifact/com.h2database/h2/1.3.168/jar).

**Step 4**: Create a file called `test.sql` with these contents:

```sql
SELECT pipelines.counter as pipelineCounter,
       stages.counter as stageCounter,
       stages.id as stageId,
       stages.rerunOfCounter,
       builds.id as buildId
  FROM stages
         JOIN pipelines ON pipelines.id = stages.pipelineId
         INNER JOIN builds ON stages.id = builds.stageId AND builds.ignored != true
 WHERE stages.id IN (
   SELECT
     id
     FROM _stages
    WHERE name = 'PIPELINE_NAME_HERE'
      AND pipelineName = 'STAGE_NAME_HERE'
    ORDER BY id DESC
    LIMIT 10 OFFSET 0
 )
 ORDER BY stages.id DESC
```

*Note*: Replace the correct pipeline name and stage name in that query.

This is a slight simplification of [this query in the GoCD codebase](https://github.com/gocd/gocd/blob/1b5821b6e5b7e3fd6dd9d7b9a9b96a94fa82656c/server/src/main/resources/com/thoughtworks/go/server/dao/maps/Stage.xml#L441).

**Step 5**: Make sure that these files are in the same directory: `cruise.h2.db`, `h2-1.3.168.jar` and `test.sql`.

**Step 6**: Run this command in that directory:

```
java -cp h2-1.3.168.jar org.h2.tools.RunScript -url "jdbc:h2:./cruise" -user sa -script test.sql -showResults
```

Just for reference, when I run it, it looks like this (this is on a Mac):

```
$ ls
cruise.h2.db  h2-1.3.168.jar  test.sql

$ java -cp h2-1.3.168.jar org.h2.tools.RunScript -url "jdbc:h2:./cruise" -user sa -script test.sql -showResults
SELECT pipelines.counter as pipelineCounter,
       stages.counter as stageCounter,
       stages.id as stageId,
       stages.rerunOfCounter,
       builds.id as buildId
  FROM stages
         JOIN pipelines ON pipelines.id = stages.pipelineId
         INNER JOIN builds ON stages.id = builds.stageId AND builds.ignored != true
 WHERE stages.id IN (
   SELECT
     id
     FROM _stages
    WHERE name = 'PIPELINE_NAME_HERE'
      AND pipelineName = 'STAGE_NAME_HERE'
    ORDER BY id DESC
    LIMIT 10 OFFSET 0
 )
 ORDER BY stages.id DESC
;
--> 1 1 1 null 1
;$
```

It should give details about the pipeline counter and stage counter as the first two numbers (`1 1 1 null 1` in that example). You can change the offsets, as you did in your previous comment. In the contents of the file, the offset it set to 0.

Maybe we can learn something from the different values that it shows?

**Comment by jsmythsci** [comment]
In looking at the query I can see what is probably happening with my affected pipelines:

Instance selection is handled by the nested SELECT query. This is where both the offset and the limit are applied. Presumably this subquery is sorting the table in ASCENDING order rather than DESCENDING. This would explain why `offset` works "properly" regardless of whether this issue manifests.

Result order is determined by the outer query, which ensures that, no matter which instances are chosen, they are always returned in DESCENDING order.

I did some testing and it seems it has something to do with how the nested query is handled. 

### API vs DB query
For my tests I stopped my test GoCD server, copied its h2db file into my home directory and then restarted the GoCD server. This allowed me to compare the results of the direct DB queries against the results I got from the API. I matched the fields as closely as I could but I couldn't find the `buildId` in the API response so I left it off.

```powershell
> [hashtable]$ggshParams = @{
    PipelineName = 'CreditDriver-Build'
    StageName = 'ExtractCIcomponents'
    Offset = 0
}

(Get-GoCDStageHistory @ggshParams).stages |
    Select-Object -Property pipeline_counter,counter,id,rerun_of_counter


pipeline_counter counter    id rerun_of_counter
---------------- -------    -- ----------------
              10 1       16745                 
               9 1       16743                 
               8 1       16741                 
               7 1       16737                 
               6 1       16733                 
               5 1       16732                 
               4 1       16713                 
               3 1       16707                 
               2 1       16699                 
               1 1       16676                 
```

```sql
$ java -cp h2-1.3.168.jar org.h2.tools.RunScript -url "jdbc:h2:./cruise" -user sa -script test.sql -showResults
SELECT pipelines.counter as pipelineCounter,
       stages.counter as stageCounter,
       stages.id as stageId,
       stages.rerunOfCounter,
       builds.id as buildId
  FROM stages
         JOIN pipelines ON pipelines.id = stages.pipelineId
         INNER JOIN builds ON stages.id = builds.stageId AND builds.ignored != true
 WHERE stages.id IN (
   SELECT
     id
     FROM _stages
    WHERE name = 'ExtractCIcomponents'
      AND pipelineName = 'CreditDriver-Build'
    ORDER BY id DESC
    LIMIT 10 OFFSET 0
 )
 ORDER BY stages.id DESC

;
--> 10 1 16745 null 30458
--> 9 1 16743 null 30448
--> 8 1 16741 null 30438
--> 7 1 16737 null 30426
--> 6 1 16733 null 30406
--> 5 1 16732 null 30405
--> 4 1 16713 null 30386
--> 3 1 16707 null 30380
--> 2 1 16699 null 30372
--> 1 1 16676 null 30319
;
```

### Nested query on its own
For this test I extracted the nested query and ran it directly. Based on the result of the previous test, the expectation was that this would return `16676..16745` but it did not:

```sql
$ java -cp h2-1.3.168.jar org.h2.tools.RunScript -url "jdbc:h2:./cruise" -user sa -script test.sql -showResults
   SELECT
     id
     FROM _stages
    WHERE name = 'ExtractCIcomponents'
      AND pipelineName = 'CreditDriver-Build'
    ORDER BY id DESC
    LIMIT 10 OFFSET 0

;
--> 180102
--> 180081
--> 180076
--> 179964
--> 179915
--> 179885
--> 179777
--> 179769
--> 179587
--> 179551
;
```

### Removing the nested query
For this test I reworked the GoCD query to join the `_stages` table instead of using a subquery. The result was that it returned the expected instances (the same IDs returned by the previous test):

```sql
$ java -cp h2-1.3.168.jar org.h2.tools.RunScript -url "jdbc:h2:./cruise" -user sa -script test.sql -showResults
SELECT pipelines.counter as pipelineCounter,
       stages.counter as stageCounter,
       stages.id as stageId,
       stages.rerunOfCounter,
       builds.id as buildId
  FROM stages
         JOIN pipelines ON pipelines.id = stages.pipelineId
         INNER JOIN builds ON stages.id = builds.stageId AND builds.ignored != true
         INNER JOIN _stages ON stages.id = _stages.id
 WHERE _stages.name = 'ExtractCIcomponents'
      AND _stages.pipelineName = 'CreditDriver-Build'
 ORDER BY stages.id DESC
 LIMIT 10 OFFSET 0

;
--> 17093 1 180102 null 545983
--> 17092 1 180081 null 545944
--> 17091 1 180076 null 545930
--> 17090 1 179964 null 545689
--> 17089 1 179915 null 545563
--> 17084 2 179885 null 545495
--> 17088 1 179777 null 545194
--> 17087 1 179769 null 545177
--> 17086 1 179587 null 544760
--> 17085 1 179551 null 544683
;```


All of this leads me to believe that there is something about the way the h2 engine is handling the subquery.

I discussed this with our DBA and he suggested using the `WITH` clause to replace build the list of IDs. I tried a few things but so far I have been unable to get the syntax right so I don't know if it will work or not.

**Comment by arvindsv** [comment]
@jsmythsci Thank you for all of this. I'm still trying to get past the fact that the inner query is returning different set of values when run by itself when compared to when it is run as a part of an outer query! That is totally unexpected.

I will need to understand that more and might need to dig into the H2 engine, to see if this can be happening elsewhere. Not being able to reproduce this locally will make it harder. I'll see what I can do about that.

I can find time to look into this on Thursday. I'll be in touch. Thank you, again!

**Comment by jsmythsci** [comment]
@arvindsv The issue seems to be related to the size of the "unlimited" result set of the inner query. With this in mind, you may be able to reproduce by omitting the `WHERE` clause:

```sql
SELECT pipelines.counter as pipelineCounter,
       stages.counter as stageCounter,
       stages.id as stageId,
       stages.rerunOfCounter,
       builds.id as buildId
  FROM stages
         JOIN pipelines ON pipelines.id = stages.pipelineId
         INNER JOIN builds ON stages.id = builds.stageId AND builds.ignored != true
 WHERE stages.id IN (
   SELECT
     id
     FROM _stages
    ORDER BY id DESC
    LIMIT 10 OFFSET 0
 )
 ORDER BY stages.id DESC
```

I tested this against my DB and confirmed it gives the "expected" result based on the manifestation of this issue:

```sql
$ java -cp h2-1.3.168.jar org.h2.tools.RunScript -url "jdbc:h2:./cruise" -user sa -script test.sql -showResults
SELECT pipelines.counter as pipelineCounter,
       stages.counter as stageCounter,
       stages.id as stageId,
       stages.rerunOfCounter,
       builds.id as buildId
  FROM stages
         JOIN pipelines ON pipelines.id = stages.pipelineId
         INNER JOIN builds ON stages.id = builds.stageId AND builds.ignored != true
 WHERE stages.id IN (
   SELECT
     id
     FROM _stages
    ORDER BY id DESC
    LIMIT 10 OFFSET 0
 )
 ORDER BY stages.id DESC

;
--> 6 1 10 null 11
--> 5 1 9 null 10
--> 4 1 8 null 9
--> 3 1 7 null 7
--> 3 1 7 null 8
--> 2 1 6 null 6
--> 1 5 5 null 5
--> 1 4 4 null 4
--> 1 3 3 null 3
--> 1 2 2 null 2
--> 1 1 1 null 1
;
```

Based on my experience so far this will still require a data set of a significant size, however; we have stages with more than 7500 instances that are not affected.

**Comment by arvindsv** [comment]
@jsmythsci I wrote a script to generate pipeline runs in an H2 DB. I don't think I was able to reproduce this, still. I tried with 10000 runs of a pipeline (just takes a couple of seconds to generate it).

Can you take a look to see if the queries do something different for you or if you see anything out of place in what I did?

The script and the results are all in: https://github.com/arvindsv/gocd_github_issue_6041
