### ISSUE TITLE
Allow reordering of pipelines from config repositories

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#6042]
##### Issue Type

- Feature enhancement

##### Summary

Currently, pipelines from config repositories (pipelines as code) are randomly sorted, since they're converted to a set of names. An optional property: `display_order_weight` can be provided, at the pipeline level, which can be used to sort the pipelines on the dashboard.

This has been mentioned in other places, such as: https://github.com/tomzo/gocd-yaml-config-plugin/issues/4 and https://github.com/gocd/gocd/issues/3704#issuecomment-384689500.

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)
