### ISSUE TITLE
Introduce a cluster profile SPA

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#6045]
##### Issue Type

- Feature proposal

##### Summary

Part of epic: #5538. Introduce a new SPA to perform CRUD operations on cluster profiles.

**Comment by viraj2712** [comment]
We are staring with the `multi-cluster-SPA` using following mockup:

![Screenshot 2019-04-04 at 12 05 50 PM](https://user-images.githubusercontent.com/34642373/55534466-26778a00-56d2-11e9-9f52-ac757dab63e5.png)

**Comment by arvindsv** [comment]
Do "Clusters" need to be separated from "Elastic profiles"? What if they're both together?

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8953-b8f0069eae5a58849cd7e0835b5f2ff421be02bc)
