### ISSUE TITLE
Console errors on older chrome version

### ISSUE THREAD

**Issue by IanVaughan** [gocd/gocd#6051]
##### Issue Type
- Bug Report

##### Summary
* When on /go/pipelines, console shows errors.
* Also cannot trigger a build as "Revision to trigger with" never returns any results.

###### Basic environment details
GoCD Version: 19.1.0 (8469-3885582184c6f7c4bbbeb94239e5dba6f5f772f4).
Google Chrome	55.0.2883.87

Works fine on 
Google Chrome	69.0.3497.81

###### Additional Environment Details

```
Uncaught (in promise) TypeError: t.map is not a function
    at new t (header_footer_shim-aa13d835b32e706a56d1.js:1)
    at Function.t.fromJSON (header_footer_shim-aa13d835b32e706a56d1.js:1)
    at header_footer_shim-aa13d835b32e706a56d1.js:1
    at Function.t.all (header_footer_shim-aa13d835b32e706a56d1.js:1)
    at Object.repeaterFn (header_footer_shim-aa13d835b32e706a56d1.js:1)
    at t.fire (vendor-and-helpers.chunk-32166bede1e07ae12906.js:67)
t @ header_footer_shim-aa13d835b32e706a56d1.js:1
t.fromJSON @ header_footer_shim-aa13d835b32e706a56d1.js:1
(anonymous) @ header_footer_shim-aa13d835b32e706a56d1.js:1
t.all @ header_footer_shim-aa13d835b32e706a56d1.js:1
(anonymous) @ header_footer_shim-aa13d835b32e706a56d1.js:1
t.fire @ vendor-and-helpers.chunk-32166bede1e07ae12906.js:67
```

##### Possible Fix
Upgrade Chrome... but am locked into a version due to company restrictions.

**Comment by ketan** [comment]
This may possibly be a dup of #5968. Can you run `localStorage.clear()` in the chrome window and still reproduce this?

For the revision to trigger feature being broken, do you see any additional errors in chrome?

I should say that I'll try and help with this issue on a best effort basis, however the versions of chrome we support are the last 2 versions. Version 55 is over 2 years old.

**Comment by ketan** [comment]
Also: Are you able to enable source maps in your chrome dev tools and check what line of code this stacktrace maps to? The current stacktrace is not good enough for me to be able to pin down the root cause of the error.

**Comment by GaneshSPatil** [comment]
@IanVaughan -- any further updates on this issue?

**Comment by GaneshSPatil** [comment]
No Updates on the issue. Marking Stale...
Closing.
