### ISSUE TITLE
Improve OSX installers

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#6058]
##### Summary

Since java 9, there's been an introduction of [Platform-Specific Desktop Features](http://openjdk.java.net/jeps/272), internal APIs such as those in the Mac OS X `com.apple.eawt` package will no longer be accessible and is handled by `java.awt.Desktop` class instead.

This makes it difficult to be able to write version independent code that works on both java 8 and anything above.

Considering the difficulty of maintaining and testing a rather primitive desktop app, I'd like for us to remove the desktop app, and move to a simple zip installer for osx (with a JRE packaged alongside).

This will also involve modifying, ir wrapping existing scripts to be able to detect a JRE present alongside the extracted code and use that JRE for running GoCD.

**Backward compatibility notes**:

- allow for [reading environment variables from known locations](https://github.com/gocd/gocd/blob/b41c08c0cef95b925adbd2446ecd6072dd1e3f38/installers/osx-shared/JavaApplicationStub64#L754-L762)
- allow for running out of the correct `WorkingDirectory` (I think `~/Library/{Go Agent,Go Server}/...`
- the agent window app would store the [server URL](https://github.com/gocd/gocd/blob/b41c08c0cef95b925adbd2446ecd6072dd1e3f38/agent-bootstrapper/src/main/java/com/thoughtworks/go/agent/bootstrapper/osx/AgentMacWindow.java#L37), and use that URL to actually launch the agent process.

**Comment by adityasood** [comment]
verified on  19.3.0-8914
