### ISSUE TITLE
New backup page always shows /go-working-dir/... as the backup location

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#6094]
##### Issue Type

- Bug Report

##### Summary

New backup page shows `/go-working-dir/...` as backup location in all server instances. Looks like its hardcoded [here](https://github.com/gocd/gocd/pull/5966/files#diff-6346a0590450c08d118fdf2c36b19cc6R109)

Expected: Location should be the full path on the server instance, it helps users to find the backup files on the server machine

<img width="721" alt="Screen Shot 2019-04-08 at 10 07 34 AM" src="https://user-images.githubusercontent.com/6533924/55699091-b70ddd00-59e6-11e9-8aae-099ca412a276.png">

**Comment by akshaydewan** [comment]
The ruby code used the variable `@backup_location = backup_service.backupLocation()` to render this. The SPA doesn't make any call on page load. Looks like I'll have to add an API endpoint called `/api/backups/path` and call it from the SPA to render this properly.
