### ISSUE TITLE
[Secrets Management] Error message repetition for unresolved secret param in material URL

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#6102]
##### Issue Type

- Bug Report

##### Summary

The error messages are repeated in the error modal for unresolved secret params in material URL.

###### Basic environment details

* Go Version: 19.3.0-8851
* JAVA Version: JDK10
* OS: Mac
* Browser vendor and version (if relevant): Chrome-73.0.3683.86

<img width="1030" alt="Screen Shot 2019-04-08 at 2 59 49 PM" src="https://user-images.githubusercontent.com/17826464/55715192-dbcb7a00-5a11-11e9-82df-e4062d77401a.png">

**Comment by maheshp** [comment]
@rajiesh @adityasood we no longer support secretParams in material URL, please verify if this is reproducible when password attribute has secretParams.
