### ISSUE TITLE
[Secrets Management]  Do not mask display URL for materials with Secret Params

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#6104]
##### Issue Type
- Feature enhancement

##### Summary

Consider a scenario where users have pipelines in older versions of GoCD with materials as 

`https://user:password@github.com/user/test-repo.git` with pooling on in Pipeline-A

the display URL for this is 

`https://user:******@github.com/user/test-repo.git`

With the ability to configure Secret-Params the URL can also be of form

`https://user:{{SECRET:[my_secret][git_pwd]}}@github.com/user/test-repo.git`

Since, this is a separate URLfor GoCD and any pipeline configured with this URL can also have pooling switched off (while earlier pipelines can continue to support the password based URLs). Let's say Pipeline-B has this URL

the display URL for this is same as pevious one

`https://user:******@github.com/user/test-repo.git`

Today neither logs nor the UI can help understand that the MDU was specific to which URL. Since, we have changed the implementation for fingerprint generation, it would be helpful to show clearly via the UI the difference between the two URLs and also log it.

Maybe change the display URL for materials with secret params to 

`https://user:{{SECRET:[my_secret][git_pwd]}}@github.com/user/test-repo.git`

**Comment by maheshp** [comment]
With addition of support for username/password attributes for all materials, we will no longer support secrets in URL. Hence closing this issue.
