### ISSUE TITLE
UI issues with login page

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#6107]
##### Issue Type
- Bug Report

##### Summary

I suppose it is highly uncommon to have more than 2 login methods. But the UI should still be able to display the plugins properly?

1. When there's only one plugin shown, it might be better if its centered and the text doesn't read "Login using one of the login methods". 
<img width="437" alt="Screen Shot 2019-04-08 at 11 39 55 AM" src="https://user-images.githubusercontent.com/4715748/55748855-8df44900-59f4-11e9-8498-13b02476b245.png">

2. 3 login methods: The separation exists only between the first and second login method? And it overlaps with the plugin image
<img width="440" alt="Screen Shot 2019-04-08 at 11 44 07 AM" src="https://user-images.githubusercontent.com/4715748/55748961-c3009b80-59f4-11e9-8f16-381b0b1acebf.png">

4. More than 3 login methods
<img width="874" alt="Screen Shot 2019-04-08 at 11 45 19 AM" src="https://user-images.githubusercontent.com/4715748/55748987-cd229a00-59f4-11e9-8072-4d1575cc59e8.png">

###### Basic environment details

* Go Version: `19.3.0 (8859-d52d487a9784b3bb7dd62d2ebe02117f1ab8fcc9)`
* Browser vendor and version (if relevant): `Chrome: 73.0.3683.103, Firefox: 66.0.2`

cc @naveenbhaskar

**Comment by maheshp** [comment]
@naveenbhaskar additionally the errors on the login page show up on the bottom which is not consistent with the way the errors are shown across the application.

![Screenshot 2019-04-05 at 11 46 56 AM](https://user-images.githubusercontent.com/1061051/55772468-fb15e600-5aa9-11e9-918c-e678fe310969.png)
 
For password based login, if a username or password is not provided the error message should ideally be next to the input field, it shows at the bottom now.

<img width="885" alt="Screenshot 2019-04-05 at 12 25 58 PM" src="https://user-images.githubusercontent.com/1061051/55772566-534ce800-5aaa-11e9-8615-0b9d91a4f836.png">

**Comment by adityasood** [comment]
Closing this issue. We have changed the login design as per [this](https://github.com/gocd/gocd/pull/6156) PR and verifying these cases on that design.
