### ISSUE TITLE
Implement Cluster Profiles Changed plugin Api call

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6115]
##### Issue Type

Related: #5937

- Feature proposal

#### Summary
The Server will make this call whenever a cluster profile is changed.
This request is made to the plugin whenever a cluster is created, updated or deleted.

##### Request Body (when a new cluster is created):
```
{
	"status": "created",
	"cluster_profile_properties": {
		"go_server_url": "https://build.gocd.org/go"
	}
}
```

##### Request Body (when a cluster profile configurations are modified):
```
{
	"status": "updated",
	"old_cluster_profile_properties": {
		"go_server_url": "https://build.gocd.org/go"
	},
	"cluster_profile_properties": {
		"go_server_url": "https://new.build.gocd.org/go"
	}
}
```

##### Request Body (when a cluster profile is deleted):
```
{
	"status": "deleted",
	"cluster_profile_properties": {
		"go_server_url": "https://build.gocd.org/go"
	}
}
```

**Comment by dhanasp** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/6120

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)
