### ISSUE TITLE
Need a way to clean up the pipeline sandbox directory after job has completed

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#613]
There should be an option to allow the pipeline sandbox directories to be cleared or even deleted after GO has completed execution of all the tasks in the job and uploaded the artifacts to the server.

This is to ensure the disk space used by agents does not grow excessively and agents are kept "clean".

It needs to be optional to allow debugging of pipeline jobs where it can be useful to have a look at the files in the pipeline directory.

This cannot easily be achieved using custom code since any tasks will execute before the upload of artifacts therefore preventing these from being uploaded if they have been deleted.

**Comment by lorijoan** [comment]
:+1: to this, we're going to have to create our own strategy to cope with this.  It would be nice if this was offered out of the box.

**Comment by richard-hulm** [comment]
This would also be a good help to us! Some of our jobs have fairly large workspaces which could be deleted as soon as they're run to save space on the Agent
