### ISSUE TITLE
Normalised URL for material configuration in GoCD

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#6132]
### Issue Type
- Feature proposal
- Feature enhancement

### Issue

Currently, there are different ways in which the URL for a material can be specified. In case of Git and Mercurial - the credentials are provided in the URL itself. But for P4, SVN and TFS - we have additional attributes of `username` and `password` for the supplying the credentials.

This can be pretty confusing as to why the different configuration support URL format differently.

### Solution

Adding the attributes of `username` and `password` for Git and Mercurial configurations will help bring about the consistency among them. In order to maintain backward compatibility, the existing URLs for the mentioned configs will be normalised.

By normalised, we mean that the URL will be parsed and the credential part(userInfo) of the URL extracted out and stored in the attributes during config migration. 

#### git
   * User info in git url will be migrated to `username` and `password` attributes
       E.g.
        Original: `<git url="https://username:password@github.com" />`
        Updated: `<git url="https://github.com" username="username" password="password" />`

#### hg
   * User info in git URL will be migrated to` username` and `password` attributes
   * Additionally, if URL contains branch(specified after ##) will be migrated to branch attribute on the material config
       E.g.
        Original: `<hg url="https://username:password@domain.com##feature" />`
        Updated: `<hg url="https://domain.com" username="username" password="password" branch="feature" />`

### Normalization of Materials in DB
For consistency, we will have to normalize material URL's in db as well. Therefore the noramalization applied to material URL's in config will be applied to the db materials as well.

### Validation
Post-normalization, 
  - userInfo will not be allowed in URL's of both git and hg materials.
  - Branch in hg material URL will not be supported

#### git 
Prior to normalization, the fingerprint generation is a function of 
 - url
 - branch

Post-normalization
 - url (without userInfo)
 - username
 - branch

#### hg 
Prior to normalization, the fingerprint generation is a function of 
 - URL (which can have branch specified)

Post normalization
 - url (without userInfo and branch)
 - username
 - branch

### Config repo

Going forward, if the user specifies the credentials in the URL attribute (for the case of config-repo), the same normalization technique will be applied during save of the said configuration and the credentials will be stored in the separate attributes. 

### Breaking change

- Will be updated soon

**Comment by arvindsv** [comment]
Remember that: `C:/abc/def.git` and `C:\abc\def.git` are both valid URLs, as are `/abc/def.git` and `file:///abc/def.git`.

**Comment by maheshp** [comment]
@kritika-singh3 @ketan following changes are required post normalization of git and hg URL's,

1. PipelineConfig API v7 with support for `username`, `password` and `encryptedPassword` for git and hg materials.
2. Post normalization if users use PipelineConfig API v6 for pipelines with git or hg materials, they might end up loosing the configured credentials, how do we handle this?
3. UI to configure materials should change to allow users to configure credentials.
4. ConfigRepo support for credentials for git and hg materials.

**Comment by bdpiparva** [comment]
@maheshp - I will take a look at Pipeline config API v7 and also think about how to handle v6 where credentials are specified in a URL.

**Comment by bdpiparva** [comment]
## Pipeline config v6 and config-repo v1
The API should retain its request body and response structure as it is. (PR #6209 and #6137)

## Pipeline config api v7
Allow credentials for Git and Hg material through only attributes. 
- [ ] If credentials are specified in the url the provide an appropriate error.

/cc @adityasood

**Comment by arvindsv** [comment]
@bdpiparva @maheshp - I agree with this. Let v6 work as it was (allow credentials) and I guess we will need to dynamically convert them to username/password attributes as we do during a config migration.

For v7, just as in the UI, credentials shouldn't be allowed in the URL. Only as separate attributes.

**Comment by arvindsv** [comment]
Oh, also, we can deprecate v6 like we usually do.

**Comment by maheshp** [comment]
The original scope of story was to normalize the existing material URL's. We have decided against doing a force migration in favor of just adding support to provide credentials other than URL (https://github.com/gocd/gocd/issues/6298).

This issue can be used to track the changes around the PipelineConfig API and ConfigRepo API.

**Comment by adityasood** [comment]
Pipeline Config and Config repo API's were verified on 19.4.0-9129
