### ISSUE TITLE
User is able to access credentials of a deleted pipeline

### ISSUE THREAD

**Issue by childsc** [gocd/gocd#6134]
##### Issue Type
Bug Report

##### Summary

User is able to access the configuration for any deleted pipeline from any Pipeline Groups which can cause issues as the configurations will contain credentials for another user and possibly other valuable variables.

This can be a concern because lots of names for Pipelines are similar because the functions and purpose of the pipelines are fairly similar in general.

From the single pipeline we have found this issue on we have seen 4 different Project team repos configurations which include the passwords. This means that 4 different teams used a pipeline with the same name.

We believe that this is not for the purpose of retrieving deleted pipelines because when cloning we get the materials of the pipeline we cloned from. Similar when creating new pipeline, the materials are the same as the user specifies.

This is not the same as #879 because this is specifically about seeing old configuration.

##### Environment

    Go Version: GoCD Version: 18.12.0 (8222-e6778f1cc84bf91e323d337c876046167da36985).
    JAVA Version: OpenJDK 11.0.1
    OS: Linux 3.13.0-147-generic
    Browser vendor and version (if relevant): NA

##### Steps to Reproduce

1.  Create pipeline "A" 
2.  Build A
3.  Make changes to the configurations including Material path 
4.  Delete Pipeline "A"
5.  Clone any other existing pipeline from Pipeline Group 2, or  create a new pipeline with the Name "A"
6.  View configuration changes and find username and password for the original pipeline "A"

##### Expected Results
Like with the build log history, from the console, to not see the actual Configuration changes of the previously deleted pipeline.

##### Actual Results
Able to view all configuration changes of deleted pipeline.

##### Possible Fix
There are numerous suggestions of ways to get around this issue. 

1)  Ideally to just not show on screen previous history. I do not know how GoCD works in the background but I would assume we could, when deleting a pipeline when there would en an entry of say DELETED PIPELINE in the config history and if a pipeline is created with the same name then only show entries up to this String or some other similar Methodology.

2) Global default setting, which cold be removed if wanted, to prevent users from creating a new pipeline which has the same name as a deleted pipeline (in the same way we can not name a new pipeline the same as another existing pipeline). 

3) Change the way Pipelines are created o they use a UUID instead of a name and the Pipeline Key.  Pipeline name could become editable too or not. 

4) change the way git materials are allowed to be created. Force users to enter a username and a password which is secret instead of entering them in the URL in the same way as, for example,  TFS SCM plugin works.

**Comment by arvindsv** [comment]
@childsc Are you talking about using the "Changes" icon in stage history?

<hr>
<img width="464" alt="2019_04_12_11-50-52" src="https://user-images.githubusercontent.com/172235/56063683-fbc6aa80-5d3d-11e9-9a7f-48a62226852d.png">
<hr>

If so, you shouldn't even need to bring back the pipeline, right? You should be able to:

1. Create pipeline "A"
2. Build A
3. Make changes to the configurations including Material path
4. Delete Pipeline "A"
5. Go to any other pipeline's stage history.
6. **As a GoCD system administrator**, click on "Config changed" link.

Right? Or, have I misunderstood this?

Assuming I'm right: As I mentioned above, this is a link which works only for GoCD system administrators. That is super-admins. It uses [this API call](https://api.gocd.org/current/#get-repository-modification-diff). These are people who can, at any time, go to the repository itself, on the filesystem (usually, at: `/var/lib/go-server/db/config.git` and execute a `git log -p`) to see this historical information.

No historical configuration information is stored in the GoCD database. Just in the git repository which holds all configuration changes.

PS: Just FYI. Typically, anything which is a possible security issue should either be disclosed over email to support@thoughtworks.com or a little more securely on https://hackerone.com/gocd.

**Comment by arvindsv** [comment]
Oh, also, we are working on [secrets management support](https://github.com/gocd/gocd/issues/5830) which should allow you to move password from materials outside of GoCD! This should be out in 19.4, the release after the upcoming one.

**Comment by childsc** [comment]
Hi @arvindsv you are correct. Thanks for the clarification.

I will close this and anything in the future I will send messages about security, if there are any, through hackerone.

It is good to know about the secrets management support in 19.4 cant wait to see it.
