### ISSUE TITLE
Placeholder issue for Cluster profile SPA

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#6154]
##### Issue Type

- Bug Report

##### Summary

This is the placeholder for all issues related to Cluster profile SPA and related UI flow

- [x] Cluster profile summary misalignment when using latest EA plugins which supports Status report too,

<img width="1434" alt="Screen Shot 2019-04-17 at 3 18 25 PM" src="https://user-images.githubusercontent.com/6533924/56278591-22ad2400-6124-11e9-8095-03c242a7473c.png">

- [x] When start to create elastic agent profile under a cluster profile, the cluster profile list selects the first profile as default, not the cluster profile for which user tries to create the agent profile. This results in the agent profile getting created under a wrong cluster profile. This issue applies to plugin id drop down too, the plugin to which cluster profile belongs to is not selected by default

- [x] On GoCD server version : 19.3.0 (8944-9b7a1b461506436c8858ad5e4cb72b540dc41e2f) when user creates a cluster profile and then elastic agent profile for it, the Elastic profile SPA disabled the `Edit` and `Clone` buttons for the newly created elastic agent profile

- [x] Unexpected behavior on the SPA when cluster profiles of multiple plugins are created - more details [here](https://github.com/gocd/gocd/issues/6154#issuecomment-485877812)

###### Basic environment details

* Go Version: `19.3.0 (8914-1d2f3acdaee2510351622c9017d238c714e6d84d)`
* Docker EA plugin version: `2.2.0-218`

**Comment by rajiesh** [comment]
Unexpected behavior on Elastic profile when server has multiple elastic agent plugins installed

**GoCD version:** 19.3.0 (8951-ce45c93dc4b648b51054bc348c3f9232169f5429)
**Docker EA Plugin:** 2.2.0-219
**K8s EA plugin:** 2.1.0-170

Startup the server with both docker and k8s EA plugins installed. Create 2 cluster profiles for each of the plugins.

**Issue 1:** 
On the above setup click on Add Elastic agent profile for say Docker EA plugin
Enter some details but leave out any of the mandatory fields empty
Click on Save
Actual behavior: The Cluster profile ID drop down list item changes to K8s cluster profile and it view is displayed

**Issue 2:**
On the above setup create an elastic agent profile for say Docker EA cluster profile with all property values
Now edit this elastic agent profile
Actual behavior: View of k8s cluster profile is loaded

**Comment by adityasood** [comment]
**Issue 3:**

On edit of an existing elastic agent profile, the save error's out with "Plugin Id must be present" error.

![Screen Shot 2019-04-24 at 1 39 51 PM](https://user-images.githubusercontent.com/17826464/56643151-ad4ad180-6696-11e9-93c0-76dbcc1b8a11.png)

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)
