### ISSUE TITLE
Updating Cluster Profile does not validate elastic agent profiles

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6159]
##### Issue Type

- Bug Report

##### Summary

Updating cluster profiles lead to invalid cruise-config.xml configurations.

Steps to reproduce:
1. Create a cluster profile 'c1' for plugin 'ecs'.
2. Create a elastic agent profile 'p1' for plugin 'ecs' cluster profile 'c1'.
3. Update cluster profile 'c1' and change plugin id to 'docker', with specifying docker plugin's cluster configurations.
4. Hit save. The configurations get saved successfully.
5. Go to cruise-config.xml page, hit edit and save. It shows validation error: `Referenced Cluster Profile and Elastic Agent Profile should belong to the same plugin. Specified cluster profile 'c1' belongs to 'docker' plugin, whereas, elastic agent profile belongs to 'ecs' plugin.`

**Comment by maheshp** [comment]
@GaneshSPatil I am wondering why should a ElasticProfile have a direct reference to the `PluginId`, since a ElasticProfile is associated with a ClusterProfile can't we derive the pluginId from it?

**Comment by GaneshSPatil** [comment]
@maheshp -- agree. But making it explicit resolves the confusion (and some implementation complexities too).

1. `plugin_id` attribute on `profile` tag under cruise-config.xml makes the profile association with plugin explicit. Instead of finding the plugin id via associated cluster.
2. In the case of elastic agent APIs, to perform any operation, to find the plugin id, we will need to find the associated cluster and then pick the plugin_id of the cluster.
3. In the case of cluster profiles API, the update of the plugin id becomes complex as we will need to remember the elastic agent profiles belonging to the plugin and upon update, we will need to verify if the referenced elastic-agent profiles match the cluster-profile plugin_id.
4. [Implementation complexities] as of today, we do entity validations to verify the cluster-profile plugin_id and referenced elastic-agent-profile plugin_id matches. But after making it an implicit reference this validation will be complex.

Because of the above-mentioned reasons (and considering the value it adds by removing it), we chose not to do it.

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)
