### ISSUE TITLE
Missing "Tests" tab in Stage Detail

### ISSUE THREAD

**Issue by Diogomrol** [gocd/gocd#6167]
##### Issue Type

- Bug Report

##### Summary

Tests tab in Stage Detail is no longer there.

###### Basic environment details

* Go Version: 19.2.0
* OS: Windows

##### Steps to Reproduce

1. Access stage details in a pipeline with tests
2. Tests tab is missing

##### Code snippets/Screenshots

According to [documentation](https://docs.gocd.org/current/navigation/stage_details_page.html) the Tests tab should be there but it is not.

Screenshot: 
![Capture](https://user-images.githubusercontent.com/9485620/56354502-cb628e80-61cb-11e9-8835-d68ac46d5a69.PNG)

**Comment by ketan** [comment]
@Diogomrol this feature was removed in 19.2.0. We will update the documentation accordingly.

Keeping the issue open until the documentation is updated.

**Comment by ankitsri11** [comment]
Updated as part of this PR: https://github.com/gocd/docs.go.cd/pull/299

**Comment by ankitsri11** [comment]
Updated doc available here: https://docs.gocd.org/current/navigation/stage_details_page.html

Closing this issue.

**Comment by Diogomrol** [comment]
Hi,

Was there any particular reason for this to be removed?

Cheers

**Comment by ketan** [comment]
The feature had too many issues and it might come back in some other (hopefully better) form later.
