### ISSUE TITLE
Improvements to add config repo form 

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#6168]
Make filling out the add config repo form more intuitive (provide tooltips, placeholders, and auto-populate as makes sense)

- [ ] Auto-populate what we can:
     -  Config Repo ID (based on repo url)
     -  File pattern (with defaults)
- [ ] Add tooltips to all fields
- [ ] Change the style of Test Connection button to make the result more obvious
- [ ] Expand the Test Connection to be a preflight check?
- [ ] Rename the Config Repository ID to “Repo name”
- [ ] Remove or rename the Plugin ID to ‘json’ and ‘yaml’ etc
- [ ] Placeholder for URL & file patterns

**Comment by kierarad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve add config repo experience](https://trello.com/c/yJ1SNV3Z/108-improve-add-config-repo-experience)
