### ISSUE TITLE
Improvements to config repo SPA

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#6169]
Update information displayed on config repo SPA
 

- [x] Add pipeline count, pipeline list, and pipeline links (to pipeline tile) for each config repo PR #6360
- [ ] Rename “last known good commit currently being used” to “commit in use”
- [x] Only show additional commits if the “last known good commit currently being used” and “latest commit in repository” are not the same
- [ ] On show commit message with sha (and link to the commit in repo)
       - If we don’t do this at least change the time to display __ time ago
- [ ] Add status to collapsed config repo
- [x] Don’t treat “config repo never parsed” as error

**Comment by kierarad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improve existing config repo SPA to make more accessible for trialers](https://trello.com/c/vfnPKvkL/107-improve-existing-config-repo-spa-to-make-more-accessible-for-trialers)
