### ISSUE TITLE
Rename `profiles` tag to `elasticAgentProfiles` under cruise-config.xml

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6170]
##### Issue Type

- Feature enhancement

##### Summary

Elastic Agent profiles are represented the following way in cruise-config.xml
```xml
<elastic>
  <profiles>
    <profile id="profile1" pluginId="my.example.plugin" />
  </profiles>
</elastic>
```

With the introduction of cluster profiles, the elastic tag looks the following way:
```xml
<elastic>
  <agentProfiles>
    <agentProfile id="profile1" pluginId="my.example.plugin" />
  </agentProfiles>
  <clusterProfiles>
    <clusterProfile id="prod-cluster1" pluginId="my.example.plugin" />
  </clusterProfiles>
</elastic>
```

Rename the `profiles` tag to `elasticAgentProfiles` to make it more explicit.

**Comment by GaneshSPatil** [comment]
\cc: @bdpiparva @maheshp

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8953-b8f0069eae5a58849cd7e0835b5f2ff421be02bc)
