### ISSUE TITLE
Remove pluginId field from profile tag

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6173]
##### Issue Type

- Feature enhancement

##### Summary

Remove `pluginId` attribute from the profile tag. Each elastic agent profile points to a cluster profile. PluginId for a profile is implicitly referenced from cluster profile.

\cc: @maheshp

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8953-b8f0069eae5a58849cd7e0835b5f2ff421be02bc)

**Comment by GaneshSPatil** [comment]
Reopening this issue.

As of now, we have fixed API only to not render plugin id, the `agentProfile` tag under `cruise-config.xml` still contains `pluginId` attribute.

**Comment by rajiesh** [comment]
Verified on 19.4.0-9155
