### ISSUE TITLE
Login Page Authorization plugin images and text needs resizing

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#6181]
##### Issue Type
- Bug Report

##### Summary

The Authorization plugin images on the login page are too small. The text on the screen is also small.

###### Basic environment details

* Go Version: 19.3.0-8944
* JAVA Version: JDK10
* OS: MacOs
* Browser vendor and version (if relevant): Chrome- 73.0.3683.103, Firefox-62.0b9 (64-bit)

![Screen Shot 2019-04-22 at 2 40 35 PM](https://user-images.githubusercontent.com/17826464/56493794-e6a40580-650d-11e9-8e56-607faadd95ba.png)
<img width="758" alt="Screen Shot 2019-04-22 at 2 16 01 PM" src="https://user-images.githubusercontent.com/17826464/56493811-f7547b80-650d-11e9-97be-951f3e399a51.png">
<img width="766" alt="Screen Shot 2019-04-22 at 2 14 50 PM" src="https://user-images.githubusercontent.com/17826464/56493841-0b987880-650e-11e9-8cd0-3d4262e70e9e.png">

**Comment by rajiesh** [comment]
Fixed on 19.3.0 release build
