### ISSUE TITLE
Secure plugin properties are stored in plain text on server restart for EA plugins

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6184]
##### Issue Type

- Security issue
- Bug Report

##### Summary

Elastic Agent plugin's secure properties are stored in plain text on server restart.

##### Steps to reproduce:
1. Configure the cluster profile for an elastic agent plugin. Verify secure properties are stored in an encrypted form.
2. Restart GoCD server.
3. Upon restart, secure properties are stored as plain text.

**Comment by GaneshSPatil** [comment]
epic: #5538

**Comment by rajiesh** [comment]
Verified on 19.3.0 (8953-b8f0069eae5a58849cd7e0835b5f2ff421be02bc)
