### ISSUE TITLE
Support for color coding of Pipelines

### ISSUE THREAD

**Issue by ashishna** [gocd/gocd#6187]
##### Issue Type

- Feature proposal
##### Summary

Enable color coding on the pipelines group or individual pipelines to easily identify environment specific pipelines.

**Comment by GaneshSPatil** [comment]
\cc: @arvindsv  @naveenbhaskar

**Comment by arvindsv** [comment]
There are no plans to do anything like this, currently. At this point, the easiest thing to do might be for @ashishna to use dashboard views to create separate views as needed.

There is a concept of a "tag" for a pipeline, that I'm considering. Maybe we can incorporate some color coding during that. But, no plans at this time, as I mentioned. Thank you!
