### ISSUE TITLE
No GUI for deleting environment

### ISSUE THREAD

**Issue by JensRantil** [gocd/gocd#619]
I looked around a lot, but could not find an option to delete an environment.

Workaround: Manually modify the configuration XML.

**Comment by md2k** [comment]
November 2015 and still not such functionality, any updates ?

**Comment by zabil** [comment]
Not priority as of now. However a pull request implementing this will be given priority if it's on time for the 15.3 release.

**Comment by smaslennikov** [comment]
To expand on OP's solution: there's apparently [this](https://groups.google.com/forum/#!topic/go-cd/XBeG9c2p4YA) way of going about it.

**Comment by GaneshSPatil** [comment]
@JensRantil @smaslennikov -- there is an [api endpoint](https://api.gocd.org/current/#delete-an-environment) to delete an environment as well, but GUI as of now.

**Comment by inferiorhumanorgans** [comment]
Has there been any movement on this?

**Comment by EscapeLife** [comment]
You can edit the gocd config file to do this.

![image](https://user-images.githubusercontent.com/16237571/62180453-b5479b00-b382-11e9-9743-e4a467ef0e1e.png)

**Comment by Preen** [comment]
It's good that there's a way to do this manually but its kind of hacky and easy to make a mess.

**Comment by arvindsv** [comment]
I would say the better way is to [use the API](https://api.gocd.org/current/#delete-an-environment).

**Comment by arvindsv** [comment]
Closing as stale. This is also now possible in the UI (if not out in 19.11, it'll be out soon).
