### ISSUE TITLE
Improvements to Cluster Profile SPA

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#6198]
##### Issue Type
- Feature enhancement

- [ ] Disable delete on cluster profile if there is an elastic profile associated with it?

- [ ] Disable delete on an elastic profile if it is used in a job?

- [ ] Add tooltip on the disabled buttons

- [ ] The expand collapse panel should reset once the cluster profile is collapsed. Currently, if the user expands any section, collapses the cluster profile and then expands again, previous selections are still shown as expanded.

**Comment by maheshp** [comment]
\cc @bdpiparva consider as part of the Elastic Agent UX changes?

**Comment by bdpiparva** [comment]
@maheshp - Sure, I'll consider the issue as part of UX changes.
