### ISSUE TITLE
Feature Request: Please bring back the pipeline in progress animation

### ISSUE THREAD

**Issue by jacktomlinson** [gocd/gocd#6201]
We have recently upgraded to Go v19.2 and are sad to see that the animation of the orange in progress bar on the pipeline dashboard has gone. 😢 

![image](https://user-images.githubusercontent.com/15871032/56743776-287fb680-676f-11e9-9eba-302d45ce359f.png)

Is there any scope for this coming back in future releases? We think it really added some user feedback as to what was happening with our pipelines. Now we find ourselves refreshing the page to work out if the status of a pipeline has changed.

Please bring it back. 😄 🤞 

Thanks very much.

**Comment by arvindsv** [comment]
@jacktomlinson Thank you for this. It's good to know what people liked. 😄  More often, you hear what people don't.

It was removed because it was a big CPU hog (see https://github.com/gocd/gocd/issues/4353). I wouldn't mind bringing it back. However, it was _just_ a browser-side animation. The static yellow bar is the same as an animated yellow bar.

I think it would be more interesting to show whether a pipeline is stuck waiting for agents. It has been discussed a few times before. Don't you think?

/cc @naveenbhaskar

**Comment by jacktomlinson** [comment]
Hi @arvindsv - thanks for coming back to me on this. It's a shame to see that it was removed because of high CPU. I wonder if we could bring it back with some `transform: translate...` magic instead? 

The waiting for agents is a good point - it's not normally until you go in and check to see what is happening that you realise an agent has not been picked up yet. I wonder if we could solve this by introducing another colour state. Maybe it has a black and white stripe stage that means it is pending to start?

I think what the animation gave the user was live feedback on the dashboard, I think that is what we miss most about it. I wonder if we could get some more interaction in there to give the user the sense of something is happening? Maybe displaying the timer of the pipeline or something.

Hopefully we see it back soon!

**Comment by ketan** [comment]
> It was removed because it was a big CPU hog (see #4353).

I was going to respond with this same message. Then I reasoned that one of the reasons for the CPU spike (at the time) was lack of support for pipeline personalization and users seeing hundreds of building pipelines (with animation).

Now that we have personalization, perhaps we can bring back the animation (perhaps in some form that does not chew so much CPU). I don't know how much of a difference a `transform: translate ..`  as suggested here makes as against the older

**Comment by ketan** [comment]
(continued from previous comment, blame the new MBP trackpad)...

I don't know how much of a difference a transform: translate .. as suggested here makes as against the older [`animation: move ...`](https://github.com/gocd/gocd/pull/4418/files). Is this something you'd be willing to experiment and try (using a browser extension like stylish)?

If there's something that you find that works reasonably well, we're happy to update our CSS>

**Comment by naveenbhaskar** [comment]
For any css animation, cpu usage will be there ; if it is used in multiple times in the same page. 
The same yellow bar which is currently there used to animate before. So the only difference you see is a small movement. 

we can try using a small animated gif instead of the css animation.

**Comment by arvindsv** [comment]
> The waiting for agents is a good point - it's not normally until you go in and check to see what is happening that you realise an agent has not been picked up yet. I wonder if we could solve this by introducing another colour state. Maybe it has a black and white stripe stage that means it is pending to start?

@jacktomlinson There's a related conversation over at https://github.com/gocd/gocd/issues/5976

**Comment by jacktomlinson** [comment]
> @jacktomlinson There's a related conversation over at #5976

Awesome thanks very much!

**Comment by jacktomlinson** [comment]
> For any css animation, cpu usage will be there ; if it is used in multiple times in the same page.
The same yellow bar which is currently there used to animate before. So the only difference you see is a small movement.
>
> we can try using a small animated gif instead of the css animation.

Nice one for picking this up @naveenbhaskar - just taking a look at your PR as well. SVG animation sounds like a better way to go rather than bringing back the CSS animation. 👍 Think it will look better than a GIF as well, particularly if we are repeating this over a long pipeline bar on Retina screens. 

Looking forward to hopefully seeing this in a future release!

**Comment by rajiesh** [comment]
Fixed in 19.6.0 release
