### ISSUE TITLE
Build cause pop up ui on pipeline history has issue when browser is IE

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#622]
If build cause pop up comes upwards on pipeline history page, the pop starts showing the newer pipeline runs in background. In the following screenshots i am viewing the build cause pop up of pipeline run 1 and it starts showing details of pipeline run 2 in the background

![pipeline-history](https://cloud.githubusercontent.com/assets/6175869/4522266/b9ccbf20-4d25-11e4-8260-98f78e00bc43.png)

![build-cause-ie-issue](https://cloud.githubusercontent.com/assets/6175869/4522273/ce38fcbc-4d25-11e4-927f-302150ff10d0.png)

**Comment by GaneshSPatil** [comment]
IE11 and older versions of IE are not supported by GoCD.
Closing this issue as `WONT-FIX`
