### ISSUE TITLE
user management page - roles squashed together

### ISSUE THREAD

**Issue by mbotmcc** [gocd/gocd#6221]
##### Issue Type

- Bug Report

##### Summary

On the user management page, if a user is in multiple roles, they're all squashed together making it impossible to read 

##### Environment

gocd 19.3

![image](https://user-images.githubusercontent.com/35934878/56885174-b3a8c700-6a63-11e9-884a-ef1ded7ae9f4.png)

**Comment by maheshp** [comment]
\cc @naveenbhaskar can you please take a look.

**Comment by naveenbhaskar** [comment]
fixed
![image](https://user-images.githubusercontent.com/1627961/56941543-baead600-6b32-11e9-81c5-b0719d3b716c.png)

**Comment by adityasood** [comment]
verified-  19.4.0-9105
