### ISSUE TITLE
Handle HG URL normalization

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#6227]
Story: #6132

#### HG material URL with branch

Currently, we support HG material URL with a branch as:

```xml
<hg url="https://username:password@domain.com##branch-name" />
```

As per URI specs, any URL with a double hash is an invalid URI. The [migration](https://github.com/gocd/gocd/blob/master/config/config-api/src/main/java/com/thoughtworks/go/config/migration/UrlDenormalizerXSLTMigration121.java#L103) will skip URL normalization because of it. 

For Hg material, we should handle this scenario as we explicitly support this URL, hence migration should run on it.

**Comment by bdpiparva** [comment]
@maheshp and I discussed it. The `##` is added to support [named branch in URL](https://support.thoughtworks.com/hc/en-us/community/posts/213261446-Go-13-2-Mercurial-Named-Branches-Support). According to the post -

```
As Go uses the ‘#’ (hash) notation to expand parameters, the ‘#’ in the URL needs to be escaped 
with another ‘#’ - hence the ‘##’ in the URL above. If you don’t have multiple branches or just 
want to point the configured material to the ‘default’ branch of your repository, simply don’t 
specify any ‘#’
``` 

Later, the branch name is extracted from the URL and passed it to hg client using `--branch` option.

#### Solution
Run migration to migrate `##branch` as an attribute on hg material.

**Comment by maheshp** [comment]
Closing this since we are not normalizing the URL's. Existing behaviour would be retained with an additional  support for providing branch in an attribute. Hence closing this issue.
