### ISSUE TITLE
Add pipeline group to view and keep it updated

### ISSUE THREAD

**Issue by mbotmcc** [gocd/gocd#6246]
##### Issue Type

- Feature proposal

##### Summary

When I create a view and select the whole pipeline group to be included, it'd be good to have any new pipelines which are added to that pipeline group automatically show up in the view. Right now I need to edit the view every time a new pipeline is added.

**Comment by arvindsv** [comment]
There's a checkbox labeled "New" which does that, but it's across all the pipelines you have access to. Not just for a group.

**Comment by mbotmcc** [comment]
thanks, but that means the views collect everything added after it's created no matter which pipeline group it belongs to which defeats the purpose I think as I still need to go and edit it

**Comment by arvindsv** [comment]
Yes, I understand. /cc @naveenbhaskar
