### ISSUE TITLE
Enable read-access users to view Go pipeline configuration and settings

### ISSUE THREAD

**Issue by tonyzwei** [gocd/gocd#6281]
##### Issue Type

- Feature proposal

##### Summary

Please enable read-access users to view Go pipeline configuration and settings. Pipeline job consoles provide a list of environment variables but it is not convenient to read-only users.

**Comment by maheshp** [comment]
@tonyzwei this seems to be part of Granular Authorization https://github.com/gocd/gocd/issues/4735 work which we have been talking/analyzing for sometime now. This is on our radar but it might be little while before we pick it up.

Meanwhile, any feedback/comments on our [initial thoughts](https://github.com/gocd/gocd/issues/4735#issuecomment-466217517) around this feature would be appreciated.

**Comment by tonyzwei** [comment]
Thanks @maheshp for reply. Just let you know this issue got a lot attention now and we really need this feature to happen.

**Comment by adityasood** [comment]
@tonyzwei we have started some work on Granular Authorization. The progress can be tracked [here](https://github.com/gocd/gocd/issues/7222).
