### ISSUE TITLE
gocd job - pick least busy server

### ISSUE THREAD

**Issue by mbotmcc** [gocd/gocd#6286]
##### Issue Type

- Feature proposal

##### Summary

It'd be good if gocd picked the least busy server when scheduling jobs. 
e.g.
We have an environment called XYZ which has 2 servers in it. Each server has 4 agents running. When I run 5 tasks which need to run on environment XYZ, gocd places 4 tasks on server A and 1 on server B. It should place 3 tasks on server A and 2 on server B

**Comment by arvindsv** [comment]
Unfortunately, for GoCD server, the agents are all opaque. It doesn't care about where they're running. It might be possible to use elastic agents to do something like this automatically, but it's unlikely to be changed in GoCD core. So, I'll close this. Thank you!
