### ISSUE TITLE
Config repo SPA: Saving an existing config repo having credentials in URL is updating the URL credentials to `*******` in config

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#6296]
##### Issue Type

- Bug Report

##### Summary

Steps to reproduce the issue

1. Create a config repo with url `https://bob:user@example.com`
2. Click on edit button
3. The url will be displayed as masked url
4. Hit save without modifying anything.
5. Check the config.xml, it will have url as `https://bob:*******@example.com`

The bug verified with GoCD server version 19.2.0 and 19.3.0

**Comment by maheshp** [comment]
This must be fixed as part of 19.4.0. @rajiesh or @adityasood can you please verify and close this issue.

**Comment by rajiesh** [comment]
It was fixed as part of 19.4 itself, however issue was left open. Closing it
