### ISSUE TITLE
Disabled users still get notifications on pipeline events

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#63]
Description
-----------

Disabled users still get notifications on pipeline events

### Steps to reproduce

- Log in as USER\_A

- Go to Preferences page and set notifications filter for pass event of pipeline X

- Log in as ADMIN and disable USER\_A

- Run pipeline X and let it pass

#### Expected result

Disabled users shouldn't receive notifications

#### **Current result**

Even thought USER\_A is disabled, user still gets notifications

**Comment by curvedental** [comment]
We've run into this a bunch of times when disabling users since we forward emails from exiting employees to their respective manager, it would be nice if we didn't have to log in as the user to disable notifications after the fact.
