### ISSUE TITLE
Handle scheduled jobs gracefully with elastic agent is upgraded

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#6328]
##### Issue Type

- Bug Report

###### Basic environment details

* Go Version: `19.3.0`
* ECS plugin version: `6.0.0`

##### Steps to Reproduce

1. Start GoCD server 19.2.0 or prior
2. Install supported version ECS plugin
3. Trigger a few jobs. This will create job plans in DB with elastic profile metadata
4. Shutdown GoCD server before any of the job gets assigned to the agent
5. Upgrade GoCD server to `19.3.0` and ECS plugin to `6.0.0`
6. Start the server

On load of the new plugin, plugin settings will be migrated to `<clusterProfile>` but stored job plans(step:3) will not have any cluster profile metadata associated

GoCD server will try to create an agent for the scheduled jobs(in stip:3) using stored elastic profile. ECS plugin will not be able to create an agent for those jobs as cluster profile metadata is not present in job plans. GoCD schedules the jobs in the order it is stored in DB, as a result, none of the elastic agent jobs will get assigned.

#### Expected Results
During an upgrade, GoCD should handle such jobs appropriately and not call create agent if cluster profile metadata is empty or null.

#### Actual Results
GoCD keeps calling create agent without cluster profile info and it goes into the loop:

1. Create agent call: GoCD makes a call to the plugin (Job: job1, elastic_profile: profile1, cluster_profile: null)
2. ECS plugin will fail to create an agent  as a cluster profile is null
3. Server ping call: Nothing will happen as the cluster profile is null
4. GoCD reschedules the job post job starvation time out

#### Possible Fix
GoCD server should not make create agent call when job plan as no cluster profile associated. 
 - See if reschedule such jobs is possible?

#### Workaround
1. Before upgrading to `19.3.0` put GoCD into [maintenance mode](https://docs.gocd.org/current/advanced_usage/maintenance_mode.html)
2. Wait for all jobs to get finished
3. Upgrade the server to `19.3.0` and upgrade the plugin to `6.0.0`

**Comment by arvindsv** [comment]
@bdpiparva I changed the blue of the information box a bit (to make it lighter) and put the message in there, to call more attention to it).

<img width="894" alt="2019_05_24_10-52-07" src="https://user-images.githubusercontent.com/172235/58336611-0894ee80-7e12-11e9-923b-5bb07e7efc1d.png">

I might go ahead and merge it with this change. If you think it looks bad, please feel free to revert it later. Thank you!

**Comment by bdpiparva** [comment]
### GoCD server version 19.2.0

- On trigger of the pipeline, the `JobAgentMetadata` table is populated with the associated elastic agent profile JSON and it has a reference to the plugin id.
- GoCD server makes a call to the plugin using the elastic profile

### After upgrading to 19.3.0

- The jobs scheduled with 19.2.0 will have an empty entry for newly added cluster profile column in the `JobAgentMetadata` table. As a result, the plugin will get the `create-agent-call` with the elastic profile and empty cluster profile and the agent creation will fail.

### Post 19.5.0

- The changes done in the PR #6270 will now error out with `NPE` as the job scheduled with GoCD server version 19.2.0 will not have the cluster profile associated in the DB.
- Earlier, the call was failing at plugin side now the user will see `NPE` logs for the jobs scheduled before upgrading GoCD server.

https://github.com/gocd/gocd/pull/6270/files#diff-e7ba17c760ccb1e62de0e3e0454c9610R173


#### With the above context now we have two options:

1. Cancel the scheduled jobs

Cancel all the jobs scheduled before the 19.2.0 and has been not completed. Also, put the reason for cancellation in job console.

2. Reschedule the jobs

	a. In this approach, we have to cancel the currently running jobs as for those we have an older version of elastic profile(without cluster profile id) stored in DB.

	b. Create a new job plan which will have an elastic profile with the cluster profile id and also store the cluster profile in the DB.
	
	c. The newly created job plan will be picked up by BuildAssignmentService for assignment.

We are thinking of going with the first approach as we are canceling the job with the reason. In a way, the user will know what happened and what they have to do next.

/cc @gocd/committers

**Comment by arvindsv** [comment]
First approach makes sense to me. As we move away from 19.2, this should happen lesser and lesser and it's only a one-time effect upon upgrade. It doesn't make sense to put in too much work for this particular scenario. What it does currently, is bad though (hang without any information).

**Comment by rajiesh** [comment]
Verified on 19.6.0 (9492-738c70cbc80a2d13eea09e5b1c9432a175a0f5b7)
