### ISSUE TITLE
docker dind image doesn't have dockerd running

### ISSUE THREAD

**Issue by varshavaradarajan** [gocd/gocd#6337]
##### Issue Type

- Bug Report

##### Summary

The gocd-agent-docker-dind:v19.4.0 does not have docker daemon running. All docker related commands fail with `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`. Probably because https://github.com/gocd/docker-gocd-agent-dind/blob/master/run-docker-daemon.sh is blank.

###### Basic environment details

* Go Version: `19.4.0`

##### Steps to Reproduce

1. Run `docker run -it --privileged gocd/gocd-agent-docker-dind:v19.4.0` in terminal 
2. Exec into the container with `docker exec -it -u go <container id> /bin/bash`
3. Run `docker ps` and `ps` inside the container

##### Expected Results

Should exit the first command with `0` and should show the dockerd and containerd processes for ps
 
##### Actual Results

Exits `docker ps` with error `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?` and `ps` of course does not show dockerd or containerd running.

##### Possible Fix

Fix `run-docker-daemon.sh`.

**Comment by arvindsv** [comment]
@varshavaradarajan Is this fixed by https://github.com/gocd/docker-gocd-agent-dind/pull/5?

**Comment by varshavaradarajan** [comment]
Yes, it is. Closing.
