### ISSUE TITLE
Raw console logs of a building job are not available

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#6350]
https://github.com/gocd/gocd/issues/6325#issuecomment-495350446:
> If we're looking at this, have you noticed that you can't get the raw console logs of a job which is in progress?

https://github.com/gocd/gocd/issues/6325#issuecomment-495595603:
> I'd expect that it shows the same log that's being shown in the scrolling logs when that is clicked. Even though it's being updated. We will need to check that it's building and do that, right?

@arvindsv For the raw console logs, we point to the final console.log file, not the temporary file. As a result, we can't see the raw logs until the build is finished. Not sure if this is existing behaviour or if it was changed accidentally. Nonetheless, it seems unrelated to this issue. We can fix it separately.

_Originally posted by @akshaydewan in https://github.com/gocd/gocd/issues/6325#issuecomment-496398992_

**Comment by rajiesh** [comment]
Verified on 19.6.0 (9478-5f827efbc8001e16417fe13503f5e240d7ed060d)
