### ISSUE TITLE
Error message not shown in Template artifacts page

### ISSUE THREAD

**Issue by anusreePrakash** [gocd/gocd#6356]
##### Issue Type
Bug Report

##### Summary

When I try to configure artifact for a template, i entered a parameter as a value for the image name field. Clicking on submit , threw an error message saying:
"Save failed, see errors below"
But there was no error message displayed on the page. Looking into the elements section of the debugger, we could see the error message added as an ng tag. This is not shown to the user.

##### Environment
Test phase on new gocd

###### Basic environment details

* Go Version: `19.3`
* JAVA Version: `1.8.0_201`
* OS: `Linux 4.14.91+`
* Browser vendor and version (if relevant): `Chrome Latest`

##### Steps to Reproduce

1. Create a new template
2. Enter param in artifact section of any stage

##### Expected Results
Proper error message must be thrown to user
##### Actual Results
No error message is displayed and page is stuck

##### Code snippets/Screenshots
<img width="1440" alt="Screenshot 2019-05-30 at 2 40 53 PM" src="https://user-images.githubusercontent.com/15318212/58622893-603bca00-82ea-11e9-88ee-622c8d384317.png">

**Comment by arvindsv** [comment]
@anusreePrakash Thank you for reporting this.

We will need to look into this.

**Comment by varshavaradarajan** [comment]
Duplicate of #3103
