### ISSUE TITLE
Feature request: Better way to handle pipeline labels/build numbers counters

### ISSUE THREAD

**Issue by jacktomlinson** [gocd/gocd#6357]
Hi there,

Wondering if you could help us out or if there is a better way this could be done. Currently our pipeline labels are a bit of a mess when we carry a build through from the first pipeline, through a number of other pipelines to finally a production pipeline.

In each of our pipelines we pull the pipeline label from the previous connecting pipeline and then add `-${COUNT}` onto the end, as outlined in an example below:

### Current setup:
Pipeline 1 label: v100
Pipeline 2 label: v100-50
Pipeline 3 label: v100-50-42
Pipeline 4 label: v100-50-42-63
Production Pipeline: v100-50-42-63-22

We are wondering if there was any way of setting a pipeline to count how many times a particular build/artifact has gone into that pipeline? 

So for example below - we have build 100 just been created and its the first time build 100 has gone into "Pipeline 2" so the label would be 100-1 if we were to re run "Pipeline 2" then it would become 100-2. 

However if we kicked off build 101 from "Pipeline 1" then "Pipeline 2" would go back to being 101-1 and not the count of just that pipeline, if that makes sense.

### Proposed setup:
Pipeline 1 label: v100
Pipeline 2 label: v100-1
Pipeline 3 label: v100-2 (v100 has been run twice here)
Pipeline 4 label: v100-1
Production Pipeline: v100-1

Is this currently possible or something we could look to add in the future?

Thanks in advance for your help.

Jack

**Comment by arvindsv** [comment]
Hello Jack,

There is no way I know of to do this with pipeline labels. What you're asking about is the stage counter in a sense. It is available to tasks as the environment variable: `GO_STAGE_COUNTER`. But, it cannot be used in a label. A label is created / decided earlier in the process, before a stage is created.

One option, which involves some work though would be to write `GO_PIPELINE_COUNTER` and `GO_STAGE_COUNTER` out as artifacts and fetch. But, it's a bit of work just to be able to get that information downstream.

**Comment by jacktomlinson** [comment]
Hi @arvindsv,

Thanks for coming back to me - Ah yes, I had no idea `GO_STAGE_COUNTER` was a thing and that is exact what would help. 

Yeah that is a bit of work and would we only get the previous pipelines' `GO_STAGE_COUNTER` to write in downstream pipeline? If that makes sense.

I think we have enough to make a small improvement now. Thanks very much. 👍

**Comment by arvindsv** [comment]
You'll need to write out the stage counter in an artifact and fetch it anywhere you need. Using your example:

1. In pipeline 1, you'd write the counters to a specific artifact. Say: `versions.txt`
2. In pipelines 2, 3 and 4, you'd do the same.
3. In "Production" pipeline, you'd fetch from pipelines 1, 2, 3 and 4 and put them all together. Using both pipeline counter and stage counter.

It's more involved, as I mentioned. But, if you have a convention you follow for artifact, job and stage names, it becomes easier.
