### ISSUE TITLE
Server dashboard not initializing w/ WSL enabled

### ISSUE THREAD

**Issue by BHANA1** [gocd/gocd#6364]
##### Issue Type

- Bug Report
##### Summary

gocd server dashboard fails to initialize and hangs up at loading when WSL is enabled on Windows 10.

##### Environment

gocd server v19.4.0 on Windows 10 Enterprise, using Google Chrome Version 74.0.3729.169 (Official Build) (32-bit)
##### Steps to Reproduce

1. Have WSL Enabled
2. Click gocd server launch icon on desktop

##### Expected Results
Server loads briefly then starts.

##### Actual Results
Server dashboard starting/loading screen hangs indefinitely

**Comment by arvindsv** [comment]
Are there any logs in `C:\Program Files (x86)\Go Server`?
