### ISSUE TITLE
Pipeline display name and description

### ISSUE THREAD

**Issue by fabriciocduarte** [gocd/gocd#6366]
##### Issue Type

- Feature proposal

##### Summary

The pipeline name works much like an ID or primary key, with connections to other entities such as environment, other pipeline materials and so on, and as such it renders itself immutable.

Pipeline names are often social to developers, teams or organizations, by introducing a display name and description fields to pipelines it would decouple the display information from the immutable pipeline name.

The description field could render markdown syntax allowing for links to wiki pages or other related documentation sources.

**Comment by TomUdr** [comment]
👍 
I'm missing this feature for long time. We're using many different pipelines by many different teams and having description somehow visible in dashboard would be very helpful. Now we need to inject the most critical meaning into the pipeline names, but we'd like to capture in description for example consequences of execution, needed parameters, usage etc.

It could be non-intrusive UX element like question mark toolip.
