### ISSUE TITLE
Rerun old stage failing without providing console output

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#6376]
[Raising a new issue based on a comment in #1996]

We are experiencing a similar issue -- We are trying to go back in our pipeline history and manually invoke the second stage of in a previous pipeline.  We see in the go-server.log file  that that the stage is being assigned.  However, after that the job is marked as failed.  There is no console output in the job detail tab, nor can we find any corresponding error message or stack traces in the go-server or go-agent log files.

this is what we see in our log file:

```
go-server.log:2019-05-31 16:15:13,113 INFO  [qtp1166807841-17] ScheduleService:230 - [Stage Schedule] Scheduling stage publish_x for pipeline myapp_release
go-server.log:2019-05-31 16:15:20,068 INFO  [101@MessageListener for WorkFinder] BuildAssignmentService:191 - [Agent Assignment] Assigned job [JobIdentifier[myapp_release, 84, 2.3.5.84, publish_x, 9, aws, 50810]] to agent [Agent [ip-10-100-14-193.mydomain, 10.100.14.193, 194988d9-53e3-4f57-9a21-e38c53fdbc9d]]
```

The other thing thing to note is that even though we see in the go-server.log file that the stage is being assigned,   on the detail page for the failed job we see this `AGENT: Not yet assigned (Unknown)`.
There are two bits of information that might be playing a role here that are worth sharing:

- We have recently changed the underlying template for the pipeline. So the template that was active when the original pipeline first stage ran is no longer active.  However, the names of the stages and jobs within the pipeline remained the same.

- For one of the materials in the pipeline, the current definition points to a different git branch that it did when the pipeline run we are trying to run the second stage on.

In our case, these are our environment details:

###### Basic environment details

* Go Version: `19.4.0`
* JAVA Version: `1.8.0_101`
* OS: `Linux 3.10.0-327.28.2.el7.x86_64`

(We had noticed this problem on GoCD 19.3.0)

Not sure how to proceed in further troubleshooting this.  Any help would be greatly appreciated.

_Originally posted by @dlethin in https://github.com/gocd/gocd/issues/1996#issuecomment-497781524_

**Comment by arvindsv** [comment]
I suppose it's possible that something went wrong because the material is changed. We will need to reproduce it and see. Unfortunately, there won't be a guarantee of a rerun if the config changes too much, but I don't like that it showed no indication anywhere. It should be clear why something did not run, at least in the server logs.

**Comment by ankitsri11** [comment]
@arvindsv @dlethin - I was able to replicate the issue after changing the branch name and re-running the old stage. The stage failed with no console output.

However, when I changed the branch back to the original (master in my case) and re-ran older instance, it ran without any issue. Can you also confirm in your case?

Here are the steps I followed:

1. Created a pipeline with below configuration (default master branch):

 ```
 <pipeline name="DeployPipeline">
      <materials>
        <git url="https://github.com/some-repo />
      </materials>
      <stage name="DeployStage">
        <jobs>
          <job name="Job">
            <tasks>
              <exec command="ls">
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
```
2. Ran it few times.
3. Changed the branch to "feature" branch

```
      <materials>
        <git url="https://github.com/some-repo" branch="feature" />
      </materials>
```
4. Re-ran the old instance of pipeline and it failed without console-output.

![Screenshot 2019-06-03 at 15 19 08](https://user-images.githubusercontent.com/6838313/58838254-ffc2ca80-8612-11e9-9642-f29f47d8dc40.png)

Enabled debug logging by adding below in logback-include.xml.

```
<?xml version="1.0" encoding="UTF-8"?>
<included>
    <logger name="com.thoughtworks.go" level="DEBUG" additivity="true">
    <appender-ref ref="${gocd.server.logback.root.appender:-FileAppender}" />
  </logger>
</included>
```
Attaching the complete logs capturing the re-run activity:
[tmp.txt](https://github.com/gocd/gocd/files/3249692/tmp.txt)

**Comment by arvindsv** [comment]
When a material is changed, it might not be able to recreate the previous state of the materials (and it knows it). Maybe. However, the console logs need to provide more information. I'm marking this as a bug we need to look into, to fix the console logs, if nothing else.

Thank you for bringing it up, @dlethin.

**Comment by arvindsv** [comment]
Also, there is some error in the logs related to the cache - and I think it makes sense to investigate.

**Comment by dlethin** [comment]
Thanks for chasing this down so quickly @arvindsv  -- I'm assuming I should be able to get past this by temporarily changing the current pipeline material branch definition as you say -- I just need to bubble this up my stack of priorities to be able to get to try this again.   I will let you know otherwise if I run into problems.   I agree it at the very least some error message would be helpful, though I would think it should be able to proceed using the githash of the material from the prior upstream stage run, but admittedly I don't know the internal workings very well to comment further.

cheers.

**Comment by arvindsv** [comment]
> I will let you know otherwise if I run into problems.

👍 

> I agree it at the very least some error message would be helpful, though I would think it should be able to proceed using the githash of the material from the prior upstream stage run, but admittedly I don't know the internal workings very well to comment further.

Yes, someone will need to understand the flow and see what can be done, once the bug which is hiding the error is fixed. I agree, in an ideal world, it should try and rerun it, even if things have changed a bit.

**Comment by arvindsv** [comment]
https://github.com/gocd/gocd/pull/6389 is related to this.
