### ISSUE TITLE
Should there be a verify connection end point for secrets file

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#6393]
##### Issue Type

- Bug Report

##### Summary

Creating this issue to get inputs if we need verify connection end point for secrets file. This can be used to add `Test Connection` option on the secrets config create/update flow. Another option is to not have specific API for verify file is present, but the validation for file is existing can be added as part of the secret config save itself

**Comment by bdpiparva** [comment]
@rajiesh - For the [gocd-file-based-secrets-plugin](https://github.com/gocd/gocd-file-based-secrets-plugin) this is implemented as part of save. On save of secret config, we ask the plugin to validate it. If config is invalid user will not be able to save it and UI will have appropriate errors on the respective field.

At this point for time, I don't see any strong reason to add verify connection endpoint for secret management plugin. /cc @maheshp  - WDYT?

**Comment by maheshp** [comment]
> @rajiesh - For the gocd-file-based-secrets-plugin this is implemented as part of save. On save of secret config, we ask the plugin to validate it. If config is invalid user will not be able to save it and UI will have appropriate errors on the respective field.

While this seems fine for a file based plugin maybe we might need to provide an option to verify connection. Verifying connection as part of a save might take time for a plugin which connects to an external Secret Manager over network and that experience might not be optimal.

I think we should consider having some consistency between plugins, the Authorization Plugin allows a `Check Connection` but others do not e.g `Artifacts`, `Secrets` etc..

**Comment by rajiesh** [comment]
Keeping it open, will verify if validation at save or exclusive verify connection API is needed for future plugins we are developing for secrets. Moving to 19.8
