### ISSUE TITLE
Server Configuration Page Rewrite

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6400]
##### Issue Type
- Feature enhancement

##### Summary

Migration existing server configuration page written in rails to a SPA.
- [ ] Server Management 
	 - [ ] API (#4189)
	 - [ ] UI
- [ ] User Management
	 - [ ] API
	 - [ ] UI
- [ ] Email Notification
	 - [ ] API (#6401)
	 - [ ] UI
- [ ] Pipeline Management
	 - [ ] API (#4189)
	 - [ ] UI
- [ ] Command Repository Management
	 - [ ] API (#4189)
	 - [ ] UI

**Comment by adityasood** [comment]
![IMG_1592](https://user-images.githubusercontent.com/17826464/65592518-5a11dd80-dfac-11e9-8b43-add1000778c5.png)

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/7102
