### ISSUE TITLE
No indication of failure when subsequent stages are run after material config is changed post first stage run

### ISSUE THREAD

**Issue by msaurabh1978** [gocd/gocd#6409]
##### Issue Type

- Bug Report

##### Summary

This bug is reproducible every time when a pipeline has more than one manual stage and more than one materials configured.  After the first stage, if we change the pipeline material configuration, let's say by removing one of the configured material, then the subsequent stage run fails. But there is no information regarding the failure, neither in the server logs nor in the job console logs.

##### Steps to Reproduce

- Create a pipeline with more than one manual stage and more than one materials
- Run the first stage successfully
- Modify the pipeline material configuration, let's say by removing one of the configured material
- Run the next stage. 
- You will see that there is no information regarding the failure (neither in server logs nor in console logs)

##### Expected Results
Information regarding why the stage run failed should be logged in console logs so that user can easily understand the reason for failure.

##### Actual Results
Currently, when a stage fails after following the above steps to reproduce, there is absolutely no information available anywhere.

**Comment by arvindsv** [comment]
@msaurabh1978 Is this the same as https://github.com/gocd/gocd/issues/6376 ?

**Comment by msaurabh1978** [comment]
> #6376

Not sure @arvindsv, doesn't look like but will check and confirm back.

**Comment by arvindsv** [comment]
@msaurabh1978 Did you find anything?

**Comment by msaurabh1978** [comment]
> @msaurabh1978 Did you find anything?

Yeah. Found the root cause and fixed it (PR is #6389). Both of these issues, though symptom wise, unrelated, happened to originate from the same cause. I will provide all the details on issue #6376

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9912-33898b3adaf72cedea1604882d3554fd586571a8)
