### ISSUE TITLE
Use Templates for emails

### ISSUE THREAD

**Issue by ckaushik** [gocd/gocd#641]
The email notifications being sent are hard coded. We have to change the source code and build to get these changes. It would be good to use a template file which defines the Subject and the body of the email using some details like StageName, BuildBreakers etc.

**Comment by srinivasupadhya** [comment]
I have added [notification end-point](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html). Should be available in 15.1.0. Hopefully you should be able to write a plugin for this.

**Comment by srinivasupadhya** [comment]
Also, #361 is similar to this.
