### ISSUE TITLE
Apply secret config rules on environment config create or update

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#6416]
### Issue Type

- Feature proposal

### Summary

With the introduction of secret param in an environment variables, A environment config create and update should validate if it can refer to a secret config. 

> Secret config
```xml
<secretConfig id="production_vault" pluginId="vault_based_plugin">
    <description>All secrets for production</description>
     <configuration>...</configuration>
    <rules>
        <allow action="refer" type="environment">production_env</allow>  
    </rules>
</secretConfig>
```
Given the above secret config, create or update should fail for the environment config refering to secret config id `production_vault` in one of the environment variable and having name other than `production_env`.

<details>
   <summary>Part of the Valid environment config</summary>

> GoCD should allow a user to create or update an environment `production_env` with the following configuration -

```xml
<secretConfig id="production_vault" pluginId="vault_based_plugin">
    <description>All secrets for production</description>
     <configuration>...</configuration>
    <rules>
        <allow action="refer" type="environment">production_env</allow>  
    </rules>
</secretConfig>
...
<environments>
    <environment name="production_env">
      <environmentvariables>
        <variable name="SSH_KEY">
          <value>{{SECRET:[test][SSH_KEY]}}</value>
        </variable>
      </environmentvariables>
      <agents>
        <physical uuid="9ed1dbd5-3bfc-4b30-a9b3-0390bdbd2f8b" />
      </agents>
      <pipelines>
        <pipeline name="deploy" />
      </pipelines>
    </environment>
</environments>
```
</details>

<details>
   <summary>Part of the invalid environment config</summary>

> GoCD should error out while creating/updating environment `can_not_refer_secret_config_production_vault` with the following configuration as secret config rule is violated.

```xml
<secretConfig id="production_vault" pluginId="vault_based_plugin">
    <description>All secrets for production</description>
     <configuration>...</configuration>
    <rules>
        <allow action="refer" type="environment">production_env</allow>  
    </rules>
</secretConfig>
...
<environments>
    <environment name="can_not_refer_secret_config_production_vault">
      <environmentvariables>
        <variable name="SSH_KEY">
          <value>{{SECRET:[test][SSH_KEY]}}</value>
        </variable>
      </environmentvariables>
      <agents>
        <physical uuid="9ed1dbd5-3bfc-4b30-a9b3-0390bdbd2f8b" />
      </agents>
      <pipelines>
        <pipeline name="deploy" />
      </pipelines>
    </environment>
</environments>
```
</details>

**Comment by maheshp** [comment]
@bdpiparva where do you think we can add this validation?

**Comment by bdpiparva** [comment]
@maheshp - This can go in `EnvironmentCommand` so that it will happen only on save or update of environment config but not on in general config validation.

> Example
```java
public boolean isValid(CruiseConfig preprocessedConfig) {
        EnvironmentConfig config = preprocessedConfig.getEnvironments().find(this.environmentConfig.name());
        try {
            rulesService.validateSecretConfigReferences(preprocessedPipelineConfig);
        } catch (RulesViolationException e) {
            result.unprocessableEntity(e.getMessage());
        }

        boolean isValid = config.validateTree(ConfigSaveValidationContext.forChain(preprocessedConfig), preprocessedConfig) && result.isSuccessful();

        if (!isValid) {
            String allErrors = new AllConfigErrors(preprocessedConfig.getAllErrors()).asString();
            result.unprocessableEntity(LocalizedMessage.composite(actionFailed, allErrors));
        }

        return isValid;
    }
```

**Comment by maheshp** [comment]
@bhupendra I am just wondering if we should add this validation. Few of my concerns are,
1. With this validation a pipeline can turn invalid on an update even if there is no change to the config, this can happen if a rule has changed.
2. Since this validation is done in a command, the behaviour would differ between API and PaC.

**Comment by bdpiparva** [comment]
> With this validation a pipeline can turn invalid on an update even if there is no change to the config, this can happen if a rule has changed.

On edit of the pipeline if the config is not valid then it will tell the user to update it. Instead of using the old config for which pipeline will fail before the assignment.

> Since this validation is done in a command, the behavior would differ between API and PaC(Pipeline as code).

Agreed, that there will be a difference between pipeline config through API and PaC. For PaC this validation can be done as part of the preflight check. We can add validation on config repo parse as well so that behavior will be similar in both the cases.

@arvindsv , @ketan - WDYT?

**Comment by arvindsv** [comment]
@bdpiparva @maheshp Is this similar to the discussion around [here](https://github.com/gocd/gocd/issues/6095#issuecomment-496777546)?

If a _pipeline_ is edited and a secret config is used which is not allowed, the pipeline edit fails. Right?

Isn't this similar, but just for environment edit?

@maheshp said:
> With this validation a pipeline can turn invalid on an update even if there is no change to the config, this can happen if a rule has changed.

But that is on edit of the secret config. Right? Won't that fail?

Remember that we also have operations such as "Move pipeline to group X" (in Admin -> Pipelines). That has the ability to make the config invalid, if a pipeline moves to a group in which a secret used in the pipeline is invalid.

<hr>

I'm not entirely clear which rules are evaluated at config save time and which rules are evaluated at runtime. I agree with @maheshp that we should decide and be consistent. Even between APIs and PaC.

**Comment by arvindsv** [comment]
Ah, I had missed https://github.com/gocd/gocd/issues/6415

**Comment by rajiesh** [comment]
Since the motivation behind this proposal is for faster feedback while using secrets in create/update of any entity, there are 3 input errors possible - Provide invalid secret config id or Invalid secret key or use a secret in entity where the rule prohibits usage - validating only rules may still leave the UX incomplete

**Comment by bdpiparva** [comment]
1. When a pipeline config is created/updated the secret config rule should apply to give faster feedback rather than failing it when a pipeline is triggered.

2. The runtime validation is introduced because of https://github.com/gocd/gocd/issues/6369#issuecomment-498348913


This validation is not the part of config validation flow(which is `validate(ValidationContext)`) but this will happen on entity update command to give faster feedback when the user is creating/updating a pipeline config.


> But that is on an edit of the secret config. Right? Won't that fail?

If I understood it right, you are saying secret config save should fail if it is referred in pipeline config?

Secret config save, should not fail as it defines who can access the secrets from a secret provider. Admin should be able to restrict the access without changing the pipeline configs. That was the reason we moved the secret config rule evaluation to runtime.

> Remember that we also have operations such as "Move pipeline to group X" (in Admin -> Pipelines). That has the ability to make the config invalid if a pipeline moves to a group in which a secret used in the pipeline is invalid.

If we apply the above-proposed solution, a user will get the appropriate errors on move or clone operation.

> I'm not entirely clear which rules are evaluated at config save time and which rules are evaluated at runtime. 

When pipeline triggered, rules from the secret config(s) used in the pipeline will be evaluated. In this issue, I am proposing the same rule should be validated on the pipeline config when it is created/updated.

> I agree with @maheshp that we should decide and be consistent. Even between APIs and PaC.

I strongly agree with this. but as of now, I am not entirely clear about how validation happens for PaC. I will spend some time on this.


> Provide invalid secret config id or Invalid secret key or use a secret in an entity where the rule prohibits usage - validating only rules may still leave the UX incomplete

Agreed, Ideally, the UI should smart enough to provide the suggestions about available secret keys for the selected secret config as mentioned in https://github.com/gocd/gocd/issues/5836

PS: This is also valid for environment config.

**Comment by arvindsv** [comment]
> Secret config save, should not fail as it defines who can access the secrets from a secret provider. **Admin should be able to restrict the access without changing the pipeline configs**. That was the reason we moved the secret config rule evaluation to runtime.

Ok, with that expectation, I understand why that secret config save should not fail.

So, if the case mentioned in https://github.com/gocd/gocd/issues/6369#issuecomment-498348913 happens, then ad admin will be able to save the secret config change. However, next pipeline run might fail (at runtime). If a pipeline admin tries to edit that pipeline, then it won't be allowed to be edited till the secret usage (which is now invalid) is removed. Right?

What happens when the server is restarted? Or if the XML is edited directly. If a full config save validates this condition, then the server won't come up. Am I right in saying that you're planning to add this verification only in pipeline (or env) update API call?

**Comment by maheshp** [comment]
Discussed this with @bdpiparva and @arvindsv. This validation is required for quicker feedback to users over runtime failures. This needs to be added when we update the config through API, config_xml, UI and PaC to keep it consitent. 

We need not wait on this to live with Secrets Management. We can introduce this validation or come up with a better UX in subsequent releases.
