### ISSUE TITLE
Metrics for Trial XP in GoCD

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6423]
> Migrated from [Trello Card 104](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;sDUPg5pz)

CTA: New Pipeline, Save + Run
Possible metric: Time from dashboard to Save/Run, Overall Time in app
Others?

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @loudaTW
> Original date: Tue, 21 May 2019 20:05:37 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-21T20%3A05%3A37.857Z)

@ibnc @marques-work Let's chat about this

**Comment by loudaTW** [comment]
@marques-work @ibnc Any progress on this?

**Comment by ibnc** [comment]
@loudaTW 

Duck and I briefly talked, and we both agree that Google analytics is out. It's too intrusive, and not inline with GoCD philosophy. 

I'll be looking into using the data sharing functionality that's already present.
