### ISSUE TITLE
Support Task config: `working directory` - How?

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6443]
> Migrated from [Trello Card 83](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;jq7onXVr)

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @kierarad
> Original date: Wed, 22 May 2019 20:02:37 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-22T20%3A02%3A37.651Z)

@marques-work is the same as #6432

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @marques-work
> Original date: Wed, 22 May 2019 20:03:44 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-22T20%3A03%3A44.881Z)

@kierarad yes, I believe it is. Let's archive that one.

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @marques-work
> Original date: Wed, 22 May 2019 20:04:10 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-22T20%3A04%3A10.571Z)

or rather, I'll archive it.

**Comment by marques-work** [comment]
possibly as:

`cd /path/to/wd; cmd arg arg...`

may need some consideration WRT being a special form that that doesn't look special.

**Comment by marques-work** [comment]
Settling on `CWD:relpath/to/wd cmd arg arg` until proven to be a Bad Idea (tm).

This syntax is concise and easy to understand. It also intentionally does not resemble a bash or other common shell construct so as not to give users the impression that constructs such as `;`, `|`, `&&`, `{...}`, and the like actually work without wrapping in a shell eval (e.g., `bash -c`).

**Comment by marques-work** [comment]
Settling on `CWD:relpath/to/wd cmd arg arg` until proven to be a Bad Idea (tm).

This syntax is concise and easy to understand. It also intentionally does not resemble a bash or other common shell construct so as not to give users the impression that constructs such as `;`, `|`, `&&`, `{...}`, and the like actually work without wrapping in a shell eval (e.g., `bash -c`).

It’s a special form, so should look like one.

**Comment by marques-work** [comment]
PR #6769

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.9.0 (9929-91f828d47612be57eeb28377e7c3ca6206b8d992)
