### ISSUE TITLE
Support Package Repository Material

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6445]
> Migrated from [Trello Card 93](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;dlf3hM0b)

The addition of the fields to the material editor is the _easy_ part. This is **not** just about that.

We should give some thought to how this impacts the flow. In old/production add pipeline flow, the user will exit the add pipeline flow to first create a package repository if none exist. Do we want that for the new flow? Or is there a way to create one without leaving the page?

**Comment by marques-work** [comment]
The easiest thing to do (which is also the most likely) is to replicate the behavior on the old page. Might need some UX consideration (or at least a tooltip) to convey the concepts, but it should be relatively low-hanging fruit.
