### ISSUE TITLE
Thin Slice - PaC Builder

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6457]
> Migrated from [Trello Card 120](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;Sa8NEbiM)

Parent issue of #6621.

Generate a skeleton pipeline definition from a plain form. The outputted file should be functional.

Possible approaches:

- transpile reverse-transform code to JS and do this client-side
- take advantage of the export plugin endpoint
- plain old string interpolation

Questions:

- user-initiated action via "preview" button?
- or automatic (not on a timer; perhaps `onchange` instead)

## Depends on

- #6600

**Comment by marques-work** [comment]
Probably best to start with the `export` endpoint; likely will need an internal API
