### ISSUE TITLE
Add/update links to test drive on website

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6459]
> Migrated from [Trello Card 43](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;TEPM6HxT)

## Related

* #6529

Link banner in blog post (example at bottom of https://www.gocd.org/2018/10/30/measure-continuous-delivery-process/)

<img width="911" alt="Screen Shot 2019-07-03 at 1 10 43 PM" src="https://user-images.githubusercontent.com/1781525/60622087-50ede780-9d94-11e9-8565-b85ccf80a14b.png">

Pages to add banner to: 
Footer link
 - @loudaTW Do you mean to add a link in the site-wide footer?

Intro Guide: https://www.gocd.org/getting-started/part-1/

~~Features: https://www.gocd.org/why-gocd/~~

~~What's New in GoCD: https://www.gocd.org/2018/10/16/new-gocd-features/~~
~~Replacing GoCD: https://www.gocd.org/2018/08/21/replacing-gocd-with-gocd/~~
~~Working with Materials: https://www.gocd.org/2018/07/17/gocd-materials-blacklisting-whitelisting/~~
~~Beginner's Guide: https://www.gocd.org/2018/01/17/continuous-delivery-beginners-guide/~~
~~CD101 blogs: https://www.gocd.org/tags/cd-101.html~~
~~GoCD v Spinnaker: https://www.gocd.org/2017/07/10/gocd-vs-spinnaker/~~
~~Deployment Pipeline Patterns: https://www.gocd.org/2017/06/22/deployment-pipeline-patterns-infographic/~~
~~CI Theatre: https://www.gocd.org/2017/05/16/its-not-CI-its-CI-theatre/~~
~~GoCD over Jenkins: https://www.gocd.org/2017/04/25/gocd-over-jenkins/~~
~~Not CD if you can't: https://www.gocd.org/tags/it-s-not-cd-if-you-can-t-deploy-right-now.html~~

Jenkins: https://www.gocd.org/jenkins/
 - @loudaTW This page has a CTA that directs to the old Getting Started experience, with a Campaign analytics tag. Do we want to redirect this CTA to the Test Drive page?

Docs Quick Help: https://docs.gocd.org/current/
 - @loudaTW There's no way to add the banner to the docs, is there a text-based solution we can use to appropriately link the Test Drive on the docs?

Docs Tour: https://docs.gocd.org/current/navigation/
 - @loudaTW Same docs issue as above.

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @loudaTW
> Original date: Tue, 21 May 2019 20:08:26 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-21T20%3A08%3A26.277Z)

@streisguth Let's prioritize these

**Comment by streisguth** [comment]
Had some issues with this partial not resizing properly with multiple lines of text because some heights were absolutely defined. Spiking out a refactor in a branch.

**Comment by streisguth** [comment]
@loudaTW 
Refactor looks good, need to QA on the few blog pages that the partial exists on but should be ready to go. Next steps will be to implement the Test Drive banners on the blog posts listed above and then merge the branch.

**Comment by loudaTW** [comment]
@streisguth Great, this sounds good. Let me know if I can do anything to help get these live.

**Comment by loudaTW** [comment]
@streisguth 

- Footer Link - Yes, just text link
- Jenkins page - yes, replace current CTA with Test Drive
- Docs - We already have a link here, let's not worry about this for now
