### ISSUE TITLE
Add CTA to Features page

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6461]
> Migrated from [Trello Card 98](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;LlRxc0UE)

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @loudaTW
> Original date: Wed, 15 May 2019 19:46:41 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-15T19%3A46%3A41.687Z)

@streisguth I'd like to officially prioritize this, making it easy for those who want to explore features access to the test drive

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @streisguth
> Original date: Wed, 15 May 2019 19:56:08 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-15T19%3A56%3A08.213Z)

@loudaTW For sure. Let me add @chandrakanth17 to this to let him know it will be next priority. It may be something good for him to pair with Veerababu on.

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @loudaTW
> Original date: Tue, 21 May 2019 20:09:08 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-21T20%3A09%3A08.667Z)

@streisguth @chandrakanth17 Any progress on this?

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @streisguth
> Original date: Tue, 21 May 2019 20:35:59 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-21T20%3A35%3A59.926Z)

@loudaTW We have links/CTA's on the features page already, and can change the text to direct to the Test Drive page.

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @loudaTW
> Original date: Wed, 22 May 2019 02:45:53 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-22T02%3A45%3A53.284Z)

@streisguth This is fine, I just want to ensure we can do that this week

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @chandrakanth17
> Original date: Wed, 22 May 2019 06:25:51 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-22T06%3A25%3A51.705Z)

Should we be adding new CTA or change the text of existing cta ? can I get mockup or more info on this @streisguth @loudaTW

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @streisguth
> Original date: Wed, 22 May 2019 18:08:42 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-22T18%3A08%3A42.464Z)

@chandrakanth17 @loudaTW I don't have a mockup, we can just change the text of one of the exiting CTA's. @loudaTW, should I use the same copy that we used in our campaign, "Test Drive GoCD in 5 Minutes"?

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @loudaTW
> Original date: Wed, 22 May 2019 18:30:47 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-22T18%3A30%3A47.220Z)

@streisguth @chandrakanth17 Please use: "Test drive these GoCD features and more in minutes" 

CTA: Start Now (I honestly don't know what to put here since we usually use Test Drive GoCD as the CTA text), but let's start here.

**Comment by loudaTW** [comment]
@streisguth Can I get an update on when this can happen?
