### ISSUE TITLE
change material for example pipelines

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6469]
> Migrated from [Trello Card 131](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;V3uXFfOS)

Reported on Gitter by trialer in China

I got connection timeouts in my logs, "STDERR: fatal: unable to access 'https://github.com/gocd-demo/demo-configuration/': Failed to connect to github.com port 443: Timed out"

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.6.0 (9306-acdbdcfe5467776f512a338f980598b04735bf3a)
