### ISSUE TITLE
Display pipelines configured by config repo, allow linking to pipeline on dashboard

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6471]
> Migrated from [Trello Card 118](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;HeiRIZ8x)

The config repo widgets should ideally display the pipelines configured by the given CR. This is a common point in both spikes, and probably a much-wanted feature anyway.

## Related

* #6458

## And the PR

* #6360

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @marques-work
> Original date: Wed, 29 May 2019 21:34:35 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-29T21%3A34%3A35.327Z)

@loudaTW FYI

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @marques-work
> Original date: Thu, 30 May 2019 21:30:04 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-05-30T21%3A30%3A04.615Z)

I'm not sure that we can guarantee linking to a pipeline on the dashboard because personalization filters might hide the pipeline. We should think about how to handle this case, or if we still want to link at all.

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @kierarad
> Original date: Wed, 05 Jun 2019 20:18:17 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-06-05T20%3A18%3A17.006Z)

@marques-work would linking to the pipelines page or pipeline history be appropriate? we may want to test this with existing GoCD users

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.6.0 (9370-8e1b89e40fbf882e547888ed7c3ac46226eacc95).


@marques-work 
" Loading pipelines defined by repository…" message doesn't go by itself, I had to refresh the page to display the list of pipelines. 

Also, can we change the text color, as it is hard to identify on that page. 

![Screenshot 2019-06-26 at 14 17 00](https://user-images.githubusercontent.com/6838313/60215721-1b3d8180-981d-11e9-95b5-b14678f1b844.png)

**Comment by marques-work** [comment]
@ankitsri11 interesting - did you receive any errors in the browser? And was this on the first page load, or only after making changes to the config repo? During development, I didn't see that behavior, but I will play with it.

**Comment by ankitsri11** [comment]
@marques-work No, I don't see any error on the browser. This was when I added the repo first time. After refresh or edit, it works fine.

**Comment by marques-work** [comment]
@ankitsri11 ok I have a theory on this that I will validate. Thanks!

**Comment by marques-work** [comment]
@ankitsri11 Can you validate that the issues were fixed by #6593?

**Comment by ankitsri11** [comment]
verified on GoCD Version: 19.6.0 (9473-62f9376120dc55e57f596b09f5e55b216814aecb)
