### ISSUE TITLE
[Bug] - Group admin gets 403 when adding pipeline

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6475]
> Migrated from [Trello Card 130](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;XBzDHkE4)

Steps to recreate:
1 - enable security
2 - create normal user
3 - give admin access to pipeline group
4 - follow link to "Add pipeline" for that group
5 - get 403 Forbidden

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.6.0 (9370-8e1b89e40fbf882e547888ed7c3ac46226eacc95)

@kierarad @marques-work however, pipeline group admin user creating a pipeline with empty template process is inconsistent with creating via the goadmin user. See below:

![pipeline-grp-admin](https://user-images.githubusercontent.com/6838313/60216822-eda60780-981f-11e9-9e70-063bde53e207.gif)

Should allow pipeline group admin user to enable template option similar to below:

![pipeline-grp-admin2](https://user-images.githubusercontent.com/6838313/60217201-08c54700-9821-11e9-8ea1-3564adcb2cc5.gif)

**Comment by kierarad** [comment]
@ankitsri11 ok, I'll take a look

**Comment by kierarad** [comment]
- [ ] Fix Template Toggle - group admin should not receive 403
- [ ] Fix Pipeline Group Dropdown - admin should not receive 403

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.6.0 (9407-ee11f624e4a6cbb4e4979d32ea512dcfe2d1777a)
