### ISSUE TITLE
Can we have a universal add pipeline button? (vs an add pipeline button per group)

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6476]
> Migrated from [Trello Card 40](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;zXPOe6Ux)

## Related

* https://github.com/gocd/gocd/pull/6308

## Attachments

* ![user4.gif](https://raw.githubusercontent.com/gocd/gocd/c65082a0b39ec9e0e5fa5565b0e7a2421487e15d/.github/trello-attachments/8bf518dbef5030b27c617dc89f6be7bb85a21fc6982d6b15008f3489e416fc57/user4.gif)

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @marques-work
> Original date: Sun, 07 Apr 2019 07:18:06 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-04-07T07%3A18%3A06.083Z)

What would the behavior be? Would group selection happen later?

**Comment by gocd-ci-user** [comment]
> Migrated comment original author: @kierarad
> Original date: Tue, 09 Apr 2019 17:49:10 GMT [(show me in my time zone)](https://dencode.com/en/date/ctime?v=2019-04-09T17%3A49%3A10.233Z)

@marques-work yes. right now it just populates the dropdown according to the pipeline group you add from

**Comment by kierarad** [comment]
Closing this as some user research indicates adding pipelines within a specific group seems to be more natural for users
