### ISSUE TITLE
[Bug] Error text not visible completely.

### ISSUE THREAD

**Issue by gocd-ci-user** [gocd/gocd#6477]
> Migrated from [Trello Card 125](https:&#x002f;&#x002f;trello.com&#x002f;c&#x002f;tSRbNl1k)

## Attachments

* ![Screenshot 2019-06-04 at 11.46.26.png](https://raw.githubusercontent.com/gocd/gocd/c65082a0b39ec9e0e5fa5565b0e7a2421487e15d/.github/trello-attachments/fa95654382e28ddcfa13196bab00c0767f2e42b58e72f166988b1d13c1db8c83/Screenshot_2019-06-04_at_11.46.26.png)

**Comment by marques-work** [comment]
Fixed by #6413.

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.6.0 (9304-a6d935eadf5d2307d1ac4a2828b068663a044a04)
