### ISSUE TITLE
Destination folder inside flyweight gets deleted in case a material is specified twice in the config (with and without destination)

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#649]
This has been fixed for git-repos, but not for other scm which get cloned inside fingerprint.

Steps to reproduce
Create 2 pipelines (pipeline A and B), each with material X
Let pipeline B specify destination directory while A does not.
MDU creates a flyweight folder for material X and also creates a destination folder inside it (with code checked out there as well)
Run pipeline A and observe the flyweight folder
 

Expected result
There should not be any destination folder created inside flyweight folder. The purpose of destination folder is only to help out with checkout at the agent side

 

Current result
 

The destination folder gets deleted. As a result when next MDU happens, the code all over gets cloned again in the destination directory

**Comment by mdaliejaz** [comment]
Verified. Works fine on 15.2.0(2012-e6220e7).
