### ISSUE TITLE
Support Multiple Active Directory Domains

### ISSUE THREAD

**Issue by dpmitchell** [gocd/gocd#652]
I'd like to put a request in to add support for multiple Active Directory domains.

I've attempted several times to use a tool called My Virtual Directory but this hasn't been successful for us. There is a lack of community and documentation around this tool.

I've also attempted to point GoCD at the root of our multiple domain tree but this hasn't proved useful either as there is no ability to lookup a domain in the tree via the root.

As a final attempt one of our Java architects reviewed the source and observed that spring allows for multiple domains to be searched, so perhaps this can be achieved natively within the codebase

Having multiple domains could assist teams that have multiple LDAP locations globally and even multiple implementations of LDAP.

Thanks

**Comment by arvindsv** [comment]
Closing this. It's old and all the LDAP related code is moved to https://github.com/gocd/gocd-ldap-authentication-plugin. That's a better place for this.
