### ISSUE TITLE
#381 Incorrect response code when accessing config diff api with incorrect commit SHA

### ISSUE THREAD

**Issue by pravds** [gocd/gocd#654]
Access API
http(s)://<go_server>/go/api/config/diff/<from-commit-SHA>/<to-commit-SHA> with invalid commit SHA and API responds with 500 internal server error.
Pull request #381

**Comment by GaneshSPatil** [comment]
GoCD config listing and diff APIs are internal implementations of how GoCD versions `cruise-config.xml` file.

These config APIs are deprecated (and moved to the `internal` namespace) as part of https://github.com/gocd/gocd/issues/7340 PR

Closing...
