### ISSUE TITLE
GoCD sometimes takes too long to assign agents to jobs

### ISSUE THREAD

**Issue by Diogomrol** [gocd/gocd#6542]
##### Issue Type

- Bug Report / Performance Issue

##### Summary

Sometimes our GoCD Server takes a lot of time to assign agents to jobs, even when the agent is free to pick up new jobs (a lot of time means something between 5 and 10 minutes).

###### Basic environment details

* Go Version: 19.5.0
* JAVA Version: AdoptOpenJDK 11
* OS: Windows Server 2008 R2 (yes I know it's not supported anymore)

###### Additional Environment Details

Support API log attached to this issue.
[supportapiapi.txt](https://github.com/gocd/gocd/files/3291247/supportapiapi.txt)

##### Expected Results
Agent assignment should be much faster.

##### Code snippets/Screenshots

Some evidences:
![ss1](https://user-images.githubusercontent.com/9485620/59520369-b0f21c00-8ec1-11e9-9acf-a5490f049b12.PNG)

![ss2](https://user-images.githubusercontent.com/9485620/59520441-e0088d80-8ec1-11e9-9c59-183393b7fc12.PNG)

If there is any more info I can provide let me know.

To give some more context, our GoCD Server has:
- ~150 pipelines
- ~200 agents
- Machine with 16 cores
- Machine with 32Gb of RAM, of which 16Gb are already allocated to the JVM (we increased this with time after experiencing performance issues).

Cheers

**Comment by Diogomrol** [comment]
Additional information: this is not only happening when assigning agents but also triggering pipelines that depend on other pipelines.

I had a pipeline 'A' that finished at 5:03pm and another one 'B' that depends on 'A' only triggered at 5:13pm (10 minutes later). That pipeline was not running and the agent was free as well.

**Comment by arvindsv** [comment]
Might be good to check a few thread dumps when it is in that state - along with logs, to see if anything shows up. It's strange that it takes that much time. What's showing in the agent logs?

**Comment by Diogomrol** [comment]
Our database already has 8Gb, can the be a problem?

**Comment by Diogomrol** [comment]
I also noticed that we are getting a huge amount of logs that we do not have on other Go Servers we have set up.

These logs are like this:

`2019-07-01 17:19:11,228 DEBUG [qtp2005266429-507967] AgentRegistrationController:113 - Processing '/admin/latest-agent.status' request with values [Agent-Content-MD5:6f80fc817c8375ece0e5806335d1b24d], [Agent-Launcher-Content-MD5:0738b4ad6b9faa0b2ef67069e0684651], [Agent-Plugins-Content-MD5:688b6117a548f82a3882daefb8fccba5], [TFS-SDK-Content-MD5:585d70e41763411de793f87d1d8f65c9]
`

We are having one of these almost on each millisecond. Is this expected @arvindsv ?

**Comment by GaneshSPatil** [comment]
@Diogomrol @arvindsv -- The [above-mentioned](https://github.com/gocd/gocd/issues/6542#issuecomment-507333705) log was added to debug [this](https://github.com/gocd/gocd/issues/4469) particular issue.
As the mentioned issue is fixed, the logline will be removed in upcoming releases of GoCD.

> We are having one of these almost on each millisecond. Is this expected @arvindsv ?

These logs are printed every time an agent checks with the server for agent upgrade information. Each agent pings the server for this information every 5 seconds. Hence these logs are seen every few seconds/milliseconds.

**Comment by Diogomrol** [comment]
Cool, so that shouldn't be the problem here, right? :)

**Comment by arvindsv** [comment]
> Our database already has 8Gb, can that be a problem?

It could be. H2 has limits around its capabilities. But, you'd need to look into the thread dumps to know more.

**Comment by marek130** [comment]
Hi, I have the same problem. How did you fix it? Any hint what to check?

**Comment by chadlwilson** [comment]
it'd probably be better to review more recent issues such as https://github.com/gocd/gocd/issues/11215 and create a new issue that describes your environment, and what you observe from the logs and be specific about what "slow" is to you.

There are many reasons this could be, which vary wildly depending on how you use GoCD including things such as static vs elastic agents, build vs agent resource labelling, GoCD version, custom agents, DB size, db constraints, server constraints, material polling. There is no single fix possible without context, and there may be things that need improving in the code, but need specific information to suggest what is worth trying.

**Comment by marek130** [comment]
@chadlwilson thanks I created #14546
