### ISSUE TITLE
Build tries to unload artifacts but its failing to do so

### ISSUE THREAD

**Issue by pratheshcentrica** [gocd/gocd#6543]
my pipeline tries to upload two files:
It uploads txt files but fails to upload ear file to Go artifacts.

on checking logs its show http 201 status code while uploading  txt file and http 500 status code while uploading ear.tar file 
ear.tar file is 400Mb and txt files is in KB

We use GO 14.2 and JDK 6

can someone help me out resolving this as it fails for just on ear.tar with same artifact path, same permissions etc

Please find the console logs:

[go] Start to upload EAR/2337/ear_build/2/ear_build on ph1246102.ams20.vzbi.caas [/customer/product/go/go-agent34] at Fri Jun 14 17:44:28 CEST 2019

[go] Uploading artifacts from /customer/product/go/go-agent34/pipelines/EAR/bgr.ear.tar to artifacts

[go] Failed to upload /customer/product/go/go-agent34/pipelines/EAR/bgr.ear.tar

[go] Uploading artifacts from /customer/product/go/go-agent34/pipelines/EAR/bgr.ear.tar to artifacts

[go] Failed to upload /customer/product/go/go-agent34/pipelines/EAR/bgr.ear.tar

[go] Uploading artifacts from /customer/product/go/go-agent34/pipelines/EAR/bgr.ear.tar to artifacts

[go] Failed to upload /customer/product/go/go-agent34/pipelines/EAR/bgr.ear.tar

[go] Uploading artifacts from /customer/product/go/go-agent34/pipelines/EAR/build_summary_bgr.txt to artifacts

[go] Uploading finished. Failed to upload [bgr.ear.tar]

**Comment by arvindsv** [comment]
This GoCD version is way too old. It's over 5 years old. Closing this issue. Please upgrade it to a community-supported 19.x version and check if it still happens. Thank you!
