### ISSUE TITLE
Config Repo doesn't support private submodules

### ISSUE THREAD

**Issue by twjjwxzq** [gocd/gocd#6546]
##### Issue Type

- Bug Report
- Feature enhancement

##### Summary

GoCD fails to parse a config repo with submodules that point to private remote repositories.

##### Environment
GoCD 19.5.0 running on Minikube cluster

###### Basic environment details

* Go Version: `19.5.0`
* JAVA Version: `1.8.0_212`
* OS: `Linux 4.15.0`

##### Steps to Reproduce

1.  Create a repo `root_repo` with a `pipeline.yml` file
2. Create another repo `sub_repo` and add it as a submodule to `root_repo`. Point the remote of `sub_repo` to a private repository.
3. Add `root_repo` as a config repo in GoCD
4. Error message shows: "This configuration repository was never parsed"

##### Expected Results

GoCD attempts to use the same credentials for cloning to root repo to clone the submodules as well, and shows a more descriptive error message on failure.

##### Actual Results

GoCD shows the following error message: "This configuration repository was never parsed"

And the GoCD Server logs show the following:
```
STDERR: Failed to clone 'root_repo/sub_repo'. Retry scheduled
STDERR: Cloning into '/go-working-dir/pipelines/flyweight/6bbfc89c-878e-491f-9c7b-6c38f7d975e8/root_repo/sub_repo'...
STDERR: Host key verification failed.
STDERR: fatal: Could not read from remote repository.
STDERR:
STDERR: Please make sure you have the correct access rights
STDERR: and the repository exists.
STDERR: fatal: clone of 'git@github.com:user/sub_repo.git' into submodule path '/go-working-dir/pipelines/flyweight/6bbfc89c-878e-491f-9c7b-6c38f7d975e8/root_repo/sub_repo' failed
STDERR: Failed to clone 'root_repo/sub_repo' a second time, aborting
```

##### Possible Fix

In my case, I didn't actually need GoCD to try and clone the submodules to find any pipeline configuration files. It would be good to have an option to tell GoCD to ignore checking out of submodules (similar to #6390). If not, could GoCD try cloning submodules with the same credentials as given to the root_repo? Or could there be a way to specify credentials for each of the submodules? At the minimum, could a more helpful error message be displayed on the UI on why the config repo could not be parsed?

**Comment by arvindsv** [comment]
The part about config repo and submodules is discussed in #6390 as @twjjwxzq said. However, I wonder if @akshaydewan or @ketan have any thoughts about the credentials question.
