### ISSUE TITLE
Remove rails based pluggable scm API

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6560]
Pluggable scm api exists in both rails and spark.
Remove rails based API as spark based API is stable.

**Comment by GaneshSPatil** [comment]
This issue can be picked up after #6558 and #6559 is merged.
As few representers are shared across these 3 APIs.

**Comment by kritika-singh3** [comment]
Fixed in https://github.com/gocd/gocd/pull/6702
