### ISSUE TITLE
GoCD console logs not visible

### ISSUE THREAD

**Issue by ckaushik** [gocd/gocd#6563]
##### Issue Type

Bug Report

##### Summary

GoCD server is not showing console logs for some jobs. The raw output is showing the logs

##### Environment

```
"Go Server Information": {
    "Version": "19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600)"
 }
```

###### Basic environment details

* Go Version: `19.3.0 (8959-259d1f79e361875995072e5c1fcc9cbda7ccc600).`
* JAVA Version: `1.8.0_201`
* OS: `Linux 4.4.0-1054-aws`
* Browser vendor and version (if relevant): `Version 74.0.3729.169 (Official Build) (64-bit)`

###### Additional Environment Details

Running on Kubernetes

##### Steps to Reproduce

1. Open the pipeline build details page https://<go-server-url>/go/tab/build/detail/<pipeline-name>/2/build/1/build

##### Expected Results

Expect the console logs to be visible in the browser 

##### Actual Results

See an blank console
See 404 errors on inspection 

##### Possible Fix

Test the javascript code against browser version specified?

##### Code snippets/Screenshots

Inspection of API calls from browser
![GoCD 404](https://user-images.githubusercontent.com/513388/59904706-dd59eb00-9421-11e9-9da0-7d90716598b8.png)

Blank screen indefinitely
![GoCD 404 2](https://user-images.githubusercontent.com/513388/59904713-e2b73580-9421-11e9-874a-34372b44af8e.png)

Raw output API is passing
![GoCD 404 3](https://user-images.githubusercontent.com/513388/59904721-e8148000-9421-11e9-9254-8c6ff79032d3.png)

##### Any other info

Some developers are able to see this consistently, while some are not able to see it at all
This leads me to believe it's either a permission issue or a browser version issue

**Comment by GaneshSPatil** [comment]
Hello @ckaushik 

The XHR request failure for `messages.json` is safe to ignore as it is was a redundant API call removed in subsequent versions of GoCD.

As the `console.log` request returned 200. can you check the contents of the response? does the response body contains the raw console log? or it was empty?

Also, can you check the `console.log` artifact generated by the job to verify if it contains any logs?
The console.log file can be found at tab `Artifacts > cruise-output > console.log`

> Some developers are able to see this consistently, while some are not able to see it at all

can we verify whether the `console.log` artifact and `console.log` API request returns the same response contents for both the users?

---

Also, can you try opening the same page in incognito mode with all browser extensions disabled? Many times we've observed that the browser extensions restricts the logs from being rendered on the screen.

**Comment by ckaushik** [comment]
Thanks @GaneshSPatil the console logs had text that matches "adtech" which was blocked by some browser extensions. Sorry I should have checked this first
