### ISSUE TITLE
Order pipeline group names in alphabetical order when cloning a pipeline

### ISSUE THREAD

**Issue by ryudice** [gocd/gocd#6567]
##### Issue Type

- Bug Report

##### Summary

Order Pipeline group names in alphabetical order when cloning a new pipeline.

We have a lot of grups and it seems they are shown in order of creation at the moment.

![image](https://user-images.githubusercontent.com/125211/59928980-1b90e380-93fd-11e9-81a9-fba60c839760.png)

###### Basic environment details

* Go Version: `19.3.0`

##### Steps to Reproduce

1. Clone a pipeline
2. 
3. 
4. 

##### Expected Results

The dropdown in the picture should order group names by alphabetical order so that they are easy to find

![image](https://user-images.githubusercontent.com/125211/59929087-5135cc80-93fd-11e9-8b0e-b3b2af37c367.png)

##### Actual Results
They seem to be order by creation time.

**Comment by viraj2712** [comment]
As we are ordering pipeline groups alphabetically while cloning the pipeline, should we make it consistent for `Move to` as well?

![Screenshot 2019-06-27 at 4 42 06 PM](https://user-images.githubusercontent.com/34642373/60261882-86a95100-98fa-11e9-91ba-3b02ff496ebb.png)

\cc: @maheshp @bdpiparva @ketan

**Comment by ketan** [comment]
Makes sense to me. Please make sure it is ordered in a case insensitive
manner.

**Comment by kritika-singh3** [comment]
Fixed in https://github.com/gocd/gocd/pull/6577 as a part of GoCD version 19.6.0

**Comment by chadlwilson** [comment]
Should this have changed the pipeline group ordering when viewing on the Dashboard, or just in config drop-down lists?

The ordering on the dashboard seems to be creation time, which is largely beyond one's control when using config repositories to import an existing set. You don't even seem to be able to change it in a custom View :(
