### ISSUE TITLE
New create pipeline SPA: Group admins are not allowed to create a pipeline.

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#6572]
##### Issue Type

- Bug Report

##### Summary

The new spa for creating a pipeline is using `pipeline_groups` api to list to available groups for the given user, and api access is currently restricted to admin only.

https://github.com/gocd/gocd/blob/e9c8c0285c00f7dd91933f504358c24513dbc242/api/api-pipeline-groups-v1/src/main/java/com/thoughtworks/go/apiv1/admin/pipelinegroups/PipelineGroupsControllerV1.java#L77

The API should not be restricted to `admin` or `group_admin`, ideally, we should be check for logged in user a valid user(`non-anonymous`) and let index call decide which are the pipeline groups for which a user have admin access. Same is also true for the `templates` api.

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.6.0 (9515-4b674c10941b6c27d7ec2a28dd946518d9211b7a)

Also here: https://github.com/gocd/gocd/issues/6475
