### ISSUE TITLE
Dashboard UI - Animation for building not used on failing status

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#6574]
##### Issue Type

- Bug Report

##### Summary

This PR https://github.com/gocd/gocd/pull/6225 took care of animation for stage in `Building` state, however animation is not present for stage `Failing` state. During a stage in failing state the stage bar looks like this

<img width="348" alt="Screen Shot 2019-06-25 at 10 52 30 AM" src="https://user-images.githubusercontent.com/6533924/60071520-ff13e480-9737-11e9-84c7-45d49d918ff0.png">

###### Basic environment details

* Go Version: `19.6.0 (9344-6987358321d7fcf55fac95d0d4663074918541b9)`

**Comment by naveenbhaskar** [comment]
will look into this

**Comment by bdpiparva** [comment]
Also, svg animation looks little sluggish see the attached gif. 

![svg-animation](https://user-images.githubusercontent.com/7871209/60080989-8d936080-974e-11e9-89fb-eaca076ec970.gif)

**Comment by bdpiparva** [comment]
@naveenbhaskar - any update on this?

**Comment by naveenbhaskar** [comment]
Not done yet.. need to spend some time fine tuning the animation.

**Comment by adityasood** [comment]
Fixed in https://github.com/gocd/gocd/pull/6638
