### ISSUE TITLE
Pipeline group passed as null during check connection on new pipeline flow(old page) for group admin user

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#6585]
##### Issue Type

- Bug Report

##### Summary

Group Admin can create the pipeline on old pipeline creation flow, but during check connection 
pipeline group is passed as `null`

###### Basic environment details

* Go Version: `19.6.0 (9384-e1464b0ed2b744bf8ce189a4eff53cbc0480dcb4)`

##### Steps to Reproduce

1. Start a server with an admin and a group admin user setup
2. Create secret configuration with allow all rule
3. Login as group admin user
4. Try creating a pipeline - use secret param for material password
5. Try check connection

##### Expected Results

Check connection should be successful

##### Actual Results

Check connection fails with error `Material with url: 'https://go-tfs-user.visualstudio.com' in Pipeline Group: 'null' does not have permission to refer to secrets using secret config 'prod-pwd'`

**Comment by bdpiparva** [comment]
@rajiesh - I think the issue is the same as https://github.com/gocd/gocd/issues/6572, Can you verify and close either one of the issue.

**Comment by rajiesh** [comment]
Verified on 19.6.0 (9438-bec8bc92121ef301fc489aa3badc5fe4e9b686fd)
