### ISSUE TITLE
Allow validating and understanding cron expressions

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#6595]
##### Issue Type

- Feature enhancement

##### Summary

The cron syntax validation simply tells if the expression is syntactically valid. However, the [quartz cron expression](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html) varies quite significantly from the [unix cron expression](https://linux.die.net/man/5/crontab) to the point where one may not be sure if the cron will trigger at the time when the user actually expects.

I was thinking of providing some feedback about the cron expression by providing one of the two hints to users (I'm unsure which one is better):

1. Tell the DateTime when the next few triggers will happen. For example, the expression`0 15 10 ? * *` will show up as `3rd July, 2019 at 10:15:00, 4th July, 2019 at 10:15:00, ....`.
2. Convert the cron expression to a human readable format. For example, the expression `0 15 10 ? * *` will show as `10:15 am everyday`.

The second option is probably better suited, IMO. But I'm eager to her other opinions.

**Comment by arvindsv** [comment]
The cron expression can get quite complicated as mentioned in [the documentation page you linked to](http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html):

```
0/5 14,18,3-39,52 * ? JAN,MAR,SEP MON-FRI 2002-2010
```

Next few triggers seems like they'll always be right. Showing a human-readable format for this kind of an expression might be very tricky (and confusing). I don't mind it as an option which works well in simple cases.

**Comment by ketan** [comment]
The expression is described by the library as`0/5 14,18,3-39,52 * ? JAN,MAR,SEP MON-FRI 2002-2010` => `Every 5 seconds, at 14, 18, minutes 03 through 39 past the hour and 52 minutes past the hour, Monday through Friday, only in January, March and September, 2002 through 2010`

A few specific timestamps may not tell the whole story about this expression.

**Comment by arvindsv** [comment]
Ok, makes sense if it can take care of it, as you showed.

**Comment by driv** [comment]
Having the next execution timestamp makes spotting errors extremely simple, since in most cases when you're writing these expressions you know when you want it to run.
Could we have both?
