### ISSUE TITLE
Check Material button and result components

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#6613]
See flow 2 prototype: https://thoughtworks-products.invisionapp.com/share/25SOQYDCDFW#/screens

Likely depends on #6611.

As part of the PaC add pipeline page, we need a component similar to `<TestConnection/>` that checks PaC definitions and returns a list of matching files.

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.9.0 (9929-91f828d47612be57eeb28377e7c3ca6206b8d992).

![Screenshot 2019-09-11 at 11 11 44](https://user-images.githubusercontent.com/6838313/64723273-120b9a80-d485-11e9-9404-f1068581479f.png)
