### ISSUE TITLE
Feature: allow us to pass "latest" api versions rather than specific versions.

### ISSUE THREAD

**Issue by childsc** [gocd/gocd#6620]
##### Issue Type
- Feature enhancement

##### Summary

As the use of the APIs are becoming more and more prevalent in the area of Automation. 

Can we have a way of requesting the "latest"  api version in our calls?

We have a number of calls to GoCD from other applications and it can be hard to know where to update the code.  Most of the time the changes do not affect the calls themselves, just version number.

###### Basic environment details

Go Server Version: | 19.5.0 (9272-496bf8b95e603c1f3980ae59042bc559eecbbbc0)
JVM version: | 11.0.1
OS Information: | Linux 3.13.0-147-generic

##### Steps to Reproduce

N/A
##### Expected Results
to be able to pass a "latest" flag to be sure to get just the latest API.

##### Actual Results
When an API is updated we need to update all reference. But we may not get them all as there are lots of teams connecting to our instance.

##### Possible Fix
The option to pass either the version number in the header or something like below:Accept: application/vnd.go.cd.vlatest+json

**Comment by ketan** [comment]
I'm attempting an implementation of this, and here's what it looks like (notice how the version is omitted in the `Accept` header):

```
$ curl http://localhost:8153/go/api/config/mailserver \
    -H 'Accept: application/vnd.go.cd+json' -i
```

```
HTTP/1.1 200 OK
Content-Type: application/vnd.go.cd.v1+json;charset=utf-8

{/*some json/*}
```

I have a couple of open questions, and I'd like to hear a few opinions about this:

- What should be the `Content-Type` in such a situation where the `Accept` header specifies `application/vnd.go.cd+json`. I'd assume it should be `application/vnd.go.cd+json`?
- Should we support `Accept: application/json` for content type negotiation?
- Should we support `Accept: */*` for content type negotiation? (Note that this will be a superset of `application/json`, so if we support this, then `application/json` will be redundant)

**Comment by jlusiardi** [comment]
For my 5 cents, lets have a look at `GET /go/api/agents`:

For 19.7.0 the content type is `application/vnd.go.cd.v5+json`. So for some older version it will be something in between `application/vnd.go.cd.v1+json` and `application/vnd.go.cd.v5+json`. A client library is unable to determine which is the correct content type for a special server unless it has a mapping of server versions to content types for every endpoint. 

What about the following proposal for future server versions: 
Have the API accept a version-less content type like `application/vnd.go.cd+json` for any `GET` request. In the response, the `Content-Type` header should signal the Version the server expects and the library then knows what to use for any other request on the endpoint.

E.g. if I would like to update and agent:

1. Get the list of agents with `Accept: application/vnd.go.cd+json`
2. Evaluate the `Content-Type` Header from the response and handle the json from the body accordingly to that content type
3. Compute the stuff to update and perform the `PATCH` operation with the proper `ACCEPT` Header with version

**Comment by arvindsv** [comment]
> What about the following proposal for future server versions:
> Have the API accept a version-less content type like application/vnd.go.cd+json for any GET request. In the response, the Content-Type header should signal the Version the server expects and the library then knows what to use for any other request on the endpoint.

Is that the same as the example @ketan mentioned above, or is it different?

**Comment by jlusiardi** [comment]
You are right, more or less the same. I just wanted to point out, that IMHO:

- GET should support version-less requests
- GET replies with a version 
- all others requests (POST, PUT, PATCH, ...) should require a specific version (which should be the same as the response from the GET had)

This wasn't clear to me to be in @ketan proposal. 

And if the decision will be to support `Accept: */* `, may be do not require the header at all?

**Comment by ketan** [comment]
> - all others requests (POST, PUT, PATCH, ...) should require a specific version (which should be the same as the response from the GET had)

That's an interesting take. Thanks.

> This wasn't clear to me to be in @ketan proposal.

Intentionally so. I was trying to avoid possible confirmation bias :)

> And if the decision will be to support `Accept: */* `, may be do not require the header at all?

Yes. It appears that most clients send that header.

**Comment by maheshp** [comment]
Reopening for testing.

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9912-33898b3adaf72cedea1604882d3554fd586571a8)
