### ISSUE TITLE
RPM installer upgrade fails on docker distributions

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6622]
##### Issue Type

- Bug Report

##### Summary

Installer upgrade from `19.5.0` to `19.6.0` fails on docker based distributions such as `centos-6`, `centos-7`.

**Comment by GaneshSPatil** [comment]
#### Technical description of the bug:

* On centos docker images `systemctl` or `upstart` is not available (by default), so the only way to install packages is by using 'init.d'.


#### RPM package upgrade scneario has following scriptlets (in the same order as they are mentioned) with their intended purpose:

- `pre-transaction`: pre-upgrade setup (if any).
- `pre-install`    : pre-install script of the newer version installation.
- `post-install`   : post-installa script of the newer version installation.
- `pre-uninstall`  : pre-uninstall script of the older version installation.
- `post-uninstall` : post-uninstall script of the older version installation.
- `post-transaction`: pre-upgrade setup (if any).


* In case of GoCD upgrade from `19.5.0` from `19.6.0` it would install `19.6.0` GoCD and later try removing `19.5.0` version. The `19.5.0` version's `post-uninstall` script does not have a version check and thus, end up removing the `19.6.0` version's files too.

* This particular issue is caused due to using `init.d` as the installation mechanism and the order of rpm scriptlet executions.

---

#### Possible fix:

##### Possible fix 1:

* Use `post-transaction` script to perform upgrade. As the post transaction script is not intented to use for installations/upgrades, this might not be the ideal solution.

##### Possible fix 2:

* Install/Upgrade GoCD as part of `post-install` scriptlet and create a copy of the newer installation. This copy can be restored back as part of `post-transaction` scriptlet, (after `post-uninstall` script).

**Comment by rajiesh** [comment]
Verified by this run - https://build.gocd.org/go/pipelines/installer-tests/970/install-tests/1
