### ISSUE TITLE
GoCD 19.5.0 API does not work as expected for GET /go/api/admin/packages

### ISSUE THREAD

**Issue by jlusiardi** [gocd/gocd#6628]
##### Issue Type

Bug Report

##### Summary

When I try to use the API to get the lists all available packages via `/go/api/admin/packages` the server just gives back an error 500. Exact curl call to test instance:
`curl -k 'https://127.0.0.1:8154/go/api/admin/packages' -u 'admin:admin' -H 'Accept:application/vnd.go.cd.v1+json' -v`

There are no packages defined yet, so i'd expect an empty list.

##### Environment

See https://gist.github.com/jlusiardi/d7846e8dd514f08e900c1da79525c9bb

##### Logs 

See https://gist.github.com/jlusiardi/239563b6864c03fe6b1d64aa7fbafb43

##### Actual Results
Curl returns:
```plain
< HTTP/1.1 500 Server Error
< Date: Tue, 16 Jul 2019 11:33:28 GMT
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-UA-Compatible: chrome=1
< Set-Cookie: JSESSIONID=node019uyvzn8btcn715uf2zs4i2ggx246.node0;Path=/go;Expires=Tue, 30-Jul-2019 11:33:28 GMT;Max-Age=1209600;Secure;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: JSESSIONID=node0aa6g59imyx5i9ddv356c1356247.node0;Path=/go;Expires=Tue, 30-Jul-2019 11:33:28 GMT;Max-Age=1209600;Secure;HttpOnly
< Content-Type: text/html;charset=utf-8
< X-Request-Id: abd81939-6721-46b2-8b8c-b626bade1528
< X-Runtime: 0.048899
< Content-Length: 1635
< 
...

<body class="rails-default-error-page">
  <!-- This file lives in public/500.html -->
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>
```

**Comment by GaneshSPatil** [comment]
This issue was introduced due to https://github.com/gocd/gocd/pull/6345

**Comment by rajiesh** [comment]
Verified on 19.6.0 (9514-9c53ca489c975cd17a5c90a0327855e1e0b436bb)

**Comment by jlusiardi** [comment]
Confirmed to work on 19.6.0
