### ISSUE TITLE
GoCD 19.5.0 API does not work as expected for GET /go/api/admin/repositories

### ISSUE THREAD

**Issue by jlusiardi** [gocd/gocd#6630]
##### Issue Type

Bug Report

##### Summary

When I try to use the API to get the lists all available packages via `/go/api/admin/repositories` the server just gives back an error 500. Exact curl call to test instance:
`curl 'http://127.0.0.1:8153/go/api/admin/repositories'  -u 'admin:admin' -H 'Accept:application/vnd.go.cd.v1+json'`

There are is one repository defined, so i'd expect a non empty list.

##### Environment

See https://gist.github.com/jlusiardi/d7846e8dd514f08e900c1da79525c9bb

##### Logs 

See https://gist.github.com/jlusiardi/93fd88a9ad855e2ce3f654a076f03c0e

##### Actual Results
Curl returns:
```plain
< HTTP/1.1 500 Server Error
< Date: Tue, 16 Jul 2019 12:46:58 GMT
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-UA-Compatible: chrome=1
< Set-Cookie: JSESSIONID=node0lalnsu8t791nvltprsqt5mnt305.node0;Path=/go;Expires=Tue, 30-Jul-2019 12:46:58 GMT;Max-Age=1209600;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Set-Cookie: JSESSIONID=node08mffh84jvjld1tfkzexwb8l7j306.node0;Path=/go;Expires=Tue, 30-Jul-2019 12:46:58 GMT;Max-Age=1209600;HttpOnly
< Content-Type: text/html;charset=utf-8
< X-Request-Id: 2c0a3ee2-91f5-4b10-a035-7d6b1740fd9e
< X-Runtime: 0.055764
< Content-Length: 1635
< 
<!DOCTYPE html>
<html>

...

<body class="rails-default-error-page">
  <!-- This file lives in public/500.html -->
  <div class="dialog">
    <div>
      <h1>We're sorry, but something went wrong.</h1>
    </div>
    <p>If you are the application owner check the logs for more information.</p>
  </div>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by GaneshSPatil** [comment]
This issue was introduced due to https://github.com/gocd/gocd/pull/6345

**Comment by jlusiardi** [comment]
Confirmed to work on 19.6.0
