### ISSUE TITLE
GoCD 19.5.0 API does not work as expected for GET /go/api/admin/plugin_settings/:id

### ISSUE THREAD

**Issue by jlusiardi** [gocd/gocd#6631]
##### Issue Type

Bug Report

##### Summary

performing `curl 'http://127.0.0.1:8153/go/api/admin/plugin_info/json.config.plugin' -u 'admin:admin' -H 'Accept: application/vnd.go.cd.v5+json'` returns a json object as expected. So I assume `json.config.plugin` is an ID. Now performing `curl 'http://127.0.0.1:8153/go/api/admin/plugin_settings/json.config.plugin' -u 'admin:admin' -H 'Accept: application/vnd.go.cd.v1+json' -i` I just get `{
  "message" : "Plugin settings with id 'json.config.plugin' was not found!"
}` (I'd expect there to be settings because in the Web UI there are two fields)

##### Environment

See https://gist.github.com/jlusiardi/d7846e8dd514f08e900c1da79525c9bb

##### Logs 

No logs are produced.

##### Actual Results
Curl returns:
```plain
Date: Tue, 16 Jul 2019 12:59:44 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: chrome=1
Set-Cookie: JSESSIONID=node02z2dn0coyew11scysp1lwjc37353.node0;Path=/go;Expires=Tue, 30-Jul-2019 12:59:44 GMT;Max-Age=1209600;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Set-Cookie: JSESSIONID=node01ho50ggw8abf31pe69pt9lae88354.node0;Path=/go;Expires=Tue, 30-Jul-2019 12:59:44 GMT;Max-Age=1209600;HttpOnly
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/vnd.go.cd.v1+json;charset=utf-8
X-Runtime: 1
Transfer-Encoding: chunked

{
  "message" : "Plugin settings with id 'json.config.plugin' was not found!"
}
```

**Comment by GaneshSPatil** [comment]
@jlusiardi -- Did you configure the plugin settings for the 'json.config.plugin' plugin (either from the UI or through the API)?

**Comment by jlusiardi** [comment]
@GaneshSPatil After setting values in the WebUI it returns an object:
```json
{
  "_links" : {
    "self" : {
      "href" : "http://127.0.0.1:8153/go/api/admin/plugin_settings/json.config.plugin"
    },
    "doc" : {
      "href" : "https://api.gocd.org/19.5.0/#plugin-settings"
    },
    "find" : {
      "href" : "http://127.0.0.1:8153/go/api/admin/plugin_settings/:plugin_id"
    }
  },
  "plugin_id" : "json.config.plugin",
  "configuration" : [ {
    "key" : "environment_pattern",
    "value" : "**/*.goenvironment.json"
  }, {
    "key" : "pipeline_pattern",
    "value" : "**/*.gopipeline.json"
  } ]
}
```

I would never the less expect an object without values.

**Comment by ketan** [comment]
@jlusiardi: since there are no settings to show, it returns a 404, as designed.

**Comment by jlusiardi** [comment]
@ketan: sorry to differ:

- how can one find out what fields there are configurable for a plugin?
- If i fill the fields and save, and clear the fields and save, an object is returned with keys but no values.

Perhaps at least enhance the documentation to describe this behaviour?

**Comment by ketan** [comment]
> Perhaps at least enhance the documentation to describe this behaviour?

Reopening

**Comment by jlusiardi** [comment]
As a proposal: https://github.com/gocd/api.go.cd/pull/364

**Comment by GaneshSPatil** [comment]
The expected behavior of the GoCD server WRT Plugin Settings API has been documented at https://api.gocd.org/current/#plugin-settings.

Fixed as part of https://github.com/gocd/api.go.cd/pull/364. Closing...

Many Thanks @jlusiardi !!
