### ISSUE TITLE
Removing all existing resource association from agent should not be allowed in agent patch update V5 API

### ISSUE THREAD

**Issue by msaurabh1978** [gocd/gocd#6645]
**Issue Type**
Bug Report

**Summary**
Agent Patch update API V5 allows resources to be removed from agents but does not allow environments to be removed from agents.

**Basic environment details**
Go Version: 19.6.0

**Steps to Reproduce**
Send Patch agent update request to v5 agent API using following JSON payload,

{
	"hostname": "testing.agentupdate.com",
	"agent_config_state": "Enabled",
	"resources": [],
	"environments": ["e1"]
}

Then existing resources associated with an agent are removed. but if u pass following JSON payload 

{
	"hostname": "testing.agentupdate.com",
	"agent_config_state": "Enabled",
	"resources": ["r1"],
	"environments": []
}
Then 422 (Unprocessable entity) error code is returned with the error message "Updating agent failed" and "Environment [] does not exist."

**Expected Results**
Since this is a Patch agent update request, either resources or environments should not be allowed to be removed by specifying an empty list.

**Actual Results**
Existing resources are removed when an empty list of resources is specified

**Comment by kritika-singh3** [comment]
What if I want to remove all the resources associated with that agent? I think an empty list should be supported for resources as well as environments.

WDYT @gocd/godev

**Comment by maheshp** [comment]
> Since this is a Patch agent update request, either resources or environments should not be allowed to be removed by specifying an empty list.

If its not allowed, how can an agent be updated to remove either the resources or environments?

**Comment by msaurabh1978** [comment]
When we (@Ketan and I) discussed this issue, we talked about inconsistencies between how resources were allowed to be removed completely but that is not the case with environments. We thought then that we should not allow completely removing resources and environments both. 

But on reconsideration, I am also inclined towards supporting it.

**Comment by maheshp** [comment]
It was decided to allow patch to take an empty array/string for both `resources` and `environments`. An empty array/string would basically remove all `resources` and `environments`. This will be available as part of Agents API v6 done as part of Moving agents outside PR #6627 

Closing this issue.
