### ISSUE TITLE
Jobs of all stages of the pipeline “docs.gocd.org-master” on build.gocd.org fails to run using elastic profile “azure-plugin-ubuntu-with-ruby”

### ISSUE THREAD

**Issue by msaurabh1978** [gocd/gocd#6646]
**Issue Type**
Bug Report

**Summary**
When jobs of the stages of the pipeline `docs.gocd.org-master` are configured to use elastic profile `azure-plugin-ubuntu-with-ruby`, then agents created by azure plugin are not registered and hence not assigned (not available) to the jobs of pipeline `docs.gocd.org-master`.

**Steps to Reproduce**
- Configure jobs of stages of the pipeline `docs.gocd.org-master` to use elastic profile `azure-plugin-ubuntu-with-ruby`
- Trigger the pipeline. 
- Notice that the job does not run because there are no agents available to be assigned for the job

**Expected Results**
The mentioned pipeline should run successfully with the mentioned elastic profile.

**Actual Results**
Agents are created by the azure plugin but they are not getting registered and hence not assigned (not available) to the jobs of pipeline `docs.gocd.org-master`.

**Comment by adityasood** [comment]
This was probably an issue with agent registration time out. Currently, all docs pipelines run with this profile. Closing this as this does not appear to be an issue.
