### ISSUE TITLE
Remove toggle for new add pipeline flow -- make this the new prod experience

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#6651]
This also entails removing the old flow.

**Comment by marques-work** [comment]
@ankitsri11 this is now merged, and I don't _think_ there should be any issues. Do you think you can do a quick run-through to make sure this didn't break anything once it's deployed to build.gocd.org? I did a check locally, but I may have missed things that you might think to check.

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.7.0 (9541-99e90542625bb808f8195c6f2f3cb1ca5014a733)
