### ISSUE TITLE
Add message to authorization page

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#6663]
Currently, for a fresh installation, the auth page is empty and doesn't have any guidelines on the setup. It is good to have something like below:

![Screenshot 2019-07-23 at 12 03 39](https://user-images.githubusercontent.com/6838313/61739879-3333f280-ad42-11e9-9cdc-1434e2dd932e.png)

```
<div class="index__tips___2K8la">
<ul data-test-id="auth-config-info">
<li>Click on "Add" to add new auth configuration.</li>
<li>An auth configuration can be used to setup user authorization.</li>
</ul>
</div>
```

**Comment by kritika-singh3** [comment]
Should we also add a link to GoCD [documentation](https://docs.gocd.org/current/configuration/dev_authentication.html) ?

**Comment by rajiesh** [comment]
Verified on 19.11.0 (10683-fc7710d5f3ada94af6cce76a704b224f79a86cf7)
