### ISSUE TITLE
[Bug] How to handle the pipeline group selector when no pipeline groups exist

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#6665]
## For context, see convo summary:

> ketanpkr: the new pipeline wizard does not allow work as expected if there are no pipeline groups present. it asks you to select an existing pipeline group (which does not exist). Someone mind taking a look?
>
> marques: ketanpkr I can look
>
> ketanpkr: thanks, I don’t know if creating pipeline groups should be in scope.
>
> ...blah blah blah... until:
>
> marques: ketanpkr for now, the easiest thing would be to just set it to `defaultGroup` without allowing the user to change it. we will prob have to discuss what the appropriate UX is for it otherwise
>
> marques: Just pushed a fix

## So, currently we fallback to a hardcoded value. Things to consider for a long-term fix

- The old flow allowed a freeform entry for the name of a pipeline group. It would prepopulate with the group name from the page URL, but one could modify it to an arbitrary value if so desired. If a group of that name didn't exist, GoCD silently created it for you.
- Do we want similar behavior? The implication is that users could create new groups from this page. Is this a concept we want?
- Or is the band-aid we have in place all that we need?

**Comment by kritika-singh3** [comment]
@marques-work ping!

**Comment by marques-work** [comment]
@kritika-singh3 hey there - is there something we should discuss with regards to this special case with the pipeline group selector?

**Comment by kritika-singh3** [comment]
@marques-work Just wanted to know if there is something that needs to be done for this. Seems like it has been left idle for a long time.

**Comment by marques-work** [comment]
@kritika-singh3 I don't think so at this point unless someone complains about its behavior. I'll close this.
