### ISSUE TITLE
Environments Get API does not honor If-None-Match header

### ISSUE THREAD

**Issue by SnehaPL** [gocd/gocd#6682]
##### Issue Type

- Bug Report

##### Summary

Environments Get API should return 304 (Not Modified) when appropriate  If-None-Match header is specified.

###### Basic environment details

* Go Version: 19.7.0 (9552-aa833fbf095e66489c765751dfa23daa741c35b4)
* JAVA Version: 1.8.0_211
* OS: Mac OS X 10.14.6

##### Expected Results
Environments Get API should return 304 (Not Modified) when appropriate  If-None-Match header is specified.

##### Actual Results
Environments Get API return 200 (Ok) when appropriate  If-None-Match header is specified.

**Comment by GaneshSPatil** [comment]
Fixed as part of #6683

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9746-6bbad2a99f2a38bfc31210777c22d9bfda941e68)
