### ISSUE TITLE
Not able to add tasks in a job.

### ISSUE THREAD

**Issue by erIamshivani** [gocd/gocd#6686]
Hi,
Since I upgraded GoCD to 19.6.0, I am facing this issue. When I try to add tasks in a job, an error is displayed as `The change you wanted was rejected.` you can find the screenshot [here](https://drive.google.com/file/d/1Q_laoMYqjnw3iEpfn8h8iL8ueWmi6Ty6/view?usp=sharing). I checked the logs, but it has no mention about this error. 

Any idea why this error is rising?

**Comment by adityasood** [comment]
@erIamshivani can you try this in an incognito browser window?

**Comment by erIamshivani** [comment]
@adityasood 
Hey it worked in incognito mode! Also, it worked in Mozilla.
But may I know the reason behind this behaviour?

**Comment by adityasood** [comment]
@erIamshivani is this issue reproducible on a browser? If yes, can you share the steps you took? 

Please also share the browser version and names of any browser extensions you have added.

**Comment by erIamshivani** [comment]
@adityasood 
First, the steps I took:

1. Started my go-server
2. Started go-agent
3. On browser, I accessed the URL: <my_ip_address>:8153. Dashboard opened.
4. For my existing pipeline, I tried to add a task in existing job of existing stage. I got the error mentioned before, screenshot is [here](https://drive.google.com/file/d/1Q_laoMYqjnw3iEpfn8h8iL8ueWmi6Ty6/view).

About Browsers:
I tried same steps on 
1. **Chromium** - Version 75.0.3770.142. 
    (Normal Mode - Error, Incognito - Worked!) Extensions - Hangouts. 
2. **Google Chrome** - Version 75.0.3770.142. 
    No extensions. Worked in Normal mode.
3. **Mozilla Firefox** - Version 63.0. 
    No add-ons. Normal mode.

**Comment by adityasood** [comment]
@erIamshivani I was able to replicate this by the following steps

1. Start a GoCD server, open a task to edit/create. Keep this open
2. Restart the GoCD server and wait for the server to be up and running
3. Go back to the open task modal in step one and try and save
4. You should see the error as you have posted

This is because of the stale session. Clearing up the browser cookies should help resolve this issue.
