### ISSUE TITLE
Custom Artifacts Path Configuration

### ISSUE THREAD

**Issue by erIamshivani** [gocd/gocd#6687]
Hi, 
As part of my tasks I am generating 2 artifacts in the form of **.tar.gz**. These are formed in folder outside my working directory. I want to view them under Artifacts Tab and also under a custom tab. 
Also, if possible, I want them to be downloadable.  

1. How can I achieve this? What should I specify in `Source` and `Destination` in Artifacts tab for a job? 
2. How to give path to any file or folder which is outside working directory?

**Comment by adityasood** [comment]
@erIamshivani request you to kindly route your queries to the GoCD community driven gitter channel. You can use this repository for any issues/feature-requests for GoCD.

Link to the channel: https://gitter.im/gocd/gocd/

**Comment by erIamshivani** [comment]
@adityasood 
Thank you for the link! I was looking for something like this.
