### ISSUE TITLE
Move the agents SPA to typescript

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#6711]
### Part 1
- [x] Render agents spa without elastic agent. This includes action like `enable`, `disable`, `delete`, `Modifying resources` and `Modifying environment association`

### Part 2 
- [x] Add Support for agent analytics

### Part 3
- Support for elastic agents. which will be done as part of https://github.com/gocd/gocd/issues/6730

**Comment by GaneshSPatil** [comment]
Done as part of GoCD release v19.10.0
