### ISSUE TITLE
Rename 'Elastic Profile' name in admin menu to 'Elastic Agent Configuration'

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#6724]
##### Summary

After discussing it with the team we have decided to rename the menu item `Elastic Profile` under the `Admin` menu to `Elastic Agent Configuration`. 

We came to this decision as the SPA is not only for the elastic agent profile. It has the cluster profile as well. The plugin will require both the configuration to get a job running using the elastic agent.

**Comment by adityasood** [comment]
This was done as part of 19.8.0 release.
