### ISSUE TITLE
Issues with new pipeline creation wizard

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#6726]
##### Issue Type

- Bug Report

##### Summary

Placeholder for all issues related to new pipeline creation wizard

- [x] Task settings should have option to specify working directory - On pipeline creation wizard material has option to specify `Alternative checkout directory`. However task settings do not have that option. Which will result in task running from the parent directory of the material checkout folder

- [x] Mercurial material do not have field for Branch. As part of 19.4.0 release we made some changes to URL Normalization for Git and Hg materials - https://github.com/gocd/gocd/issues/6132 which introduced `branch` field for Mercurial material

- [x] While creating new pipeline with the new pipeline creation wizard cannot use template which uses parameters. More details [here](https://github.com/gocd/gocd/issues/6726#issuecomment-518634101)

- [x] New Pipeline has the pause message as  (No pause cause was specified when pipeline was created via API). This is misleading as the pipeline was created via UI.

**Comment by rajiesh** [comment]
Unable to associate template with parameters usage to the newly created pipeline

- Create pipeline `foo`
- Add a parameter `test` to the pipeline `foo`
- Create an environment variable at stage/job level by name say `test_env` and set the value of it to refer to the param like - `#{test}`
- Extract a template from pipeline `foo` and call it as `foo_temp`
- Now on pipeline creation wizard start a new pipeline creation with name `bar` and in advanced settings of `Part 2` choose `use template` option
- Select template `foo_temp`
- Click on `Save` (one of the 2 save options on the page)

**Result**:

Pipeline save fails with below error - User dont have option to create param on this wizard due to which pipeline cannot be associated with the template from this wizard

<img width="1351" alt="Screen Shot 2019-08-06 at 5 10 36 PM" src="https://user-images.githubusercontent.com/6533924/62537123-5647c180-b86d-11e9-87e5-96ad5bddaf7b.png">

**Workaround**

User create pipeline without template form the wizard and them edit pipeline to add parameter and associate with template

**Comment by arvindsv** [comment]
@ibnc, @kierarad and @loudaTW: Since @marques-work is away, I've added you to this. Can you please take a look and work with @rajiesh on this?

**Comment by ibnc** [comment]
> Unable to associate template with parameters usage to the newly created pipeline
> 
> * Create pipeline `foo`
> * Add a parameter `test` to the pipeline `foo`
> * Create an environment variable at stage/job level by name say `test_env` and set the value of it to refer to the param like - `#{test}`
> * Extract a template from pipeline `foo` and call it as `foo_temp`
> * Now on pipeline creation wizard start a new pipeline creation with name `bar` and in advanced settings of `Part 2` choose `use template` option
> * Select template `foo_temp`
> * Click on `Save` (one of the 2 save options on the page)
> 
> **Result**:
> 
> Pipeline save fails with below error - User dont have option to create param on this wizard due to which pipeline cannot be associated with the template from this wizard
> 
> <img alt="Screen Shot 2019-08-06 at 5 10 36 PM" width="1351" src="https://user-images.githubusercontent.com/6533924/62537123-5647c180-b86d-11e9-87e5-96ad5bddaf7b.png">
> 
> **Workaround**
> 
> User create pipeline without template from the wizard and then edit pipeline to add parameter and associate with template

@rajiesh @arvindsv @kierarad 

Correct me if I'm wrong, but this isn't a new issue. The old add pipeline flow also didn't allow for the creation of params. It seems to be more of an issue with templates not supporting params rather than not being able to create params on the add pipeline flow. So, to me, the solution would be to add param support to templates. 

or am I missing something?

**Comment by marques-work** [comment]
@ibnc you're right, it is not a new issue - this error should also be possible with the old pipeline flow -- not to say we should ignore it though. As this is not a regression, and unless the solution is fairly trivial, I would say this issue _shouldn't block its release into 19.8.0_, however, it should be addressed in the release thereafter.

I would be hesitant to change the contracts (i.e., allowing param creation in templates) without thinking through and understanding the reason creation is limited to the pipeline level (and maybe it's obvious, but I spent exactly zero seconds thinking about it before writing this). That said, to make the add pipeline experience ergonomic for users that want to use templates, we should add support for creating params here, somewhere in the form.

/cc @rajiesh @arvindsv @kierarad

**Comment by marques-work** [comment]
☝️ btw that's just my opinion, not a decision by any means. What do other folks think?

**Comment by kierarad** [comment]
@ibnc I'm not sure about the old flow vs the new flow.

The way I see it, this is not specific to templates so adding param support to pipelines would only partially fix the issue. For example, if you try to create a pipeline with the task `echo #{my-param}` you will not be able to save the pipeline. You will get the error `Parameter 'my-param' is not defined. All pipelines using this parameter directly or via a template must define it.`

The real question to me is what should the experience be for a user who wants to create a pipeline (from a template or not) that uses a parameter? As it stands the user would have to create the pipeline. Then edit the pipeline to define the param. Then edit the pipeline to use the param. Is this reasonable? IMO, it's questionable. I actually might take the tradeoff of keeping the add flow simple for most users (by not supporting parameter definition as part of the create flow). 

However, when factoring in templates (where a user would have to create pipeline without using the template and then edit pipeline to add parameter and associate with template), I lean toward supporting parameters in the pipeline create flow. 

Btw I haven't thought much about whether it makes sense to be able to define a parameter in a template. I'm just noting that the "issue" would still stand.

**Comment by marques-work** [comment]
See https://github.com/gocd/gocd/issues/6443 for associated working directory issue

**Comment by arvindsv** [comment]
I remember conversations with @varshavaradarajan about adding default values for params in templates. Similar to what is mentioned in https://github.com/gocd/gocd/issues/829. It got hairy quite quickly and there were some cases which were hard to expose to the UI in a reasonable manner.

That will end up being a much bigger change, imo, than adding support for params at the pipeline level in this.

**Comment by kierarad** [comment]
Just to clarify - the current issue is that the new add pipeline flow does not allow users to create pipelines that reference a parameter (directly or as part of a template) because users are unable to define the parameter as part of the flow. 

Options for how to address: 
1 - Don't do anything. Force users to use the workaround: user create pipeline without template (or parameter reference) from the wizard and then edit pipeline to add parameter and associate with template (or use parameter). 
2 - Allow templates to have default values for parameters. 
3 - Allow users to define parameters as part of the flow. PR #6765 
4 - Additional option(s) not suggested/discussed? 

Which do you think we should move forward with? (I can outline the pros and cons of each if needed)
@arvindsv @marques-work @ibnc @loudaTW @streisguth @rajiesh

**Comment by rajiesh** [comment]
@kierarad IMO option 3 is a better one. If we are going to show the fields for parameters, pre-populated with the parameter names, only when user select a template using parameters then the concern of having to introduce new concept (about parameters) for first time users does not arise. I hope thats what the PR does

**Comment by arvindsv** [comment]
I prefer option 3 as well. It looks like #6765 does not automatically bring over the chosen template's parameters though. That's what @rajiesh is asking about, I think.

**Comment by rajiesh** [comment]
Yes @arvindsv thats what I meant. If user who is creating the pipeline can see parameter name pre populated  it makes it easier to provide values for them accordingly. Thats how it used to be in the old flow

**Comment by kierarad** [comment]
@arvindsv @rajiesh ok thanks. yes, that's correct. currently it doesn't bring over the templates parameters. I can make that change. 

IYO should we give the option to define parameters regardless of whether a template is selected, since they are technically independent concepts? or for simplicity sake are you suggesting only to provide the option if a template that has parameters is selected?

**Comment by arvindsv** [comment]
@kierarad You're right. Since they're independent, I think params should be available all the time.

**Comment by adityasood** [comment]
@kierarad @marques-work @ibnc I noticed that on creating a new pipeline the pause message is misleading. I have edited the issue list above and added it there. Adding a screenshot here for reference.

![Screen Shot 2019-08-29 at 12 07 37 PM](https://user-images.githubusercontent.com/17826464/63917122-868f1400-ca57-11e9-83f6-d5a81467915d.png)

**Comment by rajiesh** [comment]
@kierarad Verified changes to support parameters in new pipeline dashboard wizard. Couple of observations,

- On selecting a template which uses parameters, the parameter names are not auto populated, it was discussed [here](https://github.com/gocd/gocd/issues/6726#issuecomment-523111234)

- Why is the parameter value field named `OPTIONAL DEFAULT VALUE`? Didn't get what the name meant. The parameter values are optional, but IMO it cannot be called default, since it cannot be overridden at any other levels. Cant it just be called `VALUE`? Let know if am missing something

**Comment by marques-work** [comment]
@rajiesh I think we conflated environment variables with params as those could be overridden through "Trigger with options". Would `Optional value` be acceptable? I feel it's good to be explicit that param values are not required

**Comment by marques-work** [comment]
> I noticed that on creating a new pipeline the pause message is misleading.

@adityasood I believe @kierarad is working on this now.

**Comment by arvindsv** [comment]
@marques-work Param values are not required. But whether they are optional or not is not up to GoCD, though. It's decided by who uses it.

**Comment by arvindsv** [comment]
Given how a param is used, the pipeline might be useless and fail without it being filled. We can't put a red asterisk there, but we can't be sure it is truly optional.

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9912-33898b3adaf72cedea1604882d3554fd586571a8)
