### ISSUE TITLE
Template Authorization API returns 404

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#6727]
##### Issue Type

- Bug Report

##### Summary

Template Authorization API does not work as mentioned in [API Docs](https://api.gocd.org/current/#get-template-authorization) 

The API endpoint returns 404 (Not Found).

###### Basic environment details

* Go Version: `19.7.0-9567`

**Comment by GaneshSPatil** [comment]
This API has been broken since `18.11.0` version of GoCD.

**Comment by GaneshSPatil** [comment]
This issue was closed by automation.

Reopening it. Will close once its QA-Approved.
\cc: @rajiesh @adityasood

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9746-6bbad2a99f2a38bfc31210777c22d9bfda941e68)
