### ISSUE TITLE
Elastic Agent Configuration Page UI/UX refresh

### ISSUE THREAD

**Issue by bdpiparva** [gocd/gocd#6731]
Part of #6716 
### Issue Type
- Feature proposal

### Summary

To run GoCD jobs using elastic agent requires the following configurations: 

1. Cluster profile
2. Elastic agent profile
3. Associate jobs with the elastic agent profile

Based on the feedback received from the users we are looking at simplifying the process of running a job using the elastic agent. The proposed solution will reduce the navigation between the pages to configure the same.

#### Provide help about the elastic agent concepts
- [ ] Needs to work on the UI, we will update the image soon

#### Configuring the elastic agent configuration
![Screenshot 2019-08-07 at 3 26 33 PM](https://user-images.githubusercontent.com/7871209/62613777-c3b82880-b927-11e9-80c7-3955f2875cac.png)

#### Associating jobs with the elastic agent profile
![Screenshot 2019-08-07 at 3 36 11 PM](https://user-images.githubusercontent.com/7871209/62614504-26f68a80-b929-11e9-9e1e-cd0c9c632803.png)

---

- [ ] Move cluster profile and elastic profile creation in the wizard
- [ ] Allow associating jobs to the elastic profile
- [ ] Allow user to review and verify the changes

**Comment by rajiesh** [comment]
Association of profile with Job and Verify steps are pending from the scope defined in this issue. Closing this issue and will open new ones when work on the remaining 2 steps
