### ISSUE TITLE
[PipelineConfig] UI for Pipeline Level Settings

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#6738]
Related to Epic: #6362

This issue is for the UI only. API calls will be stubbed out.

## UX issues
1. Validation for pipeline name happens too late
2. Provide better (help) text for fields:
    - Automatic Pipeline scheduling
    - Cron timer specification
    - Pipeline locking
3. Show a consolidated view for all environment variables defined everywhere in the Environment, Pipeline, Stage, Job

## Notes
After a pipeline is saved, the pipeline name won't be editable. Making the pipeline name editable is desirable, but will be out of the scope of this story.

After a pipeline is saved, one option to show the UI could be like:
<img width="697" alt="image" src="https://user-images.githubusercontent.com/6024038/62760981-ffc3c880-baa2-11e9-877e-674560daa0a3.png">

**Comment by akshaydewan** [comment]
Current WIP screenshots:
<img width="1056" alt="Screenshot 2019-08-29 at 14 56 03" src="https://user-images.githubusercontent.com/6024038/63928497-43d83680-ca6d-11e9-8daa-a637fa7ca6f2.png">
<img width="1060" alt="Screenshot 2019-08-29 at 14 56 17" src="https://user-images.githubusercontent.com/6024038/63928508-48045400-ca6d-11e9-8e4d-d0a04b3d4639.png">

- The helpText is displayed below the input field instead of the (?) button that showed a tooltip in the old page
- The labels still need to be made user-friendly
- The styles are the default ones applied to input components, but some of them look inconsistent, such as the space between the checkbox label and its helpText. This needs to be fixed, but will likely affect all pages using the input fields.

**Comment by akshaydewan** [comment]
The Env Variables and Parameters sections are similar and straightforward. Here's the Project Management section:

<img width="1056" alt="Screenshot 2019-09-03 at 15 23 45" src="https://user-images.githubusercontent.com/6024038/64163485-fdb11780-ce5e-11e9-8f57-1d854b241878.png">
<img width="1062" alt="Screenshot 2019-09-03 at 15 24 24" src="https://user-images.githubusercontent.com/6024038/64163500-030e6200-ce5f-11e9-813a-99a0aeab9a6e.png">

For reference, the current screen looks like this - 
<img width="862" alt="Screenshot 2019-09-03 at 15 25 42" src="https://user-images.githubusercontent.com/6024038/64163552-1de0d680-ce5f-11e9-8e5c-a7aea35dc651.png">

- Removed the Mingle section
- Using a Switch instead of the radio. When the Switch is "on", the form will appear
- Added placeholder text to the text inputs

**Comment by akshaydewan** [comment]
@arvindsv @vrushaliwaykole @viraj2712 @GaneshSPatil @streisguth Any feedback so far on these screens?

I think some of them look a bit crowded because of the help text at the bottom of the fields. In our user interviews, we didn't see many users clicking on the (?) button to reveal the tooltip, so I put them at the bottom.

I think with proper margins and padding, we could make it look less crowded.

**Comment by arvindsv** [comment]
Even though it might be crowded, I _much prefer_ the explanations. They're grey and people will learn to ignore them, once they learn it. There is some space right after the name of the label ("Pattern *" and "URI *") which could be considered too. However, if there is a line wrap, it's going to mess up the formatting.

Overall, I think it looks nice and don't mind the verbosity.
