### ISSUE TITLE
[PipelineConfig] Task entry and task settings

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#6739]
Related to Epic: #6362

This issue is for the UI only. API calls will be stubbed out.

Allow the user to enter tasks and configure them.

## UX issues
1. Separate fields for Command and Arguments creates confusion. The arguments entry is confusing.
2. The Lookup Commands field creates an impression that only some commands are supported. We can choose to get rid of this entirely
3. Separate dropdown items for Ant, Rake etc. causes confusion for some users
4. There is some redundancy between Fetch Artifact and adding an upstream pipeline. Think of some ways to improve this.
5. The textboxes in Fetch Artifact don't give the impression that they will be auto-completed
6. Users tend to trip on "Source is a file (not a directory)"
7. Ensure that the new UI can handle Task plugins

## Ideas
1. The "Terminal" metaphor was used in the Trial Experience. We can consider using something similar.

**Comment by mehmetcavus** [comment]
@akshaydewan my thoughts on UX issues:
1. Arguments are the only way to keep track of what a command does and doesn't require opening edit task window (very helpful). Hope it's kept with UI improvement, and by adding a task label.
2. The Lookup Commands field is pretty helpful when command and arguments fields are pre-filled by selecting a command. My vote for keeping it. Renaming or adding more description may be better.

**Comment by mehmetcavus** [comment]
also, drag and drop support to change order of tasks would be helpful. #6805 (item 7)
