### ISSUE TITLE
Introduce a cancel stage API

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#6760]
##### Issue Type

- Feature enhancement

##### Summary

The current [cancel stage api](https://api.gocd.org/19.7.0/#cancel-stage) cancels the latest running instance of stage with given name. This can possibly cause race conditions in cases where a running stage is about to finish, but when a user attempts to cancel the stage, it accidentally ends up canceling a different (newer) instance of the stage.

I'd want to instead support a stage cancel API using the URL:

```
POST /go/api/stages/:pipeline_name/:pipeline_counter/:stage_name/:stage_counter/cancel
```

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9912-33898b3adaf72cedea1604882d3554fd586571a8)
