### ISSUE TITLE
Indicators on main navigation bar

### ISSUE THREAD

**Issue by streisguth** [gocd/gocd#6762]
Wayfinding indicators on the main navigation bar. ie when a user is on the Dashboard, there is an corresponding indication on the navigation.

![menu-nav-indicator-admin](https://user-images.githubusercontent.com/1781525/63119238-96d1ca00-bf54-11e9-8040-58eb805f93b2.png)

![menu-nav-indicator-dashboard](https://user-images.githubusercontent.com/1781525/63118785-705f5f00-bf53-11e9-80f9-14de767da32a.png)

**Comment by ankitsri11** [comment]
Verified on GoCD Version: 19.9.0 (9929-91f828d47612be57eeb28377e7c3ca6206b8d992
