### ISSUE TITLE
Artifacts not being purged

### ISSUE THREAD

**Issue by christamlyn-bridge** [gocd/gocd#6775]
##### Issue Type

- Bug Report

##### Summary

We have configured the setting to purge artefacts, but Go Server never seems to remove any artefacts.  Server runs out of disk space

##### Environment

GoCd Server running on Ubuntu

###### Basic environment details

* Go Version: `18.4.0`
* JAVA Version: `1.8.0_171`
* OS: `Linux 3.13.0-125-generic'

##### Steps to Reproduce

![image](https://user-images.githubusercontent.com/20814270/63266579-209cd280-c288-11e9-8c73-8359f3797fbf.png)

Our artefacts are being written to:
223G	/var/lib/go-server/artifacts/pipelines

The size of this directory only seems to increase, until we manually purge.

##### Expected Results
Expecting Go to clean artefacts when space is below 5.0 GB

##### Actual Results
No evidence that the job is running.  Is it logged?

**Comment by ankitsri11** [comment]
@christamlyn-bridge I tried to replicate locally on the GoCD 18.4 instance but unable to do so.

I had below configured for auto delete artifacts:

![Screenshot 2019-08-19 at 11 33 45](https://user-images.githubusercontent.com/6838313/63290003-4ec4e700-c275-11e9-8d33-a6d4b19c6496.png)

Soon after the disk space on my machine left with only 11 GB space, **ArtifactsDiskCleaner** process kicked in and tried to delete the old artifacts.

Here is the snippet from the go-server.log:

```
2019-08-19 11:28:38,506 INFO  [Thread-74] ArtifactsDiskCleaner:68 - Clearing old artifacts as the disk space is low. Current space: '11283513344'. Need to clear till we hit: '1.2884901888E10'.
2019-08-19 11:28:38,787 WARN  [Thread-74] ArtifactsDiskCleaner:83 - Ran out of stages to clear artifacts from but the disk space is still low
```

Can you check if your system disk space is less than 5 GB? The auto artifact delete process will purge artifacts when available disk space is lower than the given value. You can read more [here](https://docs.gocd.org/current/configuration/delete_artifacts.html).

I would suggest increasing the given lower disk space to 10 or 20 GB as there might be some other process on the server kicks in and consume the space and server runs out of disk space.

**Comment by christamlyn-bridge** [comment]
The IT team expanded the drive, so I'm not in the same scenario.  But I tried this

![image](https://user-images.githubusercontent.com/20814270/63326958-2d233880-c325-11e9-836b-138750a33c0f.png)

Then on the go server:

![image](https://user-images.githubusercontent.com/20814270/63327067-6f4c7a00-c325-11e9-9a8c-9151216c1aa8.png)

Some of our artifacts are large, so I wonder if it gets down to just over 5GB, creates a new artifact which consumes all the space causing the server to go into a unresponsive state.

Looks like we'll have to stick with a higher limit
