### ISSUE TITLE
Rescheduled pipeline does not show the updated Agent IP details on
the Job details page.

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#68]
Description
-----------

### Steps to reproduce

- Have a remote and localagentconfigured to your Go-Server.
- Disable the remote agent and trigger the pipeline.
- Once the local agent ip address gets assigned to the job, kill the local agent.
- Enable the remote agent so that the job gets rescheduled.

#### Expected result

The job should getrescheduled and the Job details page must show the rescheduled agent ip i.e. the remote agent IP.

#### **Current result**

The job gets rescheduled but the Job details page does not show the rescheduled agent ip i.e. the remote agent IP.

**Observed on 13.2 also.**

**Comment by chopraapooja** [comment]
This has been fixed as a part of #1089

**Comment by juhijariwala** [comment]
Verified with 15.2.0-2067 (07d65665c731a615f6a6943cce0fd03440eb4a9e).This works as expected.
