### ISSUE TITLE
UI Issues on 19.8.0 build

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#6807]
##### Issue Type

- Bug Report

##### Summary

Issue to capture general UI issues seen on 19.8.0 release

- [x] VSM page is broken - doesnt show the stage bars - https://build.gocd.org/go/pipelines/value_stream_map/build-linux/4183
- [x] Analytics views are not generated - visit any analytics page and it doesnt load. Console error shows,

```
Uncaught ReferenceError: AnalyticsEndpoint is not defined
    at Object.8 (workflow-trends-chart.js:1)
    at a (workflow-trends-chart.js:1)
    at Module.165 (workflow-trends-chart.js:1)
    at a (workflow-trends-chart.js:1)
    at n (workflow-trends-chart.js:1)
    at workflow-trends-chart.js:1
    at workflow-trends-chart.js:1
```

- [x] Footer on login/logout page broken

<img width="1435" alt="Screen Shot 2019-08-30 at 11 50 26 AM" src="https://user-images.githubusercontent.com/6533924/63997573-8442bd80-cb1c-11e9-99e7-896f3948c296.png">

- [x] Fonts and Icons broken on pages using components - Elastic profile, Artifacts store, plugins, User management, Secret management, Config Repo, Backup, Maintenance mode, auth/role config

<img width="1431" alt="Screen Shot 2019-08-30 at 11 50 08 AM" src="https://user-images.githubusercontent.com/6533924/63997818-35495800-cb1d-11e9-8fad-d732eec5cd97.png">

###### Basic environment details

* Go Version: `19.8.0 (9777-84a6c497afaea9f424b838eb024f018087eddf34)`
* Browser vendor and version (if relevant): `Chrome: Version 76.0.3809.100` `Firefox: 67`

**Comment by arvindsv** [comment]
The analytics endpoint issue should be fixed by:
  - https://github.com/gocd/gocd/commit/6731045bfda31118b45ebd962dfcccd79ecda879
  - ... and a corresponding fix in the plugin.

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9912-33898b3adaf72cedea1604882d3554fd586571a8)
