### ISSUE TITLE
User info synchronisation with external sources

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#6832]
Parent Issue: https://github.com/gocd-contrib/github-oauth-authorization-plugin/issues/69

##### Issue Type
 - Feature enhancement

##### Summary

Any GoCD user information is not updated with the actual source after the first login.
E.g. if the email associated with the github profile is updated, the same is never reflected in the GoCD until that user is deleted and added again.

##### Suggestion

After successful authentication, the user info received should be compared with the info stored in the DB. In case of any update, the DB should be updated to reflect the same.

**Comment by kritika-singh3** [comment]
Closed via automation. Reopening for testing.

**Comment by rajiesh** [comment]
Verified on 19.8.0 (9912-33898b3adaf72cedea1604882d3554fd586571a8)
