### ISSUE TITLE
error when running multiple agents on a single host after upgrade to 19.7

### ISSUE THREAD

**Issue by mkcgem** [gocd/gocd#6835]
##### Issue Type

- Bug Report

##### Summary

We've upgraded gocd from 19.5 to 19.7. Only one instance of go-agent would run at a time after the upgrade. Tried using the script from README-running-multiple-agents.md but that didn't work either. Downgraded back to 19.5 and the agents all work fine 

##### Environment
gocd 19.7
-->

###### Basic environment details

Go Server Version: | 19.7.0 (9567-727ea9db824eb6971170ac2a886ff1072ff5a235)
-- | --
JVM version: | 12.0.1
OS Information: | Linux 4.14.109-80.92.amzn1.x86_64

##### Log snippets

```
INFO   | jvm 1    | 2019/08/27 10:54:23 | WrapperManager: Initializing...
INFO   | jvm 1    | 2019/08/27 10:54:24 | [Tue Aug 27 10:54:24 UTC 2019] Starting process:
INFO   | jvm 1    | 2019/08/27 10:54:24 | [Tue Aug 27 10:54:24 UTC 2019]   Working directory    : /var/lib/go-agent
INFO   | jvm 1    | 2019/08/27 10:54:24 | [Tue Aug 27 10:54:24 UTC 2019]   Application arguments: [-serverUrl, https://1xx:8154/go]
INFO   | jvm 1    | 2019/08/27 10:54:24 | [Tue Aug 27 10:54:24 UTC 2019]            GoCD Version: 19.7.0-9567
INFO   | jvm 1    | 2019/08/27 10:54:24 | [Tue Aug 27 10:54:24 UTC 2019]            Java Version: 12.0.1
INFO   | jvm 1    | 2019/08/27 10:54:24 | [Tue Aug 27 10:54:24 UTC 2019]        Operating System: Linux(4.14.138-89.102.amzn1.x86_64)
INFO   | jvm 1    | 2019/08/27 10:54:24 | Could not find file `config/agent-bootstrapper-logback.xml'. Attempting to load from classpath.
INFO   | jvm 1    | 2019/08/27 10:54:24 | Using classpath resource `jar:onejar:lib/agent-bootstrapper-19.7.0-9567-classes.jar!/config/agent-bootstrapper-logback.xml'.
INFO   | jvm 1    | 2019/08/27 10:54:24 | SLF4J: Class path contains multiple SLF4J bindings.
INFO   | jvm 1    | 2019/08/27 10:54:24 | SLF4J: Found binding in [jar:onejar:lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
INFO   | jvm 1    | 2019/08/27 10:54:24 | SLF4J: Found binding in [jar:file:/var/lib/go-agent/data/deps-8902a0bd07c1d985-agent-launcher.jar/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
INFO   | jvm 1    | 2019/08/27 10:54:24 | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
INFO   | jvm 1    | 2019/08/27 10:54:24 | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
INFO   | jvm 1    | 2019/08/27 10:54:24 | Could not find file `config/agent-launcher-logback.xml'. Attempting to load from classpath.
INFO   | jvm 1    | 2019/08/27 10:54:24 | Using classpath resource `jar:file:/var/lib/go-agent/data/deps-8902a0bd07c1d985-agent-launcher.jar/agent-launcher-19.7.0-9567-classes.jar!/config/agent-launcher-logback.xml'.
```

**Comment by adityasood** [comment]
@mkcgem the log snippet you have shared looks like the agent started alright. Can you help me with the following

1. go-agent.log file from any of the agents which failed to startup
2. Did you see any errors when you ran the script from README-running-multiple-agents.md? Can you share the output of the script run here?

**Comment by mkcgem** [comment]
the agents would start and then stop a few seconds later

``` 2019-08-27 11:03:17,868 INFO  [main] ClassPathXmlApplicationContext:583 - Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@1060b431: startup date [Tue Aug 27 11:03:17 UTC 2019]; root of context hierarchy
2019-08-27 11:03:17,941 INFO  [main] XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [applicationContext.xml]
2019-08-27 11:03:18,107 INFO  [main] XmlBeanDefinitionReader:317 - Loading XML bean definitions from class path resource [applicationContext-plugin-infra.xml]
2019-08-27 11:03:18,537 INFO  [main] AutowiredAnnotationBeanPostProcessor:155 - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-08-27 11:03:19,058 WARN  [main] AgentStatusHttpd:92 - Could not start agent status HTTP API server on host localhost, port 8152.
java.net.BindException: Address already in use (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at java.net.ServerSocket.bind(ServerSocket.java:329)
        at fi.iki.elonen.NanoHTTPD$ServerRunnable.run(NanoHTTPD.java:1761)
        at java.lang.Thread.run(Thread.java:748) ```

this is from go-agent.log

No, didn't get any errors when running the script from README-running-multiple-agents.md

**Comment by ketan** [comment]
That is just a warning message because the agent status endpoint for all agents are attempting to bind on the same port. See https://docs.gocd.org/current/advanced_usage/agent-health-check-api.html. Perhaps the message could have been a bit clearer.

**Comment by ketan** [comment]
As far as I understand, agent execution should continue post that warning message. That error is just ignored by the agent.

**Comment by mkcgem** [comment]
there's nothing else that I can see in the logs. We don't hae any older logs to look at unfortunately

**Comment by adityasood** [comment]
@mkcgem I did a small setup at my end by installing go-agent-19.7.0-9567 on an ubuntu 14.04.

I then ran the run multiple agents script which installed the agents and started them as service go-agent-1 and go-agent-2.

You mentioned multiple agents are not working, were you able to get alteast one agent connected to GoCD server on 19.7.0? 

<img width="518" alt="Screen Shot 2019-08-29 at 2 33 30 PM" src="https://user-images.githubusercontent.com/17826464/63926914-4c7b3d80-ca6a-11e9-9ad6-309fb5622eef.png">

![Screen Shot 2019-08-29 at 2 31 19 PM](https://user-images.githubusercontent.com/17826464/63926982-73397400-ca6a-11e9-818b-65e886175b46.png)

<img width="593" alt="Screen Shot 2019-08-29 at 2 30 55 PM" src="https://user-images.githubusercontent.com/17826464/63927002-7d5b7280-ca6a-11e9-9402-4118c571a2af.png">

**Comment by mkcgem** [comment]
yes, I was able to get one agent running and connected to the gocd server but was unable to start more than one agent on the same instance

**Comment by adityasood** [comment]
@mkcgem unfortunately since there is not much information or logs available to us at this moment I will be closing this issue.

However, if someone faces this issue again and can add more details to the issue we can reopen this and take a look at it.

**Comment by mconfer** [comment]
Wanted to report that I struggled with this identical issue in a clean install of version 20.1 in a windows server 2012 R2 environment, and was able to resolve the issue by removing everything and instead doing a clean install of version 19.5. Basically with 20.1 the first agent would work out of the box, but no attempts to create or start any other agents on the same server would succeed. Everything worked first try on version 19.5.
