### ISSUE TITLE
Add section for "Finish" button on PaC form to create a config repo from the information on the form.

### ISSUE THREAD

**Issue by ibnc** [gocd/gocd#6857]
This should navigate to the configrepo SPA and link directly to the configrepo.

~~The configrepo ID should probably be a randomly generated id.~~

**Comment by ankitsri11** [comment]
This seems to be broken. I tried adding a config-repo from Pac form selecting the JSON language but when I click on finish it shows as yaml-config-plugin under the config-repositories section.

refer below gif:

![test-pac-flow](https://user-images.githubusercontent.com/6838313/65645392-2e8ef300-dfac-11e9-82a6-685addf55f7a.gif)

**Comment by ankitsri11** [comment]
@marques-work this hasn't been fixed. I still get the issue as described above. 

Moving to "To Do" status. Let me know if you have any concerns.
