### ISSUE TITLE
One time import of external pipelines (config repos) and group level clone of internal pipelines

### ISSUE THREAD

**Issue by mehmetcavus** [gocd/gocd#6873]
##### Issue Type

- Feature proposal

##### Summary

This feature is about one-time import (not adding). 

Currently external pipelines can be added with config repo, and #3549 will allow them read-only view. Editing not possible obviously, because it's managed externally. And also, config repo is for one specific project. Then:

1. What happens when user wants to use same / similar pipeline configuration and flow of projectA for projectB? 
2. What if user wants to use someone else's config repo as a starting point for projectB? 

```
Clone, edit materials in text editor, commit, add as config repo. 
And if you want to change sth, edit, commit again. Repeat. 
```

##### Expected Results

External or not, allow users repeating a pipeline configuration and flow of existing project for a new project as quick and smooth as possible. It's like "clone all pipelines of projectA and configure for new project"

##### How it works
Allow user to import a config repo which allows editing in GoCD afterwards, and that means it's not managed externally. This is exactly same with hands-on creating all pipelines and configuration from scratch. (Also, allow group level clone for internal pipelines.)

- This will not add it to list of config repos but import it to default dashboard.

Alternatives for import:
1. Add an option to existing "Create new configuration repository" window: "one-time import" 
2. Add new menu "Import Config Repo" which is exactly same with adding config repo but behavior is as described.

**Comment by adityasood** [comment]
@mehmetcavus why do you say config repo is for one specific project? Do you mean that there could be limited access available to this configuration repository?

> What happens when user wants to use same / similar pipeline configuration and flow of projectA for projectB?.

If the idea is to have repetitive configuration, wouldn't templates be a good option?

> What if user wants to use someone else's config repo as a starting point for projectB?

As you mentioned this is currently possible through cloning the already configured config repo and making suitable edits.

There are other concerns around allowing for importing of an external config repo pipeline. For e.g There could be secrets configured. This could be a private repository

> Allow user to import a config repo which allows editing in GoCD afterward, and that means it's not managed externally. This is exactly same with hands-on creating all pipelines and configuration from scratch.

I am thinking this to be similar to adding a pipeline via API and then edit it within GoCD?
