### ISSUE TITLE
Placeholder issue for a ton of copy that needs review

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#6888]
## All the fun stuff:

- [ ] 1. Text for the "New Pipeline" dropdown options:
![image](https://user-images.githubusercontent.com/723642/64388418-de97be80-cff3-11e9-9fea-a567f879b159.png)
- [ ] 2. The whole section with `Download` button (both section title and instructions):
![image](https://user-images.githubusercontent.com/723642/64388469-10108a00-cff4-11e9-8e8f-6433ddebf153.png)
- [ ] 3. All of this stuff (check material instructions, section title, checkbox text -- do we need tooltips for anything?):
![image](https://user-images.githubusercontent.com/723642/64388579-5cf46080-cff4-11e9-8f0b-300c8296aed2.png)
- [ ] 4. Check Material results (and styling needs fixing too): 
![image](https://user-images.githubusercontent.com/723642/64388650-97f69400-cff4-11e9-9dc3-3b411b977f68.png)
- [ ] 5. Terminal help text:
![image](https://user-images.githubusercontent.com/723642/64388704-cf654080-cff4-11e9-8090-29c854fafe91.png)
- [ ] 6. Plugin selection for PaC builder (currently hidden)

**Comment by ibnc** [comment]
@marques-work regarding number five (the task helper text). It looks kinda goofy when both the help and caveats section are expanded:

<img width="643" alt="Screen Shot 2019-09-17 at 15 43 57" src="https://user-images.githubusercontent.com/5726224/65085142-2a3a5880-d962-11e9-9480-142b036ce323.png">

Maybe it should be a new issue?

**Comment by ibnc** [comment]
Verified on GoCD Version: 19.9.0 (10137-727c1b8ef4b8b55e4aed25574e8331e5e4d4974f).

**Comment by marques-work** [comment]
@ibnc (and anyone else)

This was intentional, but not sure if it's the best interaction. What I was trying to solve was for when both sections are expanded -- if both headers were at the top, the user wouldn't know which paragraphs pertain to which header.

/cc @streisguth any alternative approaches?

**Comment by kierarad** [comment]
@marques-work I kind of agree with @ibnc that it looks goofy. 
What if we don't allow both to be expanded at the same time? So if you expand one it will collapse the other (if expanded)? IMO it's more digestible

**Comment by ibnc** [comment]
@marques-work It's probably fine.

... but if we do want a different approach, then maybe we could have the help text color correspond with the respective headers?

**Comment by kierarad** [comment]
@marques-work as is the interaction feels inconsistent to me. it's not really clear why when "Help" is expanded "Caveats" remains at the top
![Screen Shot 2019-09-18 at 11 28 57 AM](https://user-images.githubusercontent.com/3814794/65175462-c2d6e400-da07-11e9-99a8-ee1ef25f9c5e.png)

But when "Caveats is expanded "Help" drops below
![Screen Shot 2019-09-18 at 11 29 04 AM](https://user-images.githubusercontent.com/3814794/65175494-d2562d00-da07-11e9-9880-94579a072c16.png)

**Comment by marques-work** [comment]
@kierarad yeah, it is a little odd-looking.

To answer your question on why the caveats section is not pushed down when help is expanded is really because help sits below caveats in the dom. So at least from an implementation perspective, it makes sense that only one can be pushed down rather than either. Just depends on the lexical ordering.

But to your point, it's not the most intuitive approach. I had that feeling when I initially put it in (as an easier alternative to implementing a `help` command as proposed before), but didn't seek an alternative as I was going for a lightweight, "good-enough" approach for this adjunct piece of the CWD stuff out as the PR was becoming quite large.

Perhaps it didn't qualify as "good-enough", lightweight that it was :).

**Comment by kierarad** [comment]
@marques-work sorry I meant from a user perspective it's not clear why. I pretty much assumed from an implementation perspective it was because of it's position in the dom. 

To your point. It's probably good enough. But in the spirit of "polishing" this interaction doesn't feel polished to me

**Comment by marques-work** [comment]
@kierarad yeah, I agree it should be more polished, given the context. Maybe we can knock out a better interaction with @streisguth tomorow.
