### ISSUE TITLE
Test Drive - PaC builder content not visible when scroll

### ISSUE THREAD

**Issue by kierarad** [gocd/gocd#6910]
The form content on the left is substantially longer in content than the code preview on the right; thus when scrolling down the form to enter stage and job details, the code snippet is out of view (sitting above the viewport top) so the user no longer sees the code updating as new form data is entered.

Therefore, it would be nice to keep the preview within the viewport bounds while filling out the form.

**Comment by ibnc** [comment]
Verified on GoCD Version: 19.9.0 (10137-727c1b8ef4b8b55e4aed25574e8331e5e4d4974f)
