### ISSUE TITLE
[Bug] z-index woes for new pipeline dropdown

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#6935]
> Just tried to add Pipelines-as-Code in GoCD, but the liberal and totally biased pipelines settings icon (Fake Button!) got in the way. Sad.

![image](https://user-images.githubusercontent.com/723642/64901759-d40fa180-d651-11e9-80f6-0ce66e373c53.png)

**Comment by ankitsri11** [comment]
verified on GoCD Version: 19.9.0 (10194-34fca8f7682a65ef5fbd6726d51fd52b0c041bc6)
