### ISSUE TITLE
Length of Admin Email for GO Server

### ISSUE THREAD

**Issue by dave-ingham-tlr** [gocd/gocd#695]
I am establishing the "Email Notification" section of the Server Configuration for the GO server via the web user interface. 

I have found that the Admin Email address appears to be truncated at 65 characters. The address that I need to supply is 80 characters long and is therefore being rejected as the truncated address is not valid. 

Is this a hard limit to the length or can it be increased?

**Comment by arvindsv** [comment]
Cleanup: Was done. Closing.
