### ISSUE TITLE
GoCD page suddenly asking for client certificate

### ISSUE THREAD

**Issue by Keksparade** [gocd/gocd#6952]
##### Issue Type

- Bug Report
- Question? (moved from mailing list https://groups.google.com/forum/#!topic/go-cd/FBKM93KDyIo)

##### Summary

Hi, 

since we did an upgrade from GoCD 18.x.x (I don't remember) to 19.7.0 all of a sudden, when opening the server page in a totally new browser session, GoCD is asking for a client certificate. You can press cancel and use the page as usual however this behavior is annoying. Does anyone know why this is happening and where I can disable the client certificate request?

Any hint and help would be appreciated.

Thanks in advance!

###### Basic environment details

* Go Version: `19.8.0`
* JAVA Version: `12.0.1`
* OS: `Linux 4.15.0-62-generic`
* Browser vendor and version (if relevant): `Google Chrome 77.0.3865.75`
  Also happens when colleagues use Mozilla Firefox

##### Expected Results

No client authentication via certificate. Only showing the page with the cached login, but not asking for the certificate.

##### Actual Results

Every time the page is opened in a totally new browser session it is asking for a client certificate to be used. The dialog can be cancelled and the page will work as usual.

##### Code snippets/Screenshots

![certificate-selection](https://user-images.githubusercontent.com/15687427/65046738-73d67380-d961-11e9-81c4-3b1517937085.png)

**Comment by arvindsv** [comment]
@Keksparade Are you using Docker image or Kubernetes for the GoCD server?

**Comment by arvindsv** [comment]
@Keksparade Also, can you confirm that this happens only using Google Chrome, but not on Firefox?

**Comment by arvindsv** [comment]
Just for the record: I found that this happens on 19.5.0 too, when Java 12 is used as the JVM.

**Comment by Keksparade** [comment]
We‘re neither using Docker nor Kubernetes. 
At least two colleagues reported that they have seen the issue in Firefox too. I wasn‘t able to reproduce this intentionally on my computer, but I‘m prefering Chrome for my daily work.
Nice to know that this issue can be reproduced by you. I‘m not alone.... hooray!

**Comment by arvindsv** [comment]
Can you verify that disabling TLS 1.3, as a workaround, removes the annoying certificate prompt?

You'll need to add this `-Dgo.ssl.protocols.exclude=TLSv1.3` into your `wrapper-properties.conf` file and restart the server.

I haven't seen Firefox show an unnecessary certificate prompt, whatever different versions of GoCD and JVM I checked. I don't know why Chrome shows it yet.

It's probably not a good long-term idea to disable TLS 1.3, since browsers will stop supporting the others in some time. However, TLS 1.3 support is very new. @ketan is thinking of some ideas to do this differently in 19.9.0. So, it might be worth trying.

**Comment by Keksparade** [comment]
Perfect! I did what you we're saying and I can no longer reproduce this in my Chrome. Thank you so much!
However, you're of course right that this is only a workaround, but no solution. What's the best practice to handle such an issue? Keep this one open until it's solved or is there another issue that I can follow and check?

**Comment by ketan** [comment]
This is an issue that needs addressing. So keeping it open for now. I'll probably be able to take a look at this early next week. Until then, I think using the workaround that @arvindsv mentioned is ok.

**Comment by Keksparade** [comment]
> I haven't seen Firefox show an unnecessary certificate prompt, whatever different versions of GoCD and JVM I checked. I don't know why Chrome shows it, yet.

@arvindsv Asked my colleagues for feedback. The Firefox version used was 69.0 (64bit). Just for the record.

**Comment by arvindsv** [comment]
@Keksparade Thank you. Good to know. I did use (am using) that version as well and I wasn't able to reproduce it. Let's see whether we can reproduce the issue on that, after this is worked on.

**Comment by bdpiparva** [comment]
@Keksparade - I haven't verified the issue we see with GoCD, but it ooks like the issue with the java 12 as mentioned [here](https://mailarchive.ietf.org/arch/msg/tls/Aw1WY5gBAifAZXowgx5Ym82RIKI).

**Comment by ketan** [comment]
Reopening for @adityasood to confirm if the fix works as expected.

**Comment by adityasood** [comment]
verified on 19.9.0-(10189)
