### ISSUE TITLE
Cannot bypass proxy settings with docker-gocd-agent-dind

### ISSUE THREAD

**Issue by takurojin** [gocd/gocd#6955]
##### Issue Type

- Bug Report

##### Summary

Hi,
Since I upgraded from GOCD 19.6.x to 19.8.0, [docker-gocd-agent-dind](https://github.com/gocd/docker-gocd-agent-dind) can't bypass proxy settings anymore.
I found that there were changes [here](https://github.com/gocd/docker-gocd-agent-dind/commit/1c2c6332e64e4e0612bfb317aed8e6aee2b60c8d#diff-60713fb19f6c50a2473835df63ff17f9L57-R57) and [here](https://github.com/gocd/docker-gocd-agent-dind/commit/1c2c6332e64e4e0612bfb317aed8e6aee2b60c8d#diff-e4724ba2daa172f605632b1a23879906R2) from docker-gocd-agent-dind 19.7.x.
As a result, proxy settings by environment are ignored.
I guess that it must be added '-E' option with sudo or 'Defaults env_keep = "ftp_proxy http_proxy https_proxy no_proxy" ' at dockerd-sudo file.

Or did I miss anything?
Any hint and help would be appreciated.

###### Basic environment details

* Go Version: `19.8.0`
* JAVA Version: `12.0.1`
* OS: `Linux 4.13.0-45-generic`

##### Expected Results

docker-gocd-agent-dind should pass proxy settings.
```
bash-5.0# docker info
...
Name: docker-in-docker-agent-ea0446c4-c61d-4b0d-8b7a-322a63b0fb49
 ID: 6BIR:SWMT:GTO2:PGAB:COWI:ESGF:DPRK:BSUB:UOMO:IJYH:WUOI:WHAB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://someproxy:3128
 HTTPS Proxy: http://someproxy:3128
 No Proxy: localhost,127.0.0.1,127.0.0.0/8,(and others...)
 Registry: https://index.docker.io/v1/
...
```

##### Actual Results

```
bash-5.0# docker info
...
Name: docker-in-docker-agent-ea0446c4-c61d-4b0d-8b7a-322a63b0fb49
 ID: 6BIR:SWMT:GTO2:PGAB:COWI:ESGF:DPRK:BSUB:UOMO:IJYH:WUOI:WHAB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
...
```
##### Possible Fix

I guess that it must be added '-E' option with sudo or 'Defaults env_keep = "ftp_proxy http_proxy https_proxy no_proxy" ' at dockerd-sudo file.

**Comment by arvindsv** [comment]
@GaneshSPatil might know more about this.

**Comment by bdpiparva** [comment]
@takurojin - You can pass the environment variables in the elastic agent profiles to configure proxy

```
HTTPS_PROXY=https://example.proxy:port
HTTP_PROXY=http://example.proxy:port
```
