### ISSUE TITLE
CCTray no longer connecting after update to 19.8.0

### ISSUE THREAD

**Issue by Keksparade** [gocd/gocd#6965]
##### Issue Type

- Bug Report
- Question

##### Summary

Hi,
We're using CCTray application in our team to watch the build status and retrieve desktop notifications on failing builds. Therefore, we have a read-only user called `view` and the URL to connect to the server contains user and password for the connection in the URL: `https://view:passwordofview@<gocdserver>:<port>/go/cctray.xml`.
While this was working perfectly before, since the update of the server and GoCD from 19.7.0 to 19.8.0 CCTray is no longer able to connect to the URL. The `cctray.xml` is available and can be opened in the browser. 
What has changed between 19.7.0 and 19.8.0 that the application can no longer connect to this? I tried scanning through the release notes and fixed issues without any insights. 
Would be awesome if someone knows a solution. I know that CCTray is pretty old and unmaintained, but there is no other open source application fulfilling these requirements.

Thanks in advance!

###### Basic environment details

* Go Version: `19.8.0`
* JAVA Version: `12.0.1`
* OS: `Linux 4.15.0-62-generic`
* CCTray: `1.8.5.0` 

##### Code snippets/Screenshots

![cctray](https://user-images.githubusercontent.com/15687427/65128705-383bb800-d9fa-11e9-8e4a-c1d3e065b141.png)

**Comment by maheshp** [comment]
@Keksparade from what I remember there is nothing changed around the CCTray in GoCD 19.8.0. I was not able to reproduce this issue though.

Below are the steps I followed,

1. Brought up a GoCD 19.8.0 server - `docker run -d -p8153:8153 -p8154:8154 gocd/gocd-server:v19.8.0` 
2. Configured a pipeline, added a admin user and a view only user.
3. `curl -k https://<username>:<password>@localhost:8154/go/cctray.xml` returned the cctray xml for both the admin as well as view user.

Can you curl the cctray endpoint and see if it works?

**Comment by Keksparade** [comment]
@maheshp I can curl the endpoint and also retrieve the xml data, but CCTray is nevertheless not able to connect.

**Comment by maheshp** [comment]
Not sure what's happening with CCTray, will have to try it out and get back to you.

**Comment by ankitsri11** [comment]
@Keksparade I was able to replicate using CCTray on GoCD v19.8.0.

However, I noticed that if I use Http URL instead Https, it works fine. I'm not sure how the behaviour was on older GoCD version. I'll need to check.

Can you try Http URL once and see if that works.   

`http://user:password@<gocdserver>:8153/go/cctray.xml`

**Comment by ketan** [comment]
I suspect this may be related to to #6952. Do you mind trying the work around, and reporting back?

**Comment by Keksparade** [comment]
@ankitsri11 I'm sorry, but I cannot try the plain port because it is currently firewalled. However, we have been using the https URL for months and everything was working fine.
@ketan #6952 was reported by me and the work around is already in place. Still no connection for CCTray.

**Comment by ketan** [comment]
Do you also mind turning on the system property `-Dgo.ssl.config.clear.default.exclusions=true` and report back?

**Comment by Keksparade** [comment]
@ketan Yes, setting this property and restarting the server effects CCTray to connect again as usual. Thank you so much!
From your point of view, is this the final solution for the issue or a temporary workaround? I assume supporting weak ciphers could be a security risk, hence I'm thinking about how to improve the situation. Do we need "better" certificates?

**Comment by ketan** [comment]
I believe CCTray is likely unable to connect using some of the more modern ciphers that we enabled by default. For now I recommend using the 2 flags (for tls1.2 and the clear default default exclusions), these flags combined will tweak the ssl/tls jetty config to what existed before 19.8 while we investigate this better.

**Comment by arvindsv** [comment]
I'm assuming you're using the CruiseControl.net from [here](https://sourceforge.net/projects/ccnet/files/CruiseControl.NET%20Releases/). It was released in 2014. :) I assume it's getting to a point where it won't connect to newer TLS protocols. Need to investigate (especially the one around Chrome), but we might not be able to do much about it, since TLS 1.3 is here to stay. JVM itself will, at some point, disable those older protocols.

**Comment by ketan** [comment]
On further troubleshooting, it appears that CCTray built using dotnet core 3.5 [supports only TLSv1](https://docs.microsoft.com/en-us/dotnet/api/system.net.securityprotocoltype?view=netframework-3.5#System_Net_SecurityProtocolType_SystemDefault).

I'd like to echo what @arvindsv mentions in his [comment above](https://github.com/gocd/gocd/issues/6965#issuecomment-533642977). Knowingly enabling insecure protocols and ciphers by default is the wrong choice to make. So I'd like to keep the current code as is. And mark this bug as WONTFIX.

There are explicit toggles to enable insecure ciphers and protocols, so you should be able to turn them on as needed.

**Comment by Keksparade** [comment]
Thanks for taking the time to analyze the issue. I really understand and support your decision, it's the only reasonable way to handle this.

Unfortunately I have not found any good replacement for CCTray on Windows yet. Therefore, can you tell me if CCTray code is open source and if it would be an option to revive this project on an open source community basis?
