### ISSUE TITLE
Materials API return 404 for existing materials and modifications in 19.8.0

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#6968]
##### Issue Type

- Bug Report

##### Summary

The below material endpoints return a 404 in GoCD 19.8.0,
- https://api.gocd.org/19.8.0/#get-all-materials
- https://api.gocd.org/19.8.0/#get-material-modifications

**Comment by rajiesh** [comment]
Verified on 19.9.0 (10194-34fca8f7682a65ef5fbd6726d51fd52b0c041bc6)
