### ISSUE TITLE
Feature request: /status endpoint. 

### ISSUE THREAD

**Issue by ghost** [gocd/gocd#697]
Hi, 

To monitor the go server it would be great to have a /status endpoint, if this doesn't already exist? ideally it would return 200 OK and some json with any errors, so we can alert on error conditions in monitoring.

**Comment by arvindsv** [comment]
I recall something happening around this, recently. I don't see it documented. But, [this PR](https://github.com/gocd/gocd/pull/2239) has added a version API which can be used for this. /cc @GaneshSPatil, @ketan.

**Comment by arvindsv** [comment]
Ah, found the [PR for the documentation](https://github.com/gocd/api.go.cd/pull/84). It's not merged yet.
