### ISSUE TITLE
Cue for users to click "+ new Pipeline" once in the dashboard for first time

### ISSUE THREAD

**Issue by loudaTW** [gocd/gocd#6976]
Only +/- 30% of users are entering into the Add Pipeline wizard. We would like to increase this to help solidify their understanding of GoCD concepts, and complete a task.

Add a visible prompt to the initial dashboard interaction suggesting they add a pipeline. Once they add their pipeline successfully they wouldn't need to see this queue any longer if they revisit the dashboard. 

Once through the wizard they can do as they like with the example pipelines or anything else in the tool. 

This may require design time however let's spike this out to get some quick feedback on it.

**Comment by adityasood** [comment]
@loudaTW in this use case does the dashboard already contain some pipelines and there is a new user who is visiting the dashboard for the first time?

**Comment by loudaTW** [comment]
@adityasood There are two sets of examples. In our current flow, users end up in the config of the pipelines instead of the add pipeline flow. This is not inherently bad, however working their way through our flow would be more beneficial to them understanding GoCD concepts and ease of use, before looking under the hood of the pre-existing pipelines first.

**Comment by ibnc** [comment]
@loudaTW to clarify, this is only for test drive instances correct?

**Comment by loudaTW** [comment]
@ibnc That is correct. We would have to toggle it off for production instances.

**Comment by ibnc** [comment]
@loudaTW Terrible, ugly, bad design aside, is something like this what you were thinking? 

<img width="647" alt="Screen Shot 2019-09-23 at 14 42 41" src="https://user-images.githubusercontent.com/5726224/65465185-7416b900-de10-11e9-9d84-84819a33553d.png">

**Comment by loudaTW** [comment]
@ibnc Yes, that's basically what I was hoping for :) Perhaps we can get @streisguth to help with styling input.

**Comment by ibnc** [comment]
@loudaTW I'd love your input on the actual text content too

**Comment by loudaTW** [comment]
@ibnc Definitely, will get that over soon.

**Comment by marques-work** [comment]
@loudaTW @streisguth with this cue, could we consider getting rid of empty pipeline groups?

It’s something we certainly should discuss for the next test drive release after our initial PaC release. From a technical standpoint and a use-case standpoint, I see that feature as a negative, even though it might help guide the user during our prior test drive user tests.

**Comment by loudaTW** [comment]
@marques-work @streisguth I think we need more information before making that choice. Let's see how this affects the flow first and then revisit this topic

**Comment by loudaTW** [comment]
@ibnc Please use "Create your first pipeline" as text

**Comment by marques-work** [comment]
@loudaTW fair enough - we need some real data; I think I just don't want to forget about the issue and I think we should find a more suitable replacement interaction for it. Anyway, sorry for the tangent :).

**Comment by streisguth** [comment]
I won't go into the topic of empty pipeline groups on this issue, and will stick to the topic at hand.
Below is my first pass at an indicator. Next step, I would like to design a little css bounce animation for it.

<img width="682" alt="Screen Shot 2019-09-25 at 3 39 06 PM" src="https://user-images.githubusercontent.com/1781525/65645314-d35d0080-dfab-11e9-862f-5cb0688560d7.png">

**Comment by loudaTW** [comment]
@streisguth @ibnc If we're going to make this white, we need to make it more obvious. I get the why behind it, but the point is to give someone a visual clue, not an easy to miss suggestion.

**Comment by arvindsv** [comment]
To me, that itself looks a little too much like a button.

**Comment by loudaTW** [comment]
@streisguth I agree with @arvindsv the more I look at it. Perhaps a good opportunity to do some quick UH testing

**Comment by streisguth** [comment]
Feedback heard. The idea behind this iteration is to use the color from the header as the background to create contrast between the dialogue box and the surrounding UI. We don't use this color anywhere else in the product, and in my mind will be a 'conceptually neutral' color. I've made the silhouette look more like a classic speech bubble, putting the affordance more in line with other applications.

<img width="678" alt="Screen Shot 2019-09-26 at 1 37 47 PM" src="https://user-images.githubusercontent.com/1781525/65723575-889ebf80-e063-11e9-8920-8e253255b407.png">

**Comment by kierarad** [comment]
@streisguth no opinion on whether this is good or bad, but it looks like our old tooltips (we have multiple styles of tooltips depending on which page you are on) 

<img width="433" alt="Screen Shot 2019-09-26 at 4 43 45 PM" src="https://user-images.githubusercontent.com/3814794/65732093-1fc44100-e07d-11e9-9afc-ba98dfa04038.png">

**Comment by ibnc** [comment]
@streisguth Just found an issue with the current design:

<img width="408" alt="Screen Shot 2019-10-01 at 12 13 36" src="https://user-images.githubusercontent.com/5726224/65992913-01779000-e445-11e9-8a29-09f5fd3710f1.png">
