### ISSUE TITLE
[Bug] fix layout when validation errors occur when downloading PaC config

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#6995]
On the PaC test drive flow, if a user triggers validation errors after clicking “Download Config”, the button and error message wrap to the next line.

![1A749E92-7A38-47A1-8520-8F7D05D1FA1E](https://user-images.githubusercontent.com/723642/65530891-a4606500-dead-11e9-81d3-633ca9c03d3c.png)

This has to do with the behavior of `display: flex`. The presence of error message changes the width of the button’s container and consequently wraps.

What will _probably_ fix this is to set a fixed percentage `flex-basis` with `flex-grow` set to `0`.

**Comment by ankitsri11** [comment]
![Screenshot 2019-10-02 at 14 41 00](https://user-images.githubusercontent.com/6838313/66084113-afa53780-e522-11e9-9c2f-8132d1640d94.png)


Verified on GoCD Version: 19.10.0 (10224-1c5477efbcfe700994d8af8a1835292db734c5e2)
