### ISSUE TITLE
Rescheduled Successful job Shows no color on console log page

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#70]
Description
-----------

In this Page, default job ran successfully and show as green in color

![untitled1](https://cloud.githubusercontent.com/assets/1577718/2739791/913c107c-c6bd-11e3-8f3d-6d2a30b03b2f.png)

But the same instance if we go to console log page it doesn't show any color.

 ![dependent_build](https://cloud.githubusercontent.com/assets/1577718/2716585/acb24740-c52d-11e3-929e-d7c07ed8f07f.png)

#### Expected result

It should show header in respective job Result color with Rescheduled as
message

#### **Current result**

It shows No color with Rescheduled as message

**Comment by chopraapooja** [comment]
Fixed as a part of #1089

**Comment by arvindsv** [comment]
@zabil: I took a look at this, and looks ok to me. I think this is too much of a corner case to need a functional test. I see that there are tests at the integration level [here]( https://github.com/chopraapooja/gocd/commit/025039e510c6806d55d467cf41921b1bad22bcca) and [here](https://github.com/chopraapooja/gocd/commit/035502154175ecd72233839220d91862d101dbaa). So, I'm happy with this.

I moved it to "Testing" pipeline in zenhub, but don't know what to do after. Let me know. Thanks.

I see that there are a lot of issues in the "Closed" pipeline, which haven't been checked, I guess.

**Comment by arvindsv** [comment]
I'll close this issue for now. I think that's the next step. Verified on 15.2.0.479-7af6e1b.

**Comment by arvindsv** [comment]
I guess I still need to know how to use the zenhub workflow. I assume I can move an issue from the "Ready for QA" pipeline to "Testing" pipeline and assign the issue to myself? That's what I have been doing.

**Comment by zabil** [comment]
@arvindsv yes. We should move issues that need QA onto Ready for QA move it to testing by assigning you yourself if you are picking it up and to closed if we are done.
