### ISSUE TITLE
Support for Optional upstream dependencies through UI, API and Config Repo

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#7016]
##### Summary

Support for optional upstream dependencies was added as part of https://github.com/gocd/gocd/pull/6950. This PR adds support for only configuring Dependency Material through xml config. Add ability to configure the materials through UI, API and Config Repo.

**Comment by akshaydewan** [comment]
Tasks:
- [ ] Implement API
- [ ] Update Documentation for API
- [ ] Update schema for JSON and YAML plugins
- [ ] Update Documentation for JSON and YAML plugins
- [ ] Implement the flag on the UI

**Comment by rajiesh** [comment]
Verified on 19.10.0 (10328-5cb62ca14461d56576551e0bbec2978c909ea9b2)
