### ISSUE TITLE
Add support for Java 13

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#7017]
##### Summary

1. Currently our builds run on Java 11 and 12, add support to run on Java 13.
2. Bundle JRE 13 for installers(https://github.com/gocd/gocd/pull/6987)

**Comment by marques-work** [comment]
Going to need #8233 first to run builds on JDK 13

**Comment by marques-work** [comment]
This should be working fine now. We're already building on JDK 14, soon to be JDK 15.
