### ISSUE TITLE
Compare pipeline miss to show upstream pipeline material when tracking tool integration specified

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#7020]
##### Issue Type

- Bug Report

##### Summary

Startup the server and create a config with pipelines as below,

```
<pipeline name="first-pipeline">
    <trackingtool link="https://github.com/bob/my-project/issues/${ID}" regex="##(\d+)" />
    <materials>
        <git url="material-for-first-pipeline" dest="git" materialName="git-first-pipeline"/>
    </materials>
    <stage name="defaultStage">
        <jobs>
            <job name="defaultJob">
                <tasks>
                    <exec command="ls"/>
                </tasks>
            </job>
        </jobs>
    </stage>
</pipeline>
<pipeline name="down-pipeline">
    <trackingtool link="https://github.com/alice/my-project/issues/${ID}" regex="##(\d+)" />
    <materials>
        <git url=
            <some-git-material> dest="git" materialName="git-down-pipeline"/>
            <pipeline pipelineName="first-pipeline" stageName="defaultStage"/>
        </materials>
        <stage name="defaultStage">
            <jobs>
                <job name="defaultJob">
                    <tasks>
                        <exec command="ls"/>
                    </tasks>
                </job>
            </jobs>
        </stage>
    </pipeline>
```

Let the upstream and downstream pipelines run ones. Now visit the compare page of `down-pipeline`

###### Basic environment details

* Go Version: `19.10.0 (10207-99cfdb28ebaa4f8476f4f88a9d7fed68ea68d332)`

##### Expected Results

The compare page should show 3 materials - The `down-pipeline` own git material, the upstream pipeline material and the git material of upstream pipeline

##### Actual Results

The compare page shows only 2 materials - its own git material, the upstream pipeline material. The git(any SCM) material of upstream is not shown as expected

Regression failure is related to this - https://build.gocd.org/go/tab/build/detail/regression-SPAs/1654/Firefox/1/regression-runInstance-12

The issue is observed only when tracking tool setting is specified on the pipelines as specified above, if not compare page shows as expected

**Comment by adityasood** [comment]
I spent some time trying to look at combinations and below are my observations

### 1. Same tracking tool URL 
```xml
<pipeline name="test-pipe-1">
      <trackingtool link="https://github.com/bob/my-project/issues/${ID}" regex="##(\d+)" />
      <materials>
        <git url="git_url1" autoUpdate="false" />
      </materials>
      <stage name="defaultStage">
        <approval type="manual" />
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
  <pipelines group="group-for-dependency-walk-2">
    <pipeline name="test-pipe-2">
      <trackingtool link="https://github.com/bob/my-project/issues/${ID}" regex="##(\d+)" />
      <materials>
        <git url="git_url2" autoUpdate="false" />
        <pipeline pipelineName="test-pipe-1" stageName="defaultStage" materialName="test-upstream" />
      </materials>
      <stage name="defaultStage">
        <approval type="manual" />
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
```

With the above configuration, follow the below steps

1. Perform a commit on material git_url1 and perform a commit on git_url2.
2. Trigger pipeline test-pipe-1 and wait for it to complete
3. Trigger pipeline test-pipe-2 and wait for it to complete
4. Visit the compare pipeline page for test-pipe-2 for run 1.
5. You will see three materials.

### 2. Different tracking tool URL

```xml
<pipeline name="test-pipe-1">
      <trackingtool link="https://github.com/bob/my-project/issues/${ID}" regex="##(\d+)" />
      <materials>
        <git url="git_url1" autoUpdate="false" />
      </materials>
      <stage name="defaultStage">
        <approval type="manual" />
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
  <pipelines group="group-for-dependency-walk-2">
    <pipeline name="test-pipe-2">
      <trackingtool link="https://github.com/alice/my-project/issues/${ID}" regex="##(\d+)" />
      <materials>
        <git url="git_url2" autoUpdate="false" />
        <pipeline pipelineName="test-pipe-1" stageName="defaultStage" materialName="test-upstream" />
      </materials>
      <stage name="defaultStage">
        <approval type="manual" />
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
```
With the above configuration, follow the below steps

1. Perform a commit on material git_url1 and perform a commit on git_url2.
2. Trigger pipeline test-pipe-1 and wait for it to complete
3. Trigger pipeline test-pipe-2 and wait for it to complete
4. Visit the compare pipeline page for test-pipe-2 for run 1.
5. You will see two materials.

@kritika-singh3 looked into the code and this seems to work as expected. According to the checks in place, when we click on the compare pipeline we draw an upstream dependency graph. While drawing this graph we check if the current user has permissions on the upstream pipeline and if the tracking tool URL matches. The above test confirms it works as expected.

@arvindsv a question for you is if you remember why we had put an explicit check for matching tracking tool URL?

**Comment by arvindsv** [comment]
@kritika-singh3 @adityasood  The best reason I can think of is: At one point, the output of "Compare Pipeline" included the difference in cards from the Mingle wall. For that to have worked, the tracking tool config would have to be the same. There used to be a tab which used to show "Card Activity" and used to show Mingle cards which differed between those two pipeline instances.

I think that it's not relevant right now to check whether the tracking tool is the same.

**Comment by kritika-singh3** [comment]
Thanks @arvindsv for the input. Going forward, as you suggested that the tracking tool check is irrelevant, we should remove the same. I'll raise a PR fr that soon.

@maheshp @ketan
