### ISSUE TITLE
Documentation: describe how to bind Go to localhost

### ISSUE THREAD

**Issue by garthk** [gocd/gocd#705]
We're told how to front-end Go with an Apache proxy, but not how to prevent it from binding to `*:8153` and `*:8154`. Should we edit `config.properties`, `jetty.xml`, or `cruise-config.xml`? How?

**Comment by stevendgonzales** [comment]
bump

**Comment by stevendgonzales** [comment]
@garthk I did some digging and in https://github.com/gocd/gocd/blob/master/installers/server/release/server.sh#L112-113 it reads an ENV variable named SERVER_LISTEN_HOST that sets the ip that the go-server binds to.  I am going to make a PR to add this to the /etc/default/go-server, as this should be made an obvious configuration.

**Comment by arvindsv** [comment]
Added documentation about this. It's a [PR](https://github.com/gocd/documentation/pull/96), still. Should get accepted soon. The page will look, sort of, like [this](https://github.com/arvindsv/documentation/blob/add_options_page/user/advanced_usage/other_config_options.md).
