### ISSUE TITLE
Enhancements to Personalize

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#706]
- It should be possible to sort the list in 'Personalize' alphabetically.
- It should allow me to save my list of pipelines. Depending on what i am working on I might want to see a specific set of pipelines and easily switch to another set.

The above has been moved from issue #44

**Comment by alexschwartz** [comment]
+1 for storing sets (or views) for pipelines 

BTW, deleting must be implemented, too

**Comment by reidca** [comment]
1. It would be great to have a search box in this as well. When you have a large number of pipelines it can be hard to find the one you want to display. Lots of scrolling in a small box.

2. It would be great to have the box resizeable to prevent the massive amount of scrolling.

**Comment by arvindsv** [comment]
Closing in favor of https://github.com/gocd/gocd/issues/3842.
