### ISSUE TITLE
Inconsistent documentation on authorisation config API

### ISSUE THREAD

**Issue by mm689** [gocd/gocd#7064]
##### Issue Type

- Bug Report

##### Summary

The API for Authorization Config update behaves differently from what the API says.

##### Environment

```json
  "Go Server Information": {
    "Version": "19.9.0 (10194-34fca8f7682a65ef5fbd6726d51fd52b0c041bc6)"
  },
```

##### Steps to Reproduce

The [documentation](https://api.gocd.org/current/#update-an-authorization-configuration) says that the request body for an update operation should NOT include the `id` of the authorization config. But the server responds with `422` when id is not provided. The response:
```plain
{'message': 'Json `{"plugin_id":"cd.go.authentication.passwordfile","properties":[{"key":"PasswordFilePath","value":"/home/go/htpasswd"}]}` does not contain property \'id\''}
```
The workaround is to add `id` as in the POST request.

##### Expected Results

`id` field should not be required for PUT operation.

##### Possible Fix

Either fix documentation or change API. The id is already in the URL, so it's cleaner to remove the id in body requirement.

**Comment by bdpiparva** [comment]
@mm689 - Agreed, `Id` field should not be required in `PUT` operation and it should be fixed as such. This bug is introduced during the migration of API(https://github.com/gocd/gocd/pull/6315).

**Comment by bdpiparva** [comment]
@mm689 - PR https://github.com/gocd/gocd/pull/7070 will fix the issue.

**Comment by rajiesh** [comment]
Verified on 19.10.0 (10296-5bf08f4e5d6ddfe9a53735d75c4a95de0f087eec)
