### ISSUE TITLE
Notification Preferences Don't Persist

### ISSUE THREAD

**Issue by rschneiderman39** [gocd/gocd#7067]
##### Issue Type
- Bug Report

##### Summary
Email settings found under <Username> > Preferences does not persist (and therefore build status notifications are not received) after config.xml is changed in the browser.

##### Environment
GoCD Version: 19.8.0
Java Version: openjdk 11.0.3 2019-04-16
OS: OpenSuse Leap 15.1
Browser: latest Chrome

##### Steps to Reproduce
1. Navigate to <Username> > Preferences
2. Click 'Edit' under 'Email Settings'
3. Click 'Enable email notification'
4. Enter email address
5. Save changes
6. Add a notification ([Any Pipeline] | [Any Stage] | All | All -- | -- | -- | --)
7. Build a pipeline, receive an email
8. Navigate to Admin > Config XML
9. Click 'Edit'
10. Click 'Save'
11. Navigation to <Username> > Preferences
12. Observe that 'Email' under 'Email Settings' is empty and if you build a pipeline, you will not receive a notification email

##### Expected Results
I would expect that the email would persist in some sort of storage at least in the running instance of the go-server (AKA email is preserved/saved at least until go-server is restarted)

##### Actual Results
After editing the config.xml in the browser, the user's notification email is erased.

Thanks!!!

**Comment by rschneiderman39** [comment]
Update: I also tried adding the email via rest endpoint. That did not persist either.

**Comment by ankitsri11** [comment]
@rschneiderman39 I was able to replicate the behavior but in my case, if I logout from the instance and login back, the user's notification email is erased.

Refer below gif:

![notification_bug](https://user-images.githubusercontent.com/6838313/66434577-b24ad580-e9d7-11e9-80c7-06875e6ca823.gif)

I tried on both GoCD 19.8.0 and 19.9.0 versions and found the same issue. Also tried on Chrome, Firefox and Safari browsers.

**Comment by bdpiparva** [comment]
@rschneiderman39 - Thanks for reporting the issue. The PR https://github.com/gocd/gocd/pull/7077 is opened to fix the same.

**Comment by rschneiderman39** [comment]
@bdpiparva Thanks for your quick thorough response! Much appreciated!

**Comment by rajiesh** [comment]
Verified on 19.10.0 (10307-818f6ceeda0573fcb1fc790f89aa7ad8896bc9b4)
