### ISSUE TITLE
Enable email support link is pointing to wrong link under preferences tab

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#7068]
##### Issue Type

Bug

![Screenshot 2019-10-08 at 14 01 54](https://user-images.githubusercontent.com/6838313/66433063-516dce00-e9d4-11e9-8d5d-2f686746a7f2.png)

Currently, it is pointing to `go/admin/config/server`.

Correct url: go/admin/mail_server

**Comment by rajiesh** [comment]
Verified on 19.10.0 (10307-818f6ceeda0573fcb1fc790f89aa7ad8896bc9b4)
