### ISSUE TITLE
Users can comment on pipeline run history

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#707]
Each pipeline run can have a single comment written next to it. This can be used to share failure information among teams looking at the pipelines without needing to review the logs.

You will find more details [here](https://github.com/gocd/gocd/pull/699#issue-48037616).

**Note:** The feature is currently turned *'off'*. You will find details about turning it 'on' [here](https://github.com/gocd/gocd/pull/766#issuecomment-66963529).

**Comment by arvindsv** [comment]
Closing. Nothing to do.
