### ISSUE TITLE
Unable to configure external artifacts on a job

### ISSUE THREAD

**Issue by vrushaliwaykole** [gocd/gocd#7071]
##### Issue Type

- Bug Report

##### Summary

Unable to configure external artifacts on a job

##### Steps to Reproduce

1. Add any external artifact plugin
2. Setup artifact store
3. Try to set up external artifacts for a job

##### Expected Results
Should successfully setup the artifacts for a job. 

##### Actual Results
Following error shows up while saving

`Save failed. class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')`

**Comment by rajiesh** [comment]
Verified by regression
