### ISSUE TITLE
Unable to create pipeline

### ISSUE THREAD

**Issue by lsergei** [gocd/gocd#7081]
##### Issue Type
Bug Report

##### Summary
Cannot create pipeline with Git material after upgrade to latest GoCD

##### Environment

CentOS 7, GoCD 19.9.0

###### Basic environment details

Go Server Version: | 19.9.0 (10194-34fca8f7682a65ef5fbd6726d51fd52b0c041bc6)
JVM version: | 12.0.1
OS Information: | Linux 3.10.0-1062.1.2.el7.x86_64
Usable space in artifacts repository: | 46.6 GB
Database schema version: | 1909001
Pipelines Count: | 18

##### Steps to Reproduce

Create pipeline with Git material type, enter git url, enter user /password, press test connection - get result connection is ok.

Fill in other necessary fields.

Press **Save and Edit Full Config**, get error **Validations failed for pipeline 'XXXXX'. Error(s): [Validation failed.]. Please correct and resubmit**

Upon rechecking I can see all mandatory fields filled in but error still persists.

If I change Material type to something else than git - I am able to save the pipeline without any problems. This only happens with git material type.

**Comment by adityasood** [comment]
@lsergei I am closing this issue.

Feel free to reopen in case you are still facing this issue

**Comment by badbort** [comment]
Posting just for reference. I encountered the same issue, and found it was the following:

"auto_update" : [ "Material of type Git (<my repo here>) is specified more than once in the configuration with different values for the autoUpdate attribute. All copies of this material must have the same value for this attribute." ]
