### ISSUE TITLE
Placeholder for issues on new Agents SPA

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#7082]
##### Issue Type: Bug Report

1. **Sort order is lost on page reload**

- In the old Agents SPA, the sort column and order selected is retained on page reload. The same is not the case with the new agents SPA.

- Go Version: `GoCD Version: 19.10.0 (10277-5dacce254dcf9cb8b335cd73cf82fde55add9cac).`

##### Steps to Reproduce

1. Start the server with 2 agents and visit the Agents page (the updated one)
2. Click on sort arrows on `Sandbox` column. The table will be sorted on the basis of sandbox property.
3. Reload the page. 

##### Expected Results

The sort column and order (asc or desc) should be retained as was the behaviour with the original SPA.

##### Actual Results

The sort order is not retained and the agents are unsorted.

2. **Sorting is not working as expected.** The order of rows is different on sorting on both the pages. (See https://github.com/gocd/gocd/issues/7082#issuecomment-540495181 - the ordering of rows with `Idle` status is different. Also, the new page has no sorting by default which is not the case with older one.)

Possible reason: on older page we utilize lodash for sorting, whereas on the new page, we use inbuilt javascript sort functionality.
https://stackoverflow.com/questions/45126469/native-array-prototype-sort-and-sortby-sorts-values-differently

**Comment by viraj2712** [comment]
![agent_spa_sort](https://user-images.githubusercontent.com/34642373/66559059-56688400-eb72-11e9-8e6a-973536f91a86.gif)
