### ISSUE TITLE
Check connection button not working

### ISSUE THREAD

**Issue by niiashikwei** [gocd/gocd#709]
When creating a material, after setting up perforce credentials and clicking on check connection you get an error. However the build is able to connect to the repository and clone the repo when you kick of a build. The error was around P4PASSWD being invalid.

**Comment by jyotisingh** [comment]
Possibly the same as https://github.com/gocd/gocd/issues/1835?

**Comment by arvindsv** [comment]
Closing. Dupicate of #1835, which is fixed.
