### ISSUE TITLE
Add more pipeline states than green and red

### ISSUE THREAD

**Issue by NikoHeikki** [gocd/gocd#7093]
##### Issue Type
- Feature proposal

##### Summary

Since GoCD pipeline has stages and dependencies it leads to situation that pipeline has to be passed in order to move to next stage or trigger downstream pipeline and to avoid this happening you need to do workaround using scripts in order to trigger pipeline after some run or you need to set up manual approval to next stage and go press the gate with script in order to move to next stage for example to teardown test environment with different agent. This is not very useful, I think GoCD users needs to have more options to use platform than its said in the documents with these models. So for example why not have a pipeline status with color blue to inform that pipeline has not succeeded as expected but can trigger next stage or downstream pipeline. If you think about this differently, your build can pass, but your test wont pass = there is an issues with tests, not with pipeline build, so then there is no way to then teardown a environments or trigger pipeline that runs more tests etc to find problems in more depth without scripting. 

Also I wonder why dependencies work like this that you have pipeline that has dependencies to pipeline2 and pipeline 3, when pipeline 3 is passed it triggers pipeline 1, and not wait for pipeline2 since the previous revision was passed. Why is there no option to set that both dependencies must have been run with newer pipeline counter that it was(if build has passed with pipeline3 with revision of 87, dont trigger downstream pipeline because it has not run newer revision) and be passed and then option to allow scheduling of downstream pipeline without them both being passed with newest revision(if pipeline2 triggers and pipeline 3 doesnt run but has passed in previous revision, when pipeline2 finishes then trigger downstream pipeline!)

**Comment by adityasood** [comment]
@NikoHeikki have you looked at the Conditional Task Execution (https://docs.gocd.org/current/advanced_usage/dev_conditional_task_execution.html) which helps with the scenarios where you might want to run a task even though the previous one has failed? 

For your second query, GoCD has in built fan-in which takes care of the scenario which you have explained. However, all pipelines must be marked for auto-trigger for fan-in to work. If there are manual pipelines fan-in would not work. You can read about it here (https://docs.gocd.org/current/advanced_usage/fan_in.html)

**Comment by NikoHeikki** [comment]
@adityasood Yes I have looked and using it many tasks, but it doesnt allow to use diiferent agent, and its not nearly as good as running next stage, since there is lot more configuration available in stage, and still doesnt allow to trigger downstream pipeline since it cannot be triggered by task

And for second issues, its not going to work on for example testing pipeline where the material doesnt change, and you would still want to run it every night and then when all test are finished teardown environments. Now If you have dependency to multiple test pipelines and one of them finishes then it triggers environment teardown and all other tests which are still going will not work since no environments

**Comment by adityasood** [comment]
@NikoHeikki if you look at fan-in it will ensure that the following happens given you have modeled the pipelines as necessary. Fan-in ensures downstream are triggered with consistent material revisions. 

1. Have an upstream pipeline say build which passes and then runs test pipelines 
2. Test pipelines 1..n are run after the build passes
3. Once test pipelines 1..n are passed trigger the downstream teardown pipeline

Isn't this what you are expecting? Is my understanding of the use case correct?

I have drafted three scenarios for the following setup

build-pipeline: This has my test material
test-pipeline-{1..3}: These have build-pipeline as material
tear-down: This has all three test-pipelines as material

Scenario-1: A commit is made to the repo which triggers the build-pipeline. Once the build-pipeline is finished it triggers all three test-pipelines. Once all the test pipelines finish, tear-down pipeline is triggered

![Screen Shot 2019-10-11 at 5 44 57 PM](https://user-images.githubusercontent.com/17826464/66650831-29d66a00-ec4f-11e9-9c4f-fba5bcf3a8d9.png)

Scenario-2: A commit is made to the repo which triggers the build-pipeline. Once the build-pipeline is finished it triggers all three test-pipelines. Now, test-pipeline-2 has failed and hence tear-down is not triggered.

![Screen Shot 2019-10-11 at 5 44 44 PM](https://user-images.githubusercontent.com/17826464/66650912-5db18f80-ec4f-11e9-9670-f2d8285a7eed.png)

Scenario-3: A commit is made to the repo which triggers the build-pipeline. Once the build-pipeline is finished it triggers all three test-pipelines. Now I introduced a sleep for test-pipeline-2 to show how the tear-down waits for all upstreams to complete.

![Screen Shot 2019-10-11 at 5 42 55 PM](https://user-images.githubusercontent.com/17826464/66653661-298d9d00-ec56-11e9-82e6-74e7bb1221b3.png)

![Screen Shot 2019-10-11 at 5 44 28 PM](https://user-images.githubusercontent.com/17826464/66653691-37432280-ec56-11e9-9a52-03cb9000b9f2.png)

**Comment by NikoHeikki** [comment]
I have issue that this test-pipeline-1 triggers and passes succesfully but test-pipeline2 and test-pipeline3 are still building, but they have passed in previous run and it triggers teardown even if pipeline 2 and 3 are still building bases on their previous revision

**Comment by adityasood** [comment]
@NikoHeikki could you please put the configuration of these pipelines? Are they modeled correctly?

Were pipeline2 and pipeline3 built using the same revision as the recent pipeline1? 

Are all of these pipelines auto-triggered? A manual trigger of any pipeline will not adhere fan-in.
