### ISSUE TITLE
Configure server connection wrongly when installed the agent

### ISSUE THREAD

**Issue by tonystaark** [gocd/gocd#7095]
So I have installed the GoCD agent into my local host but unfortunately I put in the port number wrongly when asked by the installer to insert the url. Is there anyway I can reconfigure it? Or do I have to uninstall and reinstall the agent ? How to do that? I cant find any solution online.

Note: I am using WIndows.

**Comment by ketan** [comment]
There's a `config/wrapper-properties.conf` file in the install directory. Change the URL there.
