### ISSUE TITLE
GoCD Agent does not work on macOS 10.15

### ISSUE THREAD

**Issue by renep** [gocd/gocd#7096]
##### Issue Type

- Bug Report

##### Summary

The gocd agent was not [notarized](https://developer.apple.com/developer-id/), therefor the agent does not start when running on macOS 10.15 (Catalina)

##### Environment

* macOS 10.15
* Go Version: 19.9
* JAVA Version:  AdoptOpenJDK build 1.8.0_212-b03

##### Steps to Reproduce

1.  Install the gocd agent on macOS 10.15
2. Start the agent

##### Expected Results

The agent should start

##### Actual Results

The agent could not be started because the libraries from the [Java Service Wrapper](https://wrapper.tanukisoftware.com/) could not be loaded. Try to allow it using _System Preferences_ -> _Security & Privacy_ -> _General_ -> _Allow Anyway_ button does not help either. 

##### Possible Fix

Notarize the agent. See https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

**Comment by adityasood** [comment]
@renep starting GoCD release [v19.3.0](https://www.gocd.org/releases/#19-3-0) macOS installers no longer ship as osx .app files. The installers now ship as a zip file, with a shell script.

Could you ls into the unzip directory of your GoCD agent and try and start the agent as mentioned in the docs [here](https://docs.gocd.org/current/installation/install/server/osx.html).

**Comment by renep** [comment]
@adityasood I have used the zip file of course.

Here the important part from the log file:
```
INFO   | jvm 1    | 2019/10/14 11:31:25 | WrapperManager: Initializing...
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager:
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager: ERROR - Unable to load the Wrapper's native library because none of the
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager:         following files:
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager:           libwrapper-macosx-universal-64.dylib
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager:           libwrapper.dylib
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager:         could be located on the following java.library.path:
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager:           /Users/rene/Downloads/go-agent-19.9.0/wrapper
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager:         Please see the documentation for the wrapper.java.library.path
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager:         configuration property.
INFO   | jvm 1    | 2019/10/14 11:31:30 | WrapperManager:
```

**Comment by adityasood** [comment]
@renep I gave this a quick spin. After accepting it in the security preferences I could get it to work. Can you see if there are more warning in security preferences accept them and try? Also please note we have removed support for java8 in the v19.9.0. You will have to upgrade to java 11 or 12 for the server and agent to work. We package JRE 12 which you can use. To do so, you will have to edit the file wrapper-config/wrapper.conf and change the property

`wrapper.java.command=jre/Contents/Home/bin/java`

<img width="1435" alt="gocd-agent-catalina" src="https://user-images.githubusercontent.com/17826464/66744522-53370600-ee9a-11e9-8b09-3cdad84ac467.png">
<img width="1439" alt="gocd-agent-catalina-1" src="https://user-images.githubusercontent.com/17826464/66744521-53370600-ee9a-11e9-9dae-9ab150e6c6f9.png">

**Comment by renep** [comment]
With AdoptOpenJDK (install via `brew cask install adoptopenjdk12`) it does not work for me. I have tried it with the Java 12 from Oracle, and I got it working with this version. So thanks for the hint.
I'm wondering. Why do you package the jre with the agent, but it is not used per default.

Nevertheless it would be nice if you notarize gocd (server and agent) 😉.

**Comment by adityasood** [comment]
@renep 

> I'm wondering. Why do you package the jre with the agent, but it is not used per default.

With our other installers, we default to the packaged JRE. With MacOS we have recently moved to zip installers from .osx apps and allow users to have there own Java defined. We will take a look at defaulting to it for MacOs.

> Nevertheless it would be nice if you notarize gocd (server and agent) 😉.

Yes, we will take a look at this. Thank you bringing it up.
