### ISSUE TITLE
Add date to User Summary page

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#71]
## Description

Reported by user -

Would be nice to have a sortable "date added" or "since" field on the User Summary page. This allows administrators to easily identify newly added users and respond accordingly. Even better would be to add the ability to alert on this type of system event.
-   Specifically, we maintain a "GO User" email list that is used to send broadcasts to the community of users - tips, conventions, maintenance alerts... We need to know when a new user has been added to GO so we can keep the GO User email list up to date. Ultimately, GO should allow this type of notification.
-   Alerts in general of almost anything that happens in GO would be useful from the perspective of monitoring, especially concerning conventions and adherence to some of our goals. Examples: new pipeline added, new environment added, new user added, new agent added/removed,**agent status change (continues to plague us)**, pipeline added to environment, pipeline added to group, pipeline changed...

http://support.thoughtworks.com/entries/21760449-add-date-to-User-Summary-page

**Comment by arvindsv** [comment]
Closing as stale.
