### ISSUE TITLE
Pipeline references should be case insensitive

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#710]
# Issue

When an upstream pipeline is used as material for downstream pipeline and the case of upstream pipeline is changed. Pipeline fails to trigger with the following logs.

 …executeQueryForObject returned too many results…
 …Multiple independent transactions are not permitted inside single transaction surrounding…
# Expected behaviour :

Pipeline should trigger irrespective to the pipeline case.
# Environment :

Operating System : Windows
Browser : All

**Comment by anishvenkat** [comment]
This bug is similar to the issue #971.
