### ISSUE TITLE
[Config Repo SPA] Show repo status (valid or failed) when collapsed

### ISSUE THREAD

**Issue by ibnc** [gocd/gocd#7100]

**Comment by ibnc** [comment]
@marques-work could you provide more detail on what should be displayed?

**Comment by marques-work** [comment]
@ibnc:

When the config repo section is collapsed (i.e., only the header is visible), it would be useful to have, for instance, a green checkmark or red X (or similar) indicating that the parsed definition(s) are valid or invalid.

The user shouldn't have to expand the section to see this information; it should be available at a glance

**Comment by ibnc** [comment]
@marques-work @kierarad I don't agree with the statement that the failed indicator isn't noticeable enough. When the page loads, all panels will be collapsed by default. The only exception to this is config repos that have "failed" in one way or another. They are expanded by default so that the error message is visible.
