### ISSUE TITLE
Add feature to set the git 'depth' parameter

### ISSUE THREAD

**Issue by hackinjack** [gocd/gocd#711]
We have some git repos which contain pretty large history - it can take about 20 minutes just to check them out so obviously we don't need ALL this cloned into our deployments. 

Currently there is no way of getting the 'depth'  parameter added to the clone commands performed internally by Go. If there was we could check out these repos in seconds. 
---
From: Md. Ali Ejaz <mdaliejaz@gmail.com>
Sent: 14 November 2014 10:59
To: Jack Knight
Cc: go-cd-dev@googlegroups.com
Subject: Re: Git 'depth' parameter
 
Currently this is not possible. But it would be a good enhancement to have in Go. 
Please create an issue on github and someone could pick this up (or I would when I get time :)).

**Comment by mdaliejaz** [comment]
[Here](https://groups.google.com/d/msg/go-cd-dev/Zj7-TMmzMhM/jEKYToo-3fsJ) are some updates on this.

**Comment by paulclarkin** [comment]
Any update on this?

**Comment by ketan** [comment]
closin as dup of #313
