### ISSUE TITLE
GoCD v19.9 with Okta plugin broke

### ISSUE THREAD

**Issue by barrowkwan** [gocd/gocd#7117]
##### Issue Type
Okta plugin seem broken with GoCD v19.9

##### Summary

Deploy GoCD with Helm with Okta.  Authentication seems broken since we didnt' have issue with v19.2

##### Environment

GoCD in GKE deployed with Helm

##### Steps to Reproduce

1. Deploy GoCD with Helm ( GoCD v 19.9 )
2. Configure Okta
3. Got 400 when we access the login page
4. 

##### Expected Results
Should be able to lgin

##### Actual Results
Got 400/404

##### Possible Fix

We want to check if the Okta plugin need to rebuild for GoCD 19.9.  could that be some libraries or api changes  that broke Okta?

**Comment by ketan** [comment]
Version 19.2 added support for access tokens, which required changes to the extension point. The plugin probably needs to be upgraded to version 2 of the plugin extension.

**Comment by barrowkwan** [comment]
HI Ketan, how much work will require to upgrade the plugin?  I have verified that the plugin did break as I jus setup two regular GoCD server on VM ( 19.1 and 19.9 ).  The plugin broke the same way with 19.9 as we run on k8s.

**Comment by kritika-singh3** [comment]
Hello @barrowkwan, you can take the reference of https://github.com/gocd/gocd/issues/5825. You would need to implement two extra calls (based on a capability) which are made from the server. The issue above has links to PR upgrading the github, gitlab and google auth plugins which might be helpful to you. 
You can read more about authorization extension v2 from [here](https://plugin-api.gocd.org/current/authorization/)

**Comment by ketan** [comment]
Marking as closed. This requires an update to the plugin to implement additional calls as suggested by @kritika-singh3 in the comment above.
