### ISSUE TITLE
How do I configure to disable sslv3?

### ISSUE THREAD

**Issue by sawanoboly** [gocd/gocd#713]
Hi,

I'm trying to disable sslv3(use only tls) on go-server 14.3. But I can't found way to it at document.
Please let me know how to do.

**Comment by arvindsv** [comment]
Closing. SSLv3 was never enabled. Right now, I believe it is TLS. For the record, here is the [documentation](https://docs.go.cd/current/installation/ssl_tls/setting_up_ciphers.html).
