### ISSUE TITLE
GoCD should check to see if file artifacts exist

### ISSUE THREAD

**Issue by virtuald** [gocd/gocd#715]
Given that GoCD already does things like locking stages that are used by other pipelines, it should be easy enough to check to see if the other pipeline/stage is actually producing the artifact that the fetch wants.

For example, let's say a user adds an artifact and decides they want to publish it in a directory. If the fetch materials job elsewhere specifies the directory only, and that the artifact is a file -- GoCD just downloads the html index for the directory and writes that as a file, instead of producing an error.

**Comment by bf16574403** [comment]
Interest right here!
