### ISSUE TITLE
[PAC wizard] "Register" section changes

### ISSUE THREAD

**Issue by ibnc** [gocd/gocd#7150]
- Change word from "Register" to possibly "Connect"
    - **Specify** that we are connecting to _this server_ instead of just "GoCD". Many folks thought it otherwise meant to register on a public, centralized website or something
    - Another possibility is to "have GoCD watch this repository" (needs rewording)
- Create headlines for the three subsections
    - 3rd section header might be “Scan Repository for Configuration” (or "Check") so that the button label can be concise (e.g., a single verb)
- Rename "name" field label (people don’t understand it)

**Comment by kierarad** [comment]
> Many folks thought it otherwise meant to register on a public, centralized website or something"


The word "register" needs to be replaced. The associations with that word derailed the participants in the user in the research.

**Comment by kierarad** [comment]
My vote would be to make the header very concise and the supplementary text more explanatory. So I would opt for "Connect your repo to your GoCD server"

**Comment by kierarad** [comment]
@ibnc sorry, new idea. What if the heading says "Mark as Pipelines as Code Repository" and then we have supplemental text that explains "When you commit to a repo, this GoCD server will only check that repo for configuration changes if it has been marked as a Pipeline as Code repo."

**Comment by ibnc** [comment]
@kierarad mark implies that the repo has already been added to the gocd server in some way. I'm currently thinking "Add Your Repository as a Pipelines as Code Repository"

**Comment by ibnc** [comment]
Thoughts?
Screenshot 1:
<img width="1314" alt="Screen Shot 2019-10-30 at 12 02 29" src="https://user-images.githubusercontent.com/5726224/67894656-35160a80-fb16-11e9-9359-919b7a82ce5a.png">
Screenshot 2:
<img width="1313" alt="Screen Shot 2019-10-30 at 12 02 50" src="https://user-images.githubusercontent.com/5726224/67894681-46f7ad80-fb16-11e9-9430-34124a66f932.png">

**Comment by kierarad** [comment]
@ibnc yes, I agree. But that's intentional because I was assuming they were most likely going to use the same repo as the material

**Comment by kierarad** [comment]
I know this wasn't on the original issue, but I remember that the participants in the interviews thought this section was also optional (until they were forced to name the repository). 

I wonder if making the checkbox unchecked by default would help indicate that it is not optional. I believe the original idea was to make it as easy as possible. In this case forcing them to take an action (either checking the checkbox or adding other repo information) might be meaningful

**Comment by ibnc** [comment]
@kierarad But the material hasn't been added yet... right?

**Comment by marques-work** [comment]
@ibnc At this point, it has not been added yet; this step is the action of adding the repo. However, I think that while the removal of "Register" has indeed been accomplished, changing the heading to be what is outlined in the screenshots might be missing the overall goal of helping the user understand what they are really accomplishing and how it fits conceptually? I believe our user test output indicated that users did not understand what the significance of this step was (or what it was even doing for that matter).

**Comment by marques-work** [comment]
It's probably my fault for not putting that into the issue description. I realized I had put a list there without communicating the context :(

**Comment by streisguth** [comment]
It might make sense to add numerals to each of the subheaders (ie 1. Repository Details, etc).
I prefer the left-alignment in Screenshot 1. Additionally, the 'Scan Repository' button should be left-aligned beneath the paragraph in that section..

**Comment by kierarad** [comment]
@ibnc you're correct, the material has not been added yet. But does filling out the material information in the first section make the user feel like they've completed adding the material? 

Also, I'm not sure I understand why you can't mark something in a certain way (in this case as a PaC repo) as you add it? 

If "mark" doesn't feel right then perhaps "designate" would be better? Or does that have the same connotations? I'm actually ok with the word "add" but as it stands "Add Your Repository as a Pipelines as Code Repository" doesn't clarify what user the action is taking without prior knowledge of what a Pipeline as Code repository is in GoCD

**Comment by ibnc** [comment]
idk maybe something like "configure this server with the repository" or something...

**Comment by marques-work** [comment]
> But, I'm not sure how we can accomplish this with a section heading. Maybe a help icon would be helpful?

@ibnc you're right - the solution probably needs to be more than just a heading textual change. It likely needs some structural change + detail. It might be as simple as @kierarad suggested by adding some explanatory text underneath. Maybe we can try that first?

**Comment by marques-work** [comment]
> idk maybe something like "configure this server with the repository" or something...

Something along those lines, yes, but I personally feel that if a user who is not familiar with GoCD came across this, they would need more in terms of the why and the how. In isolation, to say to "configure the server with the repo" may not help the user understand in what way it is connected and why.

**Comment by kierarad** [comment]
> My mind just jumps to "you can't mark what hasn't been created yet."

@ibnc fair. I can see how that would be the case. 

> the solution probably needs to be more than just a heading textual change. It likely needs some structural change + detail. 

@marques-work I agree. IMO the user's understanding of what is happening should not hinge on the heading. It may be why we are struggling so much to determine the heading should be.

**Comment by ibnc** [comment]
@marques-work @kierarad  Since the previous section's heading is "Add Your Pipelines as Code Definition to Your SCM Repository" we could go with "Add your SCM Repository to use the defined config"

Then we can have some kind of help text go along with it, and the heading will go with the flow set by the previous header
