### ISSUE TITLE
label_template HAS to contain ${COUNT}

### ISSUE THREAD

**Issue by boatmisser** [gocd/gocd#7153]
##### Issue Type
- Bug Report

##### Summary
**GoCD Version: 19.7.0**

When creating a pipeline it appears that the `label_template` MUST contain `${COUNT}`, even though the error message implies it's optional.

E.g.
test123
Fails with `Invalid label 'test123'. Label should be composed of alphanumeric text, it can contain the build number as ${COUNT}, can contain a material revision as ${<material-name>} of ${<material-name>[:<number>]}, or use params as #{<param-name>}.`

test123-${COUNT}
Succeeds

`it can contain the build number as ${COUNT}` implies it does not have to.

##### Expected Results
Either the `label_template` should be accepted and used OR the error message should state that `${COUNT}` is mandatory

##### Actual Results
`label_template` is rejected but the error message implies the value used is valid 

##### Possible Fix
Preferably a `label_template` without `${COUNT}` would be accepted and used; alternatively the error message should be explicit in what is and is not permitted.

**Comment by arvindsv** [comment]
`${COUNT}` is not really mandatory. You are allowed to have ${<material-name>}. For instance, this is a valid pipeline config I just created:

```xml
<pipeline name="pipeline1" labeltemplate="${test1}">
  <materials>
    <git url="test-repo" materialName="test1" />
  </materials>
  <stage name="up42_stage">
    <jobs>
      <job name="up42_job">
        <tasks>
          <exec command="ls" />
        </tasks>
      </job>
    </jobs>
  </stage>
</pipeline>
```

**Comment by boatmisser** [comment]
OK, I think I phrased my issue to specifically; I apologize.

Either there is a bug in `label_template` OR the error message is incorrect.
`Invalid label 'test123'. Label should be composed of alphanumeric text, it can contain the build number as ${COUNT}, can contain a material revision as ${<material-name>} of ${<material-name>[:<number>]}, or use params as #{<param-name>}`

This message implies that `test123` is valid as this is alphanumeric text; however this label is rejected!
It also implies that `#{MY_PARAM}` is valid; this is also rejected!
The only labels that are accepted are those that container either `${COUNT}` and/or `${<material-name>}`!

My point is that either such labels as `test123` or `#{MY_PARAM}` should be a valid `label_template` OR the error message should be changed to make it clear that a label MUST container either `${COUNT}` and/or `${<material_name>}`.

**Comment by arvindsv** [comment]
@boatmisser Sure, the message can be changed. What would you recommend? Here are the rules of it, as far as I know:

1. It should either mention a material by name (`${<material-name>}`) or should have `${COUNT}`, in an _attempt_ to have the label change every run of a pipeline.
2. If it has a parameter like `#{MY_PARAM}`, the parameter needs to resolve into some text which satisfies condition 1.
3. The final content of this field should be alphanumeric (I think it can contain some special characters like a hyphen).

Or maybe we should just point to the docs? https://docs.gocd.org/current/configuration/pipeline_labeling.html
