### ISSUE TITLE
Placeholder for Issues with new Environments SPA

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7176]
#### Issues with new Environments SPA

- [x] No confirmation on the delete of an environment.
- [x] Edit environment variables popup should have a fixed height as of pipelines, agents edit popup.
- [x] When there are no physical agents, the edit agents modal shows `No agents matching search text 'undefined' found!` error.
- [x] No Cancel button for edit pipelines, agents and environment variables modal.
- [x]  Misaligned `No pipelines matching search text 'adsfasdf' found!`.
- [x] Misaligned `No agents matching search text 'adsfasdf' found!`.
- [x] Inconsistent popup headers
	- For pipelines - `Edit Pipelines Association`
	- For agents - `Edit Agents Association`
	- For Environment Variables - `Environment Variables`
- [x] Inconsistent save button for edit pipelines, agents and environment variables popup.
- [x] Show agent hostname instead of agent UUID.
- [x] a yellow border is shown at the top of the environment denoting the environment has no pipelines or agents configured. But there is no clear message denoting the same.
- [x] Show message when no environments are configured.
- [x] Add a button group to the delete environment button for consistent styling (across all pages).
- [x] Perform client-side validation of empty-environment-variable-name when an empty environment variable is added to the environment.
- [x] Clicking delete on a collapsed environment causes just <pre>`Are you sure you want to delete environment                      ?` </pre> message to show up, the environment name is rendered a couple of seconds later.
- [x] While the delete operation is in progress, disable `Yes Delete` and `Cancel` buttons and show spinner (to avoid user click `Yes Delete` option multiple times).
- [x] While the create operation is in progress, disable `Save` and `Cancel` buttons and show spinner (to avoid user click `Save` option multiple times).
- [x] Do not allow deletes for config repo environments
- [x] Disable remove environment variable button when it is defined in the config repository.
- [x] Invalid agent count is shown when the environment contains remote agents. (https://github.com/gocd/gocd/issues/7176#issuecomment-559349516)
- [x] Non-existing agent in the remote environment causes the addition of other agents to fail (https://github.com/gocd/gocd/issues/7176#issuecomment-559353500)

#### Possible Improvements

- [ ] Perform the first level of duplicate environment validation at the client-side.
- [ ] Show information about which entity has been defined in which config repository. (Similar to what we've today for the `Unavailable pipelines`)

**Comment by GaneshSPatil** [comment]
Add an ability to link to the individual environment?

Currently, on the dashboard, the pipelines can be grouped using the environment, where the environment header is a link to the environment on the `/go/admin/environments` page.

**Comment by GaneshSPatil** [comment]
@vrushaliwaykole @dhanasp -- The issue ` When there are no physical agents, the edit agents modal shows No agents matching search text 'undefined' found! error.` can still be reproduced.
Can you take a look?

**Comment by dhanasp** [comment]
> @vrushaliwaykole @dhanasp -- The issue ` When there are no physical agents, the edit agents modal shows No agents matching search text 'undefined' found! error.` can still be reproduced.
> Can you take a look?

sure.Will fix it.

**Comment by GaneshSPatil** [comment]
##### Issue
Invalid agent count is shown when the environment contains non-existing remote agents.

##### Steps to Reproduce
1. Start a local agent (say `agent-1`).
2. Verify `agent-1` shows up on the agents' page.
3. Define a config repo environment with the above agent.
```
{
  "format_version" : 1,
    "name" : "dev",
    "agents" : [ "agent-1" ]
}
```
4. Verify `dev` environment shows up on the agents page.
5. Disable and then delete `agent-1` from the agents page.
6. Visit the environments page.

##### Actual Result
`Agent Count` is shown as `1` on the environment row, whereas, expanding the environment body shows no agent.

<img width="1418" alt="Screen Shot 2019-11-28 at 11 06 51 AM" src="https://user-images.githubusercontent.com/15275847/69779814-49a9f900-11cf-11ea-88f4-99b2fa850a59.png">


##### Expected Result
Environment row should show 0 as the `Agent Count`

**Comment by GaneshSPatil** [comment]
##### Issue
Non-existing agent in the remote environment causes the addition of other agents to fail

##### Steps to Reproduce
1. Start two local agents (say `agent-1` and `agent-2`).
2. Verify `agent-1` and `agent-2` shows up on the agents' page.
3. Define a config repo environment with the `agent-1` agent.
```
{
  "format_version" : 1,
    "name" : "dev",
    "agents" : [ "agent-1" ]
}
```
4. Verify `dev` environment shows up on the agents page.
5. Disable and then delete `agent-1` from the agents page.
6. Edit the agents of the `dev` environment.
7. `agent-2` should be shown as `Available Agents`.
8. Selecting an saving `agent-2` fails with an irrelevant error `Agents with uuids '38456b88-5650-4111-9860-6b0325f9eb87' were not found!`

##### Actual Result
Adding `agent-2` to the `dev` environment fails with `Agents with uuids '38456b88-5650-4111-9860-6b0325f9eb87' were not found!` error
<img width="800" alt="Screen Shot 2019-11-28 at 11 26 37 AM" src="https://user-images.githubusercontent.com/15275847/69780722-0735eb80-11d2-11ea-82dd-0936565e4797.png">


##### Expected Result
It should allow adding `agent-2` to the `dev` environment

**Comment by rajiesh** [comment]
Closing this issue. Any improvements needed on environments page will create separate issue for them
