### ISSUE TITLE
Feature Toggles API does not allow modifying toggle value with case insensitivity

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7183]
##### Issue Type

- Bug Report

##### Summary

Feature toggles API does not allow modifying the feature toggle value with case insensitivity. 
Today, the toggle value must be passed as lower case "on" or "off".

##### Expected Results
Feature toggles API should allow modifying the feature toggle value with case insensitivity. 

##### Actual Results
Feature toggles API fails to modify the feature toggle value. 

##### Possible Fix
Change `toggleValue.equals("on")` on [this](https://github.com/gocd/gocd/blob/master/api/api-feature-toggles-v1/src/main/java/com/thoughtworks/go/apiv1/featuretoggles/FeatureTogglesControllerV1.java#L84) line to `toggleValue.equalsIgnoreCase("on")`.

**Comment by rajiesh** [comment]
Verified on 19.11.0 (10683-fc7710d5f3ada94af6cce76a704b224f79a86cf7)
