### ISSUE TITLE
Placeholder issue for new Admin pipeline page

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#7198]
##### Issue Type

- Bug Report

##### Summary

Placeholder issue for all issues related to new admin pipelines page

##### Issues

- [x] Group admins are allowed to view all the groups/pipelines on new admin pipeline page. To reproduce create 2 groups( say G1 and G2). Make user `GA` as group admin of only group G1. Now if user `GA` visits `/go/admin/pipeline_new` page user can see both groups `G1` and `G2`. However as expected user `GA` cant perform any operations on `G2` since APIs validate the authorizations

- [x] Group admin user should see the `Create new pipeline group` option. Lets disable it for group admins

- [x] On cloning of pipeline old flow takes user to cloned pipeline edit page, so that user can update the pipeline as necessary. Lets retain the same behavior with the new page too

**Comment by GaneshSPatil** [comment]
Add an ability to link to the individual pipeline group?

Currently, on the dashboard, the pipelines can be grouped using the pipeline group, where the pipeline group header is a link to the pipeline group on the `/go/admin/pipelines` page.

**Comment by ketan** [comment]
>Add an ability to link to the individual pipeline group?

I believe I've addressed this in the new pipelines page.
