### ISSUE TITLE
Add support for OpenID Connect auth

### ISSUE THREAD

**Issue by Kyle-Xie** [gocd/gocd#7202]
##### Issue Type
- Feature proposal

##### Summary
Currently, we have a LDAP plugin for 3rd login. Do we have any plan to add an OpenID plugin?

**Comment by ketan** [comment]
Is there a specific provider you're looking to integrate with?

PS: this is not planned by the core team. However the team is happy to help you implement a plugin.

**Comment by arvindsv** [comment]
Closing as stale.

**Comment by murilodag** [comment]
Hello @ketan and @arvindsv,

Would it be possible to create the plugin for Open ID using Microsoft?

**Comment by arvindsv** [comment]
@murilodag As Ketan mentioned above, if anyone wants to, then it is possible. This is likely the documentation you'll need: https://plugin-api.gocd.org/current/authorization/
