### ISSUE TITLE
Permit "pinning" a version of an upstream material

### ISSUE THREAD

**Issue by sriramnrn** [gocd/gocd#721]
I would sometimes like to pin an upstream material version to a specific known version. This is helpful when the upstream component is undergoing some churn, and I need to use a known stable version of it.

While I could use the upstream artifact as a library artifact, continuing to use it via Go lets me benefit from the Value Stream Map that Go provides.

**Comment by Thanh88Nguyen** [comment]
Hi, I am interest in having "pin" functionality in GoCD.
Is there a way to do that now ?
