### ISSUE TITLE
Error messages on agents SPA not getting displayed.

### ISSUE THREAD

**Issue by vrushaliwaykole** [gocd/gocd#7212]
##### Issue Type
- Bug Report

##### Summary
Errors and warning messages are not displayed on the Agent SPA

##### Steps to Reproduce
1. Go to Agents Tab.
2. Select the pending agent.
3. Add resources or environments

##### Expected Results
It should display some error message as pending agents need to be enabled.

##### Actual Results
No error message is displayed on the Agents page.

**Comment by rajiesh** [comment]
Verified on 19.11.0 (10685-a26556d1f0e02fa2859d8996fa95b1c5731ec4dd)
