### ISSUE TITLE
We need concept diagrams on PaC page:

### ISSUE THREAD

**Issue by loudaTW** [gocd/gocd#7227]
1. For all the pipeline config parts, just like in the wizard
2. New ones (maybe in the download section) to explain the flow (and why):
    - Download config
    - Add to repo
    - "Connect repo to this server"

**Comment by ibnc** [comment]
@loudaTW @streisguth @marques-work what do y'all think about something like the diagram in the pac builder mock up that @marques-work and @kierarad made?

**Comment by streisguth** [comment]
Zipped file with PaC Server Loading diagrams attached, as well as a full-size diagram at 440x400px.
Also included is a cover image that says 'Pipelines as Code' to act as a separator between the GoCD concepts and the PaC concepts (if we desire for it to be there.

[Diagrams - Pipelines as Code.zip](https://github.com/gocd/gocd/files/3860890/Diagrams.-.Pipelines.as.Code.zip)

Text for each of the Server Loading Diagrams is as follows:
"User commits configurations to SCM Repository"
"Once connected to the SCM Repository,the GoCD server watches for changes."
"GoCD creates/updates pipelines from changes in configuration files."
