### ISSUE TITLE
Speed up save on PIpeline config pages

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#7229]
Background: Currently the Save on Pipeline Config pages invokes `GoConfigService.updateConfigFromUI`, which is slow, since it operates on the entire cruise-config.xml. The API calls, on the other hand, use `UpdatePipelineConfigCommand`, which is faster. A quick way to make the rails pages faster would be to use this Command instead.

We have the following operations on the Pipeline Config pages (leaving aside the "create" wizard)
- [x] Pipeline Update
- [x] Stage Create
- [x] Stage Update 
- [ ] Stage Delete
- [ ] Material Add
- [ ] Material Update
- [ ] Material Delete
- [x] Job Create
- [x] Job Update
- [ ] Job Delete
- [x] Task Create
- [x] Task Update
- [ ] Task Delete
- [ ] Task reorder

**Comment by akshaydewan** [comment]
Existing issues:
- Job Timeout - entering a non-number does not show a field-level error
- Entering a non-number in `Run x instances` gives a NumberFormatException
- No Validation errors are shown on External Artifact config
- Add a "fetch artifact" task > enter "a" in all fields > save > no validation errors displayed on the field level

**Comment by arvindsv** [comment]
@maheshp Do you know whether we can close this?

**Comment by maheshp** [comment]
Not all actions listed above are moved to use the API calls, but a few important/widely used once are. I will close this issue for now since currently there is no plans to change the other actions. We can create a new issue when required.
