### ISSUE TITLE
Try pipeline configurations without pushing them into config repo

### ISSUE THREAD

**Issue by NikoHeikki** [gocd/gocd#7236]
##### Issue Type

- Feature proposal

##### Summary

Create way to edit/try pipeline configurations without pushing changes into git, now when changes need all to be committed into git, if you dont know that they will work, you will propably have to make more commits to fix another commits or amend previous one, but could there be some pipeline editor inside gocd which allows to test pipeline yamls or json without committing them into git, this also is lot faster than waiting for gocd to pull changes, or go manually trigger the polling

**Comment by arvindsv** [comment]
@NikoHeikki This is already a functionality of the plugins.

https://github.com/tomzo/gocd-json-config-plugin#Validation

https://github.com/tomzo/gocd-yaml-config-plugin#Validation

Closing this for now.
