### ISSUE TITLE
Introduce versioned Agent Job History API

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7269]
##### Issue Type

- Feature enhancement
- Technical Debt

##### Summary

Migrate existing rails based agent job history API to versioned spark API
The version of the newly implemented agent job history API will be `v1`.

**Comment by GaneshSPatil** [comment]
#### Add an ability to specify `page_size` as part of the request

The current API returns only 10 results (job history items). The number of items retrieved is denoted by the `page_size` attribute. Whereas, the API does not have the capability to accept `page_size` input.

#### Why do we need to have configurable `page_size`?

The Agent Job History API can be used on the `Agent Details Page` (upon migration from rails to SPA). The current page renders 50 job history items per page. 

Without the ability to specify `page_size` as part of the Agent Job History API, we will be forced to show only 10 job history items per page.

#### Possible Solution

Modify the API to `GET /go/api/agents/:uuid/job_run_history[/:offset][/:page_size]` where specifying `offset` and `page_size` is optional.

Need to change [this](https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/app/controllers/api/agents_controller.rb#L27) hardcoded value to user input.

**Comment by ketan** [comment]
> Add an ability to specify `page_size` as part of the request

Yes. I'll do this as part of the PR. Might need to setup some reasonable upper limits on `page_size` to not strain the DB too much.

**Comment by GaneshSPatil** [comment]
Done as part of https://github.com/gocd/gocd/pull/7274 PR.
