### ISSUE TITLE
Agents page constantly shuffles agents

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7281]
##### Issue Type

- Bug Report

##### Summary

Agents page keeps shuffling the agents (on every AJAX refresh).

##### Description

The Agents Page renders agents received from the Agents API. The Agents API renders the agents in an unordered manner. Causing the agents to shuffle at the UI.

> Why do agents shuffle the order even after sorting?

One or more agent can have a duplicate value for the column on which the agent is sorted. For Example: `Agent State`. In such scenarios, it will shuffle the agents based on received order from the API.

###### Basic environment details

* Go Version: `19.10.0`

##### Steps to Reproduce

1. Start 2 Agents
2. Make sure the agents are sorted by the default sorting column (Agent State)
3. Keep the page open for 10+ secs.
4. The order of the agents will be shuffled.

##### Expected Results
The agent order should not be shuffled. 

##### Actual Results
The agent order is shuffled. 

##### Possible Fix
Sort agents based on the combination of `column_name` and `agent_uuid` to make sure that the agents are sorted in the same order even when more than one agent has the same value for the `column_name`.
Note: `agent_uuid` is unique causing a consistent sort order.

**Comment by rajiesh** [comment]
Verified on 19.11.0 (10683-fc7710d5f3ada94af6cce76a704b224f79a86cf7)
