### ISSUE TITLE
Difficult to say if tables are sorted ASC or DESC

### ISSUE THREAD

**Issue by ketan** [gocd/gocd#7284]
##### Issue Type

- Bug Report

##### Summary

Looking at the agents table, it's difficult to say how a column is sorted. There are no special indicators to indicate "unsorted", "ascending" or "descending sort". Additionally, I can't say for sure if "unsort" is supported, where clicking a column, sorts it asc -> desc -> back to original order.

**Comment by kritika-singh3** [comment]
Fixed in #7344 in GoCD Release 19.11.0
