### ISSUE TITLE
Place holder for issues on Roles SPA

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#7297]
As part of supporting granular auth https://github.com/gocd/gocd/issues/7222, the Roles  SPA was modified to support `policy`. Below is the list of issues on the Roles SPA,

- [x] Error while adding policy to roles if none of the attributes are selected. Add a client side error handling before making a API call. 
- [x] When a new role is added, a default Deny policy is added. Is this required or do we leave it upto to the user to add a policy?
- [x] The current message `The default policy is to deny access to all GoCD entities. Configure permissions below to override that behavior.` seems confusing. We need to change the message and provide link to Policy documentation.

**Comment by kritika-singh3** [comment]
Created PR #7292 for first 2 points:
 1. Added client side validations for policy 
 2. Removed the default policy added when a new role is added. The user needs to add a new permission as per his/her need.

**Comment by adityasood** [comment]
- [ ] `All` under the action list is misleading. `Administer` is what `All` would mean. We should remove that

- [ ] `All` under the type should be removed. We can add it once we have more than one entity to support

- [ ] Order of the actions can be `Allow` and `Deny`. This is more semantic. can be ignored

**Comment by kritika-singh3** [comment]
@adityasood In reference to point 1 and 2, we have support for `*` for `type` and `action`.
Semantically, yes `*` and `administer` are one and the same. But if someone specifies the following: `<allow type="*" action="*">*</allow>`, without `All` the dropdown for respective attribute will be rendered blank. Hence, our decision of adding `All`.

![policy](https://user-images.githubusercontent.com/41165891/69776425-38a6bb00-11c2-11ea-8a8b-f0eecd42e39d.gif)

Point 3 sounds right. Will implement the same.

cc:/ @GaneshSPatil

**Comment by adityasood** [comment]
@kritika-singh3 @GaneshSPatil 

Point 1: Since both All and administer are essentially the same I am of the opinion we should drop the support for * from the policy for actions. 

For point 2: We can keep the (*). We will document it properly

**Comment by rajiesh** [comment]
Verified on 19.11.0 (10687-c532a61bb240ffbe59fe356445bea6433005563f)
