### ISSUE TITLE
Add wrapper-config files to the GoCD backup process

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#7301]
##### Issue Type

- Feature enhancement

##### Summary

Currently, the files under `/usr/share/go-server/wrapper-config` are not backed up and needs to be recreated when the GoCD server is restored with the backup data.

**Comment by malkk** [comment]
Without these files being backed up, a restore of the server will fail on all but the most basic implementations.  Prior to the changes in 19.6, you could rely on the backup to have all the necessary information.  For this reason, I consider this a break/fix and not a feature enhancement.  Lack of this is preventing us from upgrading to current versions.

**Comment by rajiesh** [comment]
Verified on 19.11.0 (10687-c532a61bb240ffbe59fe356445bea6433005563f)
