### ISSUE TITLE
Extracting a template from the Config Repo pipeline through UI fails with irrelevant error

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7318]
##### Issue Type

- Bug Report

##### Summary

Extracting a template from the config repo pipeline through UI fails with `Pipeline with name 'some-pipeline' was not found!` error even when specified config repo pipeline exists on the server.

###### Basic environment details

* Go Version: `19.11.0`

##### Steps to Reproduce

1. Define `pipeline1` pipeline in a config repository.
2. Visit new templates SPA.
3. Click `Create New Template` button.
2. Select `Extract from pipeline` option for creating a new template.
3. Select the `pipeline1` pipeline.
4. Click Extract.

##### Expected Results

Extract a template from the pipeline option should not available for Config Repo Pipelines.

##### Actual Results

Extract a template from the config repo pipelines fails with `Pipeline with name 'some-pipeline' was not found!`

##### Possible Fix
Do not show config repo pipelines in the pipelines dropdown for extract a template.

**Comment by rajiesh** [comment]
Verified on 19.12.0 (10885-3f91d1e16269ce7f01ef6d37a7bd5792ae28b4bc)
