### ISSUE TITLE
Support for SAML or SSO as a user store method

### ISSUE THREAD

**Issue by regardt-meyer** [gocd/gocd#733]
We are using Go and have a large user base, this is integrated to our LDAP (AD) store which is great. We are expanding our Go servers to be accessible from all our offices around the globe and some of these will have different LDAP servers. Instead of just allowing us to configure more than one LDAP server and tree it would be great if go support SAML for authentication, that way all the responsibility can be delegated to OKTA which we use as our SSO solution.

**Comment by srinivasupadhya** [comment]
You should be able to write an [authentication plugin](http://www.go.cd/documentation/developer/writing_go_plugins/authentication/authentication_plugin_overview.html) & [web request handling ability](http://www.go.cd/documentation/developer/writing_go_plugins/handling_web_requests.html). Reference -[Sample plugin](https://github.com/gocd/go-plugins/tree/master/plugins-for-tests/test-authentication-plugin), [GitHub OAuth plugin](https://github.com/srinivasupadhya/gocd-oauth-login)

**Comment by clearly** [comment]
@regardt-meyer We are also interested in an okta auth plugin. If your group developed one and is willing to share please comment. Otherwise we may independently develop one.

**Comment by regardt-meyer** [comment]
@clearly We have not done any development on the okta auth plugin. Happy to contribute once you guys start. At the moment we use a Virtual AD server to work around our issue.

**Comment by lenucksi** [comment]
:+1:

**Comment by arvindsv** [comment]
Closing this as it should be a plugin, as mentioned. Nothing to do from the GoCD side at this point.

**Comment by szamfirov** [comment]
You guys might want to check this out: https://github.com/szamfirov/gocd-okta-oauth-authorization-plugin

**Comment by ketan** [comment]
@szamfirov do you mind submitting a PR in this file (https://github.com/gocd/www.go.cd/blob/master/data/authorization_plugins.yml) so it appears on the website?

**Comment by ketan** [comment]
Oh, and maybe send an email to the mailing list so people are aware.
