### ISSUE TITLE
Inconsistent delete behavior of Pipeline Group SPA and Pipeline Group API

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7332]
##### Issue Type

- Bug Report

##### Summary

Pipeline Group API allows the deleting of the pipeline group containing only remote pipeline(s), whereas, on the Pipeline Config SPA, the delete pipeline group button is disabled.

##### Steps to Reproduce

1.  Define `pipeline-1` pointing to the group `group-1` in a config repository.
2. Verify `pipeline-1` and `group-1` shows up on the UI
3. Visit the Pipeline Group SPA page; Verify delete icon for the `group-1` is disabled.
4. Use Pipeline Group API to delete the `group-1`. The deletion of the `group-1` is successful with `Pipeline group with name 'group-1' was deleted successfully!`

##### Expected Results
Pipeline Group SPA and Pipeline Group API should have consistent behavior. Pipeline Group API should not allow deletion of pipeline group when it contains a pipeline (nevertheless of the pipeline origin)

##### Actual Results
Pipeline Group API allows deletion of pipeline group when it contains only remote pipelines

### Weird Behavior

Pipeline groups are not defined config repository, hence, when the config repository pipeline `pipeline-1` is merged with the GoCD config, we define an empty pipeline group `group-1`.

**After the deletion of the `group-1`, the GoCD configuration on the disk and the config object in memory goes out of sync.**

Because after the deletion of the group, the `pipeline-1` points to a non-existing group, the config object in the memory believes there is a group with name `group-1`, whereas there is no pipeline group!

As `pipeline-1` points to the non-existing `group-1`, the group shows up on the UI. Visiting the `edit`  page of the `group-1` fails with a **404** `Pipeline group with name 'group-1' was not found!` error.

**Comment by rajiesh** [comment]
Verified on 19.11.0 (10687-c532a61bb240ffbe59fe356445bea6433005563f)
