### ISSUE TITLE
Move Package Repositories SPA to typescript

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#7333]
The current Package Repo page needs to be moved from rails to typescript

Here's what the current UI looks like:
<img width="1440" alt="Screenshot 2019-11-28 at 14 36 42" src="https://user-images.githubusercontent.com/6024038/69792527-d44d2100-11ec-11ea-9159-5bba122f6483.png">
<img width="1440" alt="Screenshot 2019-11-28 at 14 37 50" src="https://user-images.githubusercontent.com/6024038/69792531-d57e4e00-11ec-11ea-9df7-31fcbd59dcb7.png">

Points to discuss:
- The package repo containing packages looks similar to Cluster Profiles and Elastic Profiles. Should we use a similar layout for the new SPA? The nesting of expandable panels can be confusing for users, as we've seen on that page. Alternately, we can retain the tree structure.
- Currently the page doesn't allow packages to be added inside the repo. This needs to be done via the Pipeline config page. I think we should allow this in the new SPA for a smoother flow, and for simplifying the Pipeline Config SPA in the future.

**Comment by arvindsv** [comment]
I agree about point 2. It makes sense to allow creating packages here.

**Comment by kritika-singh3** [comment]
For the point 1: I prefer a layout similar to what we have on Elastic Agent Configurations SPA.
Reason: It is a much cleaner and concise representation of what the package repositories and packages represent.
What I would suggest is that the outer panel is always expanded as on Pipelines SPA. It would help to reduce the confusion regarding nested expandable panels.

WDYT? @gocd/committers

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.3.0 (11521-f0170986bb47797b6ccf130e1ccb87736b45b372)
