### ISSUE TITLE
LDAP with GoCD - Locked out

### ISSUE THREAD

**Issue by vdonldsn** [gocd/gocd#734]
I have a service account established in Company's LDAP system configurator. I have followed the steps to set up the LDAP in Go for our company with my respective service account credentials. Go is now prompting with a sign in screen as I expected, but I am unable to log in with credentials from:  my service account(which LDAP was configured for; my company log in; the service account given to thougthworks(svc.us-p-jenkins-tfs); nor the original admin account 

I am being prompted at the top of screen with red circle with exclamation in it stating: Failed to authenticate with your authentication provider. Please check if your authentication provider is up and available to serve requests.

I checked the service account credentials in the LDAP system directly and it went through  seamlessly. 
I tried to provide as much detail as possible however please reach out to me for further explanation if I wasn’t explicit enough Maybe you can help!

**Comment by TraviisD** [comment]
Life saver!

**Comment by nirs5366** [comment]
Thanks a lot.. you really saved my day!

**Comment by BurkovBA** [comment]
@arvindsv This post should be a part of configuration documentation. It never mentions that `cruise-config.xml` is located in `/etc/go/cruise-config.xml`.

**Comment by markmnl** [comment]
go-server seems to reject my changes (removing security element altoghther or using password file) as invalid and somehow remembers last config file and overwrites my changes each time..

**Comment by arvindsv** [comment]
@markmnl If you're using a recent version of GoCD (as you should be), the syntax has changed a bit. You'll see something like:

```
<security>
  <authConfigs>
    <authConfig id="ldap-auth-config" pluginId="cd.go.authentication.ldap">
      ...
    </authConfig>
  </authConfigs>
</security>
```

There could be multiple `<authConfig>` tags. They're all checked in order. What I would do is to add one more to it (don't necessarily need to remove the others):

```
<authConfig id="file-auth-config" pluginId="cd.go.authentication.passwordfile">
  <property>
    <key>PasswordFilePath</key>
    <value>/etc/go/password.properties</value>
  </property>
</authConfig>
```

That'll make it use the [gocd-filebased-authentication-plugin](https://github.com/gocd/gocd-filebased-authentication-plugin). The instructions to use it are in the README there. But, the instructions in the comment above should work too. One change to improve on the above comment would be to bcrypt for password generation. Something like:

```
htpasswd -c -B -s /dev/tty admin
```

By the way, it's always a good idea to have a file-based auth config in your GoCD config for situations such as this. Once you get in, I'd recommend not removing the password file. Just make sure to use a strong password.

**Comment by AminNadimi** [comment]
Removed whole <security>: No effect
security tag comes back in full after `systemctl restart`

**Comment by AminNadimi** [comment]
Managed to fix the issue not sure how but there were several restarts.
Change config files: 
```
/etc/go/cruise-config.xml
/var/lib/go-server/db/config.git/cruise-config.xml
```
No need to restart services after change. They apply as soon as you edit config file
