### ISSUE TITLE
Visiting edit pipeline configuration page for non existing pipeline fails with 500 error

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7346]
##### Issue Type

- Bug Report

##### Summary

Visiting edit pipeline configuration page for non-existing pipeline fails with 500 error.

###### Basic environment details

* Go Version: `19.10.0`

##### Steps to Reproduce

1.  Visit https://build.gocd.org/go/admin/pipelines/build-asdf-linux/general
![Screen Shot 2019-11-29 at 3 16 45 PM](https://user-images.githubusercontent.com/15275847/69859991-4db34500-12bb-11ea-9130-e35fb57ba56a.png)

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/6363 PR in https://github.com/gocd/gocd/pull/6363/commits/79a0317f0ca0942c3251f25d232afdcd644aefe6 commit

**Comment by adityasood** [comment]
verified: 19.12.0 (10802)
