### ISSUE TITLE
Pipeline group or templates admin/view user does not see Environments link when given permissions via Policy

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#7349]
##### Issue Type
- Bug Report

##### Summary

If a user is given the view or admin permissions for a Pipeline Group the admin dropdown on the dashboard does not show environments link even when explicit allow is given to user role via a policy.

###### Basic environment details

* Go Version: 19.11.0-10678

##### Steps to Reproduce

1. Create a user 'groupadmin'
2. Grant view permission to defaultGroup for the user 'groupadmin'
3. Configure a test role and assign 'groupadmin' user to it. 
4. Create a policy to view any environment for the role 'test'
5. Logout and login as 'groupadmin'
6. The admin dropdown should have environment link listed

##### Expected Results
The admin dropdown should have environment link listed for the above scenario

##### Actual Results
The admin dropdown does not have environment link listed

**Comment by adityasood** [comment]
the above is also true if a user is given view/admin permission on templates

**Comment by GaneshSPatil** [comment]
Fixed as part of #7350
