### ISSUE TITLE
Viewing templates configurations from pipeline configurations page returns  404

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7352]
##### Issue Type

- Bug Report

##### Summary

Viewing templates configurations from stages tab of pipeline configurations page throws a 404 not found error.

<img width="1271" alt="Screen Shot 2019-12-02 at 8 46 01 PM" src="https://user-images.githubusercontent.com/15275847/69970784-dabcff00-1544-11ea-8945-85cffdf859fd.png">

###### Basic environment details

* Go Version: `19.11.0 (10641-dd47ed67222f3ed382f5334bc445e6bfa294b56f).`

###### Additional Environment Details

1. Visit https://build.gocd.org/go/admin/pipelines/build-linux/stages?current_tab=stages link
2. Click on `view` template configurations button.

**Comment by maheshp** [comment]
This issue is fixed by bringing back the old templates read-only view for now - https://github.com/gocd/gocd/pull/7353

@GaneshSPatil is exploring options to use the new templates read-only view.

**Comment by rajiesh** [comment]
Verified on 19.11.0 (10687-c532a61bb240ffbe59fe356445bea6433005563f)
