### ISSUE TITLE
Read only templates view jumps as we switch between stages/jobs

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7357]
##### Issue Type

- Feature enhancement

##### Summary

Read-only templates view changes the height of the popup as we switch between stages/jobs. As the modal height is changing on every switch, it gives a feeling of modal contents are jumping.

##### Expected Results
Read-only templates view should not change the modal height based on the content.

##### Actual Results
Read-only templates view jumps as we switch between stages/jobs

##### Possible Fix
Use fixed height for the read-only templates view modal. This can be achieved by adding `this.fixedHeight = true;` line in the [this](https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/modals.tsx#L114-L120) constructor.

**Comment by rajiesh** [comment]
Small alignment also to be fixed in case of multiple jobs in template, moving this issue to the next release

![Templates-read-only-view](https://user-images.githubusercontent.com/6533924/71163415-0b09da80-2273-11ea-91f2-339e18101362.gif)

**Comment by GaneshSPatil** [comment]
Verified the [UI alignment issue fix](https://github.com/gocd/gocd/issues/7357#issuecomment-567417821) on GoCD Version: 20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0).
