### ISSUE TITLE
server configuration page - checkbox for setting allowOnlyKnownUsersToLogin attribute

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#736]
checkbox for `allowOnlyKnownUsersToLogin` ('Allow users that exist in LDAP or in the password file to log into Go, even if they haven't been explicitly added to Go.') does not work as expected

steps:
* check & save - works
* uncheck & save - doesn't work. the options says checked.

analysis:
* there is hidden field set to current value. this is to handle case when the checkbox is unchecked & saved. but the hidden field value should be updated on checkbox update?

**Comment by stretch327** [comment]
Agreed. Even more troubling is that if you set the value to "true" in Config XML and then modify the config using the Server Configuration tab, your setting gets lost. This is a HUGE problem if you use the same auth file as you use for SVN and there are users in there that shouldn't have access.

**Comment by salizzar** [comment]
I confirmed this issue today with the same behaviour as @srinivasupadhya described.

**Comment by rajiesh** [comment]
verified on GoCD version 16.11.0 (4149-b4245e3fc79af9e07e748160084c66577125b05a), working as expected
