### ISSUE TITLE
Groovy DSL Config Repository plugin fails to export pipeline config having external artifacts

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7378]
##### Issue Type

- Bug Report

##### Summary

Groovy DSL Config Repository plugin fails to export pipeline configuration which defines an external artifact as part of a job

###### Basic environment details

* Go Version: `19.11.0`
* Groovy DSL Plugin Version: `1.0.2-129`

##### Steps to Reproduce

1.  Install any external artifact repository plugin 
2. Define an artifact store.
3. Define an external artifact as part of a job configuration.
4. Hit export pipeline configuration. The export_pipeline API call fails with a 422 error.

##### Expected Results
Groovy DSL plugin should successfully export the pipeline containing an external artifact config as part of a job.

##### Actual Results
Groovy DSL plugin fails with a 500 error to export the pipeline containing an external artifact config as part of a job.

**Comment by kritika-singh3** [comment]
The issue was with Groovy plugin. The same has been updated to accept and parse `fetch` task for external artifacts.
The experimental plugin jar can be found [here](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/releases/tag/v1.0.3-145-exp).

**Comment by kritika-singh3** [comment]
A stable release for the groovy plugin has been released and can be found [here](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/releases/tag/v1.0.3-146). This release fixes the issue.
