### ISSUE TITLE
Possible Improvement while fetching entity information on roles spa load

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7381]
##### Issue Type

- Feature enhancement
- Technical 

##### Summary

Make improvements to the fetching entity logic on roles page load.

To help end-user configure policies for different GoCD entities, we provide entity auto-suggestions.
Example: While defining policy for the environment, we show auto-suggestions for environment name.
To provide auto-suggestions, we need to know all the GoCD entities upfront. And this entity information is fetched on roles SPA load.

As with the increase in the number of entities supporting policies, the number of API calls made to get this information on roles page increases. 
We should not make multiple API calls because:
1.  A single API failure can result in page load failure.
2. Multiple API calls should not be made to fetch the relevant piece of information.

###### Possible Fix:

- Sending entity information as part of the embedded `meta` field on the page (as this information is fetched only on the page load). This approach would avoid all API calls.
- Replacing all the API calls with only one internal API which returns all the entity information.

Know More: https://github.com/gocd/gocd/pull/7271#pullrequestreview-327346302

**Comment by kritika-singh3** [comment]
Fixed a part of #7431. Sending all the necessary info for roles and auto complete suggestions as a part of a single internal API call.
