### ISSUE TITLE
The new server congfig spa jumps when the tabs are switched on a fresh page load

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#7383]
![server-config-spa](https://user-images.githubusercontent.com/17826464/70228275-14c31680-177a-11ea-8747-5c51d59c778b.gif)

If you observe the gif above, the data for the fields is populated in a slight delay to the rendering of the fields which makes it look like a jump.

Suggestion: Add a spinner.

**Comment by GaneshSPatil** [comment]
Do you think this can be achieved by having a fixed position for the `save` and `cancel` button to the bottom of the page?
