### ISSUE TITLE
GoCD Material not pulling most recent revision from TFS

### ISSUE THREAD

**Issue by recnelis** [gocd/gocd#7387]
Issue Type: Bug?

I have a very strange issue.  I have multiple pipelines that talk back to a TFS server.  For whatever reason the pipelines are NOT fetching the most recent revision.  In fact its several revisions behind.  

Ive created new pipelines with new environments and it still wont pull the most recent version.
The original pipeline was SCP_BUILD and i couldnt get it to get any higher revision than 162174.
I clone the pipeline manually and named it SCP_BUILD_New.  It pulled a newer version 162211.  
We are trying to get to 162284..

If I try and click the trigger-pipeline button it sits there and never runs.  Just gets stuck in scheduling.

Has anyone run into this before?

![image](https://user-images.githubusercontent.com/25106799/70264155-8476d880-175d-11ea-9dc8-3778af3f6495.png)

**Comment by rajiesh** [comment]
@recnelis When you tried this

> If I try and click the trigger-pipeline button it sits there and never runs. Just gets stuck in scheduling.

Is there any server health messages shown on top right corner of the page? Or any logs in `<server-working-directory>/logs/go-server.log` file to indicate the scheduling is stuck or material update is failing? Could you please share the message/log if there are any

If the server is unable to pull the latest revisions logs should help us know why its happening.
