### ISSUE TITLE
Add support for edit as action in policy

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#7390]
##### Issue Type

- Feature enhancement

##### Summary

Add support for `edit` as `action` in policy.

###### Implementation for entities:

1. Environment: The users with this permission will have access to view and update the specified resource.
2. Config-Repo: The users with this permission can view, update the config-repo as well as trigger an MDU.

**Comment by GaneshSPatil** [comment]
### Verificiation: Support Edit Action for Policies
  - [ ] Support defining edit action on policies via xml.
  - [ ] Support defining edit action on policies via roles SPA.
  - [ ] Environments Edit Policy
  	- [ ] Environments Public API
      - [ ] A user with edit policy permission should be allowed to get all visible environments.
      - [ ] A user with edit policy permission should be allowed to view permissible environment.
      - [ ] A user with edit policy permission should be allowed to edit the environment.
      - [ ] A user with edit policy permission should be allowed to patch the environment.
      - [ ] A user with edit policy permission should not be allowed to delete the environment.
      - [ ] A user with edit policy permission should not be allowed to create an new environment.
  	- [ ] Environments Internal API
      - [ ] A user with edit policy permission should be allowed to get all visible environments.
      - [ ] Environments Internal API should return permissions (`can_edit`, `can_administer`) as part of response
      - [ ] A user with edit policy permission should be allowed to update environment agent association.
  	- [ ] Environments SPA
      - [ ] A user with edit policy permission should be allowed to get all visible environments.
      - [ ] A user with edit policy permission should be allowed to modify environment pipeline association.
      - [ ] A user with edit policy permission should be allowed to modify environment agent association.
      - [ ] A user with edit policy permission should be allowed to modify environment variables.
      - [ ] A user with edit policy permission should not be allowed to delete the environment. (Disabled delete icon)
      - [ ] A user with edit policy permission should not be allowed to create an new environment. (Failure on create)
  - [ ] Config Repository Edit Policy
  	- [ ] Config Repos Public API
      - [ ] A user with edit policy permission should be allowed to get all visible config repos.
      - [ ] A user with edit policy permission should be allowed to view permissible config repo.
      - [ ] A user with edit policy permission should be allowed to edit the config repo.
      - [ ] A user with edit policy permission should be allowed to perform preflight check on a config repo.
      - [ ] A user with edit policy permission should not be allowed to delete the config repo.
      - [ ] A user with edit policy permission should not be allowed to create a new config repo.
  	- [ ] Config Repos Internal API
      - [ ] A user with edit policy permission should be allowed to get all visible config repos.
      - [ ] A user with edit policy permission should be allowed to view permissible config repo.
      - [ ] Config Repos Internal API should return permissions (`can_edit`, `can_administer`) as part of response.
      - [ ] A user with edit policy permission should be allowed to view config repo in-progress status.
      - [ ] A user with edit policy permission should be allowed to trigger config repo update.
      - [ ] A user with edit policy permission should be allowed to view entities coming from config repo.
  	- [ ] Cofig Repos SPA
      - [ ] A user with edit policy permission should be allowed to get all visible config repos.
      - [ ] A user with edit policy permission should be allowed to edit the config repo.
      - [ ] A user with edit policy permission should be allowed to trigger config repo update.
      - [ ] A user with edit policy permission should be allowed to view entities coming from config repo.
      - [ ] A user with edit policy permission should not be allowed to delete the config repo. (Disabled delete icon)
      - [ ] A user with edit policy permission should not be allowed to create an new config repo. (Failure on create)

**Comment by GaneshSPatil** [comment]
This feature has been deprioritized as there was no concrete reasoning behind for adding `edit` policy action support.

Closing...
