### ISSUE TITLE
Tooltip for Resource gets cut from view on Roles page

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#7391]
<img width="1680" alt="Screenshot 2019-12-06 at 11 16 28 AM" src="https://user-images.githubusercontent.com/6024038/70299091-e6951380-1819-11ea-9816-021b3e224041.png">

**Comment by rajiesh** [comment]
Verified on 19.12.0 (10842-29a6623b57f6c7224c75549a451965a2580dfada)
