### ISSUE TITLE
Server configuration link in preferences tab when smtp is not set
redirects user to config xml page instead of server configuration
page

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#74]
### Steps to reproduce
- Enable security but do not set smtp settings
- Access preferences page.
- There is a message asking the user to set smtp settings. The link's label is -Server Configuration. Click on this link.
#### Expected result

User should be directed to server configuration page
#### **Current result**

User is redirected to config xml page instead of server configuration page

**Comment by varshavaradarajan** [comment]
Can be closed. Points to the right URL now.
