### ISSUE TITLE
Enable settings icon for config repo pipelines from all GoCD pages

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7401]
##### Issue Type

- Feature enhancement

##### Summary

Display/Enable settings icons for config repo pipelines which will let users visit edit pipeline configurations page.

For config repository pipelines, the configurations will be shown in a read-only format.
Know more about read-only pipeline configurations here: https://github.com/gocd/gocd/pull/6363

##### Enable settings icon on pages linking to pipeline config edit page
  - [x] Dashboard
  - [x] Config Repository (**Groups, pipelines, and environments defined by this repository** section)
  - [x] Pipelines Page
  - [x] Templates Page
  - [x] Stage Details Page
  - [x] Job Details Page
  - [ ] Pipeline History Page
  - [x] VSM

**Comment by adityasood** [comment]
The changes for this are verified on 19.12.0-(10806)
