### ISSUE TITLE
Bug: Rename pipeline group containing pipelines from config repositories.

### ISSUE THREAD

**Issue by vrushaliwaykole** [gocd/gocd#7402]
##### Issue Type

- Bug Report

##### Summary

If the pipeline group has pipelines associated from config repository, renaming the group introduces an error

###### Basic environment details

* Go Version: `19.11.0 (10678-94ff598f8ae582d2d8acf9b1f2a3d0a544b6379d).`
* JAVA Version: `openjdk 11.0.2 2019-01-15`
* OS: `macOS mojave`

##### Steps to Reproduce

1. Add pipeline `some-pipeline` in config repository with pipeline group `defaultGroup` 
2. Try to edit pipeline group `defaultGroup` and rename it to `some-other-group`
3. Once the changes are saved, go back to the dashboard. Both the groups `defaultGroup` and `some-other-group` will be present.
4. Try to edit `defaultGroup`.

##### Expected Results
Pipeline group edit form should be rendered

##### Actual Results

![Screenshot 2019-12-06 at 12 46 31 PM](https://user-images.githubusercontent.com/2168315/70303808-7f319080-1826-11ea-861c-45d2aba5d913.png)

Similar Issue : #7332

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/7426
