### ISSUE TITLE
Bug: Template Stage/Jobs Run on Inifinite Loop

### ISSUE THREAD

**Issue by abbotware** [gocd/gocd#7406]
- Bug Report

##### Summary

I have a pipeline template with 4 stages.  The second stage has 2 jobs setup - one for windows and one for linux agents.  The second stages 2 jobs loop over and over again even though they are successful.

The same config worked fine in go 19.7  upgraded to 19.10 and problem appeared.  still happens in 19.11

The pipeline template is used twice - For one instance it works as expected.  In the other it does not.

###### Basic environment details

* Go Version: 19.11.0
* JAVA Version: 13.0.1
* OS: Windows Server 2019 10.0

##### Steps to Reproduce

You would need my config template - not sure how best to provide that.

##### Expected Results
should run job once

##### Actual Results
job runs over and over (see image)

##### Log snippets

not sure which log to provide - from the agent? or from the web server?

##### Code snippets/Screenshots

![image](https://user-images.githubusercontent.com/2100564/70370374-99a25300-1894-11ea-8517-2068b9b2a330.png)

**Comment by arvindsv** [comment]
I've seen something like this happen when the agent node runs out of memory due to the task it is running. Can you check the logs to see what it shows during the end of one of these tasks?

**Comment by abbotware** [comment]
sure.. but which log:  the agent log, or the server log? (or both)

**Comment by arvindsv** [comment]
I'd look in the agent log. It might be happening when it is trying to upload a big file, for instance.

**Comment by abbotware** [comment]
@arvindsv -  I have not had this happen any more - so closing it
