### ISSUE TITLE
Cancelling a stage is broken on server maintenance mode SPA 

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#7415]
The cancel stage API URL created does not have the pipeline instance and hence the API call returns 404.

![Screen Shot 2019-12-09 at 3 58 16 PM](https://user-images.githubusercontent.com/17826464/70428624-e9ec0180-1a9c-11ea-9e9e-a7c134817b2d.png)

**Comment by rajiesh** [comment]
Verified on 19.12.0
