### ISSUE TITLE
PipelineConfig API does not show validation error message for on_cancel task

### ISSUE THREAD

**Issue by akshaydewan** [gocd/gocd#7423]
##### Issue Type
- Bug Report

##### Summary
- Try to update a Pipeline and specify an invalid `on_cancel` task, for e.g. 
```json
{
  "type": "exec",
  "attributes": {
    "run_if": [
      "passed"
    ],
    "on_cancel": {
      "type": "exec",
      "attributes": {
        "run_if": [
          "passed"
        ],
        "command": "",
        "args": ""
      }
    },
    "command": "aa",
    "args": ""
  }
}
```
(Note that the `command` is empty for the `on_cancel` task)

Expected: In the response, the `on_cancel` task node should contain an `errors` object
```json
{
  "errors": {
    "command": [
      "Command cannot be empty"
    ]
  }
}
```

Actual: There is no errors object, only a top-level message.

Because of this, the UI only shows a top level error on the Tasks modal, now that we're using the API on the rails page.

**Comment by rajiesh** [comment]
Verified on 19.12.0 (10888-29b0f854605987c8edab9dced4814b62dc751a11)
