### ISSUE TITLE
Issue with positioning of tool tip in users management page

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#7442]
##### Issue Type

- Bug Report

##### Summary

Sometimes, the tool tip does not show up at all. Sometimes it shows up at the wrong location.

<img width="1677" alt="2019_12_16_10-39-07" src="https://user-images.githubusercontent.com/172235/70880930-d38bfb80-1ff0-11ea-91f4-fe5504e51398.png">

###### Basic environment details

* Go Version: `19.12.0 (10815-9efdb80045f22c3242c8a11b8fa68354c293b398)`
* JAVA Version: `13.0.1`
* OS: `Linux 4.14`
* Browser vendor and version (if relevant): `Firefox 71.0` and `Google Chrome 79.0.3945.79`

**Comment by rajiesh** [comment]
Verified on 19.12.0 (10885-3f91d1e16269ce7f01ef6d37a7bd5792ae28b4bc)
