### ISSUE TITLE
Cancelled icon is not rendered of cancelled jobs on stage details page

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7472]
##### Issue Type

- Bug Report

##### Summary

The canceled icon is not rendered for the canceled jobs on the stage details page.

Link: https://build.gocd.org/go/pipelines/build-linux-PR/5862/build-server/2/overview

![Screen Shot 2019-12-19 at 11 23 06 AM](https://user-images.githubusercontent.com/15275847/71148562-f9fca180-2251-11ea-8244-69ca97167fa6.png)

###### Basic environment details

* Go Version: `19.12.0`

##### Steps to Reproduce

1.  Create a pipeline with job(s).
2. Trigger pipeline and cancel the stage.
3. Visit the stage details page of the pipeline instance.
4. Refer failed jobs section on the left

**Comment by kritika-singh3** [comment]
@GaneshSPatil I'm unable to reproduce the error.
Steps I followed:
1. Create a pipeline with 3 jobs with all of them failing
2. Triggered the job.
3. Visited the stage details page.
<img width="465" alt="Screen Shot 2020-01-02 at 2 19 04 PM" src="https://user-images.githubusercontent.com/41165891/71658682-ffd2a680-2d6a-11ea-8d8b-2f954057b645.png">

Can you verify it on your end.

**Comment by GaneshSPatil** [comment]
@kritika-singh3 -- The issue is with the canceled stage jobs (not failed).
I've updated the [steps to reproduce](https://github.com/gocd/gocd/issues/7472#issue-540095876) this issue.

**Comment by kritika-singh3** [comment]
Able to reproduce the issue. Confirmed that the issue is present from GoCD version 19.8.0 post the changes made in #6707.

**Comment by GaneshSPatil** [comment]
Verified on GoCD Version: 20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0).

Example: https://build.gocd.org/go/pipelines/smoke/3325/Smoke/1
