### ISSUE TITLE
GoCD API returns HTML response in case of 404 error

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7478]
##### Issue Type

- Bug Report

##### Summary

In case of 404 NotFound error, GoCD API returns HTML response instead of JSON.

###### Basic environment details

* Go Version: ` 19.12.0 (10855-1a40d1cf075020c1ff72c437a6b1880169e66d5e)`

##### Steps to Reproduce

1.  Hit any spark based GoCD API which returns 404 for entity not found. (Not for incorrect url)

##### Expected Results
The API should return a JSON response

##### Actual Results
The API returns a HTML 404 page

##### Cause of Failure
As part of the in-progress GoCD release `v19.12.0`, the Pipeline Activity page has been migrated to mithril.
To do so, a Spark SPA Route entry has been added for the pipeline activity page [here](https://github.com/gocd/gocd/blob/master/spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/PipelineActivityController.java).

As part of the controller route setup, [a global `RecordNotFoundException` handler](https://github.com/gocd/gocd/blob/master/spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/PipelineActivityController.java#L61) has been registered. Causing all the `RecordNotFoundException` to render HTML response via [this](https://github.com/gocd/gocd/blob/master/spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/PipelineActivityController.java#L65-L68) method.

**Comment by bdpiparva** [comment]
@GaneshSPatil - Which API is this?

**Comment by GaneshSPatil** [comment]
@bdpiparva -- As per the spark java documentation, the exception handlers are configured for type for all routes and filters. [Documentation Link](http://sparkjava.com/documentation.html#exception-mapping)

We also have used these global exception handlers for exceptions such as: `HttpException`, `JsonParseException` and `UnprocessableEntityException`. [GoCD RouteHelper Class](https://github.com/gocd/gocd/blob/master/spark/spark-base/src/main/java/com/thoughtworks/go/spark/RoutesHelper.java#L60-L63)

As these exception handlers are not url scoped, all the APIs throwing `RecordNotFoundException` will be handled by this.

**Comment by bdpiparva** [comment]
@GaneshSPatil  -  I see the exceptions are always mapped globally even it is specified in context of the path. I have raised the PR https://github.com/gocd/gocd/pull/7480 to render response based on the `Accept` header

**Comment by rajiesh** [comment]
Verified on 19.12.0 (10886-59e3fe2cfd2513d7eef2b33f83b056775dfa585f)
