### ISSUE TITLE
[GoCD Docker Image] Allow for a convenient way to turn off GoCD components from logging to docker console

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#7479]
Today a user has to alter the docker-entrypoint.sh [here](https://github.com/gocd/gocd/blob/master/buildSrc/src/main/resources/gocd-docker-server/docker-entrypoint.sh#L94) to remove the property `-Dgo.console.stdout=true` or mark it as `false` combined with removing the console-appender from the `logback-include.xml` file to completely stop plugins and GoCD server from logging to docker console.

This would require building a fresh image with altered docker-entrypoint.sh if someone wants to default to this behavior. A user should be able to alter this using an envrionment variable

**Comment by arvindsv** [comment]
@adityasood I changed that to this:

```bash
if [ -z "${GOCD_DONT_LOG_TO_CONSOLE}" ]; then
  GOCD_SERVER_JVM_OPTS+=("-Dgo.console.stdout=true")
fi
```

When I ran it as:

```
docker run -e 'GOCD_DONT_LOG_TO_CONSOLE=true' -it my-image
```

... it still logged to console. Is the log file change also needed or is this enough? Maybe it is? Users can control the logback file anyway. Right?

**Comment by adityasood** [comment]
@arvindsv from what I know the GoCD server console logging has to be controlled via the logback-include.xml. The property `go.console.stdout=true` controls the plugin and agent process logging to the console. So a user would have to do both to completely stop GoCD logging to docker console
