### ISSUE TITLE
Pipeline From Template Doesnt Trigger

### ISSUE THREAD

**Issue by abbotware** [gocd/gocd#7486]
##### Issue Type

- Bug Report

##### Summary

pipeline made from a template is not being scheduled - according to the log it things the artifact disk is full.  this is clearly not the case as there is 60GB free and other pipelines are being scheduled

###### Basic environment details

Go Server Version: | 19.11.0 (10687-c532a61bb240ffbe59fe356445bea6433005563f)
-- | --
JVM version: | 13.0.1
OS Information: | Windows Server 2019 10.0
Usable space in artifacts repository: | 59.07 GB
Database schema version: | 1910006
Pipelines Count: | 23

##### Steps to Reproduce

not sure

##### Expected Results
pipeline should start when triggered

##### Actual Results
pipeline is not scheduled

##### Code snippets/Screenshots
2019-12-21 12:04:32,681 INFO  [qtp2073262855-46] PipelineTriggerService:43 - [Pipeline Schedule] [Requested] Manual trigger of pipeline 'Coverage.Bug' requested by anonymous
2019-12-21 12:04:32,775 INFO  [qtp2073262855-46] PipelineTriggerService:46 - [Pipeline Schedule] [Accepted] Manual trigger of pipeline 'Coverage.Bug' accepted for user anonymous
2019-12-21 12:04:32,821 INFO  [qtp2073262855-46] PipelineTriggerService:48 - [Pipeline Schedule] [Processed] Manual trigger of pipeline 'Coverage.Bug' processed with result 'com.thoughtworks.go.serverhealth.ServerHealthState@b920d25[healthStateLevel=OK,type=<HealthStateType ARTIFACTS_DISK_FULL LogScope[GLOBAL, scope=GLOBAL]>,message=,description=,expiryTime=<null>,timestamp=Sat Dec 21 12:04:32 EST 2019]'

**Comment by abbotware** [comment]
I restarted the service too - but that made no difference

**Comment by arvindsv** [comment]
The message is misleading (and arguably, shouldn't even be printed). The `healthStateLevel=OK` says that the check for `ARTIFACTS_DISK_FULL` was "OK". 🤦

So, it can be ignored.

If the pipeline did not trigger, it's not because of that reason. Are there any server health messages? Red box. Top right corner.

**Comment by abbotware** [comment]
no - all other pipelines trigger - even those using the same template

**Comment by kritika-singh3** [comment]
@abbotware Can you verify that the pipeline never gets triggered or the pipeline is triggered but an agent was never assigned?
The difference being in the 1st case, the material update has failed and the pipeline was never scheduled. It would show up as the following on your dashboard:
![Screen Shot 2019-12-30 at 4 38 57 PM](https://user-images.githubusercontent.com/41165891/71579509-e808e180-2b22-11ea-8213-ee90cf98df70.png)

In the 2nd case, the material update happened successfully and the pipeline was scheduled but an agent was never assigned. The dashboard would look like:
![Screen Shot 2019-12-30 at 4 40 37 PM](https://user-images.githubusercontent.com/41165891/71579576-3c13c600-2b23-11ea-8e70-db915542aa17.png)

**Comment by abbotware** [comment]
it is the 2nd case - its 'yellow' and I have to manually cancel it

I also upgraded to 19.12 and the problem still occurs

**Comment by kritika-singh3** [comment]
@abbotware Can you please verify that neither of the reasons defined [here](https://docs.gocd.org/current/faq/fixing_common_issues.html#agent-is-not-being-assigned-or-nothing-gets-built) are valid for your case?

**Comment by abbotware** [comment]
its definitely not that - there are many other pipelines that work and are scheduled correctly

**Comment by adityasood** [comment]
@abbotware could you help me with the following

1. Could you verify when the pipeline is triggered an agent matching the resource is available to be assigned? It could be possible that all agents matching the resources were building other jobs and hence this was unassigned.
2. Can you trigger the pipeline and collect some logs and share them with us here? 
3. Is this a recent scenario? Has this pipeline ever been run? If yes, what were the changes that caused this state?
4. Can you share the template and pipeline config with us? Please redact any sensitive information.
5. For how long has the job been unassigned?

**Comment by abbotware** [comment]
@adityasood  - 

There are no other agents (there are 5 in total) running. There are multiple pipelines with the same template.  They run fine so this is no reason why the pipeline should be unable to be scheduled.

> Can you trigger the pipeline and collect some logs and share them with us here?
i did - it was pasted above - but it doesn't seem to provide any more info.  Is there a way to turn on m more diagnostic info?  I can provide the logs, but tell me exactly which files you need (there are many logs)

>Is this a recent scenario? Has this pipeline ever been run? If yes, what were the changes that caused this state?
Pipeline was never run before - it was new and created from a template and has never been able to run.

>Can you share the template and pipeline config with us? Please redact any sensitive information.
Is there a place I can send the config files (i'd rather not post them online)

> For how long has the job been unassigned
forever.. I have to cancel it manually.  If i restart it, it still says unassigned.

**Comment by arvindsv** [comment]
It sounded like the pipeline is in a different environment without an agent in that environment. But you ruled that out as well.

Can you send the config files to support@thoughtworks.com and mention this issue number? As mentioned, please redact as needed (even though it is being sent there). Thank you!

**Comment by abbotware** [comment]
@arvindsv -  it was the **Environment** !!  whoops... 

Cloning a template does not also assign an environment...    I had all my pipelines assigned to environments before I started to 'templatize' them...  when I cloned it, it defaults to no environment.  All my agents are assigned to environments so it could not run.

There is no feedback in the UI to indicate that a pipeline can't be scheduled due to no valid environments.... similarly (i think) if you have jobs with resources that are not on any agent, you will also get the same behavior....   I dont know if the log file mentioned if there was no environment available... so you may want to double check if that gets printed to the log at least.

**Feature Request:** The UI should really show feedback to differentiate pipelines / stages / jobs that are unable to run because agents are busy and ones that have no valid environment / agent / resource combinations..  The later would be a case of never running (yellow color forever) but if it were a color like blue - then I would know there is a misconfiguration... or better yet - have one of those server wide 'warning / error' messages appear.

**Feature Request 2** - what is the probability of showing the log file within the admin section of the go server admin portal - It is a PITA to have to physically remote into the server and then find the server log 

Please let me know if either of those feature requests already exists somewhere as both would have saved a huge amount of time

**Comment by arvindsv** [comment]
About the first one: Yes, this has been brought up before. You're right that it should show feedback. This is not always straightforward because agents might temporarily have lost contact, etc. So, it might not pay to be too eager with this. However a warning would be useful. @GaneshSPatil has been considering some work around the dashboard (such as this: https://github.com/gocd/gocd/issues/3965) and during that, it might be useful to consider situations such as this.

About the second one: Maybe a way to download it can be possible, but having something stream it continuously is not planned at this time.

**Comment by abbotware** [comment]
An agent that lost contact is a different scenario from a pipeline that has no resources (or in my case here, no environment) available on any known agents.

for the second - an admin button that just downloads all relevant log files (since there are a few) would be hugely beneficial - (and would probably aid in trouble shooting all issues)

I'll close this issue shortly and open up feature requests for the above
