### ISSUE TITLE
Extend plugin API to enable automatic artifact attachments.

### ISSUE THREAD

**Issue by ruckc** [gocd/gocd#752]
I've recently written a [maven task plugin](https://github.com/ruckc/gocd-maven-plugin) for Go, and i'd like to automatically attach generated artifacts to the job (binary, source, javadoc, test results, etc...) but I don't want to have to specify the artifacts source for each one, i'd like to have the plugin automatically collect them up as part of the return ExecutionResult.success.

For example, if ExecutionResult.success was overloaded with ExecutionResult.success(String message, File ... files), it would make it trivial to automatically attach the artifacts from a maven run.

**Comment by srinivasupadhya** [comment]
+1 - ability to env. variables & artifact upload paths in task end-point would be cool.

**Comment by arvindsv** [comment]
Closing as stale.
