### ISSUE TITLE
Pipeline_groups api broken in 19.12?

### ISSUE THREAD

**Issue by unkinected** [gocd/gocd#7521]
##### 

Bug Report

##### Summary

We were on version 19.2 and using the pipeline_groups API without issue, using a bearer token for authentication. Today we upgraded to 19.12 and I can't seem to get that api anymore. If I hit the API in my browser (after logging in as a system admin), I get the message: "Either the resource you requested was not found, or you are not authorized to perform this action." Hitting it via curl or powershell gives me a 404 error. I'm passing the Accept header with the version-less string to make sure I get the latest and using the same bearer token as before (though I tried a new token too).

Has something changed with this particular API? I'm hitting other APIs without issue.

##### Environment

Details in attached json file.

###### Basic environment details

* Go Version: `19.12`
* JAVA Version: `13.0.1`
* OS: `Windows Server 2016`
* Browser vendor and version (if relevant): `Edge Chromium or Chrome (latest)`

##### Steps to Reproduce

1. Log in
2. Attempt to hit the pipeline_groups API
 

##### Expected Results
I expect pipelines results like we received in version 19.2.

##### Actual Results
404

[config.txt](https://github.com/gocd/gocd/files/4010185/config.txt)

**Comment by unkinected** [comment]
I should mention the URL I was trying to hit was: https://MYGOSERVER:8154/go/api/config/pipeline_groups

When I hit the "admin" version of that API (https://go.vaxcare.com:8154/go/api/admin/pipeline_groups), I get a similar error: The url you are trying to reach appears to be incorrect.

Both of these APIs are documented in the 19.12 version of the API documentation.

**Comment by GaneshSPatil** [comment]
Hi @unkinected,

As part of GoCD release `v19.12.0`, we have deprecated and put the un-versioned Pipeline Group config listing API endpoint behind a toggle.
To enable this you can use the following curl request.
```
curl -k 'https://<your-gocd-server-url>/go/api/admin/feature_toggles/enable_pipeline_group_config_listing_api'  -H 'Accept: application/vnd.go.cd.v1+json' -uusername:password -X PUT -d '{"toggle_value": "on"}'
```

---

> When I hit the "admin" version of that API (https://MYGOSERVER:8154/go/api/admin/pipeline_groups), I get a similar error: The URL you are trying to reach appears to be incorrect.

Did you pass in the appropriate `Accept: application/vnd.go.cd.v1+json` header while making the API call? I tried [this](https://api.gocd.org/current/#get-a-pipeline-group) request from the example on GoCD `v19.12.0` and it works as expected.

As mentioned in the [GoCD v19.12.0 API deprecations](https://api.gocd.org/current/#changes-in-19-12-0), the unversioned Pipeline Group Config Listing API has been deprecated and we recommend you to use the [versioned pipeline group config](https://api.gocd.org/current/#pipeline-group-config) API.

**Comment by unkinected** [comment]
Hi Ganesh,

I'm aware of the deprecation in 19.12. When I'm making my calls I'm passing in the accept header application/vnd.go.cd+json. I've also tried appending various versions, like application/vnd.go.cd.v1+json through application/vnd.go.cd.v8+json. It still gives me the same error. 

For example, I just tried this command: 

`curl -H "Accept: application/vnd.go.cd+json" -H "Authorization: Bearer MYBEARERTOKEN" https://MYGOURL:8154/go/api/config/pipeline_groups`

And got the message: 

`The resource you requested was not found!`

I'd rather not depend on the deprecated unversioned API, but I can't get the versioned one to work.

**Comment by adityasood** [comment]
@unkinected The Pipeline Group API is documented [here](https://api.gocd.org/current/#get-all-pipeline-groups). Please try this.

**Comment by GaneshSPatil** [comment]
Hi @unkinected,

Sorry for the confusion, these two are two different requests which require different headers.

#### To use [Pipeline Group Config Listing API](https://api.gocd.org/current/#config-listing) (on GoCD `v19.12.0`):
1.  Enable `enable_pipeline_group_config_listing_api` toggle by running following command:
```terminal
curl -k 'https://<your-gocd-server-url>/go/api/admin/feature_toggles/enable_pipeline_group_config_listing_api'  -H 'Accept: application/vnd.go.cd.v1+json' -uusername:password -X PUT -d '{"toggle_value": "on"}'
```
2. Make a request to [Pipeline Group Config Listing API](https://api.gocd.org/current/#config-listing) by running the following command:
```terminal
curl 'https://<your-gocd-server-url>/go/api/config/pipeline_groups'  -H "Authorization: Bearer MYBEARERTOKEN"
```

---

#### To use [Pipeline Group Config API](https://api.gocd.org/current/#get-all-pipeline-groups) (on GoCD  `v19.12.0`):

1. Make a request to [Pipeline Group Config API](https://api.gocd.org/current/#get-all-pipeline-groups) by running the following command:
```terminal
curl 'https://<your-gocd-server-url>/go/api/admin/pipeline_groups' -H 'Accept: application/vnd.go.cd.v1+json' -H "Authorization: Bearer MYBEARERTOKEN"
```

**Comment by arvindsv** [comment]
And, the second option is preferred going forward, right? The first one will be removed after a while.

**Comment by GaneshSPatil** [comment]
@arvindsv -- Yes, Option1: Pipeline Group Config Listing API is deprecated and will be removed in the GoCD release scheduled for Mar 2020. 

Thanks for mentioning!

**Comment by unkinected** [comment]
Ah, ok, so if I understand correctly, the /api/admin/pipeline_groups has replaced /api/config/pipeline_groups?

The /admin version is working for me, when I pass in the header Accept: application/vnd.go.cd+json

Thank you all for the help. The documentation was not clear about one of these APIs replacing the other.

**Comment by GaneshSPatil** [comment]
@unkinected -- Yes, you're right. The versioned (v1) Pipeline Group Config API replaces the unversioned Pipeline Group Config Listing API.

I will be closing this issue as the mentioned GoCD APIs are working as expected.
