### ISSUE TITLE
Pipeline Grp API update giving 200 even when passed a non-existent role

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#7534]
##### Issue Type

- Bug Report

##### Summary

The Pipeline Grp Update API is giving 200 even when you provide an non-existent role for the authorization

###### Basic environment details

* Go Version: `GoCD Version: 20.1.0 (10935-c0f673b823a90e81021e56f8947e9303e2f4c0ce)`
* JAVA Version: `Java 11`

##### Steps to Reproduce

1. Create a pipeline group `test`
2. Make a GET API call for the same to get the etag
3. Use the etag from above to make an UPDATE call

```curl
curl -v 'https://go-server-url/go/api/admin/pipeline_groups/test' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v1+json' \
      -H 'Content-Type: application/json' \
      -H 'If-Match: "0d63c2478a33e0a94ed6ee7f1538d99a"' \
      -X PUT \
      -d '{
        "name": "test",
        "authorization": {
          "view": {
            "roles": ["non-existent"]
          }
        }
      }'
```

##### Expected Results

The API should have return 422 with the errors saying that the `non-existent` role was not found.

##### Actual Results

It returns 200 and the GoCD entity gets updated with the role value.

##### Possible Fix

The line [here](https://github.com/gocd/gocd/blob/master/server/src/main/java/com/thoughtworks/go/config/update/UpdatePipelineConfigsCommand.java#L59) makes a no error check on `newPipelineGroup` but the `validate` was called on `preprocessedPipelineConfigs`. Reversing the check and updating the [representer](https://github.com/gocd/gocd/blob/master/api/api-pipeline-groups-v1/src/main/java/com/thoughtworks/go/apiv1/admin/pipelinegroups/representers/AuthorizationRepresenter.java) should fix the issue.

**Comment by rajiesh** [comment]
Verified on 20.1.0 (11090-752c45e6489aa30ef3a1fd911c82f97eb8104eaf)
