### ISSUE TITLE
[Granular Auth] Introduce Granular Auth for Elastic Agent Cluster Profile and Elastic Profile

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#7549]
1.  Permission set for Creating a Cluster Profile

```xml	
<role name=”cp_admins”>
	<policy>
		<allow action=”administer” type=”cluster_profile”>cp_*</allow>
	</policy>
	<users>
		<user>cp_admin1<user>
		<user>cp_admin2<user>
	</users>
</role>
```
#### Implicit permissions

If a user is able to administer a Cluster Profile, they will be able to administer all elastic profiles within it.

2. Permission set for viewing a Cluster Profile

```xml	
<role name=”cp_viewers”>
	<policy>
		<allow action=”view” type=”cluster_profile”>cp_*</allow>
	</policy>
	<users>
		<user>cp_view1<user>
		<user>cp_view2<user>
	</users>
</role>
```
#### Implicit permissions

If a user is able to view a Cluster Profile, they will be able to view all elastic profiles within it. I suggest only view as these can be elevated by making someone administer an EP or all. 

3. Permission set for viewing EP in a cluster profile

**A user with the below policy can view all Elastic Profiles within cluster profile CP1.**

```xml
<allow action="view" type="elastic_profile">cp_1:*</allow>
```
##### Implicit permissions
View permission on cp_1

**A user with the below policy can view all Elastic Profiles within cluster profile CP1.**
```xml
<allow action="view" type="elastic_profile">cp_1:ep_*</allow>
```
##### Implicit permissions
View permission on cp_1

**A user with the above policy can view all Elastic Profiles** 
```xml
<allow action="view" type="elastic_profile">*:*</allow>
```
##### Implicit permissions
View permission on all cluster profiles

A user with the below policy can view all Elastic Profiles matching the wildcard ep_* within cluster profile CP1

```xml
<allow action="view" type="elastic_profile">cp_*:ep_*</allow>
```

##### Implicit permissions
View permission on cluster profiles matching the pattern cp_*

4. Permission set for creating an EP in a cluster profile
**A user with the below policy can administer all Elastic Profiles within cluster profile CP1.**

```xml
<allow action="administer" type="elastic_profile">cp_1:*</allow>
```
##### Implicit permissions
View permission on cp_1

**A user with the below policy can administer all Elastic Profiles within cluster profile CP1.**
```xml
<allow action="administer" type="elastic_profile">cp_1:ep_*</allow>
```
##### Implicit permissions
View permission on cp_1

**A user with the above policy can administer all Elastic Profiles** 

```xml
<allow action="administer" type="elastic_profile">*:*</allow>
```

The above should also be allowed to be represented as 

```xml
<allow action="administer" type="elastic_profile">*</allow>
```

##### Implicit permissions
View permission on all cluster profiles

A user with the below policy can administer all Elastic Profiles matching the wildcard ep_* within cluster profile CP1

```xml
<allow action="administer" type="elastic_profile">cp_*:ep_*</allow>
```
##### Implicit permissions
View permission on cluster profiles matching the pattern cp_*

@arvindsv @maheshp @GaneshSPatil @kritika-singh3

**Comment by arvindsv** [comment]
To me, it seems a little weird to have the elastic_profile policy step be dependent on a different policy step in the same role. For instance, it can lead to challenges in understanding in cases such as:

```xml
<allow action="view" type="cluster_profile">cp1_*</allow>
<allow action="administer" type="elastic_profile"></allow>
<allow action="view" type="cluster_profile">cp2_*</allow>
```

Can this user administer elastic profiles in `cp2_*`?

<hr>

```xml
<allow action="administer" type="elastic_profile"></allow>
<allow action="view" type="cluster_profile">cp_*</allow>
```

What does this mean?

<hr>

I would never have guessed that scenario two works the way you are suggesting. I think that can lead to confusion.

Wouldn't it be easier to say:

```xml
<allow action="administer" type="elastic_profile">cp_1:*</allow>
```

or even (slightly tougher to understand):

```xml
<allow action="administer" type="elastic_profile">cp_*:*</allow>
```

**Comment by maheshp** [comment]
I second what @arvindsv is suggesting, but I am wondering if System Admins would want to control access to a specific elastic profile. I think it is good enough to allow/deny permissions to `view` or `administer` all elastic profiles within a cluster. That means, the permissions would like something below,

```xml
<allow action="administer" type="elastic_profile">cp_1</allow>
<allow action="view" type="elastic_profile">cp_1</allow>
```

**Comment by adityasood** [comment]
@arvindsv @maheshp thank you for the inputs. I have updated the comment and added a few scenarios.

I need some feedback around

For a user to view all cluster profiles and elastic profiles the following should suffice
```xml
<allow action="view" type="elastic_profile">*:*</allow>
```

However, for a user to administer all cluster profiles and elastic profiles should the following be enough?

```xml
<allow action="administer" type="elastic_profile">*:*</allow>
```
With this, it would be difficult to achieve a view of cluster profile and grant administer only to Elastic Profiles.

or 

```xml
<allow action="administer" type="cluster_profile">*</allow>
<allow action="administer" type="elastic_profile">*:*</allow>
```

/cc @GaneshSPatil @kritika-singh3

**Comment by rajiesh** [comment]
@adityasood I prefer the last option suggested on the above comment

```
<allow action="administer" type="cluster_profile">*</allow>
<allow action="administer" type="elastic_profile">*:*</allow>
```

For 2 reasons - Separate type names for Cluster profile and Elastic profile makes sense since it avoids confusion for users. Another reason, it allows more granular way of managing permissions for both entities.

However, do we need to introduce a new expression like this `*:*` for elastic profile? Wouldn't the prefix based regex which we use for all other resource like `ep_*` be sufficient. By this super admins can give users access to elastic profiles irrespective of cluster.

**Comment by GaneshSPatil** [comment]
### Status Report Access WRT Elastic Agent Policies

GoCD has the following three elastic agent status report pages for each elastic agent plugin:
- **Plugin Status Report** (Link from the plugins page)
- **Cluster Status Report** (Link from the elastic agent configuration page for each cluster profile)
- **Elastic Agent Status Report**(Link from the job details page)

As of today, these status report pages can only be accessed by **Super Administrators**.

With policy changes to the elastic agent entities, the permissions for these pages will be as follows:

| Status Report Page        | Required Permission        |
| ------------- |:-------------:|
| Plugin Status Report      | Super Administrator |
| Cluster Status Report      | View Cluster Profile Permission      |
| Elastic Agent Status Report | View Elastic Profile Permission      |

\cc: @gocd/committers

**Comment by kritika-singh3** [comment]
@GaneshSPatil This looks good enough to start with.
One query: If any user has `administer` permission for `*` cluster profile - we give them access to plugin status report as well: Does this statement makes sense?

**Comment by GaneshSPatil** [comment]
@kritika-singh3 

**NOTE**: These reports' permissions are mentioned for Elastic Agent Plugins implementing Elastic Agent `v5` extension (and not for `v4`). Also, none of the GoCD supported `v5` plugins implement the Plugin Status Report.

Here are some complexities implementing the above-mentioned permission:
1. The plugins page is only accessible to the super admins. Does this mean now cluster admins get to see all the plugins? or only the elastic agent plugins??
  If we choose to show only elastic agent plugins, will it create confusion as to why other plugins are not visible??
2. The `*` administer permission is just logical permission for all cluster profiles. And a `plugin status report` is per plugin.
    Hence, what we should be checking is, whether the current user has admin permissions on all the cluster profiles of the given plugin. This would require us to check permission against each cluster profile during policy evaluation.



This permission would get a little more complex to understand when elastic agent plugins implementing `v4` extension (`azure`, `marathon`) comes into the picture:

For such plugins:
- On the plugins page, **Plugin Settings** can only be configured by Super Administrators (as there is no granular auth support for plugin settings)
- But, the **Plugin Status Report** can be accessed by Cluster Administrators of no-op cluster.

Hence, decided to keep the plugin related entity access only for super administrators.

**Comment by kritika-singh3** [comment]
Ok. In midst of so many options and paths, the safest path is the one you mentioned @GaneshSPatil .

**Comment by GaneshSPatil** [comment]
Added granular auth support for elastic agents in GoCD Release `v20.1.0`
