### ISSUE TITLE
Placeholder issue for new Pipeline Group SPA

### ISSUE THREAD

**Issue by rajiesh** [gocd/gocd#7551]
##### Issue Type

- Bug Report

##### Summary

Placeholder issue for new Pipeline Group SPA

- [x] When group admin tries to delete a pipeline group, GET calls are made to endpoints `api/admin/security/roles` and `api/users` which returns 403 response. This causes generic error (`Failed to retrieve pipelines`) shown to user. User need to refresh the page to load the pipeline groups.

- [x] Pipeline group permissions create/edit failure messages are not shown completely. Say an admin user tried to update the pipeline group permissions. But provides a non existing role name. On save the API returns appropriate errors `Role <some_role> does not exists`. But UI shows just a generic error message as `Validations failed for pipelines 'GROUP1'. Error(s): [Validation failed.]. Please correct and resubmit.`

**Comment by kritika-singh3** [comment]
- [ ] When a role/user with admin permissions is viewed in edit modal, it only shows `admin` permissions as selected and enabled. The other two are unselected and enabled. The correct behaviour is that the other two should be checked and disabled. This is becoz the API returns only admin permissions as response.
<img width="1053" alt="Screen Shot 2020-01-08 at 10 30 52 AM" src="https://user-images.githubusercontent.com/41165891/71951713-faa9a780-3201-11ea-9008-9e9d3856e709.png">

 There are two ways of fixing this:
 1. Fix this on UI end. If an `admin` privilege is present, check all three.
 2. Fix this on API end. If an `admin` is present, also send the other 2 in the response.

Which is the preferred way of solving this? @gocd/committers

**Comment by bdpiparva** [comment]
@kritika-singh3 - IMO, I would go for option 1 instead of updating the API. As this is just for the UI representation(In perspective GoCD authorization, other two permissions does not have any meaning when a user has `admin` permission on pipeline group)

**Comment by GaneshSPatil** [comment]
> @kritika-singh3 - IMO, I would go for option 1 instead of updating the API. As this is just for the UI representation(In perspective GoCD authorization, other two permissions does not have any meaning when a user has `admin` permission on pipeline group)

Wouldn't this lead to having different representations for the config? 
An API call says [`view`, `admin`] and UI says [`view`, `operate`, `admin`]??

IMO, our SPAs should be dumb, they should just represent whatever the API sends as is!

**Comment by arvindsv** [comment]
My opinion: If the _meaning_ of the API response needs to be visualized in a way that makes more sense for users, shouldn't that be the SPA doing that?

Let me take a different scenario: If, instead of checkboxes, I say "show only a label saying 'Admin' if there is an admin permission present", that would be done in the  SPA, right? Even if the API call returns something else.

Having said that, in this case, I think it's ok to show what is being showed right now, since it should be intuitive (or we should make it so) that the admin permission overrides the others.

**Comment by rajiesh** [comment]
Verified on 20.1.0 (11090-752c45e6489aa30ef3a1fd911c82f97eb8104eaf)
