### ISSUE TITLE
GoCD installers do not source user .bash_profile

### ISSUE THREAD

**Issue by adityasood** [gocd/gocd#7556]
##### Issue Type
- Bug Report

##### Summary

The installers from GoCD v19.6.0 utilize tanuki wrapper. As part of this change, the GoCD agent and server start with the default service manager depending on the OS. For Ubuntu the service manager is systemd. Systemd being the parent of the GoCD agent process does not source any of files such as .bashrc or .profile.

###### Basic environment details

* Go Version: 19.11.0

##### Steps to Reproduce

1. Spin up a new instance Ubuntu 16.04 with Java 11 installed;
2. Install go-agent_19.12.0-10888_all.deb
3. Install rvm and ruby 2.5.3 as follows
sudo su - go
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB && exit
sudo su - go
\curl -sSL https://get.rvm.io | bash -s stable && exit
sudo su - go
rvm install 2.5.3 --autolibs=0 && exit
sudo su - go
echo $PATH
/var/go/.rvm/gems/ruby-2.5.3/bin:/var/go/.rvm/gems/ruby-2.5.3@global/bin:/var/go/.rvm/rubies/ruby-2.5.3/bin:/var/go/bin:/var/go/.local/bin:/usr/local/passenger/bin:/var/go/.gem/ruby/2.4.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/var/go/.rvm/bin:/var/go/.rvm/bin

4. Start the Go agent and enable it in GoCD UI

5. Set up a simple pipeline (See the attachment) and use the script executor to run:
echo $PATH

The console shows ruby and rvm are missing in PATH:
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin

##### Expected Results
The PATH variable should show rvm and ruby binary path

##### Possible Fix
 Please edit the file /usr/share/go-agent/bin/go-agent and make the following changes

a.) Change the first line 

earlier

`#! /bin/sh`

change to
`#! /bin/bash`

b.) Add the files to source at line number 207

earlier

`FILES_TO_SOURCE=`

change to

`FILES_TO_SOURCE="/var/go/.bash_profile" ( add necessary files to source here )`

**Comment by arvindsv** [comment]
Could ask @ketan whether there is any reason not to do this as a part of the installation, once he's back.

Also: Need to verify that everything will be ok if the file doesn't exist (I think it just shows a message).

**Comment by ketan** [comment]
Shell profile is expected to be loaded by just that — shells. GoCD runs as a service, and as such (IMO), should not load the profile from the user's shell.

The wrapper script executes GoCD using `runuser` or `su` depending on the OS, in both cases, environment variables are reset.  However users should be able to create the file `bin/go-{agent,server}.shconf` next to gocd agent/server shell script executable to load the profile, should they want it, be sure to change the permissions on the file to make sure it's executable (`0755`). This file is typically `/usr/share/go-{agent,server}/bin/go-{agent,server}.shconf` with rpm and debian installs.

```bash
# modify the shconf file as appropriate
echo 'source /var/go/.bash_profile' > /usr/share/go-agent/bin/go-agent.shconf
# mark it executable
chmod 755 /usr/share/go-agent/bin/go-agent.shconf
# restart the service
/etc/init.d/go-agent restart
```

Closing this issue as WONTFIX.
