### ISSUE TITLE
multiple copies of job running at the same time

### ISSUE THREAD

**Issue by cheeseblubber** [gocd/gocd#756]
### Issue

Sometimes GoCD agents would lose connectivity with the server for a few minutes due to network issues. This resulted in the server rescheduling the job on another agent. However, the first agent would be able to contact the server again. At this point, two copies of the same job are running on two different agents. The server doesn't recognize this, even though the stdout now shows output from both the jobs. Canceling the job results in only the rescheduled job getting canceled.

Refer to this [chat](https://groups.google.com/forum/#!topic/go-cd/QLdUPxt3lUs) history for more details.

**Comment by jlyheden** [comment]
We are seeing the same issue, due to network glitches (I assume) the running agent could not send the console output to the server, and eventually the server decides to schedule the job again to another agent resulting in multiple concurrent executions of the same job. Some of our jobs does database batch processing which is screwed up royally due to this.

**Comment by pshivana** [comment]
Go runs a thread every five minutes (by default) to reschedule jobs which were assigned to some agent but agent has lost contact as of now. It is possible change default value of 5 minutes through system property 'cruise.reschedule.hung.builds.interval' (value in milliseconds).  Hope this helps. 

However concerns is still valid that when old agent comes back old job should be handled in a better way.

**Comment by flavorjones** [comment]
Hey all,

Is there a planned fix for this anytime soon? We recently encountered this issue again.

Thanks for the hard work!

**Comment by flavorjones** [comment]
Bump - please let us know if there's a planned fix, or if I can help in any way. Thank you!

**Comment by zabil** [comment]
Go Server cannot kill tasks on a Go Agent. When a job/stage is cancelled it simply does not execute next task and marks the stage/job as cancelled. If there's a task running Go waits for it to complete.

But in this case, it cannot cancel a stage/job because that'll stop the stage/job on both the agents. 

As we are trying to get consistent build on a flaky network, like @pshivana mentioned has anyone here tried setting the "cruise.reschedule.hung.builds.interval"?

**Comment by arvindsv** [comment]
> Go Server cannot kill tasks on a Go Agent. When a job/stage is cancelled it simply does not execute next task and marks the stage/job as cancelled. If there's a task running Go waits for it to complete.

Is this true? It's right that the server cannot kill tasks on an agent, but it can and does send a message to the agent to kill all its child processes, right? Ref: [this](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/domain/builder/BuilderForKillAllChildTask.java#L27).

**Comment by zabil** [comment]
My observations are based on earlier tests. We had the tasks running on agents still sending logs after the job cancellation. Sending a kill will cause side effects.

On inspection
What you mentioned is wired up via a [builder](https://github.com/gocd/gocd/blob/04f352ac4cce4425c1d330025db90f8641006bc1/server/src/com/thoughtworks/go/server/service/builders/BuilderFactory.java#L69) for a specific task. On current Go implementation it does not kill instead, it executes a [cancel](https://github.com/gocd/gocd/blob/04f352ac4cce4425c1d330025db90f8641006bc1/common/src/com/thoughtworks/go/domain/builder/Builder.java#L101). e.g the [ExecTask](https://github.com/gocd/gocd/blob/04f352ac4cce4425c1d330025db90f8641006bc1/config/config-api/src/com/thoughtworks/go/config/ExecTask.java). You can configure what the cancel task needs to perform.

**Comment by arvindsv** [comment]
Here's a config I have:

```
<pipeline name="Test-1">
  <materials>
    <git url="/tmp/test.git" />
  </materials>
  <stage name="defaultStage">
    <jobs>
      <job name="defaultJob">
        <tasks>
          <exec command="bash">
            <arg>-c</arg>
            <arg>while sleep 2; do date; done</arg>
            <runif status="passed" />
          </exec>
        </tasks>
      </job>
    </jobs>
  </stage>
</pipeline>
```

As you can see, it is supposed to run forever. But, when you cancel the task, this gets killed. What am I missing?

You can see the behavior you mention if you have a task that does not respond well to being killed. For instance, a config such as this:

```
<pipeline name="Test-1">
  <materials>
    <git url="/tmp/test.git" />
  </materials>
  <stage name="defaultStage">
    <jobs>
      <job name="defaultJob">
        <tasks>
          <exec command="bash">
            <arg>-c</arg>
            <arg>trap "" INT TERM HUP; while sleep 2; do date; done</arg>
            <runif status="passed" />
          </exec>
        </tasks>
      </job>
    </jobs>
  </stage>
</pipeline>
```

Kill that process using this, if you try it: ```pkill -9 -f 'INT TERM'```

However, my point is that Go does try to kill its child tasks, by default. As long as they're not SCM checkout tasks, during the "Preparing" state. Do you think that's wrong?

**Comment by zabil** [comment]
Strange. Yes, on hind sight I've used tasks that don't respond well to kills.
Also, I also don't see this behavior in code. Will have to check deeper now :-(

But I think it's wrong (personal opinion) on Go's part to send kill signal for real tasks. Shouldn't it be the cancel tasks responsibility to decide a graceful exit?

**Comment by arvindsv** [comment]
I think the expectation of a user, upon canceling a job, would be to have whatever is running be stopped. The default expectation. The on-cancel task is an option to tell Go what to do instead. According to the [documentation](http://www.go.cd/documentation/user/current/advanced_usage/dev_clean_up_when_cancel.html), it gives the user the choice to do something else, or to do nothing.

**Comment by lenucksi** [comment]
#2640 appears to be related in terms of what @arvindsv described on the 5th June 2015.
Also, I agree with what he described.

**Comment by arvindsv** [comment]
Closing as stale.
