### ISSUE TITLE
[Config Repo Pipeline] Enable job settings link for jobs using elastic agent profile

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7560]
##### Issue Type

- Bug Report

##### Summary

GoCD added support to view read-only pipeline configurations for pipeline defined in config repository as part of GoCD release `v19.12.0`. 
Hence, For a pipeline defined remoting has jobs which using elastic agent profile, allow users to go the job settings page of such jobs.

![Screen Shot 2020-01-09 at 12 01 07 PM](https://user-images.githubusercontent.com/15275847/72043902-70804280-32d8-11ea-829c-16204284d95c.png)

**Comment by rajiesh** [comment]
Verified on 20.1.0 (11090-752c45e6489aa30ef3a1fd911c82f97eb8104eaf)
