### ISSUE TITLE
Dashboard UI not updating on pipeline grp authorization updates

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#7572]
##### Issue Type

- Bug Report

##### Summary

Dashboard view not getting updated on editing pipeline group authorization either via the new modal UI or Pipeline Group Config API.

###### Basic environment details

* Go Version: `20.1.0 (10977-495eebb16395605d283592b2c45c96ad9dd7da4b)`
* JAVA Version: `11.0.1`
* OS: `Mac OS X 10.13.6`

##### Steps to Reproduce

1. Login as admin user `admin`. Create a pipeline group `group` with a pipeline `test` in it.
2. Login via user `operate` and try to edit the pipeline group authorization via dashboard UI. You should not be able to edit as the user does not have operate permissions on it.
3. Logout and login as `admin`. Edit the authorization for `group` and provide user permissions `admin` to user `operate`. 
4.  Logout and login as `operate` and try to edit the pipeline group authorization via dashboard UI. 

##### Expected Results

You i.e. the user `operate` should now be able to edit the pipeline group authorization as we have granted the permissions

##### Actual Results

Still, the user `operate` can't edit the authorization via the dashboard UI.
Surprisingly, if we navigate to the Pipelines SPA, we can edit the permissions just not from the dashboard.

##### Any other info

Redo the step 3 via [Pipeline Group Update API](https://api.gocd.org/current/#update-a-pipeline-group). The results would remain the same.

However, if the `admin` or any user edits and saves the config xml (via UI), the expected results are achieved.

**Comment by GaneshSPatil** [comment]
#### Possible Issue:

This issue possibly has caused due to dashboard cache not being updated upon modifying the pipeline group authorization.

#### Workaround:
* Perform full config save operation
  1. Login into GoCD as admin
  2. Visit **Config XML** tab (`/go/admin/config_xml`)
  3. Edit and Save config without doing any config changes.

* Restart GoCD.

**Comment by kritika-singh3** [comment]
@GaneshSPatil I don't think a GoCD restart is required for the workaround.

**Comment by GaneshSPatil** [comment]
@kritika-singh3 -- These are two different workarounds:
1. Either we perform a full config save operation.
2. Or we restart the GoCD server.

In both of the cases, the entire dashboard cache will be reloaded and relevant pipelines for the users will be loaded on the dashboard.

**Comment by rajiesh** [comment]
Verified on 20.1.0 (11090-752c45e6489aa30ef3a1fd911c82f97eb8104eaf)
