### ISSUE TITLE
Expose current agent "resources" as GO_* environment variable

### ISSUE THREAD

**Issue by Antauri** [gocd/gocd#7575]
##### Feature enhancement

It would be ideal for example for enhanced Ansible-based continuous deployment scenarios, to know from the environment what "resources" does an agent have, by reading/parsing an environment variable of the same GO_* prefix as the others. 

The invoked Ansible playbooks can then react/adjust to the agent they run on (eg. based on agent resource/tag, filter some subset of the inventory, allowing basically unlimited scale for continuous deployment with Go.CD and Ansible).

##### Summary

In continuous deployment/delivery situations, one use-case for Go.CD agents is to run Ansible playbooks against an infrastructure. To avoid concurrency issues, using the inherent "locking" mechanism from Go.CD providing logical and physical safety of the infrastructure configuration, the team decides to use one (1) single agent for the whole infrastructure running "continuously" as each Git commit/on-demand scheduling triggers the next configuration (management) update.

To some degree, that scales but from a certain number upwards, the team no matter how they tune Ansible, they can't get faster runs. So the team decides to use multiple Go.CD agents and code their way towards a segregated/isolated execution of the same pipelines by adding some "agent-based" logic in the playbook code.

The team wants to get "smart" and based on agent tags (resources) eg. "core-infrastructure", "edge-infrastructure", "etc-infrastructure" have all agents assigned to the environment, run the same pipeline, but on a different subset of the infrastructure.

When looking up an environment variable that says on which agent does the playbook run from, there's no environment variable to expose such information (other than GO_JOB_NAME which is of the form "PipelineName-runOnAll-#" which doesn't say much). The alternative would be to maintain a mapping of agent hostnames to resources, but that defeats the purpose of being agnostic to the CD infrastructure (go.cd master + agent).

We think that adding a **GO_AGENT_RESOURCES** environment variable with a comma-separated or JSON/YAML list of assigned agent resources would help in continuous delivery situations where the DevOps people want to get smart/fancy about how pipelines execute. In our case it unblocks using more agents for CM with Ansible.

##### Environment

Debian-based master/agents.

###### Basic environment details

* Go Version: `19.12.0 (10888-29b0f854605987c8edab9dced4814b62dc751a11)`
* JAVA Version: `13.0.1`
* OS: `Linux 5.0.18-1-pve`
* Browser vendor and version (if relevant): `Google Chrome (latest)`

###### Additional Environment Details
We're in an Ansible based Go.CD continuous deployment environment.

##### Steps to Reproduce
0. get a team of die-hard Go.CD + Ansible fans that would not re-write to Puppet/Chef or some other CF tooling.
1. have written your initial configuration management code in Ansible, small-scale and your team loves it (auditability, VSM, pipeline dependencies, secure variables, etc.);
2. you want coherent pipeline execution so you have dedicated 1 Go.CD agent doing GitOps in lock-step fashion (one agent will take updates as they come, but only run one pipeline at a time against the whole infrastructure ensuring a logic coherency/serialization of all update requests);
3. business is booming and you scale from hundreds to thousands of nodes and now you want to use more Go.CD agents but be smart about their usage (you optimized Ansible to its fullest);
4. you still love this combination and purity of Go.CD + Ansible and want not to introduce some new technology;

##### Expected Results
Availability of a GO_AGENT_RESOURCES environment variable that could be used/looked-up. Eg:
```
agent_resources: "lookup ('env', 'GO_AGENT_RESOURCES')"
```

##### Actual Results
Nothing.

##### Possible Fix
One extra environment variable :smiley: ideally the master could send the agent his assigned resource (tags) when sending the pipeline trigger (I don't know how that maps internally but I'd expect the master to poll for changes to materials and to have this information already).

##### Log snippets
Nothing.

##### Code snippets/Screenshots
Nothing.

##### Any other info
Nothing.

**Comment by arvindsv** [comment]
I think that makes sense. :) However no one is working on this area currently. I believe a change [around here](https://github.com/gocd/gocd/blob/9bdcf0cf29ce387da8574f66f256da8f6a54e8fc/common/src/main/java/com/thoughtworks/go/remote/work/BuildAssignment.java#L85) will do, since that information will be in JobPlan, but someone like @kritika-singh3 or @GaneshSPatil will know better.

cc: @adityasood

**Comment by Antauri** [comment]
Something along the lines of:

```
String commaSeparatedResources = plan.getResources().stream().map (Object::toString).collect(Collectors.joining(","));
buildAssignment.initialEnvironmentVariableContext().setProperty("GO_AGENT_RESOURCES", commaSeparatedResources, false);
```
Feel free to commit it :) ... I wanted to do this tonight but I got a broken Java 11 set-up.

**Comment by rajiesh** [comment]
Verified on 20.1.0 (11090-752c45e6489aa30ef3a1fd911c82f97eb8104eaf)
