### ISSUE TITLE
[UI] Trigger with options UI defects while selecting material

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#76]
## Description

If the package revision with which pipeline has triggered and repo name : package name itself is big, then UI of trigger with options screen looks ugly as seen in screenshot

 ![dependent_build](https://cloud.githubusercontent.com/assets/1577718/2716592/bdcbeeb4-c52d-11e3-8fb6-d67277fdc83e.png)

**Comment by GaneshSPatil** [comment]
@naveenbhaskar @tinozza @arvindsv -- thoughts on redesigning the current trigger with options information something similar to the design mentioned [here](https://github.com/gocd/gocd/issues/76#issuecomment-46527453)?

**Comment by arvindsv** [comment]
This has been rewritten. So, done. Closing.
