### ISSUE TITLE
CPU Spike while visiting Elastic Agents Configuration page

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7603]
##### Issue Type

- Bug Report
- Performance

##### Summary

CPU spike on visiting `Create Cluster Profiles` Step on the Elastic Agents Configuration page.

###### Basic environment details

* Go Version: `v19.12.0`
* Browser vendor and version (if relevant): `Chrome Version 79.0.3945.88 (Official Build) (64-bit)`

##### Steps to Reproduce

1.  Visit Elastic Agents Configuration page (`/go/admin/elastic_agent_configurations`)
2. Click `Add` to add a new Cluster Profile.
3. Observe Activity Monitor

<img width="823" alt="Screen Shot 2020-01-14 at 2 00 55 PM" src="https://user-images.githubusercontent.com/15275847/72327098-70b47f80-36d6-11ea-8167-3cd6b8f082d0.png">

##### Expected Results
The page should load fine.

##### Actual Results
The page loads with a high CPU spike.

##### Reason
[This](https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agents/wizard.tsx#L302-L304) block of the code causes infinite redraws on the page causing the page to infinitely re-render.

To verify the infinite redraws, add the following print statement [here](https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agents/wizard.tsx#L66):
```js
console.log("redrawing...")
```

##### Possible Fix
Remove unnecessary `m.redraw();` from [here](https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agents/wizard.tsx#L304).

**Comment by rajiesh** [comment]
Verified on 20.1.0 (11109-7a59f0f111d0d51960d0e3105d85d6e9585cb940)
