### ISSUE TITLE
Yum polling plugin only finds packages with versions that have increased

### ISSUE THREAD

**Issue by hatchy** [gocd/gocd#761]
Hello

We are using the Yum polling plugin to trigger deployment pipelines based on the presence of new packages. Normally, the version number always goes up. Recently we have converted a number of Subversion projects to Git repositories. In the past we have used the Subversion revision as a version number. After moving to Git, we are using the commits count as a version number. In many cases (where projects shared a repository) the commits count is significantly lower than the last Subversion revision, meaning that the version effectively drops.

We recognise that the Yum polling plugin expects the version to increase, but we are looking for a way to 'reset' the version number for a specific package, so that we don't have to add numbers to the commits count we find from Git.

Do you have any suggestions? Is there somewhere convenient that this state can be altered? We don't want to purge the state for every package as this would cause all the deployment pipelines to trigger!

Many thanks in advance,
Mike & Mark

**Comment by arvindsv** [comment]
Closing as stale.
