### ISSUE TITLE
Console.log log format doesn't include date

### ISSUE THREAD

**Issue by abhinav-chittora** [gocd/gocd#7612]
##### Issue Type

Feature enhancement

##### Summary

Currently pipeline console log doesn't include date with each events. We would like to ingest those logs in Splunk for analysis and debug purpose and as per Splunk best practice guidelines, each event
 should include date with timestamp including zone information. 

This feature request to change timestamp of console.log to include date & timezone information. It will be great, if we can provide log format as customizable parameter. 

It will be icing on cake if we can configure to send console.log to syslog or directly to Splunk via HTTP Event Collector (REST API method).  

##### Environment
```plain
"Go Server Information": {
    "Version": "17.7.0 (5147-53fdb1b15184f93966059a42429bf9ed0bfdee59)"
  }
```
###### Basic environment details

* Go Version:  `17.7.0 (5147-53fdb1b15184f93966059a42429bf9ed0bfdee59)`
* JAVA Version: `1.8.0_232`
* OS: `Linux 3.10.0-1062.9.1.el7.x86_64`
* Browser vendor and version (if relevant): `Firefox 72.0.1 (64-bit) (MacOS)`

###### Additional Environment Details

N/A

##### Steps to Reproduce
1. Create a pipleline and trigger the pipeline. 
2. Once the pipeline is completed, check console.log and the events doesn't include date in each event. 

##### Expected Results
Console.log should have date & timezone information in each event. 

##### Actual Results
currently date & timezone information is not available in console.log

##### Possible Fix
Change the code to include date & timezone information. 

##### Log snippets

```
##|10:39:38.855 [go] Job Started: 2018-06-08 10:39:38 EDT
##|10:39:38.855
pr|10:39:38.856 [go] Start to prepare rsyslog/1/DEV/1/Deploy-Dev on go-server-dev [/var/lib/go-agent]
pr|10:39:38.865 [go] Start to update materials.
```

**Comment by ketan** [comment]
> We would like to ingest those logs in Splunk for analysis and debug purpose and as per Splunk best practice guidelines, each event should include date with timestamp including zone information.

It's possible to forward these logs to splunk if you configure an appropriate appender for the logger named `com.thoughtworks.go.util.command.CommandLine`. The documentation for [gocd logging](https://docs.gocd.org/current/advanced_usage/logging.html) provides some help and examples on how logging is configured.
