### ISSUE TITLE
Default {This Pipeline} Parameter (for fetch artifact)

### ISSUE THREAD

**Issue by abbotware** [gocd/gocd#7660]
##### Issue Type

- Feature enhancement

##### Summary

I would suggest creating a default template / pipeline parameter to refer to **{this.pipeline}** which can be used to fetch artifacts usable by Pipeline and Pipeline Templates.

I create templates that have a few stages, then I want to have a 'report' stage which aggregates artifacts from previous stages.   ${GO_PIPELINE_NAME}  and #{GO_PIPELINE_NAME}  are not valid when defining a fetch artifact  job (unless I am using the wrong variable?)

The irony is I can create custom parameter #(MY_PARAMETER) and then I can use that in fetch artifact!  It seems silly to have to define a custom parameter for the **current pipeline** since when using templates.. you then have to define the parameter in the pipeline, before you can even assign the template... etc..

**fetch artifact via parameter works**

![image](https://user-images.githubusercontent.com/2100564/73123686-732d9980-3f60-11ea-8095-25c352286553.png)

i would just want a predefined **{this.pipeline}**

**Comment by arvindsv** [comment]
Doesn't leaving the pipeline name empty end up using the current pipeline?

**Comment by abbotware** [comment]
hah you are right - i never realized it was an optional parameter!
