### ISSUE TITLE
Introduce GoCD Permissions API

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7695]
##### Issue Type

- Feature proposal

##### Summary

Introduce an API endpoint which returns the entities that user has permissions to.

### Get all permissions
This API is responsible to represent all the entities that a user has access to.

#### URL:
`/go/api/auth/permissions`

#### Format:
```json
{
    "entity_type": {
         "administer": ["entity_id1", "entity_id_2"],
         "view": ["entity_id1", "entity_id_2"],
    }
}
```

#### Examples:
```json
{
    "environments": {
         "administer": ["uat"],
         "view": ["uat", "prod"]
    },
    "pipeline_groups": {
         "administer": ["front_end_team"],
         "view": ["front_end_team", "backend_end_team"],
         "operate": ["front_end_team", "backend_end_team"]
    }
}
```

### Can-I-Use Type Permission
This API is responsible to tell whether a user has specified permission on the specified entity

#### URL:
`/go/api/auth/can-i/:permission/:entity_type/:entity_id`

#### Examples:
`/go/api/auth/can-i/view/environment/prod` - Yes
`/go/api/auth/can-i/administer/environment/prod` - No

##### Additional Information
1. Get all permissions API should include all the entity types with all entities. This API will help administrators to understand all the entities configured on GoCD.
2. This API will not respond `*` as this API returns point in time user authorization information.

**Comment by GaneshSPatil** [comment]
#### Where this information will be used?

* This API information can be represented under `Permissions` (user specific) tab, which will represent all the entities that the current user has access to.
* This API (with subtle modifications) can answer what all permissions have be granted by configuring a policy on a role. Which in-tern can be represented on the roles SPA (per role), for administrators to know whether right permissions have been configured for each role.

**Comment by rajiesh** [comment]
Verified on 20.2.0 (11275-2d8d4f728b77a4e98ebf75c4adbba669c19e81e1)
