### ISSUE TITLE
default -Xmx8G in wrapper-properties.conf has no effect on agent.jar

### ISSUE THREAD

**Issue by suside** [gocd/gocd#7698]
##### Summary
After encountering for a few times this error:
```
2020-01-24 14:48:38,619 ERROR [scheduler-2] TaskUtils$LoggingErrorHandler:95 - Unexpected error occurred in scheduled task.
java.lang.OutOfMemoryError: Java heap space
```
I decided to increase memory for the go-agent.
According to [this comment](https://github.com/gocd/gocd/blob/master/installers/include/wrapper-properties.conf.example#L36) and [performance tuning](https://docs.gocd.org/current/installation/performance_tuning.html) docs `wrapper-properties.conf` is the right place. So I removed `#` from `wrapper.java.additional.105=-Xmx8G` in `/usr/share/go-agent/wrapper-config/wrapper-properties.conf`

It turned out it has no effect.

After some digging I added `-Xms1g -Xmx2g` to `set.default.AGENT_STARTUP_ARGS` parameter in `wrapper.conf` (instead `wrapper-properties.conf`) and that fixed the `java.lang.OutOfMemoryError` problem.
I've noticed that:

1. `wrapper.java.additional.*` in `wrapper-properties.conf` works only for `agent-bootstrapper.jar`
1. `AGENT_STARTUP_ARGS` in `wrapper.conf` works for `agent.jar`, besides `Xmx` it was also tested with `-Dtoggle.agent.git.clean.keep.ignored.files`

###### Basic environment details

* Go Version: `go-agent 19.7.0-9567`
* JAVA Version: `OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.1+12, mixed mode, sharing)`
* OS: `Ubuntu 16.04 xenial`

###### Additional Environment Details

Agent installation was upgraded from `/etc/default/go-agent`

##### Possible Fix
I'm not familiar with java service wrapper but this line is commented out https://github.com/gocd/gocd/blob/master/installers/include/additional-properties.conf#L3

**Comment by ketan** [comment]
Any JVM args you specify using `wrapper.java.additional` are passed to what we call an "agent bootstrapper". The bootstrapper is a process that for the actual agent process.

So `AGENT_STARTUP_ARGS` is the right place to setup JVM arguments for the actual agent. You'd rarely have to setup JVM args for the bootstrapper, since all it does is execute the agent if it dies.

> I'm not familiar with java service wrapper but this line is commented out https://github.com/gocd/gocd/blob/master/installers/include/additional-properties.conf#L3

I can see why the confusion. But apparently the service wrapper treats it as a valid directive. Kind of like a c style `#include`, I'm sorry but this is not something we can change.

I'll close this issue out, since it seems like you've figured out what you want (`AGENT_STARTUP_ARGS`), but if you feel like there's something the GoCD team can do to improve the experience, I'm happy to hear feedback.

**Comment by suside** [comment]
First of all, thanks for super quick reply :+1: 

> So `AGENT_STARTUP_ARGS` is the right place to setup JVM arguments for the actual agent. You'd rarely have to setup JVM args for the bootstrapper, since all it does is execute the agent if it dies.

That's exactly what I figured out, but something completely different is written in the docs: https://docs.gocd.org/current/installation/performance_tuning.html#things-to-remember

> but if you feel like there's something the GoCD team can do to improve the experience

From my point of view I think that `AGENT_STARTUP_ARGS` should be described in the docs instead `wrapper.java.additional`

**Comment by arvindsv** [comment]
@suside Since you have the most context, do you mind suggesting changes here? https://github.com/gocd/docs.go.cd/blob/master/content/installation/performance_tuning.md

**Comment by suside** [comment]
Sure, will create issue/pr in the docs repo in my spare time. But please keep in mind that this comment here is misleading as well:
https://github.com/gocd/gocd/blob/0f15006b67b143132eb0743e1f9f76335411f263/installers/include/wrapper-properties.conf.example#L36-L37
After installation on Linux that file lands in `/usr/share/go-agent/wrapper-config/wrapper-properties.conf`

I guess I'll report back when the docs are fixed.

**Comment by arvindsv** [comment]
@suside I made some changes to make it more clear in https://github.com/gocd/gocd/pull/7736, and I'll update the docs a bit to fix the obvious errors at least. But feel free to make further edits.

**Comment by arvindsv** [comment]
I checked and it is clear from the docs that it is talking about the GoCD server and not the agent, but I'll make a small improvement there.

**Comment by suside** [comment]
> I made some changes to make it more clear in #7736, and I'll update the docs a bit to fix the obvious errors at least. But feel free to make further edits.

:+1: 
What you think about splitting performance_tuning.md _Things to Remember_ into two sections like so https://github.com/suside/docs.go.cd/commit/b0911c08098ff56bc3a67d9538f4d43be11ea44e

> I checked and it is clear from the docs that it is talking about the GoCD server and not the agent, but I'll make a small improvement there.

Yeah, it kinda is now for me too, but when searching for mem error for the first time... You see `Xmx` in  the docs and in the file, which is present on the agent.. well it was confusing.

**Comment by arvindsv** [comment]
@suside That change you proposed makes sense to me.

> You see Xmx in the docs and in the file, which is present on the agent.. well it was confusing.

Yes, I understand. If someone gets confused, I think it's on the documentation to be less confusing and not on the person to have "known better". So, it's definitely not on you. :)
