### ISSUE TITLE
Ability to have (almost) all config in VCS

### ISSUE THREAD

**Issue by josh-stableprice** [gocd/gocd#7702]
##### Issue Type

- Feature enhancement

##### Summary

Getting GoCD fully configured when running on kubernetes was really quite painful and I'd honestly like to be able to predefine the most basic version of the cruise-config.xml and then have everything else pulled in via VCS.

**Comment by arvindsv** [comment]
@josh-stableprice Which parts did you / were you able to have in VCS? What entities were you looking to put into VCS and were not able to?

**Comment by josh-stableprice** [comment]
@arvindsv It's my understanding that the only thing that can be put into VCS and pulled in by the pipelines as code feature, are pipelines and anything related to them directly. 

I'd like to be able to only need specify a VCS source in the cruise-config.xml and have the rest pulled in/updated automatically with changes made to that configured VCS. This way, I can test new versions of the config and avoid breaking production.

It also would work better with our Infrastructure as Code as most of the configuration of GoCD is expected to evolve independently. Users, Roles, Templates, Artifact Repos, etc. 

Hopefully this makes more sense as I apparently can't "english good" today.

**Comment by arvindsv** [comment]
@josh-stableprice Understood. Yes, there are [APIs](https://api.gocd.org/current/) for all the rest, but they can't be provided in a repository (roles, templates, etc as you mentioned). There will be some challenges related to ordering if that is allowed, but I can understand why it would be useful.

CC: @tomzo - just FYI.
