### ISSUE TITLE
Leading space in commit message breaks material modification check

### ISSUE THREAD

**Issue by hugocorbucci** [gocd/gocd#7709]
##### Issue Type

- Bug Report

##### Summary

Commit message that starts with a leading space causes pulls to fail.

```
Modification check failed for material: URL: git@***com:***/*** Branch: master
Affected pipelines are ***.05 Feb, 2020 at 11:57:25 Local Time

while scanning an alias
 in 'string', line 2132, column 5:
        * message: message
        ^
expected alphabetic or numeric character, but found  (32)
 in 'string', line 2132, column 6:
        * message: message
         ^
```

That commit specifically has the following message:
```
 message: message

* message: message
```

###### Basic environment details

* Go Version: `GoCD Version: 20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0).`
* JAVA Version: `13.0.1`
* OS: `Linux 4.15.0-46-generic`
* Browser vendor and version (if relevant): `Firefox 72.0.2`

##### Steps to Reproduce

1. Create a pipeline with a git material
2. Add a few commit
3. Make a new commit that starts with a leading space and has valid messages after with a body starting with `*`
4. See gocd error

##### Expected Results

Normally notice the modification and build the pipeline

##### Actual Results

GoCD errors and no longer pulls any further changes from the material/repository.

##### Possible Fix

When building up the list of messages, trim spaces for each commit message.

**Comment by arvindsv** [comment]
🤦‍♂ I'll add it to be fixed in the upcoming release. Thank you for finding this!

**Comment by hugocorbucci** [comment]
We've been trying to get a workaround to get past this commit for a bit now and can't find one. Is there a way we could get the materials to consider the repo's HEAD as the last known revision?

**Comment by ketan** [comment]
You could in theory write a shell wrapper `/usr/local/bin/git` that strips the specific line:

```shell
#!/bin/bash

/usr/bin/git "$@" | some filter function
```

**Comment by hugocorbucci** [comment]
Not only in theory. It works in practice too! We're out of the woods! Thank you very much @ketan

**Comment by ketan** [comment]
Be sure to delete that file afterwards.

**Comment by hugocorbucci** [comment]
Other workaround that I haven't tested yet that might've been easier: change the pipelines to be triggered by a timer, let them run once, move them back. Should (hopefully) move the last revision past the commit with the issue.
Yes. Will clean up the file once we confirm it is no longer needed. Thank you!

**Comment by maheshp** [comment]
This issue is fixed in https://github.com/gocd/gocd/pull/7714. I will re-open this issue for @rajiesh to verify the changes.

**Comment by rajiesh** [comment]
Verified on 20.2.0 (11289-c2cec4753bc4845894bb88ba70528721f23f2f9d)

**Comment by hugocorbucci** [comment]
Thank you!
