### ISSUE TITLE
Issues with moving pipelines between groups

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#7737]
##### Issue Type
- Bug Report

##### Summary

Moving pipelines between groups on the pipelines page fails if the given pipeline has a dependency material defined and uses parameters to define the upstream pipeline.

If a dependency material is defined without a name, the name defaults to the pipeline name. If the name of the upstream pipeline is a parameter then on update(in this pipeline group move) to the pipeline would fail for material name validation, as the material can only be alphanumeric.

**Comment by arvindsv** [comment]
I tried with this setup:

```
<pipelines group="firstGroup">
  <pipeline name="p1">
    <materials>
      <git url="/tmp/test.git" />
    </materials>
    <stage name="s1">
      <jobs>
        <job name="j1">
          <tasks>
            <exec command="ls" />
          </tasks>
        </job>
      </jobs>
    </stage>
  </pipeline>
  <pipeline name="p2">
    <params>
      <param name="UPSTREAM">p1</param>
    </params>
    <materials>
      <pipeline pipelineName="#{UPSTREAM}" stageName="s1" />
    </materials>
    <stage name="s2">
      <jobs>
        <job name="j2">
          <tasks>
            <exec command="ls" />
          </tasks>
        </job>
      </jobs>
    </stage>
  </pipeline>
</pipelines>
<pipelines group="secondGroup" />
```

The scenario I tried was: Move pipeline `p2` to group `secondGroup`.

### In 20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0)

It fails with a message: `Validations failed for pipeline 'p2'. Error(s): [Validation failed.]. Please correct and resubmit.`

In the XHR response, it says: `Invalid material name '#{UPSTREAM}'. This must be alphanumeric and can contain underscores and periods (however, it cannot start with a period). The maximum allowed length is 255 characters.`

### In 20.2.0 (11308-05dc4d14977d4bf10d5f5c9e9d6f88817df1ec1e)

It succeeds and the config XML looks like this:

```xml
<pipelines group="firstGroup">
  <pipeline name="p1">
    <materials>
      <git url="/tmp/test.git" />
    </materials>
    <stage name="s1">
      <jobs>
        <job name="j1">
          <tasks>
            <exec command="ls" />
          </tasks>
        </job>
      </jobs>
    </stage>
  </pipeline>
</pipelines>
<pipelines group="secondGroup">
  <pipeline name="p2">
    <params>
      <param name="UPSTREAM">p1</param>
    </params>
    <materials>
      <pipeline pipelineName="#{UPSTREAM}" stageName="s1" />
    </materials>
    <stage name="s2">
      <jobs>
        <job name="j2">
          <tasks>
            <exec command="ls" />
          </tasks>
        </job>
      </jobs>
    </stage>
  </pipeline>
</pipelines>
```

**Comment by arvindsv** [comment]
Closing as verified. There are [tests added here](https://github.com/gocd/gocd/pull/7738/files?w=1#diff-bb7ca85daf4271f2074dcc0f130ede29R215) and so no change in functional tests are needed.
