### ISSUE TITLE
JRE 8 - Java version 1.8. GoCD will now exit

### ISSUE THREAD

**Issue by replay111** [gocd/gocd#7741]
According to your download page:

```
TO RUN GoCD, YOU'LL NEED BOTH SERVER AND AGENT *

* Requires Java Runtime Environment (JRE) version 8 (for releases 17.1.0 and higher)
```

but when I am trying to start:

```
jvm 1    | Running GoCD requires Java version >= VERSION_11 and <= 13. You are currently running with Java version 1.8. GoCD will now exit!
```

Is there any way to force start gocd with java 8?

**Comment by kritika-singh3** [comment]
Hello @replay111, starting with GoCD version 19.9.0, we removed the support for Java 8 as mentioned in the [release notes](https://www.gocd.org/releases/#19-9-0). So, it is not possible to use the latest GoCD with Java 8. However, older versions will continue working with Java 8.

The latest GoCD versions will support Java 11 and 12. Support for 13 will be added soon.

This is in line with our [official stance on Java](https://www.gocd.org/2019/05/21/official-stance-on-java/) that was announced earlier this year post the Java Licensing Changes.

Thanks for pointing out the incorrect documentation. We will update the same.
