### ISSUE TITLE
Operate permission cannot View pipeline group

### ISSUE THREAD

**Issue by thomasf1234** [gocd/gocd#7747]
##### Issue Type

- Bug Report

##### Summary

When you set the permissions  for a role on a pipeline group to 'operate' and save the configuration then the user with the role cannot view the pipeline group.

##### Environment

Docker Image: gocd/gocd-server:v20.1.0
OS Information: | Linux 4.15.0-74-generic
Underlying Host OS: Ubuntu 18.04.3
Docker version 19.03.5, build 633a0ea838
Browser: Chrome + Safari (Remotely from MacOSX)

##### Steps to Reproduce

1. Under the pipelines admin page, edit a pipeline group and set a role permission to 'operate' on pipeline group
2. save the configuration
3. Login as a user with that role

##### Expected Results
'View' permission is encompassed in 'Operate' and so the user with the role can both view and operate the pipelines within the pipeline group

##### Actual Results
User cannot see the pipeline group. It is completely hidden from them.

##### Possible Fix
Have to manually update the xml and explicitly add a view permission as well as operate permission. But any change through the pipeline admin interface wipes out the change.

**Comment by arvindsv** [comment]
This has been fixed by @kritika-singh3 in #7753 and I verified it in experimental build "GoCD Version: 20.2.0 (11230-35a2600595047712b15d1b409ee799e86ccb74b6)" which is not yet up on gocd.org/download as an experimental build. It will be part of 20.2.0.

Thank you for opening this issue, @thomasf1234.

**Comment by Bewalticus** [comment]
I stumbled over this problem too. As a workaround in 20.1.0 you can add the "View" permission for this user via GUI in addition to the "Operate" permission. This works for me.

**Comment by maheshp** [comment]
Closing this issue as @arvindsv has verified it.
