### ISSUE TITLE
API to trigger stage and job

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#775]
If there are multiple stages in pipelines and if one if the later stages is manual, then the only way to trigger them right now is through Go dashboard. This API should be capable of triggering a stage if the previous stage has finished running (pass or fail).

**Comment by moritz** [comment]
I'm very interested in such an API. The use case is so I can build a chat bot that triggers a production release of some software by triggering a stage with manual approval.

**Comment by hveiga** [comment]
Is there any update on this?

**Comment by kapowie** [comment]
Please prioritise this. We also want to integrate Go with an external system. We use JIRA for our release authorisations and we want to automate the manual approvals from our JIRA workflow changes.

**Comment by ketan** [comment]
This feature is currently not on the roadmap. However, if someone is willing to contribute a patch (the gocd team can provide pointers) we are more than happy to merge it into an upcoming release.

**Comment by samcgardner** [comment]
Alright then. @ketan if you can tell me what the outstanding issues with /go/run/<pipeline> are, I'm happy to sling in a PR to fix 'em

**Comment by moritz** [comment]
@samcgardner the only issue with /go/run/<pipeline> that I'm aware of is the lack of API documentation. The endpoint itself seems to work (but I'm not on the go team, so take this with a grain of salt).

**Comment by dcworldwide** [comment]
Any updates on this guys? Seems like a very useful addition. We need it to resume a stage that was setup as manual so that we could have a manual QA process take place. We want to call the api from another app so that non-goCD admins can resume the pipeline based on their business role.

**Comment by cfontes** [comment]
I am also really interested in it...

I can try to implement it with my terrible Go skills, but no promises.... Can someone experienced in the code give me a couple pointers so I don't spend a week trying to get around ?

Cheers

**Comment by bdpiparva** [comment]
@cfontes -- This is on our roadmap and we plan to get this out in the next couple of releases.

**Comment by ketan** [comment]
@cfontes — I'd think there's a few things you may be able to help with before dipping your toes into code:

- hash out what specific APIs you'd like to see (trigger stage, trigger specific job, trigger all jobs, trigger failing jobs, trigger cancelled jobs,...)
- hash out how the various APIs should look like (http verbs, payloads, responses). See https://api.gocd.org for some inspiration.
- once that is hashed out. Start by running `./gradlew newApi -PapiName=trigger-something -PapiVersion=v1`. Then checkout [one of these](https://github.com/gocd/gocd/tree/master/api) directories for more inspiration about going about building APIs. [This](https://github.com/gocd/gocd/blob/75d1247f58ab8bcde3c5b43392a87347979f82c5/api/api-pipeline-operations-v1/src/main/java/com/thoughtworks/go/apiv1/pipelineoperations/PipelineOperationsControllerV1Delegate.java#L132-L137) is where the schedule API is at.

**Comment by arvindsv** [comment]
> I can try to implement it with my terrible Go skills, ...

@cfontes: Just wanted to add that GoCD is largely written in Java and Rails. Not golang.

PS: Always glad to hear someone wanting to help. :)

**Comment by arvindsv** [comment]
Done. Closing.

**Comment by mbhatia-mdsol** [comment]
I am not able to trigger a pipeline using schedule option. I have checked the GoCD API document. It suggests using **POST /go/api/pipelines/:pipeline_name/schedule**. But on using this i am getting error: **"404 Client Error: Not Found for url: https://gocd-stg.imedidata.net/go/api/pipelines/ctms_AWS_deployment_automation/schedule"**. The endpoint and credentials that I am using are working fine for other tasks like update and fetch pipeline details. Please help as I have tried so many things that are suggested on internet.

**Comment by chadlwilson** [comment]
Hiya @mbhatia-mdsol  - are you able to ask your question on GitHub discussions or the GoCD Google Group rather than this old feature request issue?
