### ISSUE TITLE
Improve UI of pipeline history comment feature

### ISSUE THREAD

**Issue by jyotisingh** [gocd/gocd#776]
#707 implements adding comments on a pipeline instance from the pipeline history page. This UI is in a very based form, and is something that should be enhanced for a better user experience.

One of the suggestions was to have something like this : https://www.dropbox.com/s/avo32mbt2o3gij5/PipelineHistoryComments.pdf?dl=0

**Comment by zabil** [comment]
Picking this up.

The pipeline history page will be rewritten using angular and erb templates.

**Comment by vinasoni** [comment]
Please check these two options. I have also done minor tweaks to the overall layout in these sketches.
![comment_option1](https://cloud.githubusercontent.com/assets/12891016/8543936/9803f518-24be-11e5-8c13-642f6c7e8e85.jpg)
![comment_option2](https://cloud.githubusercontent.com/assets/12891016/8543935/98028bce-24be-11e5-9352-6e6cf1e22076.jpg)

**Comment by zabil** [comment]
@vinasoni how are existing comments be listed on option 2?

**Comment by vinasoni** [comment]
Check these 2 options. I have also done minor tweaks to the layout in these sketches - 
![comment_option1](https://cloud.githubusercontent.com/assets/12891016/8544020/3d89fef6-24bf-11e5-8dc6-18ac0890fa6f.jpg)
![comment_option2](https://cloud.githubusercontent.com/assets/12891016/8544019/3d88b028-24bf-11e5-8f72-3d89bda6bb5b.jpg)

**Comment by vinasoni** [comment]
@zabil If there are existing comments, there is an icon (which a number count) clicking on it, displays the comments below the text box. I wanted to keep the comments hidden as the main focus will be on the build stages itself.

**Comment by srinivasupadhya** [comment]
@vinasoni some observations:
* there is only one 'comment' field so there cannot be multiple of them
* there is no way to know wether the user has read the comment or not
* details of the user commenting is not stored so cannot be shown on ui.

**Comment by vinasoni** [comment]
Thanks @srinivasupadhya. As this is not really a comment feature but rather a description to the build, please check the updated sketch. If there is no comment, then it displays a text field and if there is a description, it displays the text along with an edit icon for users to edit.
![comment_option3](https://cloud.githubusercontent.com/assets/12891016/8544765/be2d60e2-24c5-11e5-8301-4e60f0423cbc.jpg)

**Comment by arvindsv** [comment]
I like option 1 better, since it allows multi-line descriptions/comments. I mean, just the UI part of it. Whatever @srinivasupadhya said about not storing that information is correct. Also, in option 2, that comment box is a waste of space, if not used (not that it's a big deal, in this case).

**Comment by vinasoni** [comment]
@arvindsv As this feature is new, it is a good way for users to see the new feature by showing the text field upfront. Based on the stats of usage, we can hide the text field if it is not of much use to the users

**Comment by arvindsv** [comment]
Closing. I think this beta feature has been removed.
