### ISSUE TITLE
Notify SVN materials API returns "422 Unprocessable Entity" with GoCD 19.12.0

### ISSUE THREAD

**Issue by Keksparade** [gocd/gocd#7773]
##### Issue Type

- Bug Report
- moved from [Google group](https://groups.google.com/forum/#!topic/go-cd/3rZJ74_lo6o)

##### Summary

In our setup we are using the "Notify SVN materials" API with the UUID payload to trigger GoCD pipelines on new SVN commits. While this is working fine with GoCD 19.11.0 using the "traditional" pipeline configuration, a new GoCD-server 19.12.0 using config repositories for pipelines responds with an empty message and "422 Unprocessable Entity" code to it.

Example call and response:
```
curl https:/server:8154/go/api/admin/materials/svn/notify -k -i -u <username>:<password> -H 'Accept: application/vnd.go.cd.v2+json' -H 'Content-Type: application/json' -X POST -d '{"uuid": "<uuid>"}'

HTTP/1.1 422 Unprocessable Entity
Date: Fri, 21 Feb 2020 08:57:36 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: chrome=1
Set-Cookie: JSESSIONID=node0<sessionid>.node0; Path=/go; Expires=Fri, 06-Mar-2020 08:57:36 GMT; Max-Age=1209600; Secure; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/vnd.go.cd.v2+json;charset=utf-8
X-Runtime: 1
Transfer-Encoding: chunked


{
  "message" : ""
}
```

###### Basic environment details

* Go Version: `19.12.0`
* JAVA Version: `13.0.1`
* OS: `Linux 4.15.0-55-generic`

##### Steps to Reproduce

1. Set up GoCD 19.12.0 server
2. Create a pipeline using config repositories (material polling turned off) using subversion
3. Call notification API from a remote host using curl (see summary)

##### Expected Results

Curl response should contain a confirming message and the pipeline should be running.

##### Actual Results

Curl response is empty, HTTP code is "422 Unprocessable Entity" and the pipeline is not triggered.

**Comment by Keksparade** [comment]
@arvindsv Just checked with a "traditionally" configured pipeline, but it seems that I get the same error there. So probably something around this API has changed between 19.11.0 and 19.12.0, independent of the configuration.

**Comment by arvindsv** [comment]
@Keksparade I tried this just now with the zip of `19.11.0-10687` and `19.12.0-10888` and it worked fine.

Pipeline config:
```
<pipeline name="p1">
  <materials>
    <svn url="file:///mypath/repo1" autoUpdate="false" />
  </materials>
  <stage name="s1">
    <jobs>
      <job name="j1">
        <tasks>
          <exec command="ls" />
        </tasks>
      </job>
    </jobs>
  </stage>
</pipeline>
```

```
$ svn info
Path: .
Working Copy Root Path: /mypath/2020_02_24_09_02_tmp.69L44N/r1
URL: file:///mypath/2020_02_24_09_02_tmp.69L44N/repo1
Relative URL: ^/
Repository Root: file:///mypath/2020_02_24_09_02_tmp.69L44N/repo1
Repository UUID: 0dedf361-c0ec-4a1a-8c9a-15197d22850c
Revision: 0
Node Kind: directory
Schedule: normal
Last Changed Rev: 0
Last Changed Date: 2020-02-24 09:59:16 +0000 (Mon, 24 Feb 2020)

# On 19.1.0

$ date >f1.txt && svn commit -m "$(date)" f1.txt
Sending        f1.txt
Transmitting file data .done
Committing transaction...
Committed revision 3.

$ curl http://localhost:8153/go/api/admin/materials/svn/notify -k -i -H 'Accept: application/vnd.go.cd.v2+json' -H 'Content-Type: application/json' -X POST -d '{"uuid": "0dedf361-c0ec-4a1a-8c9a-15197d22850c"}'
HTTP/1.1 202 Accepted
Date: Mon, 24 Feb 2020 10:05:59 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: chrome=1
Set-Cookie: JSESSIONID=node0ghc7e88hneqiax3xzgr0rtbk7.node0; Path=/go; Expires=Mon, 09-Mar-2020 10:05:59 GMT; Max-Age=1209600; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/vnd.go.cd.v2+json;charset=utf-8
Vary: Accept-Encoding, User-Agent
Transfer-Encoding: chunked

{
  "message" : "The material is now scheduled for an update. Please check relevant pipeline(s) for status."
}


### Upgraded it to 19.12.0 (by replacing go.jar)

$ date >f1.txt && svn commit -m "$(date)" f1.txt
Sending        f1.txt
Transmitting file data .done
Committing transaction...
Committed revision 4.

$ curl http://localhost:8153/go/api/admin/materials/svn/notify -k -i -H 'Accept: application/vnd.go.cd.v2+json' -H 'Content-Type: application/json' -X POST -d '{"uuid": "0dedf361-c0ec-4a1a-8c9a-15197d22850c"}'
HTTP/1.1 202 Accepted
Date: Mon, 24 Feb 2020 10:08:19 GMT
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-UA-Compatible: chrome=1
Set-Cookie: JSESSIONID=node0mby7kvfqnwu7r372swv4ytos2.node0; Path=/go; Expires=Mon, 09-Mar-2020 10:08:19 GMT; Max-Age=1209600; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: max-age=0, private, must-revalidate
Content-Type: application/vnd.go.cd.v2+json;charset=utf-8
Vary: Accept-Encoding, User-Agent
Transfer-Encoding: chunked

{
  "message" : "The material is now scheduled for an update. Please check relevant pipeline(s) for status."
}
```

In both cases the pipeline triggered as normal. Could you try something similar with a local zip of those two versions, configured to use your SVN server, please?

Unprocessable entity usually means something wrong with the body of the message. I assume you're using the exact same command when checking with the two instances of GoCD server?

**Comment by Keksparade** [comment]
@arvindsv I tried what you were saying and you are right, both times a confirmation message is sent and it seems to be fine, but:

- Though a confirmation message is returned, the pipeline is not triggered.
- I still don't know why the original server is reacting with this 422 error message. In both cases I'm running the curl command from the console of the SVN server simply exchanging the hostname, nothing else. Could it be that the following point is causing the issue?
- I'm not able to create a test pipeline with `autoUpdate: false` in the yaml file on the two new test servers. As far as I've seen and understood in #3985 this is an open issue. Nevertheless, I don't get how we were even able to add some config repositories where autoUpdate is set to false in 19.12.0 without this error coming up, while others raise this error immediately.

**Comment by arvindsv** [comment]
@Keksparade It's getting very confusing. Can you please provide a config which shows this problem in a vanilla zip downloaded from gocd.org/download? A representative GoCD config (with pipeline and config repo). That way I can try and reproduce what you're seeing.

> Though a confirmation message is returned, the pipeline is not triggered.

Do you mean the setup I showed, because I _know_ that the pipeline triggers. You need to have a commit though, as you can see in the commands and outputs I showed. Are you saying it doesn't trigger when you point it to your SVN repo? Or something else? [A reproducible config will help].

**Comment by arvindsv** [comment]
I'm closing this as stale for now.
