### ISSUE TITLE
query artifacts without knowing pipeline and stage counters?

### ISSUE THREAD

**Issue by aconrad** [gocd/gocd#780]
I'm considering using Go but I want to make sure it fits my requirements.

When a contributor submits a pull request (PR) on a Github project, we want to prevent the code coverage from going down by failing the build if it does.

In order to do this, I need to retrieve the artifact `coverage.xml` generated by the PR's build (feature branch) and of the target branch (branch to merge in). Given that I know the commit SHA-1 of both branches, is there a way I can retrieve the these artifacts by their SHA-1 somehow? For example:

``` bash
$ FEATURE_COV = "coverage.abc123.xml"
$ TARGET_COV = "coverage.xyz789.xml"
$ wget "http://[server]/go/files/${FEATURE_COV}"
$ wget "http://[server]/go/files/${TARGET_COV}"
$ pycobertura diff ${TARGET_COV} ${FEATURE_COV}  # figure out whether we pass or fail the build
```

From the artifacts API docs, I see that I need `[pipelinecounter]` and `[stagecounter]` to use the artifacts API which I may not have for the target branch:

```
http://[server]/go/files/[pipeline]/[pipelinecounter]/[stage]/[stagecounter]/[job]/[filename]
```

So my question is to know whether I can query/locate artifacts by other means. Maybe by tagging the artifact with the SHA-1 so one could do:

```
http://[server]/go/files/[pipeline]/[stage]/[job]?by_tag=<SHA-1>
```

I hope this makes sense. :)

**Comment by nekberg** [comment]
Agreed - Need api avail to gather pipeline(s) with specified material, artifact, or env variables.

**Comment by arvindsv** [comment]
Closing as stale.
