### ISSUE TITLE
Compare SPA browse timeline UI issues

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#7808]
##### Issue Type

- Bug Report

##### Summary

The Comparison SPA, Browse Timeline view needs to be fixed.

<img width="1079" alt="Screen Shot 2020-03-04 at 3 01 55 PM" src="https://user-images.githubusercontent.com/1061051/75931247-5ae74f00-5e29-11ea-867a-f86f5bde3ac7.png">

**Comment by marques-work** [comment]
@maheshp I looked at the compare modal yesterday on build.gocd.org and it looked like this is all fixed.

**Comment by marques-work** [comment]
@maheshp actually I take that back. On MS Edge, it is still broken:

![image](https://user-images.githubusercontent.com/723642/76561506-aff61700-6460-11ea-8b98-b093a3669a51.png)

cc: @kritika-singh3

**Comment by maheshp** [comment]
This issue has been verified - https://github.com/gocd/gocd/pull/7863#issuecomment-610328799
