### ISSUE TITLE
[Edit Pipeline Config API] Missing response body when submitted Pipeline JSON has duplicate job name error

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7822]
##### Issue Type

- Bug Report

##### Summary

When the submitted pipeline config contains jobs with duplicate name, the request fails with following error:
```
{
  "message" : "You have defined multiple Jobs called 'up42_job'. Job names are case-insensitive and must be unique."
}
```

###### Basic environment details

* Go Version: `20.1.0`

##### Expected Results
The response should contain `data` attribute which contains the submitted pipeline json with errors on fields.

##### Actual Results
The response contains global validation error message.

##### Affected Systems

As the response received from the server does not contain the data and the field errors, a global error message is rendered on the pipeline config SPA.
![Screen Shot 2020-03-06 at 4 28 05 PM](https://user-images.githubusercontent.com/15275847/76077934-a46da080-5fc7-11ea-8ed1-e910aba5f96c.png)

**Comment by kritika-singh3** [comment]
Verified on `GoCD Version: 20.4.0 (11700-0f06e975d3cbcb0699beda94c65a2019ab17d8ba)`.
