### ISSUE TITLE
Pipeline Config API does not return any error message for invalid job resources

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#7824]
##### Issue Type

- Bug Report

##### Summary

The pipeline config API fails with a `422` response but does not return any error message in the body, when the submitted pipeline config contains invalid job resource.

###### Basic environment details

* Go Version: `20.1.0`

##### Steps to Reproduce

Create a pipeline config using API which contains invalid job resources.
Example: ` "resources" : [ "!@432&&**" ]`

##### Expected Results
The API send an appropriate error as part of response data.

##### Actual Results
No error is returned as part of response data.

**Comment by maheshp** [comment]
This issue was fixed in GoCD 20.2.0 as part of PR https://github.com/gocd/gocd/pull/7825
Verified on GoCD Version: 20.4.0 (11688-953d1f7453a918a96abc89568829fdeffe101dcf).
