### ISSUE TITLE
Defining a new pipeline does not allow to remove polling from the material

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#7847]
##### Issue Type

- Bug Report

##### Summary

* Go Version: `20.1.0`
* Related issue: https://github.com/gocd/gocd/pull/7708#issuecomment-597869926 (Point 1)

While creating a new pipeline, the wizard doesn't have a form using which the polling can be switched off for a given material.

To switch off the polling I would have to create a pipeline using `Save + Edit Full Config` option and then go to materials tab and turn off the polling, which is not desirable.

**Comment by kritika-singh3** [comment]
This also causes confusion when a material defined in Pipeline `A` with polling off is reused in the new pipeline. 
Since, the default value of polling is on - it causes different `auto_update` value error. 
The server sends a 422 with only a generic validation error with no indication of the same (and also it can't be fixed).

<img width="1287" alt="Screen Shot 2020-03-12 at 11 18 23 AM" src="https://user-images.githubusercontent.com/41165891/76491222-360b6100-6453-11ea-97e5-ca90467b64d6.png">

**Comment by marques-work** [comment]
We should expose it in the Advanced Settings section of the material, probably with some explanatory help text, or tooltip in the worst case

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.3.0 (11450-b09b089652fae2543cda69a9a788038547a19054).
