### ISSUE TITLE
Pipeline Deletion Issue

### ISSUE THREAD

**Issue by OperationsEngineers** [gocd/gocd#7860]
##### Issue Type

- Bug Report
- Feature proposal

##### Summary

Before v20.1.0 when deleting a pipeline the delete icon was greyed out if the pipeline had a dependancy. There was also a note stating what the dependency was when hovering over the delete icon.
Now every pipeline allows you to select the delete icon, and once selected it appears to delete the pipeline. If the pipeline however has a dependancy on another pipeline, it doesnt actually delete, and we are not informed of what other pipeline is dependant on it.

##### Environment

All environments

###### Basic environment details

* Go Version: 20.1.0
* JAVA Version: 13.0.1
* OS: Linux 2.6.32-358.el6.x86_64
* Browser vendor and version (if relevant): Google Chrome

##### Steps to Reproduce

This is only for pipelines that have a dependancy for another pipeline
1. Select ADMIN - Pipelines
2. Select the delete icon on a relevant pipeline

##### Expected Results
Delete icon should not be clickable on a pipeline with dependancies and a message should be displayed stating the dependancy

##### Actual Results
Delete icon is available, process appears to be deleting the pipeline, but the pipeline remains

**Comment by kritika-singh3** [comment]
@OperationsEngineers What does your screen looks like when you try to delete your upstream pipeline?

I tried a 2 pipeline setup - an `upstream` and a `downstream` pipeline. The `downstream` pipeline has the `upstream` as a material.
When I tried deleting `upstream`,  I got the following:
<img width="1673" alt="Screen Shot 2020-03-16 at 3 03 33 PM" src="https://user-images.githubusercontent.com/41165891/76742756-9e31ae00-6797-11ea-8e4d-ff91f4a7abd0.png">

My GoCD server version: `20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0)`

**Comment by OperationsEngineers** [comment]
Hi,
We are not seeing the message regarding the dependancy. When selecting the delete icon we are presented with:
![delete1](https://user-images.githubusercontent.com/29859465/76749563-944a8380-6774-11ea-83dd-c8d7e2ccef0a.jpeg)
Then when confirming the delete, we are taken back to the pipeline page where the selected pipeline hasnt been deleted:
![delete2](https://user-images.githubusercontent.com/29859465/76749882-2a7ea980-6775-11ea-9937-f2ca776ebedc.jpeg)

GoCD Version: 20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0)

**Comment by kritika-singh3** [comment]
I understand that the pipeline is not deleted. But did you see a error message on the top of the page like the one in the screenshot I shared above? 
It tells you the pipeline which is dependent on the said pipeline.

**Comment by OperationsEngineers** [comment]
I have just checked and it does appear very briefly and then dissapears. As we have 100's of pipelines, by the time we scroll to the top of the page, the message has gone. It would be good if this message is displayed in a pop up display box after selecting to delete the pipeline.

**Comment by kritika-singh3** [comment]
Possible UX improvement:  We have decided to bring back the original UX of disabling the delete pipeline icon:
 - if it is defined in a config repo
 - if it is a part of any environment
 - if it has any downstream pipelines i.e. it is being used as a material for other pipelines.

**Comment by arvindsv** [comment]
@kritika-singh3 I think it'll be good to show a message if possible about which pipelines are blocking it from being deleted. But, I know that the API call won't have the info and it might be tricky.

**Comment by GaneshSPatil** [comment]
@kritika-singh3 - As the above-mentioned fix will avoid users from running into a problem where server throws an error because of dependent pipeline. 

But the UX problem WRT to the errors not being visible is not resolved, as there are other reasons why delete (and other operations) can fail.

**Comment by kritika-singh3** [comment]
@arvindsv I updated the API which we are using to return the dependant pipelines (#7886 )

@GaneshSPatil Yes, sorry for missing it. Will update the comment.

**Comment by arvindsv** [comment]
Ah, nice! Great.

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.3.0 (11450-b09b089652fae2543cda69a9a788038547a19054).
