### ISSUE TITLE
Add "template" parameter in pipeline creation API

### ISSUE THREAD

**Issue by aresok** [gocd/gocd#791]
As an Go API client, I would like to create a pipeline based on template.
If template defines parameters, it also should be possible to put them into POST.

Currently I can only specify single command when creating a pipeline with POST to "http://[server]/go/tab/admin/pipelines/[pipeline\_name].json" URL.

It would be really useful to make a template name available here. 
Example curl with bash variables:
```
curl -X POST -H "Authorisation ${CREDENTIALS}" -d "scm=${SCM}&url=${URL}&template=${TEMPLATE}&templateParam1=abc&templateParam2=xyz" http://my_go_server/go/tab/admin/pipelines/${PIPELINE_NAME}.json
```

**Comment by srinivasupadhya** [comment]
related to #878

**Comment by arvindsv** [comment]
@maheshp, @jyotisingh: I believe this is done as a part of the [new pipeline API](https://api.go.cd/current/#create-a-pipeline). Closing. Please re-open if it's not.
