### ISSUE TITLE
[Pipeline Config SPA] General Tab

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#7915]
##### Summary

Place holder issue for all things around the General Tab.

## Data Rendering:
Sample Pipeline
```xml
<pipeline name="some" lockBehavior="lockOnFailure">
      <timer onlyOnChanges="true">0 30 10-13 ? * WED-FRI</timer>
      <materials>
        <git url="sdasd" />
      </materials>
      <stage name="S1">
        <jobs>
          <job name="j1">
            <tasks>
              <exec command="das" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
```
#### Basic Settings
  - [x] Render Label Template
  - [x] Render Automatic pipeline scheduling
#### Timer Settings
  - [x] Render Cron Timer Specification
  - [x] Render Run only on new material
#### Pipeline locking behavior
  - [x] Render appropriate radio button selected
  - [x] Run multiple instances (default) should be defaulted

#### Basic Settings
- [x] Update Label Template
- [x] Update Label template with blank value should fail validation and show errors
- [x] Update label template invalid value should fail validation and show errors
- [x] Update Automatic pipeline scheduling
#### Timer Settings
- [x] Update Cron Timer Specification
- [x] Update Cron Timer Specification with invalid value should fail validation and show errors
- [x] Run only on new material should be enabled only if Cron Timer Specification is specified
#### Pipeline locking behavior
- [x] Update Pipeline lock behavior to either of `Run multiple instances (default)`, `Run single instance of pipeline and lock on failure` or `Run single instance of pipeline at a time`

**Comment by maheshp** [comment]
## Few Issues 
### Pipeline Config Main Page
- [ ] Pause information and ability to pause is missing

### General Tab
- [ ] For mandatory fields can we add a client side validation?
- [ ] The etag for pipeline config is not updated on successful updation
    Steps to reproduce:
    1. Open the PipelineConfig General Tab
    2. Enter `0 30 10-13 ? * WED-FRI` for Cron Timer Specification
    3. Save
    4. Clear `Cron Timer Specification` field and save
    5. Error with message `Someone has modified the configuration for pipeline 'some'. Please update your copy of the config with the changes and try again.`
- [ ] Cron Timer Specification errors do not clear on a successful update
    Steps to reproduce     
    1. Open the PipelineConfig General Tab
    2. Enter `0 30 10-13 ? * WED-FOO` for Cron Timer Specification
    3. Save
    4. Form error with message `Invalid cron syntax: Illegal cron expression format (java.lang.StringIndexOutOfBoundsException: begin 4, end 7, length 6).`
    5. Enter `0 30 10-13 ? * WED-FRI` for Cron Timer Specification
    6. The pipeline config is successfully updated but the form error is not cleared.
- [ ] Cannot update Automatic pipeline scheduling
    Steps to reproduce
    1. The Automatic pipeline scheduling is selected by default
    2. Uncheck Automatic pipeline scheduling and save
    3. You will see a "Saved Successfully!" message
    4. The form is updated but the config is not really update. A page refresh will bring show Automatic pipeline scheduling checked.

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/7922 https://github.com/gocd/gocd/pull/7926 and https://github.com/gocd/gocd/pull/7928

**Comment by maheshp** [comment]
Verified pending issues on GoCD Version: 20.4.0 (11667-bfaba0628af7184486f55c1422feb6b086dd51db).
