### ISSUE TITLE
[Pipeline Config SPA] Project Management Tab

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#7921]
##### Summary

Place holder issue for all things around the Project Management Tab.

## Data Rendering:
Sample Pipeline
```xml
<pipeline name="some" lockBehavior="lockOnFailure">
<trackingtool link="http://jira.atlassian.com/go/${ID}" regex="##(\d+)" />
      <materials>
        <git url="sdasd" />
      </materials>
      <stage name="S1">
        <jobs>
          <job name="j1">
            <tasks>
              <exec command="das" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
```
#### Tracking Tool Integration
  - [x] Render Pattern
  - [x] Render URI

#### Tracking Tool Integration
- [x] Update Pattern
- [x] Update Pattern with blank value should fail validation and show errors
- [x] Update Pattern with  invalid value should fail validation and show errors
- [x] Update URI
- [x] Update URI with blank value when Pattern provided should fail validation and show errors
- [x] Update URI with invalid value should fail validation and show errors

**Comment by maheshp** [comment]
## Few Issues 

### Project Mangement Tab
- [ ] For mandatory fields can we add a client side validation?
- [ ] The etag for pipeline config is not updated on successful update
    Steps to reproduce:
    1. Open the PipelineConfig Project Managment Tab
    2. Enter Pattern `##(\d+)` and URI `http://jira.atlassian.com/go/${ID}` 
    3. Save
    4. Change Pattern field and save
    5. Error with message `Someone has modified the configuration for pipeline 'some'. Please update your copy of the config with the changes and try again.`
- [ ] Pattern and URI errors do not clear on a successful update
    Steps to reproduce     
    1. Open the PipelineConfig General Tab
    2. Enter Pattern `#(\d+)` and URI `hp://jira.atlassian.com/go/${ID}` 
    3. Save
    4. Form shows error.
     5. Enter Pattern `##(\d+)` and URI `http://jira.atlassian.com/go/${ID}` 
    6. The pipeline config is successfully updated but the form error is not cleared.

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/7922

**Comment by maheshp** [comment]
Verified pending issues on GoCD Version: 20.4.0 (11667-bfaba0628af7184486f55c1422feb6b086dd51db).
