### ISSUE TITLE
OS for Windows 2012 R2 agents not detected

### ISSUE THREAD

**Issue by matt-richardson** [gocd/gocd#793]
We have a few agents that are window 2012 r2, however they show up as "Windows NT (unknown)" in the agent list. Low priority, but still an issue.

Had a (very) quick look to see if it was an easy fix, but couldnt see anywhere where it was doing that.

**Comment by arvindsv** [comment]
I believe it is coming from [here](https://github.com/gocd/gocd/blob/master/common/src/com/thoughtworks/go/server/service/AgentRuntimeInfo.java#L106), which then leads to [this](https://github.com/gocd/gocd/blob/master/base/src/com/thoughtworks/go/util/SystemEnvironment.java#L313).

I wonder if it is possible to set a -Dos.name="Something Else". Might not work since os.name is set by Java?

**Comment by reidca** [comment]
We use Server 2012 R2 and the agents are all listed as "Windows Server 2012". There does not appear to be any difference between Server 2012 or the R2 version in the display,

**Comment by matt-richardson** [comment]
What version of java are you using, @reidca? I wonder if that makes a difference...

Ours is:
$ java -version
java version "1.7.0_09-icedtea"
OpenJDK Runtime Environment (rhel-2.3.8.0.0.1.el6_4-x86_64)
OpenJDK 64-Bit Server VM (build 23.7-b01, mixed mode)

**Comment by reidca** [comment]
We use the version that comes with the GO Installer. I have very little experience with Java however looking at the System Properties section from the support API it looks to be the same version.

https://<server name>k/go/api/support


System Properties
-----------------
  -> wrapper.service=TRUE
  -> java.vm.version=23.5-b02
  -> wrapper.version=3.3.5-st
  -> java.vendor.url=http://java.oracle.com/
  -> sun.jnu.encoding=Cp1252
  -> wrapper.jvm.port.max=31999
  -> wrapper.jvm.port.min=31000
  -> java.vm.info=mixed mode
  -> webapp.root=C:\Program Files (x86)\Go Server\work\Jetty_0_0_0_0_80_cruise.war__go__.63scoy\webapp
  -> user.dir=C:\Program Files (x86)\Go Server
  -> java.awt.headless=true
  -> sun.cpu.isalist=pentium_pro+mmx pentium_pro pentium+mmx pentium i486 i386 i86
  -> java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
  -> wrapper.jvmid=1
  -> sun.os.patch.level=
  -> cruise.server.ssl.port=443
  -> java.io.tmpdir=C:\Windows\system32\config\systemprofile\AppData\Local\Temp\
  -> user.home=C:\Windows\System32\config\systemprofile
  -> java.awt.printerjob=sun.awt.windows.WPrinterJob
  -> java.version=1.7.0_09
  -> file.encoding.pkg=sun.io
  -> java.vendor.url.bug=http://bugreport.sun.com/bugreport/
  -> file.encoding=Cp1252
  -> line.separator=

**Comment by aj-jaswanth** [comment]
I am working on this issue.

**Comment by arvindsv** [comment]
Closing as stale.
