### ISSUE TITLE
Mac installers - "Cannot be opened" message 

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#796]
![image](https://cloud.githubusercontent.com/assets/172235/5487991/2b33d6e6-8686-11e4-923e-cd0b7f2fc216.png)

The current Mac installers, for 14.4, show a message when you open them. It says, "Go Agent/Go Server can't be opened because the identity of the developer cannot be confirmed". This happens because of changes in Apple's Mac OSX Gatekeeper around 10.9 and 10.10 (Yosemite). The installer has some files at the top level inside the package, and Gatekeeper flags it as an invalid package because of that, even though it is a signed package.

Workarounds are mentioned [here](http://support.apple.com/en-us/HT202491). You need to go to "Security & Privacy" in System Preferences and allow the application to run, only once. It will work as normal, from then onwards.

**Comment by arvindsv** [comment]
Allow an easy way to set PATH and other environment variables, when this is done.

Ref: https://groups.google.com/forum/#!topic/go-cd/t98Mr1nI0Q0

**Comment by mdaliejaz** [comment]
Not able to reproduce it on my box (OSX 10.9.5). I think it happens with some specific configuration.
Will try again after a couple of days, once I'm able to find a box where this is reproducible :)
