### ISSUE TITLE
Chocolatey for Windows

### ISSUE THREAD

**Issue by maxlinc** [gocd/gocd#797]
Chocolatey is definitely the way cool kids install stuff on Windows now, even more so since the Microsoft PowerShell team announced they're working on [OneGet](http://blogs.msdn.com/b/garretts/archive/2014/04/01/my-little-secret-windows-powershell-oneget.aspx), a chocolatey-compatible package manager that will be part of PowerShell.

Chocolatey is also integrated with Chef, Ansible, Puppet, etc, just like apt for debian or yum for redhat. So the installation logic in Chocolatey can be easily be shared across projects like [go-cookbook](https://github.com/ThoughtWorksInc/go-cookbook) and [ansible-gocd](https://github.com/Tpbrown/ansible-gocd) so those projects can delegate the install to chocolatey and focus on configuration.

The reason I mention it is because there's already a [few unofficial gocd packages](https://chocolatey.org/packages?q=Thoughtworks), and chocolatey now has [package moderation](http://codebetter.com/robreynolds/2014/10/27/chocolatey-now-has-package-moderation/). So it'd be great if there was an official package maintained by the gocd org.

/cc @tpbrown since he maintains both of the projects mentioned above.

**Comment by ashutoshraina** [comment]
:+1:  Would love to see this come through..as it will ease up life on windows

**Comment by arvindsv** [comment]
Closing. This now exists: https://chocolatey.org/profiles/gocd
