### ISSUE TITLE
Breaking changes in config in version 20.2.0?

### ISSUE THREAD

**Issue by arminc** [gocd/gocd#7991]
We have been using [Gomatic](https://github.com/gocd-contrib/gomatic) to create pipelines programmatically but since version 20.2.0 they are not compatible anymore. I created an [issue in Gomatic repo](https://github.com/gocd-contrib/gomatic/issues/69) but I was wondering if you have any suggestions on what might be changed and why it doesn't work so we can maybe create a fix? 

Or do you have a suggestion for another tool that can be used to programmatically create pipelines?

**Comment by arvindsv** [comment]
@arminc I'm not sure, but I was able to confirm that the endpoint continues to work, at least on the latest experimental version of GoCD:

```
$ curl -s -v -u admin:abc123 http://localhost:8153/go/api/admin/config.xml >config.xml
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8153 (#0)
* Server auth using Basic with user 'admin'
> GET /go/api/admin/config.xml HTTP/1.1
> Host: localhost:8153
> Authorization: Basic YWRtaW46YWJjMTIz
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Thu, 09 Apr 2020 14:02:55 GMT
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-UA-Compatible: chrome=1
< Set-Cookie: JSESSIONID=node0i2u3f4oj6ya4o0okzjvoyg3328.node0; Path=/go; Expires=Thu, 23-Apr-2020 14:02:55 GMT; Max-Age=1209600; HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-CRUISE-CONFIG-MD5: fec38848d9c0f69db2600ca96152c0bf
< Content-Type: text/xml;charset=utf-8
< Vary: Accept-Encoding, User-Agent
< Content-Length: 9677
<
* Connection #0 to host localhost left intact
* Closing connection 0

# Using no confirm header (fails).
$ curl -X POST -u admin:abc123 http://localhost:8153/go/api/admin/config.xml -d md5=fec38848d9c0f69db2600ca96152c0bf --data-urlencode xmlFile@config.xml
{"message":"Missing required header `Confirm`"}

# Using `X-GoCD-Confirm` header.
$ curl -X POST -u admin:abc123 http://localhost:8153/go/api/admin/config.xml -d md5=fec38848d9c0f69db2600ca96152c0bf -H 'X-GoCD-Confirm: true' --data-urlencode xmlFile@config.xml
{"result":"File changed successfully."}

# Using `Confirm` header.
$ curl -X POST -u admin:abc123 http://localhost:8153/go/api/admin/config.xml -d md5=fec38848d9c0f69db2600ca96152c0bf -H 'Confirm: true' --data-urlencode xmlFile@config.xml
{"result":"File changed successfully."}
```

I see that the headers seem to be sent properly [here](https://github.com/gocd-contrib/gomatic/blob/c2836c4cb2cb692fc5d6109b5d8ed191efb3c7a2/gomatic/go_cd_configurator.py#L312-L323).


Of course, this is still an undocumented "feature", but I don't see any good reason for it fail in 20.2.0.

**Comment by arvindsv** [comment]
@arminc Since I had the setup ready, I tried this:

```python
#!/usr/bin/env python
from gomatic import *

configurator = GoCdConfigurator(HostRestClient("localhost:8153", ssl=False, username='admin', password='abc123'))
pipeline = configurator\
	.ensure_pipeline_group("defaultGroup")\
	.ensure_replacement_of_pipeline("P11")\
	.set_git_material(GitMaterial("/tmp/test.git", material_name="mx"))
stage = pipeline.ensure_stage("S1")
job = stage.ensure_job("J1")
job.add_task(ExecTask(['ls']))

configurator.save_updated_config(save_config_locally=True, dry_run=False)
```

... and it worked fine.

**Comment by arminc** [comment]
@arvindsv Thanks for the quick response, it might be that we are doing something more complex. I will try to find out on what it breaks. It is a pipeline which can be created on 20.1.0 but not on 20.2.0

**Comment by Sushma10037017** [comment]
@arminc Were you able to solve this? if so, please share the solution. We are facing the same issue.
Thanks!

**Comment by sriramnrn** [comment]
Hi Sushma:

Are you able to trim down the input to exactly what is failing?

-- Ram

**Comment by Sushma10037017** [comment]
Hi @sriramnrn ,
There is no particular segment in config.xml causing the failure.
In version 20.1.0, our cruise-config file sized around 280KB could be uploaded via API call mentioned below, the same config can not be uploaded in version above 20.2.0 which is throwing 400 bad request and the GoCD server log says unable to parse the form content.
If I reduce the file(to around 115KB), looks like the file is getting parsed. Is there anything that got changed in API calls after 20.2.0? 

API call used
`curl -s -XPOST ${GOCD_API_ENDPOINT}/go/admin/restful/configuration/file/POST/xml -H "Content-Type:application/x-www-form-urlencoded" --data-urlencode xmlFile@cruise-config.xml -H "Confirm: True" -u "$GO_SERVER_USER_NAME:$GO_SERVER_PASSWORD" -d md5=$config_xml_md5`

**Comment by alicekaerast** [comment]
Hi,

For anyone still having this issue, I think I have solved it - at least in our case.

The file `/usr/share/go-server/wrapper-config/wrapper-properties.conf` originally had some overrides we were setting by Ansible, including:

```
wrapper.java.additional.110=-Dorg.eclipse.jetty.server.Request.maxFormContentSize=120000000
```

This file has been overwritten by the new version somehow (still not sure exactly how), and therefore the upload limit was reset to the 200kb that is the default for Jetty.

We also have a Jetty config file alongside our cruise-config.xml file (in /etc/go for us), which appears to be ignored - and this is what through me off for a very long time.

**Comment by chadlwilson** [comment]
Thanks for sharing.

I'm not sure what might have caused the wrapper properties to be overridden. What installation mechanism are you using?

The change in default does seem a bit odd, as the default for the server's pre-packaged config is actually intended to be `30000000` in the jetty.xml, and hasn't been changed for a long time. My understanding is that normally the config dir contains a copy of the packaged default config and is only overridden if necessary due to breaking changes in Jetty. If you haven't overridden either `jetty.xml.file.name` or `cruise.config.dir` system properties it should be using `jetty.xml` from `/etc/go`, I believe.

I am wondering if some other change in `20.2.0` has somehow caused a particular installation style of GoCD server to start experiencing these problems somehow. Hmm.

**Comment by alicekaerast** [comment]
it clearly isn't using the maxFormContentSize from /etc/go/jetty.xml on the server I have been working with, but I'm not sure I want to spend much time debugging this as I'd quite like to get up to the latest stable version

I'm installing from RPM, directly from download.gocd.org

**Comment by lobsterdore** [comment]
@alicekaerast Nice work! This has fixed the issue for me, I added a similar line to the wrapper-properties.conf file and that's fixed it. This is on Ubuntu, installed via apt.
