### ISSUE TITLE
"Approval-needed" email notifications when a manual stage needs to be triggered

### ISSUE THREAD

**Issue by jefftrimm** [gocd/gocd#801]
When Pipelines require approvals to manually trigger the next Stage in a Pipeline, there is no out-of-the-box mechanism to alert people they need to trigger the next step in the flow.  

Manual Stages should have an ability to send e-mail notifications to a specified set of e-mail addresses/distribution-lists notifying them that an approval is needed, and provide the URL to the stage they need to manually activate.  The e-mail recipient should be able to click that link and be taken directly in the UI where they need to activate the next step. 

This is a key capability for any kind of an approval workflow.

**Comment by srinivasupadhya** [comment]
I have added [notification end-point](http://www.go.cd/documentation/developer/writing_go_plugins/notification/json_message_based_notification_extension.html). Should be available in 15.1.0. Hopefully you should be able to implement the above using that.

**Comment by arvindsv** [comment]
Closing as stale.
