### ISSUE TITLE
How to execute built-in command in Go agent

### ISSUE THREAD

**Issue by chrisdHN** [gocd/gocd#810]
Hi,

I've got the problem, I cannot execute built-in command - source.
`
Error happened while attempting to execute 'source /var/go/virtualenv/env1/bin/activate'. 
Please make sure [source] can be executed on this agent.

[Debug Information] Environment variable PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
`

Look like it look for the command in the PATH, but since it is built-in it won't show in PATH.
Please help, thanks.

**Comment by ringxw** [comment]
Hi Chris,
Could you elaborate on how you resolved it?

**Comment by chrisdHN** [comment]
You should wrap your buit-in command inside a shell script (bash is a good choice).
docker exec -i -t <container> bash <your shell script>.

**Comment by arvindsv** [comment]
@ringxw: If you're not using docker, just using a real shell script will do (some-file.sh, with your usage of built-in command in it). Or, if you don't want to use a separate shell script, something like this should work too: 

![image](https://cloud.githubusercontent.com/assets/172235/5736337/a2c2c5a8-9bfa-11e4-9258-bc96b6aa0002.png)

**Comment by prmammoth** [comment]
@chrisdHN. Does the environment setup by activating a virtualenv in one task, carry it's effect to subsequent tasks/stages/pipelines etc ?

**Comment by cackharot** [comment]
**@prmammoth** Yes it does.

**Comment by cristim** [comment]
@arvindsv this way of running bash shell scripts is quite ugly, isn't there a cleaner way?

**Comment by arvindsv** [comment]
The preferred approach is to use a shell script in a repository, checked in. So, the command would just be the equivalent of `./script.sh`. If not, you could use something like the [script-executor task plugin](https://github.com/gocd-contrib/script-executor-task), though it's a bad pattern to get used to. It ties your build/deploy process to GoCD. Ideally, you want it to be independent.

**Comment by arvindsv** [comment]
@cristim ^

**Comment by cristim** [comment]
Thanks @arvindsv, I'll keep this in mind.

**Comment by LaurasJ** [comment]
I am trying to execute shell script but I get: "Please make sure [./test.sh] can be executed on this agent."
Inside that script I have only:
#!/bin/bash
echo "$USER" 

If I go directly to agent machine and run script with "go" user it works.
First task in job runs "pwd" and gives back exact working directory where test.sh script is. Strange enought that "pwd" works straigt out of the box, but if I enter "echo $USER" in command field, that fails with same error as running ./test.sh . Can someone help me with that?

**Comment by sandeepbhat** [comment]
Thank you @chrisdHN for the help and thank you @arvindsv for the screenshot. I had the same issue and now it works like charm.

**Comment by shru9289** [comment]
Hi, 
I have a problem in running maven commands on GOCD . i get an error saying ,


Please make sure [mvn -s MySettings.xml -U -B clean install -f ******************:assembler-maven-plugin:1.1.10:deploy] can be executed on this agent


Though i have installed and set path for maven and java on MAC OS . Could you please tell me how do i get this fixed?. Appreciate your inputs and help
