### ISSUE TITLE
How to reference a material location via Go Environments

### ISSUE THREAD

**Issue by chrisdHN** [gocd/gocd#811]
Hi,

I've been looking the way to reference a material location. My custom shell script need a ENV variable for the material I've been working on. 
For  e.g. My material is a git branch feature_90 located at 
`
/var/lib/go-agent/pipelines/feature_90/
`
I've been looking at this section http://www.go.cd/documentation/user/current/faq/dev_use_current_revision_in_build.html but it doesn't tell about material location
Please help.
Thanks

**Comment by arvindsv** [comment]
Closing. This is a question, not an issue (yet?). Mailing list is a better forum for those.
