### ISSUE TITLE
Stuck at auth

### ISSUE THREAD

**Issue by Aeris1One** [gocd/gocd#8121]
##### Summary

It's isn't really a bug, I set up a LDAP auth but I think I've missed one thing and I'm stuck at the auth page without being able to auth (bad password error). How to remove LDAP auth from command line?

**Comment by maheshp** [comment]
@Aeris1One you can remove auth config from the cruise-config.xml file which should be located under `/etc/go` if you are on linux. If you are on a different distro,  refer to GoCD [docs](https://docs.gocd.org/current/installation/installing_go_server.html) for the location .

Remove the authConfig element pertaining to the LDAP plugin and save the file. E.g 
```xml 
<authConfig allowOnlyKnownUsersToLogin="true" id="<>" pluginId="cd.go.authentication.ldap">
....
</authConfig>
```
Going forward I would recommend you to please post questions to the [GoCD community](https://groups.google.com/forum/#!forum/go-cd)  over opening an issue. I will close this issue.
