### ISSUE TITLE
Environments Page, edit pipelines takes too long to load modal

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#8127]
##### Summary
For a large GoCD instance with pipelines > 3-4K rendering the edit pipelines modal on the environments page is slow. 

Editing the pipelines on the environment page makes a request to the internal pipeline_structure API which seems to be slow in serializing the data to JSON.
Once the JSON is received it takes significant amount of time > 25secs to render the modal.

**Comment by kritika-singh3** [comment]
Fixed in #8196 and verified on `GoCD Version: 20.5.0 (11818-b3932994090f442d17d0829804f44554ad04d309)`
