### ISSUE TITLE
Pipeline Config SPA - Possible Improvements

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8141]
##### Issue Type

- Feature enhancement

##### Description

Following enhancements could be done to the Pipeline Config SPA:

- [x]  An error adding stage shows up on the main page and doesn't go away (This behaviour is same while adding jobs)
  Steps to reproduce
   - Click on add new stage
   - Do not enter anything and click save
   - Errors show up on the Add stage modal
   - Close the modal
   - A global error shows up with the message `Validations failed for template with name                'deploy_template'. Error(s): [Validation failed.]. Please correct and resubmit.` which does not go away.

- [x] Secure environment variable should have an option to view the value while creating/editing it.

- [x] Errors adding fetch aritifact tasks does not show up on the modal
  Steps to reproduce
  - Add a pipeline, stage etc which is not an upstream of any of the pipelines using template
  - The validation errors show up on the main templates page and not the modal
  Add task buttons are disabled on fetch artifact task errors - Fixed  
  - Add fetch artifact task with all attributes as parameters and save it
  - Edit the fetch artifact task and provide an invalid parameter and save it
  - There are validation errors
  - Close the modal
    - The invalid values still show up on the task preview
    - The add task dropdown and button are disabled

**Template/Stage/Job/Job Settings**
- [x] Client side validation for required fields
- [ ]  Elastic profile errors are not mapped to the text field, shows as global errors
   Steps to reproduce
   - Provide a non-existent elastic profile id and save
   - Global error shown, ideally it should be mapped to the input field.
   - Looks like the template API needs to be fixed.

- [x] Run on instances allows a negative number to be selected, provide a min="0"  for the input element.
- [x]  Unable to select resources from autocomplete list
   - Navigate the Job Settings page
   - Move cursor on the resources textbox and enter a value
   - Select a resource from the dropdown(this works) and save.
   - Now move cursor again on the resources textbox and enter a value
   - Try selecting a resource from dropdown, this does not work.

**Template/Stage/Job/Environment Variables**
- [x] Client side validation for mandatory fields

**Template/Stage/Job/Custom Tabs**
- [x] Client side validation for mandatory field, in this case Path cannot be empty if Tab Name is specified.

- [x] Pipeline Stages or Templates (See: https://github.com/gocd/gocd/issues/8141#issuecomment-630626360)

**Comment by GaneshSPatil** [comment]
Copied from: https://github.com/gocd/gocd/issues/7816#issuecomment-630364059

[Tested on: GoCD Version: 20.4.0 (11733-33ea7d24052d505afd2fefdcfc2e6f6e5fd3f86f)]

A couple of issues around selecting between defining stages and using a template:

```xml
  <pipelines group="group1">
    <pipeline name="P1">
      <materials>
        <git url="something.git" />
      </materials>
      <stage name="S1">
        <jobs>
          <job name="J1">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </pipelines>
  <templates>
    <pipeline name="T1">
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <exec command="ls">
                <runif status="passed" />
              </exec>
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </templates>
```

------------------------------------------

- [ ] Issue 1:

    1. Edit pipeline `P1`. Go to `Stages` tab.
    2. Switch to "Use template"; dropdown has nothing.
    3. Choose `T1`.
    4. Then click "Reset" so no template is chosen.
    5. Cannot go back to `Define Stages` unless you refresh.

------------------------------------------

- [ ] Issue 2: Very similar:

    1. Edit pipeline `P1`. Go to `Stages` tab.
    2. Switch to "Use template"; dropdown has nothing.
    3. Choose `T1`.
    4. Then click "Save".
    5. Click `No` in the confirmation prompt.

    Stuck again.

------------------------------------------

@marques-work who found this says:

> I feel like the behavior should be that if I click "define stages" it should clear the template and let me continue

> alternatively, offer an "unselected" option in the dropdown. but there needs to be some instruction that the user must do this before choosing to define stages manually

> currently, if I deselect a template via "reset" it still doesn't seem to unlock the options

**Comment by kritika-singh3** [comment]
The issue: `Elastic profile errors are not mapped to the text field` under `Template/Stage/Job/Job Settings` is difficult to fix as the template does not perform validation for the elastic profile used. The validation is performed on the pipelines (configured to use the same template) - reason being the elastic profile ID could be supplied via a parameter.

**Comment by kritika-singh3** [comment]
Issue 1 in the [comment](https://github.com/gocd/gocd/issues/8141#issuecomment-630626360) has been fixed.
For issue 2, the user can click on `Reset` to go back to `Define Stages` option.
Closing this issue.
