### ISSUE TITLE
[task plugin] The output of command in console is not in correct order sometimes.

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#816]
Have seen this on windows agent.

Correct order:

```
C:\GoAgent\pipelines\test-script-executor>type *.bat 

895b8ae6-a97b-4e37-8fd7-beddf0e31dc6.bat


dir
echo "Hello %GO_TRIGGER_USER%"
type *.bat
```

In-correct order:

```
C:\GoAgent\pipelines\test-script-executor>type *.bat 
dir

echo "Hello %GO_TRIGGER_USER%"
7342af27-6f06-413d-b9dd-239b27c5a6d0.bat


type *.bat
```

**Comment by arvindsv** [comment]
I think this is the same as [this issue/conversation](https://groups.google.com/forum/#!topic/go-cd/trmwenifoAM) on the go-cd mailing list.

Here's my evidence for this:

![screen shot 2015-01-05 at 8 52 48 am](https://cloud.githubusercontent.com/assets/172235/5613868/981e124a-94b8-11e4-8fe3-e0e3e1db3849.png)

As you can see, when you do a "type *.txt", the filename is printed on to STDERR. The contents to STDOUT. So, what's happening here is that the two streams are getting interleaved, as was mentioned on the mailing list thread.

**Comment by varac** [comment]
We experience this also, i"m very interested in a fix.

**Comment by arvindsv** [comment]
Closing as stale.
