### ISSUE TITLE
GoCD does not start on Kubernetes deployment

### ISSUE THREAD

**Issue by Trojaner** [gocd/gocd#8166]
##### Issue Type
Bug Report

##### Summary
gocd does not start on kubernetes and keeps crashing instead

##### Environment
Bare-metal Kubernetes 1.17 cluster deployed with Rancher RKE
Host uses Ubuntu 19.10

###### Basic environment details
GoCD does not even start - can not look up it's environment

##### Steps to Reproduce
Install with ` helm install gocd-app --namespace gocd stable/gocd --set server.ingress.enabled=false --set server.service.type=ClusterIP`

##### Expected Results
gocd-app-server should start without crashes

##### Actual Results
gocd-app-server status stays in CrashLoopBackOff

##### Log snippets
```
/docker-entrypoint.sh: Creating directories and symlinks to hold GoCD configuration, data, and logs
$ mkdir -v -p /godata/artifacts
mkdir: can't create directory '/godata/artifacts': Permission denied
/docker-entrypoint.sh: cannot mkdir -v -p /godata/artifacts
```

**Comment by arvindsv** [comment]
Hmm, I've tried this in GKE and it works there. Could there be some different with RKE? Maybe something about how volumes are mounted?
