### ISSUE TITLE
[task plugin] param substitution for fields should be optional

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#817]
Causes this otherwise:

![screen shot 2014-12-30 at 3 30 30 pm](https://cloud.githubusercontent.com/assets/1587661/5577520/dc62fe0e-9038-11e4-9411-c037d7a17d87.png)

Hard to debug as to why it happened.

**Comment by mdaliejaz** [comment]
Though not directly related, the issue would get resolved as part of #854 
After single hash is allowed the above error wouldn't come.

**Comment by mdaliejaz** [comment]
Closing this.

**Comment by mdaliejaz** [comment]
Reopening it for now.. Will close it once the PR is merged.
Have referenced the issue, so that it could be closed together.

**Comment by arvindsv** [comment]
Closing as stale.
