### ISSUE TITLE
Gitlab webhook responds `ok` but does not trigger pipeline

### ISSUE THREAD

**Issue by AminNadimi** [gocd/gocd#8202]
##### Issue Type
- Bug Report

##### Summary

Gitlab web-hook responds:
```
Response body:
{
  "message" : "OK!"
}
```
But does not trigger pipeline.

###### Basic environment details

* GoCD Version: 20.3.0 (11530-f54d0bae7a39fe7add5460f3f8676a7936abf698).
* JVM version:  13.0.2
* OS: Linux 5.4.0-31-generic
* Browser: Firefox 76.0.1 (64-bit)

##### Steps to Reproduce

1. Install a fresh version of gocd server and agent on Linux
2. Create a pipeline and disable pooling
3. Create a gitlab repository and set web-hook integration to gocd
4. push a commit and see what happens!

##### Expected Results
Pipeline should start processing and doing stages

##### Actual Results
Simply.. Nothing happens!!

##### Log snippets
Full gitlab hook result:
```
 Request URL: POST http://192.168.x.x:8153/go/api/webhooks/gitlab/notify 202

Trigger: Push Hook

Elapsed time: 0.03 sec

Request time: 8 minutes ago
Request headers:

Content-Type: application/json
X-Gitlab-Event: Push Hook
X-Gitlab-Token: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx

Request body:

{
  "object_kind": "push",
  "event_name": "push",
  "before": "4b32edd0e1c4b1254621537aae34976252343205",
  "after": "fb74bf99b01860e9b89526694df24b3e99979b41",
  "ref": "refs/heads/master",
  "checkout_sha": "fb74bf99b01860e9b89526694df24b3e99979b41",
  "message": null,
  "user_id": 443,
  "user_name": "Amin Nadimi",
  "user_username": "Amin.Nadimi",
  "user_email": "",
  "user_avatar": "https://gitlab.domain.io/uploads/-/system/user/avatar/443/avatar.png",
  "project_id": 1513,
  "project": {
    "id": 1513,
    "name": "cicd test repo",
    "description": "",
    "web_url": "https://gitlab.domain.io/xx/cicd-test-repo",
    "avatar_url": null,
    "git_ssh_url": "ssh://git@gitlab.domain.io:2270/xx/cicd-test-repo.git",
    "git_http_url": "https://gitlab.domain.io/xx/cicd-test-repo.git",
    "namespace": "xx",
    "visibility_level": 0,
    "path_with_namespace": "xx/cicd-test-repo",
    "default_branch": "master",
    "ci_config_path": null,
    "homepage": "https://gitlab.domain.io/xx/cicd-test-repo",
    "url": "ssh://git@gitlab.domain.io:2270/xx/cicd-test-repo.git",
    "ssh_url": "ssh://git@gitlab.domain.io:2270/xx/cicd-test-repo.git",
    "http_url": "https://gitlab.domain.io/xx/cicd-test-repo.git"
  },
  "commits": [
    {
      "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "message": "Update README.md",
      "timestamp": "2020-05-30T10:25:03+04:30",
      "url": "https://gitlab.domain.io/xx/cicd-test-repo/-/commit/fb74bf99b01860e9b89526694df24b3e99979b41",
      "author": {
        "name": "Amin Nadimi",
        "email": "amin.nadimi@domain.io"
      },
      "added": [

      ],
      "modified": [
        "README.md"
      ],
      "removed": [

      ]
    }
  ],
  "total_commits_count": 1,
  "push_options": {
  },
  "repository": {
    "name": "cicd test repo",
    "url": "ssh://git@gitlab.domain.io:2270/xx/cicd-test-repo.git",
    "description": "",
    "homepage": "https://gitlab.domain.io/xx/cicd-test-repo",
    "git_http_url": "https://gitlab.domain.io/xx/cicd-test-repo.git",
    "git_ssh_url": "ssh://git@gitlab.domain.io:2270/xx/cicd-test-repo.git",
    "visibility_level": 0
  }
}

Response headers:

Connection: close
Date: Sat, 30 May 2020 09:22:25 GMT
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Ua-Compatible: chrome=1
Set-Cookie: JSESSIONID=node0aofaks4217fg87dls5i4tzn21.node0; Path=/go; Expires=Sat, 13-Jun-2020 09:22:25 GMT; Max-Age=1209600; HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Cache-Control: max-age=0, private, must-revalidate
X-Runtime: 5
Content-Type: text/html;charset=utf-8
Vary: Accept-Encoding, User-Agent

Response body:

{
  "message" : "OK!"
}
```

**Comment by AminNadimi** [comment]
go cd server log:
```
2020-05-30 15:37:27,288 INFO  [qtp870408334-27] PushWebhookControllerV1:110 - [WebHook] Noticed a git push to xx/cicd-test-repo on branch master.

```

**Comment by arvindsv** [comment]
Do you see any errors in the "Errors & Warnings" box? Top-right corner.

The "OK" is just to say that the notification was accepted. Once it is notified, `"http_url"` and `"path_with_namespace"` parts of the JSON [are used](https://github.com/gocd/gocd/blob/11f92116e118afc9a947622bae7cd3f2b265c908/api/api-webhook-v1/src/main/java/com/thoughtworks/go/apiv1/webhook/request/json/GitLabProject.java#L25-L29) to come up with [a set](https://github.com/gocd/gocd/blob/11f92116e118afc9a947622bae7cd3f2b265c908/api/api-webhook-v1/src/main/java/com/thoughtworks/go/apiv1/webhook/request/mixins/GuessUrlWebHook.java#L32) of [material URLs](https://github.com/gocd/gocd/blob/11f92116e118afc9a947622bae7cd3f2b265c908/api/api-webhook-v1/src/main/java/com/thoughtworks/go/apiv1/webhook/request/mixins/GuessUrlWebHook.java#L32) which match the event.

Those URLs are then checked to find a pipeline which matches. What is the material URL your pipeline is configured with? How does it compare to the URL in the JSON you showed?

**Comment by AminNadimi** [comment]
Nope! there is no such box in top right!

![image](https://user-images.githubusercontent.com/33121621/83937704-60678300-a7e4-11ea-84e3-20b404e67a67.png)

Ok, code is using those parameters but why there is no log about this! just `noticed a push` and done!? How am I supposed to debug this..

**Comment by AminNadimi** [comment]
No log is stored in /var/log/go-server nor in -/go-agent :(

**Comment by AminNadimi** [comment]
The above works with polling! Problem lies in webhook..

**Comment by AminNadimi** [comment]
Obviously if material url war wrong we would get :
```
{
  "message" : "No matching materials!"
}
```
instead of :
```
{
  "message" : "OK!"
}
```

**Comment by AminNadimi** [comment]
@arvindsv @GaneshSPatil @ketan  @marques-work

**Comment by AminNadimi** [comment]
Can anybody approve that gitlab hook actually works?

**Comment by AminNadimi** [comment]
Anybody?!

**Comment by arvindsv** [comment]
I don't think I heard a response to my earlier questions:

> What is the material URL your pipeline is configured with? How does it compare to the URL in the JSON you showed?

Also, whether the branches match.

I can dig a little deeper to see what's going on, with that info.

------

> Can anybody approve that gitlab hook actually works?

I don't think people follow GitHub issues so closely. If you have questions for users, the mailing list or gitter channel are probably better, but people don't seem to respond much. People just ask questions when they face problems. :/

**Comment by AminNadimi** [comment]
@arvindsv 
> What is the material URL your pipeline is configured with? How does it compare to the URL in the JSON you showed?

All the same,  gitlab repository is a local on-premise version, on internal servers of our own.

![1](https://user-images.githubusercontent.com/33121621/84255542-00484800-ab28-11ea-9519-56382e7e1649.png)
![2](https://user-images.githubusercontent.com/33121621/84255546-01797500-ab28-11ea-9732-0f97cc76b33c.png)

> Also, whether the branches match.

They are identical (master)

**Comment by AminNadimi** [comment]
Thanks, I will report the result.

**Comment by AminNadimi** [comment]
Created a fresh pipeline and new hook. worked! Gonna dig deeper in previous pipeline problem.

**Comment by arvindsv** [comment]
Maybe the other pipeline's (or its first stage) is manual? What Gitlab is notifying is that the material has changed. It's not forcing the pipeline to trigger. The pipeline will only trigger if its first stage is not manual.

**Comment by AminNadimi** [comment]
Ooops!! `Trigger type` of first stage was `manual`. Enabling `Trigger on completion of previous stage` fixed the issue. but there is no previous stage in my pipeline! :)
this might be a UI/UX issue.
Also, I think more importance should be given to this section docs
btw, thank you @arvindsv

**Comment by arvindsv** [comment]
>  Also, I think more importance should be given to this section in docs

Feel free to submit an improvement PR in the documentation repo ([user docs](https://github.com/gocd/docs.go.cd/) or [API docs](https://github.com/gocd/api.go.cd/)).
