### ISSUE TITLE
Feature proposal - pipeline counter can have a sequential increments for depending pipelines

### ISSUE THREAD

**Issue by veeramanikandanvv** [gocd/gocd#8215]
Feature Proposal:
Pipeline counter starts from 1 today for every first instance. Can we also have a feature where dependent pipelines can have instances in sequential order. Pipeline2 instance should be pipeline1 instance plus 1. If pipeline2 depends on pipeline1. 
This feature should be enabled wherever it's required and not for every depending pipelines.
Version: 19.6

**Comment by veeramanikandanvv** [comment]
Any plans to take this feature?

**Comment by maheshp** [comment]
Can you check the section `Using upstream pipeline labels` in https://docs.gocd.org/current/configuration/pipeline_labeling.html 

Do you think it will help your use case?
