### ISSUE TITLE
JSON error when trying to add Notification Filter ( match_commits )

### ISSUE THREAD

**Issue by inzi** [gocd/gocd#8220]
##### Issue Type

- Bug Report

##### Summary

The creation of a notification filter shows JSON error and does not create.

Json `{"pipeline":"[Any Pipeline]","stage":"[Any Stage]","event":"Passes"}` does not contain property 'match_commits'

##### Environment

```plain
    "OS Name": "Windows Server 2016",
    "OS Version": "10.0",
    "System Architecture": "amd64",
    "Available Processors": 4,
    "Average System Load": -1.0
```
-->

###### Basic environment details

* Go Version: GoCD Version: 20.4.0 (11749-5553066d29d315951efa5ead0c087374df6338b9)
* JAVA Version: 13.0.2
* OS: Windows Server 2016 10.0
* Browser vendor and version (if relevant): MS Edge & Safari

##### Steps to Reproduce

1. Login 
2. Go to Preferences
3. Select Pipeline, Stage, Event
4. Click ADD

##### Expected Results
The Notification filter should be created

##### Actual Results

An error message is displayed:
Json `{"pipeline":"[Any Pipeline]","stage":"[Any Stage]","event":"Passes"}` does not contain property 'match_commits'

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.5.0 (11818-b3932994090f442d17d0829804f44554ad04d309).
