### ISSUE TITLE
Support for secrets management interpolation on Pluggable SCM materials

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd#8234]
##### Issue Type
- Feature enhancement

##### Summary

It appears that currently GoCD does not interpolate variables defined using the [Secrets Management](https://docs.gocd.org/current/configuration/secrets_management.html) Plugins for use by pluggable SCM materials.

That is, if you define a `password` (or other `secure` property indicated by an SCM plugin) with a value like `{{SECRET:[file-secrets][test-password]}}` it is not interpolated/populated with the real value before sending to the SCM plugin requests.

I note that currently the [`PluggableSCMMaterial`](https://github.com/gocd/gocd/blob/master/domain/src/main/java/com/thoughtworks/go/config/materials/PluggableSCMMaterial.java) is not [`SecretParamAware`](https://github.com/gocd/gocd/blob/master/config/config-api/src/main/java/com/thoughtworks/go/config/SecretParamAware.java) and only the built-in `ScmMaterial`s have this support; with some hard-coded logic for the `password` field. 

My thought is that if a plugin indicates a value as `secure: true` in the `scm-configuration` request for a property, that it may be possible for GoCD Server to use this as an indication that a value should be eligible for `SecretParam` interpolation/retrieval prior to building the requests to the plugin.

##### Environment

GoCD 20.3.0

**Comment by arvindsv** [comment]
@chadlwilson The reason for not supporting secrets in plugin SCMs was that plugin load order is undefined. So, it's possible that the secret plugins have not loaded while other plugins have. So, this can create problems. Right, @maheshp?

In cases such as this, where the material will be checked once more. maybe it is possible? However, looking at the original issue you linked to, it looks like it is more about config repo, than pluggable SCM.

Maybe @marques-work has some thoughts.

**Comment by maheshp** [comment]
The [Secret Management](https://docs.gocd.org/current/configuration/secrets_management.html) feature was introduced with support for secret params only in Environment Variables and Password field for built-in SCM Materials.

Secrets support for all Plugins, PluggableSCMMaterials, etc... was something we considered but it  never got prioritized. With plugins, the idea was that whenever GoCD makes a request to plugin it should pass the configuration with all secrets resolved. 

> @chadlwilson The reason for not supporting secrets in plugin SCMs was that plugin load order is undefined. So, it's possible that the secret plugins have not loaded while other plugins have. So, this can create problems. Right, @maheshp?

My guess is that it might not be a problem, because MDU should happen after all the plugins are loaded. But if we want to support secrets for all plugins we will have to consider the plugin load order and its repercussions.

**Comment by chadlwilson** [comment]
Yup, all good - I understand if this isn't a priority given the relative user base for these types of plugins (and some of the downsides of using them compared to the built-in materials), but felt it was useful to have it logged specifically that this currently isn't supported, as perhaps users might expect it to now that there is support for config repo/pipelines-as-code for `PluggableSCMMaterial`s.

**Comment by arvindsv** [comment]
Just for the record: This https://github.com/gocd/gocd/blob/b3932994090f442d17d0829804f44554ad04d309/server/src/main/java/com/thoughtworks/go/server/service/MaterialService.java#L154-L158 is the code responsible for resolving secrets in materials. So, if anyone wants to extend this to pluggable materials, then it would involve implementing [SecretParamAware](https://github.com/gocd/gocd/blob/b3932994090f442d17d0829804f44554ad04d309/config/config-api/src/main/java/com/thoughtworks/go/config/SecretParamAware.java#L18) interface for [PluggableSCMMaterial](https://github.com/gocd/gocd/blob/b3932994090f442d17d0829804f44554ad04d309/domain/src/main/java/com/thoughtworks/go/config/materials/PluggableSCMMaterial.java).

This is not the more generic idea that @maheshp mentioned:

> With plugins, the idea was that whenever GoCD makes a request to plugin it should pass the configuration with all secrets resolved.

**Comment by maheshp** [comment]
Done as part of - https://github.com/gocd/gocd/pull/8503

**Comment by chadlwilson** [comment]
Very nice - thanks!
