### ISSUE TITLE
Deploy with Required Parameters

### ISSUE THREAD

**Issue by sbahmani** [gocd/gocd#826]
We want to have some options at deploy time ( just like jenkins's build with parameters feature) ; an examples would be the IP of remote server (we've got a lot of servers) that we want to deploy our application . if you're going to suggest environment variable as a solution; we want a drop down menu at least (deployer user should be able to choose from a predefined list because he/she does not know them all)!

Our final goal is to define a set of options that user forced to choose from when setting environment variable in "Trigger with options" modal window

an example photo from jenkins's build with parameters(all of build required parameters are predefined by us):
![jenkins](https://cloud.githubusercontent.com/assets/4223715/5647616/e1f98a12-969c-11e4-88db-cca6a9567b36.png)

**Comment by nick-kov** [comment]
I have a similar issue.  Did you get a solution?

**Comment by sbahmani** [comment]
@nick-kov  
no .

**Comment by yterradas** [comment]
is there an update on this feature?

**Comment by sbahmani** [comment]
I still need this feature but don't have any solution.

**Comment by arvindsv** [comment]
As far as I know, no one is working on this. Would be a nice feature to have, if you want to work on it. If you propose how it's going to work (in a generic way, as a feature), then I can point you to parts of code and help, if you like.

**Comment by junneyang** [comment]
+1

**Comment by junneyang** [comment]
@sbahmani 
i also suggest this feature but don't have any solution.
i suggest the   "ENVIRONMENT VARIABLES"  could some how replace the deploy parameters
if we define the deploy parameters in the ENVIRONMENT VARIABLES, we could modify it and then deploy.

![qq 20161009100030](https://cloud.githubusercontent.com/assets/6802322/19217040/3f644d96-8e07-11e6-942f-eff398fa80cd.png)

i don't know if this could meet your demands.

**Comment by sbahmani** [comment]
any update?

**Comment by nick-kov** [comment]
Yes.  Environment variables works.

**Comment by artburkart** [comment]
Is this something that could be implemented with a plugin?

**Comment by mattbmidigator** [comment]
I'd like to take a crack at this.. @arvindsv please let me know where to hit the code.
My proposal is to use environment variables (as everyone is doing for the play with options).
We'd add a checkbox next to each environment variable setting in the pipelines environment variables (only) with the label 'list'
The standard environment variable value textfield would be kept as the default setting for the environment variable.
If the list checkbox is checked, another textfield appears which accepts a comma-delimited list of options (such as ips, legs for builds, git branches etc). 
At the play with options dialog, the 'list' would appear as a dropdown with the default (what's stored in the standard  textfield) as the selected option (top option). Changing the selection would change what is exported to env var when the 'Trigger Pipeline' button is pressed. For all other cases, the default option would be chosen (i.e. normal play pipeline, api deploy etc). 
Does that make sense?

**Comment by mateuscosta86** [comment]
any updates on this feature?

**Comment by arvindsv** [comment]
I missed this call out to me. :( Sorry @mattbmidigator. No updates as far as I know. If anyone is still looking to do this, I'll help or ask someone better than me at this to point to the right parts of the code. Some changes are likely going to be [here](https://github.com/gocd/gocd/tree/1043b29f3d32a5ec5c37f0dc7895cc7aefd87a0a/server/src/main/webapp/WEB-INF/rails/webpack/views/dashboard/trigger_with_options) and [here](https://github.com/gocd/gocd/blob/1043b29f3d32a5ec5c37f0dc7895cc7aefd87a0a/api/api-pipeline-operations-v1/src/main/java/com/thoughtworks/go/apiv1/pipelineoperations/PipelineOperationsControllerV1.java#L119). But, the config would also need to change to accommodate this, within the pipeline (to store the "options"), I suppose.

**Comment by VijayChandamala** [comment]
Not sure on text-input params, but you can have jenkins-like choice parameter using a workaround, which looks sorta overkill , but here it is : 

Let's say you have to have a param choice with options install , uninstall and reinstall

* create an empty git repo
* Add a plain-text or a yaml with a line saying : 
     type: install
* Add this as a material to your go pipeline
* update your plain-text or yaml file to : 
     type: uninstall
* Repeat the same for reinstall
* Parse this file in your main pipeline tasks based on which you can decide what your code should do.

Make sure your commit message reflects the action (install,uninstall,reinstall) , so it becomes easier for you to identify while you try to trigger with options.

Now  you can select trigger with options and choose the appropriate commit.

Although this works, you'll have to make sure you don't commit multiple times and another problem here is if you don't use trigger with options, pipeline will pick latest commit as the parameter choice.
