### ISSUE TITLE
Better naming for whitelist/blacklist options

### ISSUE THREAD

**Issue by lucashanke** [gocd/gocd#8263]
##### Issue Type

- Feature enhancement

##### Summary

Currently, GoCD provides the capability of adding a whitelist/blacklist to materials so we can listen to/avoid changes to a particular folder. The naming for these options (widely adopted in a lot of technology tools) has a racist background, and we can and should avoid using them. https://twitter.com/andrestaltz/status/1030200563802230786?s=20

I suggest changing those options to block list and safe list.

**Comment by lucashanke** [comment]
I'm happy to work on a PR, if this is accepted.

**Comment by arvindsv** [comment]
Hello. Yes, it's something we talked about a few weeks ago, but couldn't get it into the recent release. A PR is always appreciated, but even if not, it's likely something that will happen in the upcoming release.

**Comment by GaneshSPatil** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/8266

Verified as part of https://github.com/gocd/gocd/pull/8266#issuecomment-656398034
