### ISSUE TITLE
Stop displaying "Check out these GoCD concepts" at startup if user intervention is required

### ISSUE THREAD

**Issue by axelkr** [gocd/gocd#8264]
##### Issue Type
- Feature enhancement
- Usability

##### Summary
I forgot to update the DB for the new server version and hence the server refused to start. What to took me quite a while was to realize that the server was in an error state and I needed to do something about it. I believe the reason for that is that the page for "Server loading - please wait" resembles the "Cannot connect to server - Please check the server logs" too closely. Specifically, if you just glance at the page, you might not notice that the text below the logo has changed.

##### Environment

* Go Version: 20.5.0 (11820-1c9b12ac8aa216a2c062fbec4cba18d9cfb8b404)
* JAVA Version: 13.0.2
* OS: Windows 10 10.0

##### Steps to Reproduce
1. Install&Configure Go CD Server 20.4.0
2. Upgrade to 20.5.0 without upgrading DB

##### Expected Results
Cue user that he/she needs to do something instead of waiting for server startup.

##### Actual Results
Both screens (see below) look identical at a glance and user might miss that the text has changed and that the user needs to take action.

##### Possible Fix
A simple visual cue to resolve this would be to no longer display the "Check out these GoCD concepts in the meantime.." box if user intervention is required / the page cannot connect to the server. That would leave just the text and hence draw attention to it as well.

###### Screen during normal startup (user has to wait):
![startup_user_wait](https://user-images.githubusercontent.com/7880376/85658227-4d452600-b6b3-11ea-99e0-c3f677a9d870.png)

###### Screen when startup has failed (user has to investigate):
![startup_user_investigate](https://user-images.githubusercontent.com/7880376/85658221-4b7b6280-b6b3-11ea-8c7e-d9c90d17ad6b.png)

**Comment by marques-work** [comment]
@axelkr Sorry for taking so long to get back to you. This seems pretty reasonable. While I can't guarantee when it will be released, it seems like low hanging fruit.

**Comment by GaneshSPatil** [comment]
@axelkr @marques-work - We also can show the error message in an error callout. (Just a suggestion)

<img width="1440" alt="Screen Shot 2020-09-16 at 9 56 46 AM" src="https://user-images.githubusercontent.com/15275847/93292374-0e7ec200-f803-11ea-9e91-4585d795a3fb.png">

---

For the above changes, add the following styles [here](https://github.com/gocd/gocd/blob/master/jetty9/src/main/resources/loading_pages/new.loading.page.html#L26)
```css
#status-UNKNOWN {
    border: 1px solid;
    width: 95%;
    padding: 12px;
    border-radius: 5px;
    background: #feebec;
    background-color: #feebec;
    color: #df0b16;
    border-color: #fcbabe;
}
```

**Comment by axelkr** [comment]
@marques-work  @GaneshSPatil 

Highlighting the message red would be a sufficient visual cue to me. 

Regarding adding the error message, picking the correct error message to display seems to be a hard issue. In my experience, program logs usually contain a string of exceptions (root cause + subsequent faults) along with normal exceptions (which occur but do not stop execution). Hence, I usually head directly to the log for investigation.
