### ISSUE TITLE
Can not save the newly created template

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8286]
##### Issue Type

- Bug Report

##### Summary

Can not edit the newly created template.

###### Basic environment details

* Go Version: `20.5.0`

##### Steps to Reproduce

1. Go to Admin => Templates page (`/go/admin/templates`)
2. Click create a new template button.
3. Enter a valid template name and hit save.
4. Click the edit icon of the newly created template to go to the template edit page.
5. (Without making any changes) Hit Save.

##### Expected Results

The template should be saved.

##### Actual Results

The template save fails with 'Validation Failed! Please fix the below errors before submitting.' error on the page, with no error on the page.
The developer console prints only "Uncaught (in promise) undefined"

##### Possible Fix

This error is caused due to client side [job model validation](https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/webpack/models/pipeline_configs/job.ts#L66) expecting at least one task in the job. Whereas, when a new template is created on the server, no task is added to it.

["A job must have at least one task"](https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/webpack/models/pipeline_configs/job.ts#L65-L66) validation can be removed from the model. There is already [**a view validation**](https://github.com/gocd/gocd/blob/master/server/src/main/webapp/WEB-INF/rails/webpack/views/pages/clicky_pipeline_config/tabs/job/tasks_tab_content.tsx#L255-L258) which will prevent users from deleting the only task from the job.

##### Related Issues:
#8177 #8194

**Comment by GaneshSPatil** [comment]
@maheshp @kritika-singh3 @marques-work @arvindsv - Thoughts??

**Comment by kritika-singh3** [comment]
IMO, this isn't an error - this was the desired feature. The default template creation creates a external cover. I think it was expected for the user to add in tasks and save. Without making any changes, the save as expected should fail.

**Comment by GaneshSPatil** [comment]
> IMO, this isn't an error - this was the desired feature. The default template creation creates a external cover. I think it was expected for the user to add in tasks and save. Without making any changes, the save as expected should fail.

Oh! Currently, there is no way for the end user to know why the save fails. The top level error just says "Validation Failed! Please fix the below errors before submitting.". 


If this is an expected behavior, we might need to improve the UX (and messages & help text ) to navigate the user to add a task first to the template. Because, without adding the task, edits to the other parts of the template will keep failing (that too without appropriate error).

**Comment by kritika-singh3** [comment]
> Need to improve the UX...

 +1 to that

**Comment by GaneshSPatil** [comment]
Note: Had an internal conversation with the team.

##### Possible fix:

1. Add a server side validation for a job to contain at least one task.
2. When a new template is created, GoCD server will add a default task to the `defaultJob`, making sure that there will always be at least 1 task in all the jobs.

The above two fixes will make sure that a job with no task scenario does not occur at the client side.

Closing...

**Comment by kritika-singh3** [comment]
The possible fix was implemented in #8309.
