### ISSUE TITLE
Add default parameter value when adding new parameter into template

### ISSUE THREAD

**Issue by aresok** [gocd/gocd#829]
When I'm trying to add a parameter to the template, it says: Parameter 'MY_PARAM' is not defined. All pipelines using this parameter directly or via a template must define it."
As a result, I need to edit all pipelines and provide a parameter; while having lot of pipelines basing on the template, it is really annoying.

Instead, there should be a possibility to provide a default value for the parameter.
Instead error message, an input querying for default value for new param may be presented. Param and value specified by user will be added to all pipelines, which are using the parameter and does not provide it yet.

**Comment by giorgiosironi** [comment]
:+1: on this issue

**Comment by bladealslayer** [comment]
Even better: allow the possibility to define parameters on template level and then have parameter with the same name defined on a pipeline override that.
