### ISSUE TITLE
Fetch command for external artifacts not loading "Subpath" and "Destination"

### ISSUE THREAD

**Issue by murilodag** [gocd/gocd#8299]
##### Issue Type
- Bug Report

##### Summary
After upgrade from GoCD 20.4 to 20.5, there are a few issues with fetching external files:
1. opening the fetch command for external files does display the configured Subpath and Destination
2. updating the fetch command for external files configuration using the UI from config.xml removed the Subpath and Destination

##### Environment
GoCD 20.5 (after 20.4 migration).

###### Basic environment details

* Go Version: 20.5
* JAVA Version: 13.0.2
* OS: Linux 4.14.97-90.72.amzn2.x86_64
* Browser vendor and version (if relevant): All (newest Chrome, Safari)

##### Steps to Reproduce

1. Open fetch command for external artifact
2. Check Subpath and Destination fields are empty

##### Expected Results
Subpath and Destination must be loaded from config.xml

##### Actual Results
Subpath and Destination are blank and clear config.xml after saving it

**Comment by arvindsv** [comment]
@murilodag This feels like it should be opened as an issue on whatever external artifact plugin you're using, since `Subpath` is not a GoCD concept (but probably introduced by the plugin). Which plugin are you using?

**Comment by murilodag** [comment]
Hello @arvindsv ,

This is the S3 Artifact Plugin from the supported plugins: https://www.gocd.org/plugins/
https://github.com/Diogomrol/gocd-s3-artifact-plugin/releases

**Comment by arvindsv** [comment]
@murilodag: Ok. Then it's best to open an issue there. It's not a plugin maintained by the GoCD team (usually anything in this GitHub org). The author would know best, regarding the plugin. Thanks. I'll close this issue here.

Once analyzed, if it ends up being a GoCD related issue and not a plugin issue, happy to re-open this.

**Comment by murilodag** [comment]
Hello @arvindsv,

It looks like that project is no longer being maintained and it probably needs to be removed from the GoCD supported documentation.

**Comment by arvindsv** [comment]
@murilodag Thanks. It could be. I do see a commit there 3 days ago. So, for now, I've updated the plugin page to make it clear that "unofficial" plugins are community efforts and might be unmaintained.

https://github.com/gocd/www.go.cd/pull/1158

Maybe we can wait a bit and then remove the plugin from the list.
