### ISSUE TITLE
UX/UI issue with Create new configuration repository page

### ISSUE THREAD

**Issue by Sorravit** [gocd/gocd#8301]
##### Issue Type

- Bug Report
or 
- Feature enhancement
##### Summary

Create new configuration repository and Edit configuration repository page does not show a scroll bar or any indication that it's not the end of the page which makes it looks like it's already at the end of the page.
![image](https://user-images.githubusercontent.com/11211053/86326099-662d7880-bc6b-11ea-8e01-c1fd54dd2955.png)

and many people did not realize that there's a part about the Rules and permission
![image](https://user-images.githubusercontent.com/11211053/86326170-80675680-bc6b-11ea-812c-7aea22e4a27c.png)

##### Environment

GoCD v20.5.0 
(Docker gocd/gocd-server:v20.5.)
##### Steps to Reproduce

1. Goto "Config Repositories" page
2. Click "ADD"
3.  It's there
![image](https://user-images.githubusercontent.com/11211053/86326389-d63bfe80-bc6b-11ea-9189-de5aea350825.png)

##### Expected Results
It should show the scroll bar or some indication that it's not the end of the page yet

##### Actual Results
The page did not have any indication that it does not reach the end yet.

##### Possible Fix
make scroll bar visible
or have the save button at the end of the page

**Comment by arvindsv** [comment]
Scroll bars are no longer controlled easily by app developers. :( For instance, on a Mac it is controlled at the system level. Not sure how it is on other OSes.

Also, this is a common style of modal in many places across the app, so changing the "Save" button to be inside the inner (scrolling) part will end up changing it in many other places, which might not be appropriate. :/
