### ISSUE TITLE
plugin role disabled

### ISSUE THREAD

**Issue by singhalss** [gocd/gocd#8303]
Hi,

We installed and configured go-server. We have enabled and configured "authorisation configuration" and successfully connected to our LDAP server for authentication purposes. We are able to login as a user using our AD account id. Now when we are trying to create plugin role for one of our AD group, it is shown as disabled. 

As per the documentation as mentioned on the link - https://extensions-docs.gocd.org/ldap/current/plugin-role-configuration/
we are meeting all the requirements and still not getting plugin role enabled.

Appreciate if somebody can please guide us in resolving this.

**Comment by maheshp** [comment]
@singhalss GoCD comes bundled with [LDAP Authentication plugin](https://github.com/gocd/gocd-ldap-authentication-plugin). To configure plugin roles you would need [LDAP Authorization plugin](https://github.com/gocd/gocd-ldap-authorization-plugin).
Once you [download](https://github.com/gocd/gocd-ldap-authorization-plugin/releases) and install the latest stable version, refer to the [docs](https://github.com/gocd/gocd-ldap-authorization-plugin/blob/master/docs/PLUGIN_ROLE_CONFIGURATION.md) to configure the plugin role.

**Comment by singhalss** [comment]
thanks @maheshp
