### ISSUE TITLE
Validate empty tasks in a job

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8308]
##### Issue Type

- Bug Report

##### Summary

Currently, GoCD allows defining an empty job which contains no tasks. GoCD should not allow defining an empty job or removing all the tasks from a job.

Related Issues: #8286 #8177 #8194

**Comment by kritika-singh3** [comment]
Completed and Verified as per [comment](https://github.com/gocd/gocd/pull/8309#issuecomment-659316492)
