### ISSUE TITLE
Handle branches for mercurial post commit hook 

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#832]
This is an issue for #781

Issue 1 -
Steps to Reproduce -
1) Create an hg repo called 'hg_repo'
2) Have 2 branches 'default' and 'branch1' for the repo and setup post commit hook for the repo
3) Have 2 pipelines P1 and P2 in Go
4) Let P1 have 'hg_repo' (default) as the material and P2 have 'hg_repo' (branch1) as the material and polling is turned off
5) Make a checkin in the repo for branch1 and pipeline P2 should trigger but it does not
6) Make a checkin in the repo for branch default and pipeline P1 triggers if the material url is specified as '../hg_repo' and not if it is specified as '../hg_repo##default'

Issue 2 - 
1) The behavior if post commit hook has credentials specified in it (and so does the repo), does not seem to be correct. Talk to Arika for more details

**Comment by mdaliejaz** [comment]
Issue 1:
The post commit hook works if single hash is used in the URLs.
Would be fixing other parts to accept single hash instead of making post commit hook use double hash. More details on issue #854.

**Comment by arikagoyal** [comment]
Post commit hook works fine if single hash is used post commit hook url's. Issue 2 is not an issue. Works fine on 15.1.0(1445-488540650a0611)
