### ISSUE TITLE
Reminder: Update YAML and Groovy config repo plugins for #8266

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#8333]
See: https://github.com/gocd/gocd/pull/8266#issuecomment-656234110

**Comment by GaneshSPatil** [comment]
Verified as part of https://github.com/gocd/gocd/pull/8266#issuecomment-656398034

**Comment by arvindsv** [comment]
@GaneshSPatil I don't think this is finished. Older versions will work fine, but the new `target_version` won't be supported (and export will also not work properly).

**Comment by GaneshSPatil** [comment]
apologies 😞 

reopening...

**Comment by maheshp** [comment]
Groovy Plugin v1.1.0  released - https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin/releases/tag/v1.1.0-233
GoCD 20.8.0 bundled with YAML Plugin v0.13.0 - https://github.com/gocd/gocd/pull/8559
