### ISSUE TITLE
GO - User API: User with space in name returns HTTP 422

### ISSUE THREAD

**Issue by ankitsri11** [gocd/gocd#834]
Steps to reproduce : 

1. Create a user with space in the name. e.g. 'test user'
2. Try to delete user through user API, you'll get http 422 response.
    Both the below urls are not working.
    http://goserver.com:8153/go/api/users/test user
    http://goserver.com:8153/go/api/users/test%20user

Note : User delete without space is working fine.

Below logs are generated for the API request : 

2015-01-13 14:57:58,716 WARN [1278255007@qtp-2137048240-14] Rails:? - Can't verify CSRF token authenticity
2015-01-13 14:57:58,725 FATAL [1278255007@qtp-2137048240-14] Rails:? - 
ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken):
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/actioncontroller/metal/request_forgery_protection.rb:166:in handle_unverified_request'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/request_forgery_protection.rb:173:inhandle_unverified_request'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/request_forgery_protection.rb:180:in verify_authenticity_token'
vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:380:in_run696230756process_actioncallbacks'
vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:80:in run_callbacks'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/callbacks.rb:17:inprocess_action'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/rescue.rb:29:in process_action'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:31:inprocess_action'
vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:in instrument'
vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications/instrumenter.rb:20:ininstrument'
vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications/instrumenter.rb:19:in instrument'
vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/notifications.rb:159:ininstrument'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/instrumentation.rb:30:in process_action'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/params_wrapper.rb:250:inprocess_action'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/base.rb:136:in process'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/abstract_controller/rendering.rb:44:inprocess'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal.rb:195:in dispatch'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal/rack_delegation.rb:13:indispatch'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_controller/metal.rb:231:in action'
org/jruby/RubyProc.java:271:incall'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:80:in dispatch'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:48:incall'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:71:in call'
org/jruby/RubyArray.java:1613:ineach'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/journey/router.rb:59:in call'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/routing/route_set.rb:674:incall'
vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/etag.rb:23:in call'
vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:incall'
vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/head.rb:11:in call'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/params_parser.rb:27:incall'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/flash.rb:241:in call'
file:/Users/anishn/Library/Application Support/Go Server/work/Jetty_0_0_0_0_8153_cruise.war__go__.mt8b37/webapp/WEB-INF/lib/jruby-rack-1.1.14.jar!/jruby/rack/session_store.rb:79:incontext'
vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in call'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/cookies.rb:486:incall'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/callbacks.rb:29:in call'
vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:376:in_run1288996771callcallbacks'
vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/callbacks.rb:80:in run_callbacks'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/callbacks.rb:27:incall'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/remote_ip.rb:76:in call'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:incall'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in call'
vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/rack/logger.rb:38:incall_app'
vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/rack/logger.rb:22:in call'
vendor/bundle/jruby/1.9/gems/actionpack-4.0.4/lib/action_dispatch/middleware/request_id.rb:21:incall'
vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in call'
vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/runtime.rb:17:incall'
vendor/bundle/jruby/1.9/gems/activesupport-4.0.4/lib/active_support/cache/strategy/local_cache.rb:83:in call'
vendor/bundle/jruby/1.9/gems/rack-1.5.2/lib/rack/sendfile.rb:112:incall'
vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/engine.rb:511:in call'
vendor/bundle/jruby/1.9/gems/railties-4.0.4/lib/rails/application.rb:97:incall'
file:/Users/anishn/Library/Application Support/Go Server/work/Jetty_0_0_0_0_8153_cruise.wargo_.mt8b37/webapp/WEB-INF/lib/jruby-rack-1.1.14.jar!/rack/handler/servlet.rb:22:in `call'

**Comment by rajiesh** [comment]
Verified this defect on 15.3.0-2672(47fd7343016e4a9cda3f8a871539007c2d1cf1b9).

Current behavior as observed in the test,

* Users with special chars(tested with dot(.), !, space, ampersand) are allowed to be added as go user
* From UI enable / disable users with spec chars are also successful
* Users API(DELETE, GET and PATCH) returns 404 for users with special chars(except for users with dot(.) in login name)
* Get all Users API return 500 response if any on user has space in the login name

**Comment by maheshp** [comment]
Related to #1650

**Comment by arvindsv** [comment]
Closing in favor or #1650 and #1706.
