### ISSUE TITLE
Limit number of concurrently running jobs for run on all agents

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#835]
'Run on all agents' can be used to deploy an application to 1 or more servers. To ensure zero-downtime for production deployments I like to only have a fixed number or a percentage of the servers running the update job at the same time, so there are always machines active. A feature to limit the concurrently running jobs, but in the end run it on all agents will help to do this without setting up separate stages for updating part of the machines.

**Comment by jefftrimm** [comment]
Sounds similar to https://github.com/gocd/gocd/issues/827
I think the intent and use cases are the same...

**Comment by JorritSalverda** [comment]
Yes, it's identical. Sorry for not spotting that one before.
