### ISSUE TITLE
[Bug] Config Repositories does not honor rules

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8368]
## Error 1: Pipelines coming from config repository are shown on dashboard even on rules failure.

When a config repository rules are modified to deny pipelines coming from it, GoCD does not honor those rules and such pipelines are shown on the dashboard.

#### Steps to reproduce:

1. Go to Config Repositories SPA.
2. Add a new config repository with allow everything rule.
3. Wait for GoCD to parse the pipelines.
4. Verify pipelines are shown on the dashboard.
5. Edit the config repository and remove the rules.
6. On the config repo SPA, appropriate parse error message is shown.
7. But, visiting the dashboard shows all the pipelines from config repository.

## Error 2: Stale config repository errors even on a successful parse

When config repository rules edited and specified all the appropriate rules for the entities coming from the config repository. On a successful parse, all the entities config from config repository are shown within GoCD, but shows a stale rules violation error.

#### Steps to reproduce:

1. Go to Config Repositories SPA.
2. Add a new config repository with allow everything rule.
3. Wait for GoCD to parse the pipelines.
4. Verify pipelines are shown on the dashboard.
5. edit the config repository and remove the rules.
6. Wait for parse error message to show (along with no pipelines).
7. edit the config repository again and add allow everything rule.
8. Upon successful parse, the pipeline coming from repository are shown, but also contain stale config repository rules violation error.

## Error 3: Last Known Partials are not validated against the current config repo rules

Let's say a config repository is valid with entity validations and rules.  Later a commit is made to the repo which causes invalid config and previous valid configuration is shown in GoCD. 
Now, editing the config repository rules to deny everything should cause configuration from previous commit to go away due to rules violation, but such configuration can be seen within the application.

#### Steps to reproduce:

1. Go to Config Repositories SPA.
2. Add a new config repository with allow everything rule.
3. Wait for GoCD to parse the pipelines.
4. Verify pipelines are shown on the dashboard.
5. Now make a commit to the repository which makes the configuration invalid.
6. Verify that the latest commit is marked as invalid on the config repo spa.
7. Verify that the pipelines and environments from the previous valid commits are shown on the dashboard.
8. Now edit the config repository and remove rules.
9. Upon save, GoCD should remove the last valid pipelines as those are invalid wrt to the current config repo rules.

**Comment by GaneshSPatil** [comment]
## Error 4: Updating rules to deny entities does not remove pipelines when it has dependent pipelines
 
When a config repo pipeline is dependent on a pipeline coming from another config repository. Updating the upstream pipeline config repository rules to deny pipeline does not removes the upstream pipeline from config.
 
 This issue is reproducible on GoCD versions 20.2.0 and above
 
#### Steps to reproduce:

 1. Define a config repository 'up'  contains pipeline 'upstream' with rule allow everything.
 2. Wait for pipeline 'upstream' to be shown on the UI.
 3. Define a config repository 'down'  contains pipeline 'downstream' (which has pipeline 'upstream' as material) with rule allow everything.
 4. Wait for pipeline 'downstream' to be shown on the UI.
 5. Now edit the config repository 'up' and update rule to deny all.
 6. Config repository 'up' shows rules violation errors.
 7. But pipeline 'downstream' can still be seen on dashboard.

## Error 5: Updating rules to deny entities on an invalid config repository causes invalid GoCD configuration

When a config repo pipeline is dependent on a pipeline coming from another config repository which has errors. Updating the upstream pipeline config repository rules to deny pipeline removes the upstream pipeline from the config causing the downstream pipeline refer to a non existing pipeline.

1. Define a config repository 'up'  contains pipeline 'upstream' with rule allow everything.
2. Wait for pipeline 'upstream' to be shown on the UI.
3. Define a config repository 'down'  contains pipeline 'downstream' (which has pipeline 'upstream' as material) with rule allow everything.
4. Wait for pipeline 'downstream' to be shown on the UI.
5. Make a commit to config repository 'up' which causes invalid configuration
6. Wait for an invalid configuration errors to show up on the 'up' config repository on config repository spa.
7. Verify pipeline 'upstream' is available on dashboard dispite of the errors (due to last valid partials).
8. Now edit the config repository 'up' and update rule to deny all.
9. Config repository 'up' shows rules violation errors.
10. Pipeline 'upstream' is not available on the dashboard.
11. But, pipeline 'downstream' is present which refers to a non-existing 'upstream' pipeline
12. On the config repository spa, config repo 'down' should show config validation errors for 'upstream' material.

**Comment by maheshp** [comment]
Error 1, 2, 3 are fixed and verified on GoCD Version: 20.6.0 (11995-0500dc2e9647d2ccffb976c3d9228bad7426fdbd).

Errors 4 and 5 needs to be fixed.
