### ISSUE TITLE
Ability to fail a manual stage

### ISSUE THREAD

**Issue by mythgarr** [gocd/gocd#837]
Many workflows include a manual QA/approval stage where manual testing is performed. Currently, this requires separately tracking the status of each manual step. It would be useful to be able to set a manual stage's status to failed (bonus points for allowing a comment/explanation).

**Comment by bdsl-foundry** [comment]
I've just been learning Go in the last few weeks and this is also something I thought would be useful.

It seems that go doesn't exactly support manual jobs, as far as I can tell - it supports manual **triggering** of jobs, but not manual completion of jobs.

I imagined a feature where person completing a manual job can log in to the Go Server and type in or upload any artefacts they have produced, and click a button to complete the job as either a pass or fail.

**Comment by bdsl-foundry** [comment]
A possible work-around would be to make a custom command to run an external executable which connects to the API of a separate website where work in progress is displayed and testers can enter their reports. The executable would poll the API until the manual job has a 'passed' or 'failed' stage and then return zero or non-zero to Go.

**Comment by arvindsv** [comment]
@bdsl-foundry Yes, I understand. Currently, it is a "Stage approval" and not necessarily a manual completion step. There is no plan, in progress, to change this, unfortunately.
