### ISSUE TITLE
Combining config repositories with environments

### ISSUE THREAD

**Issue by Keksparade** [gocd/gocd#8370]
##### Issue Type

- Bug Report
- Documentation Report

##### Summary

We have  a GoCD server 20.2 grown over the time, containing multiple environments to group pipelines and agents. Now we're adding new pipelines using the config repositories feature. Unfortunately, they cannot be added to any environment. Neither by the UI (`unavailable pipelines`), nor by editing the config XML (`Environment defined in com.thoughtworks.go.config.remote.FileConfigOrigin@5b9b cannot reference a pipeline in https://<subversion_material>/trunk at 6793`). Is it not possible to add a pipeline to an environment using config repositories? Either this is a bug or if this is "works as designed" some hint in the documentation would be nice.

##### Environment

* Number of pipelines: 131
* Number of environments: 6
* Number of agents: 32
* Number of unique materials: 135
* Number of schedulable materials: 68

###### Basic environment details

* Go Version: `20.2.0 (11344-0cb6660ad91a19a4064e6537374c896506add24a)`
* JAVA Version: `13.0.2`
* OS: `Linux 4.15.0-109-generic`

##### Steps to Reproduce

1. Setup two environments A and B, add pipelines and agents to them
2. Configure a pipeline using config repository
There's no chance to add the pipeline to an environment. The pipeline will never run, since no agent will ever fetch the job.

##### Expected Results

Allow adding a config repository pipeline to an existing environment either via UI or via definition in the YAML file.

##### Actual Results

Pipeline cannot be added to an environment. Agents never fetch the job.

**Comment by Keksparade** [comment]
The pipeline would be fetched, if there would be an agent not belonging to any environment. Is there any chance to assign an agent at the same time to "no" and additionally a specific environment? 

As a workaround I'll try to move the 60 pipelines and 15 agents from their current environment to no environment to make this work.

**Comment by arvindsv** [comment]
> Is it not possible to add a pipeline to an environment using config repositories?

It should be. That's a normal operation.

You haven't mentioned which config repo type you're using (JSON, YAML, etc). It might be useful to open this issue in the repo of the corresponding type.

https://github.com/tomzo/gocd-yaml-config-plugin/

https://github.com/tomzo/gocd-json-config-plugin

_How_ an environment is associated with a pipeline depends on that?

Also: An example of your usage might help. Maybe it's something as simple as the usage being in the wrong location.

**Comment by arvindsv** [comment]
Also see:

https://github.com/tomzo/gocd-yaml-config-plugin/#environment

https://github.com/tomzo/gocd-json-config-plugin/#file-pattern

Also: In 20.2.0, [rules were introduced](https://www.gocd.org/releases/#20-2-0) for config repos. The default rule is usually to "Deny All". So, you might need to configure a rule to allow a pipeline to be associated with an environment by adding a rule.

https://docs.gocd.org/current/advanced_usage/pipelines_as_code.html#specifying-rules

**Comment by GaneshSPatil** [comment]
Hi @Keksparade,

Have you tried defining a config repository environment to add the config repository pipelines to it?
See [YAML Plugin Environment Format](https://github.com/tomzo/gocd-yaml-config-plugin#environment), [JSON Plugin Environment Format](https://github.com/tomzo/gocd-json-config-plugin#environment) and [Groovy Plugin Environment Format](https://github.com/gocd-contrib/gocd-groovy-dsl-config-plugin) to define a config repository environment.

Couple of points:

#### Point 1: GoCD's Merged Environment
GoCD has a concept of merge environment, which means the same GoCD environment can be defined (partially) at many places. 
Let's see an example: 
  - We've defined a pipeline `Build-Linux` in cruise-config.xml and another pipeline `Build-Windows` in a config repository. Now, both of these pipelines needs to belong a single environment named `Build`.
  - To achieve so, we can create an environment from GoCD UI named `Build` and add pipeline `Build-Linux` to it. Though, the option to add pipeline `Build-Windows` to it would be disabled (See point 2 for the reason).
  - Then, we can use any of the above-mentioned plugin to define the remaining part of the environment `Build` in the config repository, which adds pipeline `Build-Windows` to it.

The merged environments feature of GoCD allows defining the same environment in different config repositories as well.

#### Point 2: Environments and Pipelines

GoCD does not allow referencing a config repository entity. Meaning any of the entities defined in the main cruise-config.xml can not refer to any of the entities coming from a config repository for various validation reasons.
Example: Adding config repository pipeline to a cruise-config.xml environment.

**Comment by Keksparade** [comment]
Thank you **so much** for the really quick support. It was my fault, as I didn't recognize there is so much more information and documentation about the yaml configuration plugin. This link did the trick:

https://github.com/tomzo/gocd-yaml-config-plugin/#environment

I simply had to explicitly add the environment and the fact that the pipeline defined in the config repository belongs to this environment to my yaml. Thanks again. I will have a careful look at the detailed documentation of the gocd-yaml-config-plugin!
