### ISSUE TITLE
GoCD Test Drive for 20.5.0 breaks due to an outdated database format

### ISSUE THREAD

**Issue by ZeWaka** [gocd/gocd#8377]
##### Issue Type
- Bug Report

##### Summary
Attempting to run the Test Drive with version 20.5.0 will result in the GoCD server failing to boot due to an outdated database.

##### Environment
Running in a Windows Sandbox.

###### Basic environment details

* Go Version: 2.50.0
* JAVA Version: Version 8 Update 261
* OS: Windows 10 Pro

##### Steps to Reproduce
1. Download the test drive
2. Notice that it fails to boot
3. Look at the logs and see tons of database migration errors
4. It hangs on `Wating for the GoCD server to finish initializing................`

##### Expected Results
Test Drive should work out the box.

##### Actual Results
GoCD server fails to boot.

##### Log snippets
https://pastebin.com/JyqVGL6k

**Comment by ls-devon-hakel-kinko** [comment]
I had the same issue after testing on Windows and Debian.

**Comment by marques-work** [comment]
@ZeWaka @ls-devon-hakel-kinko I've regenerated the prepackaged configs and published. This should be fixed now with the 20.5.0-11820-1043 release of the test-drive. Sorry for the inconvenience, and thanks for reporting.

**Comment by marques-work** [comment]
Closing this now - please reopen if the problem still persists.
