### ISSUE TITLE
Update Yum plugin to work on CentOS/RHEL 8

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#8389]
RHEL 8 distros have switched to `dnf` as the package manager, with `yum` as an alias.

The `repoquery` tool in such newer distros does not support the `BUILDHOST` parameter. We should update the plugin to no longer query for this data. Currently, the `BUILDHOST` field is stored in the `comment` field in the `modifications` table. We should stop doing this so that the plugin works on RHEL 8 distros.

**Comment by maheshp** [comment]
Duplicate of - https://github.com/gocd/gocd/issues/8404
