### ISSUE TITLE
Fix YUM package material plugin to work on RHEL 8

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#8404]
Our build agents are all on CentOS 8 now. Regressions are failing because RHEL 8 distros now use `dnf` as the new package manager and there are breaking changes in its implementation of `repoquery`.

See gocd/gocd-yum-repository-poller-plugin#67

**Comment by kritika-singh3** [comment]
This issue was fixed on the plugin. The plugin version bundled with GoCD has also been updated in https://github.com/gocd/gocd/commit/1f8c11baec501f02768caba5b7287b16e72b8776
