### ISSUE TITLE
Change project name to something unique

### ISSUE THREAD

**Issue by webmaster128** [gocd/gocd#843]
As a happy user of Go, I find it terribly hard to google for Go related content, if there are advanced questions.

Even when I add the (extremely long and hard to type) keyword "Continuous Delivery", I get more hits of alternative products than Go related content.

E.g. check the first 10 search results of:

[Google: continuous delivery subfolder artefact](https://www.google.com/search?q=go+continuous+delivery+subfolder+artefact)

* 1x Go.cd frontpage
* 9x content about other CI systems

or [Google: go cd subfolder artefact](https://www.google.com/search?q=go+cd+subfolder+artefact)

* 2x thoughtworks.com
* 1x github.com/gocd
* 7x entirely unrelated content (`cd` is a not-so-rare Linux command)

I made the same experience with dozens of other terms as well, which is a real productivity killer in my opinion.

**Comment by srinivasupadhya** [comment]
I think its same as #128. Please add your comments there.
