### ISSUE TITLE
Dashboard Stage Overview Issues

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8438]
##### Issue Type

- Bug Report

##### Summary

- [x] Misaligned stage success / failure / cancelled icon. (aligned more to bottom).
- [x] Increase width of the stage name on the stage overview.
- [x] Job tooltip position when scrolling
- [x] Job tooltip position for the jobs (where index of the job is more than 5)
- [x] Job state indication (building/passed/failed) bar shrinks in width when job name is longer.
- [x] Capitalize job state.
- [x] Rerun tooltip should say "Rerun Stage".
- [x] Use external link icon for stage details page link.
- [x] Show server time on hover for:
  - [x] Stage triggered on.
  - [x] Stage cancelled on.
- [x] [Bug] Rerun failed doesn't seem to work (when the first stage is failed and second stage hasnt yet run).
- [x] Change job table header field from 'job' to 'job name'.
- [x] Sortable table header.
- [x] Increase the height of the scrollable window to denote there are more items.
- [x] Tooltip opacity issue
- [x] Increase polling interval to 10sec
- [x] Always show ellipsis on agent column.
- [x] Position job rerun buttons to the left
- [x] Relative job progress bar

##### Good to have:
- [ ] Should close stage overview when pressed ESC?

**Comment by kritika-singh3** [comment]
<img width="873" alt="Screen Shot 2020-08-10 at 9 54 19 AM" src="https://user-images.githubusercontent.com/41165891/89751870-8add0180-daef-11ea-86e6-a298ce806e25.png">

 - [ ] Inconsistent icon size when one job is completed and rest are in progress (or vice-versa)
 - [ ] `building` and `in progress` should be capitalized as in `Passed`
 - [ ] The agent column is not consistent - maybe be can set the max chars as 8 and show an ellipse
 - [ ] If the current stage is in `Building` or `Failing` state - the checkboxes and the action buttons should not show up

**Comment by GaneshSPatil** [comment]
@kritika-singh3 -

> * [ ]  Inconsistent icon size when one job is completed and rest are in progress (or vice-versa)
> * [ ]  `building` and `in progress` should be capitalized as in `Passed`
> * [ ]  The agent column is not consistent - maybe we can set the max chars as 8 and show an ellipse

Point 1/2/3 has been fixed and moved to the issue description checklist.

> * [ ]  If the current stage is in `Building` or `Failing` state - the checkboxes and the action buttons should not show up

While re-doing the dashboard work, we've decided that we should always show all the action icons and disable them with appropriate message. Reasoning - removing particular action icon without reasoning may be unclear/confusing for the user.

> * [ ]  The failed and building jobs should be shown high in the order as on the stage details page

Sorting based on state while the stage is building may result into stage jumbling. As on an update, a newly failed job will change the sort order. We're planning to add sort jobs based on the header (name, state, duration), do you think it is sufficient?

**Comment by kritika-singh3** [comment]
> While re-doing the dashboard work, we've decided that we should always show all the action icons and disable them with appropriate message. Reasoning - removing particular action icon without reasoning may be unclear/confusing for the user.

Ok if this has been decided prior. Please make sure to disable the checkboxes as well and add a tooltip for them.

> Sorting based on state while the stage is building may result into stage jumbling. As on an update, a newly failed job will change the sort order. We're planning to add sort jobs based on the header (name, state, duration), do you think it is sufficient?

Might be. My reasoning was most people are interested in failed rather than passed jobs. Imagine a stage with more than 20 jobs. The dashboard shows it as failing/failed. On clicking the stage - I would want the failed jobs upfront rather than have to search for the same.
If you look on the current stage details page, the failed jobs are been shown on top. IMO, this might have been the reason.

cc:\ @GaneshSPatil

**Comment by maheshp** [comment]
Stage overview gives a option to re-run a stage when the stage is still building. The re-run option is shown when one of the job in the stage finishes.

<img width="840" alt="Screen Shot 2020-08-11 at 11 47 13 AM" src="https://user-images.githubusercontent.com/1061051/89936673-d7e0d680-dbc8-11ea-82ea-57144bdac940.png">

**Comment by maheshp** [comment]
Verified on GoCD Version: 20.7.0 (12081-b3abf30ba7f72def573ac96246eab1ad764ec184)

Pending items which can be done as part of new issue.
1. Sortable table header.
2. Should close stage overview when pressed ESC?

**Comment by maheshp** [comment]
> Pending items which can be done as part of new issue.
> 1. Sortable table header.
> 2. Should close stage overview when pressed ESC?

Sortable table header is done.
