### ISSUE TITLE
How to wait for server startup

### ISSUE THREAD

**Issue by liweinan0423** [gocd/gocd#844]
We are going to do functional tests with Go Server. The workflow is to first start a tomcat server where the product is running, then execute some functional tests to test the RESTful webservices. But the problem is the functional will fail if the server has not been started up yet, so how to let the job waiting for the server to start up in Go Server?

**Comment by srinivasupadhya** [comment]
This is a discussion topic & should be taken up on [go-cd](https://groups.google.com/forum/#!forum/go-cd).

**Comment by liweinan0423** [comment]
thanks a lot. I have posted a new topic in the group.
