### ISSUE TITLE
Secure Parameters

### ISSUE THREAD

**Issue by ghost** [gocd/gocd#845]
There are secure Environment Variables, but no Secure Parameters.  I know we can solve this with environment variables, but, as far as I can tell, we can require environment variables be set prior to the running of the pipeline which means it's harder to catch those failures.  It's really nice that Parameters are required to be defined before they can be specified in a task.  This is _particularly_ useful when there is a build template with multiple pipelines using it.

Specifically, my issue is that I have 12 build jobs that all share the a common template.  They only differ on a few strings (usernames, passwords, binary names, etc.) and I want to parameterize them as a good way of enforcing standardization across the various implementing pipelines.  This works great for now, but it means that I have to embed my passwords in plaintext which is no bueno.

**Comment by reidca** [comment]
+1 - This is really important for us as well

**Comment by jefftrimm** [comment]
+1 
Agree-- this is important for effective templatization of pipelines.

**Comment by Cyberclown** [comment]
+1 - Especially for password in the git material config

**Comment by maheshp** [comment]
GoCD introduced support for [Secret Management](https://docs.gocd.org/current/configuration/secrets_management.html) in 19.6.0. Currently Secret Params can be used in password filed for a SCM material and environment variables.

As a replacement for secure parameters one of the option is to use a paramter with the value as Secret Parameter. 
If this is not a good enough replacement, please list out the specific uses case. I will be closing this issue for now.
