### ISSUE TITLE
Init script - calls to start-daemon should be redirected

### ISSUE THREAD

**Issue by stevendgonzales** [gocd/gocd#846]
https://github.com/gocd/gocd/blob/master/installers/server/release/init.cruise-server#L71-73

Attempting to create a saltstack formula for installing go-server, and pkg install command hangs.  This is cause by the start_daemon call not redirecting output, and salt is waiting for the stdout file descriptor to close.

This also affects any calls from salt to start the service.

**Comment by stevendgonzales** [comment]
Will submit patch for this once labeled

**Comment by arvindsv** [comment]
Closed because #847 was closed.
