### ISSUE TITLE
Issues while updating the gocd server and migrating the database.

### ISSUE THREAD

**Issue by Meet116** [gocd/gocd#8487]
##### Summary
Having issue after migrating the database from h2 to h2. GOCD server is not able to start shows this error.

![image](https://user-images.githubusercontent.com/56951062/91304048-83dc1180-e7c6-11ea-92d2-9142a4919734.png)

###### Basic environment details

* Go Version: `20.1.0`
* JAVA Version: `13.0.1`
* OS: `Linux 4.4.0-1102-aws`

**Comment by maheshp** [comment]
@Meet116 is this happening after following the steps mentioned in https://docs.gocd.org/20.5.0/installation/upgrade_to_gocd_20.5.0.html 

Was the GoCD server stopped before upgrading?

**Comment by Meet116** [comment]
yes

**Comment by maheshp** [comment]
Can you please list the contents of the folder `/var/lib/go-server/db/h2db'? Have you taken a backup of your GoCD server before attempting an upgrade?

**Comment by Meet116** [comment]
Yes - I do take the backup of cruise.h2.db file. Contests in h2db folders are cruise.lock.db, cruise.mv.db, cruise.mv.db and new_cruise.trace.db

**Comment by maheshp** [comment]
Can you please ensure there are no GoCD instances running, you can try running `ps aux | grep java` and check if there is any java process running for your GoCD instance.

Once you ensure that the GoCD instance is not running, under the folder `/var/lib/go-server/db/h2db ` please retain the file `cruise.mv.db` (this should be your new migrated db) and delete rest of the files and try restarting your server.

**Comment by Meet116** [comment]
I kill all the go delete all the file except cruise.mv.db. But somehow it takes SQL database I think.
![image](https://user-images.githubusercontent.com/56951062/91386745-52f4ee80-e851-11ea-9747-2e977641c634.png)

**Comment by maheshp** [comment]
Wondering if this is an issue with file permission.

Can you check the file permissions for the file `cruise.mv.db`, it should be same as what was for old `cruise.h2.db`.
I am assuming you are using the linux installer, hence the `go` user should have read/write permission for the file  `cruise.mv.db`.

**Comment by Meet116** [comment]
Thanks issue is solved folder ownership is root
