### ISSUE TITLE
Agent API should support assigning resources to an agent

### ISSUE THREAD

**Issue by jefftrimm** [gocd/gocd#849]
The Agent API should support assigning resources to an agent.  

Consider this scenario:  if the centralized list of deployment hosts for an application is managed in Puppet or some other external source of configuration, we want the creation of an application server instance running the Go Agent within the external application host list to trigger a pipeline in Go to both approve an agent and also define a resource tag on that Agent to target Go's deployment orchestration via Go's agents.

**Comment by srinivasupadhya** [comment]
Duplicate - #264. Please comment on that issue.

**Comment by srinivasupadhya** [comment]
Also, you can assign resource & environment using an undocumented Agent API. [reference](https://groups.google.com/d/msg/go-cd/LT3ZUEn_kRE/Fw8euL3Tw3IJ)
