### ISSUE TITLE
[Stage Overview] Invalid stage settings link when a pipeline is defined from a template.

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8490]
##### Issue Type

- Bug Report

##### Summary

Stage overview popup takes to an invalid stage settings page when the pipeline is defined from a template.

###### Basic environment details

* Go Version: `20.7.0`

##### Steps to Reproduce

1. Create a pipeline from template.
2. Trigger Pipeline.
3. Open stage overview for the first stage.
4. Click stage settings gear icon.

##### Expected Results
The page should redirect to stage edit tab on the template edit page.

##### Actual Results
The page redirects to an invalid page.

**Comment by kritika-singh3** [comment]
Fixed and verified in #8491
