### ISSUE TITLE
Authentication plugin end-point

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#851]
There is quite some interest in Go users to use authentication scheme other than LDAP & File based. There is scope for many schemes to be implemented like OAuth - [1](https://groups.google.com/d/topic/go-cd/EZ09NfghHAs/discussion) & [2](https://groups.google.com/d/topic/go-cd/-YLb-61xhZs/discussion), 2-factor authentication - #34, SSO - #733 etc. Makes for a good end-point.

---

Support:

- [x] support web request handling
  - [x] ability to render view
  - [x] ability to redirect to a given URL
- [x] support required request processors
  - [x] ability to put/get/remove data from session
  - [x] ability to authenticate user (i.e. tell Go Server a user is authenticated & can be treated as a logged in user)
- [x] end-point
  - [x] ability to authenticate `username` & `password` (additional methods of authentication - other than LDAP & Password file)
  - [x] ability to search users by a search term

- [ ] To Do:
  - [x] Decide UI/UX for listing authentication plugins on login page & implement it 
  - [x] Decide if [SecurityConfig.isSecurityEnabled()](https://github.com/gocd/gocd/blob/7958ac8b613031660ee00f0591af792c06c0f74c/config/config-api/src/com/thoughtworks/go/config/SecurityConfig.java#L67) be true if ldap=false & password-file=false but authentication plugin exists
  - [ ] Decide behavior for error scenarios in username & password login when ldap, password file & plugins are involved. (code: `PluginAuthenticationProvider`, `AuthenticationProcessingFilter`). fix [Twist test](https://build.go.cd/go/tab/build/detail/regression/288/twist/1/firefox-split-runInstance-15)
  - [ ] Decide behavior for error scenarios in user search when ldap, password file & plugins are involved (code: `UserSearchService`)

---

[Developer Docs](http://www.go.cd/documentation/developer/writing_go_plugins/authentication/authentication_plugin_overview.html)
[Sample plugin](https://github.com/gocd/go-plugins/tree/master/plugins-for-tests/test-authentication-plugin)
[GitHub OAuth plugin](https://github.com/srinivasupadhya/gocd-oauth-login)

**Comment by jyotisingh** [comment]
Moved the card back to awaiting development lane, until the bugs get fixed.

**Comment by zabil** [comment]
Verified on 15.2.0(2170-05c70bb21bf9d3)

Closing this for now. 
Enable the authentication plugin [twist test] (https://build.go.cd/go/tab/build/detail/regression/288/twist/1/firefox-split-runInstance-15) after release 15.2 to implement fix for better error handling.
