### ISSUE TITLE
Test Connection with ## in Repository URL doesn't work in Pipeline Wizard

### ISSUE THREAD

**Issue by JeroenOortwijn** [gocd/gocd#8524]
##### Issue Type

- Bug Report

##### Summary

Testing the connection to an SVN repository in the Pipeline Wizard doesn't work when it contains two hash signs (##).

###### Basic environment details

* Go Version: `20.7.0 (12097-f4f86ca8d433edaf9235ed92790c11e19d7be4ed)`
* JAVA Version: `13.0.2`
* OS: `Linux 5.4.0-45-generic`
* Browser vendor and version (if relevant): `not relevant`

###### Additional Environment Details

None

##### Steps to Reproduce

1. From the dashboard, click on `New Pipeline` -> `Use Pipeline Wizard`
2. Select `Subversion` as material type.
3. Fill in `svn://10.0.0.250/Software/MoveTo/trunk/C##` as repository URL.
  The repository URL is `svn://10.0.0.250/Software/MoveTo/trunk/C#`, but the hash sign needs to be escaped by another hash sign.
4. Click on Test Connection.

##### Expected Results
The message
```
Connection OK
```
appears.

##### Actual Results
The message
```
svn: Malformed URL svn://10.0.0.250/Software/MoveTo/trunk/C## : 
Error performing command: --- Command ---
svn log --non-interactive --xml -v --limit 1 svn://10.0.0.250/Software/MoveTo/trunk/C##
--- Environment ---
{}
--- INPUT ----


--- EXIT CODE (1) ---
--- STANDARD OUT ---
<?xml version="1.0" encoding="UTF-8"?>
<log>
--- STANDARD ERR ---
STDERR: svn: E160013: File not found: revision 3737, path '/MoveTo/trunk/C##'
---
```
appears.

##### Possible Fix
Use the same code for the `Test Connection` button as the one on the `Edit material - Svn` page. The `Test Connection` button on that page does work with the `svn://10.0.0.250/Software/MoveTo/trunk/C##` repository URL.

##### Log snippets
None

##### Code snippets/Screenshots
Screenshot showing error in `Material Wizard`:
> ![Annotation 2020-09-04 140206](https://user-images.githubusercontent.com/51476918/92238451-971f6900-eeb9-11ea-818a-c61163918c6b.png)

Screenshot showing correct result on `Edit material - Svn` page:
> ![Annotation 2020-09-04 140256](https://user-images.githubusercontent.com/51476918/92238843-4e1be480-eeba-11ea-937d-231236e1cca9.png)

##### Any other info
None

**Comment by maheshp** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/8526
