### ISSUE TITLE
Allow '#' single hash in config

### ISSUE THREAD

**Issue by mdaliejaz** [gocd/gocd#854]
## Current behaviour

If one tries to save config with a single hash (in param resolvable fields), save fails with the following validation error:
_"... # must be followed by a parameter pattern or escaped by another #"_

> '#{PARAM}' is used for using parameters. '##' is used to specify '#' in URLs.
## Why should the config allow single hash?

Single hash is used in URLs. To specify branches in mercurial the URL used is `<repository URL>#branch-name`. In Go this URL is specified as `<repository URL>##branch-name`.
This behaviour is consistent even if someone wants to curl an URL with # in it.

Go sanitises the URLs before performing operations on it. This leads to the bug #832. But this sanitisation of URLs go hand in hand with de-sanitisation for displaying purpose. Check [here](https://github.com/gocd/gocd/blob/master/config/config-api/src/com/thoughtworks/go/util/command/HgUrlArgument.java).
The current behaviour is consistent. However, to resolve the aforementioned bug, we would need to fix code to not sanitise the URL until mercurial post commit hook is realised by Go. Not something I would appreciate.

The [pipeline creation API](http://www.go.cd/documentation/user/current/api/configuration_api.html#adding-a-new-pipeline) also uses double hash for creating a pipeline with Hg material (with branch). It would be better if single hash is allowed in all the places.
## Expected Behaviour

Single hash should be allowed in the config.
If someone tries to use a parameter in a wrong way (#PARAM and not #{PARAM}), Go neither complains nor resolves such texts. It should be the user's responsibility to specify the parameters with the correct semantics.
### Step I

The current behaviour to sanitise the URLs with two hashes '##' to a single hash '#' before doing any operation continues, so that the existing users don't face any problem. The change is to make Go a little more liberal in this context.
### Step II

Perform config and DB migration to move all double hashes (existing ones) to single hash. The code to sanitise URLs can then be thrown off.

**Go Version:** 14.4.0 and previous

**Comment by nikita-leonov** [comment]
There is another relevant example. We are using regexp in commands, and since single # is not allowed and require escaping whole process of writing, reading and understanding regexp is not really clear as they become not pure regexps.

**Comment by mdaliejaz** [comment]
This would resolve issue #817 as well.

**Comment by zakjan** [comment]
Any progress? It prevents writing Shell scripts as reported in https://github.com/srinivasupadhya/script-executor-task/issues/7

**Comment by hanej** [comment]
We're affected by this too

**Comment by zabil** [comment]
@hanej which version go are you using?

**Comment by hanej** [comment]
15.2

**Comment by zabil** [comment]
The pull request implementing this hasn't been merged. 

Have you tried escaping using a double hash? Will help if you provide an example of the command you are trying to execute.

**Comment by hanej** [comment]
I haven't tried that yet.  I wanted to comment out a line.
