### ISSUE TITLE
Changes to global Plugin Material Config and Package Config does not refelect on pipeline materials

### ISSUE THREAD

**Issue by maheshp** [gocd/gocd#8542]
##### Issue Type

- Bug Report

##### Summary

Plugin Materials and Package Materials are defined globally and referred in a pipeline. The in-memory PipelineConfig object has a copy of these global materials. Any updates to the configuration of the global materials does not reflect in the PipelineConfig materials. Hence, incorrect values are passed to plugin as part of material update.

**Current Workaround:**   A full config update of the config xml ensures pipeline references are updated.

**Comment by kritika-singh3** [comment]
Tested on `GoCD Version: 20.8.0 (12202-5224cab793f1fc77ed51523d667087b4c29ad7f4)`

Plugins Used: [Maven Poller](https://github.com/1and1/go-maven-poller/releases/download/go-maven-poller-1.5.1/go-maven-poller-plugin.jar)

#### Package material
Steps:

1. Define a package repository using the maven poller with url: `https://jcenter.bintray.com`.
2. Define a package for the repo defined above with values:
     - Group Id: `com.oneandone`
     - Artifact Id: `snmpman`
     - Packaging: `jar`
3. Create a pipeline with the package as the material
4. Wait for MDU to go through and pipeline to be triggered
5. Verify that the Changes dropdown on the dashboard and materials spa modification contains: `"TRACKBACK_URL":"https://oosnmp.net/dist/release"`
6. Update the package with the following values:
     - Group Id: `cd.go.plugin`
     - Artifact Id: `go-plugin-api`
7. Wait for MDU and pipeline to be triggered
8. Verify that the changes on dashboard and modifications on materials spa contains: `"TRACKBACK_URL":"http://gocd.org"`
9. Do some config change not related to pipeline config. E.g. create a new pluggable SCM or a secret config

Expected Results
The pipeline should not be triggered

Actual Results
The pipeline gets triggered with the value which corresponds to the original package defined i.e. `snmpman` one. The changes for the latest instance as well as the modifications on the materials spa will now contain `"TRACKBACK_URL":"https://oosnmp.net/dist/release"`.

The polling for the material will now contain the values from the originally configured package configuration
Moreover the manual trigger of the pipeline will also use the modifications w.r.t. the original package configuration.

**Comment by kritika-singh3** [comment]
Tested on `GoCD Version: 20.8.0 (12202-5224cab793f1fc77ed51523d667087b4c29ad7f4)`

Plugins used: [GoCD Git Path Plugin](https://github.com/TWChennai/gocd-git-path-material-plugin/releases/tag/v2.1.0-78)

#### Plugin material

Create a local repository `/tmp/plugin_test` with a folder `dummy`. Add a file `a.json` inside the folder and commit it as `initial commit`

Steps:

1. Define a pluggable scm using the GoCD Git Path Plugin with values:
     -  url: `/tmp/plugin_test`
     -  path: `dummy`
     - branch: `master`
2. Create a pipeline with the scm as the material
3. Wait for MDU to go through and pipeline to be triggered
4. Verify that the Changes dropdown on the dashboard and materials spa modification contains: `initial commit`
5. Update the pluggable scm with the following values:
      -  url: `http://github.com/gocd/gocd`
      -  path: `api`
6. Wait for MDU and pipeline to be triggered
7. Verify that the changes on dashboard and modifications on materials spa does not contain `initial commit`. At the time of writing this it was: <code>Remove the `branch_support` toggle. This enables new API versions.</code>
8. Do some config change not related to pipeline config. E.g. create a new secret config

Expected Results
The pipeline should not be triggered

Actual Results
The pipeline gets triggered with the value which corresponds to the original scm defined i.e. `/tmp/plugin_test` one. The changes for the latest instance as well as the modifications on the materials spa will now contain `initial commit`.

The manual trigger of the pipeline will also use the modifications w.r.t. the original scm configuration.
**However, the polling for the material will still fetch the modification for the updated scm configuration i.e. the `gocd/gocd` one.**

**Comment by kritika-singh3** [comment]
Verified and fixed via #8610
