### ISSUE TITLE
Enable GoCD server/agent install to Linux ARM / aarch64 system architectures

### ISSUE THREAD

**Issue by richbos** [gocd/gocd#8544]
##### Issue Type

Feature proposal

##### Summary

Enable installation of GoCD server and agent to ARM / aarch64 based systems (i.e to run on a Raspberry Pi)

##### Environment

Raspberry Pi 4 Model B Rev 1.2

###### Basic environment details

* Go Version: `go-server 20.7.0-12097`
* JAVA Version: `OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)`
* OS: `Ubuntu 20 LTS`

##### Steps to Reproduce

1. Followed installation instructions for Debian (Ubuntu) at [https://docs.gocd.org/current/installation/install/server/linux.html]( https://docs.gocd.org/current/installation/install/server/linux.html) (repo/apt method).

##### Expected Results

GoCD server service to start.

##### Actual Results
Installation did not complete and server service unable to start due to the following -

```
Unable to locate any of the following binaries:
  /usr/share/go-server/bin/../wrapper/wrapper-linux-armhf-64
  /usr/share/go-server/bin/../wrapper/wrapper-linux-armhf-32
  /usr/share/go-server/bin/../wrapper/wrapper
```

**Comment by maheshp** [comment]
GoCD installers are bundled with an appropriate JRE. Looks like the [bundled JRE](https://github.com/gocd/gocd/blob/master/buildSrc/src/main/groovy/com/thoughtworks/go/build/AdoptOpenJDKUrlHelper.groovy#L33) is targeted towards `x64` and hence would not work on a ARM based systems.

I was talking to @marques-work, we were wondering if we can download an appropriate JRE and try to bring up the server without using the installer. One of us will try it out and update the issue.

**Comment by marques-work** [comment]
@richbos

I've run GoCD on a Raspberry Pi4 on Raspberry Pi OS (formerly Raspbian) freshly imaged with `2020-08-20-raspios-buster-armhf-lite`.

As such, even though RPi4 is aarch64 with hardware FPU, Raspberry Pi OS is 32-bit. Thus, the JDK I used was built for `arm32`. I'm pretty confident that if you installed Ubuntu for aarch64, it should also work.

Using OpenJDK 11:

``` bash
$ curl -LO https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_arm_linux_hotspot_11.0.8_10.tar.gz
$ tar zxf OpenJDK11U-jdk_arm_linux_hotspot_11.0.8_10.tar.gz
$ export JAVA_HOME="$(pwd)/jdk-11.0.8+10"
$ $JAVA_HOME/bin/java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

GoCD Server:

```bash
$JAVA_HOME/bin/java -server -jar lib/go.jar
```

GoCD Agent:

```bash
$JAVA_HOME/bin/java -server -jar lib/agent-bootstrapper.jar -serverUrl "http://localhost:8153/go"
```

Successfully created and ran a pipeline:

![image](https://user-images.githubusercontent.com/723642/93053146-4081ff80-f61c-11ea-9884-d77cb6eb17a4.png)

/cc @maheshp

**Comment by richbos** [comment]
Hi, yes I am already running Ubuntu 20LTS for aarch64.

--

**Comment by marques-work** [comment]
@richbos cool - so I would go ahead and try the `java` invocations to start the either the server, agent, or both depending on your needs. It _should_ work as GoCD is primarily a Java application. Let us know how it goes!

**Comment by chadlwilson** [comment]
I've closed this for now, as the GoCD server and agent has been validated on linux arm64 as of `23.1.0`. There are a couple of pieces left noted at https://github.com/gocd/gocd/issues/8544#issuecomment-1164506659 which will be addressed separately.
1. The Linux packages declare themselves as `noarch`/`all` but actually seem to include an `x64` JRE now, which is not ideal. Need to decide whether to include the wrapper binaries for `arm64` in the same existing packages (and rely on folks overriding the x64 packaged JRE to an arm64 JRE of their choice installed separately) OR create separate `arm64` packages OR rely on folks using docker on Linux and run a pre-built/validated image.
2. For the docker images, Alpine will be amd64-only for now, due to multiple challenges specific to Alpine and musl libc vs glibc. Will try and raise/track that separately.

**Comment by alanzheng88** [comment]
this might help for anyone visiting this post in the future. i was able to get it to run on ARM architecture by passing: `--platform linux/x86_64` to my docker command

**Comment by chadlwilson** [comment]
@alanzheng88 the Alpine server and agent images are not stable or performant in my experience (or supported) via qemu emulation like this requires. If it works for you, fine, but you're on your own and would not run in production like this :)

Also not necessary with 23.1.0 - use the centos-9 server image or non-alpine agent images are built for arm64, and supported/tested/validated.
