### ISSUE TITLE
Issue with pluggable scm config from config repo

### ISSUE THREAD

**Issue by kritika-singh3** [gocd/gocd#8546]
##### Summary

Starting from GoCD 19.2.0, the pluggable SCM configuration can be defined as part of config repo along with pipelines and environments.

For Pipeline Config API and Environment API, we send a readonly property named `origin` which specifies whether the said entity has been defined in GoCD or is coming from a config-repo. But the pluggable SCM API doesn't contains so.
IMO, the pluggable SCM API should also contain so.

#### UI

 1. Currently the Pluggable SCM SPA has the edit button enabled for all. It should be disable for SCM with `origin`=config-repo
2. The same goes for Materials SPA as well.

**Comment by kritika-singh3** [comment]
Related Bug: Clicking on edit link of pluggable SCM materials takes to the pluggable SCM page where the message shows up `'scm_name' SCM has not been set up.`.

This happens sometimes (not always, randomly) due to the fact that the pluggable SCMs does not contain the SCM defined in the config-repo.

**Comment by maheshp** [comment]
Verified on `GoCD Version: 20.9.0 (12301-4e16e35a91cc4698dd2281f5856d00211d0d7dc8).` Edit/delete button for SCM's from config_repo is disabled with an appropriate message shown on hover.
