### ISSUE TITLE
Build errors in IntelliJ on a clean project

### ISSUE THREAD

**Issue by tomzo** [gocd/gocd#8560]
As a developer,
When I checkout GoCD master, import gradle project to IntelliJ
I get following error when trying to build:
```
Build file '/dojo/work/docker/gocd-server/build.gradle' line: 51

Execution failed for task ':docker:gocd-server:alpine-3.11:docker'.
> You must specify either -PdockerBuildLocalZip or -PdockerbuildServerZipLocation=/path/to/server.zip
```

I'm a bit confused on what's the purpose of `docker:*` tasks in gradle and these properties. What's the expectation of the devs here? Can we default to something sensible rather than fail explicitly?

I know, there was some work recently to make it easy to get the dev environment up and running quickly. As someone who contributes once in a while, it was quite a hassle to get the build running for me.

**Comment by marques-work** [comment]
@tomzo hmm, never seen this one before for just IDEA import. Usually you'll run into that if you're trying to build docker images.

Here's what I do (works every time -- and I blow away and rebuild my dev environment a lot via shell script):

1. Optional: try on a worktree: `git worktree add ../gocd-upstream upstream/master && cd ../gocd-upstream` (where upstream is of course `gocd/gocd`)
2. `git reset --hard && git clean -ffdx` (in case you didn't try step 1 -- you will lose any existing IDEA configs, so maybe save your `.idea/workspace.xml` at least)
3. `./gradlew prepare`
4. Open `<repo-root>/build.gradle` in IDEA and choose `Open as Project`
5. IDEA: Ensure project JDK is set correctly
6. IDEA: Enable annotation processing (required by `lombok`)

☝️ these are generally the same steps in [Setting up your development environment ](https://developer.gocd.org/current/)

If you've done those steps and you still get errors, provide some output?

**Comment by marques-work** [comment]
Hmm, actually I might have read your comment too quickly - I think you said you get this on _building_ the project (as in IDEA > Build > Build Project).

That I haven't tried. Usually running `./gradlew prepare` has sufficed for local dev in IDEA. Once that's done, I'm able to write code, compile, and write/run unit tests against it from IDEA. I also tend to use IDEA's builder instead of Gradle for builds because it's slow (except for integration tests -- those mostly only work when run with Gradle).

When it comes to starting a local GoCD instance, these are the run configs I use:

```xml
    <configuration name="Agent" type="Application" factoryName="Application">
      <option name="MAIN_CLASS_NAME" value="com.thoughtworks.go.agent.DevelopmentAgent" />
      <module name="gocd.development-utility.development-agent.main" />
      <option name="WORKING_DIRECTORY" value="agent" />
      <method v="2">
        <option name="Make" enabled="true" />
      </method>
    </configuration>
    <configuration name="Server" type="Application" factoryName="Application" singleton="true">
      <envs>
        <env name="GEM_PATH" value="" />
        <env name="GEM_HOME" value="" />
      </envs>
      <option name="MAIN_CLASS_NAME" value="com.thoughtworks.go.server.DevelopmentServer" />
      <module name="gocd.development-utility.development-server.main" />
      <option name="VM_PARAMETERS" value="-Xmx1024m -Dcruise.config.dir=dev/config -DpluginLocationMonitor.sleepTimeInSecs=1" />
      <option name="WORKING_DIRECTORY" value="server" />
      <method v="2">
        <option name="Make" enabled="true" />
      </method>
    </configuration>
```
Of course, tweak the `-Xmx` settings to your preference. You'll notice I create a separate untracked directory for `cruise.config.dir` -- that's optional, but I do that so I keep the original `server/config/cruise-config.xml` untouched since it's tracked in `git`.

**Comment by marques-work** [comment]
FWIW, I ran `Build Project` and it worked in my case, but then again I'm using IDEA's builder so it likely skips all that. I imagine if I switched to Gradle it would fail in the same way.

This is what I have set:

![image](https://user-images.githubusercontent.com/723642/93270562-41bf4380-f766-11ea-83b1-ac9296020f8c.png)

**Comment by tomzo** [comment]
Hi @marques-work thanks for the pointers. I will try this out in the evening. I'll update the developer docs if I find out what's causing this.

**Comment by marques-work** [comment]
@tomzo May I close this issue? I assume you've made any needed changes to the docs by now and have figured out the recipe for a working dev environment.

**Comment by tomzo** [comment]
@marques-work I didn't make the doc changes yet. I was busy with other things which should be over this Friday. Let me keep this open until the weekend when I have another look at the docs.

**Comment by marques-work** [comment]
@tomzo if you're still working on it, then no worries and no rush. I thought you may have just forgotten to close the issue and wanted to check with you.
