### ISSUE TITLE
Issues with Stage Overview

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8595]
##### Issue Type

- Bug Report

#### On the VSM page

- [x] Misaligned stage overview (positioned above than expcted) when a pipeline has multiple run instances for the same upstream.

- [ ] (Selecting older stage run) Selecting the older stage instance counter does not change the status of the stage instance from the pipeline-box to the current stage status from overview.

**Comment by kritika-singh3** [comment]
On the VSM page (related to #8576)

 - [ ] misaligned name with `>>` icon
 - [ ] Stage duration is rendered as `Invalid date` for a non-building stage
 - [ ] Poller is turned off by default - but if you change the stage counter - it turned on. The stage overview starts updating the job statuses. But the stage overview status bar remains in the original status.

<img width="539" alt="Screen Shot 2020-09-25 at 10 42 03 AM" src="https://user-images.githubusercontent.com/41165891/94229016-f0f4db00-ff1b-11ea-8161-637d558cf3bd.png">

**Comment by kritika-singh3** [comment]
Tested on `GoCD Version: 20.9.0 (12236-550797553265f0d8918d65356b5a59f846794cdc)` on the dashboard and pipeline activity page. (Related to #8570)

1. Selecting an older failed instance from the stage overview changes the status of stage in the dashboard as well. This behaviour is not present on pipeline activity
![1](https://user-images.githubusercontent.com/41165891/94227954-5eebd300-ff19-11ea-8eb6-1055ed9a03be.gif)

2. Rerunning a stage/job temporary removes the stage counter selection. Present on pipeline activity page as well. 
![2](https://user-images.githubusercontent.com/41165891/94227957-6317f080-ff19-11ea-8fa3-f428dfe5cc27.gif)

3. The stage duration changes after time
![3](https://user-images.githubusercontent.com/41165891/94227958-63b08700-ff19-11ea-80e6-fb52348af70b.gif)

**Comment by GaneshSPatil** [comment]
@maheshp @kritika-singh3 -

1. When an older stage instance is selected on the stage overview, the status of the stage-overview will change, but the status of the dashboard stage will always show the latest stage instance. This behavior is now consistent with other pages as well - dashboard, pipeline activity and vsm.

2. On the VSM page, when one of the pipeline has multiple instance runs, the stage overview will be misaligned, when there are more than pipeline instances for the same pipeline. 
   For upto 3 pipeline instances, the stage overview will be positioned appropriately.
   Fixing this issue requires alot of changes to HTML from vsm pages.

**Comment by kritika-singh3** [comment]
@GaneshSPatil For the second point in [this comment](https://github.com/gocd/gocd/issues/8595#issuecomment-704127948) - it is ok for me.
One query: suppose I do a scroll for the 4th instance - link on the show less link and then click on the latest instance. What will happen in this case: will the stage overview position correctly or it will be misaligned?

**Comment by kritika-singh3** [comment]
Tested on `GoCD Version: 20.9.0 (12264-30bf28b07277798dfc36761dad864e170cee5336)`:
 - The issue related to stage timings is till not fixed (Last point in [this comment](https://github.com/gocd/gocd/issues/8595#issuecomment-698729399)). Rest all the issues mentioned above have been fixed.
 
 - On pipeline activity: on a stage completion, the stage bar is not updated. Rest all information gets updated.
    <img width="1092" alt="Screen Shot 2020-10-08 at 10 55 56 AM" src="https://user-images.githubusercontent.com/41165891/95420823-ce21e800-0959-11eb-87c3-c1b8ef739586.png">
 
 - For VSM page: There is a difference in stage duration as depicted in the pipeline box and on stage overview
    <img width="995" alt="Screen Shot 2020-10-08 at 11 12 08 AM" src="https://user-images.githubusercontent.com/41165891/95420834-d24e0580-0959-11eb-9018-ab8747927acd.png">
 
 - Only visible on dashboard and pipeline activity page: Have a stage with 2 instance. Open the stage overview. Select the first one and click on the stage box on the dashboard again. The stage bar and the job info is of 2nd instance but the stage counter selection still shows 1.
    ![1a](https://user-images.githubusercontent.com/41165891/95420829-d11cd880-0959-11eb-89e7-15e079c3aeca.gif)

**Comment by kritika-singh3** [comment]
The issue regarding stage duration changes while selecting the stage instance counter is fixed via #8656

**Comment by kritika-singh3** [comment]
The stage duration issue has been moved to https://github.com/gocd/gocd/issues/8681
