### ISSUE TITLE
Agent not starting with ubuntu Docker image 20.8.0 due to wrong java version

### ISSUE THREAD

**Issue by AntonSherstiuk2020** [gocd/gocd#8596]
##### Issue Type

- Bug Report

##### Summary

Agent cannot be started using `docker-gocd-agent-ubuntu-18.04` docker image in version 20.8.0 because of unsupported java version 14 that is installed in the image.

##### Environment

GoCD agent started using the Docker image `gocd/gocd-agent-ubuntu-18.04:v20.8.0`

###### Basic environment details

* Go Version: `20.8.0`
* JAVA Version: `14`
* OS: `Ubuntu 18.04.5 LT`

##### Steps to Reproduce

1. Run the agent using docker image

##### Expected Results

agent starts

##### Actual Results

agent fails to start because of unsupported java runtime version 14

##### Possible Fix

https://github.com/gocd/docker-gocd-agent-ubuntu-18.04/pull/3

**Comment by marques-work** [comment]
@AntonSherstiuk2020 can you show me how you are getting this?

I'm not seeing this error when I try: https://github.com/gocd/docker-gocd-agent-ubuntu-18.04/pull/3#issuecomment-700114916

I ran this on my laptop with no such issue:

```bash
docker run -e GO_SERVER_URL=<local GoCD server URL> gocd/gocd-agent-ubuntu-18.04:v20.8.0
```

**Comment by marques-work** [comment]
Closing this; see https://github.com/gocd/docker-gocd-agent-ubuntu-18.04/pull/3#issuecomment-707505469
