### ISSUE TITLE
Add parameter support to pipeline template job elastic profile id

### ISSUE THREAD

**Issue by Vye** [gocd/gocd#8605]
##### Issue Type

- Feature enhancement

##### Summary
Add parameter support to job elastic profile id field. I use templates heavily. dev/tst/prd will share the same pipeline template. While I can define a dev/tst/prd elastic agent profiles (different clusters) only one can be statically configured in the job.

It would be great to be able to set elastic profile id to a parameter like `#{elastic-profile}` and define that parameter on each instance of the pipeline.

![image](https://user-images.githubusercontent.com/361779/94746955-bbdcf400-0332-11eb-9077-7bdc21685593.png)

**Comment by maheshp** [comment]
@Vye `Elastic Profile Id` attribute on jobs already supports parameters. Below is a sample example,

```xml
<pipeline name="up42" template="sample_template">
      <params>
        <param name="elastic_profile">profile1</param>
      </params>
      <materials>
        <git url="test-repo" />
      </materials>
    </pipeline>
  </pipelines>
  <templates>
    <pipeline name="sample_template">
      <stage name="up42_stage">
        <jobs>
          <job name="up42_job" elasticProfileId="#{elastic_profile}">
            <tasks>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </templates>
```

Can you please check. I will close this issue for now. If you face any issues please feel free to re-open the issue.

**Comment by Vye** [comment]
You're right. Didn't like a parameter with a dash in it. Thanks!
