### ISSUE TITLE
Elastic Agent Plugin always migrates the old plugin settings

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/gocd#8643]
##### Issue Type

- Bug Report

##### Summary

GoCD added support for elastic agents extension v5 to allow GoCD server to connect to multiple clusters to bring up elastic agents. To do so, GoCD moved away from a singular config entity plugin settings to a new concept called cluster profiles, which allowed users defining multiple cluster configurations.

As part of this new extension, all the older plugin settings were migrated to the cluster profile. Though, even after migration, the plugin settings were not deleted from the GoCD's database.

So, if a user deletes the newly migrated cluster profile after its use, GoCD will migrate the plugin settings again to the cluster profile.

###### Basic environment details

* Go Version: `20.8.0`

##### Steps to Reproduce

1. Start GoCD Server v20.8.0
2. Install docker elastic agent plugin (**docker-elastic-agents-2.1.0-174.jar**)
3. Configure plugin settings. 
4. Now, upgrade the docker elastic agent plugin to version **docker-elastic-agents-3.1.0-248.jar**
5. Verify a new cluster profile is created with the older plugin settings.
6. Now delete the newly migrated cluster profile.
7. Restart GoCD Server

##### Expected Results
The plugin settings are again migrated as a cluster profile

##### Actual Results
The plugin settings should be migrated only once to the cluster profile. Upon a successful migration of the plugin settings to cluster profile, GoCD should delete the plugin settings

**Comment by maheshp** [comment]
Verified on `GoCD Version: 20.9.0 (12292-25ed9fb08c2f5de81a8c4ddacc9c77bba732109f)`
