### ISSUE TITLE
git version mismatch between error message and actual check

### ISSUE THREAD

**Issue by giani** [gocd/gocd#8650]
##### Bug Report

https://github.com/gocd/gocd/blob/master/domain/src/main/java/com/thoughtworks/go/config/materials/git/GitMaterial.java#L59 states min version is 1.6, but when you check at https://github.com/gocd/gocd/blob/master/domain/src/main/java/com/thoughtworks/go/domain/materials/git/GitVersion.java#L31 you are looking for 1.9. 

I spent about an hour trying to debug this with 1.8, before I looked into the source :-). A fix pretty please!

**Comment by maheshp** [comment]
Fixed in https://github.com/gocd/gocd/pull/8657
