### ISSUE TITLE
notification end-point

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#867]
- [Discussion thread](https://groups.google.com/d/topic/go-cd/yziHSb1MGuw/discussion)
- [Dev Docs](http://www.go.cd/documentation/developer/writing_go_plugins/notification/notification_plugin_overview.html)
- [User Docs](http://www.go.cd/documentation/user/15.1.0/extension_points/notification_extension.html)
- sample plugin - [email notifier](https://github.com/srinivasupadhya/email-notifier)

**Comment by arikagoyal** [comment]
Bug fixes done. Closing the story
