### ISSUE TITLE
Minor Pipeline Comparison UI regressions introduced in 20.3.0

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd#8685]
##### Issue Type

- Bug Report

##### Summary

There are a couple of regressions I've noticed since upgrading from `20.1.0` to `20.5.0`. (Apologies if any of these have been fixed by 20.8.0 - I looked through the changelogs and couldn't see them referenced)

###### Basic environment details

* Go Version: `20.5.0`
* JAVA Version: `13.0.2`
* OS: `Linux 4.14.198-152.320.amzn2.x86_64`
* Browser vendor and version (if relevant): `Firefox 81.0.2`

##### Expected Results

GoCD Compare UI should have similar user experience to version prior to the refactoring.

1. "triggered by" user should be accurate
1. tracking tool links should be hyperlinked
1. ideally text wrapping shouldn't cause columns to be misaligned across multiple materials

##### Actual Results

1. **Correctness**: The "triggered by" user is displaying as `anonymous` rather than the real user when a pipeline was manually triggered. I believe [the screenshot on the release notes](https://www.gocd.org/releases/#20-3-0) even shows this issue :-) Both of the examples below were triggered by real users (still in the database). The username is displaying correctly on both the pipeline dashboard and stage view.
![image](https://user-images.githubusercontent.com/29788154/97087209-edf42400-165a-11eb-9ce3-102a2f5fe1ea.png)

2. **UX: Tracking Tool** links are no longer hyperlinked. I think they used to be? (is still working correctly on the regular "changes" dashboard pop-ups and the stage details overview).

3. **UX**: (minor comment) For _SCM/git material_ differences, the font for the main text in rows (modified by, comments etc) _seems_ a bit bigger now, and as a consequence, table columns seem to wrap more often when in a half-screen type of view (especially with users committing under git longer email addresses which can't wrap). When the table columns are forced to wrap; it seems to lead to columns in tables from different materials being horizontally aligned differently, which is a bit ugly to look through. 

Additionally, for the _pipeline materials_ when there are multiple upstream pipeline materials the column alignment is seemingly random or driven by how long the pipeline revision name is (regardless of need for wrapping,); meaning every upstream pipeline material seems to align randomly which is really difficult to read/look through. I'd expect the "Instance" and "Completed At" columns to align with each other across materials preferably.

##### Possible Fix
Regarding the #3 (wrapping), I wonder if something can be done to preserve horizontal screen real estate here to prioritise the comment; e.g 
* by using a slightly smaller font (if indeed it was made changed to be bigger and I am not imagining things?)
* by displaying shorter revision hashes (or deliberately using a smaller font for these, since they cannot wrap)
* by doing something to improve the way the columns align/wrap

**Comment by kritika-singh3** [comment]
@chadlwilson Thanks for creating the issue.
W.r.t. point 3, it will be highly appreciated if you can provide a screenshot (do hide the secrets) regarding misalignment in case of SCM/git materials. I understand the dependency materials misalignment but could not get the former one.

P.S. The font size was made consistent with the one used on other pages in the GoCD UI.

**Comment by chadlwilson** [comment]
Yeah, fair enough re: screenshots. I'll try and do so later 👍

**Comment by chadlwilson** [comment]
Here's an example.

![image](https://user-images.githubusercontent.com/29788154/97466844-869de300-197e-11eb-8ea4-618ce7ff9df5.png)

**Comment by kritika-singh3** [comment]
@chadlwilson Thanks fr the screenshot. I'll take a look.

**Comment by maheshp** [comment]
Fixed by https://github.com/gocd/gocd/pull/8691, https://github.com/gocd/gocd/pull/8698 and https://github.com/gocd/gocd/pull/8712

**Comment by chadlwilson** [comment]
Just upgraded to `20.9.0` - looking much better @kritika-singh3 and @maheshp, thanks!
