### ISSUE TITLE
Text highlighting is lost in build log when extra logs are appended

### ISSUE THREAD

**Issue by matt-richardson** [gocd/gocd#869]
While a build is running, if you highlight some text (for example if you want to show someone something) then the highlight is lost whenever new text is appended to the log.

This appears to be because the entire text is being replaced, rather than just the new text being appended.

I presume this (text replacement) would have performance issues as well, as it would probably force a re-layout of the page, but this is pure speculation.

**Comment by arvindsv** [comment]
Related to #870 as well.
