### ISSUE TITLE
GoCD behind proxy server - what are the proxy settings required by plugin to connect to external URL

### ISSUE THREAD

**Issue by tpidor** [gocd/gocd#8699]
##### Issue Type

- Bug Report

##### Summary

Our GoCD server is behind proxy - does external plugin can connect to external URL over proxy and what is the proxy settings needed? We did all config by

adding these into start-server.bat,
set GO_SERVER_HTTP_PROXY=http://user:pwd@proxyurl:port
set GO_SERVER_HTTPS_PROXY=http://user:pwd@proxyurl:port
set HTTP_PROXY=http://user:pwd@proxyurl:port
set HTTPS_PROXY=http://user:pwd@proxyurl:port

adding these into wrapper-properties.conf
wrapper.java.additional.1=-Dhttp.proxySet=true
wrapper.java.additional.2=-Dhttp.proxyHost=proxyurl
wrapper.java.additional.3=-Dhttp.proxyPort=proxyport
wrapper.java.additional.4=-Dhttp.proxyUser=proxyuser
wrapper.java.additional.5=-Dhttp.proxyPassword=proxypwd
wrapper.java.additional.6=-Dhttps.proxySet=true
wrapper.java.additional.7=-Dhttps.proxyHost=proxyurl
wrapper.java.additional.8=-Dhttps.proxyPort=proxyport
wrapper.java.additional.9=-Dhttps.proxyUser=proxyuser
wrapper.java.additional.10=-Dhttps.proxyPassword=proxypwd

adding proxy properties into server.cmd,
"%JAVA_CMD%" %OPTION% %YOURKIT% -Xms%SERVER_MEM% -Xmx%SERVER_MAX_MEM% -XX:MaxMetaspaceSize=%SERVER_MAX_PERM_GEN% %JVM_DEBUG% %GC_LOG% %GO_SERVER_SYSTEM_PROPERTIES% -Duser.language=en -DJAVA_SYS_MON_TEMP_DIR="%SERVER_DIR%\tmp" -Dorg.eclipse.jetty.server.Request.maxFormContentSize=30000000 -Djruby.rack.request.size.threshold.bytes=30000000 -Duser.country=US -Dcruise.config.dir="%SERVER_DIR%\config" -Dcruise.config.file="%SERVER_DIR%\config\cruise-config.xml" -Dcruise.server.port=%GO_SERVER_PORT% -Dcruise.server.ssl.port=%GO_SERVER_SSL_PORT% -Dhttp.proxySet=true -Dhttp.proxyHost=proxyurl -Dhttp.proxyPort=proxyport -Dhttp.proxyUser=proxyuser -Dhttp.proxyPassword=proxypwd -Dhttps.proxySet=true -Dhttps.proxyHost=proxyurl -Dhttps.proxyPort=proxyport -Dhttps.proxyUser=proxyuser -Dhttps.proxyPassword=proxypwd -jar "%SERVER_DIR%\go.jar"

but nothing worked. The plugin or GoCD server is still unable to connect to external site. I guess the other question, does GoCD server works behind proxy and connect to SaaS URLs such as git repos or package repos?

Please refer to the other ticket I posted in https://github.com/gocd-contrib/go-nuget-poller-plugin-2.0/issues/45

###### Basic environment details

* Go Version: 18.5
* JAVA Version: 1.8
* OS: Win and Linux
* Browser vendor and version (if relevant): Latest Chrome browser

##### Steps to Reproduce

1. Install plugin from https://github.com/gocd-contrib/go-nuget-poller-plugin-2.0
2. Restart GoCD Server that is behind proxy
3. Go to package repositories and add entry
4. Connect to Artifactory SaaS NuGet repo from jfrog.io JFrog Platform.
5. See below for the log messages.

##### Expected Results
GoCD external plugin should be able to connect to SaaS URLs such as Artifactory NuGet repo from JFrog Platform domain.jfrog.io.

For example in plugin-nuget.log, this is what we have when connecting to on-prem Artifactory,
2020-10-29 19:11:54,859 INFO  [qtp1007251739-29] NugetController:73 - Request name check-repository-connection
2020-10-29 19:11:54,861 INFO  [qtp1007251739-29] NugetController:73 - Request body {"repository-configuration":{"REPO_URL":{"value":"https://artifactoryurl/artifactory/api/nuget/nugetrepo"},"USERNAME":{"value":"user"},"PASSWORD":{"value":"pwd"}}}
2020-10-29 19:11:54,862 INFO  [qtp1007251739-29] NugetController:73 - Request body {}
2020-10-29 19:11:54,864 INFO  [qtp1007251739-29] NugetController:73 - Request body {}
2020-10-29 19:11:55,364 INFO  [qtp1007251739-29] NugetController:73 - Response body {"messages":["Successfully connected to repository url provided"],"status":"success"}

##### Actual Results

For example in plugin-nuget.log, currently this is what we're having when connecting to Artifactory SaaS URL,
2020-10-29 19:11:32,008 INFO  [qtp1007251739-18] NugetController:73 - Request name check-repository-connection
2020-10-29 19:11:32,009 INFO  [qtp1007251739-18] NugetController:73 - Request body {"repository-configuration":{"REPO_URL":{"value":"https://jfrogurl/artifactory/api/nuget/nugetrepo"},"USERNAME":{"value":"user"},"PASSWORD":{"value":"pwd"}}}
2020-10-29 19:11:32,011 INFO  [qtp1007251739-18] NugetController:73 - Request body {}
2020-10-29 19:11:32,013 INFO  [qtp1007251739-18] NugetController:73 - Request body {}
2020-10-29 19:11:32,049 INFO  [qtp1007251739-18] NugetController:73 - Response body {"messages":["Unsuccessful Connection"],"status":"failure"}

##### Possible Fix
seeking help

##### Log snippets
Please see expected and actual results section

**Comment by maheshp** [comment]
GoCD does nothing special when connecting to an external server(e.g in case of material update) which is behind a proxy. You will have to ensure that the external URL is accessible from the server which is running your GoCD server and agent. Also, GoCD does not support the configurations provided by you in wrapper-properties.

**Comment by maheshp** [comment]
Adding to my previous comment, the JVM properties provided by you are not consumed by the GoCD server, the GoCD Agent can be configured with these properties - https://docs.gocd.org/current/installation/configure-agent-proxy.html to connect to a GoCD server through a proxy. 

However, in this case the Nuget plugin needs to support these properties to connect to URLs behind a proxy.
