### ISSUE TITLE
Unexplained performance degradation/lock-ups after 20.5.0 to 20.8.0 upgrade

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd#8730]
##### Issue Type

- Bug Report

##### Summary

Apologies for the open-ended question, here, but we are running out of ideas. Since the upgrade form `20.5.0` to `20.8.0` we are suffering from a big decrease in usable performance/reliability, and we don't really understand what has caused it.

What we observe
- periods of time where everything locks up, e.g web requests won't return within, say 60 seconds. UI basically doesn't load/gets stuck. Our reverse proxy sometimes ending up returning 502s/504s.
- Eventually it tends to fix itself - but sometimes Kubernetes is killing the pod (failing liveness check perhaps?)
- when analyzing thread dumps where everything has seized up, it looks like 
  - there are `453` threads, `288` were Jetty threads in one example dump. The rest are normal GoCD/JVM standard threads from threadpools with default configuration.
  - `83` idle TIMED_WAITING Jetty threads
  - `47` BLOCKED trying to lock the same session in `InvalidateAuthenticationOnSecurityConfigChangeFilter`
  - `158` WAITING `waiting on condition` in what **looks like** they trying to get a DB connection. However I am unsure if I am interpreting the stack trace correctly and how to distinguish those working on a query vs. waiting for a connection
  - noticed that `68` of these are in `PipelineHistoryController.list` for whatever reason (?)
- material updates were very slow at this point and were timing out/logging that they were taking minutes. From the thread dumps, it looks like these lock a DB connection while waiting for the material to update (e.g executing git commands). Is that normal? Could that cause such cascading blocking?

We tried increasing `db.maxActive` DB connections 32 -> 64, but we have never had to do this before, and although anecdotally this improved things, that might just be luck. It doesn't seem to have addressed the root of the problem.

Looking for any suggestions on how to debug this further as it's hard to see where the real root cause is here. We've never had any such major issues on earlier GoCD versions nor changed anything significant we can think of in our environment other than upgrading GoCD and introducing the mandatory reverse proxy for TLS termination on `20.6.0`.

###### Basic environment details

* Go Version: `20.8.0`
* JAVA Version: `14.0.2`
* OS: `Linux 4.14.198-152.320.amzn2.x86_64`

###### Additional Environment Details

```json
  "Config Statistics": {
    "Valid Config": {
      "Number of pipelines": 197,
      "Number of environments": 31,
      "Number of agents": 34,
      "Number of unique materials": 326,
      "Number of schedulable materials": 329
    },
```

- Using embedded H2DB.
- Configured with [2GB,4GB] heap, 6GB container memory limit
- Configured with min 2, max 4 cores CPU

Deployed on Kubernetes via the Helm Chart with a basic raw TLS-terminating nginx ingress controller in front of it.

##### Steps to Reproduce

Really not sure as we are not sure of the root cause, other than seeing a possible correlation with very slow material updates due to the external source control repo we depend on. We have experienced slowness in the external repo before, however, and not seen a correlation with an effect on GoCD itself becoming inaccessible on earlier versions.

###### Additional Information

The 68 Jetty threads in `PipelineHistoryController.list` look identical like the below; this is roughly typical of the stack traces when it "looks like" the threads are stuck waiting for a DB connection.
```
jvm 1    | "qtp247343347-973304" #973304 prio=5 os_prio=0 cpu=8177.29ms elapsed=10681.97s tid=0x00007f51a1110000 nid=0x3dcb waiting on condition  [0x00007f51425ef000]
jvm 1    |    java.lang.Thread.State: WAITING (parking)
jvm 1    | 	at jdk.internal.misc.Unsafe.park(java.base@14.0.2/Native Method)
jvm 1    | 	- parking to wait for  <0x00000007052b7110> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
jvm 1    | 	at java.util.concurrent.locks.LockSupport.park(java.base@14.0.2/Unknown Source)
jvm 1    | 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@14.0.2/Unknown Source)
jvm 1    | 	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@14.0.2/Unknown Source)
jvm 1    | 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@14.0.2/Unknown Source)
jvm 1    | 	at org.apache.commons.pool2.impl.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:594)
jvm 1    | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:437)
jvm 1    | 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:354)
jvm 1    | 	at org.apache.commons.dbcp2.PoolingDataSource.getConnection(PoolingDataSource.java:134)
jvm 1    | 	at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
jvm 1    | 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:111)
jvm 1    | 	at org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler.invoke(TransactionAwareDataSourceProxy.java:229)
jvm 1    | 	at com.sun.proxy.$Proxy34.getAutoCommit(Unknown Source)
jvm 1    | 	at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:83)
jvm 1    | 	at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
jvm 1    | 	at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:338)
jvm 1    | 	at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:84)
jvm 1    | 	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
jvm 1    | 	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:326)
jvm 1    | 	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
jvm 1    | 	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
jvm 1    | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
jvm 1    | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
jvm 1    | 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
jvm 1    | 	at jdk.internal.reflect.GeneratedMethodAccessor412.invoke(Unknown Source)
jvm 1    | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@14.0.2/Unknown Source)
jvm 1    | 	at java.lang.reflect.Method.invoke(java.base@14.0.2/Unknown Source)
jvm 1    | 	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
jvm 1    | 	at com.sun.proxy.$Proxy37.selectOne(Unknown Source)
jvm 1    | 	at org.mybatis.spring.SqlSessionTemplate.selectOne(SqlSessionTemplate.java:166)
jvm 1    | 	at com.thoughtworks.go.server.transaction.SqlMapClientTemplate.queryForObject(SqlMapClientTemplate.java:34)
jvm 1    | 	at com.thoughtworks.go.server.dao.PipelineSqlMapDao.findPipelineByNameAndCounter(PipelineSqlMapDao.java:217)
jvm 1    | 	at com.thoughtworks.go.server.service.PipelineService.findPipelineByNameAndCounter(PipelineService.java:125)
jvm 1    | 	at com.thoughtworks.go.server.service.PipelineService.fullPipelineByCounter(PipelineService.java:129)
jvm 1    | 	at com.thoughtworks.go.server.service.StageManualTriggerChecker.check(StageManualTriggerChecker.java:42)
jvm 1    | 	at com.thoughtworks.go.server.service.CompositeChecker.check(CompositeChecker.java:31)
jvm 1    | 	at com.thoughtworks.go.server.service.SchedulingCheckerService.canScheduleStage(SchedulingCheckerService.java:161)
jvm 1    | 	at com.thoughtworks.go.server.service.ScheduleService.canRun(ScheduleService.java:534)
jvm 1    | 	at com.thoughtworks.go.server.service.PipelineHistoryService.populateCanRunStatus(PipelineHistoryService.java:249)
jvm 1    | 	at com.thoughtworks.go.server.service.PipelineHistoryService.populatePipelineInstanceModel(PipelineHistoryService.java:218)
jvm 1    | 	at com.thoughtworks.go.server.service.PipelineHistoryService.load(PipelineHistoryService.java:132)
jvm 1    | 	at com.thoughtworks.go.server.controller.PipelineHistoryController.list(PipelineHistoryController.java:92)
...SNIP
```

**Comment by dziemba** [comment]
We have noticed a similar issue with our GoCD instance after the upgrade. We then migrated from H2 to Postgresql and the issues disappeared. So while I don't know the root cause, I think it is indeed related to the new H2 setup.

**Comment by maheshp** [comment]
For those who have missed it, a note about H2 is added in the GoCD [upgrade docs](https://docs.gocd.org/current/installation/upgrade_to_gocd_20.5.0.html)
> The H2 version used in GoCD 20.5.0 has moved to use MVStore as the default storage subsystem. The [Current State](https://www.h2database.com/html/mvstore.html#current_state) of MVStore (as of June 2020) as per H2 documentation is marked as experimental. While using the default H2 is fine to get started or experimenting, we would recommend using PostgreSQL for production instances of GoCD.

**Comment by chadlwilson** [comment]
For the benefit of the community, according to offline conversation with @maheshp it seems there is a likely issue with the default # of `maxIdle` and `maxActive` DB connections when running in H2 post the `20.5.0` DB migration; and it is running with `8` instead of the previous default of `32` concurrent threads.

Given there are 10 material update threads and these seem to hold a connection while they are updating, it would seem that any slowness in source control could consume all of the DB threads; which high load periods in other use cases may also do. @dziemba - perhaps this explains what you observed also?

Workaround suggested until fix in #8777 is available with `20.10.0` is to do a file-based `db.properties` override in the appropriate config dir. (System property override I mentioned above is not working due to the same root issue)

i.e the below with the default built-in config and H2DB location.
```
db.url=jdbc:h2:./db/h2db/cruise;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;CACHE_SIZE=131072;TRACE_MAX_FILE_SIZE=16;TRACE_LEVEL_FILE=1
db.user=sa
db.maxActive=32
db.maxIdle=32
```

Seems better anecdotally (it was often unusably slow after restart when re-cloning all the materials defined by config repo and didn't seem to be after this), but will see how it goes over the next couple of days.

**Comment by arvindsv** [comment]
Remember that the `db.url` property should be as @chadlwilson wrote. It should be:

```
jdbc:h2:./db/h2db/cruise;DB_CLOSE...
```

and NOT:

```
jdbc:h2:./db/h2db/cruise.mv.db;DB_CLOSE
```

**Comment by arvindsv** [comment]
Also, general advice: It's always good to take a backup before you try things. :)

**Comment by chadlwilson** [comment]
Thanks @arvindsv - Mahesh did communicate this to me; and I did do so ;-)

**Comment by chadlwilson** [comment]
Reverted the `db.properties` override and working fine with `20.10.0` defaults, so closing this now 👍
