### ISSUE TITLE
Stripping space characters from guid.txt when loading

### ISSUE THREAD

**Issue by gaqzi** [gocd/gocd#874]
I'm working on a project where we have multiple environments coming together on one Go server. These environments and their agents needs to be configured in a very specific way, so to help with that we generate our own UUIDs based of the agent instance number and hostname. There's currently around 150 go agents and more are planned.

One thing we noticed is that when we save tour template file out editors would automatically add a newline. Which then gets transferred to Go and saved in the XML as an escaped newline character. This caused Go to start having issues dealing with the agents because the UUIDs were invalid.

Looking at the source it seems like guid.txt is taken and directly dumped into a variable without being cleaned. https://github.com/gocd/gocd/blob/7958ac8b613031660ee00f0591af792c06c0f74c/common/src/com/thoughtworks/go/config/GuidService.java

We have worked around this by stripping away newlines from our guid.txt after creating it, but it would be nicer for this to cleaned at load time.

**Comment by gaqzi** [comment]
Example of the XML config when there's a newline in guid.txt:

```diff
diff --git a/cruise-config.xml b/cruise-config.xml
index 6b59a45..5de1def 100644
--- a/cruise-config.xml
+++ b/cruise-config.xml
@@ -2044,6 +2044,7 @@
         <physical uuid="12f348ae-7381-4200-8e99-b95f319b63fa" />
         <physical uuid="61360a03-3f48-4ea8-8234-33f90ecdd1de" />
         <physical uuid="20ddf620-9845-5230-8aee-ef5f7e1bcbfe&#xA;" />
+        <physical uuid="16453a9a-9b36-53f6-8af5-4f52b3268223&#xA;" />
```

**Comment by zabil** [comment]
Will close this issue once we have some testing done.

**Comment by arikagoyal** [comment]
The current fix ensures that any whitespace that gets introduced in guid in future does not cause issues with Go's cruise-config and agent registration in any way. But what if someone has this issue in an older build and then they upgrade to 15.2. Should we take care of migration as well ?

**Comment by ketan** [comment]
> But what if someone has this issue in an older build and then they upgrade to 15.2. Should we take care of migration as well?

@arikagoyal - I don't think it's particularly worth the effort here.

**Comment by arikagoyal** [comment]
Ok i am fine with this not being done (i don't think it's a very high priority thing issue). If anyone feels otherwise we can create a separate issue and fix it as part of that. Closing this one.
