### ISSUE TITLE
Update Agent Profile API doesn't work as documented

### ISSUE THREAD

**Issue by njsaunders** [gocd/gocd#8740]
##### Issue Type

- Bug Report

##### Summary

The example given in the documentation
https://api.gocd.org/current/#update-an-elastic-agent-profile

Implies that you can "patch" an agent, but when I try to make a call to update an agent by setting RunAsSpotInstance to false I get: 

```
response.text
Out[63]: '{\n  "message" : "Validations failed for agentProfile \'ecs-agent-pyspark-vpn-data-dev\'. Error(s): [CPU must not be blank., Image must not be blank., ReservedMemory must not be blank., MaxMemory must not be blank.]. Please correct and resubmit.",\n  "data" : {\n    "id" : "ecs-agent-pyspark-vpn-data-dev",\n    "cluster_profile_id" : "ff78f9fd-955f-48f4-a0da-8ceeff85c1ac",\n    "properties" : [ {\n      "key" : "RunAsSpotInstance",\n      "value" : "true"\n    }, {\n      "key" : "CPU",\n      "errors" : {\n        "CPU" : [ "CPU must not be blank." ]\n      }\n    }, {\n      "key" : "Image",\n      "errors" : {\n        "Image" : [ "Image must not be blank." ]\n      }\n    }, {\n      "key" : "ReservedMemory",\n      "errors" : {\n        "ReservedMemory" : [ "ReservedMemory must not be blank." ]\n      }\n    }, {\n      "key" : "MaxMemory",\n      "errors" : {\n        "MaxMemory" : [ "MaxMemory must not be blank." ]\n      }\n    } ],\n    "errors" : { }\n  }\n}'
```

###### Basic environment details

* Go Version: `20.8`

**Comment by maheshp** [comment]
@njsaunders you cannot PATCH the Agent Profile using the [Update elastic agent profile API](https://api.gocd.org/current/#update-an-elastic-agent-profile). It's an API to update the entire Agent Profile and hence your payload should include all the required attributes.

**Comment by njsaunders** [comment]
Ok, but that's not what the example in the documentation shows, which shows two properties being updated with a PUT:

```
$ curl 'https://ci.example.com/go/api/elastic/profiles/unit-tests' \
      -u 'username:password' \
      -H 'Accept: application/vnd.go.cd.v2+json' \
      -H 'Content-Type: application/json' \
      -H 'If-Match: "cbc5f2d5b9c13a2cc1b1efb3d8a6155d"' \
      -X PUT \
      -d '{
        "cluster_profile_id": "prod-cluster",
        "properties": [
          {
            "key": "Image",
            "value": "gocdcontrib/gocd-dev-build:1.0.0"
          },
          {
            "key": "Environment",
            "value": "JAVA_HOME=/opt/java\nMAKE_OPTS=-j8"
          }
        ]
      }'
```

This doesn't work.

Context: I'm trying to write a script to toggle teh "RunAsSpotInstance" value for all profiles. There are lots of values that aren't configured - How should these be specified in the PUT call?

Basically I think the example needs updating as it doesn't work as written, and should include what to pass for values that aren't specified.

**Comment by arvindsv** [comment]
Isn't the properties of a cluster profile completely decided by the plugin that the cluster profile depends on? In that sense, the documentation _might_ be assuming a plugin with those properties. A saving grace is that it is consistent with the GET and POST examples shown above the PUT example.

A generic way I'd handle PUTs, especially due to the `If-Match` requirement is to do this:

1. Do a `GET`. Capture response body and the `If-Match` header.
2. Transform / update the response body.
3. Do a `PUT` using the new body with the `If-Match` value.

That's the only safe way to do a `PUT` in general, since it's not a `PATCH`.

**Comment by maheshp** [comment]
Since the API works as expected, closing the issue.
