### ISSUE TITLE
Pipeline Activiy column headings not aligned with progress "blobs"

### ISSUE THREAD

**Issue by Kolossi** [gocd/gocd#8741]
##### Issue Type

- Bug Report

##### Summary

After update from 20.4.0 to 20.8.0, noticed that pipeline history page headings are not aligned with stage "blobs".  Can't be sure it didn't exist on 20.4 before upgrade, but don't think so (colleagues have commented on it since upgrade).

##### Environment

not sure how much of .../go/api/support is wanted - it's huge!

###### Basic environment details

* Go Version: 20.8.0
* JAVA Version: 14.0.2
* OS: Linux 5.4.0-52-generic
* Browser vendor and version (if relevant): occurs in Microsoft Edge 44.18362.449.0 and Google Chrome Version 86.0.4240.183 (Official Build) (64-bit), both on Windows 10.

##### Steps to Reproduce

1. View "history" on any pipeline on our gocd install (not publicly accessible, sorry!)

##### Expected Results
Column headings should align with progress "blobs"

##### Actual Results
Column headings and blobs are misaligned as per screenshot

##### Possible Fix
Nothing to offer here.

##### Log snippets

Checked Chrome dev console, but no errors given.

##### Code snippets/Screenshots
![gocd_history_alignment](https://user-images.githubusercontent.com/5367728/98391689-dfd8d700-204e-11eb-8d7a-b3dafa57f89f.png)

##### Any other info

I tried to search for an existing issue using "history", "ui", "columns" or "alignment", but didn't find anything.

In trying to diagnose the issue, cleared browser history, Ctrl-F5, and exited all browser tabs.  Issue still occurs.

**Comment by chadlwilson** [comment]
Yeah, I can see this too in Firefox. Seems the header has `.index__stage-name___.*` with `margin-right: 50px` which doesn't seem to correspond to anything in the individual stage progressions.

**Comment by maheshp** [comment]
Fixed as part of https://github.com/gocd/gocd/pull/8782 & https://github.com/gocd/gocd/pull/8761
