### ISSUE TITLE
Dockerized agent fails to connect to server

### ISSUE THREAD

**Issue by readmodifywrite** [gocd/gocd#8759]
##### Issue Type
Bug report

or a documentation issue?

##### Summary

Dockerized gocd agent fails to connect to server.  The server itself runs.

It looks like perhaps the agent is expecting an SSL connection.  However the docs do not provide instructions to set this up and the docker command itself uses an http endpoint, not https.  Additionally the server works fine without HTTPS - in fact, HTTPS is not available when run with the command listed in the docs.

##### Environment

Linux Mint 20.04 (Ubuntu Focal)
Docker version 19.03.13, build 4484c46d9d

##### Steps to Reproduce

Run dockerized server:
docker run --name=gocd_server -d --restart=always -v /opt/gocd:/godata -p 8153:8153 gocd/gocd-server:v20.9.0
(assumes correct permissions configured on /opt/gocd for user 1000)
This step works fine.

Run dockerized agent:
docker run --name=gocd_agent -d --restart=always -e GO_SERVER_URL=http://localhost:8153/go gocd/gocd-agent-ubuntu-18.04:v20.9.0

This will fail to connect to the server.

##### Expected Results

GoCD agent should connect to server.

##### Actual Results

Console logs indicate connection refused.

The server port 8153 is accessible both externally via hostname (confirmed with browser) and internally via localhost (confirmed via telnet).

##### Log snippets
Running go-agent...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Standard Edition 64-bit 3.5.41
wrapper  |   Copyright (C) 1999-2019 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |   Licensed to ThoughtWorks for GoCD Agent
wrapper  |
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | [Tue Nov 10 21:24:56 GMT 2020] Starting process:
jvm 1    | [Tue Nov 10 21:24:56 GMT 2020]   Working directory    : /go
jvm 1    | [Tue Nov 10 21:24:56 GMT 2020]   Application arguments: [-serverUrl, http://localhost:8153/go]
jvm 1    | [Tue Nov 10 21:24:56 GMT 2020]            GoCD Version: 20.9.0-12335
jvm 1    | [Tue Nov 10 21:24:56 GMT 2020]            Java Version: 15
jvm 1    | [Tue Nov 10 21:24:56 GMT 2020]        Operating System: Linux(5.4.0-52-generic)
jvm 1    | Could not find file `config/agent-bootstrapper-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:onejar:lib/agent-bootstrapper-20.9.0-12335-classes.jar!/config/agent-bootstrapper-logback.xml'.
jvm 1    | 2020-11-10 21:24:56,456 INFO  [WrapperJarAppMain] DefaultAgentLauncherCreatorImpl:67 - Attempting to load com.thoughtworks.go.agent.launcher.AgentLauncherImpl as specified by manifest key Go-Agent-Launcher-Class
jvm 1    | 2020-11-10 21:24:56,480 INFO  [WrapperJarAppMain] ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLauncher using java.net.URLClassLoader
jvm 1    | SLF4J: Class path contains multiple SLF4J bindings.
jvm 1    | SLF4J: Found binding in [jar:onejar:lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: Found binding in [jar:file:/go/data/deps-ca7fb8b01db95630-agent-launcher.jar/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
jvm 1    | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
jvm 1    | SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
jvm 1    | 2020-11-10 21:24:56,511 INFO  [WrapperJarAppMain] AgentBootstrapper:74 - Attempting create and start launcher...
jvm 1    | 2020-11-10 21:24:56,515 INFO  [WrapperJarAppMain] ParentClassAccessFilteringClassloader:43 - Loading com.thoughtworks.cruise.agent.common.launcher.AgentLaunchDescriptor using java.net.URLClassLoader
jvm 1    | Could not find file `config/agent-launcher-logback.xml'. Attempting to load from classpath.
jvm 1    | Using classpath resource `jar:file:/go/data/deps-ca7fb8b01db95630-agent-launcher.jar/agent-launcher-20.9.0-12335-classes.jar!/config/agent-launcher-logback.xml'.
jvm 1    | 2020-11-10 21:24:56,571 INFO  [TouchLoopThread-1] Lockfile:103 - Using lock file: /go/.agent-bootstrapper.running
jvm 1    | 2020-11-10 21:24:57,047 ERROR [WrapperJarAppMain] ServerBinaryDownloader:88 - Couldn't update admin/agent-launcher.jar. Sleeping for 1m. Error:
jvm 1    | org.apache.http.conn.HttpHostConnectException: Connect to localhost:8153 [localhost/127.0.0.1] failed: Connection refused
jvm 1    | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:159)
jvm 1    | 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
jvm 1    | 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
jvm 1    | 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
jvm 1    | 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
jvm 1    | 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
jvm 1    | 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
jvm 1    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
jvm 1    | 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.fetchUpdateCheckHeaders(ServerBinaryDownloader.java:104)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.ServerBinaryDownloader.downloadIfNecessary(ServerBinaryDownloader.java:80)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.doLaunch(AgentLauncherImpl.java:88)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.lambda$launch$0(AgentLauncherImpl.java:68)
jvm 1    | 	at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:62)
jvm 1    | 	at com.thoughtworks.go.agent.launcher.AgentLauncherImpl.launch(AgentLauncherImpl.java:68)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.go(AgentBootstrapper.java:76)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.lambda$main$0(AgentBootstrapper.java:57)
jvm 1    | 	at com.thoughtworks.go.logging.LogConfigurator.runWithLogger(LogConfigurator.java:53)
jvm 1    | 	at com.thoughtworks.go.agent.bootstrapper.AgentBootstrapper.main(AgentBootstrapper.java:57)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | 	at com.thoughtworks.gocd.Boot.run(Boot.java:90)
jvm 1    | 	at com.thoughtworks.gocd.Boot.main(Boot.java:56)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
jvm 1    | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
jvm 1    | 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
jvm 1    | 	at org.tanukisoftware.wrapper.WrapperJarApp.run(WrapperJarApp.java:451)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | Caused by: java.net.ConnectException: Connection refused
jvm 1    | 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
jvm 1    | 	at java.base/sun.nio.ch.Net.pollConnectNow(Unknown Source)
jvm 1    | 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
jvm 1    | 	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
jvm 1    | 	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
jvm 1    | 	at java.base/java.net.Socket.connect(Unknown Source)
jvm 1    | 	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
jvm 1    | 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
jvm 1    | 	... 31 common frames omitted

**Comment by maheshp** [comment]
> docker run --name=gocd_agent -d --restart=always -e GO_SERVER_URL=http://localhost:8153/go gocd/gocd-agent-ubuntu-18.04:v20.9.0

The agent running in a container is unable to connect to the server since its a `localhost` GO_SERVER_URL. The GO_SERVER_URL should be accessible from within the container. Can you please change it and check.

I will close the ticket for now. If you still face issues please reopen the ticket with details.
