### ISSUE TITLE
A "fake" material type

### ISSUE THREAD

**Issue by gaqzi** [gocd/gocd#876]
We use go to manage our deployment pipelines, and thanks to it being installed on all our machines and being tagged with all the correct resources it works really well as a generic task runner. Think cronjob that needs to be run once on any host that fits the resource requirements.

When setting these up we need to rely on some kind of material, so we've created a git repo with one commit. Because of this the listing of jobs always shows the time of that commit rather than the time of when the job was started.
It also forces us to have a git repo around on the go server for this purpose. 

To facilitate using go as a task runner it would be nice to either not having to select a material or have a material type that is used for scheduled jobs that doesn't rely on any other material.

![screen_shot_2015-02-05_at_10_48_06_am](https://cloud.githubusercontent.com/assets/18167/6054200/4f6700cc-ad25-11e4-8851-e749b7b56c3f.png)

**Comment by agathish** [comment]
+1 We have the same issue. We use a dummy yum repo as material source.

**Comment by srinivasupadhya** [comment]
@gaqzi you mentioned that pipeline is for deployments. where do materials (code/packages) come from? the pipeline should ideally consume them & deploy. One of the reasons Go mandates materials for every pipeline is we want to promote the practise

> everything (code, scripts, configuration etc.) is checked into SCM / use a package (created by upstream pipeline or pushed into some package repository)

Having said that, I totally agree pipeline history page (one in your screenshot) is messed up & needs a total revamp.

**Comment by gaqzi** [comment]
@srinivasupadhya lets start with that it's a bit complicated and convoluted. :P 
We have a total of 3 Go servers. One where the primary assets are being generated, from source code. Two that are used for deployment of the same. But because of security policy we send the assets out of band. 

So there's a pipeline which connects using SFTP to fetch the materials from a "safe drop" server, which is how we get the artifacts into a state ready for deployment. (Decrypting, verifying and a bunch of other stuff.)

I'm aware that our flow is more than a little bit ridiculous, but Go works really well for this purpose for us. :)

(If you're with TW you might've  heard of the project, it's in Singapore.)

**Comment by srinivasupadhya** [comment]
> We have a total of 3 Go servers. One where the primary assets are being generated, from source code. Two that are used for deployment of the same. But because of security policy we send the assets out of band. So there's a pipeline which connects using SFTP to fetch the materials from a "safe drop" server, which is how we get the artifacts into a state ready for deployment.

Have you given a shot at package repository [plugins](http://www.go.cd/community/plugins.html)? There are a few s3 poller plugins - [1](https://github.com/sriram-r/gocd-s3material-plugin) & [2](https://groups.google.com/d/topic/go-cd-dev/fRlfHsYZDKY/discussion). I assume they could be modified to suit your case? So you can publish artifacts in specified format, say, `pipeline-name/pipeline-counter` folder structure (btw, you can write a task plugin to do this) & then write a package repository poller which polls for new changes under the folder `pipeline-name`. This makes deployments & rollbacks easier? Also, should give good end to end visualization (using [trackback URL](http://www.go.cd/documentation/user/current/extension_points/package_repository_extension.html#package-information-display) feature)?

> (If you're with TW you might've heard of the project, it's in Singapore.)

Oh yes, I have heard of it :)

**Comment by sriramnrn** [comment]
My notes:

One of our upcoming activities (Björn and I are colleagues on this project)
is to set up a central git repo which we'll use for the scripts to run this
"file transfer + decrypt" pipeline. Since Go doesn't at the moment have the
means to check out material at the server to send to the Agent (like
TeamCity does), we have had to get various firewall rules in place to
permit the Go Agents to contact this repository.

But from this work, we've come to realize the need for a Fake Material,
since I can imagine organizations where setting up a git/SVN repo would
require lots of permission seeking and explaining to random non-tech or
post-tech folks. Having a Fake Material would simply eliminate lengthy and
painful discussions.

-- Ram

**Comment by srinivasupadhya** [comment]
with the new [scm extension](http://www.go.cd/documentation/developer/writing_go_plugins/scm_material/json_message_based_scm_material_extension.html) point you should be able to write a fake plugin. hope that helps.
