### ISSUE TITLE
Cannot create new stage

### ISSUE THREAD

**Issue by readmodifywrite** [gocd/gocd#8769]
##### Issue Type
- Bug Report

##### Summary

Cannot create a new stage for an existing pipeline via the web UI.

##### Environment

Firefox 82.0
Linux Mint 20
GoCD Version: 20.9.0 (12335-cccb4960bde1166ccd79277093295ed5a18573ed)
Using docker image: gocd/gocd-server:v20.9.0

##### Steps to Reproduce

Using this workflow: https://docs.gocd.org/current/configuration/admin_add_stage.html

When clicking "save" nothing happens. No errors, nothing.  The window does not close.  If I click the "X", the window closes, and I have no new stage.

So far the only way I've found to add a stage is to delete the entire pipeline and start over.

**Comment by arvindsv** [comment]
Can you see if there are any errors in the Javascript console, please? [Right-click -> Inspect -> Console]

**Comment by readmodifywrite** [comment]
HTTP Error 412: Precondition Failed

JSON response:
{
  "message" : "Someone has modified the configuration for pipeline 'chromatron_dev'. Please update your copy of the config with the changes and try again."
}

I'm not really sure what the error message is trying to tell me.  The someone is me and only me, and the only copy of the config is on the server itself.

**Comment by maheshp** [comment]
The UI uses the [Pipeline Config API](https://api.gocd.org/current/#pipeline-config) to get/update the config. On fetching the pipeline config the API returns the `Etag` for the pipeline. On [pipeline update](https://api.gocd.org/current/#edit-pipeline-config) the UI submits this `Etag` as part of the `If-Match` header. You would get the above error if the copy of the pipeline config on the server is different from what the UI fetched.

From your comment I do understand that only you are editing the config. But, I was unable to reproduce this issue though. I brought up a fresh GoCD server running the command `docker run -d  -p8153:8153  gocd/gocd-server:v20.9.0`

**Comment by readmodifywrite** [comment]
Yeah, it's a bit odd.  I can only reproduce on my main desktop machine.  My secondary laptop didn't seem to have a problem with it.

Maybe some kind of HTTP caching issue on the client side?

**Comment by maheshp** [comment]
Can you please open the browser developer tools and check if the `If-Match` header posted to the server matches the `Etag` received from the server.

**Comment by readmodifywrite** [comment]
@maheshp I'm currently out of town, but I'll check as soon as I get back in about 10 days.

**Comment by readmodifywrite** [comment]
@maheshp OK it looks like I had a Firefox extension blocking Etags.  Thx!
