### ISSUE TITLE
bug - agent resource tags are case-sensitive when referenced from a job

### ISSUE THREAD

**Issue by jasonduff** [gocd/gocd#8774]
##### Issue Type
Bug Report

##### Summary
When a job has an agent resource tag that does NOT exactly match (e.g. case is different), it fails to find that agent.  This is an issue in 20.7.0.  It was not an issue in 18.7, which is what we upgraded from.

##### Environment
Currently running 20.7.0 on a windows server 2016 VM

###### Basic environment details
GO Version: 20.7.0
JVM: 13.0.2
OS Info: Windows Server 2016 10.0
Chrome browser
3500+ pipelines

**Comment by kritika-singh3** [comment]
Fixed via #8778 and verified on `GoCD Version: 20.10.0 (12354-b9d98c27050ca3d67d568270530c256d4c5f3750)`
