### ISSUE TITLE
Go config edit API - ability to CRUD parts of config

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#878]
parts: server - security, server - mailhost, package repository, package repository - package, scm, pipeline group, pipeline, material, stage, task, template & environment.

**Comment by srinivasupadhya** [comment]
[discussion thread](https://groups.google.com/d/topic/go-cd-dev/UjE9azB72Bc/discussion)

**Comment by bamdadd** [comment]
+1 on this. Is there anything I can help with this?

**Comment by zabil** [comment]
Thanks @bamdadd we'll need a lot of help. 
One approach we are looking at is developing new features or migrating old features to be API driven. This helps us with designing the API. This issue will be soon be linked to those features. 
Will post updates here when those features take shape.

**Comment by zabil** [comment]
This can now be done using the new framework introduced as a part of #1100 

However, these have to be split onto API's to modify resources like pipeline, stages, materials etc instead of api to modify configuration.

**Comment by GaneshSPatil** [comment]
As of GoCD release `v19.12.0`, most of the GoCD config entities support CRUD via API. 
The list of GoCD config entities supporting API updates are documented at https://api.gocd.org

GoCD has set up a framework to support entity config edit via API (for existing as well as new entities which can/will be added in future),  hence, this feature can be considered as done.
