### ISSUE TITLE
ability to delete pipeline history & artifacts on deletion from config

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#879]
Currently pipeline history is not deleted for the possibility of restoring it, i.e. if you add the pipeline back to config you get all historical runs + artifacts.

Downside:
- it brings back history even if you dint wish for it, i.e. even if the pipeline is accidentally named the same as the one that was deleted before, the history is restored which is not the expected behaviour. - [thread](https://groups.google.com/d/topic/go-cd/LVnapi82dmg/discussion)

Positives:
- deletion of database entries should help performance
- deletion of artifacts should certainly help improve storage utilization

Approach:
- It should be optional, some Go users expect the history to never be deleted for audit purposes.
- Go should only delete pipeline entries only if there is no active (in config) downstream pipeline. otherwise it creates holes in VSM for downstream pipelines & breaks links in build-cause.
- Go should recursively try to delete all upstream pipelines if the above condition is met for the upstream pipeline.

**Comment by tedops** [comment]
Alternatively, a Delete/Purge implementation would be acceptable, where pipelines can be marked for deletion using Delete, but then have an option (under Admin + an API endpoint) to Purge deleted pipelines.

**Comment by eugeneventer** [comment]
We are interested in getting this functionality, as we have a lot of pipelines and pretty high pipeline turnover.

**Comment by tedops** [comment]
Perhaps one way to accomplish this would be to prompt the user to either (i) restore the old pipeline + artifacts, or (ii) create a new one, and archive the previously-existing pipeline.

If the user chooses to archive the previously-existing pipeline, it can be moved to a PIPELINEARCHIVE table (or similar), with the app behavior based on the following configurable choices:
* Global default:
  * Keep all (or a combination of) archived pipeline history and/or artifacts
  * Delete archived pipelines after X number of days
  * Automatically delete-on-archive
* Per-pipeline archive settings that override the global default
  * **Bonus**: Have user-defined archived pipeline "filters" which can apply to a matched set/group of pipelines that override the global default (e.g. pipeline name matches a regex)

**Comment by jasonolmstead33** [comment]
Any movement on this? We are also in a situation where we would have a lot of pipelines and would love to be able to delete them or move them to a new group via the API..

**Comment by eugeneventer** [comment]
Hi guys,

Any progress here? Due to high pipeline turnover, we are running out of disk space :(

Thanks!

**Comment by zabil** [comment]
@eugeneventer we are not working on this at the moment.

**Comment by arvindsv** [comment]
@eugeneventer: If you're running out of space, it will probably not be because of pipeline history (which will be a small part of the DB). It'l probably because of artifacts. You can either set them to be automatically deleted or you can delete them yourself. The [GoCD janitor](https://github.com/ashwanthkumar/gocd-janitor) might be useful too. It's a tool written by people from the community, to clean up artifacts.

**Comment by juliuskovac** [comment]
Hey. I also miss this functionality mainly because it is not possible to perform a clean up and continue with clean slate. It's hard to remember what names ware already used and it was surprising for me when old history appeared for a pipeline when I reused old name. Anyway gocd is great, thank you for all the hard work!

**Comment by mfilteau** [comment]
+1 
Hi, I definitively want this feature!

**Comment by davidmaes** [comment]
+1, I would love to see this feature just to start with a clean slate. I have been testing how GoCD works, and with that in mind, I would like to create a clean and decent setup. If there is any way to remove everything manually without completely uninstalling gocd and install from scratch, I would love to hear it.

**Comment by arvindsv** [comment]
If you bring down the server and move/rename the file `/var/lib/go-server/db/h2db/cruise.h2.db` or `C:\Program Files (x86)\Go Server\db\h2db\cruise.h2.db` on Windows, and restart the server, it should start with no history at all but your pipelines will be around, since the config is still around.

**Comment by dudadornelles** [comment]
Would there be a hacky sql statement that we could use to clean up the run history of a pipeline right in the db? Suffering with performance...

**Comment by arvindsv** [comment]
@dudadornelles - No. Perf issue might not be just that. In fact, it's *very* rare for it to be that. That part is heavily cached upon startup.

**Comment by arvindsv** [comment]
The "No" is because the pipeline history is used to generate the VSM, etc. and we're not sure what happens to the rest of the app, if history is deleted in parts. Meaning, can't say what it will affect. Sorry. :(

**Comment by dudadornelles** [comment]
I have a couple of pipelines with 40k+ runs and anytime we open them things get pretty slow. The other pipelines with much less history run just fine though.

**Comment by arvindsv** [comment]
I tried a pipeline on an old GoCD server of ours with 150,000 runs and it was fine. I'm not sure it's correlated directly, but it seems to be the case for you. I'll try and find some time to look into your issue, soon.

**Comment by FarshadHadei** [comment]
Hi, any updates regarding this issue?

**Comment by gosiapolitowska** [comment]
Hi, any updates?

**Comment by lmachacek** [comment]
It is a pity, that this hasn't been implemented :frowning_face: 

For example, we run smoke tests each 5 minutes and then GoCD tables like `pipelinematerialrevisions` and `buildstatetransitions` swelled up and contained tens of millions of rows after few years. Thanks to that GoCD started to be slower, required more and more memory and its start time was around 10 minutes!

For those facing the same troubles, here is what we have done:

1. Stop GoCD
2. Run these queries (it will remove history for all pipelines matching the query!):
```sql
DELETE FROM pipelinematerialrevisions WHERE pipelineid IN (SELECT id FROM pipelines WHERE name LIKE '%-smoke-tests-%' OR name LIKE '%-fitness-functions');
 
DELETE FROM modifications WHERE pipelineid IN (SELECT id FROM pipelines WHERE name LIKE '%-smoke-tests-%' OR name LIKE '%-fitness-functions');
 
DELETE FROM buildstatetransitions WHERE stageid IN (SELECT s.id FROM pipelines p, stages s WHERE (p.name LIKE '%-smoke-tests-%' OR p.name LIKE '%-fitness-functions') AND p.id = s.pipelineid);

DELETE FROM pipelines WHERE name LIKE '%-smoke-tests-%' OR name LIKE '%-fitness-functions';
```
3. Start GoCD

In our case the result reduction was:
|Table | Before | After
|---------|-----------|------------|
|buildstatetransitions | 32 039 070 | 4 126 849 |
|pipelinematerialrevisions | 11 591 439 | 878 363 |
|pipelines | 4 960 490 | 313 732 |

Now GoCD starts 5x faster and don't need 20GiB of RAM :wink:

**Comment by chadlwilson** [comment]
I don’t think this ticket would solve your problem directly, just workaround it by allowing you to delete the pipeline and re-add it. Do you automatically create temporary pipelines and then throw them away or something? Having 5M pipelines in your history seems pretty extreme.

Worth noting for others that deleting the history like this may have implications for other pipeline dependencies, ability to fan-in correctly etc. So be careful.

What database are you using?

**Comment by chadlwilson** [comment]
Yeah, that's certainly an interesting and pretty extreme case, but yes this feature here would be a "workaround" for the root issue you seem to be reporting, which is severely degraded performance (especially of overall dashboard and startup time, rather than something affecting only that pipeline) with pipelines that have a huge number of runs.

I can't think of anything specific to a pipeline's # of run instances, revisions or transitions that should affect server start-up time, and shouldn't affect dashboard either. I'm certainly somewhat surprised to hear it would have that effect on performance of dashboard and memory usage as that would sound like an excessive cache inflation or fetching issue.

How many such logical pipelines did you have that allowed you to remove ~4.6M pipeline run instances from the `PIPELINES` table with the above commands?

To document the root cause and allow a better chance of looking at it, would it be possible to raise a separate issue that includes the summary of your setup here, and an approximation of what the VSM across multiple pipelines (dependencies, basically) that these `smoke-tests` pipelines would have looked like? If they are standalone (which allowed you to do the above commands safely without affecting upstream/downstream dependencies that'd also be useful to know)

**Comment by lmachacek** [comment]
OK, I'll create separate issue.

BTW: we have 36 logical pipelines which allowed us to remove ~4.6M pipeline run instances
And the slow startup is caused by loading pipelines timeline and loading of active pipelines into cache.

Before cleanup (and this is quite fast example - sometimes it took almost 10 minutes):
```
2024-04-17 20:05:44,586 INFO  [WrapperJarAppMain] PipelineRepository:78 - Start updating pipeline timeline
2024-04-17 20:07:19,498 WARN  [WrapperJarAppMain] PipelineRepository:101 - updating in memory pipeline-timeline took: 94910 ms
2024-04-17 20:10:56,199 INFO  [WrapperJarAppMain] PipelineRepository:84 - Pipeline timeline updated
2024-04-17 20:10:56,202 INFO  [WrapperJarAppMain] PipelineSqlMapDao:133 - Loading active pipelines into memory.
2024-04-17 20:10:56,211 INFO  [WrapperJarAppMain] PipelineSqlMapDao:381 - Retriving Active Pipelines from Database...
2024-04-17 20:11:10,810 INFO  [Thread-96] PipelineSqlMapDao:417 - Loading pipeline history to cache...Started
2024-04-17 20:11:10,810 INFO  [Thread-95] PipelineSqlMapDao:411 - Loading Active Pipelines to cache...Started
2024-04-17 20:11:10,810 INFO  [WrapperJarAppMain] MaterialRepository:239 - Loading PMRs,Remaining 3 Pipelines (Total: 3)...
2024-04-17 20:11:10,814 INFO  [Thread-95] PipelineSqlMapDao:414 - Loading Active Pipelines to cache...Done
2024-04-17 20:11:10,829 INFO  [Thread-96] PipelineSqlMapDao:421 - Loading pipeline history to cache...Done
2024-04-17 20:11:10,841 INFO  [WrapperJarAppMain] MaterialRepository:315 - Loading modifications, Remaining 3 PMRs(Total: 3)...
2024-04-17 20:11:10,850 INFO  [WrapperJarAppMain] PipelineSqlMapDao:135 - Done loading active pipelines into memory.
```

After cleanup:
```
2024-04-20 19:41:15,340 INFO  [WrapperJarAppMain] PipelineRepository:78 - Start updating pipeline timeline
2024-04-20 19:41:45,327 WARN  [WrapperJarAppMain] PipelineRepository:101 - updating in memory pipeline-timeline took: 29985 ms
2024-04-20 19:41:57,392 INFO  [WrapperJarAppMain] PipelineRepository:84 - Pipeline timeline updated
2024-04-20 19:41:57,402 INFO  [WrapperJarAppMain] PipelineSqlMapDao:133 - Loading active pipelines into memory.
2024-04-20 19:41:57,411 INFO  [WrapperJarAppMain] PipelineSqlMapDao:381 - Retriving Active Pipelines from Database...
2024-04-20 19:42:19,219 INFO  [Thread-95] PipelineSqlMapDao:411 - Loading Active Pipelines to cache...Started
2024-04-20 19:42:19,219 INFO  [Thread-96] PipelineSqlMapDao:417 - Loading pipeline history to cache...Started
2024-04-20 19:42:19,220 INFO  [WrapperJarAppMain] MaterialRepository:239 - Loading PMRs,Remaining 3 Pipelines (Total: 3)...
2024-04-20 19:42:19,223 INFO  [Thread-95] PipelineSqlMapDao:414 - Loading Active Pipelines to cache...Done
2024-04-20 19:42:19,241 INFO  [Thread-96] PipelineSqlMapDao:421 - Loading pipeline history to cache...Done
2024-04-20 19:42:19,304 INFO  [WrapperJarAppMain] MaterialRepository:315 - Loading modifications, Remaining 3 PMRs(Total: 3)...
2024-04-20 19:42:19,317 INFO  [WrapperJarAppMain] PipelineSqlMapDao:135 - Done loading active pipelines into memory.
```
