### ISSUE TITLE
pg_dump missing from gocd docker v20.8

### ISSUE THREAD

**Issue by darynsteelsword** [gocd/gocd#8799]
##### Issue Type

- Bug Report (of the docker container?)

##### Summary

The GoCD v20.8 docker image does not successfully run a manual or automated backup, cause appears to be that the official gocd docker image does not have pg_dump installed, fails with this error in web interface:

```Backing up Database
Failed to perform backup. Reason: org.zeroturnaround.exec.ProcessInitException: Could not execute [pg_dump, --no-password, --host=XXXXXXXX, --port=5432, --username=XXXXXXXX, gocd, --file=/go-working-dir/artifacts/serverBackups/backup_20201126-115224/db.gocd] with environment {PGPASSWORD=XXXXXXXX}. Error=2, No such file or directory
```

###### Basic environment details

```Go Server Information: "20.8.0 (12213-1e23a06e49…f1a8e83d9b209fc0a290cb)"
Pertinent startup flags: "-Dgo.database.provider=com.thoughtworks.go.postgresql.PostgresqlDatabase"
Java version: "14.0.2"
Docker startup command: docker run -d -p 8153:8153 -p 8154:8154 -v /godata:/godata -v /home/go:/home/go   ........   -e GOCD_SERVER_JVM_OPTS="-Xmx4g -Dgo.database.provider=com.thoughtworks.go.postgresql.PostgresqlDatabase" gocd/gocd-server:v20.8.0
```

##### Steps to Reproduce

1. Login as an admin user
2. Visit https://<go-server-url>/go/admin/backup
3. Click "Perform Backup"
4. Watch the backup progress step by step, until the "Backing up database" step occurs

##### Expected Results
The backup directory /go-working-dir/artifacts/serverBackups/<backup directory> should be created and populated with the manual/automated backup contents.

##### Actual Results
Backup directory is created in the appropriate location, populated with 
```
./backup_20201126-111803/version.txt
./backup_20201126-111803/config-repo.zip
./backup_20201126-111803/wrapper-config-dir.zip
./backup_20201126-111803/config-dir.zip
```

and the directory is then deleted automatically when the db backup fails.

##### Possible Fix
Inclusion of pg_dump (postgresql-client?) package into the Docker image?

##### Log snippets

Error output from web gui:
```
Failed to perform backup. Reason: org.zeroturnaround.exec.ProcessInitException: Could not execute [pg_dump, --no-password, --host=XXXXXXXX, --port=5432, --username=XXXXXXXX, gocd, --file=/go-working-dir/artifacts/serverBackups/backup_20201126-115224/db.gocd] with environment {PGPASSWORD=XXXXXXXX}. Error=2, No such file or directory
```

Error output from logs:
```
jvm 1    | 2020-11-26 11:52:56,361 ERROR [104@MessageListener for ServerBackupListener] BackupService:189 - [Backup] Failed to backup Go.
jvm 1    | java.lang.RuntimeException: org.zeroturnaround.exec.ProcessInitException: Could not execute [pg_dump, --no-password, --host=XXXXXXXX, --port=5432, --username=XXXXXXXX, gocd, --file=/go-working-dir/artifacts/serverBackups/backup_20201126-115224/db.gocd] with environment {PGPASSWORD=XXXXXXXX}. Error=2, No such file or directory
jvm 1    | 	at com.thoughtworks.go.server.database.Database.backup(Database.java:73)
jvm 1    | 	at com.thoughtworks.go.server.service.BackupService.backupDb(BackupService.java:339)
jvm 1    | 	at com.thoughtworks.go.server.service.BackupService.performBackup(BackupService.java:178)
jvm 1    | 	at com.thoughtworks.go.server.service.BackupService.startBackupWithId(BackupService.java:144)
jvm 1    | 	at com.thoughtworks.go.server.messaging.ServerBackupListener.onMessage(ServerBackupListener.java:34)
jvm 1    | 	at com.thoughtworks.go.server.messaging.ServerBackupListener.onMessage(ServerBackupListener.java:22)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.runImpl(JMSMessageListenerAdapter.java:83)
jvm 1    | 	at com.thoughtworks.go.server.messaging.activemq.JMSMessageListenerAdapter.run(JMSMessageListenerAdapter.java:63)
jvm 1    | 	at java.base/java.lang.Thread.run(Unknown Source)
jvm 1    | Caused by: org.zeroturnaround.exec.ProcessInitException: Could not execute [pg_dump, --no-password, --host=XXXXXXXX, --port=5432, --username=XXXXXXXX, gocd, --file=/go-working-dir/artifacts/serverBackups/backup_20201126-115224/db.gocd] with environment {PGPASSWORD=XXXXXXXX}. Error=2, No such file or directory
jvm 1    | 	at org.zeroturnaround.exec.ProcessInitException.newInstance(ProcessInitException.java:80)
jvm 1    | 	at org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:1002)
jvm 1    | 	at org.zeroturnaround.exec.ProcessExecutor.startInternal(ProcessExecutor.java:970)
jvm 1    | 	at org.zeroturnaround.exec.ProcessExecutor.execute(ProcessExecutor.java:906)
jvm 1    | 	at com.thoughtworks.go.server.database.pg.PostgresqlBackupProcessor.backup(PostgresqlBackupProcessor.java:42)
jvm 1    | 	at com.thoughtworks.go.server.database.ConnectionManager.backup(ConnectionManager.java:59)
jvm 1    | 	at com.thoughtworks.go.server.database.Database.backup(Database.java:71)
jvm 1    | 	... 8 common frames omitted
jvm 1    | Caused by: java.io.IOException: Cannot run program "pg_dump": error=2, No such file or directory
jvm 1    | 	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
jvm 1    | 	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
jvm 1    | 	at org.zeroturnaround.exec.ProcessExecutor.invokeStart(ProcessExecutor.java:997)
jvm 1    | 	... 13 common frames omitted
jvm 1    | Caused by: java.io.IOException: error=2, No such file or directory
jvm 1    | 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
jvm 1    | 	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
jvm 1    | 	at java.base/java.lang.ProcessImpl.start(Unknown Source)
jvm 1    | 	... 16 common frames omitted
```

Is this just a case of pg_dump not making it into the image somehow?

Thanks for any advice,

Steve

**Comment by arvindsv** [comment]
As far as I know, it was never included because there are incompatibilities between pg_dump across Postgres server versions. Since GoCD supports v9.6, v10, v11 and v12 of Postgres, it's not possible to include one version that works across all. I'm reasonably sure that an older version of pg_dump/pg_restore does not work with a newer version of the Postrgres server.

In cases other than within a Docker image, this is not a problem, since the pg_dump version wil be correct. Maybe we should document it / mention it as a note in the docs?

/cc @maheshp might know more.

**Comment by maheshp** [comment]
@arvindsv you are right, we would not be able to include a specific version of pg_dump considering the different versions supported.

> I'm reasonably sure that an older version of pg_dump/pg_restore does not work with a newer version of the Postrgres server.

Yeah, the same is mentioned in [pg_dump docs](https://www.postgresql.org/docs/9.6/app-pgdump.html)

This needs to be documented and probably with a workaround.

**Comment by arvindsv** [comment]
Maybe including v12 of pg_dump can be considered, but without a lot of testing across versions (and more, as new versions get introduced), I wouldn't be comfortable with that, given the downsides of being wrong in a backup/restore scenario. I think documenting it, and explaining it is better.

**Comment by darynsteelsword** [comment]
I'd guess that an environment variable

**Comment by arvindsv** [comment]
Possibly. If you have a tested PR,  I'm sure it will be considered. Here are some files that are relevant to this:

https://github.com/gocd/gocd/blob/f09453b57b970aa730f171eb76ccf2580d72a7ee/buildSrc/src/main/resources/gocd-docker-agent/Dockerfile.agent.ftl

https://github.com/gocd/gocd/blob/d41b35cfd9079f0d96fb8c91a13ab7c695ce3dd4/buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy

If you run:

```bash
./gradlew docker:gocd-agent:assemble -PdockerBuildLocalZip
```

... you'll see the Dockerfile etc in: `docker/gocd-agent/target/`. For instance: `docker/gocd-agent/target/alpine-3.10/docker-gocd-agent-alpine-3.10/Dockerfile`.

**Comment by arvindsv** [comment]
Also, typically stuff shouldn't be installed in the docker-entrypoint.sh. It should be installed during image creation. It feels icky to me that it will get install every time the server container starts or restarts.

**Comment by sriramnrn** [comment]
Another point of view - those who run GoCD with PostGres may have other
preferred backup mechanisms. My personal favourite is to stop GoCD, take a
backup and then start it.

Perhaps those who want pgdump as part of the container image could create
another container image deriving from it with the new layer containing the
pgdump of choice.

-- Ram

**Comment by darynsteelsword** [comment]
That's probably the easiest way to go, I'll look at that.

Cheers!

**Comment by Oliver-Loeffler** [comment]
This somehow could play well together with issue #8943. (configurable location of `pg_dump`).
