### ISSUE TITLE
Document that default agent Environment can be set via /etc/default/go-agent

### ISSUE THREAD

**Issue by keithy** [gocd/gocd#8804]
but you need to explicitly export each value or use

set -o allexport

**Comment by arvindsv** [comment]
@keithy I don't think that's true of the latest versions of GoCD, whose locations are documented here: https://docs.gocd.org/current/installation/install/agent/linux.html#location-of-gocd-agent-files

Based on that understanding, I'll close this issue. But happy to re-open if I've understood it wrong.

Also, PRs for documentation changes can be opened here: https://github.com/gocd/docs.go.cd/
