### ISSUE TITLE
GoCD server material updates taking an excessive amount of time after upgrading 20.2.0 to 20.4.0

### ISSUE THREAD

**Issue by manudawber** [gocd/gocd#8862]
##### Issue Type

- Bug Report

##### Summary

After upgrading to GoCD 20.4.0 config repository updates are taking much longer to complete. On 20.2.0 depending on the repository material updates take from a few seconds to a minute, on 20.4.0 material updates are routinely taking 30 minutes or more to complete. The pipelines belonging to these repos can not be executed while the update is underway.

##### Environment

GoCD is running on an EC2 instance of type c5.2xlarge (16 vCPU, 32GB memory). Our upgrade process is to build a new server and backup / restore to migrate data then switch over traffic using an ELB.

```plain
"Number of pipelines": 4557,
"Number of environments": 44,
"Number of agents": 97,
"Number of unique materials": 3121,
"Number of schedulable materials": 3115
```

`material.config.check.threads` = 10

###### Basic environment details

* Go Version: 20.4.0 (11749-5553066d29d315951efa5ead0c087374df6338b9)
* JAVA Version: 13.0.2
* OS: Linux 3.10.0-1160.6.1.el7.x86_64

###### Additional Environment Details

We've confirmed this is not an issue with the Bitbucket by turning on the previous GoCD installation (20.2.0), the problematic behavior is not occurring on that server.

###### Logs

Log line showing the slow material update process

```plain
2020-12-10 14:12:27,720 WARN  [ThreadPoolTaskScheduler-4] MaterialUpdateService:188 - [Material Update] Skipping update of material GitMaterial{url=ssh://git@bitbucket:7999/sp/k8s-api-pipelines.git, branch='master', submoduleFolder='null', shallowClone=false} which has been in-progress since Thu Dec 10 13:40:27 NZDT 2020
```

Number of skipped material updates due to the previous still executing in 20.2.0
```plain
$ zcat go-server.log.2020-12-09.0.gz | grep "Skipping update of material" | wc -l
6308
```

Number of skipped material updates due to the previous still executing in 20.4.0
```plain
$ zcat go-server.log.2020-12-10.0.gz | grep "Skipping update of material" | wc -l
166395
```

**Comment by maheshp** [comment]
I went through the changes between GoCD 20.2.0 - 20.4.0 and I couldn't find anything specific that could directly result in slow material updates. There might be other reasons which needs to be investigated.

Is your GoCD server using the default H2 database? 

There are by default 10 material update threads, since you have 3000+ materials, have you considered using [webhooks](https://api.gocd.org/current/#webhook) over auto polling of materials.

**Comment by manudawber** [comment]
Hey @maheshp, thanks for your response. We are using the H2 DB and are looking in to using webhooks but it will be a lot of work for us so are checking all other options first.

In the end we're planning to skip 20.4.0 as we haven't encountered the issue in any version after this one.

**Comment by maheshp** [comment]
@manudawber I will close this issue since it seems resolved.

We have seen H2 to be a bottleneck once the GoCD instance grows. Considering the size of your GoCD instance, I would probably consider migrating to PostgreSQL.
