### ISSUE TITLE
Go to Job Console Log, appears in the same window

### ISSUE THREAD

**Issue by avatarworf** [gocd/gocd#8876]
##### Feature enhancement

- Feature enhancement

##### Summary

In one of the recent GUI enhancements, the rollover on pipeline stages, places the 'Go to Job Console Log' into a new browser windows (_blank)

##### Environment

```plain
      "Number of pipelines": 278,
      "Number of environments": 1,
      "Number of agents": 9,
      "Number of unique materials": 281,
      "Number of schedulable materials": 281
```

###### Basic environment details

* Go Version: `20.10.0`
* JAVA Version: `15.0.1`
* OS: `Linux 4.14.203-156.332.amzn2.x86_64`
* Browser vendor and version (if relevant): `Chrome 87`

##### Steps to Reproduce

1. Click the Console icon, executed to a new window `_blank`

##### Expected Results
Clicking on this link appears in the same window

##### Actual Results
Launches into a new browser tab
This does, in our opinion added level of clicks, browser window switching added additional delay to using the UX, when managing multiple pipelines

##### Possible Fix
Add a new feature flag to `/etc/go/go.feature.toggles` to change `_blank` to `_self`

##### Code snippets/Screenshots

![image](https://user-images.githubusercontent.com/1407879/101878307-9de00b00-3b8f-11eb-8847-d6f4ece8faac.png)

**Comment by maheshp** [comment]
I think a feature toggle for something like this is a overkill. There has been some other [feedback](https://github.com/gocd/gocd/issues/8506#issuecomment-741857107) around the new Stage overview as well. Keeping all of this in mind we will have to consider further UX enhancement.

**Comment by dAnjou** [comment]
I second what OP is saying. Whether to open something in a new tab/window should be up to the user, it's usually just a middle-click instead of a left-click. For some reason this doesn't work for the console icon link which makes it impossible to quickly open logs for multiple jobs in a row.
