### ISSUE TITLE
gocd-server fail on start with CONFIG_GIT_REPO

### ISSUE THREAD

**Issue by Windol** [gocd/gocd#8878]
I'm trying to start a gocd-server: v20.10.0 docker containder using a git settings repository. But when cloning the configuration repository, you are giving the following error:

```console
/usr/local/sbin/git-clone-config: line 10: [: too many arguments
```

**Comment by Windol** [comment]
I was forced to create an workaround to make it work. But the problem persist.

**Comment by Windol** [comment]
Has this been verified by anyone?

**Comment by chadlwilson** [comment]
Can you share a bit more information here on your environment, the arguments you are setting and how to reproduce it?
- what is the value you're giving for `CONFIG_GIT_REPO`? If it contains credentials or private info please redact them, but anything weird like spaces or special characters would be good to know.
- which specific Docker image/tag are you using? is it the same on `21.2.0`?

**Comment by Windol** [comment]
> Can you share a bit more information here on your environment, the arguments you are setting and how to reproduce it?
> 
> * what is the value you're giving for `CONFIG_GIT_REPO`? If it contains credentials or private info please redact them, but anything weird like spaces or special characters would be good to know.

In my `CONFIG_GIT_REPO` I have only one SSH URI (no spaces and symbols) pointing to a private repository:
`CONFIG_GIT_REPO=git@bitbucket.org:organization/config.repository.git`

![image](https://user-images.githubusercontent.com/740253/129241426-20cfd038-d209-4f41-8240-6699c65051ad.png)

> * which specific Docker image/tag are you using? is it the same on `21.2.0`?

The last build I did and that showed the problem was in version `21.1.0`.
In order to create the server, I started to recreate the image by changing the `git-clone-config` file.

```
FROM gocd/gocd-server:v21.1.0

# FIXME: Remove on issue fixed
RUN sed -ri 's/(\[ ! `.*\])/[\1]/' /usr/local/sbin/git-clone-config
```

This workarround worked for me.

**Comment by chadlwilson** [comment]
While I can replicate the error in an artificial setup locally just running the script directly with bash `5.1`, I cannot replicate it with the real GoCD docker images going via the real entrypoint. Probably missing something. I have a draft change at #8878 but not keen to merge unless we really understand under which circumstances it fails here.

e.g `docker run -e CONFIG_GIT_REPO=git@github.com:gocd/gocd.git gocd/gocd-server:v21.1.0` gets past this point in the script.

```
...
$ install-gocd-plugins
$ mkdir -p /godata/plugins/external
$ git-clone-config
$ cd /godata/config
fatal: not a git repository (or any of the parent directories): .git
/usr/local/sbin/git-clone-config: fill /godata/config from git@github.com:gocd/gocd.git
$ git init
Initialized empty Git repository in /godata/config/.git/
$ git remote add origin git@github.com:gocd/gocd.git
$ git fetch
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
/usr/local/sbin/git-clone-config: cannot git fetch
/docker-entrypoint.sh: cannot git-clone-config
```

Are you doing anything else in your environment which might affect the bash version or the way it works, perhaps changing the run user, mounting volumes in some specific way or changing the Docker entrypoint?

If you have a `docker run <args>` re-prod that would help.

**Comment by chadlwilson** [comment]
OK, after a bit more thought, I managed to replicate this when mounting `/godata` to an external volume. The first time it runs it will work if `/godata/config` doesn't have a git repo in it. 

Subsequent runs it appears to log the error you mention, but continue to try and start the server regardless. If the fetch+checkout actually worked the first time it will have no effect, but if it had failed for some reason, it might be left in an inconsistent state.
