### ISSUE TITLE
Set right permissions on go server upgrade

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#889]
When upgrading go-server, the installer should chown all relevant folders and files inside it /etc/go and give permissions to go user. However looks like it just changes permissions for the topmost folder but not files inside it. Ex - Change permissions for log4j.properties inside /etc/go such that it is owned by root or some other user. Try upgrading go-server. The installation fails due to permissions issue on log4j.properties file

**Comment by arvindsv** [comment]
This used to be true a long time ago (the upgrade scripts used to use ```chown -R```). However, that caused it to try and change ownership of artifacts directory. When an artifacts directory has 200GB of artifacts, this is not pretty ... and quick. Also, shine RDF files. As long as that is taken care of, everything else can be chown'ed properly.

**Comment by arikagoyal** [comment]
Yes you are right. This should not be done for /var/lib/go-server but for /etc/go. I have edited the issue accordingly. Of-late i am seeing lot of deployment failures on different environments due to this issue so pulling this issue to 15.1 milestone.

**Comment by mdaliejaz** [comment]
Have put the fix for /etc/go

Also, we can change parts of (which is not already covered) /var/lib/go-server if required. We do change the ownership of some parts of it :)

```
in installers/shared/shared_post.sh

function fix_go_server_lib_ownership {
    go_owned_toplevel /var/lib/go-server
    go_owned_toplevel /var/lib/go-server/**
    go_owned /var/lib/go-server/db/config.git
    go_owned /var/lib/go-server/db/deltas
    go_owned /var/lib/go-server/db/h2deltas
    go_owned /var/lib/go-server/db/h2db
    go_owned /var/lib/go-server/db/command_repository/default
}

go_owned_toplevel -> chown
go_owned -> chown -R
```

**Comment by arikagoyal** [comment]
Works fine on 15.1.0(1587-dcefa94a22ae98)
