### ISSUE TITLE
"Config Changed" diff marks lines containing dash (`-`) as removed

### ISSUE THREAD

**Issue by MPV** [gocd/gocd#8899]
##### Issue Type

- Bug Report

##### Summary

"Config Changed" diff marks lines containing dash (`-`) as removed.

###### Basic environment details

* Go Version: `GoCD Version: 20.3.0 (11530-f54d0bae7a39fe7add5460f3f8676a7936abf698).`
* JAVA Version: `13.0.2`
* OS: `Linux 4.19.112+`
* Browser vendor and version (if relevant): `Chrome Version 87.0.4280.88 (Officiell version) (x86_64)`

###### Additional Environment Details

N/A

##### Steps to Reproduce

1. Make diff in a GoCD pipeline that contains dashes in the beginning of lines
2. Open "Config Changed" from the Stage Details view

##### Expected Results

Diff showing:
- green for added lines
- red for removed lines

##### Actual Results

Diff showing:
- green for added lines
- red for removed lines
- red for lines beginning with a dash (`-`)

##### Possible Fix

Only lines beginning with `-` (and no whitespace before it) should be treated as removed lines in diffs.

##### Code snippets/Screenshots

<img width="255" alt="Skärmavbild 2020-12-17 kl  16 56 25" src="https://user-images.githubusercontent.com/62675/102511597-41965300-4089-11eb-960f-841d777063f5.png">

👇 

<img width="1261" alt="Skärmavbild 2020-12-17 kl  16 51 35" src="https://user-images.githubusercontent.com/62675/102511609-465b0700-4089-11eb-8d63-00a5fee10636.png">

**Comment by marques-work** [comment]
@MPV This should be fixed in the next release. Unfortunately, we won't be backporting it to 20.3.0, so you'll have to upgrade when 21.2.0 is released to get this fix.
