### ISSUE TITLE
Windows installer should build using default makensis

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#890]
Currently, the Windows installer is generated from a ["Special Build" of NSIS](http://nsis.sourceforge.net/Special_Builds), which needs to be compiled. The default nsis package from the Debian package manager cannot be used. This is just because of the [LogSet](http://nsis.sourceforge.net/Reference/LogSet) and LogText calls, which log installation information into install.log.

This should be made optional, so that a Windows installer can more easily be built.

**Comment by mdaliejaz** [comment]
Verified. Logging looks fine on 15.2.0(2030-c393c3e).
