### ISSUE TITLE
arguments of Custom Command with spaces will failed to run

### ISSUE THREAD

**Issue by dongyuwei** [gocd/gocd#8916]
##### Issue Type
- Feature enhancement

##### Summary
When we define a Custom Command, if the argument starts with empty spaces or ends with spaces, the command will failed to run. Such as:
```bash
ls
 -al ##keep an eye the space surrounds the -al
```

or
```bash
bash
-c  ##keep an eye the space here
echo ok;
```

##### Environment
- go-agent-20.10.0
- go-server-20.10.0    20.10.0 (12356-b16b6bc3f7ad3bb39e465ff2168d1cc66c95b4d5)

macOS Big Sur or Windows 10

###### Basic environment details
* Go Version: GoCD Version: 20.10.0 (12356-b16b6bc3f7ad3bb39e465ff2168d1cc66c95b4d5).
* JAVA Version: 15.0.1
* OS: Mac OS X 10.16

##### Steps to Reproduce
1. Add a 'Custom Command' task,
2. input `ls` in command input field, and input `  -al  ` in the arguments input field.
3. run the task.

##### Expected Results
The command should passed without problem.

##### Actual Results
```
[go] Task: bash "-c " "echo ok;"took: 0.117sexited: 2
bash: - : invalid option
Usage:	bash [GNU long option] [option] ...
	bash [GNU long option] [option] script-file ...
GNU long options:
	--debug
	--debugger
	--dump-po-strings
	--dump-strings
	--help
	--init-file
	--login
	--noediting
	--noprofile
	--norc
	--posix
	--protected
	--rcfile
	--restricted
	--verbose
	--version
	--wordexp
Shell options:
	-irsD or -c command or -O shopt_option		(invocation only)
	-abefhkmnptuvxBCHP or -o option
[go] Task status: failed, took: 0.117s, exited: 2
```

Or

```
[go] Task: ls "-al "took: 0.112sexited: 1
ls: illegal option --  
usage: ls [-@ABCFGHLOPRSTUWabcdefghiklmnopqrstuwx1%] [file ...]
[go] Task status: failed, took: 0.112s, exited: 1
```

Or

```
ls:     -al: No such file or directory
[go] Task status: failed, took: 0.109s, exited: 1
```

##### Possible Fix
trim the spaces of the arguments.

##### Code snippets/Screenshots
![image](https://user-images.githubusercontent.com/112451/103149096-5a95b700-47a1-11eb-826f-fa803510e95d.png)

![image](https://user-images.githubusercontent.com/112451/103148982-7a78ab00-47a0-11eb-8427-586dcaa13a3d.png)

![image](https://user-images.githubusercontent.com/112451/103149128-9cbef880-47a1-11eb-8f7f-a7e4922b4695.png)

![image](https://user-images.githubusercontent.com/112451/103148990-8cf2e480-47a0-11eb-9315-65e8d4ba30b3.png)

**Comment by marques-work** [comment]
This is a user error more than anything else. Admittedly, it's tough to see these, and most of the time, we probably don't mean for spaces to be present. But there are instances where a space is an intentional argument. We should highlight spaces in the UI (maybe with a faint dot, like IDEs tend to do).
