### ISSUE TITLE
re-schedule of jobs causing duplicate DB entries for resource and artifacts

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#894]
Everytime a job reschedules all its resources, artifacts go doubled. So the growth is 2^x (where x is number of times job got re-scheduled). In one particular case

Job got re-scheduled 21 times (causing 2 * 2^21 resource entries (2 resources for job) & 2 * 2^21 artifact entries (2 artifacts for job)). 

This makes Go server unresponsive when the pipeline is loaded through dashboard or pipeline-history pages.

**Comment by arikagoyal** [comment]
Works fine on 15.1.0(1528-11c3045bb72f5f)
