### ISSUE TITLE
Cannot secret nor in config repo nor from pipeline as a code (yaml)

### ISSUE THREAD

**Issue by sergevonage** [gocd/gocd#8942]
##### Cannot invoke secret nor from Config Repo UI nor from pipeline as a code (yaml)

- Feature proposal
- Feature enhancement

##### Summary
I have connected AWS secret plugin and have a secret. But I don't how to access that secret from yaml in my pipeline.
All combinations are failed:
- '${{SECRET:[secret_config_id][secret_key]}}'
- '#{{SECRET:[secret_config_id][secret_key]}}'

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1. Add AWS Secret plugin
2. Add Secret
3. Use secret in pipeline as a code
4. Try to add pipeline to Config Repo

##### Expected Results

Secret processed correct
##### Actual Results

Secret isn't processed for both config repositories and pipeline yaml
##### Log snippets
```
Modification check failed for material: URL: https://github.com/<private_user>/<private_repo>/, Branch: fix/cicd No pipelines are affected by this material, perhaps this material is unused.
```

```
The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: '"latest-revision failed due to [RuntimeException: Exception (Process exited with an error: 128 (Exit value: 128)) Occurred: [git, clone, --branch=master, --no-checkout, https://username:${{SECRET:[secret_config_id][secret_key]}}@github.com
```

**Comment by arvindsv** [comment]
This issue might be relevant: https://github.com/tomzo/gocd-yaml-config-plugin/issues/136

Also, I think this issue needs to be in the [YAML plugin's repo](https://github.com/tomzo/gocd-yaml-config-plugin). So, I'll close this issue here.
