### ISSUE TITLE
Make `pg_dump` path configurable for PostgreSQL backup processor

### ISSUE THREAD

**Issue by Oliver-Loeffler** [gocd/gocd#8943]
##### Issue Type
- Feature proposal

##### Summary

In some installations where PostgreSQL is used, the automated backup procedure will fail as `pg_dump` will refuse to do its work due to a version mismatch. This can happen, when GoCD runs with a dedicated PostgreSQL instance which has version different from the one provided in by the system (via `/usr/bin`, or via path). This can be an issue on Linux and Windows Systems.

As in some unfortunate cases, an adjustment of the environment or changing the links in `/usr/bin` is not possible.
Thus it is desirable, to manually configure which version of `pg_dump` will be used by the backup process.

The backup task is launched by `com.thoughtworks.go.server.database.pg.PostgresqlBackupProcessor.java` and therein it is not defined which `pg_dump` will be used.

Following enhancement proposal:
* The backup processor already takes a Properties object called `dbProperties`.
* There, one could define a property with name `PGDUMP` which will be either empty or populated with a valid location of a `pg_dump` such as `/usr/pgsql-11/bin/pg_dump` (this one just serves as an example).  
* The provided path then could be used to launch the dump. (use of `/usr/pgsql-11/bin/pg_dump` instead of `./pg_dump` or `pg_dump`)
* If variable is not defined or left empty, go with GoCDs defaults.
* This property could be used to enable GoCD to use a different `pg_dump` version as provided by all system default means.

Personally I have solved this problem for me, buy modification of  `bin/go-server`.
The first non-comment line is now `export PATH=/path-2-my-db/bin/:$PATH`. This works well but, at each update of GoCD I have to do this again.

I have not yet prepared a PR, just want to know first, what you think!

Thanks for GoCD and you'll have a good start into 2021!
Keep up with doing this great job.

**Comment by Oliver-Loeffler** [comment]
If accepted, I'd sign the contributor agreement and make a proposal.

**Comment by maheshp** [comment]
@Oliver-Loeffler sorry for the late reply. I think it should be ok to add a new configuration in dbProperties. Probably we should think of a generic name for the new property over `PGDUMP` to allow configuring the `mysqldump` path as well.

WDYT?

**Comment by Oliver-Loeffler** [comment]
I think, allowing to configure MySQL dump location is a good idea as well. MySQL users probably face the same issue. 
A more generic name could be `DUMP_CMD` for example.

**Comment by maheshp** [comment]
`db.dumpCmd` sounds reasonable to me. We will have to document the defaults and also mention that the property could be configured with the command which includes the path [here](https://docs.gocd.org/current/installation/configuring_database/connection-properties.html) 

Thanks @Oliver-Loeffler!

**Comment by Oliver-Loeffler** [comment]
Ah, no worry, still working on this one. Yet I am struggeling with the local build.

**Comment by arvindsv** [comment]
Not sure if the trouble you're having with it is due to memory, but I had to do something like this recently:

```shell
export NODE_OPTIONS=--max_old_space_size=6120

# Also, change build.gradle
$ git diff build.gradle
diff --git a/build.gradle b/build.gradle
index ab4182508e..f4b221aec1 100644
--- a/build.gradle
+++ b/build.gradle
@@ -156,7 +156,7 @@ rootProject.ext.fullVersion = DIST_VERSION ? "${GO_VERSION}-${DIST_VERSION}" : G
 rootProject.ext.gitRevision = GIT_REVISION
 rootProject.ext.copyrightYear = Calendar.getInstance().get(Calendar.YEAR)

-project.ext.defaultJvmArgs = []
+project.ext.defaultJvmArgs = ['-Xmx5g']

 project.ext.compilerOptions = [
   sourceCompatibility: 11,

# Finally build it ...
$ ./gradlew agentGenericZip serverGenericZip
```

Without this, it kept failing due to out-of-memory issues at different places.
