### ISSUE TITLE
Consolidate Docker Image version creation / Env GOCD_PLUGIN_INSTALL_ does not work for all versions

### ISSUE THREAD

**Issue by sfuhrm** [gocd/gocd#8947]
##### Issue Type

- Bug Report

##### Summary

The docker image supports installing plugins using the env var GOCD_PLUGIN_INSTALL_* according to the [documentation](https://hub.docker.com/r/gocd/gocd-server).
Unfortunately older versions, in this example v17.6.0, do not support this yet.

##### Environment

The environment is
* Docker
* GoCD server docker image version v17.6.0

###### Basic environment details

* Go Version: v17.6.0
* JAVA Version: Java 1.8.0_151
* OS: Alpine Linux

##### Steps to Reproduce

The problem can be viewed in an integrational Circle CI setup [here](https://github.com/1and1/go-maven-poller/blob/master/.circleci/config.yml). The difference is with the blocks called 'shared_gocd_server_integration_mount' and 'shared_gocd_server_integration_env'

Positive case:

1. docker run --name gocd-server -e GOCD_PLUGIN_INSTALL_email-notifier=https://github.com/gocd-contrib/email-notifier/releases/download/v1.0.0-74-exp/email-notifier-1.0.0-74.jar -p8153:8153 gocd/gocd-server:v18.6.0
2. Browse to http://localhost:8153/go/admin/plugins and see email notifier plugin (it will say target go version is 20.9.0, but GoCD doesn't care)

Negative case:

1. docker run --name gocd-server -e GOCD_PLUGIN_INSTALL_email-notifier=https://github.com/gocd-contrib/email-notifier/releases/download/v1.0.0-74-exp/email-notifier-1.0.0-74.jar -p8153:8153 gocd/gocd-server:v17.6.0
2. Browse to http://localhost:8153/go/admin/plugins and see missing email notifier plugin

##### Expected Results

The plugin is downloaded as documented in the README.

##### Actual Results

The plugin is not downloaded.

##### Possible Fix

Consolidation of image versions should be done. It is important to have a way to integrate with different GoCD server versions.

I'd recommend creating images for *all* GoCD versions fresh all the time using one patched base image.
The base OS should be patched and secure and up-to-date.
The documentation should match all GoCD server tags.

##### Code snippets/Screenshots

It looks like the images are created based on [this](https://github.com/gocd/docker-gocd-server) github repo.

**Comment by arvindsv** [comment]
As an idea, I like it and it makes sense. But, the effort to maintain this across the 60-odd releases, given that the versions of Java changes across the different releases, etc. makes this impractical to do, _in my opinion_. Also, each release of the Docker image was fully tested at the time it was released. Trying to do that across releases also makes it even more resource intensive, especially given that the older releases are less likely to be used by a lot of people.

Given that, and assuming the GoCD team won't be doing this, I'll close this issue. However the discussion can continue, and if anyone does want to do this (and assuming DockerHub will build all of this), we can create a repo in gocd-contrib or somewhere for this. Or, we can reopen this issue at a later time too.
