### ISSUE TITLE
GOCD version 20.10 port 8154 is not working

### ISSUE THREAD

**Issue by PP-gocd** [gocd/gocd#8967]
##### Issue Type
Hi, kindly advise .  Thanks. :)

##### Summary
GOCD version 20.10 port 8154 is not working
We have upgrade GOCD from version 20.4 to 20.5 , then version 20.5 to 20.10.
1)After upgrade, we are unable to access port 8154 (default) , only can access port 8153.
2)Unable to login to GOCD GUI using the domain account.

**Comment by arvindsv** [comment]
Port 8154 was removed in 20.6.0. It was mentioned in the 20.2.0 release notes (https://www.gocd.org/releases/#20-2-0) in section "Changes to SSL Support" and was supposed to be removed in 20.6.0, which it was: https://www.gocd.org/releases/#20-6-0
