### ISSUE TITLE
Unable to login using LDAP account after upgrade from version 20.4 to 20.10.

### ISSUE THREAD

**Issue by PP-gocd** [gocd/gocd#8968]
##### Summary

Unable to login using LDAP account after upgrade from version 20.4 to 20.10.
- https://gocdserverIP:8153/go
- any changes require in the configuration ? 
- bugs of version 20.10 ? 

###### Basic environment details

* Go Version: 20.10
* JAVA Version: 1.8.0_275
* OS: Linux redhat

**Comment by arvindsv** [comment]
There isn't any useful information provided here. Questions should be sent to the mailing list: https://groups.google.com/forum/#!forum/go-cd
