### ISSUE TITLE
Error while updating Go Pipeline config using Go-CD API 17.4.0 version

### ISSUE THREAD

**Issue by Niteshcse** [gocd/gocd#8972]
Hi I am running below command using PowerShell script  for updating my Go Pipeline config using Go CD API Put method but getting error below

$putResponse = D:\temp\curl.exe  -X PUT -u 'test:****' -H 'Accept: application/vnd.go.cd.v4+json' -H 'Content-Type: application/json' -H 'If-Match: "etagvalue"' 'http://********:8153/go/api/admin/pipelines/testpipe' -d $text

"message": "Someone has modified the configuration for pipeline 'my_pipeline'. Please update your copy of the config with the changes."

Request you to please help

**Comment by arvindsv** [comment]
This (GitHub issues) is only for known issues. The mailing list conversation going on is the right place for a question.
