### ISSUE TITLE
Unable to login using LDAP account after upgrade from version 20.4 to 20.10.

### ISSUE THREAD

**Issue by PP-gocd** [gocd/gocd#8977]
Summary:
**>> Please don't ticket quickly. <<
>>Let me know if need more information.<<**

Unable to login using LDAP account after upgrade from version 20.4 to 20.10.

Before upgrade, we are able to login using LDAP account via https://gocdserverIP:8154/go.
After upgrade , we are unable to login using LDAP account via https://gocdserverIP:8153/go.

any changes require in the configuration ? which setting to change?
bugs of version 20.10 ?
If bug, please advise , how can we fix? 

Basic environment details
Go Version: 20.10
JAVA Version: 1.8.0_275
OS: Linux redhat

**Comment by arvindsv** [comment]
8153 is an HTTP port. Not HTTPS. The GoCD 20.2.0 release notes mention SSL related changes: https://www.gocd.org/releases/#20-2-0

**Comment by PP-gocd** [comment]
Noted Arvin. When we login via http "port 8153" , we are unable to login using LDAP account. 
Kindly advise us how can we fix. Thank you.

**Comment by maheshp** [comment]
@PP-gocd it will be tough to help without much information. 

Also, GitHub issue is not the right place for these questions, can you please write to the mailing list with more information.
To start of, let us know the LDAP plugin used and do you see any errors in the plugin logs.

I will close this issue.
