### ISSUE TITLE
No way to add LDAP user(s)

### ISSUE THREAD

**Issue by kramer101** [gocd/gocd#898]
Adding an LDAP user results in the "No users selected" message despite the user is actually selected (checkbook is checked) in the "Add user" dialog.

This misbehavior makes the use of AD accounts impossible.
Please see attached screenshot
Go Version: 14.4.0(1356-86064ef5ee28e0)

![go add users](https://cloud.githubusercontent.com/assets/2284205/6271032/e82f2fda-b812-11e4-8ef9-060587236e2c.jpg)

**Comment by kramer101** [comment]
Go Version: 14.4.0(1356-86064ef5ee28e0)

**Comment by arvindsv** [comment]
@kramer101, do you see this happening with all users? Or, users with space in their username or maybe a special character in their username? I ask because I'm wondering if it is related to [this](https://github.com/gocd/gocd/issues/834). I had a fix for that one, but I haven't yet submitted a PR for it.

If that's what's happening with you too, then maybe I can dust up that PR and submit it.

**Comment by arvindsv** [comment]
Might help to open the Chrome Developer console and see if there are any JS errors, or errors in the response, if you're so inclined. If not, some more info about the kind of users this happens with, might help.

**Comment by kramer101** [comment]
Hi
it does happen with more than one user. All the users I attempted to add had the bang "!" and the dash "-" in the user name. No spaces.
Hope this helps

**Comment by kramer101** [comment]
@arvindsv 
Hi
and yes there is a POST error appears in the Dev console
Please see attached

Hope this helps

Thanks
![go add users - post error](https://cloud.githubusercontent.com/assets/2284205/6274114/ef036242-b829-11e4-8066-00e39352dec5.jpg)

**Comment by arvindsv** [comment]
Yeah, that does help, thank you. I think it's very similar to #834. I'll take a look at it soon, and probably fix both together, if I can reproduce it.

**Comment by kramer101** [comment]
@arvindsv 
Great. Thanks

One other thing to mention is that I also have a password file with one user in it. In case it might matter.

**Comment by arvindsv** [comment]
I've submitted a pull request for this. While it goes into the next release, probably, here's a workaround you can use, in the developer console in Chrome:

```
jQuery.ajax({url: '/go/admin/users/create', type: 'POST', data: {
  'selection': 'on',
  'selections[][name]': '!MY-USER-NAME',
  'selections[][full_name]':'First!-Name Last!-Name',
  'selections[][email]': 'my.email@somemail.com'
}}).done(function(message) { console.log("Looks like it succeeded!")}).error(function(message) { console.error(message); })
```

Just replace the username, full name and email parts in the above snippet and paste it into the developer console, after you are logged in. Once this runs, you should be able to see the user, when you refresh the page. Here's a screenshot of this running in my browser:

![createuser](https://cloud.githubusercontent.com/assets/172235/6289284/0a86b42e-b8ed-11e4-8e2e-0c5689c6e894.png)

**Comment by kramer101** [comment]
Thanks. This workaround actually did help.

**Comment by srinivasupadhya** [comment]
works on `go-server-15.1.0-1767`
