### ISSUE TITLE
GitMaterial Authentication failed for the second user who using same repository

### ISSUE THREAD

**Issue by slankka** [gocd/gocd#8986]
##### Issue Type

- Bug Report

##### Summary

If two git materials are configured in two pipelines with same git repo and different username + accesstoken, the second user will failed to checkout.

##### Environment

```plain
"Go Server Information": {
    "Version": "20.6.0 (12005-12860aac6351e2a353728c7d7913f34d741c63e0)"
  }，
"OS Information": {
    "OS Name": "Linux",
    "OS Version": "3.10.0-862.el7.x86_64",
    "System Architecture": "amd64",
    "Available Processors": 24,
    "Average System Load": 0.67
  },
```

###### Basic environment details

* Go Version: `20.6.0 (12005-12860aac6351e2a353728c7d7913f34d741c63e0)`
* JAVA Version: `13.0.2`
* OS: `Linux 3.10.0-862.el7.x86_64`

##### Steps to Reproduce

1. create two pipeline with git credential `https://gitlab.somehost/someproject.git`, username and password(gitlab accesstoken) are provided in advanced settings. 
2. the username/accesstokens of those git material are belongs to two person. now call them userA and userB.
3. While click `test connection` in `Edit material - Git`, both repositories says: "Connection OK".
4. trigger the first pipeline mannually, later it will success.
5. trigger the second pipeline mannually, later it will output `Authentication failed`

##### Expected Results
The second pipeline should works as the first one.

##### Actual Results
The second pipeline build failed with message `Authentication failed` and `Failed to run git clone command`

##### Possible Fix

I have read some source code, the access token are stored correctly in cruise file.The material editing page uses it too.

The method `com.thoughtworks.go.config.materials.git.GitMaterial#appendCriteria` is like:
```
        parameters.put(ScmMaterialConfig.URL, url.originalArgument());
        parameters.put("branch", refSpecOrBranch);
```
the `generateFingerprintFromCriteria` is using `type`, `url`, `branch`, it will using the first pipeline's material.

It seems that is agent JVM, the `com.thoughtworks.go.config.materials.ScmMaterial`:
```
    protected String userName; //the userName is always UserA.
    protected String password;
```

I cannot figure out why `GitMaterial` failed to checkout userB's pipeline.

##### Log snippets
To see command line logs, provide:
logback-agent-include.xml
```
<logger name="com.thoughtworks.go.util.command.CommandLine" level="DEBUG" >
     <appender-ref ref="commandLineLog"/>
</logger>
```

Agentlog
```
2021-01-20 17:15:51,543 DEBUG [scheduler-3] CommandLine:350 - Running git config remote.origin.url
2021-01-20 17:15:51,681 DEBUG [scheduler-3] CommandLine:362 - Output: 
https://UserB:UserB'Accesstoken@gitlab.host/project.git
2021-01-20 17:15:51,778 DEBUG [scheduler-3] CommandLine:368 - Running git clone --branch deploy https://UserA:******@gitlab.host/project.git /var/lib/go-agent/pipelines/HandyCreated
2021-01-20 17:15:52,164 ERROR [scheduler-3] DefaultGoPublisher:137 - Failed to run git clone command
java.lang.RuntimeException: Failed to run git clone command
        at com.thoughtworks.go.util.ExceptionUtils.bomb(ExceptionUtils.java:37)
        at com.thoughtworks.go.config.materials.git.GitMaterial.updateTo(GitMaterial.java:157)
        at com.thoughtworks.go.domain.MaterialRevision.updateTo(MaterialRevision.java:147)
        at com.thoughtworks.go.domain.materials.AbstractMaterialAgent.prepare(AbstractMaterialAgent.java:43)
......
Caused by: java.lang.Exception: Failed to run git clone command
        at com.thoughtworks.go.util.ExceptionUtils.bombIfFailedToRunCommandLine(ExceptionUtils.java:51)
        at com.thoughtworks.go.config.materials.git.GitMaterial.git(GitMaterial.java:384)
        at com.thoughtworks.go.config.materials.git.GitMaterial.updateTo(GitMaterial.java:151)
        ... 20 common frames omitted

```

```
[go] Start to update materials.

[go] Start updating files at revision 65d9a85e92e8284857409fe62fcef2d80fb9211c from https://gitlab.<host>.com/<project>.git
Cloning into '/var/lib/go-agent/pipelines/HandyCreated'...
STDERR: fatal: Authentication failed for 'https://<userA>:******@<host>/<project>.git/'
Failed to run git clone command
```

##### Code snippets/Screenshots
![image](https://user-images.githubusercontent.com/8142133/105148039-e00c4d00-5b3c-11eb-8a2a-0eaf35b3646c.png)
![image](https://user-images.githubusercontent.com/8142133/105148223-14800900-5b3d-11eb-9f85-409d08834091.png)

**Comment by maheshp** [comment]
GoCD would consider the git materials from both the pipelines as same since the the repo URL is unique in both the materials. Hence as part of material update it could end up picking up the credentials from one of the configured materials.

While I need to understand why the authentication fails in one case since the Test connection passed for both, I am wondering why would you need to configure the same material with different credentials.

**Comment by slankka** [comment]
Thanks for replying @maheshp , I developed a CI-CD system based on GoCD (by GOCD API). There are different users join in one git project. They provide their own gitlab `Personal Access Token`. In some case, for example: one developer creates a pipeline for production purpose while another developer creates for test enviroment.

As far as I'm concerned, Test Connection passed because of CuriseConfig the test procedure reading is correct, however, while the GoAgent receiving a `BuildAssignment`, the build logs indicates that `com.thoughtworks.go.config.materials.git.GitMaterial` may picks up wrong username(In this issue, the first person's username.) with correct access token.

**Comment by maheshp** [comment]
Thanks @slankka I understand the reason why configuring materials with different credentials.

I will have to try to reproduce this scenario on my side. So far, my understanding was that in these kind of scenarios GoCD would pick up a material either from Pipeline-1 or Pipeline-2 but would never mix up the credentials from the materials.

**Comment by vengi57** [comment]
Even I am also facing the same, when I try to create two pipelines with repository URL as same and with different credentials
Note: When I use the same Bitbucket  repo URL for two pipelines with different credentials it was able to clone and execute the pipeline
When I use the same GitLab repo URL for two pipelines with different credentials it was a success for the first executed pipeline and the second pipeline failed because it was taking the credentials of the first pipeline

**Comment by gosszhang** [comment]
I have the same.I have delete one pipeline,but the left pipeline still use the wrong username(the pipeline I have deleted).
