### ISSUE TITLE
google-oauth with GoCD - Locked out

### ISSUE THREAD

**Issue by pracplayopen** [gocd/gocd#8989]
##### Issue Type

- Bug Report

##### Summary

1. we enabled google oauth per instructions in the admin authorization page of gocd server
2. something was configured incorrectly and it would not allow any logins
3. we were locked out of server
4. tried following instructions here to regain access: https://github.com/gocd/gocd/issues/734  (removed old security configuration, saved config and restarted server)
5. this did not work.  after restarting the server, the old configuration was somehow restored and it was still attempting oauth.  tried clearing cache and multiple browsers, to no avoid.  every time the auth section was removed and go-server restarted, it self-restored this part of the config.

###### Basic environment details

* Go Version: 19.4.0
* JAVA Version: jre1.8.0_161
* OS: tinycore-pure64 8.0
* Browser vendor and version (if relevant): chromium stable 87.0.4280.66  (also used firebox, surf, same result)

###### Additional Environment Details

We're starting server using standard server.sh scripts included with 19.4.0.

##### Steps to Reproduce

1. open admin page in gocd, go to authenticatioin
2. add a google oauth authenticator
3. add appropriate credentials
4. add domain redirect (in our case the error maybe that the domain is public the ips it resolves to are private)
5. then enable and attempt to authenticate
6. now you're locked out of server, try following issue #734  to gain access.   unfortunately it doesn't seem to take config changes.

##### Expected Results
We should be able to stop server, modify the config/cruise-config.xml file, restart and have changes apply.

##### Actual Results
Instead it's somehow restoring the old config file.

##### Possible Fix
Is there some cached config somewhere or some safety/security setting preventing this now (that wasnt' present in #734)?
I tried deleting the server's 'work' directory, as this sometimes fixes stuck issues with the server.
Had no effect though.

##### Log snippets

```
2021-01-23 01:33:23,167 INFO  [main] GoConfigMigration:94 - Upgrading config file from version 123 to version 123
2021-01-23 01:33:23,363 WARN  [Thread-82] PluginSettingsMetadataLoader:65 - Plugin: cd.go.authentication.ldap - Metadata load info: [{extension='authorization', configuration='null', view='null', error='The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Request go.plugin-settings.get-configuration is not supported by plugin.''}]
2021-01-23 01:33:23,375 INFO  [main] GoConfigMigration:102 - Finished upgrading config file
2021-01-23 01:33:24,560 WARN  [Thread-82] PluginSettingsMetadataLoader:65 - Plugin: yum - Metadata load info: [{extension='package-repository', configuration='null', view='null', error='The plugin sent a response that could not be understood by Go. Plugin returned with code '400' and the following response: 'Invalid request name go.plugin-settings.get-configuration''}]
2021-01-23 01:33:25,182 INFO  [main] CachedGoConfig:224 - About to notify config listeners

```

##### Code snippets/Screenshots

n/a
##### Any other info

Also seemed like when this happened, all our desktop-cruise control instances lost access.

**Comment by pracplayopen** [comment]
As a temporary but imperfect workaround, deleting the security section and setting the config file to read-only let us back into the server.  However now we can't change anything, so less than ideal.

**Comment by pracplayopen** [comment]
not sure what happened but setting config to read write and then fixing the security error seems to be allowing changes again, so slightly better workaround

**Comment by arvindsv** [comment]
As far as I know, there is nothing new around the security part of the config. Removing it should work (even without a server restart). In case there is a syntax (or semantic) error in the config, after it is removed, then the internal git repo of configuration changes will be used to overwrite your external changes and restore it to a known good state.

Since this is no longer a problem, I'll close this issue.

**Comment by pracplayopen** [comment]
Removing it without a server restart definitely did not have any effect.

Per https://github.com/gocd/gocd/issues/734, the only manual editing of the config in this case was removing the entire security section (both start/end 'security' tags).   Which because it didn't work (and the old confile was restored), we had to start over and remove that section again repeatedly.   So confident it's not a syntax error with removing the config (the original config was added by gui for included google authenticator).

I suppose it's possible there is some other error in our config that is only detected when the google authentication was enabled?    It can't be the security section itself because after we fixed it by setting it ro, we were able to get back in with a password file.

Perhaps it could also be that our specific failure case (trying to login to a public domain on a private ip) triggered some other sort of strange behavior in the server that affected the database.  Not sure what to look for if this was the case but if desired I can attach more logs from friday.

Anyways I totally get this is a weird weeds-type issue but just wanted to record the experiences in case it happens to somebody else.

**Comment by arvindsv** [comment]
> Anyways I totally get this is a weird weeds-type issue but just wanted to record the experiences in case it happens to somebody else.

@pracplayopen Yes, that makes sense. It could help others who face this. Thank you for recording it. :)
