### ISSUE TITLE
Improve agents page layout

### ISSUE THREAD

**Issue by greuelpirat** [gocd/gocd#8999]
##### Issue Type

Layout issues

##### Summary

* Yellow background for Building Agents overflows row
* Row-Text should be centered vertically in row

###### Basic environment details

Go Server Version: | 21.1.0 (12439-5a4959c7c4ede49165ec961b0219126cd5aa9e52)
JVM version: | 15.0.1
OS Information: | Windows Server 2019 10.0

##### Code snippets/Screenshots
![image](https://user-images.githubusercontent.com/16866222/106239027-3561f180-6202-11eb-84a6-5b166319009c.png)

**Comment by marques-work** [comment]
Thanks - I was able to reproduce this pretty easily. I'll take a look.
