### ISSUE TITLE
GoCD Agent and msbuild, nuget and localsystem problem

### ISSUE THREAD

**Issue by brian-sysmirror** [gocd/gocd#9000]
Windows 2019 Server Standard
GoCD Server (go-server-21.1.0-12439-jre-64bit-setup.exe)
GoCD Agentt (go-server-21.1.0-12439-jre-64bit-setup.exe
Microsoft Build Tool 2019 (vs_buildtools__1812409860.1607961636.exe)
Git (Git-2.30.0.2-64-bit.exe)

The default install for the GoCD Agent on Windows Server uses the localsystem account. Unfortunately, this causes problem with msbuild and nuget when the default package management format is "PackageReference", which is the Microsoft recommended format for VS 2019.

Here's a snippet of the log file

Using shared compilation with compiler from directory: c:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn
CSC : error CS2001: Source file 'C:\Windows\system32\config\systemprofile\.nuget\packages\microsoft.net.test.sdk\16.5.0\build\netcoreapp2.1\Microsoft.NET.Test.Sdk.Program.cs' could not be found. [C:\Program Files (x86)\Go Agent\pipelines\Default\TestProject\TestProject.csproj]

The solution to the problem is to create an account, grant the account the "Logon as a service" permission and use that account for the GOCD agent service.

**Comment by chadlwilson** [comment]
It looks like the best way to address this is to set the `NUGET_PACKAGES` environment variable to something like `C:\Windows\system32\config\systemprofile\.nuget\packages` to workaround NuGet's incorect concatenation with the default home dir when running as `LOCALSYSTEM` (it has a missing `\`), either at 
* your agent level in the GoCD agent `config\wrapper-properties.conf` like
   ```
   set.NUGET_PACKAGES=C:\Windows\system32\config\systemprofile\.nuget\packages
   # or maybe the below, or somewhere else
   set.NUGET_PACKAGES=C:\Windows\SysWOW64\config\systemprofile\.nuget\packages
   ```
* OR within environment variables for your individual builds
* OR within scripting that runs your builds, prior to NuGet running

See https://github.com/NuGet/Home/issues/6027#issuecomment-339417142
