### ISSUE TITLE
Config repository GIT feature broken on Windows

### ISSUE THREAD

**Issue by sysmirror** [gocd/gocd#9001]
Windows 2019 Server Standard
GoCD Server (go-server-21.1.0-12439-jre-64bit-setup.exe)
GoCD Agentt (go-server-21.1.0-12439-jre-64bit-setup.exe
Microsoft Build Tool 2019 (vs_buildtools__1812409860.1607961636.exe)
Git (Git-2.30.0.2-64-bit.exe)

The config repository feature is broken on Windows using GIT.  Here are some o the error from the log file.

2021-01-30 18:00:39,413 ERROR [qtp1201193977-36] VariableReplacer:385 - function ${escape:} type 'escape:' not a valid type

2021-01-30 17:57:29,640 WARN  [125@MessageListener for ConfigMaterialUpdateListener] ConfigMaterialUpdateListener:66 - [Config Material Update] Cannot update configuration part because material update has failed. Reason: Failed to run git clone command STDERR: Cloning into 'C:\Program Files (x86)\Go Server\pipelines\flyweight\6da8258c-6433-41dc-97e4-8f92c66e24ba'...
STDERR: fatal: Remote branch master not found in upstream origin. Cause: Failed to run git clone command

**Comment by arvindsv** [comment]
What happens if you do a "Test connection"? This just seems like a misconfigured material / repo. Not a broken feature. Based on these logs.

**Comment by sysmirror** [comment]
"Test connection" generates the error message "ref refs/heads/master".

Sorry but I forgot to mention the github connection uses a personal access
token instead of a password. Could this be the problem?

If you need more information, let me know and I'll document all the steps I
took including creating the git repository and I'll also provide complete
error logs.

**Comment by arvindsv** [comment]
Yes, it could be related to authentication or something. Two things you can check:

1. Using a public repository, say: https://github.com/tomzo/gocd-json-config-example.git

2. Doing a `git clone` using that URL, as you are using it in GoCD.

Why I suspect a problem with the repo configuration is that GoCD uses the command-line `git` itself and this error is coming from there and is shown by GoCD in the logs.

**Comment by sysmirror** [comment]
Config repository name: Test
Plugin ID: JSON Configuration Plugin
Material type: GIT
URL:  https://github.com/tomzo/gocd-json-config-example.git

Here's the error I receive when I click on the "Test Connection" button.

Error performing command: --- Command ---
git ls-remote " https://github.com/tomzo/gocd-json-config-example.git"
refs/heads/master
--- Environment ---
{}
--- INPUT ----


--- EXIT CODE (128) ---
--- STANDARD OUT ---

--- STANDARD ERR ---
STDERR: fatal: protocol ' https' is not supported

**Comment by arvindsv** [comment]
There seems to be a space, before the beginning of that URL. Can you see if removing that space does anything different?

**Comment by arvindsv** [comment]
Also, try a git clone of your original URL from the command-line.

**Comment by sysmirror** [comment]
Everything is working as expected now. I tried the original URL and that's
ok. I have no idea what I did wrong. Sorry for wasting your time.

**Comment by arvindsv** [comment]
:) No problem. Thanks for confirming it's ok.
