### ISSUE TITLE
Cannot input multiple lines for perforce material view

### ISSUE THREAD

**Issue by charlesgoonetilleke** [gocd/gocd#9002]
##### Issue Type

- Bug Report

##### Summary

After upgrading our go server to 20.4, we noticed that the Perforce (P4) material view does not accept multiple lines. Before the upgrade we were able to specify multiple lines as below to define the perforce workspace.

###### Basic environment details

* Go Version: `20.4.0`
* JAVA Version: `13.1.0`
* OS: `Windows Server 2019`
* Browser vendor and version (if relevant): `Google Chrome/Firefox`

##### Steps to Reproduce

1. Create new/edit pipeline with a Perforce material
2. Attempt to add multiple lines in the P4 View 

##### Expected Results
Should be able to define a multi-line perforce view

##### Actual Results
Can only define one line for perforce view

##### Possible Fix
Please add ability to define multiple lines for P4 View as in previous version of GoCD

**Comment by arvindsv** [comment]
Agree. This should be a textarea.

**Comment by charlesgoonetilleke** [comment]
Hi all

Any ETA on this fix?

Cheers
