### ISSUE TITLE
issues with the blacklist in materials (misleading documentation, strange behaviour)

### ISSUE THREAD

**Issue by NachbarsLumpi** [gocd/gocd#902]
In the documentation it says: "[...] _Changes of thoes files will not trigger the pipeline. the pattern is **relative to the root of the SCM repository**, not the sandbox of the pipeline._". But this is not true, it's not relative to the root of the SCM repository but relative to the root of the repository to be checked out. And there's a typo (_thoes_).

Despite that I'm unable to get it to work. We have a SVN repository layout like this:

```
applications/
  app1_type1
  app2_type2
  app3_type3
packages/
  type1Package1
  type2Package1
  type2Package2
  type3Package1
other huge stuff not to fetch/
```

There are many packages such that we fetch the application and all the packages (not the root of the svn to exclude other paths) as a material, but would like to blacklist several groups of packages by type such that builds are only triggered if a package of a certain type was changed. Blacklisting looked promising and as such we tried this (for instance on app1):

```
type2*/**/*,type3*/**/*
```

This way the pipeline is not triggered when a commit changes any of the type1 packages.

According to the documentation the configuration should be:

```
packages/type2*/**/*,packages/type3*/**/*
```

But this way the pipeline is triggered always, which to me is quite clear since the root of the checked out SCM does not include the "packages" node.

I know that there is the alternative to configure every package as a separate material, but this could take quite a long time whereas blacklisting would work just fine while it is a good trade-off between flexibility and wasted bandwidth.

And yes, I know that it would be a lot easier if each package would be under a node named after its type. But unfortunately it is currently not possible to restructure the SCM layout. :-)

**Comment by arvindsv** [comment]
I haven't given this too much thought yet, but I just wanted to clarify a point you made above:

```
This way the pipeline is not triggered when a commit changes any of the type1 packages. ...
```

How is that true? When you **blacklisted** type2 and type3, then a build should not be triggered when a commit happens into type2 or type3. Type1 commits should cause a pipeline to trigger. Right? It's a blacklist, not a whitelist.

Let me know what I'm not understanding right.

I agree with your analysis about packages/type2 vs. type2. It's not the root of the real repo, but the root of the part of the repo you specified as a material. For git, since partial checkout isn't really possible, this is correct. For SVN and others with partial checkout, the wording should be changed.

**Comment by NachbarsLumpi** [comment]
That's right. Unfortunatel, a build is not triggered even if type1 packages
are modified. We tried several different blacklist configurations with
different results, but not one behaved like we wanted. To mention some:

packages/type2*/**/*,packages/type3*/**/*

Builds always, no matter what package is modified. This is to be expected
since that we do not checkout the packages node.

type2*/**/*,type3*/**/*

Pipeline doesnt get triggered at all, no matter what package is modified.
It should fire off on type1 packages, shouldnt it? Is the pattern wrong?

**Comment by arvindsv** [comment]
It looks like the documentation might be right after all. Looking at the code, it looks like it is using the output of svn log to get the modified files. The output of svn log does contain the whole path, all the way from the root. Here's some output from a repo I created locally (matching your description):

```
$ svn log -r6 -v file:///tmp/svn-repo
------------------------------------------------------------------------
r6 | myusername | 2015-02-24 18:30:25 -0500 (Tue, 24 Feb 2015) | 1 line
Changed paths:
   M /packages/type1_first/dir1/file1

Add to packages/type1_first/dir1/file1
------------------------------------------------------------------------
```

Given this, the blacklist worked for me, when I set it to ```packages/type1*/**/*```. The patterns gets converted to the regex ```packages/type1[^/]*/([^/]*/)*[^/]*``` and then gets matched against the path shown above. If, after all the patterns are applied (against each file modified/added/deleted), if there are lines which were not removed by any of the patterns, then it is considered to be a valid commit to trigger a pipeline.

Also, I don't know if it is obvious, but this is just to decide when to trigger a pipeline, not to do a partial checkout (on the agent side, for instance). All files will be checkout out, when a build starts, whether they are blacklisted on not.

**Comment by NachbarsLumpi** [comment]
This clears away some of the fog. Gotta try that out and feed back the
results. It kind of feels like I had tried that pattern already, but even a
small error could make the difference. Anyway, can we in the mean time
continue with the discussion? For instance, i would like if you tried
this...

How does it behave if you have multiple materials from svn with each
referencing a partial checkout? I.e. like:

Material1: http://svnsrv/repo1/applications/app1oftype1
Material2: http://svnsrv/repo1/packages

And a blacklist on material2 like this:

packages/type2*/**/*,packages/type3*/**/*

And at the same time have several nested subdirectories in a type1 package?
Something along:

Packages/type1package/dir1/dir2/dir3

With files in dir2 and dir3.

What happens if the type prefixes are just one character (d, p, c)?

Puh. This is quite complicated even only to explain. :-)

**Comment by arvindsv** [comment]
> Anyway, can we in the mean time continue with the discussion?

Sure.

> Puh. This is quite complicated even only to explain. :-)

Yes, it is getting quite complicated for me to understand as well. :)

> How does it behave if you have multiple materials from svn with each
referencing a partial checkout? [snip]

Alright, that's too complicated. :) How about this? Use svnadmin create and create some repos like that, and send it to me. Then, we can at least be on the same page about it, and can talk about what patterns might work, based on which files are changed and which ones are blacklisted.

**Comment by arvindsv** [comment]
Closing. Haven't heard back in a while. I'm sure it is still confusing. Needs better docs, at least.

**Comment by reachbharathan** [comment]
@arvindsv 
In my project, for a pipeline we need to exculde all the folders except one folder,
Do we have any option to exclude all except specific one,
can you give an example for the folder ?

**Comment by ketan** [comment]
@reachbharathan — what you're looking for is a whitelist instead of a blacklist. Whitelist support was recently added in 16.6. See https://docs.go.cd/current/configuration/configuration_reference.html#git
