### ISSUE TITLE
aarch64 bootstrapper support

### ISSUE THREAD

**Issue by marques-work** [gocd/gocd#9029]
GoCD technically works on ARM64 by essentially just doing `java -jar go.jar`.

It would be nice to get the tanuki convenience bootstrapper actually working on Linux ARM64 (aarch64) and eventually MacOS on M1 (whenever an ARM-native JDK is released for macOS anyway) as this platform is becoming more important these days.

For now, it should be straightforward to support packaging linux/aarch64.

**Comment by Preen** [comment]
Any news on this?

**Comment by chadlwilson** [comment]
I don't believe any work has been done on this, no. At the time this ticket was raised the Tanuki Wrapper version theoretically already had aarch64 support on linux (`3.5.41`) so I'm not sure if there were issues with it that lead to this issue being created (and the wording "_actually working on LKinux ARM64_")

Subsequent to this the wrapper has been updated to a version with builds for MacOS aarch64 as well (`3.5.46`+) but that hasn't been tested either.

**Comment by chadlwilson** [comment]
Will close this in favour of th duplicate at #8544 which is a bit more generic. MacOS aarch64 builds and packaged JREs are tested and working in #10887 .

The Tanuki wrappers seem to be fine for aarch64 and are already being packaged, so just needs some validation, I believe.
