### ISSUE TITLE
task plugin & secure fields might not be working

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#903]
They might not be getting encrypted. Also, check [1](https://github.com/gocd/gocd/blob/2275d7e8d2e976231f99550f2c9eda9b01e02b41/config/config-api/src/com/thoughtworks/go/config/pluggabletask/PluggableTask.java#L130) & [2](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/server/service/tasks/PluggableTaskService.java#L70).

**Comment by arvindsv** [comment]
@varshavaradarajan: Were you working on something similar to this, recently?
