### ISSUE TITLE
Plugin - add ability for the same plugin to register for multiple end-points.

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#904]
Eg:
The S3 plugins (poller, fetch & publish) & similar plugins (Docker - poller & publisher) should have been one plugin.

Also, Github PR poller should be able to add task plugin which can mark the PR green/red.

**Comment by arvindsv** [comment]
I think this ability (to implement multiple endpoints) exists. Try it.

**Comment by srinivasupadhya** [comment]
existed in annotation based approach. AFAIK, the new JSON based API doesn't allow this.

**Comment by arvindsv** [comment]
Ok, I think [this](https://github.com/gocd/gocd/blob/master/plugin-infra/go-plugin-infra/src/com/thoughtworks/go/plugin/infra/FelixGoPluginOSGiFramework.java#L333) might cause the failure then, since there will be multiple objects implementing the GoPlugin interface. We will have to add some other identifier as well.

**Comment by arvindsv** [comment]
Notes for implementation: Need to put the implemented plugin type somewhere [here](https://github.com/gocd/gocd/blob/master/plugin-infra/go-plugin-activator/src/com/thoughtworks/go/plugin/activation/DefaultGoPluginActivator.java#L127) and use it somewhere around [here](https://github.com/gocd/gocd/blob/master/plugin-infra/go-plugin-infra/src/com/thoughtworks/go/plugin/infra/FelixGoPluginOSGiFramework.java#L322) and calls to [this](https://github.com/gocd/gocd/blob/master/plugin-infra/go-plugin-infra/src/com/thoughtworks/go/plugin/infra/FelixGoPluginOSGiFramework.java#L249).

**Comment by kritika-singh3** [comment]
[This](https://github.com/gocd/gocd/pull/6956) PR maybe relevant to this issue.
