### ISSUE TITLE
GOCD new version with build-in Java 15.0.2 

### ISSUE THREAD

**Issue by PP-gocd** [gocd/gocd#9056]
##### Summary

Let us know which GOCD version support the Java 15.0.2. 

After install GOCD 21.1.0 , GOCD build-in Java version is 15.0.1.
To fix Java vulnerability with Java 15.0.2, we would like to know the GOCD new version.
Kindly advise us.

###### Basic environment details

* Go Version: 21.1.0
* JAVA Version: 15.0.1
* OS: Linux 3.10.0-1160.11.1.el7.x86_64
* Browser vendor and version : Google chrome 86.0

**Comment by arvindsv** [comment]
Hello!

A new GoCD release should come out soon. Meanwhile, if you do need to use a different JRE, you should be able to modify the configuration in `wrapper-properties.conf` to point to a different JRE.

**Comment by maheshp** [comment]
Done as part of https://github.com/gocd/gocd/pull/9086
