### ISSUE TITLE
Documentation: how to assign agent to different server

### ISSUE THREAD

**Issue by matthiaskraaz** [gocd/gocd#9074]
##### Issue Type

- Documentation

##### Summary

Assignment of agent to different server fails with agent logging:

```
java.lang.RuntimeException: org.apache.http.client.ClientProtocolException: The server returned status code 422. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
   - There is possibly a reverse proxy (or load balancer) that has been misconfigured. See https://docs.gocd.org/21.1.0/installation/configure-reverse-proxy.html#agents-and-reverse-proxies for details.
```

##### Environment

Any

###### Basic environment details

Any

###### Additional Environment Details

Any

##### Steps to Reproduce

1. Connect agent to server A
2. Change server URL of agent to server B
3. Observe: agent does not show up in server B agents tab. agent logs:

```
java.lang.RuntimeException: org.apache.http.client.ClientProtocolException: The server returned status code 422. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
   - There is possibly a reverse proxy (or load balancer) that has been misconfigured. See https://docs.gocd.org/21.1.0/installation/configure-reverse-proxy.html#agents-and-reverse-proxies for details.
```

##### Expected Results

Documentation should tell that you have to remove the files "token" and "guid.txt".

##### Actual Results

Found nothing helpful in the documentation.

##### Possible Fix

Add FAQ entry

##### Log snippets

```
java.lang.RuntimeException: org.apache.http.client.ClientProtocolException: The server returned status code 422. Possible reasons include:
   - This agent has been deleted from the configuration
   - This agent is pending approval
   - There is possibly a reverse proxy (or load balancer) that has been misconfigured. See https://docs.gocd.org/21.1.0/installation/configure-reverse-proxy.html#agents-and-reverse-proxies for details.
```

##### Code snippets/Screenshots

n/a

##### Any other info

n/a

**Comment by arvindsv** [comment]
Hello! That makes sense. Would you mind opening a PR in the documentation repository for this? https://github.com/gocd/docs.go.cd/

Here's the index page which has some FAQ topics at the bottom:

https://raw.githubusercontent.com/gocd/docs.go.cd/29f76af70eed50006e9fe2607381632419c2dbeb/content/menu/index.md

You can create a new FAQ file and add it to the index here.

**Comment by arvindsv** [comment]
Since this is not a GoCD issue per-se, I'll close it.

**Comment by matthiaskraaz** [comment]
I've signed the CLA and created my very first Github pull request: https://github.com/gocd/docs.go.cd/pull/537

Could you please have a view?

**Comment by arvindsv** [comment]
@matthiaskraaz Nice first pull request! :) Congratulations. Merged.
