### ISSUE TITLE
Removing pipeline from environment does not make it available in other environment

### ISSUE THREAD

**Issue by sfuhrm** [gocd/gocd#9093]
##### Issue Type

- Bug Report

##### Summary

When removing a pipeline from one environment in `/go/admin/environments`, and then opening another environment to add this pipeline to, it is not possible.

A side reload does the trick. You can then add the pipeline to the other environment.

##### Environment

```plain
{
  "Timestamp": "2021-02-25T17:01:33+01:00",
  "Go Server Information": {
    "Version": "21.1.0 (12439-5a4959c7c4ede49165ec961b0219126cd5aa9e52)"
  },
...
```

###### Basic environment details

* Go Version: `GoCD Version: 21.1.0 (12439-5a4959c7c4ede49165ec961b0219126cd5aa9e52).`
* JAVA Version: `11.0.10`
* OS: `Linux 4.18.0-193.28.1.el8_2.x86_64`

##### Steps to Reproduce

1. Have a pipeline PIPE-A and at least two environments, lets call them ENV-A and ENV-B
2. Pipeline PIPE-A is at the moment in ENV-A
3. Remove pipeline PIPE-A from ENV-A using `/go/admin/environments`
3. Unroll/open ENV-B in the frontend to add the pipeline to
4. Pipeline PIPE-A is not available for adding in ENV-B (listed as "Unavailable pipelines" in use in ENV-A)

##### Expected Results

The pipeline should be available in ENV-B in step 4.

##### Actual Results

Pipeline is listed to be unavailable and still in use in the old environment (which is wrong).

##### Possible Fix

Reloading the `/go/admin/environments` page works.

**Comment by sriramnrn** [comment]
I'm able to reproduce this.
