### ISSUE TITLE
Need to build Ubuntu 20.04 docker image

### ISSUE THREAD

**Issue by arvindsv** [gocd/gocd#9143]
https://github.com/gocd/gocd/blob/f5d4d01eb0aa6a949d70d1314c9ad625063f6a34/buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy#L184

Maybe we can stop building 16.04?

**Comment by chadlwilson** [comment]
This was done in https://github.com/gocd/gocd/commit/ee5573a5b9db4540566972ecb61dc782ef730b9a
