### ISSUE TITLE
Config repository rules

### ISSUE THREAD

**Issue by brian-sysmirror** [gocd/gocd#9146]
In order to create a config repository, the following needs to be done.

1. Create the config repository
2. Edit the config XML
3. Add the rules section
 
<config-repo>
  <git url="/tmp/config-repo" />
  <rules>
    <allow action="refer" type="pipeline_group">*</allow>
  </rules>
</config-repo>

This is really confusing. I'd suggest one of the following options.

A) When the config repository is created, add the rules section with all permissions
B) Add the rules configuration to the config repository UI

**Comment by maheshp** [comment]
@brian-sysmirror GoCD does provide and option to configure rules through the UI while creating or updating the Config Repository. Which version of GoCD are you on, can you please check the Config Repository page and let us know if it is missing.

<img width="1052" alt="Screenshot 2021-03-22 at 10 08 31 AM" src="https://user-images.githubusercontent.com/1061051/111946859-578d3700-8b02-11eb-8bba-8ada280e58b1.png">
