### ISSUE TITLE
Create new view fails with 'Update failed because the view is out-of-date. Try refreshing the page.'

### ISSUE THREAD

**Issue by JorritSalverda** [gocd/gocd#9169]
##### Issue Type

- Bug Report

##### Summary

At least since upgrading to go.cd 21.2.0, but perhaps earlier creating new personal views stopped working. It fails with a 412 status code from the server and response body:

```
{
  "message" : "Update failed because the view is out-of-date. Try refreshing the page."
}
```

I tried to see if anything gets logged server-side at that time, but that doesn't seem to be the case.

The request body looks as follows:

```json
{
   "filters":[
      {
         "name":"Default",
         "state":[
            
         ],
         "pipelines":[
            
         ],
         "type":"blacklist"
      },
      {
         "name":"test",
         "type":"whitelist",
         "pipelines":[
            ...
         ],
         "state":[
            
         ]
      }
   ]
}
```

##### Environment

Running in Kubernetes, with our own Docker image based on `adoptopenjdk/openjdk15:alpine-jre` - see https://github.com/Travix-International/docker-gocd-server/blob/21.2.0/Dockerfile

###### Basic environment details

* Go Version: `21.2.0 (12498-16e1ac6956cd5177a99dc3fe33503661881c354f)`
* JAVA Version: `15.0.2`
* OS: `Linux 4.19.112+`

**Comment by maheshp** [comment]
Can you please clear the cookies and check if it fixes this issue?

**Comment by JorritSalverda** [comment]
Unfortunately that doesn't help.

**Comment by maheshp** [comment]
I had a quick look and was unable to reproduce this issue. 

Somebody will have to take look at it though.
