### ISSUE TITLE
SCM end-point - backed issues

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#917]
- 1) Build cause should show SCM type - SCM name, just like we do for other materials like Git. The same should be the case for material listing page, materials tab on stage details/job details page, compare pipelines.

![scm-build-cause-issue](https://cloud.githubusercontent.com/assets/6175869/6387215/4f6a9d52-bdad-11e4-8a62-56055387dc8a.png)

@srinivasupadhya mentioned that SCM type could be display name coming from plugin. However, question that needs answering, what happens if plugin goes missing ?
- 2) VSM should show an icon. Also the label before url should be SCM type and not hard coded text 'SCM'

![scm-vsm](https://cloud.githubusercontent.com/assets/6175869/6387251/20b6e622-bdae-11e4-933e-4c31811858a8.png)
- 6) Config merge issue - User A edits the url of a material. User B concurrently edits the dest directory of the material. This is probably a conflict situation, but user B gets following error -

![scm-conflict-screen](https://cloud.githubusercontent.com/assets/6175869/6796395/62481d08-d218-11e4-9916-02fc20c5135e.png)
- 7) Empty fields like 'username' and 'password' show up as environment variables in console (with some *\* value in password) which is misleading. Ideally properties not set should not show up in console as env variables

![scm-empty-fields](https://cloud.githubusercontent.com/assets/6175869/6799012/6f9fab7c-d238-11e4-921c-222c41738a62.png)
- 8) If the plugin goes missing, then navigating to materials page shows a blank page

![blank-materials-page](https://cloud.githubusercontent.com/assets/6175869/6960590/95912742-d941-11e4-8dbe-4c29915c93bc.png)

**Comment by arvindsv** [comment]
> Question: Unlike other materials (Git, Hg etc), change of SCM material name or destination directory does not cause pipeline to trigger. Should the behaviour be consistent?

Does the older behavior make sense? Why does that happen?

**Comment by arikagoyal** [comment]
Not sure why its been implemented that way

**Comment by srinivasupadhya** [comment]
> 3) Question: Unlike other materials (Git, Hg etc), change of SCM material name or destination directory does not cause pipeline to trigger. Should the behaviour be consistent ?

The behaviour for SCM plugins seems to be correct? If not let me know.

> 4) If through api, pipeline is triggered with an invalid revision, it gives following message:
```
Error while scheduling pipeline: SCM-1 [Feb-26 12:10:26]
Unable to find revision [bar-2] for material ['PluggableSCMMaterial{SCM: [url=/var/go/repos/git-repos/git-repo-2]}']
```
For git material it shows something like below:
```
Error while scheduling pipeline: SCM-1 [Feb-26 12:13:05]
Unable to find revision [fbc877d8c4480fa652f4c9fa457612efe1] for material [GitMaterial{url=/var/go/git_repo4, branch='master', submoduleFolder='null'}]
```

This happens because of [this](https://github.com/gocd/gocd/blob/7958ac8b613031660ee00f0591af792c06c0f74c/server/src/com/thoughtworks/go/server/materials/MaterialChecker.java#L52). Fixing this would mean change of message for all materials. Leaving it at that.

**Comment by arikagoyal** [comment]
Issue 1 and 7 works fine on 15.1.0(1732-6c6e0f388f6e2a)

**Comment by srinivasupadhya** [comment]
2 & 6 is pending.
