### ISSUE TITLE
Does the GOCD version 21.2.0 resolves the SSH vulnerabilities on version 21.1.0?

### ISSUE THREAD

**Issue by rpp-gocd** [gocd/gocd#9188]
Issue Type

Summary

Weak SSH algorithm were detected on version 21.1.0. were these fixed on version 21.2.0?

Weak Algorithm findings:

Key algorithms
diffie-hellman-group-exchange-sha1
diffie-hellman-group1-sha1
Encryption algorithms
aes128-ctr
aes192-ctr
aes128-gcm@openssh.com
Mac algorithms
umac-128-etm@openssh.com
umac-128@openssh.com

 Basic environment details

Go Version: 21.1.0
JAVA Version: 15.0.1
OS: Linux 3.10.0-1160.21.1.el7.x86_64
Browser vendor and version : Google chrome 89.0

**Comment by arvindsv** [comment]
GoCD doesn't embed SSH. It just uses the system SSH. Where did you find these weak algorithms? How can that be verified or reproduced?

**Comment by marques-work** [comment]
@arvindsv I think we should close this. This is likely a user error. SSH is likely whatever system their agents are on. Looks like they are running CentOS 7 or similar, which is unrelated to GoCD.

**Comment by arvindsv** [comment]
Makes sense. Closing.
