### ISSUE TITLE
go-agent exposes svn password in command line

### ISSUE THREAD

**Issue by norcnorc** [gocd/gocd#919]
When a go agent is checking out from subversion on a linux host, any user logged in to the machine can see the password being used to connect to subversion, by looking at the command line of the "svn" process.

Go should use a less insecure method of handing the password to the svn client. It could, for example, create a temporary ".subversion/auth" directory containing the password.

**Comment by norcnorc** [comment]
Specifically, [this code](https://github.com/gocd/gocd/blob/7958ac8b613031660ee00f0591af792c06c0f74c/common/src/com/thoughtworks/go/domain/materials/svn/SvnCommand.java#L261) is the problem

**Comment by norcnorc** [comment]
This may not be fixable in Go, except by implementing some expect-like automation of the interactive password prompt.

Creating a temporary .subversion/auth directory to store the credentials turns out to be rather difficult, and there doesn't seem to be any other way to hand a password to svn.

[Subversion's "project ideas" page](http://subversion.apache.org/ideas.html) includes an item to create a "credentials management tool" which could help with this. The idea originated from [this mail thread about passing credentials to svn in non-interactive contexts](http://thread.gmane.org/gmane.comp.version-control.subversion.devel/141781).

Until something like that is implemented, security-conscious Go users may want to use svn+ssh with public key authentication instead of passwords.

**Comment by arvindsv** [comment]
Thanks for the detailed follow-up. I agree with your final assessment. I'm closing this issue. If subversion introduces an easy mechanism for doing this in the future, we should definitely switch.
