### ISSUE TITLE
Please make sure docker can be executed on this agent 

### ISSUE THREAD

**Issue by nurulakbartan** [gocd/gocd#9209]
I am running docker command in gocd ci but return error 
![image](https://user-images.githubusercontent.com/81746327/114257351-9fa8c680-99e9-11eb-8202-ea25f8cc10fe.png)

OS Ubuntu 18.04 if i run command in terminal succes. how to solve it?

**Comment by sriramnrn** [comment]
Could you switch user to the go-agent (sudo su - go) and then run docker
pull?

You may need to add the go user to the docker group to give it permissions
to run.

-- Ram

**Comment by nurulakbartanjung** [comment]
after run command sudo su - go  and docker pull with chmod 666 success in local terminal, but in the agent is same error result

**Comment by nurulakbartan** [comment]
i add go user to docker group add same result

**Comment by sriramnrn** [comment]
Could you try the -D flag for debug logging?


Ram

**Comment by arvindsv** [comment]
Another interesting thing about adding a user to a group is that the current session is unaffected. Often, it needs logging-out and back in for it to take effect. In case of daemons, that might include a restart of the daemon or of the whole node / machine. Might be worth trying.
