### ISSUE TITLE
Cannot upgrade Helm chart from 1.19.3 to latest.

### ISSUE THREAD

**Issue by rayburgemeestre** [gocd/gocd#9228]
##### Issue Type

- Bug Report

##### Summary

My initial deployment was done as follows:

`helm install gocd-app gocd/gocd --version 1.19.3 --namespace gocd --set server.persistence.storageClass=gocd-app-server-data --set server.persistence.size=200Gi`

Upgrading it with broke my CI:

`helm upgrade gocd-app gocd/gocd -n gocd`

I was able to rollback:

`helm rollback gocd-app -n gocd`

##### Environment

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4+k3s1", GitCommit:"838a906ab5eba62ff529d6a3a746384eba810758", GitTreeState:"clean", BuildDate:"2021-02-22T19:49:27Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

##### Steps to Reproduce

I managed to narrow the problem down, by updating to each version provided by: `helm search repo gocd/gocd --versions`

```
[...]
helm upgrade gocd-app gocd/gocd -n gocd --version 1.22.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.23.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.24.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.25.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.26.0
helm upgrade gocd-app gocd/gocd -n gocd --version 1.27.0  # This is the last one that doesn't fail.
helm upgrade gocd-app gocd/gocd -n gocd --version 1.28.0  # This upgrade fails
```

This one succeeds:

```
Press ENTER or type command to continue
NAME    	NAMESPACE	REVISION	UPDATED                               	STATUS  	CHART      	APP VERSION
gocd-app	gocd     	14      	2021-04-21 13:20:18.88871596 +0000 UTC	deployed	gocd-1.27.0	20.4.0     
```

This one fails:

```
root@deskmini:/mnt2/NAS/kube/gocd# helm list -n gocd
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART      	APP VERSION
gocd-app	gocd     	13      	2021-04-21 12:35:43.982578584 +0000 UTC	deployed	gocd-1.28.0	20.5.0   
```

##### Expected Results

Upgrade doesn't crash gocd server

##### Actual Results

```
root@deskmini:/mnt2/NAS/kube/gocd# kubectl get pod -n gocd
NAME                               READY   STATUS             RESTARTS   AGE
gocd-app-server-65f5b6cb7f-dbwww   0/1     CrashLoopBackOff   9          42m
```
See the attached log for the full output.

##### Log snippets

See attached file.

I suspect this could be the root cause:

```
jvm 1    | It appears that you are upgrading your GoCD server and the current database is not compatible with GoCD 20.5.0 and above.Please see https://docs.gocd.org/20.5.0/installation/upgrade_to_gocd_20.5.0.html for instructions on upgrading this instance of GoCD.
```

##### Any other info
[gocd.log](https://github.com/gocd/gocd/files/6351129/gocd.log)

**Comment by kritika-singh3** [comment]
You are right @rayburgemeestre, in GoCD 20.5.0, there were changes to its database implementation. Please go through this [doc](https://docs.gocd.org/20.5.0/installation/upgrade_to_gocd_20.5.0.html) for upgradation of GoCD post 20.5.0.
Hope this helps!

**Comment by rayburgemeestre** [comment]
Thanks @kritika-singh3!
Took me a few days to find the time to do it, but I managed to go through with the update after following the steps from that doc!
I decided to keep it running with H2.
Running the latest Helm chart now :tada:

**Comment by sheetalsharma26** [comment]
> Thanks @kritika-singh3!
> Took me a few days to find the time to do it, but I managed to go through with the update after following the steps from that doc!
> I decided to keep it running with H2.
> Running the latest Helm chart now 🎉

@rayburgemeestre @kritika-singh3 can you guide me how to migrate db of gocd running in eks  as part of version upgrade, i don't find document useful for kubernetes.
