### ISSUE TITLE
Logs for Successful and Failed deployment  are not logging.

### ISSUE THREAD

**Issue by rpp-gocd** [gocd/gocd#9230]
Hi ,

We are encountering a logging issue on our GoCD. Logs for Successful and Failed deployments  are not logging on local server. 

do you know any fix on this? or do you know any other directories for logging? 

###### Basic environment details

Go Version: 21.2.0
JAVA Version: 15.0.1
OS: Linux 3.10.0-1160.21.1.el7.x86_64
Browser vendor and version : Google chrome 89.0

Thanks,

**Comment by sriramnrn** [comment]
On Thu, Apr 22, 2021 at 5:51 PM rpp-gocd ***@***.***> wrote:

> Hi ,
>
> We are encountering a logging issue on our GoCD. Logs for Successful and
> Failed deployments are not logging on local server.
>
> do you know any fix on this? or do you know any other directories for
> logging?
>

The stdout/stderr for each job are sent to the server and can be seen in
the console tab and the artifacts tab for each job. See this for an
example:
https://build.gocd.org/go/tab/build/detail/build-linux/5473/build-server/1/Rspec-runInstance-1

If your tool that performs a deployment happens to log to a file, then you
can mark that file as an artifact and show it's contents in a subtab tab.

**Comment by marques-work** [comment]
@rpp-gocd as @sriramnrn indicated, stdout and stderr output is captured by console logs. If your deployment scripts are _not_ outputting to these streams, where are you writing logs to?

If your scripts are dumping output to an arbitrary but known log path, then you should capture that log file as a build artifact so you can view it for each build.

See here: https://docs.gocd.org/current/configuration/managing_artifacts_and_reports.html
