### ISSUE TITLE
The api endpoint /go/api/jobs/scheduled.xml returns 404

### ISSUE THREAD

**Issue by alexzose** [gocd/gocd#9253]
##### Issue Type

- Bug Report

##### Summary

The api endpoint /go/api/jobs/scheduled.xml returns 404

###### Basic environment details

* Go Version:  21.2.0 (12498-16e1ac6956cd5177a99dc3fe33503661881c354f)
* JAVA Version: 15.0.2
* OS: Linux 4.4.0-170-generic

##### Steps to Reproduce

It happens on both new installations, and old (migrated ones).
As described in the docs:
curl 'https://ci.example.com/go/api/jobs/scheduled.xml' \
      -u 'username:password'
(of course the values are changed to resemble my setup)

##### Expected Results
An xml file with the scheduled jobs

##### Actual Results
404 error and no output

**Comment by kritika-singh3** [comment]
The URL you mentioned @alexzose is the older one which was deprecated in GoCD version [20.6.0](https://api.gocd.org/21.2.0/#changes-in-20-6-0).
The new URL is `/go/api/feed/jobs/scheduled.xml`. Please find the docs [here](https://api.gocd.org/21.2.0/#scheduled-jobs).

I'll close the ticket. Please message if the said URL does not work.

**Comment by arvindsv** [comment]
Looks like an old section of the doc was left behind, with the old API call. I'm removing it.
