### ISSUE TITLE
Timestamp issue

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#930]
The Go server and agent are in different time zones. See the console output below. Note there is difference in time here. To me it appears that the time on the right hand side is coming from server. Needs to be checked

![timestamp_issue](https://cloud.githubusercontent.com/assets/6175869/6478678/11d0cb28-c25e-11e4-9a66-a756b9335e91.png)

**Comment by ketan** [comment]
@jyotisingh - I verified this issue, and it is fixed
