### ISSUE TITLE
Constantly increasing number of threads

### ISSUE THREAD

**Issue by cgrim-cz** [gocd/gocd#9305]
##### Issue Type

- Bug Report

##### Summary

The number of threads is constantly increasing in our GoCD instance, which means that we can not log in under go user after a while.
At the beginning we had default nproc soft limit set on 4 096 and GoCD had around 12 000 active threads. We increased the limit on 16 384 yesterday and today GoCD is on 23 742 active threads and it is still increasing.

###### Basic environment details

* Go Version: `21.2.0` (but the same behavior was also in `20.10.0`)
* JAVA Version: `AdoptOpenJDK (build 15.0.2+7, mixed mode, sharing)`
* OS: `CentOS Linux release 7.9.2009`
* Linux kernel: `3.10.0-1160.21.1.el7.x86_64`
* HW: `Xen virtual machine with 450 GB RAM and 16 virtual CPUs`

###### Additional Environment Details

Here are some details from _/go/api/support_:
```json
  "Config Statistics": {
    "Valid Config": {
      "Number of pipelines": 634,
      "Number of environments": 9,
      "Number of agents": 0,
      "Number of unique materials": 329,
      "Number of schedulable materials": 329
    },
    "Security": {
      "Plugins": [
        {
          "Password File Authentication Plugin for GoCD": true
        },
        {
          "LDAP Authentication Plugin for GoCD": true
        }
      ],
      "Enabled": true
    }
  }
```
```json
"Thread Count": {
      "Current": 23887,
      "Total": 1717634,
      "Daemon": 121,
      "Peak": 23889
    }
```

##### Steps to Reproduce

We tried the same version of GoCD with the same configuration but only with one pipeline and one agent and threads count was still the same.

##### Expected Results

We assume that the number of threads will fluctuate and not constantly increase. 
Or is 24 thousands of active threads normal for 634 pipelines?

##### Log snippets

See the attached thread dump, where are `pool-...-thread-1` threads from `ScheduledThreadPoolExecutor` and these are the ones whose number is constantly increasing.
[threaddump.zip](https://github.com/gocd/gocd/files/6465073/threaddump.zip)

**Comment by cgrim-cz** [comment]
The next day our GoCD is on it with threads like this:
```json
    "Thread Count": {
      "Current": 42076,
      "Total": 2725698,
      "Daemon": 101,
      "Peak": 42095
    }
```

**Comment by arvindsv** [comment]
Not sure what all those pool threads are. For comparison, here are some statistics from a similarly sized server.

```
...
 "Config Statistics": {
    "Valid Config": {
      "Number of pipelines": 586,
      "Number of environments": 4,
      "Number of agents": 0,
      "Number of unique materials": 593,
      "Number of schedulable materials": 587
    },
...
    "Uptime": 1990328928,
    "Uptime (in Time Format)": "[About 552 hours, 52 minutes, 8 seconds]",
    "Spec Name": "Java Virtual Machine Specification",
    "Spec Vendor": "Oracle Corporation",
    "Spec Version": "15",
    "Input Arguments": [
      "-Xms512m",
      "-Xmx1024m",
...
  "Thread Information": {
    "Thread Count": {
      "Current": 201,
      "Total": 35078924,
      "Daemon": 131,
      "Peak": 235
    },
    "DeadLock Threads": {},
...
```

**Comment by cgrim-cz** [comment]
Only 201 threads? That's interesting and nice. While we are on 127024 threads after 6 days. Thanks to that _/go/api/support_ shows _504 Gateway Time-out_ and pipelines start to fail on:
```[15.030s][warning][os,thread] Failed to start thread - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached.```

Is there anything I can check on our GoCD installation?

**Comment by arvindsv** [comment]
I checked your thread dump with https://fastthread.io/ and could see nothing too useful (apart from the fact that over 20000 threads are waiting for something). I'd start with looking at the the GoCD configuration (wrapper-properties.conf etc) and logging configuration, to see if any properties have been changed. Something is definitely off. A normal GoCD server's thread counts shouldn't be increasing like that.

**Comment by arvindsv** [comment]
Could you also check if you have a timer trigger / cron expression set up starting with `*` or something? I'm just thinking of wild possibilities for this weird behavior.

**Comment by sriramnrn** [comment]
Could you provide a pastebin of "jstack -l JAVA_PID > jstack.out" ?

-- Ram

**Comment by cgrim-cz** [comment]
@arvindsv Thanks for the input. I'll compare configuration with the clean install and experiment with off/on.
As for timers, we have around 40 timers but none of them starts with *. Timer with the highest frequency is probably this one: `"0 0/5 * * * ? *"` and we have also variations with exceptions like this `"0 0/5 0-3,5-23 * * ? *"`

@sriramnrn I'll provide that stack tomorrow. GoCD crashed an hour ago and now there are not that many threads.

**Comment by arvindsv** [comment]
> As for timers, we have around 40 timers but none of them starts with *. Timer with the highest frequency is probably this one

Ok, thanks. That's fine. I was wondering what reasons there could be for that many threads to exist.

@sriramnrn The threaddump.zip attached in the first comment seems to be the output of `jstack -l` or `kill -3`, but it doesn't have the GC part at the end.

**Comment by cgrim-cz** [comment]
The first dump was from _VisualVM_. Here is a dump from `jstack`: 
[jstack.out.zip](https://github.com/gocd/gocd/files/6506556/jstack.out.zip)

**Comment by cgrim-cz** [comment]
The problem is solved. I went throught all plugins and discovered, that one of them (docker-elastic-agents plugin) has version which has not been released publicly and realised that former colleague did customization there. And just that update did this strange behavior.

Thank you guys for all your time and I'm very sorry that I reported a problem that is actually our fault.

**Comment by arvindsv** [comment]
No problem. Thank you for following up and helping out others who might face a similar problem. :)
