### ISSUE TITLE
error run gocd agent in docker

### ISSUE THREAD

**Issue by andrequeiroz2** [gocd/gocd#9391]
##### Issue Type
- Bug Report

##### Summary
 error gocd agent

##### install docker image
docker run -d -p8153:8153 -p8154:8154 gocd/gocd-server:v21.2.0
docker run -d -e GO_SERVER_URL=... gocd/gocd-agent-ubuntu-18.04:v21.2.0

error in gocd-agent

$ exec /usr/local/sbin/tini -g -- /go/bin/go-agent console
Running go-agent...
wrapper  | --> Wrapper Started as Console
wrapper  | Java Service Wrapper Standard Edition 64-bit 3.5.41
wrapper  |   Copyright (C) 1999-2019 Tanuki Software, Ltd. All Rights Reserved.
wrapper  |     http://wrapper.tanukisoftware.com
wrapper  |   Licensed to ThoughtWorks for GoCD Agent
wrapper  | 
wrapper  | Launching a JVM...
jvm 1    | WrapperManager: Initializing...
jvm 1    | [Thu May 27 19:00:10 GMT 2021] Starting process: 
jvm 1    | [Thu May 27 19:00:10 GMT 2021]   Working directory    : /go
jvm 1    | [Thu May 27 19:00:10 GMT 2021]   Application arguments: [-serverUrl, ...]
jvm 1    | [Thu May 27 19:00:10 GMT 2021]            GoCD Version: 21.2.0-12498
jvm 1    | [Thu May 27 19:00:10 GMT 2021]            Java Version: 15.0.2
jvm 1    | [Thu May 27 19:00:10 GMT 2021]        Operating System: Linux(5.4.0-73-generic)
jvm 1    | -serverUrl is not a valid url
jvm 1    | Usage: java -jar agent-bootstrapper.jar [options]
jvm 1    |   Options:
jvm 1    |     -help
jvm 1    |       Print this help
jvm 1    |     -rootCertFile
jvm 1    |       The root certificate from the certificate chain of the GoCD server (in 
jvm 1    |       PEM format)
jvm 1    |   * -serverUrl
jvm 1    |       The GoCD server URL. Example: http://gocd.example.com:8153/go
jvm 1    |     -sslCertificateFile
jvm 1    |       The X509 certificate for mutual TLS.
jvm 1    |     -sslPrivateKeyFile
jvm 1    |       The private key for mutual TLS.
jvm 1    |     -sslPrivateKeyPassphraseFile
jvm 1    |       The file containing the passphrase for decoding the SSL private key.
jvm 1    |     -sslVerificationMode
jvm 1    |       The SSL verification mode.
jvm 1    |       Default: FULL
jvm 1    |       Possible Values: [FULL, NONE, NO_VERIFY_HOST]
wrapper  | <-- Wrapper Stopped

**Comment by bschulz87** [comment]
Try again with a valid serverUrl

**Comment by chadlwilson** [comment]
Yeah, as suggested above and the log message `jvm 1 | -serverUrl is not a valid url` you need to set `GO_SERVER_URL` to be a valid URL. That should solve this for you.
