### ISSUE TITLE
Error starting one of my agents

### ISSUE THREAD

**Issue by maufonfa** [gocd/gocd#9468]
##### Issue Type

- Bug Report

##### Summary

I have 4 agents in the same VM. go-agent, go-agent-1, go-agent-2, and go-agent-3. I'm having a problem starting go-agent, and the error message is: 

Failed to access the script using an absolute path. Insufficient permissions may prevent the user "go" from traversing one of the folders. Please check the following permissions:
drwxr-xr-x  30 root root 4096 Jun 23 06:35 /
drwxr-xr-x  11 root root 4096 Aug 22  2019 //usr
drwxr-xr-x 172 root root 4096 Sep 16  2020 //usr/share
drwxrwxrwx   7 root root 4096 Apr 21  2020 //usr/share/go-agent
drwxrwxrwx   2 root root 4096 Jun 30 10:59 //usr/share/go-agent/bin

All other agents started correctly. I don't know what can be causing this issue.

##### Environment

I'm using Ubuntu 18.04, with 4 agents as I mentioned.

###### Basic environment details

* Go Version: 20.1.0 (11114-f2c1771e333ea92dae82cd78d2efa1310c1086f0) for both server an agent
* JAVA Version: 13.0.1
* OS: Linux 4.15.0-96-generic

##### Steps to Reproduce

1. systemctl start go-agent or /etc/init.d/go-agent start

##### Expected Results
Agent should start as the rest are doing

##### Actual Results
First agent not starting

**Comment by arvindsv** [comment]
I think there is an agent directory in `/var/lib/go-agent-1`. Can you see if the permissions there are right?
