### ISSUE TITLE
Subordinate Git Materials not updated when "Poll for new changes" unchecked / autoUpdate=false 

### ISSUE THREAD

**Issue by birchb1024** [gocd/gocd#948]
Scenario:
Pipeline:
      Materials:
            Git repo 'git_demo' "Poll for new changes" checked.
            Git repo 'git_demo_lib' "Poll for new changes" unchecked

According to the documentation *"If autoUpdate is set to false then Go will not poll the repository for changes. Instead it will check for changes only when you trigger a pipeline that contains this material"*. This is not happening. When the pipeline is triggered by a new commit in  'git_demo' the  'git_demo_lib' repository is not fetched or pulled resulting in out-of-date code in the pipeline.   This is about as popular as a rattlesnake in a lucky dip.

The workaround is to always trigger the pipeline manually.  Or force pull in the first stage via scripts.

Details:
* Gocd 14.1 installed from rpm.
* GitLab 6.8.1 3197990
* OS: RedHat 6.5

**Comment by srinivasupadhya** [comment]
Are you trying to implement [this](https://groups.google.com/d/topic/go-cd/rBouLywo3a4/discussion)?

**Comment by birchb1024** [comment]
Nope. Single pipeline.

**Comment by birchb1024** [comment]
Set "Poll for new changes" checked but Blacklist = /* seems to work.
But this issue is either a bug in the documentation or the code. 
You choose.

**Comment by srinivasupadhya** [comment]
I agree. Documentation could be improved. The case in the [forum thread](https://groups.google.com/d/topic/go-cd/rBouLywo3a4/discussion) could also be added.

**Comment by arvindsv** [comment]
Closing this. Created an issue in documentation repo for this.

**Comment by selimekizoglu** [comment]
```
<materials>
  <git url="http://example.org/project.git" dest="project" materialName="project.git" />
  <git url="http://example.org/config.git" dest="config" autoUpdate="true" materialName="config">
    <filter>
      <ignore pattern="/*" />
    </filter>
  </git>
</materials>
```

When I push a commit to config.git, the pipeline gets triggered. Go version: 14.4.0(1356-86064ef5ee28e0). Am I missing something?

**Comment by birchb1024** [comment]
Delete autoUpdate attribute ?

**Comment by arvindsv** [comment]
```/*``` says ignore all files at the first level (I'm not exactly sure about the leading slash). You might want to try ```*``` and ```**/*```.

```*``` should work for files at first level, even if ```/*``` doesn't.

```**/*``` should ignore all files, at all levels.

**Comment by selimekizoglu** [comment]
@birchb1024 Isn't the default value true?

@arvindsv **/* worked, thanks!
