### ISSUE TITLE
Missing download links for 20.4.0

### ISSUE THREAD

**Issue by MassiveHiggsField** [gocd/gocd#9485]
##### Issue Type

- Documentation Report

##### Summary

I have to upgrade an old gocd installation. In the documentation it states i have to upgrade to 20.4.0 first, see: https://docs.gocd.org/current/installation/upgrade_to_gocd_20.5.0.html . But there seems to be no way to download that version anymore. The supported versions go back to 20.6.0 (see https://www.gocd.org/download/#debian), while the older unsupoorted versions end at 19.12.0 (see https://gocd.github.io/gocd-plugin-info/gocd-releases ).

**Comment by arvindsv** [comment]
@MassiveHiggsField Thanks for bringing this up. https://gocd.github.io/gocd-plugin-info/gocd-releases should now be updated. Closing this, but can be reopened if it's wrong.

**Comment by MassiveHiggsField** [comment]
awesome thanks for the quick reply and adding the files
