### ISSUE TITLE
Timeout cancels job waiting for agent

### ISSUE THREAD

**Issue by matthiaskraaz** [gocd/gocd#9523]
##### Issue Type

Bug Report

##### Summary

Setting the job timeout in the server configuration leads to job being cancelled while the job is waiting for an agent.

###### Basic environment details

* Go Version: 21.1.0
* JAVA Version: 15.0.1
* OS: Linux 5.8.0-59-generic

##### Steps to Reproduce

1. Set job timeout in server configuration to 5 minutes
2. Configure pipeline with long-running jobs so that at least one job waits more than 5 minutes for agent
3. Job gets cancelled by GoCD after waiting for agent for 5 minutes

##### Expected Results

As documented: "cancel jobs that do not generate any console output for a period of time", see https://docs.gocd.org/current/configuration/job_timeout.html.

##### Actual Results

Job gets cancelled while waiting for an agent.

##### Possible Fix

Start timeout when job starts.

**Comment by chadlwilson** [comment]
I believe this is by design - the docs also include "it was not assigned an agent" as a condition in the section below that which you quote.

> Timeout after a period of inactivity : A job will be cancelled if:
> -   it did not have any console output for a period of time (in minutes)
> -   it was not assigned an agent

... although I agree the wording could be clarified in the preface.
 
Do you have a use case for ability to set these two timeouts independently (enhancement), or just surprised at the behaviour from reading the docs?

**Comment by matthiaskraaz** [comment]
My scenario: 

Some of the build agents have to run Windows and sometimes the build stalls on them. This costs us quite some money, as we use AWS compute resources. It also means, developers get no feedback about bad commits. As all build jobs constantly produce output, I'd like to set a timeout like 1 minute or so.

On the other hand, I have a lot of pipelines for multiple branches: trunk plus all software versions still under maintenance (nearly 10 years back). I have enough agents to build ONE branch at once. 

A build of a single branch takes 30-40 minutes. If multiple branches get a commit, jobs have to wait for an hour or so for an agent. This is expected and should not lead to a timeout. As this rarely happens, it makes no sense to invest in more agents.

I have set the timeout to 60 minutes to accomodate for multi-brach commits and still keep costs and missing feedback down when a build stalls. However this is far from ideal IMO.

**Comment by chadlwilson** [comment]
Fair enough. This seems to be a feature that is not currently available, however.

I am curious: what type of output are these jobs producing when they are "stalled", I wonder? 

And what type of build tools are they invoking as the wrapping process? Often tools have a way to set their own timeouts, or as an alternate workaround if using simple command/script tasks could you perhaps wrap the tasks in some kind of timeout scripting? (e.g `timeout x myCommand myArg` on *nix or `start myCommand myArg; Wait-Process -TImeout x myCommand` on Windows/Powershell)

**Comment by whale001** [comment]
Still relevant, GoCD 22.1.0
