### ISSUE TITLE
Please provide some way to stop new windows from being opened

### ISSUE THREAD

**Issue by iamnoah** [gocd/gocd#9526]
It is remarkable to me that in 2021, I have a piece of software with RESTful URLs that will not let me choose to open, for example, console output in the same window. This is extremely annoying. I do not want 12 tabs for GoCD opened, let me choose if I want to open something in a new window or the same window. I am just trying to drill down into a pipeline to see what happened and I have to open a new window for that? Why?! This is so frustrating. Give me a choice!

**Comment by abvm659** [comment]
Why it was removed from To do? Every single click in gocd opens new window/tab it is absolutely ridiculous ..
