### ISSUE TITLE
Incorrect information in cctray feed for a new stage/job created for a given pipeline

### ISSUE THREAD

**Issue by arikagoyal** [gocd/gocd#954]
Not sure if its an issue, but following is my observation -

1) Create a pipeline. The pipeline has run some 18 times so the pipeline label value is 18 at present
2) Create a new stage/job called 'defaultStage3/defaultJob3'
3) While the new stage is in building status for the first time, following is the entry i see in cctray. Note that the 'lastBuildLabel' and 'lastBuildTime' text below seems to be incorrect ( actually not sure where the last buildtime is getting picked from)

```xml
<Project name="Two :: defaultStage3" activity="Building" lastBuildStatus="Success" lastBuildLabel="1" lastBuildTime="2015-03-12T16:12:26" webUrl="http://10.4.1.232:8153/go/pipelines/Two/19/defaultStage3/1"/>
<Project name="Two :: defaultStage3 :: defaultJob3" activity="Building" lastBuildStatus="Success" lastBuildLabel="1" lastBuildTime="2015-03-12T16:12:26" webUrl="http://10.4.1.232:8153/go/tab/build/detail/Two/19/defaultStage3/1/defaultJob3"/>
```

4) Things however become fine once the stage has finished building showing the new details as below -

```xml
<Project name="Two :: defaultStage3" activity="Sleeping" lastBuildStatus="Success" lastBuildLabel="19" lastBuildTime="2015-03-17T16:34:43"* webUrl="http://10.4.1.232:8153/go/pipelines/Two/19/defaultStage3/1"/>
<Project name="Two :: defaultStage3 :: defaultJob3" activity="Sleeping" lastBuildStatus="Success" *lastBuildLabel="19" lastBuildTime="2015-03-17T16:34:43" webUrl="http://10.4.1.232:8153/go/tab/build/detail/Two/19/defaultStage3/1/defaultJob3"/>
```

**Comment by arvindsv** [comment]
This is, sort of, by design. At least, there is [explicit code](https://github.com/gocd/gocd/blob/master/server/src/com/thoughtworks/go/domain/activity/ProjectStatus.java#L40) for this. I think the last build time is set to the server start time (don't ask). Can you check whether that is true?

If so, since this is a corner case, which fixes itself, I'd close this.

**Comment by arikagoyal** [comment]
Yes you are right. Alright i will close this issue.
