### ISSUE TITLE
Avoid Docker Hub rate limiting during GoCD's own builds

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd#9556]
##### Issue Type

- Feature enhancement

##### Summary

Currently GoCD builds are getting rate limited by Docker Hub on image pulls causing build failures if one runs too many (e.g [here](https://build.gocd.org/go/tab/build/detail/build-linux/5511/build-non-server/1/FastTests-runInstance-1) and [here](https://build.gocd.org/go/tab/build/detail/installers/2570/docker/2/docker-server)).

My understanding of the reading at https://www.docker.com/blog/expanded-support-for-open-source-software-projects/ is that GoCD should qualify as an "Open Source Project". Perhaps it has already qualified as such under [this user](https://hub.docker.com/u/gocd), however it's not identifying itself as such during these Gradle triggered builds. 

##### Expected Results

Image pulls should ideally not be subject to the Docker Hub rate limits.

##### Actual Results

Image pulls are getting rate limited.

##### Possible Fix

- if GoCD is already an approved Open Source org per Docker; configure agents to be able to logon as the appropriate user to avoid getting rate limited
- possibly need to raise something at https://github.com/gocd/steering if there is some work necessary to become approved

**Comment by arvindsv** [comment]
The GoCD organization in DockerHub is part of a paid team plan. But, I'm not sure what else needs to happen. Maybe a specific user needs to be logged in before a pull?

<img width="930" alt="2021_08_05_19-14-33" src="https://user-images.githubusercontent.com/172235/128400587-34034c26-fb81-4f05-8341-a3fd5c4f48a4.png">

**Comment by chadlwilson** [comment]
Yeah, I believe it'd have to be `docker login`d on the agents using a personal access token/API key to get around the rate limiting.

I guess that would need to be done on the pipelines which eventually push the images to Docker Hub already.

**Comment by chadlwilson** [comment]
I haven't seen this problem since I originally created it, so happy to leave it and assume something else fixed it. I also note we have our own Nexus - not sure if that is acting as a mirror though.
