### ISSUE TITLE
Job Timeout does not work for jobs that have been assigned but not started

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#956]
When a job has been assigned to an agent whose status is "lost contact" the job never times out irrespective of the settings of "job timeout".

I do not know if this is by design or not. I suspect the job timeout feature was really designed to cancel jobs that have started but never complete due to a handing process etc. 

There needs a mechanism for jobs that have been scheduled to time out at some point or for the stage to be cancelled. Otherwise the stage will wait indefinitely and subsequent runs of the pipeline will not occur.

Currently I am having to do this manually in the UI which is painful.

I am happy to do this with APIs if there is a way however I cannot see one.

**Comment by arvindsv** [comment]
Job timeout is actually "job run timeout", and so it does not apply. So, there is a need to introduce a "job assignment timeout", I think. Marking this a bug.

**Comment by reidca** [comment]
OK, I will raise a new issue for job assignment timeout

**Comment by reidca** [comment]
#967
