### ISSUE TITLE
API method for renaming agent

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#958]
The existing agent API does not allow agents to be renamed.

This can be achieved by modifying the hostname property in the XML configuration of the agent however this is entirely a manual task.

It would be great to get a new method added to the Agent Api to allow the agent to be given a semantic name.

#124

**Comment by ketan** [comment]
I've picked this up to implement.

**Comment by zabil** [comment]
Use a PATCH instead of PUT for doing this. 
More information here [June 3 2015 4:57 PM](https://gitter.im/gocd/gocd?at=556ee4bf463d0c7c066dd838)

**Comment by ketan** [comment]
> Use a PATCH instead of PUT for doing this.

Opened #1183 to address this, also updating docs directly

**Comment by ketan** [comment]
@zabil close #959 as well?
