### ISSUE TITLE
Api method for assigning resources and environments to agents

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#959]
Would be useful to have API methods to assign resources and environments to agents.

Looking at the documentation (http://www.go.cd/documentation/user/current/api/agent_api.html)  I don't see anyway to do this.

**Comment by ketan** [comment]
I've picked this up to implement.

**Comment by zabil** [comment]
Verified on experimental release15.2.0-2149 (d0369fb00f85d395f6534a3a434b7a612d286f7b)
