### ISSUE TITLE
Environments page should have a Table of Contents style list for ease of visualisation and navigation

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#965]
It is quite difficult to see how many environments there are any to navigate to them.
As far as I know there is no way to list the environments without scrolling down to each one in turn which is time consuming and fiddly when there are lots of assigned pipelines.

A list of available environments at the top of the page as well as the ability to navigate to them quickly would be very useful.

**Comment by GaneshSPatil** [comment]
Building pipeline's information was removed from the environments page causing the environments page to only contain config related information and inturn making it easier to see all the available environments.
