### ISSUE TITLE
Api method for managing environments required

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#966]
There are no API methods available for managing environments (add/remove/edit) or for assigning agents or pipelines to environments.

Adding environment variables would be a bonus.

**Comment by arvindsv** [comment]
There was a [config API discussion](https://groups.google.com/d/topic/go-cd-dev/UjE9azB72Bc/discussion) recently on the mailing list. Without contributions from people in the community, this is going to get done slowly, if ever. It's useful, I agree. But, votes for this should either come in the form of code or influencing people in the community to pick up and implement features. :) There are some people doing that (submitting RFCs and implementing features), but no one has picked up anything related to this yet.

**Comment by zabil** [comment]
Refer #1100 for API specs

**Comment by hanej** [comment]
This is critical for us to automate the majority of our day-to-day Go work.  If we could assign environment "owners" this wouldn't be as high of a priority but making an admin responsible for development environments takes a lot of time away from more important activities.

**Comment by herby** [comment]
We need it, too. Pls, add the API. Thanks.

**Comment by arvindsv** [comment]
Happening here: https://github.com/gocd/gocd/pull/2207. @GaneshSPatil, can you please close this once it is merged? Thanks!
