### ISSUE TITLE
Require Job Assignment Timeout

### ISSUE THREAD

**Issue by reidca** [gocd/gocd#967]
When a job has been assigned to an agent whose status is "lost contact" the job never times out and the pipeline will wait indefinitely.

There needs to be a mechanism for jobs that have been scheduled to time out at some point or for the stage to be cancelled. Otherwise the stage will wait indefinitely and subsequent runs of the pipeline will not occur.

Currently I am having to do this manually in the UI which is painful.

**Comment by arvindsv** [comment]
Moving to 18.3 to consider it in 18.3 or 18.4. We need to do some digging to see what's happening, and whether we need to introduce a new property.
