### ISSUE TITLE
Bug with update config repo, browser cacheable? 

### ISSUE THREAD

**Issue by marcosmcp** [gocd/gocd#9692]
Hi, Peoples!

I'm having problem updating 'config repo'

Although the update is taking a long time, about 45 minutes,

I realized that if I enter an anonymous browser tab after 10~15 minutes the process is already finished.

I did some searching around here and didn't find anything about browser caching or anything related.

Has anyone had the same problem?

**Comment by chadlwilson** [comment]
Interesting. Perhaps there is a lost event back to the browser to say that it was completed. I have seen some strange behaviour as a user before with things looking "stuck" on config repo updates, but never looked in detail or suspected browser caching.

- If you refresh the page in the original browser was the state updated, or ONLY via an anonymous tab?
- is the failure repeatable?
- can you share your browser and GoCD version?
