### ISSUE TITLE
provide ability to put Go Server in read only mode

### ISSUE THREAD

**Issue by srinivasupadhya** [gocd/gocd#972]
This story is mainly to avoid any config/database updates while the Go Server continues to respond to requests & provide status data etc.

Done as part of this story:
* all timer threads are turned off. so material updates, scheduling etc. will not happen.
* all non-get requests (post, put, delete etc.) except the user login are turned off
* the `submit` buttons for most forms are disabled. there could be a few which are not disabled. its ok since the request will fail due to non-get requests being turned off.

this could be usefull in many situations.

**Comment by arikagoyal** [comment]
Works fine on 15.1.0(1813-b9604e0416eff3)
