### ISSUE TITLE
Move a pipeline from a pipeline group to another pipeline group

### ISSUE THREAD

**Issue by bamdadd** [gocd/gocd#979]
Hi,

Currently if I want to move a pipeline from a pipeline group to another one I either have to clone the pipeline with a different name, or modify the XML config.

A better way of moving pipeline groups would be great. something like a drag and drop of the pipelines on the admin view.

Thanks,
Bamdad

**Comment by srinivasupadhya** [comment]
Is this what you are looking for?

![screen shot 2015-03-24 at 8 05 37 pm](https://cloud.githubusercontent.com/assets/1587661/6804007/33cfd076-d261-11e4-95f6-16862cdf4374.png)

**Comment by bamdadd** [comment]
Yes, Thats it. Sorry for raising an issue for this.

However another issue still exists with ordering a pipelines within a pipeline group.
