### ISSUE TITLE
Cannot use a Template with two or more materials

### ISSUE THREAD

**Issue by rabagast** [gocd/gocd#986]
I have a template with two materials, A and B. 
When I try to create a new pipeline and use the template the wizard will ask for one material. If I input A the wizard will complain that the template uses material B and that I have not provided B. If I change the material in the wizard to B, the wizard will not create the pipline since I haven't provided material A. 

According to @arvindsv  the only way to use such a template currently is to edit the XML.

**Comment by ciotlosm** [comment]
As far as I know templates don't have material, they just define stages and make use of Pipeline parameters. Are you sure you're using templates?

**Comment by rabagast** [comment]
I can't reproduce until after easter, but it is two Fetch Artifact tasks in
the template  that point to different pipeline outputs. Does that make
sense?
 31. mar. 2015 13.52 skrev "ciotlosm" <notifications@github.com>:

**Comment by arvindsv** [comment]
From what I understood from @rabagast's message on IRC was that the setup contained two fetch artifact tasks, from two different pipelines, which were parameterized. That's where the expectation of two materials came from. I thought the config was something like this:

```
  <templates>
    <pipeline name="UsesTwoMaterials">
      <stage name="defaultStage">
        <jobs>
          <job name="defaultJob">
            <tasks>
              <fetchartifact pipeline="p1" stage="p1_s1" job="p1_s1_j1" srcdir="abc">
                <runif status="passed" />
              </fetchartifact>
              <fetchartifact pipeline="p2" stage="p2_s1" job="p2_s1_j1" srcdir="dfdf">
                <runif status="passed" />
              </fetchartifact>
              <exec command="ls" />
            </tasks>
          </job>
        </jobs>
      </stage>
    </pipeline>
  </templates>
```

However, with this config, it is allowing me to create the pipeline. Which means, it is probably related to parameterizing of the pipeline names in the fetch artifact tasks.

**Comment by arvindsv** [comment]
Ok, I think this config fails:

```
<templates>
  <pipeline name="UsesTwoMaterials">
    <stage name="defaultStage">
      <jobs>
        <job name="defaultJob">
          <tasks>
            <fetchartifact pipeline="#{Pipeline1}" stage="p1_s1" job="p1_s1_j1" srcdir="abc">
              <runif status="passed" />
            </fetchartifact>
            <fetchartifact pipeline="#{Pipeline2}" stage="p2_s1" job="p2_s1_j1" srcdir="dfdf">
              <runif status="passed" />
            </fetchartifact>
            <exec command="ls" />
          </tasks>
        </job>
      </jobs>
    </stage>
  </pipeline>
</templates>
```

I think this is the same as the issue mentioned in [this thread](https://groups.google.com/d/topic/go-cd/3yJ-oy_es4Y/discussion) in the mailing list.

**Comment by rabagast** [comment]
Thanks Aravind.

Submitting a half detailed issue before leaving the computer for two weeks
might be bad form, sorry for that.
31. mar. 2015 15.18 skrev "Aravind SV" <notifications@github.com>:

**Comment by arvindsv** [comment]
> Submitting a half detailed issue before leaving the computer for two weeks
might be bad form, sorry for that.

Ha ha. It's fine. Enjoy your time away.

**Comment by richard-hulm** [comment]
I've hit against the same issue! Would be brilliant to be able to easily template these pipelines which fetch artefacts from many upstream pipelines.

For now we've been updating one pipeline, then re-creating (through a delete & clone) all the similar ones (changing environment variables etc).

**Comment by martyn-t** [comment]
+1 useful feature to have

**Comment by TrevorAMarshall** [comment]
+1

**Comment by paullllll** [comment]
+1 
Please provide! This would help a lot of people!!!

**Comment by arvindsv** [comment]
@ketan, @zabil: After #1404 is done, it should be possible to use that to improve the wizard, right?

I'm thinking: If we make the pipeline config page itself very good and explanatory, we might even be able to get rid of the wizard. Two birds, one stone and all that.

**Comment by jh409** [comment]
+1

**Comment by christophebeling** [comment]
+1

**Comment by mahsoud** [comment]
+1
