### ISSUE TITLE
Debian 11 (Bullseye) agent docker image

### ISSUE THREAD

**Issue by netsandbox** [gocd/gocd#9873]
##### Issue Type

- Feature proposal

##### Summary

Provide a Debian 11 (Bullseye) agent docker image.

By the way you should also think about switching to the `-slim` variant of the Debian Docker images, 
which would result in smaller Debian agent images:
```
REPOSITORY             TAG            IMAGE ID       CREATED              SIZE
gocd-agent-debian-10   v21.3.0-slim   2e5a27a183bf   About a minute ago   474MB
gocd-agent-debian-10   v21.3.0        63d9e1d9ed59   4 minutes ago        543MB
```

**Comment by chadlwilson** [comment]
Noted, thanks for the reminder.

I suspect the (potential?) difficulty in switching to the slim images might be expectation of particular things being available by default in the non-slim images, of use in people's agents if they are using the GoCD images as a base image for something else they layer on top. Would need to look through what is "missing" in slim to see if that would be of concern.

It's not the same, given musl vs glibc, but If you want the smallest images with the lowest attack surface area, the Alpine images are probably the best bet.

**Comment by netsandbox** [comment]
Have a look at `.slimify-excludes` and `.slimify-includes`at https://github.com/debuerreotype/debuerreotype/tree/master/scripts for what is excluded from the slim images.
It doesn't look like something someone would expect in an agent image, but I understand your concern.
