### ISSUE TITLE
Path Manipulation

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [gocd/gocd#9888]
https://github.com/gocd/gocd/blob/86b555e57daccec6b53b246f0dcdd4d0090566ef/server/src/main/java/com/thoughtworks/go/addon/businesscontinuity/primary/controller/PrimaryStatusProviderController.java#L121-L125

We found 'pluginName' may be contaminated on line 212 of PrimaryStatusProviderController.java.Use of unfiltered data in selection of requested application file path could lead to sensitive data disclosure and potential theft of proprietary business logic.It will affect on line 124 of PrimaryStatusProviderController.java

**Comment by arvindsv** [comment]
Hello @QiAnXinCodeSafe. That's the right. That's one of the main reasons the whole of business continuity (which this code is in) is disabled. Here's a write-up related to this: https://blog.sonarsource.com/gocd-pre-auth-pipeline-takeover

**Comment by arvindsv** [comment]
Closing this since this code is un-called and unused currently, but I acknowledge that this issue exists. When we re-enable that feature, this has to be taken care of.
