### ISSUE TITLE
Create /var/lib/go-server/plugins/{bundled,external} as part of installation

### ISSUE THREAD

**Issue by patdowney** [gocd/gocd#989]
I'd like to be able to be able to test plugins by doing something like this:

```
$ docker run -v /path/to/task-assembly-1.0.0-SNAPSHOT.jar:/var/lib/go-server/plugins/external/task-assembly-1.0.0-SNAPSHOT.jar -p 8153:8153 gocd-dev:14.4.0_1
```

The above will fail because docker will create the parent directory of `/var/lib/go-server/plugins/external` because it will be owned by `root`

To work around it, I needed to hack `Dockerfile.gocd-dev` in `gocd/gocd-docker` to add

```
RUN mkdir -p /var/lib/go-server/plugins/external
RUN chown -R go:go /var/lib/go-server
```

I considered adding a PR to gocd/gocd-docker but I think the package is the more appropriate spot for it. Happy to be wrong!

**Comment by arvindsv** [comment]
I agree. I think it can be part of the installers. Maybe [this](https://github.com/gocd/gocd/blob/master/installers/shared/shared_post.sh#L178) is an appropriate place to start?

If you want to make that change and verify the installers work (maybe using [gocd-build-installer docker image](https://registry.hub.docker.com/u/gocd/gocd-build-installer/) with a new setup and an existing setup (upgrade scenario), I think the pull request would make sense.

**Comment by arvindsv** [comment]
Closing this. Docker images have been substantially improved - and the repo is now https://github.com/gocd/docker-gocd-server.
