### ISSUE TITLE
**Failed to run git clone command** error reported by GO-Agent. We are using BitBucket as repository.

### ISSUE THREAD

**Issue by harikrishna309** [gocd/gocd#9905]
**Failed to run git clone command** error reported by GO-Agent. We are using BitBucket as repository. 
Sometimes it's works and sometime it's returns the error **Failed to run git clone command** Please help. This is appearing very frequently.

_Originally posted by @sudhanshu5533 in https://github.com/gocd/gocd/issues/2571#issuecomment-541540330_

**Comment by chadlwilson** [comment]
Im afraid this isn't really sufficient information to understand what is going on. It's possible that your BitBucket server is under too much load and timing out.

How many git materials so you have against this BitBucket instance? Is this on-prem or Cloud?

If you establish a pattern correlated to load, you might want to consider not polling and using webhook triggers.
