### ISSUE TITLE
Go server restart is very slow

### ISSUE THREAD

**Issue by bamdadd** [gocd/gocd#991]
Hi,

Since we have upgraded to the latest version of the GoServer, server restarts are way longer than before.
It seems to be slower on the shut down step when it waits for the go process to terminate. 

Is there anything I can provide to help with this?

Thanks

**Comment by arvindsv** [comment]
Might be worth starting from [this thread](https://groups.google.com/d/msg/go-cd/BPQiOSNMT9I/E5cPH6Cb4xgJ) from the mailing list, to see if it is relevant. If not, you should probably check stack traces (using ```kill -3 PID```) to figure out what it is doing during startup.

If you have slow IO, it could manifest itself as a slow startup, as well.

**Comment by arvindsv** [comment]
Closing. No new information.
