### ISSUE TITLE
SSO Feature

### ISSUE THREAD

**Issue by djdta** [gocd/gocd#9925]
##### Issue Type

- Security issue? [**DO NOT** report it here. Please use [hackerone](https://hackerone.com/gocd) to report the issue.]
- Bug Report
- Feature proposal
- **Feature enhancement**
- Documentation Report
- Question? [**DO NOT** ask it here. Ask in the [mailing list](https://groups.google.com/forum/#!forum/go-cd)].

##### Summary

Currently, the tool does not support the ability to have SSO to Azure AD

##### Environment
Kubernetes Kind

###### Basic environment details

* Go Version: `Available in the footer`
* JAVA Version: `Available from http://<go-server-host>/go/about`
* OS: `Available from http://<go-server-host>/go/about`
* Browser vendor and version (if relevant): `Hopefully not Internet Explorer 7 :)`

##### Steps to Reproduce

1.  Go to the Admin tab
2. Go to Authorization Configurations
3.  See if you can added Azure AD for SSO
4.

**Comment by chadlwilson** [comment]
I'm not super familiar with what you can and cannot do with Azure AD and whether you can in fact do LDAP (as opposed to OAuth2, SAML etc), but I wonder have you looked at https://github.com/gocd/gocd-ldap-authorization-plugin?

Such things would be implemented via [plugins](https://www.gocd.org/plugins/#authorization) with GoCD.
